### ISSUE TITLE
Add collection name to the requests

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7472]
_Reported by Product Support_

**Is your feature request related to a problem? Please describe.**
Unable to differentiate requests with same name of two collections

**Steps to reproduce the behavior:**
1. Create two collections - C1 & C2
2. Create requests (R1 in C1 & R2 in C2) in each collection with the same name (Eg: DataInit)
3. Click on R1, then on click on R2.
4. The request (R1) gets replaced with R2 instead of opening it in a new tab, which leads to confusion while working with multiple tabs.

**Describe the solution you'd like**

1) Both requests to be open in different tabs and have information from which collections those requests came from, like the request and its collection name

2) Also a warning modal if a collection has requests with same name

![differentName](https://user-images.githubusercontent.com/47771757/66738266-a786b980-ee8b-11e9-8e3d-41dde72d6c30.png)

**Describe alternatives you've considered**
1) Each request only opens in New tab, if it is Edited/ Save/ Request sent
2) Right click on the request and "Open in New Tab".
3) Add a description for each request.

**Additional context**
Similar to the reported issue: https://github.com/postmanlabs/postman-app-support/issues/7399

**Comment by vivirusdi** [comment]
I prefer: 
1. Each request only opens in New tab, if it is Edited/ Save/ Request sent (Default)
2. On each request there is a description of the parent Collections for that Request. Workspace I think is optional since usually works only on a specific Workspace.

**Comment by DannyDainton** [comment]
The Collection/Folder/Sub-Folders are included in the breadcrumb of the Request, in the latest version.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/17089546/224311882-7f66b5a5-f471-41e4-a878-19ffb6c3fa6c.png">
