### ISSUE TITLE
API schema in source control

### ISSUE THREAD

**Issue by jehrlich** [a85/POSTMan-Chrome-Extension#7473]
**Use Case**

In API-first development, the API schema should be under source control. In my case, this is a github repo with a folder for each openAPI schema and a branch cut for each released version. Now I want to copy each released schema to Postman, or better yet point Postman to my repo directly. The schema may include multiple files, a root file named `openapi.yaml` and files for components such as data objects which may be referenced by full or relative urls. 

**Suggested Solution**
1. allow Postman APIs to reference a schema in an external location
2. provide a github integration to create a new Postman API version from the repo when a new release is cut.

**Comment by sankalp0o** [comment]
Thanks for the feedback @jehrlich!
We're working on providing integrations so that the schema can remain in sync with code repos. We're also considering multi-file schema support.

We recently released the support for adding and modifying schema using the Postman API, so you might be able to use this to keep your schemas in sync till we work on a proper integration. Take a look at the documentation - https://docs.api.getpostman.com/?version=latest#1d08c63e-6d79-4dc7-9e87-ee15de1d74a0

I'm curious to hear more about how you use the schema in Postman. It's still in beta and any feedback would enable us to design a better experience around the feature.

**Comment by jehrlich** [comment]
@sankalp0o asks how I hope to use the Postman schema.

I maintain a server which supports several apps maintained by developers I employ (not unlike Postman itself in many ways). How should I introduce a new feature? Like this:
1. add an issue to the github repo holding an openAPI specification of the API. When server and app developers agree on what endpoints will be needed for the new feature, cut a new API release with the necessary endpoint(s). This should include any new components such as data objects used by the endpoints. Shared data objects should be in separate files because they will be used by multiple APIs by reference. The server supports several different internal APIs used by specific apps and public APIs for integration with other services, each API in its own directory.
2. when a new API release is cut, it goes into Postman to add tests and generate docs - all the good stuff Postman is pioneering. Each API directory from the repo corresponds to a Postman API and each release branch to a Postman API version.
3. Server developers go to work to pass tests while app developers work from mocks.
4. If a problem is found with the API, either app or server developers can add an issue to the API repo, and iterate.

A logical next step would be for Postman to auto-generate tests from openAPI example data. If a valid `example` value exists for each input and output, create a corresponding test.

**Comment by sankalp0o** [comment]
Thanks for explaining it so well @jehrlich. This is goldmine for good feedback!

All of the things you mentioned (e.g. test generation) are already part of our roadmap and you should see them in Postman soon. If I could bother you, I had a couple more questions
1. You mentioned you use mocks. Do you use Postman Mock Servers? You should be able to generate one from the API specification (given examples etc). If you have, was there any gap in this flow that you experienced?
2. You also mentioned that each new release branch maps to a Postman API version. Do you ever refer to older versions in Postman? Do you write new test collections for each version or do you update the older ones? Is there any thing that you feel is missing while working with multiple versions?

We're hoping to solve how to keep schema in Postman to keep in sync with external git repos soon!

**Comment by jehrlich** [comment]
At this point I am learning Postman. I have been using openAPI for some time and IT tests on the server which will definitely benefit from being transferred to Postman. Currently no mocks. I wrote the previous app myself, and now faced with the communication problems of moving from a one-man-show to team development, so what I am writing here is really a plan for moving forward.

I plan to explore Postman mocks and versions today. Yesterday I was disappointed to learn that openAPI description fields don't seem to be transferred to Postman docs. I suppose you are working on that too. I am confused by the API --> collection generator choice (Documentation, or Contract Tests, or ..). Maybe that will become clear. 

A minor terminology issue is that Postman seems to use `schema` to refer to a root openAPI doc while openAPI `schemas` describe data objects.

**Comment by sankalp0o** [comment]
Currently the choices while generating a collection don't actually affect it, only helps in organising it within the API. But we are planning to use this information to generate more useful collections in future. I think an example would be to make sure things like OpenAPI description fields are correctly used if the generated collection is for documentation.

I'll pass on the feedback regarding schema terminology and descriptions not transferring to relevant teams, thanks!

**Comment by sankalp0o** [comment]
@jehrlich Schema Integration with GitHub is now available in the Postman app. Do give it a try and let us know how we can improve it.

**Comment by sankalp0o** [comment]
Looking back at your comments where you said 

> A logical next step would be for Postman to auto-generate tests from openAPI example data.

We recently released the ability to "validate" requests and collections against the OAS spec. While this is not exactly a test, this would inform you that your requests/responses etc do not match the prescribed values in the spec.

Do you think this is useful for you?

**Comment by jehrlich** [comment]
Thanks, Sankalp. I have been away from Postman for a bit and will take a look.

The issue for me is that what I think we are calling “contract tests” ideally should be specified in the same place as the API, which for me is an OAS3 document. It looks like Postman could be a solution, and I think SmartBear is also trying to develop something.

Ther are still some missing bits, so at present my contract tests are on the server, with some  cut-and-paste with the OAS3 spec, an ugly kludge that I hope can be deprecated.

Jim

> On Feb 4, 2020, at 11:53 AM, Sankalp Agarwal <notifications@github.com> wrote:
> 
> Looking back at your comments where you said
> 
> A logical next step would be for Postman to auto-generate tests from openAPI example data.
> 
> We recently released the ability to "validate" requests and collections against the OAS spec. While this is not exactly a test, this would inform you that your requests/responses etc do not match the prescribed values in the spec.
> 
> Do you think this is useful for you?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Jim Ehrlich, DVM
Dairy Veterinarians Group
Argyle, NY
jehrlich@dairyvets.com
http://dairyvets.com

**Comment by simundev** [comment]
Hi @sankalp0o !

I have a very similar use case in mind, so I hope I am not threadjacking.

I've tried to use the integration with Github, but I gave up. I was asked to create an Access Token, but was not told which privileges this token needs. I tried giving very few privileges, and it didn't work with a private repo. It was also not clear to me how the integration works, that is, which direction are changes flowing in. Are the changes I make in Postman propagated to the repo, or are commits to the repo reflected in Postman? Or both? I feel the user interface was not very intuitive, but I also must admit I didn't read any documentation. (I am not very experienced with Postman)

**Comment by vvs11** [comment]
Thanks for the feedback @simundev. We will keep working on improving the UI and making it more intuitive. We have documented the steps in detail here:
https://learning.postman.com/docs/integrations/github/#syncing-your-api-schemas-on-github
Please try it out and give us more feedback

**Comment by a85** [comment]
This feature is available now in Postman. Closing the issue. Please suggest improvements in other threads.
