### ISSUE TITLE
Fresh login doesn't show my collections right away

### ISSUE THREAD

**Issue by adritabhor** [a85/POSTMan-Chrome-Extension#7474]
**Description**
I was logged out of Postman App, when I logged back in as an enterprise user into the team, my collections list was empty. Then I clicked around and moved back to the collections tab on the left, my older collections got populated

**To Reproduce**
1. Go to login page for the Postman Client App
2. Login as an Enterprise User into the team.
3. Click on Collections tab, you see the screenshot attached, saying you don't have any collections. State of panic.
4. Collections load up after a few seconds.
5. Same is true for the 'History' tab.

**Expected behavior**
The message should say, "Your collections are loading... (with a spinner or similar)" if you are on collections tab and "Your history is loading... (with a spinner or similar)" instead of "you don't have any collections".

**Screenshots**
![Collection-Load](https://user-images.githubusercontent.com/54927169/66790177-9184f300-eea3-11e9-9757-90c57bf19927.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version v7.8.0
 - OS: macOS Mojave 10.14.6

**Comment by ankit-m** [comment]
This has been fixed in our web version - go.postman.co/build

**Comment by ankit-m** [comment]
We have launched Postman v8 (available for direct downloads as of now) which loads all workspace elements instantaneously.
