### ISSUE TITLE
Loss of data (Collections/Environments) after updating to the latest version 

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7475]
_Reported by Product Support_

**Describe the bug**
Once the Non-signed-in users update the application then the data doesn’t transfer over to the new app version and gets lost

**To Reproduce**
1. Launch the Postman native app without being signed-in
2. Create any collection/ environment and save it
3. Update the app version
4. The data that are present locally in the previous app version doesn't transfer over to the latest version of the application after the update

**Expected behavior**
All the data - environments/collections should remain intact in the application after the version is updated.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.2
 - OS: Windows 10

**Additional context**
With the latest version of Postman, the application creates a "backup.json" file within the "Postman" folder. Importing the .json file into the application should help users have all of the data back.

Similar to https://github.com/postmanlabs/postman-app-support/issues/6137

**Comment by kamalaknn** [comment]
@Raj-postman This report is from an old version of Postman. Are we seeing the same issue in the latest versions of Postman as well?

**Comment by Raj-postman** [comment]
Yes @kamalaknn, this occurs when the users update the application from 6.7 > 7.x. 
Reported this as part of tracking issues on this line, will check and link recently reported tickets.

**Comment by kamalaknn** [comment]
@Raj-postman Do we have the logs from any users who have reported these issues when upgrading from v6 to v7?

**Comment by Raj-postman** [comment]
@kamalaknn Have added logs from one of the similar cases

**Comment by kamalaknn** [comment]
The errors in the logs are unrelated to the issue reported here. Closing this issue since we do not have enough information to confirm correlation between v6 to v7 migration to data loss. Other data related issues are tracked separately.
