### ISSUE TITLE
Data Loss - data removed after first sign-in (when using the app w/o account)

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7478]
_Filed by Product Support_

**Describe the bug**
Data does not transfer over after the very first sign-in of a non-signed-in user. 

**To Reproduce**

1 - Using Postman w/o being signed-in - `Skip signing in and take me straight to the app` - on a version 6.7.4
2 - Have a bunch of locally populated data.
3 - Sign in to an old account (in this scenario an account already exists so **the data loss occurred during the sign-in flow**) and update.
4 - The data (here collection and environments) that are populated locally don’t transfer over to the new account. 

**Expected behavior**
After the sign-in flow, the app should sync the local data.

**App information (please complete the following information):**
 - version: 6.7.4 > 7.9.0

**Additional context**
Ways to recover the data
- Recover Local Data with Postman Canary - https://support.getpostman.com/hc/en-us/articles/360035071313-How-to-recover-my-data-
- Import the backup.json file within the Local data Postman folder

**Comment by preethammavin** [comment]
@cyrielle-hada in this case did you update then sign-in or sign-in and then update?

**Comment by kamalaknn** [comment]
@cyrielle-hada Can you give us more details on this issue as the steps that lead to this? Is it possible to share logs for cases where this has happened?
