### ISSUE TITLE
Disable Automatic Updates

### ISSUE THREAD

**Issue by TasMot** [a85/POSTMan-Chrome-Extension#7482]
**Describe the bug**
Due to security concerns, all development is done in an offline environment. There is no connection to the wider Internet and there will never be one. So while I am in Postman there is a red dot on the wrench telling me that the updates failed. 

**To Reproduce**
1. Install Postman on an offline machine
2. Wait about 2 to 5 minutes
3. At the top right hand wrench, the red dot will appear to get my attention about something
4. Go check to see if it is just the update message or an additional message

**Expected behavior**
I understand the concern to keep up to date on minor updates and security patches, but it will never be available in this environment.

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Our development environment will never allow a connection to the Internet, so the updates can't ever be retrieved by that method. I would need to know they are available, download them, copy to some media, transport to the development machine, then install them. 

Thanks, Tom

**Comment by preethammavin** [comment]
I understand the concern @TasMot but taking into account that large section of users depend on Postman to dependable and have security expectation disabling minor updates are not something we provide, saying that we do give an option to turn off major version updates.
