### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8080

### ISSUE THREAD

**Issue by lehoa2411999** [a85/POSTMan-Chrome-Extension#7483]
**Describe the bug**
Could not get any response
Error: connect ECONNREFUSED 127.0.0.1:8080

**To Reproduce**
1. I created request post with url is http://localhost:8080/api/users
2. In header, 
Request Headers:
Content-Type:"application/javascript"
Accept:"application/json"

3.  In body,
firstName:"Hoa"
lastName:"Le"
email:"lehoa08121998@gmail.com"
password:"lehoa123"
profilePictureUrl:"hoadeptrai.jpg"
platform:"windown"
appVersion:"10"

4. Error: connect ECONNREFUSED 127.0.0.1:8080

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46698432/66856773-1eb56e00-efb0-11e9-85f5-62add5cc1721.png)
![image](https://user-images.githubusercontent.com/46698432/66856788-25dc7c00-efb0-11e9-8dec-075f4d86b8b6.png)

**App information (please complete the following information):**
 - App Type [Windown App]
 - Postman Version [e.g. 7.9.0]
 - Window 10

**Additional context**
I tried turn off  turning off 'SSL certificate verification' in Settings > General"
and turn off
Global Proxy Configuration
Use System Proxy
besides, i also create file batch like that

set HTTP_PROXY=
set http_proxy=
set HTTPS_PROXY=
set https_proxy=
START %LOCALAPPDATA%\Postman\Update.exe --processStart "Postman.exe"

eventually, it didn't work! can anyone help me please!

**Comment by preethammavin** [comment]
@lehoa2411999 would redirect you post the question on https://community.getpostman.com, our community is very active and would definitely be there to help you out.
