### ISSUE TITLE
APIs Beta: Mock server endpoint /things/:id will instead go to /things

### ISSUE THREAD

**Issue by johanlunds** [a85/POSTMan-Chrome-Extension#7484]
**Describe the bug**

Using APIs Beta and creating a Mock server with 2 endpoints (using a Swagger/OpenAPI 2.0 spec in "Define" tab) like `/things/:id` and `/things`, when sending a request to `https://25f-....-547a.mock.pstmn.io/things/32` you will get response for `/things` back instead.

**To Reproduce**
1. Use APIs Beta
2. Create API using Swagger 2.0 spec and 2 endpoints `/things/:id` and `/things`
3. Create mock server
4. Send request to `/things/32`

**Expected behavior**
Response for `/things/:id` is returned.

**Actual behavior**
Response for `/things` is returned.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.9.0
 - OS: macOS

**Additional context**
If you need more info, please ask.

**Comment by vvs11** [comment]
Hi @johanlunds, Thanks for reaching out!
Could you tell us more about how you created the mock server and elaborate a little more on the two requests that you have along with the responses in the schema?
If you have generated collection from the schema, could you check the examples that are created fro the request you're sending?
Assigning the issue to you while we wait for the response :)

**Comment by vvs11** [comment]
@johanlunds closing this for now. Please feel free to open this
