### ISSUE TITLE
Typo ("Path Varaibles" -> "Path Variables") in "Find" menu filter dropdown list

### ISSUE THREAD

**Issue by david-creigh-msi** [a85/POSTMan-Chrome-Extension#7485]
**Describe the bug**

There is a typo in one of the entries in the "FILTER (ALL FIELDS)" dropdown list.

```
Path Varaibles
        ^^ [these letters should be the other way around]
```

**To Reproduce**
1. Open "Find" menu (crtl + shift + F)
2. In the text entry field with the prompt "Enter text to find...", type anything at all (the search terms are completely irrelevant)
3. Click "Find" button
4. In either the "Open tabs" or "Collections" tabs on the right hand side, click the "FILTER (ALL FIELDS)" dropdown list.
5. Scroll down to the "Examples" sub-list, 

**Expected behavior**
The typo looks like it should be corrected to either of:
- `Path Variables` 
   - (just correcting the actual typo)
- `Path variables`
   - (the rest of the entries on the list are in this format (i.e. First word capitalised, no other words capitalised).)

**Screenshots**
![image](https://user-images.githubusercontent.com/50200567/66858011-61f7e880-ef80-11e9-9d0f-7af51d8f304a.png)

 ![image](https://user-images.githubusercontent.com/50200567/66858053-75a34f00-ef80-11e9-8c61-dc8f4c10537b.png)

**App information (please complete the following information):**
 - App Type: Postman for Windows
 - Postman Version 7.9.0
    - win32 10.0.17763 / x64
 - OS: Windows 10

**Additional context**
N/A.

**Comment by kamalaknn** [comment]
This should be fixed in Postman 7.12 😄
