### ISSUE TITLE
不能正确删除字码

### ISSUE THREAD

**Issue by ubuntu2204** [a85/POSTMan-Chrome-Extension#7487]
**Describe the bug**
body->raw->json
已经打的很多字，删除的时候，删掉的不是想要删掉的字

**Screenshots**
![image](https://user-images.githubusercontent.com/44113641/66891408-abe1dc80-f01b-11e9-8010-fab2131d86de.png)

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [v7.9.0]
 - OS: [ubuntu1804lts]

**Comment by kamalaknn** [comment]
Hey @godot0413301 

I am having a little trouble understanding this issue. Translating with Google shows

> "Many words that have been played, when deleted, the words that are deleted are not the words that you want to delete."

Are you saying that you are seeing issues with the Text editor where the text you are seeing is differing from the saved version? 

If you can clarify the actual issue and give more information on how to reproduce it, we can help you better.

**Comment by ubuntu2204** [comment]
the bug is that：my os is ubuntu 1804lts，I edit the char （include delete char），but in fact，I edited other char。just like the picture up there 。in os windows10，the same operation is no bug。

**Comment by ubuntu2204** [comment]
the text I edit，is not the text I edited。only in os ubuntu1804lts

**Comment by kamalaknn** [comment]
@godot0413301 This looks like a duplicate of #2985 where the cursor position that is shown on the editor is different from where the characters are inserted or deleted. Can you confirm?

**Comment by ubuntu2204** [comment]
this bug a little like #2985.but different is My windows10 pro does the same thing，there is no bug.the bug is only on my ubuntu1804lts

**Comment by kevin-postman** [comment]
@godot0413301 You see the same issue in Windows 10... earlier you mentioned on Windows 10 it was not a bug? Can you provide the text in the screenshot above pasted here so I can try to copy/paste the same to reproduce the issue?

**Comment by numaanashraf** [comment]
Duplicate of #2985
