### ISSUE TITLE
PUT requests are not getting executed correctly through Postman

### ISSUE THREAD

**Issue by ramya303** [a85/POSTMan-Chrome-Extension#7488]
I am trying to execute a PUT request through Postman, but I get the error as '405Method Not Allowed'.
On looking at the response, I see that the method name 'PUT' is passed incorrectly as 'UT'

Refer the below image.

![image](https://user-images.githubusercontent.com/19899372/66891591-35d37a80-f007-11e9-9148-85ca5c6f2250.png)

**Comment by coditva** [comment]
Hey @ramya303,
I haven't been able to reproduce this on my end. Here are some things that can be done as first steps to debug this:
- Can you tell me what is the response when you send a put request to `https://postman-echo.com/put`?
- Can you also try and send a request to the localhost endpoint via curl and see if it's a problem with the endpoint itself? You can use the [Code generation feature of Postman](https://learning.getpostman.com/docs/postman/sending_api_requests/generate_code_snippets) for this!

**Comment by danielmustafa** [comment]
I'm also seeing this issue when trying to hit an Azure File Service endpoint:

`<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>InvalidHttpVerb</Code>
    <Message>The HTTP verb specified is invalid - it is not recognized by the server.
RequestId:9f37517a-401a-006b-7f45-e7b49e000000
Time:2020-02-19T16:55:10.7215786Z</Message>
    <Verb>UT</Verb>
</Error>`

When I called the postman-echo.com endpoint I'm getting the following on a 200:

```
{
    "args": {},
    "data": {},
    "files": {},
    "form": {},
    "headers": {
        "x-forwarded-proto": "https",
        "host": "postman-echo.com",
        "content-length": "0",
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "cache-control": "no-cache",
        "postman-token": "b33a3d3c-321d-4f38-8ed5-7c2499da76e4",
        "user-agent": "PostmanRuntime/7.22.0",
        "x-forwarded-port": "443"
    },
    "json": null,
    "url": "https://postman-echo.com/put"
}
```

When I tried using the code generation for curl I got a different error (400), related to my request

Edit:
Just to note, I'm using Version 7.16.1 (7.16.1) on Mac OS Catalina

**Comment by mccannt** [comment]
@wheezymustafa Can you try this again on the latest version of our app? 
I just tried doing the steps you outlined above and its working fine for me. Both within the app and also with the cURL that's generated.

Please let us know.

**Comment by mccannt** [comment]
Closing this out for now. 
Please let us know if this is still an issue with the latest version of the application.

**Comment by ahmedkhan847** [comment]
I am having same issue with latest version I am unable to hit a PUR request when I hit https://postman-echo.com/put I am getting following response I am on latest version of it.

```
{
    "args": {},
    "data": {},
    "files": {},
    "form": {},
    "headers": {
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "host": "postman-echo.com",
        "x-amzn-trace-id": "Root=1-5faf8358-5f549b9d7c8feb6a52183be1",
        "content-length": "0",
        "user-agent": "PostmanRuntime/7.26.5",
        "accept": "*/*",
        "cache-control": "no-cache",
        "postman-token": "2706de31-e844-413f-b16c-bc7134a3deed",
        "accept-encoding": "gzip, deflate, br"
    },
    "json": null,
    "url": "https://postman-echo.com/put"
}
```

**Comment by mccannt** [comment]
@ahmedkhan847 Can you give us more context here? It's not clear what the issue is here.

**Comment by ahmedkhan847** [comment]
@mccannt  I have PUT api which I am trying to hit via Postman instead of calling PUT it always calls GET request
