### ISSUE TITLE
Background suspicious activity

### ISSUE THREAD

**Issue by VijitCoder** [a85/POSTMan-Chrome-Extension#7489]
**Describe the bug**
Updates are turned off:

![2019-10-16_20-29](https://user-images.githubusercontent.com/8523131/66924527-f9c70680-f054-11e9-92e9-c6c9961dad98.png)

But when I stating the program, in the background it download something and messing up in the directory, that not belongs to this program. 

It doing something more cause after closing the program a strange window remains with a zero width and titled "Shared".

Eventually it can be so that on the next  start the program just hangs with an eternal spinning in the splash window. The only way is to delete `~/.config/Postman` folder.

**To Reproduce**
1. Start the program and wait a couple minutes.
2. Go to the directory, where is the program's folder placed. Check new unexpected files like these 

![2019-10-16_20-25](https://user-images.githubusercontent.com/8523131/66924524-f92e7000-f054-11e9-8663-95d7e6adff31.png)

**Expected behavior**
No background downloads, switching versions and other not approved actions.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.8
 - OS: Linux Mint 19.1

**Comment by harryi3t** [comment]
@VijitCoder That is expected behaviour. You have disabled downloading the __major updates__.
Postman always downloads the minor updates and bug fixes automatically.

![Postman](https://user-images.githubusercontent.com/5207331/67082965-dc5e7d80-f1b7-11e9-8b84-8376a6e73355.png)

That being said, I think we can certainly improve on communicating this in a better way to our users.
- cc @vkaegis

**Comment by VijitCoder** [comment]
Changing from 7.8.0 to 7.9.0 is a _minor_ update? Not bad, yeah..

**Comment by VijitCoder** [comment]
But what about 

> It doing something more cause after closing the program a strange window remains with a zero width and titled "Shared".

What is that?

**Comment by VijitCoder** [comment]
I understood about the "minor" sense. It is about the version indeed: _major.minor.build_.

**Comment by kamalaknn** [comment]
> It doing something more cause after closing the program a strange window remains with a zero width and titled "Shared".

The "Shared" window is a background browser process that uses browser stack to perform actions. This allows us to perform network and compute intensive programs(like syncing and versioning offline data) in the background without sacrificing the responsiveness of the Postman UI windows.
