### ISSUE TITLE
Memory and CPU consumption on sending big files after request has finished

### ISSUE THREAD

**Issue by bo44arov** [a85/POSTMan-Chrome-Extension#7492]
**Describe the bug**
On a server side I needed to read just a few first lines of a large file from request stream and then return 200 (without uploading the whole file)
But once recieve 200 responce Postman still consumes CPU and memory as if posting a stream goes on.

**To Reproduce**
1. Create sample api method within any language that reads few lines (bytes) from input http stream and then closes stream and returns OK
2. In Postman create POST request with binary body and select a file 1Gb+ size
3. Send this request to a sample api method
4. Observe CPU, memory and disk consumption in task manager after succeful response (200) from server

**Expected behavior**
CPU, memory and disk consumption goes down right after recieving response from server

**App information (please complete the following information):**
 - App Type: .Net Core 2.2 Api
 - Postman Version 7.9.0
 - OS: Windows 10 Educational

**Comment by advapiIT** [comment]
Got a similar problem when sending 256MB via JSON. Postman IDE closed (I have not checked immediatly if the process was still on. Found after 12 hour 10GB of process in RAM!!!)

**Comment by bo44arov** [comment]
Figured out the issue - Postman sends Connection: Keep-alive by default.
By manually setting header Connection: Close solved the initial issue
