### ISSUE TITLE
Postman Interceptor does not connect to native app on mac os

### ISSUE THREAD

**Issue by sorakiu** [a85/POSTMan-Chrome-Extension#7495]
**Describe the bug**
I followed the instructions listed here: https://learning.getpostman.com/docs/postman/sending_api_requests/interceptor_extension/#installing-the-interceptor-bridge/

**To Reproduce**
1. install native postman app
2. install interceptor bridge
3. install interceptor extension in chrome
4. turn on capture requests in chrome
5. enable interceptor in native postman app
6. the interceptor icon remains greyed out.

**Expected behavior**
Interceptor connected in native postman app

**Screenshots**
![image](https://user-images.githubusercontent.com/291045/67035235-465b2200-f0e7-11e9-908f-63a2fce77162.png)

**App information (please complete the following information):**
- native app
 - Postman Version 7.9.0 (7.9.0)
 - OS: macOS Catalina - 10.15
- Chrome: Version 77.0.3865.120 (Official Build) (64-bit)
- interceptor extension: 0.2.28

**Additional context**

I tried installing it both as myself and as root. I also tried it by right-clicking on the script (after making it executable) and selecting open.

There were never any errors and the file is appearing in the destination, but it doesn't work.

**Comment by sorakiu** [comment]
So if you run `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome` from the command-line, it will output errors to the terminal window. It repeatedly lists `[68962:72963:1017/141837.385548:ERROR:native_process_launcher_posix.cc(89)] Error launching process`

On a whim, I also changed nativeserver-MacOS to executable:
```
chmod +x nativeserver-MacOS
```

Then I started getting security errors, so I right clicked on it in finder and did open so I could clear the security error.

Postman now shows it as connected.

You may want to update the instructions for MacOS

**Comment by abhijitkane** [comment]
@sorakiu Yep - this is specific to OSX Catalina. We're working on an improved installation experience.

**Comment by LeLunZ** [comment]
> @sorakiu Yep - this is specific to OSX Catalina. We're working on an improved installation experience.

I am still having the same problem.
Is there a fix? 
Running:  `
chmod +x nativeserver-MacOS `   doesn't help

Postman won't connect to the interceptor Bridge.

**Comment by xneg** [comment]
Any luck with this issue? I have a problem too. OSX Catalina. Before OS update it worked for me.

**Comment by sorakiu** [comment]
@xneg @LeLunZ - did you run it manually? until I ran it - catalina's security protections wouldn't let it start.

**Comment by xneg** [comment]
@sorakiu what is **it**? Sorry, I didn't understand your workaround. I used this instruction https://community.getpostman.com/t/interceptor-integration-for-postman-native-apps/5290
When I run chrome from terminal I don't see your errors. So I thought that your workaround is not for me. What is `nativeserver-MacOS` and where I can find it?

**Comment by LeLunZ** [comment]
> @sorakiu what is **it**? Sorry, I didn't understand your workaround. I used this instruction https://community.getpostman.com/t/interceptor-integration-for-postman-native-apps/5290
> When I run chrome from terminal I don't see your errors. So I thought that your workaround is not for me. What is `nativeserver-MacOS` and where I can find it?

nativeserver-MacOS is in the postman Interceptor Bridge Folder.



> @xneg @LeLunZ - did you run it manually? until I ran it - catalina's security protections wouldn't let it start.

I ran it via Terminal and Finder and in the Terminal there was no error. And security protection wasn’t there.

**Comment by xneg** [comment]
@LeLunZ As I see there is only manifest file `com.postman.postmanapp.json` that is copied via script. What should we make executable?

**Comment by GroomedGorilla** [comment]
@sorakiu 's fix worked for me on Mac OS Catalina.  To summarise:

1. I added `chmod +x nativeserver-MacOS` to the `install_hosts` file (I put it right above the final `echo` line)
2. Run the script again (`bash install_hosts`)
3. You will likely get security warnings from the OS saying the script if from an untrusted developer. Open System Preferences > Security & Privacy. In the General tab you should see a message saying something along the lines of "nativeserver-MacOS is requesting access". Click the padlock, enter your password and click `Allow` next to the nativeserver-MacOS message

If any further security prompts pop up you should now be able to click "Allow". Also try relaunching Chrome if this persists.

This worked for me and Interceptor shows as connected. Hope it helps

**Comment by deeTEEcee** [comment]
fyi, another issue i hit with the interceptor script was that its assuming that it's moving from file to file but the old `~/.postman/<interceptor>` location seems to have been a directory instead. also, at this point the docs dont provide me a link to the bridge installation.
