### ISSUE TITLE
Unable to log in or post to forum

### ISSUE THREAD

**Issue by jehrlich** [a85/POSTMan-Chrome-Extension#7496]
**Describe the bug**
Unable to log in or post to forum

**To Reproduce**
1. Go to https://www.getpostman.com/community
2. Click on Login button 
3. redirected to https://identity.getpostman.com/accounts, click on my postman account 
4. redirected to https://vcpr-org.postman.co/workspaces?type=personal 

**Expected behavior**
at step 4 should be redirected to the discourse forum as a logged-in user

**App information (please complete the following information):**
mac/Firefox

**Additional context**
I have implemented Discourse SSO myself. Looks like you didn't get the response payload right (which is more difficult than it needs to be because Discourse does not publish their SSO API except as a text narrative.)

**Comment by jehrlich** [comment]
The failure was because I had not confirmed my email address. There was a warning at the top of the web UI (step 3 above), but I ignored it because I was using the app which seemed to behave correctly. 

`Welcome to Postman! We've sent you an email with a link to verify your email address. Didn't get the mail? Resend it`

This makes it my error, I suppose, but a better warning would have helped. It's not clear why I should bother to verify email. I am now logged in correctly to the forum.

**Comment by ArjunSingh-PM** [comment]
We have added an error page to urge the user to verify their email address to access https://www.getpostman.com/community
