### ISSUE TITLE
Pressing escape when there are unsaved changes in a modal dialog closes without confirmation

### ISSUE THREAD

**Issue by kamalaknn** [a85/POSTMan-Chrome-Extension#7497]
**Describe the bug**
When there are unsaved changes in a modal dialog, pressing escape closes it and leads to complete loss of the user input

**To Reproduce**
1. Click "Edit" on a collection
2. Enter "Description" or "Tests" or "Pre-request Scripts"
3. Press escape
4. Click "Edit" on the same collection, notice all data is lost.

**Expected behavior**
Pressing escape when there are unsaved changes should warn before closing

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] - N/A
 - Postman Version [e.g. 6.0.1] - N/A
 - OS: [e.g. macOS High Sierra 10.13.2] - N/A

**Comment by sankalp0o** [comment]
This issue has been fixed in the latest Postman app.

**Comment by kamalaknn** [comment]
This is fixed in this one particular case. There are two other modals that are still affected by issue and are being fixed. We can close this once they are fixed. 

cc @insomniac12 @sujayvenaik

**Comment by kamalaknn** [comment]
Most of the flows have been fixed now. Closing this issue.
