### ISSUE TITLE
[Question] Is it possible to have private environment for shared Workspace?

### ISSUE THREAD

**Issue by Ghedeon** [a85/POSTMan-Chrome-Extension#7498]
Correct me if I'm wrong, but at the moment, the shared workspace environment is also shared. Is there any way to have an additional private environment for my shared workspace?

**Comment by sankalp0o** [comment]
Hey @Ghedeon , it is not currently possible to have private environments in shared team workspaces. Can you help me understand the use case better? What are you looking to do?

**Comment by Ghedeon** [comment]
Let's say a team of devs is making requests to staging server from Postman. Usually, there is a shared pool of test accounts on staging. That's ok, but as a developer, I'd want to have my personal set of testing accounts and credentials in Postman's environment, so we don't make conflicting requests. I don't mind sharing this data with others but I don't see a point of doing that. Having a private set of environment variables will help us to keep the shared workspace cleaner.

**Comment by sankalp0o** [comment]
Thanks for helping me understand @Ghedeon. For organising things better in team context, we recommend using workspaces. You can either
1. Create a new workspace with the shared collections and private environments. This will avoid polluting the team workspace with things that only you use. Your collections and requests will still keep in sync.
2. Utilise current value (unsynced) in the same environment that the rest of your team uses. This will save you the trouble of maintaining duplicate environments while not save your private values with the team.

Happy to hear thoughts about why the above might not work for you.

**Comment by Ghedeon** [comment]
@sankalp0o `Create a new workspace with the shared collections and private environments.` I'd love to but how? Right now I have my Private workspace and Team Workspace. And they don't intersect at all. I can't create a private environment and use it in my Team Workspace. And similarly, whenever I create an environment in my Team Workspace, it's being synced with the team.

**Comment by sankalp0o** [comment]
@Ghedeon You could do this
1. Create a new Personal Workspace
2. Share all the collections from the Team Workspaces into this one
3. Create new environments into this Workspace that you need

This will ensure that your environments aren't shared. Let me know if this doesn't work!

**Comment by Akkarine** [comment]
It would be a nice feature for private API keys. Copying collections is an unconvinient workaround.
