### ISSUE TITLE
Block sign out in versions < 7.xx to prevent data loss

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7499]
_Filed by Product Support_

**Is your feature request related to a problem? Please describe.**

Users who are using the app with sync disabled only have their data stored locally.

The warning that is triggered on the signout process was implemented for version 7.xx - it warns that the local storage gets wiped out once we sign out from the app. 

<img width="473" alt="Screen Shot 2019-10-18 at 11 50 48" src="https://user-images.githubusercontent.com/47351631/67088692-b62be400-f19d-11e9-94a7-5a36f018e20d.png">

However, users who are using the app **in a lower version** won't see the warning and thus are not told their local data are stored locally and they might want to create a backup before signing out.

**Describe the solution you'd like**
Block the sign-out until the migration to version 7 is complete and add a message saying:
_We are migrating your data. We will sign you out after the data is complete_

**Comment by kamalaknn** [comment]
@cyrielle-hada This dialog with the warning message is shown before sign out for version 6 of Postman. What exactly is the version where you are not seeing this warning message?

**Comment by cyrielle-hada** [comment]
@kamalaknn the user was on version 6.7.2

**Comment by kamalaknn** [comment]
@cyrielle-hada This warning dialog is present in 6.7.2 version as well. I'm closing this issue for now. Please update if there is any additional information that will help us reproduce this issues.
