### ISSUE TITLE
The passed count in the collection is not correct. 

### ISSUE THREAD

**Issue by vijayphani** [a85/POSTMan-Chrome-Extension#7503]
The count after running a collection is wrong. 

Create a collection and run the collection.  The count of passed tests is 0. Although all of them passed.

**Comment by shamasis** [comment]
@vijayphani ... while we try reproducing this at our end, can you help by providing a sample collection that reproduces this issue? Also which version of app and platform are you on?

**Comment by DannyDainton** [comment]
Hey @vijayphani 

I'm going to close out this issue due to inactivity/lack of details to allow us to debug this locally. We can look to open this back up if the problem still persists.
