### ISSUE TITLE
Open postman passing the information to be executed

### ISSUE THREAD

**Issue by Angelk90** [a85/POSTMan-Chrome-Extension#7504]
**Is your feature request related to a problem? Please describe.**
I'm writing the documentation for the bees, I'm using this https://redocly.github.io/redoc/#tag/pet, as you can see there is a part on the right where it shows you the type of call Get, Post, address, payload, etc.

I would do this via a button if you click to send all this information to postman to be able to set up the call and then be executed by the user if he wishes.

**Describe the solution you'd like**
So what I wish was that it could be possible to send information from an external program to postman in order to set the call to be able to be executed.

In my case the communication will have to take place between the browser that sends the information to postman.

What I want to do is this:

- The user accesses the site
- This queries the server
- Taking information via http, a kind of json or other
- To then pass it to Postman if user has installed, in order to configure the call to be executed.

json:

```
{
type: "GET",
url: "https://...",
headers: {},
body:{},
...
}
```

**Comment by Angelk90** [comment]
Hi @shamasis : Is there anything new if this functionality could be integrated?

**Comment by postman-kenji** [comment]
Closing given the age of the request. @Angelk90 please feel free to reopen if this is still an issue and you'd like to promote the request. Thanks!
