### ISSUE TITLE
Better way to add billing/admin ("support") users

### ISSUE THREAD

**Issue by lasergoat** [a85/POSTMan-Chrome-Extension#7507]
**Is your feature request related to a problem? Please describe.**
Yes.

1. the team management page talks about how you can add a `support` role. BUT it doesn't actually say that a `support` role is "a user with a `billing` role and no other role" - I had to figure it out on my own, also not clearly in the docs.

    a. the docs [here](https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/managing_your_team/) do say it, but still could be more clear, and it could be mentioned on the team management page itself:

> "Each team can have up to 2 support accounts (only have admin or billing rights, and are not paid for)."

2. it's not possible to just add a `support` role directly either. you have to invite someone, wait for them to use the invite, then change their role. AND if your team is already full, you have to add a slot or kick someone else out first before you can invite them. And the really annoying part is you cannot change their role until they use the invite.

3. If your team is full and you try to invite someone via email, the invite never sends AND you don't see an error or toast or anything. You are forced to wonder what is going on until you remember that you have to add a slot and then go re-invite the user.

**Describe the solution you'd like**
1. The team management page should clearly state what a support role is.
2. The invite page should allow you to choose a role ahead of time 
3. You should be able to invite a support use even if your developer team is full
4. If your team is full, the invite page should either tell you to go add a slot OR it should just do it for you and ask if it's ok.

**Describe alternatives you've considered**
n/a

**Additional context**
I opened a ticket called:

> [Postman] Re: feature request - make it easier to add support roles

and he told me to post here. I don't care if you solve this issue but I want you to know that it's likely causing confusion for other users.

**Comment by abhijitkane** [comment]
@lasergoat We've updated this flow - on https://go.postman.co/team/invite, you can choose roles before you invite users, and this allows you to invite users with support-only roles too.

This should solve #2 and #3 in your list - we have the other two entries on our list.
