### ISSUE TITLE
Monitor for Team Not using Env Variables

### ISSUE THREAD

**Issue by technovasation** [a85/POSTMan-Chrome-Extension#7509]
**Describe the bug**
Able to run a monitor successfully in personal workspace but when the same monitor is created from the same environment and collection in the team workspace it fails to use the environment variables. 

**To Reproduce**
1. Click on "Monitor a collection"
2. Fill out the required parameters: 
 a. **Monitor Name**: "Test Monitor"
 b. **Collection**: "Specific Collection" (already tested locally on postman desktop app 7.9.0)
 c. **Version**: CURRENT
 d. **Environment**: Specific Environment for the test selected
 e. **Schedule**: Minute Timer / Every 30 Minutes
 f. **Regions**: Select Manually / Asia Pacific
 g. **Additional Preferences**: [x] Don't follow redirects
3. Click Add Monitor
4. Run monitor

**Expected behavior**
The expectation is that the same monitor created for the same collection in a personal workspace will have the same outcome as the monitor created in a team workspace.

**Screenshots**
Successful test in personal workspace: 
![successtest](https://user-images.githubusercontent.com/16444339/67255082-066fb280-f4cc-11e9-9464-30b8774df5d1.png)

Failed test in team workspace:
![failedtest](https://user-images.githubusercontent.com/16444339/67255078-fe177780-f4cb-11e9-8f8f-c28959baecd5.png)

**App information (please complete the following information):**
 - App Type: Native app 
 - Postman Version 7.9.0
 - OS: Windows 10 & Ubuntu 19.04

**Comment by godfrzero** [comment]
@technovasation Regarding the monitor that's failing, was it run on a schedule or using the API/webhook?

**Comment by moose1882** [comment]
on a schedule fails but even running it manually has same result

**Comment by moose1882** [comment]
has there been any progress on this issue?

**Comment by shivam-postman** [comment]
Hi @moose1882, are you still facing the issue?

**Comment by godfrzero** [comment]
Closing this for now, will reopen if additional reports/information comes in.
