### ISSUE TITLE
manjaro kde桌面环境使用postman7.9版本，无法同步collections

### ISSUE THREAD

**Issue by debugbb** [a85/POSTMan-Chrome-Extension#7510]
manjaro kde桌面环境使用postman7.9版本，无法同步collections。
尝试了重新安装，重新登录，都不能同步。
同步按钮会转很长时间，最后同步按钮变灰，不能再次点击同步。
![2019-10-22_10-19](https://user-images.githubusercontent.com/6327466/67255602-7c1c5400-f4b5-11e9-832d-da9a25ca739b.png)

**Comment by numaanashraf** [comment]
Translation:

Title: Manjaro kde desktop environment uses postman7.9 version, unable to synchronize collections
Body: The manjaro kde desktop environment uses the postman 7.9 version and cannot synchronize collections.
I tried to reinstall, log in again, and I can't sync.
The sync button will turn for a long time, and finally the sync button will be grayed out and you cannot click sync again.

**Comment by debugbb** [comment]
可能是网络问题，第二天发现同步下来了。
Translation:
It may be a network problem, and the next day it was found to be in sync.
