### ISSUE TITLE
Use collections for simple load testing

### ISSUE THREAD

**Issue by digitalthjarta** [a85/POSTMan-Chrome-Extension#7511]
I'd love to the that Postman could have a basic form of load testing. Basically what running all requests in a collection is today, but be able to set it to repeat X time over a period of Y minutes. As for reporting I'd like to the when it breaks and how response times is affected. 

I know there are plenty of tools that does this, but it's hard to find a tool that is as easy to use as Postman and since many of us already use Postman for API testing it would be awesome just to use it for basic load testing to. "Hammer Time by Postman"

**Comment by preethammavin** [comment]
@digitalthjarta hey, this is not on our roadmap as of yet, but I am taking this as a feature request for Load Testing. We would look at how we can enable the use-case in the future

**Comment by malvikach** [comment]
Closing this, as this is being tracked here: [Github issue# 493](https://github.com/postmanlabs/postman-app-support/issues/493)

Please feel free to provide further feedback to us on the linked issue. I will keep the issue updated with news on this.
