### ISSUE TITLE
Publish document still exist even thought the collection has been deleted.

### ISSUE THREAD

**Issue by myazid** [a85/POSTMan-Chrome-Extension#7513]
**Describe the bug**
Publish document still exists even when Collection has been deleted.

**To Reproduce**
1. From Team Workspace, publish document
2. Delete collection from Team Workspace
3. Publish document still viewable.

**Expected behavior**
Published document should not be viewable.

**Screenshots**
No screenshot. 

**App information (please complete the following information):**
 - Chrome App
 - Postman Version 7.9.0
 - OS: [macOS Mojave 10.14.6]

**Additional context**
Need help to unpublish content.

**Comment by godfrzero** [comment]
@myazid I just wanted to clarify one thing: Are you deleting the collection, or removing it from the workspace? Technically, if a collection has been deleted, it _can't_ fetched and displayed as a published documentation.

**Comment by myazid** [comment]
> @myazid I just wanted to clarify one thing: Are you deleting the collection, or removing it from the workspace? Technically, if a collection has been deleted, it _can't_ fetched and displayed as a published documentation.

I deleted the collection.

**Comment by godfrzero** [comment]
Alright, since this is a published documentation, it should be okay to post the URL here. If you'd like to avoid that, please send us the URL via help@getpostman.com

**Comment by myazid** [comment]
Will email you.

**Comment by ranchanarajasekaran** [comment]
The collection was removed and not deleted . Closing this thread as it is not an issue .
