### ISSUE TITLE
pm.environment.get("variable_name") in tests not picking the value from the test data csv file

### ISSUE THREAD

**Issue by hari2anand** [a85/POSTMan-Chrome-Extension#7514]
**Describe the bug**
Test Fails on assertions as the "(pm.environment.get("variable_name"))" fails to load the value from data file (csv) in tests["Response Validation"] =pm.expect(pm.response.json().variable_name).to.equal(pm.environment.get("variable_name"));
**To Reproduce**
1. Write a test to assert value in the response to match the environment variable
 tests["Response Validation"] =pm.expect(pm.response.json().variable_name).to.equal(pm.environment.get("variable_name"));
2. Run Collection runner
3. Select and load the data file in csv
4. Run the collection
5. and see the error

**Expected behavior**
Test should pass by loading the value in csv(requests/path/headers/body are working fine, only issue in the tests)

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.9.0
 - OS: Windows 10
**Additional context**

**Comment by hari2anand** [comment]
update!
 works fine! if used pm.variables.get("variable_name") instead pm.environment.get("variable_name")

**Comment by vvs11** [comment]
Great! @hari2anand Closing this for now. Let us know if you still face any issues
