### ISSUE TITLE
App crashes when using any menu item from keyboard or from shortcuts

### ISSUE THREAD

**Issue by arlemi** [a85/POSTMan-Chrome-Extension#7515]
**Describe the bug**
When on the login/signup page, either when opening the app or after login out, clicking `Postman` in the menu bar and then `Preferences` completely closes the app. Looks like a crash but no error message from either the OS or Postman is displayed.

**To Reproduce**
1. Open a new Postman session / logout from Postman 
2. Click on `Postman` in the Mac menu bar
3. Click `Preferences`
4. See the app closing

**Expected behavior**
I would expect the app to stay on and either: 
- tell me that preferences are not available when not logged in
- show me the settings page with a reduced amount of settings

**Screenshots**
![preferences](https://user-images.githubusercontent.com/5029719/67291791-fd85dd80-f4d9-11e9-915e-cc63efdc00c6.gif)

**App information (please complete the following information):**
 - Native App
 - Version 7.9.0 (7.9.0)
 - macOS Mojave 10.14.6

**Additional context**
None

**Comment by tim-sebring** [comment]
I have the same issue in Linux (Fedora 30, 64bit) when I click on "Settings" from the file menu. It just crashes. (I was trying to see if I could set a proxy since I don't have a direct internet connection.)

**Comment by baztian** [comment]
It should work if you first hit the skip sign in link. At least this worked for me

**Comment by Joulss** [comment]
I have the same problem (Ubuntu 18.04 64bit / i3wm) when I click on any menu item.
The console reports "TypeError: Cannot read property '0' of undefined"

**Comment by ankurdengla** [comment]
The fix fo this issue has been released as part of Postman v7.16.0. 

Please feel free to reopen the issue if the problem still persists.

**Comment by arlemi** [comment]
@ankurdengla1996 Is the expected behaviour now that nothing happens? If so can't we grey out the button?
