### ISSUE TITLE
Unable to get file request body in pre-request script 

### ISSUE THREAD

**Issue by sebastien-ma** [a85/POSTMan-Chrome-Extension#7516]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement custom signing in pre-request scripts. I've noticed that I can't get the request body when selecting a local file in the request. I need to read the file content in order to calculate a digest of the file content.

**Describe the solution you'd like**
Be able to get the file content in pre-request script.

**Describe alternatives you've considered**
Get sufficient metadata of the file being uploaded like SHA256 checksum etc.

**Comment by codenirvana** [comment]
Similar to #7210

**Comment by arlemi** [comment]
Closing this as a duplicate of #7210 to make it easier to track feature requests.
