### ISSUE TITLE
pm.environment.get before pm.environment.set is rewriting initial values in environment

### ISSUE THREAD

**Issue by shabubu** [a85/POSTMan-Chrome-Extension#7517]
**Describe the bug**
Under certain scenarios environment variables for postman retrieved and set within a prerequest script are overriding the initial value.  This is a big deal for my team as this is now taking values considered secret that are only set in `current value` columns, copies these secrets to initial value and finally syncs it to POSTMAN.

**To Reproduce**
1. Create a request within a workspace
2. Create or select an environment for variables
3. set environment variable in postman with a different value for current and initial value
4. Use a prerequest script for the request that uses `pm.environment.get` to get the value just set
5. use pm.environment.set for a different variable
6.  Make request
7.  View environment variables, the variable retrieved with `pm.environment.get` both the initial and the current value are now what the current value was set to
8. the variable set now has the the same value for initial and current value to whatever it was set as in the script.

**Expected behavior**
I would never expect getting a value in a script to change my workspace environment initial value settings.  Additonally, would not expect pm.environment.set to override initial value, either.

**Screenshots**
![postman_bug](https://user-images.githubusercontent.com/4340059/67345460-f23dac80-f4ef-11e9-9cfd-d6da990b3b3b.gif)

**App information (please complete the following information):**
 - Native App
 - v6.7.4
 - macOS Mojave 10.14.6

**Additional context**
Just reiterating how this is a very big deal for my company as this is causing leakage of personal password detail between team members due to rewriting initial values and syncing it to the postman cloud.

**Comment by DannyDainton** [comment]
Hey @shabubu,

It looks like your team is running an older version of the App - The current version is `7.9.0`, I know migrating a Team is a slightly different affair than a single person but it's worth looking into. We don't want you missing out on all the new features.

I tested this scenario in the latest version, you might want to disable this setting and give this another go:

<img width="346" alt="Screenshot 2019-10-24 at 10 05 57" src="https://user-images.githubusercontent.com/17089546/67470866-5d999280-f646-11e9-98fa-5441eecefd27.png">

![Persist_Variables](https://user-images.githubusercontent.com/17089546/67471063-b10be080-f646-11e9-8387-6ecd0d5cfde4.gif)

**Comment by shamasis** [comment]
Please update to latest app to see if things are resolved. Closing for now. Will be happy to reopen.
