### ISSUE TITLE
path variables are not replaced in example request of generated document

### ISSUE THREAD

**Issue by qiyuan-wang** [a85/POSTMan-Chrome-Extension#7518]
**Describe the bug**
**path variables** are not replaced in example request part of document.

**To Reproduce**
1. Create a collection
2. Create a request in collection created by step 1
3. Use path variables in URL
4. Save request
5. Select 'View in web' in collection panel
6. Check the request example in generated document.

**Expected behavior**
Request example should be code that reader can copy & paste to their terminal for testing.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

![image](https://user-images.githubusercontent.com/974160/67367766-badf0680-f5a8-11e9-8977-70562f10f8f0.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.9
 - OS: macOS Mojave 10.14.6

**Additional context**

**Comment by Cazaimi** [comment]
Investigating this.

**Comment by ranchanarajasekaran** [comment]
This issue has been resolved. Please reopen the issue to report any feedback on the same.
