### ISSUE TITLE
New Collection Variable Access Fails in Newman

### ISSUE THREAD

**Issue by SOTFNicole** [a85/POSTMan-Chrome-Extension#7519]
**Describe the bug**
Thanks to enhancement [5053](https://github.com/postmanlabs/postman-app-support/issues/5053#issuecomment-542555156) we can finally set and get collection variables. This is highly helpful to not pollute environment with variables specific to a collection. But it seems that while this is running just fine in Postman Runner, it triggers an error when run by Newman. 

I have made a call to 
var myVar= pm.collectionVariables.get('someVar');
in the pre-request scripts of the collection. 

Running a item in the collection manually or using runner to run the collection does not encounter any errors. But when using Runner it errors with "TypeError in prerequest-script"

**To Reproduce**
1. Create a collection
2. Add one request to the collection
3. Add a test to the request.
3. Add a variable to the collection
4. In the pre-request on the collection add a call to get the collection variable using the pm.collectionVariables.get method
5. Run the collection with newman
6. Will get a failed test reading "TypeError in prerequest-script"

**Expected behavior**
The collection variable should be gotten from the collection without error and all tests for the request should pass.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type Native App vs Newman
 - Postman Version 7.9.0

**Comment by DannyDainton** [comment]
Hey @SOTFNicole 

What version of Newman do you have installed?  I have `4.5.5` and this is working for me.

I've set a Variable at the Collection level and I'm using this in 2 places, the Params and logged the value out to the console using the same code that you posted.

<img width="1318" alt="Screenshot 2019-10-24 at 09 47 54" src="https://user-images.githubusercontent.com/17089546/67469359-f975cf00-f643-11e9-888f-302b73e00098.png">

<img width="734" alt="Screenshot 2019-10-24 at 09 49 09" src="https://user-images.githubusercontent.com/17089546/67469383-05fa2780-f644-11e9-886b-5feed3bacde7.png">

- Do you have any other code in that `Pre-Request Script` that might be causing the issue?
- What is the value of the Variable? 
- Can you provide a screenshot or a sample collection to reproduce the issue?

**Comment by SOTFNicole** [comment]
Apologies! There was some confusing amongst my DevOps team when I first followed up on this, they were looking at the wrong environment. Updating newman to 4.5.5 on our linux server resolved the issue.
