### ISSUE TITLE
Select a request in tree view from the runner

### ISSUE THREAD

**Issue by leofrances-extflowbird** [a85/POSTMan-Chrome-Extension#7525]
**Description of my problem**
When I run my tests in the runner and some tests fail, I'm always very frustrated I cannot open my request in the tree viewer from the runner and open the editor after. My collections have a lot of requests (between 500 and 1000). So, it is very complicated to retrieve my failed requests in the tree view to open the request editor. The only solution I found is: read the path of my request in the tooltip (because it is too long), and open folder by folder in my tree view. This solution is too boring for me and I've lost a lot of time.

**The solution I would like**
I would like to have a button in my run results of the runner to open my request in the tree viewer.

**Comment by malvikach** [comment]
Hi @leofrances-extflowbird 

This problem has been addressed in the latest Postman Release (version 10.12.0). 

You can now click on request names to open the requests from the Collection Runner Results. This will help with faster navigation while debugging and fixing a problem. We have also introduced a more efficient way to look at the response and request details (headers, bodies). 

![ezgif com-optimize (3)](https://user-images.githubusercontent.com/89449769/225821046-571441d0-00d3-4b80-8ee2-5fb6c50d026e.gif)

Please Note: The Postman version update is being rolled out, you will get it in the next 2-3 days if you haven't already.

Thanks again for your patience and feedback. We really appreciate it.

I am closing this issue, but please feel free to let us know about your experience.

Cheers!
Malvika
