### ISSUE TITLE
DevTools->Network is not showing information about the calls made.

### ISSUE THREAD

**Issue by ykartsev** [a85/POSTMan-Chrome-Extension#7529]
**Describe the bug**
According to the [documentation](https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs#network-calls-with-postman-console): 
> **Similar to DevTools**, **every call** along with its headers, network information, and payloads will be logged to the Postman Console.

Although, my DevTools->Network only shows javascript-related requests (see screenshot below) after I execute a request. I.e. data about the executed request is not shown.

In Chrome App this was not an issue - it was always possible to see all executed requests, copy them as cURL, etc. Although, since Postman became a native app, DevTools->Network is not displaying information about the calls made, so it's impossible to copy as cURL, as well as use other nice functions.

**To Reproduce**
1. Click '+' to add a new request.
2. Compose new GET request for say "https://google.com"
3. Open View -> Developer -> DevTools (either shared or current - both have the same behavior)
4. Click "Send" button
4. Observe 

**Expected behavior**
DevTools->Network should display information about "every call along with its headers, network information, and payloads" (like it was in Chrome App).

**Screenshots**
Request executed:
<img width="933" alt="Screen Shot 2019-10-24 at 11 33 14" src="https://user-images.githubusercontent.com/3834742/67501469-537d9100-f652-11e9-8a3b-15c139845d2e.png">

DevTools output after execution (no information about the call made, only JavaScript stuff):
<img width="839" alt="Screen Shot 2019-10-24 at 11 33 23" src="https://user-images.githubusercontent.com/3834742/67501486-58424500-f652-11e9-9d06-0dbef48b331d.png">

Console output after execution that confirms that the call was made:
<img width="882" alt="Screen Shot 2019-10-24 at 11 34 10" src="https://user-images.githubusercontent.com/3834742/67501494-5d06f900-f652-11e9-82c0-41eac63d0d00.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.10.0
 - OS: macOS Catalina 10.15 (although, this was reproducible in High Sierra and Mojave)
 - Chrome version (just in case): 78.0.3904.70 (Official Build) (64-bit)

**Comment by numaanashraf** [comment]
@ykartsev For Postman Desktop Apps, the network logs do not appear inside the DevTools. Please use the Postman Console to view your request logs. - https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs/#for-the-native-app-for-mac--windows--linux-1

**Comment by ykartsev** [comment]
Thank you @numaanashraf , it's not only viewing that I need... otherwise console would be just fine. What I can't do from console - is to copy request as cURL and other useful options (but mainly this one). Are there any plans to fix DevTools or maybe introduce "copy as cURL" option to the console? Should I add a feature request for that?

Thank you.
