### ISSUE TITLE
Opening Test runner causes postman to freeze

### ISSUE THREAD

**Issue by DerekSansom** [a85/POSTMan-Chrome-Extension#7531]
**Describe the bug**
Since last updating it'sno longer possible to run the collection runner, and attempting to ope it freezes everything

**To Reproduce**
1. Open Postman.
2. Hover over a collection
3. click arrow top right of collection name to open collection runner
4. Panel opens, at top of panel click Run

Nothing happens and the whole app freezes, so this panel cannot be hidden, nothing else can be clicked on except close button to shut everythgin down

**Expected behavior**
I excpect the collection runner to open, and the app not to freeze and not become completely unusable

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version [7.10.0]
 - OS: [Ubintu 18.04.3]

**Additional context**

**Comment by codenirvana** [comment]
@DerekSansom thanks for reporting this issue. Do you see any error logs in the [DevTools Console Logs](https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs/#for-the-native-app-for-mac--windows--linux)?

Is this happening for every collection? Does it freeze on opening runner using the shortcut (`Ctrl + Shift + N`)?

**Comment by DerekSansom** [comment]
From the console logs:

> Initializing the global config
> vendor-shared.js:517437 App updater event Object
> vendor-shared.js:517437 Disconnected from Interceptor
> 2vendor-shared.js:517437 Could not find on EditorStore. Missing or invalid
> parameter.
> (anonymous) @ vendor-shared.js:517437
> 3vendor-shared.js:517437 Could not find on CollectionStore. Missing or
> invalid parameter.
> (anonymous) @ vendor-shared.js:517437


This does just appear to be on one collection, I can open the collection
runner from other collections and by the shortcut (useful thanks)

But even after doing that if I do it via the original collection everything
just freezes again

Thanks,
Derek

**Comment by saswatds** [comment]
Hi @DerekSansom Can you give us a size estimate of this collection; like count of requests, size of request bodies, etc.

**Comment by DerekSansom** [comment]
84 requests across 10 subfolders (of which I only ever run one folder)
probably 50/50 get/post
posts, some are minimal, some up to 300 lines formatted xml/json

**Comment by saswatds** [comment]
We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not freeze or crash. Can you update to the latest version and check if this issue is fixed for you?

**Comment by DerekSansom** [comment]
Yes this works now, thank you
