### ISSUE TITLE
Generate code snippets layout bug

### ISSUE THREAD

**Issue by Weilet** [a85/POSTMan-Chrome-Extension#7533]
**Describe the bug**
The secondary menu of language selection in generate code snippets panel are invisiable.
In Windows 10 1903, setting zoom to 150%

**To Reproduce**
1. create a reuqest
2. click 'code' to enter generate code panel
3. click the language selection
4. The secondary menu are invisiable

**Expected behavior**
A secondary menu should be seen.

**Screenshots**
<img width="576" alt="Snipaste_2019-10-25_12-48-01" src="https://user-images.githubusercontent.com/32561597/67543916-1387de00-f726-11e9-8222-4b668ed75862.png">

**App information (please complete the following information):**
 - Native App
 - win32 10.0.17763 / x64
 - Windows 10 1903

**Additional context**
Nope

**Comment by DannyDainton** [comment]
Hey @Weilet 

What version of the App is this? 

There is a right scroll bar within that menu that I can see, that will show what you're looking for. 

This post on our Community fourm will also provide some help:

https://community.getpostman.com/t/not-able-to-see-the-javascript-or-node-js-code-in-postman/8433

**Comment by Weilet** [comment]
Solved, I found myself ignore right scroll bar on the buttom of the selection.
