### ISSUE TITLE
Postman doesn't open

### ISSUE THREAD

**Issue by Soraga54** [a85/POSTMan-Chrome-Extension#7534]
**Describe the bug**
When I run postman, either by click icon or by run with command 'postman', nothing happens.
I had look for the processus postman and I didn't find the processus postman.

**To Reproduce**
1. Either click icon or run a command to run postman
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/29144613/67550543-0a3b4900-f707-11e9-8f30-f674042acfec.png)

**App information (please complete the following information):**
 - Postman Version : 
![image](https://user-images.githubusercontent.com/29144613/67550685-5edec400-f707-11e9-8bf6-4aa2174b14fb.png)
 - OS: Debian GNU/Linux 10 (buster)

**Comment by froblesmartin** [comment]
It is something related with the latest version. I have found a basic workaround :sweat_smile: , install the previous version:
`sudo snap install postman --channel=v6/stable`

**Comment by harryi3t** [comment]
@Soraga54 
When did this start happening (after an update or fresh install)?
Can you try running the following commands to just confirm that the `postman` command is pointing to the snap binary
```bash
which postman # should be like /snap/bin/postman
ls -l `which postman` # should be like /usr/bin/snap (this should be same for all snap apps)
```

Also, if possible please share the logs at help@getpostman.com (please mention the GitHub issues number: 7534). This would help us in identifying the issue faster.
You can get the logs from `~/snap/postman/current/.config/Postman/logs`

**Comment by froblesmartin** [comment]
> @Soraga54
> When did this start happening (after an update or fresh install)?
> Can you try running the following commands to just confirm that the `postman` command is pointing to the snap binary
> 
> ```shell
> which postman # should be like /snap/bin/postman
> ls -l `which postman` # should be like /usr/bin/snap (this should be same for all snap apps)
> ```
> 
> Also, if possible please share the logs at [help@getpostman.com](mailto:help@getpostman.com) (please mention the GitHub issues number: 7534). This would help us in identifying the issue faster.
> You can get the logs from `~/snap/postman/current/.config/Postman/logs`

@harryi3t In our case, using Fedora 30 and having Postman installed with Snap this is the result of those 2 commands:

which postman: `/var/lib/snapd/snap/bin/postman`
ls -l \`which postman\`: `lrwxrwxrwx. 1 root root 13 Oct 24 11:30 /var/lib/snapd/snap/bin/postman -> /usr/bin/snap`

About the logs, there is nothing. No log receive anything even using the desktop launcher or just running `postman` in terminal.

The application is on the same version as OP, updated 5 days ago at 11:30 CEST (current date is Tuesday 29 October 2019)

**Comment by harryi3t** [comment]
@froblesmartin I am assuming you meant there are no logs on the terminal. Can you check the logs directory on the file system `~/snap/postman/current/.config/Postman/logs`?

Also, was the same app working fine before the 7.10.0 update?

**Comment by froblesmartin** [comment]
> @froblesmartin I am assuming you meant there are no logs on the terminal. Can you check the logs directory on the file system `~/snap/postman/current/.config/Postman/logs`?
> 
> Also, was the same app working fine before the 7.10.0 update?

Hi @harryi3t. Yes, those logs are the ones I mean, none of them have been modified since the new versions was released, even running the app through the CLI either the .desktop launcher.

Yes, last week it was working in 5 computers and since Thursday we have been suffering this in all of them.

**Comment by harryi3t** [comment]
@froblesmartin 
Could you try opening the app directly using the executable

```bash
SNAP=true /snap/postman/current/usr/share/Postman/Postman
```

This will help us narrow down the issue and would let us know if the issue is specific to the snap variant of Postman.

**Comment by kctang** [comment]
i was facing this issue yesterday when using wayland. today i switched back to x11 and postman (installed via snap) launched without issue. just sharing in case wayland is the cause of the incompatibility - i am not 100% sure.

**Comment by harryi3t** [comment]
Thanks @kctang for providing this extra information.
@froblesmartin Are you using Wayland or x11? If using Wayland, could you try switching to x11?

**Comment by harryi3t** [comment]
We are tracking this issue here https://github.com/postmanlabs/postman-app-support/issues/6252

**Comment by akvadrako** [comment]
This isn't a duplicate of #6252. Even without native wayland support, other Electron apps work under wayland using XWayland. Why doesn't Postman?

**Comment by xrn** [comment]
@harryi3t I have exactly same issue - using your command Postman is starting.

Debian 10
Postman for Linux
Version 7.13.0
linux 5.4.0-1-amd64 / x64

**Comment by Kocicak** [comment]
Working command: `DISABLE_WAYLAND=1 snap run postman`

I have just edited .desktop file (/var/lib/snapd/desktop/applications/postman_postman.desktop) - added that env variable and now it is OK. We just need to wait for postman / electron devs add support for wayland.

Or maybe we should stick to X11 for another year or so, it just works.

**Comment by michalfita** [comment]
Same issue for me. :+1: for adding temporary workaround to the `.desktop` file in the snap.

**Comment by ajuliang** [comment]
> Working command: `DISABLE_WAYLAND=1 snap run postman`
> 
> I have just edited .desktop file (/var/lib/snapd/desktop/applications/postman_postman.desktop) - added that env variable and now it is OK. We just need to wait for postman / electron devs add support for wayland.
> 
> Or maybe we should stick to X11 for another year or so, it just works.

It works for me!! Thank you.

**Comment by harryi3t** [comment]
In the latest version of Postman (on snap), the app does this by default now.
