### ISSUE TITLE
Password recovery mail not received

### ISSUE THREAD

**Issue by JavaPioneer** [a85/POSTMan-Chrome-Extension#7535]
When I retrieve my password, the system does not send me a password recovery email.

I retrieve my password  by :
https://identity.getpostman.com/trouble-signing-in

and Client , My email is  **@163.com;

**Comment by sivcan** [comment]
Is this still an active issue, since this was filed in 2019? 

@JavaPioneer I'll be closing this, in case it's still an issue then please let us know or write to us at help@postman.com in-case you aren't receiving the reset password email.

Thanks!
