### ISSUE TITLE
Better team management - license usage / activity report

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#7538]
**Is your feature request related to a problem? Please describe.**
Our Postman team has been growing quite rapidly and we have a lot of users throughout different roles, offices and even countries, so it is really hard to keep track of who is actually using their license. This means we may be paying for users who really do not need the license and those spots can be used for someone else.

**Describe the solution you'd like**
For accounts with support role to be able to view at least some limited user activity, a good start will be last logged-in date/timer, which would greatly help with managing the team.

**Describe alternatives you've considered**
N/A

**Comment by VicKetchup** [comment]
Something to add to this ticket, would be nice to be able to configure a value to remove the users from the team if they are inactive automatically and have the amount of users slots automatically reduced to only the ones being used on every billing cycle refresh.

**Comment by ArjunSingh-PM** [comment]
@VicKetchup You can view the [Members Overview Report](https://learning.postman.com/docs/reports/members-overview-reports/) for the last active date of your team members. Let us know if you have further queries on this.
