### ISSUE TITLE
Feature Request: Create Folders in collection

### ISSUE THREAD

**Issue by FREEZX** [a85/POSTMan-Chrome-Extension#754]
Adding multiple levels of grouping would make this extension even more awesome.
For example if i'm developing a RESTful API for something and it would make sense to be able to create folders in the collection, each representing a different resource endpoint, each folder containing requests for inserting, removing, updating etc.
I'm working on different apps, so i use collections to separate different apps.

**Comment by nedkoh** [comment]
Not having nested folders is a big impediment of the product's usability. This makes organizing and working with large apis extremely difficult. Same applies to a few endpoints which support many combinations.
