### ISSUE TITLE
Custom mimetype

### ISSUE THREAD

**Issue by imclint21** [a85/POSTMan-Chrome-Extension#7542]
Hi,

Could you allow any mime type ? I would like by example set text/csv or other!

Thanks

**Comment by arlemi** [comment]
Hi @clintnetwork,

You can set the MIME type that you wish in the Headers tab of your request. 
![Screenshot 2019-10-28 at 11 30 07](https://user-images.githubusercontent.com/5029719/67675141-53450480-f976-11e9-99d1-dd9fcb1ab187.png)

Is that what you're looking for?

**Comment by imclint21** [comment]
ha yes it's true, but maybe you can add a `custom` option in the list where we have json, text, etc
