### ISSUE TITLE
didn't adding the latest version.

### ISSUE THREAD

**Issue by Monukushwaha** [a85/POSTMan-Chrome-Extension#7543]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by kamalaknn** [comment]
@Monukushwaha We are not able to identify the issue from your bug report. Please follow the issue template and [guideline](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) to help us identify the root cause better.
