### ISSUE TITLE
Broken image link in doc «Variables complete reference»

### ISSUE THREAD

**Issue by molechka** [a85/POSTMan-Chrome-Extension#7548]
**Describe the bug**
Link for picture — https://assets.postman.com/postman-docs/ariables-Chart.png
Need to add «V» at the beginning — Variables-Chart.png

**To Reproduce**
1. Go to «Variables complete reference» — https://learning.getpostman.com/docs/postman/environments_and_globals/variables_complete_reference/
2. Click on picture in «Variables’ scope pictorially»

**behavior**
Link https://assets.postman.com/postman-docs/ariables-Chart.png and AccessDenied

**Expected behavior**
Open link https://assets.postman.com/postman-docs/Variables-Chart.png

**Screenshots**
![step 1](https://user-images.githubusercontent.com/5832910/67683319-3de5cf80-f9a2-11e9-8be3-dbfd65d70d57.png)
![error](https://user-images.githubusercontent.com/5832910/67683320-3de5cf80-f9a2-11e9-981c-e5dd37846a38.png)
![expected link](https://user-images.githubusercontent.com/5832910/67683321-3de5cf80-f9a2-11e9-9bf2-97785092e38a.png)

**Comment by DannyDainton** [comment]
Closing this issue as it's been resolved.
