### ISSUE TITLE
Auth helpers are pre-filled with data

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7550]
**Describe the bug**
It seems that the OAuth helpers are pre-filled with the last auth data when they actually should not be. 

Two cases:

- the request in a different collection
- the request is not associated with a collection
- completely new workspaces

**Expected behavior**
I would not expect the auth helpers to be prefilled with any information when being opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/1197635/67710024-10efe780-f9b7-11e9-852e-51945dc2212e.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.10.0
 - OS: macOS

**Comment by shamasis** [comment]
Hmm. This was a frequently requested feature back in 2014. I will let @vkaegis look back at this and see if these can be converted to tiny in modal settings/checkboxes to toggle this behaviour - but this just an idea and might conflict with our design components.

**Comment by giridharvc7** [comment]
This is now fixed in v8.1
