### ISSUE TITLE
Console remains empty / request not sent after OAuth2 token request

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7551]
**Describe the bug**
I am trying to fetch an OAuth2 token using the OAuth2 helper for "Client Credentials" grant type.

**To Reproduce**
1. Go to Authorization
2. Select OAuth 2.0
3. Click "Get new access token"
4. Select Grant Type "Client credentials" (or Authorization Code)
5. Fill in some data
6. The error appears: "Could not complete OAuth 2.0 login. Check Postman console for more details."
7. The Postman console remains empty (I have checked for all filters to be enabled), no request is being sent.

**Expected behavior**
The request should be sent and the Postman console should display it.

**Screenshots**
![image](https://user-images.githubusercontent.com/1197635/67710948-e4d56600-f9b8-11e9-8f31-ed1e02f86b4c.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.10.0
 - OS: macOS

**Comment by loughrao** [comment]
Similarly I am not seeing anything in the postman console on successful Oauth2 requests. Is there a way that we can revert to 7.9? I have been unsuccessful at downgrading.

**Comment by vdespa** [comment]
@loughrao The changelog has download links for all previous versions of Postman.

https://www.getpostman.com/downloads/release-notes

**Comment by thoffmann-fms** [comment]
Same issue.  Fiddler shows the request being made and rejected but the console remains blank.

**Comment by alexantom** [comment]
![postman_oauth2_login](https://user-images.githubusercontent.com/54152098/68534028-df471c80-02e4-11ea-86ec-fa9bc23d9380.png)

<img width="1088" alt="postman_oauth2_sign_progress" src="https://user-images.githubusercontent.com/54152098/68534035-ebcb7500-02e4-11ea-9f66-5797d4619538.png">

![postman_after_sign_in](https://user-images.githubusercontent.com/54152098/68534043-00a80880-02e5-11ea-9010-8312dbfd41d1.png)


is this a related issue,  after login the console is blocked ?

This is the version details

```
Postman for Mac
Version 7.11.0
OS X 18.7.0 / x64
```

```
System Version: macOS 10.14.6 (18G103)
Kernel Version: Darwin 18.7.0
Boot Volume: Macintosh HD
```

**Comment by vdespa** [comment]
@alexantom it does look related. Do you get the error as well?

**Comment by alexantom** [comment]
I'm not able to see any error  from console.

**Comment by fjblau** [comment]
Same on my mac... looking for a fix

**Comment by alpharoux** [comment]
I tried using the callback URL = https://app.getpostman.com/oauth2/callback which will sometimes (2/10) bring me to the login page but most of the time just the blank screen.

If the login screen has been successfully loaded, after I have provided my credentials the login screen becomes blank - the access token details are not displayed.

This was working with me last December 2019.

**Comment by vdespa** [comment]
I have just tested again an OAuth2 using Postman version 7.16.0 and it worked. For that reason, I will be closing this issue.

If you still encounter issues with this, please create a new issue and describe your problem there.

**Comment by bberliner** [comment]
Seeing this exact same problem with Postman 7.17.0. Very frustrating. Used to work perfectly. My OAuth Server will do a 302 Redirect to complete the /authorize flow to:

```
location: https://www.getpostman.com/oauth2/callback?code=O2AC.foo.bar.NY1VS7NQSIWNEEGBCS4YQ&state=abc123
```

That returns another redirect 301 to:

```
location: https://www.postman.com/oauth2/callback?code=O2AC.foo.bar.NY1VS7NQSIWNEEGBCS4YQ&state=abc123
```

which redirects with a 301 to a different place:

```
location: https://app.getpostman.com/oauth2/callback?code=O2AC.foo.bar.NY1VS7NQSIWNEEGBCS4YQ&state=abc123
```

which finally resolves with an echo of all the headers and a status 200, which does not allow Postman to finalize the OAuth flows:

```
< HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache, must-revalidate
< Cache-Control: no-cache, no-store, must-revalidate
< Cache-control: no-cache="set-cookie"
< Content-Type: text/html;charset=UTF-8
< Date: Tue, 04 Feb 2020 20:55:36 GMT
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Expires: 0
< Pragma: no-cache
< Pragma: no-cache
< Server: nginx
< Set-Cookie: PHPSESSID=tcntp28o26g5a41ito2bbsddvp; expires=Wed, 05-Feb-2020 12:55:36 GMT; Max-Age=57600; path=/
< Set-Cookie: AWSELB=13494177162DC29BAEE2C0803504272B36F3A2CE0CAB2FEB4A23D29A50F1241500AE79150D695DDDE7A14AD024CEA61F4ED06EDED5A379DFB022094E1C0FF5D623C7895CBC;PATH=/;MAX-AGE=1440
< Set-Cookie: AWSELBCORS=13494177162DC29BAEE2C0803504272B36F3A2CE0CAB2FEB4A23D29A50F1241500AE79150D695DDDE7A14AD024CEA61F4ED06EDED5A379DFB022094E1C0FF5D623C7895CBC;PATH=/;MAX-AGE=1440;SECURE;SAMESITE=None
< Strict-Transport-Security: max-age=31536000; preload
< X-Frame-Options: SAMEORIGIN
< X-Powered-By: PHP/7.2.26
< X-Srv-Name:
< X-Srv-Span:
< X-Srv-Trace: v=1;t=1856357e63e45647
< X-Xss-Protection: 1; mode=block
< Content-Length: 1
< Connection: keep-alive
```

Can someone please re-open this? Thank you!

**Comment by mrichman** [comment]
Same issue using Postman 7.22.1 on macOS. I'm using Amazon Cognito OAuth2 with Implicit grant type. Nothing in the Postman Console at all. Setting Callback URL to https://app.getpostman.com/oauth2/callback has no effect.

**Comment by vdespa** [comment]
@mrichman Can you send us a screenshot with your OAuth2 configuration from Postman (blur or remove any sensitive data)?

**Comment by mrichman** [comment]
Opened separate issue with screenshots here
https://github.com/postmanlabs/postman-app-support/issues/8319
