### ISSUE TITLE
Documentation example request/clarification

### ISSUE THREAD

**Issue by akrueger** [a85/POSTMan-Chrome-Extension#7558]
I'm looking for an explanation in the documentation for the following arguments given to the `jsonBody()` function:

```
pm.response.to.have.jsonBody(optionalExpectEqual:Object)
pm.response.to.have.jsonBody(optionalExpectPath:String)
pm.response.to.have.jsonBody(optionalExpectPath:String, optionalValue:*)
```

What do these refer to?
`optionalExpectEqual:Object`
`optionalExpectPath:String`
`optionalExpectPath:String, optionalValue:*`

I am wanting to see if my object property exists.

The object: 
```
{
  data: {
    user: {
      ...
  }
}
```

`pm.response.to.have.jsonBody('data')` seems to check that the data object is present, but I am unsure if I can also check that `data.user` exists. The "path" name makes me think I can, but I haven't succeeded with this yet.

**Comment by xk0der** [comment]
You hunch is correct, you can use the `pm.response.to.have.jsonBody(optionalExpectPath:String)` assertion call for existence of the path within a JSON resonse body.

In your case, the test should look like the following
```
pm.response.to.have.jsonBody("data.user");
```

I'm attaching a JSON export of a collection demonstrating all three assertion calls:
[Test JSON Body.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3829295/Test.JSON.Body.postman_collection.json.zip)

[Import ](https://learning.getpostman.com/docs/postman/collections/data-formats/#importing-postman-data)the attached [collection](https://github.com/postmanlabs/postman-app-support/files/3829295/Test.JSON.Body.postman_collection.json.zip) and run it to view the assertion in action.

Check out the "Test" tab to view the code.

Here is a brief note on each of the calls:

* `pm.response.to.have.jsonBody(optionalExpectEqual:Object)`
Check for an existence of a JSON object within JSON response body.
_Example_:  `pm.response.to.have.jsonBody({"obj": { "a" : "1" } });`
* `pm.response.to.have.jsonBody(optionalExpectPath:String)`
Check if the specified path exists within JSON response body
_Example_:  `pm.response.to.have.jsonBody("result.data");`
* `pm.response.to.have.jsonBody(optionalExpectPath:String, optionalValue:*)`
Check that value at the path equals the one supplied
_Example_: `pm.response.to.have.jsonBody("result.data", [1,2,3]);`

**Comment by clemjt** [comment]
Hi @xk0der I tried to use your attached collection especially with the method `pm.response.to.have.jsonBody(optionalExpectEqual:Object)` but was not able to make the test fail when trying to modify it. Would it be possible for you to write at least one test which fails with this method? Currently, it seems to always succeed regardless of the change I make to the body or at the test itself.

I'm attaching a JSON export of your collection modified to demonstrate you my assertions:
[Test JSON Body With Test Which Should Fail But Doesnt.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/4297440/Test.JSON.Body.With.Test.Which.Should.Fail.But.Doesnt.postman_collection.json.zip)

Thank you in advance.

**Comment by szaitsev** [comment]
Is there any plan to fix the bug? It is really major issue with whole testing framework inside the Postman.
