### ISSUE TITLE
Email Subject Postman Pro when on Free Plan

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7560]
Writing on behalf of the 
<img width="741" alt="Screen Shot 2019-10-30 at 3 49 16 PM" src="https://user-images.githubusercontent.com/5624835/67905292-158adc00-fb2e-11e9-8f45-2c88d523e7f4.png">
user

**Describe the bug**
Invite emails to teams when on the free team mention Postman Pro in the subject.

**To Reproduce**
1. Create a free team
2. invite a teammate
3. check subject on invite email 

**Expected behavior**
Invite to Postman and not Postman Pro

**Additional context**
May cause users to question if they are being charged. Definitely users who downgraded from Pro to free.

**Comment by DannyDainton** [comment]
I believe that this has been sorted now @stcalica - Would you be able to confirm, please?

**Comment by DannyDainton** [comment]
Closing this out @stcalica - We can open again if the issue is still displayed in the email subject.
