### ISSUE TITLE
Duplicate environments being generated, possibly due to version mismatches

### ISSUE THREAD

**Issue by josephpconley** [a85/POSTMan-Chrome-Extension#7561]
**Describe the bug**
In our team workspace, we've been experiencing an issue where our environments are being duplicated (often several times).  We believe this is likely due to some members being on version 7+, while others were on 6

**Expected behavior**
I expect environments to not be duplicated

**App information (please complete the following information):**
- Native App
- Postman Version 6 and 7 
- Variety of OS's, mostly Linux and Mac

**Comment by vvs11** [comment]
@josephpconley Could you provide us with more information about how the environments are duplicated and what steps should be followed to reproduce this?

**Comment by shamasis** [comment]
Additionally, you can email help@postman.com with your user details and check in to see if we can trace the cause of this from any form of server errors.

**Comment by josephpconley** [comment]
I will close, latest version of Postman doesn't seem to be having this issue.  Thanks!
