### ISSUE TITLE
Postman Echo: Request body is omitted when Content-Type is missing

### ISSUE THREAD

**Issue by vadimklimov** [a85/POSTMan-Chrome-Extension#7565]
**Describe the bug**
While using Postman Echo service, it has been noticed that when requests contain content in the body and don't contain indication of MIME type of the body (a header 'Content-Type' is missing in the request), the service omits submitted body content.

**To Reproduce**
1. In Postman application: send a POST request to https://postman-echo.com/post with some body content and remove a header 'Content-Type' from the request. Alternatively, in cURL, execute command: curl -X POST https://postman-echo.com/post -d 'Test message'.
2. The echo service sends back response body:
`{
	"args": {},
	"data": "",
	"files": {},
	"form": {
		"Test message": ""
	},
	"headers": {
		"x-forwarded-proto": "https",
		"host": "postman-echo.com",
		"content-length": "12",
		"accept": "*/*",
		"content-type": "application/x-www-form-urlencoded",
		"user-agent": "curl/7.58.0",
		"x-forwarded-port": "443"
	},
	"json": {
		"Test message": ""
	},
	"url": "https://postman-echo.com/post"
}`
3.. Inspect response body and check content of an element 'data' (that shall contain echoed request body) - the element happens to have no value, although the submitted request contained body.

Similar behavior has been noticed for other HTTP methods (PUT, etc.) - here, POST request is provided as an example.

**Expected behavior**
Echoed request body shall contain content of the body that has been submitted in the request, similarly to requests that are submitted with a valid value of the header 'Content-Type' - such as: curl -X POST https://postman-echo.com/post -H 'Content-Type: text/plain' -d 'Test message'. Corresponding response body for such a request contains the originally submitted body as a value in the element 'data':
`{
	"args": {},
	"data": "Test message",
	"files": {},
	"form": {},
	"headers": {
		"x-forwarded-proto": "https",
		"host": "postman-echo.com",
		"content-length": "12",
		"accept": "*/*",
		"content-type": "text/plain",
		"user-agent": "curl/7.58.0",
		"x-forwarded-port": "443"
	},
	"json": null,
	"url": "https://postman-echo.com/post"
}`

**App information:**
 - Postman native application 7.10.0
 - cURL 7.58.0

**Comment by DannyDainton** [comment]
@VadimKlimov Is this something that you're using and having issues with?

**Comment by vadimklimov** [comment]
@DannyDainton, yes, the issue still remains. The issue was identified accidentally, when one of callers was tested against the Postman Echo service and the header Content-Type was omitted (although in normal circumstances, callers would normally set the content type header).

**Comment by apoorvgupta03** [comment]
https://github.com/postmanlabs/postman-app-support/assets/110587492/a6a26312-da3a-4865-9285-161267c0096b

@vadimklimov Now upon hitting the `https://postman-echo.com/post` endpoint without any  `content-type` headers,  the `Test Message` is in the `data` object of the response.
