### ISSUE TITLE
"Migrate my team to v7.0

### ISSUE THREAD

**Issue by joshua-bn** [a85/POSTMan-Chrome-Extension#7567]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by kamalaknn** [comment]
@joshua-bn We are not able to understand the issue you are facing from this description.

If you are having trouble migrating your team to Postman v7 please reach out to `help@getpostman.com` from your registered email address. 

If you are seeing any unexpected behaviors when trying to update to Postman v7 or using Postman after upgrading to v7 please provide more details so we can take a closer look at it.
