### ISSUE TITLE
"Migrate my team to v7.0" "Learn more" link broken

### ISSUE THREAD

**Issue by joshua-bn** [a85/POSTMan-Chrome-Extension#7568]
**Describe the bug**
Got a notification to migrate my team to v7. Clicked on the "learn more link" get a 404.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by sankalp0o** [comment]
@abhijitkane Would this need to be fixed on the docs or in the product?

**Comment by Pricilla09** [comment]
Seems like the same issue exists when you are trying to publish the Docs, and the "Learn more about version tags" link is broken as well. 

Environment Information

Platform Type: Native Desktop App
Postman Version: Version 8.0.6
Operating System: Win 10

https://user-images.githubusercontent.com/71498483/108924947-a7e5b600-7676-11eb-918e-40ecdab2c2d0.mp4

**Comment by timbochamp** [comment]
I'm going to close this out where migrations from v6 to v7 for teams happened in January this year, so I don't think this link is accessible anymore. 

For the second issue, the publish documentation flow uses Postman for Web now, and the "Learn more about version tags" link was working for me when testing on Windows 10. 

Please feel free to reopen this if I'm mistaken here!
