### ISSUE TITLE
Typing '{' in the middle of request URL of an imported collection results in an error

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7570]
**Describe the bug**
A user reported that they had imported a collection and when they type '`{`' in the middle of the URL, an error is instantly thrown.

I found out after some investigation that the Collection JSON had variable descriptions with fields that aren't part of Postman's Collection JSON schema.

And importing this collection resulted in the creation of "empty" variables.
<img width="508" alt="Screen Shot 2019-11-01 at 12 58 06 PM" src="https://user-images.githubusercontent.com/21366/67993782-42163380-fca7-11e9-8d50-08b139c07dea.png">

When we type '`{'` Postman tries to autocomplete variable names, but since these are 'undefined' an exception is thrown and thus the error.

**To Reproduce**
1. Export a collection with collection level variables
2. Edit all variables so that they do not conform to Postman Collection's JSON schema
3. Import this collection
4. Edit URL and enter '{' in the middle of the URL
5. An error will pop-up right away!
<img width="476" alt="Screen Shot 2019-11-01 at 12 56 39 PM" src="https://user-images.githubusercontent.com/21366/67993747-1004d180-fca7-11e9-8cef-1ec405b70221.png">

**Expected behaviour**

- No errors should be thrown and URL editing should happen normally.
- I believe the error lies within the "collection importing" code, which should throw warnings about invalid schema and should not create empty variables.

**App information (please complete the following information):**
 - App Type : Native App]
 - Postman Version : 7.10.0
 - OS: macOS 

**Additional context**
Logged by Postman on behalf of a user.

**Comment by xk0der** [comment]
To anyone landing here for a similar issue, check [collection variables](https://learning.getpostman.com/docs/postman/environments-and-globals/variables-complete-reference/#collection-variables) and if you find any empty variables, removing those should help fix the issue.

**Comment by xk0der** [comment]
More details provided by our user internally at Zendesk states that the tool used to generate the collection was https://github.com/postmanlabs/swagger2-postman2

**Comment by kamalaknn** [comment]
@xk0der Can you provide a sample collection that we can use to reproduce this issue?

**Comment by adamvanaken** [comment]
Hey. Original user here. Below is the original swagger.json and a reproducing postman collection. They might not be from the same source, but the structure should be the same as the original issue.

[swagger.json.txt](https://github.com/postmanlabs/postman-app-support/files/3809370/swagger.json.txt)
[Client Settings Service.postman_collection.json.txt](https://github.com/postmanlabs/postman-app-support/files/3809371/Client.Settings.Service.postman_collection.json.txt)

**Comment by kamalaknn** [comment]
Hey @adamvan101 

Thanks for the info. I was able to reproduce this issue. We will look into fixing this issue.

**Comment by kamalaknn** [comment]
Hey @adamvan101 

We've pushed a fix for this on the [canary channel](https://www.getpostman.com/downloads/canary) in Postman 7.12.0-canary01. We will keep this thread up to date when the fix is on the stable channel.

Please let us know if you are still seeing issues on the Canary channel.

**Comment by kamalaknn** [comment]
@adamvan101 This is released as part of Postman 7.12. I'm closing this issue now.
