### ISSUE TITLE
Hello, does postman support extending the proprietary protocol written by java?

### ISSUE THREAD

**Issue by jianglgit** [a85/POSTMan-Chrome-Extension#7572]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by postman-kenji** [comment]
This request requires further information. @jianglgit Please reopen if the question is still valid, with additional details. Thanks!

**Comment by jianglgit** [comment]
感谢！我已经收到您的邮件。
