### ISSUE TITLE
https://github.com/postmanlabs/postman-app-support/issues/3157

### ISSUE THREAD

**Issue by VigneshwariSrinivasan** [a85/POSTMan-Chrome-Extension#7574]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by saswatds** [comment]
This is issue lacks information on how to reproduce. We would request you to reopen this issue with step or more information help us identify the issue.

**Comment by VigneshwariSrinivasan** [comment]
Step 1 - I had a collection having 3 POST and 2 GET requests.
Step 2 - My collection is for User Registration.
Step 3 - But while running the collection , i cant able to run all 3 POST and 2 GET requests, instead it is running only one request.
But i want to run all the requests from my collection.
