### ISSUE TITLE
Permission error while trying to access archive collections 

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#7576]
**Describe the bug**
User is getting Permission error while trying to access archive collections 

**To Reproduce**
1. Navigate to  https://go.postman.co/usage/archive
2. Getting "**You don't have permission to view this page**"

**Expected behavior**
User should be able to download the data from the archive

**Screenshots**
![Screenshot 2019-11-04 at 2 37 28 PM](https://user-images.githubusercontent.com/41741228/68119198-1190fc80-ff28-11e9-9cd5-5065d054ba74.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version -7.6.0

**Comment by sankalp0o** [comment]
Hey @ash007-postman 
Is this a Pro/Enterprise team that's seeing this? If yes, we're tracking this issue at #7476.

**Comment by ash007-postman** [comment]
@sankalp0o Yes, they upgraded from Free to Postman Pro

**Comment by sankalp0o** [comment]
I'm closing this ticket since we're already tracking this at #7476. This is a known bug when archived collections do not get unarchived on upgrading to Pro. We're working on fixing this as we speak and should have a resolution very soon.
