### ISSUE TITLE
GitHub Integration - support for Pull Requests

### ISSUE THREAD

**Issue by narbit** [a85/POSTMan-Chrome-Extension#7578]
This is a general question about GitHub integration. 

Forking and merging described in the [docs](https://learning.getpostman.com/docs/postman/collections/version-control-for-collections/) - appears to be Postman's functionality for team collaboration and change tracking. When forking, no actual fork is created in GitHub. Is there currently any way to get team's feedback via some type of Postman equivalent of pull request?

**Comment by preethammavin** [comment]
@narbit thanks for the feedback, we are looking at how we can address this workflow. Will definitely reach out when we have a better idea of how we can solve this. Taking this feedback for now.

**Comment by ankitjaggi** [comment]
@narbit Postman has it's own Pull Request functionality now which you can use to solve your use case. For more information, you can head over to our [Learning Center](https://learning.postman.com/docs/collaborating-in-postman/version-control/#creating-pull-requests).

**Comment by shashankawasthi88** [comment]
@narbit Also with the launch of V10 we have introduced a new API builder experience with native git integration. Read my [blogpost](https://blog.postman.com/announcing-postmans-redesigned-api-builder-with-native-git-support/) to read more about it. You can also schedule a call with me to discuss the end-to-end flow.  You can set up a time with me using [this](https://calendly.com/shashank-awasthi/v10-feedback?month=2022-09) link.
