### ISSUE TITLE
Monitor Performance no displaying response times

### ISSUE THREAD

**Issue by sebainones** [a85/POSTMan-Chrome-Extension#7579]
**Describe the bug**
Monitor Performance graph is not displaying the response times.

**To Reproduce**
1. Go to your Workspace
2. Click on Monitors.
3. Click on the specific Monitor you want to visualize.
4. See error (Graph not loading the time responses)

![PostmanBug](https://user-images.githubusercontent.com/4959157/68192446-a12ebd80-ffb1-11e9-9abb-da6351e77e4f.png)

**Expected behavior**
The graph should show the different time responses on different days **as it used to do!**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 -  Using the Postman Web Interface.
-  Using Chrome Version 77.0.3865.120
-  Locally I have v7.10.0

**Additional context**
It has started happening in the past few days.

**Comment by shivam-postman** [comment]
Hello @sebainones , we've identified the issue and the fix will be out soon. Meanwhile, you can try the following steps to display the graph correctly:

1. Go to your workspace monitors.
2. Select a monitor, different from the one you want to view.
3. Refresh the page.
4. Go to your workspace monitors and select the monitor you wanted to view.

Do let us know if this doesn't solve the problem.

**Comment by ArjunSingh-PM** [comment]
@sebainones Thanks for sharing this issue with us. Is this a persistent issue for you or does this issue resolve after refreshing the monitoring page?

**Comment by sebainones** [comment]
Hello @shivam-postman . Yes, those steps did the trick ;)
Thank so much for the quick reply and let me know if you need further information from my side.

**Comment by shivam-postman** [comment]
@sebainones  the fix is out and the page should be loading now. Can you please verify?

**Comment by sebainones** [comment]
Yes. I have just verified it. It's working as expected :+1: 
Thanks  @shivam-postman for fixing it so quickly.

**Comment by ArjunSingh-PM** [comment]
Thanks a lot for the confirmation, @sebainones!
