### ISSUE TITLE
Team admin encountered workspaces without admins - unable to manage users and delete workspaces

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7586]
**Describe the bug**
A user, who is a Team admin, reported seeing workspaces without any "admin".
For these workspaces, they are unable to change the "role" for themselves or any other workspace members.

This was reported for both the _default_ Team workspace and a _normal_ Team workspace.

The user would like to be able to control the workspaces to remove users and delete the non-default workspace.

**To Reproduce**
I was unable to reproduce.
I was able to change roles for workspaces after removing all workspace admins.

**Expected behaviour**
* After removing all other workspace admins, Team admin should obtain workspace admin roles.
* For default workspace there should be at least one workspace-admin

**Screenshots**
Default Team workspace
![image](https://user-images.githubusercontent.com/21366/68267815-8e52e080-00b8-11ea-8b4f-ff0f2837d36c.png)

Team workspace with only the Team Admin in it
![image](https://user-images.githubusercontent.com/21366/68267844-ab87af00-00b8-11ea-851c-f96475876456.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version : 7.10.0
 - OS: unclear

**Additional context**
Logged by Postman on behalf of the user.
Team and workspace details provided internally.

**Comment by sankalp0o** [comment]
Thanks for reporting! We will look into why this is happening and get back soon.

**Comment by sankalp0o** [comment]
Hey Amit, we've fixed the problem. Now if the last admin tries to leave the workspace, they'd be asked to assign someone else the admin role. Also if the last admin leaves the team, "everyone in team" get the Admin role.
I'm closing the issue but please let us know if someone else runs into this problem.

**Comment by boskomirkic** [comment]
> Hey Amit, we've fixed the problem. Now if the last admin tries to leave the workspace, they'd be asked to assign someone else the admin role. Also if the last admin leaves the team, "everyone in team" get the Admin role. I'm closing the issue but please let us know if someone else runs into this problem.
***************************************************************
Hi, yesterday I have encountered one other scenario where workspace can still end up without admin; it is when the only Private workspace Admin is removed from a team by Team Admin via "Manage team", while there is another Private workspace member who is not an admin. In that case there is no control as explained above.

Postman for Web, Version 9.22.4-220623-1100
