### ISSUE TITLE
The request code (eg cUrl) with temporary headers can not run directly in a terminal using command line mode

### ISSUE THREAD

**Issue by ljppttfn** [a85/POSTMan-Chrome-Extension#7588]
**Describe the bug**
The request code (eg cUrl) with temporary headers can not run directly in a terminal using command line mode.

When remove `-H 'Content-Length: 344' \` then run successfully.

**Comment by saswatds** [comment]
Hi @ljppttfn, The new codegen has the setting to stop including temporary headers in the generated code.
![Screenshot 2019-11-21 at 5 57 37 PM](https://user-images.githubusercontent.com/8796447/69338089-6a7ec580-0c88-11ea-99aa-00952924d3a5.png)
