### ISSUE TITLE
Postman for Mac Unable to Sync

### ISSUE THREAD

**Issue by mssio** [a85/POSTMan-Chrome-Extension#7589]
**Describe the bug**
I can't enable sync in Postman for Mac.

**To Reproduce**
When I use the app, sync button did nothing at all when pressed. I can't sync my workspace at all, and when I try to create new workspace the app ask me show enable sync button, and when pressed it just open this web page: https://learning.getpostman.com/docs/postman/launching-postman/syncing/

**Expected behavior**
I should be able to sync my requests and/or collections and can create multiple workspace

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.10.0
 - OS: macOS Catalina 10.15.1

**Comment by Ghusar** [comment]
@mssio Can you try logout and login to postman app, If that does not resolve the issue, you can write us to help@getpostman.com so that we can take a closer look.

**Comment by mssio** [comment]
@Ghusar 

yeah I have tried log out and log in again, but the issue still persist. I have also tried restarting my Mac, reinstalling the app but nothing works. Okay I will send email to help@getpostman.com.

Thanks for your reply.

**Comment by Ghusar** [comment]
@mssio Were you able to resolve this issue?

**Comment by Ghusar** [comment]
@mssio Closing this issue for now. Feel free to reopen it again
