### ISSUE TITLE
Lost all my data.

### ISSUE THREAD

**Issue by michaelsearcy** [a85/POSTMan-Chrome-Extension#759]
Not sure how it happened but I lost all my data. I am always signed in using Google 2 factor authentication. I had a 3 month old backup dump, I am using now. I think you should build a feature that keeps all the data in a Google Drive folder.

**Comment by a85** [comment]
This issue has been fixed by Google in the latest version of Chrome. We now provide a backup service for free to individual users: http://blog.getpostman.com/2015/03/03/postman-2-0-with-sync-is-here/
