### ISSUE TITLE
Prior notification before deleting the data from Trash.

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#7590]
**Is your feature request related to a problem? Please describe.**
A prior notification before deleting the collections from the trash. So that one can recover before it gets deleted permanently from the trash.

**Additional context**
Collections get deleted after a certain interval of time as per the plan.
Users on Postman **Free license** can recover **one-day old collections**.
Users on Postman **Pro license** can recover collections up to **15-days.**
Users on Postman **Enterprise license** can recover collections up to **30-days.**

Prior notification will help to recover the collections from trash if the user has missed to recover it, within the specified interval of time.

**Comment by preethammavin** [comment]
@Swapnil-getpostman sending a notification for every element which is about to be permanently deleted would cause a large amount of noise in notifications.  But would look how we can enable this information to be conveyed to the user in a better format.

**Comment by Swapnil-getpostman** [comment]
@preethammavin Yes, it will cause noise in notifications. 
Just a suggestion, If we can provide the user with a checkbox in the settings tab to receive the notifications, then this will be completely the user's choice to receive notifications.
