### ISSUE TITLE
Keep syncing

### ISSUE THREAD

**Issue by drpiou** [a85/POSTMan-Chrome-Extension#7591]
**Describe the bug**
The app keeps syncing, ending up to use resources from the computer (constantly between 7-19% CPU usage).

**To Reproduce**
I don't know how to reproduce this error, I wish it didn't happened and I don't think that logging out is the correct solution.

**Expected behavior**
I expect the app to sync only when a changes is made, not constantly.

**Screenshots**
![Screenshot 2019-11-06 at 15 36 45](https://user-images.githubusercontent.com/474368/68307432-8476b080-00ab-11ea-8bcd-660edb1392d2.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.10.0
 - macOS Mojave 10.14.6

**Additional context**
Thanks :)

**Comment by cyrielle-hada** [comment]
@drpiou would you be able to tell us some more about the nature of collections? How many requests do they contain? As explained in the issue #6463 - we recently added a hard limit on syncing of examples with a large request body (5MB).

**Comment by preethammavin** [comment]
Closing the issue for now, do reopen the ticket with the above mentioned information for us get to the bottom of it.

**Comment by olopezdeveloper** [comment]
Same error here..
