### ISSUE TITLE
 collection runner CSV body json

### ISSUE THREAD

**Issue by iamdavid2** [a85/POSTMan-Chrome-Extension#7594]
**Describe the bug**
the request body is not the same as the preview , the preview shows "" , but the request body doesn't send " " 

**To Reproduce**
1. Create a new POST Request
2. In the body put some variables (read by CSV)
the first and the second columns contains number and the third column contains a string

![image](https://user-images.githubusercontent.com/7917477/68350909-dfba9a00-00cf-11ea-8ccc-8889e19dea2b.png)
3. Create a csv file

![image](https://user-images.githubusercontent.com/7917477/68350954-07a9fd80-00d0-11ea-87b5-3205b7cab1c0.png)

4. Click on Runner
the preview is ok, it shows the third values as string
![image](https://user-images.githubusercontent.com/7917477/68351172-a33b6e00-00d0-11ea-81fa-f373740a491a.png)

5. Run the test, and then check the request Body
the value is not a String , it doesn't have the "", in an API is not the same when you send "COURSE111" or COURSE111

![image](https://user-images.githubusercontent.com/7917477/68351255-e1d12880-00d0-11ea-82d7-707be973d5ef.png)

Postman for Windows
Version 6.0.10
win32 10.0.18362 / x64

**Comment by iamdavid2** [comment]
is not a issue

**Comment by simran0901** [comment]
@iamdavid2  why this is not an issue..m also facing the same issue..sorry if asking newbee question

**Comment by iamdavid2** [comment]
@simran0901 in the raw you can setup you string using "" for example 
![image](https://user-images.githubusercontent.com/7917477/69573352-ebdd9d00-0f93-11ea-9ee0-555444d24599.png)

**Comment by iamdavid2** [comment]
![image](https://user-images.githubusercontent.com/7917477/69573455-20e9ef80-0f94-11ea-8a11-965782c96612.png)
