### ISSUE TITLE
There was an error in evaluating the test script:  Error: sandbox: execution interrupted, bridge disconnecting.

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#7595]
I'm the Postman v7.10.0 native app on Linux.  When I submit requests against an API with a large response, I get the following error in the "Test Results" tab: "There was an error in evaluating the test script:  Error: sandbox: execution interrupted, bridge disconnecting."

Response info:
200OK
1051ms
8.77 MB

**Comment by shamasis** [comment]
This will need more info to reproduce. Can you provide details that would help us reproduce this?

**Comment by codenirvana** [comment]
We've have made significant improvements in our sandbox to handle large response payloads.
I hope this will be fixed after upgrading to the latest version of the app.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.
