### ISSUE TITLE
Show compressed body size

### ISSUE THREAD

**Issue by Eomm** [a85/POSTMan-Chrome-Extension#7596]
Hi,
the `Size:` field shows the amount of uncompressed payload:

![image](https://user-images.githubusercontent.com/11404065/68372810-e08c1400-0141-11ea-8229-afb26f2ef955.png)

And if I remove the response header (to avoid the uncompression of Postman) I get the size I'm interested:

![image](https://user-images.githubusercontent.com/11404065/68372943-17fac080-0142-11ea-96e3-b7800dc1a965.png)

Could we add a `Before uncompression` field?

![image](https://user-images.githubusercontent.com/11404065/68373008-3cef3380-0142-11ea-832e-173547d12aa7.png)

Thanks

Related to https://github.com/postmanlabs/postman-app-support/issues/5885

**Comment by MilosRandelovic** [comment]
+1

I've spent some time trying to make my server do gzip compression automatically, and it would be nice if Postman could help me verify the actual transfer size.

**Comment by thoughtworks200** [comment]
+1

**Comment by tareqdayya** [comment]
+1

**Comment by tafia** [comment]
+1

**Comment by jonasfrid** [comment]
+1

**Comment by vaibhavpacharya** [comment]
+1

**Comment by Samreay** [comment]
@shamasis - any movement on this?

**Comment by tamirs9876** [comment]
+1

**Comment by mathnogueira** [comment]
+1

**Comment by ElliotNB** [comment]
@shamasis  +1

**Comment by goriunov** [comment]
+1

**Comment by pedrotambo** [comment]
+1

**Comment by augustoicaro** [comment]
+1

**Comment by danielramireze** [comment]
+1

**Comment by lada** [comment]
+1

**Comment by wilsonssss** [comment]
+1

**Comment by goforgold** [comment]
+1

**Comment by s00pa** [comment]
+1

**Comment by dranitski** [comment]
+1

**Comment by alexkev** [comment]
+1

**Comment by raymondKelly** [comment]
+1

**Comment by MonsterMetroid** [comment]
+1

**Comment by juber-nunes** [comment]
2 1/2 years, any updates on this?

**Comment by okcthulhu** [comment]
Our team is considering switching to Insomnia for this exact reason. We need to know the uncompressed response size in order to test what's going on with API limitations from our providers. Would love to see a fix.

**Comment by kevinswiber** [comment]
> ***Note***
> This is not an official resolution.

A workaround I use is to either `console.log` the information I need or use the Postman visualizer.

Here's a script I drop in to the Tests tab to use the visualizer and inspect the body size:

```js
const template = `
<b>Response body size (bytes):</b>
<ul>
<li>Body size: {{bodySize}}</li>
<li>Content size: {{contentSize}}</li>
<li>Compression: {{compression}}</li>
</ul>
`;

const bodySize = pm.response.text().length;
const contentSize = pm.response.size().body;
const compression = bodySize - contentSize; // bytes saved

pm.visualizer.set(template, { bodySize, contentSize, compression })
```

You have to select the `Visualize` tab in the Response pane, and it looks something like this:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/78582/182684047-1b53461a-1665-4c64-be08-61650db5dee8.png">

**Comment by Albob** [comment]
@kevinswiber 
> ```js
> const template = `
> <b>Response body size (bytes):</b>
> <ul>
> <li>Body size: {{bodySize}}</li>
> <li>Content size: {{contentSize}}</li>
> <li>Compression: {{compression}}</li>
> </ul>
> `;
> 
> const bodySize = pm.response.text().length;
> const contentSize = pm.response.size().body;
> const compression = bodySize - contentSize; // bytes saved
> 
> pm.visualizer.set(template, { bodySize, contentSize, compression })
> ```

This actually gives me a negative compression:


![image](https://user-images.githubusercontent.com/1536632/186438888-16c3f717-9b7d-41d2-887e-88f54dfe7334.png)

This must be the difference between the raw text and the expanded/pretty JSON displayed. Or maybe you inverted body and content size ?

```js
const contentSize = pm.response.text().length;
const bodySize = pm.response.size().body;
```

Anyway, this is miles away of the real compressed size that I can read from Chrome: ~25KB instead of ~146KB

![image](https://user-images.githubusercontent.com/1536632/186440329-6513d9ef-61f7-49ae-8182-7aecfd3e3036.png)

**Comment by Albob** [comment]
And yeah +1 on this request 👍

**Comment by zhao1532072926** [comment]
+1

**Comment by kevinswiber** [comment]
@Albob There could be a number of reasons for this.  My first guess would be that the `Content-Length` header isn't matching the actual length of the response body.  This can happen when proxies, for example, modify the response body without modifying the value of the `Content-Length` header.  The compression value should never be less than zero.

Why is Chrome showing different results? That's an interesting one.  Check the `Accept-Encoding` request header in Postman and make sure it matches what you're seeing in Chrome.  Then check the `Content-Encoding` response header in both Postman and Chrome to make sure they match.

**Comment by yevhenii-username** [comment]
+1

**Comment by joebone** [comment]
seriously? I have a chunked transfer encoded gzip stream with no content length at all, and not even via the dev tools is this available? Calls to the proxy, sure. And in the console, all of the response headers, but the actual like to the body?
Body is more than 10 KB and can only be viewed in editor.  Except the uncompressed version is 140 megs, and printing it "pretty" isn't great.

Bad form, Peter! [[Hook reference for you younguns](https://i.imgflip.com/kckwh.jpg) 
Guess its back to curl again.. and not the windows one, which apparently doesn't support --compressed

wsl curl --compressed -so /dev/null http://www.whatsmyip.org/http-compression-test/ -w '%{size_download}'

**Comment by joebone** [comment]
what.

**Comment by wilbit** [comment]
+1

**Comment by Buyukcaglar** [comment]
Any updates on this feature?

**Comment by icedice** [comment]
I need this as well, annoying that we cannot see this out of the box.

**Comment by xiekeyi98** [comment]
+1,
I need this to investigate server-side performance issues and compare different compression methods( gzip , br , deflate,etc)

**Comment by nastassia-citian** [comment]
Anyone have any alternatives for calculating compressed response size?

**Comment by icedice** [comment]
> Anyone have any alternatives for calculating compressed response size? 

I solved it by running the traffic  through mitmproxy and checking the size there, it works but it's a bit convoluted for a basic task.

**Comment by Buyukcaglar** [comment]
> Anyone have any alternatives for calculating compressed response size?

Insomnia

**Comment by bcmcq** [comment]
+1 🙏

**Comment by bjaraszk** [comment]
+1

**Comment by nastassia-citian** [comment]
I ended up adding middleware to my routes to log the compressed / decompressed size. Cross checking with dev tools network tab, it seems pretty accurate. 

```js
const logDataSize = (data) => {
    console.warn(`res object size ${typeof data === 'object' ? '(compressed)' : '(decompressed)'}: `, Buffer.byteLength(JSON.stringify(data), 'utf8') / 1024 / 1024 + ' MB');
};

// Middleware function to log response size
app.use((req, res, next) => {
    const originalSend = res.send;

    if (req.app.get('env') === 'development') {
        res.send = function(data) {
            logDataSize(data);
            originalSend.call(this, data);
        };
    }

    next();
});
```

**Comment by Greg-Hyliion** [comment]
+1

**Comment by TheAustinG** [comment]
Do +1s even matter at this point? This issue is going on 4 years with no updates. I doubt this is even close to being on their roadmap. Super disappointing.

Anyway, +1 in case it actually does carry any weight lol

**Comment by Quezler** [comment]
+1

**Comment by yuenhy** [comment]
+1

**Comment by tapionx** [comment]
+1

**Comment by itsdax** [comment]
✨ +1 ✨

**Comment by gfrancomsft** [comment]
+1

**Comment by cocorossello** [comment]
+1

**Comment by alexanderb444** [comment]
+1

**Comment by Nabeelaron** [comment]
Any updates on the feature request ? @shamasis

**Comment by PDonoso-DMF** [comment]
+1

**Comment by Slepoyi** [comment]
Idk how this super helpful feature hasn't been implemented yet. +1

**Comment by SoftStoneDevelop** [comment]
+1

**Comment by robinknox** [comment]
+1

**Comment by parthverma1** [comment]
Hi, 
With version 11.8 ([Download Link](https://www.postman.com/downloads/)) of the app, we have improved the way we were calculating response sizes. You can now see both compressed and uncompressed body size for compressed responses. The size metric in the response section displays the actual number of bytes that were transferred over the network. 
<img width="350" alt="image" src="https://github.com/user-attachments/assets/cf038611-9319-4d69-9aa6-f6c42ba04070">


https://github.com/user-attachments/assets/c934fd0c-0400-4a00-bf8b-5d60e2c598c6
