### ISSUE TITLE
twitter menuitems point to @postmanclient instead of @getpostman

### ISSUE THREAD

**Issue by BdR76** [a85/POSTMan-Chrome-Extension#7601]
Not really a bug but the twitter menuitems point to the old twitter account @postmanclient instead of @getpostman (Postman v7.11.0 Windows)

two menu items in the GUI:
- Help > Twitter
- Settings (wrench icon) > @postmanclient

**Comment by harryi3t** [comment]
@BdR76 Thanks for reporting this issue. We will get these links fixed in the next release.

**Comment by kevin-postman** [comment]
@BdR76 This should now be resolved in the latest release, 7.12.
