### ISSUE TITLE
Textbox to add cookie to request does not appear

### ISSUE THREAD

**Issue by phil-hutchinson** [a85/POSTMan-Chrome-Extension#7603]
Description
Textbox to add cookie to request does not appear

To Reproduce

1. Start the Postman application
1. Click on the "Cookies" link below the Send button
1. Enter a domain (e.g. https://www.google.com) in the top edit box and click add
1. Select the added domain, and an "+ Add Cookie" button should appear
1. Verify that no textbox appears allowing entry of the cookie

Expected behavior
A textbox appears allowing the entry of a cookie for the selected domain

Screenshots
![image](https://user-images.githubusercontent.com/21108547/68409101-5f318300-013b-11ea-9fc5-09e8d5c2c5bb.png)

App information
 - App Type: Native (x64)
 - Postman Version: 7.11.0
 - OS: Windows

Additional context
Fresh install yesterday (7.10?) and I encountered the problem. Got the update to 7.11 today but this did not resolve the issue.

**Comment by codenirvana** [comment]
Note to self: this is failing because the protocol is included with the domain name.

This field only accepts the hostname without `protocol` and `port`.
Set just `www.google.com` or `localhost` instead of `https://google.com`/ `localhost:8080`.

Removing the protocol will unblock this issue. cc. @coditva

**Comment by klassic93** [comment]
removing the protocol also doesn`t work

**Comment by ElSamhaa** [comment]
also domains with ports e.g `localhost:3000` produce the same issue.

**Comment by jeffepic** [comment]
Seeing this issue on Mac 7.26.0

**Comment by virtualdxs** [comment]
Same on Arch Linux - reproduced with protocol; removing protocol fixes it. Sounds like it just needs an error message.

**Comment by danielsss** [comment]
Same on Mac OS `127.0.0.1:8080` with postman v7.27.1

**Comment by arafay993** [comment]
facing the same issue when added domain name `localhost:8000` and I am using Linux mint. Anyone know how to solve it ?

**Comment by klassic93** [comment]
try to write just localhost when add your domain

**Comment by imwillhang** [comment]
Nope still doesn't work

**Comment by DannyDainton** [comment]
Hey folks

Is anyone still having issues with this after removing the protocol or just using `localhost` without the port?

**Comment by timbochamp** [comment]
Text boxes to add a cookie for localhost with port suffixes (`localhost:####`) and for `https://` prefixes, although we strip out these suffixes and prefixes respectively for the valid input mentioned above. This is both on Postman for Web and on the Postman version 8 app as of writing this.

I'm going to close out this issue, but please feel free to reopen if there's still problems occurring with this issue!
