### ISSUE TITLE
$randomSecondaryAddress Dynamic Variable not working

### ISSUE THREAD

**Issue by nathanbAL** [a85/POSTMan-Chrome-Extension#7604]
**Describe the bug**
I'm using the dynamic variable $randomSecondaryAddress in a request as a string however my response is just printing "addressSecondLine": "{{$randomSecondaryAddress}}",

**To Reproduce**
1. Go to a POST request that utilizes an address field 
2. Utilize {{$randomSecondaryAddress}} in request, example "addressSecondLine": "{{$randomSecondaryAddress}}"
3. Send POST request
4. Secondary address does not get set

**Expected behavior**
I expected a dynamic secondary address e.g. suite 100, apt. A2, etc.

**Screenshots**
n/a

**App information (please complete the following information):**
 
 - Version 7.10.0 (7.10.0)
 - OS: macOS

**Additional context**
n/a

**Comment by DannyDainton** [comment]
Hey @nathanbAL,

I'm not sure where you saw that it was a variable to use in the application but It's not one that we have listed anywhere.

The documentation:

https://learning.getpostman.com/docs/postman/scripts/postman-sandbox-api-reference/#phone-address-and-location

Auto Complete view in the app:
<img width="428" alt="Screenshot 2019-11-07 at 22 48 00" src="https://user-images.githubusercontent.com/17089546/68434468-e66d0e00-01b0-11ea-9579-fdc821e49a7f.png">

The main [fakerJS ](https://github.com/marak/faker.js#api-methods) module does list this as an option but the Implementation in Postman is only a sub-set of the full module

**Comment by nathanbAL** [comment]
@DannyDainton I had pulled it from this list and I swear it used to work. https://postman-quick-reference-guide.readthedocs.io/en/latest/dynamic-variables.html

**Comment by shamasis** [comment]
It could have worked during beta and canary stages.

**Comment by coditva** [comment]
@nathanbAL you're right that it used to work, but that was only in early development releases where we were testing out ways to implement dynamic variables in the App. It was removed in the stable release along with some others which we did not intend to support.

Hope that solves your question; closing this issue.
