### ISSUE TITLE
Environment variable replaced with random characters

### ISSUE THREAD

**Issue by spatil-scandilabs** [a85/POSTMan-Chrome-Extension#7605]
Environment variables is replaced with some (http:///%7B%7BURL%7D%7D/) random characters in monitoring tool and eventually all the requests are getting failed. 
Although if I ran the same correction from the tool, its runs successfully. 
There is some issue with the monitoring tool.

**Comment by vvs11** [comment]
Hey @spatil-scandilabs, Thanks for writing in!
Could you provide us with some more details about the issue that you're facing? Also, it'd be great if you can share the steps to reproduce.

**Comment by spatil-scandilabs** [comment]
Hey, 
So I set project url as a environment/ global variable: 
E.g.: URL is: https://www.google.com
Now I set this URL in a environment/global variable as below: 
VARIABLE: URL
INITIAL VALUE: https://www.google.com
CURRENT VALUE: https://www.google.com 

If I want to use this variable in the api request, I have to set it like: 
{{URL}}/<following path>

So far, all good. 
If I run this from the Collection Runner, it works perfectly fine. 

But if I set up monitoring for the same then it fails, because in the variables {{URL}} is replaced with (%7B%7BURL%7D%7D/) these characters ans hence I seen error in the log like. 
Please check the error log snippet below: 
`2 | 16:04:50 | Generate Token
-- | -- | --
3 | 16:04:50 | POST {{URL}}/api/authtoken
4 | 16:04:52 | Error: Invalid URI "http:///%7B%7BURL%7D%7D/api/authtoken"
5 | 16:04:52 | JSONError: Unexpected token u in JSON at position 0
6 | 16:04:52 | JSONError: Unexpected token u in JSON at position 0`

Hope you are getting this, if not then please let me know. 

Thanks!

**Comment by shivam-postman** [comment]
Hi @spatil-scandilabs, the issue should've been fixed now. It'd be great if you could confirm.
