### ISSUE TITLE
Cyrillic characters in cookies break requests

### ISSUE THREAD

**Issue by alex-bolenok-centralreach** [a85/POSTMan-Chrome-Extension#7606]
**Describe the bug**
Postman is unable to send cookies with Cyrillic characters in the value

**To Reproduce**
1. Create a new GET request to https://api.adviceslip.com/advice
1. Click on Cookies, the Manage Cookies dialog appears
1. Click on "Type a domain name", type `adviceslip.com`
1. Click on Add
1. Scroll down to adviceslip.com, click on Add Cookie
1. Paste this text into the memo box: `cyrillic-cookie=тест; path=/; domain=.adviceslip.com;`
1. Click on Save
1. Close the Manage Cookies dialog
1. Open View / Show Postman Console
1. Click on Send

**Expected behavior**
* The request is sent
* The JSON output is shown in the Output / Body tab
* There are no errors in the Postman console

**Actual behavior**
* The request is not being sent
* The error is shown in the Output tab:

        Could not get any response
        There was an error connecting to https://api.adviceslip.com/advice.
        Why this might have happened:
        The server couldn't send a response:
        Ensure that the backend is working properly
        Self-signed SSL certificates are being blocked:
        Fix this by turning off 'SSL certificate verification' in Settings > General
        Proxy configured incorrectly
        Ensure that proxy is configured correctly in Settings > Proxy
        Request timeout:
        Change request timeout in Settings > General

* An error is shown in the Postman console:

        GET https://api.adviceslip.com/advice
        Error: Invalid character in header content ["Cookie"]

**App information (please complete the following information):**

    Postman for Windows
    Version 7.11.0
    win32 10.0.14393 / x64

**Additional context**
This is a huge problem when the Interceptor is running and the browser keeps sending Cyrillic cookies

**Comment by mccannt** [comment]
Thanks for logging this issue @alex-bolenok-centralreach 
I was able to replicate the issue locally and we are investigating this. We will follow up when we have additional information.

**Comment by alex-bolenok-centralreach** [comment]
@mccannt any news on this? Thanks!

**Comment by mccannt** [comment]
Apologies for the late response @alex-bolenok-centralreach 
This is actively being worked on, so I anticipate we should be able to release this fix shortly. 
Appreciate your patience while we fix this up.

**Comment by mohitranka** [comment]
@alex-bolenok-centralreach The fix is now is available in the latest app versions 7, 8 & web.

**Comment by alex-bolenok-centralreach** [comment]
@mohitranka @mccannt this still reproduces as of v9.8.3

**Comment by msimko81** [comment]
@mohitranka This still reproduces on 7.36.5 (latest/stable snap version).
