### ISSUE TITLE
Editors in postman not scrollable when you increase the editor size by dragging 'Response' and then select and scroll to bottom

### ISSUE THREAD

**Issue by grgakshay** [a85/POSTMan-Chrome-Extension#7609]
**Describe the bug**
Editors in postman not scrollable when you increase the editor size by dragging 'Response' and then select some text in the editor and try to scroll to the bottom.

**To Reproduce**
1. Past large data in the editor.
2. Increase the editor size by dragging the 'Response' section to the bottom.
2. Select some text through mouse and try to drag the selection till end
3. The user can't scroll to the bottom and only the visible portion is selected through the mouse.

**Expected behavior**
The editor should be scrollable to the bottom upon selection.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - Native App
 - Postman Version v 7.10.0
 - OS: MacOS Mojave v10.14.5

**Comment by numaanashraf** [comment]
@grgakshay Could you send us a screen recording for this? We are unable to replicate this.

**Comment by grgakshay** [comment]
@numaanashraf Please find the recording below :)
https://drive.google.com/file/d/1rJ_GjMaDykzZ7u6Coc8AfHvTyu6g4sAL/view?usp=sharing

**Comment by kamalaknn** [comment]
@grgakshay It looks like in this case the bottom border of the editor is well beyond the bottom border of the Postman application. That is why dragging beyond the bottom border of the Postman app is not scrolling the editor immediately since it is still within the height of the editor.

**Comment by kamalaknn** [comment]
@grgakshay This should be addressed with #5903
