### ISSUE TITLE
Postman Monitor Not Completing Report Execution, Stuck on 'Loading'

### ISSUE THREAD

**Issue by labossieresr** [a85/POSTMan-Chrome-Extension#7611]
I have a collection that runs daily in PM Monitor and when I go to load the page it never completes loading. In the "Region" field it states 'Loading...' with an active spinning wheel (further indicating it is still loading). It was working fine for the past number of months and then it just started this new behavior. The graph of daily runs is no longer displayed (cause still loading).  Refreshing via the browser or via the Refresh button within PM Monitor does not change things. 

1. Go to 'https://gold-water-1172.postman.co/monitors/1e987c9d-0f60-40b0-b766-70aa3b470841?workspace=d048272d-7d39-4974-9c5d-221f056bef05'
2. See how it never completes loading
3. Refreshing via the browser or via the Refresh button within the PM Monitor screen does not change the behavior.

Like other PM monitors I have running, I expect the web page to complete loading and display the graph with related detailed data below.

This is running in Postman's environment so I can't speak to what the Postman version or OS is. I will say that I am 'viewing' with Chrome Version 78.0.3904.97 (Official Build) (64-bit).

**Comment by shivam-postman** [comment]
Hello @labossieresr , the fix will be out this week. Meanwhile, you can try the following steps to display the graph correctly:

1. Go to your workspace monitors.
2. Select a monitor, different from the one you want to view.
3. Refresh the page.
4. Go to your workspace monitors and select the monitor you wanted to view.

Do let us know if this doesn't solve the problem.

**Comment by labossieresr** [comment]
It did work as described!  Unfortunately, it only works this way that I can
tell. Meaning I can't even take the URL copy/paste into another browser and
have it work. I MUST follow your procedure for it to work.So I don't feel
it solved the problem as it seems inappropriate to require me to do it
every time. I view it more of a workaround or a troubleshooting step to
help you solve it the right way.

Thx!

**Comment by shivam-postman** [comment]
I agree, this is only a temporary workaround. The actual fix would be available this week itself. Apologies for the inconvenience.

**Comment by shivam-postman** [comment]
@labossieresr the fix is out and the page should be loading fine now. Can you please verify?

**Comment by labossieresr** [comment]
It works if I open a new tab but not for the one that I had previously
opened (same browser session) . In that case, it actually doesn't work when
trying to switch between monitors now.(...loading). having said that, from
my perspective I feel I am good as it worked when loading in a new tab.

Thank you,
Steve

**Comment by shivam-postman** [comment]
@labossieresr Can you please confirm that the old browser session you're referring to, was created ~24 hours ago or before?

**Comment by ArjunSingh-PM** [comment]
This issue is resolved.
