### ISSUE TITLE
Clear tokens button

### ISSUE THREAD

**Issue by fabiocastilhos** [a85/POSTMan-Chrome-Extension#7612]
It's possible to add a "Clear all" tokens button so I don't have to delete the expired tokens one by one?

Something like this:
![image](https://user-images.githubusercontent.com/730416/68476798-7ee3ac80-020a-11ea-9c6d-2fda509fc537.png)

**Comment by lmsurpre** [comment]
In my version (7.26) I found this Delete dropdown under the Manage Access Tokens link with options for deleting all tokens or deleting just the expired ones.
![image](https://user-images.githubusercontent.com/5478798/85450826-35f92200-b567-11ea-8936-ff51aa9e950e.png)

I think this issue can be closed.

**Comment by arlemi** [comment]
Good catch @lmsurpre , we've released that feature in 7.26 but forgot to close this one!
