### ISSUE TITLE
Support silent installation on Windows

### ISSUE THREAD

**Issue by anurag246** [a85/POSTMan-Chrome-Extension#7615]
In our corporate the Software Installation and Support team need to install the software on developers workstations in background, so that their work is not interrupted. Right now, all I could find was a GUI based installation or upgrade interface, and was looking for the Silent Install Parameters so that we can silently install the product without GUI

**Comment by vizion316** [comment]
I created a batch script and ran through SCCM. One line:

"Postman-win64-7.14.0-Setup.exe" --silent

Funny thing is there is nothing about this on their site. It's the same switch as the uninstaller. It suppresses the auto start of the app as well. Hope this helps anyone else that has this nightmare.

**Comment by aimar115** [comment]
Got my sccm deployment working following this guide: https://www.prajwaldesai.com/deploy-microsoft-teams-using-sccm/

both install and uninstall are working.

**Comment by vasilvestre** [comment]
This is actually more than needed https://github.com/microsoft/winget-pkgs/pull/894
Non-support of silent install reduce possible future installs.

**Comment by arlemi** [comment]
Closing this to gather all feedback in #4576 which talks about adding MSI installer that would support SCCM, silent install, and install for all users.

**Comment by ghost** [comment]
Thank you for looking into a silent .msi. installer. For enterprises, by far, the best way for us to install on our systems regardless of the deployment mechanism.
