### ISSUE TITLE
Learning Center - Billing Links throwing 404s

### ISSUE THREAD

**Issue by Andy-APIs** [a85/POSTMan-Chrome-Extension#7616]
Learning Center - Managing Pro Billing pages are throwing 404s.

**To Reproduce**
In Learning Center > Managing your Billing section > all links under `How to get a copy of an existing invoice` section throw a 404. Each link appears to be redirecting to same page.
See: https://learning.getpostman.com/docs/postman-pro/managing-pro/managing-your-billing/#how-to-get-a-copy-of-an-existing-invoice

Links point to: https://learning.getpostman.com/docs/postman_pro/managing-pro/changing-your-plan 

**App information (please complete the following information):**
Learning Center Docs

**Comment by SueSmith** [comment]
I believe this will be fixed by billing doc updates by @claireriley about to be pushed to prod https://github.com/postmanlabs/postman-docs/pull/2056

**Comment by DannyDainton** [comment]
Hey @Andy-GetPostman 

I believe that this has been fixed so I'm going to close it out - If that's not, we can open it back up again :D
