### ISSUE TITLE
Unable to install the latest version of Postman 7.11.0

### ISSUE THREAD

**Issue by Akhil-WebDev** [a85/POSTMan-Chrome-Extension#7620]
I just downloaded the new .exe file from "https://www.getpostman.com/downloads/" for my respective system (Windows 7), the installation throws an error on trying to install.
![Postman](https://user-images.githubusercontent.com/39221179/68583096-58d83980-04a2-11ea-91a2-5da099655998.JPG)

**Comment by numaanashraf** [comment]
Thanks for reporting this @Akhil-WebDev. We are tracking this at #6707

**Comment by numaanashraf** [comment]
Duplicate of #6707
