### ISSUE TITLE
POST behaviour vs GET behaviour

### ISSUE THREAD

**Issue by jrmore** [a85/POSTMan-Chrome-Extension#7621]
**Describe the bug**
The error behaviour of POST and GET appear to be different based on the contents of the root component of the URL.

**To Reproduce**
Steps to reproduce the behaviour:
1. `GET 192.168.2.22:8000//api/rebates/v1/getRebate?clientID=zz@zz.zz` works as expected as does `GET 192.168.2.22:8000/api/rebates/v1/getRebate?clientID=zz@zz.zz` with the only difference being the double vs single backslash after :8000
2. `POST http://192.168.2.22:8000//api/rebates/v1/processRebate` will not work and invokes a 405 Method Not Allowed error but the same `POST http://192.168.2.22:8000/api/rebates/v1/processRebate` which removes the extra backslash after the :8000 behaves as expected

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type Native App
 - Postman v7.10.0
 -  Operating System: Linux Mint 19.2
            Kernel: Linux 4.15.0-66-generic
      Architecture: x86-64

**Additional context**
Going against a server written in go using the GorillaMux http library
This is not a major issue it was just an irritating and took a while to investigate.

**Comment by saswatds** [comment]
Hi @jrmore we have not been able reproduce such a behaviour. All urls are parsed in the same manner regardless of the Method. So most likely this is an issue with a server while processing the request. Closing this issue now as no other user has reported about such a behaviour.
