### ISSUE TITLE
How to send a POST request of base64 string from body.

### ISSUE THREAD

**Issue by anishvarma01** [a85/POSTMan-Chrome-Extension#7622]
I have a fiddler post request. In that the body is base64 string and there is an header "Fiddler-Encoding: base64". 

Can i make same request through postman? I tried it but i not able to decode the string. Does postman has this feature like fiddler?

**Comment by vikiCoder** [comment]
Hi @anishvarma01,

We do not support changing request body through scripts at the moment. A possible workaround for your use case is to use environment variables and keep base64 request body in the a variable. Then decode the base64 string from the environment in the pre-request script and use it as the request body. See the below screenshot for an example:

**Request body:**
![image](https://user-images.githubusercontent.com/16588032/77036919-2dc4a000-69d6-11ea-9217-3f017348592a.png)

**Pre-request script:**
![image](https://user-images.githubusercontent.com/16588032/77036994-4df45f00-69d6-11ea-884c-18ba5fc03170.png)

**Environment variables:**
![image](https://user-images.githubusercontent.com/16588032/77037056-711f0e80-69d6-11ea-9a39-4dd5d20d6b8b.png)

Closing this issue for now. If you are interested in mutating request body from pre-request script, we are tracking it in https://github.com/postmanlabs/postman-app-support/issues/4808.
