### ISSUE TITLE
Postman getting stuck very frequently

### ISSUE THREAD

**Issue by sriharikss** [a85/POSTMan-Chrome-Extension#7624]
**Describe the bug**
When I am running a collection manually which has around 15 - 20 steps, postman is getting stuck. Once I click on the tab/step, it is taking time to open the same.

**To Reproduce**
1. Go to any postman collection which has more than 15 steps
2. Run the steps continuously and click on next step

**Expected behavior**
Tool should not be hunged

**Screenshots**
N.A

**App information (please complete the following information):**
 - App Type : Desktop App
 - Postman Version : 7.11.0
 - OS: Win10 64 bit

**Additional context**
Though I clear the history, this issue occurs. Is there anyway to increase the memory/ clear cache for the postman.

**Comment by kamalaknn** [comment]
Hey @sriharikss 

Do you see any actions other than opening a request in a tab slowing down? Also when you run 15-20 steps are you referring to sending individual requests in Postman App or running the collection in Collection Runner.

If you could give a screen-recording that will be useful.
