### ISSUE TITLE
Why do i get a excel file named response.xls by postman,but i get a normal excel file from the browser address

### ISSUE THREAD

**Issue by xiongxinxin** [a85/POSTMan-Chrome-Extension#7625]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by harryi3t** [comment]
@xiongxinxin We need the template (description, steps to reproduce, expected behavior, screenshots, app & OS info, etc) to be filled in order to triage the issue.
