### ISSUE TITLE
Add ability to share environments externally

### ISSUE THREAD

**Issue by Millais** [a85/POSTMan-Chrome-Extension#7629]
Hello,

I'm currently working with Postman to rollout the Enterprise license at PayPal. The vision is that Postman is a standard part of the software package here.

In our teams we would like the ability to share both collections _and_ environments externally with developers.

Today Postman offers the ability to share a collection via a link:

![Screenshot 2019-11-12 at 15 32 25](https://user-images.githubusercontent.com/7149113/68685299-d747e080-0561-11ea-912f-f175ffdb2848.png)

However, there is no option to embed the environment as part of this link. This means that when we work with external developers and partners, we are required to share the environment we set up for them using a different route – manually exporting and sharing via email, versus a link. There's no common method to share these individually or both together via a single link.

Many thanks,
Patrick

**Comment by sankalp0o** [comment]
@Millais Did you mean sharing it publicly or in a closed group?

**Comment by Millais** [comment]
@sankalp0o Sharing it publicly.

**Comment by gitThingsDone** [comment]
@Millais You can now create a public workspace and add an environment there to share it publicly. 
https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/#creating-a-public-workspace
Any environment you share to a public workspace will also get a public link like https://www.postman.com/postman/workspace/postman-public-workspace/environment/5922408-6d01dd05-b174-4ac9-9741-56d561fe7bca

**Comment by sankalp0o** [comment]
Hey Patrick, I hope that you've had a chance to try out public workspaces. Do they solve your use case of sharing environments publicly?

I'm closing this ticket, but please reach out if you can think of any way we can make this experience better for you and your collaborators!
