### ISSUE TITLE
Add ability to update current environment variable only

### ISSUE THREAD

**Issue by Millais** [a85/POSTMan-Chrome-Extension#7631]
Hello,

I'm currently working with Postman to rollout the Enterprise license at PayPal. The vision is that Postman is a standard part of the software package here.

Leading on from @rkeet's comment on #5173, we need the ability to only update the _current_ environment variable in Postman. In a collaborative team environment – where there are multiple team members using the same environment – pre/post scripts will regularly mutate environments with transactional (ephemeral) values.

As team members will be using the shared environment in parallel, the transactional variables become out of sync between different users. This is because `.setEnvironmentVariable()` in pre/post scripts will update the _initial_ value. This gets synced across the team environment. This then causes issues when team members make a sequence of API requests with variables that no longer belong to them.

The ability to only update the current value will mean that team members can run a sequence of API requests with local _current_ values without worrying about side effects from the team.

Many thanks,
Patrick

**Comment by harryi3t** [comment]
@Millais Updating the environment values from the pre/post script will always update the `current value`.
It will also update the initial value if the setting `Automatically persist variable values` is turned on. If you do not want the initial value to be updated automatically, please make sure the setting is turned off.

![image](https://user-images.githubusercontent.com/5207331/68732221-b2eb1300-05f8-11ea-82d6-bbe3d76d227f.png)

cc @codenirvana

**Comment by Millais** [comment]
@harryi3t How can we turn this off on a team level?

In a shared/collaborative environment we would like each team member to have this disabled so the environments don't get accidentally modified.

**Comment by harryi3t** [comment]
@Millais Right now this is not supported but we are already tacking a feature request for this https://github.com/postmanlabs/postman-app-support/issues/6852.
You can subscribe to this thread for future updates.
