### ISSUE TITLE
Keepalive TCP packet not being sent

### ISSUE THREAD

**Issue by renansph** [a85/POSTMan-Chrome-Extension#7632]
Bugs description:
Using Postman desktop, when i send a POST request that take a long to process on server i don't receive the asnwer. The same doesn't happen on Postman Chrome version. I've debugged with Wireshark and noticed that the desktop client is not sending keep alive TCP packets. The Postman Chrome version is sending normally. I don't need to set any header since im using HTTP 1.1.

Steps to reproduce the behavior (desktop client):
1. Desktop client configs: 
![postman desktop configs - print7](https://user-images.githubusercontent.com/37335651/68705053-285cd200-056c-11ea-9b86-fcd66db1250b.jpg)

2. Desktop client version:
![postman desktop version - print 8](https://user-images.githubusercontent.com/37335651/68705104-3874b180-056c-11ea-8bd8-e8d39d8efd65.jpg)

3. Post request and headers:
![postman desktop request and headers - print 9](https://user-images.githubusercontent.com/37335651/68705303-91444a00-056c-11ea-9aa6-439cfeadc86d.jpg)

4. Post request and body:
![postman chrome request and body - print 10](https://user-images.githubusercontent.com/37335651/68705437-d7011280-056c-11ea-88d3-9b7d9fece58a.jpg)

5. Server side Wireshark flow:
- Server receive request.
- No keep alive packet is received.
- Server finish processing after a few seconds e send ok (200) response to the client.
![postman desktop wireshark server flow - print 11](https://user-images.githubusercontent.com/37335651/68706366-770b6b80-056e-11ea-8405-b2e069169a13.jpg)

6. Client side Wireshark - request sent without any response (even server sending 200 on step 5):
![postman desktop wireshark client flow - print 12](https://user-images.githubusercontent.com/37335651/68706789-424be400-056f-11ea-8800-28845867290e.jpg)

Expected behavior (Chrome client that seens to be working correctly):
1. Chrome client configs:
![postman chrome configs - print1](https://user-images.githubusercontent.com/37335651/68708486-95736600-0572-11ea-8ebb-9e48d7b1db9b.jpg)

2. Chrome client version:
![postman chrome version - print 2](https://user-images.githubusercontent.com/37335651/68708512-a1f7be80-0572-11ea-9e28-526c6edf6857.jpg)

3. Post request and headers:
![postman chrome request and headers - print 3](https://user-images.githubusercontent.com/37335651/68708670-f602a300-0572-11ea-916a-1919990a3dd4.jpg)

4. Post request and body:
![postman chrome request and body - print 4](https://user-images.githubusercontent.com/37335651/68708738-16326200-0573-11ea-88a0-771c0626d753.jpg)

5.Client Wireshark flow (notice the keep alive packets):
![postman chrome wireshark client flow - print 5](https://user-images.githubusercontent.com/37335651/68708784-3104d680-0573-11ea-8289-c8997f8597a8.jpg)

6.Server Wireshark flow (notice the keep alive packets):
![postman chrome wireshark server flow - print 6](https://user-images.githubusercontent.com/37335651/68708816-3eba5c00-0573-11ea-8f68-68aeb619ba41.jpg)

**Comment by shamasis** [comment]
Hmm. That’s odd. As far as I know, keep alive sockets are sent by default. Let me loop in @codenirvana to check if something’s changed here or if there are any caveats.

**Comment by codenirvana** [comment]
@renansph That's odd. The native app by default tries to establish a keep-alive connection (unless there's a `connection` header set).

Are you getting no response in the native app (is it getting timed out)?
Is it possible to share the endpoint publicly? If not can you send this request using `curl` with `-v` flag and share the verbose logs (without sensitive information).

**Comment by renansph** [comment]
Sure, ill provid it.

**Comment by renansph** [comment]
> @renansph That's odd. The native app by default tries to establish a keep-alive connection (unless there's a `connection` header set).
> 
> Are you getting no response in the native app (is it getting timed out)?

Yes, i get no response. He keep waiting for the response and no error or timeout message is shown.

> Is it possible to share the endpoint publicly? If not can you send this request using `curl` with `-v` flag and share the verbose logs (without sensitive information).

Sure, ill provide it.

**Comment by renansph** [comment]
> @renansph That's odd. The native app by default tries to establish a keep-alive connection (unless there's a `connection` header set).
> 
> Are you getting no response in the native app (is it getting timed out)?
> Is it possible to share the endpoint publicly? If not can you send this request using `curl` with `-v` flag and share the verbose logs (without sensitive information).

Hi. I set up an ending point to simulate the issue. Just send a **GET** request to URL **http://191.235.92.114/checkserver/**

It'll take 300 seconds to return the response, so please be a little patient if calling the request from Postman Chrome extension. The desktop version will never return any response as expected to reproduce the issue.

Expected response:
```
{
    "hasErrors": false,
    "message": "",
    "objectResult": {
        "data": "ok"
    }
}
```

**Comment by renansph** [comment]
Hi. I have some updates. I figured out that this is a problem with the Azure network as described [here](https://carsonip.me/posts/azure-tcp-idle-timeout-tcp-keepalive-python/). TCP connection actually don't need to send keep alive packets to keep the connection open.  What happen is that after 4 minutes idle the TCP connections is closed by Azure NAT but no reset packet (RST) is sent neither to the server nor to the client. Both sides still think the TCP connection is open. Ppl say this is a behavior of Azure load balancer, but i'm not using it, its a normal NAT network, so i think this is a general behavior of Azure NAT. The solution is described on the same link, that is enable the keep alive packets on the server's OS for a idle timeout less than 4 minutes. If someone is having the same problem and using load balancer, i heard that Azure now have an option to increase the timeout or enable the TCP RST. Anyway, thanks everyone for the support.

**Comment by vvs11** [comment]
Thanks @renansph for reaching out to us. Let us know if you face any issues in the future
