### ISSUE TITLE
Eliminate the need for escaping in cURL commands

### ISSUE THREAD

**Issue by happycappie** [a85/POSTMan-Chrome-Extension#7633]
If Postman could use single quotes to surround the json blob when it generates the curl command, that would eliminate the need for all the escaping in the generated examples/commands. Is this currently possible or would this be a feature request?

Also, should I be posting this here in Git or on Community (https://community.getpostman.com/t/eliminate-the-need-for-escaping-in-curl-commands/8972)? 

thanks

**Comment by Raja-Simha** [comment]
@conradpronto Thank you for your feedback. In general, if you think your question could be answered by the wider community, our community page is a great resource. You can report bugs and feature requests on Github. We do keep an eye on both Github and our discourse pages.

**Comment by shreys7** [comment]
Hey, @conradpronto In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'New Code Generation Mode' flag enabled in Postman's global settings.

This particular problem has been solved in the new codegen mode.
![Screenshot 2020-01-02 at 1 40 19 PM](https://user-images.githubusercontent.com/20665864/71657369-90a68380-2d65-11ea-8357-82e75b7e3b51.png)
Feel free to comment if you have any more suggestions.

**Comment by happycappie** [comment]
That sounds great.  How to update to 7.2.1?  Current response when trying to do so:  You are up to date! Postman v7.14.0 is the latest version

**Comment by shreys7** [comment]
Head over to the Settings icon on the top right -> Settings -> Update. Here you can check for updates and download the latest update if required. Closing this for now.

**Comment by happycappie** [comment]
Yes, I am aware of that. The point is that the version that was being downloaded is not the newer version that is covered in this ticket.

On May 4, 2020, at 03:18, Shrey Shah <notifications@github.com> wrote:

﻿

Head over to the gear icon on the top right -> Settings -> Update. Here you can check for updates and download the latest update if required. Closing this for now.
