### ISSUE TITLE
Github backup integration does not list all repositories

### ISSUE THREAD

**Issue by tobyhede** [a85/POSTMan-Chrome-Extension#7634]
**Describe the bug**
When I attempt to create a Github backup, the  integration does not list all repositories in the pull-down menu. In my case it cuts off at repos starting with the letter "m"

We have 499 repositories, so I assume there is some filtering or limit happening.

**To Reproduce**
1. Go to Github Integration
2. Add a personal token 
3. Open the "Choose Repository" select dropdown
4. Repository List is incomplete.

**Expected behavior**
I expect the list of repositories to show all the repositories.

**Screenshots**
<img width="427" alt="Screen Shot 2019-11-13 at 3 49 17 pm" src="https://user-images.githubusercontent.com/28390/68734118-4807ff00-062d-11ea-8da7-fa5a6c294586.png">

**Comment by gimlidc** [comment]
Same issue here - unable to integrate repo from <ec.*>

**Comment by Shimmi** [comment]
I did a little dig in. Seems there is a hardcoded pagination to fetch 10 pages each containing 30 repositories. Given this, the Postman really lists only the first 300 repositories.

The pagination mechanism shall be fixed or at least added the ability to specify the repository URL manually.

This is a total blocker for us.
![image](https://user-images.githubusercontent.com/3158339/76947610-2a61e380-6906-11ea-9ebc-33cd91db341d.png)

**Comment by abhijitkane** [comment]
@Shimmi We're prioritising this - I'll let you know as soon as we have an update.

**Comment by Atishay4294** [comment]
Our team has implemented a fix to bump the repository fetching limit from 300 to 1000. This is expected to go live early next week.
We'll keep you posted on the release.

@gimlidc @Shimmi - We'd like to use this opportunity to understand how many repositories do you have? Such inputs will eventually allow us to plan a solution that can take care of a larger number of repositories in the future(no ETA yet).

Stay safe and have a good day. :)

**Comment by Atishay4294** [comment]
@gimlidc @Shimmi @tobyhede - We've bumped the fetching limit to 1000 and it is live.
Can you review and see if this solves the problem for you?

Leave a +1 here to acknowledge :)

**Comment by Shimmi** [comment]
Hi @Atishay4294 ,
That is great news! Thank you!

We are reviewing it. Will let you know once we successfully test it.

Jiri

**Comment by tobyhede** [comment]
Awesome, thanks!

**Comment by Atishay4294** [comment]
@tobyhede - Can we close this issue if it works for you?

**Comment by Atishay4294** [comment]
Closing this issue for now.
Feel free to reopen if you run into problems with GitHub repositories in the drop-down menu.

**Comment by ravikantdos** [comment]
For me, this issue is still there.
As a workaround, I gave my repository name starting with 'A'.
Because hardly it was listing the first 30 repositories.

**Comment by shashankawasthi88** [comment]
@ravikantdos can you post a screen recording for the same?  I am not able to reproduce the same at my end.

**Comment by ravikantdos** [comment]
Not sure about recording or screen shot... Because that for my live project... What I can do I will get the console log and share with you. Additionally if will try to create more repository for my personal one and try if it's the same issue  then I can share with you.

**Comment by ravikantdos** [comment]
@shashankawasthi88 From console log I could find - "7index.js:3757 Could not find on l. Missing or invalid parameter." 
I am working with 300+ Repos.

**Comment by GerkinDev** [comment]
Using latest snap version of postman, it fetches only 100 repos.

![image](https://user-images.githubusercontent.com/8212504/127899471-6d9ddf46-0dbf-4849-ad05-c6b8fd8a9b6d.png)

**Comment by vinitshahdeo** [comment]
@GerkinDev Thanks for reporting this. We have shipped out Postman `v8.9.1` on [Snap store](https://snapcraft.io/postman) today. Can you please upgrade to the latest version and try out the same flow?

**Comment by GerkinDev** [comment]
> @GerkinDev Thanks for reporting this. We have shipped out Postman `v8.9.1` on [Snap store](https://snapcraft.io/postman) today. Can you please upgrade to the latest version and try out the same flow?

I can confirm this works. Thank you!

**Comment by manojrana-nytimes** [comment]
Hi, Any reason for bumping to 1000 LIMIT instead fixing by proper pagination because Our Org have more than 1000 Repos. This fix doesnt help us.

**Comment by Pipe-Runner** [comment]
> Hi, Any reason for bumping to 1000 LIMIT instead fixing by proper pagination because Our Org have more than 1000 Repos. This fix doesnt help us.

Yes, we are adding support for paginated API in the dropdown. It is being worked on as we speak. Sorry for the inconvenience.

**Comment by manojrana-nytimes** [comment]
> > Hi, Any reason for bumping to 1000 LIMIT instead fixing by proper pagination because Our Org have more than 1000 Repos. This fix doesnt help us.
> 
> Yes, we are adding support for paginated API in the dropdown. It is being worked on as we speak. Sorry for the inconvenience.

Hi is there a timeline for the fix?

**Comment by boangeli** [comment]
facing same issue. (over 1000 repo here!)
