### ISSUE TITLE
Request for an option to Contact support via Web dashboard

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7635]
**Is your feature request related to a problem? Please describe.**
Unable to contact support after being logged into the Web dashboard

**Describe the solution you'd like**
To provide an option that is similar to the one found in the application
![ContactSupport](https://user-images.githubusercontent.com/47771757/68737972-08302000-060b-11ea-9662-e1f53f7f1f10.png)

**Describe alternatives you've considered**
- Write to help@getpostman 
- Submit a ticket via https://www.getpostman.com/support

**Comment by DannyDainton** [comment]
The web dashboard is no longer part of the Postman platform but the web version of Postman has this option in the settings. 

<img width="490" alt="image" src="https://user-images.githubusercontent.com/17089546/177347486-fd0fd34c-09b6-44ac-9917-e2925529dcae.png">
