### ISSUE TITLE
How to generate 11 digit random munber 

### ISSUE THREAD

**Issue by SDixit1** [a85/POSTMan-Chrome-Extension#7636]
I want to generate 11 digit random phone number stating with 01 or 02

**Comment by shamasis** [comment]
Hey ... you can use Postman pre-request scripts to set value of a variable and use the same. You can also check if any of the built in dynamic variables meet your needs. 

Also, you may reach out at community.getpostman.com for getting more detailed info on how to do these. Also, there’s a section on our docs highlighting how to use variables and scripts.
