### ISSUE TITLE
Load resources with relative links in preview tab

### ISSUE THREAD

**Issue by abdulla-allaith** [a85/POSTMan-Chrome-Extension#7637]
As described in #2948 :

>when you make request to server and it's responding with HTML page all relative links to CSS/JS/etc files will be broken and will not work. Full URLs is working fine.
>
>So /assets/style.css will not work while http://example.com/assets/style.css will work in Preview tab and HTML is shown correctly.

This causes issues when I am loading a page not developed by myself (I can't request changing all relative links to absolute links!).
It would make the preview tab as superior as it should be, replicating any normal browser (at least on loading css/js, previewing it as it was intended).

Only the 2nd part of the original issue was fixed:
> Also it would be great to open links from JSON response in default browser rather than in new postman tab.

The main part of the issue was ignored!

**Comment by codycraven** [comment]
I just spent 30 minutes trying to figure out why I couldn't get CSS assets to load in the preview and finally stumbled upon this issue. I attempted mutating the response body in a test (so that I could convert absolute paths into fully qualified urls with regex) but it looks like mutating the body isn't possible.

**Comment by shamasis** [comment]
I’m afraid that the preview tab of app is not supported to load any external resource at the moment and shows the raw HTML alone. 😞

This request is already being tracked in another github thread. Will post updates when we pick this feature up. Meanwhile, I will find, check and update the other thread with progress.

**Comment by samuelgfeller** [comment]
This is so frustrating. I wanted to use Postman to make tests with pre-saved requests to see if the site displays the error messages correctly. 
@shamasis which other github thread if I may ask? I found only this one, #2948 and #1048, but they are all closed.
