### ISSUE TITLE
Bootcamp/Automated testing : Chaining non working if 'Send Postman Token Header' is off

### ISSUE THREAD

**Issue by Rom1deTroyes** [a85/POSTMan-Chrome-Extension#7638]
**Describe the bug**
When following the Bootcamp about Automated testing, the Chaining data between requests was non working because 'Send Postman Token Header' is off in my Settings.

As the lesson use this header, it show a strange behavour thas is not obvious to solve for beginers (like me :-) )

```JS
pm.globals.set("newToken", jsonData.headers['postman-token']);
````

**To Reproduce**
1. Go to 'Settings' -> Headers -> `Send Postman Token header` : switch to `off`
2. Go to  'Bootcamp' and launch `Automated testing` 
3. Follow the 'Carry data between requests' steps until `Got to quick look`
4. See that the 'New variable is created' with blank value (and realize that `postman-token` is not in the body response).
5. If you continue the lesson, Param `token` of POST request will be blank too, and so the response : 
```JS
    "args": {
        "token": ""
    },
    "data": {
        "method": "POST"
    },
```
**Expected behavior**
Following the lessons may not interfer with specific configuration.

Maybe use one of fields returned by a basic cURL request, or testing the param on a 'pre-request-script' ?

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : v7.11.0
 - OS : Win10Pro v10.0.17763

**Additional context**
I had disabled the `Send Postman Token header` a while ago to copy/paste cURL request, and forget about that... And, whell, at last take some time to follow the lessons and have better practices with Postman tools :-)

**Comment by DannyDainton** [comment]
Hey @prashantagarwal 

Is this an issue that you're tracking on the Onboarding squad?

**Comment by arlemi** [comment]
Hey there,

I'm closing this issue as the Bootcamp is not available in the app anymore from the March 2023 (v10.12) release.

If you're interested in Postman training courses here's a few resources to check out:
-  [Postman Quickstarts](https://quickstarts.postman.com/) 
-  [Postman Academy](https://academy.postman.com/)
- [Postman Intergalactic webinars](https://www.postman.com/events/intergalactic/)
