### ISSUE TITLE
Expired cookies are not deleted

### ISSUE THREAD

**Issue by mserdur** [a85/POSTMan-Chrome-Extension#7639]
**Describe the bug**
A Set-Cookie header with an expiration date already exceeded does not cause the saved cookie to be removed.
Example: 
After server returns following Set-Cookie header shortTermTicket cookie still exists and sent with requests.
shortTermTicket=;expires=Thu, 01 Jan 1970 00:00:00 UTC;Version=1;Path=/;Max-Age=0;HttpOnly

**To Reproduce**
1. Send a request to a service which sets a valid cookie
2. Send another requests to a service which sets the cookie created in step 1 to an expired date.
3. Check the cookies for the domain name. The cookie which must be removed is still there.
4. Make a 3rd request to the service and check the "Cookie" request header to see the cookie is included in the header.

**Expected behavior**
Expired cookie should be deleted and not included in subsequent requests.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.10.0, win32 10.0.17763 / x64 ]
 - OS: [windows 10]

**Additional context**

**Comment by vikiCoder** [comment]
Hi @mserdur,

We have recently fixed a bug where cookies having both fields `expires=<past date>` and `Max-Age=0` were not being deleted properly. Please update to the latest [Postman app (v7.20.0)](https://www.postman.com/downloads/) and it will work as expected. I am closing the issue for now. Feel free to reopen the issue if it still persists even after updating the app.
