### ISSUE TITLE
Bootcamp/Collaboration : Lesson doesn't work with acount email

### ISSUE THREAD

**Issue by Rom1deTroyes** [a85/POSTMan-Chrome-Extension#7640]
**Describe the bug**
If you use the email of your account, and : 
- share as "collaborator" you got the message
    `You need to specify atleast one role that allows updating roles on this workspace`
- share as "admin" you got no message

In both case, the lesson stop and the % is droped to 0 (but still 'in progress').

**To Reproduce**

The 'Collaborator' flow
1. Go to 'Bootcamp' and launch Collaboration -> Collaborate with your team
2. Follow the steps and enter your acount email address
3. See the `Collaborator` status
4. Continue until the `Send Invitation`
5. See the message `You need to specify atleast one role that allows updating roles on this workspace`
6. Lesson is ended and shows as 0% completed.

The 'Admin' flow :
1. Go to 'Bootcamp' and launch Collaboration -> Collaborate with your team
2. Follow the steps and enter your acount email address
3. See the `Collaborator` status
4. Continue until the `Send Invitation`
5. See the message `You need to specify atleast one role that allows updating roles on this workspace`
6. Lesson is ended and shows as 0% completed.

**Expected behavior**
Lesson to finish, and having a 100% status (for Glory :-) )

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by Rom1deTroyes** [comment]
May be related with #6551 ?

(also tried with an other email address : the lesson don't finish event when the Collaborator accepts the invitation and use the Collection.

**Comment by arlemi** [comment]
Hey there,

I'm closing this issue as the Bootcamp is not available in the app anymore from the March 2023 (v10.12) release.

If you're interested in Postman training courses here's a few resources to check out:
-  [Postman Quickstarts](https://quickstarts.postman.com/) 
-  [Postman Academy](https://academy.postman.com/)
- [Postman Intergalactic webinars](https://www.postman.com/events/intergalactic/)
