### ISSUE TITLE
Import json failed

### ISSUE THREAD

**Issue by jecaestevez** [a85/POSTMan-Chrome-Extension#7641]
**Describe the bug**
upload json file in collection runner fail

**To Reproduce**
1. Go to 'collection runner'
2. Click on 'Select file '
3. Import json file

**Expected behavior**
the file should be loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/1833176/68792474-b1970600-064b-11ea-99e2-4bc5417a83ee.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [windows 10]

**Additional context**

**Comment by codenirvana** [comment]
@jecaestevez Looks like the JSON file you are trying to upload as an iteration data is not valid.
Can you verify the JSON content (must be an array)?

**Comment by jecaestevez** [comment]
Here we  have the json file  which I tried http
://www.microtalleres.es/courses/list
<http://www.microtalleres.es/courses/list>

**Comment by codenirvana** [comment]
@jecaestevez As mentioned previously, the iteration data expects an Array so just passing the `Courses` array will fix your issue. Like this:

```
[
  {
    Title: "..",
    IsActive: true
    ..
  },
  {..}
]
```

Also, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
