### ISSUE TITLE
change font style for "Import"  "runner"  and "open new" buttons

### ISSUE THREAD

**Issue by jecaestevez** [a85/POSTMan-Chrome-Extension#7642]
**Is your feature request related to a problem? Please describe.**
When I see "Import"  "runner"  and "open new" buttons, it looks like disable for me

![image](https://user-images.githubusercontent.com/1833176/68792630-02a6fa00-064c-11ea-85a7-d27b27f6c531.png)

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/1833176/68792656-0dfa2580-064c-11ea-9eb9-7804c0fbd041.png)

**Describe alternatives you've considered**
other colours different than disable

**Additional context**

**Comment by nik72619c** [comment]
This issue has been fixed in the new release of the postman app `7.20`. Therefore, closing this issue.
