### ISSUE TITLE
Importing and exporting a collection to json does not keep request responses in the same order

### ISSUE THREAD

**Issue by agheorghe-careplanner** [a85/POSTMan-Chrome-Extension#7645]
1. Importing and exporting a collection to json does not keep request responses in the same order.
2. Exporting a collection and comparing to an export made from its fork will not have responses in the same order not allowing a correct diff.

**To Reproduce 1**
1. Export a collection to json (tried v2.1 and v2, both have the same behaviour)
2. Import the collection json as a copy
3. Export the copy collection to json without making any changes
3. Compare the 2 files using diff or any software and you will find the responses will be in a different order.

**Expected behavior 1**
Comparing the 2 files using diff or any software should not display any differences

Steps to reproduce the behavior 2:
1. Export a collection to json (tried v2.1 and v2, both have the same behaviour)
2. Fork the collection
3. Export the forked collection to json without making any changes
3. Compare the 2 files using diff or any software and you will find the responses will be in a different order.

**Expected behavior 2**
Comparing the 2 files using diff or any software should not display any differences

**App information (please complete the following information):**
App Type - Native
Postman - Version 7.11.0 (7.11.0)
MacOSX - Catalina - 10.15

**Comment by saswatds** [comment]
This issue is caused by  https://github.com/postmanlabs/postman-app-support/issues/1070
The order of examples/responses ~is guaranteed~ in the collection right now.

Edit: The order is *not* guaranteed

**Comment by agheorghe-careplanner** [comment]
Thank you for your answer, but I don't see how the examples/responses are guaranteed?

Even if the export keeps things in a consistent way, importing will always change the order. The export after an import does not keep the same order as the one before it.

**Comment by saswatds** [comment]
Sorry for the typo. It's not guaranteed
