### ISSUE TITLE
Change values in json

### ISSUE THREAD

**Issue by MrFail** [a85/POSTMan-Chrome-Extension#7647]
**Describe the bug**
When you put a json into raw section and press "Beatify" it change the values in json ( for long int).

**To Reproduce**
1. Choose "Raw" section
2. Put json format string
3. Click on "Beatify"

**Screenshots**
Example:
![image](https://user-images.githubusercontent.com/11087193/68864098-3724bf80-06f9-11ea-8e20-21742d585a76.png)
Press "Beautify"
![image](https://user-images.githubusercontent.com/11087193/68864180-5ae80580-06f9-11ea-84f2-81211c4202bb.png)
Version of pastman
![image](https://user-images.githubusercontent.com/11087193/68864303-9551a280-06f9-11ea-971b-a39601851154.png)
**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.11.0
 - OS: Windows 10

**Comment by shamasis** [comment]
Tracking here https://github.com/postmanlabs/postman-app-support/issues/7623
