### ISSUE TITLE
Keep comments private to a workspace for Collections shared within private workspaces

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7650]
Logged by Postman on behalf of a user.

**Is your feature request related to a problem? Please describe.**
For Enterprise users utilizing [Private Workspaces](https://learning.getpostman.com/docs/postman/workspaces/intro-to-workspaces/#private-workspaces), they may want to share Collections across multiple Private workspaces where outside contributors may be invited.

Currently, if you comment in a Collection's request on a shared workspace, the comment is visible in any workspace (including private workspaces). Given the people within these workspaces may be from different organizations, this may lead to a leak of sensitive information via comments.

This is also a bit counter-intuitive as a user may assume that any activity within a Private workspace is "private".

**Describe the solution you'd like**
All activity including comments on shared Collections within Private workspaces should remain within the workspace.

**Describe alternatives you've considered**
The current workaround is to fork the collection and add it to a Private workspace. This keeps the comments on a forked collection limited to it, and thus within the workspace (or workspaces) where it's shared.

The downside is that a manual push/pull is required if any changes are made to the source Collection.

**Comment by sankalp0o** [comment]
Thanks for the feedback! We understand where the confusion comes from. In Postman, comments are visible to everyone who can view the collection, irrespective of the workspace. 

I'm keeping the feature request open to limit the visibility of comments but this is not on our roadmap currently. Will keep you updated if we decide to pick this up. In the meantime, it's recommended to set more secure access control on the collection itself.

**Comment by ramji367** [comment]
Since Collections can [no longer be shared](https://blog.postman.com/collaborating-postman-workspace-roles/) between workspaces, this issue is not relevant anymore. Hence closing.
