### ISSUE TITLE
Not being able to connect to MS Dynamics using the rest end point (oAuth 2.0)

### ISSUE THREAD

**Issue by lvejs** [a85/POSTMan-Chrome-Extension#7651]
**Describe the bug**
Not being able to connect to MS Dynamics using the rest end point (oAuth 2.0)

**To Reproduce**

**Expected behavior**
Successful JSON response with payload. Actual behavior (error) is "401 Access Denied".

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type - MS Dynamics CRM Web App
 - Postman Version 7.0
 - OS: Windows

**Additional context**
![postman error](https://user-images.githubusercontent.com/57775733/68901275-3bea7300-06fb-11ea-90a9-49ad758521eb.png)

**Comment by vikiCoder** [comment]
Hi @lvejs,

This does not look like an issue with the Postman app. I suspect there is some problem with permissions for the token you are using. Can you please try sending the same request from command line using cURL generated by the Postman app and see if it works? You can generate the cURL command as described in [this page](https://learning.postman.com/docs/postman/sending-api-requests/generate-code-snippets/).

**Comment by codenirvana** [comment]
Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.
