### ISSUE TITLE
Postman can not be shown on the screen when minimized

### ISSUE THREAD

**Issue by Syslog2905** [a85/POSTMan-Chrome-Extension#7652]
**Describe the bug**
It is connected with #2833 
**To Reproduce**
1. Use 2 monitors. Go to 'Postman' which is on the right monitor and click RestoreDown icon on the upper right

**Expected behavior**
Postman window to ger smaller. Instead it disapper from the screen, you can see it flkkering on the right outside the monitor.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - Postman Version 7.1.1
 - OS: Win10, 64bit
**Additional context**
Workaround:  Hover over the Postman tray icon, right click the running instance and select Maximize. If this option to maximize is not available, make Run as administrator and then again try right click + Maximize.

**Comment by mccannt** [comment]
@Syslog2905 Is this still an issue for you on the latest version of our application?
I have not been able to successfully recreate this issue.

**Comment by DannyDainton** [comment]
Hey @Syslog2905 - Closing this out due to inactivity, if you're still seeing the issue please reach out to us and we can take a closer look.
