### ISSUE TITLE
Automatic GraphQL introspection

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#7655]
**Is your feature request related to a problem? Please describe.**
Auto complete GraphQL queries.

**Describe the solution you'd like**
When a GraphQL request is made, Postman can try to introspect the API internally and show an option to create a schema automatically and provide auto-complete of queries.

**Describe alternatives you've considered**
Manually fetching schema and creating an API.

**Comment by kamalaknn** [comment]
Duplicate of #6719
