### ISSUE TITLE
"Two-pane view" option is shown as "OFF" in Settings, while the user interface shows two-panel view

### ISSUE THREAD

**Issue by aleftinalex** [a85/POSTMan-Chrome-Extension#7657]
"Two-pane view" option is shown as "OFF" in Settings, while the user interface shows two-panel view

Steps:
1. Create an account and log-in to the app at the first time
2. In the set-up steps while logging-in chose the radio-button with "Two-pane view"
3. Check that user interface really shows Two-pane view ---> It shows correctly
3. Go to "Settings" --> User Interface

AR: "Two-pane view" option is shown as "OFF"
ER: "Two-pane view" option is shown as "ON"

Environment: MacOS, 
Postman for Mac
Version 7.11.0
OS X 16.7.0 / x64

**Comment by prashantagarwal** [comment]
@aleftinalex We have revamped our entire UX to onboard you better on Postman. This bug now seems irrelevant to the current UI.
