### ISSUE TITLE
Postman client try out APIs locally( without upload to Postman workspace on internet)

### ISSUE THREAD

**Issue by vaibhavn** [a85/POSTMan-Chrome-Extension#7659]
**Describe the bug**
I have an query( not a bug), there are some APIs with OpenAPI/Swagger JSON files.  I would like to import same to Windows Postman client. Would it upload these APIs to postman server/some default workspace when I import to postman client? 
Please note that query is with respect to without logging-in to Postman workspace.
My product APIs are strictly designed for internal use and not allowed to upload to any third party sites( without an agreement). 

**To Reproduce**
1. Click on 'Import'
2. Import Open API JSON files.
3. Do NOT 'Sign In' to Postman site from Postman client.

**Expected behavior**
APIs should not be uploaded to postman workspace or any other web server.
For example: https://web.postman.co

**App information (please complete the following information):**
 - Native App
 - Postman Version [7.11.0]
 - OS: Windows 10 Enterprise

**Comment by sankalp0o** [comment]
Hey @vaibhavn 
You should be able to import an OpenAPI file to Postman without needing to logging in (using the Import button on the header). This will let you create a **[Collection](https://learning.getpostman.com/docs/postman/collections/intro-to-collections/)** which you can use to test the API on Postman. Without logging in though, you would not be able to create a Postman **[API](https://learning.getpostman.com/docs/postman/design-and-develop-apis/introduction-to-apis/)** which has a host of other benefits.

I'm closing this ticket, but feel free to reach out in case there's any other questions!
