### ISSUE TITLE
Postman adding extra headers to response

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#7663]
**Describe the bug**
We have noticed that our 204 responses started failing tests, as Content-Type header is being returned, however after inspection of our code we couldn't find any place where that header might be setup or returned. We then tried to make the same request through terminal (with -i to see response headers) and "OtherTool" and we saw that this header was only coming back on Postman. After more investigation we found that there are three extra headers overall that are returned on Postman: content-type, connection and content-length.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a request to an endpoint that doesn't return content-type, connection and content-length
2. Postman will report that content-type, connection and content-length headers were returned

**Expected behavior**
No content-type, connection and content-length headers should be returned.

**Screenshots**
Postman:
![image](https://user-images.githubusercontent.com/43671684/69071007-13c38280-0a21-11ea-90dd-93fe9c03b611.png)
"OtherTool":
![image](https://user-images.githubusercontent.com/43671684/69070949-fee6ef00-0a20-11ea-80d9-95ca5db1f260.png)
Terminal:
![image](https://user-images.githubusercontent.com/43671684/69070985-0c9c7480-0a21-11ea-8be3-abdcb700c699.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.11.0
 - OS: macOS Catalina 10.15

**Additional Context**
If you need the cURL, probably best to share it through email or agree a Hangouts call as it is time sensitive (only will give this response for 30 minutes) and includes sensitive information.

**Comment by codenirvana** [comment]
@VicKetchup Postman shows the exact same header it receives from the requesting server. Since these are response headers, we have no control over these.

I feel this is happening because of the additional headers we send while making the request, like `Connection: keep-alive`.

Try sending `Connection: close` and check if that removes the `Connection` headers.
I am not sure about the reason for `content-type` and `content-length` headers. 😕

**Comment by VicKetchup** [comment]
Hi @codenirvana,

Unfortunately that has not removed the connection header: 
![image](https://user-images.githubusercontent.com/43671684/69135936-e672e500-0ab1-11ea-890c-d25bfce83f58.png)
I was also confused, as I tried a request to https://httpstat.us/204, which doesn't produce any of these, however two other tools, on top of our code inspection, show that we do not send these headers, so seems to be Postman specific for some reason.
As previously mentioned, I would be happy to share the cURL through email or have a call to resolve this issue.

**Comment by codenirvana** [comment]
@VicKetchup Looks like the requesting server is respecting the request headers to generate response headers.
Can you check if sending `Connection`, `Accept-Encoding` etc. headers to the other clients (curl) also behave the same way?

**Comment by VicKetchup** [comment]
@codenirvana Please see the screenshot below, but that is not the case...
![image](https://user-images.githubusercontent.com/43671684/69528768-cb4b1e00-0f66-11ea-91e5-92be1b58127d.png)
Same request on Postman:
![image](https://user-images.githubusercontent.com/43671684/69528895-08afab80-0f67-11ea-9e9e-1229e89f3c7d.png)

**Comment by shamasis** [comment]
I think we have arrived at a deadlock here. We are unable to reproduce this without getting hold of the actual endpoint. I have a suggestion though ... try the latest Postman Canary (https://www.getpostman.com/downloads/canary) ... it has a new feature that allows you to disable the default headers Postman sends. Try turning off as many as applicable to see if your response matches.

One fun stuff ... recently I noticed that a server would send a set of headers if the requesting client had one user-agent header and another set when the user-agent was changed!

**Comment by VicKetchup** [comment]
@shamasis Thank you very much for the suggestion and that is an interesting observation. 
By process of elimination it was the Host header in our case, will check with our devs.
A suggestion for this new build, have a toggleable option in the settings to always have the Automatic headers disabled :)

**Comment by VicKetchup** [comment]
@shamasis 
UPDATE:
Without the Host header we get a 400 error, however it is not even calling our API (checked gateway logs and nothing was there), so it seems like with that disabled it's calling some other host.
Here is the response we get without the Host header:
_

> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
> <HTML>
> 
> <HEAD>
> 	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
> 	<TITLE>ERROR: The request could not be satisfied</TITLE>
> </HEAD>
> 
> <BODY>
> 	<H1>400 ERROR</H1>
> 	<H2>The request could not be satisfied.</H2>
> 	<HR noshade size="1px">
> 	Bad request.
> 	We can't connect to the server for this app or website at this time. There might be too much traffic or a
> 	configuration error. Try again later, or contact the app or website owner.
> 	<BR clear="all">
> If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
> 	<BR clear="all">
> 	<HR noshade size="1px">
> 	<PRE>
> Generated by cloudfront (CloudFront)
> Request ID: ZYyL_9tvVHnpiYNZ5WoDwpIzif3jvFpTSTzc2zBvACHoAah-EC3AxA==
> </PRE>
> 	<ADDRESS>
> 	</ADDRESS>
> </BODY>
> 
> </HTML>

_
This also means that it is still unclear how we are getting the Content-Type header, using Postman's User-Agent through terminal still doesn't give us Content-Type in the response.

**Comment by codenirvana** [comment]
@VicKetchup `Host` header is a required header for the most servers (and load balancers). As you can see, the 400 response is from CloudFront.

When you disable the `Host` header, Postman does send the request without it and you can verify this by using an echo server like this: https://gist.github.com/codenirvana/afb41744865e13d77da7be7ed2f2539c

**Comment by VicKetchup** [comment]
@codenirvana sending request through other clients or using cURL directly in Terminal without the Host header works just fine and the request from Postman without Host header doesn't even reach our gateway, so seems like some issue on Postman side.

**Comment by codenirvana** [comment]
@VicKetchup Is it possible to share the endpoint which we can use to reproduce this behavior?

As you can see in this screenshot, the postman-echo endpoint also responds with 400 when the host is removed while sending requests through curl.
![Screenshot 2020-03-12 at 8 31 29 PM](https://user-images.githubusercontent.com/4865836/76535211-8a88fd80-64a0-11ea-8393-2ac647e4a936.png)

**Comment by VicKetchup** [comment]
@codenirvana Could I share this through email? If so, shall I message to help@getpostman.com or could we do it more directly? My work email: viktor.tkachuk@tui.com

**Comment by codenirvana** [comment]
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/7663#issuecomment-597872925 and our followup conversation over the email, the latest version of the Postman app gives more control over the addition of the automatic addition of request headers.
In this particular case, disabling the `Connection` and `Accept-Encoding` headers fixes the issue.

**Comment by VicKetchup** [comment]
As per email conversation, our issue was due to http1.1 being used by Postman, while all other clients used http2, hope that helps anyone running into the same. And thanks @codenirvana for all the help.
