### ISSUE TITLE
Postman thinks I am offline

### ISSUE THREAD

**Issue by Matt-VL** [a85/POSTMan-Chrome-Extension#7666]
**Describe the bug**
Postman thinks I am offline so I cannot switch to my Team workspace.

**To Reproduce**
1. Click My Workspace
2. Switch to the "Team" tab
3. Notice error "You need to have an active internet connection to be able to switch to or create a workspace."

**Expected behavior**
Team workspace should appear allowing me to switch to it.

**Screenshots**
![PostmanIssue1](https://user-images.githubusercontent.com/56362247/69093047-ad883100-0a1b-11ea-970d-d536335c5169.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.12.0
 - OS: Windows 10 Pro Build 18363

**Additional context**
This started happening in the past 2 weeks. The only things that have changed on my end are applying some windows updates. Others have applied the same updates and are not having the issues I am.

**Comment by ankit-m** [comment]
@Matt-VL could you please provide the following information

1. Open go.postman.co, login and see if you are able to view workspaces?
2. What is the color of the sync icon in the top bar of your app? Red/blue/grey?
3. Send a screenshot of the `Console` tab in `View` -> `Developer` -> `Show Devtools (Shared)`

Postman app requires a websocket connection to be established with our servers. In many cases, network or firewall settings block websockets. Just trying to ensure that this isn't the case here.

**Comment by Matt-VL** [comment]
@ankit-m 

1. Yes I can see personal and team workspaces on go.postman.co
2. Red
3. 
![DevConsolePostman](https://user-images.githubusercontent.com/56362247/69553240-d9506d00-0f6d-11ea-9483-d66212d894e4.png)

**Comment by Matt-VL** [comment]
I am now on v7.12.0.

I have also added Postman as trusted apps through our Firewall and still getting the same issue.

**Comment by Matt-VL** [comment]
@ankit-m any update?

**Comment by Matt-VL** [comment]
@ankit-m I resolved this by deleting my entire Postman folder in AppData/Local and AppData/Roaming

**Comment by dsmatana** [comment]
Have same problem for a looong time and way to debug why it's happening. We are paying for this !

**Comment by devesh-dbdigital** [comment]
I also resolve this problem by deleting the postman folder in Appdata/local and appdata/roaming folder. I am using window 10  and Postman v7.21.2

**Comment by rzinnatullin** [comment]
Not sure if it will help to investigate, but I had 2 Postman instances open on different machines, then installed the 3rd one on the 3rd machine. The 3rd instance was saying that there's no internet connection, and one of the other instances was saying `One of your active Postman sessions has ended. You’ve gone over the maximum of 3 simultaneous sessions.`
However, at the same time, `status.postman.com` is saying `Degraded performance on the App for some users`

**Comment by DogGuyDavid** [comment]
I am having the same issue today.  I am able to use the internet just fine on all apps except Postman.

**Comment by arlemi** [comment]
@DogGuyDavid Some users are experiencing degraded performance with the app, including sync. You can follow the issue on our status page: https://status.postman.com/

**Comment by zeabdelkhalek** [comment]
Same issue with the latest version: 7.27.1

**Comment by urmichm** [comment]
Same issue with the latest version: 8.2

**Comment by SebastianJust** [comment]
Have the same issue now on v8.5.1

**Comment by jeffreyhawkins** [comment]
Only solution I found to work around this on macos:

1. Quit Postman
2. From terminal... `mv ~/Library/ApplicationSupport/Postman ~/Library/ApplicationSupport/Postman-org`
3. Restart Postman

**Comment by sunilmhta** [comment]
I am also facing this issue for around 3 weeks now. Haven't found anything which works for me. I don't see any patten. On web postman, I see my status as "Syncing" but on the desktop app, it says I am offline. I am also on Windows 10, postman version 9.0.3

**Comment by arlemi** [comment]
@sunilmhta Are you using a firewall (personal or company one)? Are you seeing the same on different machines?

**Comment by sunilmhta** [comment]
Yes, my remote machine(inside the office) is working fine but in my laptop I am facing this issue. The issue is quite random in the laptop. Like just now, it's showing "Syncing" but just a couple of hours ago, it was showing "Offline". There is no firewall issue, otherwise it won't work randomly. I have closed all the other instances of my postman on remote machines.

**Comment by arlemi** [comment]
@sunilmhta Next time this happens please get the logs (see how: https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs-) and open a ticket through postman.com/support. The support team will be able to look into it in more details.
