### ISSUE TITLE
Team migration from Pro to Enterprise static regions still greyed out 

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7670]
Team has migrated from Pro to Enterprise with static regions made available, yet still greyed out in-app and not selectable.

**Comment by godfrzero** [comment]
@stcalica Could you add steps to reproduce please?

**Comment by shivam-postman** [comment]
https://github.com/postmanlabs/postman-app-support/issues/7293#issuecomment-555077866
I think this comment explains what the behaviour is and what it should be.

**Comment by sherff** [comment]
hi, 
we upgraded from postman pro to enterprise but several enterprise features are still greyed out:
- Static IP Region in Monitor Feature
- I get a frequent reminder in the bottom left about archived collections, that there are too many and that I should visit a Link (to the postman web page) to solve it. this link points me to a not available site.

something seems to have gone wrong with the upgrade to postman enterprise licence.

**Comment by mccannt** [comment]
Closing this out as it appears it may no longer be an issue.
