### ISSUE TITLE
Postman collection, web view, does indicate need for bearer token in collection documentation

### ISSUE THREAD

**Issue by MarkusAnthony** [a85/POSTMan-Chrome-Extension#7673]
For my collection I setup authorization type to be "Bearer Token" but I do not see any indication in the web view documentation for my apis. 

1. Go to a collection in the app
2. Click on ...
3. Click on Edit
4. Click on Authorization Tab
5. For Type choose "Bearer Token"
6. For Token put an environment variable such as {{token}}
7. Click Update
8. Click on Sync button
9. View your collection documentation in the web view
10. Look for any indications that a bearer token is required

At the least I would expect a header or something near the top that includes an indication that the collection has been setup with a bearer token.

I would like it to actually update every "request"example like it does when I add it to the header, for example:

--header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJtcmlzc21hbm5AbnV2b2RpYS5jb20iLCJ0cmFja0lkIjoiMjVkYWZmNDctOTdiNC00MzexampleN2MtMDNjZDQyYmIzMTNhIiwiYXV0aG9yaXphdGlvbnMiOltdLCJpYXQiOjE1NjI3MDM4MDMsImlzcyI6Ikdlc3RhbHQgRGlhZ25vc3RpY3MifQ.83QLbcmPSAHnKy5vCy_nWAFcj9nHHPeNBPPG4GctICM"

**App information (please complete the following information):**
 - App Type: latest app 
 - Postman Version: Postman v7.11.0
 - OS: windows 10

**Additional context**

This is really problematic as the coders don't have any idea that a bearer token used. Nor do they have any indication if it is used for all or some requests.

**Comment by Raja-Simha** [comment]
@MarkusAnthony Thanks for your feedback.

We do show an icon indicating that a particular request needs authentication
![image](https://user-images.githubusercontent.com/45988836/69212964-c19d7100-0b88-11ea-8c1a-babf9fa485c2.png)

However, we do realize that we can show more information on how a request is being authenticated. I will keep this request open. Please feel free to share any more suggestions you may have w.r.t showing authentication information.

**Comment by Raja-Simha** [comment]
This is fixed now. Documentation now indicates the auth type required for an endpoint.
