### ISSUE TITLE
Ubuntu 19.10 KDE Postman silently crashes on launch

### ISSUE THREAD

**Issue by charlesritchea** [a85/POSTMan-Chrome-Extension#7677]
**Describe the bug**
When running KDE Plasma in Ubuntu 19.10, if I try to start postman, it just fails silently. No terminal output or anything. No postman process in ps -A

**To Reproduce**
Start postman

**Expected behavior**
Either postman starts or there is as least some feedback

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.10.0
 - OS: Ubuntu 19.10 Plasma

**Comment by harryi3t** [comment]
@charlesritchea Are you using Wayland?
If not sure, you can check using `echo $XDG_SESSION_TYPE`

**Comment by charlesritchea** [comment]
I think I was using x11 at the time. I was remote and couldn't restart. Once I got into the office and restarted the problem went away. I noticed the process name was Postman, not postman, so it's possible it was just a zombie preventing new instances. Either way, some feedback would have been nice. Closing since I can't reproduce now

**Comment by charlesritchea** [comment]
@harryi3t ^
