### ISSUE TITLE
Allow Postman Docs to be embedded on another page

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7678]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to embed Postman documentation on a site other than the docs page we host.

User comment:
https://community.getpostman.com/t/unable-to-host-postman-doc-from-my-webserver/9117
```
Hi All, I am running an nginx server which is currently hosting three tabs swagger ui, postman api (from the published postman doc ) and postman examples.

In console, I get this error Refused to display “postman doc url” in a frame because VM set ‘X-Frame-Options’ to ‘deny’

Both postman doc and postman examples are getting refused to connect error.

Can someone please help me?

Thanks
```

**Describe the solution you'd like**
Allow Postman documentation pages to embedded on other sites.

**Describe alternatives you've considered**
Support for rendering a Collection definition, outside of the Postman Documentation Service.

**Additional context**

**Comment by a85** [comment]
There are no immediate plans to embed Postman docs as they might create security issues down the road. Docs will continue to be a hosted cloud service. Users can host them on their custom domains for now.
