### ISSUE TITLE
Admin is unable to login to the Postman application after mistakenly disabling all available authentication methods in the Team Settings

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#7679]
**Describe the bug**
Admin is unable to login back to the Postman application after mistakenly disabling all available authentication methods in the Team Settings and logging out. Please note that the Team that the admin belongs to has a single admin.

**To Reproduce**
1. As a Team Admin, navigate to Team < Settings < Authentication 
2. Disable all Authentication methods
3. Log out of the application
4. Try logging into the application with the credentials
5. You can see a client-side validation message stating that the current authentication method has been disabled

**Expected behavior**
Postman password has to be re-enabled for the team so that the team is allowed to login to the application

**Comment by gdbhowmick** [comment]
Hi Aamir, are you logged-in in any other devices (maybe Postman App)?

**Comment by aamir-ahmed** [comment]
Unfortunately, the user is the only admin on the team and is currently not logged on in any device.

**Comment by ArjunSingh-PM** [comment]
A fix is now in place to ensure that at least one authentication method is enabled at all time.
