### ISSUE TITLE
Improve message clarity when collection is removed

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7681]
**Is your feature request related to a problem? Please describe.**
After removing a collection from a team workspace and later trying to open it from the dashboard (https://go.postman.co/me/collections) it throws the below error message. 

<img width="666" alt="Screen Shot 2019-11-20 at 11 29 43" src="https://user-images.githubusercontent.com/47351631/69236279-180baf00-0b8b-11ea-83cd-c26a2c68ce48.png">

**Describe the solution you'd like**
Improve the clarity of the message so it doesn't look like an error and highlight the possibility to share it back to a workspace. 

**Describe alternatives you've considered**
Make a section in the dashboard called "Removed collections" which would solve the following second problem. A team may accidentally remove a collection during a workspace clean-up. When the team realizes that a collection is being missing, they don't necessarily think of heading to  https://go.postman.co/me/collections to look for it.

**Comment by sankalp0o** [comment]
Thanks for reporting @cyrielle-hada ! You're absolutely correct that this is not very clear. We'll definitely improve the messaging here and also consider having another section for collections like these.

**Comment by soubhir-uxd** [comment]
Hi @cyrielle-hada !
We have improved the messaging and the experience around this section. Please have a look and share your valuable feedback.
