### ISSUE TITLE
Graphql support in forked collections

### ISSUE THREAD

**Issue by eoneal89** [a85/POSTMan-Chrome-Extension#7682]
Currently if a collection is forked, changes for the beta graphql body are not accounted for when trying to merge changes back in to the origin collection.

It would be nice when changes occur in the graphql body that they appear in the list of changes in the merge tool.

There should at least be a way to force merge collections even when postman doesn't think there is a change.

**Comment by ankit-m** [comment]
Hey @eoneal89,

I am able to reproduce the scenario you mentioned and it looks like a bug. I have created a bug on our internal issue tracker and will keep you posted about the progress.

**Comment by kartikjain26** [comment]
@eoneal89  We are working on this fix currently. I'll let you know as soon as it is out there in production.

**Comment by kartikjain26** [comment]
@eoneal89 This is out in production.
