### ISSUE TITLE
Issue Setting variables with 'postman.setEnvironmentVariable' vs 'pm.environment.set'

### ISSUE THREAD

**Issue by ebookerd1** [a85/POSTMan-Chrome-Extension#7683]
**Describe the bug**
I was creating functions to test globally in my project. For some reason the variables functions were not being saved when use `pm.environment.set`

pm.environment.set("utils", () => {
    var myFunction1 = () => {
        //do something
    }
    var myFunction2 = () => {
        let func1Result = myFunction1();
        //do something else
    }
    return {
        myPackage: {
            myFunction1,
            myFunction2
        }
    };
});

When I do `pm.environment.get('utils'); ` the response is null. I can also confirm this in the `Environment Quick Look`. But when I use `postman.setEnvironmentVariable` with the above method. The variable is updated as expected and I can see a value in `Environment Quick Look`.

Is this a bug or is that expected???

**To Reproduce**
1. Go to 'Pre-request Script'
2. Assign function to an environment variable. Using `pm.environment.set`
3. In the test Call `pm.environment.get` for the variable

**Expected behavior**
Variable is not null and or contains the functions text.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.10.0 (7.10.0)
 - OS: macOS Mojave 10.14.6

**Additional context**
Seems Globals, Environment, and Collection variables have this issue when passing functions to the variables as:
    pm.environment.set(
    pm.globals.set(
    pm.collections.set(

**Comment by codenirvana** [comment]
@ebookerd1 That's expected behavior.
The deprecated `postman.setEnvironmentVariable` API automatically converts the non-string input to its string representation, however with `pm.environment.set` you have to manually convert to string.

In this case, you have to convert the function to its string representation using the `toString` method.
