### ISSUE TITLE
'pm.request.url.query' doesn't contain any disabled query params while the request method is "GET" while the request is send by using 'run collection' feature

### ISSUE THREAD

**Issue by menglingxuan** [a85/POSTMan-Chrome-Extension#7686]
**Describe the bug**
'pm.request.url.query' doesn't contain any disabled query params while the request method is "GET" while the request is send by 'collection run' feature

**To Reproduce**
1. create a collection
2. add a request to collection, (the request method is "GET")
3. add two query params named: "test1", "test2", which the "test2" param is disabled
4. write the following script for the request's pre-requestScript(or for collection's pre-requestScript):
     `
     console.log(pm.request);
     `
5. send request without using collection run
6. check the console output: 'pm.request.url.query' should contains disabled param named "test2"( passed )
7. using 'run collection' to send the request
8. check the console output: 'pm.request.url.query' should contains disabled param named "test2"( failed, there are just non-disabled query params)

**Expected behavior**
when using run collection, 'pm.request.url.query' should contains disabled query param
     ps: this is the trueth in earlest previous version of postman.

**Screenshots**
None.

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version:  v7.12.0
 - OS:  Windows 10

**Additional context**
None.

**Comment by vikiCoder** [comment]
Hi @menglingxuan, I was able to reproduce the issue. As you said, it does not get disabled params in pre-request script if the request is sent via runner but it gets disabled params when the same request is sent via requester. We will be fixing the issue soon and update here.

**Comment by menglingxuan** [comment]
thx. for you work

**Comment by menglingxuan** [comment]
> Hi @menglingxuan, I was able to reproduce the issue. As you said, it does not get disabled params in pre-request script if the request is sent via runner but it gets disabled params when the same request is sent via requester. We will be fixing the issue soon and update here.

**Comment by vikiCoder** [comment]
Hi @menglingxuan,

This issue is fixed in the latest release of the Postman app (v7.24.0). Please update to the latest version to check it out.
