### ISSUE TITLE
The application crashes if the request returns a large amount of data. In my case, 18 MB

### ISSUE THREAD

**Issue by AnastasiyaSm** [a85/POSTMan-Chrome-Extension#7689]
The application crashes if the request returns a large amount of data.

Send a post request as a result of which voluminous data will return (see screenshots. 1 screenshot corresponds to "did not crash", 2 screenshot - "crash"

Actual result - application black screen

Run a Runner that includes a query that returns bulk data
Actual result - application terminated

**App information (please complete the following information):**
 - Native App
- Postman v7.12.0
- Windows 10 pro

**Additional context**
![image](https://user-images.githubusercontent.com/58032676/69333779-693ea000-0c6a-11ea-9cae-0ae9abb5f766.png)
![image](https://user-images.githubusercontent.com/58032676/69333805-78bde900-0c6a-11ea-92e9-7e714400b8ed.png)
![image](https://user-images.githubusercontent.com/58032676/69333942-ba4e9400-0c6a-11ea-9563-630afd3b86f0.png)

**Comment by saswatds** [comment]
Hi @AnastasiyaSm, Can you confirm if you are consuming the response in the `Test Script`?

**Comment by AnastasiyaSm** [comment]
![image](https://user-images.githubusercontent.com/58032676/69337578-4617ee80-0c72-11ea-9e35-cffdf341b450.png)
[response.txt](https://github.com/postmanlabs/postman-app-support/files/3874599/response.txt)

**Comment by AnastasiyaSm** [comment]
pm.test("Response time is less than 200ms", function () {
    pm.expect(pm.response.responseTime).to.be.below(200);
});

var schema = JSON.parse(pm.globals.get('pointAll'));

pm.test("Схема валидна", function() {
  var data = JSON.parse(responseBody);
  var valid = tv4.validate(data, schema, false, true);
  if (valid !== true) {
      // console.log(tv4.error);
      console.log(tv4.error.dataPath);
  }
  pm.expect(valid).to.be.true;
});

**Comment by AnastasiyaSm** [comment]
> Hi @AnastasiyaSm, Can you confirm if you are consuming the response in the `Test Script`?

Without test scripts, it also crashes. For experiment, removed scripts

**Comment by saswatds** [comment]
Thanks @AnastasiyaSm. We will take a deeper look into this.

**Comment by shamasis** [comment]
@AnastasiyaSm can you try the latest postman app to see if it is still crashing? In my case, `https://postman-echo.com/bytes/30/MB` and even `https://postman-echo.com/bytes/40/MB?type=json` works with or without scripts.

1. I am on latest Postman version 7.20
2. I have response timeout set to 0 (infinity) in app setting
3. I have max response size set to 50 mb in app settings

Please check and let us know with these conditions and we will reopen if there is more info that can accurately reproduce the scenario

![Screenshot 2020-03-12 at 01 50 02](https://user-images.githubusercontent.com/232373/76460343-d9348a00-6403-11ea-87e6-9dc413342d46.png)
