### ISSUE TITLE
[Feature Request] Description tab in request pane

### ISSUE THREAD

**Issue by sanjkagm** [a85/POSTMan-Chrome-Extension#7691]
Hi Postman people.

I am making our platform's API  PM collection that will be shared across our customers. Some our requests, request fields or their responses aren't very self explanatory or have some "bells and whistles". I wrote a descriptions for each request and realized that it's not that intuitive to find these descriptions, especially for new Postman users.

My suggestion is to add **Description** tab in request pane, next to params, headers, body, etc, to show the description that was written when this request was created. That's a visible place for it and might be a very helpful feature for Postman users.

![image](https://user-images.githubusercontent.com/22824614/69356605-648ae380-0c8c-11ea-9090-bd5cbdd2d616.png)

Postman v7.12.0

**Comment by Raja-Simha** [comment]
@sanjkagm You can now view the documentation for every request in the context bar on the web. Checkout the new UX on the web here - https://www.postman.com/postman/workspace/postman-public-workspace/overview. The same UX will be brought into the app soon. 

Closing this for now. Please reopen if you think this is not solved yet.
