### ISSUE TITLE
Postman 6 Failing on Network Error.

### ISSUE THREAD

**Issue by bsweaty** [a85/POSTMan-Chrome-Extension#7695]
**Describe the bug**
I can download postman 7 from your website just fine, but every attempt at downloading postman 6 throws a network error.

**To Reproduce**
1. Go to https://www.getpostman.com/downloads/ and download postman 7, works fine.
2. Go to https://learning.getpostman.com/docs/postman-pro/managing-pro/migrating-to-v7/#download-latest-postman-v6-app and download postman 6 for os x. fails on a network error.

**Expected behavior**
Seems to be an issue with downloading from your server. I've tried on 3 different networks with no luck. In Safari, it appeared to complete but evidently didn't, showed up as corrupt.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/2700879/69463180-38c53780-0d38-11ea-8563-649d02c8a84f.png)

**App information (please complete the following information):**
 - Download Native App 
 - Postman Version 6 & 7
 - OS: OS X Mojave
- Browser: Chrome, Safara

**Additional context**

**Comment by numaanashraf** [comment]
@bsweaty This looks like an intermittent network issue that looks resolved now. Could you try this again and let us know if you are still facing this?
