### ISSUE TITLE
Allow multi-use invite links to be deleted from Web Dashboard

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7697]
**Is your feature request related to a problem? Please describe.**
Once a multi-use invite link has been created, it cannot be deleted by a user-facing option, forcing support to intervene in circumstances where this is necessary.

**Describe the solution you'd like**
Allow multi-use invite links to be deleted from the invite management portal:
https://go.postman.co/settings/team/manage-invite-links

**Describe alternatives you've considered**
Display multi-use invite links on the /team page, and allow them to be deleted from same.

**Additional context**

**Comment by ArjunSingh-PM** [comment]
Active multi-use invites can now be deleted via the UI.
