### ISSUE TITLE
Unable to edit / save requests after adding new user to team account

### ISSUE THREAD

**Issue by marijnhurkens** [a85/POSTMan-Chrome-Extension#7702]
**Describe the bug**
After adding a second user to our team account and making them admin over a workspace we're unable to edit and save requests using the new account.

When editing a request and hitting save the save new request window pops up (as if I'm creating a new request). When searching for a collection in that window none can be found. The user is team admin and admin within the workspace.

I've tried logging out and in to postman, synchronizing, etc.

**Expected behavior**
I am able to work normally in the workspace and make changes.

**App information (please complete the following information):**
 - Native
 - Postman 7.12.0
 - OS: macOS 10.15.1 (19B88)

**Comment by marijnhurkens** [comment]
Postman also seems to be syncing randomly and when opening a saved request and executing it it seems to not use the http method. It uses GET for everything... (see screenshot)

![Screenshot 2019-11-26 at 12 59 11](https://user-images.githubusercontent.com/3952305/69629659-a5984480-104c-11ea-9408-0937ef960e18.png)

**Comment by ankit-m** [comment]
@marijnhurkens can you verify that the new user has edit access on the collection? Workspace admins don't necessarily have edit permissions on all collections inside it.

Do you see a padlock icon next to the collection name in the sidebar? If yes, then the new user does not have access to the collection. Click on the `ᐧᐧᐧ` icon to show the collection menu and click on `Manage Roles`. Here you can give editor access to your team members.

**Comment by ankit-m** [comment]
As for the request method issue, can you please provide a little more information? Is it happening for all requests or just this one? Can you also provide a screen recording with the `Console` open to see the details of the actual request sent.

**Comment by vvs11** [comment]
@marijnhurkens closing the issue for now. Please feel free to reopen this if you're still facing this
