### ISSUE TITLE
When the fields in the response body returned by the interface are connected using ‘-’, an error is reported when the return value is obtained and set as an environment variable.

### ISSUE THREAD

**Issue by junhaohe** [a85/POSTMan-Chrome-Extension#7706]
{
    "error_code": 0,
    "error_msg": "Success",
    "result": {
        "Access": 1,
        "User-Name": "admin",
        "Facein-Csrf": "a6b969c468f7005fe496618b4ab52ba5",
        "Session-Id": "7405d73992c60b6da5080ed7fe5d0f3a|c52bec0fba7664184e1428b8c8139ede696f29017b6ca5f1124da4612112c50d"
    }
}
var jsonData = JSON.parse(responseBody);
//对responseBody进行json格式化
postman.setEnvironmentVariable("User-Name", jsonData.result.User-Name);
//这里User-Name无法设置为环境变量

**Comment by saswatds** [comment]
Hi @junhaohe `User-Name` is not a valid identifier in javascript https://developer.mozilla.org/en-US/docs/Glossary/Identifier You will need to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors instead of `dot Notation`

**Comment by junhaohe** [comment]
Ok, thanks!



15021157146@163.com
 
发件人： Saswat
发送时间： 2019-11-28 14:19
收件人： postmanlabs/postman-app-support
抄送： junhaohe; Mention
主题： Re: [postmanlabs/postman-app-support] When the fields in the response body returned by the interface are connected using ‘-’, an error is reported when the return value is obtained and set as an environment variable. (#7706)
Hi @junhaohe User-Name is not a valid identifier in javascript https://developer.mozilla.org/en-US/docs/Glossary/Identifier You will need to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors instead of dot Notation
