### ISSUE TITLE
Console only shows OperationalError logs

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#7707]
**Describe the bug**
When opening the console for the main Postman Window, and firing any request which used to log various information, the only log I obtain is a OperationalError log (both as a debug log and an uncaught exception in a promise).

**Expected behavior**
Supposed to see all the logs I put in the pre-request and test sections.

**Screenshots**
![Screenshot 2019-11-27 at 09 24 24](https://user-images.githubusercontent.com/9873597/69706342-ce294880-10f7-11ea-8960-d1ef43285120.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.12.0
 - OS: macOS Mojave 10.14.6

**Additional context**
It has been a while since I opened the console.
The only thing I've changed since the last time is a definitions.json file which I download in my collection's pre-request code, and feed into TinyValidator. This process seems to be working fine since I'm receiving the updated file and the test are detecting the good and bad results.

**Comment by numaanashraf** [comment]
@jooleeanh Logs from pre-request and tests scripts appear in the Postman Console now. We no longer log these in the DevTools in our desktop apps - https://learning.getpostman.com/docs/postman/sending-api-requests/debugging-and-logs/#for-the-native-app-for-mac--windows--linux-1
