### ISSUE TITLE
Error in JSON syntac coloring  

### ISSUE THREAD

**Issue by Yuri-Harel** [a85/POSTMan-Chrome-Extension#7709]
**Describe the bug**
If the body of a request is :

```json{"a":{"b":[]}}```
Then the last two }} will be marked in read as if they are erroneous. 

**To Reproduce**
Just create such a request with the above code in.  

**Expected behavior**
Not to have that coloring.

**Comment by Yuri-Harel** [comment]
The browser I'm forced to use at work doesn't allow me to click the edit button, so just ignore the json at the start. The body should be just : {"a":{"b":[]}}

**Comment by kamalaknn** [comment]
@Yuri-Harel Thanks for reporting the issue. If I understand this correctly your response for the endpoint is `json{"a":{"b":[]}}` and that is not formatted correctly in the response pretty view.

Could you let us know the version of Postman you are using?

This is a screenshot from the latest version of Postman with the same response from your original description.

![Screenshot 2019-12-02 at 11 54 37 AM](https://user-images.githubusercontent.com/8401064/69935457-f13e6880-14fa-11ea-9315-530e8f572031.png)

**Comment by Yuri-Harel** [comment]
I'm using version 6.5.3 . 

I apologize, It seems I was unclear. When creating a request with a JSON body that looks like this : 
{"a":{"b":[]}} 

And exactly like this, without formatting, the pretty print of the body shows }} in color, probably because it incorrectly assumes there is a variable somewhere. It of course would have been much clearer with a screenshot, but I can't upload these either.

**Comment by kamalaknn** [comment]
Thanks for clarifying that @Yuri-Harel 

We will look into this. In the meantime, you can beautify the JSON by clicking the `beautify` button on the latest version, which will format the JSON body and you will not see the red highlighting.

**Comment by pankajk07** [comment]
@Yuri-Harel  we have made changes to the editor which fixes this issue. Please update the app and try it out.

**Comment by Yuri-Harel** [comment]
Great, thanks :)
