### ISSUE TITLE
Undesired automatic URL encoding

### ISSUE THREAD

**Issue by shtrip** [a85/POSTMan-Chrome-Extension#771]
Suddenly Postman (packaged app) is automatically encoding URLs. This is undesired behavior because as a user I am no longer in control of what is sent to the server. 

Please remove this behavior or at least put it in a setting.

**Comment by lyudash** [comment]
Hello,

I am using Postman 4.6.0 and URL is still automatic encoded. Is there some setting I am missing?

For example my URI is set to https://hostname:portname/t/org.name/partner.name/<string.in.xml.tag>

But the actual request is sent with 

https://hostname:portname/t/org.name/partner.name/%3Cstring.in.xml.tag%3E

How can I eliminate the encoding before url is sent?

**Comment by abhijitkane** [comment]
@lyudash Can you attach a screenshot of your Postman screen? Also, are there any errors in the console - https://www.getpostman.com/docs/errors?

**Comment by lyudash** [comment]
![404](https://cloud.githubusercontent.com/assets/21022610/17649598/21b868e0-6242-11e6-8307-81a6287df342.png)

**Comment by lyudash** [comment]
![console](https://cloud.githubusercontent.com/assets/21022610/17649738/afb42cae-6244-11e6-9399-1aba0d32efe7.png)

**Comment by lyudash** [comment]
I added 2 screenshots, thanks for the quick reply. I do not see any errors on the console, even though I expected to see the 404 ...

**Comment by arapoport** [comment]
Hi!

I have the same problem. I send a POST request using Postman:
`https://example.org/create?!!!!!!!!!!!!!!!!` 
and on the server side nginx logs following:
`"POST /create?%21%21%21%21%21%21%21%21%21%21%21%21%21%21%21%21 HTTP/1.1"`

When I send the same request from my program nginx logs it correctly without exclamation marks being escaped.

This is very painful because Postman nowhere shows the real request (even in Postman Console).

**Comment by glidester** [comment]
Hi,

I'm also running into issues with this 'auto-magic' url encoding in Postman stand-alone ver 6.0.10.

I have an rql enpoint I'm trying to exercise with Postman. Attempting to send "transactions?eq(date,20170322)" ends up at the server as "transactions?eq%28date,20170322%29".

The parenthesis are being url encoded even though the server does not need them to be but I have no control over Postman's behaviour regarding this.

Please can we have an option to disable this 'auto-magic' url encoding please.

Cheers

**Comment by sepo-one** [comment]
+1

**Comment by AuriR** [comment]
+1 This is super annoying.

**Comment by AuriR** [comment]
Important: This is NOT an issue in the Chrome app. Only the desktop app appears to have this issue.

**Comment by joeharrison714** [comment]
+1

**Comment by zlatinejc** [comment]
+1

**Comment by nbolser** [comment]
+1

**Comment by felipexw** [comment]
+1
