### ISSUE TITLE
postman-echo doesn't set cookies

### ISSUE THREAD

**Issue by adessaigne** [a85/POSTMan-Chrome-Extension#7710]
**Describe the bug**
When using https://postman-echo.com/cookies/set?foo1=bar1&foo2=bar2, it doesn't set the cookies

**To Reproduce**
1. Follow the documentation https://docs.postman-echo.com/?version=latest#3de3b135-b3cc-3a68-ba27-b6d373e03c8c and type the sample curl command
2. There's no cookies configured

**Expected behavior**
There are 2 cookies configured

**Analysis**
When looking at the response:
```
HTTP/1.1 302 Found
Content-Type: text/plain; charset=utf-8
Date: Wed, 27 Nov 2019 17:01:18 GMT
Location: /cookies
Server: nginx
set-cookie: foo1=bar1; Path=/
set-cookie: foo2=bar2; Path=/
set-cookie: sails.sid=s%3ATVZC8RqCMokaYU3D0W5T5baB_KOkMadF.paEvjICe%2FVAgZ9GiiqFxJMVUoMZmCFRo80%2B1tyRIrCo; Path=/; HttpOnly
```
It replies `set-cookie` and not `Set-Cookie`

**Comment by coditva** [comment]
Hey @adessaigne, the headers are case insensitive. So `set-cookie` is same as `Set-Cookie` or even `SeT-CoOkIe`.
