### ISSUE TITLE
console.log not working, slow UI and high CPU use

### ISSUE THREAD

**Issue by knottronix** [a85/POSTMan-Chrome-Extension#7722]
The bug is that using console.log in my test scripts or pre requests scripts no longer work. Also postman seems to take quite high CPU, and is very slow - takes 2 or 3 seconds to switch between / open requests

(I've tried restarting, reinstalling and done a lot of googling to no avail) 

**To Reproduce**
1. Start postman and Create new request. 
2. Add js code console.log("test);  to pre - request or test
3. open View - Developer - Show Dev Tools - 
4. Click "Console" to see the console.
5. note it has errors already just form startup
6. Run your request, and note nothing appears in the console. 

**Expected behavior**
Test to appear in the console log window

**App information (please complete the following information):**
 - Native app Version 7.12.0 win32 10.0.18362 / x64
 - OS: Windows 10 64 bit: OS build: 18362.476

**Additional context**
I think this only started when i updated to the new version. I have quite a lot of collections, some with some big image content in, however, the console.log still works on my older version of postman (7.10) on my other PC (same collections etc). I have some pretty fuky test code (using Eval) that automatically writes tests for the API requests to the console - or rather it did! (funky code at the end of this post in case it's relevant )

on start-up console has this content:

Initializing the global config
vendor-shared.js:518632 App updater event Object
vendor-shared.js:518632 Disconnected from Interceptor
2vendor-shared.js:518632 Could not find on EditorStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:518632

vendor-shared.js:518632 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@298] TypeError: Cannot read property 'subscribe' of undefined
    at APIListStore.subscribeToWorkspaceForAllAPIs (vendor-shared.js:512150)
    at APIListStore.isSocketConnected (vendor-shared.js:512059)
    at executeAction$$1 (vendor-shared.js:18348)
    at res (vendor-shared.js:18340)
    at reactionRunner (vendor-shared.js:19760)
    at Reaction$$1.onInvalidate (vendor-shared.js:19740)
    at Reaction$$1.runReaction (vendor-shared.js:19374)
    at runReactionsHelper (vendor-shared.js:19502)
    at reactionScheduler (vendor-shared.js:19480)
    at vendor-shared.js:19509
    at batchedUpdates (vendor-shared.js:265891)
    at tc (vendor-shared.js:265774)
    at reactionScheduler (vendor-shared.js:19509)
    at runReactions$$1 (vendor-shared.js:19485)
    at endBatch$$1 (vendor-shared.js:19197)
    at endAction (vendor-shared.js:18383)
    at executeAction$$1 (vendor-shared.js:18351)
    at SyncStatusStore.res (vendor-shared.js:18340)
    at SyncStatusStore.handleStatusChange (vendor-shared.js:511733)
    at EventEmitter.SyncStatusStore.pm.eventBus.channel.subscribe.event (vendor-shared.js:511647)
    at EventEmitter.emit (vendor-shared.js:50090)
    at _dispatch (vendor-shared.js:143288)
    at EventEmitter.<anonymous> (vendor-shared.js:143298)
    at EventEmitter.emit (/C:/ProgramData/knott/Postman/app-7.12.0/resources/app.asar/html/events.js:182)

Could not find on CollectionStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:518632
vendor-shared.js:518632 Could not find on CollectionStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:518632
find @ vendor-shared.js:51620
get parent @ vendor-shared.js:233212
trackDerivedFunction$$1 @ vendor-shared.js:18878
ComputedValue$$1.computeValue @ vendor-shared.js:18670
ComputedValue$$1.trackAndCompute @ vendor-shared.js:18655
ComputedValue$$1.get @ vendor-shared.js:18615
ObservableObjectAdministration$$1.read @ vendor-shared.js:21295
get @ vendor-shared.js:21559
editorInterface.setAdditionalData.Object @ vendor-shared.js:403158
trackDerivedFunction$$1 @ vendor-shared.js:18878
ComputedValue$$1.computeValue @ vendor-shared.js:18670
ComputedValue$$1.trackAndCompute @ vendor-shared.js:18655
ComputedValue$$1.get @ vendor-shared.js:18615
getAdditionalData @ vendor-shared.js:235219
render @ vendor-shared.js:482946
allowStateChanges$$1 @ vendor-shared.js:18392
(anonymous) @ vendor-shared.js:24695
trackDerivedFunction$$1 @ vendor-shared.js:18878
Reaction$$1.track @ vendor-shared.js:19404
reactiveRender @ vendor-shared.js:24689
h @ vendor-shared.js:265850
beginWork @ vendor-shared.js:265853
d @ vendor-shared.js:265881
f @ vendor-shared.js:265881
g @ vendor-shared.js:265882
m @ vendor-shared.js:265889
w @ vendor-shared.js:265888
batchedUpdates @ vendor-shared.js:265891
tc @ vendor-shared.js:265774
reactionScheduler @ vendor-shared.js:19509
runReactions$$1 @ vendor-shared.js:19485
endBatch$$1 @ vendor-shared.js:19197
transaction$$1 @ vendor-shared.js:20382
initializeContributions @ vendor-shared.js:235172
Promise.resolve.then.then.then @ vendor-shared.js:187178
vendor-shared.js:518632 App updater event {name: "checkForElectronUpdate", namespace: "app-update"}
vendor-shared.js:518632 App updater event {name: "checkForElectronUpdate", namespace: "app-update"}

in case relevent this is my funky auto test writing code:

pm.globals.set('loadUtils', function loadUtils() {
    let utils = {};
    utils.writePropertyCheckTestCodeToConsole = function writePropertyCheckTestCodeToConsole() {
        let jsonData = JSON.parse(responseBody);
        eval( //make function in the context of the utils function
            `  function quote(key){
                if(!isNaN(key)){
                    return key;
                }
                return "'" + key + "'";
            }
            `);
        //******************* THIS WRITES (to console) A 'HAS PROPRTY, TYPE and VALUES' TEST FOR THE CURRENT RESPONSE 4 levels DEEP //***************************
        var maxStringValueLengthToWroteTestFor = 50;
        var output=`pm.test("Response has all expected fields (3 levels deep)", function () {\n`;
        var valueOutput = `pm.test("Selected Response values are as expected  (3 levels deep)", function () {\n`;
        var typesOutput = `pm.test("All Response properties are of the expected type (3 levels deep)", function () {\n`;
        Object.keys(jsonData).forEach(function(key) {
            //1st level
            output = output + `    pm.expect(jsonData).to.have.property("${key}");\n` ;
            console.log(`key: ${key} is ${typeof jsonData[key]}`);
            switch (typeof jsonData[key]) {
                case 'string': 
                    if(jsonData[key].length <= maxStringValueLengthToWroteTestFor){
                        valueOutput = valueOutput + `       pm.expect(jsonData.${key} ==  \`${jsonData[key]}\`).to.be.true;\n` ; 
                    }
                    typesOutput = typesOutput + `       pm.expect(jsonData.${key}).to.be.a('string');\n` ;
                break;
                case 'number': 
                    valueOutput = valueOutput + `       pm.expect(jsonData.${key} ==  ${jsonData[key]}).to.be.true;\n` ;
                    typesOutput = typesOutput + `       pm.expect(jsonData.${key}).to.be.a('number');\n` ;
                 break;
                case 'boolean': 
                    valueOutput = valueOutput + `       pm.expect(jsonData.${key} ==  ${jsonData[key]}).to.be.true;\n` ;
                    typesOutput = typesOutput + `       pm.expect(jsonData.${key}).to.be.a('boolean');\n` ;
                break;
                case 'object': 
                    //typesOutput = typesOutput + `       pm.expect(jsonData.${key}).to.be.a('object');\n` ;
                    if(jsonData[key] !== null){
                        //2nd level
                        Object.keys(jsonData[key]).forEach(function(nKey) {
                          console.log(`key: ${nKey} is ${typeof jsonData[key][nKey]}`);
                          output = output + `        pm.expect(jsonData[${quote(key)}]).to.have.property("${nKey}");\n` ;
                    
                         switch (typeof jsonData[key][nKey]) {
                         case 'string': 
                               if(jsonData[key][nKey].length <= maxStringValueLengthToWroteTestFor){
                                   valueOutput = valueOutput + `       pm.expect(jsonData['${key}']['${nKey}'] ==  \`${jsonData[key][nKey]}\`).to.be.true;\n` ;
                               }
                               typesOutput = typesOutput + `       pm.expect(jsonData['${key}']['${nKey}']).to.be.a('string');\n` ;
                           break;
                            case 'number': 
                                valueOutput = valueOutput + `       pm.expect(jsonData['${key}']['${nKey}'] ==  ${jsonData[key][nKey]}).to.be.true;\n` ;
                                 typesOutput = typesOutput + `      pm.expect(jsonData['${key}']['${nKey}']).to.be.a('number');\n` ;
                             break;
                            case 'boolean': 
                                valueOutput = valueOutput + `       pm.expect(jsonData['${key}']['${nKey}']==  ${jsonData[key][nKey]}).to.be.true;\n` ;
                                typesOutput = typesOutput + `       pm.expect(jsonData['${key}']['${nKey}']).to.be.a('boolean');\n` ;
                            break;                    
                        }
                        // 3rd level 
                        if(typeof jsonData[key][nKey] === 'object' && jsonData[key][nKey] !== null){
                            console.log(`key: ${nKey} is ${typeof jsonData[nKey]}`);
                            Object.keys(jsonData[key][nKey]).forEach(function(nnKey) {
                                switch (typeof jsonData[key][nKey][nnKey]) {
                                     case 'string': 
                                        if(jsonData[key][nKey][nnKey].length <= maxStringValueLengthToWroteTestFor){
                                           valueOutput = valueOutput + `       pm.expect(jsonData[${quote(key)}][${quote(nKey)}][${quote(nnKey)}] ==  \`${jsonData[key][nKey][nnKey]}\`).to.be.true;\n` ;
                                        }
                                           typesOutput = typesOutput + `       pm.expect(jsonData[${quote(key)}][${quote(nKey)}][${quote(nnKey)}]).to.be.a('string');\n` ;
                                       break;
                                        case 'number': 
                                            valueOutput = valueOutput + `       pm.expect(jsonData[${quote(key)}][${quote(nKey)}][${quote(nnKey)}] ==  ${jsonData[key][nKey][nnKey]}).to.be.true;\n` ;
                                             typesOutput = typesOutput + `      pm.expect(jsonData[${quote(key)}][${quote(nKey)}][${quote(nnKey)}]).to.be.a('number');\n` ;
                                         break;
                                        case 'boolean': 
                                            valueOutput = valueOutput + `       pm.expect(jsonData[${quote(key)}][${quote(nKey)}][${quote(nnKey)}]==  ${jsonData[key][nKey][nnKey]}).to.be.true;\n` ;
                                            typesOutput = typesOutput + `       pm.expect(jsonData[${quote(key)}][${quote(nKey)}][${quote(nnKey)}]).to.be.a('boolean');\n` ;
                                        break;                    
                                    }
                            output = output + `            pm.expect(jsonData[${quote(key)}][${quote(nKey)}]).to.have.property("${nnKey}");\n` ;
                            
                            });
                        } 
                    });
            }    
                break;
        }
            
             //console.log(`${typeof Object[key]} is typeof ${key}` );
            

        });
        output = output + `});`;
        typesOutput = typesOutput + `});`;
        valueOutput = valueOutput + `});`;
        console.log(output + '\n\n\n' + typesOutput + '\n\n\n' + valueOutput);   
        //**************************************************************************************************************************
    }
    return utils;
} + '; loadUtils();');
tests['Utils initialized'] = true;

**Comment by ritwijsinha** [comment]
Hello @knottronix,

`console.log()` inside your Pre-request / Test scripts can be seen in Postman Console.

To open Postman Console, either click on the Console icon in the Footer:

![image](https://user-images.githubusercontent.com/19693841/69951578-818ca580-151b-11ea-8293-fd3f27d62f07.png)

or open it from the Menu:

![image](https://user-images.githubusercontent.com/19693841/69951613-923d1b80-151b-11ea-9fd5-d98a382ed590.png)

(Note: ⌥⌘C is for macOS, you can use `Ctrl + Alt + C` on Windows)


Cheers!

**Comment by knottronix** [comment]
thanks @ritwijsinha  - but the console.log is not working. I know where it is, as I use it all the time, until it stopped working

**Comment by ritwijsinha** [comment]
@knottronix 

Is it possible that you have the 'Log' filtered out? It seems to be working for me on Postman v7.12.0

Here is how you can toggle the filters:

![image](https://user-images.githubusercontent.com/19693841/69961065-fd451d00-1530-11ea-81da-6eac4b736dbd.png)

**Comment by knottronix** [comment]
Many thanks ritwijsinha - it was not that the log was not selected, but that the console.log was now appearing in postman console, whereas in previous version of postman the logs would come under View >> Developer >> Show Dev Tools >> select console tab. So unless I am going crazy (which is possible!) they moved. 

Many thanks again for taking the time to read all this and help me - much appreciated!

**Comment by ritwijsinha** [comment]
@knottronix 

Glad to help 😄

Cheers! 🎉
