### ISSUE TITLE
Dim app on HDR display

### ISSUE THREAD

**Issue by RobinTTY** [a85/POSTMan-Chrome-Extension#7723]
**Describe the bug**
The Postman app is very dim on an HDR enabled display.

**To Reproduce**
Steps to reproduce the behavior (only applies to HDR displays):
1. Press Windows button
2. Search for HDR
3. Open windows HD color settings
4. Set slider "Play HDR games and apps" to enabled
5. Start postman app

**Expected behavior**
App starts with correct color profile.

**Workaround**
If the parameter "--force-color-profile sRGB" is supplied to the app at startup the app will be displayed correctly.

**Screenshots**
Without workaround(chrome for comparison):
![IMG_20191202_151816](https://user-images.githubusercontent.com/27669180/69967120-12618200-1518-11ea-8903-608de401a503.jpg)

With workaround:

![IMG_20191202_151904](https://user-images.githubusercontent.com/27669180/69967162-20af9e00-1518-11ea-9d2e-a24fd27774be.jpg)

**App information:**
 - Postman Version v7.12.0
 - OS: Windows 10 1909

**Additional context**
Problem was resolved in the case of VSCode by updating the app to Electron 6: microsoft/vscode#68069

**Comment by RobinTTY** [comment]
Not an actual bug, brightness can be adjusted trough the "SDR content appearance" slider in the "windows hd color settings". My fault.

**Comment by seanocali** [comment]
> Not an actual bug, brightness can be adjusted trough the "SDR content appearance" slider in the "windows hd color settings". My fault.

This doesn't solve it at all and you were right the first time it's a bug. All Electron apps had this problem, many were fixed like VS Code.

**Comment by RobinTTY** [comment]
> > Not an actual bug, brightness can be adjusted trough the "SDR content appearance" slider in the "windows hd color settings". My fault.
> 
> This doesn't solve it at all and you were right the first time it's a bug. All Electron apps had this problem, many were fixed like VS Code.

I'm not knowledgeable on this subject so I can't say if this should be considered a bug or not. In my case at least one other app was behaving in the same way (Chromes built in pdf viewer) and after changing the SDR content apperance it was fixed for me without the colors being off so I considered it fixed.

**Comment by MeromTh** [comment]
just start with `Postman.exe --force-color-profile srgb`

**Comment by numaanashraf** [comment]
Re-opening this issue to investigate further. There should be a way for us to detect this and auto apply any workarounds that's needed.

**Comment by lkiii** [comment]
Having the same issue as described here

**Comment by numaanashraf** [comment]
This seems to be an issue with the underlying version of Electron we are using and there are [reports](https://github.com/microsoft/vscode/issues/68069#issuecomment-540828899) that this is addressed in Electron 6.x. Postman is currently upgrading its Electron version to 7.x and we'll post updates here when we have a public build out.

**Comment by harryi3t** [comment]
@RobinTTY @seanocali @MeromTh @lkiii 
We've pushed an update involving updating to Electron v7 on our early access canary channel that should resolve this issue 🎉. Do try it out and let us know.

You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by RobinTTY** [comment]
@harryi3t the issue is resolved for me on the canary channel. Thank you!

**Comment by twitharshil** [comment]
@RobinTTY @seanocali @MeromTh @lkiii
We’ve pushed the updates in our stable app v7.25.1 that should fix this issue 🎉. 
Feel free to reopen the issue if you are still facing this problem on Postman v7.25.1 onwards.
