### ISSUE TITLE
Indicator to highlight tested request

### ISSUE THREAD

**Issue by kdfemi** [a85/POSTMan-Chrome-Extension#7724]
**Is your feature request related to a problem? Please describe.**
As frontend developer i want to be able to mark API Endpoint i have implemented on my App, this will easy my workflow in situation where API are not properly arranged or categorized

**Describe the solution you'd like**
A check box to mark API Endpoint as implemented

**Comment by preethammavin** [comment]
@kdfemi I dont think this is something we would pick up in the short or mid-term as a feature request, but you could unblock yourself in multiple ways either naming the request to implemented or now, or would keep two folders in the collection one which has designed ones and another implemented ones. 

I personally use forks to track what needs to be implemented to what is implemented.
