### ISSUE TITLE
Escape char is appended to parameter when clicking on a URL to open in new tab

### ISSUE THREAD

**Issue by a-harvie** [a85/POSTMan-Chrome-Extension#7726]
**Describe the bug**
When a clickable URL is returned in a request, surrounded by escaped quotes, clicking on the URL carries the escape character in the final parameter of the new request.

The behaviour is seen whether the original response is viewed in "pretty" or "raw".

**To Reproduce**
1. Send a GET request in the desktop UI that returns a URL in escaped quotes (e.g. a jsonp response.)
2. Click on the URL in the response
3. Inspect the final parameter in the newly generated request
4. It has the escape character appended

**Expected behavior**
The newly generated request should not have an escape character appended.

**Screenshots**
Step 1/2: GET request that returns a URL in escaped quotes:

![postman_screenshot_01](https://user-images.githubusercontent.com/2982612/69967742-175a0d80-14e7-11ea-9df1-0602b8515356.png)

Step 3/4: escape character is appended:

![postman_screenshot_02](https://user-images.githubusercontent.com/2982612/69967797-25a82980-14e7-11ea-8c3d-71f169f42750.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.12.0
 - OS: macOS Mojave 10.14.6

**Additional context**
There are several open issues relating to escape chars, so this may be related, but I couldn't see one that obviously described the behaviour I'm seeing.

**Comment by kevin-postman** [comment]
@kamalaknn curious as I have never returned responses from API endpoints with escaped text. It seems the \" at the start of the url is removed.. and the last " is removed.. I assume that in this case we should never end a URL line with \, is that the gist of this issue? Not sure if there are other scenarios where a \ would be valid.

**Comment by pankajk07** [comment]
Hey @a-harvie, we have fixed this issue as part of `v7.35` release. Please update your app and do give it a try.
