### ISSUE TITLE
Current workspace in test scripts

### ISSUE THREAD

**Issue by midrissi** [a85/POSTMan-Chrome-Extension#7727]
**Is your feature request related to a problem? Please describe.**
I have developed a [framework](https://github.com/izmjs/izmjs) that auto-generate the postman documentation from the source code. The developer can also synchronize the generated documentation with an existing postman collection.

If the developer has a large number of collections in different workspaces, it will be difficult for him to get the collection identifier.

Postman has an awesome API, showing collections of a specific workspace. But, it does not give me the option to get the current space from test scripts.

**Describe the solution you'd like**
It would be great if the postman sandbox exposes the current workspace information (Name, ID and the type).

**Comment by shamasis** [comment]
I see your use-case, but if I may, I would rather suggest a different approach than the scripts knowing workspace related info. The scripts knowing workspace will cause unexpected coupling while executing collections out of context of workspace - say as a monitor or say in CI.

I'm afraid that this may not be possible at the moment. Closing this.

Meanwhile, I am looping in @vkaegis to assimilate aspects from here into additional improvements that he is already working on, for collection identification.
