### ISSUE TITLE
Code Snippet in python Request not working

### ISSUE THREAD

**Issue by andreaperezisla** [a85/POSTMan-Chrome-Extension#7732]
Good morning,
I'm trying to make a POST request from Python to upload a pdf file to an API. When I do it in Postman, it works fine, returning some info that I need for following steps. However, when i generate code snippet to use it in python, it doesnt work, showing a 500 error message from the API. If u could help me could be great :D 

I'm using Python 3.7.0 in Windows 10 and Postman 7.12.0

Attached is the code snippet

**Comment by arlemi** [comment]
@andreaperezisla Avoid sharing any file containing private keys (such as API Keys, Postman Tokens etc.), please remove your shared file. :)  

Regarding your issue, the 500 error implies a server error, are you able to get any logs from the server-side? That'd help.
