### ISSUE TITLE
Undo-shortcut doesn't work while naming collection/request

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7733]
**Describe the bug**
Unable to undo ( Cmd + Z) an action while adding a name to the collection, folder or request

**To Reproduce**
1. Create a collection
2. Edit the collection
3. Change the name of Collection/Folder/Request
4. Undo (Cmd + Z) doesn't work

**Expected behavior**
Be able to perform the action for easier progress

**Screenshots**

![UndoAction](https://user-images.githubusercontent.com/47771757/70079304-7bd1b580-162a-11ea-96d1-f2a02a4e9368.gif)

**App information (please complete the following information):**
 - App Type - Native app
 - Postman Version - v.7.12
 - OS: macOS Catalina

**Additional context**
- The action doesn't work for Name of the **Examples** for a request
- Also, for the **Comments** - The undo/refresh button takes care of it for now

![Comment:Example](https://user-images.githubusercontent.com/47771757/70080109-fa7b2280-162b-11ea-9742-bc808648d223.png)

- **Works well** for adding a description for a collection, folder or request and for others

**Comment by kamalaknn** [comment]
@Raj-postman This is fixed on the latest version of Postman.
