### ISSUE TITLE
Error Importing swagger 2.0 spec with absolute path reference

### ISSUE THREAD

**Issue by boubech** [a85/POSTMan-Chrome-Extension#7735]
**Describe the bug**
Unable to import OpenFile 2.0 with absolute path reference.

**To Reproduce**
1. Go to 'Import'
2. Go to 'Import From Link'
3. Scroll down to 'https://gitlab.com/kathra/kathra/kathra-services/kathra-catalogmanager/kathra-catalogmanager-api/raw/1.1.x/swagger.yml'
4. Click to 'Generation collection'

**Expected behavior**
An collection should be created, but the message "Error Importing swagger 2.0" occurred

**Workaround**
I have to modify the section "responses" to add attribute "content" (from OpenApi 3.0 specs), this attribute is not specified in Swagger 2.0.

***With error***
>
      responses:
        200:
          description: "CatalogEntry with providerId"
          schema:
            $ref: "https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry"
>

***With workaround***
> 
      responses:
        200:
          description: "CatalogEntry with providerId"
          content:
            schema:
                $ref: "https://gitlab.com/kathra/kathra/kathra-core/kathra-core-api/raw/1.1.x/swagger.yml#/definitions/CatalogEntry"

> 

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.12.0
 - OS: Ubuntu 19.10

**Comment by VShingala** [comment]
@boubech I was able to successfully import specified schema in latest Postman App. Can you try importing your schema once in latest app.

**App information**
Postman for Mac
Version 7.22.1
OS X 19.4.0 / x64

**Comment by umeshp7** [comment]
Hey @boubech! I tried importing the schema you provided, I was successfully able to import it as API and generate collection. 
Closing this for now. Feel free to reopen if the issue persists.
