### ISSUE TITLE
Leaving a team as the last member and joining a new team orphans collections in the old team.

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7736]
_This is a bug discovered internally and is being logged by Postman for tracking it publicly as well._

**Describe the bug**
Currently when you are the last member in a team and just leaving a team and **not** joining a new team option to move data to a personal workspace is provided.

But when you are the last member in a team and join a new team the collections within the old team are orphaned. Collections/Environments should be transferred to the user's personal workspace when as it happens when the last user leaves a team.

**To Reproduce**
Steps to reproduce the behaviour:
1. Leave a team as the last member
2. Collections in the Team will not be transferred to a personal workspace.

**Expected behaviour**
Collections/Environments should be moved to the last user to leave a team even if they join a new team.

**Comment by sankalp0o** [comment]
Hey @xk0der , this issue has been fixed. I'm closing this ticket but let us know the transfer doesn't work as expected or if something can be improved. Thanks for reporting!
