### ISSUE TITLE
Circular references can't be resolved

### ISSUE THREAD

**Issue by sroettering** [a85/POSTMan-Chrome-Extension#7740]
**Describe the bug**
When importing an OpenAPI 3 YAML file with circular references the import fails.
It is arguable that having circular references is a bad design, but I can't change it easily.

**To Reproduce**
1. Create a yaml file with a circular reference (author <-> post example should work)
2. Import the file into postman
3. The import fails and the console shows a circular reference error

**Expected behavior**
I would expect postman to be able to import circular references.

**Screenshots**
![image](https://user-images.githubusercontent.com/2598613/70142217-0650fe00-1699-11ea-824c-83dbf0273756.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.13.0
 - OS: macOS mojave

**Comment by abhijitkane** [comment]
@sroettering Can you check with v7.14? I'm seeing upto 4 levels of circular references faked for a schema (eg. https://gist.github.com/abhijitkane/bd57dba53921d5470aa5971cf3189a58)

**Comment by sroettering** [comment]
I updated postman to 7.14 and tried to import my schema file again and it still shows the toast message in the bottom right corner that it could not be imported. However, I do not get any console messages anymore, so I can't tell why it failed.
Loading the schema into https://editor.swagger.io/ works fine without any errors. So I guess the file is valid.

**Comment by abhijitkane** [comment]
@sroettering Can you attach a file you're seeing this error for? You can also email the file to help@getpostman.com.

**Comment by sroettering** [comment]
Sent an email with the file. Hope it helps.

**Comment by augustocb23** [comment]
Any progress?
[Swagger UI](https://sandbox.simboxplay.com.br:5001/index.html)
[Schema](https://sandbox.simboxplay.com.br:5001/swagger/v1/swagger.json)

I'm with the same problem. The model `Jogo` haves a reference to `UltimaVersao`, of `VersaoJogo` type, that haves a reference to `Jogo` again.

**Comment by sroettering** [comment]
I can confirm that my example file works now in version 7.19.1
So if @augustocb23 case is resolved as well, I guess this issue can be closed.

**Comment by umeshp7** [comment]
@sroettering Thank you for confirming. 
@augustocb23 Couldn't download the schema from the links you have provided. 
I request you to try it in v7.19.1.

**Comment by augustocb23** [comment]
Sorry, there was a problem with my link 😬

Now is working well on v7.19.1. The issue can be closed.
Thanks!

**Comment by Zino-ctrlZ** [comment]
Hi what package is being used to import the OpenApi document here ? I'm running into similar issues using `openapi-to-postmanv2' in nodeJs
