### ISSUE TITLE
Curl Command cannot be imported

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#7741]
**Describe the bug**
I'm unable to import a curl command using Postman in the latest version of Postman (7.13.0)
**To Reproduce**
Curl : curl -i -k -H"Authorization: Bearer key" https://google.com
1. Go into Postman and click 'Import'
2. Click 'Paste Raw Text' and paste the curl command inside
3. Click 'Import'

**Expected behavior**
Postman will shown a notification saying "Error while importing Curl: Cannot read property 'write' of undefined" and will not import the curl command.

**Screenshots**
![image](https://user-images.githubusercontent.com/49036568/70151610-b88dc300-16a3-11ea-91f7-da26e64e7686.png)

**App information (please complete the following information):**
 - App Type:Native App
 - Postman Version: 7.13.0
 - OS: win32 10.0.17134 x64

**Comment by abhijitkane** [comment]
@distologyProgrammer Can you add a space after `-H`? That should unblock you for now.  This seems to be an issue with commander (the bash input parsing lib we're using). Will require deeper investigation.

**Comment by ghost** [comment]
That seemed to work thank you.
