### ISSUE TITLE
Undo (Cmd + Z) does not work while renaming request name in a tab

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#7745]
**Describe the bug**
Undo shortcut does not work while editing request name in a tab.

**To Reproduce**
1. Create a reqest
2. Open it in a tab
3. Click on the pen icon to edit request name
4. Type something
5. Try Cmd + Z.

Observe no undo.

**Expected behavior**
Undo.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.13.0
 - OS: macOS Catalina

**Comment by nik72619c** [comment]
This issue has been fixed in Postman v7.19.1.
