### ISSUE TITLE
Bad request (400) for NTLM auth inherited by parent while running collection

### ISSUE THREAD

**Issue by snkkid99** [a85/POSTMan-Chrome-Extension#7747]
Same problem that was in the Issue #4092 except that I have a "Bad request (400)" 
Tested with Postman v7.13.0
* With NTLM Authentication inherited by parent the 3rd query fail
![RunnerProbelm](https://user-images.githubusercontent.com/11087423/70230038-c1d86780-1757-11ea-94a9-091c549736ef.png)
* The problem is solved when I set the authentication as NTLM directly in the query
![RunnerProbelm](https://user-images.githubusercontent.com/11087423/70230797-67d8a180-1759-11ea-97ca-14435559551c.png)

**To Reproduce**
1 Create a new collection
2 Set the Authorization of the colletion as NTLM
3 Create a request to query a url that need an NTLM authentication
4 Set the authorisation of the query as inherited from parent
5 run the query in the "runner" with 10 Iterations

**Comment by coditva** [comment]
@snkkid99 Thanks for reporting!
This seems to be a problem in `postman-runtime`'s state management for NTLM auth. We'll let you know when we have a fix. Stay tuned!

**Comment by CedricHg** [comment]
Any updates on this? Still happens in Postman For Windows v10.13.5

**Comment by louagej** [comment]
Any idea when this will be fixed?

**Comment by vytas-soderholm** [comment]
Also running into this.

**Comment by NupurSingla2288** [comment]
It is still happening with postman v10.17

**Comment by zewa666** [comment]
yep, still happening with the most recent update. But as someone already mentioned placing the auth on every individual request vs inheriting it solves the problem

**Comment by sandeep-singh-pstmn** [comment]
Hey everyone, We are pleased to inform you that the issue has been resolved with the latest update (v11.1.0). We kindly request that you update your application and verify the fix.

https://github.com/postmanlabs/postman-app-support/assets/85243040/11817023-b517-4189-b741-9579a0ced8d9

**Comment by Dustin4444** [comment]
> Same problem that was in the Issue #4092 except that I have a "Bad request (400)" 
> Tested with Postman v7.13.0
> * With NTLM Authentication inherited by parent the 3rd query fail
> ![RunnerProbelm](https://user-images.githubusercontent.com/11087423/70230038-c1d86780-1757-11ea-94a9-091c549736ef.png)
> * The problem is solved when I set the authentication as NTLM directly in the query
> ![RunnerProbelm](https://user-images.githubusercontent.com/11087423/70230797-67d8a180-1759-11ea-97ca-14435559551c.png)
> 
> **To Reproduce**
> 1 Create a new collection
> 2 Set the Authorization of the colletion as NTLM
> 3 Create a request to query a url that need an NTLM authentication
> 4 Set the authorisation of the query as inherited from parent
> 5 run the query in the "runner" with 10 Iterations
>
