### ISSUE TITLE
Documentation - delay between scrolling and syntax highlighting

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7748]
**Is your feature request related to a problem? Please describe.**
There is some latency between when scrolling happens and the text is highlighted correctly. 
https://www.loom.com/share/cf0ab3511f464ceab78e1a0b0480adf2

**To Reproduce**
1. Open any documentation - https://docs.postman-echo.com/?version=latest
2. Notice the latency rendering the syntax highlighting when scrolling. 

**Describe the solution you'd like**
See syntax highlighting on the documentation rendering upon open the doc.

**Comment by godfrzero** [comment]
There is an intentional delay after a scroll, this is not a bug. @Raja-Simha As long as we're rendering the entire doc in one shot, we can't syntax highlight the entire document.
