### ISSUE TITLE
Object spread operator triggers incorrect warning in script editors

### ISSUE THREAD

**Issue by Quozzo** [a85/POSTMan-Chrome-Extension#7749]
**Describe the bug**
The object spread operator is being displayed as a syntax error by the linting tool with a yellow exclamation mark on the line numbers. The JavaScript run as expected.

**To Reproduce**
Type the object spread operator, something like:
```
const obj1 = {foo: "bar"}
const obj2  = {lorem: "ipsum"}
    
const obj = {...obj1, ...obj2}
console.log(obj)
```

**Expected behavior**
The linting tool not to complain that this is expecting the closing bracket instead of the spread operator (...) which could also cause the linting tool to experience an unrecoverable error.

![image](https://user-images.githubusercontent.com/3494473/70244730-e4c14680-176c-11ea-953c-3fc485c8eec8.png)
![image](https://user-images.githubusercontent.com/3494473/70244783-fc003400-176c-11ea-92f4-45a5239bd998.png)

**App information (please complete the following information):**
Postman for Windows
Version 7.13.0
win32 10.0.18362 / x64

**Comment by pankajk07** [comment]
Fixed as part of v7.24
