### ISSUE TITLE
Google Says Postman is unsecure and there for will not allow API connections

### ISSUE THREAD

**Issue by sinistersparrow** [a85/POSTMan-Chrome-Extension#7750]
**Describe the bug**
When attempting Oauth2 connections to google-based api's, Google states that the Postman embedded browser function is not secure and will not allow logging in to receive API Token.

**To Reproduce**
1.  Create an OAuth 2.0 client ID
    Go to Google Console -> API -> OAuth consent screen
        Add getpostman.com to the Authorized domains. Click Save.
    Go to Google Console -> API -> Credentials
        Click 'Create credentials' -> OAuth client ID -> Web application
            Name: 'getpostman'
            Authorized redirect URIs: https://www.getpostman.com/oauth2/callback
    Copy the generated Client ID and Client secret fields for later use

2. In Postman select Authorization tab and select "OAuth 2.0" type. Click 'Get New Access Token'

    Fill the GET NEW ACCESS TOKEN form as following
        Token Name: 'Google OAuth getpostman'
        Grant Type: 'Authorization Code'
        Callback URL: https://www.getpostman.com/oauth2/callback
        Auth URL: https://accounts.google.com/o/oauth2/auth
        Access Token URL: https://accounts.google.com/o/oauth2/token
        Client ID: Client ID generated in the step 2 (e.g., '123456789012-abracadabra1234546789blablabla12.apps.googleusercontent.com')
        Client Secret: Client secret generated in the step 2 (e.g., 'ABRACADABRAus1ZMGHvq9R-L')
        Scope: see the Google docs for the required OAuth scope (e.g., https://www.googleapis.com/auth/cloud-platform)
        State: Empty
        Client Authentication: "Send as Basic Auth header"
    Click 'Request Token' and 'Use Token'

**Expected behavior**
A token value will be inserted into the "Access Token" block of the Authorization Tab

**Screenshots**
https://i.stack.imgur.com/58ZrV.png
https://i.stack.imgur.com/y7d47.png
https://i.stack.imgur.com/0SAMf.png

**App information (please complete the following information):**
 - App Type: Native App
 - Postman: Version v7.13.0
 - OS: Windows 10 AND MAC OS Catalina

**Additional context**
I have turned off SSL certificate verification and the response is not different

**Comment by a85** [comment]
This is apparently a change in behavior by Google against all embedded browsers. We are tracking this issue closely.

**Comment by kamalaknn** [comment]
Hey @sinistersparrow 

Thanks for reporting this issue. We are tracking issues related to unsupported or embedded browser errors in OAuth 2.0 and login flows in #7700 

I'm closing this as a duplicate. Please follow the original issue for updates.
