### ISSUE TITLE
Blank page appears when creating new mock server

### ISSUE THREAD

**Issue by JoelAzevedo** [a85/POSTMan-Chrome-Extension#7751]
**Describe the bug**
When I create a mock service, it doesn't show nothing on step "1. Select a collection to mock"

**To Reproduce**
1. Go to '+ New' orange button and click on it
2. On Create New, click 'Mock Server'
3. On step '1. Select a collection to mock' it appears a blank page.

**Expected behavior**
It was expected to see the corresponding options.

**Screenshots**
[Link to error (image) ](https://i.imgur.com/zyCDThV.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.13.0
 - OS: Windows 10 Pro, Version 1903, OS build: 18362.476

**Comment by dushyantchillale** [comment]
@JoelAzevedo Thanks for raising the issue!
Could you please let me know if this was an issue you saw once or if you're still able to reproduce the issue.

**Comment by JoelAzevedo** [comment]
Hi @dushyantchillale, you're welcome. I can still reproduce the issue. In fact, I just tested it now, same Postman version and same OS.

**Comment by dushyantchillale** [comment]
@JoelAzevedo Thanks for your response. Could you please write into Postman Support via email : help@getpostman.com from the email used to login to Postman? We'll take a look into it!

**Comment by JoelAzevedo** [comment]
Sure. Already sent.

**Comment by vvs11** [comment]
This is fixed in version 7.18.
