### ISSUE TITLE
Run In Postman Button is not Importing Collection

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7752]
filing on behalf of the user. 

**Describe the bug**
Run In Postman button is not importing collection into Postman App. 
When clicking on the button nothing happens. 

**To Reproduce**
1. Go to published documentation and click the Run In Postman button in the top right corner. 
2. Check Postman app for collection, the collection is not there. 

**Expected behavior**
Expect for Collection to import into App or to provide feedback that Collection was not imported. 

Additional investigation shows the Chrome browser where the button has clicked that request is stalled and canceled:

<img width="1503" alt="Screen Shot 2019-12-05 at 10 22 12 AM" src="https://user-images.githubusercontent.com/5624835/70262433-2dff9f00-1749-11ea-8334-7540b8e7674d.png">

When looking at logs in Postman App: 

<img width="796" alt="Screen Shot 2019-12-05 at 10 23 10 AM" src="https://user-images.githubusercontent.com/5624835/70262459-3e177e80-1749-11ea-80c2-661d8fec8e62.png">

postman://app/collections/import/XXXXXXXX?referrer=XXXXX 

However, a workaround is to click on the link itself and paste it into the browser address bar itself. 
But for a casual user for discovery, this is not an optimal option for the company marketing their API.

**Comment by stcalica** [comment]
Windows seems to have an issue with importing when the URL gets very long, as data about a collection seems to be passed in the URL to import, a workaround is to try to reduce the size of the collection or environment. Or forgo the environment for the time being.

**Comment by dhineshwiz** [comment]
Fix for this is deployed in Postman APP V7.20.0.
Closing the issue for now, please feel free to reopen the issue, if you face it again.

**Comment by Bhasski** [comment]
I am facing import issues while trying to import the 1up health collection that they have given in Docs.
No such specific error in logs 

[20392][1649159005243][main][info]["ProtocolHandler~handleOpenUrl: postman://app/collections/import/e5259db17c571bafddc4?referrer=https%3A%2F%2F1up.health%2F#?env%5B1upHealth%20API%20Variables%5D=W3sia2V5IjoiY2xpZW50X2lkIiwidmFsdWUiOiJnZXRfZnJvbV9xdWlja19zdGFydF9ndWlkZSIsImVuYWJsZWQiOnRydWUsInR5cGUiOiJ0ZXh0In0seyJrZXkiOiJjbGllbnRfc2VjcmV0IiwidmFsdWUiOiJnZXRfZnJvbV9xdWlja19zdGFydF9ndWlkZSIsImVuYWJsZWQiOnRydWUsInR5cGUiOiJ0ZXh0In0seyJrZXkiOiJjb2RlIiwidmFsdWUiOiJzZXRfYnlfc3RlcHNfMV9vcl8yIiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6InRleHQifSx7ImtleSI6ImFjY2Vzc190b2tlbiIsInZhbHVlIjoic2V0X2J5X3N0ZXBzXzNfb3JfNCIsImVuYWJsZWQiOnRydWUsInR5cGUiOiJ0ZXh0In0seyJrZXkiOiJyZWZyZXNoX3Rva2VuIiwidmFsdWUiOiJzZXRfYnlfc3RlcHNfM19vcl80IiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6InRleHQifV0="]

this is what I am seeing in logs .. GUI says fails to import

**Comment by Bhasski** [comment]
![1up Health  collection import error](https://user-images.githubusercontent.com/7147842/161752990-466ff3bf-6ed6-46d8-9c63-44e9b6785178.png)

**Comment by bhargavkaranam** [comment]
@Bhasski The collection that is on their [website](https://1up.health/docs/start/quick-start-guide/postman-collection) seems to have been deleted. Hence, the import is erroring out. There is another Run in Postman button at the bottom of the same page, the import via that button is working. Can you check?

This is the [link](https://app.getpostman.com/run-collection/8cedbf1d94c912f8023a#?env%5B1upHealth%20API%20Variables%5D=W3sia2V5IjoiY2xpZW50X2lkIiwidmFsdWUiOiJnZXRfZnJvbV9xdWlja19zdGFydF9ndWlkZSIsImVuYWJsZWQiOnRydWUsInR5cGUiOiJ0ZXh0In0seyJrZXkiOiJjbGllbnRfc2VjcmV0IiwidmFsdWUiOiJnZXRfZnJvbV9xdWlja19zdGFydF9ndWlkZSIsImVuYWJsZWQiOnRydWUsInR5cGUiOiJ0ZXh0In0seyJrZXkiOiJjb2RlIiwidmFsdWUiOiJzZXRfYnlfc3RlcHNfMV9vcl8yIiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6InRleHQifSx7ImtleSI6ImFjY2Vzc190b2tlbiIsInZhbHVlIjoic2V0X2J5X3N0ZXBzXzNfb3JfNCIsImVuYWJsZWQiOnRydWUsInR5cGUiOiJ0ZXh0In0seyJrZXkiOiJyZWZyZXNoX3Rva2VuIiwidmFsdWUiOiJzZXRfYnlfc3RlcHNfM19vcl80IiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6InRleHQifV0=) that you can use to import.

**Comment by Bhasski** [comment]
Yeah . That worked .
Thanks for prompt reply. I struggled because I couldn't get from the
message and logs .

Regards
Bhaskar Taneja
