### ISSUE TITLE
Run in Postman on Explore pages doesn't import environment

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7753]
**Describe the bug**
On explore.getpostman.com, clicking Run in Postman, does not import the environment published with the Collection.

Clicking Run in Postman on the documentation page _does_ import the published environment.

**To Reproduce**
1. Go to: https://explore.postman.com/team/3spqmTWCHCEzYt
2. Click Run in Postman
3. See no environment is imported
4. Go to: https://documenter.getpostman.com/view/656533/S1EH21Qu?version=latest
5. Click Run in Postman
6. See environment is imported

**Expected behavior**
Clicking Run in Postman imports a published environment, on both Explore and documentation pages.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Web dashboard (Chrome)
 - Postman Version: 7.12.0
 - OS: MacOS Catalina

**Comment by dhineshwiz** [comment]
This is fixed on https://explore.postman.com now, closing the issue
