### ISSUE TITLE
Getting Blank Black screen frequently tried reinstalling multiple times

### ISSUE THREAD

**Issue by fazilbashasn** [a85/POSTMan-Chrome-Extension#7754]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by fazilbashasn** [comment]
![image](https://user-images.githubusercontent.com/15376090/70305111-8e660d80-1829-11ea-9b45-d0bc4df0d928.png)

**Comment by fazilbashasn** [comment]
**Describe the bug**
Getting Blank Black screen frequently tried reinstalling multiple times still issue continues intermittently

**To Reproduce:**
Not sure about the steps to replicate
Expected behavior
A clear and concise description of what you expected to happen.

**Screenshots:**
Screenshots attached
![image](https://user-images.githubusercontent.com/15376090/70305306-12b89080-182a-11ea-9050-1c6ba4763154.png)

App information (please complete the following information):

App Type:  Native App
Postman Version: 7.13.0
OS: Windows 10 64 Bit


Above is the attached screenshot. 
It is the Intermittent issue....Not sure about the steps to replicate it but it happens once its open and and switch to the app to test something.

Thanks,
Fazil

**Comment by Raj-postman** [comment]
Hi @fazilbashasn 

Could you send us the logs from `View -> Developer -> Show logs` in Explorer to help@getpostman.com? If you are unable to access the menu bar when this error occurs you can find the logs in one of these directories:

`C:\Users\<user>\AppData\Local\Postman` and
`C:\Users\<user>\AppData\Roaming\Postman`

**Comment by fazilbashasn** [comment]
I have mailed the logs to the above email.
This is happening to Latest Postman as well not only Canary.

Thanks,
Fazil

**Comment by kamalaknn** [comment]
@fazilbashasn Thanks for reporting the issue. I'm closing this as a duplicate of #4764. Please follow up with the original issue for updates.

**Comment by TomLaMantia** [comment]
I am also experiencing this problem with Postman 7.14.0 on Windows 10 .

Setting the appropriate env var to disable GPU usage and running in compatibility modes as suggested in other threads does not do the trick for me.

**Comment by vsarunov** [comment]
Seeing the same thing as @TomLaMantia and did the recommendations. Though my postman request are very huge in payload, and there are multiple tabs open. It started crashing when There where to many tabs with too big requests. Now as soon as I try to open postman it shows all the tabs open and does not allow to close them just crashes.  Last log line in renderer-shell is '[21168][1591440372798][shell][error]["Render process for requester webview crashed",{"isTrusted":false}]'

**Comment by TomLaMantia** [comment]
Interesting @vsarunov, my requests contain large payloads as well. Could be related for anyone trying to reproduce this issue.

**Comment by arlemi** [comment]
@TomLaMantia @vsarunov Could you try the suggestions from that page? https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-
