### ISSUE TITLE
Query Param Encoding Issue

### ISSUE THREAD

**Issue by supunt** [a85/POSTMan-Chrome-Extension#7758]
**Query Params does not encode properly**
Consider the endpoint example below

`http://localhost:20047/v3.0/foo-summaries?bor=OBR&valnDate=2019-11-08`

If we are to pass Certain special characters to the string query param **bor** listed below it does not do the encoding properly

- &
- '#'
- '+'

**To Reproduce**
Example 1 - **bor = OBR&**

![image](https://user-images.githubusercontent.com/12725369/70396937-96a88d80-1a61-11ea-90ac-44d28c03d9d4.png)

Example 2 - **bor = OBR&1**

![image](https://user-images.githubusercontent.com/12725369/70396956-d7a0a200-1a61-11ea-976d-67d565c23870.png)

Example 3 - **bor = OBR# - Causes some weird behaviors**

![image](https://user-images.githubusercontent.com/12725369/70397000-5eee1580-1a62-11ea-91e3-dafcafe4efb1.png)

Example 4 - **bor = OBR+ - '+' turns in to a space**

![image](https://user-images.githubusercontent.com/12725369/70397029-aa082880-1a62-11ea-8b27-f36d32021bf5.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version v7.13.0
 - OS: Windows 10

**Comment by vikiCoder** [comment]
Hi, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0).
