### ISSUE TITLE
Script pane crashes when referencing pm.collectionVariables methods if any collection variable has a JS object as value

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7759]
**Describe the bug**
If you store a JavasScript object within Collection Variables, and later try to reference the collection variables using pm.collectionVariables methods the script / Pre-request script pane crashes and the following screen is shown.
<img width="506" alt="Screen Shot 2019-12-09 at 4 31 54 PM" src="https://user-images.githubusercontent.com/21366/70405260-6bde2980-1aa1-11ea-84ba-e451791f3cb7.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Store an object by putting something similar to the following in either script or pre-request script.
1.a `pm.collectionVariables.set("x",{"var":"val"});`
2. Run the request to store the object in the Collection variables store.
3. Type `pm.collectionVariables.has("x")` to reproduce the issue.

The issue can be reproduced by using any of the `pm.collectionVariables` methods and any of script editors can be used
* Pre-request 
* Collection level pre-request
* Test script

**Attaching a test collection:** [CollectionVariable Crash.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3937786/CollectionVariable.Crash.postman_collection.json.zip)
Run the request once and then edit scripts to reproduce the issue.

**Expected behaviour**
Script panes should not crash.

**Screenshots**
Errors as seen in DevTools Current View
![image](https://user-images.githubusercontent.com/21366/70406349-494e0f80-1aa5-11ea-9c1e-b75e932ced0d.png)

**App information (please complete the following information):**
 - App Type : Native App]
 - Postman Version 7.13.0
 - OS: Tested on MacOS Catalina and Windows 10

**Additional context**
Logged by Postman on behalf of a user.

**Comment by arlemi** [comment]
This was fixed in 7.18.0. :)
