### ISSUE TITLE
Horrible page update issues in the packaged up on Yosemite.

### ISSUE THREAD

**Issue by vladvino** [a85/POSTMan-Chrome-Extension#776]
It happens after a requests that return responses. To make the page redraw properly you need to double click on multiple list items or hide and show left pane.

![2014-10-28 at 6 17 pm](https://cloud.githubusercontent.com/assets/1009046/4819772/af7d84be-5f09-11e4-91cd-d3d805fc0409.png)

**Comment by shamasis** [comment]
Issue #705 is very similar and seems related.

**Comment by shamasis** [comment]
@vladvino The duplicate issue #705 has been closed. I am assuming that it would fix your issue too. As such, closing this bug. In case you are still facing this issue, let us know. :-)
