### ISSUE TITLE
Can't login to postman mac client because google auth page says app not secured

### ISSUE THREAD

**Issue by adotg** [a85/POSTMan-Chrome-Extension#7762]
**Describe the bug**
Can't log in to postman mac client using google auth service. After putting user name and password google redirects to a page which says the page from which the auth is performed might not be secured.

**To Reproduce**
This happened while I was using postman and then the system shut down because of low battery and when I turned it on the app logs me out and asked me to login. 
I choose "Log in using Google" and after user name and pasword entry it redirects me to a page where it alerts the login is not possible.

**Expected behavior**
Login happens and I get back my old postman data.

**Screenshots**
<img width="1917" alt="Screenshot 2019-12-09 at 1 28 21 PM" src="https://user-images.githubusercontent.com/7579500/70418205-febe9a00-1a88-11ea-9713-4b290ecef66b.png">

**App information (please complete the following information):**
 - App Type [Native App for MacOS]
 - Postman Version [Version 7.13.0 (7.13.0)]
 - OS: [e.g. macOS Mojave 10.14.5]

**Comment by fchoquet** [comment]
Same problem for me

**Comment by elssar** [comment]
Hey @adotg  and @fchoquet , we've just released a feature that lets you login to the Postman app via your browser. Can you try that out, you need to click on the link to "Try on a web browser." below the login form.

![browser-based-login-link](https://user-images.githubusercontent.com/1042301/70425519-60860080-1a97-11ea-8b42-75da953f22a3.png)

**Comment by adotg** [comment]
Done, it's working. Thanks.
@elssar up to you if you wanna close the issue.

**Comment by fchoquet** [comment]
Works for me too.
Thanks! 👍

**Comment by aswanthpp** [comment]
I am facing the same issue, Also I tried website login, but its not working

**Comment by gdbhowmick** [comment]
@aswanthpp What error are you getting incase of website login? Could you please provide a screenshot or maybe the error message you are seeing?

**Comment by dreampowder** [comment]
I've logged in from website, and it automatically opened the postman app after the login. But it kept saying the same thing until i received the new postman update. 
After updating the app, i was able to login to the app

**Comment by aswanthpp** [comment]
@gdbhowmick 
<img width="1680" alt="Screenshot 2019-12-11 at 10 13 59 PM" src="https://user-images.githubusercontent.com/20645925/70641529-caeb9c00-1c63-11ea-9cb0-7e5f1a9d571c.png">

I am getting this error

**Comment by Gunjan4542** [comment]
> @gdbhowmick
> <img alt="Screenshot 2019-12-11 at 10 13 59 PM" width="1680" src="https://user-images.githubusercontent.com/20645925/70641529-caeb9c00-1c63-11ea-9cb0-7e5f1a9d571c.png">
> 
> I am getting this error

@aswanthpp  It looks like you have an internet connection issue. Is there any proxy on your network that might be causing the problem?
