### ISSUE TITLE
OAuth 2.0 - Exception: Correlation failed.

### ISSUE THREAD

**Issue by SebastianJust** [a85/POSTMan-Chrome-Extension#7763]
Hi, 
I've done this for the last half a year, but suddenly, i get following error message while trying to authenticate against our identity provider. 

![image](https://user-images.githubusercontent.com/24389114/70433854-0d09b780-1a83-11ea-9251-eb9b736b4170.png)

If i'm doing the same in a browser it works fine. I've tried to google the last 2 days, but i cannot find anything about this. It also works, if i deploy the code.

This is my start up config:

            var csiServer = Configuration.GetSection("AppSettings")["CSIServiceUrl"];
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";

            })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.SignInScheme = "Cookies";

                    options.Authority = csiServer;
                    options.RequireHttpsMetadata = false;

                    options.ClientId = "xxx";
                    options.SaveTokens = true;
                    options.ResponseType = "code id_token";
                    options.Resource = "openid profile xxxxx";
                    options.Scope.Clear();

                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("xxx");
                    options.Scope.Add("openid");
                    options.Scope.Add("profile");
                    options.SaveTokens = true;
                    options.ClientSecret = "xxxxx";
                    options.GetClaimsFromUserInfoEndpoint = true; 
                    options.ClaimActions.Clear();
                    options.ClaimActions.MapAll();
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };
                });

In postman: 

![image](https://user-images.githubusercontent.com/24389114/70434136-aafd8200-1a83-11ea-8c92-502278a7be3b.png)

What have i tried? 
- Removed postman completely and installed it again
- Uninstalled visual studio and reinstalled
- Deployed the same code to a server (here it works) 

This is my log: 

> 2019-12-09 12:43:26.429 +01:00 [INF] Request finished in 1.1782ms 302 
> 2019-12-09 12:43:27.033 +01:00 [INF] Request starting HTTP/1.1 POST http://localhost:44336/signin-oidc application/x-www-form-urlencoded 1829
> 2019-12-09 12:43:27.033 +01:00 [INF] Policy execution failed.
> 2019-12-09 12:43:27.033 +01:00 [INF] Request origin null does not have permission to access the resource.
> 2019-12-09 12:43:27.033 +01:00 [WRN] '.AspNetCore.Correlation.oidc.sgqe3-9Hj4HquN7CaRRIUPHfw2UNyQFt9BArMaCjMnY' cookie not found.
> 2019-12-09 12:43:27.034 +01:00 [INF] Error from RemoteAuthentication: Correlation failed..
> 2019-12-09 12:43:27.034 +01:00 [ERR] An unhandled exception has occurred while executing the request.
> System.Exception: An error was encountered while handling the remote login. ---> System.Exception: Correlation failed.
>    --- End of inner exception stack trace ---
>    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> 

Specs: 

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Postman/7.13.0 Chrome/66.0.3359.181 Electron/3.1.8-postman.5 Safari/537.36
--

![image](https://user-images.githubusercontent.com/24389114/70434421-6d4d2900-1a84-11ea-8086-fab6ce07f858.png)

**Comment by Boomit2016** [comment]
I'm having the same issue. Authorization still works but not in Postman.

```
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Warning: '.AspNetCore.Correlation.aad.EymgQ1I4BQb8cPvkI1LQZSuIkXxieyCyCRzonop3Qpg' cookie not found.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Information: Error from RemoteAuthentication: Correlation failed..
```

**Comment by SebastianJust** [comment]
Yes exactly the same for me.

**Comment by SebastianJust** [comment]
After restore back up of my PC It worked. 

But I think we still need an answer why that happened?

**Comment by fernandomediavalet** [comment]
This issue is definitely happening to me as well since yesterday. I spent the entire day trying to tweak cookie settings on my identity services API, until I realized it wasn't working only when using Postman (native app). It _does_ work on the deprecated Chrome extension, though.

@SebastianJust's details seem to be good enough, but I will happily provide you with more logs if needed. Let me know.

**Comment by SebastianJust** [comment]
FYI if i use SoapUi i have the same problem.

**Comment by svict4** [comment]
> It _does_ work on the deprecated Chrome extension, though.

Thanks for the workaround in the meantime.

**Comment by SebastianJust** [comment]
Is there any solution for this issue? I suddenly came up again.

**Comment by SebastianJust** [comment]
Found solution in my case: It's because of net core 2.1. I upgraded to: 3.0, and here it works: 

https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio
https://stackoverflow.com/questions/59310431/what-could-cause-a-correlation-cookie-to-not-be-returned-on-specific-devices

**Comment by vikiCoder** [comment]
Thanks @SebastianJust for the links you provided. Looking at the links, the issue seems to be related to https://github.com/postmanlabs/postman-app-support/issues/7592

**Comment by vikiCoder** [comment]
Hi,

We've added an option in OAuth2 that allows you to authenticate using your system's default browser while generating OAuth 2.0 token. That should solve the problem. Check out [my comment](https://github.com/postmanlabs/postman-app-support/issues/7700#issuecomment-626273229) on a [similar issue](https://github.com/postmanlabs/postman-app-support/issues/7700) for more details. Feel free to reopen the issue if the problem still persists.
