### ISSUE TITLE
Importing raw data via an API request

### ISSUE THREAD

**Issue by MozartHetfield** [a85/POSTMan-Chrome-Extension#7771]
**Is your feature request related to a problem? Please describe.**
I generated a new JSON based on a Swagger documentation. The new JSON fits perfectly when I import it in Postman the following way: Import -> Paste Raw Data. I searched through the Postman APIs, but I couldn't find a way to automatically import the raw text via an API.

**Describe the solution you'd like**
I would like an API that accepts the formats that "Paste Raw Data" accepts, to be able to import the JSON that I have. Maybe there already is one and I missed it.

Thanks!

**Comment by preethammavin** [comment]
@MozartHetfield can you try the Postman API for importing as specified in the doc and let me know if it works
https://docs.api.getpostman.com/?version=latest#09886971-e1e2-4a62-8f59-f7abfd79ff5e

**Comment by preethammavin** [comment]
Closing the issue for now, as with the current set of information we are unable to investigate further.
