### ISSUE TITLE
In postmann -> code -> generate code -> php code generator is not show any options.

### ISSUE THREAD

**Issue by Tabassum09** [a85/POSTMan-Chrome-Extension#7776]
**Describe the bug**
In postmann -> code -> generate code -> php code generator is not show any options .

**To Reproduce**
1. Go to 'postmann'
2. Click on 'code'
3. drop-down select  ''PHP"
4. No option is visible for me. (error)

**Expected behavior**
should show multiple options as curl and others.
![Screenshot from 2019-12-11 12-07-41](https://user-images.githubusercontent.com/37328477/70598277-79fe8800-1c10-11ea-974e-bc776226ce71.png)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version : 7.13.0
 - OS: Ubuntu 18.04

**Additional context**

**Comment by abhijitkane** [comment]
@Tabassum09 Can you enable the 'New Code Generation Mode' setting in the global options (wrench icon in the top-right)? The older code generation mode doesn't support options for any language.

**Comment by preethammavin** [comment]
@Tabassum09 closing the issue for now, do let us know if the issue still persists and reopen the issue.
