### ISSUE TITLE
Using Postman to test IdentityServer4 OAuth 2.0 Authorization Code Flow Fails

### ISSUE THREAD

**Issue by cowlinb6** [a85/POSTMan-Chrome-Extension#7777]
**Description**
Attempting to use Postman with OAuth 2.0 Authorization Code does not work. When I'm prompted to login and enter correct credentials when I click the Login button it just redirects back to the login screen.

I was expecting the token to be retrieved.

**To Reproduce**
1. Create new request within Postman
2. Set the Auth type to be OAuth 2.0
3. Set the Add auth data to Request Headers
4. Click on Get New Access Token
5. Populate the details as shown

![image](https://user-images.githubusercontent.com/12410874/70629357-c0101780-1c21-11ea-8033-44c1196373ad.png)

6. Click on Request Token
7. Enter bob/bob as the username and password
8. Click Login
9. Redirected back to the Login page

![image](https://user-images.githubusercontent.com/12410874/70629452-ecc42f00-1c21-11ea-9c04-6dad85338052.png)

**Expected behavior**
I was expecting the login screen to disappear and the token to be retrieved and displayed in Postman.

**App information:**
 - App Type: Native App]
 - Postman Version: v7.13.0
 - OS: Windows 10

**Additional context**
Also tested with the latest Canary build with the same results. This did use to work just cannot find from what version of Postman this stopped.

Other apps such as SoapUI works ok.

**Comment by vandenbergjp** [comment]
I'm also experiencing the same issue.

**Comment by fernandomediavalet** [comment]
Probably caused by the same problem described by #7763

**Comment by SebastianJust** [comment]
After i've installed my back up it works. I truly don't get it, why it doesn't work. 
If i use: SOAP UI it's the same issue.

**Comment by kkadir** [comment]
Having the same issue on v7.13.0, but it used to work as expected before. I am not sure if this broke after a Postman update or IdentityServer4 update or ASP.NET Core 3.1 update.

**Comment by fernandomediavalet** [comment]
The issue happens on v7.13.0 as it's not keeping/storing the authentication http-only cookies dropped by IdentityServer (even though when using Fiddler you can clearly see that the cookies are sent as response to previous methods in the authentication dance), and therefore the not-stored-cookies are not sent along with the request that requires them (by default, "/signin-oidc")

**Comment by fernandomediavalet** [comment]
Here are some logs to show that the cookies are sent as a response, but Postman isn't storing them:

![image](https://user-images.githubusercontent.com/37375046/70747033-f5793b80-1cdb-11ea-86b2-9a23ba26a2f9.png)

This then causes the subsequent calls to /signin-oidc to fail since the http-only cookies are missing in the request.

![image](https://user-images.githubusercontent.com/37375046/70747615-40478300-1cdd-11ea-8e45-57ac01d46fb3.png)

**Comment by cowlinb6** [comment]
This looks to be caused by by setting the SameSite attribute on the authorisation cookie to None. As Postman is using Chrome 66 this will reject any cookies that have this set to None.

If you don't set the SameSite attribute for Postman requests (i.e. via User Agent detection) then it should work.

This link gives more details on incompatible clients:
https://www.chromium.org/updates/same-site/incompatible-clients

**Comment by luuksommers** [comment]
Here is also some Microsoft documentation how to handle it in the meantime:

https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

**Comment by konstad** [comment]
i am also experiencing this issue :(

**Comment by pcbl** [comment]
same issue on my end. We have done the update to .Net Core 3.1 and IdentitityServer4  and since then cannot use postman to get the token. Not so keen on add code to handle the SameSite on my end.

**Comment by JoseyJimmy** [comment]
Any ideas on how to Automate OAuth2.0 Authorization on POSTMAN Collection?

**Comment by carlblanchard** [comment]
I've been struggling with this for a few days now. I am using postman version v7.22.1 (The current latest version) I have tried two IDSrv setups https://github.com/skoruba/IdentityServer4.Admin  & https://github.com/KevinDockx/SecuringAspNetCore3WithOAuth2AndOIDC both of which their clients work fine. I have set up Postman following many different examples (this one has been the best) https://stackoverflow.com/questions/58197304/how-to-call-identity-server-4-with-postman-for-login 
I've checked the obvious and put breakpoints where the user is authentication happens, that's all correct the auth succeeds. 

Even if I set the same site cookie to Lax or not set it at all it still fails.
Now I am starting to think it's perhaps a problem in Postman.  Does anyone have any concrete information on this problem?

**Comment by SebastianJust** [comment]
Hi @carlblanchard,
I had the same issue, but I upgraded from .NET CORE 2.2 to 3.0 and that worked for me :)

**Comment by carlblanchard** [comment]
Hi, Sebastian, what version of postman are you using? both the examples I've used are .net core 3.1. I've just added a swagger client and that's working fine. The lowest common denominator now seems to be PostMan.

**Comment by SebastianJust** [comment]
Hi @carlblanchard,
Okay. I'm using same version: Postman v7.22.1.

Do you have any logs, you can provide?

**Comment by carlblanchard** [comment]
I've captured the requests to idsrv you can see the 302 back to the login screen. 
You will need fiddler to view the session file if you don't already have it https://www.telerik.com/fiddler

Sadly the logging in Skoruba is pretty simple, perhaps try downloading  https://github.com/skoruba/IdentityServer4.Admin and try replicating it. 

The log is in the zip it Github doesn't accept .saz which is the fiddler session
[fiddler_session.zip](https://github.com/postmanlabs/postman-app-support/files/4515347/fiddler_session.zip)

**Comment by SebastianJust** [comment]
Hm. Yeah I can see it, but here it seems like it works. 
I had same issue (https://github.com/postmanlabs/postman-app-support/issues/7763).

Can you provide some details from postman - and maybe install a logger to have more details? I'm using Serilog.

**Comment by carlblanchard** [comment]
Wow, you had to rebuild your machine, that's insane. To be honest I think I am just going to give up trying to use postman. I have swagger working and I've wasted too much time on this now. 
I really appreciate your help, Sebastian. It appears to be, not an easy fix. which is a shame because I really like PostMan. Thanks for your help.

**Comment by SebastianJust** [comment]
Yeah - I'm glad I had back up. 
Cool! Np man! :) Happy to try helping.

**Comment by carlblanchard** [comment]
Hi Sebastian, Finally resolved the issue. Installing PostmanCanary done the job. 
https://github.com/postmanlabs/postman-app-support/issues/8364

**Comment by SebastianJust** [comment]
Wuhu! So cool! :) 
Thank you. 
Have a great weekend.

**Comment by sshanzel** [comment]
This happens to me as well. I've followed the accepted answer on this [StackOverflow Question](https://stackoverflow.com/questions/59250716/identity-server-4-with-the-docker-compose-redirects-to-login-page-after-connect) and it worked! It specifies the cases that it needs to apply the configuration for the CookiePolicy placed. if i'm not mistaken.

**Note:** I am using .Net Core 3.1 and still I've placed `None` at `SameSite` options in order for it to work.  `Unspecified` value doesn't work on my case.

**Comment by vikiCoder** [comment]
Hi,

We've added an option in OAuth2 that allows you to authenticate using your system's default browser while generating OAuth 2.0 token. That should solve the problem. Check out [my comment](https://github.com/postmanlabs/postman-app-support/issues/7700#issuecomment-626273229) on a [similar issue](https://github.com/postmanlabs/postman-app-support/issues/7700) for more details. Feel free to reopen the issue if the problem still persists.
