### ISSUE TITLE
Auto detect if a Data file is out of date in the Collection Runner

### ISSUE THREAD

**Issue by Quietbeat** [a85/POSTMan-Chrome-Extension#7781]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When I'm in the Collection Runner (CR) and a run has completed, I'll update the Data file then run the collection again but sometimes I forget to remove the current Data file and re-select the updated file. I'd be super handy if you could auto-detect a date/time change to the associated Data file whenever the Collection Runner has focus and offer to use the updated file.

Additionally you could add a "Refresh" button but I really want to see Auto-Update.

**Describe alternatives you've considered**
None...I have to manually remove the current file then re-add it.

**Comment by ASStroh** [comment]
You need to manage this yourself. It's a security issue to allow a web-based application to listen to your system's directories. Also, not really a big deal to have to tell Postman you've updated a data file. 

I recommend newman/CLI. Used cleverly, it can solve your problem, and more.

**Comment by Quietbeat** [comment]
I'm using the Postman app in Windows 10 so you can implement a feature/task to auto-check if a file has changed. I'm not going to use Newman.

**Comment by preethammavin** [comment]
@Quietbeat I do understand the ease that it would add, but auto-detection in the file change is not something Postman would be doing as it has few concerns around it (one of them being a security concern our users would have). 

We do pick the latest version of the data file which is attached for a collection run, if you were to update the existing file we do pick that one. If you were to edit and save it as another file, you would have reattach it.
