### ISSUE TITLE
Add ability to only show Passe or Failed runs in the Collection Runner

### ISSUE THREAD

**Issue by Quietbeat** [a85/POSTMan-Chrome-Extension#7782]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When the Collection Runner (CR) has completed a run, I want the option to see just the Passed or Failed iterations. You could turn the # of Passed and Failed circles (under the Collection Runner tab) into actual buttons.

In most of my tests, I have Scripts that run once the test is complete so I need to see 1) The iteration that failed and all of the tests that ran. Clicking the red square only shows the iteration.

**Describe alternatives you've considered**
None

**Comment by giridharvc7** [comment]
This is available in Postman 8.x, please check out our app or the Postman web. 
![Screenshot 2021-04-30 at 3 10 37 PM](https://user-images.githubusercontent.com/1040583/116677778-3b649b80-a9c6-11eb-8e4a-91756585773f.png)
