### ISSUE TITLE
Unable to delete API version

### ISSUE THREAD

**Issue by CookieMonitor** [a85/POSTMan-Chrome-Extension#7783]
**Describe the bug**
When testing the ability to create API versioning, I created a 'test_version' as per screenshot 1.
Made a few changes, pressed the sync button in Postman. (Unsure whether this actually made the changes or not..)

When attempting to delete the API version branch, it keep returning an Error. Almost as if the request is invalid or something.

**To Reproduce**
1. Go to 'API's' then Into an API instance.
2. Click on 'Show All Versions'
3. Make a 'test_version' API version and switch to branch.
4. Attempt to Delete the branch.
5. The API version "Develop" section goes empty, however the actual object/api version instance remains.
6. Then you receive the error message continually as per attached.

**Expected behavior**
Should provide the user with the prompt to delete said API version (it does), then delete the object instance.
(i don't know if there are features for trash_versioning or anything for version restores - could be a potential future feature)

**Screenshots**
![version-cannot-delete1](https://user-images.githubusercontent.com/17626822/70672048-c4900b00-1cc9-11ea-9ec4-f60482c37829.PNG)
![version-cannot-delete2](https://user-images.githubusercontent.com/17626822/70672053-c78afb80-1cc9-11ea-9503-ec08dd7c2872.PNG)
![version-cannot-delete3](https://user-images.githubusercontent.com/17626822/70672056-cbb71900-1cc9-11ea-8719-69f5126a79a4.PNG)

**App information (please complete the following information):**
 - App Type [Chrome App] - not sure i know how to provide this info..
 - Postman Version - Postman v7.13.0
 - Windows 10

**Comment by sankalp0o** [comment]
Thanks for informing us @CookieMonitor. This shouldn't be happening and we'll look into this.

**Comment by jazzyarchitects** [comment]
@CookieMonitor We have drilled down to an issue on our end and are working on a fix. In the meanwhile can do try the following to delete the apiversion:
1. Remove all relations from the apiversion you are trying to delete
2. Delete the apiversion

Let us know if this works for you.

**Comment by sankalp0o** [comment]
@CookieMonitor This has been fixed in the latest Postman app. I'm closing this issue but please feel free to reopen it if you can't get it to work.
