### ISSUE TITLE
Need an overflow bar in Collection Runner‘s Run Summary

### ISSUE THREAD

**Issue by chen-yi-tester** [a85/POSTMan-Chrome-Extension#7785]
**Is your feature request related to a problem? Please describe.**
When i run the collections for 100 times, i can only see 50 or less result 
**Describe the solution you'd like**
An overflow bar in Collection Runner‘s Run Summary so I can drag and see more
**Describe alternatives you've considered**

**Additional context**
![ppp](https://user-images.githubusercontent.com/57658722/70678972-b0024180-1cce-11ea-8da6-4e3da18ee95d.png)

**Comment by vvs11** [comment]
Hi, @chen-yi-tester.  Thanks for writing in!
We will look into this and will update you with a timeline soon. 
Could you let us know more about the use-case you're trying to solve with collection runs? It'd help us design a better UX

**Comment by chen-yi-tester** [comment]
> Hi, @chen-yi-tester. Thanks for writing in!
> We will look into this and will update you with a timeline soon.
> Could you let us know more about the use-case you're trying to solve with collection runs? It'd help us design a better UX

![无标题](https://user-images.githubusercontent.com/57658722/70913750-9146d680-2051-11ea-907a-1e16fe3a8b33.png)
I just wanna this (as you can see in the pic i uploaded)

**Comment by giridharvc7** [comment]
This is fixed, please check out Postman 8.x on the app or the [Postman web](https://www.postman.com/downloads/) and let us know what you think.
