### ISSUE TITLE
Offline message all the time - user cant join team or sync collections

### ISSUE THREAD

**Issue by MarekKrolczyk** [a85/POSTMan-Chrome-Extension#7787]
**Describe the bug**
I'm not able to join team and sync collections. Offline error is displayed all the time. It worked before, problem exists few days already.

**To Reproduce**
1. Log in to postman native app
2. Click on 'Join' button
3. See error:
vendor-shared.js:197411 Could not find on CollectionStore. Missing or invalid parameter.
(anonymous) @ vendor-shared.js:197411
4vendor-shared.js:197411 Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (vendor-shared.js:80767)
    at EventEmitter.emit (vendor-shared.js:50085)
    at _dispatch (vendor-shared.js:143867)
    at EventEmitter.<anonymous> (vendor-shared.js:143877)
    at EventEmitter.emit (/C:/Users/xxx/AppData/Local/Postman/app-7.13.0/resources/app.asar/html/events.js:182)

**Expected behavior**
User is logged in. Collections are synced.

**Screenshots**
![2019-12-12_13h21_23](https://user-images.githubusercontent.com/55488592/70712257-a800cc80-1ce3-11ea-8928-f0664f0bf2b8.png)
![2019-12-12_13h22_00](https://user-images.githubusercontent.com/55488592/70712259-a800cc80-1ce3-11ea-9224-9bf17c30e642.png)
![2019-12-12_13h22_33](https://user-images.githubusercontent.com/55488592/70712275-b64ee880-1ce3-11ea-9910-b6fb9994d007.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version [7.13.0]
 - OS: Windows 10

**Additional context**
I tried to:
- Login and logout
- turned off all firewalls
- reinstall postman
- login other accounts

**Comment by xk0der** [comment]
Hey @Jaszczomp997, I see you already tried turning off firewalls - but I assume that was the firewall on your machine? If you are trying this within your company/organization maybe they are blocking HTTP sockets.

Postman uses HTTP sockets to perform sync and other network operations. From the screenshot, it looks like HTTP sockets are being blocked. 

The easiest way to test this would be to try connecting to a different network, say a mobile hotspot and see if things work! Or if you can test things from your home, as stuff shouldn't be blocked there.

**Comment by MarekKrolczyk** [comment]
Fixed with cleaning local storage : https://support.getpostman.com/hc/en-us/articles/360025359014
