### ISSUE TITLE
Hardcoded Collection Variables Disappear

### ISSUE THREAD

**Issue by rwilliams3** [a85/POSTMan-Chrome-Extension#7790]
**Hardcoded Collection Variables Disappear**
Once a collection is either updated via fork merge or exported/imported to/from json, hardcoded collection level variables disappear entirely. My team and I used the collection variables to store long queries and large json objects. Its a bit of a pain to keep replacing them or to set them via pre-request scripts. 

**To Reproduce**
1. Set a hardcoded collection variable on a forked collection branch
2. Merge branch back to master
3. Check collection variables for hardcoded value
OR
1. Set a hardcoded collection variable 
2. Export collection to JSON
3. Re-import collection json to Postman app. 
4. Check collection variables for hardcoded value

**Expected behavior**
Its seems that hardcoded collection level variables should persist no matter what. Unlike Environment/Global variables they actually sit within the collection itself.  

**App information:**
 -  Native App
 - Postman Version 7.13.0
 - OS: macOS Sierra 10.12.6

**Comment by xk0der** [comment]
@rwilliams3 I tried the steps you mentioned and was unable to reproduce the issue. The variables persisted in both the scenarios (merge and import). That causes me to think that possibly the issue might be related to the values being stored in the variables?

I used simple values only, looks like JSON objects might be the cause of the issue.

Would you try the steps with some simple variable names and values and see if things work? That should help narrow down where the problem lies.

If it's the JSON objects causing the issue, I guess the quickest way to fix things would to use `JSON.stringify()` to store the objects as string values and then you may parse the values using `JSON.parse()` in your scripts.

I will let Postman devs qualify this further.

**Comment by brunomoreira86** [comment]
I am using Postman Version 7.36.0 (7.36.0) and I similar issue but in my case, they disappear randomly after running calling requests several times.

**Comment by ghost** [comment]
I have had this issue through v7+ and now in v8+. The variables at folder level stay for me, but when I export the collection, they are being lost and thus when someone imports them, they now do not have these essential variables.

**Comment by ebookerd1** [comment]
I am having this issue as well. I forked my collection saved merged and then the variables disappeared after. (I saved of course) on Postman v8.11

**Comment by rochanram** [comment]
I tried all the steps in the original comment and was not able to reproduce it. 
@ebookerd1 , @brunomoreira86, @rwilliams3 Is this still happening?

**Comment by DannyDainton** [comment]
Closing this for now, we can look to reopen the issue if you're still facing it on the latest version of the platform.

**Comment by david-kariuki** [comment]
I am having the same issue.
I have created so many variables under my collection only to lose them when saving.

**Comment by david-kariuki** [comment]
Though the issue disappears when I restart postman, oh well. It then beautifully and awesomely yet so accurately and perfectly deletes them all. Now I have to happily and confidently start over hoping to lose them all over again. What a day. Honestly, this is great GREATLY ANNOYING. When I restart again, they are all there. This feels like betting.

**Comment by vedkribhu** [comment]
@david-kariuki on which version of the app are you facing this? Is this happening on postman web as well? What are exact steps to reproduce this

**Comment by david-kariuki** [comment]
This was only happening on the desktop version. I have not had any problems with the web app. Unfortunately, I cannot reproduce the same. The problem seemed to be a hit or miss. Below is the version information.

<br>

******

**Postman for Linux**
|||
|-|-|
| Version | 10.11.2 |
| UI Version | 10.11.2-ui-230309-0541 |
| Desktop Platform Version | 10.11.1 |
| Architecture | x64 |
| OS Platform | linux 6.1.18-200.fc37.x86_64 |
