### ISSUE TITLE
OpenApi 3.0.0 import file with remote reference fails

### ISSUE THREAD

**Issue by melaniemarc** [a85/POSTMan-Chrome-Extension#7794]
When I import a specification file (OpenApi 3.0.0) containing remote references to schemas and requestBodies description, Postman is not able to find schema for response from my spec file.
The ./components/schemas and ./components/requestBodies content are not parsed.

Is Postman able to read remote references ? 

```
 {
  "value": "reference ./components/schemas/User.json not found in the api spec"
 }
```

1. Import file
2. Generate Collection from OpenApi 3.0 schema

![image](https://user-images.githubusercontent.com/58809240/70793139-fc1ab800-1d9a-11ea-9ed6-86675771210f.png)

3. Collections : Get all users

![image](https://user-images.githubusercontent.com/58809240/70794357-c2977c00-1d9d-11ea-86db-dff129bdfbf8.png)

4. Clic on example : "The users list has been succefully retrieved"
5. The expected response body is not recognized

![image](https://user-images.githubusercontent.com/58809240/70794417-e5c22b80-1d9d-11ea-9f9c-6763ccfbec8c.png)

The ./components/schemas/User.json is not found

 - App Type : Native App
 - Postman v7.13.0
 - OS: Ubuntu 19.04

**Comment by AlexZeitler** [comment]
@vvs11 @abhijitkane We faced this as well today. Is there a rough ETA for a fix?

**Comment by VShingala** [comment]
@melaniemarc @AlexZeitler Thank you for reporting this.

We do support multi-file schemas for OpenAPI but not currently through the 'Generate Collection' button in the API tab.
To import multifile schemas as a collection you can use the IMPORT button on the top left corner of the Postman app and choose the option Folder to upload the entire folder containing this multi-file schema. It will be converted into a collection.

We are working to bring the multifile support on the 'Generate Collection' flow as well. But we don't have any ETA on it.

Please let us know if you face any further problems with this.

**Comment by JesseTG** [comment]
So, how's this coming along?

**Comment by lastlistener** [comment]
Came to ask the same as @JesseTG. This actually doesn't work whether you use the "Import -> Folder" flow or any other importing flow in Postman. 

Postman will load every openAPI file in the folder you specified, but it does not honor references to local files or remote resources in included definitions. For example, if one of the files in your folder has a structure like pathName: {post: {parameters:[{name: "myParam", schema: $ref: "./myParamDefinition"}]}}, Postman won't recognize and load the referenced definition. 

I was extremely surprised by this, it seems like absolutely vital functionality for any real-world API testing where refs are commonly used in larger API structure.

**Comment by rufik** [comment]
Well, I can't even import API using "folder" option - I click "choose folder from your computer", I choose proper folder (it's windows, path does not contains spaces), click "OK" and....nothing. Still on import screen with "choose folder from your computer" button.

**Comment by bpiselli** [comment]
+1

**Comment by thomafred** [comment]
+1

**Comment by n8bour** [comment]
+1

**Comment by jonico** [comment]
Update: I have tried @VShingala 's suggestion with Postman 10 and [this multi-file project](https://github.com/jonico/openapi-boilerplate) and everything worked as expected, including collection generation 🎉

**Comment by akshaydeo** [comment]
[Multi-file schema](https://blog.postman.com/announcing-postmans-redesigned-api-builder-with-native-git-support/) is now supported for Open API 3.0 (and 2.0 support is coming soon).
