### ISSUE TITLE
broken link in the documentation

### ISSUE THREAD

**Issue by bayanistka** [a85/POSTMan-Chrome-Extension#7796]
I found the broken link https://learning.getpostman.com/docs/postman/environments_and_globals/variables

![image](https://user-images.githubusercontent.com/32704753/70799170-f5e80400-1db9-11ea-8756-238b5835717b.png)

**Comment by harryi3t** [comment]
@bayanistka For me, it's redirecting to https://learning.getpostman.com/docs/postman/variables-and-environments/variables/ which opens fine. Can you check again?

**Comment by preethammavin** [comment]
@bayanistka it's redirecting me to the page mentioned above, feel free to reopen the issue if it is not solved
