### ISSUE TITLE
{{$randomStateAbbr}} not returning any result

### ISSUE THREAD

**Issue by teckler** [a85/POSTMan-Chrome-Extension#7797]
**Describe the bug**
When using the dynamic variable {{$randomStateAbbr}}, no results are returned. Other dynamic variables are working as intended. 

**To Reproduce**
1. Create a pre-request script with the following code in any dummy call:
pm.variables.set("tst_regionCode", pm.variables.replaceIn('{{$randomStateAbbr}}'));
pm.variables.set("tst_fullName", pm.variables.replaceIn('{{$randomFullName}}'));
console.log(pm.variables.get("tst_regionCode"))
console.log(pm.variables.get("tst_fullName"))
2. Run the call to execute the script
3. View results in console.
 
--> {{$randomStateAbbr}}
-->  Thora Schmitt

**Expected behavior**
{{$randomStateAbbr}} would return a two-letter state code like "NY" per the documentation.

**Screenshots**
n/a

**Comment by preethammavin** [comment]
@teckler thanks for reporting this, we will let you know when the bug is fixed.

**Comment by coditva** [comment]
@teckler So turns out the documentation is a little bit outdated. To be clear, **Postman does not support `randomStateAbbr` dynamic variable**. We will update the documentation. Sorry for the confusion!

**Comment by mikesigs** [comment]
I just got bit by this today. The docs aren't updated yet, so I thought I'd provide a longer list of dynamic variables from the docs that don't produce a result.

```
$randomZipCode
$randomCityPrefix
$randomCitySuffix
$randomStreetSuffix
$randomStreetPrefix
$randomSecondaryAddress
$randomState
$randomStateAbbr
$randomDateBetween
$randomCurrencyAmount
$randomImage
$randomTechnicsImage
$randomNameTitle
$randomPhoneNumberFormat
$randomPhoneFormats
$randomArrayElement
$randomObjectElement
```

**Comment by coditva** [comment]
@mikesigs You can see this updated list for a reference: https://learning.getpostman.com/docs/postman/scripts/postman-sandbox-api-reference/#dynamic-variables
