### ISSUE TITLE
Postman on-prem

### ISSUE THREAD

**Issue by Cereal916** [a85/POSTMan-Chrome-Extension#7804]
**Is your feature request related to a problem? Please describe.**
I work for a company that deals with a lot of PII/PHI. So when evaluating software we use internally there is lots of scrutiny about any information that is stored outside the company, even if it is just test data.

**Describe the solution you'd like**
If there was an on-prem option for enterprise it could completely revolutionize the way we test our apis/share collections/etc without worrying about PII leak. Specifically storing collections and environments on-prem would be a sufficient start, but the addition of monitoring would be great.

**Comment by cyrielle-hada** [comment]
@Cereal916 Unfortunately, we don't currently have any plans for an on-prem version of Postman.

In the event that our cloud-based product doesn't meet your organization requirements - you may want to explore  [Newman](https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/) - our open-source command-line runtime tool for Postman collections.

- https://github.com/postmanlabs/newman

Between using Postman without signing in and Newman to run collections in your private cloud/internal data centers you can get most of the functional benefits of Postman collections and tests. However, this solution doesn't let you use collaboration and Postman Mocks, Monitors, and Documentation.

**Comment by cherlo** [comment]
Postman is about to have a major mass-exodus if it already hasn't with the new quota restrictions.  Not having a no-prem version is a boned headed decision.
