### ISSUE TITLE
Environment not syncing when updating via Postman API

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#7805]
**Describe the bug**
 We are using Postman in our organization to run integration tests against our API.
Now, we seem to have an issue with this. In order for this to work, an API key must be generated.
This can be done, by a user A logging into the portal and create a new API key. However, when another person B is updating environment variables, they don't seem to be picked up until user A syncs their workspace.
This is of course not what we want, it seems we need a general API key that is not user-specific and reflects any updates that occur to the workspace or environment files.

**To Reproduce**
1. User A will Generate the API Key
2. User B will make some changes in the collection but these changes aren't reflected since the API key isn't generated by this user
3.  User A will need to make the changes again in the collection, only then the  changes made by user B will be updated along with the changes by User A

**Expected behavior**
Environment should sync when updating via Postman API.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.12]
 - OS: [Mac]

**Comment by preethammavin** [comment]
@ash007-postman are both the users online when this happens
Also trying to reclarify the issue
1) User A generates the API Key and pastes in an environment variable
2) User B Tries to run the collection/ send a request with the same environment
3) No changes on the environment are reflected till the user makes changes to the collection

This should not happen, can you check if the user had pasted the API key in the initial value and not the current value. Also both the users are online at one point in time to get the data synced.

**Comment by ash007-postman** [comment]
@preethammavin 
**User** 
The whole issue is…
User A generates an API key
That API key is used to connect to the collection in our build pipeline and run the ‘integration tests’ created in that postman collection
Build pipeline runs, integration tests throw an error
User B notices an issue with the code in those test, and he makes an update to the script in the postman collection
The build pipeline is run again
The same issue is being thrown, just as if the code in the postman was not fixed.
User A connects again with Postman
The build pipeline is run again
Integration tests work, new code is being run

As you might see, this is an issue if user A would get sick for a period of time, as nobody is able to fix the issues, unless that person generates a new API key.

But in that scenario, you are running in circles. So you want a system API key to use to connect to the collection, and not a user API key

**Comment by ankit-m** [comment]
I am able to reproduce this issue and have created an issue on our internal tracker to fix this. Will update this thread once it is fixed.

**Comment by ankit-m** [comment]
@ash007-postman This issue should be fixed now. Syncing of environment variables works fine. Let me give a brief description of the issue so that everyone is on the same page.

1. User A and User B are in a workspace W which has a collection C and an environment E
2. User A generates an API key - K.
3. CI uses K to access C and E to run the collection (using `newman run https://api.getpostman.com/collections/:id?apikey=:key -e https://api.getpostman.com/environments/:id?apikey=:key`).
4. User B updates the **current value** of a variable in E via Postman client.
5. CI runs C with E again - Uses new values updated by User B.

Let me know if this resolves your issue. If not, feel free to reopen this ticket.
