### ISSUE TITLE
Could not properly import curl with "X-XSRF-TOKEN"

### ISSUE THREAD

**Issue by vanthuanqs** [a85/POSTMan-Chrome-Extension#7806]
**Describe the bug**
I am facing with error _Could not get any response_ after import curl 

**To Reproduce**

1. Click on button **Import**, choose **Paste Raw Text** and submit
![image](https://user-images.githubusercontent.com/4916817/70896162-ca1b8700-2022-11ea-9d79-407b902e9b73.png)

2. Click on **Send** button to send the request
4. See error (of couse I turned off SSL certificate validation):
![image](https://user-images.githubusercontent.com/4916817/70896285-064ee780-2023-11ea-99ce-2cba87328ca2.png)

**Expected behavior**
Should receive response

**Screenshots**
![image](https://user-images.githubusercontent.com/4916817/70896671-bae90900-2023-11ea-83f7-9b35c7db7a64.png)
![image](https://user-images.githubusercontent.com/4916817/70896924-3a76d800-2024-11ea-96ab-e97ddfa9a40c.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.13.0]
 - OS: [Ubuntu 19.04]

**Additional context**
After debug, I found the reason is Postman does not import curl properly
There is header `X-XSRF-TOKEN` in curl but in Postman it's `X-X SRF-TOKEN`
![image](https://user-images.githubusercontent.com/4916817/70896587-8b3a0100-2023-11ea-8b0c-43a92468a419.png)

**Comment by abhijitkane** [comment]
Able to reproduce with `curl -H 'X-XSRF-Token: Hello' http://domain.com`

**Comment by abhijitkane** [comment]
Thanks for reporting this @vanthuanqs. We'll take this up soon.

**Comment by vanthuanqs** [comment]
@abhijitkane Thank you!

**Comment by vanthuanqs** [comment]
@abhijitkane This problem is also happened on Mac OS
Postman for Mac
Version 7.13.0
OS X 19.2.0 / x64

**Comment by shreys7** [comment]
Hey @vanthuanqs , we have added the fix for this issue and it will be released with the next Postman App version - **7.22**, planned on 8th April.

**Comment by vanthuanqs** [comment]
Awesome work, thank you!
