### ISSUE TITLE
"400 SAML assertion not yet valid" error after submitting ADFS credentials for SSO Login

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#7807]
**Describe the bug**
Unable to login to Postman application or Dashboard via SSO Login after entering ADFS credentials

**To Reproduce**
1. Click on Enterprise Sign-in
2. Select ADFS as iDP
3. Enter ADFS credentials and submit
4. 400 SAML assertion not yet valid error message on the screen

**Expected behavior**
Being logged into the Postman application or Web Application

**App information (please complete the following information):**
 - App Type [Web Application and Native application]

**Additional context**
The ADFS that is being used is not exposed on the Internet

**Comment by elssar** [comment]
This means that the Identity Provider sent a `notBefore` timestamp with the SAML assertion, and that timestamp is in the future. Likely because of clock drift on the Identity Provider.
