### ISSUE TITLE
【Help】The request methods what I send by PostMan all become Get

### ISSUE THREAD

**Issue by vipwwjie** [a85/POSTMan-Chrome-Extension#7809]
Just Like This.
In a specified url link, when I send a request other than the Get request，they all become Get Request,Include Post,Delete,Put,and so on.
But if i change a url link,it becomes normal.
My PostMan Version Is 7.13.0
![image](https://user-images.githubusercontent.com/34475480/70966228-7f0a7e00-20cd-11ea-91b0-649a8494c564.png)

**Comment by vipwwjie** [comment]
![image](https://user-images.githubusercontent.com/34475480/70966290-b711c100-20cd-11ea-9e8c-02a5d28d4e84.png)

**Comment by preethammavin** [comment]
@vipwwjie can you verify if the requests go through with curl and let us know? you can generate the request from Postman Code generator which is right below the save button.

**Comment by vipwwjie** [comment]
@preethammavin DELETE /teaching/redis/cache/broadcast HTTP/1.1
Host: dev-api-teaching-codemaster.codemao.cn:80
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4NjcsInVzZXJfdHlwZSI6ImFkbWluIiwianRpIjoiMGRkMzFlOTctZWZhZi00ZjczLTg5YzQtZTM4M2Y4ZGM4NjU4IiwiaWF0IjoxNTc1MDI3MTA2fQ.TRqDUyon7m_lHqR-8rTnR6_oxMCSi5Lt0x-df2rEUik
User-Agent: PostmanRuntime/7.20.1
Accept: */*
Cache-Control: no-cache
Postman-Token: 3620b67a-7531-4be1-9c96-9c467e05ef1f,9ede6ded-9f80-4d68-a99c-74e1d389621d
Accept-Encoding: gzip, deflate
Referer: http://dev-api-teaching-codemaster.codemao.cn:80/teaching/redis/cache/broadcast
Connection: keep-alive
cache-control: no-cache

**Comment by vipwwjie** [comment]
@preethammavin

**Comment by saswatds** [comment]
@vipwwjie I have deleted the comment because it contained sensitive information.

**Comment by vipwwjie** [comment]
@saswatds Get it. I have blocked sensitive infomation.

**Comment by vipwwjie** [comment]
@preethammavin thanks for your answer.
Postman code as follows:
DELETE /teaching/redis/cache/broadcast HTTP/1.1
Host: xx:80
authorization: Bearer
User-Agent: PostmanRuntime/7.20.1
Accept: */*
Cache-Control: no-cache
Postman-Token: 857ae048-5c81-4996-b4b1-e48a40a407fb,7e9e50bb-f4dd-4caa-abe4-3ff55ee0fab8
Accept-Encoding: gzip, deflate
Referer: xx
Connection: keep-alive
cache-control: no-cache

I tried it in my frend's postman, it worked. I don't know why.

**Comment by vikiCoder** [comment]
@vipwwjie Can you please check whether there are any redirects happening in your request? You can check that in Postman console by looking for a redirect sign if there is any (like shown in the screenshot below). If there is a redirect with redirect code other than 307 and 308, Postman changes any request method (DELETE in your case) to GET method while following redirects. You can change this behavior by turning on `Follow original HTTP Method` request setting (from settings tab of your request).

<img width="758" alt="Screenshot 2019-12-19 at 12 56 33 PM" src="https://user-images.githubusercontent.com/16588032/71154073-b65d6400-2260-11ea-9f01-dcb25c2baa84.png">

**Comment by vipwwjie** [comment]
@vikiCoder Sorry to reply so late. thank you so much, according to your help, it worked.
