### ISSUE TITLE
Override the 'Host' header

### ISSUE THREAD

**Issue by lnetherton** [a85/POSTMan-Chrome-Extension#781]
I have just come across PostMan and it seems to be a perfect replacement for the archaic use of `curl` that I am currently using.

However, I can't completely move to PostMan because there seems to be one feature that `curl` can perform which PostMan can't. I often use curl to send a POST request to a specific server, bypassing our load balancer. The problem is that our web engine is bound to a specific hostname. Lets call it: loadbalanced.mysite.com. The 'real' servers that sit underneath the load balancer have names like internal1.mysite.com and internal2.mysite.com.

An example `curl` POST request to our normal service might look like this:

    curl -X POST -F "SomeKey=12345" http://loadbalanced.mysite.com

The problem here is that the load balancer chooses which real server to send the request to, and we have no control over which one that will be. So, the trick I employ to send a request to a specific server is to override the Host header:

    curl -X POST -H "Host: loadbalanced.mysite.com" -F "SomeKey=12345" http://internal1.mysite.com

This works fine in `curl`. Unfortunately, when I try to add a "Host" to the header list in PostMan it doesn't work. If I view the preview of the HTTP request then I can see why:

    POST /api/searchsimilar HTTP/1.1
    Host: internal1.mysite.com
    Host: loadbalanced.mysite.com
    Cache-Control: no-cache

It seems that the Host in the header is being written twice, rather than being overridden. With the 'wrong' Host being placed first.

**Comment by a85** [comment]
As pointed by @abhijitkane, you can use the Postman Interceptor extension to get around this.

**Comment by mucyomiller** [comment]
Thanks You save my day!

**Comment by chefren** [comment]
For anyone landing here still, the current postman app allows overriding by simply adding the Header again, here's an example with a `HOST` variable to populate the header. Notice the default calculated value is stroked out.
![Screen Shot 2022-08-24 at 16 52 41](https://user-images.githubusercontent.com/2918150/186350932-3cd09db5-5ad5-4d9d-a06e-95166982cef3.png)

This header trick also would cater for the `--connect-to` enforcing behaviour [in curl](https://www.man7.org/linux/man-pages/man1/curl.1.html)
