### ISSUE TITLE
edit mode closes unexpectedly

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#7811]
**To Reproduce**
1. Open any collection
2. Right сlick on any folder or request and select "rename"
3. Selected item name became editable
3. Move mouse cursor a bit
4. request or folder name became fixed

**Expected behavior**
It is expected to hold edit mode untill i press return or click anywhere on the screen

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version 7.13
 - OS: windows 7 pro 32 bits

**Additional context**
When I select item to rename and press ctrl+E, it is holds renemable if I don't move mouse cursor. The issue wasn't notised on previous versions of postman

**Comment by harryi3t** [comment]
@m3dbedb Thanks for raising the issue. We were not able to reproduce the issue on our end.
Can you share a screen recording showing the issue? It would help us identify and fix the issue faster.

**Comment by m3dbedb** [comment]
I will try to share it later. It happened when I worked in windows 10 connected via rdp to windows 7 with postman. Maybe deal in rdp.

**Comment by harryi3t** [comment]
@m3dbedb Closing this out due to lack of activity. 
If the issue persists, please let us know with steps to reproduce or a screen recording.
