### ISSUE TITLE
SQL Code

### ISSUE THREAD

**Issue by atulTrip** [a85/POSTMan-Chrome-Extension#7818]
**Is your feature request related to a problem? Please describe.**
Can the "Code" be available in SQL programming/stored procedure call

**Describe the solution you'd like**
Can the "Code" be available in SQL programming/stored procedure call

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by preethammavin** [comment]
@atulTrip can you give more details on your workflow and the use case for us to better understand the request.

**Comment by DannyDainton** [comment]
Hey @atulTrip 

As no additional information has been shared about this feature request, I'm going to close this for now. If this is still a feature that you would like to see, please provide some more context and details of the workflow.
