### ISSUE TITLE
Problem with sections order in documentation

### ISSUE THREAD

**Issue by victor-v** [a85/POSTMan-Chrome-Extension#7819]
**Describe the bug**
Sections structure order in app (https://c2n.me/45a93fz) is different to documentation https://c2n.me/45a97od

**To Reproduce**
1. create sections in app
2. publish docs
3. see difference

**Expected behavior**
Expected that order structure in docs will be same as in app. 

**Screenshots**
https://c2n.me/45a93fz 
https://c2n.me/45a97od

**App information (please complete the following information):**
 - Postman Version [v7.14.0]

**Comment by mrz1836** [comment]
Having same issue. Most current version of Postman, every collection is in sync. Cleared cache, cannot get it to list my requests right.

(Left is docs - Right is my postman)
<img width="433" alt="Screen Shot 2019-12-18 at 3 47 31 PM" src="https://user-images.githubusercontent.com/3743002/71122109-d253fd80-21ad-11ea-9d57-9ecbb302e2d7.png">

**Comment by Raja-Simha** [comment]
@victor-v and @mrz1836 thanks for reporting this issue. I can reproduce this and we will look into it.

**Comment by mrz1836** [comment]
Any update on this @Raja-Simha ? It seems it's only getting worse... and it's becoming annoying that I can't sort the requests (making it harder for the users reading documentation)

My /users/ requests (docs [left] vs postman app [right])
<img width="511" alt="Screen Shot 2020-01-13 at 1 35 48 PM" src="https://user-images.githubusercontent.com/3743002/72281998-bfe0ae80-3609-11ea-921a-4b68e1105e83.png">

**Comment by Raja-Simha** [comment]
@mrz1836 Changes to request order will not be reflected within public docs immediately but it should in some time once the changes are synced and they bypass cache. Could you please let me know if that is not the case.

**Comment by mrz1836** [comment]
@Raja-Simha  No that one folder is fubar. The sort/order does not work at all in the "users" folder. Let me know if you want to chat or DM I can show you.

**Comment by Raja-Simha** [comment]
@mrz1836 Sure. Let's chat.

**Comment by mrz1836** [comment]
@Raja-Simha  You can find my email or twitter handle from [my website](https://mrz1818.com)

I can share you my collection and documentation and you can see/test it.

**Comment by ranchanarajasekaran** [comment]
This behaviour is not reproducible.
Closing this for now, please feel free to reopen if you’re still facing this.
