### ISSUE TITLE
Large Integer Rounding Creates Differences in Raw versus Pretty

### ISSUE THREAD

**Issue by pcarrollsbr** [a85/POSTMan-Chrome-Extension#7822]
This is an appeal to reconsider a previous concern and possibly act on it differently than was done in 2017-2018: https://github.com/postmanlabs/postman-app-support/issues/2736.
Let's support large numbers as first class citizens in Postman. Without such support, undetected differences between 'Pretty' and 'Raw' will occur causing unnecessary diagnosis, triage, and workarounds. 

I encountered large integers, because the API I am testing returns a Unix timestamp in nanoseconds. Unix time is the number of seconds that has elapsed since 1-Jan 1970 midnight UTC. It requires 19 digits accuracy. 

Timestamps that are returned like this in a raw response: 1576606385826164**100** appear like this in the pretty: 1576606385826164**200**. 

**Screen Captures**

Here is a sample Postman Console 'Pretty' versus 'Raw' response. Observer the values for "created". 
![image](https://user-images.githubusercontent.com/57232222/71123229-35469400-21b0-11ea-8d6e-1de07923aa71.png)

![image](https://user-images.githubusercontent.com/57232222/71123248-3d063880-21b0-11ea-96eb-86066755fc53.png)

In one instance within the screen captures, “created” in the response body shows in pretty as: 1576020549598484700 while in raw: 1576020549598484800
a difference of 100 nanoseconds in that case. 

**Expected behavior**
If raw and pretty can not be made identical, does it make sense to offer a means to detect that rounding has occurred? 

**App information (please complete the following information):**
Postman v7.13.0

**Comment by shamasis** [comment]
@pcarrollsbr - just to be on same page, you’re specifically referring to this being an issue in Postman Console and not in the response rendering in the builder window? I’m confirming since we’ve recently ensured that response is shown as-is without JSON parsing in the response view. 

Console on the other hand might need some work from our end.

**Comment by pcarrollsbr** [comment]
Yes, I was more concerned about the disconnect between raw and formatted within the console. As you can see in the builder, there may be lingering affects from really big numbers. 
  

  
  

----------------------------------------

**Comment by vikiCoder** [comment]
Hi @pcarrollsbr, I was able to reproduce the problem. We will be fixing this soon. Stay tuned for the updates.

**Comment by shamasis** [comment]
Hi,

The latest version of console shows responses without any form of parsing and as such prevents any misleading large integer issue.

![image](https://user-images.githubusercontent.com/232373/81510021-780a3380-932c-11ea-8527-4112e316f41e.png)
