### ISSUE TITLE
Double clicking the title bar of postman app makes window invisible

### ISSUE THREAD

**Issue by huangjingcai** [a85/POSTMan-Chrome-Extension#7823]
My OS:
macOS Catalina 10.15.2

Postman Version:
7.14.0

II have encountered it a few times and reinstalled each time。
<img width="1365" alt="WX20191219-104523@2x" src="https://user-images.githubusercontent.com/3855873/71140678-e7cc3480-224c-11ea-8286-8b26a094e358.png">

**Comment by harryi3t** [comment]
@huangjingcai Thanks for reporting the issue 👍 
We were able to reproduce it and are working on a fix. We will update this thread once the fix is available.

**Comment by twitharshil** [comment]
@huangjingcai We have fixed this issue in Postman v7.19, if you are still facing it please let us know.
