### ISSUE TITLE
Enabling "Include Temporary headders" Does not include inherited Auth bearer tokens

### ISSUE THREAD

**Issue by firewuff** [a85/POSTMan-Chrome-Extension#7827]
Since the upgrade to v7.14.0 generating code from a Postman request is not including the temporary headders generated by postman, specifically those generated from inherited Auth settings.  

This is related to the "New Code Generation Mode". 

**To Reproduce**
1. Create a collection and set the AuthZ to "Bearer Token" and provide a value
2. Create a call in that selection and set the AuthZ to "inherited from Parent"
3. click the code button and select the gear icon.  ensure "Include Temporary headers" option is enabled
4. select cURL for the code type (for example) 

**Expected behavior**
Response should include a line similar to the below
  --header 'Authorization: Bearer <SOME_BEARER_TOKEN>' \

**Actual behaviour** 
This line is missing, only the basic cURL command is being displayed

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.14.0
 - Windows 10

**Additional context**
This behaviour is NOT seen if you send a request in postman first.  it only occurs if you open a new request and try and generate the code, in which case ALL temp headers are seen including the AuthZ

Adding a bearer authz at the call level works if you click "preview Request" first, in this case ONLY the AuthZ header is seen in the generated code.  There is however no way to do this for inherited Auth.

**Comment by codezninja** [comment]
Could this also be causing the issue with copy the headers to another request. For instance if I have a call with Auth Basic Auth when I click on a link to a new tab it won't auth since its not picking the temporary headers. If I do no auth and set the Authorization header manually in the first request. the subsequent clicks copy it successfully

**Comment by HodGreeley** [comment]
I'm also seeing this with v7.20.0 on a Mac.

On a related note, why is inherited auth treated as a temporary header in the first place?

**Comment by shreys7** [comment]
Hey @firewuff, with Postman 7.21.0, We have improved experience around the headers which lets you see all the headers that will be sent with the request, beforehand. Thus, we have removed the `Include Temporary headers` option from code generator configurations, and this header will be automatically added to the code generated.

**Comment by firewuff** [comment]
Thanks, I can confirm that this is fix and working as expected.  Keep up the great work!
