### ISSUE TITLE
Postman goes blank (javascript exception)

### ISSUE THREAD

**Issue by gulvklud** [a85/POSTMan-Chrome-Extension#7829]
**Describe the bug**
If i don't hurry and open the developer console during startup, the app will crash and go blank.

**To Reproduce**
Unfortunately, haven't been able to reproduce on any of my coworkers computers.

I think it might have something to do with me having some pretty huge (5mb+) json payloads stored in my collections.

**Expected behavior**
To not go blank on startup.

**Screenshots**
![image](https://user-images.githubusercontent.com/1478224/71238120-99c63800-2303-11ea-9947-47ad164b4a97.png)
![image](https://user-images.githubusercontent.com/1478224/71238157-afd3f880-2303-11ea-816a-97fbaa541b29.png)

**App information (please complete the following information):**
 - App Type: Windows App
 - Postman Version: 7.14.1
 - OS: Windows 10

**Comment by mccannt** [comment]
@caroen Is this still an issue for you on the most recent version of the application?

**Comment by mccannt** [comment]
Closing this issue due to input from the original user. 
If this is still an issue, please let us know and we can reopen this issue.
