### ISSUE TITLE
Facing slowness while using collections

### ISSUE THREAD

**Issue by parsh7** [a85/POSTMan-Chrome-Extension#7830]
Hi Team,

There is huge slowness i'm facing in postman while using collections. There is not more than 20 api's in my collection still getting slowness.

Regards,
Prashant Patil

**Comment by bauzer714** [comment]
Seeing the same issue. Modifying even a single form data parameter will put postman into a tailspin and peg the CPU at 100% for several minutes.  Those not on 7.14 have no issue.

Affected Version: v7.14.0

**Comment by mccannt** [comment]
@parsh7 @bauzer714 Are you still facing this issue with the most recent version of the application?
We have made recent performance and stability improvements that should help with this issue.

**Comment by bauzer714** [comment]
I haven't been using postman as much lately, but don't recall still having this issue.
