### ISSUE TITLE
Show folder name in collection runner

### ISSUE THREAD

**Issue by sjoller** [a85/POSTMan-Chrome-Extension#7831]
I have all my tests nested in folders, but when I go to the collection runner, the "RUN ORDER" list only shows icons for the folders, and when mousing over, it just says "Folder".
It would be a lot more useful if the folder name was shown in the list or, at the very least, in the mouseover text.

![image](https://user-images.githubusercontent.com/628256/71258342-36a1c900-2336-11ea-8a08-46fa9abc3237.png)

**Comment by giridharvc7** [comment]
This is now fixed, please check Postman version 8.x in the app or try out Postman web. http://postma.com/app
