### ISSUE TITLE
Postman: Sign Up with Google Button doesn't response (Screen record attached) WIN10 x64 Desktop App

### ISSUE THREAD

**Issue by or-hasson** [a85/POSTMan-Chrome-Extension#7835]
**Describe the bug**
Postman: Sign Up with Google Button doesn't response (Screen record attached) WIN10 x64 Desktop App

**To Reproduce**
1. Download Postman x64 on Win10.
2. Install Postman.
3. After open Postman Desktop App the Sign with Google button doesn't Response.

**Expected behavior**
The OAuth with Google button should work.

See the attached video: 
https://streamable.com/ahk69

 - App Type: Desktop Application x64
 - Postman v7.14.0
 - OS: Win10 x64

Thanks,

Or Hasson

**Comment by or-hasson** [comment]
It seems not to response in the first time after the installation.

**Comment by gdbhowmick** [comment]
@Hasson777 You need to accept the terms of use. You need to check the first checkbox.

**Comment by or-hasson** [comment]
> @Hasson777 You need to accept the terms of use. You need to check the first checkbox.

Thanks It seems to solve it.
But I think it should notify the user to do that first or at least when click the button.

Thanks,
Or Hasson
