### ISSUE TITLE
Invisible archived collection

### ISSUE THREAD

**Issue by artchen** [a85/POSTMan-Chrome-Extension#7837]
**Describe the bug**
In "My Workspace" there is always a warning of "_Some collections in this workspace are archived because free plan only supports 25 shared requests. Don't worry, you can still access them but won't be able to work on them. Postman paid teams get unlimited shared requests._". But when I click into the archived collections web page it says Your archive is empty.

**To Reproduce**
1. Go to Collections list of My Workspace.
2. Click on "ARCHIVED COLLECTIONS (1)".
3. The Archived Collections page shows no collection.

**Expected behavior**
The Archived Collections page should show the one archived collection with actions that I can take (delete, unarchive, etc).

**Screenshots**
https://cdn.otakism.com/images/share/Screen%20Shot%202019-12-21%20at%203.48.32%20PM.png
https://cdn.otakism.com/images/share/Screen%20Shot%202019-12-21%20at%203.48.40%20PM.png

**App information (please complete the following information):**
 - App Type: Native app (both Win and Mac), Web app.
 - Postman Version: Latest
 - OS: macOS Catalina

**Additional context**
N/A

**Comment by sankalp0o** [comment]
Hey @artchen , thanks for bringing this to our attention. This is not the expected behaviour and we'll look into this. Will keep you updated.

**Comment by artchen** [comment]
Thanks for taking a look. Looking forward to the fix. Lemme know if you need my account identifier to look into the data.

**Comment by avani-n** [comment]
@artchen Is the issue still happening? If yes, could you please write to us at help@getpostman.com with the workspace id so that we can take a closer look.

Please include the GitHub issue number - 7837 in the email.

Thanks

**Comment by artchen** [comment]
The issue still persists. Could you lemme know how to find the workspace id, and do you refer to "My Workspace"? I don't have any team workspace under my account as for now.

**Comment by avani-n** [comment]
Hi @artchen 

Our support team has received required information at help@getpostman.com from you and would be following up with any additional questions required to resolve this issue.

**Comment by avani-n** [comment]
@artchen We have identified the root cause and underlying issue is now resolved! Let us know if you're still experiencing issues.
