### ISSUE TITLE
Sign in with Google faild, 500 errors.

### ISSUE THREAD

**Issue by czd890** [a85/POSTMan-Chrome-Extension#7839]
Version: You are up to date! Postman v7.14.0 is the latest version.

![image](https://user-images.githubusercontent.com/4011549/71333695-f2047080-2575-11ea-8b5f-6f6379edb621.png)
![image](https://user-images.githubusercontent.com/4011549/71333712-0a748b00-2576-11ea-9800-f04fe60c054b.png)
![image](https://user-images.githubusercontent.com/4011549/71333760-3e4fb080-2576-11ea-90d1-51176af4c9a6.png)

**Comment by preethammavin** [comment]
@czd890 are you experiencing this still, I see that our services are functional and running.

**Comment by patlola** [comment]
@preethammavin just downloaded a new mac build version -> 7.14.0 (7.14.0), getting 5xx while doing `sign in with google` even try on web browser is getting the same error because it's taking me to the same link.

update: It looks like this is fixed. thanks

**Comment by kartios** [comment]
@preethammavin I am getting the exact issue as OP. I have the latest version of Postman as well.

**Comment by godfrzero** [comment]
@kartios Could you let us know if this happening consistently, or if it's intermittent? In addition, if you try to sign in directly from the browser (without having the app involved) via https://identity.getpostman.com/login?addAccount=1 does it still throw the same error?

**Comment by kartios** [comment]
Signing in through the browser works, I've never had a problem with that. For the app, this problem has been happening consistently. I have not been able to log into it for about 5 days now, with the same exact 500 error OP showed.

**Comment by ghost** [comment]
@kartios That error which you got, was it on app, or on web, were you able to complete the signin in browser (which opens when you click sign in with google in app)? Also was your session expired when you initiated sign in with google, i.e did you see this kind of view (with your email being masked) when you clicked on sign in with google, 
![image](https://user-images.githubusercontent.com/59233498/71449502-98699500-2773-11ea-97dd-c9ced00c2883.png)

**Comment by kartios** [comment]
It happens in the browser after I click "Sign in with Google". Originally I saw the email masked as you show it, but now I don't even see that because I signed out hoping that would work. If I actually log into the browser it works but then I don't get any of the postman features, I can just see some of our endpoints and get some cURL commands.

This error is still happening by the way, and it has been almost two weeks I'd say.

**Comment by ghost** [comment]
@kartios Do you happen to use VPN in browser, or are you behind some proxy, can you once verify that IP address in your browser and in app is same? You can check the IP address used in app by sending GET request to `https://postman-echo.com/ip` using postman and on browser you can search for `What is my IP`

**Comment by czd890** [comment]
@kartios @meetSuraj 
I found a possible cause.
500 error if I use SS proxy( proxy *.google.com) in Chrome browser

**Comment by godfrzero** [comment]
This error seems to be due to an IP check we do on the backend. @kartios Can you see if disabling the proxy temporarily fixes the problem for you?

**Comment by FlackMonkey** [comment]
Hi! It now ends up with 400 (Request invalid or expired)  on sign in from app using google sign in
Ubuntu 18.04

@preethammavin

**Comment by preethammavin** [comment]
Hi, we have pushed few stability fixes can you confirm if the issue is fixed or you continue to see the same issue pop up.

**Comment by ArjunSingh-PM** [comment]
@kartios @FlackMonkey @patlola Could you please confirm that this issue is resolved for you.

**Comment by ArjunSingh-PM** [comment]
Closing the issue for now, as we have deployed stability fixes for the same. Please do let us know if the issue continues to persist.
