### ISSUE TITLE
Program freezing when importing OpenAPI JSON file

### ISSUE THREAD

**Issue by darnley** [a85/POSTMan-Chrome-Extension#7844]
**Describe the bug**
The application freezes when I try to import a OpenAPI JSON file generated by Swagger. When I try to load a `swagger.json` ([download here](https://github.com/postmanlabs/postman-app-support/files/4000739/swagger.zip)) file which is a OpenAPI 3.0.1 specification, the program starts to use a lot of CPU and RAM memory, then it displays a black screen and nothing occurs.

**To Reproduce**
1. Go to 'Import' button at the top of program
2. Choose the tab 'Import File'
3. Click on 'Choose Files'
4. Choose the `swagger.json` file ([download here](https://github.com/postmanlabs/postman-app-support/files/4000739/swagger.zip))
5. Mark 'Generate a Postman collection' option.
6. Click on 'Next' button

**Expected behavior**
The Postman is supposed to load the `swagger.json`, which is a OpenAPI specification, to a collection.

**Screenshots**
Before I start to import the `swagger.json` file, the program uses the following resources:
![image](https://user-images.githubusercontent.com/4915497/71449444-751af780-272b-11ea-96aa-7cf7b217ff46.png)

After I start the importation, the RAM and CPU utilization increases. While that, the program doesn't respond any clicks.
![image](https://user-images.githubusercontent.com/4915497/71449453-a09de200-272b-11ea-9f4d-682797a26161.png)
![image](https://user-images.githubusercontent.com/4915497/71449461-cfb45380-272b-11ea-83fc-eb6bdb7e53fb.png)
![image](https://user-images.githubusercontent.com/4915497/71449476-e8bd0480-272b-11ea-8efa-a2a840c5da07.png)

Then the program stops the high memory/CPU utilization.
![image](https://user-images.githubusercontent.com/4915497/71449484-13a75880-272c-11ea-936b-ff2911d05df5.png)

When I go to Postman, I see a black screen.
![image](https://user-images.githubusercontent.com/4915497/71449489-2a4daf80-272c-11ea-9f76-277098bf21a5.png)

**App information (please complete the following information):**
 - Postman for Desktop v7.14.0
 - OS: Windows 10 Pro (Version 10.0.18363 Build 18363) x64
 - Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2801 Mhz, 4 Core(s), 8 Logical Processor(s)
 - Installed Physical Memory (RAM): 16.0 GB

**Additional context**
I don't have additional contexts.

**Comment by barrcodes** [comment]
Same exact issue. 

OS: Mac Catalina
CPU: 2.6 intel i7
Mem: 16 gb
Postman: 7.15.0

**Comment by dante2130** [comment]
Reproduced on 3 macOS machines with different hardware. i7 16 Gb Catalina 10.15.1-10.15.2

**Comment by ghost** [comment]
Same issue

OS: Mac Mojave
CPU: 2.8 GHz Intel Core i7
Memory: 16GB
Postman: 7.17.0

**Comment by rbonine** [comment]
Same here:

OS: Windows Server 2019 DataCenter (VM running in Azure)
16 GB RAM
CPU: Intel Xeon E5-2673
Postman v7.17.0

Swagger file is 1.46MB.   I get no feedback whatsoever after the import starts.  CPU and memory usage grows steadily and eventually I get a black screen.

**Comment by ghost** [comment]
This is still an issue in Version 7.19.0.

Postman is pretty much unusable for me as a result.

I see this is marked as 'Blocked/Need info'. What more information do you need? @devanSAGA

**Comment by kamalaknn** [comment]
Hey @dcp65 

I was able to reproduce this issue with the sample JSON attached by @darnley. This crash seems to be coming from our `openapi-to-postman` convertor node module. It seems to be reported and tracked on that repo - https://github.com/postmanlabs/openapi-to-postman/issues/124 

Looping in @abhijitkane @umeshp7

**Comment by umeshp7** [comment]
@darnley 
I tried with the file provided by you, and I was successfully able to generate collection on App v7.19. 
I request you to try it on the latest version of the App and report if you face any difficulties. 

@dcp65 Is there a specific OpenAPI schema that is causing the app to freeze for you? It would be great if you can share it with us here or you could send it over to help@postman.com and we'll take a look.

**Comment by ghost** [comment]
OK, here is an example of swagger.json that causes Postman to hang on import.

It does seem to be the circular dependency issue (postmanlabs/openapi-to-postman#124)

The thing is, this was working for me up until very recently.

```json
{
  "swagger": "2.0",
  "info": {
    "description": "Sample API",
    "version": "v1",
    "title": "Sample API",
    "termsOfService": "http://www.example.com/termsOfService",
    "contact": {
      "name": "Sample",
      "url": "http://sample.com/",
      "email": "sample@sample.com"
    }
  },
  "host": "{{host}}",
  "basePath": "/sample/api",
  "tags": [
    {
      "name": "Folder tree"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/folder-tree": {
      "get": {
        "tags": [
          "Folder tree"
        ],
        "summary": "List folder tree",
        "description": "Returns a list of folders in a nested, tree structure.",
        "operationId": "listFolderTree",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "myParam",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Auth token.",
            "required": true,
            "type": "string",
            "default": "token='{{token}}'"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/FolderTree"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "FolderTree": {
      "type": "object",
      "properties": {
        "airlineUid": {
          "type": "string"
        },
        "uid": {
          "type": "string"
        },
        "created": {
          "type": "string",
          "format": "date-time"
        },
        "modified": {
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "EMAIL",
            "NORMAL"
          ]
        },
        "description": {
          "type": "string"
        },
        "deleted": {
          "type": "boolean"
        },
        "foo": {
          "type": "boolean"
        },
        "global": {
          "type": "boolean"
        },
        "bar": {
          "type": "boolean"
        },
        "foobar": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "source": {
          "type": "string"
        },
        "sourceId": {
          "type": "string"
        },
        "sourceFields": {
          "type": "object",
          "additionalProperties": {
            "type": "object"
          }
        },
        "children": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "$ref": "#/definitions/FolderTree"
          }
        },
        "fullName": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by darnley** [comment]
> @darnley
> I tried with the file provided by you, and I was successfully able to generate collection on App v7.19.
> I request you to try it on the latest version of the App and report if you face any difficulties.
> 
> @dcp65 Is there a specific OpenAPI schema that is causing the app to freeze for you? It would be great if you can share it with us here or you could send it over to [help@postman.com](mailto:help@postman.com) and we'll take a look.

Hello, @umeshp7 . I have tested on v7.18.1 which is the lastest stable version for me and the same error happened
![image](https://user-images.githubusercontent.com/4915497/75184992-14f10380-5724-11ea-965a-df829f204719.png)
Is v7.19 a beta release? I guess that is not available for me.

**Comment by darnley** [comment]
Hello, @umeshp7 

Now the v7.19.1 is available for me.
![image](https://user-images.githubusercontent.com/4915497/75296408-ddf61d00-580b-11ea-82da-715d7e341c0d.png)

The error not happened again. I am currently able to import the swagger file without errors.
![image](https://user-images.githubusercontent.com/4915497/75296493-1990e700-580c-11ea-92ab-8b3d9146d861.png)

I guess that the issue is **resolved**.

**Comment by umeshp7** [comment]
@darnley Thank you for the confirmation. 

@dcp65 I was able to reproduce the error with your swagger schema even in v7.19.1. We are currently working on a fix for circular references. We will keep you posted on the progress.

**Comment by mroknich** [comment]
Bump. Still running into this error on version 7.21.1 (7.21.1).

**Comment by timmki** [comment]
Same here. Due to massive adaptation of Openapi in all our services it would be amazing to make this work reliably. (Version 7.21.1 on Win 10 Pro)

**Comment by umeshp7** [comment]
We are currently in the process of releasing a fix for this. 
@timmki @mroknich Is there a specific OpenAPI schema that is causing the app to freeze for you? It would be great if you can share it with us here or you could also send it over to help@postman.com and we'll take a look.

**Comment by timmki** [comment]
Unfortunately I cannot share the specification due to NDAs with our client. But we also have recursions in our model due to hierachical structures between model entities.

**Comment by llaurenz** [comment]
For me import worked when I exported using openAPI 3.0. For openApi 2.0 I also got a black screen. and postman froze. Import was also much quicker using .yaml instead of .json. 

Unfortunately, after the API import I can not create a collection:
- If I use .json file, then I get error message: "The schema size is more than the allowed limit of 5 MB."
- If I use .yaml file, then postman freezes again. After restart I shortly see the collection, but then the collection is gone.

Is there anything I can do?

**Comment by cyptus** [comment]
same issue here while using an OpenAPI 3.0 yaml definition with circular dependency.

**Comment by laverix** [comment]
same here

**Comment by alejandro501** [comment]
same issue, Ubuntu 22.04, 3 years later... any improvements?

**Comment by dhwaneetbhatt** [comment]
@alejandro501 what is the version of Postman you're using and what is the file that you are importing?

Over the years we have improved our importing experience and we are continuing to make it better. The original issue reported in this thread is no longer reproducible as Postman is able to import the data easily in the latest v10 version.

**Comment by nekkitl** [comment]
Good morning, gentlemen's 
The same. 
Latest macOS Sonoma, macpro7,1/48CT CPU
