### ISSUE TITLE
Bug on Tests

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#7845]
I set up a wrong script in "Tests" and Postman returned a OK result but it should show a message about the problem.

My case:
I was expecting a body response like this 

{
    "error": "WRONG"
}

But the body response was

{
    "error": "invalid_client"
}

And Postman returned PASS in Test Results.

![image](https://user-images.githubusercontent.com/30181711/71479261-54f24380-27d2-11ea-86c4-617a84c34d70.png)

![image](https://user-images.githubusercontent.com/30181711/71479236-3ee48300-27d2-11ea-96fb-3c3dccb6a087.png)

Thanks ;)

**Comment by vdespa** [comment]
You did not specify the second parameter for the pm.test() function.

So the syntax is not correct in this case but not a Postman bug. Use the proper syntax and it will work.

**Comment by ghost** [comment]
hello :)

my point is:

the sintax is wrong but postman doesn't alert about it. besides, it returns that the test PASS.

**Comment by ghost** [comment]
Any help?

**Comment by saswatds** [comment]
@Paulo-Sensedia The syntax is correct with respect to javascript. If you analyze you code 
```
pm.test('json value check'), 
function () {
  ...
}
```

`,` comma is valid javascript syntax. What this effectively means that. 
`pm.test('json value check')` is an empty test which will always pass and then define a `function`  which does not relate to a test. 

For more information check https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

Closing this issue as this does not seems to be a bug.
