### ISSUE TITLE
Debugs from templates used by visualiser are not logged in the console

### ISSUE THREAD

**Issue by pimajor** [a85/POSTMan-Chrome-Extension#7846]
On Windows 10, Postman App v7.14.0.
Debugs such as "console.log("test")" in the template of the visualiser are not logged in the console's log.
The test script performs what it should do, so it is not a script error.

This is the simple code to test the console log:
![image](https://user-images.githubusercontent.com/1444438/71481645-04450f80-27ff-11ea-9295-22d13214fa23.png)

This is the output:

![image](https://user-images.githubusercontent.com/1444438/71481670-1fb01a80-27ff-11ea-8437-e00dddd9e400.png)

This is the console log ():
![image](https://user-images.githubusercontent.com/1444438/71481656-12932b80-27ff-11ea-9173-6922073b132f.png)

I expect to see a console log " test inside", one can see that the last console.log in the test is working.

**Comment by vikiCoder** [comment]
Hi @pimajor,

This is the intended behavior for console.log() inside visualizer templates. Logs from visualizer are not shown in Postman console. If you want to see those logs, you can open developer window for the visualizer template by right-clicking on the visualizer area and selecting `inspect visualization` as shown in below GIF. Please refer to [this link](https://learning.getpostman.com/docs/postman/sending-api-requests/visualizer/#debugging-visualizers) (https://learning.getpostman.com/docs/postman/sending-api-requests/visualizer/#debugging-visualizers).

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16588032/71509732-5bf08300-28b2-11ea-8cc2-5cb33fa13623.gif)
