### ISSUE TITLE
Error in "Tests": Something Went Wrong - stops the user from doing anything due to code error

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7848]
**Describe the bug**
While using the editor, it seems that the error Something Went Wrong prevents the user from doing anything.

**To Reproduce**
1. Open a request, go to Tests
2. Paste the following code:

`pm.response.to.have.jsonSchema(schema:Objec);`

3. Try deleting the letter "c" from schema:Objec

**Expected behavior**
No error

**Screenshots**
<img width="649" alt="Screenshot 2019-12-27 at 10 12 54" src="https://user-images.githubusercontent.com/1197635/71508877-f391a980-2891-11ea-832c-db9f173586c0.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.14.0 (7.14.0)
 - OS: macOS

**Additional context**

**Comment by shamasis** [comment]
This looks serious. We are on it.

**Comment by ritwijsinha** [comment]
Hey @vdespa,

I'm unable to reproduce this bug. This is what happens when I follow your steps (tried deleting both the `"c"` characters in "s**c**hema:Obje**c**", also tried using `fn + delete`):

![Github7848](https://user-images.githubusercontent.com/19693841/73159302-3c948200-410c-11ea-93ce-4ad143a33f6a.gif)

Are you reliably able to reproduce this? If yes, it would be awesome if you could help us reproduce this!

Cheers.

**Comment by coditva** [comment]
@vdespa Do you have a collection variable with value as an object? And do you see any logs in the Chrome Developer Tools?

This might be similar to https://github.com/postmanlabs/postman-app-support/issues/7759

**Comment by vdespa** [comment]
I have reported this back in December. I can't reproduce this anymore in Version 7.16.0.

**Comment by vdespa** [comment]
I recently encountered this issue again. 

![ezgif-2-1b78d8e09c9d](https://user-images.githubusercontent.com/1197635/74037454-48920680-498c-11ea-95f7-7e8b06e0f221.gif)

As you can see, the request is not part of a collection. But I did manage to catch an error in the DevTools.

<img width="992" alt="Screenshot 2020-02-07 at 09 27 21" src="https://user-images.githubusercontent.com/1197635/74037497-6495a800-498c-11ea-91ea-25edc4559e6d.png">

"xml.js:22 Error: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Badditionalneeds%2C%20bookingdates%2C%20depositpaid%2C%20firstname%2C%20lastname%2C%20totalprice%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

**Comment by coditva** [comment]
I think I got it. @vdespa Can you confirm that you have a global variable with key of type `object`?

**Comment by vdespa** [comment]
Yes, I do have one of type object @coditva

**Comment by arlemi** [comment]
@vdespa We've pushed a fix for this in 7.18.0, can you try again and let us know if you're still seeing the issue?

**Comment by vdespa** [comment]
@arlemi - still crashes in Version 7.19.1

**Comment by arlemi** [comment]
@vdespa Yep my bad, we fixed an issue that was similar but not exactly the same. Will keep updating when we pick it up. :)

**Comment by coditva** [comment]
@vdespa Hi! This is now fixed in Postman `v7.20.0`! 🎉

**Comment by vdespa** [comment]
Great to see this fixed! Thank you.
