### ISSUE TITLE
Exporting environment doen't include correct current values

### ISSUE THREAD

**Issue by hiren929** [a85/POSTMan-Chrome-Extension#7849]
**Describe the bug**
Postman for PC version v7.14.0. Exported environment file has correct initial value but wrong current value. Current value for all variables is same a initial value, which is wrong. 

**To Reproduce**
1. Add new environment
2. Add a variable with different current and initial values
3. Export to a file
4. Look into the file

**Expected behavior**
Correct current value from the environment

**App information (please complete the following information):**
 - Postman for PC version v7.14.0.

**Comment by vdespa** [comment]
Hi @hiren929 

This is expected.

The current value is something that is private to your account / local installation and does not get shared.

If you don't want this, you can change the following setting:

![image](https://user-images.githubusercontent.com/1197635/71544213-e30e2b80-2984-11ea-9433-c635cf6a541b.png)

**Comment by hiren929** [comment]
Got it. Thx.
