### ISSUE TITLE
You did not fetched handover early enough.

### ISSUE THREAD

**Issue by pazfelipe** [a85/POSTMan-Chrome-Extension#7851]
I cannot sign in with google account. Everytime I tried to sign in this message appeared:

> you cannot fetch handover more than once

now, this one appears:

> You did not fetched handover early enough

**Comment by majidmvulle** [comment]
Same issue.

![Screen Shot 2019-12-29 at 16 56 23](https://user-images.githubusercontent.com/1475098/71557195-2a1b2000-2a5c-11ea-92b8-69707f346c1c.png)

**Comment by majidmvulle** [comment]
@pazfelipe Clear cache or use a different browser/incognito. Works for me now.

**Comment by specialtactics** [comment]
Same here, I tried using both incognito and a different browser, same outcome.

Really ridiculous, I tried every option, tried to log in with browser (same error), I kept using the "go into the app anyway" option, but it would just ask me to sign in again. After maybe 10 mins of messing around with it, I finally was able to end up in offline mode without postman blocking me with a sign-in window.

We have a paid team account, and this is really unacceptable, if the sign in is broken, at least let people use the app offline without wasting time on gymnastics !

**Comment by ArjunSingh-PM** [comment]
@pazfelipe Thank you for reporting this issue. We have identified the root cause for the same and are working to resolve it.

**Comment by ghost** [comment]
@specialtactics Can you provide us exact error message that you are getting, is it `You did not fetched handover early enough` or `You cannot fetch handover more than once` error. 

Can you provide us the exact step you took for logging in?

**Comment by vlad88sv** [comment]
I'm getting the same on Ubuntu 9.10, Postman 7.13.0, this happens only with login via Gmail

Tried incognito tab, etc.

Edit: I had to reset (or set?) my password and login without Gmail, it worked flawlessly

**Comment by specialtactics** [comment]
@meetSuraj 

1. Start postman app (linux, fedora 64bit)
1. Log in option
1. Sign in using google
1. Launches a link which looks like this `https://identity.getpostman.com/client-auth/start?auth_challenge=XXXXXXetc` in my browser (chrome, but I also tried firefox, and private windows for both as I said)
1. Error: **You cannot fetch handover more than once.**
1. Then I try and click the link from postman, "open in your browser"
1. I get the error **You did not fetched handover early enough.** (even if I do it very quick)

Also worth noting, I'm running the latest version of postman.

Also I can't get into offline mode again - it is not clear at all how to do this, please outline. I don't want to sign out and lose all my local data that I am working with.

**Comment by ghost** [comment]
@specialtactics So for the first time when the link opened up in your browser as soon as you click on `Sign in with Google`, What error does it throw then? When you say you tried in other browsers, did you mean you copied the link and pasted it in another browser and incognito window to try?

**Comment by specialtactics** [comment]
@meetSuraj The first time it shows **You cannot fetch handover more than once.**

>  When you say you tried in other browsers, did you mean you copied the link and pasted it in another browser and incognito window to try?

Yes, correct.

**Comment by ghost** [comment]
@specialtactics Meanwhile you can follow the step @vlad88sv took, you can reset your password and login normally without google.

1. Go to identity.getpostman.com
2. Click trouble signing in
3. Enter your email
4. On your mail password reset link will come
5. Click it and set your password
6. Login without google using that password

**Comment by specialtactics** [comment]
Thanks @meetSuraj that worked, I can access postman gain without google auth.

**Comment by ghost** [comment]
@vlad88sv Were you also facing the `You cannot fetch handover more than once` initially, as soon as the browser opened when you clicked on `Sign in with Google`? Are you able to reproduce it?

**Comment by vlad88sv** [comment]
@meetSuraj yes, I signed out and and retried, same result.

![image](https://user-images.githubusercontent.com/91489/71723880-e6297180-2df3-11ea-9ebe-b373d0c439e2.png)

**Comment by vlad88sv** [comment]
Additional info:

- Installed via Snap
- I get these messages on console on start (even if I have xdg-mime available):
> ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
>Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed

**Comment by ghost** [comment]
@vlad88sv Can you disable all your extensions in browser and try again, I suspect some extension is reloading the page, which causes this error.

**Comment by vlad88sv** [comment]
Oh! I think I've found the issue.

On Kubuntu, when postman tries to open the Gmail's SSO URL it calls kio-slave, it prefetches the URL to open the appropriate app based on the output.

So, when kio-slave founds it's HTMl it opens the browser, but the link is already invalid.

**Comment by specialtactics** [comment]
@vlad88sv  That maybe makes sense, because I'm using KDE as well.

**Comment by vlad88sv** [comment]
Well I think I can confirm that's the cause
![2020-01-07_19-04](https://user-images.githubusercontent.com/91489/71941871-ea051d00-3180-11ea-932d-e1c1a78f503a.png)

KIO slave log:

```
kdeinit5: Got EXEC_NEW '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/http.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/http.so'
kf5.kio.kio_http: 
kf5.kio.kio_http: Hostname is now: "identity.getpostman.com" ( "identity.getpostman.com" )
kf5.kio.kio_http: QUrl("https://identity.getpostman.com/client-auth/start?auth_challenge=*redacted*&auth_device=app_native")
kf5.kio.kio_http: QUrl("https://identity.getpostman.com/client-auth/start?auth_challenge=*redacted*&auth_device=app_native")
```

...followed by a long http exchange between google and kio-client, which resulted in `Emitting mimetype  "text/html"` that causes Chrome/browser to open.

This can be verified by using this guide:
https://community.kde.org/Guidelines_and_HOWTOs/Debugging/Debugging_IOSlaves#GUI_.28Qt5.2FKF5_instructions.29

**Comment by elzdave** [comment]
> @meetSuraj
> 
>     1. Start postman app (linux, fedora 64bit)
> 
>     2. Log in option
> 
>     3. Sign in using google
> 
>     4. Launches a link which looks like this `https://identity.getpostman.com/client-auth/start?auth_challenge=XXXXXXetc` in my browser (chrome, but I also tried firefox, and private windows for both as I said)
> 
>     5. Error: **You cannot fetch handover more than once.**
> 
>     6. Then I try and click the link from postman, "open in your browser"
> 
>     7. I get the error **You did not fetched handover early enough.** (even if I do it very quick)
> 
> 
> Also worth noting, I'm running the latest version of postman.
> 
> Also I can't get into offline mode again - it is not clear at all how to do this, please outline. I don't want to sign out and lose all my local data that I am working with.

Same here, using Postman on Fedora 31

**Comment by ghost** [comment]
@elzdave That link which gets opened in browser can be only used once, and it is somehow getting requested to before it is open in browser, that is why you are getting that error, other people that are facing the same issue, problem was that in KDE, link gets fetched before to check the mime type and based on mime-type application is opened, in case of `text/html` it is browser. Can you see if it is the same case for you? Meanwhile you can follow the method outlined [here](https://github.com/postmanlabs/postman-app-support/issues/7851#issuecomment-570447153) and login to continue your work.

**Comment by elzdave** [comment]
@meetSuraj yes, exactly as you stated above, the problem was caused by KDE. Followed your proposed method and managed to login manually with new password works for me, thank you

**Comment by godfrzero** [comment]
We've tweaked the login flow a bit to address the issues mentioned in this thread. @elzdave @pazfelipe Can either of you confirm that the browser-based login flow works as expected for you now?

**Comment by elzdave** [comment]
@godfrzero I did logout and login again using "Sign in with Google" options and it worked perfectly as expected. Thank you for addressing this issue

**Comment by godfrzero** [comment]
Awesome, thanks for confirming @elzdave. I'm closing this ticket then.
