### ISSUE TITLE
Unable to start postman stable installed via snap on ubuntu 19.10

### ISSUE THREAD

**Issue by mukulsharma9118** [a85/POSTMan-Chrome-Extension#7852]
**Describe the bug**
Unable to start postman stable installed via snap on ubuntu 19.10
Installed it using **sudo snap install postman**

**To Reproduce**
Go to gnome menu and click on postman
type postman on terminal

**Comment by ankurdengla** [comment]
Hey @mukulsharma9118 , we were not able to reproduce the issue at our end (on ubuntu 19.10). Here are the steps we followed - 
- Installed postman using **sudo snap install postman** on terminal
- Executed app using menu
- Executed using **postman** command in terminal
In both the cases, the app opened normally.

Could you help us by letting us know the error message that you are seeing when trying to execute the app from the terminal?

**Comment by alainbelez** [comment]
i'm also unable to launch snap version 7.13.0 on ubuntu 18.04. i forgot which version i was using before, but it was running fine before. i can however launch the app using `/snap/postman/97/usr/share/Postman/Postman`

**Comment by mukulsharma9118** [comment]
> i'm also unable to launch snap version 7.13.0 on ubuntu 18.04. i forgot which version i was using before, but it was running fine before. i can however launch the app using `/snap/postman/97/usr/share/Postman/Postman`

Same with me i was able to launch the app via /snap/postman/97/usr/share/Postman/Postman

**Comment by mukulsharma9118** [comment]
> Hey @mukulsharma9118 , we were not able to reproduce the issue at our end (on ubuntu 19.10). Here are the steps we followed -
> 
>     * Installed postman using **sudo snap install postman** on terminal
> 
>     * Executed app using menu
> 
>     * Executed using **postman** command in terminal
>       In both the cases, the app opened normally.
> 
> 
> Could you help us by letting us know the error message that you are seeing when trying to execute the app from the terminal?

There was no error message, Terminal waits for some second and then nothing happens,
I moved to the flatpak version and hence closing this issue

**Comment by ghost** [comment]
Create an empty file on the desktop and paste the following text in it, save and launch!

```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=Postman
Icon=/snap/postman/current/usr/share/Postman/resources/app/assets/icon.png
#Exec=/snap/postman/current/usr/share/Postman/Postman %U
Exec=/snap/bin/postman
Categories=Development;
MimeType=x-scheme-handler/postman
Terminal=false
```

**Comment by frederikheld** [comment]
Same issue here. Fresh install of postman 7.19.1 via "sudo snap install postman" after I had uninstalled a previous version which didn't start. Newly installed version doesn't start as well, neither via app drawer nor via terminal. Ubuntu version is 19.10.

**Comment by harryi3t** [comment]
@frederikheld I did a fresh installation of ubuntu 19.10 and installed Postman using snap. I could not reproduce the issue. Could you share the logs that you see on the terminal while running following commands:

```bash
which postman 
// should be "/snap/bin/postman"

postman 
// it should include something like 
// xxxxxxxx main info "Booting Postman 7.19.1, linux-5.3.0-40-generic on x64"
```

**Comment by frederikheld** [comment]
This is what happens:

```sh
frederik@laptopf2-1:~$ which postman
/snap/bin/postman
frederik@laptopf2-1:~$ postman
frederik@laptopf2-1:~$ 
```
After running the `postman` command, there's a period of 10 to 20 seconds in which nothing happens, then I'm back at the command prompt. No output.

If I run `postman` again, I'm back at the prompt without noticable delay.

Feels like there's some first-start procedure that fails...

Is there something like `postman -v` to get more verbose output?

**Comment by frederikheld** [comment]
This is what happens:
```sh
frederik@mycomputer:~$ which postman
/snap/bin/postman
frederik@mycomputer:~$ postman
frederik@mycomputer:~$ 
```

After I have run the `postman` command, there is a period of 10 to 20 seconds in which nothing happens. Then I'm back at the command prompt. No output.

If I run `postman` again, I'm back at the command prompt without noticeable delay.

Feels like there's some kind of first-start procedure that fails.

Is there something like `postman -v` to get more verbose output?

**Comment by frederikheld** [comment]
I did a couple of experiments. After another re-install, postman is now version 7.20.0. But same result.

This is /snap/bin, I don't know if it helps you:

```sh
frederik@mycomputer:~$ ll /snap/bin/
total n
drwxr-xr-x  2 root root 4096 Mär 15 13:42 ./
drwxr-xr-x 22 root root 4096 Mär 15 13:42 ../
[...]
lrwxrwxrwx  1 root root   13 Mär 15 13:42 postman -> /usr/bin/snap*
[...]
```

If I run `/snap/bin/postman`, the result is the same as with `postman`.

**Comment by harryi3t** [comment]
@frederikheld Are you on Wayland or x11? We have received user reports where Electron apps distributed through SNAP have problems working on Wayland.

Could you try running this command? This would temporarily disable Wayland.
DISABLE_WAYLAND=1 snap run postman

This is being tracked here https://github.com/postmanlabs/postman-app-support/issues/6252

**Comment by frederikheld** [comment]
Awesome! That was the issue! Thank you very much! Nothing but trouble with Wayland :-P So it's an Electron issue?

However, Postman is starting now :-) I got a couple of errors though. Is this of any value for you?

```sh
frederik@mycomputer:~$ DISABLE_WAYLAND=1 snap run postman
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Not disabling GPU
shm_open() failed: Permission denied
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: 1: xdg-mime: not found

Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
1584572058702 main info "Booting Postman 7.20.1, linux-5.3.0-42-generic on x64"
1584572058703 main info "EventBus~initialize - Success"
1584572058717 main info "UpdateHandler~init - Success"
1584572058720 main info "RuntimeExecutionService~initialized: Success"
1584572058723 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1584572059568 main info "Bootstrap-models~bootstrap - Success"
1584572060493 main info "window-manager~newSharedWindow: Shell loaded"
1584572065000 main info "Main~AppEvents - Received booted event for process shared"
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
1584572068186 main info "Main~AppEvents - Received booted event for process requester"
```

**Comment by Maokei** [comment]
I also had issue with postman and wayland, works DISABLE_WAYLAND=1 snap run postman

**Comment by oscar-edomex** [comment]
Same issue with me. `DISABLE_WAYLAND=1 snap run postman` did the trick. Is this something that needs to be done each time to run it forever now?

**Comment by harryi3t** [comment]
@oscarmrom Is the latest version of Postman on snap, this is done by the app itself. So, the users won't have to do this anymore 🎉

**Comment by odrade** [comment]
Same issue with the latest version of Postman on snap (download today). DISABLE_WAYLAND=1 snap run postman work.

**Comment by enkeyz** [comment]
Same issue on Ubuntu 20.04.

**Comment by calvo-jp** [comment]
Issue's still present in Ubuntu **21.04**. Running `postman --version` outputs something like this
```
The disableGPU setting is set to undefined
Not disabling GPU
(postman:140883): Gtk-WARNING **: 11:23:10.184: cannot open display: :0
```

**Comment by 0xdolan** [comment]
Same issue on **Ubuntu 21.04**. I have to use this command to open it:

DISABLE_WAYLAND=1 snap run postman

**Comment by denkasyanov** [comment]
Not sure when this is fixed again, but if you want to fix launcher in Application here is what helped me

1.  Open `/var/lib/snapd/desktop/applications/postman_postman.desktop`
2.  Add `DISABLE_WAYLAND=1` to `Exec` like that:
```
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/postman_postman.desktop DISABLE_WAYLAND=1 /snap/bin/postman
```
Also not sure if this change will persist after update

**Comment by 0xdolan** [comment]
Thank you, my friend. It works fine for me.
