### ISSUE TITLE
Does Postman send OPTIONS requests before GET or POST requests?

### ISSUE THREAD

**Issue by akelesis** [a85/POSTMan-Chrome-Extension#7853]
Hello guys!

I'm not having exactly a bug or anything like that, but I want to understand a little bit more about how postman works with get and post requests.
I'm developing a system which needs to get info from a third-party API, I have no trouble when I access the URLs with postman, but when I try to access it through my application it blocks my options request and interrupts the process. 
The thing is that I need to use custom headers to get the info I need. So I want to know if it could be a restriction in the API which doesn't allow OPTIONS requests or if it's my fault in any way.

**Comment by preethammavin** [comment]
@akelesis if works in Postman, would use our code generator to generate the request code in the language you prefer and try testing it out. 

For further support, you can open a thread in our community which is pretty active in helping and will also ensure others benefit from the responses.

**Edit:** Looks like [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is getting in your way.
