### ISSUE TITLE
Monitor page shows "Something went wrong. We were unable to retrieve monitor details. Please try again."

### ISSUE THREAD

**Issue by shivam-postman** [a85/POSTMan-Chrome-Extension#7854]
When selecting a monitor to view the details, the page shows "Something went wrong. We were unable to retrieve monitor details. Please try again."
This is happening only for older versions of postman app (before v7.0).

<img width="896" alt="Screenshot 2019-12-30 at 19 26 27" src="https://user-images.githubusercontent.com/53427068/71584789-4db49800-2b3a-11ea-97f2-d4353d168544.png">

**Comment by shivam-postman** [comment]
The monitors can be made accessible by updating the app and allowing the sync to complete. We're working on adding the support for older versions as well.

**Comment by ArjunSingh-PM** [comment]
Resolved this issue.
