### ISSUE TITLE
failed to extract installer postman app on Windows 10. Need solution

### ISSUE THREAD

**Issue by thealiraza** [a85/POSTMan-Chrome-Extension#7855]
I am installing Postman on windows 10. In earlier windows, which I reinstalled, it was working fine. But, now it is giving error : 
**failed to extract installer**
version: Postman-win64-7.14.0
I need urgent help and am unable to solve the issue. I can't find any solution on this repository or google.

![Capture](https://user-images.githubusercontent.com/37246697/71586122-dd5a4680-2b3a-11ea-8637-037f660b7701.PNG)

Thank you.

**Comment by numaanashraf** [comment]
Seems to be a duplicate of #6707

**Comment by ankurdengla** [comment]
Hey @thealiraza !

Closing this since this is a duplicate of #6707 . Please follow the original thread for updates.
Also, could you share the `SquirrelSetup.Log` file which is present at `%LOCALAPPDATA%\Postman`.
