### ISSUE TITLE
Workspace member names do not show up while editing on dashboard

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#7858]
**Describe the bug**
Editing a workspace `/workspaces/:id/edit` does not show team member names.

**To Reproduce**
1. Open dashboard (go.postman.co/workspaces?type=team)
2. Click on the `···` button
3. Click on `Manage members`
4. Observe no team member names

**Expected behavior**
Show names

**Comment by sankalp0o** [comment]
Hey @ankit-m can you provide us more info as we are unable to reproduce this. Maybe a screenshot of what you're seeing on the screen.

**Comment by sankalp0o** [comment]
Thanks for reporting this @ankit-m! This issue has been fixed. If you encounter this again, please let us know by reopening this issue.
