### ISSUE TITLE
PathVariable not support Chinese

### ISSUE THREAD

**Issue by Hansanshi** [a85/POSTMan-Chrome-Extension#7860]
The version of postman is Postman for Mac Version 7.14.0.
It will remind me with sentence like "Could not get any response There was an error connecting to "，while I can open url correctly on Firefox or Chrome, or just remove Chinese.

**Comment by preethammavin** [comment]
@Hansanshi any chance you can provide the request that you are trying to access? if not can you create a dummy request with the Chinese characters for us to test it out?

**Comment by Hansanshi** [comment]
the url for test
`http://127.0.0.1:8080/api/中文`

The error msg of postman is 
`Could not get any response
There was an error connecting to http://127.0.0.1:8080/api/%E4%B8%AD%E6%96%87.`

please note, dircetly copy this url and paste into postman, the url may be converted into `http://127.0.0.1:8080/api/%E4%B8%AD%E6%96%87`, and problem disappear.
@preethammavin

**Comment by codenirvana** [comment]
@Hansanshi This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.
