### ISSUE TITLE
Stuck in infinite loop while starting Postman app on Windows 10 Pro

### ISSUE THREAD

**Issue by apurvaj1204** [a85/POSTMan-Chrome-Extension#7861]
**Describe the bug**
The Postman application runs into infinite loop while starting it up from Windows 10 Pro. It gives a message for preparing the workspaces. Please see the attached image for your reference. 

**To Reproduce**
1. Download Postman desktop application 
2. Run the downloaded exe file.

**Actual behavior**
The postman runs into infinite loop.
**Expected behavior**
The Postman application should start successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/47164065/71660791-0f8ac480-2d44-11ea-86ba-69017cf8b149.png)

**App information (please complete the following information):**
 - App Type : Desktop App
 - Postman Version 7.14.0
 - OS: Microsoft Windows 10 Pro 

**Additional context**

**Comment by cyrielle-hada** [comment]
@apurvaj1204 We recommend clearing your local data. You can find the full instructions in [this article](https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-). 

Closing in favor of https://github.com/postmanlabs/postman-app-support/issues/7746
