### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by zarub2k** [a85/POSTMan-Chrome-Extension#7864]
https://www.getpostman.com/resources/infographics/galaxy-tour-2020/

I tried to fill some information for requesting the tour to my city. But I am getting 404 error.

**Comment by Raj-postman** [comment]
@zarub2k Thank you for bringing this to our attention. It looks like the link for the page under resources is no longer available. Can you try to fill out the information from the link below and let us know if that helps.

- https://www.getpostman.com/galaxy-tour-2020
