### ISSUE TITLE
Collection runner hanging with 5000+ iterations

### ISSUE THREAD

**Issue by oktay89** [a85/POSTMan-Chrome-Extension#7865]
**Describe the bug**
Collection runner hangs (becomes "not responding" tab). Sometimes it crashes completely the POSTMan App. 

**To Reproduce**
1. Create HTTP request with pre-request script (calculating next hexadecimal value) and test - expecting http response to be a json
2. Pre-request script reads/writes the current hexadecimal in collection variable on every iteration
3. The value is sent as parameter with the http request
4. Start collection runner and choose 5000+ iterations

**Expected behavior**
No crashes of POSTMan app and the app should be useable all the time.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.14.0
 - OS: Windows 10 64bit

**Additional context**
My PC Hardware is pretty decent - Ryzen 2600x, 16GB DDR4 Ram, NVMe SanDisk Extreme Pro. In windows task manager performance tab CPU/Memory/Disk looks good (<50%) while running the test. 
HTTP Response takes 80-100ms.

**Ideas on what could cause the problem**
1. Am I using the wrong type of storage to save the variable?
2. Is the frontend too slow with 5000+ result rows?

**Comment by jamespavett** [comment]
Myself and a colleague are currently using the native postman app to do basic POST requests with 10000s iterations. I think we are getting the same issue as above, as at around 15000 iterations the frontend becomes unresponsive and crashes.

**Comment by timbochamp** [comment]
@oktay89 @jamespavett Performance should now be much better in the latest Postman Canary application (v8.0.0-canary09), as well as in Postman for Web. Can you please try it out and confirm if it's fixed for you? I tried a couple collections with iteration counts of 5000+ and was able to get through them without crashes/unresponsiveness.

**Comment by timbochamp** [comment]
I'm going to close this out but please feel free to reopen again if you encounter the crashes/unresponsiveness with high iteration counts in our Postman Version 8.0.2 app or on Postman for Web.
