### ISSUE TITLE
Form-Data file is displayed in code section of API Documentation

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#7866]
The form-data file in the request is available in the code section of the documentation.  Ideally, the upload file should not be available there as the file that we're uploading in the request is local to our system.

**Steps to reproduce the behavior:**
1. Create a request in a collection using form-data as a body type 
2. publish the collection & you will see the file being available in the code section.

**Expected behavior**
The file should not even be available in the code section as the file that you’re uploading is local to your system.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/71717939-bb650a80-2e3f-11ea-9163-9590dd6c4ca2.png)

**Comment by Cazaimi** [comment]
@Ramya-From-Postman, as of now, we don't have a mechanism to ascertain all the parts of a request, which might be sensitive. For example, some users might choose to send an access token as a query param and might hard code that. Hence, I suggest that the user store this information as an environment variable and expose that in the request ([check this page for reference](https://learning.postman.com/docs/postman/variables-and-environments/variables/)).

As a result, the file would only be ever displayed if the user decides to:
a. View the private documentation with the environment
b. Publish the documentation with that environment

In all other cases, the variable's value would not be resolved. 

@Raja-Simha, this is not really a bug and can be marked as closed.
