### ISSUE TITLE
Not all dynamic variables are resolved

### ISSUE THREAD

**Issue by ValeriyDP** [a85/POSTMan-Chrome-Extension#7868]
**Describe the bug**
Not all dynamic variables are resolved

```
{{$randomZipCode}}
{{$randomCityPrefix}}
{{$randomCitySuffix}}
{{$randomStreetSuffix}}
{{$randomStreetPrefix}}
{{$randomSecondaryAddress}}
{{$randomCounty}}
{{$randomState}}
{{$randomStateAbbr}}
{{$randomDateBetween}}
{{$randomCurrencyAmount}}
{{$randomImage}}
{{$randomTechnicsImage}}
{{$randomNameTitle}}
{{$randomPhoneNumberFormat}}
{{$randomPhoneFormats}}
{{$randomArrayElement}}
{{$randomObjectElement}}
```

**To Reproduce**
1. Go to any request tab
2. Use any of the variables from the list above
3. See error `Uresolved Variable`

**Expected behavior**
All variables from the list above should be resolved according to this guide https://learning.getpostman.com/docs/postman/variables-and-environments/variables-list/

**App information (please complete the following information):**
 - Postman for Linux
 - Postman Version 7.14.0
 - OS: Ubuntu  18.04 linux 5.0.0-37-generic / x64

#971

**Comment by coditva** [comment]
@ValeriyDevPro The list you mentioned is outdated. We're working on updating the list. In the meantime, you can use this list as a reference: https://learning.getpostman.com/docs/postman/scripts/postman-sandbox-api-reference/#dynamic-variables

Sorry for the confusion!

Ref: https://github.com/postmanlabs/postman-docs/issues/2054
cc @arlemi @kaustavdm

**Comment by ValeriyDP** [comment]
Ok, but why in the new list there are no variables for zipCode and country?

**Comment by coditva** [comment]
We're using `faker.js` library to support our dynamic variables as of now. There were some issues with it only generation zip codes and counties for US. So, we decided to remove them for now.
That being said, we might add more dynamic variables in the future when we are able to find a good solution that works for everyone and not just US.

BTW, you can use `$randomCountry` to generate random country.

**Comment by ValeriyDP** [comment]
Thanks, for the clarification.
I know about faker.js, US specific zips and states are OK for me, that why I thought there is a bug. I believe, in documentation there would be enough to add a note that some random data is US specific and do not remove this functionality.
But anyway thanks.

Regards.

**Comment by coditva** [comment]
@ValeriyDevPro I see your point. But Postman is used everywhere in the world and keeping some variables just US specific is not the way we would like to move forward. Also, changing the behaviour of variables later would become more difficult too as people would depend on the previous behaviour. I hope you understand. :)

**Comment by ValeriyDP** [comment]
@coditva  Sorry, but I have one more question, you have said:
> But Postman is used everywhere in the world and keeping some variables just US-specific is not the way we would like to move forward.

If I will use `country: {{$randomCountry}}` and `state: {{$randomState}}` faker will take a random country, and random state, without dependency on the selected country ex. `country: France` and `state: Alabama` or, in case when it will be implemented whenever, state from any other country.

But if you'll plan to implement a random country and a random state within this country, then your decision to remove state makes sense.
Because for now, if I need a random state I'm using any random word. For me, this is no matter, because it is fake data, and for me is more important that attribute in a request is not empty, rather than state US specific or any other country-specific.

Regards

**Comment by wasyster** [comment]
I can't resolve any of Location variables. The link mentioned up, are still not resolving any data.

thnx

**Comment by arlemi** [comment]
@wasyster Where in the app are you having issues with these variables not resolving? The updated list has now been published here https://learning.postman.com/docs/postman/variables-and-environments/variables-list/

**Comment by wasyster** [comment]
values given at [here](https://learning.postman.com/docs/postman/variables-and-environments/variables-list/) are not resolved. I'm tried using it in a collection pre-request script. Always got empty for any location variable.

**Comment by MuckT** [comment]
> values given at [here](https://learning.postman.com/docs/postman/variables-and-environments/variables-list/) are not resolved. I'm tried using it in a collection pre-request script. Always got empty for any location variable.

Checkout this workaround in issue [886 - not able to use dynamic variables like {{$guid}} inside the pre-request script](https://github.com/postmanlabs/postman-app-support/issues/886#issuecomment-366734356)

**Comment by arlemi** [comment]
@wasyster ~~Dynamic variables can't be used in pre-request or tests scripts. We'll update the documentation to reflect that.~~

Edit: To use Dynamic variables in pre-request or test scripts, use `pm.variables.replaceIn()`, e.g. `pm.variables.replaceIn('{{$randomFirstName}}')`. :) 

Ref: https://learning.postman.com/docs/postman/scripts/postman-sandbox-api-reference/#pmvariables

**Comment by online** [comment]
Tell me, please, why variable `{{$randomImage}}` not resolve? The [documentation](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/) states that this should work.

**Comment by arlemi** [comment]
@online The documentation needs to be updated, both `{{randomImage}}` and `{{randomTechnicsImage}}` have been removed but this was not reflected in the docs. I have a [PR waiting](https://github.com/postmanlabs/postman-docs/pull/2754) to be merged to fix that, sorry!
