### ISSUE TITLE
Postman rapidly consuming 18GB of RAM despite not being open

### ISSUE THREAD

**Issue by aelesia** [a85/POSTMan-Chrome-Extension#7870]
**Describe the bug**
- Postman application was closed 2 days ago. (clicked the X button on Windows)
- Firefox and Webstorm suddenly crashed 3 times in a row
- Each time they crashed, screen went black for 3 seconds
- Opened Task Manager to check. Postman was rapidly consuming RAM despite not being actively open.
- Postman RAM usage went up from 15GB to 17.8GB within 20 seconds.
- Ended the process immediately.

**To Reproduce**
- Unknown

**Expected behavior**
- Postman process should have been killed 2 days ago when I closed the app.
- Postman should not be consuming 17.8GB of RAM

**Screenshots**
1) [Task Manager](https://i.imgur.com/GmfY2HS.png)
2) [App was not open when this occured](https://i.imgur.com/2alOoi2.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version [Version 7.14.0 win32 10.0.18362 / x64]
 - OS: Windows 10 Pro Version	10.0.18362 Build 18362

**Additional context**

**Comment by harryi3t** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/7870 with the difference that here the App was closed.

**Comment by aelesia** [comment]
Happened again today. 

1) Postman was closed many days ago. 
2) Screen went black and multiple apps crashed. 
3) Postman had 3 processes open, consuming 20GB+ in total.
4) Took a screenshot but the picture wasn't saved. Possibly ran out of RAM.
5) Ended all 3 processes.
6) Took a second screenshot of the aftermath. You can see CPU, RAM, Disk 0 I/O & WiFi I/O spiking to >90%.

I'm uninstalling this software due to it possibly being malware.

![image](https://user-images.githubusercontent.com/7008316/72917250-6bae9a80-3d7e-11ea-87d0-40d5f5ba40e4.png)

Below: Typical usage

![image](https://user-images.githubusercontent.com/7008316/72917481-df50a780-3d7e-11ea-983b-01e176d75018.png)

**Comment by nabham** [comment]
Facing similar issue, when the app was closed postman hogging RAM and CPU.

**Comment by joel-wenzel** [comment]
Same thing happened to me. 2 processes were running in the background consuming 100% of ram.
Postman version: v7.26.0

**Comment by mccannt** [comment]
Thanks for the information everyone. We are constantly making performance improvements to the app, so keeping up with the latest version will hopefully help with situations like this. 

We will keep everyone updated on further improvements.

**Comment by VladimirCatrici** [comment]
Whoa, just had the same issue

**Comment by Fazzani** [comment]
I noticed the same thing yesterday

**Comment by mhmacleod** [comment]
Same here. up to 5gb without signs of stopping, force-closed it, restarted and it straight popped back to 6g and climbing...and i'm not even doing anything. I can't believe the last response to 'look at this' was a full year ago and no one's been assigned to it since.

**Comment by Placeborg** [comment]
I just had the same issue. While already being closed, Postman appeared to keep running in the background while taking up more then 20gb of memory.

This happens on a machine that has an (almost) fresh windows (11) instalation.

This issue appeared after some fiddling with the 'send and download' feature on my end. After having the window for the download open for a few seconds Postman suddenly crashed. A few hours later I started looking around in my task manager to see what was causing issues, only to found Postman spiking the memory as mentioned before.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/4687
