### ISSUE TITLE
Downloads greater than 20Mb make Postman just quit

### ISSUE THREAD

**Issue by hfsrazzimonti** [a85/POSTMan-Chrome-Extension#7871]
**Describe the bug**
Calling a filedownload API method POST download the file but if file is more than about 30Mb in size, when done postman just exits. However postman is still in memory and consuming 50% CPU and memory, I have to end task.

**To Reproduce**
1. try download a large file from an API, no matter the type of file

**Expected behavior**
Either display data received or offer to save to file.

**Screenshots**
Postman just quits, disappears after done downloading the large file.

**App information (please complete the following information):**
 - App Type [calling method in API in C#]
 - Postman Version [7.14.0]
 - OS: [Windows 10 64-bit]

**Additional context**

**Comment by shamasis** [comment]
We have made significant improvement in this direction can you try the latest app and provide us with feedback. Effectively, you should be able to download and even view 50mb-ish files. Above that, it depends upon system and experience might be sluggish and hopefully not a crash for very large size even.

There is a app setting that you need to set to control the max download size.

**Comment by vikiCoder** [comment]
@hfsrazzimonti, I was able to reproduce the issue. We have identified the problem and we will be fixing this soon. Will update the thread when it is fixed.

**Comment by arlemi** [comment]
We've made performance improvements for downloading and saving large responses, update your app and let us know if it's smoother! (available from v7.22)

**Comment by ghost** [comment]
Hi, I have this problem in the newest postman version. When I'm trying to use send and download and file is >300 MB (I did not check it for smaller files)
Postman Version:
![image](https://user-images.githubusercontent.com/52471410/161347149-88c61bf1-9cf5-4e49-a172-88dfad32b2fc.png)

App Type:
[calling method in API in C#]

OS:
![image](https://user-images.githubusercontent.com/52471410/161347327-a30b3d05-f1e7-4019-b0d4-150ccd41fd9f.png)

**Comment by arlemi** [comment]
@Syjamnik Please open a new issue, this one has already been closed.
