### ISSUE TITLE
Microsoft Teams Integration Team Activity Feed posts Personal Workspace activity

### ISSUE THREAD

**Issue by davidmw** [a85/POSTMan-Chrome-Extension#7872]
**Describe the bug**
Team members working in Personal Workspaces are finding that activity is posted to Teams via this integration. This problem surfaced on or before Dec 26 2019 and wasn't previously occurring with this established connector. I've deleted and recreated the integration - same problem exists. All Personal Workspace activity is posted to the webhook.

**Expected behavior**
Only Team Workspace activity should be posted to MS Teams.

**App information (please complete the following information):**
Postman v7.14.0

**Comment by sujayvenaik** [comment]
@davidmw Can you confirm once that the activity feed for the collection/postman entities that you are getting while being in the personal workspace is not present in any team workspace?

**Comment by davidmw** [comment]
There are no integrations installed in my personal workspace and I've not shared the collection with others or the team. Every update of my personal collection is getting added to the team activity feed. So, yes.

**Comment by sujayvenaik** [comment]
Ok, we have reproduced this at our end. I'll keep this thread updated as soon as we release a fix for this.

**Comment by sankalp0o** [comment]
Hey @davidmw , the issue has been resolved now. I'm closing the issue but please let us know if this doesn't solve the problem for you!
