### ISSUE TITLE
Unable to read text for Longer Request/ Folder names

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7875]
**Is your feature request related to a problem? Please describe.**
Currently, when we have a longer Title/Folder name the text gets cut off which makes it difficult for users to read the documentation.

![text](https://user-images.githubusercontent.com/47771757/71811609-278f7a80-309b-11ea-9e8c-f127edccff79.gif)

**Describe the solution you'd like**
Be able to format the title text or scroll through the entire title.

**Describe alternatives you've considered**
To provide a shorter title name and provide the rest of the details in the description section.

**Comment by ranchanarajasekaran** [comment]
We show a tooltip for folder/request on hovering which displays the full name. 
Closing the issue .
