### ISSUE TITLE
Not able to integrate Postman PRO with Gitlab

### ISSUE THREAD

**Issue by somyata** [a85/POSTMan-Chrome-Extension#7876]
**Describe the bug**
I am trying to integrate GITLab with Postman PRO by following the instructions given on Learning site - "https://learning.getpostman.com/docs/postman-pro/integrations/gitlab/".

I went until Add integration button. It does not give me any error 

**To Reproduce**
I am trying to integrate GITLab with Postman PRO by following the instructions given on Learning site - "https://learning.getpostman.com/docs/postman-pro/integrations/gitlab/".

1. I went until Add integration button( as described in the learning center).
2.  It does not give me any error.

**Expected behavior**
The Changes in Postman app should be comitted to Gitlab. or rather my filed should by backed up in the Gitlab, as it says

**App information (please complete the following information):**
 - App Type [eNative App]
 - Postman Version [e.g. 7.14
 - OS: Windows
**Additional context**

**Comment by Raj-postman** [comment]
Hi @somyata 

If you have followed the documentation, you should be able to commit your collections on GitLab. Can you try adding a new request to your Postman collection and check if the same is committed on GitLab (This helped me when I couldn't find my integration committed)?

Also, below are my details on Integration:
- Can you try adding a Directory for you to identify the same.

![Details](https://user-images.githubusercontent.com/47771757/72495621-37525000-384d-11ea-8383-c89018d2c698.png)
- File uploaded on Gitlab Directory

![Uploaded_To_GitLab](https://user-images.githubusercontent.com/47771757/72495630-3faa8b00-384d-11ea-95b9-505b9f6d6e9c.png)

**Comment by kartikjain26** [comment]
@somyata  Also make sure if you're using custom domain gitlab integration, you're not behind an internal vpc which prevents us to push to gitlab projects.

**Comment by SabriH10** [comment]
Hi @somyata,

If it's alright with you, considering the suggestions provided above and no response I assume this has been addressed. 

If that isn't the case and you're still observing an issue don't hesitate to re-open this issue, and we'll be happy to assist further.
