### ISSUE TITLE
Content-Type header override not working when used with multipart/form-data file upload

### ISSUE THREAD

**Issue by bezugla** [a85/POSTMan-Chrome-Extension#7878]
**Describe the bug**
Content-Type header override not working when used with multipart/form-data file upload

**To Reproduce**
1. Create a POST request with file upload
2. Choose any file
3. Select header "Content-Type: blah"
4. Send request

**Expected behavior**
Postman sends a request with "Content-Type: blah"

**What I see**
Postman sends request with correct (generated) Content-Type, 
e.g. multipart/form-data; boundary=--------------------------469238036262547722247381
even though I select "Content-Type: blah" in the header grid

**App information (please complete the following information):**
 - App Type Native App for MacOS
 - Postman Version 7.14.0
 - OS: macOS Mojave 10.14.3 (18D42)

**Additional context**
Curl is able to override the headers with no problem, here is an example:

curl -H "Authorization: Bearer {TOKEN}" -X POST -F upload=@/myfile.csv -H "Content-Type: blah" https://myservice/endpoint

**Comment by appurva21** [comment]
Hi @bezugla!

We have added more control around the automatically added headers with the latest release of the App (`v7.21.0`) which will allow you to choose the exact headers that you want to send with the request.  You can override the automatically added `Content-Type` header with a valid value or even disable the auto-generated one and add your own `Content-Type` header with any value.

![image](https://user-images.githubusercontent.com/24985700/77529289-56a4d380-6eb5-11ea-9dec-a2523c2c20a2.png)

**Note**: Any value in the format `multipart/form-data; boundary={{boundary}}` is considered as a valid value for `Content-Type` header when used with `multipart/form-data` 

Refer to the documentation [here](https://learning.postman.com/docs/postman/sending-api-requests/requests/#auto-generated-headers) for more insights about Auto-generated headers.
