### ISSUE TITLE
Postman runner crashes on requests >10k

### ISSUE THREAD

**Issue by ShajilJohn** [a85/POSTMan-Chrome-Extension#7879]
**Describe the bug**
we are running postman runner for 10K iterations, but the requests fail after some 60% execution. The postman collection has some 4 requests and time delay set set to 100ms. 

[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/4029369/renderer-shared.log)

**Comment by shamasis** [comment]
closing this in favour of #7865
