### ISSUE TITLE
How to acehive test automation for login end point 

### ISSUE THREAD

**Issue by YogiReddyY** [a85/POSTMan-Chrome-Extension#7880]
Scenario : Trying to test login end point.  First time when user trying to logging in, which results login html. How do we provide the user credential and submit login form.

**Comment by prashantagarwal** [comment]
@YogiReddyY We use this repo for tracking possible bugs and new feature requests. I think this question is more apt for our [Postman community](https://community.postman.com/). I am sure our awesome developer community will help you in solving your use case.
