### ISSUE TITLE
Postman does not start in Ubuntu 19.04

### ISSUE THREAD

**Issue by Morons** [a85/POSTMan-Chrome-Extension#7881]
Installed postman with 'snap install postman'
Once installed I try and start it from the " Start Application"  screen by clicking on the Icon
no syslog entries when I start

my syslog reported! 'cat /var/log/syslog |grep postman'
`Jan  7 12:58:48 vostro snapd[1169]: api.go:952: Installing snap "postman" revision unset
Jan  7 12:58:56 vostro systemd[1]: Mounting Mount unit for postman, revision 97...
Jan  7 12:58:56 vostro systemd[1]: Mounted Mount unit for postman, revision 97.
Jan  7 12:58:57 vostro kernel: [14674.861768] audit: type=1400 audit(1578394737.662:192): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="snap-update-ns.postman" pid=21786 comm="apparmor_parser"
Jan  7 12:58:57 vostro kernel: [14674.917923] audit: type=1400 audit(1578394737.718:193): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="snap.postman.postman" pid=21787 comm="apparmor_parser"
Jan  7 12:59:12 vostro kernel: [14689.905672] audit: type=1400 audit(1578394752.706:194): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap-update-ns.postman" pid=21988 comm="apparmor_parser"
Jan  7 12:59:13 vostro kernel: [14690.202755] audit: type=1400 audit(1578394753.002:195): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="snap.postman.postman" pid=21989 comm="apparmor_parser"
`

**Comment by harryi3t** [comment]
@Morons 
1. Can you try to start the app from the terminal and let us know what logs do you see on the terminal
```
$ postman
```
2. In case you get the log `could not get the lock, quitting` there might be another instance already running in the background. Try killing it from the system monitor or from the terminal by running `pkill Postman`

**Comment by Morons** [comment]
No Nothing happens! even in the Syslog

**Comment by Morons** [comment]
I think to break it you need to upgrade from 18.10 with the GUI once is force you - reason that 18.10 is not supported anymore (its not LTS)

**Comment by rastann** [comment]
I have this error when I am trying to start Postman:

./Postman: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

I have installed that library.

**Comment by harryi3t** [comment]
@rastann Could you try installing the missing library
You can try running this command:
```bash
# You might need to use `sudo`
apt install libgtk2.0-0 
```

Or alternatively, try out the snap version of Postman
```
snap install postman
```

**Comment by michalfita** [comment]
I have the same not starting issue for snap 7.24.0 on Ubuntu 20.04. Reported on [snapcraft forum](https://forum.snapcraft.io/t/postman-7-24-0-on-ubuntu-20-04-dont-start/17601) as well.

**Comment by claspie** [comment]
Snap version of Postman doesn't start.
Been unable to use Postman since I upgrade to Ubuntu 20.04.
Removed the Postman snap app and installed it back, still the same problem.

**Comment by michalfita** [comment]
@claspie Try: `DISABLE_WAYLAND=1 snap run postman`
Works in my case.

**Comment by ghost** [comment]
2 days . unable to run postman on Fedora , going to switch to any other tool sadly .

**Comment by keithchad** [comment]
Make sure you have installed Postman and not postman agent

**Comment by JP-from-Postman** [comment]
Another report of this on Ubuntu 20.4. Output from launching via terminal below:

$ postman 
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead. 
A JavaScript error occurred in the main process 
Uncaught Exception: 
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 1 (Unknown system error 1) 
at Object.networkInterfaces (os.js:195:16) 
at getIPType (/snap/postman/128/usr/share/Postman/resources/app/node_modules/node-ipc/entities/Defaults.js:67:34) 
at new Defaults (/snap/postman/128/usr/share/Postman/resources/app/node_modules/node-ipc/entities/Defaults.js:45:21) 
at new Parser (/snap/postman/128/usr/share/Postman/resources/app/node_modules/node-ipc/entities/EventParser.js:8:14) 
at Object.<anonymous> (/snap/postman/128/usr/share/Postman/resources/app/node_modules/node-ipc/dao/client.js:15:19) 
at Module._compile (internal/modules/cjs/loader.js:880:30) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10) 
at Module.load (internal/modules/cjs/loader.js:735:32) 
at Module._load (internal/modules/cjs/loader.js:648:12) 
at Module._load (electron/js2c/asar.js:717:26) 
at Function.Module._load (electron/js2c/asar.js:717:26) 
at Module.require (internal/modules/cjs/loader.js:775:19) 
at require (internal/modules/cjs/helpers.js:68:18) 
at Object.<anonymous> (/snap/postman/128/usr/share/Postman/resources/app/node_modules/node-ipc/services/IPC.js:4:14) 
at Module._compile (internal/modules/cjs/loader.js:880:30) 
at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10) 
Gtk-Message: Failed to load module "canberra-gtk-module" 
Gtk-Message: Failed to load module "canberra-gtk-module"

**Comment by LeShino** [comment]
Hello, i have the same issue. When i launch it with terminal 
i get this message: 

LeShino@ThinkPad:~$ postman
The disableGPU setting is set to undefined
Not disabling GPU
(postman:8814): Gtk-WARNING **: 22:34:30.255: cannot open display: :0

Can someone give me a way to solve this ? Thanks.

**Comment by jviotti** [comment]
There are many different issues discussed in this thread. To summarize:

- One reason is because of the missing GTK library in the Snap, which has been fixed in recent versions of the app
- The `uv_interface_addresses` error, which is tracked in https://github.com/postmanlabs/postman-app-support/issues/10126
- Running the Snap on Wayland, which is tracked in https://github.com/postmanlabs/postman-app-support/issues/8196 and https://github.com/postmanlabs/postman-app-support/issues/9746

I'll close this ticket so that we can continue the conversation on the more specific ones!
