### ISSUE TITLE
AWS Signature is Invalid

### ISSUE THREAD

**Issue by gpmind** [a85/POSTMan-Chrome-Extension#7882]
**AWS Signature Authorization Headers are invalid**
When generating Authorization headers with AWS Signature, the signature generated is invalid and Postman doesn't even perform the request.

**To Reproduce**
1. Select the Authorization tab under a request
2. Select AWS Signature
3. Enter AccessKey and SecretKey
4. Click Preview Request
5. Click Send
6. Postman doesn't send the request and the Console shows:

> Error: Invalid character in header content ["Authorization"]

**Expected behavior**
Send the request and retrieve the response status code

**Screenshots**
![image](https://user-images.githubusercontent.com/52084603/71917041-35053d00-314d-11ea-9604-7ba385c39c34.png)

**App information (please complete the following information):**
 - Linux App
 - Postman Version [e.g. 7.13.0]
 - OS: [Ubuntu 18.04.3 LTS]

**Comment by gpmind** [comment]
There's a newline character after the AccessKey in the Credential key/pair in the Authorization header, when removing it, Postman sends the request fine, but AWS still answers with an invalid signature error.

**Comment by vikiCoder** [comment]
Hi @gpmind,

It possible that you have entered a newline character in AccessKey while entering credentials in the authorization tab. This is a common error we've seen when user copy-pasts things (AWS credentials in your case) from somewhere else. Please make sure that there are no newline/white space characters at the beginning or end of any fields of AWS auth. Let us know if the request still fails after that.

**Comment by gpmind** [comment]
> Hi @gpmind,
> 
> It possible that you have entered a newline character in AccessKey while entering credentials in the authorization tab. This is a common error we've seen when user copy-pasts things (AWS credentials in your case) from somewhere else. Please make sure that there are no newline/white space characters at the beginning or end of any fields of AWS auth. Let us know if the request still fails after that.

Yes, so? It's still a bug. Just chomp the input either when crafting the signature or when focusing out of the box. Should be a trivial fix.

**Comment by shamasis** [comment]
@gpmind ... we’ve seen substantial cases where auto magical trimming of input fields causes issue while debugging. Someone has request failing because of newline in their programme and when they run in Postman it works because we trimmed and they don’t know why. 

Instead of trimming, we are adding ways to highlight the newline and boundary white space and other “possibly” invalid characters. This would be out in canary soon. 

Subsequently, we will add UI level copy-paste handlers which will let you know that there are newlines in paste and also add a central icon on top that would upfront tell you the presence of newline character. So, it is unlikely that we will trim it automatically.

**Comment by gpmind** [comment]
Sounds good, thank you

**Comment by TheClassic** [comment]
I just encountered this issue. It was difficult to identify that a newline was inadvertently pasted into the AccessKey field. The request failed as described above. It would be good if this was field was better validated by Postman before attempting the request

**Comment by ritwijsinha** [comment]
Hey @gpmind @TheClassic 

We've introduced the feature for visualizing whitespaces and highlighting invalid characters, which would help you in debugging this super easily!

To use this, please update to Postman 7.21.0 😄

For more info, go through this: https://learning.postman.com/docs/postman/sending-api-requests/requests/#troubleshooting-your-requests

Cheers! 🎉
