### ISSUE TITLE
API Documentation doesn't support to document error codes for an API.

### ISSUE THREAD

**Issue by muhammad-shafique** [a85/POSTMan-Chrome-Extension#7885]
**Is your feature request related to a problem? Please describe.**
I need to add supported error codes that a specific API can return in response.

**Describe the solution you'd like**
There must be an option to document error codes description under Postman API documentation.

**Describe alternatives you've considered**
I couldn't find any alternative yet.

**Comment by muhammad-shafique** [comment]
Dear Raja-Simha,
Thank you for picking up this as feature.

Eagerly waiting for this feature to be used for our product documentation. :)

**Comment by muhammad-shafique** [comment]
Hi Postman Team,

Is there any chance to get this feature implemented please? Actually we need to document our product documentation if this could help us, else we need to move to any other alternative.

Would appreciate your response on this, thanks!

**Comment by godfrzero** [comment]
@muhammad-shafique Is there a reason why these error codes can't be documented using the freeform request/folder descriptions? We've seen people use markdown tables or lists to cover this use case.

**Comment by muhammad-shafique** [comment]
Can you please provide any example or screenshot? I tried but couldn't find where to document possible error code for a  particular web response.

**Comment by Raja-Simha** [comment]
Here are a couple of examples I found.
![image](https://user-images.githubusercontent.com/45988836/73970636-55522400-48d2-11ea-9ccf-ebd1d0bb8d0e.png)

![image](https://user-images.githubusercontent.com/45988836/73970702-7155c580-48d2-11ea-97d3-a77bef873514.png)

Feel free to share your thoughts around these and let us know if this helps.

**Comment by mehdinourollah** [comment]
Can you tell me how this is possible ?
I can't figure it out how to display the end-user response codes and error codes

**Comment by mehdinourollah** [comment]
> Here are a couple of examples I found. ![image](https://user-images.githubusercontent.com/45988836/73970636-55522400-48d2-11ea-9ccf-ebd1d0bb8d0e.png)
> 
> ![image](https://user-images.githubusercontent.com/45988836/73970702-7155c580-48d2-11ea-97d3-a77bef873514.png)
> 
> Feel free to share your thoughts around these and let us know if this helps.

I mean this...can you explain more?

**Comment by kamil-bednarek** [comment]
Same here. Unfortunately generator doesn't support error codes. Only error description is visible to viewer.
