### ISSUE TITLE
Is it possible to force built-in random variable values to be generated on declaration, not when referenced?

### ISSUE THREAD

**Issue by IanKemp** [a85/POSTMan-Chrome-Extension#7886]
The content I'm sending to my API looks like this:

```json
{
    "firstName": "<string>",
    "lastName": "<string>",
    "email": "{{test_loginEmail}}",
    "password": "{{test_loginPassword}}",
    "confirmPassword": "{{test_loginPassword}}"
}
```

I have setup the following pre-request script so that a random password is generated every time the API is invoked:

```js
pm.variables.set("test_loginPassword", "{{$randomPassword}}");
```

The problem is that `$randomPassword` and friends are evaluated **when referenced**, not **when declared**. The result is that `password` and `confirmPassword` end up having different values, thus the API call fails.

How can I get the desired behaviour without using a hard-coded value?

**Comment by vvs11** [comment]
@saswatds @codenirvana Could you help here?

**Comment by BryanMorgan** [comment]
You can use the `replaceIn` function to set a variable and then set your `test_loginPassword` value like this:

```
let password = pm.variables.replaceIn('{{$randomPassword}}')
pm.variables.set("password", password)
```

**Comment by pdonorio** [comment]
Thanks @BryanMorgan, 
your snippet inside the "Pre-req." works like a charm!

**Comment by coditva** [comment]
Thanks @BryanMorgan for providing the solution! Closing this issue now. :)
