### ISSUE TITLE
It is possible to copy-paste a linefeed into an HTML Header and waste 2 hours searching for the problem 

### ISSUE THREAD

**Issue by froh42** [a85/POSTMan-Chrome-Extension#7887]
**Describe the bug**
While I can't (as should) enter a linefeed into a header field I can _**copy-paste**_ it into a header field. This makes the request fail with a generic error message and enables me to waste an hour or two wondering why my request won't work when I enable the Authorization header.

**To Reproduce**
1. Create a simple get request, add an Authorization header
2. Copy-paste the "Bearer 12345abcdef...." from a text file INCLUDING the linefeed
3. Paste it into the Authorization header
4. Execute query
5. See the error message along with the (in this case also correct) hint to disable certificate verification
6. Wonder why turnig of certificate validation does not fix the request
7. Curse aloud when you notice it was the linefeed and you have seen this before and just forgot. 

**Expected behavior**
On paste into a header field strip everything past the first line, or prevent pasting in this case or sanitize trailing linefeeds. Or detect malformed requests and write something about that in the error message.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.14.0]
 - OS: [Windows 10 Fall 2019]

**Comment by shamasis** [comment]
I wish this would have happened to you next month. (Not the part of your 2 hours being wasted, but the fact that you couldn’t notice that a line feed got in the way.) 😛

Our next release of Postman Canary contains a feature where we show and highlight all invalid characters input in headers. Please do try it out and give us feedback.

**Comment by shamasis** [comment]
The latest Postman app highlights these erroneous characters.
