### ISSUE TITLE
Postman takes almost 70% of CPU 

### ISSUE THREAD

**Issue by bartholomew1** [a85/POSTMan-Chrome-Extension#7889]
**Describe the bug**
After some time postman, started taking almost 60% of my CPU. I tried reinstallation with manual delete of postman files that are left in the App data folder.
**To Reproduce**
Steps to reproduce the behaviour:
1. Open Postman

**Expected behaviour**
Postman is not taking 60% of my CPU while in idle state and does not open additional processes.

**Screenshots**
![Postman](https://user-images.githubusercontent.com/59235448/71997401-1e8ade80-323e-11ea-845f-6fe3fe3523cc.PNG)
![Potman](https://user-images.githubusercontent.com/59235448/72056090-3d37b680-32cc-11ea-8267-6d2906f14528.PNG)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.14.0
 - OS: Windows 10 Enterprise 1803 (64x)

Additional Info:
Fix from similar tickets seams to not be working in my case.

**Comment by ankurdengla** [comment]
Hey @bartholomew1 ! 
We are tracking issues related to high CPU usage in this thread - https://github.com/postmanlabs/postman-app-support/issues/7294

I'm closing this issue as a duplicate. Please follow the original thread for updates.
