### ISSUE TITLE
(Specific Collection) Change log won't load in app or browser, crashes browser tab

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7892]
**Describe the bug**
Team reports that the change log for a **specific collection** doesn't load in either in the application or browser. Loading the change log for this specific collection in the browser causes the tab to crash.

Collection in question is fairly large (130 requests).

**To Reproduce**
_(Support unable to reproduce)_
1. Open change log in app for specific collection
2. See that change log doesn't load (only shows load spinner)
3. Open change log in browser for specific collection
4. See that change log doesn't load, and tab crashes

**Expected behavior**
Change log loads successfully

**Screenshots**
![Screenshot at Jan 07 17-20-01](https://user-images.githubusercontent.com/43283131/72006738-1e222180-3205-11ea-9669-5256b4442e79.png)

**App information (please complete the following information):**
 - App Type: Native app, web dashboard (Chrome, Firefox)
 - Postman Version: 7.14.0
 - OS: macOS

**Additional context**
See internal notes

**Comment by ankit-m** [comment]
We are aware of changelog not loading in certain scenarios. The fix requires changes in data models and is tracked on our internal roadmap. Will update this issue when it is fixed.

**Comment by DannyDainton** [comment]
Hey @ankit-m 

Is this still an issue for those scenarios you know about?

**Comment by DannyDainton** [comment]
Closing this out for now but we can open it again if the issue is still occurring for users.
