### ISSUE TITLE
Request description is deleted when visibility is toggled

### ISSUE THREAD

**Issue by rsweetland** [a85/POSTMan-Chrome-Extension#7893]
If the request description is accidentally toggled while editing, changes are lost: 

![2020-01-08 16 44 33](https://user-images.githubusercontent.com/81267/72028094-32cadd80-3236-11ea-889a-6ca921ab0efb.gif)

Autosave would be nice. Simply storing the content in a temporary variable would solve the pain.

As a workaround, one can always write markdown elsewhere and copy / paste. 

Postman Version 7.14.0 (7.14.0)
macOS: 10.15.2

**Comment by lepirlouit** [comment]
also the save indicator flag is not toggled in tab

**Comment by Raja-Simha** [comment]
@rsweetland thanks for reporting this. We will fix this.

**Comment by Raja-Simha** [comment]
We've pushed out a fix for this. Closing this issue.
