### ISSUE TITLE
Unable to authorise Github application while generate Oauth token

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#7896]
Recently, I have noticed that the authorize button has been grayed out in the process of generating Oauth 2.0 token for Github application.

**Steps to reproduce the behavior:**
1. In the postman app, navigate to Authorization tab & select the type as Oauth2.0
2. Click on "_Get New Access Token_" --> Fill in all the necessary information & hit _Request token_
2. You will be prompted to sign-in to your Github account --> Upon signing in, the process gets stuck at "**Authorize application"** 

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/72065084-5b6cd900-3303-11ea-8a55-aa4e8f8214b9.png)
 

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version: 7.14.0
 - OS:  macOS High Sierra 10.14

**Comment by vikiCoder** [comment]
Hi,

We've added an option in OAuth2 that allows you to authenticate using your system's default browser while generating OAuth 2.0 token. That should solve the problem. Check out [my comment](https://github.com/postmanlabs/postman-app-support/issues/7700#issuecomment-626273229) on a [similar issue](https://github.com/postmanlabs/postman-app-support/issues/7700) for more details.
