### ISSUE TITLE
Postman App: Sign-In with Google not working

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#7897]
**Describe the bug**
**The user reported the following:**
I am Facing Sign In Issue while accessing My Postman Application, it hangs trying to sign-in with Google.
But in chrome it is displaying “you’re signed in - Just open up the postman app and you will be good to go” However it hangs trying to sign-in with Google.

**To Reproduce**
Attached the doc with the sequence of steps taken.

**Expected behavior**
Should be able to sign in successfully via the app

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.14]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Comment by lmindwarel** [comment]
I have similar issue:

When I try to sign in with google, browser open and I have 403.

**Comment by ghost** [comment]
@lmindwarel Do you happen to use VPN in browser, or are you behind some proxy, can you once verify that IP address in your browser and in app is same? You can check the IP address used in app by sending GET request to `https://postman-echo.com/ip using postman` and on browser you can search for `What is my IP`. We are tracking similar issue here https://github.com/postmanlabs/postman-app-support/issues/7839, you can take a look at it for more information.

**Comment by lmindwarel** [comment]
I do not use VPN, nor proxy. I have this issues on 2 differents computer, on different network.
I have checked, same IP on postman and browser.
Thanks for your help

**Comment by ghost** [comment]
@lmindwarel Can you tell us the error message that you are getting, are you able to reproduce it?

**Comment by lmindwarel** [comment]
![image](https://user-images.githubusercontent.com/34281254/72253693-6b860080-3602-11ea-93e7-2ae726667386.png)
Here is the link opened in browser: https://identity.getpostman.com/client-auth/start?auth_challenge=0ed5c884bca3292c85bf011bd4a1e3ca468293b44fed30a6534f127a2af4321a&auth_device=app_native

I've fresh install of Postman. When clicking on "sign in via google", the first opened link work, but the issues will happen when you reach the second page and click "open in browser" (see screen)

**Comment by ghost** [comment]
@lmindwarel Were you able to login when the link opened for the first time? Did you see the success page in your web browser?

**Comment by lmindwarel** [comment]
Yes it was working on my laptop with the home page link
But I tried again on my other computer and it does not work from the link on the home page, nor from the second link "open your browser"...
Maybe because my google account was already used on my other computer ?

**Comment by diwakar-s-maurya** [comment]
I am also facing the same problem - 403. I am using "Postman for Linux - Version 7.15.0 - linux 5.0.0-38-generic / x64"

**Comment by ghost** [comment]
@lmindwarel As you said that it is not working on the other computer, on that computer have you tried to check the IP on both app and browser, if it works in one of your PC and not other one, other one may have some proxy extension installed in web browser, which is causing this issue.

**Comment by ghost** [comment]
@diwakar-s-maurya Have you installed any proxy/VPN extension in browser? You can follow the steps listed below and check if you have same IP on app and browser.

> @lmindwarel Do you happen to use VPN in browser, or are you behind some proxy, can you once verify that IP address in your browser and in app is same? You can check the IP address used in app by sending GET request to `https://postman-echo.com/ip using postman` and on browser you can search for `What is my IP`. We are tracking similar issue here #7839, you can take a look at it for more information.

**Comment by lmindwarel** [comment]
This issues was the same as #7851 . I'm on KDE too.
I follow the steps you give (reset pass etc.) and it's working.
But so strange because sign in with google work 1/2 month ago.
Thanks for your help

**Comment by diwakar-s-maurya** [comment]
@meetSuraj Yes, I am also using KDE (Plasma v5.15.4). I followed the of reset password and it's working now.

**Comment by preethammavin** [comment]
Closing the issue for now, as we have deployed stability fixes for the same. Please do let us know if the issue continues to persist.

**Comment by majidakbari** [comment]
The new postman is a complete mess

**Comment by ghost** [comment]
@majidakbari  I'm sorry to hear you had such a frustrating experience, can you elaborate what exact issue are you facing?

**Comment by majidakbari** [comment]
@meetSuraj 
I've created a collection locally and for couple of times I tried to publish the docs; It doesn't work and shows an error as follows:
The request has the following fields missing or wrongly provided: collectionId.
Also this is not the only issue...

**Comment by ghost** [comment]
@majidakbari Sorry for the inconvenience you faced, but I really appreciate you bringing this issue to my attention. Can you file separate issue for this with all the relevant details, we will look into it as soon as possible.

**Comment by jcesarprog** [comment]
can't sign in postman on ubuntu LTS with the snap installation

**Comment by sqhqk58** [comment]
Your computer's IP address changed while signing in. Make sure your IP address is stable and try again.
This make me want to use another app. Please fix it when sign-in by Google.!!!
