### ISSUE TITLE
Error when importing a valid OpenAPI 3.0 API file

### ISSUE THREAD

**Issue by wooger** [a85/POSTMan-Chrome-Extension#7898]
**Describe the bug**
Importing valid OpenAPI 3.0 / swagger files into postman fails with the error "Error while importing OpenAPI 3.0: 
Could not import."

**To Reproduce**
1. Go to https://app.swaggerhub.com/apis/Delta-FS/Members/0.1 and export the API in JSON or yaml format
2. Switch to Postman, click on the 'import' button and then the 'choose files' button
3. Select the downloaded (json or yaml) file - it may be inside a zip.
4. Click the 'Next' button
4. See error popup in Postman "Error while importing OpenAPI 3.0: 
Could not import."

**Expected behavior**
The OpenAPI is imported as a collection.

**Screenshots**
![image](https://user-images.githubusercontent.com/361154/72083092-25c2f280-32f9-11ea-87fa-7eaac816cfc7.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.1.5
 - OS: Windows 10

**Additional context**
There is nothing logged in the postman console.
The same issue exists with the Canary build of Postman.
The commandline tool openapi-to-postmanv2 also fails to convert these files.

**Comment by umeshp7** [comment]
@wooger Could you please try this again in the latest version of the App and let us know if you are still facing this issue?

I tried with the schema you have given and I am able to import it on the latest version of the App.

**Comment by umeshp7** [comment]
@wooger Closing this for now. 

Feel free to reopen if you are still facing the problem.

**Comment by devbright** [comment]
![image](https://user-images.githubusercontent.com/2283039/206119162-f0dd851c-6c92-46a4-977e-a2f1f161a84f.png)

Adding "version" in the "info" node may help you.
