### ISSUE TITLE
I cannot see how many tests are failing until the end of the iteration

### ISSUE THREAD

**Issue by bothyculture** [a85/POSTMan-Chrome-Extension#7899]
When running a large test collection in the Collection Runner I cannot see whether the tests are passing unless I scroll downwards continuously as the tests are running. 

I would prefer it if I could see some feedback on how many were passing. If a large number start to fail then I can cancel the run.

It would be better if the green and red circles were visible and updated all the time during the run.

![image](https://user-images.githubusercontent.com/16387629/72153130-e6ea7680-33a4-11ea-9487-dde3dc336245.png)

![image](https://user-images.githubusercontent.com/16387629/72153145-f8338300-33a4-11ea-9670-6afe617d40ea.png)

**Comment by giridharvc7** [comment]
This is now fixed in v8.0 . Please check and let us know what you think!
