### ISSUE TITLE
Show array's length number

### ISSUE THREAD

**Issue by hupo376787** [a85/POSTMan-Chrome-Extension#7900]
Hi, when the response data contains arrays, how to know the array's length quickly?
![image](https://user-images.githubusercontent.com/14960168/72202036-c5b58300-3495-11ea-99f7-8722d98d94a0.png)

Currently we have to check and count, this is annoying.

Can you guys show a number at the array root like below?

![image](https://user-images.githubusercontent.com/14960168/72202072-280e8380-3496-11ea-92af-3489916736cf.png)

If does, that will be great.

**Comment by kamalaknn** [comment]
Duplicate of #5923
