### ISSUE TITLE
postman login wrong.tips: something the wrong.

### ISSUE THREAD

**Issue by ihao56** [a85/POSTMan-Chrome-Extension#7903]
**Describe the bug**

**To Reproduce**
1. Go to 'open postman'
2. Click on 'sign in'
3. tips 'something went wrong'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by Gunjan4542** [comment]
@lailuohao Could you check after sometime, a planned maintenance is going on. [Check here](https://status.getpostman.com/?_ga=2.163915391.1140212892.1578811273-1445113031.1573631831)
