### ISSUE TITLE
Postman showing 200 status code instead of 302

### ISSUE THREAD

**Issue by mattshenton** [a85/POSTMan-Chrome-Extension#7905]
I am using Postman to test my ruby on rails app locally.  The route I am calling responds with a redirect link.  I understand that when *automatically follow redirects* is set to on in settings, it should automatically open the link in your default browser.  However, Postman is saying that the status code is 200, so it is not redirecting anywhere.  When I make the same request with cURL, it correctly tells me that the status code is 302 found.  Is there something I need to change within my Postman settings or somewhere else in the app such that it correctly recognizes the 302 response status code?

**Comment by Rob-DeRosia** [comment]
If your goal is to stop at the redirect status code, uncheck the **Automatically follow redirects** setting.

**Comment by ankit-m** [comment]
Like @AisoRed said, you can find the settings by clicking on the wrench icon in the top bar. Feel free to re-open this issue if you need more help.
