### ISSUE TITLE
Show fork name in runner

### ISSUE THREAD

**Issue by Ebtoulson** [a85/POSTMan-Chrome-Extension#7906]
**Is your feature request related to a problem? Please describe.**
After forking a collection and making changes, I'm unable to see which collection is the original and which is the fork in the runner.

**Describe the solution you'd like**
Please include the fork name beside the collection name in the runner.

**Describe alternatives you've considered**
None. Running both may not always work in every situation and order is a poor indicator. 

**Additional context**

<img width="501" alt="Screen Shot 2020-01-13 at 3 15 48 PM" src="https://user-images.githubusercontent.com/1562555/72288743-b8280680-3617-11ea-93bb-7bfaf76e26de.png">

**Comment by saswatds** [comment]
@Ebtoulson  We have fixed this issue on our latest version 7.18.0. Can you update to the latest version and verify this issue is fixed for you?

**Comment by Ebtoulson** [comment]
I see the fork name now. Thanks!
