### ISSUE TITLE
Postman shows different application with the browser application

### ISSUE THREAD

**Issue by raypanjaitan** [a85/POSTMan-Chrome-Extension#7908]
**Describe the bug**
I have multiple projects. Using XAMPP and customized domain.
For instance I have 2 laravel projects, A and B. Whenever I try to open the application using A's domain name from my browser it shows application A, but when I access the domain from postman it shows application B.

**Expected behavior**
It shows application A from the postman

**Additional context**
I am using laravel, xampp, Chrome as the browser

**Comment by sankalp0o** [comment]
Hey @raylucker! Were you able to debug this? If you try to access this domain through cURL, are you able to reproduce this? Do let us know some more details (maybe the domain itself) or reach out to the Postman Community https://community.postman.com/ in case someone has run into the same problem as this.

**Comment by SabriH10** [comment]
Hi @raylucker,

If that's alright with you, I'll close this as we haven't received a response to the last message. If you're still observing a problem, feel free to either re-open this issue or leverage the Postman Community as suggested.
