### ISSUE TITLE
Environment Variables dialogue should be draggable

### ISSUE THREAD

**Issue by levensailor** [a85/POSTMan-Chrome-Extension#7909]
When creating an environment to add variables, I have to write down the variable names used in the collection, ie: {access_token}, {mytoken}, {usertoken} {access-token} so I reference the names when adding environment variables.

Ideally the window in the foreground would be draggable so that I can drag it out of the way and see the name of the variable i the tab loaded in the background

**Comment by giridharvc7** [comment]
Environment is now available as a separate tab, this should be fixing your problem
Apart from this, you can now select a part of your request and `Set as Variable` , this helps you create new Environment and global variables without switching context.
Let us know what you think of these changes! @levensailor
<img width="1061" alt="Screenshot 2021-04-14 at 1 33 15 PM" src="https://user-images.githubusercontent.com/1040583/114675871-5bd5fa00-9d26-11eb-9b73-c1d8a90b38df.png">
<img width="1057" alt="Screenshot 2021-04-14 at 1 33 51 PM" src="https://user-images.githubusercontent.com/1040583/114675883-5e385400-9d26-11eb-8782-6db652d8d070.png">
