### ISSUE TITLE
Glitch character appears when write hangeul character in "Collections>Request Descriptions"

### ISSUE THREAD

**Issue by seongwon-kang** [a85/POSTMan-Chrome-Extension#7910]
Glitch character appears when write hangeul character in "Collections>Request Descriptions"

**To Reproduce**
1. Go to "Collections"
2. Make a Collection and a Request
3. Click on 'Edit Request Description'
4. Write random Hangeul(가-힣, U+AC00-U+D7AF) with keyboard layout "Hangeul Keyboard(101 Key) Type 1"
5. some unexpected character appears (but disappears when cursor lose focus)

**Expected behavior**

**Screenshots**
![bug2](https://user-images.githubusercontent.com/56567660/72327290-19bda300-36f4-11ea-9ed2-4358779f100a.gif)

**App information (please complete the following information):**
 - App Type : Postman for Windows
 - Postman Version 7.15.0, win32 10.0.18362 / x64
 - OS: Windows 10

**Comment by shamasis** [comment]
Seems like this is a common issue across all input fields with different fields having different behaviour! Try inputting this emoji 👨‍👩‍👦 and hitting backspace to delete it. It will be interesting!

**Comment by pankajk07** [comment]
Fixed as part of v7.24
