### ISSUE TITLE
Add warning message while deleting collection of larger sizes

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7911]
**Is your feature request related to a problem?**
Currently, when a collection is deleted - the deleted collection is not found on the trash and hence cannot be recovered. This is as per the designed workflow, where the collections of size 30Mb and above are not provided an option to be recovered.

**Describe the solution you'd like**
Add a warning message while deleting the collection something like: "Deleting this collection will permanently remove it from your workspace and the same cannot be recovered as the size of the collection exceeds 30 Mb"

![Example](https://user-images.githubusercontent.com/47771757/72328708-6d6ec300-36d9-11ea-881d-f2c71998b1a5.png)

**Describe alternatives you've considered**
Splitting the collection into the smaller collection, to be able to recover the same in event of deletion

**Additional context**
It would be helpful if we get an option to check the collection size. An Option such as "Details" field.

_[Filed by Postman]_

**Comment by ankit-m** [comment]
We now show a warning when a collection cannot be recovered from trash.
