### ISSUE TITLE
UX suggestion while updating user roles

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#7915]
Team Management UX suggestion

When I update a user's role within my team, I don't see that I need to save my choices (or take any additional action). The notification to do this is at the top and out of view. 

<img width="1533" alt="Screen Shot 2020-01-14 at 4 11 08 PM" src="https://user-images.githubusercontent.com/17693714/72395186-871a0580-36ed-11ea-8afe-378a6e2fe505.png">

I would need to scroll up to see this notification and Save button. If I don't scroll up, I am unaware that my updates will not be persisted.

<img width="1533" alt="Screen Shot 2020-01-14 at 4 11 11 PM" src="https://user-images.githubusercontent.com/17693714/72395182-841f1500-36ed-11ea-858c-84e4c056949b.png">

**Comment by ArjunSingh-PM** [comment]
The UI for managing members and groups has been revamped and this issue has been resolved.
