### ISSUE TITLE
Add a tab to manage all effective variables for a request

### ISSUE THREAD

**Issue by rburnham52** [a85/POSTMan-Chrome-Extension#7916]
**Is your feature request related to a problem? Please describe.**
While developing an API it is useful to setup postman for manual testing. parameters such as ID's can change depending on what you want to test. 

It makes sense to set ID's up as variables but currently it is a bit painful to see and override what the values are for your current request

**Describe the solution you'd like**
Add a UI similar to the Headers Table that clearly lists all your environment variables names/values. These should be populated to show what variables are in effect and pre-populate the value.

For example you might have a `{{port}} : 3000` variable  set for the default at the global level but it is overridden ad the Collection level to `{{port}} : 5000`. This tab should display 5000 as the value. 

In addition to this you should be able to override the value for the current session. This is very useful for local variables like ID's that often change during testing. 

Session level overrides can be local only and potentially not persisted so when you close the session they are reset or at least just stored locally. 

- Bonus feature would be to group the variables based on the level they are defined (eg Global/Collection/Local)

**Describe alternatives you've considered**
Provide an easy way to override variables for you current session.

**Comment by skatikia** [comment]
@rburnham52  Sorry for the delayed reply, but I have good news!!!

With Postman **V11.14**, we have introduced **a way for you to view all your variables in one place**.

Click on the button next to the environment switcher to bring up the variables pane. This pane bubbles up the variables used in the request and also shows variables that are accessible from different scopes (collections, environments and globals).

![variables-pane](https://github.com/user-attachments/assets/28443513-2c48-4065-82fa-48c7cb02bb63)

I hope you like this change as much as we do! Update your app to start working with this change and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
