### ISSUE TITLE
Remapped control keys (paste, undo, redo) does not work in Mac using Windows Keyboard

### ISSUE THREAD

**Issue by serendipity30** [a85/POSTMan-Chrome-Extension#7917]
Remapped keys in Mac does not work when using Windows keyboard in Postman. 

**To Reproduce**
1. Go to System Preferences... / Keyboard / Shortcuts...
2. Add separate shortcuts for Cut, Copy, Paste, Undo, Redo & use keyboard keys Ctrl+X, Ctrl+C, Ctrl+V, Ctrl-Z, Ctrl-Y respectively to map them. Ensure that mapping is applicable for all applications. No changes are done in Modifier Keys section.
3. Copy any text from outside of Postman such as Atom text editor.
4. Attempt to paste into, say, body within postman using keyboard (Ctrl+V).
5. Nothing happens although Edit menu blinks.
6. Try to use Ctrl+Z or Ctrl+Y & no effect except just menu blinks.
7. Ctrl+V works only in Header area and URL text bar but then Undo (Ctrl+Z) or Redo (Ctrl+Y) does not work in there.

**Expected behavior**
I should be able to use Cut, Copy, Paste, Undo, Redo using keyboard keys Ctrl+X, Ctrl+C, Ctrl+V, Ctrl-Z, Ctrl-Y.  

**App information (please complete the following information):**
 - App Type: Postman App
 - Postman Version: 7.14.0
 - OS: [macOS Mojave 10.14.6]

**Comment by twitharshil** [comment]
Hey @serendipity30 

The issue seems to be fixed in the latest versions of the postman application. Closing this ticket, feel free to reopen if you face the issue again

**Comment by serendipity30** [comment]
@twitharshil This issue still exists. Please re-open this defect.

**Comment by Aminmalek** [comment]
I have the issue with Ctrl-Y in Ubuntu 22.04 snap version
