### ISSUE TITLE
Support Sorting Environments

### ISSUE THREAD

**Issue by neillindberg** [a85/POSTMan-Chrome-Extension#7919]
**Problem**
I'm always frustrated when my QA team member points hands me a big wad of collection and environment and I need to go change some environment value, but the keys aren't sorted in the editor pane. I find myself scrolling through gigantic lists of unsorted added-as-needed environment values. Here is a snippet of what I'm talking about:
![image](https://user-images.githubusercontent.com/1066286/72442527-4fa16c80-3772-11ea-996d-af0b5e1b9a4e.png)

**Solution**
I want some sort of ease-of-sorting. Whether that is a sorting button when in the edit pane:
![image](https://user-images.githubusercontent.com/1066286/72442632-79f32a00-3772-11ea-8531-f0b1cd538af8.png)
-or-
If, upon EXPORT there are options to sort (and possibly drop null values, but that is another thing).

**Describe alternatives you've considered**
As a fullstack guy I made my own tool, but it would be really nice if my strictly QA team member could hand me sorted environments (and I'm certain it would speed things up for him too).

Here's my own tool (might help somebody dealing with the same issue). It will read and write a PM Environment in-place. Run with:
`node sorter.js -- ../relative_path/to_file.json`

```
const fs = require('fs');
const path = require('path');
//
const fileName = process.argv.slice(2).pop();
if (!fileName) {
    console.log('File name expected.');
    process.exit(1);
}
const filePath = path.join(__dirname, fileName);
console.log('Loading PostMan Environment: ', filePath);
const pmEnvironment = JSON.parse(fs.readFileSync(filePath))
//
const sortByKey = (a, b) => (a.key < b.key) ? -1 : (a.key > b.key) ? 1 : 0;
// values: [{key, value, enabled}]
const sortedValues = pmEnvironment.values.filter(value => (value.value) ? true : false).sort(sortByKey);
//
pmEnvironment.values = sortedValues;
// console.log(pmEnvironment);
fs.writeFile(filePath, JSON.stringify(pmEnvironment, null, 4), (err) => {
    if (err) console.log('Sort PM Environment ERROR: ', err);
    console.log('Operation finished.');
});
```

**Comment by giridharvc7** [comment]
Hello folks, we have released sorting & filtering on variables in our latest update to Postman (10.12) - the update is being rolled out, you will get it in the next couple of days if you haven't already.

You can read about the latest updates we have on variables and its management [here](https://blog.postman.com/faster-and-easier-variable-management-in-postman/). We hope you like these updates. Thank you for your patience and your feedback, we really appreciate it. 

![Sort](https://user-images.githubusercontent.com/1040583/225613544-6b3754c2-7550-41f5-b00e-57c287ded079.gif)
