### ISSUE TITLE
Google login with a 2nd account does not work

### ISSUE THREAD

**Issue by johanlunds** [a85/POSTMan-Chrome-Extension#7920]
**Describe the bug**

I have 2 Postman accounts (1 work, 1 personal). Both have Google/Gmail addresses. Using "Login with Gooogle" I can only login with my personal Gmail address. I never get an option to login with my work Google email.

**To Reproduce**

1. Create 2 Postman accounts, both created using "Login with Google" and 2 different Google accounts
1. Log out
2. Click "Login with Google"
3. Some redirects happen
5. I am logged in using my personal email and personal Postman account

**Expected behavior**

Currently it automatically picks the personal email, I never get an option to pick my work email to authenticate with.

Even if I later click "Add account" in the Postman account dropdown, and click my work email, some redirects happen and it still just logs me in to my personal account.

**Screenshots**

None.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.14.0
 - OS: Mac

**Additional context**

I found a workaround luckily. Reset password for my work Google/Postman account. Now logging in with password instead.

**Comment by ghost** [comment]
@johanlunds Are you logged in with both personal and work account in google? If you have only logged in your personal account in google, then when our application ask google to authenticate you, google automatically uses the account logged in and not provide option to login with different account, but if you have multiple google account logged in, then it takes to account chooser page.

**Comment by johanlunds** [comment]
That worked. I had been logged out of my 2nd Google account. Sorry about that. Closing.
