### ISSUE TITLE
Docs: inserting a sample request/example in different parts of documentation

### ISSUE THREAD

**Issue by OlgaUtochka** [a85/POSTMan-Chrome-Extension#7924]
**Is your feature request related to a problem? Please describe.**
We find sample requests and responses generated by Postman very convenient. However, all the requests are given only in the end of documentation.

**Describe the solution you'd like**
It would be useful to have an option to place a direct link to a request or the request itself in the "text part" of documentation.

**Describe alternatives you've considered**
Currently, I write something like "see a sample request and response in the end of this documentation", which is not very useful.

**Comment by Raja-Simha** [comment]
@OlgaUtochka Could you explain what you mean by end of documentation? Do you have a really long collection description? You could also share your documentation if it has been published.

**Comment by OlgaUtochka** [comment]
@Raja-Simha 

Here's our documentation: [3DiVi Face Machine Cloud API ](https://docs.facemachine.3divi.com/?version=3002fe83-8c78-4dda-8bc4-09658ad0256d#filtering).

As you can see, our description is quite long, and there are many sections. Here's a part of a GraphQL sample in the section "Filtering", and it would be very convenient to insert an "interactive" sample in this very section (we have this sample in the folder "Events" > "Filter events"). 

By "the end of this documentation" I mean the folders with sample requests and responses. I guess, it's impossible to insert a link to this or that request in a text part ("description") of the docs at the moment.

**Comment by Raja-Simha** [comment]
Here is the link to the section you are referring to in the folder "Events" > "Filter events"- https://docs.facemachine.3divi.com/?version=3002fe83-8c78-4dda-8bc4-09658ad0256d#e2ee688a-d839-4728-9b65-b86ebea42d38

We add tags to every description section, folder and request of the documentation which can be referred to directly or shared across. You could also use markdown to add a URL to text like - [here](https://docs.facemachine.3divi.com/?version=3002fe83-8c78-4dda-8bc4-09658ad0256d#e2ee688a-d839-4728-9b65-b86ebea42d38) Just click on a particular section and copy the URL to get the associated tag. 

Let me know if this is what you are looking for.

**Comment by Raja-Simha** [comment]
@OlgaUtochka I am assuming you understood how to link to different sections within postman documentation. Closing this issue. Do re-open if you are still blocked on this.
