### ISSUE TITLE
Issue with Postman Installation

### ISSUE THREAD

**Issue by gbweber** [a85/POSTMan-Chrome-Extension#7933]
When installing the application, it appears a message saying that I have used another version of Postman and that i need to download the latest version. Well, there is only version to download for window 32 bits.

**Comment by numaanashraf** [comment]
Hi @gbweber, could you try downloading the latest version again from our website? We just noticed that the download link on website was serving the previous version and we have resolved this issue.

**Comment by gbweber** [comment]
Hi
I still have the issue. I downloaded the latest version, but was not able to install it. Now the message says: "Not able to open Postman".  Please find below the attached file.
    El lunes, 20 de enero de 2020 02:31:08 GMT-3, Numaan Ashraf <notifications@github.com> escribió:  
 
 
Hi @gbweber, could you try downloading the latest version again from our website? We just noticed that the download link on website was serving the previous version and we have resolved this issue.

**Comment by gbweber** [comment]
Yes, that part was fixed, now I am able to download the latest version, but the app doesn't open when it is installed. There is a black square (the app trying to open) and after several seconds, the message box appears saying: "Not able to open Postman".

**Comment by seongwon-kang** [comment]
Install [Everything](https://www.voidtools.com/en-us/), search "Postman" and delete all related folder and retry install
