### ISSUE TITLE
Placement of welcome screen is off for dual monitor laptop.

### ISSUE THREAD

**Issue by DragonMeme** [a85/POSTMan-Chrome-Extension#7935]
**Describe the bug**
A technical bug that renders placement of the starting window that is placed half cut on to the combination of the two screens. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a second screen display via HDMI cable.
2. Start Postman.
3. The starting screen will be shown half on Screen 0 and the other half on screen 1.

**Expected behaviour**
The starting screen should be placed in the middle of Screen 0 (primary screen) only.

**Screenshots**
Circled orange is the placement of the application starting up on dual screen.
![Actual Behaviour](https://user-images.githubusercontent.com/48312022/72697730-d3f65400-3ba5-11ea-87ad-46f6b7351584.png)

**App information:**
 - Postman Version: 7.16.0
 - OS: Ubuntu 18.04.3

**Comment by ankurdengla** [comment]
We are tracking this issue here - https://github.com/postmanlabs/postman-app-support/issues/7251

**Comment by ankurdengla** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/7251

**Comment by twitharshil** [comment]
Hi @DragonMeme 
Could you try out our early access Canary build? https://www.postman.com/downloads/canary/. We are testing some improvements that should address this particular issue. You can install and use the Canary build side by side with the stable app.
