### ISSUE TITLE
PostmanConsole - copy of "SelectAll" does only copy the part visible in the Console, not the entire "selectAll" part

### ISSUE THREAD

**Issue by clembones** [a85/POSTMan-Chrome-Extension#7936]
**Describe the bug**
in postman console, run a Collection with lots of output - 
wanting to copy/paste ALL of it, I do - SELECT ALL, 
and copy it - pasting it elsewhere, it only did paste the "visible" part in the Console, whilst SELECT ALL, did correctly select all the Console output, 
thx

**Comment by ritwijsinha** [comment]
Duplicate of #7685
