### ISSUE TITLE
Collection runner seems not to recognise text file anymore

### ISSUE THREAD

**Issue by crendsist** [a85/POSTMan-Chrome-Extension#7937]
**Describe the bug**
After update to version 7.16 in the collection runner we could not upload anymore the very same csv text file (type 'Text Document'), we get "Could not determine format of data file".

**To Reproduce**
1. Select a request from a collection in order to open the collection runner
2. Click on 'Select file' and upload the text file
3. Select 'Data File Type' text/csv
4. Click on 'Preview'

**Expected behavior**
See the correct preview of the file

**Screenshots**
![image](https://user-images.githubusercontent.com/47521409/72714859-bdcda100-3b6f-11ea-9111-d8f6c88f97f3.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version:  7.16.0
 - OS: Windows

**Comment by ritwijsinha** [comment]
Hey @crendsist 

We're able to reproduce this on our end, and are fixing this ASAP.

Meanwhile, just rename your data file from `.txt` to `.csv` to continue working with your data.

Cheers!

**Comment by clayt666** [comment]
I am not having a problem getting the file recognized (I am using .csv), but the data isn't coming in. I have double and triple checked that the parameter name matches, but the url always contains "{{variableValue}}" rather than the value out of the file.

**Comment by saswatds** [comment]
@crendsist We have fixed this issue on our latest version `7.18.0`. Can you update to the latest version and verify this issue is fixed for you?

**Comment by clayt666** [comment]
With version `7.18.0` I no longer see my issue.

**Comment by saswatds** [comment]
Thanks for verifying. Closing this issue now as resolved.
