### ISSUE TITLE
Discrepancy in Monitor Usage information

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#7938]
**The user reported the following:**

**Describe the bug**
There is a Discrepancy in  Monitor Usage under Usage Overview page. Monitor usage shows a different number than Monitoring usage details (Once you click on Monitoring usage)

**To Reproduce**
1. Go to Usage Resource usage 
2. Click on View Detailed Monitoring Usage 
3. Next page (Monitoring Usage Details) shows different data

**Expected behavior**
The number should be the same in both the pages 

**Screenshots**
![1](https://user-images.githubusercontent.com/41741228/72720634-67c52180-3ba0-11ea-8bc4-b330610fd721.png)
![2](https://user-images.githubusercontent.com/41741228/72720636-685db800-3ba0-11ea-9443-bc4045081fa4.png)

**Comment by shivam-postman** [comment]
In the details page, we have an option to select the timeframe. Is the time period same on overview and details page?

**Comment by ash007-postman** [comment]
@shivam-postman Yes, the time frame is the same for both the pages.

**Comment by LeoZandvliet** [comment]
I also encounter this issue and we are using more than our subscription at the time of writing :( During several hours I 'monitored' the numbers on both pages, and they add up correctly.
When calculating with some rough daily usage numbers, could it be the resource usage just didn't reset at the start of the last period (in my case that would be 13 feb.)?

**Comment by shivam-postman** [comment]
@LeoZandvliet @ash007-postman, can you try checking the usage now? It should be displaying the same value at both the places.

**Comment by LeoZandvliet** [comment]
Thanks for the fast solving!
I refreshed the totals and details page within the same second, and the totals are at 26210 and the details show 26234. I guess that will be due some sort of caching mechanism of the totals count on your side, this is acceptable for us. 
Am I right about the slight difference?

**Comment by shivam-postman** [comment]
Yes, the slight difference would be gone in sometime.

**Comment by ArjunSingh-PM** [comment]
This issue is resolved.
