### ISSUE TITLE
Collection Run details is not showing variable resolved URL instead shows the variable name

### ISSUE THREAD

**Issue by gaberlungi** [a85/POSTMan-Chrome-Extension#7940]
**Describe the bug**
After updating to v7.16.0 there is some missing info in the detail popup of the link of every requests in the collection runner, specially:

- "Response body was not logged" in Response Body
- Request URL shows variable name instead of value (example: {{URL}})

This information was previously there

**To Reproduce**
1. Go to the Collection Runner
2. Run any collection (specially one that uses variables in the request URL)
3. Click on one of the request detail links
4. Open Request URL and Response Body details

**Expected behavior**
Actual value of Request URL and Response Body is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/26352139/72727195-9fc16a00-3b8a-11ea-8f1d-547032ac77ff.png)

**App information (please complete the following information):**
- App Type: Native App
- Postman Version: 7.16.0
- OS: Windows

**Comment by arlemi** [comment]
Showing variable names instead of values was also reported by a user on Discourse: 
https://community.getpostman.com/t/environment-variables-are-not-displayed-at-collection-runner-after-update-postman-to-version-7-16/10209

**Comment by AnaGoulart23** [comment]
I have the same problem

**Comment by panasuri** [comment]
Same problem here

**Comment by saswatds** [comment]
Hi, the response logging is now controlled behind setting when you start a run, turning it on will show the headers and body details. 
![Screenshot 2020-01-21 at 11 38 15 AM](https://user-images.githubusercontent.com/8796447/72779677-c0e59180-3c42-11ea-9740-71368cbe01aa.png)

Meanwhile, we will get the URL not resolving issues fixed.

Alternatively, you can use the `Postman Console` to see more details about all the requests during the collection run. Shortcut to open console `Options+Command+C`(Mac) or `Alt+Ctrl+C`(Win).

**Comment by gaberlungi** [comment]
Thank you.

**Comment by stcalica** [comment]
reported by user. 
blocking their release pipeline.

**Comment by dwaite498** [comment]
I am having the same issue and I have a growing list of API runs that need to happen. Is there any idea as to when this issue will be resolved?

**Comment by appurva21** [comment]
Hey!!
We have fixed the issue from our end and should be out with the next release of the app.

**Comment by AnaGoulart23** [comment]
have a die to launch an update? @appurva21

**Comment by appurva21** [comment]
Hi @AnaGoulart23,
The fix is available in latest version of the postman app.
You can update your app or can download the latest version from here: https://www.getpostman.com/downloads/

**Comment by saswatds** [comment]
Closing this issue for now as we have internally verified that this is fixed. If the issue still persists for you then feel free to reopen this issue.

**Comment by AnaGoulart23** [comment]
I saw that in some cases the error message: "Response body was not logged"  persist

**Comment by arlemi** [comment]
@AnaGoulart23 Are you still seeing this? If so could you provide more details on the cases where this happens?

**Comment by bpb-aws-book** [comment]
https://github.com/postmanlabs/postman-mcp-server/issues/130
