### ISSUE TITLE
Run Result Export in Version 7.16

### ISSUE THREAD

**Issue by hbertsch** [a85/POSTMan-Chrome-Extension#7941]
**Describe the bug**
Since version 7.16 in the run report the runtime of each request is not listed seperatly any longer for each run. Before i had a list in there that looked something like:

`"times": [
				"313",
				"200",
				"221",
				"215",
				"354",
				"274",
				"210",
				"214",
				"306",
				"211",
				"214",
				"201",`

not there is only one number left, no mater how often the request is executed. This greatly interferes with our current pipeline.

**To Reproduce**
1. Upgrade from version 7.15 to 7.16
2. Run a collection n times
3. Try to find the nice runtime listing ;)

**Expected behavior**
A "times" list as described above.

**App information (please complete the following information):**
 - App Type: native app
 - Postman Version v7.16
 - OS: macOS Catalina 10.15.2

**Comment by mccannt** [comment]
Thanks for reporting this issue @HenningBertsch 
We have logged an issue for this to investigate and resolve.

**Comment by hbertsch** [comment]
A similar issue exists for the "allTests" section too when running tests multiple times: 

* expected result:
`"allTests": [
				{
					" must respond with HTTP 200": true,
					" must respond with an access token": true,
					" must respond with the scope you've requested": true
				},
				{
					" must respond with HTTP 200": true,
					" must respond with an access token": true,
					" must respond with the scope you've requested": true
				},
				{
					" must respond with HTTP 200": true,
					" must respond with an access token": true,
					" must respond with the scope you've requested": true
				},
				{
					" must respond with HTTP 200": true,
					" must respond with an access token": true,
					" must respond with the scope you've requested": true
				},`
* result in version 7.16:
**field is non existent in PM v7.16 any longer**

**Comment by mccannt** [comment]
Thanks again @HenningBertsch 
We have added this to the issue as well. 

I am curious, can you tell us how exactly you are using this information from the runs as part of your CI/CD systems?

**Comment by hbertsch** [comment]
Hi @mccannt, sure.
The APIs we use are numerous and hidden behind various API gateways. Also we do not have full insights into their logs and telemetry data (for a variety of reasons). We use the json export of our test results mainly to see which endpoints act reliably and to track their response times for certain use cases.

E.g. if a team wants to know how a set of services and operations (for their use cases) is responding on different stages, we can easily process the results and create graphical reports for them (like curves and diagrams). There certainly are other clever ways and more sophisticated tools to do this, but we prefer this lightweight solution.

**Comment by mccannt** [comment]
@HenningBertsch Great! This is much appreciated and very much makes sense how it would work in your use case.
Thanks for sharing that with us.

We are actively looking into this so stay tuned :)

**Comment by saswatds** [comment]
Hey @HenningBertsch this issue has been fixed from our end and should be out with the next release of the app.

**Comment by hbertsch** [comment]
Hi @mccannt  & @saswatds, thanks a lot for investigating this issue! Hope to get my hands on the new version soon :)

**Comment by saswatds** [comment]
@HenningBertsch This fix is available in the latest release of the app. Closing this issue now, feel free to reopen if the issue persists for you.
