### ISSUE TITLE
UI: "Body" tab doesn't clear when HEAD request sending.

### ISSUE THREAD

**Issue by ISDemidoff** [a85/POSTMan-Chrome-Extension#7942]
**Describe the bug**
"Body" tab doesn't clear when HEAD request sending.

**To Reproduce**
You should have correctly working server with GET/HEAD contract (HEAD should return same headers (and only headers!) as GET on resource). My case is file provider.

![HEAD_request_bug_postman](https://user-images.githubusercontent.com/20634742/72786199-92c27a80-3c5f-11ea-95b7-c1d1dffdba2b.gif)

1. Drop GET request on valid resource with 200 response and some body (my case is valid image with correct Content-Type and Content-Length headers)
2. Verify that you see contents in "Body" tab (image for me) and stats that shows you've downloaded this file
3. Drop HEAD request on the same resource
4. Error: you still see (same) contents in "Body" tab, but stats shows that you've got only headers

**Expected behavior**
"Body" tab is empty when response body is empty. It should be clear.

**App information (please complete the following information):**
Postman for Mac
Version 7.16.0
OS X 18.7.0 / x64

macOS Mojave 10.14.6 (18G103) on MacBook Pro (15-inch, 2018)

**Comment by shamasis** [comment]
I could reproduce this and this is happening for only when previous GET response had non text / image data and new response has no body data.

Text based API does not reproduce this.
1. Sent a GET request to `https://httpbin.org/anything with body being raw `{{$guid}}` as value
2. See the server respond with a GUID in response `data` JSON field
3. Switch to head and send request
4. See the body as blank

Image API reproduces this.
1. Send GET call to https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
2. See image in response
3. Switch to head and send request
4. See previous image.

My hunch is that the HEAD call returns header of content-type image and not actual body. The UI keeps showing last preview.

**Comment by mccannt** [comment]
@ISDemidoff We have made some recent changes around this. Can you try with the latest version of the application and let us know if it has been resolved for you?
