### ISSUE TITLE
TypeError: Cannot read property 'responseTime' of undefined

### ISSUE THREAD

**Issue by gshakir125** [a85/POSTMan-Chrome-Extension#7943]

**Comment by arlemi** [comment]
@gshakir125 Please open a new issue following the bug report template, this isn't enough information for us to try to help.

**Comment by gshakir125** [comment]
Thank you sir for your  response, i have removed the  detailed  content about the  issue  because there was a misconception to me so i have resolved the issue myself, that's why i have removed the content.
