### ISSUE TITLE
Disable auto update of minor versions

### ISSUE THREAD

**Issue by hbertsch** [a85/POSTMan-Chrome-Extension#7944]
Postman is automatically updating  to the next version (e.g. 7.15 to 7.16) and there is no way to prevent this. I have switched off the "Auto Major Update" option but this won't do the trick. 

Since there are bugs in the newer versions that prevent working properly for us this is a troubling issue.

**Is your feature request related to a problem? Please describe.**
Related to this problem, since it will lead to the described error each time after a restart: https://github.com/postmanlabs/postman-app-support/issues/7941#issuecomment-576414954

**Describe the solution you'd like**
Option to disable auto updates completely. 

* App information (please complete the following information):
App Type: native app
Postman Version v7.15
OS: macOS Catalina 10.15.2

* Screenshot (notice the restart notification message):
<img width="716" alt="PMv7 15autoupdate" src="https://user-images.githubusercontent.com/14974052/72795338-c42a4e80-3c3d-11ea-81c0-40792319319e.png">

**Comment by jyeros** [comment]
I agree that it is useful to have all bug and security fixes but if I am using an metered connection I think it should not be downloaded automatically, the updates aren't so big but sometimes there are a few of them and have an impact when use this type of connection.

**Comment by ks1977** [comment]
please give us the possibility to: 
1) completely disable all kinds of automatic updating
2) choose the installation directory ourself!

Thanks a million!

**Comment by arlemi** [comment]
This is a duplicate of #6999, sorry for not noticing earlier! Closing this one. 🙂

**Comment by stefanluchian** [comment]
@ Postman guys: Why are you insisting to force us to update, even on minor updates?
This is no way to win new users! And you might lose existing ones.
We simply don't want automatically minor updates! Is it so hard to understand it?
We are not some mobile-app-freaks who just want to have the latest thing.
Just let us decide if and when we want minor updates!
This is really annoying!
Stop forcing us to update! Should be our decision!
