### ISSUE TITLE
Scripting: pm.request.url inconsistent treatment of disabled params in toString() versus getQueryString() and getPathWithQuery()

### ISSUE THREAD

**Issue by vincentq** [a85/POSTMan-Chrome-Extension#7945]
**Describe the bug**
In pre-request scripts (and likely test scripts, but I haven't tested this scenario myself), the behaviour of `pm.request.url.toString()` is different to `pm.request.url.getQueryString()` and `pm.request.url.getPathWithQuery()` when there are disabled (unchecked) GET parameters in the Postman UI.

_My use case: Using pre-request scripts to calculate a HMAC-SHA1 signature against the path and query string of the request URL. This script needs to intercepts the request, computes the signature and appends the signature to the query string._

**To Reproduce**
1. Create any GET request with a disabled query param
2. In a pre-request script, enter the following:
```javascript
console.log("toString(): " + pm.request.url.toString());
console.log("getPathWithQuery(): " + pm.request.url.getPathWithQuery());
```
3. Enable Postman Console
4. Send the request (endpoint does not need to be real)
5. Console log output is as follows
```
toString(): http://example.com/?enabled=123
getPathWithQuery(): /?enabled=123&disabled=456
```

**Expected behavior**
The query strings should be consistent between the two. In my use case it is beneficial to hide the disabled parameters, because these are not being sent to the server and therefore is not part of the message to be signed. However other use cases may differ - perhaps the API documentation needs to be clearer on how disabled parameters will be handled, and provide some control over this.

**Screenshots**
Sample request:
![Request setup](https://user-images.githubusercontent.com/536401/72816870-efa04e00-3cbc-11ea-8b77-f737a1726fb2.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.16.0
 - OS: Windows 10 Version 1903

**Additional context**
Workaround: Passing `{ignoreDisabled: true}` into `getQueryString()` and `getPathWithQuery()` produces the expected behaviour, however this is not in line with the documented usage and may relate to deprecated behaviour.

**Comment by vincentq** [comment]
Relevant source snippet: https://github.com/postmanlabs/postman-collection/blob/develop/lib/collection/url.js#L279
```javascript
/**
     * Returns the stringified query string for this URL.
     *
     * @param {?Boolean} [encode=false] - Enables URL encoding when processing the query string
     * @returns {String}
     *
     * @deprecated since v3.4.6, drop support for `encode`
     *
     * @note Deprecated variant of this function is as follows:
     * - param {?Object} [options={}]
     * - param {?Boolean} options.encode - Enables URL encoding when processing the query string.
     * - param {?Boolean} options.ignoreDisabled - Prevents disabled query parameters from showing up in the unparsed
     */
    getQueryString: function (encode) {
        if (!this.query.count()) {
            return E;
        }

        if (typeof encode === OBJECT) { // @todo discontinue in v4
            return QueryParam.unparse(this.query.all(), encode);
        }

        return QueryParam.unparse(this.query.all(), { encode: encode });
    },
```

There is reference to deprecated functionality for the `encode` but does not address `ignoreDisabled`, and the implementation in `toString()` simply implements as follows:
```javascript
        if (this.query && this.query.count()) {
            queryString = this.getQueryString({ ignoreDisabled: true });
            queryString && (rawUrl += QUERY_SEPARATOR + queryString);
        }
```

A more sensible default here would be to add `ignoreDisabled: true` to `getQueryString` and `getPathWithQuery` and introduce further parameters to override this behaviour for specific use cases (what was wrong with passing an options object?)

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v9.9.0).

<img width="574" alt="Screenshot 2022-01-17 at 7 20 26 PM" src="https://user-images.githubusercontent.com/4865836/149780814-b04d0fda-5aff-4fe9-9c92-4fbf28b7bd8a.png">
