### ISSUE TITLE
"Content-Type is present" script is failing in 7.16.0

### ISSUE THREAD

**Issue by CrunchyTechieGuh** [a85/POSTMan-Chrome-Extension#7948]
When using the "Content-Type is present" snippet to verify that a response is Content-Type application/json, the test will fail saying Content-Type is Json | AssertionError: expected response to have header with key 'application/json'. This did not fail in previous versions.

**To Reproduce**
1. Create a request that will return a Json response.
2. In tests tab, find the snippet called Response headers: Content-Type header check
3. Change string in script that was copied into tests to "application/json"
4. Send request. Test will fail for above error

**Expected behavior**
Test should pass with a Json response

**Screenshots**
![image](https://user-images.githubusercontent.com/60202095/72942841-b950e600-3d31-11ea-81ca-aada00fd3f34.png)
![image](https://user-images.githubusercontent.com/60202095/72942878-cc63b600-3d31-11ea-94db-4889cf8f41d1.png)

**App information**
Postman for Windows Version 7.16.0 
Windows 10 Enterprise Version 1809 OS Build 17763.914

**Comment by CrunchyTechieGuh** [comment]
I have reproduced this with a binary/octet-stream type response also.

**Comment by DannyDainton** [comment]
Hey @CrunchyTechieGuh ,

That error is saying that the `Key` is incorrect as that would be `Content-Type`. The value of the key would be 'application/json' or the type of response header for your request.

The snippet in the app takes a second argument for the value of the key `pm.response.to.have.header(key:String, optionalValue:String)`.

In the test, that would look like this:
```javascript
pm.test("Content-Type is application/json", function () {
    pm.response.to.have.header("Content-Type", "application/json");
});
```

More information can be found here:
https://learning.getpostman.com/docs/postman/scripts/postman-sandbox-api-reference/#response-assertion-api-available-in-the-test-scripts

**Comment by CrunchyTechieGuh** [comment]
I suspected this exact thing so thank you!
