### ISSUE TITLE
Postman using 28-45% CPU while being in background

### ISSUE THREAD

**Issue by Aravindsaivellappat** [a85/POSTMan-Chrome-Extension#7953]
**Describe the bug**
Postman running on macOS Mojave consuming about 28-45% CPU on average while in minimized state and without running any tasks.

**To Reproduce**
1. Open postman.
2. Hit a couple of API requests (can be any).
3. Leave it idle for some time.
4. Try checking the activity monitor.
5. Minimize the application.
6. Again verify the CPU usage in activity monitor.

**Expected behavior**
Even during the idle time, the application will be using about 28-45% CPU in total. It can also be noticed that the application consuming above 80% power.

**Screenshots**
<img width="557" alt="Screenshot 2020-01-24 at 2 34 43 PM" src="https://user-images.githubusercontent.com/52652569/73057167-ce0ab680-3eb6-11ea-9567-4a546ef57172.png">
<img width="600" alt="Screenshot 2020-01-24 at 2 35 03 PM" src="https://user-images.githubusercontent.com/52652569/73057168-cea34d00-3eb6-11ea-81ae-b49518e664a9.png">

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 7.13.0
 - macOS Mojave 10.14.5

**Comment by ankurdengla** [comment]
Hey @Aravindsaivellappat ! 

Thank you for reaching out and reporting this issue. We are tracking issues related to high CPU consumption in this thread - #7294 . 

I'm closing this as a duplicate. Please follow the original thread for updates. It would also be helpful if you could tell us how much data you have in the app (i.e. number and size of collections, number and size of environments etc.)
