### ISSUE TITLE
Check for a JSON value

### ISSUE THREAD

**Issue by gshakir125** [a85/POSTMan-Chrome-Extension#7958]
What's Wrong with the following test script code to check a Json value in response in postman, I am getting following.
**Error:**
Check for a JSON Value in response | JSONError: Unexpected token '-' at 10:1 ----------------------Request------------------------------- ^)

**Test Script Code**
pm.test("Check for a JSON Value in response",function(){
    var data = pm.response.json();
    pm.expect(data.city).to.equal("Lahore");
});

**Response body is following**
{
    "City": "Lahore",
    "Temperature": "14 Degree celsius",
    "Humidity": "50 Percent",
    "WeatherDescription": "smoke",
    "WindSpeed": "1.22 Km per hour",
    "WindDirectionDegree": "290 Degree"
}

----------------------Request-------------------------------

Request Line: GET /utilities/weatherfull/city/lahore 

Request Method: GET

Request Time: 2020-01-25 05: 37: 45

Accept-Encoding: gzip, deflate, br

Host address: restapi.demoqa.com

Client IP: 

Client Port: 47824

HTTP Protocol Version: 

Connection: close

User-Agent: PostmanRuntime/7.22.0

Accept-Language: 

Request body: 

-------------------------Response---------------------------

Status Line: HTTP/1.1 200 OK

Response status code -> 200 OK

Server: openresty

Date: Sat,
25 Jan 2020 05: 38: 41 GMT

Content-Type: application/json; charset=utf-8

Content-Length: 460

Connection: close

X-Cache-Key: /data/2.5/weather?APPID=199c0c704dcd69ff1a88fc99385dae08&q=lahore

Access-Control-Allow-Origin: *

Access-Control-Allow-Credentials: true

Access-Control-Allow-Methods: GET, POST

Response Body: {
    "City": "Lahore",
    "Temperature": "14 Degree celsius",
    "Humidity": "50 Percent",
    "WeatherDescription": "smoke",
    "WindSpeed": "1.22 Km per hour",
    "WindDirectionDegree": "290 Degree"
}

**Comment by christopher-nash** [comment]
You are having this issue because of the API you are calling, specifically caused by the `pm.response.json()` you are using. That call is trying to turn the _entire_ response body into JSON, but there are characters in the response body which are invalid JSON.

The full API's response body is literally
```json
{
    "City": "Lahore",
    "Temperature": "11.2 Degree celsius",
    "Humidity": "76 Percent",
    "WeatherDescription": "smoke",
    "WindSpeed": "1.5 Km per hour",
    "WindDirectionDegree": "360 Degree"
}

----------------------Request-------------------------------
Request Line: GET /utilities/weatherfull/city/lahore 
Request Method: GET
Request Time: 2020-01-29 16: 53: 31
Accept-Encoding: gzip, deflate, br
Host address: restapi.demoqa.com
Client IP: 
Client Port: 50968
HTTP Protocol Version: 
Connection: close
User-Agent: PostmanRuntime/7.22.0
Accept-Language: 

Request body: 
-------------------------Response---------------------------
Status Line: HTTP/1.1 200 OK
Response status code -> 200 OK
Server: openresty
Date: Wed,
29 Jan 2020 16: 54: 28 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 458
Connection: close
X-Cache-Key: /data/2.5/weather?APPID=199c0c704dcd69ff1a88fc99385dae08&q=lahore
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST

Response Body: {
    "City": "Lahore",
    "Temperature": "11.2 Degree celsius",
    "Humidity": "76 Percent",
    "WeatherDescription": "smoke",
    "WindSpeed": "1.5 Km per hour",
    "WindDirectionDegree": "360 Degree"
}
```

Because that API is regurgitating everything that was included in the request and the full body, including headers and things it is invalid JSON. That API breaks the standard spec of only including standard JSON.

Everything after the line 
```json
 "WindDirectionDegree": "360 Degree"
}
``` 
is invalid JSON so it "blows up" when trying to serialize to JSON.

You need to find out a way to tell the API you are calling to _not_ include the extra stuff after the actual JSON body, or rework you test so that it doesn't try and serialize the entire body to JSON (I can't offer tips on that because I don't know how to do it).

**Comment by sankalp0o** [comment]
Hey @gshakir125, I hope that the explanation provided by @christopher-nash was able to solve your problem. If you require more assistant, please reach out to the Postman Community at  https://community.postman.com/ where people might be able to help you out!
