### ISSUE TITLE
Postman 7.16.1 has a major bug in Collection Runner 

### ISSUE THREAD

**Issue by amodmahajan2016** [a85/POSTMan-Chrome-Extension#7959]
Collection Runner is not able to read values from data files. 

Steps to reproduce:-
1. Create a Collection.
2. Add a paramterised request to it. 
3. Create data file.
4. Run using collection runner.

Expected:- Should run successful.
Actual:- Variables are not replaced with actual values. But Postman console shows correctly.

![image](https://user-images.githubusercontent.com/20769876/73117508-a6762580-3f6c-11ea-9207-29b6220de7f9.png)
![image](https://user-images.githubusercontent.com/20769876/73117512-b2fa7e00-3f6c-11ea-91a5-0dbf3c9cd62b.png)

Collection Link:- https://www.getpostman.com/collections/045a9545b18612cdd4c8

**Comment by arlemi** [comment]
Hey @amodmahajan2016, we're currently tracking this in #7940, it should be fixed in the next release. 

Closing this one.

**Comment by AnaGoulart23** [comment]
quando será lançada a próxima version?

**Comment by arlemi** [comment]
@AnaGoulart23 It is planned to be released on the 29th of January.
