### ISSUE TITLE
Issues with syncing - probably related to constant HTTP 429 - Too many request errors

### ISSUE THREAD

**Issue by pwae** [a85/POSTMan-Chrome-Extension#7961]
I apologies in advance if this issue should have been posted in community, but it does not seem like a using the application issue, but instead an issue potentially with my account.

**Describe the bug**
Whenever i try to set up sync, or whatever; with any of the postman sync api's, i see in the developer console that I get a Too many requests HTTP Error (429). Screenshot below.

I've had this account since 2014 (originally had a postman jetpack purchased on it).
I have never previously tried to do anything with Sync, but i determined i would do something with it as of the last few days, so i could use the multiple workspace functionality.
It was in trying to set up this, that i ran into all my issues. and seem to have traced it back to this error occurring.

As a status, the Sync icon is constantly red, anything i do to try and set up sync within the app does not work. If i create a new workspace on the web site, and then open it in the native app, postman tells me i need to be invited to that workspace; and then i can't join it.

i saw an issue #6104 which suggested a case of updated and deleting content from Application Support/Postman; and have done this to no success.

To eliminate any "temporary" issues around API rate limits, i logged out of postman last night after trying, waited 24 hours, then opened postman, logged in again, and was still confronted with the same Too many requests issue.

My account username is the same as my github account.

I'm not sure what else i can provide right now to assist; but i'm more than happy to provide anything required. you can also contact me via email if this is more an account issue please.

**To Reproduce**
Steps to reproduce the behaviour:
n/a

**Expected behaviour**
n/a

**Screenshots**

![Screen Shot 2020-01-27 at 00 39 24](https://user-images.githubusercontent.com/252082/73136114-06b8b480-409e-11ea-8458-3ea68845bba6.png)

**App information (please complete the following information):**
 - Native App
 - was an older version (don't recall, but still occurring on latest - Version 7.16.1 (7.16.1)
 - macOS Mojave - 10.14.6

**Additional context**

**Comment by masturi** [comment]
I have exactly the same issue:
- Sync button in constantly red
- 429 (Too Many Requests)
- Account since ~2015 (with jetpack)
- macOS Catalina 10.15.4
- Postman for Mac, Version 7.23.0, OS X 19.4.0 / x64

**Comment by gtonioli** [comment]
Same issues here:

- Sync button in constantly red
- 429 (Too Many Requests)
- Account since 2016
- Windows 10 Pro 18362.778
- Postman for Windows, Version 7.24.0 / x64

**Comment by glpunk** [comment]
Same problem here, any update?

Linux popOS 20.04

**Comment by navneetgarggate6** [comment]
same issue

**Comment by DannyDainton** [comment]
Hey @glpunk / @navneetgarggate6 

As you are the most recent users to comment could either of you share more details of the issue you're facing, please? Screenshots of a short video of this happening in the latest version will help visualise the issue and allow us to debug further.
