### ISSUE TITLE
error while importing: format not recognized in postman

### ISSUE THREAD

**Issue by namrata66sharma** [a85/POSTMan-Chrome-Extension#7962]
**Describe the bug**
Whenever I go to import and inside paste raw text https://any-api.com/rottentomatoes_com/rottentomatoes_com/docs/Movie_Lists/BoxOfficeMovieLists and click on import, the error message is displayed "error while importing: format not recognized"

1. Go to postman
2. Click on import -> click on paste raw text
3. Click on import in the import box
4. See error message "error while importing: format not recognized"

**Expected behavior**
Response should be generated

**Screenshots**
![Uploading image.png…]()

**App information (please complete the following information):**
 - Website [opened in Google chrome]
 - Postman Version 7.16.1
 - OS: Windows 10

I am experiencing this issue while testing all api today.

**Comment by ptolemys** [comment]
Hi @namrata66sharma - 

The link you are using : 
https://any-api.com/rottentomatoes_com/rottentomatoes_com/docs/Movie_Lists/BoxOfficeMovieLists
is simply a URL that can open on browser using GET protocol. This is not a valid curl format which Postman recognizes for imports. 

You should try importing the following :

`curl -X GET 'https://any-api.com/rottentomatoes_com/rottentomatoes_com/docs/Movie_Lists/BoxOfficeMovieLists'`

**Comment by sankalp0o** [comment]
Hey @namrata66sharma, I hope that the explanation provided by @ptolemys was able to solve your problem. If you require more assistant, please reach out to the Postman Community at https://community.postman.com/!

**Comment by MihaRomanov** [comment]
try this https://learning.postman.com/docs/getting-started/importing-and-exporting/importing-data/
