### ISSUE TITLE
Popup dialog blocking field value

### ISSUE THREAD

**Issue by jadamita** [a85/POSTMan-Chrome-Extension#7963]
**Describe the bug**
When clicking on a request body, (ex: a form-data value of a field, it displays a list of different #values like "#guid", "#randomInt"). This display box should be set to a toggle, or this little box shouldn't be displayed at the top left of the box. My JSON body is smaller then the size of this popup, so it makes it extremely tedious to modify the values with this display popping up every time I go to change the value. Maybe have the dialog popup to the right of the value field box.

**To Reproduce**
1. Open a new request
2. Go to the body tab
3. Select the "form-data" radio-button
4. Enter a small json body in the value field. (Be sure the JSON is more then 1 line)
`{
	"var": "joseph"
}`
5. Click off the field value (inside the main json object {})
6. Click on the field value again to see the display pop up.

**Expected behavior**
I imagine this small dialog should popup to the right of the body value box once it's expanded.

**App information (please complete the following information):**
 - App Type: Desktop client app
 - Postman Version: 7.16.1
 - OS: Windows 10

**Comment by ankurdengla** [comment]
Hey @jadamita !
Could you provide us screenshot(s) of the issue in order to help us understand it better?

**Comment by jadamita** [comment]
![screenshot](https://user-images.githubusercontent.com/12914665/73754690-c1962180-4732-11ea-9a29-3ffb95781ef6.PNG)
The window blocks the value every time you click on it, can this be a toggle? or have it open at a different location based on the value input box size?

**Comment by ankurdengla** [comment]
Hey @jadamita !
Thanks for sharing the screenshot of the issue. From what I can see, the issue is that the dropdown is blocking the actual content of the cell. You can disable this from `Settings -> Variable Autocomplete`. 

![Screenshot 2020-02-05 at 2 00 40 PM](https://user-images.githubusercontent.com/26045713/73824395-1a8fb380-4820-11ea-8e9f-61742eb7f0e7.png)

**Comment by jadamita** [comment]
Wow! I have no idea how I over-looked that option.

Thanks
