### ISSUE TITLE
Downgrade to postman 7.15.0

### ISSUE THREAD

**Issue by elyaell** [a85/POSTMan-Chrome-Extension#7964]
1. Postman Native App
2. Version 7.15.0
3. Windows 10

Since the upgrade to 7.16.0/1, members of the team can't synchronized their postman application. 
Tried to downgrade the version to 7.15.0 to check if the problem exists in this version too (and rules out postman for the possible cause of the bug), but after the installation, postman seems to detect that a more recent version has been used on the computer and refuse to launch.

What should i do to be able to downgrade the application ?

**Comment by milititskiy** [comment]
You need to Physically delete the folder of the 7.16.version.To do that You have to go to the root folder in the system :C:\Users\{{your_username_here}}\AppData\Local\Postman amd delete the folder with name app-7.16.0/1.

**Comment by harryi3t** [comment]
@FaithFeather Could you provide us more details about the issues you or your team members faced on v7.16.x?

**Comment by SabriH10** [comment]
Hi @FaithFeather,

If it's alright with you, I'm going to go ahead and close this issue. If this issue still hasn't been addressed and your team are observing problems, please feel free to either re-open this issue or open a ticket via https://www.postman.com/support/, and we'll be happy to investigate further.
