### ISSUE TITLE
'View in Web' rendered docs do not resolve environmental variable for first request

### ISSUE THREAD

**Issue by jwbanning** [a85/POSTMan-Chrome-Extension#7966]
**Describe the bug**
When generating documentation from the 'View in Web' button on the collection call out 
![viewInweb](https://user-images.githubusercontent.com/2584258/73299680-3f0ede80-41d5-11ea-9e51-f1c74442ae37.png), the rendered code sample documentation does not resolve the environmental variable for the first request. 

<img width="1762" alt="Screen Shot 2020-01-28 at 1 55 07 PM" src="https://user-images.githubusercontent.com/2584258/73300001-df650300-41d5-11ea-8d39-69f4e9a685a5.png">

{{url}} should resolve to what it is set to. This works for all the other requests. 

**To Reproduce**
1. Create a collection. Mine has 4 requests. 
2. Create an environment that has some variable and use that in the collection. I used {{url}}
3. Click on the View in Web button from the collection call out. 
4. From the rendered documents, select the environment that contains the environmental variable.  
5. Looking at the code samples in the rendered docs, the {{url}} should be replaced with the variable value.  
6. See image below.

**Expected behavior**
The {{url}} environmental var would resolve for the code samples. This is happening for all code samples for the first request. 

**Screenshots**
![url](https://user-images.githubusercontent.com/2584258/73300249-53071000-41d6-11ea-87f6-ff83fd44de16.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version Version 7.16.0 (7.16.0)
 - OS: 10.15.2

**Comment by Raja-Simha** [comment]
@jwbanning could you make sure that you selected an appropriate environment through the dropdown. Your screenshots suggest that you have not selected an environment through the environment dropdown.

**Comment by jwbanning** [comment]
Here is the updated images >  
![environ](https://user-images.githubusercontent.com/2584258/73375914-2e687200-4282-11ea-80aa-72a27613f064.png)

**Comment by godfrzero** [comment]
1. If you reorder the requests so that this request is second, does the problem still persist?
2. Is this happening in the published version of the documentation as well?
3. Would it be possible to share the published URL for this collection so we can take a closer look?

**Comment by jwbanning** [comment]
@godfrzero I know more about this now. There is no sample for the GET. I am still seeing an odd behavior  and would like to either share a video about it or get on a call so i can share my screen. In the mean time here is the URL:

**Comment by godfrzero** [comment]
I was able to reproduce the bug using a similar collection. It looks like this happens when there is no example specified. @Raja-Simha Can you tag this one as a bug?

**Comment by ranchanarajasekaran** [comment]
This issue has been fixed.
