### ISSUE TITLE
Create iteration variables in prerequisite script

### ISSUE THREAD

**Issue by alexszarko** [a85/POSTMan-Chrome-Extension#7967]
Is it possible to create a set of multi-iteration variables in the pre-req script so that when running the collection or request it can iterate using those variable in the request or test on the response?  If so any hints on syntax?

**Comment by SabriH10** [comment]
Hey @alexszarko ,

Apologies for the late reply here on your inquiry. I just wanted to check if, perhaps the following feature could help. It's not in regards to the pre-request script, but if you're looking at testing different variable values for each iteration you could try using the Collection runner and importing a data file:
https://learning.postman.com/docs/running-collections/working-with-data-files/

Let me know if this helps. Apologies again for the delay!

**Comment by SabriH10** [comment]
Hi @alexszarko ,

Just following-up on my previous response. Was the information helpful for your particular use-case?

**Comment by DannyDainton** [comment]
Hey @alexszarko 

I'm going to close this issue due to inactivity.
