### ISSUE TITLE
Cannot connect using proxy

### ISSUE THREAD

**Issue by DimaOrdenov** [a85/POSTMan-Chrome-Extension#7970]
**Describe the bug**
I am trying to use global and manually-set proxy settings of my corporate network, but have problems connecting to postman servers.

**To Reproduce**
1. Go to Postman -> Preferences -> Proxy
2. Check "Use System Proxy" and check "Respect HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables"
3. Restart Postman app and get message "You seem to be offline" w/o ability to connect to Postman servers (check updates, for example)

OR

2.1. Uncheck "Use System Proxy" and check "Global Proxy Configuration"
2.2. Set values for
 - Proxy type: "HTTP" - On and "HTTPS" - On
 - Proxy Server: https://corporate.proxy.server AND corporate.proxy.server.port_number
 - Proxy Auth: "On"
 - Username, Password
3. Restart Postman app and get message "You seem to be offline" w/o ability to connect to Postman servers (check updates, for example)

**Expected behavior**
Connect to postman servers, get updates or team workspace info

**Screenshots**
![image](https://user-images.githubusercontent.com/16692044/73352191-aa25e700-42a1-11ea-97ba-cb78a5b5bc53.png)
![image](https://user-images.githubusercontent.com/16692044/73352203-b14cf500-42a1-11ea-90c9-ae3d6ef7ab23.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.16.1
 - OS: macOS Mojave 10.14.4

**Comment by ankurdengla** [comment]
Hey @DimaOrdenov !
Thank you for reaching out to us. The `Proxy` settings in the Settings modal only affects the request sending feature of Postman. It does not apply to features such as sync, checking for updates etc.

Currently, we do not have support for accessing Postman's cloud features (like sync, updates etc.) through a proxy server that has authentication. We are already tracking this as a feature request at this thread - #6053 .

I'm closing this as a duplicate. Please follow the original thread for updates.
