### ISSUE TITLE
Clearing local storage when log out

### ISSUE THREAD

**Issue by JohnyCape** [a85/POSTMan-Chrome-Extension#7971]
**Describe the bug**
NOT SYNCED COLLECTIONS ARE LOST WHEN LOGOUT!

**To Reproduce**
1. Open postman without loging into.
2. Add collection.
3. Sign in.
4. Log out.
Result: Lost all collections. This is crazy...

**Expected behavior**
Shouldn't clear local storage if it's not synced.

**Screenshots**
-

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version Version 7.16.1

 - OS: win32 10.0.18363 / x64

**Additional context**
What is the reason to clear local storage when log out? I lost ALL MY COLLECTIONS!!!!!!!!!!!!!!!!!

**Comment by ArjunSingh-PM** [comment]
@JohnyCape Thank you for writing to us. When you logged out of the app, did you see a warning message - _You have unsaved changes_

<img width="478" alt="Signing out with unsaved data" src="https://user-images.githubusercontent.com/53265429/75652344-d78af980-5c80-11ea-8a4e-51cc0a7569ad.png">

**Comment by DannyDainton** [comment]
Closing this out due to inactivity.
