### ISSUE TITLE
Postman API error at Get Single Monitor endpoint

### ISSUE THREAD

**Issue by bruce-palmer** [a85/POSTMan-Chrome-Extension#7974]
We have an in-house .NET utility to run monitor collections via Newman. This utility has been working for several months.

In the last week or so the utility has failed. Specifically, when it attempts to retrieve the details of a monitor it gets a 400 error.

I have tested the API call in Postman and get the same error.

Sample call:
https://api.getpostman.com/monitors/2173985-1e82297a-2d1e-41b0-983b-d9f34203bab7?apikey={{postman-apikey}}

Result:
400 Bad Request
{
    "error": {
        "name": "paramsConflictError",
        "message": "Invalid Job filter: user_id"
    }
}

I have tried this call multiple times with both monitor ids and uids and get the same error every time.

Getting a list of monitors works okay.

Is this a bug in the endpoint, or has something changed and I need to modify how I call the endpoint?

 - App Type: .NET app
 - Postman Version: 7.16.1
 - OS: Windows 10

**Comment by bruce-palmer** [comment]
I've tried again today and have the same problem as reported above.

In addition I now get an empty list when asking the Postman API for a list of monitors (previously the list was fully populated). I can see the monitors in the Postman UI.

And when I ask the Postman API for a list of workspaces I get a truncated list, not including the ones I belong to. But I can see all of them in the Postman UI.

Has there been some kind of authorisation or authentication change? Do I need to generate a new API key?

Would really like to know what's going on here. The one error message I've received (in the original post) doesn't help, and the missing data that was there before is a mystery.

**Comment by shivam-postman** [comment]
Hi @bruce-palmer, are you still getting the same error message (`Invalid Job filter: user_id`) or a different one?

**Comment by bruce-palmer** [comment]
Hi @shivam-postman,

When I try to get the details of a monitor, as per the original post, today I get the following response:

{
    "error": {
        "name": "forbiddenError",
        "message": "You do not have access to this monitor."
    }
}

When I try an get a list of monitors with this call:

https://api.getpostman.com/monitors?apikey={{postman-apikey}}

I get the following response:

{
    "monitors": []
}

When I originally posted about the problem, listing monitors returned a list of all our monitors. Today it doesn't.

I can't figure out what's changing that's blocking my access.

Thanks.

**Comment by ShankMahadev** [comment]
Hi @ArjunSingh-PM, 
Could you please escalate this issue?
It is breaking our automated builds, and affects our ability to successfully do deployments. Its a high priority issue for us and we need a resolution to this problem as soon as possible. We have been using Postman for a while now and a swift resolution to the issue is a need.
Regards,
Shank

**Comment by shivam-postman** [comment]
Hi @ShankMahadev, we're looking into the issue and will get back soon.

**Comment by shivam-postman** [comment]
@bruce-palmer It looks like you were a part of some team earlier (before 03/02/2020) and when you were no longer in it, the empty monitor list started showing up in the response. The list you're seeing now, is of your personal monitors. As for the individual monitor, it belongs to the team, most likely, hence can't be accessed outside it. Do let me know if any part of this doesn't seem right.

@ShankMahadev, can you provide the ID of the monitor in question and the error which you're getting? Thanks.

**Comment by bruce-palmer** [comment]
@shivam-postman This morning I generated a new API key. The new key was longer than the old key I was using.

With the new key our automated test running is working again.

The new key is the only change I've made. I still don't understand why this problem occurred.

I consider the issue now fixed.
