### ISSUE TITLE
SSO Login via ADFS fails specifically on the Mac Application

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#7975]
**Describe the bug**
**SSO Login via embedded browser on Postman Mac Application**:- Users get a "Something went wrong" error message after they click on "Enterprise Sign-in" and select ADFS as the Authentication method
**SSO Login via Browser on Postman Application**:- User appears to be logged in on the Browser, but the Login status is not reflected on the Postman Mac Application

**To Reproduce**
Steps to reproduce the behaviour:
SSO Login via embedded browser on Postman Mac Application
1. Go to "Enterprise Sign in"
2. Click on 'ADFS Authentication Method.'
3. Something went wrong error

SSO Login via Browser on Postman Application
1. Click on "Login via Browser"
2. Go to "Enterprise Sign in"
3. Select "ADFS" authentication method
4. Enter credentials and submit
5. View the following screen:
![Web Dashboard-Screen](https://user-images.githubusercontent.com/51746288/73517321-26930400-4421-11ea-85d6-b50b7ce039e0.png)
6. Navigate back to the app to see the following screen
![App-Screen](https://user-images.githubusercontent.com/51746288/73517408-66f28200-4421-11ea-9eec-4fd82cf5e92f.png)
7. Click on "check if you’re signed in", it does nothing, and clicking “open your browser” presents the following error message:
"403 You did not fetched handover early enough"

**Expected behavior**
Via Embedded Browser:- Navigate to the Identity Provider Login Screen
via Browser:- You should be logged onto The Postman Mac application when you navigate to it

**App information (please complete the following information):**
 - App Type :- Native App
 - OS: Mac
From logs:
`Postman 7.15.0, darwin-18.7.0 on x6`

**Additional context**
1. The issue exists only on the Postman Mac Application, Users are able to login on the Web Dashboard as well as on the Postman Windows Application
2. The Mac uses Kerberos to authenticate to the proxy
3. From Support:- Log analysis reveals that the ADFS server is not initiating a redirect to Postman service URL identity.getpostman.com 
4. From User:- Wireshark traces where the Mac is talking to the ADFS domain, (there is no FIN/ACK to end the TCP interaction

**Comment by DannyDainton** [comment]
Hey @aamir-ahmed 

Do you know if this is still an issue on the latest version of the app?

**Comment by DannyDainton** [comment]
Closing this after confirmation from @aamir-ahmed that it's no longer an issue.
