### ISSUE TITLE
Postman Pro API: You are not authenticated by the server.

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#7980]
The Postman Pro API Documentation at https://docs.api.getpostman.com/?version=latest#authentication should mention that for custom domains, you should still use `https://api.getpostman.com` instead of your custom domain, otherwise you will get a `{"error":{"name":"authenticationError","message":"You are not authenticated by the server."}}` error.

**Comment by davidespihernandez** [comment]
Hi, we have been improving the documentation for the Postman API in the Public Postman Workspace. You can find the documentation here: https://www.postman.com/postman/workspace/postman-public-workspace/collection/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a?ctx=documentation

The Postman API is served from https://api.getpostman.com in any case (see the URL in the requests in that collection).
