### ISSUE TITLE
Postman Pro API Support for Getting Global Variables

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#7982]
There's no API definition in `https://docs.api.getpostman.com/?version=latest#96c34392-1e36-d1cb-af89-1c95365184ab` for submitting a GET to retrieve global variables.  I'm not sure if this is an oversight in the documentation or it needs to be a new feature.

**Comment by johnwyles** [comment]
Please add this feature or document it's API in the API documentation. If the Global has a UUID, you can get Environments, and you can get Collections it is only natural you should be able to get the Globals. This is incomplete both with how this would seem to naturally work and incomplete with regards to Newman.

**Comment by jenslauterbach** [comment]
I am also interested in this feature. We could use this for `newman` runs in our CI/CD pipeline as well.

**Comment by beckerGil** [comment]
I am also interested in this feature

**Comment by gunesmes** [comment]
I am also interested in this feature

**Comment by BharatB427** [comment]
+1, Interested in this feature.

**Comment by samuelClo** [comment]
+1

**Comment by HCS-Georgii** [comment]
+1, highly required feature

**Comment by fonestardev** [comment]
+1, highly required feature

**Comment by tzarfaros** [comment]
+1, Interested in this feature.

**Comment by ramith** [comment]
+1, I'm also interested in this feature.

**Comment by Mahonnant** [comment]
+1

**Comment by mahmoudozil** [comment]
+1!!!

**Comment by ddfreiling** [comment]
+1

**Comment by watsonian** [comment]
I would also like to see a way of updating the Global variables as well. We're creating a third party integration that syncs secrets to Postman as variables and it will be able to cover Collections and Environments. We'd love to be able to support Global variables as well.

**Comment by jsteiml** [comment]
+1 please!

**Comment by anhhanuman** [comment]
+1 please

**Comment by davidespihernandez** [comment]
Good news!
- The new [Workspace Global Variables API](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-a75846bd-c1c7-43e3-88f6-a0c752db83c5) allows to CRUD the workspace global variables (similar to the environments API).
- In addition, you should be able to modify collection variables using the [PATCH collections endpoint](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-24607f03-453e-4936-b544-78d99e05cd19).

Hopefully, you will find these APIs helpful.

**Comment by jwyles-ampliforce** [comment]
@davidespihernandez this is great news! thank you for sharing!

**Comment by johnwyles** [comment]
@davidespihernandez This is great news! Thank you for your attention to this issue and helping to supply further information!
