### ISSUE TITLE
Include usage metrics in a Reporting view

### ISSUE THREAD

**Issue by carolin-postman** [a85/POSTMan-Chrome-Extension#7986]
**Is your feature request related to a problem? Please describe.**
More of an idea than a problem

**Describe the solution you'd like**
As an admin, I'd like to be able to view usage stats of my team to identify users who have been in/active over a certain period of time (ex. 3/6/9/ months.) in a dashboard.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by bhargavkn** [comment]
@carolin-postman This has been released to enterprise teams and one can view this by clicking on the Team Members tile on Team Activity page.

Let's close this issue?
