### ISSUE TITLE
JSON syntax validator in body editor does not recognize invalid data type

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7987]
**Describe the bug**
When creating a request with a JSON payload, the editor for JSON deems as valid a data type that is not valid.

**To Reproduce**
1. Create a POST request, with the RAW body and TYPE JSON
2. Paste
```
{
	"foo": 007
}
```
3. See that the validator does not indicate any errors

**Expected behavior**
The JSON validator should kick in and notice that 007 is not valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/1197635/73696973-7258de00-46ab-11ea-81ed-b92f0fa520cf.png)

![image](https://user-images.githubusercontent.com/1197635/73696991-7be24600-46ab-11ea-8525-85aac43ec0ef.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.16.0
 - OS: masOS

**Comment by kamalaknn** [comment]
@vdespa We've updated the editor for request body in the latest version. You should now see validation errors for these inputs 😄

**Comment by vdespa** [comment]
The error is now "Expected comma" which is still confusing but at least there is an error. Thanks for looking into this.
