### ISSUE TITLE
GitHub integration removal missing for FREE version

### ISSUE THREAD

**Issue by kesamlats** [a85/POSTMan-Chrome-Extension#7988]
**Is your feature request related to a problem? Please describe.**
Not able to remove integration. Removed api version binding but seems the integration is still there as I tried to create integration to different repo for the same API and it is failing on the integration being still "in database". I was not able to follow the PRO guideline as Configure Integration tab is empty.

**Describe the solution you'd like**
In case of bug fix the issue + clean DB. Otherwise make FREE version integrations visible in Configured integrations like it is with PRO version.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by kesamlats** [comment]
In the meantime: found a "workaroud" by creating a new API. As this issue is related to FREE version you would probably need to delete the existing one (with its change history) as there is limit of max 3 APIs.

**Comment by pranayat** [comment]
Hey, you should be able to see the integration listed in the 'Configured Integrations' tab.
Can you confirm if you are viewing the 'Configured Integrations' tab in the same workspace in which your API exists? 
Also, share screenshots if you can.

**Comment by dushyantchillale** [comment]
@kesamlats Just checking in to see if you had a chance to go through @pranaya94 's comment?

**Comment by Hayk-S** [comment]
Closing this issue out. Please feel free to reopen if there are any issues with this.

**Comment by Hayk-S** [comment]
Closing this issue out. Please feel free to reopen if there are any issues with this.
