### ISSUE TITLE
User feedback: utilizing insecure passwords

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7989]
**Is your feature request related to a problem? Please describe.**
User shared feedback that they shouldn't be required to utilize a secure password for our services, contending that while we can advise, we shouldn't enforce this as a hard requirement.

**Describe the solution you'd like**
For consideration: allowing users to opt out of secure passwords.

**Comment by ArjunSingh-PM** [comment]
@JP-from-Postman Could you please elaborate on which specific requirement/restriction did the user have an issue with?

**Comment by JP-from-Postman** [comment]
@ArjunSingh-PM this user's feedback was that no password safety requirement of any kind should be enforced strictly. Currently, I think we only mandate a minimum length.

**Comment by ArjunSingh-PM** [comment]
@JP-from-Postman, we enforce only a limit on character length i.e. 8 to 64 characters. This is something we intend to keep as is.
