### ISSUE TITLE
Documentation to 200 Response to the Postman 'API Key Owner' endpoint out of sync with collection available from the 'Run in Postman' button

### ISSUE THREAD

**Issue by jwbanning** [a85/POSTMan-Chrome-Extension#7991]
From this webpage: https://docs.api.getpostman.com/?version=latest#906a4a52-82f7-e494-d39f-a7344a9097e0

The documentation for a 200-Example response for the  "https://api.getpostman.com/me"  endpoint shows: 

<img width="490" alt="Screen Shot 2020-02-04 at 2 09 42 PM" src="https://user-images.githubusercontent.com/2584258/73792686-aab6f580-4759-11ea-80f6-8de718e087d2.png">

But if you hit the "Run in Postman" at the top of the same page (https://docs.api.getpostman.com/?), the collection that is imported has a different 200 response after executing the request

<img width="789" alt="documentation" src="https://user-images.githubusercontent.com/2584258/73793084-80196c80-475a-11ea-83c4-4e0b1b9d5811.png">

**To Reproduce**
1. Go to  the following page https://docs.api.getpostman.com/?, and look at the documentation for the 200 response on the User > API Key request endpoint. It shows that success is:
`{
  "user": {
    "id": "631643"
  }
}`

2. Scroll to the top of that page and import the collection using the Run in Postman button. 
3. Scroll down to User > API Key request in your collection and replace the {{postman_api_key}} with a valid key. You will see a response containing the 
`"operations": [
        {
            "name": "adp_api_usage",
            "limit": 100,
            "usage": 32,
            "overage": 0
        },`

**Expected behavior**
Documentation and expected results should be the same.

**Comment by jwbanning** [comment]
Also saw that within the Operation array, the "monitor_request_runs" limits is portrayed as a string:

` {
            "name": "monitor_request_runs",
            "limit": "100000",
            "usage": 1746,
            "overage": 0
        },`

**Comment by DannyDainton** [comment]
The original link looks to be pointing to the deprecated Postman API documentation - The most up-to-date version can be found in this public workspace.

https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-f6f8cf93-7b52-4167-bf91-cb38d13684e1
