### ISSUE TITLE
Issues with resolving variables in CSV runner

### ISSUE THREAD

**Issue by natemadel** [a85/POSTMan-Chrome-Extension#7993]
There is an issue with CSV runner wherein it seems to be only resolving 1 variable of the 2 variables I am using in my request body from the csv. I've verified column headers match the variable names exactly. I am on version  v7.17.0

**To Reproduce**
1. Create a simple post request inside a collection
2. Use 2 variables in the POST body (mine are id_lp and id_user)
3. Select Runner
4. Choose Collection
5. Choose File
6. Run Collection

**Expected behavior**
Both variables in the CSV are resolved to variables in the request body

**Current behavior*
Only 1 of the variable is resolved into the request body

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version v7.17.0
-  macOS

**Additional context**
I saw a similar issue reported in the last version that said it was resolved

<img width="679" alt="Screen Shot 2020-02-04 at 7 11 36 PM" src="https://user-images.githubusercontent.com/60676932/73798933-5d02b300-4782-11ea-8c36-527ca7ddc837.png">
<img width="700" alt="Screen Shot 2020-02-04 at 7 12 08 PM" src="https://user-images.githubusercontent.com/60676932/73798939-63912a80-4782-11ea-932b-33f562217ef8.png">
<img width="472" alt="Screen Shot 2020-02-04 at 7 15 23 PM" src="https://user-images.githubusercontent.com/60676932/73799040-ba96ff80-4782-11ea-9beb-d80a6517d348.png">

**Comment by natemadel** [comment]
Update.. this only happens with column A of the csv. Shifting all your values over 1 column (and leaving column A blank) fixes it. I assume Postman has an error with their column index numbering

**Comment by cyrielle-hada** [comment]
@natemadel your file might contain UTF-8 with Byte order mark characters which would explain the issue you're seeing.

Data-files with BOM characters or encoding other than UTF-8 are not working at the moment - Engineering has already fixed the issue on our Canary build - https://www.postman.com/downloads/canary. It should be pushed to production soon.

**Comment by saswatds** [comment]
@natemadel We have pushed a fix to this issue on the latest postman app version `7.18.0`. Can you verify that this issue is fixed for you?

**Comment by saswatds** [comment]
Closing this issue assuming your file contained BOM characters, which is fixed in the latest version of the app. Feel free to re-open if the issue persists for you.
