### ISSUE TITLE
Postman slows down the PC

### ISSUE THREAD

**Issue by adikhel** [a85/POSTMan-Chrome-Extension#7994]
**Describe the bug**
When I open Postman app, my pc slows down to a crawl

**To Reproduce**
1. Open Postman app

**Expected behavior**
I expect postman to not slow down my PC

**App information (please complete the following information):**
 - App Type Windows EXE
 - Postman Version: 7.14.0
 - OS: Windows 10
 - RAM: 20GB

**Comment by kamalaknn** [comment]
Hey @adikhel 

Could you send us the logs so we can take a closer look at what's going on here? You can find the logs by following the `View -> Developer -> View logs in Finder` menu option.

**Comment by kamalaknn** [comment]
Hey @adikhel

I'm closing this issue due to lack of response. Please provide us more information if you are still seeing this issue.

**Comment by collinsuzebu** [comment]
I have same problem...

**Comment by WafflesMcDuff** [comment]
Me too

**Comment by franco9700** [comment]
Me too. The old version of postman do not cause this problem for me but it is not as good as the new version.

**Comment by KimzInc** [comment]
For me, everything stops and the only solution is to forcefully restart my PC, I am using Linux OS, Ubuntu
