### ISSUE TITLE
Collection Runner - Request titles overlap each other if they are collapsed and re-ran

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#7997]
Here's a video, take a look at the first and second request titles when they are re-ran:
https://www.loom.com/share/379615fab5c14f6b90e3b4ccd9893f7d

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a collection that contains 2 requests
2. Make sure the first collection contains no tests
3. Run the collection via the Collection Runner
4. Upon completion, collapse the first request
5. Click Retry
6. Observe the titles of the first two requests

**Expected behaviour**
- I would expect the collapse state to be remembered when I click Retry or the collapse state is forgotten and all requests are open

**Screenshots**
![image](https://user-images.githubusercontent.com/9334128/73859077-639c3380-4831-11ea-9008-70f10c630639.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.17.0
 - OS: Mac OS Catalina 10.15.3

**Comment by appurva21** [comment]
Hi @Faz540, thanks for reporting the issue.
We're able to reproduce this on our end and are fixing this ASAP.

**Comment by arlemi** [comment]
A fix was released in the latest version of the app (7.19.1). :)
