### ISSUE TITLE
fails to import this SDL

### ISSUE THREAD

**Issue by adamblum** [a85/POSTMan-Chrome-Extension#7998]
**Describe the bug**
attempting to import this bug generates error: "expected 'r' instead of 'y'"

**To Reproduce**
- create New API
- Import File
Use attached file
**Expected behavior**
Imports schema

**Comment by adamblum** [comment]
won't let me attach the SDL file. so here it is inline:

type AuthPayload {
  id: Int!
  email: String!
  roles: String!
}

type Doc {
  id: Int!
  title: String!
  org: Org
  uri: String!
  identifier: String!
  officialUri: String!
  creator: String!
  publisher: String!
  version: String!
  description: String!
  language: String!
  adoptionStatus: String!
  frameworktype: FrameworkType
  note: String!
  items: [Item]
}

type FrameworkType {
  id: Int!
  frameworkType: String!
  docs: [Doc]
}

type Item {
  id: Int!
  doc: Doc
  uri: String!
  identifier: String!
  fullStatement: String!
  abbreviatedStatement: String!
  conceptKeywords: String!
  language: String!
  notes: String!
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  signup(signUpInput: SignUpInput): AuthPayload!
  login(loginInput: LoginInput): AuthPayload!
}

type Org {
  id: Int!
  name: String
  users: [User]
}

type Query {
  docs: [Doc]
  doc: Doc
  items: [Item]
  org: Org
  users: [User]
  user: User
}

input SignUpInput {
  email: String!
  password: String!
}

type User {
  id: Int!
  username: String
  org: Org
}

**Comment by vvs11** [comment]
Hi @adamblum could you share some more details with us? Your OS version, app version and if possible a video of this?

**Comment by umeshp7** [comment]
@adamblum 
The GraphQL SDL provided by you is successfully imported in the recent version of Postman App (7.25.0). #8429 
Could you please verify it and let us know if you are still facing any issues?

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved in version: 7.25.0

Please feel free to reopen with the steps to reproduce if the issue persists.
