### ISSUE TITLE
Variable's Current Value syncing to Initial value 

### ISSUE THREAD

**Issue by aengusbates** [a85/POSTMan-Chrome-Extension#8001]
**Describe the bug**
Postman is currently always syncing a variable's Current Value back to Initial Value on each request where any variable is updated when a test is run. 

This is a problem because Postman includes Initial Value when exporting a collection, but not Current Value. Postman also syncs Initial Value to the cloud, but not Current Value. 

**To Reproduce**
1. Create Collection
2. Set 2 valuables on collection: "foo" and "bar". Leave Initial values for both variables blank. Set current values to "foo":"123" and "bar"":"456".
3. Add request. The endpoint does not matter.
4. Add the following line to the "test" that is run after the request.
`pm.collectionVariables.set("foo", "789");`
5. Run request.
6. Edit collection to view variables.

**Expected behaviour**
Initial Value for "Bar" variable should be blank.

**Actual behaviour**
Initial Value for "Bar" has been set to "456", its Current Value.

**Screenshots**
NA

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.16.1 (7.16.1)
 - OS: macOS Catalina 10.15.3

**Additional context**

**Comment by aengusbates** [comment]
[Leaking Variables Test.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/4162022/Leaking.Variables.Test.postman_collection.json.zip)

**Comment by matt-ball** [comment]
This is intended behavior - setting "Automatically persist variable values" to "Off" in the general preferences will prevent the syncing between the two values. 

Being able to control this setting at a team level is a feature request I'd pull from this context.

https://github.com/postmanlabs/postman-app-support/issues/6852

**Comment by aengusbates** [comment]
Thanks Matt, 

Defaulting this setting to off seems like the most intuitive and most secure behaviour.  I see a comment on #6852 mentioning that that's already the plan.  

Closing ticket.
