### ISSUE TITLE
 v7.18.0-canary01 not opening new tabs automatically

### ISSUE THREAD

**Issue by MichalTaratuta** [a85/POSTMan-Chrome-Extension#8003]
**Describe the bug**
It seems that canary version does not open new tabs automatically when clicking on a saved request from a collection. Postman used to automatically open new tab whenever I would click on different saved request in collections.

**To Reproduce**

0.  Start Postman with 0 tabs
1. Go to a collection and click on any saved request.
2. Click on another saved request
3. Bug: Postman will change the only open tab for the last saved request from the step 2

Alternatively:

0.  Start Postman with 0 tabs
1. Go to a collection and click on any saved request.
2. Right click on another saved request chose "Open in new tab"
3. Click on another saved request (2 are already opened) 
4. Bug: Postman will change the latest open tab for the saved request from the step 2 to a tab for request from step 3
 

**Expected behavior**
Fore every new saved request from collection a new tab should have been opened

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version  v7.18.0-canary01
 - OS: WinShit 10 Enterprise

**Additional context**
I hope this is not a feature

**Comment by appurva21** [comment]
Hey @MichalTaratuta,
The behavior which you are looking for can be enabled by the following steps:
1. Go to App Settings
![image](https://user-images.githubusercontent.com/24985700/73934453-7fbcd500-4904-11ea-992d-6e00d82dcb26.png)
2. Under `General` tab, look for a setting named `Always open requests in new tab` and enable that setting.
![image](https://user-images.githubusercontent.com/24985700/73934600-ca3e5180-4904-11ea-9ac3-dca7e9f3380b.png)

To get more insights about Tabs in Postman please go through the following link: https://learning.postman.com/docs/postman/sending-api-requests/working-with-tabs/#types-of-tabs

**Comment by MichalTaratuta** [comment]
@appurva21 Thanks, I was not aware of this setting

**Comment by walker-ken** [comment]
Regardless of this setting, should right-clicking on a saved request and selecting "Open in new tab" not open the request in a new tab?
