### ISSUE TITLE
Show a bread crums path to current open request

### ISSUE THREAD

**Issue by HenrikHolmIT** [a85/POSTMan-Chrome-Extension#8006]
Projects grow large and sometimes you can loose overview.

We have large Collections with many Requests and sometimes we open multiple Requests from different Collections.

Please add a bread crumb path somewhere in a request so its easier to know where it actually belongs.

**Comment by HenrikHolmIT** [comment]
For clarity here is a wiki that explains what bread crumbs are: https://en.wikipedia.org/wiki/Breadcrumb_navigation

How this could be implemented with the Request Name control.
In our example we have Collections like 'API v1' and 'API v2'. Under those there are folders and then Requests. So bread crumbing would look something like this

 API v1 > Foldername > RequestName

Clicking it would still just function as renaming the request but when not renaming it would show the above bread crumb text.

**Comment by vkaegis** [comment]
@HenrikHolmIT Thanks for writing in! Totally understand the need, this is something we've been prototyping internally for a while. No ETA on this just yet, but we'll keep you updated.

**Comment by DannyDainton** [comment]
Hey @HenrikHolmIT

This is now a feature within the V8 app, I'm going to close this issue out.
