### ISSUE TITLE
Import cURL with x-www-form-urlencoded

### ISSUE THREAD

**Issue by mandaputtra** [a85/POSTMan-Chrome-Extension#8007]
**Is your feature request related to a problem? Please describe.**
I had a problem importing form cURL, when you had your form data as `x-form-url-encoded` why it can't parse the Form Data?

This following cURL can't be importedinto postman, it parse the header but not the body.

```
curl 'https://website.com/api' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Accept: application/json, text/plain, */*' -H 'Sec-Fetch-Dest: empty' -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9pcmlzLmxvY2FsL2FwaS9hZG1pbi9sb2dpbiIsImlhdCI6MTU2ODIwMjU3OSwiZXhwIjoxNTY4MjA2MTc5LCJuYmYiOjE1NjgyMDI1NzksImp0aSI6IkphUXk1cTFSa0NMeXJyam4ifQ.OoTNsJmqweqweqwsadasdqwe1239TRevZHuw1kC6QpWdth0pN2A' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36' -H 'DNT: 1' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryRQ0NDimFIJ05dYrn' -H 'Origin: https://iris-fe.otesuto.com' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://iris-fe.otesuto.com/job/6' -H 'Accept-Language: en-US,en;q=0.9,id;q=0.8' --data-binary $'------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="remarks"\r\n\r\nHEllo\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="user_id"\r\n\r\n1\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="asign_id"\r\n\r\n1\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="status"\r\n\r\nOngoing\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="update_action"\r\n\r\nstatus\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="gps_coordinate"\r\n\r\nnull\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn\r\nContent-Disposition: form-data; name="picture_before"; filename="Screenshot from 2020-01-31 18-28-13.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundaryRQ0NDimFIJ05dYrn--\r\n' --compressed
```

**Describe the solution you'd like**

I want postman to also parse the body, like the chrome does, the image / file (the binary part) aren't necessary but the field is must.

**Describe alternatives you've considered**

I have no clue on how this feature could be implemented, but seing how the Chrome Dev tools do it maybe they had some regex.

**Additional context**

No.

**Comment by jonnytest1** [comment]
same - I mainly want to do 'copy as cURL' in the chrome dev tools and import that in postman , However the Formdata doesnt get parsed into the FormData field 

How about doing automatic conversion from FormData to raw and backwards on tab switch if possible

**Comment by mandaputtra** [comment]
I believe because there are no `-F` flag so the programs could not run it see [here](https://github.com/Kong/insomnia/issues/457)

**Comment by jonnytest1** [comment]
looks like Id have to add one -F per form Param ; would probably be easier to just create the request manually then

**Comment by mandaputtra** [comment]
@jonnytest1 if the chrome copy does curl like that so postman must behave like that too, whether using -F or not. When chrome / firefox implements it, so it will be nice if postman also can parse that

**Comment by shpodg** [comment]
I have the same problem, what is the progress now?

**Comment by VShingala** [comment]
This was fixed as part of already present issue: https://github.com/postmanlabs/postman-app-support/issues/7895#issuecomment-833232087

@shpodg Could you share `cURL` which is not getting imported correctly? We can take a detailed look if it's something specific.

Mentioned cURL on the top comment is now imported correctly. Below is example on the latest Postman App.


https://github.com/postmanlabs/postman-app-support/assets/16756296/87e5e829-a5b8-40a1-ac20-b6ebe75036bc

**Comment by VShingala** [comment]
Closing this as it has been fixed already. Feel free to reopen or add comment if there's further issue.

**Comment by mdestafadilah** [comment]
its now problem. 

> https://www.postman.com/satusehat/satusehat-public/overview

from postman it's success full. with failed with insomnia. :(
