### ISSUE TITLE
Importing a OpenApi 3.0 JSON with a multipart request inside via the Import External API Spec API does not generate a valid Postman collection schema.

### ISSUE THREAD

**Issue by akaczinski** [a85/POSTMan-Chrome-Extension#8008]
**Describe the bug**
After I import an OpenApi 3.0 JSON spec which contains a multipart request via the /import/openapi endpoint, and then export it out to the Postman Collection 2.1.0 JSON schema, the request's body in the export I receive looks like this:
`"body": {"mode": "formdata","formdata": [{"key": "file","value": "<binary>"}]`

If I attempt to re-import the file into Postman directly from the UI, it works fine. However, if I attempt to import via the Collection endpoint, I receive the following errors:
`"Found 7 errors with the supplied collection.\nshould match exactly one schema in oneOf\nshould be null\nshould match exactly one schema in oneOf\nshould be string\nshould match exactly one schema in oneOf\nshould have required property 'item'\nshould match exactly one schema in oneOf"`

This is because, after importing the OpenApi JSON spec, it does not set a "type": "file" in the formdata body which violates the Postman Collection schema v2.1.0.

**To Reproduce**
1. Import an OpenApi 3.0 request to the Import External API Spec to /import/openapi which has a multipart request in it which looks similar to the one I listed above
2. Export the collection that's generated
3. Re-import the collection via the Postman Collection POST endpoint

**Expected behavior**
After importing OpenApi 3.0 into the import external API spec, the "type" value is automatically assigned to "file".

**App information (please complete the following information):**
 - Postman v7.17.0 Windows 10

**Additional Info:**
The OpenApi 3.0 schema I imported into Postman looks like this in the requestbody:
`"requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "description": "file",
                                        "type": "string",
                                        "format": "binary"
                                    }
                                },
                                "required": [
                                    "file"
                                ]
                            }
                        }
                    }
                }`

An example of the exported collection from Postman:
`{
	"info": {
		"_postman_id": "73dc186a-7829-4013-a6c2-9f29941c950d",
		"name": "temp",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "requestMediaUpload3",
			"request": {
				"auth": {
					"type": "noauth"
				},
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"value": "multipart/form-data"
					}
				],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "file",
							"value": "<binary>"
						}
					]
				},
				"url": {
					"raw": "{{baseUrl}}/api/device",
					"host": [
						"{{baseUrl}}"
					],
					"path": [
						"api",
						"device"
					]
				}
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}`

**Comment by Mechanicalkeyboard** [comment]
I was unable to reproduce this issue using the example provided. 
If you have a scrubbed OpenApi 3.0 spec that you can provide that exhibits this behaviour, please reopen and let me know!
