### ISSUE TITLE
I cannot purchase monthly, the button is greyed out

### ISSUE THREAD

**Issue by tsheaff** [a85/POSTMan-Chrome-Extension#8009]
**Describe the bug**
When I try to add a seat, only the Annual button is clickable

**To Reproduce**
1. Go to https://calmdotcom.postman.co/billing/plans/change

**Expected behavior**
I can purchase monthly

**Screenshots**
![image](https://user-images.githubusercontent.com/1238684/73997856-9d923600-4914-11ea-87cb-ffd3b6d2793c.png)
![image](https://user-images.githubusercontent.com/1238684/73997883-b26ec980-4914-11ea-8565-cef6d33d2cba.png)

**Comment by tithisharma98** [comment]
@tsheaff Request you to email at help@getpostman.com if you still need help with this issue. Thanks!

**Comment by DannyDainton** [comment]
Hey @tithisharma98 / @tsheaff Is this still an issue that you're facing? If not, could we close this out now?
