### ISSUE TITLE
Minimize,Maximize and Close Buttons Lack

### ISSUE THREAD

**Issue by richemmanu** [a85/POSTMan-Chrome-Extension#8011]
Postman has lost maximize,minimize,close buttons on windows 10 latest build.
![Image_Post](https://user-images.githubusercontent.com/16068642/74016722-f8bf3980-49a3-11ea-8591-652174bd12e9.PNG)

**Comment by kamalaknn** [comment]
@richemmanu It is possible that your app is in fullscreen mode. You can try F11 key to get out of the fullscreen mode. 

We are tracking a separate issue [here](https://github.com/postmanlabs/postman-app-support/issues/6811) to display some form of feedback that the app is currently in fullscreen.

I'm closing this issue now. Feel free to let us know if you're still seeing this issue.
