### ISSUE TITLE
Duplicating a Collection twice will give it existing name

### ISSUE THREAD

**Issue by HenrikHolmIT** [a85/POSTMan-Chrome-Extension#8012]
**Describe the bug**
We have a 'Template' Collection that we use to make new collections from. It has default configuration of Description, Authorization, Pre-request Scripts, Tests and Variables.

If we copy this Collection Twice without renaming it we get 2 Collections named 'Template Copy'

**To Reproduce**
Duplicate a given Collection twice without renaming between duplication.

**Expected behavior**
Duplicate should be named incrementally if name already exists. First one 'Collectionname Copy'. Second 'Collectionname Copy 1', Third one 'Collectionname Copy 2'
If copy 1 i renamed then a new duplicate should be called 'Collectionname Copy 1' because that is the first available name.

**Screenshots**
No need for screenshots

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.17
 - OS: Windows 10 Pro Build 1909

**Additional context**
No additional context to give

**Comment by mccannt** [comment]
Resolved in v7.29.0
