### ISSUE TITLE
Publish collection API

### ISSUE THREAD

**Issue by cbetta** [a85/POSTMan-Chrome-Extension#8019]
## Background 

We can currently upload a new Postman collection through the API, yet we can't make our entire process automatic as we can't update the shared link for the published collection to point to the latest version of the collection.

## Request

We'd really love to either see the **Update collection** API updated with a way to pass along a param to tell it to also update the published link for the collection, or alternatively we'd like to see a new API to trigger an update of the link.

**Comment by bzmw** [comment]
This is also something that I would like to see, it's the only thing in my CI pipeline for my API schema that is not automated.

**Comment by JoseHervas** [comment]
Same thing here. I'm trying to publish my collections on my CI pipeline. Any workaround to do this?

**Comment by cbetta** [comment]
Really dissapointed this hasn't been made an API yet. It seems like the desktop app has the ability so clearly an API does exist.

**Comment by Raja-Simha** [comment]
Duplicate of #7833

**Comment by cbetta** [comment]
@Raja-Simha how exactly is this a duplicate of #7833?

**Comment by jaredtbates** [comment]
Hey @Raja-Simha, we are looking for a feature like this - our CI manages the whole OpenAPI/Postman lifecycle and the only manual step in this process is publishing from the Postman desktop client.
