### ISSUE TITLE
macos command+tab workding incorrectly when switch between postman window and other app window 

### ISSUE THREAD

**Issue by AL-Liang** [a85/POSTMan-Chrome-Extension#8023]
OS：macos 10.15.2
postman version：Postman for Mac Version 7.16.1  OS X 19.2.0 / x64

describe bug: 

Sometimes, command+tab workding incoorectly when switch between postman window and other app window, it will juts switch to destop instead of postman window.

How To Reproduce:
use command+tab to switch between postman window and other app window serveral times (maybe in 10 times), it will juts switch to desktop instead of postman window. It is bothering users.

At first, I thought it is a macos bug. Then I found out it happens only when I switch between the postman window and other app window(such as chrome or Intellj IDEA).

Expected behavior
Users can always use command+tab shortcut to switch to postman window when they choose the postman window.

BTW, I hope I can upload a screen recording file to show it clearly.

**Comment by ghost** [comment]
@AL-Liang  Thanks for reporting this. Can you upload a screen recording for this ?

**Comment by AL-Liang** [comment]
> @AL-Liang Thanks for reporting this. Can you upload a screen recording for this ?

Thanks. It bothered me a few days. However, I can not reproduce it today. I will just close this issue. Maybe I missed some triger conditions. I will upload a screen recoding if I encounter this problem again.
