### ISSUE TITLE
CSV parser works differently for newman and collection runner

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#8024]
**Describe the bug**

CSV parsing of, CSV files that contain double quotes works differently in newman and collection runner.

for passing double quotes in csv data the approach is :

"""test""" which will be resolved to "test" in the request (Collection runner)
"\"test\"" which will be resolved to "test" in the request (newman) 

**To Reproduce**

1) Create a post request to "https://reqres.in/api/users"
2) Set the request body as  : 

```
{
    "name": {{user}},
    "job": {{pass}}
}
```
3) Create two CSV files:

1.csv:

```
user,pass
"""something""","""something"""
```

2.csv:

```
user,pass
"\"something\"","\"something\""
```

4) Run the collection using both the CSVs and observe the behavior in newman and postman collection runner

**Expected behavior**

Both collection runner and newman should have same behavior as collection runner is used to test data-driven testing before running it from cmd.

**Comment by codenirvana** [comment]
@praveendvd This is fixed in Newman v5.
Check the Newman [v4 to v5 migration guide](https://github.com/postmanlabs/newman/blob/develop/MIGRATION.md#migrating-from-v4-to-v5) and [changelog](https://github.com/postmanlabs/newman/blob/v5.0.0/CHANGELOG.yaml#L1) for more details.
