### ISSUE TITLE
Feature request: ZIP download option

### ISSUE THREAD

**Issue by himanshuPandey25** [a85/POSTMan-Chrome-Extension#8026]
**Is your feature request related to a problem? Please describe.**
As you know in many environments developer may not have access to install an application or installation required to get approvals at many levels.

**Describe the solution you'd like**
To prevent all this can you provide a ZIP archive download option. It will be of great use to many of us.

**Describe alternatives you've considered**
Anything that does not requires a installation.

**Comment by kamalaknn** [comment]
Hi @himanshuPandey25 

Can you give us some more details about your workflow? And what operating system are you on? If I'm right you are referring to the download option for the latest version and not asking for downloads on older versions?

**Comment by harryi3t** [comment]
@himanshuPandey25 Are you referring to the portal executables that do not require installation or admin privileges?

**Comment by himanshuPandey25** [comment]
@kamalaknn I am using Windows server 2012 or later. We work on different landscapes where we might not have the admin previlages to install postman.
@harryi3t yes I am asking for executables which don't require installation.
This option is not available right now at your download page.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/3884
