### ISSUE TITLE
Collection Runner Collection Fork Label disappears/is missing

### ISSUE THREAD

**Issue by Wotuu** [a85/POSTMan-Chrome-Extension#8027]
**Is your feature request related to a problem? Please describe.**
With the resolving of https://github.com/postmanlabs/postman-app-support/issues/6540 we're now running into a (minor) different issue. When running a forked Collection in the Collection Runner you can not see which fork you're actually running. What we used to do is attach an issue number in the Collection's name, but this is no longer necessary with the resolution of the above issue. Now all names are the same and we cannot see which branch we're running.

Small snippet of my main Postman window showing forked Collections:
![image](https://user-images.githubusercontent.com/811809/74140900-3d421380-4bf6-11ea-91be-243eb9695a2f.png)

Collection Runner (does not show fork label):
![image](https://user-images.githubusercontent.com/811809/74140987-6662a400-4bf6-11ea-915c-d65ac58a943a.png)

Am I running the fork for ONE-1892 or ONE-1897?

When starting the Collection Runner manually (not directly from a Collection) it DOES briefly show the fork label, but it disappears when you select a Collection:

![xvbITf8JDM](https://user-images.githubusercontent.com/811809/74141735-c73eac00-4bf7-11ea-870d-a5d2c00fc071.gif)

**Describe the solution you'd like**
I'd like to have the fork label to be included in various places in the Collection Runner. Current: `One API Endpoints Tests Base`, new: `One API Endpoints Tests Base <fork label>`

This change needs to be done in multiple places.

* Main Collection Runner window prior to running a Collection (see above screenshot)
* When running the actual collection at the top
* Collection Runner Recent Runs

**Describe alternatives you've considered**
It's not such a big problem that an alternative is required. The Collection Runner still works, it's just nice to be able to see exactly what you're going to run instead of having to restart the Collection Runner to be sure.

**Additional context**
Not applicable, if any other information is required I'd be happy to supply it.

**Comment by appurva21** [comment]
@Wotuu Thanks for reporting this. We will take a look at it during our next round of improvements in the Collection Runner.

**Comment by Wotuu** [comment]
One other thing I noticed, in the Notifications area of Postman it doesn't show the branch info either:
![image](https://user-images.githubusercontent.com/811809/76087228-06250f00-5fb6-11ea-8b59-0c99b9992d46.png)

**Comment by arlemi** [comment]
Hey @Wotuu! 

We've added both of these in 7.21.0, hope this helps with your request! 

![Screenshot 2020-03-24 at 15 48 59](https://user-images.githubusercontent.com/5029719/77447141-39a1cf00-6de7-11ea-8b1d-bc6848e58087.png)
![Screenshot 2020-03-24 at 15 49 59](https://user-images.githubusercontent.com/5029719/77447147-3c042900-6de7-11ea-913a-8febfd3ba548.png)
