### ISSUE TITLE
Broken/clumsy UI in "Two pane view" when form-data has multiple key/value pairs

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#8029]
**Describe the bug**

When a `form-data` with multiple key/value pairs is viewed in "Two pane view" mode, the UI becomes clumsy and difficult to navigate. 

**To Reproduce**
1. Create a new request
2. Navigate to the `body` tab  and select `form-data`
3. Add about 50 dummy keys and their corresponding values
4. View this window in "Two pane view" by navigating to the icon at the bottom right

**Expected behavior**
The UI should be easy to navigate when viewed in "Two pane view"  mode. 

**Screenshots**

**Single pane view**
![image](https://user-images.githubusercontent.com/10200603/74153072-02e57000-4c10-11ea-8c16-8fabbb4543b1.png)

**Two pane view**
![image](https://user-images.githubusercontent.com/10200603/74152902-979b9e00-4c0f-11ea-8716-794e72fd3b01.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.17

**Additional context**

 See [video](https://www.loom.com/share/05cc9ce2231c4e32b02cf0ea867e798c)

**Comment by kamalaknn** [comment]
Hi @labifrancis 

Thanks for the report and the screen recording. We were able to reproduce this issue.
