### ISSUE TITLE
folder and multi-select drag and drop

### ISSUE THREAD

**Issue by barelnir** [a85/POSTMan-Chrome-Extension#803]
Hi,

we are using postman collections to publish our APIs.
because we work in a team many times we develop new APIs but in the meanwhile the published collection is updated therefore we need to do:
1. import the newer collection
2. create the folder ( can't drag and drop folders )
3. drag and drop each API item.

we really like to have folder and multi-select drag and drop option.
and also i think that the drag and drop is a bit problematic and doesn't follow the mouse all the time.
need to shake the mouse until it mark the right folder

**Comment by eappell** [comment]
+1 - I have a large collection of services from my last job (within the same organization).  I don't need them all as often now, so would like to move them to an "archive" folder, but it's not possible to drag and drop folders into other folders.  So I'm having to re-create every folder and drag all of the service calls into the new folders under the archive folder.  This enhancement would make life much easier!

**Comment by kajo123** [comment]
+1 here too. Would really help with organising large numbers of tests/requests

**Comment by josephnoall** [comment]
+1

**Comment by ronaldsalas** [comment]
+1

**Comment by ambar-cloudcover** [comment]
+1 for multi-select drag and drop

**Comment by kachraf** [comment]
+1

**Comment by armandomejiam** [comment]
+1 totally

**Comment by ghost** [comment]
+1

**Comment by jadams74** [comment]
+1

**Comment by prashantbhate** [comment]
+1

Currently Its really hard to organise captured requests (50+) into collections/directories (once they are captured via postman proxy) as I need to move it one by one

**Comment by oliverm2112** [comment]
+1

**Comment by dzottola** [comment]
(人´口`)

**Comment by thetreythomas** [comment]
Another +1

**Comment by oliverm2112** [comment]
+1 Again - another update, another disappointment. Please stop adding new shit and fix this most basic of issues. How many more years do we have to wait for this? Too bad the source code isn't available or I'd do it myself. How much would it cost? Maybe we can crowd fund this feature.

**Comment by MilkBiscuit** [comment]
+1   OMG it has been 4 years.

**Comment by oliverm2112** [comment]
Looks like it's on the roadmap - be still my heart!

**Comment by bojasna** [comment]
Hey guys,
Any news if this is still on the roadmap, finished or otherwise?
Thanks

**Comment by Anonyma** [comment]
+1...

Edit: you can get around this by exporting collections as a JSON, modifying the structure from a text editor and reimporting them https://community.postman.com/t/is-it-possible-to-move-existing-collections-into-a-folder/7955/10
but it's still surprising that we have to juggle our way around a simple missing multi-select...

**Comment by giridharvc7** [comment]
This is now introduced in v9.22+ . Give it a spint and let us know what you think. 
Release [blog ](https://blog.postman.com/introducing-sidebar-bulk-actions/)

**Comment by oliverm2112** [comment]
FINALLY!!!!!!!!!!!!!!!!!!!!! Thank you - it works great!

**Comment by barelnir** [comment]
thanks @giridharvc7 for make dreams come true ;)
