### ISSUE TITLE
Can't access environment/Global variables from within a function defined in a Global variable 

### ISSUE THREAD

**Issue by LucasAstol** [a85/POSTMan-Chrome-Extension#8031]
**Describe the bug**
I had a declare a function in a Global variable so I can then reuse that piece of code without having to copy paste the chunk of code again and again. Thing is that when I invoke the function from within the Global variable I doesn't have access to any of the variables wheter they are enviromental or Global.

**To Reproduce**
1. Create a function into a variable(Pre-request Script tab)
```
postman.setGlobalVariable("myUtils", function myUtils() {
let utils = {};

utils.sum = function sum(){
    var myResult = pm.environment.get("num1")+pm.environment.get("num2");
    pm.environment.set("result", myResult);
};
return utils;
} + '; myUtils();'
); 
```

2. Call function in Tests tab
```
let utils = eval(globals.myUtils);
utils.sum();
console.log("Sum result: " + pm.environment.get("result"));
```

**Expected behavior**
Should return sum result

**App information (please complete the following information):**

 - Postman Version 7.16
 - windows

**Comment by coditva** [comment]
@LucasAstol I think there's some confusion here... In the `utils.sum` function, you're setting an environment variable but in the tests script you're logging the return value.


You can either add this in your pre-request script's `sum` function:
```javascript
let myResult = pm.environment.get("num1") + pm.environment.get("num2");
return myResult;
```

Or, in the tests script, you can do this:
```javascript
let utils = eval(pm.globals.get('myUtils'));
utils.sum();

let var1 = pm.environment.get('result');
console.log(var1);
```

Hope that helps. If this solves your problem, feel free to close the issue. :)

**Comment by LucasAstol** [comment]
You are right @coditva sorry about that, I made a mistake when copy pasting. Now I have updated the comment meaning having a void function wouldn't be able to access the environment variable. Thing is I was calling the function incorrectly.

Apologize. I believe this can be closed.
