### ISSUE TITLE
Interceptor filter in Chrome isn't applied

### ISSUE THREAD

**Issue by arlemi** [a85/POSTMan-Chrome-Extension#8033]
Reported by a user on Twitter: https://twitter.com/jdgregson/status/1226925004803039234

**Describe the bug**
When setting a filter on the interceptor it is applied in the Chrome extension but not in the Postman app.

**To Reproduce**
1. Set a filter for the interceptor in the chrome extension
2. See that the history in the Postman app still shows all requests

**Expected behavior**
Filter should be applied in the Postman app too.

**Screenshots**
![interceptorfilter](https://user-images.githubusercontent.com/5029719/74177040-d5f58500-4c30-11ea-8f6d-c966b864b343.gif)

**App information (please complete the following information):**
 - Native app
 - Version 7.18.0 (7.18.0)
 - macOS Catalina 10.15.1
- Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Interceptor version 0.2.28

**Additional context**
When the filter is set in the Postman app it works normally.

**Comment by saialekhya-postman** [comment]
@arlemi This is not a bug.
Interceptor extension UI is only for the chrome app, filters the user adds and toggle switch state from the interceptor extension will be respected by the chrome app, not the native app.

We are working on the `Interceptor extension` redesign, once that is out users can apply filters separately for the chrome app and native app by switching Interceptor extension mode.
