### ISSUE TITLE
Removing a user from a team does not delegate access to their mocks servers

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#8035]
**Describe the bug**
A user was removed from a team since they were no longer part of the organization. This caused issues with access to Public Mock Servers created by the user. Resulting in the following error being thrown when trying to access the Mock server:
` {"error":{"name":"syncError","header":"You need access","message":"To view or edit the mock server, request access from the collection editor."}}`

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a user create a Collection and a Mock server within a Team Workspace
2. Have an Admin user remove the user from step 1 _*_
3. Workspace members can no longer access the Mock server

\* _If the user leaves the team by themself the issue does not occur!_

**Expected behaviour**
When an admin removes a user from a Team workspace, access to Mock servers created should be delegated to workspace members.

**Available Workarounds**
- Forking the Collection and creating a new Mock Server, then replacing the reference to old Mock's URL with the new one will help.
- Re-adding the removed user also helps but may not be feasible for everyone.

**App information (please complete the following information):**
- Tested via Postman Native app 7.17.0 
- OS: Any

**Additional context**
Logged by Postman retroactively for a user report resulting in the discovery of this bug

**Comment by mccannt** [comment]
@xk0der This issue should now be resolved. Can you confirm?

**Comment by xk0der** [comment]
Thanks, @mccannt! This has been resolved, hence closing this issue.
