### ISSUE TITLE
Current plan not reflecting properly

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#8037]
**Describe the bug**
I am currently subscribed to business plan and after navigating the `/usage` page link below, it shows that I am on enterprise plan instead of a business plan.
https://go.postman.co/usage 
![image](https://user-images.githubusercontent.com/52168965/74212342-c1110400-4cb9-11ea-9ae5-e0278cea570b.png)

And when I navigate the below link for `billing/overview` page from the same account, it shows I am on Business annual which is the correct one. 
https://go.postman.co/billing/overview 
![image](https://user-images.githubusercontent.com/52168965/74212352-cec68980-4cb9-11ea-934e-1ce0e0c47ca4.png)

**Expected behavior**
It should show the actual subscribed plan on the /usage page, as it is causing confusion for the users.

**Comment by DannyDainton** [comment]
Hey @Swapnil-getpostman 

Is this still an issue for you in the latest version?

**Comment by Swapnil-getpostman** [comment]
@DannyDainton it works as expected now.

**Comment by DannyDainton** [comment]
Thank you for confirming.

I'm going to close this one out. 🚀
