### ISSUE TITLE
Proxy crashes the native app if port is already in use

### ISSUE THREAD

**Issue by arlemi** [a85/POSTMan-Chrome-Extension#8039]
**Describe the bug**
If another app (other version of Postman, node server etc.) already uses the port set for the Postman Proxy, when turning the Proxy on the Postman app will crash.

**To Reproduce**
1. Open Postman Canary
2. Turn the Proxy on on port `5555`
3. Open Postman
4. Turn the Proxy on on port `5555`
5. Notice the app closing unexpectedly 

**Expected behavior**
The app shouldn't close but show a message saying the port is already in use.

**Screenshots**
![proxyportcrash](https://user-images.githubusercontent.com/5029719/74232242-4a2b3980-4cc0-11ea-83b6-e5edbba62695.gif)

**App information (please complete the following information):**
 - Native app
 - 7.18.0
 - macOS Catalina 10.15.1

**Additional context**

**Comment by chughmayank** [comment]
This is being tracked at #5905
