### ISSUE TITLE
Export collection generates empty collection v7.18.0

### ISSUE THREAD

**Issue by 802856294** [a85/POSTMan-Chrome-Extension#8044]
**Describe the bug**
Export Collection Results in skeleton empty requests. 

Windows 8.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to collection
2. Click on right-click and select export
3. Choose version 2.1
4. supply file name  and press save

**Expected behaviour**
Collection file should describe the collection

```
{
	"info": {
		"_postman_id": "7fb84e1f-61ac-4282-b467-ac69ded5517f",
		"name": "Creates a VirtualHub",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Retrieves the details of a VirtualWAN",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": ""
				}
			},
			"response": []
		},
		{
			"name": "Creates a VirtualHub ",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": ""
				}
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}

```

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by 802856294** [comment]
OS Windows 8.1
Post Man v7.18.0

Azure Rest API Call
PUT
https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Network/virtualWans/{{virtualWANName}}?api-version=2019-09-01

Header
Authorization
Bearer {{bearerToken}}
Content-Type
application/json

Body raw JSON
```
{ 
	"location": "{{location}}",
	"properties":
	{
		"allowBranchToBranchTraffic": "{{allowBranchToBranchTraffic}}"
	}	
	
}
```

**Comment by brunohadlich** [comment]
I'm facing the same issue with Postman for Mac - OS X 19.3.0 / x64, version 7.18.1.

**Comment by DannyDainton** [comment]
Hey @brunohadlich / @802856294 

Is this something that you're both still having issues within the latest version of the app.

**Comment by DannyDainton** [comment]
I'm going to close this issue but we can open this up again if this is still a problem that people are facing.
