### ISSUE TITLE
disable multiple selection

### ISSUE THREAD

**Issue by katlimruiz** [a85/POSTMan-Chrome-Extension#8048]
when you drag your mouse to select the text in the textbox, postman will "confuse" the drag, and apply it to the grid which makes it cumbersome to edit the grid (for example, params or body grid).

I bet other people find this annoying.

multiselection should be done in another way (perhaps using keyboard only, or with ctrl key pressed).

**Comment by kamalaknn** [comment]
Hey @katlimruiz 

Thanks for reporting this. We are tracking this issue in #5078.

I'm closing this as a duplicate. Please follow the original thread for updates.
