### ISSUE TITLE
Add hyperlink to comment notifications in postman app

### ISSUE THREAD

**Issue by spencerrichardhenry** [a85/POSTMan-Chrome-Extension#8052]
Email notifications of comments that mention you include a hyperlink to that request. App notifications give you the comment but don't tell you what request it's on.

App notifications should do something similar to emails.

Folder structure description could be an alternative to a hyperlink

![image](https://user-images.githubusercontent.com/46569542/74378862-ef6b0e00-4da3-11ea-9119-50e7c1a7d557.png)
Note the lack of context on these notifications as to which requests these comments are for

**Comment by sankalp0o** [comment]
Hi @spencerrichardhenry. If you've seen the comment notifications recently, they include a hyperlink to the exact request and the request opens directly in your app without redirecting you to the web view. I'm very curious if this has improved your experience of working with comments. If not, what's missing?

**Comment by spencerrichardhenry** [comment]
hey sankal, this is great to hear! Sadly I'm not using Postman actively anymore as I switched jobs so I can't give further comment on the issue.
