### ISSUE TITLE
Notifications should include the fork name

### ISSUE THREAD

**Issue by spencerrichardhenry** [a85/POSTMan-Chrome-Extension#8053]
Email/in-app notifications of comments that mention you include the name of the collection the comment is on. However, they don't tell you what fork of that collection the comment is in.

Notifications should include the fork name instead of just the collection name (i.e. Joe Smith replied to your comment on Public APIs [joe's branch] Collection

![image](https://user-images.githubusercontent.com/46569542/74378862-ef6b0e00-4da3-11ea-9119-50e7c1a7d557.png)
Note that I can't tell which of our 4 forks these two comment notifications are referring to.

**Comment by sankalp0o** [comment]
Hey @spencerrichardhenry , thanks for the suggestion! We are currently working on improving the commenting experience so this is very timely! I see you've posted a bunch of issues, is there anything else that we can improve for your team to collaborate better through comments? Happy to get on a call to discuss this as well.

**Comment by spencerrichardhenry** [comment]
I made issues for what I could remember as pain points -- the PR feature that was just released for web has addressed a lot of our other pain points. I will keep in touch though with future suggestions!

**Comment by spencerrichardhenry** [comment]
@sankalp0o I can't seem to tag you on this issue but I've created another feature request here: https://github.com/postmanlabs/postman-app-support/issues/8109
Happy to hop on a call to discuss this bit more as it isn't as cut and dry, and there are a few other UX things that I don't feel are worth writing tickets but might be worth mentioning.

**Comment by tithisharma98** [comment]
Hi @spencerrichardhenry , this is Tithi here from Postman product research. I would love to get on a call with you and understand your use cases around the issues which you are facing. Please feel free to book a slot as per your convenience using this link. Link - https://calendly.com/tithi-sharma/postman-user-research-interview . Please feel free to reach out to me if you have any queries. Looking forward to our call :) 

Email - tithi.sharma@postman.com

**Comment by ankitjaggi** [comment]
This has now been fixed in the latest version of the Postman App. Feel free to create a new issue if the problem persists.
