### ISSUE TITLE
Manage OAuth 2.0 tokens always shows error "Something Went Wrong" 

### ISSUE THREAD

**Issue by slkorolev** [a85/POSTMan-Chrome-Extension#8054]
**Describe the bug**
After update to 7.18.0 on macOS I am unable to manage OAuth 2.0 tokens: every time I click _Manage Tokens_ in the _Available Tokens_ listbox I receive a standard error message **Something Went Wrong**.

**To Reproduce**
1. Create an arbitrary request
2. Click on 'Authorization' tab below the request url
3. select OAuth 2.0 from TYPE listbox
4. Click on 'Available Tokens' listbox
5. Select 'Manage Tokens' from drop down list
6. See error dialog

**Expected behavior**
Normal 'Manage Tokens' dialog should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/7373931/74435461-65cb4700-4e5c-11ea-9530-2eee20bba540.png)

![image](https://user-images.githubusercontent.com/7373931/74435496-7a0f4400-4e5c-11ea-944a-b9bdf39d60f0.png)

**App information (please complete the following information):**
 - Node JS app
 - 7.18.0
 - OS: macOS Catalina 10.15.3

**Additional context**

**Comment by ribosome100110** [comment]
Having the exact same issue. When selecting Manage Tokens I get the "Something Went Wrong" screen. Using Postman app on Windows 10 x64

**Comment by slkorolev** [comment]
The error still persists in 7.18.1 on macOS

**Comment by ianrandell** [comment]
Yep just ran into same issue v7.19.1 on Windows 10 x64

**Comment by mrychlicka** [comment]
same problem in v7.18.0 release, Ubuntu18

**Comment by slkorolev** [comment]
Persists in 7.19.1, macOS Catalina

**Comment by ianrandell** [comment]
I can confirm that this error does NOT occur in v7.13 windows 10 x64.
I installed v7.13 from chocolatey package after uninstalling previous version and cleaning out traces of files from under c:\users\xxx folder.
I then used the same oauth creds to hit the same (faulty) endpoint.
Postman v7.13 nicely reports an error for the token.
![image](https://user-images.githubusercontent.com/19835651/75340179-e8ef9280-5889-11ea-8bba-363f2d7d4c64.png)

**Comment by Raj-postman** [comment]
Issue persists on the version- 7.19.1-windows-x64

**Comment by berend-de-jong** [comment]
For me it appeared while I had the Manage Tokens screen open normally and was in the process of deleting all tokens in the left sidebar. I might have clicked too fast and the Something Went Wrong message appeared. It now shows every time I try to open Manage Tokens, also after restarting Postman. It looks like the data in the account is corrupt?

Using macOS Catalina.

**Comment by slkorolev** [comment]
For now 7.13.0 works on Windows, just make sure you've switched off the automatic updates

**Comment by AntLaC** [comment]
> For now 7.13.0 works on Windows, just make sure you've switched off the automatic updates

right...so how do you propose those who already have the latest version do this?

This is actually a work stop for me as I'm trying to add a token

**Comment by slkorolev** [comment]
> right...so how do you propose those who already have the latest version do this?

Uninstall 7.19.1 and install [7.13.0](https://www.fosshub.com/Postman-old.html?dwl=Postman-win64-7.13.0-Setup.exe)

**Comment by vikiCoder** [comment]
Hi everyone,

We have fixed this issue with `Manage Tokens` dialog and the fix is out in the latest [Postman canary (7.21.0-canary01)](https://www.postman.com/downloads/canary). It will be fixed in the next version of the Postman app (v7.21) soon. Meanwhile, please check out the latest [Postman canary](https://www.postman.com/downloads/canary) and let us know if you are still facing the same issue in it.

**Comment by roberthtux** [comment]
same problem in v7.20.0 release, Ubuntu18

**Comment by MattMulhern** [comment]
same on osx `Version 7.20.1 (7.20.1)`

**Comment by vikiCoder** [comment]
The fix is out in the latest version of the Postman app (v7.21.0).
