### ISSUE TITLE
Keyboard shortcuts for changing tabs

### ISSUE THREAD

**Issue by nlwillia** [a85/POSTMan-Chrome-Extension#8055]
It would be helpful if the Windows Postman App had keyboard support for changing the current request tab.

ex: compare with browsers, spreadsheets, etc. where Ctrl-PageUp and Ctrl-PageDown (also frequently aliased as Ctrl-Tab and Ctrl-Shift-Tab) can be used to quickly navigate

This was [previously requested](#3280), but prematurely closed and never seems to have been properly considered.

In a highly-tabbed UI like Postman, there may be cases where the best choice for tab "focus" for keyboard controls might be ambiguous, but at least having Request tab support would be a big win for productivity when working with a few ad hoc requests that need to be swapped frequently.

**Comment by ankurdengla** [comment]
Hey @nlwillia !
We do have support for keyboard shortcuts to switch the current tab. This can be done using Ctrl-Tab and Ctrl-Shift-Tab on Windows. A few things that might help you resolve your issue - 
* Please try updating your app to the latest version. This can be downloaded from https://www.postman.com/downloads
* Make sure that Keyboard Shortcuts are not disabled in `Settings` - 
![Keyboard](https://user-images.githubusercontent.com/26045713/74504310-c8364d00-4f19-11ea-98e7-f880eddde91f.JPG)

Do let us know if this resolves your issue.

**Comment by nlwillia** [comment]
I don't normally use Ctrl-Tab and didn't think to try that.  Those shortcuts are working.

Is there any chance of Ctrl-PageUp and Ctrl-PageDown aliases?  Those seem to be the more widely used combination for tab switching--to the extent that I have the rocker on my mouse wheel bound to them...which works everywhere else but Postman.

**Comment by grinderX19** [comment]
> Is there any chance of Ctrl-PageUp and Ctrl-PageDown aliases?

Totally agreed, this would be very helpful and intuitive as most application use the same shortcuts.

**Comment by gthieme** [comment]
I really miss not having an alias for Ctrl+PageUp and Ctrl+PageDown. Those shortcuts works in so many other apps that I constantly get tripped up when it isn't supported in Postman.

**Comment by saurabhjayant** [comment]
Hey, @nlwillia . Thanks for all the great feedback! We've been playing around with an idea that might help alleviate some of the issues that you mentioned with the tabbed experience in Postman. In the web app, you can now go to your Settings page and toggle a no-tab state, which completely removes tabs from Postman. This will allow you to use Postman with browser tabs like any other browser-based application and not have a lot of conflicts when it comes to shortcuts and browser functionality. As a part of this, we've also enabled Open in New Tab actions on most navigational items, so while by default, all pages open in the same tab, you can always explicitly open new tabs when you want to see things side by side. It'd be great if you could try this out and let us know how this works for your use case.

P.S. We're also exploring improvements for the desktop application but will use this to validate some approaches before we go ahead and do that.

**Comment by nlwillia** [comment]
![image](https://user-images.githubusercontent.com/803755/183969571-333dc50b-dea8-4d21-add0-d4ab08d06418.png)

![image](https://user-images.githubusercontent.com/803755/183969935-36ce234b-5359-43e5-9436-ead7dcf5168a.png)

I haven't previously used the web version, but I see what you mean.  While it's nice to have the option, it's not a great analogue for the collected experience in the app and being able to navigate it flexibly without the clunkiness of full page loads.  The "new tab" interaction is also somewhat proprietary...browser users expect ctrl-click/middle-click/bookmark/etc. to work on things that are semantically links.

**Comment by saurabhjayant** [comment]
Thanks for the feedback @nlwillia. We are soon going to work on the desktop tab. We'll keep you posted on that.

**Comment by planetabhi** [comment]
@nlwillia We recently added the capability to [customize your keyboard shortcuts](https://blog.postman.com/postman-customizable-keyboard-shortcuts/). We do not plan to change the defaults, but you can personalize them to best suit your needs. Hope this helps.
