### ISSUE TITLE
Cookies not being added to request

### ISSUE THREAD

**Issue by lastbulletbender** [a85/POSTMan-Chrome-Extension#8057]
**Describe the bug**
Cookies are not being added to the request, even when set manually or through the interceptor.
**To Reproduce**
1. Go to Cookies tab
2. Add cookies manually
3. Send request/ Generate code
4. No cookie field used.

**Expected behavior**
The request should be sent along with the cookies. Generated code should have cookies field.

**Screenshots**
Screenshot 1 : Cookie added to request
Screenshot 2 : Generated Code

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 7.18.0
 - OS: macOS Catalina 10.15.1 (19B88)
<img width="720" alt="Screenshot 1" src="https://user-images.githubusercontent.com/18240346/74463116-54635880-4eb7-11ea-9020-0e5f491ea0d7.png">
<img width="526" alt="Screenshot 2" src="https://user-images.githubusercontent.com/18240346/74463125-56c5b280-4eb7-11ea-957e-2814d3db39fa.png">

**Comment by lastbulletbender** [comment]
Hopefully I am not making a stupid mistake 😅

**Comment by tyd** [comment]
I'm having the same issue when **Settings -> General -> New Code Generation Mode** is set to **On**... but turning that to **Off** does indeed start including cookies in the generated code. I'd much prefer this work with the setting **On** as the output is much cleaner.

**App information:**
- App Type : Native App
- Postman Version : 7.19.1
- OS: macOS Mojave 10.14.6 (18G1012)

**Comment by shreys7** [comment]
Hey @lastbulletbender @tyd , thanks for reporting this. We are already aware of this issue and working on the fix. We will update you here soon.

**Comment by lastbulletbender** [comment]
Thanks a lot :)

**Comment by zoek1** [comment]
@shreys7 could i take this? I recently send a PR to the code generators project so i think i can table this in short time

**Comment by shreys7** [comment]
@lastbulletbender @tyd With the latest Postman App, the cookie headers are being successfully added in the code snippets generated. Can you update your App to the latest version and verify the fix?
![image](https://user-images.githubusercontent.com/20665864/80944303-d738e700-8e06-11ea-8e7e-5dcca6307679.png)

**Comment by tyd** [comment]
@shreys7 I updated to 7.23.0 and I'm not seeing cookies added. Is 7.23.0 the correct version?

**Comment by lastbulletbender** [comment]
@tyd @shreys7 The cookies are being added on 7.23.0 for me.

**Comment by tyd** [comment]
> @tyd @shreys7 The cookies are being added on 7.23.0 for me.

I tested more and the cookies are added to requests that have the URL explicitly defined, but cookies aren't added for requests that use a var for the host url.

**Example with URL set (works):**
![image](https://user-images.githubusercontent.com/1465854/81000549-a905d800-8e03-11ea-9448-9b9f08f5a7c1.png)
![image](https://user-images.githubusercontent.com/1465854/81000557-ac995f00-8e03-11ea-823f-49c36a354b31.png)

**Example with URL as variable (does not work):**
![image](https://user-images.githubusercontent.com/1465854/81000741-f124fa80-8e03-11ea-82b8-9dab769fb7d1.png)
![image](https://user-images.githubusercontent.com/1465854/81000630-ccc91e00-8e03-11ea-97b4-79a909d34fea.png)
![image](https://user-images.githubusercontent.com/1465854/81000615-c5a21000-8e03-11ea-92e0-eca442a31470.png)
(Note: generated code has the var set correctly)

**Comment by arlemi** [comment]
@tyd We're tracking this in #8348. Closing this one as this has been resolved. 🙂

**Comment by muldon** [comment]
for me the cookies are not being added in both situations (using or not using variables). Currently using mac version 9.29.3

**Comment by jeremysf** [comment]
No cookies are being added for me, using mac version 9.31.8. I'm trying to do a POST request with a JSON body to a .ly domain. I have also tried the web app.

**Comment by energy2522** [comment]
I sent a request and cookies were added, but when I send another request with the same domain they are not added to request

**Comment by shubhbhargav** [comment]
@energy2522 @jeremysf @muldon Can you please share a screen recording of the issue to help us debug this further?

**Comment by energy2522** [comment]
https://user-images.githubusercontent.com/17969823/192588505-0b46e623-5f24-4bf9-96ec-f348fb9d558e.mov

let me know if you need more information

**Comment by shubhbhargav** [comment]
I see. This is related to the localhost domain not being supported at this moment for Cookies. We will share more updates for this on this ticket: https://github.com/postmanlabs/postman-app-support/issues/10185
