### ISSUE TITLE
Search field behaviour, highlighting results

### ISSUE THREAD

**Issue by Mahonnant** [a85/POSTMan-Chrome-Extension#8062]
**Is your feature request related to a problem? Please describe.**
Before v7.18.0 when I used the search field in Postman windows, only the results matching my input were displayed. This behaviour has changed in v7.18.0 and now it opens all folders in which a matching request can be found, all requests in the folders (matching and non matching my query) are displayed. It highlights matching elements in request name (font color changes to orange in dark theme).
The problem is I can have fairly long names for my requests and sometimes the highlighted matching element is not displayed in the pane because it is cropped.

**Describe the solution you'd like**
Either revert to previous behaviour (non-matching requests are not displayed) or highlights the matching requests differently (background color change ?) so I can find them more easily.

**Comment by SemyenSoldatenko** [comment]
I have the same issue.
When my search phrase exists in any request, it looks like ALL my requests match 😕 

Additionally search can not find any request by:
⤵️ by parameter name
⤵️ by parameter value
⤵️ by path fragment

**Comment by Mahonnant** [comment]
New behaviour reverted in v7.18.1 (bug #8045) ==> you can close this feature request
