### ISSUE TITLE
pm.request script to return a complete URL(string) 

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#8063]
**Is your feature request related to a problem? Please describe.**

When a user uses `pm.request.url`  to get the URL a request is being sent to, it returns an array with the different components of the URL

The result doesn't give a full string of the URL. The below result is returned:

![image](https://user-images.githubusercontent.com/10200603/74539050-a51d9480-4f3d-11ea-8b0e-379e60c321ac.png)

**Describe the solution you'd like**

pm.request script should surface a complete URL in string format 
 
**Describe alternatives you've considered**

A workaround that’s not necessarily a workaround would be to have them parameterize the request URL and just retrieve the variable to be printed.

**Comment by xk0der** [comment]
There is a documented way to fetch the request's URL within scripts using the `url` attribute of the  [pm.request](https://learning.postman.com/docs/postman/scripts/postman-sandbox-api-reference/#pmrequest) object.

_Example:_ 
    
    let currentUrl = pm.request.url.toString();

_References:_
* http://www.postmanlabs.com/postman-collection/Request.html
* http://www.postmanlabs.com/postman-collection/Url.html
