### ISSUE TITLE
Using the x-mock-match-request-headers will not return default response when header is not passed

### ISSUE THREAD

**Issue by jwbanning** [a85/POSTMan-Chrome-Extension#8065]
**Describe the bug**
While using a the x-mock-match-request-headers against my mock server, the default response is not returned when nothing is passed in the header.

**To Reproduce**
1. Set up a mock server with 3 examples. 
    a. Default example. Response should be 

```
{
	number:default
}

```
<img width="523" alt="default" src="https://user-images.githubusercontent.com/2584258/74553381-dd60ab00-4f1c-11ea-85f0-6d2789eb71e2.png">

    b. Example ONE.  key: values of number:one is set for the header. Response should be 

```
{
	number:one
}
```

<img width="637" alt="one" src="https://user-images.githubusercontent.com/2584258/74553336-c3bf6380-4f1c-11ea-8b13-d6ef7340c7bc.png">
   
 c. example named TWO when a key: values of number:two is set for the header. Response should be 

```
{
	number:two
}
```

<img width="592" alt="two" src="https://user-images.githubusercontent.com/2584258/74553354-ce79f880-4f1c-11ea-8ec1-b5760cfd9c99.png">

2. Send the request with the different header parameters: 
number: one | two  
x-mock-match-request-headers: number

<img width="656" alt="Screen Shot 2020-02-14 at 11 29 29 AM" src="https://user-images.githubusercontent.com/2584258/74553576-4e07c780-4f1d-11ea-9632-1369581b5386.png">
This works correctly.

3. Send the request without any header parameters 

<img width="656" alt="Screen Shot 2020-02-14 at 11 29 29 AM" src="https://user-images.githubusercontent.com/2584258/74553733-8effdc00-4f1d-11ea-9b91-0a567650648e.png">

and the response is the example when the header value is one: 

```
{
	number:one
}
```

**Expected behavior**
When nothing is passed in the header, the default response would return. 

I have made a couple videos that I can share to illustrate the issue.

**Comment by pranayat** [comment]
Hi,
When nothing is passed in the header then all 3 examples become equal candidates for a response and one of them is chosen.
This happens because when the `x-mock-match-request-headers` header is not sent (or no value is set therein), the headers set in the example requests are ignored.
Hence, the examples 'default', 'ONE' and 'TWO' are all treated equally (I'm assuming they all have the same path). In your case, example 'ONE' was chosen.
Do let me know if this cleared things up. If not, do share the videos you made.

**Comment by jwbanning** [comment]
meow.mov
<https://drive.google.com/file/d/1GgppFq_rFef_xy6nh0X_oUibDIM1JvTq/view?usp=drive_web>


I am still unsure. I would think when i do not pass anything in the header
the default example would hit.. See the movie

**Comment by pranayat** [comment]
All 3 examples are identical if their headers are ignored. The headers are ignored if the `x-mock-match-request-headers` header is not sent (or is empty). Hence any one of the 3 may be chosen (though the same one will be chosen every time). There is no construct of 'priority' or 'ordering' or 'default' among identical examples in Postman currently.
