### ISSUE TITLE
Request Token button - No UI feedback

### ISSUE THREAD

**Issue by thoffmann-fms** [a85/POSTMan-Chrome-Extension#8066]
**Is your feature request related to a problem? Please describe.**
The OAuth process can sometimes take more than a second or two so when clicking the "Request Token" button Postman just sits there with no obvious UI feedback that anything is happending.

**Describe the solution you'd like**
"Request Token" button should Disable itself and a spinner should display while waiting for the token response.

**Describe alternatives you've considered**
Bring up the Postman Console to watch what's happening but it does not update until the process succeeds for fails.

**Additional context**

**Comment by giridharvc7** [comment]
@timothyhoffmann Can you confirm if you still face this issue? 
When you request a "Generate New Access Token", you'll be shown this screen on the Postman app that lets you know that token generation is in progress. 
<img width="619" alt="Screenshot 2022-07-19 at 7 19 40 PM" src="https://user-images.githubusercontent.com/1040583/179767263-aa91fa52-3613-4f4e-8c3e-c8c0cc17b4ae.png">


Closing the ticket for now, feel free to reopen it if this doesn't solve for your use case

**Comment by thoffmann-fms** [comment]
Yes, thanks, feedback windows worked fine.
