### ISSUE TITLE
Manage Access Token screen, Use Token button hides

### ISSUE THREAD

**Issue by thoffmann-fms** [a85/POSTMan-Chrome-Extension#8067]
**Is your feature request related to a problem? Please describe.**
After requesting a new token the Manage Access Tokens screen is displayed with the the token.  However the default window size is such that the Use Token button is off-screen and one has to scroll down to click it.

**Describe the solution you'd like**
Move the Use Token button to the top of the screen or move Use Token to the list of token on the left where the Trashcan is.  It would useful to automatically display the Use Token icon without having to guess it's there by hovering over the token list they way the Trash icon is hidden.  Changing the size of the window may not always work depending on the size of the Access Token unless the token text displayed by default is truncated and a copy/view button added to get to the full token text.

**Describe alternatives you've considered**
Just scroll down each time.

**Additional context**
![image](https://user-images.githubusercontent.com/28546239/74555009-c7f17e00-4f28-11ea-865b-2bfb6ebe8167.png)

**Comment by arlemi** [comment]
We've moved the button at the top of the page to make sure no one's missing it in the latest version of the app (7.22). :)

**Comment by alanwill** [comment]
It looks like this might have broken the ability to right click on the token and add it to your environment variable 😢
