### ISSUE TITLE
Extra slash in the request path redirects with wrong request method

### ISSUE THREAD

**Issue by AndyJepkes** [a85/POSTMan-Chrome-Extension#8070]
**Describe the bug**
My request had an extra slash in it, which is quite easy to do when using variables for the host. It seems that postman attempted to "fix" this with a 301 redirect however the request method was not respected.

**To Reproduce**
1) Set up a variable such as: host = 'http://myhost.com/'
2) Create a patch request that would produce and extra '/' in the path: `[PATCH] {{host}}/api`
3) Click send
4) Observe in the postman console that the request has been redirected with the fixed path but the wrong method.

**Expected behavior**
Show an error or visibly indicate in the URL bar that there is a problem.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.18.0]
 - OS: [Windows 10]

**Comment by coditva** [comment]
Hey @AndyJepkes, Postman has a default behaviour of redirecting with the `GET` method. But you can always configure this at request level by setting the "Follow original HTTP Method" option:

![image](https://user-images.githubusercontent.com/8445768/76198683-85178300-6214-11ea-8dd5-b3aaf64c662f.png)
