### ISSUE TITLE
[Visualizer] CSS selector nth-child does not work as expected

### ISSUE THREAD

**Issue by Sawiq** [a85/POSTMan-Chrome-Extension#8074]
**Describe the bug**
While rendering a list in visualiser the css nth-child selector does not work. For example every row of a table is rendered as if it was the first row.

**To Reproduce**
1. Create a visualizer template similar to the below:
```
var template = `
<style>
tr:nth-child(even) {
    background-color: #CCC;
}
</style>

<table>
    <tr>
        <th>Field 1</th>
        <th>Field 2</th>
    </tr>
    
    {{#each response}}
    <tr>
        <td>{{field1}}</td>
        <td>{{field2}}</td>
    <tr>
    {{/each}}
</table>
`
if (pm.response.code == 200){
    pm.visualizer.set(template, {
        response: pm.response.json()
    });
}
```
2. Perform an API request resulting in an array, of objects containing fields *field1*, *field2*.

**Expected behaviour**
Table rows with alternating background colours.

**Current behaviour** 
All rows coloured as if there were the first row

**App information (please complete the following information):**
 - Postman v7.18.0 Native
 - OS: Linux Mint 19.3

**Comment by vikiCoder** [comment]
Hi @Sawiq,

It is because of the missing closing tag `</tr>` in your template. The line before `{{/each}}` in your template should be `</tr>` instead of `<tr>`. Then it will work as expected 🙂

I am closing the issue for now. Feel free to reopen if you face any other problem.
