### ISSUE TITLE
Willing to help students?

### ISSUE THREAD

**Issue by eupn11** [a85/POSTMan-Chrome-Extension#8080]
Hi guys!

I am part of a group of students, and for a certain course (digital innovation) we want to learn about how a github project is coordinated. We are looking for two contributors in this project, who want to help us out. We have some short questions. We are willing to contribute to this project as well, by for example testing out.

You can email me at eupn11@gmail.com

**Comment by sankalp0o** [comment]
Hey @eupn11, This issue tracker might not be the correct place for finding contributors. If you need help from the Postman community specifically, please post this at https://community.postman.com/. Best of luck!
