### ISSUE TITLE
Run result "environment not show correct environment"

### ISSUE THREAD

**Issue by ildemartinez** [a85/POSTMan-Chrome-Extension#8081]
**Describe the bug**
In the Run Results from Runner near the tittle of the collection showns the environment used..if you use one environment it show the correct name but if you press retry to run again the tests "No environment is shown"

**To Reproduce**
1. Go to Runner select a environment and run the tests'
2. The test runs and the Run results shows the correct environment used near the collection name
3. Press retry
4. Now the environment used changed to "No Environment"

**Expected behavior**
Any time you press retry in the Run Result should show the used environment

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![imagen](https://user-images.githubusercontent.com/1641352/74759904-d1a51980-5279-11ea-8893-077367a562fc.png)

![imagen](https://user-images.githubusercontent.com/1641352/74759943-e5e91680-5279-11ea-8855-709c10b1b044.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.18.1]
 - OS: [Windows 10]

**Additional context**

**Comment by appurva21** [comment]
Hi @ildemartinez , Thanks for reporting the issue. 
Can you please clarify what exactly the issue is. Is it about the correct environment name not being displayed or the environment not being actually used on retrying the run?

**Comment by ildemartinez** [comment]
Yes, is the environment name not being displayed correctly ... the environment used is the correct

**Comment by toneplex** [comment]
I've experienced this when pressing the 'retry' button. The environment is set correctly, but after clicking retry, the environment name gets changed to 'No Environment'.

**Comment by saswatds** [comment]
Hi everyone, we have fixed this issue on our end and it should be out in our next release of the app.

**Comment by ildemartinez** [comment]
Great!! close the issue

**Comment by arlemi** [comment]
Just to confirm, this was push with the 7.21.0 release!

**Comment by ildemartinez** [comment]
Yes...works fine!
