### ISSUE TITLE
Improve flow to unshare a collection

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#8083]
**Is your feature request related to a problem? Please describe.**
It is not so obvious that once a collection is shared, it becomes a team owned collection. 
Due to this behavior, deleting a collection from the team workspace deletes it as well from the personal workspace. 

It is not so intuitive to **find out how to unshare the collection**. For now, the solution to un-share a collection is to remove it from the team workspace. 

<img width="494" alt="Screen Shot 2020-02-19 at 14 50 22" src="https://user-images.githubusercontent.com/47351631/74845660-408c7c00-5327-11ea-92fa-6e4679c741ee.png">

**Describe the solution you'd like**
- Add a warning message before sharing the collection and tell the user how to un-share it. 
- Add some kind of messaging once the collection is shared such as: "you have just shared the collection "abc" with the team workspace "def", if you want to undo this action, click here..."

**Comment by sankalp0o** [comment]
@cyrielle-hada removing a collection should only remove it from that workspace. Are you able to reproduce this? 

We do not have plans to introduce an option to "Unshare" since the "Remove" does the same thing technically.

**Comment by cyrielle-hada** [comment]
@sankalp0o I think I have made a mistake in the description of the issue. I believe I meant: when you _delete_ the shared collection (i.e perform the action from the team workspace), it deletes the collection from the personal workspace as well.

**Comment by sankalp0o** [comment]
Yes, I get it now. But like I said though, "Remove" does the same action of removing it from just one workspace, hence adding an "Unshare" action doesn't make sense at this point. 

Is there any workflow that can't be achieved by "Remove"? Or is there something we're unable to communicate properly? 

Sharing a collection in a team workspace just shares it with everyone in the workspace. We don't have a strict concept for 'ownership'. It's true, the collection is considered a "Shared" collection but you get to give roles to other people in the team as you see fit.

**Comment by JaggedJax** [comment]
I no longer see any option to "Remove" or unshare a collection from a workspace. How can this be done now?

**Comment by cyrielle-hada** [comment]
@JaggedJax We have removed this feature. You can now [**move** elements from one workspace to another](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#moving-elements-to-workspaces).
