### ISSUE TITLE
Importing OpenAPI spec causes header parameters to be duplicated for each response type.

### ISSUE THREAD

**Issue by agmcleod** [a85/POSTMan-Chrome-Extension#8085]
**Describe the bug**
When working on an API for a client, I imported the resolved JSON documentation export from swagger hub. I noticed when trying to publish the docs via postman, that the error response would show the API Key & request signature headers multiple times, and would also omit it for the other responses.

**To Reproduce**
I then tried generating a new api from scratch, using an example one from swagger, and added a header value. Same thing happened. Here's the exported collection: https://gist.github.com/agmcleod/529ab83d6980a435e7c9cb07b54b08b4#file-example-postman-collection-json
 
Here's the openapi file i imported: https://gist.github.com/agmcleod/529ab83d6980a435e7c9cb07b54b08b4

**Expected behavior**
I'd expect the headers & request body to stay the same for each response selected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/113275/74879118-7edd6780-5336-11ea-8042-10e5217a9c99.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.18.0
 - OS: macOS Catalina

**Comment by VShingala** [comment]
@agmcleod This issue has been fixed. I've verified the fix for the specification shared by you and it's working as expected.

I'll go ahead and close the issue for now, feel free to re-open it if you face any further problems.
