### ISSUE TITLE
API usage should count fort team workspaces only

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#8086]
**Feature improvement of:** the creation of APIs via the API tab.

<img width="486" alt="Screen Shot 2020-02-20 at 12 09 13" src="https://user-images.githubusercontent.com/47351631/74932473-d5e84880-53d9-11ea-9ff8-a771268ee86c.png">

**Is your feature request related to a problem? Please describe.**

Right now, if a user joins a team with X APIs, the number of APIs this user has on his personal account will increase of X the overall API usage of the team.

<img width="441" alt="Screen Shot 2020-02-20 at 12 09 56" src="https://user-images.githubusercontent.com/47351631/74932515-f0222680-53d9-11ea-9f3d-25fd873b3f67.png">

This behavior may not be well-suited for teams who share APIs with their clients/"guest accounts" inside their team.

**Describe the solution you'd like**
Make the APIs limit include APIs created team workspaces only instead of personal workspaces AND team workspaces. 

**Describe alternatives you've considered**
n/a

**Comment by sankalp0o** [comment]
Thanks for the feedback @cyrielle-hada! We've heard similar questions around how teams should be using APIs and we've answered some of them here - https://community.postman.com/t/postman-pro-total-number-of-apis/10108
APIs are a team resource and all users within a team are counted as being part of the team and hence team limits apply to them. 
I'm closing this issue for now, but please let us know if there are any more questions. We're always happy to hear feedback on how teams are using APIs and how we could improve the experience for them!
