### ISSUE TITLE
Import CURL command does not parse the Digest Auth flag correctly

### ISSUE THREAD

**Issue by hc-danieltiziani** [a85/POSTMan-Chrome-Extension#8087]
**Describe the bug**
When you import the curl command below, it does not adjust the authentication to use the Digest Auth. It used the Basic Auth instead.

```
curl -X GET -u "TST:TEST" --digest -i "https://cloud.mongodb.com/api/atlas/v1.0"
```

**Expected behavior**
Use the Digest Authentication

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.14.0 (7.14.0)
 - OS: macOS High Sierra 10.13.2

**Comment by dhwaneetbhatt** [comment]
@hc-danieltiziani We're looking into this issue. We will keep this thread updated as we ship the fix.

**Comment by dhwaneetbhatt** [comment]
@hc-danieltiziani We have fixed this issue in the latest version of the app. Please try it out and reopen if the issue persists.
