### ISSUE TITLE
Variable in Post call raw body request payload was not resolved

### ISSUE THREAD

**Issue by kaiyuan01** [a85/POSTMan-Chrome-Extension#8090]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

Version 7.18.1 does not support this feature any more?

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by jeff812** [comment]
https://github.com/postmanlabs/postman-app-support/issues/4061

Seeing similar behavior within the latest version, Postman v7.21.1

Unable to use my integer variables that are being set via pre-request within the request body.

**Comment by DannyDainton** [comment]
Closing the issue due to inactivity and lack of contextual information.
