### ISSUE TITLE
totalTime (total run time) missing from exported run results

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8096]
**Describe the bug**
In previous versions of Postman, exporting Collection run results included "totalTime": the total time taken by the Collection run. In 7.18.0, this is missing. This change, if intentional, is not included in release notes.

**To Reproduce**
1. Run a Collection in the Collection Runner
2. Click Export Results
3. Open file and search for "totalTime"
4. See that this is missing from the current format.

**Expected behavior**
Exported run results contains "totalTime", indicating the total time taken by the Collection run.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.18.0
 - OS: macOS

**Additional context**

**Comment by acondron77584** [comment]
I believe this problem was introduced in 7.17.

**Comment by acondron77584** [comment]
This problem can also be reproduced when running on Windows.

**Comment by saswatds** [comment]
I have been able to reproduce this issue. We will get this fixed as soon as possible.

**Comment by arlemi** [comment]
The `totalTime` variable has been added from 7.21.0!
