### ISSUE TITLE
Workspace creator isn't updated when that user is removed from the team

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#8097]
**Describe the bug**
On a team's web dashboard, the creator of a workspace is listed below the workspace name. When that user is removed, the name remains which may cause confusion

**To Reproduce**
1. Go to your team's web dashboard – [go.postman.co](https://go.postman.co)
2. Remove someone from the team that has created a team workspace
3. Notice that they're still listed as the creator below the workspace name

**Expected behavior**
Upon being removed from a team, the creator of that workspace should be updated to reflect someone that's currently on the team.

**Screenshots**
Workspaces
![image](https://user-images.githubusercontent.com/4734306/75069098-1cab7080-54b6-11ea-9d82-8faaa6dffb88.png)

Clicking on the profile of the user that was removed and listed as the creator
![image](https://user-images.githubusercontent.com/4734306/75069130-3056d700-54b6-11ea-802b-e33bbc843c17.png)

Workspace details page
![image](https://user-images.githubusercontent.com/4734306/75069207-541a1d00-54b6-11ea-85ca-c4f99d3fed37.png)

**Additional context**
[Filed by Postman]

**Comment by sankalp0o** [comment]
Thanks for reporting this @chrisdeso! We'll look into this.

**Comment by sankalp0o** [comment]
@chrisdeso this has been fixed and we now show "Deactivated user" instead of showing the creator of the workspace. Please note that this only represents who created the workspace and not the "Owner". Workspace Access control is still an independent thing.
