### ISSUE TITLE
Unable to validate schema with type: array

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#8098]
**Describe the bug**
Unable to validate schema with type: array

**To Reproduce:**

1. Define/Import an API schema
2. Click on Develop > Check for validation
3. Receive: Issues found > View Issues
4. **Error:** The property didn't match the specified schema

**Expected behavior**
Should be able to validate with array without any issues.

**Screenshots**

![GH](https://user-images.githubusercontent.com/47771757/75156571-660af280-5738-11ea-9585-db134044df8a.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v.7.18.0
 - OS: macOS

**Additional context**
_[Filed_by_Support]_

**Comment by sankalp0o** [comment]
@Raj-postman Thanks for letting us know! The validation feature is new and we're working on improving it. To help us diagnose this, could you let us know
- What is the response body in the example for the request in question
- How is the response body defined in the specification

**Comment by geoffturk** [comment]
App Type - Native App
Postman Version - 7.19.1
OS: macOS

Hi. I am experiencing a similar issue, which I documented over in the Community forum:
https://community.postman.com/t/schema-validation-not-providing-details-of-reported-issue/11063

Here is the response body in the example I mentioned above:

```
{
    "data": [
        {
            "id": "5e5792b234d88e12b8511b92",
            "accountNumber": "1YNykgIi3T2NDeElON0IqcPOpPI",
            "entityName": "Farmer Freddy's Veg",
            "entityPhone": "+4420832132132",
            "incType": "sole",
            "companyNumber": "none",
            "website": "https://farmer-freddy.null",
            "turnover": 10000,
            "description": "High quality carpentry at a reasonable price.",
            "locationAddress": "123 Main",
            "locationCity": "London",
            "locationRegion": "Greater London",
            "locationPostalCode": "UK1 2ENG",
            "locationCountry": "England",
            "status": "tradingAccepted",
            "offers": [
                "organic-vegetables",
                "organic-fruits"
            ],
            "wants": [
                "carpentry",
                "beer"
            ],
            "isFavorite": true
        }
    ],
    "meta": {
        "numberOfResults": 1,
        "totalPages": 1
    }
}
```

And here is the response body defined in the spec:

```
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Entity'
                  meta:
                    type: object
                    properties:
                      numberOfResults:
                        type: number
                        format: int32
                      totalPages:
                        type: number
                        format: int32
              example: 
                data: 
                  - id: 5de8dea0bdb7911205c0a6d7
                    accountNumber: 1Y3wqV4FGDBRTZD1Dyo9VB65TRV
                    entityName: Latz Limited
                    entityPhone: +442079876543
                    incType: ltd
                    companyNumber: A29384756
                    website: https://latz.null
                    turnover: 5000
                    description: A full service, bespoke UK demo company.
                    locationAddress: 908 Pawwwwlll Mawwwlll
                    locationCity: London
                    locationRegion: Greater London
                    locationPostalCode: UK1 2ENG
                    locationCountry: England
                    status: tradingAccepted
                    offers:
                      - tutorials
                    wants:
                      - pizza
                      - beer
                      - antacid
                    isFavorite: false
                meta:
                  numberOfResults: 1
                  totalPages: 1

components:
  schemas:
    Entity:
      type: object
      title: Entity
      description: A single and unique entity linked to a user
      properties:
        id:
          type: string
        accountNumber:
          type: string
        entityName:
          type: string
        entityPhone:
          type: string
        incType:
          type: string
        companyNumber:
          type: string
        website:
          type: string
        turnover:
          type: integer
          format: int32
        description:
          type: string
        locationAddress:
          type: string
        locationCity:
          type: string
        locationRegion:
          type: string
        locationPostalCode:
          type: string
        locationCountry:
          type: string
        status:
          type: string
          enum:
            - pending
            - accepted
            - rejected
            - tradingPending
            - tradingAccepted
            - tradingRejected
        offers:
          type: array
          items:
            type: string
        wants:
          type: array
          items:
            type: string
        isFavorite:
          type: boolean
```

**Comment by Raj-postman** [comment]
@sankalp0o So here is the API schema which I used to replicate this: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

**Comment by sankalp0o** [comment]
Thanks, @geoffturk! We'll have a look at this. We are planning to add more details to the validation of response body and that should help you figure out what's the actual problem.

**Comment by sankalp0o** [comment]
@Raj-postman can you also let us know the response body? Without that, we won't be able to figure out what's the problem.

**Comment by soniCaH** [comment]
I'm having similar issues I think:

My first very simple schema:

```
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Seasons",
    "license": {
      "name": "MIT"
    }
  },
  "servers": [
    {
      "url": "http://example.com"
    }
  ],
  "paths": {
    "/seasons": {
      "get": {
        "summary": "List of all known seasons",
        "operationId": "listSeasons",
        "tags": [
          "season"
        ],
        "responses": {
          "200": {
            "description": "List of all seasons",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Season"
                  }
                },
                "example": [
                  { 
                    "name": "2018 - 2019" 
                  }
                  { 
                    "name": "2019 - 2020" 
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Season": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "example": {
          "name": "1920"
        }
      },
      
    }
  }
}
```

will validate on this example data:

```
[
 {
  "name": "2018 - 2019"
 }
 {
  "name": "2019 - 2020"
 }
]
```

**Comment by sankalp0o** [comment]
@Raj-postman @soniCaH @geoffturk we've identified a bug with validating arrays and fixed it. Can you please check and let us know if this solves your problem?

**Comment by idroxid** [comment]
@sankalp0o Same issue here... Can you please tell me if the Canary build includes the fix ?
v7.24.0-canary03 seems to still have the bug.

**Comment by jazzyarchitects** [comment]
@idroxid Yes, the Canary build includes the fix. Would you be able to share the schema or a snippet of the schema you are using since we are not able to reproduce the issue?

**Comment by sankalp0o** [comment]
@soniCaH @idroxid can you confirm if you're still seeing the same issue in the latest Postman app?

**Comment by soniCaH** [comment]
> @soniCaH @idroxid can you confirm if you're still seeing the same issue in the latest Postman app?

Confirmed, thanks!!!

**Comment by sankalp0o** [comment]
Assuming you meant that you're no longer seeing the issue. 

Do let us know if you face any other problems with the validation feature. We're working on improving it at the moment, would love your feedback!

**Comment by geoffturk** [comment]
FYI, it's working fine for me now.

**Comment by lyzkov** [comment]
> Thanks, @geoffturk! We'll have a look at this. We are planning to add more details to the validation of the response body, and that should help you figure out what's the actual problem.

It will be helpful to get any clues about validation issues. Without them, this feature is nearly useless.
For instance, the current version of postman shows me a very cryptic message:
`The property didn't match the specified schema in (...)`

**Comment by arlemi** [comment]
@lyzkov We're working on improvements for validating collections against schema, hoping to release a new version sometime this month, more info in #6722 .
