### ISSUE TITLE
java.lang.NullPointerException null

### ISSUE THREAD

**Issue by alakdam07** [a85/POSTMan-Chrome-Extension#8100]
I tried to get data from one open Api. I followed all instruction to get the data based on API documentation but I get error. Can anyone please help me out.

Here is the link of the site: **https://digitransit.fi/en/developers/apis/1-routing-api/**

**Comment by prashantagarwal** [comment]
@alakdam07 This seems to be an issue with the API that you are using and not with Postman. I will recommend you to contact the owner/publisher of the API. Thanks
