### ISSUE TITLE
APIs usage detailed overview

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#8102]
_Filed by Product Support_ 

**Is your feature request related to a problem? Please describe.**
The API usage page lack in providing some information.: team members are unable to see who has API created in their personal or team workspace. 

**Describe the solution you'd like**
Provide an API overview similar to the `View all collections` page - https://app.postman.co/team/elements with the name of the person who has created the API. 

**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by sankalp0o** [comment]
Duplicate of #8103
