### ISSUE TITLE
Issues with Postman v7.19.1

### ISSUE THREAD

**Issue by feardarkness** [a85/POSTMan-Chrome-Extension#8105]
**Describe the bug**
I can't save, duplicate or create new requests on Ubuntu 18.

**To Reproduce**
Pressing *ctrl + s* or right click and choosing duplicate or trying to save a new request.

**Expected behavior**
Saving, duplicating or updating requests.

**Screenshots**
![Selección_151](https://user-images.githubusercontent.com/860571/75300463-4c3bdf00-580e-11ea-8482-3663ca990a7e.png)
![Selección_152](https://user-images.githubusercontent.com/860571/75300471-51009300-580e-11ea-8042-ad72eab6ffa3.png)

**App information:**
 - Linux Desktop App
 - Postman Version 7.19.1
 - OS: Ubuntu 18

**Additional context**
Everything was working as expected previously, the issues started after updating to the new Version.

**Comment by appurva21** [comment]
Hi @feardarkness, we are not able to reproduce the issue. It would help us if you can provide some more insight into the request which led you to this issue.
If you have some sensitive data in the request, please feel free to send the information over email (help@postman.com)

Thanks

**Comment by feardarkness** [comment]
Thank you, I've found that only a few requests are not working, so I reinstalled Postman and now it's working.
