### ISSUE TITLE
Own domain for api documentation

### ISSUE THREAD

**Issue by AndreyKrivopalov** [a85/POSTMan-Chrome-Extension#8108]
**Describe the bug**
Api docs page do not work on my own url (https://api.tencar.ru)

**To Reproduce**

1. Go to https://api.tencar.ru

**Expected behavior**
In browser console i have error:

Refused to load https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js because it does not appear in the script-src directive of the Content Security Policy.

**Screenshots**
![2020-02-26_19-19-13](https://user-images.githubusercontent.com/58070031/75364516-ea8e7a00-58cc-11ea-8f6e-d3fc83e72670.png)

**App information (please complete the following information):**
 - All browsers and OS

**Comment by Cazaimi** [comment]
@AndreyKrivopalov, this issue has been reported once before on one of our internal channels.

For **security reasons**, we don't allow execution of scripts other than those that are trusted by us, as part of the documentation. This, is why you're seeing the CSP error. 

Please try disabling the rocker loader script and the documentation should load. 

Please reply to this thread if you face any further problems, thanks!

**Comment by AndreyKrivopalov** [comment]
> @AndreyKrivopalov, this issue has been reported once before on one of our internal channels.
> 
> For **security reasons**, we don't allow execution of scripts other than those that are trusted by us, as part of the documentation. This, is why you're seeing the CSP error.
> 
> Please try disabling the rocker loader script and the documentation should load.
> 
> Please reply to this thread if you face any further problems, thanks!

It is not my script, how can i disable rocket loader on your server?

**Comment by AndreyKrivopalov** [comment]
Solved! I am disable rocket loader on cloudflare settings and error was gone
