### ISSUE TITLE
PR folder structure elucidation

### ISSUE THREAD

**Issue by spencerrichardhenry** [a85/POSTMan-Chrome-Extension#8109]
The new pull request feature is a wonderful improvement on version control, but it leaves our team wanting some better elucidation on folder structure changes. This is particularly important because the ordering and placement of tests holds functional meaning, since there are folder level tests as well as because the tests run based on folder order.

When you hover over the exclamation by a [MOVED] tag (see image below), it tells you what folder the request has been moved to. We would highly prefer for this to show the entire file path of where it came from and where it went to. see below for an idea of what this would look like.
![image](https://user-images.githubusercontent.com/46569542/75364671-4f1fe980-5879-11ea-8df9-1ee534efeef5.png)
![image](https://user-images.githubusercontent.com/46569542/75365135-fe5cc080-5879-11ea-8c51-587753564284.png)

Additionally, it would be nice to have some sort of review of the folder structure in the PR view (maybe in overview). Something like this:
![image](https://user-images.githubusercontent.com/46569542/75365471-74612780-587a-11ea-925b-b2281ad8da19.png)
where hovering over the yellow text would tell you where it moved from. This could replace the current implementation of showing a folder [MODIFIED] and then shwoing the Folders Order, possibly by just showing a copy of the folder structure before and a copy after side by side.

The implementation is less important than just having some way to understand folder structure changes better within a pull request.

**Comment by ankit-m** [comment]
You can now see the folder structure in PR diff view.
