### ISSUE TITLE
tv4.validate does not validate properly when using 'const' schema property

### ISSUE THREAD

**Issue by catherine-greene** [a85/POSTMan-Chrome-Extension#8110]
tv4.validate does not tell the difference when using '**const**' schema property

```
const jsonData = {
            "id": 1160134,
            "lastUpdatedBy": "API_TEST"
         }
const schema = {
    "required": [
        "id",
        "lastUpdatedBy",
        ],
    "properties": {
        "id": {
            "type": "integer"
        },
        "lastUpdatedBy": {
            "type": "string",
            **"const": "API_TEST3"**
        }
   }
}

tv4.validate(jsonData, schema);
```

App information
 - Postman v7.19.1
 - OS: Windows 10

**Comment by DannyDainton** [comment]
Hey @catherine-greene,

I would recommend using Ajv over tv4 to validate your schema in the app. Taking your example response, this should return the error that you were expecting: 

```
const schema = {
    "required": [
        "id",
        "lastUpdatedBy",
        ],
    "properties": {
        "id": {
            "type": "integer"
        },
        "lastUpdatedBy": {
            "type": "string",
            "const": "API_TEST3"
        }
   }
}

pm.test('Schema is valid', function() {
  pm.response.to.be.jsonSchema(schema)
});
```

`AssertionError: expected data to satisfy schema but found following errors: data.lastUpdatedBy should be equal to constant`

**Comment by catherine-greene** [comment]
Thank you!
Replaced tv4 with ajv. Works fine!

But that would be nice to have a remark in tv4 (or Postman) documentation about such an issue. 
It is not evident that tv4 does not work with const as expected.

**Comment by DannyDainton** [comment]
Glad that helped! 🏆 

The [tv4](https://github.com/geraintluff/tv4) project hasn't been updated for over 2 years so I suspect this isn't the only issue that users are likely to see when using that module. :( 

If this solves your issue, would you like to close out this issue?
