### ISSUE TITLE
Environment value update from Postman Native App not reflected on https://web.postman.co/ 

### ISSUE THREAD

**Issue by oguennec** [a85/POSTMan-Chrome-Extension#8113]
**Describe the bug**
Environment variables values updates made from Postman Native App are not reflected in the environment available on https://web.postman.co/ (used for collection monitoring).

**To Reproduce**
1. Create a collection using environment variables (like an access_token)
2. Click on Monitor Collection
3. Update the environment variable access_token with a new value
4. See in https://web.postman.co/environments/your-environment-id?workspace=your-workspace-id that the old value for access_token is still showing.

**Expected behavior**
A new value for an environment variable set in Postman Native App should be reflected in https://web.postman.co/environments (same workspace)

**App information (please complete the following information):**
 - Native App / https://web.postman.co/
 - Postman Versio 7.16.1
 - MacOS Mojave 10.14.6

**Additional context**

**Comment by timbochamp** [comment]
I'm going to close this where I believe the use case of syncing an environment variable updated value should happen in real-time between the desktop app and Postman for Web when sanity checking on the latest v9.16.1 version. Please feel free to reopen if this isn't the case, or if I'm mistaken in closing this out!
