### ISSUE TITLE
Enhance team discovery flow

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#8115]
**Is your feature request related to a problem? Please describe.**
The current team discovery flow does not provide context as to why someone is requesting to join this Postman team. Without details like use-case or team- it becomes difficult for admins to approve a request, especially in large organisations where there are many user slots available.

**Describe the solution you'd like**
Have a workflow where the user requesting to join the team can submit details as to why they're requesting to join the team. Maybe a quick form or text box associated with it would help.

**Describe alternatives you've considered**
Currently, the alternative method I see is- admins reject the invite to join the team-> then check with the particular user in their org through another medium to vet the reason to join, like the use-case, team, etc. and then onboard them through their SSO flow or send a request to them again.

**Comment by prashantagarwal** [comment]
This is now available in Postman app v7.27
