### ISSUE TITLE
Test Runner Percentage is not properly updated based upon the iteration

### ISSUE THREAD

**Issue by sulaimaan26** [a85/POSTMan-Chrome-Extension#8116]
**Describe the bug**
Test Runner Percentage is not properly updated based upon the iteration count

**To Reproduce**
1. Navigate to any collection which has more than 3 Request
2. Click on 'Runner' from header
3. Create a Test with iteration count as '50'
4. Start the Test

**Expected behavior**
Percentage should be updated based upon the iteration count. For example, If test is in iteration 25(for total iteration count 50) the percentage should be in **50%** but now it shows as 15%

**Screenshots**
Review the attachments for your reference

![image](https://user-images.githubusercontent.com/49139974/75446850-d038b880-592d-11ea-8d3f-4d78784a76e0.png)

**App information (please complete the following information):**
 - App Type Native: APP
 - Postman Version: 7.19.1
 - OS: Windows 10 PRO

**Additional context**
This is an low priority issue can be consider as a enhancements

**Comment by mccannt** [comment]
@sulaimaan26 Can you confirm you are still seeing this behaviour? 
We have recently made some improvements around the Runner and I am not seeing this issue currently.

**Comment by mccannt** [comment]
Closing this issue out. 
If you are still experiencing this issue, please do let us know.
