### ISSUE TITLE
"Edit Monitor" screen - "Schedule" field - value "Minute Timer" is greyed out without explanation on https://web.postman.co/monitors

### ISSUE THREAD

**Issue by oguennec** [a85/POSTMan-Chrome-Extension#8117]
**Describe the bug**
https://web.postman.co/monitors, Edit Monitor screen, Schedule field shows a list of options including the Minute Timer but it is greyed out / not selectable

**To Reproduce**
1. Create a collection
2. Click on Monitor Collection
4. Select Hour Timer
3. See in https://web.postman.co/environments/your-environment-id?workspace=your-workspace-id that the Minute Timer is greyed out / not selectable

**Expected behavior**
https://web.postman.co/monitors, Edit Monitor screen, Schedule field shows a list of options including Minute Timer which is selectable / not greyed out.

**Screenshots**
The Hour Timer is selected
![image](https://user-images.githubusercontent.com/6723310/75455216-25e28480-5971-11ea-82e9-cd40858c90a4.png)
The Minute Timer is greyed out in the drop down list
![image](https://user-images.githubusercontent.com/6723310/75452095-8b327780-5969-11ea-81a1-5fff45f49646.png)

**App information (please complete the following information):**
 - https://web.postman.co/monitors
 - Postman Version 7.16.1 (Native App used to creation collection and setup monitoring)
 - MacOS Mojave 10.14.6

**Comment by oguennec** [comment]
I have found out from the Native App that Minute Timer is not available on the free plan (although I have been able to use it for some time on the free plan).

![image](https://user-images.githubusercontent.com/6723310/75457127-aa360700-5973-11ea-94de-200f67adfcac.png)

I leave this ticket open as it would be informative to have the same message mentioning that Minute Timer is not available on the free plan on [https://web.postman.co/monitors](https://web.postman.co/monitors)

**Comment by ArjunSingh-PM** [comment]
@oguennec Thank you for pointing this out. We will include the message for the _Minute Timer_ at the Postman dashboard as well.

**Comment by charlie-postman** [comment]
We have updated our documentation. Closing the ticket.
