### ISSUE TITLE
Cookies are lost when the application is closed

### ISSUE THREAD

**Issue by tyd** [a85/POSTMan-Chrome-Extension#8118]
**Describe the bug**
Cookies are lost when the application is closed.

**To Reproduce**
1. Go to Cookies tab
1. Add cookies manually
1. Close cookie management dialog
1. Exit the Postman application
1. Open the Postman application
1. Go to Cookies tab, cookies added in step 2 are now gone

**Expected behavior**
Cookies should persist across application restarts

**Screenshots**
1. Added a cookie
![image](https://user-images.githubusercontent.com/1465854/75460555-d4b99d00-593e-11ea-824b-f9514c5703a1.png)
1. After restarting the application cookies are gone
![image](https://user-images.githubusercontent.com/1465854/75460801-22cea080-593f-11ea-864e-b8bf28131fd2.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.19.1
 - OS: macOS Mojave 10.14.6 (18G1012)

**Comment by shamasis** [comment]
Hey @tyd - got to know from @codenirvana that this happens because cookies without an expiry date is treated as “session cookie.” You could set expiry dates manually for now while we explore ways to improve the UX here.

**Comment by tyd** [comment]
@shamasis Thanks for the info! Makes more sense now. I also confirmed setting **;Max-Age=2147483648** makes the cookies persist across application restarts.

Note:
- [RFC 2616 Section 14.6](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.6) _2147483648_ is the RFC maximum, but lower values work as expected too.

**Comment by shamasis** [comment]
@tyd We are thinking of adding this max age by default when cookies are added through the UI. Eventually, the UI itself would be simplified to handle and identify these easily. Dealing with cookie string directly is a pain. @vkaegis is also exploring a tabular layout for this.

**Comment by coditva** [comment]
@tyd We've added an additional attribute `Expires` with default value of an year from the current date. You can always choose to remove this to create a session cookie if you want!

Please update to Postman `v7.21.0` :tada:

![image](https://user-images.githubusercontent.com/8445768/77320695-0acc2000-6d37-11ea-9ea7-716c49961b42.png)
