### ISSUE TITLE
"Response body was not logged" in Runner

### ISSUE THREAD

**Issue by danieladougan** [a85/POSTMan-Chrome-Extension#8122]
When viewing tests in the Runner (especially failing ones), sometimes I will see the response, and sometimes I will see "Response body was not logged."

I can understand this could be a space/memory issue, but being able to see the exact reason why a test is failing in the Runner would be a big time saver.

1. Run the Runner over a large collection. You might have to do this multiple times to reproduce.
2. Hover over a test.
3. Click the arrow next to "Response Body" to expand it.

I expected to see the response body when I hover over the test in the Runner.

**Screenshots**
![image](https://user-images.githubusercontent.com/42144517/75579642-47f10b00-5a34-11ea-9316-310a275c60df.png)

**App information (please complete the following information):**
- Native Windows app
- Postman v7.19.1
- Windows 10

It looks like this issue or something similar was reported and closed out in 2017 and 2018, but this is now 2020, and it's still a problem.

**Comment by vk-s78** [comment]
I am having the same issue with my console
![image](https://user-images.githubusercontent.com/56678288/77693484-559ca080-6fa0-11ea-9883-7798183e7187.png)

**Comment by hungtdao** [comment]
Has anyone known this issue been resolved?

**Comment by fathur** [comment]
any answer for this question, it has been two years?

**Comment by malvikach** [comment]
Hi, While running collections, responses are not saved by default. However, you can choose to save the responses inside your session by selecting the below option under your 'Advanced Settings':
<img width="478" alt="Screenshot 2022-11-23 at 5 44 22 PM" src="https://user-images.githubusercontent.com/89449769/203544778-ea22e00c-cd6c-42af-9bed-99072acd429e.png">

Note: This will save your response headers and bodies in your session. 
I hope this helps. I am keeping this issue open since the option to save/log responses was not very obvious.

**Comment by malvikach** [comment]
Hi folks,

I wanted to inform you about a few changes we have done to improve this flow.

1. Option to Save Responses/Persist Responses has been moved out of advanced settings and is now available under runner directly:
<img width="536" alt="Screenshot 2023-03-17 at 12 18 51 PM" src="https://user-images.githubusercontent.com/89449769/225833417-2970b50e-51af-4f45-ac0e-80d27ddc462c.png">
2. Now clicking on Request names on the Runner Details screen, will navigate you directly to the Requests. You can view the Response bodies and other details, by clicking on the test result. this will open the details on the Right-hand pane. Response Bodies are now formatted and you have the ability to copy or search on it. 

![ezgif com-optimize (3)](https://user-images.githubusercontent.com/89449769/225833781-7f59b6f8-849f-40ef-adc1-b28df4bb57f2.gif)


3. If you forget to persist the Response Body, you have the option to navigate to the runner from the Results. This will auto-check the option to 'Persist Responses in a session' and run the collection. 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/89449769/225835511-b0c1adcc-5701-4d2c-9038-9e042e219727.gif)

We are also evaluating the option to save the responses by default, being tracked on [Github # 11601](https://github.com/postmanlabs/postman-app-support/issues/11601)
Hope this is helpful. Thanks again for the feedback! We really appreciate it. 🙇 

Cheers!
Malvika
