### ISSUE TITLE
During authentication from authentication screen at the point the user should be redirect to the consent page the login page is simply reloaded.

### ISSUE THREAD

**Issue by B4st13n** [a85/POSTMan-Chrome-Extension#8123]
**Describe the bug**
Compatibility issue between Postman and IdentityServer4 (https://github.com/IdentityServer). 

**To Reproduce**
Using Postman authentication screen with OAuth 2. During authentication from authentication screen at the point the user should be redirect to the consent page the login page is simply reloaded.

More details on your community forums: https://community.postman.com/t/using-postman-to-test-identityserver4-oauth-authentication-code-flow/9524

Please read the post.

**Expected behavior**
The browser should go to consent page then retrieve the token.

**Screenshots**
For this, please just check the post

**App information (please complete the following information):**
- Postman for Windows. "You are up to date! Postman v7.19.1 is the latest version."
- Identity Server 3 with .NET code 3.1

**Additional context**
They are several tutorial on the web explaining how to use Postman with Identity Server 4 but all seems a little but outdated and no one work now. I think this is an issue of Postman because I can use my Identity Server with all other tools I tried. Only Postman (and Insomnia) cannot. It seems both share the same mini browser. I think the issue is coming from that.

I can give you link to my code of Identity Server and my collection of request. I also opened a question on Stackoverflow and many other forum. I still get no help or no reaction from Postman.
Here: https://stackoverflow.com/q/60318190/196526

**Comment by pcbl** [comment]
Hey everyone. I am facing exactly this issue. Are there any workarounds that does not require me to change my backend to handle the SameSite policy?

**Comment by Yawnder** [comment]
Hi,
Any update on that? I'm having the same issue, and neither this thread, nor the community one [(here)](https://community.postman.com/t/using-postman-to-test-identityserver4-oauth-authentication-code-flow/9524/3) show any progress.

**Comment by PiotrCzajkowski** [comment]
Hi. I have the same problem, and I've found temporary solution. You can use chrome extension for postman: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=pl. It`s an older version (5.5.0) but it works! Using extension you can gain an access_token and rest of the work do in desktop app.

**Comment by mccannt** [comment]
@B4st13n @pcbl @Yawnder @PiotrCzajkowski Can you confirm this is still an issue on the latest version of the app?

**Comment by Mechanicalkeyboard** [comment]
Closing this issue, please feel free to reopen if it is still present.

**Comment by B4st13n** [comment]
Sorry for this late reply. I can now confirm it is fixed by the latest version of Postman.

**Comment by B4st13n** [comment]
And now I can re-use Postman. Nice.
