### ISSUE TITLE
Global Variables not working

### ISSUE THREAD

**Issue by jpiell** [a85/POSTMan-Chrome-Extension#8124]
**Describe the bug**
{{$randomZipCode}} does not work
{{$randomStateAbbr}} does not work

**To Reproduce**
1. Add these variables to the body of your request.
2. Submit your request
3. See error

**Expected behavior**
Expected behavior is a random value for these variables is created.

**Comment by coditva** [comment]
Hey @jpiell, these variables are not present in Postman anymore. Please see this list for reference: https://learning.getpostman.com/docs/postman/scripts/postman-sandbox-api-reference/#dynamic-variables

Ref: https://github.com/postmanlabs/postman-docs/issues/2054 https://github.com/postmanlabs/postman-app-support/issues/7990
