### ISSUE TITLE
Import cURL doesn't import body

### ISSUE THREAD

**Issue by Jk1484** [a85/POSTMan-Chrome-Extension#8126]
**Describe the bug**
I have a request. When I get the cURL of request and import it, body is not imported.
For some other requests, this method works. But for this cURL: 
```
curl --location --request PUT 'http://192.168.73.22/api/admin/v0/device/control/status' \
--header 'Authorization: <redacted>' \
--header 'Content-Type: application/json' \
--data-raw '{
	"deviceID": "ffffffff-9334-1a1b-ffff-ffffef05ac4a",
	"phone": "+0000000000000"
}'

Import doesn't import body. This cURL is copied from code section of request.

```
**To Reproduce**
1. Go to a request
2. Click on code
3. Scroll down to cURL
4. Copy the cURL
5. Go to IMPORT -> Paste raw text
6. Paste the cURT
7. Click IMPORT

**Screenshots**
Here is the body of request:
![Selection_437](https://user-images.githubusercontent.com/35270240/75645966-d69a9d80-5c69-11ea-83c9-0f51f75acc9a.png)

Here is the cURL of request:
![Selection_436](https://user-images.githubusercontent.com/35270240/75645942-c256a080-5c69-11ea-818f-435d68d0c4cf.png)

When I copy cURL and import it like this:
![Selection_438](https://user-images.githubusercontent.com/35270240/75646025-fcc03d80-5c69-11ea-8970-bc0e1de3d122.png)

Body is not imported:
![Selection_439](https://user-images.githubusercontent.com/35270240/75646079-3133f980-5c6a-11ea-80c7-3cab6ddd4805.png)

**App information (please complete the following information):**
 - Postman Version [v7.18.0]
 - OS: [Linux Ubuntu 18.04.4 LTS]

**Comment by umeshp7** [comment]
@Jk1484 Thanks for reporting this. 
We are working a fix for this, will be out soon.
Meanwhile you could try changing the `--data-raw` to `--data`. This will import the body too.

**Comment by umeshp7** [comment]
Duplicate of: https://github.com/postmanlabs/postman-app-support/issues/7895

**Comment by gs-aagarwal** [comment]
Is this pushed to production ? I am still facing this issue

**Comment by effyteva** [comment]
I still face this issue as well

**Comment by roma2341** [comment]
Postman 8.10. issue is there

**Comment by ramazansancar** [comment]
Check here: https://learning.postman.com/docs/getting-started/importing-and-exporting/importing-curl-commands/
