### ISSUE TITLE
customize response httpstatus,  return Could not get any response

### ISSUE THREAD

**Issue by xieyy09** [a85/POSTMan-Chrome-Extension#8128]
HI I encountered a problem

**version**
Postman for Linux
Version 7.19.1

When an error occurred in the request, I set the status code of the response, but returned:

![image](https://user-images.githubusercontent.com/21615006/75734033-d06ff400-5d31-11ea-88fb-cb706e638bd0.png)

![image](https://user-images.githubusercontent.com/21615006/75734043-d665d500-5d31-11ea-8c8d-bef173672d3a.png)

When I return the universal status code, it is normal. Am I missing any settings?

![image](https://user-images.githubusercontent.com/21615006/75734187-39576c00-5d32-11ea-97af-21864c551768.png)

**Comment by coditva** [comment]
@xieyy09 I *think* this might be because of an invalid character in your message (maybe a newline instead of `\r\n`)? Can you verify the same and see if this error persists.

You can also try this out with `curl --verbose` and see if there's something else that is wrong here.

**Comment by xieyy09** [comment]
HI, I reproduced the error.
Chrome and curl return normally, postman error is the same!

**chrome:**
![image](https://user-images.githubusercontent.com/21615006/77271687-4260ab00-6cea-11ea-8b5c-0b93a25777c1.png)
![image](https://user-images.githubusercontent.com/21615006/77271693-47255f00-6cea-11ea-9bc1-4dfafd8c918d.png)
**curl:**
![image](https://user-images.githubusercontent.com/21615006/77271733-5e644c80-6cea-11ea-9027-be7468be8eab.png)
**postman:**
![image](https://user-images.githubusercontent.com/21615006/77271752-6cb26880-6cea-11ea-9503-cec805bee278.png)
![image](https://user-images.githubusercontent.com/21615006/77271765-78059400-6cea-11ea-87fa-dd8cf549e041.png)

**Comment by coditva** [comment]
It seems to be that the status code is 5 characters instead of 3 characters long. This is what's causing Postman to fail to parse the response!

According to the [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6), the status codes are supposed to be 3 digits only.

It is NodeJS that fails and returns this error. This is a limitation of the response parser itself.
