### ISSUE TITLE
FEATURE REQUEST: Snippet to make sure something in response body is not there

### ISSUE THREAD

**Issue by mmathe03** [a85/POSTMan-Chrome-Extension#813]
There are snippets that allow me to look for something in the response body to ensure it is there, but I would also like to ensure something is not there.  This would actually be more useful.  Is there a way to do that now or will this hopefully be a new feature in the future?

**Comment by sandeepmstar** [comment]
Use - pm.test("Reposne body Does not contains the string - abc", function () {
pm.expect(pm.response.text()).to.not.include("abc");
});
