### ISSUE TITLE
Zoom only works 10x, and then stops working

### ISSUE THREAD

**Issue by gingters** [a85/POSTMan-Chrome-Extension#8130]
**Describe the bug**
When presenting with Postman, it is important to zoom in a LOT to make the contents presentable for the audience in the back.

**To Reproduce**
Open Postman and Press `Ctrl +` to Zoom in. 
This will only work 10 times and then cease to work.

**Expected behavior**
Whenever Ctrl + is pressed, the app should zoom in further, without a limit.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.19.1
 - OS: Windows 10

**Comment by arlemi** [comment]
We upped how much you can zoom in from 150%-to 500% in the latest version of the app (7.22), update it and you should be able to zoom (almost) as much as you'd like!

**Comment by numaanashraf** [comment]
Hey everyone, we discovered an [issue](https://github.com/postmanlabs/postman-app-support/issues/8298) in v7.22.0 and had to revert this particular improvement as part of v7.22.1 patch. We'll definitely bring back the expanded zoom ranges once we iron out few issues there.

**Comment by gingters** [comment]
Oh, how unfortunate. I really was happy that this was adressed so quickly and I could use better zooming in in my upcoming webinar talks.
But anyways, keep up the great work 👍 and be sure that I wait desperately for this ;)

**Comment by numaanashraf** [comment]
We hope to have this out as part of `v7.23`, which should hit stable in two weeks. It'll be available even sooner on our early access 'canary' channel - we'll let you know the moment it does. Thanks for your patience @gingters!

**Comment by numaanashraf** [comment]
@gingters This is available in v7.25 :)
