### ISSUE TITLE
Could not get any response There was an error connecting to https://reqres.in/api/users. Why this might have happened: The server couldn't send a response: Ensure that the backend is working properly Self-signed SSL certificates are being blocked: Fix this by turning off 'SSL certificate verification' in Settings > General Proxy configured incorrectly Ensure that proxy is configured correctly in Settings > Proxy Request timeout: Change request timeout in Settings > General

### ISSUE THREAD

**Issue by shona-code** [a85/POSTMan-Chrome-Extension#8132]
Error: connect ETIMEDOUT 104.27.134.11:443 with Could not get any response
There was an error connecting to https://reqres.in/api/users.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

**Comment by shona-code** [comment]
Error: connect ETIMEDOUT 104.27.134.11:443 in console

**Comment by untilted-document** [comment]
Perhaps you could consider editing the Subject of your issue so it's a little shorter

**Comment by coditva** [comment]
@shona-code This seems to be an issue with the server itself? I tried it with `http://` protocol and got this response:

Trying it with `https://` gave me "Could not get response" and in the Postman Console, I see this message:
![image](https://user-images.githubusercontent.com/8445768/76862271-ddd5c400-6883-11ea-8211-cce7b060f613.png)

Trying it out with `curl` gives me a similar error too:
```curl
*   Trying 104.27.134.11...
* TCP_NODELAY set
* Connected to 104.27.134.11 (104.27.134.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, handshake failure (552):
* error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure
```

Hope this helps. Feel free to re-open if you think I've missed something. :)
