### ISSUE TITLE
filter routes in my collection

### ISSUE THREAD

**Issue by chenkamin** [a85/POSTMan-Chrome-Extension#8133]
hey,
im not sure if its a bug or a feature :) 
so far, when i typed a route name in the filter input i got only the matching routes.
now, when i do the same im still seeing all my routes but the mathcing one's are in orange.

i have more then many routes and it is hard to find the orange ones.

can i configure the filter? it is happen because of an update?

thanks,
chen

**Comment by coditva** [comment]
Hey @chenkamin, this issue has been fixed in the latest version of the App (7.19.1). Please update and let us know if it's still an issue for you.

**Comment by chenkamin** [comment]
solved !
