### ISSUE TITLE
Keep Alive connections shared when ports are different

### ISSUE THREAD

**Issue by chris-branch** [a85/POSTMan-Chrome-Extension#8134]
**Describe the bug**
Postman 7.19.1 (Mac OS) appears to have a bug related to Keep Alive connections that share the same domain name, but different ports. Example:

http://localhost:8000/public
http://localhost:8001/admin

When I send a GET request to one of these endpoints via Postman, everything works fine. However, when I try to interleave GET requests to both endpoints, I receive a successful response from whichever one I hit first, and a 404 from the other. If I wait 75 seconds, then I can successfully hit the second endpoint (but then the first endpoint returns 404 until I wait another 75 seconds). If I add a “Connection: close” header to both requests, then the problem does not occur – I can interleave calls without waiting 75 seconds. Also, if I use curl to run the same requests (generated by Postman), the problem does not occur.

I also noticed that the request that Postman sends to localhost:8001 that returns the 404 response shows up in my server logs as localhost:8000 even though it says localhost:8001 in the Postman console.

Conclusion: I suspect that Postman is maintaining a connection pool for keep alive connections and incorrectly reusing connections for the same host but different ports. It should match both host and port before allowing connection reuse.

**To Reproduce**
1. GET http://localhost:8000/public  (response = 200)
2. GET http://localhost:8001/admin  (response = 404)
3. ...wait at least 75 seconds...
4. GET http://localhost:8001/admin  (response = 200)
5. GET http://localhost:8000/public  (response = 404)

**Expected behavior**
Expected a 200 response consistently from both requests, independent of the order requests are executed and/or idle time in between requests.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.19.1
 - OS: macOS Mojave 10.14.6

**Additional context**
n/a

**Comment by codenirvana** [comment]
@chris-branch Yes, Postman does maintain a connection pool for the keep-alive connections but this issue is very unlikely to happen.

Can you share a sample server that we can use to reproduce this issue locally?

**Comment by chris-branch** [comment]
Sorry, it turns out the bug is with our corporate proxy.  Postman is working fine.  It didn't occur to me that requests to localhost would use the proxy, but they do in our setup.

In case this helps someone else in the future, I'll go ahead and post the test case I created.  Use the attached docker-compose file (rename from .txt to .yml) and run these steps:

1. docker-compose up -d
2. Open a web browser and verify that the following two requests work:
   http://localhost:8001/one.html
   http://localhost:8002/two.html
3. Use Postman to execute a GET request for each url above in separate tabs.

In my case, whichever url I hit first will return a 200 with the correct body content, and the other url will return a 404 for a short time because it's actually hitting the wrong port.  If I open Postman settings and turn off "Use System Proxy" under the Proxy tab, then everything works as expected.

Sorry for the false alarm.

[docker-compose.txt](https://github.com/postmanlabs/postman-app-support/files/4301229/docker-compose.txt)
