### ISSUE TITLE
Mac OSX Postman v7.17 ~ v7.18.1 keeps becoming unresponsive to mouse clicks (but not hover) and text entry cursor is now erratic

### ISSUE THREAD

**Issue by bkmdev** [a85/POSTMan-Chrome-Extension#8135]
**Issue**:
Mac OSX Postman v7.17 ~ v7.18.1 keeps becoming unresponsive to mouse clicks (but not hover) and text entry cursor is now erratic.  

**Environment**:  

- **OS ver**:  Mac OSX 10.13.1 + 
- **App ver**:  Postman "Native" v7.17 ~ v7.18.1 (note:  Issue _did not_ occur in v6.X of Postman app.  Only after upgrading to v7.17+ did this issue begin)

**Reproducibility**:  50?-100% (I do not know what exactly is causing this, but this is becoming increasingly frequent, impacting to work and reducing Postman's usability)

**To Reproduce**:

1. Launch Postman
2. Switch between Team and individual workspaces, use or leave app in background for a few mins to hours

**Expected behavior**
Postman app when switched back to, responds to mouse clicks and text typing/cutting (via keyboard) is not "messed up"

**Actual**:  
Postman app (including "Postman Console") becomes unresponsive to any mouse clicks and only responds to hover and entering text in URL field.  Entering text (or cutting via `<CMD-x>` ) in text fields is also erratic (see attached .gif) below:  

**Screenshots/Videos**:

![OSX_10 13 X_Postman_v7 18 1_mouse_clicking_broken](https://user-images.githubusercontent.com/770365/75805139-39199980-5d4f-11ea-8482-9249e253d607.gif)

A few comments about the recording:  

1.  Apologies for the odd recording resolution, my screen is at a high resolution and I tried to record this in a way that does not disclose confidential information.
2.  It's a bit hard to see but clicking on the HTTP method drop-down triangle (as well as several other areas of the app) does nothing
3.  In the recording, where you see "foo" highlighted is where I attempted to "cut" via the keyboard (`<CMD-x>`), which did nothing (oddly, R-clicking and selecting "Cut" did work).  _Not shown_:  If one attempts to type over the highlighted "foo", the cursor jumps to some other position in the text after the colon (`:`).  

**Troubleshooting Attempted**:  

- While restarting the app helps, it only helps for a while till the issue manifests itself again.  You also lose any data from your current session.  
- Have tried bringing up issue in gitter.im channel to no response (> ~3 weeks?).  
- Examined relevant Postman logs and do not see any error messages.  
- Searched https://postmanlabs/postmap-app-support repo for existing issues but did not see any

**Workaround**:  Oddly found that opening and closing "Current Shell"'s DevTools ("Electron" (Chromium?)) console, ie: *View > Develop > Show DevTools (Current Shell)* allows app to respond again for a while.  

**Additional context**
N/A

**Comment by phalverson** [comment]
I am also experiencing this with version `7.19.1` , it's becoming very intrusive to keep restarting the application so frequently.

**Comment by ejain** [comment]
Same here with `7.23.0`. Only parts of the UI become unresponsive, sometimes just the "Send" button, other times the tabs as well... The DevTools workaround works for me.

**Comment by numaanashraf** [comment]
@ejain Could you try out our early access Canary build? https://www.postman.com/downloads/canary/. We are testing some improvements that should address this particular issue. You can install and use the Canary build side by side with the stable app.

**Comment by bkmdev** [comment]
✅ After leaving it open for a few days & interacting it with periodically, I can confirm the issue appears to be fixed now in canary build `Version 7.24.0-canary03` 👍 Do you know when this canary build will be released into the main release channel?

PS:  Just out of curiosity, what was the cause? and what commit fixed this?  🤔

**Comment by ejain** [comment]
I'm still seeing this issue with `7.24.0`.

**Comment by twitharshil** [comment]
Hi,
We’ve pushed the updates in our stable app v7.25.1 that should fix this issue 🎉. 
Feel free to reopen the issue if you are still facing this problem on Postman v7.25.1 onwards.
