### ISSUE TITLE
Mock server not matching by query parameters

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8138]
**Describe the bug**
Mock server appears to _not_ be matching by request parameters in the following scenario:

Mock server includes 3 examples responses, each differentiated by one query parameter (`special_parameter`).

Example URLs:
{{host}}/module/child/{{key}}/users/{{id}}?Type=*TOKEN1,*TOKEN2,*TOKEN3,*TOKEN4&**special_parameter=NEGATIVE**
{{host}}/module/child/{{key}}/users/{{id}}?Type=*TOKEN1,*TOKEN2,*TOKEN3,*TOKEN4&**special_parameter=POSITIVE**
{{host}}/module/child/{{key}}/users/{{id}}?Type=*TOKEN1,*TOKEN2,*TOKEN3,*TOKEN4&**special_parameter=ALL**

Sending requests to the mock server only ever returns the example containing **special_parameter=ALL**.

**To Reproduce**

1. See following documentation page for a working mock server / environment:
- https://documenter.getpostman.com/view/5293839/SzRuWqz3?version=latest
2. Select environment, and try sending one of the requests in example collection to mock server
3. See that only the example with **special_parameter=ALL** is ever returned

**Expected behavior**
Mock server matches to example where query parameters match.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.19.1
 - OS: macOS Catalina 10.15.2

**Comment by pranayat** [comment]
The `*` character in the request to the mock server is encoded as `%2A` by Postman 7.19.1 before sending.
This does not match the `*` in the saved example request. Hence the query parameters of none of the 3 examples exactly match the requests sent to the server.

On the other hand, the query parameter keys (TYPE, special_parameter) do match for all 3 examples, making all of them equally likely to be selected. In this case, 'ALL' is being selected.

It would be best to check how your client (browser or Postman in this case) is encoding the request and save the example requests accordingly.

**Comment by JP-from-Postman** [comment]
Thanks @pranaya94 .

I tried replacing the asterisks in the examples with `%2A`, and it _almost_ fixes the problem. The requests with `special_parameter=ALL|POSITIVE` match to the appropriate example, but the NEGATIVE request doesn't match — it returns the POSITIVE example. Any thoughts?

Feel free to play around with the mock server I have setup below:
https://documenter.getpostman.com/view/5293839/SzRuWqz3?version=latest

**Comment by pranayat** [comment]
This is happening because the `x-mock-response-name` header value has been set to 'POSITIVE' in the NEGATIVE example.

**Comment by JP-from-Postman** [comment]
Whoops, right you are. Thanks @pranaya94! Marking closed.
