### ISSUE TITLE
Crashing when trying to capture requests with proxy source on an already used port

### ISSUE THREAD

**Issue by denizoztreves** [a85/POSTMan-Chrome-Extension#8143]
**Describe the bug**
When trying to capture requests on Postman the application crashes.

**To Reproduce**
1. Run a local application on port a given port ie 16419
2. Click on 'Capture requests and cookies'
3. Fill port as 16419
4. Turn on capture requests switch
5. Application crashes

**Expected behavior**
A clear error message stating that the port is unavailable/already used

**App information (please complete the following information):**
 - MacOS Native app
 - Postman Version 7.19.1 (7.19.1)
 - OS: macOS Catalina 10.15.3

**Comment by shashankawasthi88** [comment]
@denizoztreves are you still experiencing this issue with the latest updates? In the current app version, I can see that we get a clear message when the port is already occupied. 
Which version of app are you currently using?

**Comment by denizoztreves** [comment]
The version that the problem was appearing It is stated on the description of the issue. I think this bug is fixed down the line with a product update, since it is not a problem anymore for me.
