### ISSUE TITLE
Inserting the "{" in the URL of a request crashes

### ISSUE THREAD

**Issue by jwbanning** [a85/POSTMan-Chrome-Extension#8144]
**Describe the bug**
I am trying to change a URL from http://example.com to use an environmental var. The syntax should be the double curly bracket "{{ }}". When I go to modify the request string in the application, inserting the "{" makes the app fail. 

**To Reproduce**
https://postman.slack.com/files/UQMT8K4DS/FU1UM0HAS/header.mov

**Expected behavior**
The environmental variable or curly brackets would be allowd. 

**Screenshots**
<img width="933" alt="Screen Shot 2020-03-04 at 3 05 20 PM" src="https://user-images.githubusercontent.com/2584258/75923204-393a9780-5e2a-11ea-873f-198392500367.png">
<img width="1169" alt="Screen Shot 2020-03-04 at 3 03 45 PM" src="https://user-images.githubusercontent.com/2584258/75923209-39d32e00-5e2a-11ea-9cda-43bd7e0cb74b.png">

**App information (please complete the following information):**
 - Postman Version [7.19.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Comment by numaanashraf** [comment]
This is resolved in v7.23
