### ISSUE TITLE
Hihgly suspect older account is causing sync failed

### ISSUE THREAD

**Issue by eslym** [a85/POSTMan-Chrome-Extension#8145]
My postman account always failed to sync while my friend's account is success, the only different between our account is my account was created years ago, and the sync is success after I deleted and re-created my account, so highly suspect some failing of sync is causing by server issue with older account.

**Comment by preethammavin** [comment]
@eslym any chance you can email us at help@postman.com with the registered email for us to take a closer look?

**Comment by preethammavin** [comment]
@eslym thanks for the email, I was able to confirm my hunch that you had disabled the sync functionality when you had initially signed-up which caused the issue. A re-signup fixed it.
