### ISSUE TITLE
Postman API rate limit issue

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#8148]
**Describe the bug**
To better monitor the health of our environments, we are using Postman APIs every morning to collect the results of all monitor runs. However recently we have noticed that some data was not coming through and after investigation, found that this is due to "Rate limit exceeded" error that we are getting.

**To Reproduce**
1. Create some script to go through each monitor to get run data
2. Rate limit exceeded error will come up

**Expected behavior**
The rate limit should be increased to prevent this from happening.

**Screenshots**
![image](https://user-images.githubusercontent.com/43671684/75971709-119b0c00-5eca-11ea-83e9-7884f502a3a0.png)

**App information (please complete the following information):**
N/A - APIs

**Comment by ArjunSingh-PM** [comment]
@VicKetchup, thank you for writing to us. Could you elaborate on what is the objective behind retrieving the entire run data for all monitors.

**Comment by VicKetchup** [comment]
@ArjunSingh-PM We store the data (for last 30 runs) and then put it up on a webpage using in-house API to request the stored data. This webpage is then used across offices so everyone knows how we are doing, here is the main page which now unfortunately doesn't display the data properly due to this issue: 
![image](https://user-images.githubusercontent.com/43671684/75985225-d1e11e00-5ee3-11ea-8475-ce39e1b52d6c.png)

**Comment by VicKetchup** [comment]
Our rate would be lower if the monitors API didn't show the monitors that no longer exist, we have quite a few of those, so maybe by removing those, the rate issue would go away.

**Comment by godfrzero** [comment]
@VicKetchup The Postman API has rate limits imposed on it, as documented here: https://documenter.getpostman.com/view/631643/JsLs/?version=latest#rate-limits

We'll be looking at API improvements later on, so we'll take these filters into consideration. The rate limit itself is unlikely to change.

**Comment by preethammavin** [comment]
@VicKetchup you could delete the set of monitors that you don't have in use and have delays between API requests to fetch them to avoid the rate limit. Closing the issue for now, do feel free to reopen the issue if the above suggestion doesn't work.

**Comment by VicKetchup** [comment]
> @VicKetchup you could delete the set of monitors that you don't have in use

@preethammavin that has already been done, however the monitors API still returns those monitors, when trying to access them, we get an error saying that monitor does not exist. Could this be checked on your side?

**Comment by ArjunSingh-PM** [comment]
@VicKetchup I have created a ticket - Monitor list returned by the API includes deleted monitors. We are working on resolving the same.

Refer: https://github.com/postmanlabs/postman-app-support/issues/8176
