### ISSUE TITLE
Postman crash when activating Capture requests function on a port already bind

### ISSUE THREAD

**Issue by fordevtls** [a85/POSTMan-Chrome-Extension#8150]
**Describe the bug**
Postman crash when activating Capture requests function on a port already bind

**To Reproduce**
1. Has a process other than Postman bind to a specific port, like 8080
2. Go to 'Capture requests and cookie with Postman'
3. Set the Port to '8080'
4. Click on the switch button to put it on 'ON'
5. Postman crash without any message.

**Expected behavior**
Postman not crash, and display message that the port is already bind by an

**App information (please complete the following information):**
 - Native App
 - Postman Version [7.19.1]
 - OS: [Windows 10]

**Comment by shashankawasthi88** [comment]
@fordevtls this should be solved in the latest version of the Postman App. Postman now shows a toast to indicate if the port is already in use.
