### ISSUE TITLE
API usage discrepancy - unable to remove APIs

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#8151]
**Describe the bug**

I can't remove unnecessary APIs in order to make space in my resource usage.
The View detailed API usage - https://app.postman.co/usage/apis shows that a user in my team has 6 APIs.

However, the APIs have been deleted by the user **from all the workspaces including its own personal workspace**.

The personal API view of this user -  https://app.postman.co/me/apis - shows an empty list.

**To Reproduce**
1. Create APIs both in my personal workspace and team workspace
2. See the APIs created in step 1 reflected 
    - in the app
    - in the view detailed API usage - https://app.postman.co/usage/apis
    - in my personal API usage view - https://app.postman.co/me/api
3. Delete them from all the workspaces including my own personal workspace.
4. The deleted APIs created in step 1 don’t appear anywhere and the deletion won't be reflected in the resource API usage. 

**Expected behavior**
The APIs are removed completely.

**Comment by cyrielle-hada** [comment]
**Postman update**

This issue is happening because the API has been removed from all the workspaces. 
The cause of the underlying issue has been found and a fixed was pushed to resolve this flow.

However, users who have removed the APIs before the fix will face this issue (Dec 15 to Feb 6). 

**Workaround** 

Delete the APIs from the account where the APIs were created using [the Postman API](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#a67ddfe9-1337-4133-83dc-851fee33c55f):

1. Generate an API key heading to https://go.postman.co/settings/me/api-keys.
2. Open the terminal on your machine
3. Run the following curl command on the terminal: 
     `<api-key>` to be replaced by the key generated in Step 1. 
     `<api-id>` to be replaced but the API id - you can fetch using the [Get all APIs Postman API](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#3ebf9324-fb36-4e44-81cf-c24915515272) 

```curl -v --location --request DELETE 'https://api.getpostman.com/apis/<api-id>' \ --header 'x-api-key: <api-key>'```

**Comment by jazzyarchitects** [comment]
Just wanted to add that if the API which you want to delete is not visible to you in any of the workspaces, you can omit the `workspace` query parameter in [Get all APIs Postman API](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#3ebf9324-fb36-4e44-81cf-c24915515272) which will fetch all the APIs accessible to you. 

Once you find the API you want to delete, you can use the `curl` command given in the previous comment.

**Comment by sankalp0o** [comment]
Closing this as the original issue was resolved. If someone is still facing this problem, please refer to the steps posted above. Do let us know if the issue persists after this as well!
