### ISSUE TITLE
Post body row cursor exception bug

### ISSUE THREAD

**Issue by 18853477039** [a85/POSTMan-Chrome-Extension#8152]
**Describe the bug**
can't revise row.
Normal use on Windows

**To Reproduce**
1. Go to 'Post'
2. Click on 'body'，'row'
3. Enter anything
4.Click anywhere entered
5. backspace
6.see error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.19.1]
 - OS: [e.g. Ubuntu  18.04]

**Additional context**

**Comment by vvs11** [comment]
@18853477039 Could you let us know in more detail what you're trying to do? I am not able to reproduce this. If possible could you also attach some screenshots?

**Comment by 18853477039** [comment]
> @18853477039 Could you let us know in more detail what you're trying to do? I am not able to reproduce this. If possible could you also attach some screenshots?

Thanks for all, I think this bug had been fixed.  What I want to say is  the position of the cursor I see does not match the actual position of the cursor, such as this is "1234|"   ,use | for cursor,   when I backspace  it may be "13|4"   instead of  "123|" . Now, I can't reproduce also. Finally, I wish you all good health
