### ISSUE TITLE
Postman desktop app hangs on POST request, keeps sending but no response, OS is Manjaro

### ISSUE THREAD

**Issue by sidartdesai** [a85/POSTMan-Chrome-Extension#8153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by coditva** [comment]
@sidartdesai Can you provide more context about this?

Also, can you try sending this request with `curl` with verbose logging `-v` and check if it's the server that's taking a long time to respond? If that's the case, you can set the `Request timeout` option in settings in Postman to timeout any request that takes a long time.

**Comment by sidartdesai** [comment]
@coditva Thanks for your response.

Managed to solve this.
Error : i had installed it from AUR 
Solution : uninstalled & reinstalled from snap

Worked..
