### ISSUE TITLE
Moving towards the next-generation URL processor

### ISSUE THREAD

**Issue by codenirvana** [a85/POSTMan-Chrome-Extension#8154]
<details><summary>Updates</summary>

* Enabled in [Postman Canary](https://www.postman.com/downloads/canary) since version `7.20.0-canary03`.
* In opt-in mode since Postman version `7.20.0`.
* In opt-out mode since Postman version `7.28.0`.
* Default since Postman version `8.0.0`.
</details>

We have introduced an improved URL processing system within Postman. This provides you the flexibility and compatibility with the ever-evolving landscape of HTTP clients and servers you requested us to help better manage. Additionally, it fixes a number of limitations of the present URL processor around the aspects of parsing and encoding.

Since the new URL processing system is a ground-up replacement of how Postman parses and encodes your URLs, we would love that you check whether your existing issues around URL parsing and encoding are addressed all while not creating any unintended side-effects.

## How to start using the new URL processor.
> Default URL processor in Postman v8.
<img width="1552" alt="postman-settings" src="https://user-images.githubusercontent.com/4865836/76343092-99977080-6325-11ea-9b37-0e824726847f.png">

## What do you get when you use the new processor?
**Address major encoding related concerns**
A host of issues around encoding, [such as disparity of expectations in URL encoding](https://github.com/postmanlabs/postman-app-support/issues/4555), is closer to being resolved. Encoding of the URL path and query parameters were the most contentious of all and almost all of them are now waiting for your feedback to be marked as resolved.

Issues which got addressed are as follows:

Issue | Fixes
-- | --
Variables with reserved characters are not resolved | #5779, #7316
Nested variables are not resolved | #7965
Line breaks are not handled properly | #4267
Trailing whitespaces gets trimmed | #6097
Encoding issues in path | #3469 #7432 #6126 #7155 #7300 #7123
Encoding issues in query params | #4555 #4171 #5752

**Seamless experience matching popular HTTP clients and browsers**
The new URL parser matches the encoding behavior of most prominent HTTP clients and browsers. Mainly, it adopts maximum parts of the [WHATWG (URL) standards](https://url.spec.whatwg.org/) that the world has come to like and agree upon. The new processor leverages the knowledge of your intents that it can gather from the user interface and provides the least ambiguous and forgiving URL parsing for the many obscure URLs that we have encountered. It also attempts to bridge the gap between what URL you enter in Postman UI and what is actually sent across the wire.

**Make requests to exotic API endpoints**
Equipped with full control of URL processing, we can now provide the unmatched ability to completely turn off encoding algorithms on URL path and query parameters. This is available as a setting alongside your requests and, as such, opens up the possibility for you to send requests to virtually the most stubborn or dated API servers and [debug endpoints that have encoding related issues](https://github.com/postmanlabs/postman-app-support/issues/4171).
<img width="968" alt="disabled-encoding" src="https://user-images.githubusercontent.com/4865836/76072995-ee05bd80-5fbe-11ea-8398-2615c17715e1.png">

**Making the best out of "variables" feature in Postman**
This new URL processor is aware of Postman Variables (which look like `{{this}}`) at its core. As such variable names that conflict with URL parsing are no longer an issue. Even the usage of nested variable names are now enabled in URLs.
- Resolves variables with [reserved characters](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) like `{{host#1}}` (Fixes https://github.com/postmanlabs/postman-app-support/issues/5779)
- Resolves nested variables like `{{api-{{version}}}}` (Fixes https://github.com/postmanlabs/postman-app-support/issues/7965)

## URL Encoding
URLs are permitted to only contain a certain range of characters. Any character falling outside of that range must be [encoded](https://en.wikipedia.org/wiki/Percent-encoding). How such characters are encoded, and which characters to encode depends entirely on where the character is located within the structure of the URL. Based on WHATWG URL Standard, Postman encodes the following characters in a URL component:

URL Component | Characters to Encode
-- | --
Path | `SPACE`, `"`, `<`, `>`, `#`, `?`, `{`, `}`, <code>`</code>
Query | `SPACE`, `"`, `#`, `&`, `'`, `<`, `=`, `>` 
User info | `SPACE`, `"`, `<`, `>`, `#`, `?`, `{`, `}`, `/`, `:`, `;`, `=`, `@`, `[`, `\`, `]`, `^`, `|`, <code>`</code>

## Some interesting new features that got added
- Better support for IPv6 in URLs
- Support for IP shorthand such as `127.1` for `127.0.0.1`
- Support for `\\` in the path for Windows compatibility
- Safer handling of multi-byte characters (emojis) and other multi-lingual character sets. (Fixes https://github.com/postmanlabs/postman-app-support/issues/4549)
- Better handling of newlines and whitespace characters. (Fixes https://github.com/postmanlabs/postman-app-support/issues/4267)

<details><summary>References </summary>

- [Postman URL Encoder](https://github.com/postmanlabs/postman-url-encoder)
- [Postman URL Parser](https://github.com/postmanlabs/postman-collection/blob/develop/lib/url-parse.js)
- [WhatWG URL Standard](https://url.spec.whatwg.org/)
</details>

Cheers 🎉

**Comment by kharmabum** [comment]
Got here via https://github.com/postmanlabs/postman-app-support/issues/4171

In the latest build of Postman on macOS as of this writing I'm experience a behavior where auto-url-encoding cannot be enabled (v7.36.0):

- If I have the next gen url parsing ON, and auto url encoding ON, I do not get auto url encoding
- If I have next gen url parsing OFF, I do not get auto url encoding.

Let me know if I can provide any additional characteristics or run tests for y'all locally.

**Comment by codenirvana** [comment]
@kharmabum Can you share an example URL with the encoding you are expecting?

**Comment by kharmabum** [comment]
@codenirvana 

### Actual
`http://localhost:8080/api/foo?asOf=2020-09-06T03:59:59+10` 

### Expected
`http://localhost:8080/api/foo?asOf=2020-09-06T03%3A59%3A59%2B10`

**Comment by kharmabum** [comment]
@codenirvana here's [a video](https://www.dropbox.com/s/de5x50li3lk6fs0/postman-example.mov?dl=0) of the behavior.
```
Postman for Mac
Version 7.36.0
OS X 18.7.0 / x64
```

**Comment by sufisaid** [comment]
Is "Use next generation URL processing" mandatory from version 8 because I don't see an option for disabling it? I'm using "{}" in my queries and now that I can't disable this option, requests can't pass through AWS API GW.
Do you have in plan to bring back this option so we could have control over it and enable/disable it when required?

**Comment by codenirvana** [comment]
@sufisaid Yes, this is the default since Postman v8.

We've seen a lot of [similar reports](https://github.com/postmanlabs/postman-app-support/issues/8791#issuecomment-661813107) _(check linked issues in this thread)_ regarding the query parameters encoding ever since we made this change. Sadly there's no common URL encoding standard that every client and programming language follows and being a debugging tool we can't enforce one.

That's why we are following the  [WHATWG (URL) standard](https://url.spec.whatwg.org/#percent-encoded-bytes) which is widely adopted in web browsers and modern programming languages. And most importantly, encodes only the reserved and restricted characters in a URL component.

According to the WHATWG standard, only the following ASCII characters in the query string needs to be encoded:
`SPACE`, `"`, `#`, `<`, `>`, and `'`.

Additionally, Postman's key-value query input encodes `&` and `=` characters automatically because in a query-param, these are the reserved characters as well. Anything else can be encoded by either:
1. Manually encoding additional characters
2. Highlight the text and right-click to encode the selection using the helper
![Screenshot 2020-07-21 at 5 25 33 PM](https://user-images.githubusercontent.com/4865836/88052150-70120f80-cb77-11ea-9c06-e8d2cfa0b373.png)
3. Add the following script as part of your Pre-request script to do the same:
```js
pm.request.url.query.each((q) => {
     q.update(encodeURIComponent(q.toString())) // or, encodeURI
});
```

If the workarounds discussed above didn't help or facing any other URL encoding or parsing related issue, please report a new bug.

Closing as this change is made default since Postman v8.
