### ISSUE TITLE
Did not receive reset password email

### ISSUE THREAD

**Issue by sindhususarla** [a85/POSTMan-Chrome-Extension#8155]
**Describe the bug**
I did not receive reset password email to sindhu.susarla@siriusxm.com

**To Reproduce**
I clicked on trouble signing in
But did not receive email

**Expected behavior**
Had to receive an email to reset pwd.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [most updated one]
 - OS: [windows]

**Comment by Raj-postman** [comment]
Hi @sindhususarla 

Checked it from our end and see that the reset email has been delivered to your inbox. Could you try resetting the password once again and see if you are able to locate it now?

If you are unable to find the email yet, please write to us at help@postman.com and we will help you with the same.

**Comment by sindhususarla** [comment]
Hello,

Found the email in junk folder. Thanks! You can close the ticket now.
