### ISSUE TITLE
Upload file support in GraphQL 

### ISSUE THREAD

**Issue by bipinct** [a85/POSTMan-Chrome-Extension#8156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sankalp0o** [comment]
@bipin000 can you elaborate on the problem you're facing?

**Comment by numaanashraf** [comment]
@bipin000 We are tracking this at #7072

**Comment by numaanashraf** [comment]
Duplicate of #7072
