### ISSUE TITLE
On small screens, collection page hides 2 primary sections

### ISSUE THREAD

**Issue by tristandenyer** [a85/POSTMan-Chrome-Extension#8158]
**Describe the bug**
When the user vies the collection page in a small viewport, the "How do I run this API collection?" and "New to Postman?" seconds disappear. The only left to do is "Download JSON".

This causes two problems:
— people viewing this on smaller viewports don't get buttons for the Postman app.
— Google little to nothing for SEO, and therefore Search Results Preview becomes so basic it almost looks broken / wrong (doesn't look like a legit Postman result, IMO). Reason is Google indexes web pages using the small / mobile breakpoints—which is where this page fails.

**To Reproduce**
1. Go to 'https://app.getpostman.com/view-collection/0911a7fefbc14ed2e4cb'
2. Resize browser window
3. See that the two sections listed above disappear. (Again, this is how Google views and indexes this page—with nothing on it.)

**Expected behavior**
All sections should be responsive and be presented to the visitor and Google. Even if the user is on their phone, we should show the buttons and handle the interaction in a way that informs the visitor that Postman is best viewed on a desktop, or something similar. We should not be hiding elements just based on screensize.

**Screenshots**
<img width="965" alt="Screen Shot 2020-03-07 at 11 13 10 PM" src="https://user-images.githubusercontent.com/4358288/76158425-7e7cf480-60ca-11ea-8167-1e934aee8835.png">
<img width="1445" alt="Screen Shot 2020-03-07 at 11 12 57 PM" src="https://user-images.githubusercontent.com/4358288/76158426-7fae2180-60ca-11ea-8edb-6b71494d5797.png">

**App information (please complete the following information):**
 - Not app-specific

**Additional context**

**Comment by DannyDainton** [comment]
Hey @tristandenyer / @preethammavin 

Is this still an issue with the latest version?

Not sure what this page is or how users are accessing this information, would either of you be able to provide some context?

**Comment by tristandenyer** [comment]
@DannyDainton I found this page by Googling "postman bigcommerce".
And it is still an issue.

**Comment by gitThingsDone** [comment]
We have deprecated the view-collection page now, this now redirects to the run-collection page, which works better with smaller screens too https://elements.getpostman.com/run-collection/0911a7fefbc14ed2e4cb
<img width="492" alt="image" src="https://user-images.githubusercontent.com/64534208/192959537-484bc33f-9c01-40bb-9006-a871d12f8b60.png">
