### ISSUE TITLE
Title tag and Description tag missing from collection web page

### ISSUE THREAD

**Issue by tristandenyer** [a85/POSTMan-Chrome-Extension#8159]
**Describe the bug**
The <title> and <meta name=”description” ...> tags are missing from the public collection pages. And as stated in #8158 we are hiding content on the small / mobile breakpoint, this leaves Google virtually nothing for the Search result, making the result not very engaging.

**To Reproduce**
1. Google search for "bigcommerce postman collection"
2. Scroll down until you see a short search result that says "No information is available for this page." with the postman URL.
3. Note how it looks not very inviting to click on.

**Expected behavior**
Public Collection pages' search results to be fleshed out using content provided by the collection. Converting the title of the collection from an h2 to h1 will help. Using that title in the title tag as "[title_of_collection] | Postman Collection" would help. Using the collection description in the description metatag would help. And fixing #8158 would help give Google more content for the search result and not think the page is virtually empty.

**Screenshots**
<img width="799" alt="Screen Shot 2020-03-07 at 11 07 48 PM" src="https://user-images.githubusercontent.com/4358288/76158558-dec06600-60cb-11ea-9fbc-a7d17ec27918.png">

**App information (please complete the following information):**
 - Postman public collection web pages

**Additional context**

**Comment by sony-mathew** [comment]
Hey @tristandenyer 
We've been continuously improving our documentation to better serve you. Regarding your issue, this is no longer there with the latest versions of the app.

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
