### ISSUE TITLE
My collection just disappeared.

### ISSUE THREAD

**Issue by abeal-hottomali** [a85/POSTMan-Chrome-Extension#8161]
I've been getting repeated warnings in the Postman app that my collection was approaching the size where it would exceed the allowable size for data sharing for free accounts.

What I expected to happen when I exceeded this limit was I would get a notification that my collection could no longer be shared properly.

What actually happened is my collection entirely disappeared.  I now have "ARCHIVED COLLECTIONS (1)" at the bottom left, linking to https://hottomali.postman.co/usage/archive, where I get to request to get my data back.     This occurred immediately after I added a new request, so I believe it is directly related to collection sharing size.

Running Postman version Version 7.19.1

**Comment by abeal-hottomali** [comment]
Also, now seeing this:

![image](https://user-images.githubusercontent.com/48416080/76265513-ebef6900-6221-11ea-888b-4b88f75342e8.png)

**Comment by xk0der** [comment]
Hey @abeal-hottomali , the limitation [only applies to free plan when sharing](https://learning.postman.com/docs/postman/collaboration/collaboration-intro/#how-archiving-works) within "Team workspaces". 

Follow the steps listed here to recover your archived-collections:
https://learning.postman.com/docs/postman/collaboration/collaboration-intro/#recovering-your-archived-collections

Alternatively, download a dump of all your data from the app, as described here: https://learning.postman.com/docs/postman/collections/data-formats/#data-dumps (_Make sure to select ".. all data .." option_)
Next, [import](https://learning.postman.com/docs/postman/collections/data-formats/#importing-postman-data) this dump into a personal workspace (preferably a [new personal workspace](https://learning.postman.com/docs/postman/workspaces/creating-workspaces/))

**Comment by abeal-hottomali** [comment]
Thank you for the response -  I've recovered my collection, but I still believe this issue stands.  I've no complaint with Postman having a paid support tier, but having my collection completely disappear out from under me and forcing me to re-import it from archive to get it back after I added a new request was very upsetting.  It's the behaviour that Postman exhibits for free tier when you exceed the quota threshold that I think should be revisited.

**Comment by xk0der** [comment]
@abeal-hottomali agree! 

- Maybe there should be a an in-app mechanism to restore archived collection to a personal workspace, makes it a one-click restore compared to a having to manually export and import it back.
- Or maybe not even archive it! Move the collection to a personal workspace when it exceeds team workspace limits, call the workspace "Overage Workspace" / "Team Archived Collections"?

Just throwing some ideas out there :)

**Comment by preethammavin** [comment]
Hey, We appreciate the feedback and have noted for future improvements. We do communicate that some of your requests would be archived once you have breached the limit and also provide ample time for the user to stay within the limit or upgrade.
