### ISSUE TITLE
Resource usage shows more integrations than we have

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#8165]
**Describe the bug**
In our Resource Usage we see that 66 integrations are configured, however after going through all workspaces, could only find 56. 

**Expected behavior**
The amount of integrations in Resource Usages should equal the actual amount of integrations. There also should be a way to view all integrations in one place.

**Comment by abhijitkane** [comment]
@VicKetchup That's odd - can you email us at help-at-getpostman-dot-com from your registered email? We'll check the integrations at our end and get back to you.

**Comment by VicKetchup** [comment]
@abhijitkane Not sure if this is a coincidence, however after deleting some integrations that we deemed unnecessary, the count now matches the amount that we have configured. Will keep this open in case there is some issue that still needs to be fixed, however all good on our side now.

**Comment by abhijitkane** [comment]
Closing as a few issues around this were fixed. Feel free to reopen if you continue to see this.
