### ISSUE TITLE
Cannot access Secure cookies programmatically using Cookie Jar via Pre-Request Script

### ISSUE THREAD

**Issue by jeffjenk** [a85/POSTMan-Chrome-Extension#8168]
**Describe the bug**
I used the Interceptor to access some cookies from a web app I am testing. I can see the cookies getting correctly set in Postman and I have whitelisted the domain so that I can access them programmatically. When I try to access them with a script like:

```Javascript
 const cookieJar = pm.cookies.jar();
 cookieJar.getAll("domain.com", function(error, cookies) {
     console.log("error: ", error);
     console.log("cookies: ", cookies);
 });
```
I can access the cookies set for the domain but if the cookie has the `Secure` flag then I can not access it: 
`cookie_name=COOKIE_VAL; path=/; domain=domain.com; Secure;`

**To Reproduce**
1. Add a cookie to the Cookie interface
![image](https://user-images.githubusercontent.com/936604/76387674-2ebf5700-6370-11ea-8377-af3fe31a32c0.png)

2. Make sure the domain is whitelisted so cookies can be accessed programmatically
![image](https://user-images.githubusercontent.com/936604/76387434-9aed8b00-636f-11ea-9c51-e87a624ecdcd.png)

3. Add `Secure` flag to the cookie
![image](https://user-images.githubusercontent.com/936604/76387402-814c4380-636f-11ea-8299-7a5c09d97d67.png)

4. Run test script above in Pre-Request Script window
![image](https://user-images.githubusercontent.com/936604/76387488-bce70d80-636f-11ea-9151-8588633b1e50.png)

5. Observe cookie is not outputted to console if `Secure` flag is set
![image](https://user-images.githubusercontent.com/936604/76387510-d0927400-636f-11ea-9694-eb5cec666296.png)

6. Remove `Secure` flag and rerun script
![image](https://user-images.githubusercontent.com/936604/76387547-e2741700-636f-11ea-9dbd-a0987424ba1d.png)

7. Observe cookie is printed to console if `Secure` flag is not set
![image](https://user-images.githubusercontent.com/936604/76387595-f881d780-636f-11ea-825a-877d25e62736.png)

**Expected behavior**
Cookies with `Secure` flag should still be accessible via scripts.

**App information (please complete the following information):**
 - App Type Native
 - Postman Version 7.20.0
 - OS: Windows

**Comment by codenirvana** [comment]
@jeffjenk I hope changing `"domain.com"` to `"https://domain.com"` fixes your issue! 😄 

The first argument takes the URL and responds with the cookies which are accessible by it. If the protocol is missing, it defaults to `http`.

You can either add the `https` protocol manually or pass the URL as `pm.request.url` to re-use the same request URL.

**Comment by jeffjenk** [comment]
Hi @codenirvana OMG thank you that makes perfect sense and is working for me now. Thank you for such a quick response.

**Comment by jeffjenk** [comment]
@codenirvana this is slightly related, while i have you, can I access `HttpOnly` cookies via scripts?

**Comment by codenirvana** [comment]
@jeffjenk Yes.

**Comment by pasha-github** [comment]
Hello @codenirvana , I am still seeing this issue despite using `pm.request.url` to get the url automatically. I am using postman client v9.9.3. I have provided the script and associated error below -

**Script**
```
const cookiejar = pm.cookies.jar();
cookiejar.clear(pm.request.url, function (error) {
    if(error)
    console.log("Error Clearing Cookies: "+error);
    else
    console.log("Cookies cleared succesfully");

})
```


**Error**
``` 
Error: CookieStore: programmatic access to "anypoint.mulesoft.com" is denied 
```
Here is the cookie info:
``` _csrf=<Cookie Value>; Path=/; Secure; HttpOnly; ```

**Url is -** 
``` https://anypoint.mulesoft.com/accounts/login ```

**Expected behavior**
Cookies should be cleared.

**App information** 

App Type - Native (Desktop client)
Postman Version 9.9.3.
OS: Windows

**Comment by codenirvana** [comment]
@pasha-github You need to first whitelist the domain for programmatic cookie access.

<img width="773" alt="Screenshot 2022-01-20 at 9 08 44 AM" src="https://user-images.githubusercontent.com/4865836/150269328-064fa2cf-4549-47ef-836f-c7cad7ae2587.png">
<img width="761" alt="Screenshot 2022-01-20 at 9 09 49 AM" src="https://user-images.githubusercontent.com/4865836/150269336-2b01abc6-2fba-47b5-9a5e-494cbf0d3e82.png">

**Comment by pasha-github** [comment]
Appreciate the quick response, that helped. While I was aware about the domain whitelisting step, I figured that I was doing it incorrectly which caused the issue. The screenshots were very helpful. Thanks Again!!!

**Comment by fedulovivan** [comment]
There is an issue, still. With HttpOnly=false and Secure=true cookie. Even with whitelisted domain, Im not able to read required cookie with **pm.cookies.get** API. only JAR-based API is working.
so instead of using this (**not working!**):
```js
 pm.request.headers.add({
   key: "X-CSRF-TOKEN",
   value: pm.cookies.get("CSRF-TOKEN")
 })
```
I have to use this (**works ok**):
```js
const cookieJar = pm.cookies.jar();
cookieJar.get("https://local.domain.net", "CSRF-TOKEN", function(error, value) {
    if (error) console.log(error);
    pm.request.headers.add({ key: "X-CSRF-TOKEN", value });
});
```

**Comment by ValerioJiang** [comment]
> [@pasha-github](https://github.com/pasha-github) You need to first whitelist the domain for programmatic cookie access.
> 
> <img alt="Screenshot 2022-01-20 at 9 08 44 AM" width="773" src="https://user-images.githubusercontent.com/4865836/150269328-064fa2cf-4549-47ef-836f-c7cad7ae2587.png">
> 
> <img alt="Screenshot 2022-01-20 at 9 09 49 AM" width="761" src="https://user-images.githubusercontent.com/4865836/150269336-2b01abc6-2fba-47b5-9a5e-494cbf0d3e82.png">

Thanks it worked, i got the same problem testing Mulesoft APIs
