### ISSUE TITLE
Issue with the favicon upload

### ISSUE THREAD

**Issue by amigobg** [a85/POSTMan-Chrome-Extension#8169]
**Describe the bug**
The issue comes when trying to uploading favicon from the "Team Settings". 

**To Reproduce**
1. Go to 'General -> Settings'
2. Click on 'Favicon'
3. Scroll down to 'Upload from computer'
4. Something went wrong
There was an error uploading your image. Our engineers have been notified and we should have this fixed shortly.

**App information (please complete the following information):**
 - App Type [e.g. Firefox ]

**Additional context**
Something went wrong
There was an error uploading your image. Our engineers have been notified and we should have this fixed shortly.

**Comment by abhijitkane** [comment]
@amigobg While we investigate this, can you try the favicon upload from a different browser or an incognito/private tab?

**Comment by amigobg** [comment]
> @amigobg While we investigate this, can you try the favicon upload from a different browser or an incognito/private tab?

It is the same from Chrome, I was tried in the incognito tab also (OS: Linux Mint).

**Comment by smitit173** [comment]
hey @amigobg ,
Could you please share a developer tools screenshot of the network tab.
Also could you let me know the format of the image that you're trying to upload

Cheers,
Smit

**Comment by xk0der** [comment]
@amigobg do check the image dimensions that you are trying to upload.

My testing shows that anything below `100x100` pixels in dimensions works!

Try scaling the image to less than `100x100` pixels in dimensions and see if that helps (I've tested `94x94` and `99x99` - both had worked!)

**Comment by kepikoi** [comment]
It doesn't work for me. Uploading a 90x90 favicon.ico (jpg compression, 7KB) via an up-to-date chrome in incognito tab.

Im getting this error `{"error":{"message":"Upload preset must be specified when using unsigned upload"}}` from https://api.cloudinary.com/v1_1/postman/image/upload.

**Comment by DannyDainton** [comment]
Hey @kepikoi 

I'm going to close this issue as it appears to be fixed - If you're still having an issue with it, would you be able to provide the `.ico` file so that we can take a look for our side.
