### ISSUE TITLE
Postman bootcamp doesn't finish loading

### ISSUE THREAD

**Issue by deepakpathania-zz** [a85/POSTMan-Chrome-Extension#8171]
**Describe the bug**
Clicking on Postman Bootcamp opens a new tab but it gets stuck in the loading state. (The API to fetch all lessons for a skill is not working.)

**To Reproduce**
1. Go to any workspace
2. Click on Bootcamp at the bottom
3. App gets stuck in the loading state.

**Expected behavior**
Postman Bootcamp should load.

**Screenshots**
![Screenshot 2020-03-12 at 12 21 53 PM](https://user-images.githubusercontent.com/15071438/76495291-8fc45900-645c-11ea-84e1-cc4cf94bfa61.png)

**App information (please complete the following information):**
 - App Type - Native
 - Postman Version - 7.17.0
 - OS: macOS Catalina v10.15.1

**Comment by sivcan** [comment]
@deepakpathania I am unable to reproduce this issue at my end.
Did you try to quit the app and reload it? Is it failing for you consistently?

Additionally, can you please update to the latest version (7.20.0) as of today and try it out?

**Comment by deepakpathania-zz** [comment]
Failing consistently. Updated the app to 7.20.0, still failing.
![Screenshot 2020-03-12 at 3 33 30 PM](https://user-images.githubusercontent.com/15071438/76509971-d921a200-6476-11ea-9f92-95e1c6be75ed.png)

User id - 7164605

**Comment by sivcan** [comment]
@deepakpathania Can you confirm whether this is regarding a proxy issue at your end or not?
Let us know, thanks.

**Comment by prashantagarwal** [comment]
@deepakpathania Were you able to reproduce this on a different network?

**Comment by deepakpathania-zz** [comment]
@prashantagarwal Yes, not working on a different network either.

As seen above in the screenshot, getting a 304 for the fetch skill API, please let me know if you need additional context.

**Comment by prashantagarwal** [comment]
@deepakpathania Is it still showing error for you?. We haven't been able to reproduce this at our end.

**Comment by prashantagarwal** [comment]
@deepakpathania If you are still facing this issue please let us know. As this issue appears to be happening only with you, I would recommend if you could check your network/firewall settings once.
