### ISSUE TITLE
Links in Settings>About point to http://undefined

### ISSUE THREAD

**Issue by joh-braeuer** [a85/POSTMan-Chrome-Extension#8172]
In the Windows desktop application of Postman (v7.20.0) all links in the "About" page of the Settings are pointing to "http://undefined".

**To Reproduce**
1. Click on 'File' > 'Settings'
2. Click on the last tab: 'About'
3. Click on any of the six links

**App information:**
 - App Type: 64 bit Desktop Application for Windows
 - Postman Version: 7.20.0
 - OS: Windows 10

**Comment by joh-braeuer** [comment]
My standard browser is Firefox 74.0 (latest)

**Comment by kamalaknn** [comment]
Thanks @joh-braeuer 

We are able to reproduce this issue. We will be pushing a fix for soon.

**Comment by devanSAGA** [comment]
Thanks again @joh-braeuer for reporting this. We have resolved this issue in Postman 7.20.1.
