### ISSUE TITLE
Please convert the format of imported graphql request params in the clipboard

### ISSUE THREAD

**Issue by automatiche** [a85/POSTMan-Chrome-Extension#8175]
when i copied a request text as ‘Copy as cURL’ from chrome.devtools.network，params, eg. ‘ObjID!’ will be escaped to ObjID\u0021. i import it as 'Paste Raw Text’ and sent request, then i got a error message "Unknown type…”. could you convert it into the correct format?

**Comment by abhijitkane** [comment]
@automatiche Thanks - can you post a sample curl command that you're seeing this with, and a screenshot of the error you're seeing?

**Comment by abhijitkane** [comment]
@automatiche Closing this for lack of a response. Feel free to reopen if you see this again.

**Comment by splinter89** [comment]
@abhijitkane Please see https://github.com/postmanlabs/postman-app-support/issues/8505
It contains all the details for this pesky issue.
