### ISSUE TITLE
Monitor list returned by the Postman API includes deleted monitors

### ISSUE THREAD

**Issue by ArjunSingh-PM** [a85/POSTMan-Chrome-Extension#8176]
**Describe the bug**
Monitor list returned by the Postman API includes deleted monitors.  
When trying to access these deleted monitors, monitor does not exist error is returned.

**To Reproduce**
1. Create a monitor 
2. Delete the monitor
3. Retrieve monitor listing via the Postman API
4. The list includes the deleted monitor 

**Expected behavior**
Deleted monitors should not be included in the monitor listing

**Comment by godfrzero** [comment]
I've been unable to reproduce this issue, both by deleting monitors via the Postman API and via the web Dashboard.

**Comment by ArjunSingh-PM** [comment]
@VicKetchup could you please elaborate on the steps you follow that results in a list of monitors that includes deleted monitors?

**Comment by VicKetchup** [comment]
@godfrzero @ArjunSingh-PM Unfortunately I cannot provide the exact details of how to reproduce this, as I only realised this was an issue by looking at the logs of our Lambda that goes through each monitor. I can provide uids of the monitors have this issue if that would help.

**Comment by godfrzero** [comment]
The monitors which continue to show up in the listing response, are they monitors which were deleted via the Postman API? Is it possible that the monitor was paused instead of being deleted?

**Comment by VicKetchup** [comment]
@godfrzero The monitors were deleted using the web dashboard and cannot be seen anywhere besides the API response. Also a paused monitor would not return 
`{
    "error": {
        "name": "instanceNotFoundError",
        "message": "The specified monitor does not exist."
    }
}`

**Comment by Hayk-S** [comment]
Hi @VicKetchup , I was not able to reproduce this issue following the steps you described. Are you still facing this issue ?

**Comment by VicKetchup** [comment]
@Hayk-S It looks like some change was implemented, as the error now reads:
`{"error":{"name":"forbiddenError","message":"You don't have access to this monitor."}}`
However there are still monitors on API that are no longer present anywhere else.

**Comment by VicKetchup** [comment]
Shall I send email with all the IDs of the monitors that we are having issue with?

**Comment by charlie-postman** [comment]
We closed the issue as the issue can't be reproduced.
