### ISSUE TITLE
Postman takes the wrong "code" in OAuth2.0 Access Code grant flow

### ISSUE THREAD

**Issue by leehambley** [a85/POSTMan-Chrome-Extension#8177]
**Describe the bug**

Cross-posting from stackoverflow at the request of Postman staffer @DannyDainton. The grant flow mistakenly sends some random completely unrelated data for `code` to the OAuth2 token exchange endpoint:

An extremely thorough description is here https://stackoverflow.com/questions/60668411/

In short my server issues codes which look like:

`3b9ac786-f9d1-40f9-b884-35e17b2fa756.70a3be09-8edf-47ed-9803-d08550a07faa.8794bba2-6f2b-4512-8bd7-6d5073852d1c`

And Postman is picking up something like:

`4/xgFPM8rkZXA1pWguPMHPKg8GS3BrI7whtmSq2U2K4_4Cy62m10y2l3IQp3KuiLRyaLaZWKCUiGJGEWVJ9K4zcTc`

Stepping through the process in curl shows the difference, and in curl/netcat it works, postman as a black-box is just doing something strange inside which I cannot effectively debug.

**To Reproduce**
1. Use the Oauth2.0 "Access Code" grant flow with Keycloak 9.0.0 hosted under Docker-Compose
2. Sign in with Google IdP and observe it blows up with invalid code error (the codes look wrong)
3. If signing in with a password observe that it works

**Expected behavior**
It should use the right code, and ideally the postman console would make it MUCH easier to see what URL was opened in the browser flow window, and what responses were received etc. 

I got some insights from using a SOCKS proxy for my whole network, and running postman from the CLI to get more logging into, and generally debugging at the network level, but I'm still not certain what response postman 

**App information (please complete the following information):**
 - App Type: Flatpak linux fedora (see also my SO post)
 - Postman Version 7.20.0
 - OS:Fedora 31 (or whatever is newest)

**Additional context**

I *suspect* (but don't know how this is possible) that the code with the completely wrong format, is maybe the code that Google's OAuth flow yields, although I'm authenticating against my own OAuth2 server with Google as an IdP, so I don't really know, it's too hard to get logs to see what's happening.

**Comment by vikiCoder** [comment]
Possible duplicate of https://github.com/postmanlabs/postman-app-support/issues/7105

**Comment by leehambley** [comment]
I may be able to "confirm" that this problem is indeed a dupe of #7105 because now that my SSO is hosted on another domain, and not localhost, I cannot reproduce the issue. 

I suggest to close this, and I'll make a similar comment on the SO post.
