### ISSUE TITLE
Wrong encoding in the Postman app

### ISSUE THREAD

**Issue by dengayevskiy** [a85/POSTMan-Chrome-Extension#818]
Hi guys!

I have an issue with wrong encoding in the Postman app. 
This is how my request looks like in the ext:
![2014-11-18_16-59-22](https://cloud.githubusercontent.com/assets/7139091/5089550/d7f5102e-6f44-11e4-9a69-c38cea27724b.png)
And this is how it looks like in the app:
![2014-11-18_16-59-13](https://cloud.githubusercontent.com/assets/7139091/5089566/f3d391b2-6f44-11e4-96c2-f1be7d0eb4e8.png)

**Comment by adorsett** [comment]
I have the same issue, it's breaking my ability to test a third-party API using Postman.  If I write a quick python app that uses OAuth1 and I don't percent-encode the realm, it works just fine.  If I try it via Postman which percent-encodes that realm, the server returns a 401.  Can we make this encoding a configurable option to account for servers that may not be spec compliant?
