### ISSUE TITLE
Postman generates the header Content-Length without body

### ISSUE THREAD

**Issue by leofrances-extflowbird** [a85/POSTMan-Chrome-Extension#8181]
**Describe the bug**
Postman generates the header Content-Length: 0 when the body is not set (no header Content-Type) for the DELETE verb. This is a problem for our server because the requests with the header Content-Length are considered with a body. But it is not the case. So, to avoid this issue, we must fill the header Content-Typewhile there is no body.

**To Reproduce**
1. Send a DELETE request without the header Content-Type
2. Postman generates the header Content-Length: 0

**Expected behavior**
We would like the Postman does not generate the header Content-Length when the body and the header Content-Type are not set.

**App information**
 - App Type: Native App
 - Postman Version: 7.20.1
 - OS: Windows 10

**Comment by appurva21** [comment]
Hey @leofrances-extflowbird, we have fixed this issue in the latest App release `v7.21.0` 🎉 . 

We have also added more control around the automatically added headers with this release which will allow you to choose the exact headers that you want to send with the request. Refer the documentation [here](https://learning.postman.com/docs/postman/sending-api-requests/requests/#auto-generated-headers) for more insights.

I am closing this issue, but feel free to reopen it in case the issue still persists.

**Comment by leofrances-extflowbird** [comment]
@appurva21 Thank you so much!
