### ISSUE TITLE
Clarify which resources reset monthly

### ISSUE THREAD

**Issue by SabriH10** [a85/POSTMan-Chrome-Extension#8182]
**Is your feature request related to a problem? Please describe.**
Considering the total number of API's created is fixed, it would help to clarify which resources are reset monthly and which aren't.

**Describe the solution you'd like**
Ideally, more clarity on which resources reset monthly. This could be in the form of a special information message or the structure of how the information is presented.

**Describe alternatives you've considered**

Updating the Docs to reflect this information.

**Additional context**

<img width="337" alt="Screen Shot 2020-03-16 at 11 37 23 AM" src="https://user-images.githubusercontent.com/62078336/76775146-4f761b00-677b-11ea-904b-71361b968a90.png">
as well as https://web.postman.co/usage

**Comment by sankalp0o** [comment]
@BrandonGordon126 perhaps we can tweak the labels here?

**Comment by DannyDainton** [comment]
This section of the platform has been updated since the issue was raised with several of the items mentioned being removed.

I'm going to close this out but if this is still a confusing area for users we can look to reopen this again.
