### ISSUE TITLE
Support Multiple Snapshots Per Collection

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#8183]
It would be nice to be able to support multiple snapshots per collection.  For example, we could have different versions of the collection for each release in different snapshots.  Then Newman could be used to point to the right version of the collection based on the release.

**Comment by vvs11** [comment]
@jcald1 we support versioning of collections. Please go through the documentation and see if it satisfies your use case.
https://learning.postman.com/docs/postman/collections/version-control-for-collections/

https://learning.postman.com/docs/postman/design-and-develop-apis/versioning-an-api/

**Comment by vvs11** [comment]
@jcald1  Closing the issue for now. If you have more questions, please post them on our community:
https://community.getpostman.com/ 
We will definitely assist you.
