### ISSUE TITLE
SSL Handshake error with new Postman for Windows Version 7.20.0 win32

### ISSUE THREAD

**Issue by mzarify** [a85/POSTMan-Chrome-Extension#8184]
**Describe the bug**
Since new update of Postman (Version 7.20.0 win32) we get SSL handshake error while hitting our APIs. CRT,KEY, PFX files and Passphrase are all good. So we have installed back the older version, and then we could hit our API again.

**To Reproduce**
1. Try to hit a service behind SSL 
2. From Settings -->Certificates, add all required CRT,KEY, PFX files and Passphrase
3. Hit the API
4. You will get error: "Could not get any response
There was an error connecting to http://{{url}}"

**Expected behavior**
To hit API and get a response.

**Screenshots**
Attached
![image](https://user-images.githubusercontent.com/6429703/76852295-448abb80-684b-11ea-83ee-2f5730e51cb2.png)

**App information (please complete the following information):**
 - Native App
 - Postman for Windows Version 7.20.0 win32
 - Windows 10

**Comment by codenirvana** [comment]
@mzarify What's the error message in the [Postman Console](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/#for-the-native-app-for-mac--windows--linux) (CTRL + ALT + C).

Also, does turning off the "SSL certificate verification" form the settings fixes this issue?

**Comment by mzarify** [comment]
POST {{url}}/
Error: Invalid URI "http:///%7B%7Burl%7D%7D/..."
Warning: This request did not get sent completely and might not have all the required system headers

**Comment by mzarify** [comment]
We also turned OFF/ON SSL certificate verification, and it didnt help

**Comment by codenirvana** [comment]
@mzarify I see this is not an issue with the SSL certificate.

The problem here is, the variable `{{url}}` is unresolved.
Check if you have the required environment selected before making the request.

**Comment by mzarify** [comment]
@codenirvana Sorry Retry now with correct URL :)
POST https://OUR URL
Error: Client network socket disconnected before secure TLS connection was established
Warning: This request did not get sent completely and might not have all the required system headers

**Comment by mzarify** [comment]
![image](https://user-images.githubusercontent.com/6429703/76853705-1fe41300-684e-11ea-90b3-aac1bef6801e.png)

**Comment by morrisond91** [comment]
I am getting this issue too

Turning SSL certificate verification off fixes the issue, but this is not a fix for me but more than a work around.

The website certificate was recently replaced with new cert from GlobalSign

![image](https://user-images.githubusercontent.com/35499920/76947705-ee2a8500-68fd-11ea-955e-f521c015d271.png)

**Comment by codenirvana** [comment]
@mzarify This is probably because of the proxy setup.
Check if turning off the global and system proxy from settings fixes this issue?

**Comment by mzarify** [comment]
@codenirvana Thanks for the reply. It didn't solve the issue.

**Comment by ronhks** [comment]
We experienced the same, with 7.21.1. It doesn't matter if we disable the SLL verification to off or not. We got SSL handshake error.
I works well with 6.7.4. So we downgraded to it:
https://dl.pstmn.io/download/version/6.7.4/osx64
https://dl.pstmn.io/download/version/6.7.4/win64

**Comment by amanrique1** [comment]
I had the same error, are you sure that this service use https? check that on the request

**Comment by DannyDainton** [comment]
Hey 👋🏻 

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
