### ISSUE TITLE
Shared request count incorrect

### ISSUE THREAD

**Issue by karthiks3000** [a85/POSTMan-Chrome-Extension#8187]
**Describe the bug**
I have a single shared workspace with only 1 other team mate and we have 1 collection with 9 requests shared. The Shared Requests count however is showing 18/25.
It was correctly showing 9/25 as long as I was the only one on the team. The minute my team mate joined, the count doubled, even though the api count is only 9.

**Expected behavior**
Since there are only 9 apis shared, the shared request count should be 9/25

**Screenshots**
![postman](https://user-images.githubusercontent.com/13357707/76866355-6891d100-683a-11ea-814e-fad9443a6b25.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.20.1]
 - OS: [macOS High Sierra 10.13.6]

**Comment by ankit-m** [comment]
@karthiks3000 can you check if any other team workspace has some other collection?

**Comment by karthiks3000** [comment]
No this is our only workspace that has a collection. The "Team Workspace" is empty.

![Screen Shot 2020-03-17 at 12 28 03 PM](https://user-images.githubusercontent.com/13357707/76878265-f83f7b80-684a-11ea-87e1-faba7692ff5b.png)

**Comment by stcalica** [comment]
Hi @karthiks3000  can you submit a ticket below so we can work through this issue together? 
https://www.postman.com/support

**Comment by karthiks3000** [comment]
@stcalica I've submitted a ticket - #48044

**Comment by Mechanicalkeyboard** [comment]
Unable to reproduce this issue on the latest version of postman app. If this issue is still present, please reopen and we will investigate further.
