### ISSUE TITLE
Incorrect changelog entry for request body

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#8189]
**Describe the bug**
Request body changelog shows 3 changes and an empty array when only text was added.

**To Reproduce**
1. Create a new collection.
2. Create a new request.
3. Open request and add raw (text) body.
4. Open collection changelog.

Observe
![image](https://user-images.githubusercontent.com/9019878/76876900-a291c000-6898-11ea-82a5-93f33f7ac71b.png)

It shows that I made 3 changes, but I only made 1.

**Expected behavior**
Do not show empty array and show only 1 change.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.20
 - OS: macOS Catalina

**Comment by DannyDainton** [comment]
Hey @ankit-m,

Is this still an issue in the latest version?

**Comment by ankit-m** [comment]
Issue fixed.
