### ISSUE TITLE
Unable to submit pull request against read only collection

### ISSUE THREAD

**Issue by jpzabriskie** [a85/POSTMan-Chrome-Extension#8190]
**Describe the bug**
While attempting to submit a pull request against a read only collection I get the following error 'something went wrong, unable to perform this action for pull requests'

after spending some time looking into it I found the following using devtools under the response tab:
{"errors":[{"message":"Unable to perform this action for pull request.","locations":[{"line":2,"column":3}],"path":["createPullRequest"],"extensions":{"code":"**FORBIDDEN**","exception":{"title":"Something went wrong","code":403}}}],"data":{"createPullRequest":null}}

This lead me to attempting a pull request against a collection I had modify rights to which worked as I expect it would

**To Reproduce**
1. Fork a collection from a team workspace to your local workspace
2. make some changes
3. From the three dots on your collection select 'Create Pull Request'
4. Fill out the form and push the 'Create Pull Request button

**Expected behavior**
I Expect to be able to submit a pull request against a collection I have read only access to. As long as the reviewer has modify right this should work as the reviewer is the one merging the collections(?)

**Screenshots**
![postman-defect](https://user-images.githubusercontent.com/35781306/76908622-c5a77a00-686e-11ea-9cc3-3e0a2a62d0dd.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
Attempted in both MacOS app and Chrome
 - Postman Version [e.g. 6.0.1]
App Version: 7.20.1
 - OS: [e.g. macOS High Sierra 10.13.2]
macOS: 10.13.6

**Comment by ankit-m** [comment]
@jpzabriskie 

The collection was forked in your personal workspace and the destination collection was in a team workspace. When you create a PR, the reviewers need view access on the forked collection to see the diff. Hence, you are seeing the error.

We are improving error messages, adding inline messages while creating forks and adding the ability to share the forked collection before creating a pull request. These improvements will help in better communication of such states.

If there is anything else, please feel free to reopen this ticket.

**Comment by jpzabriskie** [comment]
@ankit-m Thanks, I think that would explain a few different things I was seeing.
