### ISSUE TITLE
Allow for CSV upload for team invites

### ISSUE THREAD

**Issue by yiantseng** [a85/POSTMan-Chrome-Extension#8192]
**Is your feature request related to a problem? Please describe.**
There is no way to mass invite a group of people via CSV to a team, similar to how you can mass invite via CSV to a workspace.

**Describe the solution you'd like**
Add an option of uploading a CSV to invite users. This would allow users to join the team without forcing them into a workspace.

**Describe alternatives you've considered**
Workaround is to upload a CSV and invite them to a workspace

**Additional context**

**Comment by ArjunSingh-PM** [comment]
We have the feature to invite users to a team or a workspace via a CSV file.
