### ISSUE TITLE
Monitor Test Results do not match actual run

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#8197]
**Describe the bug**
Today our spec website went down causing a test failure and error on every request. It seems like Monitors are not able to handle that amount of failures/errors as the Test Results tab displays only few of the requests that were done (if you look at the logs, all the requests are present there).

**To Reproduce**
1. Create a monitor with a test that errors and fails on every request
2. Run the monitor
3. Test Results will only have a few requests, while Log will show everything

**Expected behavior**
Test Results should show all the requests that were made and all the tests that were run and their results.

**Screenshots**
As you can see in the image below, only one failure is reported even though there were 36:
![image](https://user-images.githubusercontent.com/43671684/77059628-21891480-69cf-11ea-9739-c36c804f3f4a.png)

**App information (please complete the following information):**
N/A - Monitors

**Comment by godfrzero** [comment]
@VicKetchup Are the results displayed on the monitoring dashboard accurate? I'm trying to isolate the scope of the problem.

**Comment by VicKetchup** [comment]
@godfrzero No, on the monitoring dashboards only a couple of requests are shown, for the Slack integration shown above, we only had 4 requests displayed: 
![image](https://user-images.githubusercontent.com/43671684/77070380-0378df80-69e2-11ea-91f4-b63be8fa8dca.png)

**Comment by VicKetchup** [comment]
Is there any update on this issue? Now this is happening even for the runs where a few tests failed, so it's really hard to keep track of and understand the issues.
![image](https://user-images.githubusercontent.com/43671684/83745878-25374980-a656-11ea-9eb7-a5ec5fc34f75.png)

**Comment by aman-postman** [comment]
@VicKetchup Can you please check and let us know if you are still facing this problem?

**Comment by VicKetchup** [comment]
@aman-postman Yes, this is still the case unfortunately :(

**Comment by VicKetchup** [comment]
@aman-postman @godfrzero Today got all of the failures listed in Slack and all results shown on the dashboard :)

**Comment by ArjunSingh-PM** [comment]
@VicKetchup Glad to know that this issue is resolved for you!
