### ISSUE TITLE
Order of query parameters in app doesn't match order on docs page

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8199]
**Describe the bug**
User reported that query parameters have a different order in-app than on the docs page for the Collection.

**To Reproduce**
_Support not able to reproduce_

**Expected behavior**
The order of query parameters matches what is shown in the app.

**App information (please complete the following information):**
 - App Type: Native app, docs page
 - Postman Version: 7.20.0
 - OS: Windows

**Additional context**
See internal notes

**Comment by godfrzero** [comment]
@JP-from-Postman If the collection is fetched via the Postman API, are the parameters in the correct order?

**Comment by JP-from-Postman** [comment]
@godfrzero I don't have access to the collection connected to this bug. I'll inquire with the user who reported it.

**Comment by godfrzero** [comment]
Closing this ticket for now, will reopen if we get additional information or new reports.
