### ISSUE TITLE
Missing body when importing CURL with data-raw body defined in Canary 7.21.0-canary03 

### ISSUE THREAD

**Issue by filfreire** [a85/POSTMan-Chrome-Extension#8204]
**Describe the bug**
In Postman Canary 7.21.0-canary03 (for MacOS), when importing `curl` requests with body as `data-raw` flag, the body ends up missing in Postman.

Same as issue https://github.com/postmanlabs/postman-app-support/issues/7895 (but for latest canary version)

**To Reproduce**
1. Import with "Paste Raw Text" the following `curl`:
```
curl --location --request POST 'https://test-URL.test' --header 'x-api-key: thisisanapikey' --header 'Accept-Language: en-US' --header 'Content-Type: application/json' --header 'User-Agent: testuser/test' --data-raw '{
  "items": [
    {
      "test":1,
      "testb":2,
      "testc":"test"
    }
  ]
}'
``` 
2. Check body tab of the imported request.

**Expected behavior**
Was expecting to have the body imported.

**Screenshots**
![Screenshot 2020-03-20 at 11 42 50](https://user-images.githubusercontent.com/11976836/77156733-43060100-6aa0-11ea-9a2e-41a79c3b1564.png)

**App information (please complete the following information):**
 - Native App
 - `7.21.0-canary03`
 - OS: macOS Mojave

**Additional context**
/cc @DannyDainton

**Comment by DannyDainton** [comment]
Hey @filfreire, 

Just for additional Info - Amending the `--data-raw` flag to `--data` will import the correct request.

<img width="686" alt="Screenshot 2020-03-20 at 11 01 50" src="https://user-images.githubusercontent.com/17089546/77157926-3a123100-6a9a-11ea-9dc1-71cb13857249.png">

**Comment by filfreire** [comment]
@DannyDainton thanks mate!

**Comment by vvs11** [comment]
@filfreire, hope your problem is solved. If not, feel free to reopen this issue.

**Comment by DannyDainton** [comment]
@vvs11It's a duplicate of the issue mentioned by @filrfreire in the original message.
