### ISSUE TITLE
Text of Dark Theme is Too Dim

### ISSUE THREAD

**Issue by SDESkowronski** [a85/POSTMan-Chrome-Extension#8207]
**Describe the bug**
The text of the Dark Theme is too dim to read for older eyes like mine. Especially during the day when there is lots of sunlight coming in. I use Dark Themes in other apps that uses brighter fonts and they are quite pleasant to use during the day. 

**To Reproduce**
1. Open the Postman app
2. Switch to Dark Theme
3. View all of the text, especially in the daylight.
4. Noticed how dim the text fonts are.

**Expected behavior**
Either a brighter font should be used OR another higher contrast dark theme should be provided OR the ability for us users to modify the theme is needed.

**Comment by kamalaknn** [comment]
Hey @SDESkowronski 

We are looking at improving the general accessibility of Postman with better contrast for colors. Is there any part of the App where you are noticing this? Can you attach screenshots of particular sections where you are having issues if any?

**Comment by d1820** [comment]
I agree, This is the only app I have that I just can not run in DarkMode. It needs a better contrast palette that uses softer colors. Maybe refer to the VSCode theme Dark+  has a good contrast set
![image](https://user-images.githubusercontent.com/377631/109327902-12812800-7816-11eb-9d50-1fd66a5e2167.png)

**Comment by chris-torruella** [comment]
Hi @SDESkowronski, now Postman v11 introduces a whole set of application themes accessible via Settings/Themes. Now you can also sync these with your System preferences. But very importantly, we've also included High Contrast themes for enhanced contrast as needed. We hope these will help to improve your experience, and we're eager to hear your feedback. Cheers!
