### ISSUE TITLE
All of my request are empty

### ISSUE THREAD

**Issue by casti004** [a85/POSTMan-Chrome-Extension#8208]
**Describe the bug**
I created a new request folder and tested 14 api request that I placed in that folder.
I reopened Postman the next day and all of the requests are empty.

**To Reproduce**
1. Go to 'My account'
2. Click on 'ResidentialListingsAPI folder'
3. Scroll down to 'GetListings' request
4. See error: the entire request including the url is blank

**Expected behavior**
To see previous requests

**Comment by vvs11** [comment]
@casti004 This should not be happening. Could you write to us at help@getpostman.com and we will definitely assist you.

**Comment by xk0der** [comment]
@casti004 we did not hear back from you at the support ticket hence closing this GitHub issue as well. 

Do reply back to the message you received via our Support portal to re-open the ticket if you change mind and we would love to help you out!
