### ISSUE TITLE
"API Key" option under Authorization does not show up - v5.5.4 on Mac

### ISSUE THREAD

**Issue by thesurenk** [a85/POSTMan-Chrome-Extension#8209]
**Describe the bug**
Following the docs at https://learning.postman.com/docs/postman/sending-api-requests/authorization/#api-key , on Postman 5.5 on Mac , the "API Key" does not show up under Authentication > Type options. 

**To Reproduce**
1. Go to Postman
2. Create a new request
3. Go to Authorization tab, under Type dropdown, "API Key" option does not show up.

**Expected behavior**
"API Key" option show up under Authorization > Type options

**Screenshots**
![Screen Shot 2020-03-20 at 5 00 20 PM](https://user-images.githubusercontent.com/902972/77209476-58912000-6acc-11ea-8c04-da782f2d31b2.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version 5.5.4
 - OS: Mac OS Mojave 10.14.6

**Comment by vvs11** [comment]
@ksurendra it is available in the latest version of Postman. Please update your app and let us know if you're still facing issues 
![image](https://user-images.githubusercontent.com/4140290/77225334-1b906080-6b94-11ea-82fb-d6058a1909e2.png)

**Comment by Shivam-Pancholi** [comment]
My postman is updated but i.m still not getting API key option in Authorization tab

**Comment by arlemi** [comment]
@Shivam-Pancholi Which version of Postman are you using? You can be sure to grab the latest version by going on our download page: https://www.postman.com/downloads/
