### ISSUE TITLE
Pull request view: Nest them in their folders

### ISSUE THREAD

**Issue by ColdCerealAtWork** [a85/POSTMan-Chrome-Extension#8210]
**Is your feature request related to a problem? Please describe.**
When reviewing a large pull request I get no information about where the request exists in the collection. It makes it very difficult to understand what request was changed.

**Describe the solution you'd like**
I'd love to have a nested list to the left of the changes where I can expand folders to find the changes and select them to view the changes that were made.

**Additional context**
I'm really happy pull requests are a thing now, and look forward to seeing future iterations of this feature.

**Comment by ankit-m** [comment]
You can now see folder structure in the PR diff view.
