### ISSUE TITLE
Pre-request headers Keys issue- If there is only one header of type application/json and key used is 'headers' then it takes the default header text/plain

### ISSUE THREAD

**Issue by bhawna0612** [a85/POSTMan-Chrome-Extension#8211]
**Description**
Postman version 7.20.1. Pre-request headers Keys issue- If there is only one header of type application/json and key used is 'headers' then it takes the default header text/plain. If key is changed to singular 'header' then it works fine

**To Reproduce**
1. Go to postman app
2. Add pre-request script with only one header of type application/json but use the key as 'headers' instead of 'header'
3. Send request and see request headers in postman console
4. It shows Content-Type: text/plain instead of application/json
5. Switch 'headers' to 'header' and send the request and see console logs
6. This time request header content-type shows correctly

**Expected behavior**
if headers key is used with only one header key pair, it should take the mentioned header in the script, not the default header

**Screenshots**
![image](https://user-images.githubusercontent.com/51174633/77213905-cd168f80-6ac9-11ea-973d-e36f101022b9.png)
![image](https://user-images.githubusercontent.com/51174633/77214001-2c749f80-6aca-11ea-9ed9-c4ab43b64130.png)

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [7.20.1]
 - OS: [Windows 10]

**Comment by vvs11** [comment]
@bhawna0612 I am not able to reproduce the issue. This is how it looks like:
1. I am using key as 'headers':
![image](https://user-images.githubusercontent.com/4140290/77225556-1d5b2380-6b96-11ea-882e-c74281c2923b.png)

No header is added

2. I am using key as 'header'
![image](https://user-images.githubusercontent.com/4140290/77225578-53000c80-6b96-11ea-86dc-87da0830e374.png)


The correct header is added.

I am seeing an error in your pre-request script execution in the screenshot you attached. Could you check that once and try this after resolving the error?

**Comment by bhawna0612** [comment]
@vvs11 I can reproduce the issue constantly. I tried multiple times. In my first screenshot, the reason for the error is incorrect Content-type request header. Because it picked correct request header when key is used as 'header' that's why there is no error in 2nd pre-request.

But in your case, when you used the key as 'headers' why it didn't add the header in request? It should add the Content-type header correct?

**Comment by vvs11** [comment]
@bhawna0612  You can add multiple headers by using multiple key-value pairs in 'header' section. 
'headers' is not valid

**Comment by bhawna0612** [comment]
I am closing this issue for now
