### ISSUE TITLE
Feature request : Get environment variables from Hashicorp vault on runtime

### ISSUE THREAD

**Issue by electricsrini** [a85/POSTMan-Chrome-Extension#8216]
Currently, for Postman collection managed via environment variables, the credentials are stored unsecured in the application. The users may also inadvertently export and share the environment variables - which may not be desired.

Is there any pattern / test / support for the below workflow –

1. For environment variables, have Hashicorp Vault as the backend credentials store.
2. Get the values (placeholder) for the environment variables dynamically, after authentication with Vault to unseal and fetch.
3. Post execution / user input, disconnect and close this connection.

This can help restrict inadvertent credentials leak that may happen.

**Comment by lucatoldo** [comment]
I fully support this feature request too..

**Comment by scdrill-hydrogen** [comment]
Sign me up! :)

**Comment by Suhas-Gaikwad** [comment]
Thank you for your patience. We have released a feature for seamless integration with HashiCorp Vault in the release of [Postman v11](https://blog.postman.com/announcing-postman-v11/). Check the [learning center](https://learning.postman.com/docs/sending-requests/postman-vault/hashicorp-vault/) to learn more about the feature.


Postman Vault is also part of the Postman V11 release. Postman Vault enables you to store sensitive data in your local instance of Postman. Check the [learning center](https://learning.postman.com/docs/sending-requests/postman-vault-secrets/) to learn about the Postman Vault feature.
