### ISSUE TITLE
System Installer for Postman native app

### ISSUE THREAD

**Issue by xmha97** [a85/POSTMan-Chrome-Extension#8220]
The Postman installer, install Postman only for current user.
Please make system installer (install for all users)

like VisualStudio Code
[![VisualStudio Code Site](https://user-images.githubusercontent.com/23485114/77267363-fa2c9300-6cbf-11ea-9e78-5db8680e6ca2.png)](https://code.visualstudio.com/#alt-downloads)

Similar of #3897

**Comment by arlemi** [comment]
We're tracking this in #4576, please add any feedback you feel is relevant there! 

Closing this one.
