### ISSUE TITLE
Bootcamp lesson Resume button doesn't work

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#8221]
**Describe the bug**
Postman Bootcamp Resume button doesn't take the user back to the lesson. 
Nothing happens when clicking on it.

**To Reproduce**

1. Open the Postman prod app - version 7.20.1
2. Click on Bootcamp Select any skill (for example, API documentation)
3. Click learn and start the lesson  
4. Before the lesson is 100% completed, select another collection and another request - the tooltip disappears. 
5. Go back to the Bootcamp view.  
6. Click Resume for the skill In Progress. 
7. Nothing happens. 

**Expected behavior**
The resume button should take the user back where he stopped the lesson. 

**Screenshots**
<img width="678" alt="Screen Shot 2020-03-18 at 09 24 04" src="https://user-images.githubusercontent.com/47351631/77312744-7d6ada80-6cfa-11ea-8155-25a222b3b82b.png">

**App information (please complete the following information):**
- Postman App: Version 7.20.1
- OS: MacOS

**Comment by prashantagarwal** [comment]
@cyrielle-hada The fix for this is now available in production.
