### ISSUE TITLE
hosts file with multiple domains on a single line is not properly used

### ISSUE THREAD

**Issue by Chibby** [a85/POSTMan-Chrome-Extension#8222]
**Describe the bug**
I am using [ddev](https://ddev.readthedocs.io) for local development. ddev will add local domains on a single line in the hosts file. This can add up quickly, so right now I have 56 domains on a single line, all pointing to 127.0.0.1.
All goes well for the first 27, but from domain #28 and beyond, Postman does not recognise the domains anymore.

**To Reproduce**
1. open the hosts file
2. add, at the minimum, 28 domains
3. submit any request via postman to domain #28 or beyond

**Expected behavior**
As all domains continue to function perfectly using a browser, any terminal tool, etc. it seems clear that Postman should also understand any domain in the hosts file.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.20.1
 - OS: macOS Catalina 10.15.3

**Comment by coditva** [comment]
Hey @Chibby, I tried setting multiple hosts on a single line as:
```hosts
127.0.0.1	d1 d2 d3 d4 d5 d6 d7 d8 d9 d10 d11 d12 d13 d14 d15 d16 d17 d18 d19 d20 d21 d22 d23 d24 d25 d26 d27 d28 d29 d30 d31 d32 d33 d34 d35 d36 d37 d38 d39 d40 d41 d42 d43 d44 d45 d46 d47 d48 d49 d50 d51 d52 d53 d54 d55 d56
```

This seems to be working fine for me in Postman. I was able to send request to `http://d28:3000` (all domains from `d1` to `d56` infact) and it sent the request correctly and display the response.

Can you provide with more info about the hosts file like:
- what is the length of the whole line
- what is the length of the domain name which fails
- does it work when you split the line into multiple lines

OS: MacOS Catalina 10.15.1

**Comment by Chibby** [comment]
> what is the length of the whole line

Currently 1903 characters

> what is the length of the domain name which fails

Longest functional domain name: 43 characters
Longest failing domain name: 41 characters

> does it work when you split the line into multiple lines

Yes.

So I guess it has nothing to do with the amount of domains, but with the length of the line.

**Comment by coditva** [comment]
@Chibby I updated my hosts file to include this line:
```
127.0.0.1 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa5 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa6 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa7 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa10 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa11 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa12 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa13 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa14 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa15 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa16 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa17 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa18 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa19 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa20 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa21 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa22 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa23 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa24 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa25 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa26 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa27 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa28 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa29 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa30 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa31 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa32 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa33 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa34 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa35 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa36 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa37 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa38 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa39 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa40 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa41 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa42 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa43 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa44 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa45 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa46 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa47 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa48 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa49 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa50 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa51 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa52 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa53 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa54 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa55 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa56
```

Every domain name is 40 `a` followed by a number. The total length of line is 3894! And every domain is working fine for me...

Does you domain names contain any special characters? Could you share the domain list or maybe just the domain name that is failing?

**Comment by Chibby** [comment]
The only difference between your test case, and my real case is the relative complexity of domains used. Most local domains follow this pattern: `<project-name>.loc.loyals.online`. Some have even more segments. The problem in my line seems to occur after a domain name that has 5 segments (`www.<project-name>.loc.loyals.online`).

There are no special characters involved.

I am reluctant to share the full list on a public forum, so I hope this is enough information.

**Comment by coditva** [comment]
@Chibby Even this does not seem to be the issue! I added this line in my hostfile:
```
127.0.0.1 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh1 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh2 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh3 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh4 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh5 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh6 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh7 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh8 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh9 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh10 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh11 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh12 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh13 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh14 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh15 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh16 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh17 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh18 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh19 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh20 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh21 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh22 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh23 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh24 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh25 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh26 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh27 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh28 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh29 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh30 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh31 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh32 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh33 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh34 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh35 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh36 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh37 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh38 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh39 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh40 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh41 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh42 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh43 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh44 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh45 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh46 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh47 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh48 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh49 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh50 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh51 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh52 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh53 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh54 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh55 aaaaa.bbbbb.ccccc.ddddd.eeeee.fffff.ggggg.hhhhh56
```
and everything is still working as expected.

Can you check what happens if you remove the host that is not working? Do other hosts work after this? What happens when you put this host on a different line than other hosts?

I feel this might not be a hosts file issue but maybe a certificate or proxy issue(?)

cc @codenirvana

**Comment by Chibby** [comment]
I have tinkered with the hosts file, and I now have a file where all domains function as intended. I do believe you are right that this may not be a hosts file issue.
As far as I am concerned: case closed.
I would thank you for your patience and assistance.
