### ISSUE TITLE
Allow update many account collections with one api call

### ISSUE THREAD

**Issue by Bysmyyr** [a85/POSTMan-Chrome-Extension#8224]
Now we have to update 30 account collections with individual API calls. This is not necessary and it would be nice to do it with only one call which updates them all.

**Comment by vvs11** [comment]
@Bysmyyr could you elaborate your use case in a little more detail?
You have one Postman account and 30 collections in it or there are different accounts?

**Comment by Bysmyyr** [comment]
We generate Postman collections from apib-files in CI which update them for 30 developers.

**Comment by vvs11** [comment]
and these 30 developers have 30 different accounts on Postman?

**Comment by Bysmyyr** [comment]
Of course every developer has their own account

**Comment by sankalp0o** [comment]
@Bysmyyr if you create a team with all your developers, the collections they work on will remain in sync. Hence, you'd be able to update a single collection and all your developers would be able to use the latest collection. You would also be able to use advanced workflows like forking and merging this way.

Teams in Postman can be created for free (although with some limitations). I hope this helps you make your workflow easier. I'm closing this issue but do try it out and let us know if we can do anything else to improve!

P.S. Very interested in understanding how are you converting your API Blueprint to a collection. We have first-party converters for OpenAPI and RAML formats.

**Comment by Bysmyyr** [comment]
https://github.com/SharperShape/vanadia
