### ISSUE TITLE
API tab crashes when another tab is closed

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#8225]
**Describe the bug**
API tab crashes unexpectedly

**To Reproduce**
1. Open an API in a tab
2. Open requests in few tabs and continue working
3. Switch back to the API tab after some time

**Expected behavior**
Not crash

**Screenshots**
![Screenshot 2020-03-23 at 7 15 19 PM](https://user-images.githubusercontent.com/3295568/77324954-829d4900-6d3d-11ea-8f94-0b9b6c806ce8.png)

Screenshot of crash log in DevTools
![Screenshot 2020-03-23 at 7 14 55 PM](https://user-images.githubusercontent.com/3295568/77324988-9052ce80-6d3d-11ea-8421-af3a05eb91c3.png)

**App information (please complete the following information):**
 - App Type: Desktop Mac
 - Postman Version: v7.21.0
 - OS: macOS Catalina 10.15

**Comment by numaanashraf** [comment]
More details on this issue:

This seems to be triggered when a different tab is closed.

**Comment by shivangibajpai12** [comment]
@numaanashraf Thank you for reporting this issue.
We are able to reproduce this issue. This happens when any adjacent active tab to the API tab is closed. We are working on the fix.

**Comment by shivangibajpai12** [comment]
This issue has been fixed in Postman 7.21.1.
