### ISSUE TITLE
OAuth Request Authorization Code Not Working

### ISSUE THREAD

**Issue by GlennIM** [a85/POSTMan-Chrome-Extension#8227]
When clicking the "Request Token" button, the "Connect To Pinterest" dialog appears to grant access, then when I click the OK button in that dialog I get the following error message...

{"status": "failure", "code": 12, "data": "path: /oauth/\nparams:<dict_itemiterator object at 0x7fad8ef24050>\nAuthError(code=500, message='dial tcp 127.0.0.1:22000: connect: connection refused')", "message": "Something went wrong on our end. Sorry about that.", "endpoint_name": "oauth_connect"}

What is the work around for this?

**Comment by vikiCoder** [comment]
Hi @GlennIM, from the error message it seems to be a problem at the server side. Where are you seeing this message, on the browser popup while granting the access?

**Comment by GlennIM** [comment]
Yes. See attached image.
![AccessTokenError](https://user-images.githubusercontent.com/40885095/77331109-48588b00-6cee-11ea-92b4-68c9d8a539d2.jpg)

**Comment by GlennIM** [comment]
Here is the input for the request... I have the callback URL shown in the input below set in my pinterest app.
![AccessTokenErrorInput](https://user-images.githubusercontent.com/40885095/77331678-10057c80-6cef-11ea-970c-ec73a33d8948.jpg)

**Comment by GlennIM** [comment]
Is there a fix for this?

**Comment by vikiCoder** [comment]
This is a problem from the Pinterest server side. Please contact Pinterest regarding the error. I am closing the issue since It is not a problem with the Postman app.
