### ISSUE TITLE
The "Automatically follow redirects" setting's description conflicts with the title.

### ISSUE THREAD

**Issue by breathermachine** [a85/POSTMan-Chrome-Extension#8228]
**Describe the bug**
The "Automatically follow redirects" setting's description conflicts with the title. 
<img width="766" alt="Screen Shot 2020-03-19 at 10 31 34" src="https://user-images.githubusercontent.com/16012337/77332557-89d84d00-6d65-11ea-8179-0d6d9320f6cc.png">
What does ON mean here?

Does it mean "Automatically follow redirects" as implied by the title? Or "Prevent requests that return a 300-series response from being automatically redirected." as implied by the description?

**To Reproduce**
1. Go to a request's Settings Tab
2. Look for "Automatically follow redirects" setting
3. Verify that the corresponding description is "Prevent requests that return a 300-series response from being automatically redirected."

**Expected behavior**
Description should match the title of the setting. It should be something like "Allow requests that return a 300-series response to be automatically redirected."

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version: Version 7.20.0 (7.20.0)
 - OS: macOS Catalina 10.15.1

**Additional context**

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.

Please feel free to reopen with the steps to reproduce if the issue persists.
