### ISSUE TITLE
FEATURE REQUEST:  Shared Collections for Teams

### ISSUE THREAD

**Issue by mmathe03** [a85/POSTMan-Chrome-Extension#823]
My team just purchased several team accounts of Jetpack under the assumption that we could share collections with each other.  Unfortunately I'm not seeing any way to actually share collections.  Is this a feature that will be coming soon?  Thanks.

**Comment by a85** [comment]
@wcandillon @mmathe03 @davidschreiber Our team beta is underway. Send us an email at help@getpostman.com to join. :)

**Comment by richardwhatever** [comment]
+1 this is why we upgraded too.

**Comment by jaredwilkening** [comment]
+1 for this feature. Was also under the impression from the site this was already available. Was about to upgrade our team.

**Comment by jfiorillozinio** [comment]
This was implemented on Postman Sync Beta using Postman Team sync ?

**Comment by abhijitkane** [comment]
@jaredwilkening That's correct. Sharing collection among team members is a feature that's part of the beta program. You can sign up at https://beta.getpostman.com/intro/

**Comment by jaredwilkening** [comment]
thanks @abhijitkane!

**Comment by jfiorillozinio** [comment]
But this feature is not working yet, right? Because I tried with a couple of friends and I was not able to sync the collections

**Comment by abhijitkane** [comment]
@jfiorillozinio Are you using the team sync application? Can you send your username and team name to help@getpostman.com?

**Comment by a85** [comment]
Team Sync is available as part of our Postman Cloud service. If you are a Postman account holder on (getpostman.com), you can log in and purchase the upgrade. More details coming soon.
