### ISSUE TITLE
BUG:Mock is not happening if only request body has change 

### ISSUE THREAD

**Issue by im-bhaskar** [a85/POSTMan-Chrome-Extension#8233]
**Describe the bug**
If a URI path is same for a POST request
when i change the request body as per our application response is keep on changes 
on this situation we can't able to reproduce that as a mock example.

Because it only saved the first API example and concentrated on URI path and did't checking body.
As result of this when i hit other API then first it is giving the first API response for all others even i saved the different example.

**To Reproduce**
1. Go to Collection
2. Create a mock server
3. Copy link and api key
4. Run the actual api and save as a example
5. Do it for other api also
6. Switch to Mock URL and sync it
7. Hit mock URL

**Expected behavior**
For Same URI and different body the examples set are the different.
for individual API the response should be what i saved in example 

**App information (please complete the following information):**
 - App Type native windows app
 - Postman Version 7.21.0
 - OS: Windows 10

**Comment by vvs11** [comment]
Hey @Bhaskarbe, Thanks for writing in. If I understand the problem correctly, you're trying to match requests with different bodies and the same URL. 
You need to enable body matching by using 'x-mock-match-request-body' header in the mock request. You can go through the documentation here.

https://learning.postman.com/docs/postman/mock-servers/mock-with-api/#run-the-mock-service

Let us know if that solves your problem

**Comment by im-bhaskar** [comment]
Thank you @vvs11 it's working....
