### ISSUE TITLE
Postman Teams blocks sharing of collections

### ISSUE THREAD

**Issue by ma-schmidt-de** [a85/POSTMan-Chrome-Extension#8236]
**Describe the bug**
I was trying to import 21 collections to my team workspace but only 6 actually reached Postman cloud. My personal desktop app keeps trying to upload but fails.

**To Reproduce**
1. Login to user that is part of a Team on Postman Team plan
2. Switch to a team workspace
3. Attempt to upload 10+ collections
4. No error is shown. 
5. Login with a different user of the same team workspace and open this workspace
6. Error Message is shown as a popup in the bottom right corner.

**Expected behavior**
There is no collection share limit for Teams on plan Postman Teams. I must be able to upload anything.

**Screenshots**
![Screenshot 2020-03-24 at 13 40 03](https://user-images.githubusercontent.com/19306046/77428332-33582680-6dd8-11ea-8233-0ae0ee58e184.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.21.0
 - OS: macOS 10.15.2

**Additional context**
I'm the admin of our team. The billing overview page of our team tells me, I'm on a Postman Team plan and we do indeed pay a monthly fee!! We purchased the payed plan because of the cloud sharing capabilities and now they don't work!?

**Comment by cyrielle-hada** [comment]
Hi @ma-schmidt-de - It may sound very rudimentary but would you sign out and sign back in, and see if the issue persists?

If it doesn't help, please submit a support ticket from this page: https://support.getpostman.com/hc/en-us/requests/new so we can take a look at your team account and see what is going on.

**Comment by ma-schmidt-de** [comment]
We re-launched the desktop app and the error vanished.

Still, the error appears for new members joining the team concerning them there might be something wrong with our account. I recommend fixing it.

**Comment by DannyDainton** [comment]
The archiving of Collections no longer happens on the platform. If you're still facing this issue in the latest version, we can investigate further.
