### ISSUE TITLE
Postman codegen list not expanding sideways

### ISSUE THREAD

**Issue by someshkoli** [a85/POSTMan-Chrome-Extension#8239]
**Describe the bug**
The codegenerator language list is not expanding sideways as for the languages having more than one codegen support, the type of codegen option opens sideways it is not visible until scrolled using the scrollbar

**To Reproduce**
1. Go to 'open any request'
2. Click on 'code' to follow to the codegenerator and click on the language
3. Scroll down to get any language with multiple codegen available 
4. scroll over it and notice the list view is not being expanded sideways

**Expected behavior**
On scrolling on language having multiple codegen support the list view should either expand sideways or those options should be displayed below the language

**Screenshots**
![Screenshot from 2020-03-25 05-51-42](https://user-images.githubusercontent.com/41543649/77489112-2f221c80-6e5d-11ea-9cb3-3acd62f1d0de.png)
to check for further info we need to scroll using the scroll bar below which is quite not so user friendly
![Screenshot from 2020-03-25 05-51-48](https://user-images.githubusercontent.com/41543649/77489120-31847680-6e5d-11ea-9251-b8f0f9bcc0b3.png)

**App information (please complete the following information):**
 - App Type native
 - Postman Version 7.2.2
 - OS: Linux Kali 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux

**Comment by kamalaknn** [comment]
@someshkoli Thanks for reporting this. We are tracking this in #6559.  I'm closing this as a duplicate. Please subscribe to the original issue for updates.

**Comment by abhijitkane** [comment]
@someshkoli While this is fixed, I'd recommend switching to the new code-generation feature (Postman settings -> New Code Generation Mode). We've introduced the ability to configure the generated code snippet and included a number of bugfixes. Would love your feedback on that :)

**Comment by someshkoli** [comment]
Checked out the new Codegen UI. This is much better, easy to use than previous one and looks great. Good job team.
