### ISSUE TITLE
Postman install and update fail since 7.21.0

### ISSUE THREAD

**Issue by DuchenePierre** [a85/POSTMan-Chrome-Extension#8240]
**Describe the bug**
Installation and update is broken since at least 7.21.0

**To Reproduce**
1. Download installer
2. Execute installer
3. Watch it fail

**Expected behavior**

App should be installed or updated properly

**Screenshots**

![image](https://user-images.githubusercontent.com/62640999/77514256-c6e03480-6e76-11ea-8d2f-89aff8010317.png)

**App information (please complete the following information):**
 - Native App
 - Tested with 7.21.0 and 7.21.1 (couldn't find earlier version on postman site)
 - OS: Windows 7 Entreprise SP1 64bits

**Comment by DuchenePierre** [comment]
I found an old 7.16 installer in my download folder and it installed postman 7.16.0 properly

**Comment by AadiMehta** [comment]
+1 It upgraded itself and now couldn't start the postman. This is really bad!

**Comment by DuchenePierre** [comment]
Hello @kamalaknn ,

Can you link the duplicated issue ?

Than you

**Comment by harryi3t** [comment]
@DuchenePierre We are tracking this here https://github.com/postmanlabs/postman-app-support/issues/6723

Could you share your logs from `%AppData%\Postman\logs` at help@postman.com?
It would really help us triage and fix the issue faster. Please do mention the GitHub issue ID (8240) and your GitHub username (DuchenePierre) in the mail. Thanks!

**Comment by DuchenePierre** [comment]
> @DuchenePierre We are tracking this here #6723
> 
> Could you share your logs from `%AppData%\Postman\logs` at [help@postman.com](mailto:help@postman.com)?
> It would really help us triage and fix the issue faster. Please do mention the GitHub issue ID (8240) and your GitHub username (DuchenePierre) in the mail. Thanks!

I already applied this fix https://github.com/postmanlabs/postman-app-support/issues/6723#issuecomment-595365241
and it worked for me.

Please fix this or at least allow us to disable auto-update, this has been really annoying to reinstall postman 7.16 each time I closed the app !

This is some bad quality control here. And that's right there in the middle of postman's "our values" section on the website.
