### ISSUE TITLE
Reserved words for tests are not highlighted when using the Light Theme

### ISSUE THREAD

**Issue by 4en6** [a85/POSTMan-Chrome-Extension#8241]
**Describe the bug**
Reserved words  like functions have the same font and style as the other code when writing tests in the Tests tab and Pre-Request Script tab. This is only valid for the Light theme.

**Steps to reproduce the behavior:**
1. Make sure you are using the Light theme.
2. Create a request.
3. Go to Tests tab.
4. Click on Status code: Code is 200 snippet and observe the style. 
5. Change the theme to Dark and see the same snippet.

**Expected behavior:**
Reserved words as in the case _status_ in `    pm.response.to.have.status(200);
` should change color as it is when using Dark theme.

**Screenshots**
![DarkTheme](https://user-images.githubusercontent.com/34267870/77535780-7a5b2000-6e9b-11ea-9ef5-4b67a57cf880.png)
![LightTheme](https://user-images.githubusercontent.com/34267870/77535783-7b8c4d00-6e9b-11ea-810a-6fdbccc0d483.png)

**App information:**
 - Postman Version 7.21.1
 - OS: Windows 10

**Comment by pankajk07** [comment]
Fixed as part of v7.24
