### ISSUE TITLE
Font size too big of list when inside blockquote

### ISSUE THREAD

**Issue by IsraelBoiko-Objective** [a85/POSTMan-Chrome-Extension#8242]
**Describe the bug**
When adding a list to a block quote, the font size differs from the option "View in web" vs published at "documentador"

**To Reproduce**

Add this description:
```markdown
Outsit blockquotes:
- Item 1
- Item 2
- Item 3

> Example:
> - Item 1
> - Item 2
> - Item 3
```

**Expected behavior**
The documentation has same style in boot locations (published in "documentator" same the "View in web")

**Screenshots**
Expected (like View in web):
![image](https://user-images.githubusercontent.com/54552553/77582956-ff0b6580-6ebe-11ea-87d4-7914c2f5e392.png)

Actual (endpoint: https://documenter.getpostman.com/view/...)
![image](https://user-images.githubusercontent.com/54552553/77582990-10547200-6ebf-11ea-87eb-da5b65000b12.png)

**Comment by ajeet-postman** [comment]
@IsraelBoiko-Objective This issue is fixed. Can you please confirm?

**Comment by akshaydeo** [comment]
@IsraelBoiko-Objective feel free to open the ticket if it's still not working for you 🙇‍♂️
