### ISSUE TITLE
Canary: Cannot Open Second Account

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#8243]
In Postman (non-Canary), I have two different Cloud accounts with two emails. I'm able to switch between the two.  However, when I exit out and I open Canary, I'm only able to see the collections in one account.   The other one does open up for me but there are no collections listed.

**Comment by Raj-postman** [comment]
Hi @jcald1 sorry to hear that - Could you please write to us at help@postman.com or submit a new request by navigating to [this link](https://support.getpostman.com/hc/en-us/requests/new?_ga=2.41576166.51033459.1566575975-1984505412.1566575975) with this GitHub title and we will definitely assist you further on this.

**Comment by jcald1** [comment]
@Raj-postman , sent to `help@postman.com`

**Comment by xk0der** [comment]
Solved via support channel.
