### ISSUE TITLE
Feature Request:Add ability to sync API to other git repositories

### ISSUE THREAD

**Issue by tfleisher-aaxis** [a85/POSTMan-Chrome-Extension#8245]
**Is your feature request related to a problem? Please describe.**
Currently it appears that the "connect Repository" button from APIs only supports sync to github. We are not using github so are unable to use this feature. 

**Describe the solution you'd like**
It would be nice to be able to sync changes to other git repositories such as GitLab

**Describe alternatives you've considered**
There doesn't appear to any alternative within Postman other than manually copying changes (moving repositories to Github is not an option for us), but Swaggerhub currently supports sync fo APIs to GitLab, GitHub, Bitbucket Cloud, and Bitbucket Server.

**Comment by theopract** [comment]
Looking forward for an ability to sync to gitlab as well 👍

**Comment by ezarko** [comment]
GitHub Enterprise

**Comment by VikasPareek** [comment]
I'm looking forward to the completion of this feature and get to use it. I would love to see Postman sync to our **BitBucket cloud & BitBucket Server** git repositories.

**Comment by obieo** [comment]
Do we have a list of the repositories that are on the roadmap for integration. Azure Repos would be great

**Comment by obieo** [comment]
Azure Git Repos

**Comment by zleroy** [comment]
A GitLab integration for storing collections would be much appreciated

**Comment by shashankawasthi88** [comment]
@zleroy A GitLab Integration to backup (store) your collections already exist (https://learning.postman.com/docs/integrations/available-integrations/gitlab/).   This thread is specifically talking about syncing the API schema (and not backing up collection), which is only available for GitHub as of now.

**Comment by zleroy** [comment]
Thanks for your reply. I am interested in a two way sync like the GitHub
integration.

**Comment by shashankawasthi88** [comment]
@zleroy thanks for the clarification. We are evaluating GitLab/ other git repositories, for two-way schema sync integration. Will post the updates on the thread itself.

**Comment by pederkronsgaard** [comment]
Google Cloud Source Repositories would be great.

**Comment by pawel-tomkiel** [comment]
@shashankawasthi88 - our use case is like we have services in Github on custom domain and would love to keep those in sync with Postman collections for testing purposes. Would be great to see this feature planned on roadmap :)

**Comment by jotsarup** [comment]
@pawel-tomkiel we currently have integration to backup collections to Github on custom domain 
https://learning.postman.com/docs/integrations/available-integrations/github/#backup-collections-to-github-on-custom-domain

If you workflow is not achieved with us, please let us know.

**Comment by pawel-tomkiel** [comment]
We want it exactly other way around (and I understood that this ticket is about it) :) we have services with openapi definitions, and we want Postman to automatically update collections basing on changed JSON files in GitHub repo on custom domain.

**Comment by jotsarup** [comment]
@pawel-tomkiel I get your point. While we have 2 way **schema sync** integration on Github, but we don't support custom domain on **schema sync**. We are actively working and will let you know :)

**Comment by michaltajchertdev** [comment]
Would be great to make it work with BitBucket.

**Comment by gabel** [comment]
@jotsarup Any news on the sync that @pawel-tomkiel mentioned?

Openapi Spec in Github Enterprise -> sync changes to -> Postman API/Collection

**Comment by abhijitkane** [comment]
@gabel This is something we're actively working on, and hope to have an update to share soon.

**Comment by arlemi** [comment]
Hey everyone! We've added native Git support (Bitbucket and GitHub for now, more to come) in Postman v9. Please[ check this blog post](https://blog.postman.com/announcing-new-postman-api-platform/) for more info, and update your app to try it out!

**Comment by huyz** [comment]
@arlemi Thanks for the news.  Are you working on adding support for GitHub Enterprise?

**Comment by arlemi** [comment]
@huyz You can integrate with GitHub Enterprise on the Postman Enterprise plan. More info on this plan here: https://www.postman.com/postman-enterprise/
![image](https://user-images.githubusercontent.com/5029719/133981655-db92775d-9fbd-4e49-98f9-1550fd2bb1c5.png)

**Comment by shashankawasthi88** [comment]
Hey Everyone, while we are planning to add more repository Integrations soon (GitLab, Azure, etc.), we would want to gain some feedback on the recent release (API Platform with Integrations with repository Integrations). We would love to know how well the release caters to your use cases. People asking for Integrations not yet introduced may also schedule as the flow would remain the same irrespective of the repository. 
You can schedule a call with us using this link - https://calendly.com/shashank-awasthi/api-platform-feedback
