### ISSUE TITLE
Could not get any response

### ISSUE THREAD

**Issue by karanraj97** [a85/POSTMan-Chrome-Extension#8247]
Postman shows **Could not get any response** for every request made on external API's
If I use Localhost then postman works fine. I don't know why it is happening.
![image](https://user-images.githubusercontent.com/20990432/77713931-c45c1700-6ffd-11ea-965e-b12db58ec482.png)

Same API which is working on browsers and chrome postman
![image](https://user-images.githubusercontent.com/20990432/77714007-f9686980-6ffd-11ea-96c1-7cf195064fa4.png)
![image](https://user-images.githubusercontent.com/20990432/77714129-49dfc700-6ffe-11ea-90a0-2607af81f0ea.png)

Below screenshot is the error shown in postman console
![image](https://user-images.githubusercontent.com/20990432/77714190-6e3ba380-6ffe-11ea-9704-71162e60ed8e.png)

Below screenshot is settings
![image](https://user-images.githubusercontent.com/20990432/77714265-90352600-6ffe-11ea-9e96-d4c24084439b.png)

 - App Type : windows postman
 - Postman Version :  v7.21.1
 - OS: windows 10 64bit

**Comment by vvs11** [comment]
@karanraj97 Looks like there is some problem with your internet connectivity with Postman. I can see the sync icon as disabled in the screenshot you posted. Could you please check that and try again?

**Comment by karanraj97** [comment]
> 
> 
> @karanraj97 Looks like there is some problem with your internet connectivity with Postman. I can see the sync icon as disabled in the screenshot you posted. Could you please check that and try again?

@vvs11 I didn't sign in. I think, sync is available only when we signed in. Am I correct or Wrong?

**Comment by codenirvana** [comment]
@karanraj97 can you verify that you don't have any proxy configured?

**Comment by karanraj97** [comment]
> 
> 
> @karanraj97 can you verify that you don't have any proxy configured?

I didn't configure any proxy.
![image](https://user-images.githubusercontent.com/20990432/77765552-69113f80-7064-11ea-98f8-839ffcd66ff0.png)

![image](https://user-images.githubusercontent.com/20990432/77765798-c9a07c80-7064-11ea-91e2-5e226f70d62e.png)

**Comment by codenirvana** [comment]
@karanraj97 that's odd 😕 
Can you check what's the error message in the Postman Console (CMD/CTRL + ALT + C)?

The API you are trying out(`https://jsonplaceholder.typicode.com/users`) is working fine for me.

**Comment by karanraj97** [comment]
> 
> 
> @karanraj97 that's odd 😕
> Can you check what's the error message in the Postman Console (CMD/CTRL + ALT + C)?
> 
> The API you are trying out(`https://jsonplaceholder.typicode.com/users`) is working fine for me.

Yes It's working on browser and chrome postman extension but for my windows it was not working for past 3 days.

Now, It works fine. Thanks :) I don't know What happened. I did something but i don't know.

**Comment by karanraj97** [comment]
Thanks @vvs1 problem solved. But I don't know What I did. I did random actions. I rename the host,network,hostname files and again renamed to its original name. Now It is working.

**Comment by karanraj97** [comment]
Again Not working :(

**Comment by karanraj97** [comment]
> 
> 
> @karanraj97 that's odd 😕
> Can you check what's the error message in the Postman Console (CMD/CTRL + ALT + C)?
> 
> The API you are trying out(`https://jsonplaceholder.typicode.com/users`) is working fine for me.

![image](https://user-images.githubusercontent.com/20990432/77814725-bf6c9580-70d9-11ea-8507-3f05fa96649d.png)
this is the error

**Comment by sujaykundu777** [comment]
@karanraj97 Seems working fine in mine ! 
Using Postman v7.21.1

**Comment by karanraj97** [comment]
> 
> 
> @karanraj97 Seems working fine in mine !
> Using Postman v7.21.1

Thanks for reply. I don't know why It is not working. I reset my laptop and also It is not working. From Eclipse also I can't make rest call. Some time It works. But It happen rarely. Yesterday Postman works. I put my lap in sleep mode and came back and try to work on postman, This time It failed
😞 .

**Comment by karanraj97** [comment]
Is There any option to block eclipse / postman to make rest call alone ?

**Comment by vvs11** [comment]
@karanraj97 this looks like a local problem. I am also able to get response from this URL. I can see the request being timed out from the host in the screenshot you posted. Could you please check that once?
We have a community of Postman users to help with these kinds of issues. Please feel free to reach out 
https://community.getpostman.com/
