### ISSUE TITLE
ability to "see" the URL used by an api call

### ISSUE THREAD

**Issue by nutmix** [a85/POSTMan-Chrome-Extension#8249]
I have hundreds of API calls in dozens of collections and dozens of environments.
The URL and query string of every call is variable driven, so I need to know what URL is actually being used.

When you execute a call using the "SEND" button, it will show you the response, but there is no way to see what URL is used (nor the completely raw request and response).    To see the URL, you have to setup an external proxy, such as charles proxy or fiddler, or to force an error (e.g. by disabling internet) which does show the URL. 

The Talend/restlet UI is much better in this regard, as its call history.  I find my self switching between the two - I used talend for basic testing, as I can see more info, but use postman when I need more complex OATH scripting etc.  It would be great if one tool could do both.

**Comment by SabriH10** [comment]
Hi @nutmix ,

Thank you for getting in touch. I believe, based on my understanding of your issue, that the Postman console should be able to address your concern. 

You can access the postman console by going to `View --> Show Postman Console` on your app, clicking on the Postman console icon at the bottom left of the app or using the keyboard shortcut ( `CMD/CTRL + ALT + C` ). More information can be found here: https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/ if needed.

Hopefully, this helps.
