### ISSUE TITLE
Header values (enum) resolve to the type, rather than enum value for OpenApi 3.0

### ISSUE THREAD

**Issue by rob4629** [a85/POSTMan-Chrome-Extension#8250]
**Describe the bug**
Background: We're using Swagger 2.0, but I've converted this to OpenApi 3.0, in order to import to Postman.

Not sure if this is a bug, or a feature request... but I noticed that uploading our swagger definition file caused header values to be resolved with "string", rather than the value of the associated enum.

An example of our swagger file:
```js
{
    "openapi": "3.0.0",
    "info": {
        "version": "1",
        "x-form": "internal",
        "x-name": "mine",
        "x-repository": "my_service.git",
        "title": "My Service",
        "description": "My Service"
    },
    "tags": [],
    "paths": {
        "/v1/events": {
            "post": {
                "x-authtypes": [
                    "my_auth_type"
                ],
                "description": "sample code",
                "tags": [
                    "Misc"
                ],
                "responses": {
                    "200": {
                        "description": "Success."
                    },
                    "204": {
                        "description": "Success."
                    },
                    "401": {
                        "description": "Unrecognized event."
                    },
                    "404": {
                        "description": "Data referenced by event not found."
                    },
                    "415": {
                        "description": "Unsupported request Content-Type: must be `application/json`."
                    },
                    "500": {
                        "description": "Internal error."
                    }
                },
                "parameters": [
                    {
                        "in": "header",
                        "name": "Auth-Type",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "my_auth_type"
                            ]
                        }
                    }
                ]
            }
        },
    "servers": [
        {
            "url": "http://localhost:4000"
        }
    ],
    "components": {
        "parameters": {},
        "schemas": {}
    }
}
```

**To Reproduce**
1. Import the above schema as raw JSON
2. Check `Headers` values for path

**Expected behavior**
The `Headers` value should be a dropdown / pre-populated with the enum values

**Screenshots**
![Postman-header-value-enum](https://user-images.githubusercontent.com/37812673/77776390-2e2eed80-700b-11ea-8328-d9cdfa41cc21.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.16.0
 - OS: macOS Catalina 10.15.3

**Comment by VShingala** [comment]
@rob4629 Thanks for raising the issue.

You can select options while Importing or Generating collection from API definition under `Show advanced settings` dropdown. Make sure you select `Example` for options `Request parameter generation` and `Response parameter generation`. This will make sure that the value that is generated adheres to the schema. For the API definition mentioned, the header value will be one of the values under enum.

We are closing this issue, for now. Feel free to reopen this issue if you have any further problems with this.
