### ISSUE TITLE
Query parameters are inconsistently passsed to server when using enable/disable checkbox

### ISSUE THREAD

**Issue by mtaylorfsmb** [a85/POSTMan-Chrome-Extension#8251]
**Describe the bug**
When enabling/disabling query parameters in the UI it is inconsistent whether Postman actually sends the parameter irrelevant of what is shown in the path URL.

**To Reproduce**
1. Create a new GET request that goes to a URL of the form: `https://www.tempuri.org/documents?field1=&field2=&field3=`
2. The query parameters should show up in the Query Params area, checked
3. Set `field1` to `test`
4. Uncheck `field2`
5. Set `field3` to `123`
6. Save the request and close the tab
7. Reopen the request and the query parameters should be properly shown.
8. Send the request and use the `Code` button to see what curl command was used.
9. Check the `field2` parameter and assign it a value.
10. Notice the URL changes accordingly.
11. Send the request again.
12. Check what was sent via curl.
13. In my case `field2` may be in the URL that was sent but there is no value. In other cases it isn't sent at all.
14. Set `field2` to a new value and try again. Same behavior.
15. Uncheck `field1` or `field3` and verify the query is sent without these parameters.
16. Check the parameter back and send again. Once again the parameters are sent. 

*Note: This is not an issue with sending to curl itself. I originally started looking into this when testing my own API and finding that not all the parameters I was setting are making it to my API. This seems like a general issue with how Postman is sending data.*

In my experience if you start with a saved request that already has all the parameters enabled (irrelevant of whether they have values or not) then it is less likely Postman will "skip" those parameters.

**Expected behavior**
When toggling query parameters on and off the corresponding request should either included or not include the parameter based upon this setting. The URL shown in the UI should exactly match what is being sent via the code behind the scenes (e.g. curl).

**Screenshots**
![postman_curl](https://user-images.githubusercontent.com/38144840/77777574-c1711e80-701d-11ea-8017-7cec563a6295.png)
![postman_UI](https://user-images.githubusercontent.com/38144840/77777576-c209b500-701d-11ea-824a-fa51716962c6.PNG)

**App information (please complete the following information):**
 - App Type: Windows native app
 - Postman Version 7.21.1 (happened on previous version as well)
 - OS: Windows 10

**Comment by vikiCoder** [comment]
Hi @mtaylorfsmb,

This issue is fixed in the latest release of the Postman app (v7.24.0). Please update to the latest version to check it out. Feel free to reopen the issue if the problem still persists.
