### ISSUE TITLE
Canary: Unable to Beautify

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#8253]
Version: Version 7.22.0-canary03 (7.22.0-canary03)

I created an HTTP request with the body (end of the ticket).

I clicked on "Beautify" and nothing happened.

Body:
{
        "id": 2,
        "cloudUserId": {{CLOUD_USER_ID}},
        "legacyUserId": {{LEGACY_USER_ID}},
        "accountId": {{ACCOUNT_ID}},
        "subAccountId": null,
        "releaseId": 88881,
        "title": "foo1",
        "body": {
            "pressKit": {
                "name": {
                    "key": "{http://businesswire.com/schemas/presskit}PressKit",
                    "prefix": "",
                    "string": "{http://businesswire.com/schemas/presskit}PressKit",
                    "localPart": "PressKit",
                    "namespaceURI": "http://businesswire.com/schemas/presskit"
                },
                "value": {
                    "booth": "12",
                    "title": "Test Org",
                    "contacts": {
                        "contact": [
                            {
                                "eMail": "test@test.com",
                                "phone": "123-123-1234",
                                "title": "",
                                "lastName": "testlastname",
                                "TYPE_NAME": "pressKit.ContactType",
                                "firstName": "testname",
                                "contactTypeCode": "3",
                                "contactTypeOther": ""
                            },
                            {
                                "eMail": "test@test.com",
                                "phone": "123-123-1234",
                                "title": "",
                                "lastName": "testlastname",
                                "TYPE_NAME": "pressKit.ContactType",
                                "firstName": "test2name",
                                "contactTypeCode": "2",
                                "contactTypeOther": ""
                            }
                        ],
                        "TYPE_NAME": "pressKit.PressKit.Contacts"
                    },
                    "headline": "Test Org to Exhibit at 2018 QA INT Trade Show",
                    "TYPE_NAME": "pressKit.PressKit",
                    "companyFax": "",
                    "companyUrl": "http://www.test.com",
                    "companyName": "Test Org",
                    "description": "Test description",
                    "companyPhone": "123-123-1234",
                    "maxAssetCount": 3,
                    "customerNumber": 2187507,
                    "pressKitPermaLink": "testtest",
                    "companyAddressCity": "Fake City",
                    "companySocialLinks": {
                        "TYPE_NAME": "pressKit.PressKit.CompanySocialLinks",
                        "companySocialLink": [
                            {
                                "link": "https://www.facebook.com/YourFacebookPage",
                                "TYPE_NAME": "pressKit.CompanySocialLinkType",
                                "socialTypeCode": "Facebook"
                            },
                            {
                                "link": "https://twitter.com/YourTwitterPage",
                                "TYPE_NAME": "pressKit.CompanySocialLinkType",
                                "socialTypeCode": "Twitter"
                            },
                            {
                                "link": "https://www.youtube.com/YourYouTubePage",
                                "TYPE_NAME": "pressKit.CompanySocialLinkType",
                                "socialTypeCode": "YouTube"
                            },
                            {
                                "link": "https://www.linkedin.com/YourLinkedInPage",
                                "TYPE_NAME": "pressKit.CompanySocialLinkType",
                                "socialTypeCode": "LinkedIn"
                            }
                        ]
                    },
                    "participationLevel": "Exhibitor",
                    "tradeShowEventGuid": "527e8d6b694a9c283c412310bdb68a0c",
                    "tradeShowGenreNote": "2018 QA INT Trade Show",
                    "tradeShowPermaLink": "2018-qa-int-trade-show",
                    "companyAddressState": "OH",
                    "companyAddressStreet1": "123 Fake St.",
                    "companyAddressStreet2": "",
                    "companyAddressPostalCode": "12334",
                    "companyAddressCountryCode": "US"
                }
            },
            "releaseText": {
                "name": {
                    "key": "{http://businesswire.com/schemas/ReleaseText}ReleaseText",
                    "prefix": "",
                    "string": "{http://businesswire.com/schemas/ReleaseText}ReleaseText",
                    "localPart": "ReleaseText",
                    "namespaceURI": "http://businesswire.com/schemas/ReleaseText"
                },
                "value": {
                    "TYPE_NAME": "releaseText.ReleaseText",
                    "edgarFiling": {
                        "cccCode": "33333333",
                        "cfrForm": "6-K",
                        "cikCode": "0123456789",
                        "TYPE_NAME": "releaseText.EdgarFilingType",
                        "comboPack": true,
                        "registrant": {
                            "TYPE_NAME": "releaseText.RegistrantType",
                            "contactName": "ryan",
                            "contactEmail": "some.email@gmail.com",
                            "contactPhone": "4156222222"
                        },
                        "billingCode": "6KK",
                        "reviewByDate": "05-Sep-2019",
                        "reviewByTime": "15:00",
                        "htmlConversion": "Yes",
                        "reviewByTimeZone": "PT"
                    },
                    "socialMedia": [
                        {
                            "language": "en",
                            "TYPE_NAME": "releaseText.SocialMediaType",
                            "twitterHandle": "@yresnob"
                        }
                    ],
                    "amfRegulatory": {
                        "TYPE_NAME": "releaseText.AMFRegulatoryType"
                    },
                    "releaseThemes": {
                        "TYPE_NAME": "releaseText.ReleaseThemesType",
                        "releaseTheme1": 8
                    },
                    "pullQuoteTweet": {
                        "TYPE_NAME": "releaseText.PullQuoteTweetType",
                        "disableTweetBtn": "false",
                        "disablePullQuote": "false"
                    },
                    "releaseSummary": "rel summary",
                    "smartMarketing": {
                        "font": "arial",
                        "theme": "custom",
                        "header": "color",
                        "layout": "1",
                        "TYPE_NAME": "releaseText.SmartMarketingType",
                        "background": "color",
                        "mmFeatured": "featured",
                        "pageBkSpec": "#AD6D6D",
                        "socialAbout": "about",
                        "headerBkColorSpec": "#6E4646",
                        "contentBkColorSpec": "#A36F6F",
                        "headerTextColorSpec": "#755252",
                        "contentTextColorSpec": "#A85C5C"
                    },
                    "requireCopyApproval": "Yes",
                    "organizationInformation": {
                        "TYPE_NAME": "releaseText.OrganizationInformationType",
                        "securitiesIdentifier": [
                            {
                                "isin": "FR0000133308",
                                "exchange": "NYX",
                                "TYPE_NAME": "releaseText.SecuritiesIdentifierType",
                                "tickerSymbol": "appl"
                            }
                        ]
                    }
                }
            }
}
}

**Comment by jcald1** [comment]
I left off the quotes around the variable name.

**Comment by jcald1** [comment]
This issue happens in the current version of Postman.  It happens when using numeric variables in the HTTP body.

**Comment by DannyDainton** [comment]
This happens when the body contains dynamic variables (`{{....}}`) as it believes it's not valid JSON.

This following message can be seen in the console:

<img width="1008" alt="Screenshot 2020-03-29 at 21 33 54" src="https://user-images.githubusercontent.com/17089546/77860085-158a2780-7205-11ea-8903-e9f6302e7e9e.png">

By removing these key/values from the body and then selecting `Beautify`, you will see that the feature works correctly.

```
"cloudUserId": {{CLOUD_USER_ID}}
"legacyUserId": {{LEGACY_USER_ID}}
"accountId": {{ACCOUNT_ID}}
```

**Comment by kamalaknn** [comment]
Hey @jcald1 

Thanks for reporting this issue. As @DannyDainton pointed out this is because Postman is not able to beautify JSON that contain variables. We are tracking this in #4313 

I'm closing this as a duplicate. Please follow the original issue for updates.
