### ISSUE TITLE
Params list doesn't scroll when moving row up or down on Params tab.

### ISSUE THREAD

**Issue by mvv-acc** [a85/POSTMan-Chrome-Extension#8257]
**Describe the bug**
When list of params is making scroll bar enabled, it's impossible to move one row from bottom to top with one mouse drag (list of Params doesn't scroll automatically).

**To Reproduce**
1. Create new POST request.
2. In Params tab create as many Key - Value combinations as needed for scroll bar to appear.
3. Scroll down and try to move bottom row to the top.
4. Observe that list isn't moving and you need few drag&drops to move the Parameter further.

**Expected behavior**
List is scrolled automatically.

**App information (please complete the following information):**
 - Postman Version [e.g. 7.21.1]

**Additional context**

**Comment by lflucasferreira** [comment]
The shortcut for moving up and down the rows is not working either. 

**CMD + SHIFT + Arrow UP (or Arrow Down)**

It displays "Something Went Wrong" and makes me unable to return to the request, so I lose them.

**Comment by lucifercr07** [comment]
@lflucasferreira Thanks for reporting the issue, we are now tracking it as part of this [issue](https://github.com/postmanlabs/postman-app-support/issues/9157).

**Comment by lucifercr07** [comment]
@mvv-acc Sorry but I couldn't validate the issue, if we drag the param to be moved at the top of the param tab the list scrolls up automatically and we can place the param at the top. Do let me know if you're still facing the issue.

**Comment by lucifercr07** [comment]
@mvv-acc  issue is not reproducible in current builds of postman, hence closing the ticket. Please let us know if further assistance is required regarding this.
