### ISSUE TITLE
completely disable automatic updating, please

### ISSUE THREAD

**Issue by ks1977** [a85/POSTMan-Chrome-Extension#8259]
Hi, 

We are working in a locked down environment, meaning our company policy prohibits users from installing software updates.  Could we please obtain a version where **all kind of updates** can be disabled **completely**?

Thanks a million!

**Comment by arlemi** [comment]
Hi @ks1977 ,

We already have a feature request in for that, please add to it there. :)
https://github.com/postmanlabs/postman-app-support/issues/7944

**Comment by ks1977** [comment]
> Hi @ks1977 ,
> 
> We already have a feature request in for that, please add to it there. :)
> #7944

OK... and when do you guys plan to implement this (for companies much needed) feature ?

**Comment by arlemi** [comment]
This isn't planned for now but we will update the linked topic if anything changes!

**Comment by ks1977** [comment]
Still not planned?  And also: when will it be possible to choose a different installation directory?  We really need this!

**Comment by arlemi** [comment]
@ks1977 This one is tracked in #6999.

**Comment by stefanluchian** [comment]
@ Postman guys: Why are you insisting to force us to update, even on minor updates?
This is no way to win new users! And you might lose existing ones.
We simply don't want automatically minor updates! Is it so hard to understand it?
We are not some mobile-app-freaks who just want to have the latest thing.
Just let us decide if and when we want minor updates!
This is really annoying!
Stop forcing us to update! Should be our decision!
