### ISSUE TITLE
Canary: Removing Path Parameters Does Not Clear the Green Circle

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#8262]
Version: Version 7.22.0-canary03 (7.22.0-canary03)

Create a PUT or POST request.
Add a path parameter key.
Unclick the query parameter.  The green circle is not cleared.
If you click it again and delete the individual values then unclick it again, it still doesn't clear the green circle

**Comment by vvs11** [comment]
@jcald1, it clears the green circle if you remove the entry by clicking the 'x' button on the right end of the row.
Green circle only indicates presence of a query parameter, if you uncheck it and send the request, these params don't get sent
