### ISSUE TITLE
Allow Multiple Snapshots Per Collection

### ISSUE THREAD

**Issue by jcald1** [a85/POSTMan-Chrome-Extension#8265]
It would be nice to be able to have multiple snapshots per collection.

Alternatively, is there a way to have at least one snapshot per version of an API or collection?

**Comment by vvs11** [comment]
@jcald1  we support versioning of collections. Please go through the documentation and see if it satisfies your use case.
https://learning.postman.com/docs/postman/collections/version-control-for-collections/

https://learning.postman.com/docs/postman/design-and-develop-apis/versioning-an-api/

You can also post queries on our community 
https://community.getpostman.com/
