### ISSUE TITLE
Problem with importing multiple security headers while importing OpenAPI docs

### ISSUE THREAD

**Issue by prondzyn** [a85/POSTMan-Chrome-Extension#8266]
**Describe the bug**
The import Open API json file is not working properly for multiple secrets headers.

**To Reproduce**
1. Save [attached docs](https://github.com/postmanlabs/postman-app-support/files/4413888/example.txt) as a JSON file.
2. Go to 'Import'
3. Go to 'Import File' tab
4. Choose the JSON file
5. As a result you will get an imported collection, but when you go into the details of the example endpoint you will see only one header - `access-token`, as on the below screenshot.

**Expected behavior**
I'm expecting to see both `access-token` and `secret-token` in the headers.

**Screenshots**
![imported_in_postman](https://user-images.githubusercontent.com/5822647/78117350-d971e500-7405-11ea-8629-79d1892586c6.png)

**App information (please complete the following information):**
 - Postman v7.21.1

**The JSON file content**
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "TEST",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "security": [
    {
      "access-token": [],
      "secret-token": []
    }
  ],
  "paths": {
    "/v1/examples": {
      "get": {
        "tags": [
          "EXAMPLE"
        ],
        "operationId": "get examples",
        "parameters": [
          {
            "name": "query",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "default response",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Example"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Example": {
        "type": "object",
        "properties": {
          "value1": {
            "type": "string"
          },
          "value2": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "access-token": {
        "type": "apiKey",
        "name": "access-token",
        "in": "header"
      },
      "secret-token": {
        "type": "apiKey",
        "name": "secret-token",
        "in": "header"
      }
    }
  }
}
```

**Comment by CosmicAnalogue465** [comment]
@abhijitkane same, were you able to solve this ?

**Comment by chughmayank** [comment]
Hi @prondzyn  - Apologies for reverting late on this issue. Currently we only support a single authentication scheme at the collection & folder level. And for adding support for multiple Auth is already open and is being worked on. You can track it here: #6833 

Closing this ticket for now. Feel free to reach out to us in case of any queries.

**Comment by prondzyn** [comment]
@chughmayank thanks for the reply. I will be watching #6833

**Comment by clintberry** [comment]
It appears that #6833 doesn't address this problem. If an open api spec has multiple security schemas, when generating the collection from it, it only uses one of them. If it has multiple header-based auth schemas, it only uses the first. If two auth headers are required the generation does not work.
