### ISSUE TITLE
Postman extremely slow

### ISSUE THREAD

**Issue by GranitBerisha** [a85/POSTMan-Chrome-Extension#8269]
Version : 7.21.1 (7.21.1)
Macos : 10.15.4 (19E266)

I cant even make a request is extremly slow, I have to restart 2-3 times jus to get a response back. 
The idea is that it works great after I change the window/app and come back tto make another request it freezes and have to wait 1-2minutes to get it back working 

cpu usage : 

 Postman Helper	90.3	41:42.70	39	8	0.0	0.00	22779	granitberisha	(null)	-	No	No	No	0 bytes		0 bytes	0 bytes	0 bytes	No	No	(null)	0 bytes	0 bytes	0	0	0 bytes	0 bytes	0 bytes	0 bytes	No	

Memory : 

 Postman Helper	1.30 GB	36	283	22779	granitberisha	0.7	41:54.70	11	0.0	0.00	(null)	-	No	No	No	0 bytes	0 bytes	0 bytes	No	No	(null)	0 bytes	0 bytes	0	0	0 bytes	0 bytes	0 bytes	0 bytes	No

**Comment by numaanashraf** [comment]
Thanks for reporting this. We have a ton of performance improvements that is planned to hit stable soon and this issue might be resolved in the coming release. These fixes are currently available on our early access builds - https://www.postman.com/downloads/canary. It'll help us a lot if you could try this build out and let us know if performance is better.

**Comment by GranitBerisha** [comment]
huhh I should had open this issue days ago, thanks the canary build is working great for now.

**Comment by numaanashraf** [comment]
That's great to hear @GranitBerisha. These improvements will be available on the stable build next week.

**Comment by fenoloco** [comment]
Canary version has the same issue.. so I think will not be solved on the next stable build.. You need to improve a lot the performance for fork, merge and the app itself.. 
This application is becoming an non enterprise level.. works if you are playing with 2 services but wen you have more than 30 collections and more than 10 thousands test its not working fine.

**Comment by daceves** [comment]
I'm having some slowness with PostMan as well. I was wondering if there was a way to enable a debug mode or where can I find logging as to what PostMan is doing. At times I suspect its not PostMan but rather my connection. However, there are enough instances where its clearly PostMan "hanging" and not responding. 

Here are specifically the type of things I would love to get some help with finding:
Logs for requests being made - Looking for information beyond what happened from client to backend service. I've had instances where I make a request and all is right with the world. But I can't make a subsequent requests. At least not for about 10-15 seconds. The application appears to freeze. I'm curious to know what its doing.

Logs for Workspace synchronization - If I haven't had PostMan open all day, it seems like the workplace synchronization pins whatever other operations a user may want to do and focuses on synchronization. Its very slow to create a new method/tab/request. I'm only a part of 2 other workspaces which are I'd say medium sized. 50-60 APIs in each of the workspaces. 

I'm of course assuming this kind of logging exists. I'll try to do a little digging.

**Comment by arlemi** [comment]
@daceves Here's info on where to find the Postman logs: https://support.getpostman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-

Can you check if you have a lot of history saved in the app? (in the `History` sidebar)

**Comment by OliverRC** [comment]
I have an issue where Postman just sits there creaming the CPU at idle (Intel i7-8665U)
![image](https://user-images.githubusercontent.com/1888486/86341501-acc4a800-bc56-11ea-83f2-0408bd66c327.png)
![image](https://user-images.githubusercontent.com/1888486/86341513-afbf9880-bc56-11ea-8320-085c9e87c210.png)

**Comment by vileppanen** [comment]
> @daceves Here's info on where to find the Postman logs: https://support.getpostman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-
> 
> Can you check if you have a lot of history saved in the app? (in the `History` sidebar)

Had this massive performance issues also in macOS 10.15.7 and Postman version 7.33.1

Saw this hint about the History data and clearing them, after doing so I'm currently experiencing much better performance.

Before doing the clearing, the activity monitor showed Postman process to constantly being at some > 100% of CPU time.

After clearing histories, it dropped below 10% 🤷

**Comment by samhk222** [comment]
![image](https://user-images.githubusercontent.com/58010/99665083-e8b2ab00-2a47-11eb-8feb-4e831c41ddda.png)

**Comment by solid-ahlholm** [comment]
Thanks @arlemi, clearing the history solved my problem, going from constant +30% CPU usage to <1%

**Comment by ValdoGhafoor** [comment]
Postman takes more than 30s to open on Macbook pro M1 (empty postman, no requests, not the first open)
When it finally opens, UI takes around 9 secondes to load (white screen)
v8.2

We are seeking for alternatives as this is no longer acceptable for a business

**Comment by g4z** [comment]
i never used the history tab before. turns out it was the reason for the terrible performance. the UI froze for 15 mins as it cleared the history, i disabled the save history function and finally Postman is usable for the first time since version 7 was release :/ i wish i had found this earlier :facepalm:

**Comment by kamalaknn** [comment]
We've released many improvements to how Postman loads collections and history in workspaces. Do try out the [latest version](https://www.postman.com/downloads/) and let us know if you are still facing any issues.
