### ISSUE TITLE
Authorization header gets generated twice for Basic Auth type request 

### ISSUE THREAD

**Issue by anilaselwyn-nbcuni** [a85/POSTMan-Chrome-Extension#8271]
Authorization header gets generated twice for Basic Auth type request 

**Steps to reproduce the behavior:**
1. Trying to get an amazoncongnito token
2. Post request 
3. Use Authorization type Basic Auth with Valid username & password 
4. See curl 

{code}
curl --location --request POST 'https://host-xyz' \
--header 'Authorization: Basic xyz' \
--header 'Cache-Control: no-cache' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Host: xyz.amazoncognito.com' \
--header 'Postman-Token: generated postman token' \
--header 'User-Agent: PostmanRuntime/7.15.0' \
--header 'accept-encoding: gzip, deflate' \
--header 'content-length: ' \
--header 'cookie: XSRF-TOKEN=generated token' \
--header 'Authorization: Basic xyz='
{code}

**Error**: 
400 Bad Request

**Expected behavior**
200 and a good response 

I'm unable to get rid of the headers that are generated twice

**Comment by shreys7** [comment]
Hey @anilaselwyn-nbcuni , can you mention the App version in which you are facing this issue?
Go to Settings icon(top right) -> Settings -> About

**Comment by anilaselwyn-nbcuni** [comment]
Hi ,

Here’s the version -

Postman for Mac
Version 7.21.1
OS X 18.7.0 / x64

Thanks,
Anila

**Comment by shreys7** [comment]
I tried reproducing this on **Postman 7.21.1** but could not reproduce by the steps you mentioned above. Can you provide detailed steps to reproduce and/or screenshots, video recordings to help us solve the issue? @anilaselwyn-nbcuni 
![image](https://user-images.githubusercontent.com/20665864/78166068-ddcfe980-7469-11ea-9418-ab40f27580c0.png)
![image](https://user-images.githubusercontent.com/20665864/78166099-e9231500-7469-11ea-9dda-0e3a0ef0cf05.png)

**Comment by anilaselwyn-nbcuni** [comment]
Hey Shrey,
If you click on the headers tab you can see Authorization header being sent twice and that was causing an issue with the response.
But I just downloaded Version 7.21.2 and I don’t see that issue anymore. For e.g: in the below screenshot I would see Authorization header being sent twice in the request.
But I don’t see an issue anymore. I get the expected response

[cid:image001.png@01D60A9C.937CE4A0]

Thanks,
Anila
