### ISSUE TITLE
Postman will not work on my laptop no matter what I do

### ISSUE THREAD

**Issue by afelthe** [a85/POSTMan-Chrome-Extension#8272]
**Describe the bug**
Postman will not work on my computer no matter where I am, no matter what browser I use and no matter which aspect of the error I try to troubleshoot with other github documentation.  All requests result in the following error:

Could not get any response

Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

**To Reproduce**
Without disclosing my access tokens I cannot really reproduce this for you.

**Expected behavior**
The same request works in Fiddler, so basically, I know the request has been structured properly.  It should result in a response JSON file.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by ProBeta1** [comment]
@afelthe Seems you are trying to configure Postman for the first time . The chrome app is deprecated for start , so you must use only the native apps . Then try following in the same order :

1. Check and recheck the proxy settings.
2. Open Postman Console (View -> Show Postman Console).
3. Send a request , you may like to follow [this](https://learning.postman.com/docs/postman/sending-api-requests/requests/#adding-request-detail).

If this works , that's great :1st_place_medal: . If not , post the screenshot of the console logs here .

**Comment by vvs11** [comment]
@afelthe Please let know if you're able to get this working

**Comment by vvs11** [comment]
Closing for now. Please feel free to reopen if you're still seeing the issue. You can also post queries on our community: http://community.getpostman.com/  to get quick response
