### ISSUE TITLE
Ubuntu Software does not install newest snap

### ISSUE THREAD

**Issue by beruic** [a85/POSTMan-Chrome-Extension#8273]
**Describe the bug**
Installing the snap version of Postman from Ubuntu Software will use the channel `V6/stable` instead of `latest/stable`.

**To Reproduce**
1. Open Ubuntu Software.
2. Search for Postman.
3. Open the single found item.
4. Check which channel it will install from and try to change it.

**Expected behavior**
I expected to be able to install the same version as from https://www.postman.com/downloads/.

**Screenshots**
Sorry my screenshot is in Danish.
![screenshot_2020-04-02 00-54-08](https://user-images.githubusercontent.com/724716/78194329-204ef180-747d-11ea-9a24-af8ecdfc63c8.png)

**App information (please complete the following information):**
 - App Type [Native app from Snap]
 - Postman Version [7.21.1]
 - OS: [Ubuntu 19.10]

**Additional context**
It is possible to install `latest/stable` from terminal with `sudo snap install postman`, but Ubuntu Software still thinks it is `V6/stable` that is installed.

**Comment by harryi3t** [comment]
@beruic Thanks for bringing this to our attention.
Looks like Ubuntu software is not picking the `default` track but the custom track `v6` that we had created to support teams who have not migrated to [Postman v7](https://learning.postman.com/docs/administration/migrating-to-v7/)

I checked that other snap apps are facing the same issue (like skype).
We are checking with the snap team on how to fix this issue
https://forum.snapcraft.io/t/track-request-v6-for-postman/13425/9?u=harryi3t

**Comment by beruic** [comment]
Seems like this has been fixed now. Just installed 7.22.1 through Gnome from channel latest/stable.

It doesn't start though. It just exits immediately when running, without anything written to stdout.

**Comment by beruic** [comment]
So. Is my above comment a new issue, or will you just continue with this one?

**Comment by harryi3t** [comment]
@beruic It would be a different issue if the app is not opening. This is only tracking the outdated version being shown on the Ubuntu Software.

Can you try updating to the latest version: v7.26.0? In this, we have fixed an issue where Postman was not launching on the Linux system using the Wayland protocol. If that still does not fix the issue, please create a new one for that.

**Comment by beruic** [comment]
@harryi3t I can confirm that the newest snap runs under Wayland on Ubuntu 19.10.

**Comment by twitharshil** [comment]
Marking the issue closed as it is fixed now 👍
