### ISSUE TITLE
Private Mock Server apikey as query param not working, x-api-key in header is fine

### ISSUE THREAD

**Issue by maconrad** [a85/POSTMan-Chrome-Extension#8274]
Hi All

When marking a mock server as private, setting the API Key via Query Param (named apikey as per documentation) results in mockNotFoundError. When using the same mock server/endpoint with x-api-key and using the Header, results are returned without a problem.
Tested with 2 different Mock Servers, same behaviour. 

{
    "error": {
        "name": "mockNotFoundError",
        "message": "Please refresh and try again."
    }
}

**To Reproduce**
1. Pick any mock server
2. Set authorization to apikey and Add to Query Params
3. Send request

**Expected behavior**
Setting apikey via Query Param should return same result as with x-api-key set via header.

**App information (please complete the following information):**
 - App Type -Native App
 - Postman Version - v7.21.1
 - OS: Win10

Saw some other issues related, but they state it should be fixed by version 7.20.
https://github.com/postmanlabs/postman-app-support/issues/7758

Reference: https://documenter.getpostman.com/view/631643/JsLs/?version=latest#authentication

**Comment by DannyDainton** [comment]
That appears to be an older version of the Postman API documentation - The new UI states that only the `x-api-key` can be used in the header.

![image](https://user-images.githubusercontent.com/17089546/175936957-9d4c218d-5e4e-4930-9dbc-7b2faaa08ab9.png)

More details can also be found in the learning center:
https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/setting-up-mock/#configuring-mock-details
