### ISSUE TITLE
Problem with adding description for more than one folder in a collection

### ISSUE THREAD

**Issue by RezDev94** [a85/POSTMan-Chrome-Extension#8276]
**Describe the bug**
I have a collection with multiple folders inside, when I add description for more than one folder, It's getting messy.

**App information:**
 - App Type [Native App]
 - Postman Version [7.21.1]
 - OS: Ubuntu

**Comment by Raja-Simha** [comment]
@RezaT1994 could you elaborate more on the issue. Not really sure what you mean by 'messy'. Any screenshots or steps to reproduce will be helpful.

**Comment by RezDev94** [comment]
Here is the messy screenshot
![Screenshot from 2020-04-03 16-20-10](https://user-images.githubusercontent.com/31609638/78358110-e1798280-75c7-11ea-9eb6-dc2effb6c19a.png)

But when I click on view more It got fixed
![Screenshot from 2020-04-03 16-20-28](https://user-images.githubusercontent.com/31609638/78358168-f9e99d00-75c7-11ea-8e27-4ea81eb54a4c.png)

**Comment by DannyDainton** [comment]
Hey @RezaT1994 

Given the information that you have provided, it's going to be difficult to recreate this issue. I'm going to close this for now but if you can provide clear steps to produce the problem or a link to an existing collection, we can look to investigate this further.
