### ISSUE TITLE
Do not cut users off from using the Postman app when a sync conflict occurs.

### ISSUE THREAD

**Issue by shivros** [a85/POSTMan-Chrome-Extension#8277]
**Is your feature request related to a problem? Please describe.**
Postman froze after I finished adding ~30 requests to a collection. I had to kill the process and when I restarted, I was given an error screen with the only option being "Use server changes".

The rest of the app is inaccessible, making it very difficult for me to back up any of my work.

**Describe the solution you'd like**
Either there should be a "Use local changes" button alongside the "Use server changes" button, or the app shouldn't lock me out from doing exports or backing up all of the work I'd put in before the crash.

**Describe alternatives you've considered**
There aren't really alternatives here. Postman presents one option - to paraphrase - "Lose all of your unsaved work".

It seems reasonable and low-effort to allow a user to utilize exports, collection duplication, or some other method of backing up local changes.

Everything needed already exists in Postman. The only barrier is the fact that the error screen cuts users off from accessing the app entirely. Just don't do that.

**Additional context**
![use-server-changes](https://user-images.githubusercontent.com/8656127/78296487-119f2380-74eb-11ea-965b-081e50e6604c.png)

**Comment by ankitjaggi** [comment]
Hey @typenil! This is certainly not the experience we expect to provide you. Can you send an email over to help@getpostman.com with the app logs and any more screenshots that you can help us with?

**Comment by ankit-m** [comment]
We have pushed out a fix which does not block you in case of sync errors.
