### ISSUE TITLE
Semicolon not working in URL

### ISSUE THREAD

**Issue by eliassal** [a85/POSTMan-Chrome-Extension#8278]
**Describe the bug**
I have a node.js app and trying to do some sql test. When I run the query and append ";", it fails and get an error in the node web application whereas without it works fine and I get a response 

**To Reproduce**
1. Enter salam7:8081/adventureproc/12
2. Click on send
3. I get a response as follows
{
        "RecursionLevel": 0,
        "BusinessEntityID": 12,
        "FirstName": "Thierry",
        "LastName": "D'Hers",
        "OrganizationNode": "/1/1/5/1/",
        "ManagerFirstName": "Ovidiu",
        "ManagerLastName": "Cracium"
    },
4. salam7:8081/adventureproc/12**;**
after 10 or 15 seconds I get 
and in my node app log I see
**Screenshots**
![Postman](https://user-images.githubusercontent.com/8447864/78297816-ad06b780-7530-11ea-8e9e-aae4aafd3cbd.jpg)

**App information (please complete the following information):**
 - App Type = Chrome App, 
 - Postman Version = Postman for Chrome Version 5.5.5
 - OS: win 10 64bit

**Comment by eliassal** [comment]
Hi, any news?

**Comment by SabriH10** [comment]
Hi @eliassal,

The latest blog post entitled `Introducing the Next-Generation Postman URL Processor` discusses a feature that may potentially address your concern ( no guarantee but worth trying). The post can be found here:
https://blog.postman.com/2020/04/06/introducing-the-next-generation-postman-url-processor/

If you'd then like to enable the feature and see if it helps you can go to your Settings ---> General and under `Request` you should see `Use next generation URL processing` and switch that on. Would you like to give that a try and see if it helps?

**Comment by vvs11** [comment]
@eliassal, hope this resolves your issue. If it doesn't, please feel free to post a query/problem on our community.
https://community.getpostman.com/

**Comment by eliassal** [comment]
Hi, ther is no this option in settings as you can notice in the snapshot
![PostmanSetting](https://user-images.githubusercontent.com/8447864/79048102-f767f280-7c1a-11ea-8eb3-75f98a60a87b.jpg)

**Comment by eliassal** [comment]
I upgraded to Postman-win64-7.22.1, now I have the option but it did not help. Withou the "**;**" it works fine as you can notice in the 2 snapshots

![PostmanSetting_002](https://user-images.githubusercontent.com/8447864/79048334-b2dd5680-7c1c-11ea-89ca-86931aedd404.jpg)

When "**;**" is added it keeps looping for almost 5 to 10 minutes
![PostmanSetting_003](https://user-images.githubusercontent.com/8447864/79048346-cc7e9e00-7c1c-11ea-806a-5947631714af.jpg)


then it fails
![PostmanSetting_004](https://user-images.githubusercontent.com/8447864/79048364-e9b36c80-7c1c-11ea-9520-69c9814e7a5b.jpg)

**Comment by eliassal** [comment]
Hi, any feedback on this? Thanks

**Comment by codenirvana** [comment]
@eliassal Can you share a scaled-down collection (or the API endpoint) which we can use to reproduce this issue?

I think you are facing issues in the requesting server which is timing out because that route is not handled.

**Comment by eliassal** [comment]
Hi, you can visit 
https://github.com/ScaryDBA/PresentationCode
The APIs I am using is using the js files in SQLInjection directory
https://github.com/ScaryDBA/PresentationCode/tree/master/SQLInjection

**Comment by codenirvana** [comment]
@eliassal Thanks for this reference repository but unfortunately I can't set up this server on the machine (because of win32 OS requirement).

But, I went through the source and set up a similar local server and I can confirm that this is not an issue of Postman or semicolon in the URL.

**Comment by eliassal** [comment]
OK thanks for your help. A question regarding postman tests. It seems it has a rich collection of APIs to right test, is there a plugin/ or addon for intellisense to help writing tests and being more productive?

**Comment by codenirvana** [comment]
@eliassal We are currently working on IntelliSense in scripts and you can try out the new editor changes in our [Canary](https://www.postman.com/downloads/canary) channel.

For more updates, follow https://github.com/postmanlabs/postman-app-support/issues/3919
