### ISSUE TITLE
Shared Collection Experiencing Intermittent Request Reordering Inside folders

### ISSUE THREAD

**Issue by bensullivan** [a85/POSTMan-Chrome-Extension#8279]
**Describe the bug**
We use Postman to automate workflows with our API and then assert responses from specific requests to ascertain if the workflow has behaved correctly.  We have a collection that is shared between two users.  We duplicate folders to create new tests quickly (and then modify the duplicated folder and requests contained therein).  One user is using Postman on Windows (v7.21.1) and I am using the latest release on macos.

**To Reproduce**
We can't reproduce reliably but we're intermittently seeing requests within folders losing the ordering we setup when the other user opens the collection with their client.  They seem to go from POST -> GET -> PATCH -> GET to GET -> GET -> POST -> PATCH.  We could use setNextRequest to make the execution more reliable but the ordering is very important to us to understand the intent of the workflow the test is based on when we look at the test in the collection explorer.  We will not be able to effectively maintain our workflow tests without reliable ordering of the test requests.

**Expected behavior**
When one user duplicates a folder in the shared collection and rearranges the request ordering for the new test, when the other user opens the collection, the order of the requests within the folder are as the first user arranged them.

**App information (please complete the following information):**
 - App Type [Native]
 - Postman Version [Windows v7.21.1, macos v7.21.1]
 - OS: [Windows 10, macos 10.15.4]

We have a paid subscription - Team name is Core Illumination and slug is coreillumination.  Users are ben@coreillumination.com and jo@coreillumination.com

**Comment by DannyDainton** [comment]
Hey @bensullivan,

Is this an issue that you're still seeing in the latest app version?

**Comment by DannyDainton** [comment]
Hey @bensullivan 

I'm going to close this one out, if it's still an issue, we can open in back up and take a look at any new information you might have.
