### ISSUE TITLE
Postman freezes

### ISSUE THREAD

**Issue by alogim** [a85/POSTMan-Chrome-Extension#8281]
**Describe the bug**
Simply open Postman, perform a request and the application freezes. 

**To Reproduce**
1. Open Postman either from the command line or from the desktop shortcut
2. Perform a simple request
4. The application hangs and does not respond to the user any more.

**Expected behavior**
The application should work smoothly and should not freeze.

**App information (please complete the following information):**
 - App Type: native app
 - Postman Version: 7.21.1
 - OS: archlinux, tried installing it both manually (by downloading the application from the official web site) and from the AUR 

**Notes:**

- I do not have any collection, any API or element in history. I deleted everything to make sure that  the outputs of the old request did not interfere. 

- The response of the call is a JSON array, with a size of 15.84 KB (710 lines).

- I am on archlinux, with Xfce4 4.14 and electron 4.2.12.

**Comment by numaanashraf** [comment]
@alogim Thanks for reporting this. We do not officially support Arch Linux at the moment and the version available on AUR is community maintained. The current version of Postman uses a custom build of Electron, which is not public, and Postman with `Electron 4.2.12` is not officially tested or compatible. We recommend reaching out to the AUR community or Postman community (http://community.postman.com/) for help with this issue.

**Comment by alogim** [comment]
I see you have closed the issue, however, as I have explained, I also tried the version on the website and I have the same exact problem. Nonetheless, I will follow the link you published and ask for help there.
