### ISSUE TITLE
Duplicating duplicated requests fails

### ISSUE THREAD

**Issue by c-minus** [a85/POSTMan-Chrome-Extension#8283]
**Describe the bug**
When duplicating a request which was already been duplicated instead of getting the expected request you get initial duplicated request.

**To Reproduce**
1. Create a Collection
2. Create a Folder
3. Add request => further referenced as R1
4. Add some keys in the Body->x-www-form-urlencoded
5. Duplicate request  => further referenced as R2
6. On the duplicated request modify some of the keys in the Body->x-www-form-urlencoded
7. Duplicate the duplicated request => further referenced as R3

**Expected behavior**
R3 should inherit keys from R2 and not from R1.

**Comment by anibal-acosta** [comment]
Same problem with version 7.21.2. Cannot copy a request tab using the "Duplicate Tab" menu, because any change in the duplicated tab also change the original tab

**Comment by timbochamp** [comment]
@c-minus @anibal-acosta I believe this should now be resolved in our latest Postman version 8 app release, as well as on Postman for Web! I did save both my R1 and R2 requests before duplicating them to see the keys duplicate successfully with R3 inheriting R2's changes.

I'm going to close out this issue, but please feel free to reopen if you're still encountering this issue after updating.
