### ISSUE TITLE
`Learn more` link 404's for IdP configuration in Native app

### ISSUE THREAD

**Issue by SabriH10** [a85/POSTMan-Chrome-Extension#8285]
**Describe the bug**
When clicking on `Learn More` for the option to `Automatically add new users to this authentication method to my team` page 404's.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Team settings
2. Click on Authentication
3. Scroll down to IdP (e.g. Okta ) and click on Edit
4. Click on Learn more for `Automatically add new users to this authentication method to my team`

**Expected behaviour**
Presumably should route to documentation.

**Screenshots**
![Screen_Shot_2020-04-03_at_11_23_39_AM](https://user-images.githubusercontent.com/62078336/78387854-fea15780-75ad-11ea-9d09-20ebbda69765.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.21.2 ( But most likely reproducible on any version )

**Comment by SueSmith** [comment]
Opened a docs pr for this https://github.com/postmanlabs/postman-docs/pull/2308

**Comment by tristandenyer** [comment]
We should make sure a GitHub Issues gets made for the Product team to update this link on their end as well—we shouldn't rely on a redirect.

**Comment by ArjunSingh-PM** [comment]
This issue is resolved.

**Comment by tristandenyer** [comment]
@ArjunSingh-PM Was the link in the app updated?

**Comment by ArjunSingh-PM** [comment]
@tristandenyer, not yet. There is a Jira ticket open for that.
