### ISSUE TITLE
Can't Find Preview Request Button When Doing Basic Authorization

### ISSUE THREAD

**Issue by ethen8181** [a85/POSTMan-Chrome-Extension#8286]
**Describe the bug**
Can't find the preview request button when doing Basic Auth.

**To Reproduce**
N/A

**Expected behavior**
There was a Preview Request button before.

**Screenshots**
<img width="362" alt="Screen Shot 2020-04-03 at 5 45 04 PM" src="https://user-images.githubusercontent.com/12273134/78415170-e3960e00-75d4-11ea-9c49-86618b689905.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.21.1
 - OS: macOS High Sierra 10.13.6

**Additional context**
N/A

**Comment by vvs11** [comment]
@ethen8181 We have removed Preview Request button in the latest release. Now, you'll see a real time preview of your Auth headers in the headers section.
https://learning.postman.com/docs/postman/sending-api-requests/authorization/#specifying-authorization-details
