### ISSUE TITLE
Parse error on multiple "Content-Length" response headers

### ISSUE THREAD

**Issue by literakl** [a85/POSTMan-Chrome-Extension#8287]
**Describe the bug**

When server sends only headers for OPTIONS query Postman will tell that the server did not respond. Originally spotted here: https://github.com/nanoexpress/nanoexpress/issues/87 

**To Reproduce**
1. Checkout this repository https://github.com/literakl/nano-options
2. Start the server with npm run nano
3. Create new Postman OPTIONS query to http://127.0.0.1:3000/v1/users/1e0tcb2kn2
4. Postman says that server did not respond

This is the real response:

c:\bin\curl\bin>curl -X OPTIONS http://127.0.0.1:3000/v1/users/1e0tcb2kn2 -i
HTTP/1.1 200 OK
Vary: Origin
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
Access-Control-Allow-Headers: Content-Type,Authorization
Content-Length: 0
uWebSockets: v0.17
Content-Length: 0

I found this error in postman console:

OPTIONS http://127.0.0.1:3000/v1/users/1e0tcb2kn2
Error: Parse Error
Warning: This request did not get sent completely and might not have all the required system headers

**Expected behavior**
Postman shall tell that the request succeeded, it shall show the time and received headers.

**Screenshots**
![image](https://user-images.githubusercontent.com/6383287/78454304-8a42e300-7697-11ea-8093-3622bed1ec93.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version - how can I find it? There is no about box.
 - OS: W10 64bit

**Additional context**

**Comment by codenirvana** [comment]
@literakl This is happening because of the multiple  "Content-Length" response headers.
```console
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> OPTIONS /v1/users/1e0tcb2kn2 HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 204 No Content
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
< Vary: Access-Control-Request-Headers
< Content-Length: 0
< uWebSockets: v0.17
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0
```

Although both the values are the same, this behavior is inherited from [Node.js](https://github.com/nodejs/node/issues/6517).

**Comment by literakl** [comment]
I know. But I would prefer if postman would display the content and showed
there error eventually.

Dne ne 17. 5. 2020 2:13 uživatel Udit Vasu <notifications@github.com>
napsal:

**Comment by mccannt** [comment]
This issue should now be resolved. We also will have some improvements that we are planning to make to the messaging on error, at a later time.
