### ISSUE TITLE
Web Launchpad

### ISSUE THREAD

**Issue by kinlane** [a85/POSTMan-Chrome-Extension#8291]
**Is your feature request related to a problem? Please describe.**
I am looking for a single URL, not associated with APIs, collections, environments, etc to share with team members.

**Describe the solution you'd like**
Add a default launchpad tab for each of my workspaces in my team web dashboard.

**Describe alternatives you've considered**
Telling my team members to use their client launchpad as discovery, but it doesn't give me a single URL I can use in my documentation and other resources.

**Additional context**
The url would end up just being: https://[team-name].postman.co/workspaces/[workspace_id]/

![web-launchpad-suggestion](https://user-images.githubusercontent.com/56100/78710188-c1003f80-78c9-11ea-9a71-2aba3d8cf939.jpg)

**Comment by prashantagarwal** [comment]
We now have a workspace overview page for all your workspaces.
