### ISSUE TITLE
Unable to sync collentions to application on windows

### ISSUE THREAD

**Issue by tumiiik** [a85/POSTMan-Chrome-Extension#8295]
Hello,

**Describe the bug**
I downloaded the latest version of Postman. After then I logged in to the application but the account is not synchronized (like collections). When I checked collection through a web browser I can see them. The sync button in Postman is red and when I click on it, nothing happens.

**To Reproduce**
1. Download latest version postman ( v7.21.2) on windows 
2. Sign in
3. Click on Sync button
4. The sync button is red and nothing is happening

**Expected behavior**
Sync all collections

**Screenshots**
![image](https://user-images.githubusercontent.com/5836895/78780527-0fcbd900-799f-11ea-86eb-9ee5df3bfa08.png)

**App information (please complete the following information):**
postman ( v7.21.2) on windows 

Thanks

**Comment by ankit-m** [comment]
@tumiiik can you open the devtools console (View -> Developer -> Show Devtools (Shared)) and add screenshots of the console log?

The red sync icon indicates that we were unable to connect to our servers via websocket. This may happen due to firewall or proxy issues.

**Comment by gplusdotgr** [comment]
Many problems on Catalina since a couple of days ago (OS update?). Logging in, syncing, nothing works.  I logged out. Cleared Application Postman folder. Uninstalled. Reinstalled. Logged out and in with different google account. 

**Mac OS: 10.15.4 (19E266)
Postman: Version 7.22.1 (7.22.1)**

Console error:
```
Initializing the global config
vendor-shared.js:239549 Error: Possible EventEmitter memory leak detected. 11 model-events listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (vendor-shared.js:48244)
    at EventEmitter.addListener (vendor-shared.js:48260)
    at EventBus._subscribe (vendor-shared.js:154432)
    at Object.init (vendor-shared.js:191902)
    at err (shared.js:7972)
    at vendor-shared.js:146794
    at vendor-shared.js:90790
    at replenish (vendor-shared.js:128692)
    at iterateeCallback (vendor-shared.js:128681)
    at vendor-shared.js:90811
    at vendor-shared.js:146791
    at __WEBPACK_IMPORTED_MODULE_0__modules_controllers_EditorDataCacheController__.default.clear.then (shared.js:18423)
```

![image](https://user-images.githubusercontent.com/1768834/79309587-d2b19a80-7efa-11ea-9bbf-263e9ee079ed.png)

![image](https://user-images.githubusercontent.com/1768834/79310171-c67a0d00-7efb-11ea-9732-2c76e32c2110.png)

```
500
Something went wrong. Our engineers are working on fixing this as soon as possible.

Request Trace: v=1;t=b41bbea9bf626f02
```

**Comment by JohanO** [comment]
I also got the exact same problem. Here's a screenshot of my developer tools
![image](https://user-images.githubusercontent.com/1762833/79309612-de9d5c80-7efa-11ea-99a9-c0eeceb90afc.png)

**Comment by ankit-m** [comment]
Our servers were facing some issues yesterday which caused syncing to not work for some of our customers. This is resolved now.
