### ISSUE TITLE
App resets zoom levels after updating

### ISSUE THREAD

**Issue by kamalaknn** [a85/POSTMan-Chrome-Extension#8298]
**Describe the bug**
Zoom levels are reset to much lower level on updating to 7.22

**To Reproduce**
1. Zoom in a little on 7.21 or lower
2. Update to 7,22
3. See that zoom level is reset to a much lower level

**Expected behavior**
Zoom level should be preserved

**Screenshots**
Before
<img width="1281" alt="Screenshot 2020-04-08 at 9 56 36 PM" src="https://user-images.githubusercontent.com/8401064/78809081-fef18680-79e3-11ea-9fbf-10375031100e.png">

After

<img width="1281" alt="Screenshot 2020-04-08 at 9 57 07 PM" src="https://user-images.githubusercontent.com/8401064/78809104-06b12b00-79e4-11ea-8958-5c015f05e0e3.png">

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] :Native
 - Postman Version [e.g. 6.0.1]: 7.22
 - OS: [e.g. macOS High Sierra 10.13.2] N/A

**Additional context**

**Comment by harryi3t** [comment]
This is fixed in Postman v7.22.1

**Comment by petru-motrescu** [comment]
Hey 👋

Just downloaded Postman on my new MacBook with Apple silicon and I can reproduce this issue.

Installed from Postman v9.19.3 for macOS (arm64)
Postman version 9.19.0
macOS Monterey version 12.4
