### ISSUE TITLE
Chromium browser support issue for Postman Interceptor Bridge

### ISSUE THREAD

**Issue by s101d1** [a85/POSTMan-Chrome-Extension#8301]
**Describe the bug**
Can't install Interceptor bridge for Chromium browser on linux.

**To Reproduce**
* Install chromium browser. Make sure you don't have google chrome installed.

* Install postman interceptor extension on the chromium.

* Install postman.

* Try to install the interceptor bridge (https://learning.postman.com/docs/postman/sending-api-requests/interceptor/#installing-interceptor) and you will see error message:

> COULDN'T INSTALL
> 
> ERROR CODE: CHROME_NOT_INSTALLED

**Expected behavior**
Interceptor bridge should get installed successfully.

According to the documentation, it seems the postman will try to look for hard-coded chrome settings location at: `~/.config/google-chrome/NativeMessagingHosts`. The chromium setting folder is located at this folder instead: `~/.config/chromium/NativeMessagingHosts`.

I think the solution is to add option for user to change the lookup chrome settings folder.

**App information:**

Linux Distro: Manjaro

Postman version: 7.22.1

Chromium version: 80.0.3987.163 (Official Build) Arch Linux (64-bit)

**Comment by FloLaco** [comment]
This command fix the issue for me : `ln -s ~/.config/chromium/ ~/.config/google-chrome`

**Comment by CryptoMaster-LIVE** [comment]
Similar issue here using Brave Browser which is also based on the Chromium engine.

In this case, I needed to create a symbolic link as @FloLaco has done above:

ln -s ~/.config/BraveSoftware/Brave-Browser/ ~/.config/google-chrome

This is NOT a solution IMHO however, merely a workaround.

**Comment by andriy-f** [comment]
> This command fix the issue for me : `ln -s ~/.config/chromium/ ~/.config/google-chrome`

This is good workaround but doesn't work if you have BOTH Chrome and Chromium installed

**Comment by hauzlife** [comment]
AFTER doing the fix provided by @FloLaco I had to create NativeMessagingHosts folder with:

`cd ~/.config/google-chrome`
 `mkdir NativeMessagingHosts`
 
 ..to get  everything working.

**Comment by ijcnvv** [comment]
there is `~/snap/chromium/common/chromium` in my case

**Comment by crutley** [comment]
I had already been using Interceptor with Chrome, but wanted to switch to Chromium.  I found a file `com.postman.postmanapp.json` in `~/.config/google-chrome`, and simply copied it into `~/.config/chromium`, and that got things working!  So, in one command, `cp ~/.config/google-chrome/com.postman.postmanapp.json ~/.config/chromium/com.postman.postmanapp.json`.

But alternately, I think the `ln` method can be adjust to account for the concerns of @andriy-f regarding having both installed.  It seems that only the one file is needed, so `ln -s ~/.config/chromium/com.postman.postmanapp.json ~/.config/google-chromecom.postman.postmanapp.json` works, I think, and keeps the rest of the configs separate.

**Comment by DannyDainton** [comment]
As there are a number of workarounds mentioned in the thread, I'm going to close this issue for now. We can reopen this if other people are still facing problems after trying these different methods.
