### ISSUE TITLE
[Feature request] Add a "Pull changes from forked collection" in the app to sync a fork with the original collection

### ISSUE THREAD

**Issue by adussaut** [a85/POSTMan-Chrome-Extension#8303]
Hi, here's a small request to enhance the app user experience.

**Is your feature request related to a problem? Please describe.**
There is no intuitive way to pull changes from the forked collection to your fork as of today.
You have to go through the "Merge changes" button on the app to see if the button "Pull changes" is available on the website, which is a waste of time.

**Describe the solution you'd like**
Add a "Pull changes"/"Sync with master"/"Update fork"  button in the app to automatically update a fork if no unmerged changes have been made on the fork.

**Describe alternatives you've considered**
We can do this with the "Merge changes" button but it's not intuitive and time consuming.

**Comment by ankit-m** [comment]
This is released in Postman v8.

**Comment by ivorynoise** [comment]
To pull changes, click on the collection. In the menu button on right, click `pull changes`. 

<img width="1726" alt="postman-pull-changes" src="https://user-images.githubusercontent.com/11216794/165274454-d61aee72-eb46-4b18-8468-6b107470770b.png">
