### ISSUE TITLE
Schema tv4 validation stopped working since the last Postman application update

### ISSUE THREAD

**Issue by jperucello** [a85/POSTMan-Chrome-Extension#8304]
**Describe the bug**
Since last Postman application update tv4 schema validation is throwing an error.

**To Reproduce**
Create test for Json schema 
`pm.test('Schema is valid', () => {
    pm.expect(tv4.validate(4, {"type": "number"})).to.be.true;
});`

Response: 
TypeError: r.definedKeywords[a].slice is not a function

**Expected behavior**
Validator to return true/false and show on test results

**Screenshots**
![image](https://user-images.githubusercontent.com/35104798/78894671-c72f2100-7a6d-11ea-8660-0e99d75b0c7c.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version v7.22.0
 - OS: Windows 10

**Additional context**
Should I be using another validation/function?

**Comment by DannyDainton** [comment]
@jperucello If you use something like this in your test, it will use AJV for the schema validations.

```
pm.test("Check Schema", () => {
    pm.response.to.have.jsonSchema(schema)
}) 
```

**Comment by vvs11** [comment]
@jperucello closing this issue for now, if you have any other queries, please reach out to our community: https://community.getpostman.com/
