### ISSUE TITLE
Request Descriptions not added

### ISSUE THREAD

**Issue by zkcloud** [a85/POSTMan-Chrome-Extension#8307]
**Describe the bug**
When add request in left menu，write 'Request description(Optional)', then save , but 'Request description' didn't  display in right, lost.

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 7.22.1
 - OS: win10

**Additional context**

**Comment by vvs11** [comment]
@zkcloud Could you give us steps to reproduce this issue. Screenshots or videos for this would be really helpful too

**Comment by Raja-Simha** [comment]
Closing this as we do not have enough information to reproduce this and investigate further.
