### ISSUE TITLE
POST requests don't send any data

### ISSUE THREAD

**Issue by raj-kesavan** [a85/POSTMan-Chrome-Extension#831]
I can't send any data with POST.
I'm on Normal mode, raw, JSON, with the data {"hello": "world"}. My server is receiving empty packets. 
I also tried from a different REST client, Advanced Rest Client (Chrome extension) - worked fine. Any ideas? This was working fine a couple days ago.

**Comment by johnkchiu** [comment]
bump bump bump.  This is happening to me also, and it's both the legacy (in-chrome app) or the packaged app.  Did something change in Chrome that's blocking this?

**Comment by abhijitkane** [comment]
@johnkchiu No, nothing related to this has changed. And you're facing the problem in the legacy app as well, which doesn't even have Interceptor support.

Do see any errors in the console?

**Comment by johnkchiu** [comment]
Looks like it's just user error.  I was posting to the wrong endpoint, so I thought the payload was empty.  Thanks @abhijitkane .

**Comment by arvinddhasmana** [comment]
I faced the same issue in PostMan and Advance REST Client both.
I am passing my data in Body as <b>x-www-form-urlencoded</b>
I fixed it by using <b>Content-Type</b> as <b>application/x-www-form-urlencoded</b> in request header.
My response content type is still <b>Content-Type → application/json; charset=utf-8</b>

**Comment by svgaman** [comment]
Like arvinddhasmana, i must pass x-www-form-urlencoded while my response is application/json; charset=utf-8

**Comment by redbeandev** [comment]
Filename is shown as empty when generate code for phpcurl for me even after adding files

**Comment by RaziMailk** [comment]
**expressjs server don't send data back to Postman**
when i make post request from postman, the request data was shown server but server response i.e status code and json object  was not send to poastman, poastman was loading...

**Comment by zlanich** [comment]
@abhijitkane Said not to explicitly set the Content-Type header, so I deleted mine (even though it looked like Postman was changing it fine), then reset my raw:application/json setting, allowing Postman to set a fresh Content-Type header, and it worked for the first time. Try this.

**Comment by nunziofiore** [comment]
+1 here ... 
Versione 6.3.0 (6.3.0) native app

**Comment by kamleshwebtech** [comment]
How can we post form fields data eg. name, email along with a file by PUT method? I am getting null value after submitting the form in Postman. How can i check my api, please suggest me. Thanks.
