### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by SiDDevNet** [a85/POSTMan-Chrome-Extension#8310]
**Describe the bug**
Can not proceed with setup wizard

**To Reproduce**
1. Go to ''Download Directory"
2. Click on 'Postman-win32-7.22.1-Setup.exe'
3. Scroll down to 'Wait for the Login Authentication Page'

**Expected behavior**
Screen should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/63461095/78998171-a8ac5100-7b65-11ea-84d7-a638af6b5ac8.png)

**App information (please complete the following information):**
Installer
latest downloaded from website
Windows 7 Service Pack 1

**Additional context**
Please create another installer
![image](https://user-images.githubusercontent.com/63461095/78998802-fe352d80-7b66-11ea-80eb-d37a27ec5943.png)

**Comment by SiDDevNet** [comment]
![image](https://user-images.githubusercontent.com/63461095/78999338-080b6080-7b68-11ea-8b74-f01784e3713e.png)
Same Issue Occurs with Canary Setup of Postman

**Comment by harryi3t** [comment]
@SiDDevNet We had seen the users facing a similar issue where a combination of OS version + GPU hardware + driver versions did not work well with Electron/Chrome (which is internally used by Postman).

To confirm whether you are affected by the same issue, could you try opening the app with an extra argument `--disable-gpu`?
```
# cd in the directory where Postman.exe is present (`%appdata%/Postman`)
Postman.exe --disable-gpu
```

If Postman launches properly after this workaround, you can make it permanent by adding an environment variable `POSTMAN_DISABLE_GPU=true`. For more details see https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by numaanashraf** [comment]
Issue resolved via email. Cause was GPU related.
