### ISSUE TITLE
Bootcamp > "Carry data between requests" crashes halfway through

### ISSUE THREAD

**Issue by arpieb** [a85/POSTMan-Chrome-Extension#8311]
**Describe the bug**
While following the "Bootcamp > Carry data between requests" guided tutorial, the tutorial gets to the view variables step and clicking next bails on the guide, and clicking continue at the bottom of the screen starts over several steps back.

**To Reproduce**
1. Go to Bootcamp
2. Click on 'Carry data between requests'
3. Follow the guide up to executing the request, then when it prompts to 'Go to quick look' you see the variables, and the next  guide pops up with "New variable is created!" and a prompt to click Next to continue
4. Click Next, and the guide disappears.  Prompt at bottom of screen has "Continue learning" link, clicking this takes you back several steps in the tutorial.

**Expected behavior**
I would expect the tutorial to continue since the last guide box said I was only 54% completed.

**Screenshots**
![image](https://user-images.githubusercontent.com/449910/79002145-dcfc1f00-7b1d-11ea-9969-92b504343fec.png)

**App information (please complete the following information):**
 - Native App
 - Postman v7.22.1
 - Windows 10 Pro, v1809, build 17763.1098

**Additional context**
Going in order in the Bootcamp, so far the others have had no issues...

**Comment by prashantagarwal** [comment]
@arpieb Thanks for reporting this, I was able to reproduce this issue. I'll update you once we have a fix ready for this.

**Comment by prashantagarwal** [comment]
@arpieb We have fixed this as part of Postman **v7.23.0**.
