### ISSUE TITLE
Post man server sync and resolve conflict too annoying

### ISSUE THREAD

**Issue by shirshak55** [a85/POSTMan-Chrome-Extension#8312]
Work on some thing and it forever annoys like server is not is sync and always wants me to resolve conflict. And this time i am even unable to resolve. And I am only working alone so there shouldn't be any chance of conflict. 

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/8097377/79012021-0dc36f00-7b85-11ea-937f-9f2ee92c8db7.png">

**Comment by ankit-m** [comment]
@shirshak55 we have resolved this in our latest update `v7.22.1`. Could you confirm that you are on this version?

**Comment by shirshak55** [comment]
i am on latest version.

**Comment by preethammavin** [comment]
@shirshak55 do you still see the issue?

**Comment by shirshak55** [comment]
@preethammavin i reinstalled so now there is no way to reproduce right? As i cannot reproduce i think i should close this issue.
