### ISSUE TITLE
Schema validation not providing details of reported issue

### ISSUE THREAD

**Issue by ash-at-github** [a85/POSTMan-Chrome-Extension#8313]
Came across exact same issue as defined here: https://community.postman.com/t/schema-validation-not-providing-details-of-reported-issue/11063
Could not find resolution anywhere. Updated the postman version to latest 7.22 but issue still persists

**Comment by vvs11** [comment]
Thanks @ash-at-github for reporting. We will take a look and get this resolved

**Comment by arlemi** [comment]
This was fixed in the latest version of the app (7.27), please update and let us know if this is still not working!
