### ISSUE TITLE
Can't see to send POST request in version 7.22.1

### ISSUE THREAD

**Issue by vbakshi123-star** [a85/POSTMan-Chrome-Extension#8316]
Can't see to send POST request in version 7.22.1

Postman app got automatically updated to version  7.22.1 where all collections open up in browser, but no option to send post requests. I can see all my collections in the browser, but don't see where to send post requests. It was pretty darn easy on the app.

**Comment by weeix** [comment]
If POST doesn't reside within the method list, you might try typing it directly then choose `Save method 'POST'`.

![image](https://user-images.githubusercontent.com/6592791/79059532-52dec280-7ca5-11ea-8517-31ce90590119.png)

**Comment by DannyDainton** [comment]
@vbakshi123-star 

In the bottom right corner of the app, can you check if it's in `Build` mode?

It sounds like you have it in `Browse` mode.

**Comment by vbakshi123-star** [comment]
> @vbakshi123-star
> 
> In the bottom right corner of the app, can you check if it's in `Build` mode?
> 
> It sounds like you have it in `Browse` mode.

I figured it out yesterday and was trying to close off the issue, but lost my internet connection. Sorry guys, too silly of me. Thank you for your help though.
