### ISSUE TITLE
API tab goes into `Loading..` state when deleted

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#8321]
**Describe the bug**
API tab goes into `Loading..` state when API is deleted.

**To Reproduce**
1. Create an API
2. Open the API in a new tab by double clicking the API in the sidebar
3. Delete the API while the tab is open
4. See tab title change to `Loading ...`

**Expected behavior**
It should go into a deleted state.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.22.1
 - OS: macOS Catalina

**Comment by shivangibajpai12** [comment]
@ankit-m Thanks for reporting the issue. This has been fixed in app v7.24.
