### ISSUE TITLE
Socket hangup while sending request (in app version 7.20.1 to 7.22.1) 

### ISSUE THREAD

**Issue by vladyslovestepanov** [a85/POSTMan-Chrome-Extension#8324]
**Describe the bug**
I get this error during a month and a half, for sure should report earlier

**To Reproduce**
1. Use Postman from 7.20.1 to 7.22.1
2. Attempt an API call

**Expected behavior**
For Postman to work as it works with other hosts which I send a request to

**Screenshots**
![image](https://user-images.githubusercontent.com/52454096/79216529-ff5fa680-7e55-11ea-8117-57301086ef7e.png)
--------
![image](https://user-images.githubusercontent.com/52454096/79216864-90cf1880-7e56-11ea-9525-d3da81f08b6f.png)

**App information (please complete the following information):**
Postman for Windows
Version 7.22.1
win32 10.0.18362 / x64

**Comment by vvs11** [comment]
similar to #8517 
@vladyslovestepanov could you follow the steps mentioned in the above issue and see if it is resolved?

**Comment by timbochamp** [comment]
I'm closing this out due to inactivity, but if this is still an issue for you in the latest v9.16.1, we can look to reopen it again!
