### ISSUE TITLE
Schema changelog resets for every new API version

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#8325]
**Describe the bug**
When you create a new API version, the changelog just shows one changelog with the entire schema. This makes it very difficult to use. Ex. What changed from v1.1.0 to v1.2.0 in an API.

**To Reproduce**
1. Create API
2. Add schema
3. Make changes and save.
4. Create new version.
5. Open changelog.
6. Observe only one changelog entry.

**Expected behavior**
Show complete changelog across versions (like collection).

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version:  7.22.1
 - OS: macOS Catalina

**Comment by vvs11** [comment]
@ankit-m this is the behavior we designed it for because the restore and add version tag flows were becoming slightly cumbersome. Will mark it as a feature request to track .

**Comment by abhijitkane** [comment]
With Postman v9, one version of the API can have the API definition evolve across multiple releases. A version is intended to be used with a parallel API development track.
