### ISSUE TITLE
Dark splash screen if using dark mode

### ISSUE THREAD

**Issue by djnesmith** [a85/POSTMan-Chrome-Extension#8326]
When you start up Postman it has a very bright splash screen.  If you are using dark mode could you make it so this splash screen is dark?  Thanks!

**Comment by bean5** [comment]
@postman-support this is technically a bug (albeit a small one).

Version 8 defaults to flash of white. Version 7 was defaulting to a "tan/beige" color until it loads configurations. So technically the app regressed.

**Comment by jviotti** [comment]
Merging this ticket with https://github.com/postmanlabs/postman-app-support/issues/9794
