### ISSUE TITLE
Published Documentation Formatting Issues

### ISSUE THREAD

**Issue by carrrson** [a85/POSTMan-Chrome-Extension#8327]
**Describe the bug**
When publishing documentation, the collection information looks fine pre-publishing in the web view, but once I click publish, the publish preview and the preview documentation show very weird formatting issues.  

**To Reproduce**
1. Go to collection > publish collection
2. Click on either "preview documentation", or go ahead and publish.
3. Notice that the collection data is cut off by the left sidebar, and that the environment and layout chooser dropdowns are out of place and behaving strangely (clicking on choose environment on the left side of the screen shows the dropdown options on the right side) 

**Expected behavior**
Expected normal postman documentation formatting. I have not noticed this issue before today. 

**Screenshots**
This is in chrome:
<img width="2549" alt="Chrome preview" src="https://user-images.githubusercontent.com/20145532/79241706-67f05880-7e41-11ea-9b97-4de04ad00927.png">

**App information (please complete the following information):**
 - Chrome issue - Version 80.0.3987.149 (Official Build) (64-bit) - also an issue in safari
 - Postman Version v7.21.1
 - OS: macOS Catalina 10.15.3

**Comment by mrojash213** [comment]
Hello Postman team, 

I would like to provide visibility that our organization is having the same problem.

**Comment by Raja-Simha** [comment]
@carrrson and @mrojash213 can you guys please try a hard refresh and let us know if the issue still persists. We are looking into this.

**Comment by xk0der** [comment]
@mrojash213 @carrrson  Thank you again for reporting this! 

Our Engineering team identified an issue where stale assets were being served, breaking the page.
The cache issue has now been fixed and the documentation should start to show properly!

Do let us know if you continue to face this issue!
