### ISSUE TITLE
UI hang with 5 postman windows open

### ISSUE THREAD

**Issue by David-A-Anderson** [a85/POSTMan-Chrome-Extension#8328]
**Describe the bug**
I find that if I have 5 or more Postman windows open with different environments one of the postman windows will hang after using for less than an hour of switching between the windows doing different tasks, also switching betwen browsers, Slack, Postico, etc.. More often than not it is the second window that I opened that hangs. 

**Expected behavior**
Postman should not hang

**App information (please complete the following information):**
 - App Type - just hitting various rest endpoints
 - Version 7.22.1 (7.22.1)
 - OS: macOS 10.15.3

If I have three or four Postman windows open at a time I can work unmolested for many days.

**Comment by numaanashraf** [comment]
@David-A-Anderson Could you share a screen recording to help us understand this issue better and replicate this at our end?

**Comment by kamalaknn** [comment]
@David-A-Anderson I could not recreate the issues you have reported with multiple Postman windows on the latest version. I am closing this issue since we do not have enough information to replicate this from our side.
