### ISSUE TITLE
API tab reloads on reconnect

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#8330]
**Describe the bug**
When app goes offline and then online, an API tab which is open goes into a full loading state. This sometimes takes too long to load.

**To Reproduce**
1. Create an API
2. Add schema
3. Go offline and come back online
4. Observe full-tab reload

**Expected behavior**
Block online actions, not the whole tab.
**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.22.1
 - OS: macOS Cataline

**Comment by sankalp0o** [comment]
Thanks for letting us know @ankit-m! We'll relook at the experience here as well as the loading time.

**Comment by shivangibajpai12** [comment]
This has been fixed in app 7.26.
