### ISSUE TITLE
[Postman offline]

### ISSUE THREAD

**Issue by letanloc1998** [a85/POSTMan-Chrome-Extension#8331]
**Describe the bug**
You need to have an active internet connection to be able to switch to or create a workspace.

**To Reproduce**
Can't sync Postman, offline. But I can access internet

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26348718/79308956-aeb67f00-7f23-11ea-8ad4-a541402f0a2b.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.22.1
 - OS: Windows 10 1909

**Additional context**

**Comment by OrdinaPoolAuto** [comment]
I encounter the same problem. Not always, but many times: "No internet connection".

**Comment by letanloc1998** [comment]
> I encounter the same problem. No always, but many times: "No internet connection".

This is the first time I got this problem
I have restart, change network, but it still not working ~~

**Comment by letanloc1998** [comment]
Ok, It's working.
Thank you very much
