### ISSUE TITLE
v7.22.1: no response after good response. Toggles.

### ISSUE THREAD

**Issue by OrdinaPoolAuto** [a85/POSTMan-Chrome-Extension#8332]
Postman version v7.22.1.

Today I upgraded to version v7.22.1.

Now i encounter the problem that when I do a "Send", I get the Response back. When I do a Send again, i receive a "Could not get any response" error message.
When I send again, i get a good response. Send again => error.

This toggles all the time. Even for all requests I have.
So:
- Good Response
- Error
- Good Response
- Error
- ....

Looks like a buffer is not cleared after getting the response.

Regards,
Martin

**Comment by vvs11** [comment]
@OrdinaPoolAuto could you check the error message you see in the console? You an open it from bottom left.
![image](https://user-images.githubusercontent.com/4140290/79366920-9ae23b80-7f6a-11ea-9ce6-c05505a9ee4f.png)

**Comment by OrdinaPoolAuto** [comment]
See the toggling here.
![image](https://user-images.githubusercontent.com/62640748/79421358-ee7c7580-7fba-11ea-87bc-730713584b63.png)
Please see the error message.
![image](https://user-images.githubusercontent.com/62640748/79421409-06ec9000-7fbb-11ea-9a11-126c8522290e.png)

This is a continuous process. This happens since the new version. Before the new version, all worked fine.

**Comment by DannyDainton** [comment]
Hey @OrdinaPoolAuto 

I'm closing this out due to inactivity, if you're still facing the issue in the latest version, we can look to reopen this again and investigate further.
