### ISSUE TITLE
X-mock-match-request-body not matching examples

### ISSUE THREAD

**Issue by mustela** [a85/POSTMan-Chrome-Extension#8335]
Hey guys,
Im having a hard time trying to make graphql requests match the examples and I can't understand what is really failing. 

Some context: https://community.postman.com/t/x-mock-match-request-body-with-graphql/11905/4

And now Im where *I believe* the bodies are exactly the same but still not matching: 
This is the example:
![Screenshot 2020-04-15 at 11 00 16](https://user-images.githubusercontent.com/325222/79320088-7efa7d80-7f09-11ea-910e-7fec580a11e8.png)

And the query

```
curl --location --request POST 'xxxxxx/v1/query' \
--header 'x-mock-match-request-body: true' \
--data-raw '{"operationName":"login","variables":{"email":"test@gmail.com","password":"12345678"},"query":"mutation login($email: String!, $password: String!) {\n  login(login: $email, password: $password) {\n    token\n    id\n    first_name\n    last_name\n    email\n  }\n}"}'
```
<img width="956" alt="Screenshot 2020-04-15 at 10 52 16" src="https://user-images.githubusercontent.com/325222/79320319-f16b5d80-7f09-11ea-93f7-0638d6402a53.png">

I [opened also an issue](https://github.com/postmanlabs/postman-app-support/issues/8334) to change how you guys are displaying the payload since it's hard to test/check things using the UI.

Any clue? 

Thanks a lot!

**Comment by mustela** [comment]
FWIW adding `--header 'Content-Type: application/json' \ ` isn't working neither.

**Comment by mustela** [comment]
Guys any update on this one?

**Comment by pranayat** [comment]
If you are using the `x-mock-match-request-body` header, then make sure that the `Content-Type` header in your request to the mock server is the same as the `Content-Type` header in the example request (not response) you want to match.

Try the following steps:
1. Include Content-Type application/json in the request you are sending to the mock server
2. Include Content-Type application/json in the example request which you want to match (no need to set in the example response). Make sure no other Content-Type is set in the example request you want to match.

I tried reproducing this using the curl you shared (plus Content-Type header) and was able to get a response successfully.
```curl --location --request POST 'https://c7f6eb4a-7eba-4484-badc-a058a8f2f806.mock.pstmn.io/v1/query' \
--header 'x-mock-match-request-body: true' \
--header 'Content-Type: application/json' \
--data-raw '{"operationName":"login","variables":{"email":"test@gmail.com","password":"12345678"},"query":"mutation login($email: String!, $password: String!) {\n  login(login: $email, password: $password) {\n    token\n    id\n    first_name\n    last_name\n    email\n  }\n}"}'
```

Here's the collection I created the mock on to recreate this:
```
{
	"info": {
		"_postman_id": "1ee7308b-d09a-471f-9e97-f6d3c1686022",
		"name": "GraphQL Mock",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "r1",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "x-mock-match-request-body",
						"value": "true",
						"type": "text"
					},
					{
						"key": "Content-Type",
						"value": "application/json",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"operationName\": \"login\",\n\t\"variables\": {\n\t\t\"email\": \"test@gmail.com\",\n\t\t\"password\": \"12345678\"\n\t},\n\t\"query\":\"mutation login($email: String!, $password: String!) {\\n  login(login: $email, password: $password) {\\n    token\\n    id\\n    first_name\\n    last_name\\n    email\\n  }\\n}\"\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "replace_with_mock_url/v1/query",
					"protocol": "https",
					"host": [
						"replace_with_mock_url",
						"mock",
						"pstmn",
						"io"
					],
					"path": [
						"v1",
						"query"
					]
				}
			},
			"response": [
				{
					"name": "r1",
					"originalRequest": {
						"method": "POST",
						"header": [
							{
								"key": "Content-Type",
								"name": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\n\t\"operationName\": \"login\",\n\t\"variables\": {\n\t\t\"email\": \"test@gmail.com\",\n\t\t\"password\": \"12345678\"\n\t},\n\t\"query\":\"mutation login($email: String!, $password: String!) {\\n  login(login: $email, password: $password) {\\n    token\\n    id\\n    first_name\\n    last_name\\n    email\\n  }\\n}\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "nada/v1/query",
							"host": [
								"nada"
							],
							"path": [
								"v1",
								"query"
							]
						}
					},
					"status": "OK",
					"code": 200,
					"_postman_previewlanguage": "json",
					"header": null,
					"cookie": [],
					"body": "{\n\t\"data\": \"some response\"\n}"
				}
			]
		}
	],
	"protocolProfileBehavior": {}
}
```

You can import this and see if there's anything you are doing differently.

If this does not solve your issue, please reach out to help@getpostman.com
We have a very active community that can help you too. You can post your questions on https://community.postman.com/

**Comment by mustela** [comment]
Thanks @pranaya94 for the answer, and yes, it is working only when I use `Content-Type: application/json`
But it is not if the content type header has something else (I do have the same header in the request example). This doesn't work `'Content-Type: application/json; charset=utf-8'`, it doesn't match.

**Comment by vvs11** [comment]
@mustela Thanks for the feedback. This looks like a bug in our system. Will keep a track of it and post updates soon

**Comment by mustela** [comment]
Hello there! Any update on this one ? Thanks a lot!

**Comment by pranayat** [comment]
@mustela We are working on the fix and shall update you when done.

**Comment by pranayat** [comment]
> Thanks @pranaya94 for the answer, and yes, it is working only when I use `Content-Type: application/json`
> But it is not if the content type header has something else (I do have the same header in the request example). This doesn't work `'Content-Type: application/json; charset=utf-8'`, it doesn't match.

@mustela You should now be able to match bodies for header `'Content-Type: application/json; charset=utf-8'`.

**Comment by vvs11** [comment]
@mustela This is fixed now. Please feel free to re-open if you're still facing the issue

**Comment by vickrammark** [comment]
> If you are using the `x-mock-match-request-body` header, then make sure that the `Content-Type` header in your request to the mock server is the same as the `Content-Type` header in the example request (not response) you want to match.
> 
> Try the following steps:
> 
> 1. Include Content-Type application/json in the request you are sending to the mock server
> 2. Include Content-Type application/json in the example request which you want to match (no need to set in the example response). Make sure no other Content-Type is set in the example request you want to match.
> 
> I tried reproducing this using the curl you shared (plus Content-Type header) and was able to get a response successfully.
> 
> ```
> --header 'x-mock-match-request-body: true' \
> --header 'Content-Type: application/json' \
> --data-raw '{"operationName":"login","variables":{"email":"test@gmail.com","password":"12345678"},"query":"mutation login($email: String!, $password: String!) {\n  login(login: $email, password: $password) {\n    token\n    id\n    first_name\n    last_name\n    email\n  }\n}"}'
> ```
> 
> Here's the collection I created the mock on to recreate this:
> 
> ```
> {
> 	"info": {
> 		"_postman_id": "1ee7308b-d09a-471f-9e97-f6d3c1686022",
> 		"name": "GraphQL Mock",
> 		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
> 	},
> 	"item": [
> 		{
> 			"name": "r1",
> 			"request": {
> 				"method": "POST",
> 				"header": [
> 					{
> 						"key": "x-mock-match-request-body",
> 						"value": "true",
> 						"type": "text"
> 					},
> 					{
> 						"key": "Content-Type",
> 						"value": "application/json",
> 						"type": "text"
> 					}
> 				],
> 				"body": {
> 					"mode": "raw",
> 					"raw": "{\n\t\"operationName\": \"login\",\n\t\"variables\": {\n\t\t\"email\": \"test@gmail.com\",\n\t\t\"password\": \"12345678\"\n\t},\n\t\"query\":\"mutation login($email: String!, $password: String!) {\\n  login(login: $email, password: $password) {\\n    token\\n    id\\n    first_name\\n    last_name\\n    email\\n  }\\n}\"\n}",
> 					"options": {
> 						"raw": {
> 							"language": "json"
> 						}
> 					}
> 				},
> 				"url": {
> 					"raw": "replace_with_mock_url/v1/query",
> 					"protocol": "https",
> 					"host": [
> 						"replace_with_mock_url",
> 						"mock",
> 						"pstmn",
> 						"io"
> 					],
> 					"path": [
> 						"v1",
> 						"query"
> 					]
> 				}
> 			},
> 			"response": [
> 				{
> 					"name": "r1",
> 					"originalRequest": {
> 						"method": "POST",
> 						"header": [
> 							{
> 								"key": "Content-Type",
> 								"name": "Content-Type",
> 								"value": "application/json",
> 								"type": "text"
> 							}
> 						],
> 						"body": {
> 							"mode": "raw",
> 							"raw": "{\n\t\"operationName\": \"login\",\n\t\"variables\": {\n\t\t\"email\": \"test@gmail.com\",\n\t\t\"password\": \"12345678\"\n\t},\n\t\"query\":\"mutation login($email: String!, $password: String!) {\\n  login(login: $email, password: $password) {\\n    token\\n    id\\n    first_name\\n    last_name\\n    email\\n  }\\n}\"\n}",
> 							"options": {
> 								"raw": {
> 									"language": "json"
> 								}
> 							}
> 						},
> 						"url": {
> 							"raw": "nada/v1/query",
> 							"host": [
> 								"nada"
> 							],
> 							"path": [
> 								"v1",
> 								"query"
> 							]
> 						}
> 					},
> 					"status": "OK",
> 					"code": 200,
> 					"_postman_previewlanguage": "json",
> 					"header": null,
> 					"cookie": [],
> 					"body": "{\n\t\"data\": \"some response\"\n}"
> 				}
> 			]
> 		}
> 	],
> 	"protocolProfileBehavior": {}
> }
> ```
> 
> You can import this and see if there's anything you are doing differently.
> 
> If this does not solve your issue, please reach out to [help@getpostman.com](mailto:help@getpostman.com) We have a very active community that can help you too. You can post your questions on https://community.postman.com/

Nice
