### ISSUE TITLE
Not able to login to Postman through google

### ISSUE THREAD

**Issue by Pushpa029** [a85/POSTMan-Chrome-Extension#8336]
**Describe the bug**
Not able to login to Postman. Is it down?

**To Reproduce**
1. Launch the app
2. Click on sign in with google
3. Get error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42090484/79327417-b7ec1f80-7f14-11ea-9677-455a07322e37.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.22.1
 - OS: Windows 10

**Additional context**

**Comment by peconia** [comment]
I have the same issue. Cannot login using google id on the Windows app or in any browser.

**Comment by cyrielle-h** [comment]
Thank you for flagging this issue. We are currently experiencing some downtime and our Engineering team is working as quickly as possible to get everything back up and running. 

To keep track of this issue, feel free to subscribe to this incident on our [Status Page](https://status.postman.com/).

**Comment by arlemi** [comment]
@Pushpa029 @peconia That incident is now resolved! Sorry for the trouble and let us know if you're still experiencing issues. :)
