### ISSUE TITLE
MacOS app is not syncing

### ISSUE THREAD

**Issue by janswist** [a85/POSTMan-Chrome-Extension#8337]
I had an issue with syncing the app after update to the latest version. I uninstalled it completely, signed-in via Google and error is still there. How is that possible? I see other people also having trouble to sync their app and if not exported data all would be lost.

**Comment by arlemi** [comment]
There is an ongoing issue with our service, we're currently working on a fix, sorry about that! 

You can follow updates on our status page as well as subscribe to the incident to be alerted as soon as the status is updated. ➡️ https://status.postman.com/

**Comment by arlemi** [comment]
@janswist That incident is now resolved! Sorry for the trouble and let us know if you're still experiencing issues.
