### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by zarpio** [a85/POSTMan-Chrome-Extension#8338]
Everything was working fine last night, I didn't even update or change a setting... postman unable to sync anything.

- macOS Mojave
- Postman 7.22.1

**Tried**
- Signout and Signin
- Downloaded again and installed

![image](https://user-images.githubusercontent.com/112050/79338201-504bc980-7f40-11ea-8428-03b9239816b6.png)

**Comment by arlemi** [comment]
There is an ongoing issue with our service, we're currently working on a fix, sorry about that! 

You can follow updates on our status page as well as subscribe to the incident to be alerted as soon as the status is updated. ➡️ https://status.postman.com/

**Comment by arlemi** [comment]
@zarpio That incident is now resolved! Sorry for the trouble and let us know if you're still experiencing issues.
