### ISSUE TITLE
Collection Runner - wrong progress indication

### ISSUE THREAD

**Issue by MarcBKirsch** [a85/POSTMan-Chrome-Extension#8342]
**Describe the bug**
The progress indication sometimes shows utterly wrong progress information. After 50+ of 900 iterations, the indicator was changing from 0 to 1 (it not frozen!)
<img width="955" alt="PM wrong progress indication" src="https://user-images.githubusercontent.com/15914824/79443537-3d85d300-7fda-11ea-917e-342f0d80c72d.PNG">

**To Reproduce**
1. Start many collections runs with a high number of iterations
2. Monitor that behavior
3. Please note it's an intermittent issue. It does not appear all the time.

**Expected behavior**
Usually the progress bar is correct.

**Screenshots**
See attached.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.22.1
 - OS: Windows 10 Enterprise

**Additional context**
It's an intermittent issue

**Comment by DannyDainton** [comment]
Hey @MarcBKirsch 

I'm unable to reproduce this issue in the latest version of the platform. If this is still an issue that you're facing and you can provide some steps to consistently recreate the problem, we can look at opening the issue again.
