### ISSUE TITLE
Set Environment variable Access Token 

### ISSUE THREAD

**Issue by kevyaugusto** [a85/POSTMan-Chrome-Extension#8344]
After generating the Access token, tab Authorization, type=O Auth 2.0, I set my environment variable with the token generated. 
Steps
1- generate the token
2- select the token generated
3- right button click > set variable menu > choose the variable you want to set.
4- go to the variable and see the token value, it ALWAYS contains a NEWLINE char (\n) at the end of the token, which I have to clean it every time I generate and set the variable.

---
Outcome
When using the menu Set variable after generating the token, is it possible to remove this NEWLINE? 

![image](https://user-images.githubusercontent.com/1820655/79525757-fdd8ed00-80a6-11ea-9494-08dd1f6129d9.png)

![image](https://user-images.githubusercontent.com/1820655/79525858-48f30000-80a7-11ea-911b-28a1f5a1b6c8.png)

**Comment by DannyDainton** [comment]
Hey @kevyaugusto 

Is this something that you're still having an issue with?

**Comment by DannyDainton** [comment]
Hey @kevyaugusto 

I'm going to close this issue out for now, if this is still something that you're having a problem with we can open it up again.
