### ISSUE TITLE
pm.globals.set will not set a function

### ISSUE THREAD

**Issue by daswass** [a85/POSTMan-Chrome-Extension#8346]
**Describe the bug**
I have a set of requests that are run in order by a Monitor for end-to-end testing of my application. I am changing the deprecated testing methods to the new ones but pm.globals.set does not allow me to set a function whereas postman.setGlobalVariable does. I am doing this to simplify cleanup in the last request. The first request creates a cleanup function, and the last request runs it in an eval() in the test.

**To Reproduce**

1. In a request have the following in a test
```
// postman.setGlobalVariable does work here
pm.globals.set("clearTestVariables", () => {
    pm.environment.unset("integration-token");
    pm.environment.unset("yyyymmdd");
});
```

2. In a second request have this in a test:
`eval(globals.clearTestVariables)();`

**Expected behavior**
Parity between pm.globals.set and postman.setGlobalVariable or another way to accomplish the same goal.

**Comment by DannyDainton** [comment]
Hey @daswass,

Is this still an issue for you?

I've used something like this in the past to clear out the variables, based on a specific naming convention that I had.

```javascript
function cleanup() {
    const clean = _.keys(pm.environment.toObject())
    _.each(clean, (arrItem) => {
        if (arrItem.startsWith("some_prefix")) {
            pm.environment.unset(arrItem)
        }
    })
}
cleanup()
```
