### ISSUE TITLE
Renaming a workspace removed some collections in the workspace

### ISSUE THREAD

**Issue by navirineni** [a85/POSTMan-Chrome-Extension#8347]
**Describe the bug**
Renaming a workspace removed some collections in the workspace. I have lost all the collections and the data.

**To Reproduce**
1. Go to Workspace drop down
2. On your Workspace name Click on ... and select Rename
3. Change the name of the workspace 
4. All the collections in the workspace are gone. I don't find them in my account too on the web.

**Expected behavior**
Workspace has to be renamed with all the data persisting in it.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [Version 7.7.3 (7.7.3)]
 - OS: [macOS Mojave 10.14.6]

**Additional context**

**Comment by navirineni** [comment]
<img width="1581" alt="Screen Shot 2020-04-17 at 11 11 12 AM" src="https://user-images.githubusercontent.com/50954773/79584364-4b039180-809c-11ea-8286-80ae7b9dd049.png">

**Comment by mccannt** [comment]
@avirinenin Apologies for not following up sooner. Can you confirm if this is still an issue for you? 

I have tried this locally and I am not seeing the issue currently, we have made improvements in this area recently that may have resolved this for you.

**Comment by navirineni** [comment]
I will check and get back to you. Thanks.

**Comment by mccannt** [comment]
@avirinenin We will close this issue for now. 
If this is still an issue, please feel free to reopen.

**Comment by navirineni** [comment]
Sounds good. I got  to test that out and I don't want to risk my real data on that. So I need some time
