### ISSUE TITLE
Error merging but not useful message is shared to the user

### ISSUE THREAD

**Issue by fenoloco** [a85/POSTMan-Chrome-Extension#8352]
**Describe the bug**
We are a team of 13 persons and multiples times we have issues merging collection forks and the only message that appears on the screen is an error saying collection could not be merged.

**To Reproduce**
I don't have a way to make this happens.. but happens multiples times and we decide to delete the fork and create it again, I think you should improve the message shows to the user so you can track that error on some way.

**Expected behavior**
Improved error messages.

**Comment by fenoloco** [comment]
![image](https://user-images.githubusercontent.com/3210977/80138686-8eb63980-857b-11ea-9dee-5f07d7265562.png)

**Comment by DannyDainton** [comment]
Hey @fenoloco 

Are you/your team still facing issues with merging forks in the latest version?

**Comment by DannyDainton** [comment]
Hey @fenoloco,

I'm going to close out this issue due to inactivity, please feel free to reach out to us if the problem persists in the latest version.
