### ISSUE TITLE
Sync is not working properly

### ISSUE THREAD

**Issue by fenoloco** [a85/POSTMan-Chrome-Extension#8353]
**Describe the bug**
Sync stop working and the only way to make it working again is to login and logout

**To Reproduce**
I don't have a way to force this happens but support team suggest me to logout/login so I think is widely know for your team.

**Expected behavior**
Sync improvement

**Comment by preethammavin** [comment]
@fenoloco that was an downtime in our services, we had posted the same on the statuspage. Do let us know if it happens again.

**Comment by fenoloco** [comment]
Suppose was a downtime.. (was not but suppose it was) why I need to do a logout and login to sync again.

Also read this: "I don't have a way to force this happens **but support team suggest me to logout/login so I think is widely know for your team**."

This ticket should no be closed.
