### ISSUE TITLE
Postman not save any request

### ISSUE THREAD

**Issue by yosacyber** [a85/POSTMan-Chrome-Extension#8354]
Postman not save any request, If I choose RAW, so form-data is data lost. 
and If I choose RAW form-data, raw data and others is lost.. i hop you fix its

**Comment by vvs11** [comment]
@yosacyber Could you give us the steps that need to be performed to reproduce this issue?

**Comment by vvs11** [comment]
Closing this for now. Please feel free to reopen this. Also, we have a very active community where you can get a quicker response for your queries 
community.getpostman.com
