### ISSUE TITLE
Dark themed Postman shows a bright menu bar on Windows and Linux 

### ISSUE THREAD

**Issue by marktoman** [a85/POSTMan-Chrome-Extension#8355]
**Is your feature request related to a problem? Please describe.**
Eye draining bright menu bar contrasting with the dark theme:

![image](https://user-images.githubusercontent.com/47689923/79699415-d729da80-828f-11ea-8b4d-f0fe57345373.png)

**Describe the solution you'd like**
The standard Windows solution is to hide the menu bar and show it on Alt keypress. This behavior is usually disabled in the settings by default.

**Describe alternatives you've considered**
Making the menu bar dark is also an option.

**Additional context**
Electron apps that have this feature: VS Code, Insomnia

**Comment by numaanashraf** [comment]
@marektoman System dark theme is partially supported in our early access canary build. https://www.postman.com/downloads/canary. Could you take that for a spin and let us know?

**Comment by marktoman** [comment]
@numaanashraf That solves the problem entirely, thanks.

**Comment by numaanashraf** [comment]
Glad to hear that! We'll keep the issue open till this lands on our stable channels.

**Comment by twitharshil** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5302
