### ISSUE TITLE
Can't access JS variables set in pre-request script

### ISSUE THREAD

**Issue by Username-is-unavailable** [a85/POSTMan-Chrome-Extension#8356]
Hi everbody.

I wanted to access a function that I defined in a pre-request script like:

![coll](https://user-images.githubusercontent.com/64019140/79756226-9a56f580-831a-11ea-8d8a-55f6b4d1a762.PNG)

Here's the code:
```
if (pm.identity == undefined)
{
    var setUser1 = () => {
        pm.environment.set('at', pm.environment.get('at_user1'));
    }
    var setUser2 = () => {
        pm.environment.set('at', pm.environment.get('at_user2'));
    }
    
    pm.identity = {
        setUser1,
        setUser2
    };
}
```

Unfortunately when I try to access this object, it says `undefined`.
Here's a screenshot and an excerpt of the postman console:
![req](https://user-images.githubusercontent.com/64019140/79756447-eace5300-831a-11ea-8fa0-b4b3bdd80618.PNG)

Is that a bug or a feature? And if it's desired behaviour, is there a way to achieve what I wanted?

I don't want to copy-paste the pre-request script into all of my 3000 requests. Actually I don't want to touch my requests scripts at all, but only call the function when needed.
Also it must only execute once for the whole collection, else it may also impact performance when executed for each request.

I read some documentation and googled a bit, but I can only find stuff about postmans variable scopes but not their JS variable scopes.

Using Postman v7.22.1

**Comment by DannyDainton** [comment]
You could access something like that using this in the Collection pre-request script:

```
utils = {
    setUser1: (pm) => {
        pm.environment.set('at', pm.environment.get('at_user1'));
    },
    setUser2: (pm) => {
        pm.environment.set('at', pm.environment.get('at_user2'));
    }
};
```

Then you would call that in a request using:

```
utils.setUser1(pm)
```

The `pm` argument is needed here or that function wouldn't execute correctly.
