### ISSUE TITLE
[7.22.1] unexpectedly closes under win 10 64bit

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#8357]
**the bug description**
the app unexpectedly closes with no load

**To Reproduce**
1. open postman
2. open another app
3. See postman is gone

**Expected behavior**
7.21 does not shows such behaviour

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version [7.22.1]
 - OS: windows 10 64 bit

**Additional context**
The system was not loaded, cpu and ram is 75% free

**Comment by numaanashraf** [comment]
@m3dbedb Could you send us a screen recording of this issue? Helps us debug this faster.

**Comment by DannyDainton** [comment]
Hey @m3dbedb

I'm going to close this issue out for now. 

If you're able to reproduce this problem on the latest version, we can open this issue again and look to see what's going on.
