### ISSUE TITLE
Show details about who and what paused a monitor

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#8358]
Filed by Postman, for general awareness, for an internal feature-request raised recently.

**Is your feature request related to a problem? Please describe.**
Currently, a monitor may auto-pause if there are errors (not test failure). A monitor may also be paused by a team member who has access.
This information is currently not captured in the "audit" logs or notifications.

**Describe the solution you'd like**

- Audit logs and notifications should capture who/what paused a monitor.
- The _last_ what/who paused monitor reason should be present next to monitors on the web-dashboards as well.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by godfrzero** [comment]
This is available now within an "activity log" pane on all platforms.
