### ISSUE TITLE
Postman not able to handle white space as charterer in password field

### ISSUE THREAD

**Issue by prakashettigar** [a85/POSTMan-Chrome-Extension#8359]
Basic Auth Password field does not accept white space, We have white space in the password it must be encoded, Postman is not handling it
If white space is added return <h1>401 Authorization Required</h1>

**Comment by vikiCoder** [comment]
Hi @prakashettigar,

Basic auth [RFC-7617](https://tools.ietf.org/html/rfc7617) does not suggest percent-encoding username/password. There is even an example in RFC just before the [section 2.1](https://tools.ietf.org/html/rfc7617#section-2.1) where the Authorization header for username `Aladdin` and password `open sesame` is shown as `Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==`. Postman also does the same as shown in the below screenshot:

![image](https://user-images.githubusercontent.com/16588032/79972392-8266a980-84b3-11ea-9fdc-eaf28978ec04.png)

If your server requires percent-encoded password, you can do it manually by right-clicking the password field and selecting `EncodeURIComponent` option.
