### ISSUE TITLE
Different Icons in Taskbar on different display scales

### ISSUE THREAD

**Issue by MichaelFlucher** [a85/POSTMan-Chrome-Extension#8361]
**Describe the bug**
Using a Surface Laptop 3 (2496x1664) and an external Display (1920x1080) I get two different Icons in the Taskbar. It changes when editing the scale of the display.

**To Reproduce**
1. use an external Display
2. open display settings and give the two displays a different scale (e.g. 100% and 125%)

**Expected behavior**
Same Icons, doesn't matter which scale.

**Screenshots**
External Display on 100%:
![image](https://user-images.githubusercontent.com/56301583/79839932-80b6bc00-83b5-11ea-852f-809f7f1d9b59.png)
External Display on 125%:
![image](https://user-images.githubusercontent.com/56301583/79840073-b2c81e00-83b5-11ea-8d74-b923bb66bbea.png)
Surface on 100%:
![image](https://user-images.githubusercontent.com/56301583/79840130-cd01fc00-83b5-11ea-9914-3689676fa234.png)
Surface on 150%:
![image](https://user-images.githubusercontent.com/56301583/79840195-e440e980-83b5-11ea-84bf-f2e51d69b182.png)

**App information (please complete the following information):**
 - App Type Postman for Windows
 - Postman Version 7.22.1
 - OS: win32 10.0.18363 / x64

**Comment by numaanashraf** [comment]
@MichaelFlucher This is intentionally and we choose the best logo variant that is still clear and legible for the chosen scale. I've passed this feedback onto our design team and we'll take this into consideration as we improve Postman.
