### ISSUE TITLE
Every request change updates collection variables' IDs and commits them

### ISSUE THREAD

**Issue by joshua-bn** [a85/POSTMan-Chrome-Extension#8365]
**Describe the bug**
When I make a change to a request (eg change a request name) it gets committed to a repo. That collection file then contains changes to all of the collection variable IDs. I didn't change any variables, just the request name.

This makes it very difficult to see what was actually changed.

**To Reproduce**
1. Setup Postman to commit changes to a repo
2. Add collection variables
3. Add a request
4. Change the request
5. Check the commits in the repo
6. Observe they contain variable id changes

**Expected behavior**
When I make a change to a request all that gets committed is the change to the request, not variable ID changes.

**Screenshots**
This was the only change I made. I removed a tab:
![image](https://user-images.githubusercontent.com/53793523/79900771-c33fbf00-83dc-11ea-80e5-0786d36ae81e.png)

Then there are 100 lines changed like this:
![image](https://user-images.githubusercontent.com/53793523/79900730-ae632b80-83dc-11ea-879d-c28af2a544aa.png)

**App information (please complete the following information):**
 - App Type native app
 - Postman Version Version 7.22.1 (7.22.1)
 - OS: macOS 10.15.3 (19D76)

**Additional context**

**Comment by bdunavant** [comment]
I came here looking for info about this same situation.   It causes a ton of unnecessary churn, and unwanted triggers of our CI/CD pipeline.

**Comment by dhaifley** [comment]
I am also experiencing this same issue.  It would be nice to not have such noisy commits for simple changes to tests within a collection.  Using all environment or local variables is less than ideal for the tests we are working with.

**Comment by shamasis** [comment]
Hi everyone. We intend to address this and a number of other related items (as outlined in this issue https://github.com/postmanlabs/postman-app-support/issues/2906). I do not have an ETA yet, but I can confirm that this is on our short term roadmap.

**Comment by mohitranka** [comment]
Hello! 👋  This issue was fixed along with #2906 . Please let us know if you continue to face any issues in the latest versions of the apps.
