### ISSUE TITLE
OpenAPI 3.0 nullable not supported

### ISSUE THREAD

**Issue by fabiendeborde** [a85/POSTMan-Chrome-Extension#8369]
Hello,
I am working on  a schema that was failing validation in Postman documentation tab, and finally found why it was failing.
I have this property in the schema 
```
siteLogo:
    type: string
```

and this example
```
siteLogo: null
```

Even when adding `nullable: true` in my schema the validation fails.
If I replace the example by `siteLogo: ''`, it passes.

Am i missing something, or the nullable property is not supported?

**Comment by VShingala** [comment]
@FabienDeborde Yes, It seems `nullable` keyword is not supported yet. The reason for it is we use JSON schema validation (we first convert OpenAPI schema to JSON schema for validation) and `nullable` is not supported by JSON schema.

Adding this as feature request.

**Comment by fabiendeborde** [comment]
@VShingala
Thank you for your answer. I was not sure if I had missed something.
From what I have read, the `null` type is supported in OpenAPI 3.1.
Between `nullable` property and `null` type, I have no idea which is easier to implement, but I hope you can add this feature in a somewhat near future.

**Comment by abhijitkane** [comment]
Thanks for reporting this @FabienDeborde 
@VShingala Changed this to `bug` - we should correctly interpret all parts of OAS that we claim to support.
