### ISSUE TITLE
Two collection can't share the same golbal variavles

### ISSUE THREAD

**Issue by ZoolMons** [a85/POSTMan-Chrome-Extension#8370]
**Describe the bug**
When I use the Postman's collection to run a post Method with a Json file include 5000 Json data.U know that may spend much time for server to do this, so the token will be invalid in 30 minutes later.So, i have to open other collection to run Login request for every 20 minutes before another collection's  token expired.But I found the token can't be updated in the Json file's collection,I console.log() two collections' token value,its strange.In Json file's collection, its always the same token value.But in Login collection, token is updated successful.Can u understand my poor English?Do u need me to post my script here?(I use the global variable in the two collections to share token value)
Thanks

**Comment by vvs11** [comment]
@ZoolMons, It'd be really helpful if you can share the script. You can also go through the documentation of using environments in scripts here:
https://learning.postman.com/docs/postman/variables-and-environments/variables/#defining-variables-in-scripts

We have a very active community where you can find the answer to your queries very quickly. Please feel free to post questions there. 
https://community.postman.com/

**Comment by vvs11** [comment]
closing this for now. Please feel free to reopen if you are still having issues
