### ISSUE TITLE
Postman app cookies are not being updated when they change in Chrome

### ISSUE THREAD

**Issue by JoeNyland** [a85/POSTMan-Chrome-Extension#8371]
**Describe the bug**
Native Postman app cookies are not being updated when they change in Chrome (using Interceptor extension for Chrome)

**To Reproduce**
1. Turn on interceptor and add localhost as a domain to track cookies for
1. Log in to web app on localhost in Chrome
1. Check that cookie has been tracked by Interceptor in Postman app
1. Log out of web app on localhost in Chrome
1. Log in to web app on localhost in Chrome
1. Cookie value has not been updated in Postman app, regardless of the fact that it has changed in Chrome

**Expected behavior**
According to the docs, Postman and Interceptor should keep the cookies in sync for the selected domains between Chrome and Postman.

> Interceptor keeps cookies for a fixed set of domains in sync, updating Postman from the browser when cookies update, including deletions.
[source](https://learning.postman.com/docs/postman/sending-api-requests/interceptor/#syncing-cookies)

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type: Native App and Chrome Interceptor extension
 - Postman Version: 7.22.1
 - Interceptor Version: 1.0.2
 - OS: macOS Catalina 10.15.4

**Additional context**
N/A

**Comment by chughmayank** [comment]
Hey @JoeNyland ! Are you still facing this issue? We pushed a couple of fixes in interceptor and you can check them out in the latest version of interceptor. You can use the learning doc to find how to update the interceptor here: https://learning.postman.com/docs/sending-requests/capturing-request-data/interceptor/#updating-interceptor

**Comment by JoeNyland** [comment]
Hey @chughmayank . I've not had this issue recently, so I'm happy to say this looks to be resolved. Sorry I've not communicated that until now 🤦 .
