### ISSUE TITLE
What scopes are required for the Github integration?

### ISSUE THREAD

**Issue by zgirod** [a85/POSTMan-Chrome-Extension#8372]
Hello,

I am setting up the Github integration to backup postman collections.  When configuring the personal access tokens in github can you please tell me the minimum scopes required to make the integration work.

If I missed the documentation somewhere please let me know and sorry I couldn't find it.

**Comment by SabriH10** [comment]
Hey @zgirod ,

The scopes needed for GitHub integration can be found in the documentation here: https://learning.postman.com/docs/integrations/github/#generating-a-github-personal-access-token

Hopefully, this helps.

**Comment by zgirod** [comment]
Sweet, much thanks!

**Comment by zgirod** [comment]
I would suggest you guys add a link to the documentation from this page: https://{{domain}}.postman.co/integrations/services/github/add/collection_github

At least would have helped me out..
