### ISSUE TITLE
Blank query parameters for saved request don't update from table

### ISSUE THREAD

**Issue by mnalsup** [a85/POSTMan-Chrome-Extension#8374]
**Describe the bug**
I am seeing an issue where blank query parameters from saved requests remain blank even if a value is given to them in the Params table. The value will update if the URL is modified.

**To Reproduce**
1. Create a request with a blank query parameter.
For example:
![image](https://user-images.githubusercontent.com/5252756/80030999-ae336080-84ae-11ea-89c9-7ff81aac048e.png)
2. Save the request and close it
![image](https://user-images.githubusercontent.com/5252756/80031198-fb173700-84ae-11ea-924e-4ea37310ffaa.png)
3. Open the request
4. Update the blank query parameter to some value (e.g. "world") using the table.
5. Send Request
![image](https://user-images.githubusercontent.com/5252756/80031409-3fa2d280-84af-11ea-8b6b-42d644ec610c.png)

I expected the query parameter hello=world to be sent. However, it was still blank after updating the value from blank to "world". The URL above the table does not reflect the actual request sent.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.22.1
 - OS: macOS Mojave 10.14.6 

Appears to be similar to:
#8251

**Comment by codenirvana** [comment]
@mnalsup Thanks for reporting this issue, we can reproduce this issue locally and will push a fix for this as soon as possible.

For now, the only workaround I see is to save the request again before sending the request.

**Comment by vikiCoder** [comment]
Hi @mnalsup,

This issue is fixed in the latest release of the Postman app (v7.24.0). Please update to the latest version to check it out. Feel free to reopen the issue if the problem still persists.
