### ISSUE TITLE
Postman response change the file extension from .mp3 to .mpga 

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#8377]
On behalf of user:

I have an api endpoint which is expected to return a .mp3 file (content-type:audio/mpeg, content-disposition:attachment; filename=my_filename.mp3).

On my first call, the response automatically calls the Save As dialog box with a default filename (‘GENERATED_GUID-response.mpga’).

![image](https://user-images.githubusercontent.com/41741228/80107207-6be64e00-8598-11ea-9d39-881c54a99154.png)
****

When I tried to cancel the save prompt and execute the same request call again, the Save As prompt is not showing up unless I change the input parameters to return a different file.

Please note that the default filename from the Auto Save As prompt always changes the extension of my expected file from .mp3 to .mpga.

The expected file only shows right (filename and extension) if I tried to save the file using the Save Response -> Save to a File instead.

![image](https://user-images.githubusercontent.com/41741228/80107247-7acd0080-8598-11ea-9fb2-6e416918ec99.png)

**Comment by DannyDainton** [comment]
Hey @ash007-postman 

Do we know if this is still an issue that the user is facing?

**Comment by Mechanicalkeyboard** [comment]
I was able to reproduce this issue.

**Comment by codenirvana** [comment]
This issue is fixed in the latest version of the Postman app `v8.3.0`.
