### ISSUE TITLE
Could not get any response There was an error connecting to

### ISSUE THREAD

**Issue by srajamohan** [a85/POSTMan-Chrome-Extension#8381]
**Working api's suddenly stopped working**

In developer console I can see that EditorStore was not able to find some parameters.

**Screenshots**
Attaching developer console screenshot
**App information (please complete the following information):**
 - Postman Version 7.23.0 (7.23.0)
 - OS: [e.g. macOS Mojave 10.14.6]

![image](https://user-images.githubusercontent.com/11278648/80129579-1d12c700-854c-11ea-9afd-e0c08c9a3e4f.png)

**Comment by vvs11** [comment]
@srajamohan Could you provide some more details so that we can assist you, Right now I am not able to understand what exactly is the issue

**Comment by vvs11** [comment]
@srajamohan Closing this for now.We have a very active community that will help you resolve your issues quickly.  Please feel free to reach out at http://community.getpostman.com/
