### ISSUE TITLE
"Open in Builder" does not work for few cases inside "Find and Replace"

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#8383]
**Describe the bug**
The `open in builder` button does not open the request in a tab for a few cases. 
![image](https://user-images.githubusercontent.com/5207331/80132991-29ce0400-85ba-11ea-8555-8d1a541003c4.png)

**To Reproduce**
1. Download this collection [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/eff743675b1a6cd432af)
2. Press `Cmd+shift+F` to open the `Find & Replace` panel
3. Search `kebab`
4. In the `collections` tab, click `Open in builder` -> it does nothing
5. Try searching for `token` -> this one works (at least for me)

This might or might not be related to the fact that having an underscore in the text that I search, never works.

**Expected behavior**
The request should open in a tab

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] Native Desktop App
 - Postman Version - 7.23.0
 - OS: macOS

**Comment by harryi3t** [comment]
I am no longer able to reproduce the issue even on the same version v7.23.0 where it happened the last time.

**Comment by sandeepmishra007** [comment]
Facing the same issue in Version 9.6.0. Please suggest.

**Comment by davecader** [comment]
This is still an issue with v9.18.0
