### ISSUE TITLE
Response body links opening incorrectly

### ISSUE THREAD

**Issue by HodGreeley** [a85/POSTMan-Chrome-Extension#8384]
Links in body responses open a new Postman tab instead of opening in a browser.

Links returned in the body of a response are normally active and clickable via ctrl/cmd + click.  The normal response is to open the URL in a browser.  After running for some period, links will start opening new tabs in Postman itself.

1. Create a call that produces a link in the response body.  E.g GET https://postman-echo.com/get?link="http://www.example.com"
2. Ctrl/Cmd click on 'http://www.example.com' in the response body tab.
3. See Postman opens a new tab instead of a browser window.

I have only observed this behavior after Postman has been running for a while.  Estimate at least five minutes, but it's hard to quantify.

**Expected behavior**
Link should be referred to a browser to open.

**App information (please complete the following information):**
 - Native app
 - Version 7.22.1
 - macOS Mojave 10.14.6

**Comment by DannyDainton** [comment]
Hey @HodGreeley,

I'm currently using v7.23.0 of the native Postman app. Using CMD + Click is opening the link in my default browser. Clicking directly on the link open it in a new tab. 

I left it open for 15 mins and didn't see the same behaviour. 

![Open_Browser](https://user-images.githubusercontent.com/17089546/80209917-c6c88580-862a-11ea-9c98-e8fedc4ce9a9.gif)

**Comment by HodGreeley** [comment]
I will try to reproduce with better details.  I think it's happening after actively using the app.  I'll try to pin down the circumstances more closely.

**Comment by vvs11** [comment]
@HodGreeley I am closing this for now, please feel free to re-open if you're still seeing this issue. You can also post on our community to get a quick response
