### ISSUE TITLE
UTF-8 content encoding not supported in body

### ISSUE THREAD

**Issue by vikas-getconnect** [a85/POSTMan-Chrome-Extension#8385]
**Describe the bug**
No content received to the server when the body has UTF-8 content

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a mock server using `docker run -d --rm -p 1080:1080 jamesdbloom/mockserver`
2. Create dummy API request as `curl --location --request PUT 'http://localhost:1080/mockserver/expectation'
--header 'Content-Type: application/json' 
--data-raw '{
          "httpRequest" : {
            "method" : "POST",
           "path" : "/utf1",
           "body" : {
		      "type" : "STRING",
		      "string" : "我说中国话",
		      "contentType" : "text/plain;charset=utf-8"
		    }
          },
           "httpResponse" : {
            "body" : {
                    "type": "JSON",
                    "json": "{\"name\":\"vikas\"}",
                    "contentType": "application/json; charset=utf-8"
                }
          }
}'`
3. POST the request from curl and verify setup is correct `curl --location --request POST 'http://localhost:1080/utf' --header 'Content-Type: text/plain;charset=utf-8' --data-raw '我说中国话'
Output : {"name":"vikas"}`
4. Check request receive to server and content length as 15`
http://localhost:1080/mockserver/retrieve?type=REQUESTS
{
    "method": "POST",
    "path": "/utf",
    "headers": {
      "Host": [
        "localhost:1080"
      ],
      "User-Agent": [
        "curl/7.54.0"
      ],
      "Accept": [
        "*/*"
      ],
      "Content-Type": [
        "text/plain;charset=utf-8"
      ],
      "Content-Length": [
        "15"
      ]
    },
    "keepAlive": true,
    "secure": false,
    "body": {
      "type": "STRING",
      "string": "我说中国话",
      "contentType": "text/plain; charset=utf-8"
    }
  }`

5. Now try same with postman as `curl --location --request POST 'http://192.168.0.101:1080/utf' 
--header 'Content-Type: text/plain;charset=UTF-8' 
--data-raw '"我说中国话"' `

6. Check request received at server again, you see **content-length as 0**
`  http://localhost:1080/mockserver/retrieve?type=REQUESTS`
`{
    "method": "POST",
    "path": "/utf",
    "headers": {
      "Content-Type": [
        "text/plain;charset=UTF-8"
      ],
      "content-length": [
        "0"
      ]
    },
    "keepAlive": true,
    "secure": false
  }`

**Expected behaviour**
Content length should not be 0. It should send the content as UTF-8 encoding

**Screenshots**
<img width="1118" alt="Screenshot 2020-04-24 at 10 36 03 AM" src="https://user-images.githubusercontent.com/6822992/80177045-1ea9c100-8618-11ea-9ec8-61980ac9d51e.png">

**App information:**
 - App Type [ Native App]
 - Postman Version [7.23.0]
 - OS: [e.g. macOS Mojave 10.14.6]

**Comment by codenirvana** [comment]
@vikas-getconnect Getting the following error on step 2:
```
1 error:
 - an expectation or expectation array is required but value was "null"curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) nested brace in URL position 19:
```

**Comment by vikas-getconnect** [comment]
@codenirvana  remove \ and try 

> vikass-MacBook-Pro:sequoia vikaschaudhary$ curl -v --location --request PUT 'http://localhost:1080/mockserver/expectation' --header 'Content-Type: application/json'  --data-raw '{ "httpRequest" : { "method" : "POST", "path" : "/utf1", "body" : { "type" : "STRING", "string" : "我说中国话", "contentType" : "text/plain;charset=utf-8" } }, "httpResponse" : { "body" : { "type": "JSON", "json": "{\"name\":\"vikas\"}", "contentType": "application/json; charset=utf-8" } } }'
> *   Trying ::1...
> * TCP_NODELAY set
> * Connected to localhost (::1) port 1080 (#0)
> > PUT /mockserver/expectation HTTP/1.1
> > Host: localhost:1080
> > User-Agent: curl/7.54.0
> > Accept: */*
> > Content-Type: application/json
> > Content-Length: 297
> >
> * upload completely sent off: 297 out of 297 bytes
> < HTTP/1.1 201 Created
> < version: 5.7.2
> < connection: keep-alive
> < content-length: 0
> <
> * Connection #0 to host localhost left intact

Also observed that if its raw then content is always 0

**Comment by codenirvana** [comment]
@vikas-getconnect You have to set the right `Content-Type` before sending the request.

<img width="981" alt="Screenshot 2020-04-24 at 6 29 23 PM" src="https://user-images.githubusercontent.com/4865836/80215174-a5cb5900-8659-11ea-8cc1-7cfeedb636c8.png">

**Comment by vikas-getconnect** [comment]
@codenirvana check step 3 which has headers 

<img width="1118" alt="Screenshot 2020-04-24 at 6 59 33 PM" src="https://user-images.githubusercontent.com/6822992/80217877-078dc200-865e-11ea-8f65-91d9e7ae03b4.png">
<img width="1119" alt="Screenshot 2020-04-24 at 6 59 20 PM" src="https://user-images.githubusercontent.com/6822992/80217885-09f01c00-865e-11ea-909e-ab61980af6d7.png">

**Comment by codenirvana** [comment]
@vikas-getconnect You are probably facing issues because you have disabled the `Host` header and most servers reject requests without that.

Here's how I tested:
```
curl -v -X PUT 'http://localhost:1080/mockserver/expectation' -d '{
  "httpRequest" : {
    "method" : "POST",
   "path" : "/utf1",
   "body" : {
  "type" : "STRING",
  "string" : "我说中国话",
  "contentType" : "text/plain;charset=utf-8"
}
  },
   "httpResponse" : {
    "body" : {
            "type": "JSON",
            "json": "{\"name\":\"vikas\"}",
            "contentType": "application/json; charset=utf-8"
        }
  }
}'
```

and requested `http://localhost:1080/utf1` with `Content-Type: text/plain;charset=utf-8` and raw `我说中国话` body without disabling any of the auto-generated headers.

Also, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.

**Comment by vikas-getconnect** [comment]
@codenirvana This is mock server setup. Also as mentioned in step 3 where we don't pass host header but we got a correct response. Is there anyhow I can track what postman is sending to the server?

**Comment by codenirvana** [comment]
@vikas-getconnect Like Postman, curl also includes a few auto-generated headers implicitly. Add `-v` flag to check the actual request sent via curl.

You can check the actual request sent via Postman using the [Postman console](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/#for-the-native-app-for-mac--windows--linux) (`CMD/CTRL + ALT + C`).
