### ISSUE TITLE
2-Way Sync Fails to Sync when the change originates on GitHub 

### ISSUE THREAD

**Issue by jarrodparkes** [a85/POSTMan-Chrome-Extension#8386]
**Describe the bug**
I've connected a Postman-managed API spec to a GitHub repository. As soon as I made the connection, I saw the spec (OpenAPI 3.0, JSON) appear in GitHub and everything appeared to be working correctly. Then, I made a change in Postman to the spec, and that change was correctly propagated to the GitHub repository, that also looks good.

However, when I pushed a change to the spec directly in GitHub (or anything external from Postman), the change never propagated back into Postman. For example, I made the following change to the spec using a text editor on my local machine:

```
     "info": {
-        "title": "Time",
+        "title": "TimeSheets",
         "version": "1.0.0",
-        "description": "Time API",
+        "description": "TimeSheets API",
         "license": {
             "name": "MIT"
         },
```

And then I committed this change and pushed it to the GitHub repository (to the same branch and same file used in the integration between Postman and GitHub). GitHub now shows the change and commit, but I can never get the change to appear in the Postman app. I've tried logging in-and-out and I've hit the various refresh buttons in the UI — nothing seems to work. Postman still shows the spec as being synced with this message: "Your schema is being synced with [file-name] file in your [repo-name] repo."

**To Reproduce**
1. Create an API in the Postman app
2. Connect the API (spec) to GitHub
3. Observe that the spec is being synced to GitHub
4. Make a change to the spec from outside of Postman (ex: in GitHub directly, or on your local machine in a text editor) and commit/push that change to GitHub
5. Observe that the change is not reflected in Postman (i.e. 2-way sync is not working)

**Expected behavior**
Unless I'm misunderstanding, 2-way sync implies that "changes from Postman to GitHub" are synced *as well as* "changes from GitHub/repo to Postman". Only one of these works. That is 1-way sync.

**Screenshots**
<img width="1014" alt="Screen Shot 2020-04-24 at 10 38 32 AM" src="https://user-images.githubusercontent.com/1331063/80230689-e5715100-8617-11ea-8d04-e190d324ccc7.png">
<img width="1372" alt="Screen Shot 2020-04-24 at 10 38 51 AM" src="https://user-images.githubusercontent.com/1331063/80230691-e609e780-8617-11ea-8137-0734b865f48a.png">

**App information (please complete the following information):**
 - App Type: Postman for Mac
 - Postman Version: Version 7.23.0 (7.23.0)
 - OS: macOS Catalina Version 10.15.4

**Comment by pranayat** [comment]
Hey, it seems like you haven't configured the webhook for the integration in Github.
You can refer to this doc describing how to do it - https://learning.postman.com/docs/integrations/github/#configuring-github-integration-for-api-schemas

Do let us know if this solves your issue.

**Comment by jarrodparkes** [comment]
@pranaya94 thanks for sharing. this did lead me to get it fixed. turns out I was using the incorrect payload url and secret (I had been simultaneously trying to set this up for two different specs and miscopied).

It might be useful in the docs to include a screen like this because GitHub's web hook settings provides useful information (see bottom) about when/if syncs fail. It also provides a way to retry the deliveries to verify if you've fixed the problem 👍 

<img width="1680" alt="Screen Shot 2020-04-24 at 12 24 24 PM" src="https://user-images.githubusercontent.com/1331063/80240018-d1811b80-8626-11ea-8bfa-dbaedba149c6.png">
