### ISSUE TITLE
Receiving emails about a deleted monitor

### ISSUE THREAD

**Issue by patrickgaskill** [a85/POSTMan-Chrome-Extension#8387]
I created a new Team Workspace, and then added the example SimpleKart API to it while following the tutorial. I then deleted the SimpleKart API and all the associated collections, monitors, etc. I still receive notification emails for the SimpleKart monitor that no longer exists.

**Comment by godfrzero** [comment]
@patrickgaskill Can you check if the monitor is still visible at https://go.postman.co/team/elements?type=monitor ? It sounds like the monitor was removed from the workspace, but not deleted. This will let us confirm that.
If you're able to see it on that page, you can also delete the monitor from there so it'll sort out the emails.

**Comment by godfrzero** [comment]
Closing this for now, will reopen if we get additional reports or any other information.

**Comment by dhawariata19** [comment]
I am experiencing the same thing but the https://web.postman.co/team/elements?type=monitor page does not load to check on the status.
