### ISSUE TITLE
Mask sensitive values displayed in the Environment Quick Look window

### ISSUE THREAD

**Issue by urbanaut** [a85/POSTMan-Chrome-Extension#8388]
When presenting or screen sharing with Postman, I may change one or more of the  values in the "Current Value" boxes within the "Environment Quick Look" while other colleagues are viewing Postman on my Desktop.  

As the "Environment Quick Look" window opens, it displays Global Variables which contain passwords as some of the values. Could you please add a feature that would allow a user to mask sensitive values, like passwords, in the Environment Quick Look window?

**Comment by vvs11** [comment]
@urbanaut Thanks for writing in!. This is definitely on our roadmap but we don't have an ETA yet. Will keep you posted.

**Comment by urbanaut** [comment]
Any progress on this? :-)

**Comment by bfrazarlou** [comment]
It could even automatically mask any value named "password".

**Comment by sallymcnally** [comment]
This would be a great addition.  I was able to see passwords through an online class last week.

**Comment by mbauerdev** [comment]
Same here!

**Comment by malvikach** [comment]
@urbanaut We are happy to share that our team has started work on this and we are looking to roll it out in early 2022. Thanks for sharing your feedback with us and helping us improve the product.

**Comment by malvikach** [comment]
We are excited to announce that, with this release (9.7.0) we have shipped the masking feature. 

You can now mark variable type on environment and globals. We support types `default` and `secret` with this release. 

- Type default will appear as plaintext on the screen, while type secret will enable masking of initial and current values of the variables. Variable type secret can be used to store sensitive information such as passwords, keys, tokens and secrets. 

<img width="1350" alt="screenshot_for_git_ticket" src="https://user-images.githubusercontent.com/89449769/147692368-191a2d38-c37b-408d-ba25-49cdae781cc5.png">

- Postman will automatically mark type default for any new variable that is created and for the existing variables. Editors can change the types on existing variables or create new variables with secret types

- You can use the toggle feature to temporarily view the masked values at various touchpoints on app/web (quick look, edit view, set as variable, pop-ups etc)

![masking_video](https://user-images.githubusercontent.com/89449769/147692381-87780880-5aab-4349-a411-7ec31bd8d95d.gif)


We hope this helps increase your productivity and enables you with better security.
