### ISSUE TITLE
Postman version migration error not displayed for users on V6

### ISSUE THREAD

**Issue by lakshmajee** [a85/POSTMan-Chrome-Extension#8389]
**Describe the bug**
Postman is not loading my collections in postman native client.
**OS**: Ubuntu 19.02
**Postman version ** 
```Postman for Linux
Version 6.7.6
linux 5.3.0-46-generic / x64
```
Note: I was able to view my collections in browser based postman i.e, some-domain.postman.co/

**To Reproduce**
1. No steps required, just install and login with an existing account and wait for the collections to load.

**Expected behavior**
postman should load the collections.

**Screenshots**
![Postman loading forever](https://raw.githubusercontent.com/lakshmajim/imgs/master/postman-loading-forever.png)
![Postman version](https://raw.githubusercontent.com/lakshmajim/imgs/master/postman-version.png)

**App information (please complete the following information):**
 - App Type  Native App
 - Postman Version 6.7.6
 - OS: Ubuntu 19.04

**Additional context**
NA - Facing this issue from last week.

**Comment by preethammavin** [comment]
@lakshmajim can you write to us at help@postman.com. So that we can take a deeper look into this? If possible do attach a screenshot of the build view

**Comment by mrbase** [comment]
Have the same issue.

OS: Ubuntu 18.04.4 LTS
Postman: Version 6.7.6 linux 4.15.0-1079-oem / x64

Installed via Snap

**Comment by avani-n** [comment]
Hey @mrbase, can you write to us at help@postman.com with logs attached so that we can take a deeper look into this? More details about how to get logs is listed here: https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/

**Comment by mrbase** [comment]
@avani-n send

**Comment by avani-n** [comment]
Thank you @mrbase for reaching out to support with logs. Issue has been identified as team has migrated to v7. For each team members to be able to use updated version, App version needs to be upgraded to v7 of App. Latest version of postman can be downloaded from [here](https://www.postman.com/downloads/).

**Comment by sankalp0o** [comment]
**Why is this happening?**
It seems like your team has migrated to the newer version of the app and you're trying to log in with an older version (which isn't compatible). This is documented here - https://learning.postman.com/docs/administration/migrating-to-v7/

The older app version should've shown a readable warning about the same. We're still looking into why this isn't happening.

**What can you do to fix the problem?**
Download and log in with the new version of the Postman app - [https://www.postman.com/downloads/](https://www.postman.com/downloads/)

**This still doesn't fix the issue for me**
If you're still facing the problem in the new version, please reach out to help@postman.com with [logs from the app](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/) and we will help you further!

**Comment by lakshmajee** [comment]
@sankalp0o using Postman Canary for now and is working as expected for now.
The thing is I have installed Postman native client from Ubuntu software center (is still an older version (6.x)). And it doesn't ask me to update the postman version.

**Comment by mrbase** [comment]
@lakshmajim I had to uninstall the old version, and select the newest from the gui to have it installed via snap.

**Comment by lakshmajee** [comment]
@mrbase where can I find *snap* in ubuntu?.  Is this different from ubuntu software center?

**Comment by mrbase** [comment]
@lakshmajim It's used by Ubuntu Software Center, so just go there :)

**Comment by cNoveron** [comment]
> Hey @mrbase, can you write to us at [help@postman.com](mailto:help@postman.com) with logs attached so that we can take a deeper look into this? More details about how to get logs is listed here: https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/

Here are my logs. Can you guys help me? @avani-n @preethammavin 

```
09:25:34.281 vendor-shared.js:118180 Initializing the global config
09:25:34.611 vendor-shared.js:48593 Could not find on WorkspaceStore. Missing or invalid parameter.
find @ vendor-shared.js:48593
09:25:34.748 vendor-shared.js:48593 Could not find on WorkspaceStore. Missing or invalid parameter.
find @ vendor-shared.js:48593
09:25:34.798 vendor-shared.js:48593 Could not find on EditorStore. Missing or invalid parameter.
find @ vendor-shared.js:48593
09:25:34.984 vendor-shared.js:48593 Could not find on EditorStore. Missing or invalid parameter.
find @ vendor-shared.js:48593
09:25:35.209 vendor-shared.js:48593 Could not find on CollectionStore. Missing or invalid parameter.
find @ vendor-shared.js:48593
09:25:36.679 vendor-shared.js:48593 Could not find on CollectionStore. Missing or invalid parameter.
find @ vendor-shared.js:48593
09:26:16.301 vendor-shared.js:48594 Could not perform update on UserListStore. id is missing in definition.
update @ vendor-shared.js:48594
09:26:17.349 vendor-shared.js:48593 Could not find on CollectionStore. Missing or invalid parameter.
find @ vendor-shared.js:48593
```

**Comment by avani-n** [comment]
Hey @carlosescom could you send the logs to help@postman.com and also the information about the Postman App version you are using?

**Comment by mccannt** [comment]
Just a quick update for everyone. We are still investigating these issues on a case by case basis. 
If anything is still experiencing an issue, I would encourage you to download the latest version of the application from [HERE](https://www.postman.com/downloads/)

**Comment by DannyDainton** [comment]
Hey folks,

I'm going to close out this issue for now but if users are still experiencing an issue here, we can open the issue again and look into the details of the problem.

**Comment by neerajjain-mpn** [comment]
Hi, I am getting below error on one of my shared workspaces on desktop version of the app. Unable to load the collection.
Other workspaces are working fine on desktop app. Also the workspace where I am having issues loading, works fine on browser.

Could not find on l. Missing or invalid parameter.
index.js:3757 Could not find on l. Missing or invalid parameter.

**Comment by DannyDainton** [comment]
Hey @neerajjain-mpn,

As this issue originally relates to V6 of the platform and is now closed. I would recommend raising a new issue with all the details of your current context and version.
