### ISSUE TITLE
API get Mock call logs

### ISSUE THREAD

**Issue by LisaLiu2** [a85/POSTMan-Chrome-Extension#8391]
As a user, I want to get the call logs when I use Mock server to test some cloud service, but I only can see the logs on website, could you provide an API to get the Mock Call logs? so that I can automatically analyze the logs.

**Comment by Dhembla** [comment]
Hey @LisaLiu2,
You can access call logs data for a mock server using this [API](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-f25efa16-1813-4279-8a89-a94ba968533e).
