### ISSUE TITLE
There is a black window while i try to open Postman

### ISSUE THREAD

**Issue by LessLia** [a85/POSTMan-Chrome-Extension#8392]
There is a black window while i try to open Postman

1. I have the latest version of Postman 7.23.0 from https://www.postman.com/downloads/
2. I have windows 10 32x
3. Launch the Postman

**Unxpected behavior**
I have only black window. There is no any errors. It is really stopped my work in IT company.
![image](https://user-images.githubusercontent.com/15209043/80303762-ed1d2b00-87ba-11ea-98bf-b80503de56b6.png)

**Expected behavior**
There is should by a blanck window with tabs

**Comment by numaanashraf** [comment]
@LessLia Could you try the workaround detailed at https://support.getpostman.com/hc/en-us/articles/360026088854-Postman-window-is-blank?

**Comment by LessLia** [comment]
> @LessLia Could you try the workaround detailed at https://support.getpostman.com/hc/en-us/articles/360026088854-Postman-window-is-blank?

Thank you! Postman is working now!

**Comment by numaanashraf** [comment]
@LessLia Glad to hear that. Closing this issue.
