### ISSUE TITLE
Encoding issue with synced APIs on GitHub

### ISSUE THREAD

**Issue by fabiendeborde** [a85/POSTMan-Chrome-Extension#8395]
Hello,　I have some Japanese text in my OpenAPI document, and I recently synced it with a GitHub repository, but the Japanese text comes out wrongly encoded and messes with the schema validity.

For example, this code
```
openapi: 3.0.0
info:
  title: My API
  version: 2.0.0
  description: 'My app 管理画面専用API'
```
will be saved as this
```
openapi: 3.0.0
info:
  title: My API
  version: 2.0.0
  description: 'My app ��;b�(API'
```
  
I am using Postman 7.22.1 on latest Mac version (10.15.4).

**Comment by smalltide** [comment]
I meet the same issue, is there any fix plan?

**Comment by Ramya-From-Postman** [comment]
@FabienDeborde, @smalltide  We have fixed this issue. Please verify the same and reach out to us incase the issue persists.

**Comment by fabiendeborde** [comment]
@Ramya-From-Postman I couldn't do extensive testing at the moment, but it seems it is fixed for us! Thanks a lot for the update!

**Comment by smalltide** [comment]
@Ramya-From-Postman 

It works well for us now.
Thanks
