### ISSUE TITLE
[Server down]

### ISSUE THREAD

**Issue by letanloc1998** [a85/POSTMan-Chrome-Extension#8397]
**Describe the bug**
I think your server contionue down

**To Reproduce**
Can't sync data

![image](https://user-images.githubusercontent.com/26348718/80349639-bc5ff300-8899-11ea-8dee-e45640469dcf.png)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/26348718/80349659-c255d400-8899-11ea-89a2-d74e3d70c627.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by preethammavin** [comment]
@letanloc1998 can you try restarting the application? and check if you are connected to the internet. If that does not work then please write to us at help@postman.com to take a deeper look

**Comment by letanloc1998** [comment]
> @letanloc1998 can you try restarting the application? and check if you are connected to the internet. If that does not work then please write to us at [help@postman.com](mailto:help@postman.com) to take a deeper look

Of course, I do any way
But now, maybe it up

Same issue: https://github.com/postmanlabs/postman-app-support/issues/8398
