### ISSUE TITLE
Postman not syncing

### ISSUE THREAD

**Issue by alereisan** [a85/POSTMan-Chrome-Extension#8398]
**Describe the bug**
On my Mac Postman is not completing the syncing process, the syncing spinner never stops.

**To Reproduce**
1. Start Postman
2. See out of date collections and never ending syncing spinner

**Expected behavior**
Collections should be synced

**App information (please complete the following information):**
 - App Type Mac App
 - Postman Version Version 7.23.0 (7.23.0)
 - OS: macOS Catalina Version 10.15.4

I have restarted Postman and Mac already.

**Comment by preethammavin** [comment]
@alereisan are you still facing the issue?

**Comment by alereisan** [comment]
@preethammavin yes

**Comment by preethammavin** [comment]
@alereisan can you write to us at help@postman.com so that we can take a closer look. Please do attach logs that you would find in view-> developer -> view finder in logs

**Comment by alereisan** [comment]
As Postman Support recommended to me: After deleting the app data by following the guide https://support.getpostman.com/hc/en-us/articles/360025359014 everything works again.
