### ISSUE TITLE
Downloaded archived collection missing request bodies

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#8400]
**Describe the bug**

When free team users have their collections archived and go request a data export from  https://app.postman.co/me/export - the body from all the requests have disappeared. 

**To Reproduce**
1. Get the collection A archived
2. Go to the Archive page - https://app.postman.co/me/export  and request a data export. 
3. Once available, download the data. 
4. Import the archived collection into a personal workspace.
5. See that request bodies for the collection A are empty.

**Expected behavior**
Navigating to https://go.postman.co/usage/archive should allow me to trigger a job that'll retrieve the collections and requests that have been archived - **the request body included.**

**App information (please complete the following information):**
- Postman Version 7.23.0 
- OS X 10.15.4
- Chrome 81

**Workaround** - Performing data-dump works - in the Potman app > Settings > Data > Download ✅

**Comment by sankalp0o** [comment]
We've identified the bug that is causing this and we're working on fixing it. We'll share progress on this thread.

In the meantime, the workaround mentioned above should allow you to access your data, request body included.

**Comment by inoas** [comment]
I have been hit by this this week after I downgraded a while ago and my subscription ended.

### what happend
- all my shared collections, despite being the only user on the team, got archived
- all the archives had no request data such as body params for post requests (essentially rendering things useless)

### what I did
- I got really disappointed towards the support team as this kind of feels like vendor-lock-in and I am kind of alergic towards bad biz ethics.
- I resubbed for 1 more month, and found my request on postman.co and could reshare them with myself and they reappeared in my postman

### what should/will happen
- the support team tries to help me figure out how to downgrade without losing my requests despite that I am the only user on any team (I have removed other users before downgrading the sub)
- there should be a way to contact support except through the sales email of your support team... i really felt lost.

... let's see where this goes.

**Comment by cyrielle-hada** [comment]
Closing the issue as a fix has been released.
