### ISSUE TITLE
Doc: Long tables in collapsible sections have no "View More" button

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#8401]
This is an issue in Postman Documenter: if a long table is placed in a collapsible section, the "View More" button is missing and the bottom part of the table is hidden.
It occurs with multiple browsers, devices, O/S and screen resolutions but in some rare cases it works fine. 

**Demo**: https://documenter.getpostman.com/view/8758645/SzfDw4YG?version=latest

**Expected behavior**
Same behavior as long tables outside collapsible sections: with a View More button. 

**Screenshot**
![image](https://user-images.githubusercontent.com/64472771/80482695-b899a280-8965-11ea-9c96-680514898c6b.png)

**App information**
 - Postman Version 7.23.0
 - OS: Multiple (tested in latest Windows and Mac OS Mojave 10.14.6)
 - Browsers: Chrome 81.0.4044.122 (Official Build) (64-bit), Firefox 75.0 (64-bit), Safari 13.1
 - Screen resolution: 1366 x 1024 and 1440 x 900

**Workarounds**
Splitting tables or removing the details tags.

**Comment by Raja-Simha** [comment]
@EWieman thanks for reporting. We will look into this issue

**Comment by Cazaimi** [comment]
@EWieman , really appreciate you publishing a documentation to demonstrate the bug! As already mentioned by @Raja-Simha , we'll be looking into the same.

**Comment by ghost** [comment]
The View More option is back now so the issue seems to be fixed. Checked in different browsers. I'll close the issue, thanks for fixing!
