### ISSUE TITLE
Computed OAuth1 oauth_signature displayed incorrectly in Authorization Header since 7.21.0

### ISSUE THREAD

**Issue by aitalian** [a85/POSTMan-Chrome-Extension#8402]
**Describe the bug**
Beginning in Postman for Windows version `7.21.0`, when using Authorization Type OAuth 1.0, the computed `oauth_signature` displayed to the user in the Authorization Header and viewing generated Code samples are incorrect, but a submitted request still works.

From the changelog for the affected version, I believe this may be relevant:
> [GitHub #3999] - Added an option to toggle encoding of Authorization header in OAuth1

**Version(s) affected**
Postman for Windows `>= 7.21.0` (23 Mar, 2020)
Regression first appears in Postman for Windows version 7.21.0 (repeatable in 7.22.1 & 7.23.0) and is NOT present in 7.20.1.

**To Reproduce**
Begin by installing Postman for Windows version 7.21.0. Use/import a collection/environment of your choice that utilizes OAuth 1.0.

1. Send a (valid) request using OAuth 1.0 authorization with auto-generated timestamp and nonce. Signature method can be either `HMAC-SHA256` or `HMAC-SHA1`.
1. In the request tab, view the Headers, and unhide auto-generated headers.
1. Observe the Authorization header string for each key/value pair. Take note of the generated `oauth_timestamp`, `oauth_nonce`, and `oauth_signature` values.
1. Using your language/library of choice, attempt to generate an OAuth1 signature using the same submitted `oauth_nonce`, `oauth_timestamp`, and applicable consumer/token secrets/keys from your environment. Compare your generated signature to the `oauth_signature` value Postman is displaying in the Authorization header. Observe that it does NOT match the computed value.
1. Click the "Code" link at the top right in the requests tab.
1. In the Generate Code Snippets window, observe that the same incorrect `oauth_signature` value persists in each code snippet language listed.

Repeat the above steps on version 7.20.1 and observe that the displayed oauth_signature is generated correctly.

Note that checking "Encode the parameters in the Authorization header" does not change the end result - whether the signature is encoded or not, is not the reason for the mismatch.

**Expected behavior**
The `oauth_signature` in the Authorization headers displayed to a user is generated correctly.

**App information (please complete the following information):**
 - Postman for Windows version >= 7.21.0 (23 Mar, 2020)
 - OS: Windows 10 Pro 1909 64-bit

**Comment by mohitranka** [comment]
This issue has been fixed in the latest release, v7.27.0. Please upgrade and let us know if you face any issues.

**Comment by noizecamp** [comment]
This issue is happening again on v 7.27.1. Please take a look.

**Comment by firstlight-comm** [comment]
OAuth 1.0 signature is failing in v7.27.1, but succeeds in other versions

**Comment by arlemi** [comment]
@noizecamp @Firstlist-comm Please follow up in #8737.
