### ISSUE TITLE
It would be really nice if we can share the api privately i.e internal to the teams

### ISSUE THREAD

**Issue by lokeshreddyp** [a85/POSTMan-Chrome-Extension#8405]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-
I'm unsure if this feature exists. If that exists please navigate me to it

**Comment by arlemi** [comment]
Can you give a bit more details as to what you'd like to be shared? 
Are you talking about an API Network private to a Postman team? (see https://explore.postman.com/)

**Comment by lokeshreddyp** [comment]
Sorry for not being clear.If I have an API designed and wanted to publish. Currently, there is a way to publish it publicly, but I do not want to publish it to everybody, instead, I want to publish it to our internal team. @arlemi

**Comment by sankalp0o** [comment]
@lokeshreddyp thanks for reaching out! 
We have a feature that lets you "Share" collections and APIs with your team? Here are some links that describe this feature! https://learning.postman.com/docs/postman/collections/sharing-collections/ https://learning.postman.com/docs/postman/design-and-develop-apis/managing-apis/#sharing-apis

I'm closing this ticket because I think this is what you were looking for. In case it doesn't, or if we can improve the experience somehow, please let us know!

**Comment by lokeshreddyp** [comment]
That is not what I'm looking for.I want to push the API privately because everyone in the team can see the documentation @sankalp0o

**Comment by arlemi** [comment]
We have "Private API Network"on [our roadmap](https://trello.com/c/6rOiYjfW/131-private-api-network), that sounds similar to what you're asking. Though it will only be available for Business and Enterprise plans at first. 

Reopning this and marking as a feature request, thanks for the suggestion!

**Comment by sankalp0o** [comment]
@lokeshreddyp Just so that we understand your use case correctly, you want to share it with some members in your Postman team but not everyone?

**Comment by lokeshreddyp** [comment]
I mean publish API Privately - internally to our team 

Currently, PostMan has a feature to publish API, at that point that will be available to the public

**Comment by arlemi** [comment]
@lokeshreddyp Can you clarify what you mean by "team", do you mean:
- your engineering team as a whole (e.g. Postman AND non-Postman users), so a private page protected by a password for example.
- your Postman team (e.g. only your engineers that are in the same [team workspace](https://learning.postman.com/docs/postman/workspaces/intro-to-workspaces/#team-workspaces)), so documentation where you would need to login with your Postman account

**Comment by lokeshreddyp** [comment]
that means it will only be published privately to the members who in the organization's team workspace only and cannot be viewed or accessed by other postman users.

**Comment by preethammavin** [comment]
@lokeshreddyp let me see if I can get that information right.
You want to publish/share API documentation but only to the section of people on your Postman team?
Postman has private workspaces where the elements( in this case API documentation) shared in it is only visible to the users in that workspace. The elements in that workspace will only be made visible if the users in that workspace share to any other team workspace. This is available for Business and Enterprise plan: https://learning.postman.com/docs/postman/workspaces/intro-to-workspaces/#private-workspaces

If you want to share it with the team but not the whole organization you can share it any workspace as mentioned above by @sankalp0o 

We are also working on the Internal API network, very similar to our external API network (https://explore.postman.com/) where users can publish to only their internal Postman team as API definition.

Let me know if this clears it up.
Assuming that you are looking for API documentation to be published to be visible only to your organization without some users being in the same Postman Team is not possible as of now.

**Comment by gitThingsDone** [comment]
@lokeshreddyp We recently launched the private API Network ([v7.27](https://www.postman.com/downloads/)), which allows you to publish APIs privately within your team. Do check it out and let us know if this solves your use-case! (docs [here](https://learning.postman.com/docs/postman/collaboration/adding-private-network/#adding-your-apis))

**Comment by arlemi** [comment]
The Private API network should be solving this issue, will close it for now. Let us know if you have any feedback!
