### ISSUE TITLE
Name of service field shows all text in view mode but only shows 395x18 points in edit mode

### ISSUE THREAD

**Issue by garywade** [a85/POSTMan-Chrome-Extension#8406]
**Describe the bug**
The name of the service being viewed/edited/ran has a name field that shows the full contents of its text filled to the width of the window, but when the user clicks on the pencil icon to edit its contents, the text field used is only 395x18 points in size (text viewing portion).  Since there's nothing else being shown, it seems reasonable the edit field should take up the entire possible space rather than a very small amount.

**To Reproduce**
1. Name a service to have a long name, typically some values that differentiate it from another one
2. Notice the text field used, even after the first edit, is still the same small size rather than taking up the available space
3. Notice the full space available is used to display the value in view mode.

**Expected behavior**
Edit mode should take advantage of the available space, or at least a much larger amount than currently used.

**Screenshots**
<img width="1674" alt="Screen Shot 2020-04-28 at 4 03 59 PM" src="https://user-images.githubusercontent.com/21062735/80546512-a8d08d00-896a-11ea-807f-641a702420b9.png">
<img width="1677" alt="Screen Shot 2020-04-28 at 4 03 49 PM" src="https://user-images.githubusercontent.com/21062735/80546514-aa01ba00-896a-11ea-95aa-9cd2edfad065.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.23.0 (7.23.0)
 - OS: macOS 10.15.4

**Additional context**

**Comment by arlemi** [comment]
This was fixed in the latest version of the app, please update your app and let us know if this is still not working!
