### ISSUE TITLE
Please add empty-guid predefined global variable

### ISSUE THREAD

**Issue by weitzhandler** [a85/POSTMan-Chrome-Extension#8407]
Much like `{{$guid}}`, please add something like `empty-guid` (`00000000-0000-0000-0000-000000000000`), that generates an uninitialized guid, to be used for validation purposes.

Alternatives: copy-paste from [here](https://stackoverflow.com/a/48804617/75500).

**Comment by arlemi** [comment]
Hey @weitzhandler,

 We're using faker.js to generate dynamic variables, you would need to request that feature on their project for it to eventually make it to Postman: https://github.com/Marak/faker.js

In the meantime, you could [define a variable](https://learning.postman.com/docs/postman/variables-and-environments/variables/) called `empty-guid` and initialise it to `00000000-0000-0000-0000-000000000000`, then you could call it the same way in your request (e.g. `{{empty-guid}}`).
