### ISSUE TITLE
Feature request: Support OAuth 2.0 refresh tokens (for Authorization code flow)

### ISSUE THREAD

**Issue by anno1985** [a85/POSTMan-Chrome-Extension#8409]
From what I understand, Postman does currently not automatically support OAuth 2.0 refresh tokens. 

When using the Authorization code flow (i.e. user needs to log in) it would be nice if Postman would (optionally) [renew a token](https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/) when it has expired/is about to expire and when it also had received a refresh token from the auth server. (Our tokens expire after a couple of minutes, and having to re-authenticate constantly isn't an option.)

Being able to persist OAuth 2.0 settings with collections as per #5459 or #2433 together with this feature would really help.

**Comment by arlemi** [comment]
Please follow #2452 for updates regarding that feature-request. 🙂
I'd recommend you check out that answer that explains how to automatically refresh tokens using collection-level pre-request scripts: https://github.com/postmanlabs/postman-app-support/issues/2452#issuecomment-382149670
