### ISSUE TITLE
Possibility to disable optional request parameters while importing from OpenAPI

### ISSUE THREAD

**Issue by prondzyn** [a85/POSTMan-Chrome-Extension#8410]
**Is your feature request related to a problem? Please describe.**
Not sure if it is a feature. Maybe such an option already exists and I only cannot find how use it. My problem is that when I'm importing collection from OpenAPI JSON. I have endpoints that have optional and required request parameters. Currently, after import, all such parameters are marked as enabled - no matter if it is optional or required.

![what_i_have](https://user-images.githubusercontent.com/5822647/80588550-d83dd300-8a18-11ea-8ec8-a2266542a277.png)

**Describe the solution you'd like**
I would like to have optional parameters marked as disabled and required parameters marked as enabled.

![what_i_would_like_to_have](https://user-images.githubusercontent.com/5822647/80588563-dc69f080-8a18-11ea-9a0a-c1f4b6702ea8.png)

**Describe alternatives you've considered**
I was not thinking about alternatives. Are there any alternatives?

**Additional context**
Example OpenAPI to import:
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "TEST",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "security": [
    {
      "access-token": [],
      "secret-token": []
    }
  ],
  "paths": {
    "/v1/examples": {
      "get": {
        "tags": [
          "EXAMPLE"
        ],
        "operationId": "get examples",
        "parameters": [
          {
            "name": "requiredParam",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "optionalParam",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "default response",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Example"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Example": {
        "type": "object",
        "properties": {
          "value1": {
            "type": "string"
          },
          "value2": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "access-token": {
        "type": "apiKey",
        "name": "access-token",
        "in": "header"
      },
      "secret-token": {
        "type": "apiKey",
        "name": "secret-token",
        "in": "header"
      }
    }
  }
}
```

**Comment by abhijitkane** [comment]
@prondzyn Yep - we're tracking this at https://github.com/postmanlabs/openapi-to-postman/issues/31. Closing this as a duplicate.

**Comment by prondzyn** [comment]
Thank you. Sorry for the duplicate.
