### ISSUE TITLE
Explain conversion from OpenAPI examples to Postman

### ISSUE THREAD

**Issue by JayChandler** [a85/POSTMan-Chrome-Extension#8413]
How does Postman convert examples from requests and responses into Postman examples. It seems multiple examples under the media type are not supported ?

It seems Postman always takes the first example from **requestBody** and maps it to the first example of each **response** example?

Is it really always necessary to manually edit the collection examples to work properly ? I would have expected Postman would display it a bit more like swagger

This is my code

```
paths:
  /freightcosts:
    post:
      tags:
        - "Freight costs"
      summary: "Calculates freight costs"
      operationId: freightCosts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FreightCostsRequest"
            examples:
              example-1:
                summary: "Example 1"
                value:
                  customerNr: "10000017"
                  orderType: D
                  deliveryAddress:
                    countryId: ITA
                    stateId: MI
                  lineItems:
                    - sku: "109074"
                      salesUnit: conf
                      quantity: 1
                      nettPrice: 23.52
                    - sku: "115219"
                      salesUnit: pz
                      quantity: 10
                      nettPrice: 4.8
              example-2:
                summary: "Example 2"
                value:
                  customerNr: "10000017"
                  orderType: D
                  deliveryAddress:
                    countryId: ITA
                    stateId: MI
                  lineItems:
                    - sku: "109074"
                      salesUnit: conf
                      quantity: 1
                      nettPrice: 23.52
      responses:
        "200":
          description: "A list of freight costs"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FreightCostsRow"
              examples:
                single-line:
                  summary: "Single line"
                  value:
                    - code: FREIGHT
                      description: "costi di trasporto"
                      amount: 5
                      currencyCode: EUR
                multiple-lines:
                  summary: "Multiple line"
                  value:
                    - code: FREIGHT
                      description: "costi di trasporto"
                      amount: 5
                      currencyCode: EUR
                    - code: WEIGHT
                      description: "costi di trasporto"
                      amount: 10
                      currencyCode: EUR
        "503":
          description: "Load balancer error"
          content:
            text/html:
              schema:
                type: "string"
              example: >+
                <html>
                  <body>
                    <h1>503 Service Unavailable</h1>
                    No server is available to handle this request.
                  </body>
                </html>
        default:
          description: "Error response"
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                title: "Server error"
                status: 500
                detail: "Something bad happened"
```

**Comment by VShingala** [comment]
@JayChandler  
For requestBody, Postman Collection request body contains first example.

For responses, Each response of OpenAPI schema is mapped to postman collection response. First example is picked up for one response (i.e. for 200 single-line example is picked up).

Now as one collection request/response can have only one body, only first example is assigned as request/response body.

Can you suggest what will ideal generated collection be for you in this case?

**Comment by JayChandler** [comment]
I understand that in OpenAPI there is no relation between request and response examples like in Postman so i think it's quite difficult to do the right thing. In my personal opinion i would treat request examples and response examples in their own way. 

If **multiple request examples** are defined there should be a **dropdown** like in the **swagger** ui to choose which example to show. In an API which is very powerful and configurable multiple examples are very important to show different use cases.

The same goes for multiple response examples. The description can be used to build a semantical relationship between request and response.

I think the way swagger ui does it is pretty cool
```
paths:
  /freightcosts:
    post:
      tags:
        - "Freight costs"
      summary: "Calculates freight costs"
      operationId: freightCosts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FreightCostsRequest"
            examples:
              example-1:
                summary: "Example 1"
                value:
                  customerNr: "10000017"
                  orderType: D
                  deliveryAddress:
                    countryId: ITA
                    stateId: MI
                  lineItems:
                    - sku: "109074"
                      salesUnit: conf
                      quantity: 1
                      nettPrice: 23.52
                    - sku: "115219"
                      salesUnit: pz
                      quantity: 10
                      nettPrice: 4.8
              example-2:
                summary: "Example 2"
                value:
                  customerNr: "10000017"
                  orderType: D
                  deliveryAddress:
                    countryId: ITA
                    stateId: MI
                  lineItems:
                    - sku: "109074"
                      salesUnit: conf
                      quantity: 1
                      nettPrice: 23.52
      responses:
        "200":
          description: "A list of freight costs"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FreightCostsRow"
              examples:
                single-line:
                  summary: "Example 1 - Single line"
                  value:
                    - code: FREIGHT
                      description: "costi di trasporto"
                      amount: 5
                      currencyCode: EUR
                multiple-lines:
                  summary: "Example 1 - Multiple line"
                  value:
                    - code: FREIGHT
                      description: "costi di trasporto"
                      amount: 5
                      currencyCode: EUR
                    - code: WEIGHT
                      description: "costi di trasporto"
                      amount: 10
                      currencyCode: EUR
        "503":
          description: "Load balancer error"
          content:
            text/html:
              schema:
                type: "string"
              example: >+
                <html>
                  <body>
                    <h1>503 Service Unavailable</h1>
                    No server is available to handle this request.
                  </body>
                </html>
        default:
          description: "Error response"
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                title: "Server error"
                status: 500
                detail: "Something bad happened"
```

![Desktop_screenshot](https://user-images.githubusercontent.com/6359575/80966324-9b0c8300-8e14-11ea-883f-34b52345572c.png)

**Comment by simoalex** [comment]
Hey guys, thank you for this thread. The whole last week I'm searching exactly what Jay's talking about. Postman is a genius tool, but importing from OpenAPI with examples is hell because it imports only the first example and ignores others. In fact, you need to make all examples manually in Postman every time you export a new version of OpenAPI yaml/json-file and make a collection from it.

> I understand that in OpenAPI there is no relation between request and response examples

And this is a problem. But we can bypass this using many ways:
1. Make examples one by one. Take the first example from requestBody and connect it with the first example from responses (like it works now). Then take the second example from requestBody and connect it with the second example from responses. And so on.
2. Using names. Every example in OpenAPI has a name. If the name in requestBody and responses match we can make an example from it. Repeat with all examples.
The first option is more convenient, the second is more accurate.

@VShingala I hope you can make it because it will make Postman a magnificent tool for Design First workflow (https://apisyouwonthate.com/blog/api-design-first-vs-code-first).
The whole week I tried to find a good tool that can make a mock-server from my OpenAPI YAML with multiple examples and exact responses for exact requests, I tried a lot of mock-servers and nobody can do this! Postman can (with x-mock-response-code header), but you can't export multiple examples from the OpenAPI file. I hope you will fix this.

**Comment by kpsteven** [comment]
I'm also encountering some flaws regarding my examples in postman when generating my documentation from a yaml.
My issue is that postman is randomly selecting one example to show among all available in my yaml.

My suggestion would be to do something similar as the environment selection when previewing the documentation.
When you're previewing your documentation in postman web, there is no environment. You can select the one you like and then click publish. Then the documentation will take this environment by default to every user who look at your documentation.
This could be a great feature for the examples, too.

**Comment by blinkofaneye** [comment]
Any update on this ?

**Comment by Ronnie-J** [comment]
I second this. I used a lot of time understanding this implementation in Postman. I would suggest following the method implemented in swagger ui. I have API endpoints with multiple examples for request body's and response as well.

**Comment by popensesame** [comment]
+1 I'd like to generate multiple postman examples for a single status code from an openapi schema and also control which request body examples are mapped to response examples.

Could we use named examples for request bodies and responses and then generate postman examples by matching the names of the openapi examples to generate postman examples?

For example:

```
paths:
  authenticate:
    post:
      summary: Get a token
      requestBody:
        content:
          application/json:
            schema: "#/components/schemas/LoginRequest"
            examples:
              AuthenticateSuccess:
                summary: Request tokens successfully
                value:
                  username: user@company.com
                  password: password
              BadPasswordError:
                summary: Request tokens - bad password
                value:
                  username: dummy@company.com
                  password: incorrect_password
      responses:
        200:
          description: Oauth tokens (access, id, refresh) for the authenticated user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
              examples:
                AuthenticateSuccess:
                  value:
                    Token: XXXXXXXXXXXXXXXXXX
        400:
          description: User not found error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNotFoundError"
              examples:
                BadPasswordError:
                  value:
                    message: Incorrect password.
```

So two postman examples would be generated, one based on the AuthenticateSuccess key, and another based on the BadPasswordError key.

**Comment by fgblomqvist** [comment]
@VShingala Thanks for implementing this! Will that change roll out in the normal Postman client or is that plugin standalone?

**Comment by VShingala** [comment]
@fgblomqvist This will be rolled out with the next version of Postman App client v10.19 which is scheduled to be released around 15th Oct.

**Comment by VShingala** [comment]
@JayChandler @simoalex @kpsteven @blinkofaneye @Ronnie-J @popensesame @fgblomqvist We've added support for this with latest Postman App v10.19. Please give it a try and let us know your feedback.

Here's brief overview of how this will work.

1. If request body and response body both have an example with the same example key, we'll create a separate example with matching request and response body.
2. If request body and response body example key doesn't match, we'll try to create a matching based on the order or mention of these examples. i.e. 1st example will contain 1st request body example and 1st response body example in it.
3. If after above, we have request or response bodies without matching, we'll use the existing behavior of using the first example. (Note that, we'll create one separate example for each example for both the request body and response body even if matches are not found)

**Comment by roman-novosad-exa** [comment]
@VShingala hey. thanks for putting efforts in it. but I do still see the problem with examples. None of them is being added to the request normally nor to the response. please checkout the video - https://www.loom.com/share/b80d17ae0a3d497190b749c85442b54e
I'm running Postman
UI Version: 10.23.1-ui-240213-0705
Desktop Platform Version: 10.23.0 (10.23.0)

**Comment by VShingala** [comment]
@roman-novosad-exa It seems you've incorrect options selected while generating this collection.

We've mentioned how to use `Examples` while generating a collection here, Could you follow this and let us know if still face further issue with it?: https://github.com/postmanlabs/postman-app-support/issues/10878#issuecomment-1914743881

**Comment by roman-novosad-exa** [comment]
@VShingala thanks for the quick response. it helped!
I'm facing another issue, when importing multiple examples in request/response body. Is it possible somehow to disable automatic matching and merging these if no keys are matching?

**Comment by VShingala** [comment]
@roman-novosad-exa You can find more about how we match requests-responses here (https://github.com/postmanlabs/openapi-to-postman/pull/768#issue-1911459880). Currently, what you mentioned about _"disable automatic matching and merging these if no keys are matching"_ is not supported since we haven't had use case for this yet.

**Comment by roman-novosad-exa** [comment]
@VShingala can it be added if now there is such use case?

**Comment by VShingala** [comment]
@roman-novosad-exa Could you raise a separate ticket for it under [this repo](https://github.com/postmanlabs/openapi-to-postman/issues) with exact use-case you have and assign it to me? i.e. With exact behaviour and examples if possible. Also could you mention in that issue what do you mean by merging and how it should work?
