### ISSUE TITLE
Preview response in default browser

### ISSUE THREAD

**Issue by caot** [a85/POSTMan-Chrome-Extension#8415]
Is it possible to put the response in Preview to a external or default browser? And the browser can be configured beside the Preview Tab.

**Comment by arlemi** [comment]
If you're asking about opening a link present in a response then you can use `cmd+click` or `ctrl+click`.

If you're wondering about getting the whole response directly in the browser then this isn't feasible, instead you can download the response (using the dropdown on the right of the `Send` button) and then open it in browser. 

Example with an image: 
![download](https://user-images.githubusercontent.com/5029719/80650193-6e9ae480-8a6b-11ea-9c22-0ff71bf28271.gif)

**Comment by caot** [comment]
It's not  the links in the response but the response itself.

**Comment by arlemi** [comment]
In that case I'm assuming downloading the response allows you to do what you want. 

If not, please open a [new feature request](https://github.com/postmanlabs/postman-app-support/issues/new?template=Feature_request.md) and fill in all the details (inc. why you would need that option, possible solution...).
