### ISSUE TITLE
Environment variable reference fails

### ISSUE THREAD

**Issue by MichaelBrooks-Version1** [a85/POSTMan-Chrome-Extension#8419]
**Describe the bug**
My URL fails to resolve an environment variable.

**To Reproduce**
Create an environment variable EmbossURL whose value is the start of a URL, and a collection variable MTR of any value.
Create a request and embed {{EmbossURL}} at the beginning and {{MTR}} somewhere in the middle.
{{MTR}} is displayed in orange and if you hover the mouse pointer over it, a popup displays the resolution.
{{EmbossURL}} is displayed in red and if you hover the mouse pointer over it, a popup reports "Unresolved variable".

**Expected behavior**
Both variables within the displayed URL should be shown coloured orange and when you hover the mouse pointer over them a popup should display their resolution.

**Screenshots**
![PostmanEnvVarResolveFail](https://user-images.githubusercontent.com/55983317/80713748-d729a600-8aeb-11ea-811b-3cb6d4bf87da.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.20.1
 - OS: Windows 10 build 18362.778

**Additional context**
Nothing to add.

**Comment by arlemi** [comment]
Hey @MichaelBrooks-Version1, looking at your screenshot it looks like you've written the variable name in the `Initial Value` field instead of `Variable` when setting your environment variable. Moving `EmbossURL` to the variable field will fix your issue.

**Comment by MichaelBrooks-Version1** [comment]
Yes, I just spotted that one myself and came back here to update the issue. 
I never said I wasn't stupid...    ;-)

Thanks arlemi.
