### ISSUE TITLE
variable values are not saved with collection export

### ISSUE THREAD

**Issue by fedup41** [a85/POSTMan-Chrome-Extension#8421]
I edit the collection and provide a variable called baseURL with a certain value.  Upon exporting the collection the resulting JSON does not include the value.

![image](https://user-images.githubusercontent.com/8181401/80749602-4b644980-8aec-11ea-8cff-f289034b64a7.png)

![image](https://user-images.githubusercontent.com/8181401/80749857-bb72cf80-8aec-11ea-8248-78ecab73cfa4.png)

![image](https://user-images.githubusercontent.com/8181401/80749485-1bb54180-8aec-11ea-8ba6-081285d50fee.png)

The value that I entered and shows up in the GUI should be present in the exported collection json.  I get the same incorrect results with any of the 3 export formats.

Postman v7.23.0

**Comment by fedup41** [comment]
Clarification - this was more of a misunderstanding on my part.  Apparently it is the initial value only that is saved.  The current value is not.  Maybe both should be exported.

**Comment by arlemi** [comment]
@fedup41 We do not export the current value to allow users that are sharing their collections to be able to use different configurations without editing their colleagues' ones. 
You can read more about it on our Learning Center: 
https://learning.postman.com/docs/postman/variables-and-environments/variables/#sessions-in-postman

**Comment by quebez** [comment]
You cannot export the variable values, however, after you export it, you can **manually populate the values at the end of the json file**.

**Comment by DannyDainton** [comment]
@quebez If the variable has been explicitly shared by the user, they will be part of the exported Collection.

<img width="3326" height="534" alt="Image" src="https://github.com/user-attachments/assets/d1f67761-6f14-4bf5-b046-64eba0b0fb55" />
<img width="738" height="372" alt="Image" src="https://github.com/user-attachments/assets/cd767efd-52e4-4f10-89f4-4ac177fc9bf7" />

If you only have a data in the `Value` column and not in the `Shared Value` column, it will not be exported. The variable also won't be seen in the cloud based features like Monitors.
