### ISSUE TITLE
Backslashes are converted to forwardslash when undesired

### ISSUE THREAD

**Issue by jscripts** [a85/POSTMan-Chrome-Extension#8422]
**Describe the bug**
When attempting to send a Backslash character \ as part of a parameter Postman converts it to a forward slash, even when encoded as %5c.

**To Reproduce**
1. Attempt to send a GET request to an endpoint in the form of {baseURI}/stringWith\character
Alternate:
1. Type the GET request URL in the navigation bar, making sure to include a backslash. Then attempt to add a parameter using the Params tab - the backslash turns into a foward slash

**Expected behavior**
I expect Postman not to convert my request into {baseURI}/stringwith/character and instead send it as parameter

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/64613652/80757449-2bd81b80-8b02-11ea-9ba3-e5698abb6a78.png)
![image](https://user-images.githubusercontent.com/64613652/80757487-3e525500-8b02-11ea-8b6f-16e69ba034a4.png)

**App information (please complete the following information):**
 - App Type - .NET
 - Postman Version 7.23.0
 - OS: Windows 10

**Additional context**
This only occurs when attempting to send the route in the format above ({baseURL/resource/45\5423).  It does work correctly when sending the request as {baseURL}/resource?id=54\23

**Comment by vikiCoder** [comment]
Hi @jscripts,

This is intended behavior. Backslashes(`\`) in URL path are always converted to forward slashes(`/`). But backslashes in URL query are kept as it is. Browsers also do the same thing (see below GIF).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16588032/81141479-66bad300-8f8a-11ea-8062-4763d74c4e80.gif)
