### ISSUE TITLE
Enable Javascript in Response Preview

### ISSUE THREAD

**Issue by aslamanver** [a85/POSTMan-Chrome-Extension#8424]
![Screenshot from 2020-05-02 04-42-30](https://user-images.githubusercontent.com/19545844/80848020-5ecbfd80-8c2f-11ea-88ef-5dd5a9a8ecf0.png)

**Comment by kamalaknn** [comment]
Hey, @aslamanver Thanks for writing in. We are tracking this request in #2646. 

I'm closing this as a duplicate. Please follow the original thread for updates.
