### ISSUE TITLE
How to get a nice folder hierarchy?

### ISSUE THREAD

**Issue by JayChandler** [a85/POSTMan-Chrome-Extension#8428]
How do i get this nice orange folders ? I created a folder in my collection but in my documentation it does not look this way? 

![TreeViewFolder](https://user-images.githubusercontent.com/6359575/80969802-76b3a500-8e1a-11ea-9a18-818e9b65b4a3.PNG)

**Comment by arlemi** [comment]
@JayChandler This is the public view, you need to go all the way to publishing your documentation to see the view with the folders. 

See how to in the Learning Center: https://learning.postman.com/docs/postman/api-documentation/publishing-your-docs/#publishing-and-unpublishing

**Comment by JayChandler** [comment]
@arlemi Thx for response. Still unclear why published documentation renders differently then the preview. Why? Some APIs may still be visible  only for internal purposes.

**Comment by arlemi** [comment]
@JayChandler When in preview mode you can edit your documentation inline (inc. folder names) and I'm guessing we're using a different library to allow that which results in a different render.
