### ISSUE TITLE
Release notes has spurious characters in GitHub URLs

### ISSUE THREAD

**Issue by tristandenyer** [a85/POSTMan-Chrome-Extension#8431]
**Describe the bug**
The JSON coming back from the Release Notes endpoint contains spurious characters (escaping?) in the GitHub URLs, causing some web crawlers to see these as 404s on the rendered page.

**To Reproduce**
1. Go to 'view-source:https://www.postman.com/downloads/release-notes/'
2. Search for 'https:\/\/github'

**Expected behavior**
The rest of the URLs coming back are properly formed. All URLs coming back from this endpoint should be properly formed at the source as `https://github.com/*`

**Screenshots**
<img width="1055" alt="Screen Shot 2020-05-04 at 9 42 21 AM" src="https://user-images.githubusercontent.com/4358288/80991082-57058800-8dec-11ea-9c6d-06ac35e699d5.png">
As seen by web crawler:
<img width="983" alt="Screen Shot 2020-05-04 at 9 33 00 AM" src="https://user-images.githubusercontent.com/4358288/80991104-61278680-8dec-11ea-85f1-5e07bdc0032b.png">

**App information (please complete the following information):**
 - n/a (not in app, specifically)

**Additional context**

**Comment by numaanashraf** [comment]
This has been resolved. Closing.
