### ISSUE TITLE
Save collection runner order

### ISSUE THREAD

**Issue by caedmonm** [a85/POSTMan-Chrome-Extension#8433]
I have an API with 50 or so requests, organised into folders. When I go to run tests on them all in the Collection Runner I have to spend a good few minutes re-ordering them to prevent errors. I'd love to be able to save the order without having to get rid of my folder structure.

**Comment by matt-ball** [comment]
One thing you can do is look at the "Recent runs" section (right-hand pane) once you open the Collection Runner. Picking any of these runs from the list allows you to identify how the requests ran and you can execute the same sequence by hitting "Retry". Next to that, you can also export the results (and therefore the order), to be able to import the sequence and "Retry" again at any time.

**Comment by caedmonm** [comment]
Thanks @matt-ball I'm not sure how's I'd missed the recent runs, that's a good solution for me.

**Comment by michael-camilo** [comment]
Can't we name and save the runners? I run requests isolated and also together but calling endpoints in different orders to test more than one feature in the same collection, so creating it all again, or searching among the runners in the history takes a lot of time...

**Comment by sciamano89** [comment]
Yeah, I agree, and I can't believe this is not a feature already. Exporting and re-importing the collection runs don't behave the same at all, as they lose the entire customization: after importing them, clicking "Run Again" loses the custom order of the requests; also, it runs them all, completely ignoring the fact that I have disabled some requests. And clicking "New" just opens up the default settings (all requests are selected and in their default order). Basically, importing the Collection Run is completely useless.

**Comment by caedmonm** [comment]
I've reopened as I'm clearly not alone in wanting this, "Recent runs" helped a little but it's far from a perfect solution.

**Comment by sciamano89** [comment]
That's the thing though, for me it's not working at all when re-importing the runs (basically the runner settings get completely reset the moment I import them). It only works if I use the "Recent runs" as you've mentioned, but I don't want to keep browsing through my history to dig up the right set of tests. Curious, do they still work if you restart the application? My gut tells me that the app caches the runner settings, and they're not carried over to the json export, so I'm curious if they're carried over app restarts

**Comment by Paul-Schroeder** [comment]
This would be a nice feature to have - please add my vote to this request!

**Comment by jparram** [comment]
This would be amazing to have.  I have currently defined different collections for each scenario I want to test... this is cumbersome, and it would be amazing to define test run scenarios built off the collection, and not have to reconfigure them for each run.

**Comment by FreeFlight-Code** [comment]
Also would love to see this!

**Comment by thmasker** [comment]
In my opinion, this feature is a must

**Comment by markdsearle** [comment]
Yup agreed.

**Comment by tmcentee** [comment]
This isn't the most ideal solution but I just resolved this same issue for myself by manually ordering the requests within the collection folders. That way, when I go to run a collection's tests, they're already in the order I want. We also leverage local variables to persist generated IDs along the way (for basic CRUD flow testing).

Caveat: We have separate collections for pure API tests versus normal day-to-day one off collection requests.

**Comment by 8x8-lfairweather** [comment]
I'm also hoping this is in the pipeline! 

Manually ordering the requests inside the collection is fine if that collection only has a small group of similar requests.... but it can get a bit messy when you want to split those requests into subfolders (for medium-large collections with sub-context). 

A feature that allows you to save runner order makes sense and is the most intuitive! I also think it would be widely used (in my opinion).

**Comment by JakobStadlhuber** [comment]
Push

**Comment by Mwahahaha** [comment]
Please add my vote to this feature request!

**Comment by Coding-Means-Always-Learning** [comment]
We would like this feature as well. Appreciate collection is running all the requests within a folder. However when we allow the option to check / select certain requests it is will be helpful for Postman to remember that setting unless it is changed again by the user. 
This allows us to run the collection with same setting in future

I appreciate there is also an option to do this through history however it is not neat when we have several collection folders and trying to sort and remember what is the last updated setting on it.

**Comment by malvikach** [comment]
@Coding-Means-Always-Learning Thanks for your feedback.

I definitely understand how it might be confusing to get this achieved using history if you are running different settings. 

However, I would love to understand your use case better. How do you utilize the setting and what use cases does it enable you with? We are looking at improving the runner experience and your feedback will definitely help us a lot.  
Let me know if you would be up for a short call sometime this week to talk about it. 

Please drop me a note at malvika.chaudhary@postman.com if you are interested and I will coordinate some time to speak.

**Comment by caedmonm** [comment]
Hi @malvikach I've emailed you with our use case but to summarise here:

I'd like to be able to save multiple runs to test different things, for example I might want to test all the calls required to get a new user setup, or for them to perform a series of tasks.

**Comment by malvikach** [comment]
@caedmonm thanks for your note. I am trying to understand if you have thought about creating different collections to achieve the above test scenarios capability. Let me know if this makes sense. 

Marking @matt-ball to also look into this and provide his thoughts. 

As mentioned over email, it will help if we can do a  quick discussion on this to understand your use case.

**Comment by caedmonm** [comment]
@malvikach creating new collections might work, although it would also mean we'd have to keep them all updated every time we add a new request. It doesn't seem like an ideal solution - but maybe a workaround. Just seen your email - I'll get back to you about a call. Thanks :)

**Comment by malvikach** [comment]
I see your point! let's build up on this when we talk.
Cheers!

**Comment by marcin-backbase** [comment]
Push! Just stumbled upon this discussion when searching for this feature! It would support reusability much, as saving different test scenarios for various calls order of same APIs as separate collections is non-maintainable on larger scale.

**Comment by malvikach** [comment]
@marcin-backbase Thanks for the feedback. We have taken note of this feature request to enable reusability. I will update this thread when we start looking at this. 
Thanks

**Comment by richardholroyd** [comment]
+1 for this feature - also came here looking for the same thing. Reproducing collection runs that require a small subset of requests from large/complex collections is pretty painful, this would be a big help.

@marcin-backbase - hi from another Backbaser :)

**Comment by swdpcomputing** [comment]
+1 In fact, the lack of this feature isa what's stopping me from using Postman fully. It's currently a useful reference tool, but the functionality to define and save runs is a must to use it seriously. My preference would be in json format. Something like:

`
"collectionRuns": {
    "firstRun": {
      "actions": [
        {
          "instruction": "setCollectionVariable",
          "variable": "var1",
          "newValue": "foo"
        },
        {
          "instruction": "runQuery",
          "queryName": "getUserWithId"
        }
      ]
    }
  },
`

**Comment by davehouser1** [comment]
Can someone tell me how to get to "recent runs"? I do not see this at all in Linux 9.31.13-ui-220927-1450.

**UPDATE:** I figured it out how to check previous runs you did. 
To clarify for anyone else that could not find the "recent runs" section in Postman, that's because it does not exist. There is no "recent runs" button or section. 
However you can find previous runs you did by going to "History" on the left hand menu, then manually scroll to find a previous run, and select it for it to load.
Unfortunately this process has a two problems:
- The history does not give descriptions of which runs are which. Therefore you will need to select each one, and select "New Run" to check the order. 
- I have found no way to export he history, so there is no way to share this manually with peers or do backups. 

There needs to be a way to save the order of runs. This order needs to be included in exports of collections too. Or at the very least, when selecting "Run Test" make postman remember and use the previous run order used every time.

**Comment by sbettwieser** [comment]
Can't believe this hasn't been added as a feature for the past few years. You'd think if you had customizable repeatable request runners, you'd also add a way to save/load them. Why did they add Flows before this? You can't even edit variables in them.

**Comment by Narviath** [comment]
Hello,

I'm sorry to recomment but, the "run again" feature is not what we need, we want a real save and/or export feature for runner configuration and reorganisation of request.

If you use a lot postman your "recents run" section will be flooded and it's hard to find what you want.

**Comment by malvikach** [comment]
Hi All 👋 

I have few updates to share with the folks who are interested in running collections with different run orders and save them for future use:

1. We recently introduced a 'Runs' tab on collections which lists all your collection runs (from Runner and Postman CLI) along with some metrics like no. of tests passed/failed etc 
<img width="1002" alt="runs" src="https://user-images.githubusercontent.com/89449769/203740354-5a0009af-2561-4619-9ad4-bf536b471e24.png">

This can help you access your recent runs for a collection faster as compared to using history. 

2. We recently introduced the ability to 'Schedule Collection Runs' to run at specified intervals/frequencies such as weekly 
or daily (even hourly or every few mins). This also supports the ability to save the run orders along with the schedule configuration. I thought this might be something you might be interested to try and see if it solves your use case while also automating these runs. You can read more on our [blog](https://blog.postman.com/automate-your-api-testing-by-scheduling-your-collection-runs-on-postman/)
![Custom order 1](https://user-images.githubusercontent.com/89449769/203742944-f471bf59-7b2b-44c7-a2b8-f727f230e9e1.gif)

3. You can also use Postman CLI to run requests in a certain order by specifying the order using -i command option:
Example: `postman collection run <collection_uid> -i <request1> -i <request5> -i <request3>`
Postman will also help you generate the command so you don't have to spend a lot of time on this:


https://user-images.githubusercontent.com/89449769/203749019-2b6c2316-6a85-4cad-9928-80fe3753a856.mov


 Read more about this on our [learning center](https://learning.postman.com/docs/postman-cli/postman-cli-run-collection/#running-a-collection-in-a-specific-order)

I understand this might still not completely solve the underlying problem where you want to save the run order and run them manually at any point in time using Collection Runner, but these are a few steps we have taken in this direction. 

I would love to talk about this with you. Specifically am looking to get some understanding of your workflow about new requests getting added to the underlying collection (where you want to use saved run orders) or requests that are referenced in your order but are removed from the collection. Please drop me a note on malvika.chaudhary@postman.com or feel free to setup time using my [calendly](https://calendly.com/malvika-chaudhary/v10-feedback?month=2022-11). 

Cheers!
Malvika

**Comment by jackerman88** [comment]
Another +1 to this request.

In my situation, I'm using postman to run integration tests after deployment of an ASP.NET server. I'd like to be able to organize the requests in a folder for each controller, but I need to be able to run some requests before others even though they're in different controllers.

**Comment by Bilboramix** [comment]
Hello @malvikach , is the feature is still in Beta ?
Will it be available in offline client ?

**Comment by malvikach** [comment]
@Bilboramix We haven't released a solution for 'saving runner order'. However, to save the runner order, we must sync/store it in Postman Cloud - which implies that this cannot be made available in the offline client.

**Comment by Bilboramix** [comment]
@malvikach Oh that's sad to read this and a bit unfair :(
I mean this save could be written on the local machine like the collection saves, so it's not that you can't : You don't want to do it.
Imo the cloud should be an optional pick...

But well, i'm not postman team and i see that this software is evolving to a SaaS solution, leaving slowly offline client...

**Comment by MadsFSorensen** [comment]
+1

**Comment by vestbroyek** [comment]
+1

**Comment by malvikach** [comment]
Hi All, @caedmonm ,

We have added the functionality of saving the runner orders for past runs. This means even if you restart app or log in via a different device- the order of your runs is saved in the history. It also allows you to access the run orders used by your team members. 

You can access a past run from Collection -> Runs -> Functional and open a past report as shown below to view and re-run the same order:

https://github.com/postmanlabs/postman-app-support/assets/89449769/cf31ed64-371a-41e8-ba3d-c633d9f8aa4e


Note that in the above I had a customized run order and the same was reflected in the past run and was used to "Re-run" the same order of collection. 

We hope this helps you be more productive while using Collection Runner. If you have any further feedback for us on this, we would love to hear from you!

Cheers!
Malvika
