### ISSUE TITLE
Download link for Linux is missing on Postman website

### ISSUE THREAD

**Issue by cedafter** [a85/POSTMan-Chrome-Extension#8435]
There's no download link displayed and no auto download when I go to the following link:
https://www.postman.com/downloads/

From Google cache the download link should be :
https://dl.pstmn.io/download/latest/linux64

Browser: Firefox
OS: Linux

![1](https://user-images.githubusercontent.com/2945509/81022009-d33fb000-8e6c-11ea-9ba5-11f49280cc87.png)

**Comment by preethammavin** [comment]
@zaraced thanks for reporting this, we are getting this fixed Asap.

**Comment by Ryan-McBride** [comment]
I've pushed a fix for this to production and it is working in my VM, both in 64 bit ubuntu and  32bit fedora. Thanks again for letting us know about this.

**Comment by cedafter** [comment]
Thank you for your quick reaction on this. I'm closing this issue since I've just checked and it's fixed now. Sorry for late feedback.

![D7CaOVEWkAA0tVL](https://user-images.githubusercontent.com/2945509/81420521-5eac9000-9150-11ea-8bd5-ae1e9db27054.jpeg)
