### ISSUE TITLE
App taking too much time to open after an update

### ISSUE THREAD

**Issue by AnvarNazar** [a85/POSTMan-Chrome-Extension#8436]
**Describe the bug**
After I click update the loading screen saying "Preparing your workspace this will take a few minutes" stays for too long

**To Reproduce**
1. Go to Settings
2. Click on 'An update has downloaded, restart to continue'

**Expected behavior**
Open the app as soon as possible after updation

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.x
 - OS: Ubuntu 18.04 Bionic Beaver

**Additional context**
It successfully launch the app after I killed all the postman process and select the app again. It is not taking minutes to prepare work spaces then

**Comment by kamalaknn** [comment]
@AnvarNazar We have removed the intermediary loading screen and made many performance improvements to the desktop app recently. 

Do try out the latest version and let us know if you are still seeing any issues.
