### ISSUE TITLE
Trouble accessing request body members

### ISSUE THREAD

**Issue by b-wils** [a85/POSTMan-Chrome-Extension#8442]
**Describe the bug**
I am unable to access the values of urlencoded fields from the pre-request script. Logs reveal the urlencoded object, but when I attempt to access values I get undefined.

**To Reproduce**

1. Start a request in PostMan
2. Add a urlencoded body
3. Attempt to log urlencoded body `console.log(pm.request.body.urlencoded[0])`
4. Prints as undefined in the console

**Expected behavior**

I am able to access values of the urlencoded request body

**Screenshots**

![image](https://user-images.githubusercontent.com/1399576/81120610-b483fc80-8ef2-11ea-800e-30f91ae69449.png)

**App information (please complete the following information):**
 - Postman 7.23

**Additional context**
I've tried a few variations of this using the field key as well but couldn't get it to work.

**Comment by DannyDainton** [comment]
Hey @b-wils,

I've found that either of these ways will help you to access that data from the request:

```
console.log(pm.request.body.urlencoded.toObject().username)

console.log(pm.request.body.urlencoded.members[0].value)
```

![Screenshot 2020-05-06 at 10 04 02](https://user-images.githubusercontent.com/17089546/81159524-f3f92a00-8f80-11ea-8b82-f140a4a67b7b.png)

**Comment by b-wils** [comment]
That works, thanks @DannyDainton !!

I'm curious, are there docs anywhere on this?

**Comment by arlemi** [comment]
@b-wils You can find our SDK docs online, admittedly they are not the easiest to find but they are there. 😅 

If you go to the [RequestBody page](https://www.postmanlabs.com/postman-collection/RequestBody.html) and scroll down to `urlencode`, you'll see that it returns a [PropertyList instance](https://www.postmanlabs.com/postman-collection/PropertyList.html).

You can use `has()` to check whether an item exists in the `x-www-form-urlencoded` parameters, e.g.
```console.log(pm.request.body.urlencoded.has('key'))```
or you can display the first parameter using `idx()`, e.g.
```console.log(pm.request.body.urlencoded.idx(0))```

I'll go ahead and close the issue, feel free to reopen it if this doesn't solve your problem.
