### ISSUE TITLE
Add search facility in environment variable window. This will be useful, when having 50+ env variables

### ISSUE THREAD

**Issue by rb610** [a85/POSTMan-Chrome-Extension#8443]
Add search facility in environment variable window. This will be useful, when having 50+ env variables

currently it is difficult to find particular env variable.

**Comment by giridharvc7** [comment]
Tracking this a duplicate to #5342

**Comment by vedkribhu** [comment]
In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback.
![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219374983-1f66d6cb-4f5e-4c39-9fe5-7c5b2998c9b5.png)
We are also working on adding sort functionality available in the manage variables table which should be out next month.
