### ISSUE TITLE
Extend limit for reviewers

### ISSUE THREAD

**Issue by Etnic** [a85/POSTMan-Chrome-Extension#8445]
Now it is possible for pull request add maximum of 3 reviewers. I am working in a team of 10 people and we would like to start using pull requests from postman. Could you extend this option so we can add all members from the team to join the review?

Also approve button will be great so we can see that reviewer who did review are okay with changes and after that if 2 or more people approve PR will be merged.

**Comment by ankit-m** [comment]
Hi @Etnic,

Thank you for creating this ticket. We will increase the limit for the number of reviewers very soon. I will update the thread once the change is out on production.

**Comment by Etnic** [comment]
Hello,

thanks for the update. It is great news. Thanks a lot.

S pozdravom,

Martin Kubus

kontakt :  +421 911 160 385
                kubus.martin@gmail.com


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ankit-m** [comment]
We have extended the maximum number of reviewers to 50.
