### ISSUE TITLE
I need a solution on accessing the filename from postman runner in pre-req.

### ISSUE THREAD

**Issue by Agastyabisht123** [a85/POSTMan-Chrome-Extension#8446]
How can I set the file name as environment variable which I have selected in Runner?
Is their any way I can print the file name which I have selected in runner?

**Comment by shamasis** [comment]
What file name? File name of the iteration data?

**Comment by Agastyabisht123** [comment]
Yes, I need to set the iteration data file name as environment variable. Any idea how can I set that?

**Comment by cyrielle-hada** [comment]
Closing as it's a duplicate from this issue - https://github.com/postmanlabs/postman-app-support/issues/8450. I replied there. :)
