### ISSUE TITLE
pm.expect not working when there are - in attribute name

### ISSUE THREAD

**Issue by bagrip** [a85/POSTMan-Chrome-Extension#8449]
pm. expect doesnt recognize attribute name if it contains dash like **foo-bar**, error bar is undefined.

pm.expect(category[0].expression.foo-**bar**-expression)

ReferenceError: **bar** is not defined

**Comment by DannyDainton** [comment]
Hey @bagrip, 

You would need to use bracket notation and wrap the key in quotes, to reference properties with names like that one:

`pm.expect(category[0].expression.['foo-bar-expression'])`

These types of questions might be better answered over on our community site. 😁

https://community.postman.com/

**Comment by bagrip** [comment]
@DannyDainton  Actually I tried this before, getting error and that is why I reported it. Screenshot attached

![image](https://user-images.githubusercontent.com/42482742/81427637-ec1bc000-910f-11ea-881a-ff21a0d899c2.png)

**Comment by DannyDainton** [comment]
Its more than likely the extra dot I added. 😬 

`pm.expect(category[0].expression['foo-bar-expression'])`

This is only one part of the statement though - that would need additional information on the end to know _what_ to expect. For example `.to.be.a('string')`

Have you already stored the response using `pm.response.json()`?

**Comment by bagrip** [comment]
It working fine now, just removed dot as suggested
Thank you @DannyDainton
