### ISSUE TITLE
To be able to access the data filename in pre-request script or test script.

### ISSUE THREAD

**Issue by Agastyabisht123** [a85/POSTMan-Chrome-Extension#8450]
I was trying set the data filename as a environment variable which I selected in collection runner. I checked the possibilities in pm.iterationData object but I do not see any option. Is it possible to access the data file name? If not then, can it be added as a new feature?

**Comment by cyrielle-hada** [comment]
There isn't a Sandbox method for accessing file name from the Postman app. However, if there is a unique identifier in the input JSON, you could pull that value into the output file name. For example, for the following JSON file:

```
[
    {
      "filename":"file_123.json",
      "property1":"abc",
      "property2":"def"
    },
    {
      "filename":"file_123.json",
      "property1":"ghi",
      "property2":"jkl"
    }
]

```

You can use `pm.iterationData.get("filename")` to grab the filename property in each iteration.

If you only want to include filename in the first index of your array, but still need the filename accessible throughout the collection run, you could do something like the following in your script:

`if(pm.iterationData.has("filename")){pm.variables.set("filename",pm.iterationData.get("filename"))}`

This will set a local variable with the filename. Then just use pm.variables.get("filename") wherever it is needed in the rest of the run.
