### ISSUE TITLE
Postman application GUI renders improperly in one monitor but not the other

### ISSUE THREAD

**Issue by thejorro** [a85/POSTMan-Chrome-Extension#8452]
**Describe the bug**
Postman application GUI renders improperly in one monitor but not the other.

**To Reproduce**
Happens passively, between restarts and reinstallations.

**Expected behavior**
Postman application should not have rendering issues in either monitor.

**Screenshots**
Monitor 1 is the problem display.

Monitor 1:
![PostmanMonitor1](https://user-images.githubusercontent.com/59811974/81436357-5eec6180-9137-11ea-8d19-108d1103262f.png)

Monitor 2:
![PostmanMonitor2](https://user-images.githubusercontent.com/59811974/81436360-5f84f800-9137-11ea-8f32-d5398f7e56b9.png)

**App information (please complete the following information):**
 - Postman application (Windows)
 - Version 7.23.0
 - OS: Windows 10 10.0.18363

**Additional context**
Both monitors are configured the same: 1920 x 1080, 100% DPI scaling. One is 60Hz (DisplayPort), one is 144Hz (DVI-D). 

If I drag the Postman app window between monitors, the graphical artifact goes away as soon as the window is mostly in Monitor 2. 

Nvidia Graphics driver: 445.87

**Comment by numaanashraf** [comment]
@thejorro Could you try out our early access 'Canary' channel - https://www.postman.com/downloads/canary and and let us know if you are facing the same issue in Canary build as well?

**Comment by thejorro** [comment]
Thanks @numaanashraf, looks like it works as expected with the Canary version, no graphical issues present.

**Comment by numaanashraf** [comment]
Glad to hear that @thejorro. The same fix should land on our stable app soon.

**Comment by twitharshil** [comment]
Hi @thejorro 
We’ve pushed the updates in our stable app v7.25.1 that should fix this issue 🎉. 
Feel free to reopen the issue if you are still facing this problem on Postman v7.25.1 onwards.
