### ISSUE TITLE
Collections only support one tagged version

### ISSUE THREAD

**Issue by dvgica** [a85/POSTMan-Chrome-Extension#8454]
**Describe the bug**

The docs [here](https://learning.postman.com/docs/postman/design-and-develop-apis/versioning-an-api/) show that you can add new version tags to a collection. But it seems you can only have one tag. There is no option to "Add Version Tag", you have to remove the existing tag before creating a new one.

**To Reproduce**
1. Create an API
1. Link it to a Collection with docs
1. Create a tag in the Collection to your API version
1. Make a new API version
4. Attempt to create a new tag in the associated Collection

**Expected behavior**
It should allow you to create a new tag.

**Screenshots**
![Screen Shot 2020-05-08 at 4 58 34 PM](https://user-images.githubusercontent.com/947530/81449000-53a43080-914d-11ea-9fdf-a12abb472e53.png)

**App information (please complete the following information):**
 - Native app
 - 7.23.0
 - Both Linux and Mac

**Additional context**
On the Team plan.

**Comment by preethammavin** [comment]
@DWvanGeest as from the screenshot I can see there is only one changelog, if you have multiple API versions that are defined you can attach those versions to the collection changelog, but one tag can be applied to one changelog only at the moment. 
I would love to hear your workflow to better understand your use case here.
