### ISSUE TITLE
Cannot convert Swagger 2.0 file

### ISSUE THREAD

**Issue by richbraman** [a85/POSTMan-Chrome-Extension#8457]
**Describe the bug**
Cannot convert file
https://sandbox.dpc.cms.gov/api/swagger.json

**To Reproduce**
trying to convert schema to a collection
Try to convert in Postman and it says it cannot

**Expected behavior**
I expected it to convert

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

PM v.7.23

**Additional context**
Let me know why it won't convert

**Comment by ivan-nenov** [comment]
@richbraman I am having the same issue. A workaround is to replace "swagger" with "openapi" on line 2 of your json.

**Comment by VShingala** [comment]
@richbraman @ivan-nenov Thanks for raising the issue. We have identified the issue and we'll update this thread and associated [community thread](https://community.postman.com/t/cannot-import-swagger-2-0-file-anymore-it-was-working-before-updating-to-7-2-2/6545) with more information.

**Comment by arlemi** [comment]
We had to delay the release of the app, I'm reopening this issue for now and will close it again once 7.35 is widely available. 🙂
