### ISSUE TITLE
Background Internet data usage

### ISSUE THREAD

**Issue by umangbista2** [a85/POSTMan-Chrome-Extension#8458]
Each time I app my desktop Postman app on Mac, it download 150MB of data in the background, even though I have automatic updates turned off in the app preferences.
What data is it downloading? 
Asking because for Cellphone Data users, it's a bit expensive process.

**Comment by kamalaknn** [comment]
Hey @umangbista2 

Are you signed in with an account on Postman? If yes, are you part of a Team where other contributors work on the same workspace?

Also, it is worth noting that the app preference only disables major updates. Minor patches could be updated.

**Comment by umangbista2** [comment]
I am logged in and working alone in project.  I partly was able to understand that it might be minor patches. 
But my concern is, it is happening quite often like 1 out of 3 times. 
TBH, it consumes 10% of my data plan. Quite annoying. :/

**Comment by jviotti** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9089
