### ISSUE TITLE
Automatic theme based on the Windows theme

### ISSUE THREAD

**Issue by bothyculture** [a85/POSTMan-Chrome-Extension#8459]
I like the mac OS 'Auto Theme' where I get a light theme in daylight and dark theme in the evening. 

I would also like it if all my apps on Windows followed the OS theme so I don't have to change them all myself. Please introduce and 'auto' theme that will respect my setting on Windows.

**Comment by tduek** [comment]
+1, please implement! I switch the theme in the Postman app manually every day when macOS switches automatically (mine auto switches to dark at night and light during the day). Please enable an option for it to follow the system. Most other apps I use already do this. We're one of the only ones that don't.

**Comment by bean5** [comment]
Both version 7 and 8 have a default that is used until the user's settings are loaded. Version 7 was far less harsh on the eyes. I think it used a tan/beige. Neither seem to have the ability to default to dark theme until loading is complete nor defaulting to last used theme until finished starting. That would be nice to have.

**Comment by aharbavets** [comment]
Absoultely agree, it's very annoying to switch theme manually every day at least 2 times.

Also on Windows and macOS it can be implemented pretty simply:

Windows:
-----------
1. Listen for the WMSettingChange event
2. Check `message.section == "ImmersiveColorSet"`
3. If it's true, then set theme according to the value `AppsUseLightTheme` in the Windows registry at the path `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\`

macOS
--------
1. Subscribe to the `kAppleInterfaceThemeChangedNotification` event using DistributedNotificationCenter
2. Get the current theme (in Swift): 
`let appearanceDescription = NSApplication.shared.effectiveAppearance.debugDescription.lowercased()`
3. if `appearanceDescription.contains("dark")` then set dark theme, else set light theme

Sample app: https://github.com/ruiaureliano/macOS-Appearance

JavaScript - works on macOS, Windows and in Firefox on Linux (later could be supported in other JS engines)
=================================================================
```
window.matchMedia("(prefers-color-scheme: dark)").addListener(
    e => {
        const darkMode = matchMedia('(prefers-color-scheme: dark)').matches;
        // switch theme here
    }
); 
```

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5817
