### ISSUE TITLE
Postman Console stopped showing request and responses

### ISSUE THREAD

**Issue by vlundsteen** [a85/POSTMan-Chrome-Extension#8460]
**Describe the bug**
I have been using Postman for about a year without any problems. Suddenly a few weeks ago, Postman Console stopped showing request and responses, no matter what requests I try. Output from console.log() still shows up fine. I have upgraded, uninstalled/reinstalled - no change.
Is there some setting on my PC that disables showing of requests/responses in console?

**To Reproduce**
Send any request - e.g. GET postman-echo.com/get

**Expected behavior**
Expected console to show "GET http://postman-echo.com/get" wth "fold-out" option to inspect request/response:
![image](https://user-images.githubusercontent.com/8932648/81500521-fdf99080-92d2-11ea-922b-cb15e291d58c.png)

**Actual behavior**
Nothing is shown in console:
![image](https://user-images.githubusercontent.com/8932648/81500695-2f269080-92d4-11ea-9ae4-667a91ebe431.png)

**App information (please complete the following information):**
 - Native App
 - Postman for Windows 10 version 7.24.0

**Additional context**
In PostmanCanary installed on same PC, console works OK.

**Comment by DannyDainton** [comment]
Hey @vlundsteen,

It looks like you have the `Hide Network` box checked in the second image.

**Comment by shamasis** [comment]
Seems like this issue is safe to be marked closed. :-) I am happy to reopen if the problem persists even after unchecking "Hide Network"
