### ISSUE TITLE
Accept header on imported OpenAPI 3.0 Specs

### ISSUE THREAD

**Issue by liamkeily** [a85/POSTMan-Chrome-Extension#8461]
When an OpenAPI spec is imported into Postman the Accept header is not set. 

This provides a bad JSON Api experience because some backends (e.g. [Laravel](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Exceptions/Handler.php#L208)) will return html responses if no `Accept: application/json` header is sent. 

It would be nice if Postman could look at the content type of the defined responses in the spec and set the appropriate header. This is how it works in [Swagger Editor](https://editor.swagger.io/) (see the "Try It Out" feature)

Alternatively a way to define this globally for a collection (like auth) would be less tedious than having to set it manually for each endpoint every time a new spec is imported.

**Comment by shreys7** [comment]
@liamkeily I tried the following OpenAPI schema import in Postman version 7.24.0 and was able to import the spec successfully with `Accept` header present. Version 7.24.0 includes support for configurable options of OpenAPI, RAML and GraphQL. You would need to set Request parameter generation to `Example` to have the request parameters pick values from examples provided in the schema. Can you try updating your App to the latest version and see if the problem still persists?
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "Swagger PetStore",
    "version": "1.0.0"
  },
  "paths": {
    "/pet": {
      "get": {
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string",
              "example": "application/json "
            }
          }
        ]
      }
    }
  }
}
```
![image](https://user-images.githubusercontent.com/20665864/81529628-df4fd400-937c-11ea-8ce9-768051efdc6c.png)
![image](https://user-images.githubusercontent.com/20665864/81529190-f3470600-937b-11ea-8373-a2a975c49862.png)

**Comment by liamkeily** [comment]
Nice that does seem to do what i need

One slight concern is that the [OpenAPI spec](https://swagger.io/specification/) says `If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.` but it doesn't seem to be causing an issue

**Comment by joelasaxton** [comment]
This solution appears to not work anymore. There no longer seems to be a way to get default Accept request headers into Postman via OpenAPI yaml file.

**Comment by VShingala** [comment]
@joelasaxton As suggested in [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-10), Headers like `Accept`, `Content-Type` and `Authorization` are supposed to be ignored. Due to this, we have changed the default behavior of not including these headers.

You can still include these headers by turning on an option named `Keep Implicit Header` that is accessible during import steps under `Show Advanced Option`.

<img width="945" alt="Screenshot 2022-01-27 at 11 26 59 AM" src="https://user-images.githubusercontent.com/16756296/151304030-559204d8-ae0c-4050-8106-821dd61cb173.png">

**Comment by PeterHindes** [comment]
How are they supposed to be defined if they are not in parameters? I need to document the Accept header in my openapi spec somwhere.

**Comment by VShingala** [comment]
@PeterHindes They are supposed to be your `media-type` from `responses.<code>.content.<media-type>` of related request.

Ref: https://swagger.io/docs/specification/v3_0/describing-parameters/#header-parameters
