### ISSUE TITLE
Feature Request : Add Extra Submit button 

### ISSUE THREAD

**Issue by darkworks** [a85/POSTMan-Chrome-Extension#8462]
Problem 1:  well postman have Send and Save buttons it top  right corner 

![image](https://user-images.githubusercontent.com/12841788/81530668-c0e8d900-937a-11ea-90c8-d92dd8725be3.png)

so imagine if you have big api to test and have a lot of input fileds then each time you press that Send button to see result you have to scroll to the bottom of page because results appear thear.

and then when you make changes to api you have again to scroll to top to press that send button 

Solution : 

just add another send Button copy it bottom of the page 

![image](https://user-images.githubusercontent.com/12841788/81530857-20df7f80-937b-11ea-82b1-95ae3a52161c.png)

 problem 2 : there is another problem is that return data view always reset to default html like when i set it now to json and send request to api it will reset to html , so it will be good if its kept locked base on your choice and its saved as setting so that it change when i want should not auto reset on each request , 
so if user have selected JSON then it will be good if return data is checked that its valid json or not

like 

```
function isJson(item) {
    item = typeof item !== "string"
        ? JSON.stringify(item)
        : item;
    try {
        item = JSON.parse(item);
    } catch (e) {
        return false;
    }
    if (typeof item === "object" && item !== null) {
        return true;
    }
    return false;
}
```

so incase its not valid json or xml you can reset to html but if its valid then user choice should be prefered 

![image](https://user-images.githubusercontent.com/12841788/81531112-8fbcd880-937b-11ea-9684-062ce6337b7d.png)

problem 3 : another small problem is that UI of scroll bar its  gray and very thing , please make it little big and give ti some orange color so that is visible and easily yo grabe beside this there is api post fields x near to it which make it dangerous as sometime i mistakenly click on them 

![image](https://user-images.githubusercontent.com/12841788/81531283-de6a7280-937b-11ea-853d-7ab8e76158ac.png)

**Comment by coditva** [comment]
Hey @darkworks, thanks for the feedback! We're working on some UI changes which will fix some of the issues you mentioned.
Stay tuned! :)

**Comment by coditva** [comment]
We've pushed out a change in the latest version of Postman where you can send a request and see the results without scrolling at all! 🎉 Update to version 7.28.0 and let us know how you feel.

![84889240-77ce2800-b090-11ea-9fd5-7a0bb38a094e](https://user-images.githubusercontent.com/8445768/87385176-15971300-c5bb-11ea-80af-403187077cb5.gif)
