### ISSUE TITLE
Code editor does not highlight certain javascript tokens

### ISSUE THREAD

**Issue by VincentChen1212** [a85/POSTMan-Chrome-Extension#8463]
My UI Become no Color
![2](https://user-images.githubusercontent.com/51907583/81533376-ac1b3e00-9398-11ea-90eb-eca60b6a2c56.png)

It's colorful original
![1](https://user-images.githubusercontent.com/51907583/81533468-d836bf00-9398-11ea-8b1a-c58235b372d8.png)

Where can I setting???

Thanks !!

**Comment by pankajk07** [comment]
@VincentChen1212 In v7.24 we did some changes to the code editor, because of which you might see some differences in terms of syntax highlighting. We are tracking this and will push the changes with better syntax highlighting in one of the upcoming releases.
