### ISSUE TITLE
Postman API Validation doesn't recognize dictionaries

### ISSUE THREAD

**Issue by yoshutch** [a85/POSTMan-Chrome-Extension#8468]
**Describe the bug**
The API validation appears to misinterpret the OpenAPI 3 schema defined in the Postman API when the request body or response body is a dictionary. Postman incorrectly expects the request/response to be a string when it should be a dictionary object.

I want my API to return a dictionary object like:
```json
{
	"someKey1": {
		"prop1": "foo"
	},
        "someOtherKey": {
                "prop1": "bar"
	}
}
```

But after defining it in OpenAPI 3, and after generating a collection based off of the API, the validation returns the issue:
`The response body needs to be of type string, but we found an object instead in Sample response`

**To Reproduce**
1. Go to the API tab in Postman and create a new API (OpenAPI 3.0 for schema type)
2. Change the OpenAPI 3 definition to:
```yaml
openapi: 3.0.0
info:
  version: '1'
  title: Test Postman Bug
paths:
  /test:
    get:
      responses:
        '200':
          description: 'Sample response'
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    prop1:
                      type: string
              example:
                someKey1:
                  prop1: foo
                someOtherKey:
                  prop2: bar
```
3. Click "Generate Collection" button to create a test suite collection
4. Go to the Test tab of the API and click on the "validate" button for the the just created collection
5. The Validation fails, click the "View Issues" to see the issue that says: `The response body needs to be of type string, but we found an object instead in Sample response`

**Expected behavior**
I expect the validation to pass since the provided example should match the defined schema.

**Screenshots**
Screenshot of the validation issue:
![image](https://user-images.githubusercontent.com/6410743/81595823-52a71500-9380-11ea-8ef2-39e6d55fe596.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.24.0
 - OS: Windows 10
```
Postman for Windows
Version 7.24.0
win32 10.0.18362 / x64
```

**Additional context**
I'm not an OpenAPI 3 expert, but from what I researched this is how you define dictionaries according to [this swagger.io post](https://swagger.io/docs/specification/data-models/dictionaries/). So if my OpenAPI 3/JSON schema is not correct, then I apologize and would like to know how to define a dictionary object where Postman can validate it correctly.

**Comment by molteninjabob** [comment]
I'm also seeing this behavior. I'm also seeing it with an array of objects, which, like using a dictionary, uses the `additionalProperties` keyword.

**Comment by VShingala** [comment]
@yoshutch @molteninjabob Thanks for reporting the issue.

We have[ fixed](https://github.com/postmanlabs/openapi-to-postman/pull/294) this issue and the fix should be available on the latest Postman App v7.33. We are closing this issue for now. Feel free to reopen this issue if you have any further problems with this.

**Comment by sciamano89** [comment]
Hello! This is related, but not exactly the same issue. I'm getting the same error message, but I'm sending a request with `x-www-form-urlencoded` body, and setting my field to string, and the actual value I use is this:  `["one", "two", "three"]`. Why can't Postman treat it like a string? My server successfully decodes it with json. My error message is `The request body needs to be of type string, but we found "one,two,three"`. Thanks

**Comment by VShingala** [comment]
@sciamano89 In this case, mentioned warning is suggested due to the validation feature treating the provided value as an array and not a string but schema having type as a string. You can keep type of you field `array`, most of servers follow encoding standards specified [here](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameterStyle) by OpenAPI specification.

For example, try generating a collection for this example OpenAPI spec and send request for generated collection request (Make sure you use `Example` for `Request parameter generation` option under `Show Advanced options` dropdown while generating collection). Out of box, there should be no issues and if you see the response, it will also have the corresponding property as an array.

```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: URL Encoded validation
  license:
    name: MIT
servers:
  - url: https://postman-echo.com
paths:
  /post:
    post:
      tags:
      - pet
      summary: Updates a pet in the store with form data
      operationId: updatePetWithForm
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              properties:
                sampleProp:
                  type: array
                  items:
                    type: string
                  example: ["one", "two", "three"]
              required:
              - sampleProp
      responses:
        '200':
          description: Pet updated.
```

**Comment by sciamano89** [comment]
> You can keep type of you field `array`

I actually had it as an array originally, the only difference is that I used a `ref` to a string component instead of the inline `type: string`, and I didn’t have an example, but an example in my string reference. I believe the warning was exactly the same though, saying it expected a string, which I thought was odd since it was an array
