### ISSUE TITLE
CA Certificate does not work with HTTPS proxy

### ISSUE THREAD

**Issue by helmus** [a85/POSTMan-Chrome-Extension#8469]
**Describe the bug**
Importing a CA Certificate into Postman does not work when an HTTPS proxy is configured.

When using a proxy for HTTPS traffic ( Using HTTP CONNECT ), postman does not allow the target host to use a self-signed certificate, even if the CA certificate has been imported into Postman.
"SSL Certificate Validation" can be disabled as a work around.

**To Reproduce**

- Generate a self-signed CA certificate `ca.pem` and use it to create and sign cetifcate `local.pem` for hostname `local.host` ( or other DNS name that you control )  
- Import `ca.pem` in postman in settings -> CA Certificates.
- Setup an https server with `local.pem` certificate.
- Make an https request to the server from postman to ensure the CA certificate is imported correctly. ( The request should succeed ) 
- Now setup an HTTPS proxy that supports HTTPS CONNECT. ( I used github.com/cssivision/reverseproxy )
- Configure Postman to use this proxy for https ( Settings -> Proxy )
- Make the same request from Postman to the server.
   - The request will fail. ( You have reproduced the bug )
   - Console will show `Error: self signed certificate in certificate chain`
- Disable "SSL Certificate Validation" in General settings
- Make the same request from Postman to the server.
   - The request will succeed. ( you verified the work around )

To validate the proxy setup with curl ( on MacOs )
  - Import the certificate into your login keychain
     - you can also use one of the cli options instead such as `--with-ca-bundle`
  - Point the `https_proxy` environment variable to your proxy. 
  - Make the request trough curl ( it should succeed )

**Expected behavior**

The request should go trough.

**Screenshots**

**App information (please complete the following information):**
 - Postman Version: Version 7.24.0 (7.24.0)
 - OS: MacOS 10.15.4 (19E287)

**Additional context**
My assumption here is that the code that handles proxying is using different TLS settings than the code used for non-proxied requests. And this path must have been overlooked when the CA certificates feature was added.  
I would be willing to send a PR if someone could send me in the right direction in the codebase.

**Comment by mohitranka** [comment]
This has been fixed in the lastest Postman app V7.27. Please upgrade and let us know if it works fine for you!

**Comment by helmus** [comment]
It works! Thank you so much!  😄
