### ISSUE TITLE
Find widget icons not visible in schema editor on Postman Web

### ISSUE THREAD

**Issue by solitarypenman** [a85/POSTMan-Chrome-Extension#8470]
**Describe the bug**
The Find widget icons are not visible in the API Schema Editor on Postman Web.

**To Reproduce**
1. Go to API Schema Editor on Postman Web
2. Click on the find icon on the right extreme of the toolbar.
3. Find widget opens up in the editor without any icons visible.

**Expected behavior**
Icons in the find widget should be visible.

**Screenshots**
<img width="1277" alt="abc" src="https://user-images.githubusercontent.com/52424149/81643816-0e7d4880-9444-11ea-9112-b55d523411f3.PNG">

**App information (please complete the following information):**
 - App Type: Google Chrome
 - Postman Version: N/A
 - OS: macOS Catalina 10.15

**Additional context**
- This bug is appearing in the following browsers too: Firefox, IE 11, Safari etc.

**Comment by DannyDainton** [comment]
Hey @solitarypenman 

Just checked the latest version on the web and I can see the icons. Can you confirm that you're seeing them too? 🙏 

![Screenshot 2020-08-14 at 17 27 36](https://user-images.githubusercontent.com/17089546/90271394-aa5b8d80-de53-11ea-91b1-333e9e3bd2ed.png)
