### ISSUE TITLE
.split on newline character different in Postman vs Newman

### ISSUE THREAD

**Issue by cprice-ping** [a85/POSTMan-Chrome-Extension#8472]
**Describe the bug**
When parsing an environment variable with a newline character, the Postman UI handles the `.split()` function differently than Newman.

In Postman, you use `.split("\\n")` but in Newman you need `.split("\n")`

**To Reproduce**
1. Save multi-line text into your environment 
2. In Postman, add a Pre-Request Script:

```
var parsedText = pm.environment.get("multiLineText").split("\n");
console.log(parsedText);
```
3. This will error
4. Run the call in Newman -- it'll work
5. Replace `("\n")` with `("\\n")`
6. Repeat the test -- it will work in Postman, but not in Newman

**Expected behavior**
The same command should work in both run methods

**App information (please complete the following information):**
 - Newman (5.0.0) Docker container
 - Postman Version [7.24.0]

**Comment by codenirvana** [comment]
@cprice-ping Can you share a scaled-down collection (or steps) which we can use to reproduce this issue?

Are you stringifying the variable (`JSON.stringify`)?

**Comment by cprice-ping** [comment]
Sure -- here's a sample Environment with an example of a string I'm parsing:

```json
{
	"id": "40199d03-d15c-47e4-b502-8b62f98479d1",
	"name": "Solution-Customer360-Advanced",
	"values": [
		{
			"key": "pfBaseURL",
			"value": " https://{{YourPingFedHost}}:9031",
			"enabled": true
		},
		{
			"key": "pingIdSdk",
			"value": "#Auto-Generated from PingOne, downloaded by id=[000000] email=[bogus@pingidentity.com]\n#Thu Jan 09 11:17:59 MST 2020\napi_key=YourAPIKey\ntoken=YourToken\npingidsdk_url=https://sdk.pingid.com/pingid\naccount_id=YourAccountID",
			"enabled": true
		},
		{	"key": "sdkAppId",
			"value": "YourPIDSDKAppID",
			"enabled": true
		},
		{
			"key": "pingCentralHost",
			"value": "https://{{YourPingCentralHost}}",
			"enabled": true
		}
	],
	"_postman_variable_scope": "environment",
	"_postman_exported_at": "2020-02-24T18:49:30.401Z",
	"_postman_exported_using": "Postman/7.18.1"
}
```

And in the Pre-Request script, I have this line:

`var sdkProperties = pm.environment.get("pingIdSdk").split("\n");`

This `.split` works in Newman, but not Postman (you need `.split("\\n")` )

**Comment by codenirvana** [comment]
@cprice-ping I see no issues here... also, tried importing this environment and `.split("\n")` is working fine.

Are you manually entering `\n` (instead of actual newline/enter) while updating the variable in Postman?

**Comment by cprice-ping** [comment]
It's not splitting correctly -- with the `/n` you only get a single element, but with `//n` you get 6.

![image](https://user-images.githubusercontent.com/43251598/81735360-c9f4ab80-9449-11ea-98b6-fedadf00fde8.png)

Here's a collection with a sample call:

```
{
	"info": {
		"_postman_id": "a5b79e9d-dfb2-4ebe-be43-79595d47515f",
		"name": "ScratchPad",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Postman .split() testing",
			"event": [
				{
					"listen": "prerequest",
					"script": {
						"id": "6651354e-371d-41fc-9497-3055d75a4bf2",
						"exec": [
							"// Parse out the {{pingIdSdk}} variables from the PIDSDK properties file in the Environment.",
							"// Postman behaves differently than Newman with this `.split()`",
							"var sdkProperties = pm.environment.get(\"pingIdSdk\").split(\"\\n\");",
							"console.log(sdkProperties);",
							""
						],
						"type": "text/javascript"
					}
				},
				{
					"listen": "test",
					"script": {
						"id": "e67ba09c-e146-42ea-95ed-e07ed1005d35",
						"exec": [
							""
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"auth": {
					"type": "noauth"
				},
				"method": "GET",
				"header": [],
				"url": {
					"raw": "https://postman-echo.com",
					"protocol": "https",
					"host": [
						"postman-echo",
						"com"
					]
				},
				"description": "This is a sample of a problem with the JS `.split()` function"
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}
```

**Comment by codenirvana** [comment]
@cprice-ping That's possible only if literally `\n`s are entered in the variable value.

Please check the attached GIF where I imported your collection and environment...

![GH-8472](https://user-images.githubusercontent.com/4865836/81737451-bc750b00-94b5-11ea-83ad-5224ba18e28a.gif)

**Comment by cprice-ping** [comment]
Ahhh -- the underlying piece is that the Environment normally handles this and splits the `/n` on Import?

I'm just pasting back the value from an Env export - so that's where the extra escape is needed.

**Comment by codenirvana** [comment]
@cprice-ping Yes, the newlines are handled automatically on import.

Pasting `\n` manually doesn't convert it to a new line. You need to manually convert all those `\n`s to the actual newline character.

I hope this solves your issue, closing this issue now. Also, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
