### ISSUE TITLE
`unset` Variable removes initial value

### ISSUE THREAD

**Issue by chaffeqa** [a85/POSTMan-Chrome-Extension#8477]
**Describe the bug**
If you call `pm.<scope>.unset("variableName")` it deletes the variable (including initial value).
In addition, calling `pm.variables.unset("variableName")` means the local run will default to the next higher value of that variable, which means there is no way to "clear" a variable (bearer token for example) in a local script run without deleting it across environment or global.

**Expected behavior**
Have an intuitive way to unset a local/env/global variable (aka: clear it) without persisting the "initial" value across accounts

**App information (please complete the following information):**
 - Native App
 - Version 7.24.0 (7.24.0)
 - OSX 10.15.4 (19E287)

**Additional context**
This mainly shows itself when trying to demo `unauthorized` access errors for an endpoint, where we want to `unset` the default Bearer token (saved to environment or global initials)

**Comment by vvs11** [comment]
@chaffeqa you can use pm.environment.set("variable)key", ""); to unset a variable without deleting it from the environment. Along with this, you can use 'Automatically persist variable values' to choose whether you want to sync the variable or not. Let us know if that solves your use-case.

**Comment by vvs11** [comment]
@chaffeqa closing this for now. Please feel free to re-open this. You can also post your questions on our community here http://community.getpostman.com/ to get a quick response
