### ISSUE TITLE
Duplicating or downloading an environment does not copy values

### ISSUE THREAD

**Issue by tarinidash** [a85/POSTMan-Chrome-Extension#8478]
**Describe the bug**
When hit "duplicate environment" on an environment , a copy is created with on key(properties) but no values.

**To Reproduce**
1. Click on Manage Environment
2. select an environment
3. click on "duplicate environment"
4. Go to the newly copy of environment and double click to open and check the values.
5. repeat steps 3-5 for downloading an environment and check the json file for values.

**Expected behavior**
The new copy of environment should have been exact replica.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.24.0 (7.24.0)]
 - OS: [macOS Catalina 10.15.4]

**Comment by arlemi** [comment]
@tarinidash You need to use the initial value field to make sure the value is being exported/duplicated.

From [our Learning Center](https://learning.postman.com/docs/postman/variables-and-environments/variables/#specifying-variable-detail):
> Initial values are shared when you share a collection or environment. Current values are local and not synced or shared. See sessions in Postman for more on local vs synced variables.

Hope that helps. 😄

**Comment by tarinidash** [comment]
Thank you @arlemi . I should have referred to Learning Center before creating a bug.

**Comment by HagnMarkus** [comment]
Just a thought - even though the ticket has been closed for a long time:I think that copying and synchronizing / sharing are two different things.  I actually already expect to get a duplicate including "current values" when copying. It is still in my area and therefore not yet subject to any security aspect. Too bad, this makes working with environments very cumbersome.
