### ISSUE TITLE
"Couldnt Get any Response" error on changing the Content-Lenght in Request Header

### ISSUE THREAD

**Issue by qabandlab** [a85/POSTMan-Chrome-Extension#8479]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by arlemi** [comment]
@qabandlab If you're facing a bug please open a new issue and fill in the required fields to help us investigate. 

If you have a general question on how to use a specific API, please ask it in our [community forum](https://community.getpostman.com/).
