### ISSUE TITLE
Cannot upload a file using Monitor Collection

### ISSUE THREAD

**Issue by akperiste** [a85/POSTMan-Chrome-Extension#8480]
Hi,
while using the Monitor Collection option, I cannot upload file using a POST request. I get error "Form param ``, file load error: file resolver not supported".
I can easily send this request using the "start collection" button.

I set a working directory as "\AppData\Local\Postman\app-7.24.0\files" and have my file there.
I'm using Postman v7.24.0
Body filetype: form-data
Headers: content-type multipart/form-data; boundary=< calculated when request is sent >

Thanks for help

**Comment by Hugobox** [comment]
👀 I have the same issue

**Comment by moto83** [comment]
Same here

**Comment by rashidablanca** [comment]
Same issue here. Any update on when will this be fixed?

**Comment by ArjunSingh-PM** [comment]
@akperiste Thank you for sharing this issue with us. This is not supported by Monitors as of now, but we will be taking this up as a feature request.

**Comment by batashovp** [comment]
Dear postman, that fix is super necessary

**Comment by coder0028** [comment]
@charlie-postman  is this feature added ? Thanks in advance.

**Comment by charlie-postman** [comment]
@coder0028 Thanks for following it up. The feature is not added (implemented) yet. We'll provide an estimated delivery date soon and update the ticket.

**Comment by arturkuchynski** [comment]
@charlie-postman 
@godfrzero 
@anudeepmedicharla

Are there any updates regarding this issue? Looks like It was postponed for a 3 months without any changes.

**Comment by rashidablanca** [comment]
Hello. Is there an update regarding this please?

**Comment by PaulDMendoza** [comment]
We need this as well. It's kind of crazy this isn't already addressed. 

A lot of our APIs take file uploads and we have defined all our APIs in Postman but now we have learned the monitors don't work. I really want to use Postman to monitor all of our APIs across our various environments (Alpha, Beta, Hotfix, Production) but this is a major blocker for us.

Until this is resolved I have to have a human run the test plans manually on their local Postman instance which isn't ideal. I'd rather have Postman Monitors checking the APIs every 15 minutes or so.

**Comment by charlie-postman** [comment]
I am sorry to follow up on this late. We will probably not have the capacity to pick it up in Q4, 2021. We understand that this capability is critical for many of our customers. However, the team has other priorities to focus on at this point.

**Comment by FBO-Testing** [comment]
Hello, I/we also have this problem. Is there a timetable for the targeted solution?

**Comment by pegasusnotunicorn** [comment]
Is this going to be fixed anytime soon?

**Comment by charlie-postman** [comment]
Sorry that the opportunity is still pending and thanks for the queries. At the moment, we don't have a timeline to get the opportunity addressed due to other priorities.

**Comment by markman641** [comment]
How is this not a thing?
So everyone who needs files in their testing is SOL?
There has to be a way to do this.

**Comment by aladendorf** [comment]
Uploading files is a common case? Please let us know if there is a plan to fix this :)

**Comment by TKnapp8743** [comment]
This seems like this would be a super common use case. My requests require this and as such, I can't use the monitors. Please address soon, ty

**Comment by AlexKalyna** [comment]
It's been 2 two years since this ticket was created. Is there any progress or even hope this feature will be implemented? Without it using Monitor is useless for our company.

**Comment by vinch00** [comment]
+1 Please prioritize this feature

**Comment by Yuri-M-Dias** [comment]
Found this from Google, two years of "wontfix"? Could at least have the decency to document that this is not supported on the UI, so we know to not expect it to work. Much better than to have the monitor directly.

**Comment by godfrzero** [comment]
Hey folks! We haven't picked this up yet but it's on our radar. We've recently added support for data files and extended the monitor timeout from 5 to 15 minutes, so I'll post an ETA for supporting file uploads here as soon as we have one figured out.

> Could at least have the decency to document that this is not supported on the UI, so we know to not expect it to work.

In the meantime, we'll update the documentation to clearly outline the constraints currently in effect.

**Comment by jblalock** [comment]
I don't see anywhere in the docs about this limitation. Guess we'll go back to home-rolled CURL.

**Comment by W3Edd** [comment]
It's been more than two yeas and I don't believe you have not implemented this.
Guess it will take an startup to solve this.

**Comment by jawak** [comment]
+1 Please prioritize this feature

**Comment by tkrajewski89** [comment]
Any update, please?

**Comment by cancan10** [comment]
Any update for this issue ?

**Comment by esma-tsx** [comment]
I hope this feature will be  prioritize too, this is the only missing part that prevents us from using monitor which uploading file is the key to the project

**Comment by shreyash02** [comment]
Slightly off, but related topic: How do you guys collaborate with your teammates on files while running the collections locally? How do you share them and how do you ensure that they put it in the right location on their local file system to get the collection running properly locally?

**Comment by walterholohan** [comment]
Any update on this?

**Comment by AnnOhremenko** [comment]
Hi everyone! I have faced the same issue and found this topic. And I am pretty disappointed that during 2 years!!! you couldn't fix this bug or add it as a feature. 
It is very weird that when I have run the collection by hand - Postman could see the file, but when I have added this collection to the monitor - it can't. I couldn't setup up the automatic monitoring of our service. I am blocked.
And as I could see from the comments above - many people also struggling with this issue. 
Is it possible to give higher priority to this?

**Comment by esma-tsx** [comment]
> Hi everyone! I have faced the same issue and found this topic. And I am pretty disappointed that during 2 years!!! you couldn't fix this bug or add it as a feature.
> It is very weird that when I have run the collection by hand - Postman could see the file, but when I have added this collection to the monitor - it can't. I couldn't setup up the automatic monitoring of our service. I am blocked.
> And as I could see from the comments above - many people also struggling with this issue.
> Is it possible to give higher priority to this?

I feel you, I am having the same problem for now I am using Newman to solve the issue but it would be really nice to use the monitor in postman directly... since it is in the program and it is maintained by postman... I really want to see this feature really soon

**Comment by malvikach** [comment]
@AnnOhremenko @esma-tsx 👋 We understand your pain and we have our eyes on this issue. We will update the thread as and when we have more news to share. 

I might reach out here to validate and share some early mocks with you so I can get your feedback. 

Regards
Malvika

**Comment by paytonmcl** [comment]
@malvikach appreciate you taking this on. Please let us know if you need any additional users to provide feedback :) Our team would greatly benefit from this feature!

**Comment by mark-attridge** [comment]
Please address this issue with your HIGHEST priority.  Monitors need this capability NOW.

Manual test runs for requests with files is not feasible.

Please fix this!

**Comment by pride1995** [comment]
Really need this feature for the KYC register process！

**Comment by prafulkolhe89** [comment]
> > Hi everyone! I have faced the same issue and found this topic. And I am pretty disappointed that during 2 years!!! you couldn't fix this bug or add it as a feature.
> > It is very weird that when I have run the collection by hand - Postman could see the file, but when I have added this collection to the monitor - it can't. I couldn't setup up the automatic monitoring of our service. I am blocked.
> > And as I could see from the comments above - many people also struggling with this issue.
> > Is it possible to give higher priority to this?
> 
> I feel you, I am having the same problem for now I am using Newman to solve the issue but it would be really nice to use the monitor in postman directly... since it is in the program and it is maintained by postman... I really want to see this feature really soon

Can you pls share how has newMan helped u resolve the issue.

**Comment by davidxhive** [comment]
It has now passed 3 years mark and I just stumbled upon this post realizing this feature still isn't supported... :(

**Comment by esma-tsx** [comment]
> > > Hi everyone! I have faced the same issue and found this topic. And I am pretty disappointed that during 2 years!!! you couldn't fix this bug or add it as a feature.
> > > It is very weird that when I have run the collection by hand - Postman could see the file, but when I have added this collection to the monitor - it can't. I couldn't setup up the automatic monitoring of our service. I am blocked.
> > > And as I could see from the comments above - many people also struggling with this issue.
> > > Is it possible to give higher priority to this?
> > 
> > 
> > I feel you, I am having the same problem for now I am using Newman to solve the issue but it would be really nice to use the monitor in postman directly... since it is in the program and it is maintained by postman... I really want to see this feature really soon
> 
> Can you pls share how has newMan helped u resolve the issue.

In order to work with Newman you will need to add the video/binary file as same repository as your Newman will run at and in your Newman command you will add option --working-dir [the binary file relative path]  so it will take the file from there for your uploads  . Some other options are here  https://learning.postman.com/docs/collections/using-newman-cli/newman-options/

**Comment by JasonMDavey** [comment]
I've also had issues with this, and had to implement a horrible workaround - creating custom "dummy" endpoints which simulate a file upload with some pre-baked data, just so we can use them in our Postman monitors.

**Comment by olgakvap** [comment]
Do you have any updates on this issue?

**Comment by malvikach** [comment]
@olgakvap Yes, we have started work on this and we will keep this thread updated with more news on it!

**Comment by esma-tsx** [comment]
That's awesome thanks for the update @malvikach

**Comment by olgakvap** [comment]
> @olgakvap Yes, we have started work on this and we will keep this thread updated with more news on it!

Do you have any news?

**Comment by esma-tsx** [comment]
Any news about this issue ?  @malvikach

**Comment by giridharvc7** [comment]
We released this featured a few months back. You can now upload files to the Postman cloud, these files are accessible across your team, and also in your monitors. 
You can read more about this feature [here](https://blog.postman.com/introducing-file-storage-for-tests-and-requests/)

**Comment by olgakvap** [comment]
Did anyone try it? It didn't work for me

**Comment by mark-attridge** [comment]
> Did anyone try it? It didn't work for me

Yes, it works very well.
