### ISSUE TITLE
Request content type header is not picked automatically when saving example.

### ISSUE THREAD

**Issue by kriss1897** [a85/POSTMan-Chrome-Extension#8482]
**Description**
Request content type is not picked automatically when saving a response as an example.
The content type is header is updated when we select JSON manually in picking content type.

**To Reproduce**
1. Send a request with some request body so that the req headers include a `content-type` header.
2. Save the response as an example. 
3. Check the example request headers to see that the content type of request is not present.
4. When the expected content-type is selected from the request content type dropdown, the header is populated in headers.

**Expected behavior**
When saving a response as an example, the content-type in example request should be automatically set the respective content-type header from the request.

**Screenshots**
[Screen Recording](https://drive.google.com/file/d/1EU8pJQOGaA5mb6hKILKWlx7PJnUtIn5i/view?usp=sharing)

**App information:**
 - App Type: Native APp
 - Postman Version 7.23.0
 - OS: macOS Catalina 10.15.3

**Additional context**
Request body matching fails for mock server requests when the header is not present in saved examples.

**Comment by DannyDainton** [comment]
If the original request has the `content-type` header manually added, rather than the helper adding this to the auto-generated header - This would show in the saved example.

**Comment by apoorvgupta03** [comment]
Hey @kriss1897, you can now `Try` request sending our examples and they will be containing the same headers as the original request. 
If you add any custom header, it will be shown in the examples' header section too. 

https://github.com/postmanlabs/postman-app-support/assets/110587492/d8a51770-f382-42ba-a7e7-2daede40c574
