### ISSUE TITLE
Add Collection location info and name filter option to open request tab

### ISSUE THREAD

**Issue by jeffrimko** [a85/POSTMan-Chrome-Extension#8486]
**Is your feature request related to a problem? Please describe.**
No, this is just a convenience request.

**Describe the solution you'd like**
It would be nice to easily see the Collection location of an open request tab. For example, when hovering over the tab of an open request, it currently only shows the request name, maybe consider adding the Collection name/folder as well. It would also be nice to right click on an open request tab and have the option to update the search filter based on the request name. **UPDATE**: arlemi pointed out that that if the collection/subfolder for a request is expanded, there is currently a sidebar-move feature that will bring the request into focus. It would be nice if this feature would also work with collapsed collections/subfolders, either by automatically expanding them or allowing the user to expand all collections/subfolders (maybe add buttons near the "+ New Collection" button).

**Describe alternatives you've considered**
Currently its possible to manually enter the name of an open request tab into the search filter. **UPDATE**: The sidebar-move feature will work if the collect/subfolder of a request is already expanded.

**Comment by arlemi** [comment]
@jeffrimko Opening the tab should also be moving the collection sidebar to where the request is, is that what you're looking for? 

![findrequest](https://user-images.githubusercontent.com/5029719/82028376-76729f80-968d-11ea-9834-25970c48576e.gif)

**Comment by jeffrimko** [comment]
Okay, I never noticed the sidebar-move feature before, maybe because I often use search filters due to having dozens of collections, that's a nice feature! On my install (Postman 7.24.0 on Windows 10) it will only do the sidebar-move if the collection and any subfolder is already expanded (e.g. if the subfolder or collection containing "Get By Id" was collapsed the sidebar-move would not work in the example GIF), would be kind of nice if it always did the sidebar-move with an auto-expand if possible.

**Comment by jeffrimko** [comment]
Alternatively, it might be nice to have buttons to "expand all collections/subfolders" and "collapse all collections/subfolders" maybe somewhere near the "+ New Collection" button. Then it would be possible to expand everything which would allow the sidebar-move to work properly when clicking on an open request tab.

**Comment by arlemi** [comment]
@jeffrimko Good points. Could you update your first post to reflect these feature requests too? It'll make it easier for us to track later on.

**Comment by eraymond-bt** [comment]
I would also like to see the sidebar reflect the currently selected tab, even if the folders in the sidebar were collapsed. Without this feature, it's time consuming to find and expand the folder where the current tab lives. Are there any updates for this enhancement request? Thank you!

**Comment by giridharvc7** [comment]
This is fixed in app v8, please check and let us know this works for you @jeffrimko 
<img width="857" alt="Screenshot 2021-04-14 at 1 32 39 AM" src="https://user-images.githubusercontent.com/1040583/114613889-82ae1500-9cc1-11eb-81ac-24c57d1b09a0.png">

**Comment by labossieresr** [comment]
Yes  @jeffrimko <https://github.com/jeffrimko>. I confirmed you not only
now display the path to the request (collection, folders and request), when
the tab is clicked on, you actually open the collection and folder(s) and
place me right on the request. Nicely done and thank you!

**Comment by jeffrimko** [comment]
Yeah, I'm on v8.1.0 and it looks great, very clear where the request is located. Thank you for the update!
