### ISSUE TITLE
Version 7.24.0 (7.24.0) on MacOS freezes when hiting a simple REST API

### ISSUE THREAD

**Issue by shubhshukla** [a85/POSTMan-Chrome-Extension#8487]
**Describe the bug**
Trying to get data from a locally running spring boot app. After clicking Send button and getting JSON response it takes approximately 10 seconds. Although time taken by API to respond is only ~150ms.

**Screenshots**
![image](https://user-images.githubusercontent.com/17101288/81987127-b5393300-9656-11ea-98b0-f245c6667b5d.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 7.24.0
 - OS: [e.g. macOS Catalina 10.15.3]

**Comment by codenirvana** [comment]
Can you share a scaled-down collection (or an API endpoint) which we can use to reproduce this issue?

**Comment by shubhshukla** [comment]
As weird as it may sound, tried to record screen to post here, and then postman started behaving correctly.

**Comment by arlemi** [comment]
@shubhshukla Thanks for letting us know, I'll close this issue for now. Do reach out if this happens again!
