### ISSUE TITLE
Request to increase the Github backup integration repo limit

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#8489]
**Is your feature request related to a problem? Please describe.**
When we attempt to create a Github backup, the integration does not list all repositories in the pull-down menu. This is due to the 1000 repo limit we currently have.

**Describe the solution you'd like**
To list out all of the repositories.

**Additional context**
When organizations have more than 2000+ Github Repo - users cannot select target Repo from the postman page.

Previous update: https://github.com/postmanlabs/postman-app-support/issues/7634#issuecomment-604936762

_Filed by Product support_

**Comment by saialekhya-postman** [comment]
@Raj-postman Added an input field where users can enter their `ownerName/repositoryName` if the repository name is not available in dropdown.
This fix is out in production.

**Comment by smalltide** [comment]
This fix my issue, Thanks
