### ISSUE TITLE
I would like to associate my postman tests (written in Javascript) with Azure devops Plans test cases

### ISSUE THREAD

**Issue by Madhusudanpatidar** [a85/POSTMan-Chrome-Extension#8490]
I have Postman api tests that run successfully in azure pipeline, I export results in jUnit format and publish them, the results are displayed properly.
**I would like to associate my postman tests (written in Javascript) with Plans test cases.**

I can't find a precise documentation about this case in general, there is a suggestion here that uses c# https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops

but i am using javascript. Is there a way to solve this ?
sorry for the missed out ticket, i can't say if this is an enhancement or a bug or a feature request

**Comment by vvs11** [comment]
@Madhusudanpatidar Thanks for writing in! Could you post this question on our community http://community.getpostman.com/ to get quick help?

**Comment by JanBorupJakobsen** [comment]
You could check out: 
https://github.com/jbjakobs/Postman/wiki
