### ISSUE TITLE
store response run time and pass to next api uind Newman cli 

### ISSUE THREAD

**Issue by Madhusudanpatidar** [a85/POSTMan-Chrome-Extension#8491]
**Describe the bug**
I have 3 api in the collection
first api >> response have token >> store token from response in **var/global/env**
second api >> use first api **token** as input & generate response **one of the dataid**, same again store dataid in **var/global**
third api >> use the first & second api response **token & data id** as input and getting third api response
So above scenario is working on the postman individually.

**All the above api is only GET request**
I have export collection of above 3 api and as well as environment/globals in the json format

Run collection using newman cli to run postman collection and global variable on command prompt
so its working but first api pass and other 2 api fails, 
bcz api is depends on each other and every time response is new.

So my question is that, how can store run time token and dataid and pass to next one??

i think its clear, so please share response ASAP...thanks team

**Comment by oliveiradep** [comment]
I have the same problem here. Only fixed values ​​in environment variables can be used among different collections.

**Comment by DannyDainton** [comment]
Hey @Madhusudanpatidar 

I'm unable to reproduce the issue given the information you have provided. If this is still an issue on the latest version of the platform, we can look to reopen it again.
