### ISSUE TITLE
Redirects do not show headers in console

### ISSUE THREAD

**Issue by edgreenberg** [a85/POSTMan-Chrome-Extension#8492]
**Describe the bug**
When a 301 redirect is received, the console does not show the full request and response headers. 

**To Reproduce**
Construct and send an http request to a server that returns 301 redirect to https. 

**Expected behavior**
In the console, I expect to see the request and response headers below the network section of the 
http request, just as I do in the following https request.  Instead, I get nothing but the network section.

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
       Native App
 - Postman Version [e.g. 6.0.1]
       "You are up to date! Postman v7.24.0 is the latest version."
 - OS: [e.g. macOS High Sierra 10.13.2]
       Windows 10 Enterprise Version 1909

**Additional context**
The header info is valuable in figuring out what engendered the redirect. It also would have pointed out to me that the HTTP attempt exposes the bearer token. I had to learn that in wireshark.

**Comment by codenirvana** [comment]
**Postman v8.3.0** added support for showing request and response headers for redirects.

<img width="1012" alt="Screenshot 2021-04-26 at 11 13 31 PM" src="https://user-images.githubusercontent.com/4865836/116127159-21d10480-a6e5-11eb-93a7-16a4ace18b51.png">
