### ISSUE TITLE
Dynamically set Null value is not passed 'as is' in json input data.

### ISSUE THREAD

**Issue by SelinMaryK** [a85/POSTMan-Chrome-Extension#8493]
Dynamically set Null value is not passed 'as is' in json input data. Instead when a variable is set as null, empty data is being passed, which creates error in request.

1. In the pre request set value for the required parameter as null
eg: pm.environment.set("abc", null);
2. The null value is correctly set on the quick look variables.

**Expected behavior**
The dynamically set needs to be passed as is what is set.
for eg if abc is set as null, the null value as is must be passed in the request.
pm.environment.set("abc", null);

json input body
{
  "abc" : null
}

**Screenshots**
Environment data
Environment quick look correctly shows null value
![image](https://user-images.githubusercontent.com/55212925/82065571-8e1e4800-96ce-11ea-9c55-dd872b3d6ae9.png)
But on opening the environment file(Manage environment), its empty 
![image](https://user-images.githubusercontent.com/55212925/82065755-cf165c80-96ce-11ea-9504-58bda38e0b2c.png)

Request data
![image](https://user-images.githubusercontent.com/55212925/82065187-12bc9680-96ce-11ea-8725-9d70576aae1c.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version v7.24.0
 - OS: windows 10

**Comment by codenirvana** [comment]
@SelinMaryK Thanks for reporting this, we can reproduce this issue locally.
I will let you know once this is fixed.

**Comment by mohitranka** [comment]
@SelinMaryK This has been fixed in the lastest Postman app V7.27. Please upgrade and let us know if it works fine for you!

**Comment by radszczygiel** [comment]
Yeah it's fixed but after update another thing is broken down
When i set environment variable for ex. pm.environment.set("myVar", "myString"), it's resolving in request body JSON without quotes:
{
   "Var": {{myVar}}
}
is resolving to:
{
   "Var": myString
}
Which is obviously wrong. String variables should be resolved with quotes in JSON bodies and without them in for example URL path

**Comment by codenirvana** [comment]
@asnaebaem That's the expected behavior as it's just string replacement. You have to wrap the variable string in quotes like this:

```json
{
    "Var": "{{myVar}}"
}
```

**Comment by radszczygiel** [comment]
If i do so, then if i assign to my variable null like this pm.environment.set("myVar", null)
i got 
{
    "Var": "null"
}
So when i got values which can be string or null i can't resolve them as "myVar"/null, i have myVar/null or "myVar"/"null" and none of them is ok imo.

**Comment by codenirvana** [comment]
So, to handle a situation like this you have to set the variable using:

```js
pm.environment.set("myVar", JSON.stringify(myVar))
```

and keep the body as:
```text
{
    "Var": {{myVar}}
}
```

**Comment by radszczygiel** [comment]
Ok, so now, what if i have variable i use in both places - JSON body and in another request in collection in URL path - i have to create another variable that stores unquoted value because my url goes like this http://mysite/"myvar".com ? 

Also null in variable value now make url www.mysite.com/getSth/{{id}} looks like www.mysite.com/getSth/null
Big thanks for helping anyway :)

**Comment by codenirvana** [comment]
@asnaebaem I understand your concern and there are multiple workarounds but there's no better way I can think of.

That's why we've seen a lot of users actually building the request body object within the script itself and store it in a variable (say, `responseBody`) as a JSON string. And, keep the request body as simple as `{{responseBody}}`.

You can also reach out to the wider Postman Community (https://community.getpostman.com/) to understand how others have solved this issue.

**Comment by radszczygiel** [comment]
Or just stay with 7.26 when only problem was null thats resolving wrongly ;)

**Comment by awritchie** [comment]
I created an issue around the "{{null}" -> "null" thing: https://github.com/postmanlabs/postman-app-support/issues/8709

**Comment by SelinMaryK** [comment]
Thank you for fixing the issue. The null issue has been fixed. However i find postman crashing very frequently with the latest version. This was not seen much in the previous version.
![image](https://user-images.githubusercontent.com/55212925/86410872-e7146080-bcbb-11ea-95a8-a7f012eb287e.png)
