### ISSUE TITLE
How to delete archived collections

### ISSUE THREAD

**Issue by zzswang** [a85/POSTMan-Chrome-Extension#8497]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/1524745/82109567-ab542480-9769-11ea-9776-a90a930c04a4.png)

I want to delete archived collections. when call from api, it said

```
{
  error: {
    name: 'instanceNotFoundError',
    message: 'The specified item does not exist.',
    details: { item: 'collection', id: '6a509a77-b042-4d2e-81b3-0d2c49f182aa' }
  },
  status: 404
}
```

**Describe the solution you'd like**

Some ui to delete those archived collections.

**Describe alternatives you've considered**

Allow delete collection api to delete those archived ones.

**Comment by cyrielle-hada** [comment]
@zzswang the question of deleting archived collections was addressed multiple times, like here: https://github.com/postmanlabs/postman-app-support/issues/5457.

You should be able to delete the archived collections using the [Postman API](https://docs.api.getpostman.com/). GET [all your Collection IDs](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#3190c896-4216-a0a3-aa38-a041d0c2eb72). Please make sure you're using the collection uid.

Then DELETE them as needed. You'll need to first generate an API key for the Postman API. Then, [DELETE the collection by Collection ID](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#af648b8e-236c-b9e8-dd6c-3d7058d5c04b).

**Comment by zzswang** [comment]
1. the archived collections is in default team workspace.
2. failed to remove those collections with [DELETE the collection by Collection ID API](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#af648b8e-236c-b9e8-dd6c-3d7058d5c04b)

response

```
{
  error: {
    name: 'instanceNotFoundError',
    message: 'The specified item does not exist.',
    details: { item: 'collection', id: 'ba2b631f-b47b-4866-b31a-aa0ecff51023' }
  },
  status: 404
}
```

**Comment by zzswang** [comment]
I get the id from [LIST API](https://documenter.getpostman.com/view/631643/JsLs/?version=latest#3190c896-4216-a0a3-aa38-a041d0c2eb72), and success to delete those not archived ones.

**Comment by cyrielle-hada** [comment]
@zzswang could you try these set of steps to delete the archive collection? 

1. Generate an API key for the Postman API [here](https://go.postman.co/settings/me/api-keys).
2. Use the below cURL code to complete each action - just add your own key in place of {{your_api_key}}​.
3. GET all collections, to get the needed Collection UIDs. Please make sure you're using the collection UID and not the collection ID.
<img width="583" alt="Screenshot 2020-05-19 at 15 21 11" src="https://user-images.githubusercontent.com/47351631/82338264-959e6380-99e4-11ea-868a-3e0adf37db6f.png">

```
curl -X GET \  https://api.getpostman.com/collections \
-H 'X-Api-Key: {{your_api_key}}' \
-H 'cache-control: no-cache'
```
4. DELETE collection by Collection ID. Again, here please make sure you're using the collection UID and not the collection ID.

```
curl -X DELETE \
'https://api.getpostman.com/collections/{{collection_uid}}' \
-H 'X-Api-Key: {{your_api_key}}' \
-H 'cache-control: no-cache'
```

 _You can also do this directly in Postman if you want._

**Comment by zzswang** [comment]
@cyrielle-hada  

Great, it works.
