### ISSUE TITLE
Extracting number from response body not working

### ISSUE THREAD

**Issue by rrm415** [a85/POSTMan-Chrome-Extension#8498]
I am able to successfully extract a "string" from the response body and update that "string" in the environment variable.

**I am NOT able to extract a _number_ from the response body and update the number in an environment variable.** 

Is this intentional?

To reproduce, find a number in a response you can extract and save to an environment variable. Then see if you are successful, I continuously get NULL or simply blank.

**Comment by rrm415** [comment]
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("CustomerID", jsonData.customerId);

**Comment by arlemi** [comment]
@rrm415 You need to use `pm.environment.set();` instead.
You can also use `pm.response.json()` to get the response body. 

E.g.:
```javascript
const jsonData = pm.response.json();
pm.environment.set("CustomerID",  jsonData.customerId);
```

See our Learning Center for more information: https://learning.postman.com/docs/postman/scripts/postman-sandbox-api-reference/#pmenvironment
