### ISSUE TITLE
URL segment parameters

### ISSUE THREAD

**Issue by datashaman** [a85/POSTMan-Chrome-Extension#85]
Rails routing and pretty much most other REST-based systems use segments in the URL to convey context and parameters to the controller. It does not appear possible to do this using POSTMan, which cuts out a large portion of your core users.

**Comment by ericingram** [comment]
@a85 Is there any way to disable this feature? We built an API that uses colon characters at the beginning of a segment to access resource metadata. For example GET /:models. Postman replaces ":models" with empty string in this case.

Would you consider passing the original string if no param value is provided to replace it?

**Comment by czardoz** [comment]
@ericingram, as a workaround, have you tried setting the variable value to ":whatever"?

**Comment by datashaman** [comment]
I would suggest the easiest approach around this is to rather pass through
the original token if there is no parameter for that URL segment.

So in your case, if there's nothing to substitute for :models, then it
stays as literally :models.

In other cases, where a parameter exists, use the parameter.

**Comment by czardoz** [comment]
@datashaman, what if someone actually wants to leave that value blank? 

The way I see it, ":anything" is a variable. If you want the value to be ":anything", it's best to set it explicitly.

**Comment by datashaman** [comment]
The problem is there's no way to escape that ':' so it is not recognized as
a placeholder. Add a way to escape the : and also to escape the escape
character and you should be good to go. :)

**Comment by czardoz** [comment]
Not sure what you mean by "there's no way to escape that ':' so it is not recognized as a placeholder".

I was able to send a request to "/:var" with this setup:

![screenshot from 2015-08-28 14 13 36](https://cloud.githubusercontent.com/assets/3726484/9542511/07c9bf24-4d8f-11e5-99a3-1fe06d3c2b5a.png)

This is my server code:

```
from flask import Flask
app = Flask(__name__)

@app.route('/:var')
def hello_world():
    return 'Hello World!'

if __name__ == '__main__':
    app.run()
```

and this is the output, which shows that the request was caught on the "/:var" path.

```
(issue-85)aniket [~/tmp/issue-85] -> python server.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Aug/2015 14:12:47] "GET /:var HTTP/1.1" 200 -
```

What escaping functionality is needed here?

**Comment by datashaman** [comment]
Uh, my bad. I'm misunderstanding the problem. It's not one of escaping, it's of selective replacement of the parameter, but as you've said what if it should be blank. Perhaps a special 'blank' token? But then you need a way to escape that because the 'blank token' might ALSO be a legit parameter in some weird situation. Token-ception. :)

**Comment by pvsune** [comment]
i'm doing a pre-request script and i noticed that `request.url` did not change the path variable to correct one (e.g. `http://klapaucius.io/:id`). do you guys have any idea how i can get the correct url? thanks!

**Comment by abhijitkane** [comment]
@pvsune The pre-request script does not have variables resolved. You can try changing the `:id` to `{{id}}`, and using `id` as an environment variable.

You can then use a little regex to replace the variable yourself - 

`var resolvedUrl = request.url.replace(/{{(\w*)}}/g,function(str,key) {return environment[key]});`

**Comment by pvsune** [comment]
thanks @abhijitkane i thought there's a prettier way

**Comment by igorsantos07** [comment]
I've been wanting this feature for ages <3
However, I had to dig through Google to find it. Is there any place where it's explicitly shown to new users that I've missed?

**Comment by gchiacchio** [comment]
> @pvsune The pre-request script does not have variables resolved. 

@abhijitkane Do you think in the future there will be a way to access the path variables as the environment variables from the pre-request scripts?

**Comment by cdtinney** [comment]
+1.

Would be very useful.

**Comment by vcmJonasTarnowetzki** [comment]
Can we modify the search pattern to not require a leading slash?  My company is working with an api specification that requires url segments with parameters be formatted as `/resource=id/`.  Postman is capable of generating correctly formatted api tests from our swagger.json (ie `/resource=:id/`) but it cannot identify the parameter `:id`.

EDIT: It would be better to make the pattern accept either leading slashes or equals symbols (`[\/|=]`).  Otherwise it would accept invalid patterns such as `resource:id`.

**Comment by jmurowaniecki** [comment]
Hello there!

Somebody can tell me if it's possible to use multiple **optional** uri segments like `/user(/:id|:username)`?

I'm planning to use **:id** or **:username** - both are optional since when nothing is informed the response are the user logged.

Or maybe are easier to duplicate and change the uri with proper descriptions :thinking: ??

Now I'm using this way:

```json
"name": "user(/:id|:username)",
"item": [
    {
        "name": "/user",
        "request": {
            "method": "GET",
            "header": [],
            "body": {
                "mode": "raw",
                "raw": ""
            },
            "url": {
                "raw": "/user",
                "path": [
                    "user"
                ]
            },
            "description": "request logged user data."
        },
        "response": []
    },
    {
        "name": "/user/:id",
        "protocolProfileBehavior": {
            "disableBodyPruning": true
        },
        "request": {
            "method": "GET",
            "header": [
                {
                    "key": "Content-Type",
                    "name": "Content-Type",
                    "type": "text",
                    "value": "application/x-www-form-urlencoded"
                }
            ],
            "body": {
                "mode": "file",
                "file": {}
            },
            "url": {
                "raw": "/user/:id",
                "path": [
                    "user",
                    ":id"
                ],
                "variable": [
                    {
                        "description": "User ID.",
                        "key": "id",
                        "value": "42"
                    }
                ]
            },
            "description": "request using id."
        },
        "response": []
    },
    {
        "name": "/user/:username",
        "protocolProfileBehavior": {
            "disableBodyPruning": true
        },
        "request": {
            "method": "GET",
            "header": [
                {
                    "key": "Content-Type",
                    "name": "Content-Type",
                    "type": "text",
                    "value": "application/x-www-form-urlencoded"
                }
            ],
            "body": {
                "mode": "file",
                "file": {}
            },
            "url": {
                "raw": "/user/:username",
                "path": [
                    "user",
                    ":username"
                ],
                "variable": [
                    {
                        "key": "username",
                        "value": "douglasadams",
                        "description": "Username duh."
                    }
                ]
            },
            "description": "request using username."
        },
        "response": []
    }
]
```

But the idea is replace by
```json
"name": "/user",
"item": [
    {
        "name": "/user(/:id|:username)",
        "request": {
            "method": "GET",
            "header": [
                {
                    "key": "Content-Type",
                    "name": "Content-Type",
                    "type": "text",
                    "value": "application/x-www-form-urlencoded"
                }
            ],
            "body": {
                "mode": "raw",
                "raw": ""
            },
            "url": {
                "raw": "/user(/:id|:username)",
                "path": [
                    "user",
                    [":id", ":username"]
                ],
                "variable": [
                    {
                        "description": "User ID.",
                        "key": "id",
                        "value": "42"
                    },
                    {
                        "key": "username",
                        "value": "douglasadams",
                        "description": "Username duh."
                    }
                ]
            },
            "description": "request logged user data."
        },
        "response": []
    }
]
```


What do you think? It might be possible?
