### ISSUE TITLE
Broken UI in the collection browser when the collection description is long enough

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#8503]
**Describe the bug**
The UI in the collection browser is broken when the documentation of a collection is long enough.
The requests can be seen through (please refer to the screenshot), along with the `View Less` button appearing somewhere in the middle.

**To Reproduce**
1. Go to a collection that has a really long description, you [can use this](https://explore.postman.com/templates/436/write-responses-to-file).
2. Click on '>' arrow to open the collection browser
3. Under the `Documentation` tab, click on 'View More' 
4. Observe that requests can be seen through the description, resulting in a broken UI. 

**Expected behavior**
The requests shouldn't be visible in between the description, they should be visible after the description at the end.

**Screenshots**
![image](https://user-images.githubusercontent.com/12631777/82292843-31ba7180-99c9-11ea-92a0-54208eaae2fd.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.24
 - OS: macOS 10.15.4

**Comment by pankajk07** [comment]
This is fixed as part of `v.7.25`.
