### ISSUE TITLE
Request to copy values from the request into the mocked response

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#8504]
**Is your feature request related to a problem? Please describe.**
While using Postman Mocks - would like to include a value from the incoming request to the example response.

**Describe the solution you'd like**
Since it's not possible to define an Example response for every possible value of the string. Instead, would like to just define one Example responses but with the value of name copied from the incoming request to that example response.

Demonstrated with examples:

```
Request:
{ "name": "<arbitrary string>", (ignored values) }
Response
{ "name": "<the same arbitrary string>", (mocked values) }

Request:
{ "name": "Foo 123", (ignored values) }
Response
{ "name": "Foo 123", (mocked values) }

Request:
{ "name": "bar", (ignored values) }
Response
{ "name": "bar", (mocked values) }

Request:
{ "name": "some string", (ignored values) }
Response
{ "name": "some string", (mocked values) }

...
```

**Additional context**
For testing a Create endpoint, would like the mocked 201 response to mirror all the values sent in the request, but perhaps with an Id set.

*_Filed by Product Support_*

**Comment by vvs11** [comment]
similar to  #6437

**Comment by ghost** [comment]
#6437 seems to be about copying **query parameters or path segments** from the request to the response. This issue is rather about copying **JSON body fields** from the request to the response.

**Comment by vvs11** [comment]
Keeping it open as a feature request.

**Comment by Dhembla** [comment]
Hey @Raj-postman @mronnblom-cint , As per our latest app release(v10.7), we have added support for template helpers that can be used while authoring examples and helps you access request data(headers, body, query params and path segments) in mock responses. You can read more about the feature [here](https://blog.postman.com/introducing-support-for-templating-in-postman-mock-servers/).
Please give it a try and let us know if the solution meets your needs. Thanks for your patience. 🙇
