### ISSUE TITLE
Postman 7.24.0 cannot be installed on macOS Catalina 10.15.2

### ISSUE THREAD

**Issue by edwardkads** [a85/POSTMan-Chrome-Extension#8507]
Postman fails to install on macOS catalina, fails with the error “Postman” can’t be opened because Apple cannot check it for malicious software.

**Steps to reproduce**
1. Go to https://www.postman.com/downloads/
2. Click on the download button (currently Version 7.24.0)
3. Double click on downloaded file to extract
4. Double click the extracted Postman app

**Expected behavior**
The App or the installer should run

**Actual Behaviour**
It fails with message -> “Postman” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

**Screenshots**
<img width="425" alt="Screen Shot 2020-05-19 at 11 33 36 AM" src="https://user-images.githubusercontent.com/14234810/82346593-a808a500-99c4-11ea-8cfe-59274c168b6e.png">

**App information**
 - Native app
 - 7.24.0
 - OS: macOS Catalina 10.15.2

**Comment by kamalaknn** [comment]
Hey @edwardkads 

Are you still seeing this issue? If yes, could you run the following command via Terminal and share the results?

`spctl --assess --type install {path-to-postman}/Postman.app/Contents/MacOS/Postman`

**Comment by edwardkads** [comment]
Hi @kamalaknn I was able to resolve the issue by  disabling the assessment rule. Thanks `sudo spctl --master-disable`

**Comment by preexo** [comment]
This problem still holds for version 7.29.1 using macos Catalina 10.15.6
I can't work around it due to restrictions, it leaves postman not-usable

➜  ~ spctl --assess --type install /Applications/Postman.app/Contents/MacOS/Postman
/Applications/Postman.app/Contents/MacOS/Postman: rejected

**Comment by Asaph434** [comment]
j'ai la version catalina 10.15 actuellement, est-ce que c'est possible de l'avoir actuellement
