### ISSUE TITLE
Make working with expiring OpenIDConnect tokens easier

### ISSUE THREAD

**Issue by friedrich-brunzema** [a85/POSTMan-Chrome-Extension#8508]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by how hard it is to get an OAuth2/OpenIdConnect token into Postman, considering that tokens have very short lifetimes.

**Describe the solution you'd like**
I have written a command line utility that targets a specific IDP (keycloak) that gets me a valid token.  The utility pretends to be a web user-agent and puts the username/password in the appropriate login box fields. My solution is easy to integrate with newman.

```
token=$(gt get-token -e dev -p demo)
cat testcoll.json | sed -e "s/%TOKEN%/$token/g" > testcoll_with_creds.json
newman run testcoll_with_creds.json
```

But that does not work with Postman.  With Postman, I have to edit the collection and replace the contents of my {{token}} variable.  Luckily my utility also copies the JWT token to the clipboard.  But our timeout is 5min -- so when working, I have to constantly get new tokens.
So ideally postman would have an option to call a custom program that outputs a token to stdout, and set the collection variable associated with the bearer token.  There should be an option to define the token timeout, so that a new token is only requested when needed.

**Describe alternatives you've considered**
Alternatives are described above.  If an external program could patch (via rest?) a new token right into the collection variable store - that could work too, but be less desirable than a pull model.
**Additional context**

**Comment by mccannt** [comment]
@friedrich-brunzema Thx for the suggestion. We are currently tracking this [here](https://github.com/postmanlabs/postman-app-support/issues/2361) check back for updates.
