### ISSUE TITLE
Cannot import JSON collections anymore

### ISSUE THREAD

**Issue by arellanoemilio** [a85/POSTMan-Chrome-Extension#8509]
**Describe the bug**
I can no longer import previously exported Collections that were exported as JSON files  "Collection v2.1 (recommended)"

I am using Postman Version 7.24.0 64-bit on Windows 10.

**To Reproduce**
1. Right Click on a collection
2. From the pop up menu click 'Export'
3. From the pop up window export collection as 'Collection v2.1(recommended)' and save file as 'export.json'.
4. Right Click on the same collection
5. from pop up menu click 'Delete'
6. On Top left corner click 'Import'
7. On the pop up window click 'Upload Files'
8. Select previously exported file 'export.json' from the file explorer
9. Click 'Open'
10. See Error 'Error while importing: format not recognized'

**Expected behavior**
I expected the collection to be re created and get populated with all of the requests it originally had

**Screenshots**
![image](https://user-images.githubusercontent.com/15184380/82379459-f46bd900-99f4-11ea-9c4c-0172be1de466.png)
![image](https://user-images.githubusercontent.com/15184380/82379404-daca9180-99f4-11ea-8df1-729c18926139.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.24.0 
 - OS: Windows 10

**Additional context**

**Comment by alex88** [comment]
@arellanoemilio did you find a solution for this?

**Comment by arellanoemilio** [comment]
Yes the JSON file was had a syntax error in it; therefore, when I tried to import it postman wasn’t able to read it. After fixing the syntax error, the import tool worked as expected.

Emilio Arellano

**Comment by alex88** [comment]
Oh ok thank you for replying. Looks like we're hitting another bug then.

**Comment by fernandojmartin** [comment]
Hi there.
Just to add up: I got the same error message.
It's also confusing the first import screen as it doesn't lists JSON as a valid format file to be loaded.
Just copy/pasted the json string as "raw text" and it worked fine (parsed and imported the whole collection).
The json was perfectly valid.

![image](https://user-images.githubusercontent.com/722826/103902242-0069ef80-50d9-11eb-93be-f197307c6b5b.png)
![image](https://user-images.githubusercontent.com/722826/103902297-111a6580-50d9-11eb-9ff8-d95408629805.png)
