### ISSUE TITLE
System Resource Excessive

### ISSUE THREAD

**Issue by jrmore** [a85/POSTMan-Chrome-Extension#8510]
**Describe the bug**
I am sorry I cannot provide a clear and concise description. All I have is.
After working most of the day (every day for the past 2 years) on a Lenovo desktop running Linux Mint 19.3 today my system fans turned on and kept running ( never noticed them before) so loud it did attract my attention. I was just editing a file at the time but have a very large number of processes running. When I checked the system monitor all 8 CPUS were pegged at 100% and the only process consuming CPU was Postman (native app). As soon as I killed it the CPUs dropped to 0% and a couple of minutes later the fans had ceased running.
I never shut the systems down and so Postman has probably been running since the last update. There are a couple of Postman processes still running but not using any resources. I presume they are synch watchers. 
Don't know what else I can add but if there are logs created that I could send to you please let me know.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by arlemi** [comment]
We're centralising these reports in #7294, I'll close this one and we can follow up there.

In the meantime could you please retrieve the logs and forward them to help@postman.com? 
See [Where can I find logs for the Postman app](https://support.getpostman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-).
