### ISSUE TITLE
error: snap "postman" has no services

### ISSUE THREAD

**Issue by ayr-ton** [a85/POSTMan-Chrome-Extension#8513]
**Describe the bug**
Installed snap in Ubuntu 20.04 and got the error `error: snap "postman" has no services` 

**To Reproduce**
1. Using Ubuntu 20.04, run `sudo snap install postman`
2. Should get a success install message
3. Ran `sudo snap logs postman`
4. See `error: snap "postman" has no services` 

**Expected behavior**
To have default installation working as expected in Ubuntu 20.04

**App information (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Postman 7.24.0 from Postman, Inc. (postman-inc✓)
 - Kernel 5.4.0-31-generic

**Comment by ayr-ton** [comment]
Discussion in snapcraft.io forum:
https://forum.snapcraft.io/t/postman-7-24-0-on-ubuntu-20-04-dont-start/17601/2

**Comment by jviotti** [comment]
We have re-written our Snap packaging logic and believe the issue is solved now. Please re-open if you face the same problem on newer versions of the app!

**Comment by mojanad** [comment]
Stiil not working

> We have re-written our Snap packaging logic and believe the issue is solved now. Please re-open if you face the same problem on newer versions of the app!
