### ISSUE TITLE
Sync breaks variables

### ISSUE THREAD

**Issue by aetonsi** [a85/POSTMan-Chrome-Extension#8514]
**Describe the bug** / **To Reproduce**
I have 2 machines with postman installed.
If i do "heavy" editing of the environment/global variables (move, add, delete, rename a lot of them) on a single machine, everything works correctly.
As soon as i open up postman on the second machine, sync starts and everything gets scrambled: variables get wrong values, wrong placement, some variables are added/deleted, some aren't, some edits are just ignored/rolled back.
It then gets saved in the cloud like that, i checked in the dashboard.
The scrambled variables are then synced back on the first machine, and i end up with that mess on both machines.

**Expected behavior**
I'd expect that the changes i do on the first machine get synced and duplicated on the second machine.
Currently it seems like syncing does a two-way mirror sync (this is just a personal speculation), instead of a progressive sync using timestamps to keep track of the sequence of changes. If that's the case, that's probably the reason why everything broke.
The app on the second machine is usually opened while it's still open on the first machine, i don't know if this could make a substantial difference.

**Screenshots**
example screenshot with some of the problems explained
![image](https://user-images.githubusercontent.com/18366087/82467887-7bd34e00-9ac2-11ea-95e7-e44266ba77e6.png)

**App information (please complete the following information):**
first machine: Postman native app v7.22.1 for win32 10.0.18363 / x64
second machine: Postman native app v7.24.0 for  win32 10.0.18363 / x64

<hr>

Thank you for your time, have a nice day

**Comment by james-postman** [comment]
Hi @aetonsi 

Sorry for the delay, I've been taking a look at this issue for you. Could you tell me are you able to reproduce the bug in the current version of the Postman app?

If so, could you tell me approximately how many environment/global variables you are working with please?

Thanks
James

**Comment by aetonsi** [comment]
Hello sir,
i did some quick testing and the issue doesn't seem to be present anymore.
I'm not doing such heavy testing anymore...
I'd warn you again if it comes back, on my next big refactoring.

---
Have a nice day.

**Comment by james-postman** [comment]
Thanks very much for getting back to me @aetonsi!

I'll close this out for now then, but don't hesitate to reach out if you experience the issue again.

James
