### ISSUE TITLE
"Check for updates" is closing SETTINGS window first, it should not.  

### ISSUE THREAD

**Issue by gigaimage** [a85/POSTMan-Chrome-Extension#8516]
**Describe the bug**

Regardless of update available or not (latest already installed), Check for updates action should not close entire SETTINGS screen. Not only it's functionally incorrect but not a user-friendly workflow as it forces to start all over with extra clicks to reopen SETTINGS. 

**To Reproduce**
**Pre-condition: Latest version is installed. No updates available.** 

1. From Launchpad tab click on "... More settings".
2. On SETTINGS window click to go to Update tab.
3. Click on "Check for updates" button.

**Expected behavior**
SETTINGS window is still open while update check starts|in progress

**App information (please complete the following information):**
 - App Type : Native App (see attached screenshot)
 - Postman Version & 
 - OS 
<img width="271" alt="Screen Shot 2020-05-20 at 11 51 42 AM" src="https://user-images.githubusercontent.com/1184087/82485460-4e6dac80-9a90-11ea-8005-16799799c75c.png">

<img width="493" alt="Screen Shot 2020-05-20 at 11 46 40 AM" src="https://user-images.githubusercontent.com/1184087/82485186-e8812500-9a8f-11ea-9114-6cc709ee363b.png">

**Comment by DannyDainton** [comment]
Unable to reproduce this in the latest version of the platform - Closing this for now but we can look to reopen it if this is still a problem for you.
