### ISSUE TITLE
"Sending Request" times out, no response for GET request.

### ISSUE THREAD

**Issue by here2thrive960** [a85/POSTMan-Chrome-Extension#8517]
**Describe the bug**
Using a MEAN stack application. Checking the routes to the mongo database. When I send the get request in Postman, it gets stuck "sending request" and then just times out.

**To Reproduce**
1. Start Node/Express server in terminal
2. Start mongo, and make sure server is still activated error free
3. Logged on to Postman
4. Sending a GET request to my app
5. "Sending Request" message comes on the bottom and stays that way until finally responding with "Could not get any response" message.

**Expected behavior**
I expected to see an empty dictionary in the response, since I have not created any entries yet.

**Screenshots**
![image](https://user-images.githubusercontent.com/29413045/82514220-04a1b800-9aca-11ea-8e33-332886545f4c.png)
![image](https://user-images.githubusercontent.com/29413045/82514162-d6bc7380-9ac9-11ea-8159-425f0b210bb2.png)
![image](https://user-images.githubusercontent.com/29413045/82514178-e89e1680-9ac9-11ea-8a39-f3db47120b9f.png)

**App information (please complete the following information):**
 - App Type [ MERN stack app (MongoDB w/ NodeJS and ExpressJS) ]
 - Postman Version [ 7.24.0 (7.24.0) ]
 - OS: [ macOS Catalina 10.15.4 ]

**Additional context**
n/a

**Comment by codenirvana** [comment]
Can you share the steps which we can use to reproduce this issue?

Also, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.

**Comment by here2thrive960** [comment]
@codenirvana I have detailed the steps in my posting as per the instructions of the template.

**Comment by shamasis** [comment]
The dev tool console you posted screenshot of is not the console that outputs request error. Can you post what error you see in Postman Console - you’ll find it from menu as well as third icon on the bottom status bar of app.

**Comment by here2thrive960** [comment]
![image](https://user-images.githubusercontent.com/29413045/82695907-d97aae00-9c1a-11ea-977f-67a3dd11f1fb.png)
![image](https://user-images.githubusercontent.com/29413045/82695976-f9aa6d00-9c1a-11ea-9e84-3aed109da445.png)
![image](https://user-images.githubusercontent.com/29413045/82696012-0c24a680-9c1b-11ea-84e3-2e30e7d6a704.png)

**Comment by codenirvana** [comment]
@ashwinchalaka "socket hang up" can be caused from both the client and the server-side... 
Since the Postman by default doesn't times-out the request, I suspect this is happening because of the way the server is closing the connection.

**Comment by here2thrive960** [comment]
@codenirvana Thanks for getting back to me. How can I troubleshoot and fix this issue?

**Comment by codenirvana** [comment]
Can you update to the latest version of the Postman app which shows the difference between "Could not send request" v/s "Could not get response"?

**Comment by here2thrive960** [comment]
<img width="482" alt="Screen Shot 2020-05-27 at 4 40 13 PM" src="https://user-images.githubusercontent.com/29413045/83082614-c6137c80-a038-11ea-8c34-d9cf84723dbc.png">

**Comment by codenirvana** [comment]
@ashwinchalaka What I meant was, in the latest Postman app when you get the "socket hang up" error message... the response section shows that is it because of "Could not send request" or "Could not get response"?

<img width="690" alt="Screenshot 2020-05-28 at 8 53 14 AM" src="https://user-images.githubusercontent.com/4865836/83095423-f272db80-a0c0-11ea-9d9d-46fb7488c287.png">

**Comment by gianpaj** [comment]
In my case, I had a variable e.g `{{STAGING}}` and the value was `domain.com` – **without** a protocol.
Because of this, the request was stuck.

Adding `https://` fixed this for me

**Comment by DannyDainton** [comment]
Hey @ashwinchalaka 

I'm going to close this issue due to inactivity, if you're still facing this issue in the latest version of the platform, we can look to reopen it again.
