### ISSUE TITLE
"Something Went Wrong" error screen shown when trying to get "Run summary" from "Collection Runner >> Run Results"

### ISSUE THREAD

**Issue by jizuzqui** [a85/POSTMan-Chrome-Extension#8520]
**Describe the bug**
"Something Went Wrong" error screen is shown when trying to get "Run summary" from "Collection Runner >> Run Results" after executing a Collection Runner.

**To Reproduce**
1. Run any Postman Collection for a while.
2. Stop the Runner.
3. Open Run Results.
4. Click on "Run Summary". The "Something Went Wrong" window will be shown.

**Expected behavior**
Show the "Run Summary" correctly.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.24.0
 - OS: Windows 10
![Postman_run_summary_error_1](https://user-images.githubusercontent.com/17247633/82543433-d1a40680-9b53-11ea-87c2-ac4ac8a04b34.PNG)
![Postman_run_summary_error_2](https://user-images.githubusercontent.com/17247633/82543442-d49ef700-9b53-11ea-9c0a-09929257b1c6.PNG)

**Comment by vvs11** [comment]
@jizuzqui could you share the details of the collection that you're running? How many requests are there and how many iterations are you running? Also, what are the runner configurations that you're using?
I tried to reproduce this with a collection of 5 requests but couldn't. It'd be really helpful if you can share more details

**Comment by jizuzqui** [comment]
@vvs11 sure, I'm not currently using the laptop where I reproduced it but tomorrow I'll try to share all the details you've mentioned

**Comment by vvs11** [comment]
@jizuzqui closing this for now. Please feel free to reopen this if it's still not working for you. You can also post queries on our community community.getpostman.com to get responses quickly
