### ISSUE TITLE
how to automate send and download for downloading files?

### ISSUE THREAD

**Issue by bharatramawat28** [a85/POSTMan-Chrome-Extension#8521]
I have a api where a docx file is to be downloaded but the response comes out in octet stream . When i use send and download then it is working fine. I want to automate this so then when i run collection the file is to be downloaded automatically. How can i do that?

**Comment by arlemi** [comment]
@bharatramawat28 Please ask that question on our Community forum https://community.postman.com/ where people will be able to help. 😃

**Comment by bharatramawat28** [comment]
There is no response on community page also
