### ISSUE TITLE
Converting YAML file to API collection generates examples based on responses only.

### ISSUE THREAD

**Issue by EllaVish** [a85/POSTMan-Chrome-Extension#8523]
Hello,

I created a small yaml file, containing 2 examples of content.
My propose is to use a collection via postman and choose different examples, containing different values in order to cover several use-cases.

When yaml code is edited in the swagger editor, i can see my examples and choose between them:
![hhh1](https://user-images.githubusercontent.com/64786367/82565223-b69cbb00-9b82-11ea-9500-1af613187c46.jpg)

When i'm adding this API to postman and generating a collection from it i see that the 'examples' are generated and based on the responses that I added in my yaml file.
All the 'body' params are showing only the first example.
![ttt](https://user-images.githubusercontent.com/64786367/82565536-43e00f80-9b83-11ea-888c-f6b99bf3b2a2.jpg)

Is there any way of doing that?
I want to be able to 'attach' request and responses examples.
For example: 
can get response '200' with 2 different examples, containing different values (one full request, one with un-required keys that are omitted).

my yaml file:
```
openapi: 3.0.0
info:
  description: "Test"
  version: "2.2.2"
  title: "my test"
host: "somehost"
basePath: "/somepath"
schemes:
- "https"
tags:
  - name: hello
    description: helloWorld
    
paths:
  /hello:
    post:
      description: "some description"
      operationId: "example-test"
      tags: ["example-test"]

      requestBody:
        required: true
        content:
          application/json:
            schema:
               $ref: "#/components/schemas/myRequest"
            examples:  
              ex1:
                $ref: "#/components/examples/test1"
              ex2:
                $ref: "#/components/examples/test2"
      responses:
        "204":
          description: "All good"
        "500":
          description: "second one"

components:
  schemas:
    myRequest:
      type: object
      required: 
      - name
      - lastname
      properties:
        name:
          type: string
        lastname:
          type: string
  examples:
    test1:
      value:
        name: test1
        lastname: test1
      description: "ohhhhh1"
    test2:
      value:
        name: test2
        lastname: test2
      description: "ohhhh2"
```

**Comment by VShingala** [comment]
@EllaVish We've added support for the consumption of multiple examples for the request and response body mentioned in the OpenAPI definition and the generation of request examples based on these examples. More on how this works can be found [here](https://github.com/postmanlabs/openapi-to-postman/pull/768#issue-1911459880).

I was able to generate collection with 2 examples having different request body examples from mentioned definition by you.

![image](https://github.com/postmanlabs/postman-app-support/assets/16756296/220f077f-b883-4a7e-8c91-50da0cf0bdb8)
