### ISSUE TITLE
Public documentation sidebar links to anchors JUST too low

### ISSUE THREAD

**Issue by chrismaddern** [a85/POSTMan-Chrome-Extension#8524]
**Describe the bug**
When tapping on a request in the sidebar on a public documentation site, the anchor always navigates you to a location that's _just_ too low, i.e. putting the title just under the header bar.

<img width="700" alt="Screen Shot 2020-05-21 at 3 43 45 PM" src="https://user-images.githubusercontent.com/1068437/82599191-ded3ec00-9b79-11ea-823c-c7927b3341aa.png">

**To Reproduce**
1. Go to a public documentation site
2. Click on any sidebar anchor

**Expected behavior**
The title of the section linked to should be just below the header bar, not under it.

**Screenshots**
<img width="700" alt="Screen Shot 2020-05-21 at 3 43 45 PM" src="https://user-images.githubusercontent.com/1068437/82599266-f6ab7000-9b79-11ea-8d58-acd3fc9ead0f.png">

**App information (please complete the following information):**
 - Chrome 81 on Mac OS

**Comment by ranchanarajasekaran** [comment]
This issue has been fixed. Please reopen the issue to report any feedback on the same.
