### ISSUE TITLE
same request get deffrent results between Collection Runner and the Tab

### ISSUE THREAD

**Issue by chen-yi-tester** [a85/POSTMan-Chrome-Extension#8525]
**Describe the bug**
i can get the right response of a request with clickling the 'send' button,but when the request runs in the Collection Runner ，the parameter is mistaken. 

**Screenshots**
request in the Tab
![image](https://user-images.githubusercontent.com/57658722/82628849-8e639980-9c20-11ea-88a5-596aceb27d6a.png)

request  console  in the Runner
![image](https://user-images.githubusercontent.com/57658722/82635862-d5a75580-9c33-11ea-81c7-68a8cafd1610.png)

**Comment by codenirvana** [comment]
@chen-yi-tester Probably you haven't selected the right environment before starting the run.

<img width="469" alt="Screenshot 2020-05-22 at 9 15 43 AM" src="https://user-images.githubusercontent.com/4865836/82629324-fb6d3400-9c0c-11ea-8517-1f231795b5ca.png">

I see the `host` variable is resolved correctly but not `LEVEL3_AGENT_ID`.
But, how does `LEVEL3_AGENT_ID` gets converted to `level3_agent_id`? 🤔

**Comment by chen-yi-tester** [comment]
> @chen-yi-tester Probably you haven't selected the right environment before starting the run.
> 
> <img alt="Screenshot 2020-05-22 at 9 15 43 AM" width="469" src="https://user-images.githubusercontent.com/4865836/82629324-fb6d3400-9c0c-11ea-8517-1f231795b5ca.png">
> 
> I see the `host` variable is resolved correctly but not `LEVEL3_AGENT_ID`.
> But, how does `LEVEL3_AGENT_ID` gets converted to `level3_agent_id`? 🤔

Thanks for your attention , i never use any enviroment,and my parameters are all global. I use capital worlds because they are constants  
![image](https://user-images.githubusercontent.com/57658722/82636261-c7a60480-9c34-11ea-96a2-4205fd090297.png)

**Comment by codenirvana** [comment]
That's odd... Can you share a scaled-down collection (or steps) which we can use to reproduce this issue?

**Comment by chen-yi-tester** [comment]
> That's odd... Can you share a scaled-down collection (or steps) which we can use to reproduce this issue?

What should i do to share a scaled-down collection (or steps) with you ?

**Comment by codenirvana** [comment]
@chen-yi-tester we need steps or a collection which we can use to reproduce this issue locally.

**Comment by chen-yi-tester** [comment]
> @chen-yi-tester we need steps or a collection which we can use to reproduce this issue locally.

https://www.getpostman.com/collections/f1270e72f1a9694c0fc5 
can you use this collection?

**Comment by codenirvana** [comment]
@chen-yi-tester No, the variables are not defined.
Can you create a test collection using some [echo endpoint](http://postman-echo.com/) to demonstrate this issue?

**Comment by chen-yi-tester** [comment]
> @chen-yi-tester No, the variables are not defined.
> Can you create a test collection using some [echo endpoint](http://postman-echo.com/) to demonstrate this issue?

I have tried useing the echo endpoint ,it didnt demoinstrate. May i send the collection link and My Workspace.postman_globals.json to your own email_address?

**Comment by codenirvana** [comment]
@chen-yi-tester If I understood your problem correctly... your global variable `level3_agent_id` is resolving correctly when the request is sent via the Builder window but not via Runner.

I tried doing the same thing using the latest Postman app and everything is working as expected. Since we haven't seen other users facing the same issue, I suggest you debug your collection and variables properly to identify the issue.

**Comment by chen-yi-tester** [comment]
> @chen-yi-tester If I understood your problem correctly... your global variable `level3_agent_id` is resolving correctly when the request is sent via the Builder window but not via Runner.
> 
> I tried doing the same thing using the latest Postman app and everything is working as expected. Since we haven't seen other users facing the same issue, I suggest you debug your collection and variables properly to identify the issue.

I replaced LEVEL3_AGENT_ID with  level3_agent_id.  it works😂
