### ISSUE TITLE
Search in the environment variables

### ISSUE THREAD

**Issue by ColdCerealAtWork** [a85/POSTMan-Chrome-Extension#8530]
**Is your feature request related to a problem? Please describe.**
Some of my environments are very large and its frustrating to dig through them to find a single variable.

**Describe the solution you'd like**
I'd love a search box that does a live filter of your environment variables

**Describe alternatives you've considered**
Setting variables as favorites, categorizing them, or alphabetizing them would all be helpful.

**Additional context**
![2020-05-22 14_02_30-Kibana - OneNote](https://user-images.githubusercontent.com/45828766/82709437-721e2780-9c35-11ea-909d-f0d7c96298ab.png)

**Comment by SabriH10** [comment]
Hi @KristianAtVsp,

Have you tried using the Global search function? Perhaps you may find it useful for your case. If you go to the [Keyboard Shortcuts modal]:(https://learning.postman.com/docs/postman/launching-postman/keyboard-shortcuts/#view-keyboard-shortcuts-for-your-os) 

![image](https://user-images.githubusercontent.com/62078336/82710188-48262e80-9c50-11ea-8051-4c48b17480f4.png)
And scroll down under **Windows and Modals** you should see the shortcut for **Find** or **SHIFT+CMD+F** on macOS. It should look something like this:

![image](https://user-images.githubusercontent.com/62078336/82710313-93404180-9c50-11ea-9680-615d2062b69e.png)

I hope this helps.

**Comment by praveendvd** [comment]
> Hi @KristianAtVsp,
> 
> Have you tried using the Global search function? Perhaps you may find it useful for your case. If you go to the [Keyboard Shortcuts modal]:(https://learning.postman.com/docs/postman/launching-postman/keyboard-shortcuts/#view-keyboard-shortcuts-for-your-os)
> 
> ![image](https://user-images.githubusercontent.com/62078336/82710188-48262e80-9c50-11ea-8051-4c48b17480f4.png)
> And scroll down under **Windows and Modals** you should see the shortcut for **Find** or **SHIFT+CMD+F** on macOS. It should look something like this:
> 
> ![image](https://user-images.githubusercontent.com/62078336/82710313-93404180-9c50-11ea-9680-615d2062b69e.png)
> 
> I hope this helps.

This won't show the content of the variable , again we have to scroll through everything

**Comment by borislt** [comment]
Really miss ability to quick search the envs. Got lots of them. Very tiresome to skim through.

**Comment by SabriH10** [comment]
Duplicate of #6562

**Comment by SabriH10** [comment]
@KristianAtVsp I believe there's an existing request for this feature. In the meantime, a colleague built this tool that _may_ alleviate some of the hassle. It can be found here: https://github.com/kevinswiber/postmanctl, and there's a script that allows you to search iterate all environments with a key: https://github.com/kevinswiber/postmanctl/blob/master/examples/iterate-over-environments/find-environment-with-key.sh.

I know this doesn't fully address your question, but hopefully, it helps!

**Comment by giridharvc7** [comment]
Tracking this a duplicate to #5342

**Comment by vedkribhu** [comment]
In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback.
![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219374771-26ab2b5f-c2fc-4177-9d82-718633064885.png)

**Comment by ColdCerealAtWork** [comment]
> In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback. ![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219374771-26ab2b5f-c2fc-4177-9d82-718633064885.png)

This is a huge improvement for my workflow, thank you. Taking it a step further would be to add that filter to the environment preview dropdown.

**Comment by ColdCerealAtWork** [comment]
> Tracking this a duplicate to #5342

This request is actually different. I'd like the filter added to the 'quick look', not just the environment management screen. Can this request please be reopened?
