### ISSUE TITLE
HTTP Code for multipart/form-data

### ISSUE THREAD

**Issue by DonBakke** [a85/POSTMan-Chrome-Extension#8531]
**Describe the bug**
When testing an API that requires multipart/form-data content, the Code tool display incorrect results for HTTP.

**To Reproduce**
1. Set the Content-Type request header value to "multipart/form-data; boundary=<calculated when request is sent>"
2. It helps if you have another request header, like Cookie.
2. POST a request to a URL.
2. Click on Code.
3. Click on HTTP in the list of languages.

**Expected behavior**
I expect the Cookie header and the Content-Header separated by CR/LF, but instead I see them concatenated.
I expect the boundary values used to separate each form-data value to have an extra "--" in front.
I expect the final boundary value to have an extra "--" at the end.
I also noticed that the Postman Console results look well formed *and* the boundary value used is very different from the Code. I would expect these to be in alignment.

**Screenshots**
Here is what my HTTP Code looks like:
POST /mvr/v101b6/mvsvc?profile_location=HNL2&status_code=20&trans_type_code=REGISTRATION&veh_type_code=AUTO HTTP/1.1
Host: tstapi.hnl.info
Cookie: TS01377eb4=016a2109af90c9a818a4bf82ff1c93535b00738a33b98eaad836c587a323129b32a765f55cda7fb6536aa9ca1f94a80e04d913269eContent-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="bodytype_code"

2DCP
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="color_major_code"

BLK
----WebKitFormBoundary7MA4YWxkTrZu0gW

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.25.0
 - OS: Windows 10 Pro 1909

**Comment by DannyDainton** [comment]
Closing this due to age and inactivity - If this is still an issue for you on the latest version, we can look at reopening it again.
