### ISSUE TITLE
POST call to an API generates different results 

### ISSUE THREAD

**Issue by SONAL48** [a85/POSTMan-Chrome-Extension#8532]
**Describe the bug**
I made a POST call to an API and the headers were imported.There are 11 headers that should have appeared in the Header Section but unfortunately I see 20 headers (9 hidden headers) which gets added on it's own in POSTMAN.When the same call was made via Postman (Extension available on Google,I received status code 200).Why so?

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by arlemi** [comment]
@SONAL48 Please ask this question on [our community forum](https://community.postman.com/) since this isn't a bug or a feature request. 
We've talked about Live Preview (being able to show/edit hidden headers) here: https://community.postman.com/t/live-preview-is-out/11497

**Comment by SONAL48** [comment]
Sure and thank you!
