### ISSUE TITLE
Unable to publish documentation

### ISSUE THREAD

**Issue by mrz1836** [a85/POSTMan-Chrome-Extension#8533]
**Describe the bug**
1) Created a new version, edited some requests, saved changes to the new version
2) Went into the documentation publisher interface, choose my new version, and hit publish

**To Reproduce**
1. Go to our API documentation and choose a new version, hit publish

**Expected behavior**
The new version to be published, which it was not published.

**Screenshots**
<img width="446" alt="Screen Shot 2020-05-23 at 1 02 48 PM" src="https://user-images.githubusercontent.com/3743002/82736216-f1733000-9cf5-11ea-9fde-8ce65ce03996.png">

**App information (please complete the following information):**
 - App Type native app for editing (using Web for publishing docs)
 - Postman Version 7.25.0
 - OS: Mac OS

**Comment by bhargavkaranam** [comment]
Hi @mrz1836,
This is a known issue that we're tracking when you try to publish the collection to API Network with your Team Public Profile disabled. Can you let us know if you're trying to publish the collection to API Network too?

You can check that based on the toggle on the Documentation Publish Page (Collection Discovery)

![image](https://user-images.githubusercontent.com/8963298/82740794-aabf1d80-9d69-11ea-837a-f1d209fabfaf.png)



If that's the case - you can go to Team Settings and enable your Team Public Profile to fix this (https://go.postman.co/settings/team/general)

![image](https://user-images.githubusercontent.com/8963298/82740725-2371aa00-9d69-11ea-9f66-9920af28104d.png)


If you just wish to publish the documentation and not publish to the API Network - you can toggle Collection Discovery (according to the screenshot above) and try publishing, the documentation should get published. Hope this helps, let me know if you have any queries.

**Comment by mrz1836** [comment]
Yes the "Collection Discovery" was enabled.

I now just disabled "Collection Discovery" and tried to publish and did not receive an error

**Comment by gitThingsDone** [comment]
Closing this ticket as we have moved the collection discovery option away from the publish flow
