### ISSUE TITLE
Two-pane view makes the entire UI extremely slow

### ISSUE THREAD

**Issue by seizir** [a85/POSTMan-Chrome-Extension#8535]
**Describe the bug**
Two-pane view makes the entire UI extremely slow when a text editor is displayed.

**To Reproduce**
Enable two-pane view.
Switch to a tab that uses the Monaco text editor (Pre-request, Tests, response body)
Try interacting with other elements of the UI such as dropdowns or resizing the panes.
See video for example. https://streamable.com/ewhr3s

**Expected behavior**
The UI should be as responsive as with two-pane view turned off.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.25.0
 - OS: Windows 10 1909

**Comment by ritwijsinha** [comment]
Hey @seizir,

Thanks for reporting this. We have fixed it in the latest version of Postman (`v7.26.1`).
Please update your app!

Cheers! 🎉
