### ISSUE TITLE
Importing GraphQL Collection -> Error while importing GraphQL: Could not generate collection. Error Message:Maximum call stack size exceeded

### ISSUE THREAD

**Issue by danielmhanover** [a85/POSTMan-Chrome-Extension#8536]
**Describe the bug**
While importing my GraphQL Collection, I get a maximum call stack size exceeded error.

**Expected behavior**
No Error

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - 7.25.0
 - macOS latest

**Additional context**

**Comment by umeshp7** [comment]
@danielmhanover 
Thank you for reporting this. 
Can you provide us more details of the GraphQL schema you are trying to import? Will be great if you can share the schema here or send it to us on help@postman.com

**Comment by danielmhanover** [comment]
Sent!

**Comment by danielmhanover** [comment]
@umeshp7 just sent it with the URL of this issue in the subject line. Let me know what the solution is here

**Comment by umeshp7** [comment]
@danielmhanover Thank you, we are working to get this fixed as soon as possible.

**Comment by danielmhanover** [comment]
@umeshp7 has this been fixed yet?

**Comment by olivoil** [comment]
I'm also getting `Maximum call stack size exceeded` using the postman app and `graphql-to-postman` when trying to import a graphQL file

**Comment by mccannt** [comment]
Apologies, we are currently investigating this further. 
We will share updates when we have something.

**Comment by mccannt** [comment]
We should have this now resolved. 
@danielmhanover and @olivoil can you verify this is now resolved in the most recent version of the application?

**Comment by mccannt** [comment]
Closing out this issue. If you are still experiencing issues with this let us know.
