### ISSUE TITLE
Unnecessary quotes around encoded filename* parameter

### ISSUE THREAD

**Issue by xanto521** [a85/POSTMan-Chrome-Extension#8537]
**Describe the bug**
When I was using this app, I found that the file name I uploaded in the form would have a double quote symbol in the file name obtained in the back end

**Screenshots**
this is the app ui
![微信截图_20200525135443](https://user-images.githubusercontent.com/25278688/82782619-50b87800-9e8f-11ea-8012-12b9321864ae.png)

this is  python flask function request.files.get() get 
![微信截图_20200525135845](https://user-images.githubusercontent.com/25278688/82782838-e18f5380-9e8f-11ea-8261-f2ff74d6c570.png)

Why is there a double quote after the file name?

**App information:**
 - App Type : 
   Postman  for windows desktop
 - Postman Version 
   7.24.0
 - OS: 
   windows 10 Professional version 1909

**Comment by codenirvana** [comment]
@a66298458 This doesn't look like an issue from Postman as it forwards the filename as-is.
You can confirm this by checking the `filename=` attribute sent in the raw log of the [Postman console](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/).

**Comment by xanto521** [comment]
> @a66298458 This doesn't look like an issue from Postman as it forwards the filename as-is.
> You can confirm this by checking the `filename=` attribute sent in the raw log of the [Postman console](https://learning.postman.com/docs/postman/sending-api-requests/debugging-and-logs/).

@codenirvana 
when i use web ui to upload file , there is no this problem

when i use `Progress Telerik Fiddler Web Debugger` to check data, i find a different place

this is the form data from web ui upload
![微信截图_20200526171311](https://user-images.githubusercontent.com/25278688/82882834-360bff00-9f74-11ea-8159-bf6eec89b262.png)

this is the form data from postman upload
![微信截图_20200526171429](https://user-images.githubusercontent.com/25278688/82882960-62278000-9f74-11ea-9ab3-e1f427d9d91c.png)

i think this is the key of the problem, but i can't find how to fixed that.

**Comment by codenirvana** [comment]
@a66298458 I see no issue in the `Content-Disposition` headers and the filename is set correctly.
Probably, the server is not able to process the `filename*` attribute which is added because of the non-ASCII file name.

Which server/form-data body-parser are you using to process this?
Check if uploading a filename with just ASCII characters works fine for you.

**Comment by xanto521** [comment]
@codenirvana i use python flask webserver , the api is `request.files.get('upload_file')`



```
from flask import request
request.files.get('upload_file')
```

**Comment by codenirvana** [comment]
@a66298458 I tried reproducing this issue using a flask server and looks like its body-parser is not able to process the `filename*` attribute in `Content-Disposition` header.
Also, the library which is used internally recommends using the Unicode characters in the filename.

Closing this issue as we are already tracking this feature request of disabling the `filename*` attribute here: https://github.com/postmanlabs/postman-app-support/issues/8308

**Comment by itsjef** [comment]
@codenirvana I'm having this issue too. It happens specially when uploading a file whose name contains non-ASCII character (blue circle). Uploading from web-form or command line (using cURL or httpie) is fine.

![image](https://user-images.githubusercontent.com/1902587/83736584-0fd51600-a67c-11ea-90e0-a800a7ced5c9.png)

App info:
* Postman for windows desktop
* Postman Version: v7.25.2
* OS: Windows 10

**Comment by itsjef** [comment]
Looks like it happens specially to Flask and libraries built on top of it (Eve, Flask-RESTful...). I created another server with Sanic and the filename returned correctly. :)

**Comment by codenirvana** [comment]
@itsjef As mentioned in https://github.com/postmanlabs/postman-app-support/issues/8537#issuecomment-635225864, Postman implements [RFC 6266](https://tools.ietf.org/html/rfc6266) which introduces this new `filename *` disposition parameter for Non-ASCII file names.

A lot of body-parsers don't support this yet but if you check the `Content-Disposition` header set by Postman, it includes both `filename` and `filename*` parameters for backward compatibility.
```
Content-Disposition: form-data; name="file"; filename="你好.xlsx"; filename*="UTF-8''%E4%BD%A0%E5%A5%BD.xlsx"
```

But looks like Flask's body-parser has a different way to extract the filename from the `Content-Disposition` header.

We are already tracking a feature request #8308 which will allow you to disable `filename *`  addition.

**Comment by obfusk** [comment]
Actually, I think it *is* a bug in postman. Looking at the example:

```
Content-Disposition: form-data; name="file"; filename="你好.xlsx"; filename*="UTF-8''%E4%BD%A0%E5%A5%BD.xlsx"
```

And looking at the relevant RFCs (https://tools.ietf.org/html/rfc6266 & https://tools.ietf.org/html/rfc5987), I notice that `filename*=` does not support `quoted-string` values -- only percent-encoding -- whereas the example combines both. When removing the non-RFC-compliant quotes, the example seems to work just fine with flask:

```
Content-Disposition: form-data; name="file"; filename="你好.xlsx"; filename*=UTF-8''%E4%BD%A0%E5%A5%BD.xlsx
```

**Comment by arlemi** [comment]
We had to delay the release of the app, I'm reopening this issue for now and will close it again once 7.35 is widely available. 🙂
