### ISSUE TITLE
SurveyMonkey API V3 is no longer working

### ISSUE THREAD

**Issue by WebXplorer** [a85/POSTMan-Chrome-Extension#8539]
**Describe the bug**
SurveyMonkey API V3 is no longer working.

Currently the urls point to https://api.surveymonkey.net/v3 and that doesn't work anymore. It does work when I change it to https://api.surveymonkey.com/v3

The error I get is: Error: getaddrinfo ENOTFOUND api.eu.surveymonkey.net api.eu.surveymonkey.net:443

PS. It would also be nice to have a EU variant of the API. This should set the url to https://api.eu.surveymonkey.com/v3

**Comment by arlemi** [comment]
@WebXplorer The documentation for the SurveyMonkey API is owned by SurveyMonkey, please reach out to them to let them know they need to update it.
