### ISSUE TITLE
Postman unusable, takes up one processor on idle

### ISSUE THREAD

**Issue by whyvez** [a85/POSTMan-Chrome-Extension#8540]
**Describe the bug**
Postman is unusable and takes up a whole processor sitting idle. You need to wait 30 seconds for a click to do something. I also noticed the sync icon at the top of the app is consistently syncing.

**To Reproduce**
1. Open postman.

**Expected behavior**
The App should be responsive and I should have to wait 30 seconds for a click. Postman should not take a whole processor when sitting idle.

**Screenshots**
![Screen Shot 2020-05-25 at 12 02 18 PM](https://user-images.githubusercontent.com/1593907/82834865-979e7180-9e7f-11ea-9e92-18c593b4543e.png)
![Screen Shot 2020-05-25 at 12 02 31 PM](https://user-images.githubusercontent.com/1593907/82834881-9e2ce900-9e7f-11ea-8214-a700843034ba.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version: 7.25.0
 - MacOS Catalina 10.15.1

**Additional context**
My machine is n 8 core i9 with 32GB of ram.

**Comment by sadohert** [comment]
I'm seeing the exact same issues:

* UI slow to respond
* Request take long time to return
* Sync spinner never stops spinning.

Environment:
* Postman Version 7.24.0 (7.24.0) - Native App
* MacOS Cataline 10.15.4 (19E287)
* MacBook Pro 2019 - 2.6 GHz 6-Core Intel Core i7, 16 GB Ram

**Comment by kamalaknn** [comment]
Hey @sadohert @whyvez 

Could you share the application logs from `View -> Developer -> View logs in Finder` with us at `help@postman.com` so we can debug this better?

**Comment by whyvez** [comment]
@kamalaknn Done.

**Comment by sadohert** [comment]
I will when it slows down again.  I tried to upgrade to latest, which was slow.  Had to kill the app twice, but then the upgrade completed and its running okay for me.... I've found this issue to not happen 100% of the time.

**Comment by kamalaknn** [comment]
@whyvez @sadohert Could you try signing out and signing back in and see if it helps?

@whyvez From your logs, I noticed that the app was trying to sync a lot of history which could have caused the performance issues for you. Signing out and signing back in limits this problem to some extent. 

Also, do you use interceptor or request capture features on Postman that could have led to increased history creation on your account?

**Comment by sadohert** [comment]
I definitely use the interceptor.  Logging out and back in is taking some time as the UI is moving slow, and I don't want to lose any of my local changes.

Is there anything I can do to limit the impact of interceptor (assuming that's my issue)?

**Comment by whyvez** [comment]
I was using the interceptor but, had disabled it this morning thinking it might be the cause. Disabling the interceptor didn't help. Trying to log out and back in...

**Comment by kamalaknn** [comment]
@sadohert We are working on some improvements that will improve the performance when working with a large number of history.

In the meantime, I would recommend signing out and signing back in or clearing older groups of history - if you are okay clearing those changes. Alternatively, you could separate your work within multiple workspaces to reduce some of the load.

**Comment by sadohert** [comment]
Awesome, thanks @kamalaknn .  I logged out and back in and the sync spinner now seems to complete/stop spinning.  I also deleted all history before today (there was only one other day from April that had history after logging back in).  I'll come back if I see the issue come back.  Interceptor is off right now.

**Comment by kamalaknn** [comment]
Thanks for the confirmation @sadohert 

We are tracking high CPU and memory usage issues under #7294. I'm closing this issue as a duplicate. Please follow the original thread for updates.
