### ISSUE TITLE
Unable to import OpenAPI using schema link

### ISSUE THREAD

**Issue by umeshp7** [a85/POSTMan-Chrome-Extension#8542]
**Describe the bug**
I am unable to import OpenAPI schema via link. There is no feedback/toast of the error. 

**To Reproduce**
1. Click on the 'IMPORT' button on top left corner
2. Choose import as link
3. Paste the following link https://apireference.getresponse.com/open-api.json
4. On the next screen notice that nothing happens when you click the 'IMPORT' cta button.

**Expected behavior**
The collection and API should be imported.

**App information (please complete the following information):**
 - App Type Native App 
 - Postman Version 7.24
 - OS: Observed in all three.

**Additional context**

WORKAROUND: 
Deselecting the API option from the 'IMPORT AS' dropdown in the "Confirm your Import" screen Imports the collection successfully. 
<img width="780" alt="Screenshot 2020-05-26 at 2 04 09 PM" src="https://user-images.githubusercontent.com/31915995/83157361-2251cb80-a121-11ea-9799-6322017052ec.png">

**Comment by allfortips** [comment]
Hi!
The OS is Windows 10.
Postman version: v7.25.0

**Comment by umeshp7** [comment]
@allfortips Thanks for pointing that out, although it is not working in MacOS as well. 
Updated the original issue.

**Comment by chughmayank** [comment]
@allfortips  - The issue has been resolved. Feel free to reach out in case you still face the issue.
