### ISSUE TITLE
Openssl  Error on sending api request

### ISSUE THREAD

**Issue by shirshak55** [a85/POSTMan-Chrome-Extension#8544]
Whenever i send request i see this error

```
Error: write EPROTO 4774329792:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../../vendor/node/deps/openssl/openssl/ssl/record/ssl3_record.c:252:
```

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/8097377/82924490-23a5bb80-9f9c-11ea-8061-dc745134752a.png">

**Comment by codenirvana** [comment]
@shirshak55 are you behind a proxy?
Try sending a request with the proxy settings disabled.
Also, check if disabling the "SSL certificate verification" setting fixes this issue.

**Comment by shirshak55** [comment]
@codenirvana 

Actually the error is very very unhelpful. I found i used https://localhost instead of http://localhost. https://localhost simply doesn't exists. Should i close this issue?

**Comment by codenirvana** [comment]
@shirshak55 Thanks for the confirmation, closing this issue.

**Comment by Mepecbe** [comment]
Проверьте, точно ли вы используете порт 443 для HTTPS запросов
