### ISSUE TITLE
request.url adds a "/" at the end of URL in v7.25

### ISSUE THREAD

**Issue by gonzalojorge** [a85/POSTMan-Chrome-Extension#8545]
**Describe the bug**
Starting in v7.25, the Postman "request.url" seems to append a / at the end of defined URL.
eg. when doing a POST to https://test.com, the request.url variable will store "https://test.com".
 
This is minor, but when a Postman user has scripting logic to match the request.url with a variable, it may cause issues.

**To Reproduce**
1. Add a URL in the Postman URL section with no / at the end.
2. Add scripting logic to capture request.url (eg. console.log(request.url);)
3. Send a request.
4. Compare both strings.

**Expected behavior**
The expectation is that the URL is not modified in runtime (no / added at the end of the URL).

 

**Screenshots**
Screenshot of a console.log(request.url); vs the URL in the Postman URL section: 
![Capture](https://user-images.githubusercontent.com/41925924/82938885-17980a80-9f58-11ea-9104-3203fe7d1e77.PNG)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.25
 - OS: Win 10

**Additional context**
The problem seems to start with v7.25.

**Comment by codenirvana** [comment]
@gonzalojorge I can understand your use-case but since v7.25 `pm.request` in a pre-request script is the user authored request whereas in a test script it represents the final form of the request which was sent over the wire.
