### ISSUE TITLE
Unable to match a simple Soap body with `x-mock-match-request-body`

### ISSUE THREAD

**Issue by scb-haukland** [a85/POSTMan-Chrome-Extension#8549]
**Describe the bug**
Unable to match a simple Soap body with `x-mock-match-request-body`.

**To Reproduce**
1. Create an example for a mock server with any url, any http verb and any response
    - e.g. `POST {{url}}/test` with the response:
```
    {
        "test":"test"
    }
```
2. Add the following request body in the example:
```
    <soap:Envelope>
    </soap:Envelope>
```
3. Create a request pointed at the example url with the same body as the example body
4. Send the request
5. Add the header `x-mock-match-request-body` and give the value `true`
6. Send the request

**Expected behavior**

Step 4 is expected to return the example response as the body is not matched and the http verb and url path is correct - this works as expected

Step 6 is expected to return the example response as the body is the same as specified in the example and the http verb and url path is correct - this does NOT work as expected

**Screenshots**
Mock example:
![image](https://user-images.githubusercontent.com/66007557/83003347-7a4bdd80-a00e-11ea-9f57-110858b575d5.png)
Mock example headers and response:
![image](https://user-images.githubusercontent.com/66007557/83003509-b5e6a780-a00e-11ea-9d29-954e9f29d7e5.png)

Request with body matching:
![image](https://user-images.githubusercontent.com/66007557/83003617-dadb1a80-a00e-11ea-87a5-ea41fb3e1816.png)
Headers and response:
![image](https://user-images.githubusercontent.com/66007557/83003656-e890a000-a00e-11ea-8aaf-c865b0c4bde2.png)

Headers and response without body matching:
![image](https://user-images.githubusercontent.com/66007557/83003739-065e0500-a00f-11ea-803b-eccb4fe7a6f5.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 7.24.0]
 - OS: [Windows 10 Enterprise]

**Comment by scb-haukland** [comment]
Works with JSON:
Response with matching body header and mathing body:
![image](https://user-images.githubusercontent.com/66007557/83006420-7cb03680-a012-11ea-81b2-6e6ec238c619.png)
The mathcing body:
![image](https://user-images.githubusercontent.com/66007557/83006460-8afe5280-a012-11ea-8f1c-0eae68fa3c7c.png)
The example definition
![image](https://user-images.githubusercontent.com/66007557/83006505-9e112280-a012-11ea-9fe9-bf5fd7b2accd.png)

**Comment by pranayat** [comment]
@scb-haukland Can you confirm if you have the header `Content-Type: application/xml` set in both:
1. The request sent to the mock server
2. The example request

**Comment by scb-haukland** [comment]
Thank you @pranaya94, this solved my isuue
