### ISSUE TITLE
Bad data in COVID-19 API

### ISSUE THREAD

**Issue by emarquit** [a85/POSTMan-Chrome-Extension#8553]
**Describe the bug**
The first two characters appear to be missing from each contact email address in the "[County Health Departments for All 50 US States](https://documenter.getpostman.com/view/8854915/SzYXVdyQ?version=latest)" list

**To Reproduce**
1. Go to https://documenter.getpostman.com/view/8854915/SzYXVdyQ?version=latest
2. Load any of the state contact lists
3. Observe the email addresses in the resulting list; they all appear to be missing the first ~2 characters

**Expected behavior**
Each email address would be complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/66038686/83075505-d7ed2380-a028-11ea-9852-b73796fe8e89.png)

**Comment by DannyDainton** [comment]
Hey @emarquit 

Would you be able to raise this issue on the https://github.com/postmanlabs/covid-19-apis repo, please?

**Comment by emarquit** [comment]
OK, done: https://github.com/postmanlabs/covid-19-apis/issues/288 

Thanks for pointing me in the right direction @DannyDainton .
