### ISSUE TITLE
Disable automatic header per request

### ISSUE THREAD

**Issue by pawoolley** [a85/POSTMan-Chrome-Extension#8556]
I would like the ability to disable/exclude an automatically added header on a request.

_Postman for Mac
Version 7.25.0
OS X 19.4.0 / x64_

**Is your feature request related to a problem? Please describe.**

My use case is this:  I have setup Cookie Management for domain "my-domain" and have 2 URLs under that domain that I am making requests to.

Request no. 1 to "my-domain" is used to create an access token.  For this request, I am happy for Postman to automatically add the "Cookie" header to the request.  For request no. 2 to "my-domain", I would now like to use the access token that I got from request no. 1 in an "Authorization: Bearer ..." header.  For request no. 2, I *don't* want the "Cookie" header automatically added.  I want to be 100% sure that request no. 2 is succeeding because of the credentials in the "Authorization" header, not because of the automatically added "Cookie" header.

To achieve this, I have to go in to Cookie Management and manually remove the cookie.  The problem now is that the cookie is removed from *all* requests, not just request no. 2.

If I want to redo the test, I have to keep going round the cycle of manually adding and removing cookies via Cookie Management.

**Describe the solution you'd like**
On an individual request, I would like the option to disable/exclude the automatic adding of a header(s), perhaps by being allow to tick/untick the box next to the automatically added header.  In my use case, I can let Cookie Management do it's thing as normal with request no. 1, but I can choose to not have the "Cookie" header automatically added to request no. 2.

**Describe alternatives you've considered**
As described above, the workaround I have at the minute is to keep adding and removing cookies from Cookie Management.

**Comment by appurva21** [comment]
Hey @pawoolley !!
We got your use case covered 😄  There are two possible ways to solve your issue:

1. **Using Request setting**: You can go to the `Settings` tab inside your 2nd request and look for the `Disable cookie jar` setting. Turning this on will prevent existing cookies in the cookie jar from being added as a header for this request. Also, it will prevent cookies used in this request from being stored in the cookie jar.
![image](https://user-images.githubusercontent.com/24985700/83138106-ee1de100-a107-11ea-8294-36f89658ccf2.png)


2. **Using Programmatic access on cookies**: You can whitelist your domain inside the Cookie Manager modal and then clear the cookie jar in a pre-request script of the 2nd request.
![image](https://user-images.githubusercontent.com/24985700/83137896-8ff0fe00-a107-11ea-936e-63469eb9609d.png)
![image](https://user-images.githubusercontent.com/24985700/83138506-85833400-a108-11ea-9111-2d6ed28cd6dd.png)

You can read more about Programtically accessing cookies [here](https://learning.postman.com/docs/postman/sending-api-requests/cookies/#programmatic-access-of-cookies)

**Comment by pawoolley** [comment]
Thank you, Appurva.  That's awesome!  I felt like there might be a way to do it, but just couldn't seem to figure it out.  And thank you for the quick response.
