### ISSUE TITLE
Postman removing extra data in JSON response

### ISSUE THREAD

**Issue by mjwaddell1** [a85/POSTMan-Chrome-Extension#8557]
**Describe the bug**
When using Postman to request data, I receive a clean JSON block in the response. When requesting the same data using Curl, I get extra data after the JSON block. It appears that Postman is not displaying the extra data.

Postman response:
{
  "CandidateToken" : "oMJK8Ea08IWDz67Qk",
  "RequisitionNumber" : "70200215",
  "Language" : "US",
  "ConfirmedSubmissionFlag" : false
}

Curl response:
{
  "CandidateToken" : "oMJK8Ea08IWDz67Qk",
  "RequisitionNumber" : "70200215",
  "Language" : "US",
  "ConfirmedSubmissionFlag" : false
}This is extra data

**To Reproduce**
Use http GET. Connect to any server that returns additional text after the JSON block. I can't share our server info because it is password protected.

**Expected behavior**
The extra data should be displayed in Postman (same output as curl)

**App information (please complete the following information):**
Windows 10 Enterprise 1803
Command line curl
Postman 7.25.0

**Comment by codenirvana** [comment]
@mjwaddell1 I tried reproducing this issue using a local Node.js server.

```js
const net = require('net');

net.createServer(function (socket) {
  socket.on('data', function (chunk) {
    socket.write('HTTP/1.1 200 Ok\r\n');
    socket.write("content-type: application/json\r\n");
    socket.write("content-length: 172\r\n");
    socket.write('\r\n');
    socket.write(`{
      "CandidateToken": "oMJK8Ea08IWDz67Qk",
      "RequisitionNumber": "70200215",
      "Language": "US",
      "ConfirmedSubmissionFlag": false
    }This is extra data`);
    socket.end();
  });
}).listen(3000);
```

Working fine for me... can you let me know how can I modify this response payload to reproduce this issue locally?

<img width="1067" alt="Screenshot 2020-05-28 at 9 14 16 PM" src="https://user-images.githubusercontent.com/4865836/83163069-351bce80-a128-11ea-819a-c1eee936a943.png">

**Comment by mjwaddell1** [comment]
Our vendor has updated their server to remove the extra data. I cannot reproduce now. Thanks for your help.
