### ISSUE TITLE
Using variable set with ISO 8601 date is not working

### ISSUE THREAD

**Issue by mantonellipartner** [a85/POSTMan-Chrome-Extension#8563]
**Describe the bug**
I'm trying to send a request to the ovh APIs. It seems that when I set a variable {{dateIsoNow}}, whatever if it is environment, globals or collection with an ISO 8601 date, the variable is not working properly.

If I use this same date in parameter, without using {{dateIsoNow}} it's working perfectly.

**To Reproduce**
**Test 1 :** 
1.Go to Prerequest and set your request as follow:

var dateIsoNow = new Date().toISOString();
pm.globals.set("dateIsoNow", dateIsoNow);

2. Try to use it as paremeter, it's not working. 
**Test 2:**
1. Set you environment variable directly in the environment collection.
dateIsoNow : 2020-05-29T07:49:13.803Z

2. Try to use it as paremeter, it's not working. 

**Test 3:**
1. Using directly the date 2020-05-29T07:49:13.803Z and it's working.

**Test 4:**

When I copy/paste the result of the variable set globals, variables or environnent from setting:
![image](https://user-images.githubusercontent.com/49745466/83240408-a6e03080-a199-11ea-967a-2be4b1a3b5c7.png)

Into a bloc note I have a space or break line at the end of my date. 

I hope you understood the issue, I can't share the proper API because we have all the information about credential, signature ....

Thank's for your help.

**Comment by codenirvana** [comment]
I am not able to understand the issue from the steps you have provided.
Is it possible for you to create a sample collection using some [echo APIs](http://postman-echo.com/) which we can use to reproduce this issue locally?

**Comment by mccannt** [comment]
Closing. If this is still an issue please re-open with the requested details and we will investigate.
