### ISSUE TITLE
webservice interface return xml is code statemented

### ISSUE THREAD

**Issue by likeer** [a85/POSTMan-Chrome-Extension#8566]
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Body>
        <ns1:submitDataTResponse soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns1="http://control.kernel.midplat.lis.sinosoft.com">
            <submitDataTReturn xsi:type="xsd:string">&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;TranData&gt;
  &lt;BaseInfo&gt;
    &lt;Flag&gt;009999&lt;/Flag&gt;
    &lt;FlagCode&gt;4200&lt;/FlagCode&gt;
    &lt;Desc&gt;&#x540C;&#x4E00;&#x4EA4;&#x6613;&#x6D41;&#x6C34;&#x53F7;&#x53EA;&#x80FD;&#x5F55;&#x5165;&#x4E00;&#x6B21;&lt;/Desc&gt;
    &lt;TransrNo&gt;SD158382536975640030131&lt;/TransrNo&gt;
    &lt;FunctionFlag&gt;09&lt;/FunctionFlag&gt;
    &lt;BankDate&gt;20200529&lt;/BankDate&gt;
    &lt;BankTime&gt;183517&lt;/BankTime&gt;
  &lt;/BaseInfo&gt;
&lt;/TranData&gt;
</submitDataTReturn>
        </ns1:submitDataTResponse>
    </soapenv:Body>
</soapenv:Envelope>

**Describe the bug**
webservice interface return xml is code statemented

**Expected behavior**
Normal character format

**App information (please complete the following information):**
 - Postman Version [e.g. 7.25.0]
 - OS: windows 11

**Comment by kamalaknn** [comment]
@likeer Could you give us more information about the issue you are facing?

Could you describe more what you mean by `code statemented` and what you would expect as the right behavior? 

If you could attach screenshots of the issue you are seeing, that would be useful too.

**Comment by DannyDainton** [comment]
Closing issue due to age and inactivity - If you're still facing this problem, please provide more contextual information which will allow us to investigate further.
