### ISSUE TITLE
Code-gen in documenter becomes illegible with darker background colors

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#8571]
**Describe the bug**
The code generation feature becomes illegible when a darker background color has been selected for the documentation.

**To Reproduce**
1. Go to https://documenter.getpostman.com/view/3407886/RWgp1fB5
2. Click on the nut icon to open the code-gen feature.

**Expected behavior**
The text should be legible and the font color should adapt to the background color.

**Screenshots**
![image](https://user-images.githubusercontent.com/12631777/83439361-9ca38800-a460-11ea-80e4-c20768c50909.png)

Also reported here: https://community.postman.com/t/all-popups-showing-weird-dark-background/13021/3

**Comment by DannyDainton** [comment]
@sivcan Is this one that we can close out now?

**Comment by DannyDainton** [comment]
This issue has now been fixed.
