### ISSUE TITLE
301 redirect doesn't respect HTTP method

### ISSUE THREAD

**Issue by streamlinenz** [a85/POSTMan-Chrome-Extension#8572]
**Describe the bug**
301 redirect doesn't respect HTTP method

**To Reproduce**
Create a new method that will trigger server-side 301 response.
If the original config is anything other than GET the call will fail as Postmane will call the new redirected URL using GET methos

**Expected behavior**
301 redirection should respect original method

**Screenshots**
Output from CloudWatch for affected call.
The call triggers a 301 because it is trying to strip the trailing / from the call:
`
2020-06-02T12:02:20.116+12:00 - - [02/Jun/2020:00:02:20 +0000] "PUT /api/test/put/ HTTP/1.1" 301 258 "-" "PostmanRuntime/7.25.0"
-- | --`
`  | 2020-06-02T12:02:20.214+12:00 - - [02/Jun/2020:00:02:20 +0000] "GET /api/test/put HTTP/1.1" 405 329510 "https://hostname.domain.com/api/test/put/" "PostmanRuntime/7.25.0"
`

**App information (please complete the following information):**
 - Native app
 - Postman Version 7.25.0 (7.25.0)
 - OS: MacOS Catalina 10.15.5 (19F101)

**Comment by xk0der** [comment]
Hey @damianmk 

I believe this is intentional!

Quoting from: https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

> **Permanent Redirection** `301`, `308`
> The specification did not intend to allow method changes, but there are existing user agents that do change their method. 308 was created to remove the ambiguity of the behavior when using non-GET methods.

> **Temporary Redirection** `302`, `303`, `307`
> The specification did not intend to allow method changes, but there are existing user agents that do change their method. 307 was created to remove the ambiguity of the behavior when using non-GET methods.

I tested a redirect using `307` and `308` response codes using a test server and in both cases, the HTTP method was preserved.

I will nevertheless leave this open for the Postman engineers to qualify.

**Comment by codenirvana** [comment]
@damianmk I hope enabling "Follow original HTTP Method" request setting will fix your issue.

<img width="910" alt="Screenshot 2020-06-02 at 11 55 36 AM" src="https://user-images.githubusercontent.com/4865836/83487099-099e3880-a4c8-11ea-88d7-a0e9cdf9c9fa.png">

**Comment by xk0der** [comment]
Thanks for the help, @codenirvana ! 🎉 

Closing this, as there is a per-request setting to get the required behaviour.
