### ISSUE TITLE
Snap Postman Custom Proxy not working

### ISSUE THREAD

**Issue by Ratatinator97** [a85/POSTMan-Chrome-Extension#8573]
**Describe the bug**
Postman Snap : Porxy setting not working.

When I launch Postman with : `postman --proxy-server=127.0.0.1:3128` it works perfectly but when I configure the custom proxy inside postman it does not ! 

**To Reproduce**
1. Install snap on ubuntu 18.04
2. Install Postman via snap
3. launch postman
4. Go to params > proxy settings > Custom proxy > addr: 127.0.0.1 port: 3128
5. Reload Postman 
6. Internet still not working in postman

`1591086941079 main info "Booting Postman 7.25.1, linux-4.15.0-64-generic on x64"
1591086941080 main info "EventBus~initialize - Success"
1591086941082 main warn "CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/live/snap/postman/110/.config/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/home/live/snap/postman/110/.config/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/home/live/snap/postman/110/.config/Postman/Postman_Config/proxy'"}
1591086941083 main info "CloudProxyManager~init - Success"
`

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - Snap
 - Version 7.25.1
 - Ubuntu 18.04

**Comment by codenirvana** [comment]
@Ratatinator97 Did you encounter this after upgrading or has this issue always been there?
Could you please answer the following in order to help us triage this issue better? - 

* Are you using the proxy for just sending requests though Postman or to connect to Postman online services?
* Could you verify if you are able to send requests using Postman after setting the Custom Proxy Settings? 
* Could you share a screenshot of the proxy settings modal ? **Please hide any sensitive information such as username, password, etc. before sharing the screenshot**

**Comment by Ratatinator97** [comment]
I just have installed it on a Virtual Machine (ubuntu 18.04),
1) I want to use the proxy for both (postman online services in order to sync my workspace with my team and Requests through postman to test some APIs)
2) Yes I am able to send some requests, so the proxy is working on requests
3) 
![2020-06-02 13_15_06-LIVE18  En fonction  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/45072484/83514039-255b0c00-a4d3-11ea-8cd6-c90af6b3b3d1.png)

**Comment by ankurdengla** [comment]
Hey @Ratatinator97 ! 

The custom proxy settings are under the `Proxy configuration for sending requests` section. This means that currently these only apply to sending requests and not for Postman online services such login, syncing etc. 

For other Postman online features, we currently only support your system's default proxy settings. So the ways to use your custom proxy for these are - 
* Setting the proxy configuration `127.0.0.1:3128` in your system's proxy settings
* Or you could just pass a `proxy-server` param when launching the app from the command line (As you tried out before)

**Comment by Ratatinator97** [comment]
Okay my bad, thanks for that :)
