### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by hgorina** [a85/POSTMan-Chrome-Extension#8576]
**Describe the bug**
was trying to run more then 5000 iterations,
iterations were run successfully to 16%, then stalled and memory leak started. For an hour memory usage kept climbing while iterations stopped.
I had to kill application in task manager
No record of that run in the collection runner

**To Reproduce**

**Expected behavior**
iterations finish or some kind of feedback.
memory should not climb when iterations not proceeding
If there is a limitation to number of iterations, I am not aware (newbie)
**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - Native App
 - Postman Version Postman v7.23.0
 - OS: Windows 10
**Additional context**
I will update postman and will try to run 2000 at a time, see what happens

**Comment by mccannt** [comment]
@hgorina Just checking on on this as we have been making regular performance improvements.

Have you updated to the most recent version of the app and tried this again?

**Comment by mccannt** [comment]
Closing this due to non-response. 
Feel free to re-open if this is still an issue.
