### ISSUE TITLE
Write to File

### ISSUE THREAD

**Issue by rfmartorelli** [a85/POSTMan-Chrome-Extension#8578]
Issue: When running large collections via the collection runner, although I can see the responses there is no easy way within postman to write them to a file.  Additionally, I would like to write the console output to a file.  For testing, I do a lot of parsing and output to easily see the important information from my responses so this information is sometimes more valuable to me than the actual responses.

Current workaround: I use newman, but I'd prefer to stay within postman.

**Comment by DannyDainton** [comment]
Hey @rfmartorelli,

This has been recently asked over on our [community site](https://community.postman.com/t/how-to-download-file-while-running-collection-runner/13080)

The response provided in the thread includes a solution that should help you achieve that when working with the Collection Runner.

**Comment by sivcan** [comment]
There's a [workaround suggested in the community](https://community.postman.com/t/need-to-capture-response-body-of-each-iteration/3657/2) that you can follow and achieve this.
