### ISSUE TITLE
Collections and sets of environment variables are duplicated 

### ISSUE THREAD

**Issue by automagiq** [a85/POSTMan-Chrome-Extension#8581]
Postman Version 7.25.2. OS X 19.5.0 / x64
After I created Postman Account and added a new workspace and now when I switch to Personal workspace I  see that some of my collections and set of environment variables are duplicated.

How to resolve this?

**Comment by DannyDainton** [comment]
Hey @automagiq 

Would you be able to provide a details example of what you're seeing, please? This will allow us to investigate what's going on here.

**Comment by automagiq** [comment]
<img width="1679" alt="Screen Shot 2020-06-04 at 9 56 24 AM" src="https://user-images.githubusercontent.com/49632874/83780364-4eea7380-a64a-11ea-923f-e8801e53c195.png">

**Comment by DannyDainton** [comment]
Hey @automagiq 

Are these showing as duplicates in the `Browse` mode? The mode switcher can be found in the bottom right of the application.

Would you also be able to check these on the Dashboard in a Browsers - https://go.postman.co/

Just trying to gather more information 😄

**Comment by automagiq** [comment]
<img width="1405" alt="Screen Shot 2020-06-10 at 11 18 35 AM" src="https://user-images.githubusercontent.com/49632874/84298303-23fd9500-ab0c-11ea-8a76-8ce3e3a7ac5b.png">
Yes it is duplicated showing as duplicates in the Browse mode too.

**Comment by automagiq** [comment]
<img width="1624" alt="Screen Shot 2020-06-10 at 11 20 31 AM" src="https://user-images.githubusercontent.com/49632874/84299728-73dd5b80-ab0e-11ea-8431-fe173dacc27d.png">

**Comment by vvs11** [comment]
@automagiq could you write to us at help@getpostman.com? We will be able to support you better.

**Comment by Raj-postman** [comment]
There was an issue with syncing, for which improvement fixes were released in the latest version. Hence, closing this GitHub issue 🎉
