### ISSUE TITLE
Allow "-" in the domain name for the Identity Provider Issuer field on Postman SSO configuration

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#8582]
**Is your feature request related to a problem? Please describe.**
User see's a client-side validation message 'Please enter a valid URL'  when they add in the Identity Provider Issuer with a "-" in the domain name during Postman SSO configuration.
Example: "https://idp-issuer.team.com/idp/SSO.saml2"

**Describe the solution you'd like**
User should be allowed to enter a "-" in the domain name for the Identity Provider Issuer field.

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved in version: Dashboard v2.29.0
Please feel free to reopen with the steps to reproduce if the issue persists.
