### ISSUE TITLE
Postmain fails to display plaintext response

### ISSUE THREAD

**Issue by racinmat** [a85/POSTMan-Chrome-Extension#8584]
**Describe the bug**
Postman fails for following request:
here is the request saved in collection
```json
{
	"info": {
		"_postman_id": "8ac6ea90-5552-4a56-a80c-d7386950e09b",
		"name": "julia package server",
		"description": "Things to try julia package server",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "registries",
			"protocolProfileBehavior": {
				"disabledSystemHeaders": {
					"accept": true, "user-agent": true, "accept-encoding": true, "connection": true
				}
			},
			"request": {
				"method": "GET",
				"header": [{"key": "Accept-Encoding", "value": "*", "type": "text"},
					{"key": "Content-Type", "value": "text/plain", "type": "text"}
				],
				"url": {
					"raw": "https://eu.pkg.julialang.org/registries",
					"protocol": "https",
					"host": ["eu","pkg","julialang","org"],
					"path": ["registries"]
				}
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}
```

**To Reproduce**
Run the query.

**Expected behavior**
When it's ran as curl command which is generated from the Postman, I obtain desired response:
```
C:\Users\racinsky>curl --location --request GET "https://eu.pkg.julialang.org/registries" --header "Accept-Encoding: *" --header "Content-Type: text/plain"
/registry/23338594-aafe-5451-b93e-139f81909106/808c9ccc5e89d3eb1201eccc40f134eb2a9d0f6a
```
but postman fails to show this because there are missing headers, the server returns just this single row as response.
Is it possible to use Postman for such responses, or should I use another tool?

**Screenshots**
![image](https://user-images.githubusercontent.com/5525771/83633031-93213980-a5a0-11ea-805c-6a9965a1dff7.png)

**App information (please complete the following information):**
 - Postman for Windows
 - Version 7.25.2
 - OS: win32 10.0.18362 / x64

**Comment by codenirvana** [comment]
@racinmat It looks like that the requesting server is responding with `Content-Encoding: gzip` response header but plain text response body.

**Comment by racinmat** [comment]
And is there a way to force postman to ignore the wrong encoding?

**Comment by codenirvana** [comment]
I am afraid there's no way to disable that (since `Content-Encoding` is present) at the moment.

**Comment by racinmat** [comment]
I see, thanks, I will report it then as an issue to the server.
