### ISSUE TITLE
How to Identify the random required node value from a response 

### ISSUE THREAD

**Issue by ArunSNambiar** [a85/POSTMan-Chrome-Extension#8585]
[
{
"client_code": 29,
"known_as": null,
"title": "Ms",
"forename": "Test",
"surname": "Client",
"date_of_birth": "1972-04-19T00:00:00Z",
"gender": "Female",
"has_photo": false
},
{
"client_code": 40456,
"known_as": null,
"title": "Dr",
"forename": "Arun",
"surname": "Nambiar",
"date_of_birth": null,
"gender": "",
"has_photo": false
.
.
.
}
]

This is the response from a postman. I want to identify the 'client_code' of a client which is having its forname='Arun' from the response. How Can I find it..
I tried by using json path finder but each time when new client gets created, the index varies. 
Please help.  

I should be able to change the string value of forename/surname for next execution and should be able to identify respective client code. Please have a look.

**Comment by arlemi** [comment]
@ArunSNambiar Please ask this question on the community forum: https://community.postman.com/
