### ISSUE TITLE
Text is not rendered as string in collection Runner

### ISSUE THREAD

**Issue by alagu-chandran** [a85/POSTMan-Chrome-Extension#8586]
Error
I try to import the CSV file, with data contains string and number. When seeing the Preview (Screenshot 1), string is enclosed in the double Quotes. But when collection runner plotted in the request body, it didn't surround by the quotes(Screenshot 2). and even it doesn't consider this as a String.

To Reproduce
1. Import the csv file in the collection runner
2. use the variable inside the request body

**Expected behavior**
The field should be considered as text field

**Screenshots**
Screenshot 1
<img width="666" alt="Screenshot 2020-06-04 at 10 37 31 AM" src="https://user-images.githubusercontent.com/48908149/83717131-83acf980-a64f-11ea-9ee4-cddb4ea3e37a.png">

Screenshot 2

<img width="586" alt="Screenshot 2020-06-04 at 10 41 59 AM" src="https://user-images.githubusercontent.com/48908149/83717355-249bb480-a650-11ea-9533-a05ed1cae5b3.png">

**App information **
 - App Type [Native App]
 - Postman Version [Version 7.25.0 (7.25.0)]
 - OS: [e.g. macOS Catalina 10.15.4]

**Comment by mccannt** [comment]
@alagu-chandran 
Thanks for reaching out. I am curious if you are wrapping your values that are expected to be a string in quotes? 

For example:
![image](https://user-images.githubusercontent.com/14275144/84278203-d6345d00-ab0a-11ea-941f-8faba1ef644c.png)

It does look like we may have an issue in the Preview where we have logic that assumes a type based on the value.

**Comment by alagu-chandran** [comment]
@mccannt 
Thanks for reaching out, thing is when collection runs from data set it renders payload as following
```
{
  "test": {
    "text1": Hello,
    "number": {{num}},
    "text2": "world"
  }
}

instead of this
{
  "test": {
    "text1": "Hello",
    "number": {{num}},
    "text2": "world"
  }
}
```

The problem is "text1" is not rendered as text in the collection runner for the first field itself. That's the problem we are trying to eliminate

**Comment by mccannt** [comment]
@alagu-chandran 
The preview screen, when working with a data file, assumes a type based on what it sees in the field. This is not necessarily absolute and assumed everywhere. 

So when you make your calls, if you are expecting a type = string for the field "text1". My advice would be to wrap it in quotes to avoid this from happening and then you can ensure that it will be treated as a string, much like you did with "text2" in your example.

**Comment by alagu-chandran** [comment]
@mccannt 

It's working as expected. thanks for clarifying us.
