### ISSUE TITLE
Add Network Throttling Setting to Postman

### ISSUE THREAD

**Issue by Laurence-Walpole** [a85/POSTMan-Chrome-Extension#8588]
**Is your feature request related to a problem? Please describe.**
Postman is great for testing APIs in a sandbox environment. However, it is not great for testing them in a simulated environment. Firefox and Chrome both have built in "Network Throttling" settings, which simulates a poor network connection. Postman does not have this.

**Describe the solution you'd like**
The ability to add a network throttle to sent requests (no, using the Chrome debugger does not work).

**Describe alternatives you've considered**
Installing a 3rd-party app which ALL my network traffic would have to go through, throughout the duration of my testing.

**Additional context**
Just a simple dropdown in the request Settings tab pane, that allows you to select from a multitude of network throttle options (Firefox does this VERY well).
![image](https://user-images.githubusercontent.com/14222028/83753775-ccba7900-a662-11ea-84be-9dd7f1ead518.png)

**Comment by codenirvana** [comment]
@Laurence-Walpole Thanks for the feature request but we are already tracking a similar feature request #3777.

This will be a great addition and we will try to prioritize this as soon as possible.
Closing this, Please follow #3777 for more updates on this.
