### ISSUE TITLE
Unable to recover archived collection

### ISSUE THREAD

**Issue by dbethel** [a85/POSTMan-Chrome-Extension#8591]
I was using a shared collection and when I saved a new request, the entire collection got archived and I am no longer able to access any of the requests. I understand that it is a free account and it is limited, but archiving the collection in this manner is absurd and cannot possibly be the intended action.  I could see an error saying that I am past my limit and cannot save anymore or something like that.  What a horrible user experience.

**Comment by Raj-postman** [comment]
Hi @dbethel 

In the latest version of the application - we have added a prompt message that warns users at regular intervals when they are about to hit the free limits. But we do understand the confusion around the archiving flows and our team is working towards making it more intuitive. We are currently tracking this request on this GitHub link here: https://github.com/postmanlabs/postman-app-support/issues/7654

Add any additional comments on the same thread that will help our team look into it while building this :)

You should be able to recover all of your archived collection by [following this link here](https://www.youtube.com/watch?v=Bei42qAtdLs). Hope this helps!

**Comment by Raj-postman** [comment]
@dbethel Hope you were able to recover the archived collections via reference. Do let us know if you face any issues with the same.

**Comment by dbethel** [comment]
Thank you, I was able to recover most of what I had lost.  I just wanted to let you guys know what a terrible user experience this was and how much time/work I lost due to the poor user experience.
