### ISSUE TITLE
resolve synch conflicts popup keeps appearing

### ISSUE THREAD

**Issue by bitcoder** [a85/POSTMan-Chrome-Extension#8593]
**Describe the bug**

**To Reproduce**

1. use Postman for a while with a logged in account
1. create some requests

**Expected behavior**
No synch errors should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/553801/83907450-53538100-a75d-11ea-8237-b1449bb8c758.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.25.2
 - OS: MacOS 10.15.4

**Additional context**
This problem still happens as mentioned earlier on  #4360  and is quite annoying.
The conflicts make no sense. I'm a single and only user editing the collection. More, as you can see Postman thinks there are conflicts in all requests even though there are no differences.

Besides fixing this issue, I kindly suggest a slight UI improvement:
- To have a possibility of choosing to "Use all local changes", as with the default behaviour users have to go over all the requests and opt for the local changes (otherwise, information is lost as it happened to me)

**Comment by dzykovic** [comment]
I have the same issue, clicking sync or reset does not help, it hides dialog for a while and then it comes again. I am working alone on collection from a single pc, any update conflicts are not expected. I noticed that when I export collection and compare changes after sync - only field order changed in some places in the json file, values not changed. Also, I noticed that sync is quite slow, can take a minute or more while spinning sync icon - not sure if it is related. And also more often I see sync conflicts when PC resumes from sleep. Besides that removing collection online or locally and re-importing from a file also does not help.

**Comment by bitcoder** [comment]
this is really frustrating and makes using the product almost impossible. How can't this be prioritized over new features?

**Comment by postman-evaluations** [comment]
@dzykovic @bitcoder We have identified couple of issues with the modal and are working on fixing them. They will be out on production app next month. I will triage this specific issue and post an update.

**Comment by kartikjain26** [comment]
@dzykovic @bitcoder We have identified couple of issues with the modal and are working on fixing them. They will be out on production app next month. I will triage this specific issue and post an update.

**Comment by mccannt** [comment]
This should now be resolved. Closing the issue, please feel free to reopen if this is still an issue.
