### ISSUE TITLE
Locating a single request in the Collections tree views

### ISSUE THREAD

**Issue by spacentime** [a85/POSTMan-Chrome-Extension#8603]
While working with many Postman request and navigating through the tabs , there is no way to see where a single request which is now an open tab is located in the Tree view, so you don't really know where it belongs - even when using properly naming convection it is not a easy to do task especially when you have multiple versions of a similar request.

Visual Studio has a feature to locate the active document in the Solution view and it's named "“Sync with Active Document” and looks like double arrows

**Comment by kamalaknn** [comment]
Hey @spacentime 

Thank you for your feedback. We are tracking this request in #7099. 

I'm closing this as a duplicate. Please follow the original thread for updates.
