### ISSUE TITLE
Add setting to control Postman's use of discrete or integrated GPUs

### ISSUE THREAD

**Issue by pratnala** [a85/POSTMan-Chrome-Extension#8605]
**Describe the bug**

Postman is using the discrete NVIDIA GPU that is present on my laptop

**To Reproduce**

1. Open Postman
2. Check NVIDIA GPU Activity
3. You will see Postman listed as using the GPU

**Expected behavior**

NVIDIA GPU is generally used by games or other graphically intensive programs. I would expect Postman to use the integrated GPU as it is not a graphically intensive program.

**Screenshots**

![Screenshot of NVIDIA GPU Activity showing Postman using the GPU](https://user-images.githubusercontent.com/1689565/84103037-d4618100-a9c6-11ea-8ecf-2ec82227a3c6.png)

**App information**

 - App Type: Postman for Windows
 - Postman Version: 7.26.0
 - OS: Windows 10 x64 2004 (19041.264)

**Additional context**

I don't know when this started happening but I only noticed it today. It is possible it started in a previous version too.

**Comment by numaanashraf** [comment]
@pratnala Postman uses the discrete GPU by default for better UI rendering performance. There is a flag that can be set to control this - instructions are [here](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621).

**Comment by numaanashraf** [comment]
Converting this to a feature request to expose this as a configuration/setting within the application instead of a flag.

**Comment by pratnala** [comment]
Curious why it uses the discrete GPU by default? Many apps render fine using the integrated GPU, right?

**Comment by pratnala** [comment]
I can confirm that adding the environment variable works. And I don't see any downgrade in Postman's graphical performance. Thanks! 👍

**Comment by diversenok** [comment]
@numaanashraf, NVIDIA Control Panel **already has** a designated setting for selecting a discrete or integrated GPU per program.

![NVIDIA Control Panel](https://user-images.githubusercontent.com/30962924/97366307-63eccb00-18a7-11eb-8489-92ca7eb25ca2.png)

Instead of complying with the user's choice, you decided that you know better and ignore it. As a solution, you suggest something that requires modifying the system-wide configuration and a logout. Seriously? And now, you want to invent a new switch in the settings, all because you cannot do like other programs and let the user control GPU settings in the place where it is supposed to happen? 😕

**Comment by pratnala** [comment]
Closing this issue as I don't see it in recent updates.

**Comment by numaanashraf** [comment]
@pratnala This is coming in our immediate next release (v8.6.0) that is planned to rollout in the second week of June

**Comment by g-bohvalov** [comment]
Will just leave it here, as the Nvidia Settings page suggested by @diversenok doesn't work and never worked, don't think ppl are so dumb that they don't know this could be managed inside Nvidia settings.

What definitely works for Windows 10, if you have this new Graphics settings option:
![image](https://user-images.githubusercontent.com/19384845/120428767-f0e78d80-c37c-11eb-9b69-c4af1c6671ef.png)

Cheers

**Comment by DartMen** [comment]
A year has passed, and still no descent solution.

@georgealar 's method needs to be adjusted after every single postman update as the postman dev decided it would be smart to have the version number written in the filename...


edit > omg they hid it in the Help menu.. 

![image](https://user-images.githubusercontent.com/54860099/121892337-e59d4600-cd1c-11eb-9efe-4bae05c906e2.png)

Hardware Acceleration? Integrated Graphics != hardware?

Please consider making "Hardware Acceleration" unchecked per default, so users of Postman don't waste their battery life unexpectedly..

**Comment by g-bohvalov** [comment]
> A year has passed, and still no descent solution.
> 
> @georgealar 's method needs to be adjusted after every single postman update as the postman dev decided it would be smart to have the version number written in the filename...
> 
> edit > omg they hid it in the Help menu..
> 
> ![image](https://user-images.githubusercontent.com/54860099/121892337-e59d4600-cd1c-11eb-9efe-4bae05c906e2.png)
> 
> Hardware Acceleration? Integrated Graphics != hardware?
> 
> Please consider making "Hardware Acceleration" unchecked per default, so users of Postman don't waste their battery life unexpectedly..

finally, got that update today, thanks @postman-support 🙏

**Comment by jviotti** [comment]
@DartMen 

> Please consider making "Hardware Acceleration" unchecked per default, so users of Postman don't waste their battery life unexpectedly..

We would need to double-check this, though. Chromium heavily uses the GPU for various tasks, and disabling the GPU might mean a lot more work on the CPU, which could end up resulting in more battery consumption! The performance boost on hardware acceleration can also be significant depending on the machine. Apps like Google Chrome do enable it by default.

**Comment by jviotti** [comment]
I'm closing this ticket as resolved! Thanks a lot for all the great feedback!

**Comment by dstarkowski** [comment]
@jviotti 
Either the setting is named wrong, or it's not fixed. This issue is not about disabling hardware acceleration.
 
I'm running Edge, Chrome, VS Code, Azure Data Studio and Postman on my machine. All chromium based, all use hardware acceleration. Only Postman forces use of **discrete** GPU. All others are **hardware accelerated** using **integrated** GPU.

**Comment by jkonrath-postman** [comment]
PR for Learning Center docs change: https://github.com/postmanlabs/postman-docs/pull/3220

**Comment by shoaib30** [comment]
@dstarkowski  you're absolutely right. 

>  disabling the GPU might mean a lot more work on the CPU, which could end up resulting in more battery consumption!

@jviotti using the discrete GPU consumes a lot more battery than working on the CPU. The power rating of a CPU along with the integrated GPU is usually less than the power rating of a dedicated GPU. 

Not sure if **Hardware Acceleration** toggles between discrete and integrated or completely disables hardware acceleration. Ideally, it would be a toggle between **Completely off** or **Using Integrated GPU**

**Comment by steve-cp** [comment]
As this thread was the first result in Google while searching for a solution in January 2023 here's what worked for me. Postman still ignores the Windows 10 Graphics Settings, and there's nothing about GPU in the Postman settings, so Postman single-handedly prevented me to use my laptop on battery. 
But in the current UI you can find a hamburger icon in the top left corner of the window, and under it, there is a "Help/Disable Hardware Acceleration" option, which worked for me.

**Comment by aydnfb** [comment]
![image](https://github.com/postmanlabs/postman-app-support/assets/129346753/8e8f8d67-42fc-465a-92b2-57f0efc619d6)
layar postman putih, bagaimana cara nya agar kembali ke semula

**Comment by leonardo-gooten** [comment]
This is the most bizarre default behavior I've ever seen.. A simple app using discrete GPU... 
Simply destroys battery performance on windows laptops

**Comment by gulsoy83** [comment]
1. Using `POSTMAN_DISABLE_GPU=true` environment value completely turns off hardware acceleration, even if iGPU is available.
2. Using Graphics performance preference tab in Windows is useless: 
- Postman uses sneaky tactics to update itself, which changes the path of postman.exe with every new version. As a result, any graphics preference rules you create become obsolete.
- I cannot prevent Postman from auto-updating, and every time it updates, it immediately activates the dGPU. This is extremely frustrating.

The real solution would be to disable Postman’s automatic self-updates entirely. I’m this close to uninstalling it.
