### ISSUE TITLE
creating snipper for http.client in Python doesn't truncate protocol from from parameter for http.client.HTTPSConnection()

### ISSUE THREAD

**Issue by tomaszwojciechowski** [a85/POSTMan-Chrome-Extension#8610]
**Describe the bug**
When I generate snippet for http.client in Python and would like to use https protocol for endpoint's url, then in generated snippet I see:
`http.client.HTTPSConnection("https://example.com")`
while there should be just:
`http.client.HTTPSConnection("example.com")`
(without protocol in string). 

**App information:**
 - App: Native App
 - Postman Versio: 7.26.0
 - OS: Windows 10

**Comment by webholik** [comment]
@tomaszwojciechowski Are you storing the URL in a variable? There was an [issue](https://github.com/postmanlabs/postman-code-generators/issues/330) that caused the extra https:// to appear in the host, if the url was stored in a variable. But that has been fixed.

**Comment by DannyDainton** [comment]
Closing this due to age and inactivity. If this is still an issue, we can look at reopening this again.
