### ISSUE TITLE
Funcionality to zoom in and zoom out for response body

### ISSUE THREAD

**Issue by tomaszwojciechowski** [a85/POSTMan-Chrome-Extension#8615]
It would be useful to have functionality to zoom in and zoom out for response body, similar like it works in IntelliJ IDEs where you can achieve it by using mouse's scroll.

**Comment by arlemi** [comment]
You can already: 
- zoom in using Ctrl + or CMD + on the whole app
- change the font size by going to the app settings and changing the font-size

Would that solve your issue?

**Comment by tomaszwojciechowski** [comment]
Yes. Thank you.
