### ISSUE TITLE
Incorrect {{var}} highlight in example response json-body with escaped characters

### ISSUE THREAD

**Issue by zigszigsdk** [a85/POSTMan-Chrome-Extension#8616]
Description:
The highlight linter doesn't colorize {{variables}} correctly in example json-body responses (possible elsewhere too) with escaped characters. The highlight is early by the number of escaped characters before the {{variable}} and short by the same amount.

Screenshot: https://prnt.sc/sx34hw
![download](https://user-images.githubusercontent.com/4865836/84253460-9632a180-ab2d-11ea-94be-c9310ba36265.png)

Versions:
Postman v7.26.0 standalone on Win10.

**Comment by pankajk07** [comment]
@zigszigsdk , we have fixed this as part of `v7.28` release. Please update the app and try it out. Do let us know if you come across any other issues.
