### ISSUE TITLE
Windows header / title bar styling

### ISSUE THREAD

**Issue by 06MasonG** [a85/POSTMan-Chrome-Extension#8618]
It seems to be a common occurance for electron developed applications where by the header / title bar has default styling.

Very minor in terms of actual functionality but it's frustrating to see an un-styled header when the rest of the app looks so clean and styled.

Is it possible to apply styling to the header / title bar? Perhaps this package would help - https://www.npmjs.com/package/custom-electron-titlebar

![image](https://user-images.githubusercontent.com/44588748/84261170-37f8c500-ab13-11ea-9a4c-4b8e51a890c3.png)

Thanks

**Comment by arlemi** [comment]
Thanks for writing in @06MasonG , we're already tracking this in #5302. I'll close this one. 🙂
