### ISSUE TITLE
"Failed to generate some collections" on import/openapi while importing Open API specification

### ISSUE THREAD

**Issue by ducka** [a85/POSTMan-Chrome-Extension#8620]
**Describe the bug**
Recently it appears the `import/openapi` endpoint on Postman's API has started failing when our build pipeline attempts to generate collections for our APIs. When we attempt to upload a valid OpenApi specification to the `import/openapi` endpoint the endpoint responds with a HTTP 200, and a response body that states **Failed to generate some collections** for the specification we're attempting to upload.

We're only attempting to upload one specification at a time. I've uploaded the specification via the Postman UI and it's successfully imported as a collection, so i know for sure the OpenAPI specification is valid. I've double checked my request is well formed and matches your documentation (it does). There's been no changes to the deployment scripts on my side, so it seems to me like there has been a regression introduced on the `import/openapi` endpoint.

Could you please confirm, Postman?

**To Reproduce**
1. Post a valid Open API specification as type `json` or`string` to the `import/openapi`
4. You will receive a HTTP 200 response from the endpoint that looks something like this: `"{"collections":[{"error":"Failed to generate some collections","collections":["Payment Service (v1.0|QA|Internal)"]}],"environments":[]}"`

**Expected behavior**
The request should succeed and a collection should be created in Postman based off the Open API spec.

**Screenshots**
![image](https://user-images.githubusercontent.com/491226/84286842-20cbce80-ab37-11ea-8358-ecf3e0cc4776.png)

**App information (please complete the following information):**
 - App Type: Postman API

**Comment by zipzapp** [comment]
Perhaps related to this issue, I can no longer Generate a collection from a valid openAPI 3.0 JSON schema. I'm seeing a similar error message to "Failed to generate some collections" but at the end I believe it says "returned undefined". Where can i find a the error message log? I can post more details but I'm not sure where to look. This is a big part of our workflow, we need to generate collections from apis! Thank you

**Comment by umeshp7** [comment]
@zipzapp @ducka Sorry you are facing these issues. 
We have identified the issue and working on a fix to get the import working as soon as possible. 
We'll have an update for you soon.

**Comment by umeshp7** [comment]
@ducka @zipzapp 
We have added a possible fix to this issue. Could you please try importing your schema through the Postman import API and see if it works now?

**Comment by ducka** [comment]
Awesome @umeshp7, it looks the issue has been resolved. Our deployment pipeline is generating postman collections again.
