### ISSUE TITLE
Shared Requests Limit Showing every time

### ISSUE THREAD

**Issue by emzyme20** [a85/POSTMan-Chrome-Extension#8621]
**Describe the bug**
I created a Team workspace and attempted to share a collection. It warned me that I had shared more than the 25 allowed requests. I deleted the collection as I was not in a position to upgrade my plan. I am now back to using just a personal workspace and every time I open Postman it warns me that I have exceeded my sharing allowance.

I no longer have the collection. I have been unable to delete the team workspace as it warns me that you cannot delete the default workspace and the usage stats have not updated since I deleted the collection of requests being shared.

**To Reproduce**
1. Go to Postman app
1. Create a Team workspace
1. Share a collection that is too big for your free plan
1. See the error
1. Delete collection
1. Warning still shows on loading Postman and usage stats do not update

**Expected behavior**
Usage stats should reset once a collection has been deleted that was added to a team workspace.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/3832400/84296117-79a16400-ab43-11ea-9871-ec78ebab44dd.png)

**App information (please complete the following information):**
 - Chrome Version 83.0.4103.97
 - Postman Postman v7.26.0
 - OS: Windows 10

**Additional context**

**Comment by arlemi** [comment]
Are you still seeing this today? The message may take a little while to go away. 

If you're still seeing it, could you double check you do not have another team workspace?

**Comment by emzyme20** [comment]
> Are you still seeing this today? The message may take a little while to go away.
> 
> If you're still seeing it, could you double check you do not have another team workspace?

It's still there. This happened 2 weeks ago and I deleted the shared collection immediately when I realised that I couldn't use the feature on basic plan. Everyday I get that message and I think it's because I can't delete the workspace as it's the default one even though it has nothing in it anymore.

![image](https://user-images.githubusercontent.com/3832400/84376451-13672080-abd9-11ea-85a0-58c6133f5860.png)

**Comment by arlemi** [comment]
@emzyme20 Can you check if any collections are showing when you access that link? https://go.postman.co/team/elements?type=collection

**Comment by emzyme20** [comment]
> @emzyme20 Can you check if any collections are showing when you access that link? https://go.postman.co/team/elements?type=collection

Yes, I see my personal workspace collections and I have circled the 2 collections that I created in the team workspace but have subsequently deleted..

![image](https://user-images.githubusercontent.com/3832400/84379233-6347e680-abdd-11ea-9a37-8dc6e4aa8d03.png)

There is no option to delete from here either. If I click on the links, I get taken to a page that has no requests in it,

**Comment by arlemi** [comment]
Looks like you ran into a rare case of orphaned collection! Can you try sharing these collections to one of your workspace (either personal or team), then make sure you use the `Delete` entry and not `Remove from Workspace`. 

Let us know if that solves it!

**Comment by emzyme20** [comment]
> Looks like you ran into a rare case of orphaned collection! Can you try sharing these collections to one of your workspace (either personal or team), then make sure you use the `Delete` entry and not `Remove from Workspace`.
> 
> Let us know if that solves it!

Yes, that solved my issue - thanks so much. I moved it to a personal workspace and deleted as you suggested.
