### ISSUE TITLE
Freezes on scrolling

### ISSUE THREAD

**Issue by garipov** [a85/POSTMan-Chrome-Extension#8624]
**Describe the bug**
After scrolling a response result the app freezes and nothing is working anymore.

**To Reproduce**
1. Open the macOS app.
2. Create new request
3. Paste some url, for example https://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=439d4b804bc8187953eb36d2a8c26a02 (the url has been copied from [example](https://openweathermap.org/current))
4. Scroll down to watch result, then scroll up, and again scroll down/up several times.
5. My version of app freezes at this moment.

**Expected behavior**
The app continues to live. I can scroll as many times as I want.

**Screenshots**
I've recorded the [video](https://yadi.sk/i/dS1ZYemPUDBvEA)

**App information (please complete the following information):**
 - macOS native app
 - Postman Version 7.26.0
 - OS: macOS Catalina 10.15.4

**Comment by garipov** [comment]
Tried to update my OS to macOS Catalina 10.15.5. But nothing changed with this behavior.

**Comment by numaanashraf** [comment]
@garipov Would it be possible to record and share a performance profile? It'll help us triage the issue and resolve as soon as possible.

Here's the how-to on recording a profile: https://www.loom.com/share/01e103f8511549ec93e22ff2afb2769e

**Comment by garipov** [comment]
Hm... I tried to do that but the performance tool froze also.
And then It didn't appear any more.

I'll observe on it. If it doesn't happen again, I'll close the issue.

**Comment by garipov** [comment]
Well, I didn't catch that anymore. 🤷‍♂️ Close issue.
Could be reopened if something changes.

**Comment by mkoppanen** [comment]
Sorry to comment on a closed issue but seeing the same behaviour. It's not reproducible (at least not reliably) but will do more tests tomorrow. It seems to happen after following patterns:

1. Use postman for a while to interact with an API
2. At some point scroll a paged API response (JSON) all the way down
3. Result: postman stops responding completely. On dock it's not suggesting "Force Quit" but rather "Quit" and quitting the process exits immediately

**Comment by arlemi** [comment]
Hey @mkoppanen, please open a new issue if you manage to replicate it, you can also include your logs to make it easier for us to replicate and fix: https://support.getpostman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-
