### ISSUE TITLE
msg 

### ISSUE THREAD

**Issue by marcojsa** [a85/POSTMan-Chrome-Extension#8625]
Hi all,

I'm trying to send an API request to Zoho CRM using Postman. Zoho uses the OAuth2.0 Authentication method, and it's very easy to get the access token through Postman using the Zoho CRM Collection, but when I try to make a request a msgbox appears with the following message:

"There was an error in evaluating the Pre-request Script:  undefined: access-token is empty or expired"

I found in many forums another persons with the same issue, but none of the proposed solutions worked for me, so I decided to contact Zoho support. I shared my screen with a Zoho developer and he tried for hours to fix that. We tried to insert lots of scripts into Pre-Request Scripts tab, defining the access-token variable, we tried to set access-token as a global variable but nothing worked (and the access token was not expired).

So Zoho's developer told me it's an issue in Postman and suggested me contact Postman to fix this bug, but watching a tutorial video made by Zoho (https://www.youtube.com/watch?v=ETlhFkx47rg&t) they follow exactly the same steps I did without any issue...
anyone could kindly help me with that? I'm attaching Postman's screenshots with my setup and the scripts we used into Pre-Request Scripts.
![PM1](https://user-images.githubusercontent.com/18744929/84338640-f7c92f00-ab72-11ea-80e6-b64ecdb29e17.PNG)
<img width="921" alt="Img3" src="https://user-images.githubusercontent.com/18744929/84338669-0e6f8600-ab73-11ea-8ebe-36217aa46c81.png">

Some addicional informations:
OS: Windows 10 64bits
Postman version: 7.26.0

**Comment by erigglem** [comment]
If you open a new tab in Postman, this will work without the error. Took me hours to finally figure this out.

**Comment by DannyDainton** [comment]
Hey @marcojsa 

I'm going to close this issue - If you're still experiencing this in the new version of the platform, we can look at reopening it again.
