### ISSUE TITLE
Postman isn't syncing collections (duplicated, imported, etc) from v7.26.0

### ISSUE THREAD

**Issue by tmladenovWL** [a85/POSTMan-Chrome-Extension#8627]
**Describe the bug**
Starting around the 04th of June, I or anyone on my team, we are having issues creating / duplicating / importing and then syncing to Postman's cloud any collections via Postman GUI to be visible for everyone on team's workspaces. The 'update' button is turning all the time but no collection appears on Postman's portal, or appears after a huge amount of time, meaning that there's some sort of a connection problem between Postman app and Postman servers. 
The missing of these collections hugely impacts our operations as they are an initial point for our testing process.

**To Reproduce**
1. Have someone create a collection in a team workspace with access limited to themselves (mimics when we push things to Postman's API from our apps with a specific token).
3. The collection will be locked for anyone else but the person whose token was used, still, you should be able to duplicate it;
4. The duplicated collection takes forever to sync (it doesn't), hence it is missing from Postman's API and for anyone else, including the person duplicating it, it is missing from the collections under their own account;
5. You cannot set access due to error: "You are not permitted to perform the action."
6. After this point, the collection might not or might (after a lot of time) appear on Postman's portal. BUT if you do anything to the collection during syncing, like renaming, it just never appears on the portal. We experimented with this, waited for hours with no results.

**Expected behavior**
Like before the 4th of June, The syncing should be done at most in a few minutes when you create a new collection (basically) in a particular team workspace.

**Screenshots**
N/A

**App information (please complete the following information):**
 - Native App
 - version: v 7.26.0 (started at v 7.25.9)
 - OS: Windows 10 Pro, build 1909

**Additional context**
We have either Team or Business Postman license. For data privacy reasons, we'd like to know where we could contact the support via email to provide you with further details?

**Comment by vvs11** [comment]
@tmladenovWL could you write to help@getpostman.com? We will be able to help you better there

**Comment by tmladenovWL** [comment]
> @tmladenovWL could you write to [help@getpostman.com](mailto:help@getpostman.com)? We will be able to help you better there

Hello vvs11,

Thanks for your reply. I have just sent an email to this email address as you advised.

Best Regards,
Tihomir

**Comment by cyrielle-hada** [comment]
There was an issue when collections were duplicated - its syncing call was queued which caused the indefinite syncing. 
The queueing improvements were released in v7.27.1. 
Closing this GitHub issue ✅
