### ISSUE TITLE
POSTMAN closed all of a sudden. Unable to Launch. Its been more than 25 minutes.

### ISSUE THREAD

**Issue by dmoryani** [a85/POSTMan-Chrome-Extension#8628]
**Describe the bug**
Unable to launch POSTMAN ( Application).

**To Reproduce**

**Expected behavior**
It should launch faster.

**Screenshots**
![image](https://user-images.githubusercontent.com/31031890/84363492-6654ce00-ac01-11ea-8569-95f3ee3ff906.png)

POSTMAN version: 7+
MacBook Pro version:10.14.6

**Comment by ankurdengla** [comment]
Hey @dmoryani !
Sometimes inconsistencies in the underlying storage of the app can prevent the app from launching. User can unblock themselves by following this troubleshooting guide - https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

We are tracking this here - #6723

Closing this as a duplicate.
