### ISSUE TITLE
I can't tell what Collection (or Folder) a given request is for

### ISSUE THREAD

**Issue by jwbanning** [a85/POSTMan-Chrome-Extension#8629]
**Is your feature request related to a problem? Please describe.**
I deal with a lot of open tabs (requests) at times. Unless I have the related Collection and Folder (if any) open already and  scroll up/down the navigation of the Collections, I can't tell what Collection (or Folder) a given request is for. I need to  look at the request and start opening Collections and Folders to find where "its home" is. 

**Describe the solution you'd like**
Can you add a “mouse-over” function that displayed the collection name and any related folder/subfolders. I see you already have that general functionality as when you mouse-over the “Launchpad” tab, it displays “Launchpad”. For example, display the following text when you mouse-over a request tab: “Collection NameGoesHere > FolderNameGoesHere > SubfolderNameGoesHere”.

![image](https://user-images.githubusercontent.com/2584258/84389637-f6702480-abbb-11ea-931a-14ff1946fab6.png)

**Describe alternatives you've considered**
Another possibility is when you click on the tab to make it your active request in the main body, there is currently a down-arrow next to the request name. Click on that down-arrow and it exposes the Description field that you can then optionally edit. You could add another field that is read-only in nature that describes the path to the request.
![image](https://user-images.githubusercontent.com/2584258/84389692-0f78d580-abbc-11ea-8ef7-95ed515fb9e8.png)

**Additional context**
Postman provided the response > "If you switch to a tab that has a saved request open, its corresponding request in the sidebar gets focussed and highlighted"

But the problem is I have to go open up every collection and folder until I find the one highlighted. If I had them already open, not as much of an issue. However, if you closed out of Postman and then go back in, all the collections are closed.  Expanding the one you THINK it may be in shows all the folders closed.

So while the feature of remembering all my tabs (unsaved or not) between Postman sessions is great, it doesn’t remember what collections and folders I had opened so therefore I start hunting and pecking, trying to find which one the given tab (request) was in.

 Video > https://drive.google.com/open?id=17GBIsRfosMBAmhpUikleYOGvAC9r_Olk

**Comment by labossieresr** [comment]
Thx @jwbanning for creating!  If/once implemented, this will be a big time saver for me.

**Comment by labossieresr** [comment]
Another possible solution is when you click on the tab (request), open the collection, folder(s) and highlight the request in the navigation pane that the tab (request) is for.

**Comment by vvs11** [comment]
similar to #8486

**Comment by CeterusMike** [comment]
Really like this idea. I've got some requests with similar/identical names in a collection I use so I run into this a lot. If I could make a suggestion on this, maybe instead of showing on hover, the height of the tabs could be increased a little and it could be put above or below the tab title?

![image](https://user-images.githubusercontent.com/54405440/91089792-142d2180-e622-11ea-8a79-b72f1834af1f.png)

**Comment by eraymond-bt** [comment]
I would also like to see the sidebar reflect the currently selected tab, even if the folders in the sidebar were collapsed. Without this feature, it's time consuming to find and expand the folder where the current tab lives. Are there any updates for this enhancement request? Thank you!

**Comment by giridharvc7** [comment]
This is now fixed in v8 , we'd love to know what you think about this update
<img width="857" alt="Screenshot 2021-04-14 at 1 32 39 AM" src="https://user-images.githubusercontent.com/1040583/114613725-55f9fd80-9cc1-11eb-9fca-bbbd64f51290.png">

**Comment by labossieresr** [comment]
Yes the functionality has been added. I confirmed you not only now display the path to the request (collection, folder(s) and request), when the tab is clicked on, you actually open the collection and folder(s) and place me right on the request. Nicely done and thank you!
