### ISSUE TITLE
Packaged App Importing Collection

### ISSUE THREAD

**Issue by agalpin** [a85/POSTMan-Chrome-Extension#863]
I had a few collections and exported them individually as I was having issues with a Full data backup (getting to big/throwing errors).

On attempting to reimport them  they refuse to work, don't report any info, mouse cursor blinks a bit but that's about it.

Is there a way to turn on debug for this so I can get a problem to solve, maybe a validator?

**Comment by abhijitkane** [comment]
There's an issue with the current export functionality - we'll be fixing that in the next release. There's a validator available at https://www.npmjs.com/package/postman_validator. Though it's not comprehensive, it might be able to identify the problem.

Could you email the collection file that's causing problems to help@getpostman.com? You can remove the URLs/headers if they contain sensitive information.

**Comment by abhijitkane** [comment]
No, that's fine.

We're looking at the requests issue, we should have something in the coming releases.
