### ISSUE TITLE
Files not selected after choosing the file in form-data file value field

### ISSUE THREAD

**Issue by gagantk** [a85/POSTMan-Chrome-Extension#8630]
**Describe the bug**
Select Files button in form-data options is not accepting any file to be selected there. I have tried several times and with several file extensions too. The file doesn't appear in Postman after I select from File Explorer popup. I have tried uninstalling and reinstalling Postman. But none of these worked.

**To Reproduce**
1. Click on New Request.
2. Change from GET to POST.
3. Click on Body tab.
4. Select "form-data".
5. Change from Text to File in Key column.
6. Click on Select Files and choose any file.
7. The selected file doesn't appear or show in Postman. When I hover over it, it shows "No file selected".

**Expected behavior**
The selected file should appear on Postman value column and it could be used while sending requests.

**App information (please complete the following information):**
 - Native App
 - 7.26.0
 - OS: Windows 10 Pro

**Comment by vvs11** [comment]
@gagantk I am able to see the file in form-data.
Could you share a video where this is happening in your system?

<img width="1114" alt="Screenshot 2020-06-14 at 6 01 21 PM" src="https://user-images.githubusercontent.com/4140290/84593279-0fe9c880-ae69-11ea-8842-4e9ab25627eb.png">

**Comment by gagantk** [comment]
While I faced this issue I was on 7.25, now I'm on 7.26 but still this issue exists with me.

@vvs11 I have attached a video of my issue, please check below.

![video (1)](https://user-images.githubusercontent.com/41661218/84596221-0ddc3580-ae7a-11ea-9204-61b1e5fa12fa.gif)

**Comment by Amandeepsinghghai** [comment]
@gagantk I was facing a similar issue. In my case, the popup was not opening in **Version 7.26.0**.

I upgraded to **Version 7.26.1** and that seems to have fixed the issue.

**Comment by gagantk** [comment]
@Amandeepsinghghai Your issue is different than mine. Yours is popup not opening, but with mine it's fine. The issue is selected file is not showing up in Postman.

Today I upgraded to version 7.27.0, still this issue exists with my Postman.

**Comment by DannyDainton** [comment]
Hey @gagantk / @Amandeepsinghghai  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.

**Comment by GiaBaoDoan** [comment]
how to fix them , need i update a new version

**Comment by vedkribhu** [comment]
@GiaBaoDoan can you describe the issue you are facing and specify the version of the application you're using?

**Comment by cameronfromtorq** [comment]
using postman web with agent version 0.4.25
reproducing this error - no errors or console logs 

https://gyazo.com/290d102a1d980e6fed389dc5278a9cab

**Comment by SanketBelieve** [comment]
Update Your version or Try it in Postman Desktop. in postman Desktop it will run properly .
