### ISSUE TITLE
Postman Monitor Intermittent Environment Variable Parsing Failure

### ISSUE THREAD

**Issue by ernestm** [a85/POSTMan-Chrome-Extension#8632]
**Describe the bug**
Postman monitors occasionally seem to just fail in their ability to parse variables in and the monitor fails, and then it gets its act together and recovers.  But the pages torment our engineers.

**To Reproduce**
I have some monitors hitting our /ping endpoint over time to monitor them.  But sometimes, for example today at 10:16 AM CT, the monitor starts throwing errors parsing the environment variables into the URL. The console says 

```
1 | 10:16:04 | PayAPI Ping Prod started
-- | -- | --
2 | 10:16:04 | Ping the PayAPI
3 | 10:16:04 | GET {{url}}/{{stage}}/v1/ping
4 | 10:16:04 | Error: Invalid URI "http:///%7B%7Burl%7D%7D/%7B%7Bstage%7D%7D/v1/ping"
5 | 10:16:04 | Failed: HTTP Response 200
6 | 10:16:04 | expected { Object (id, _details, ...) } to have property 'code'
7 | 10:16:04 | Failed: Response Valid
8 | 10:16:04 | expected { Object (id, _details, ...) } to have property 'code'
9 | 10:16:04 | Failed: Expected Ping Message Response
10 | 10:16:04 | Unexpected token u in JSON at position 0
11 | 10:16:04 | Check if user is authenticated
12 | 10:16:04 | GET {{url}}/{{stage}}/v1/ping/secure
13 | 10:16:04 | Error: Invalid URI "http:///%7B%7Burl%7D%7D/%7B%7Bstage%7D%7D/v1/ping/secure"
14 | 10:16:04 | PayAPI Ping Prod finished
```
It does this once or twice and then returns to working correctly.  No one is making changes or even in postman at these times, it's just sometimes as the monitor runs independently.

I check the postman service status page but there's no indication of something wrong. 

**Expected behavior**
Monitors should work every time unless the actual API they're exercising is down.  Normally the monitor console for the call above looks like

```
1 | 10:05:42 | PayAPI Ping Prod started
-- | -- | --
2 | 10:05:42 | Ping the PayAPI
3 | 10:05:42 | GET https://pay.precision-autonomy.com/api/v1/ping
4 | 10:05:44 | Check if user is authenticated
5 | 10:05:44 | GET https://pay.precision-autonomy.com/api/v1/ping/secure
6 | 10:05:45 | PayAPI Ping Prod finished
```

**Screenshots**
![Screen Shot 2020-06-11 at 11 53 06 AM](https://user-images.githubusercontent.com/1273721/84417952-0992ec80-abdc-11ea-8f17-55efc8059ea2.png)

**App information (please complete the following information):**
No app/OS, this is happening from the cloud part of Postman

**Comment by DannyDainton** [comment]
Hey @ernestm

Is this still an issue that you're facing in the latest version?

**Comment by alexzakabluk** [comment]
Are there any updates on this issue? It still appears from time to time in the latest version for our monitors. Thanks

**Comment by suntoshakula** [comment]
this is still an issue, currently i get same error

**Comment by suntoshakula** [comment]
![github-issue](https://user-images.githubusercontent.com/76269239/173460277-346834ca-5149-44ff-a75b-e65dfcc2c151.JPG)

**Comment by godfrzero** [comment]
We've pushed out a fix for this issue and environment resolution should no longer fail intermittently. 🎉

**Comment by suntoshakula** [comment]
https://github.com/postmanlabs/postman-app-support/issues/6001

these links could be helpful too just in case if the issue is not resolved
