### ISSUE TITLE
Support the JSON:API standard as a JSON content type

### ISSUE THREAD

**Issue by tomharel** [a85/POSTMan-Chrome-Extension#8635]
**Is your feature request related to a problem? Please describe.**
When using Postman to publish API docs with the [JSON:API](https://jsonapi.org/) standard, we have to specify:
```Content-Type: application/vnd.api+json```

This leads to Postman weirdly formatting example requests as text (i.e. not understanding that the body is actually a JSON object), which makes it hard for implementers to copy paste the request.

For example:
<img width="1645" alt="Screen Shot 2020-06-11 at 15 15 04" src="https://user-images.githubusercontent.com/3478172/84444331-63a0ab80-abf6-11ea-9071-fc42f31722df.png">

**Describe the solution you'd like**
Ideally, Postman will recognize `application/vnd.api+json` as JSON.

**Comment by shashankawasthi88** [comment]
@tomharel This should be fixed in the latest Postman version. `application/vnd.api+json ` should now be treated as JSON.
