### ISSUE TITLE
Deprecated notice in Node request code and introduce node-fetch code

### ISSUE THREAD

**Issue by srikanta72** [a85/POSTMan-Chrome-Extension#8636]
Node request API has been deprecated since Feb. 

So could you guys please show "deprecated" notice in Node "request-module" code and introduce the "node-fetch-module" code. 

I am not able to add the screenshot. Let me know if I am not clear. I will add more info.

**Comment by mccannt** [comment]
@srikanta72 If you could provide more information on this it would be helpful.

**Comment by mccannt** [comment]
Closing this issue as there is no response. Please feel free to reopen with additional information if this is still an issue.
