### ISSUE TITLE
Node native code not working or missing some part

### ISSUE THREAD

**Issue by srikanta72** [a85/POSTMan-Chrome-Extension#8637]
The below code is shown as part of node native code but does not work as part of node script.
I guess the import might need a change. 
```
var http = require('follow-redirects').http;
var fs = require('fs');

var qs = require('querystring');

var options = {
  'method': 'POST',
  'hostname': 'localhost',
  'port': 4602,
  'path': '/libs/wcm/core/content/sites/createpagewizard/_jcr_content',
  'headers': {
    'Authorization': 'Basic YWRtaW46YWRtaW4=',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Cookie': 'cq-authoring-mode=TOUCH'
  },
  'maxRedirects': 20
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function (chunk) {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });

  res.on("error", function (error) {
    console.error(error);
  });
});

var postData = qs.stringify({
  'parentPath': '/content/we-retail/ca/en/experience/arctic-surfing-in-lofoten/test-name',
  'template': '/conf/we-retail/settings/wcm/templates/content-page',
  './jcr:title': 'test02-title',
  'pageName': 'test-name3',
  './pageTitle': 'test-page title'
});

req.write(postData);

req.end();


```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by srikanta72** [comment]
The below code started working. Please change the feature accordingly.


```
var http = require('http');
// var http = require('follow-redirects').http;
// var fs = require('fs');

var qs = require('querystring');

var options = {
  'method': 'POST',
  'hostname': 'localhost',
  'port': 4602,
  'path': '/libs/wcm/core/content/sites/createpagewizard/_jcr_content',
  'headers': {
    'Authorization': 'Basic YWRtaW46YWRtaW4=',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Cookie': 'cq-authoring-mode=TOUCH'
  },
  'maxRedirects': 20
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function (chunk) {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });

  res.on("error", function (error) {
    console.error(error);
  });
});

var postData = qs.stringify({
  'parentPath': '/content/we-retail/ca/en/experience/arctic-surfing-in-lofoten/test-name',
  'template': '/conf/we-retail/settings/wcm/templates/content-page',
  './jcr:title': 'test02-title',
  'pageName': 'test-name3',
  './pageTitle': 'test-page title'
});

req.write(postData);

req.end();
```

**Comment by srikanta72** [comment]
The use of **_var_** is not recommended in Node js and should be used **const** at least at import level while using _require()_.

**Comment by srikanta72** [comment]
Please use the native api examples as given in 
https://nodejs.org/en/knowledge/HTTP/clients/how-to-create-a-HTTP-request/

**Comment by shreys7** [comment]
For generating the snippets using `const`, `let`, etc. you can use the option `Enable ES6 features` for Nodejs Native. Enable it and the snippets will be using the declarations as you mentioned. Click on the Settings icon and the options will appear as shown below

![image](https://user-images.githubusercontent.com/20665864/84481793-416d6300-acb4-11ea-82e0-4a99e30c11d3.png)

**Comment by srikanta72** [comment]
I could not see this ES6 option. Could you please confirm this is from the latest update else I will check the latest version and comment here.

**Comment by shreys7** [comment]
Can you see if the setting `New Code generation mode` is enabled in the global settings as shown below? I am on the latest version of postman App - 7.26.0

![image](https://user-images.githubusercontent.com/20665864/84501077-7937d300-acd3-11ea-8b0a-04b4181d71e1.png)

**Comment by srikanta72** [comment]
Thank you for the confirmation. I will check and get back to here.

**Comment by umeshp7** [comment]
Hey @srikanta72! Was this issue resolved for you after switching to the New code generatation mode?
