### ISSUE TITLE
Favorite Collections unfavorited if you reimport it

### ISSUE THREAD

**Issue by GranitBerisha** [a85/POSTMan-Chrome-Extension#8638]
If I have a collection that I imported and favorited, after I reimport, it will be removed from favorites and I have to favorite it again.

Its a small issue but wanted to have this resolved thanks :)

**Comment by arlemi** [comment]
Any imported entity is considered as a new one by Postman (it will have a different ID etc.). Therefore it can't star it automatically. 
I'd recommend having a look at Version Control instead: https://learning.postman.com/docs/postman/collections/version-control-for-collections/

**Comment by GranitBerisha** [comment]
Not sure what you mean but considered new? We have a dialog that tell us that this collections is already here, and with a message do you want to replace or make a copy!.

So we know that we have another collection just want to add this favorite attribute too, but as I said this is not a big issue thanks

**Comment by arlemi** [comment]
New as we assign it a new Collection ID, new Request IDs etc., and do not copy anything over. All that Postman detects is that you're importing a collection with the same name, which isn't enough to conclude that this is the same collection (see gif below).

![import](https://user-images.githubusercontent.com/5029719/80374083-02af5500-888e-11ea-854b-7172d6ef8200.gif)

Would updating the text in that window to "A collection with the name xxx already exists" make it clearer?
