### ISSUE TITLE
Postman Collection export Collection variables even after deletion

### ISSUE THREAD

**Issue by sonalezops** [a85/POSTMan-Chrome-Extension#8639]
**Describe the bug**
Postman collection while creating defined collection variables but later on deleted collection variables and still in collection export has the variables.

**To Reproduce**
1. Go to '...' Postman and create a collection
2. Define collection variables in request pre-script and set the value
3. Now define the same variable and value in Environment variable
4. Delete the collection variable from pre-script
5. Export the postman collection
6. Even after deleting collection variables the export json has the collection variables

**Expected behavior**
Postman collection exported should not have collection variables if deleted

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version v7.25.0
 - OS: Windows 10

**Comment by vvs11** [comment]
@sonalezops I am not able to reproduce this. Could you add a video where we can see this happening?  It will help us in figuring out the steps that we are missing.

**Comment by DannyDainton** [comment]
Hey @sonalezops 

Are you still facing this issue?

**Comment by DannyDainton** [comment]
Hey @sonalezops 

I'm going to close this issue for now but we can look at opening it again if this is still an issue for you / other users.
