### ISSUE TITLE
Common Function declaration:

### ISSUE THREAD

**Issue by Dip686** [a85/POSTMan-Chrome-Extension#8650]
**Is your feature request related to a problem? Please describe.**
Postman variable reuse feature helped me a lot. But I am stuck in case of reusing functions. For example I was using a random number generator function in my collection. Which is used across different requests. There may be some hacky way to use it though. But it would be great if we can get common function declaration option that we have in case of variables.
Is it possible I can define shareable function across 
- Prescript and test of same request
- Across requests
- Within  environment 

**Describe the solution you'd like**
Common shareable utility function declaration feature in postman app.

**Comment by postfrzero** [comment]
Hey folks -- Postman v11 rolled out a few weeks ago with support for the new Package Library, which enables you to reuse code by creating and requiring packages within your scripts. Learn more about the Package Library [here](https://blog.postman.com/postman-v11-plans-packaging-updates-2024/#what-is-the-package-library-for-reusable-scripts) or [here](https://learning.postman.com/docs/tests-and-scripts/write-scripts/package-library/).
