### ISSUE TITLE
Postman will loose all collections after running into an API error

### ISSUE THREAD

**Issue by itinance** [a85/POSTMan-Chrome-Extension#8653]
**Describe the bug**

After upgrading to latest version 7.26.0 I experience the following bug:
Collections will be removed automatically without any further notice when one of them caused a failure due running.

**To Reproduce**

1. import collections (we have 3 e.g.)
2. run one of them in Postman Runner, expecting that a specific API call in this collection will cause an error 
3. all other collections have been be removed now automatically but not this collection having this specific error from 2
4. the removed collections aren't even visible in trash and there is no way to recover them instead of reimporting again

**Expected behavior**

If a collection runs into an error, the error should be displayed. But at no circumstances any other collection should be removed automatically.

**Screenshots**

This is how it looks like after we've created (or imported) 3 collections with several tests inside:

<img width="305" alt="Screenshot 2020-06-14 10 20 53" src="https://user-images.githubusercontent.com/1758597/84588714-1d339280-ae2a-11ea-9d6a-0335fa9c9e05.png">

Then we run a collection in test runner. It will cause an error. The test runner will still show "0 failed" but this is another issue

<img width="1044" alt="Screenshot 2020-06-14 10 23 39" src="https://user-images.githubusercontent.com/1758597/84588751-523fe500-ae2a-11ea-88c2-77563f864e24.png">

After closing the test runner, all other collections have been removed automatically. It remains only the collection that was executed before and have caused some errors:

<img width="324" alt="Screenshot 2020-06-14 10 24 05" src="https://user-images.githubusercontent.com/1758597/84588773-6be12c80-ae2a-11ea-87fc-e14a3723c3f0.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.26.0
 - OS: macOS Catalina 10.15.5

**Additional context**

This is reproducable at any time even after uninstall and re-install the Postman App.

I've also filed a ticket at https://support.getpostman.com/hc/en-us/requests/52393

**Comment by itinance** [comment]
Btw, is there a place where we can download older versions? I'd like to test this behaviour with older versions and would give feedback here

**Comment by DannyDainton** [comment]
Hey @itinance 

I'm going to close this issue due to inactivity, if you're still facing the same issue in the latest version, we can look to reopen it again.
