### ISSUE TITLE
The blurred window of the Postman

### ISSUE THREAD

**Issue by marson77** [a85/POSTMan-Chrome-Extension#8654]
**Describe the bug**
When the window of Postman is opened it is blurred.

**To Reproduce**
1. Open the Postman 
2. See the blurred window

**Expected behavior**
The window of Postman is clear

**Screenshots**
![Новый точечный рисунок (2)](https://user-images.githubusercontent.com/60729600/84590981-8247b200-ae43-11ea-85df-11acd4ab6c99.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.26.0
 - OS: Windows 7 x64

**Additional context**

**Comment by numaanashraf** [comment]
@marson77 Could you try disabling GPU & hardware accelerated rendering via [these instructions](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621)?

**Comment by numaanashraf** [comment]
I'm going to close this but don't hesitate to reach out if you still have this issue after disabling hardware acceleration.

**Comment by jviotti** [comment]
@marson77 Do you happen to remember what GPU brand and model were you running on that machine?

**Comment by yinxie** [comment]
This happens on my DELL Precision 7760 NVidia A4000, DELL Precision 9710 RTX 3060. I can't disable HR because I am on an external monitor, I have to turn on HR on external monitors for resolution related issues.
