### ISSUE TITLE
postman freezes in mac

### ISSUE THREAD

**Issue by cyb3rs4pi3n** [a85/POSTMan-Chrome-Extension#8660]
**Description**
Version 7.26.0 (7.26.0)
Mac OS: 10.14.6 
App Type: Desktop App

**Reproduce**
Open postman
1. Sign in
2. Hit APIs
3. Freezes intermittently

This is happening after the update. Have to force close it and restart after about 2-3 API request.

**Comment by pankajk07** [comment]
We are tracking this here - https://github.com/postmanlabs/postman-app-support/issues/8624.
Closing this issue as a duplicate.

**Comment by numaanashraf** [comment]
@cyb3rs4pi3n Would it be possible to record and share a performance profile? It'll help us triage the issue and resolve as soon as possible.

Here's the how-to on recording a profile: https://www.loom.com/share/01e103f8511549ec93e22ff2afb2769e

**Comment by DeepakDani7** [comment]
Also Facing same issue in mac , postman hanging issue version 6.7.4 , tried to troubleshoot but not resolved
Please provide solution for this

**Comment by nurullahturkoglu** [comment]
I encountered the same error, Postman was freezing as soon as I opened it. I opened a new window by right clicking on the Postman application from the dock. Then I opened and closed the application and the problem was solved.
