### ISSUE TITLE
Tool does not holds imported collection.

### ISSUE THREAD

**Issue by avinashgupta-gep** [a85/POSTMan-Chrome-Extension#8662]
**Describe the bug**
When we import the collection or variables JSON file into Postman, it vanishes. I am using latest version "v7.26.0"

**To Reproduce**
1. Import existing collection/variable file.
2. After few seconds, the tool wont show imported files.

**Expected behavior**
The imported files should be available in the tool.

**Screenshots**
NA

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version : v7.26.0
 - OS: Windows 10

**Additional context**
NA

**Comment by minakshi-goel** [comment]
I am seeing same issue with newly created collection. It just disappeared in a while. I tried importing from the from the backup I had but this collection with 300 requests keeps disappearing. Sync with online account is also not helping, this collection is not seen when I log into postman.co

**Comment by avinashgupta-gep** [comment]
Hi Team,
Do we have an ETA for this?

Thanks!

**Comment by cyrielle-hada** [comment]
@avinashgupta-gep @minakshi-goel The behavior you're experiencing may be related to a known issue we are tracking. 

Initial reports mentioned that they were able to solve the problem by completely uninstalling the version of Postman they had, and installing the latest version - https://www.postman.com/downloads/. Would you please try that and let us know how it goes?

**Comment by cyrielle-hada** [comment]
@avinashgupta-gep @minakshi-goel  I wanted to check-in with you and see if you're still experiencing the behavior and if so, would you also be able to [raise a support ticket ](https://go.pstmn.io/help-center-signin-newrequest)and send your logs as well as a screen record that shows how to replicate the behavior? To find the logs, please navigate to View > Developer > View Logs in Finder/Explorer.

<img width="1461" alt="85529025-8d999b00-b604-11ea-842b-0a34314c34c6" src="https://user-images.githubusercontent.com/47351631/85537321-c5581100-b60b-11ea-8b31-3e3052bea4fb.png">

**Comment by ankit-m** [comment]
We have pushed out a fix for this. Please reopen the issue if this is still happening for you.
