### ISSUE TITLE
Slowdown of desktop app

### ISSUE THREAD

**Issue by ZacharyKearns** [a85/POSTMan-Chrome-Extension#8664]
**Describe the bug**
The desktop app feels much less responsive after the latest update. I use the app on both Windows 10 and macOS High Sierra. The CPU usage is normal when the app is open but not being used but spikes to between 50-75 % when trying to do even simple things in the app like send a request.

**To Reproduce**
1. Open app
2. Open request
3. Select environment
4. Send request

**Expected behavior**
App performed well and was responsive up until the latest release.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - Native app
 - 7.26.0
 - Windows 10 1809

- Native app
- 7.26.0
- macOS High Sierra 10.13.6

**Additional context**

**Comment by numaanashraf** [comment]
@ZacharyKearns Would it be possible to record and share a performance profile? It'll help us triage the issue and resolve as soon as possible.

Here's the how-to on recording a profile: https://www.loom.com/share/01e103f8511549ec93e22ff2afb2769e

**Comment by j-fbriere** [comment]
I have witnessed the same change after the last update on my machine.
Everything feels sluggish with the UI of the desktop application.
For instance, modifying a variable from an environment is very slow.

On Postman for Windows Version 7.26.0
On Windows 10 Pro Version 2004

**Comment by marionzr** [comment]
Same version same problem.
On Postman for Windows Version 7.26.0
On Windows 10 Pro Version 64-bit 16GB RAM Core i7-3630QM
https://www.loom.com/share/6d6cf94869aa4c63ab5ca4f0b6d35041

**Comment by numaanashraf** [comment]
@j-fbriere @marionzr Could you share a performance profile as well? It'll help us triage the issue and resolve as soon as possible.

Here's the how-to on recording a profile: https://www.loom.com/share/01e103f8511549ec93e22ff2afb2769e

**Comment by ZacharyKearns** [comment]
macOS

[Profile-20200616T000858.json.zip](https://github.com/postmanlabs/postman-app-support/files/4784332/Profile-20200616T000858.json.zip)

**Comment by j-fbriere** [comment]
I created a profile of the modification of a variable from an environment.

On Postman for Windows Version 7.26.0
On Windows 10 Pro 64-bit Version 2004, 32 GB RAM, Core i7-8750H

[Profile-20200616T002703.json.gz](https://github.com/postmanlabs/postman-app-support/files/4784366/Profile-20200616T002703.json.gz)

**Comment by kamalaknn** [comment]
Hey @ZacharyKearns 

Thanks for the performance profile. We are investigating the issue.

It looks like there is performance degradation with the Two Pane layout. While we continue to investigate this issue, could you switch to the Single Pane layout to continue with your workflows?

**Comment by ZacharyKearns** [comment]
@kamalaknn I just tried single pane and the performance is much better, will use that for now.

**Comment by kamalaknn** [comment]
Hey @j-fbriere 

From your profile, I could see that you are facing performance issues when loading Manage Environments dialog. We are tracking this in #5827.

**Comment by yus-erdo** [comment]
> It looks like there is performance degradation with the Two Pane layout. While we continue to investigate this issue, could you switch to the Single Pane layout to continue with your workflows?

Came to file this issue and this fixed the problem. Let me know if you need my profiling too.

**Comment by kamalaknn** [comment]
Hey @erdogany 

It would be great if you can share the profile. It will help us verify the cause.

**Comment by berk-can** [comment]
using single pane mod really helped me thank you so much for the idea @kamalaknn 
Knowing that this app is open-source, I can be very OK with using in single pane mode, I wish you find problem easily, thanks again for the amazing tool postman team

**Comment by kamalaknn** [comment]
Thanks @berk-can @erdogany @ZacharyKearns for the confirmation. We are working on a fix for this and will be released on the stable channel soon.

The [Canary](https://www.postman.com/downloads/canary/) channel has this fix and some improvements to pane layout as well if you'd like to give it a try.

**Comment by kamalaknn** [comment]
This fix is now available in the stable channel as well in the latest version 7.26.1.
