### ISSUE TITLE
Postman raw option disabled

### ISSUE THREAD

**Issue by AhsanHasan** [a85/POSTMan-Chrome-Extension#8666]
![Screenshot 2020-06-16 at 13 49 59](https://user-images.githubusercontent.com/28825229/84776970-e8b20900-afd8-11ea-9b2b-30a170777d3b.png)
Hi! I am facing an issue while choosing RAW under body tab while sending a POST request. I could not figure this out the reason why it is disabled.
Help will be much appreciated!
POSTMAN Information
Postman for Linux
Version 7.26.0
linux 5.3.0-55-generic / x64

**Comment by arlemi** [comment]
Hey! Could you provide a screenshot of what you're seeing?

**Comment by AhsanHasan** [comment]
> Hey! Could you provide a screenshot of what you're seeing?

Thanks for replying, just uploaded a screenshot. I am not getting anything I am able to choose form or any other option but not raw.

**Comment by kamalaknn** [comment]
@AhsanHasan Could you check if you are seeing any errors in the DevTools?  You can open them from `View -> Developer -> Show DevTools (Current View)`)

**Comment by AhsanHasan** [comment]
> @AhsanHasan Could you check if you are seeing any errors in the DevTools? You can open them from `View -> Developer -> Show DevTools (Current View)`)

Failed to load resource: the server responded with a status of 403 (Forbidden) that's the only one

**Comment by codenirvana** [comment]
@AhsanHasan are you not able to switch between request body modes?

Can you share a gif/video to show the problem you are facing or steps we can use to reproduce this issue locally?
