### ISSUE TITLE
getting error on team workspace when request has fileStream

### ISSUE THREAD

**Issue by qabandlab** [a85/POSTMan-Chrome-Extension#8667]
**Describe the bug**

**To Reproduce**
A request is sent: POST some url/attachments with body below:
filestream: some audio (file type)

<img width="679" alt="image" src="https://user-images.githubusercontent.com/57613912/84763505-e4004b80-affe-11ea-9bb2-5809223a051d.png">

It is working in personal workspace but not on team workspace. It is throwing 500 error. But when manually uploading the audio file it is working.

File is located at /Users/someuser/Postman/files

**Expected behavior**
Should work also on team workspace.

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by Mechanicalkeyboard** [comment]
I am not seeing the behaviour describe in the ticket when trying to reproduce this issue. 
@qabandlab Could you please see if this issue is still present?

**Comment by DivyaMoryani** [comment]
Working now, no issues! thank you...
