### ISSUE TITLE
Postman Echo replaces https:// with http:// in response url

### ISSUE THREAD

**Issue by paulmdavies** [a85/POSTMan-Chrome-Extension#8673]
**Describe the bug**
Postman Echo replaces https:// with http:// in response url.

**To Reproduce**
1. Go to "https://postman-echo.com/get"
2. The "url" in the response is "http://postman-echo.com/get"

**Expected behavior**
The "url" in the response should be "https://postman-echo.com/get"

**Additional context**
We have some automated tests which perform a get like this, which seem to fail regularly but not all the time. This behaviour first started around 2020-06-12, with this having worked as expected for months beforehand.

**Comment by Prashansa-K** [comment]
Hey @paulmdavies  
This issue is now fixed. Please, let us know if any other problem arises related to the fix.
