### ISSUE TITLE
Share Collection - You do not have permission to share this collection

### ISSUE THREAD

**Issue by markbullock-mbo** [a85/POSTMan-Chrome-Extension#8676]
**Describe the bug**
Error when attempting to Share Collection

**To Reproduce**
1. In a team workspace, duplicate a collection
2. Try to share the new collection
Actual behavior: You do not have permission to share this collection

**Expected behavior**
I think a dialog where I can set permissions for the shared collection.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.26.0
 - OS: Windows 10 Enterprise

**Additional context**

**Comment by avani-n** [comment]
Hey @markbullock-mbo 

There could be a few reasons why this happens. We are looking into improving the error state here. However to help us identify the root cause, could you please write to us at help@getpostman.com with information about collection id?

**Comment by JohannesLyytikka** [comment]
I have the exact same issue.

**Comment by sromano88-svc** [comment]
I have the same issue, but on local Workspace.
I have fixed it updating the local Postman version.
Problem found in version 7.26
Problem solved in version 7.27.1.

**Comment by sankalp0o** [comment]
We have pushed out some improvements in app v7.27.1. If you are facing this issue, please update your app. Let us know if this does not help.

**Comment by nuryagdym** [comment]
The same here, failing to share the duplicated collection. Postman v7.28.0 is installed.

**Comment by mccannt** [comment]
Resolved in v7.29.0
