### ISSUE TITLE
 Visualize escape regex slash

### ISSUE THREAD

**Issue by devraw** [a85/POSTMan-Chrome-Extension#8678]
**Describe the bug**
 Visualize escape regex slash

**To Reproduce**
Put the script in Tests, send request then inspect visualization.
```
let template = `
    <script>
        pm.getData((err, data) => {
            let regex = /data:image\/[^;]+;base64[^"]+/;
        });
    </script>
`;

pm.visualizer.set(template, {response: pm.response.text()});
```

**Expected behavior**
Slash should not be escaped.

**Screenshots**
![image](https://user-images.githubusercontent.com/46481086/84970308-fab4b880-b14c-11ea-8777-18178daaa947.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [ 7.26.0 ]
 - OS: [Win10 2004]

**Comment by DannyDainton** [comment]
Closing due to age and inactivity. If this is still an issue you're facing in the latest version of the platform, we can look at reopening this again.

**Comment by devraw** [comment]
> Closing due to age and inactivity. If this is still an issue you're facing in the latest version of the platform, we can look at reopening this again.

@DannyDainton It still exists in v9.23.3

**Comment by DannyDainton** [comment]
Could you expand and explain the context of the usage, please?

**Comment by devraw** [comment]
I made a mistake,  the backslash is an escape character in Javascript. I should use double backslash to express one backslash.
