### ISSUE TITLE
Display merged changes after a pull requests changes to status Merged

### ISSUE THREAD

**Issue by alenpokos** [a85/POSTMan-Chrome-Extension#8682]
**Is your feature request related to a problem? Please describe.**
Once a pull request is merged, Changes tab shows message ie. "merged by username xx days ago.".
This makes it hard to review what changes were mada using certain pull request.

**Describe the solution you'd like**
Show actual changes that were merged to destination collection, similar how it is in other version control systems such as git.

**Describe alternatives you've considered**
We have enabled git integration in hopes to have this recorded in commits. This way we have a record of change but still we are unable to figure out what changes were made using this particular pull request.

**Comment by paymand** [comment]
:+1: for this feature request. Would be great to see the changes introduced by the PR **after** it is merged.

**Comment by ankit-m** [comment]
This feature released and available on Postman web as well as native apps.
