### ISSUE TITLE
Cannot import from link (Error while importing: format not recognized)

### ISSUE THREAD

**Issue by Mazyod** [a85/POSTMan-Chrome-Extension#8686]
**Describe the bug**
Trying to import a collection from a link which resides on a server using self-signed certificate files, even though in preferences I have turned off SSL verification.

```
https://localhost:5000/openapi.json
```

**To Reproduce**
1. Open Postman
2. Click on 'import'
3. Click on 'Link'
4. Paste `https` link on a server with self-signed certificate
5. Click 'import'
6. See error

**Expected behavior**
The import flow proceeds normally

**App information (please complete the following information):**
 - Postman desktop app
 - v7.26.1
 - OS: macOS Catalina 10.15.5

**Comment by kaq527** [comment]
8.6.0 the problem still exists

**Comment by arlemi** [comment]
@kaq527 Can you please provide more details, and steps to reproduce the issue?

**Comment by elkikin25** [comment]
Postman v8.10.0 the problem still exists

`{
  "openapi": "3.0.1",
  "info": {
    "title": "API Billing",
    "description": "Test for Digital Ware",
    "contact": {
      "name": "Elki Martinez",
      "email": "elkin.martinez@outlook.com"
    },
    "license": {
      "name": "Todos los derechos reservados"
    }
  },
  "paths": {
    "/api/invoces": {
      "get": {
        "tags": [
          "Invoice"
        ],
        "parameters": [
          {
            "name": "StartDueDate",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          },
          {
            "name": "EndDueDate",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          },
          {
            "name": "Number",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/InvoiceOutModel"
                  }
                }
              }
            }
          }
        }
      },
      "head": {
        "tags": [
          "Invoice"
        ],
        "parameters": [
          {
            "name": "StartDueDate",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          },
          {
            "name": "EndDueDate",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          },
          {
            "name": "Number",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/InvoiceOutModel"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Invoice"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceInModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceInModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceInModel"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceInModel"
              }
            },
            "text/xml": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceInModel"
              }
            },
            "application/*+xml": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceInModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "Invoice"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceUpdateModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceUpdateModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceUpdateModel"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceUpdateModel"
              }
            },
            "text/xml": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceUpdateModel"
              }
            },
            "application/*+xml": {
              "schema": {
                "$ref": "#/components/schemas/InvoiceUpdateModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/invoces/{idInvoice}": {
      "get": {
        "tags": [
          "Invoice"
        ],
        "operationId": "Invoice",
        "parameters": [
          {
            "name": "idInvoice",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InvoiceOutModel"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Invoice"
        ],
        "parameters": [
          {
            "name": "idInvoice",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/products": {
      "get": {
        "tags": [
          "Product"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ProductOutModel"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Product"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "text/xml": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "application/*+xml": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "Product"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "text/xml": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            },
            "application/*+xml": {
              "schema": {
                "$ref": "#/components/schemas/ProductInModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/products/{idProduct}": {
      "get": {
        "tags": [
          "Product"
        ],
        "operationId": "Product",
        "parameters": [
          {
            "name": "idProduct",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductOutModel"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Product"
        ],
        "parameters": [
          {
            "name": "idProduct",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/productcollections": {
      "post": {
        "tags": [
          "ProductCollections"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/ProductInModel"
                }
              }
            },
            "text/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/ProductInModel"
                }
              }
            },
            "application/*+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/ProductInModel"
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/ProductInModel"
                }
              }
            },
            "text/xml": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/ProductInModel"
                }
              }
            },
            "application/*+xml": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/ProductInModel"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "format": "uuid"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "format": "uuid"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "format": "uuid"
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "format": "uuid"
                  }
                }
              },
              "text/xml": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "format": "uuid"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "InvoiceInItemsModel": {
        "type": "object",
        "properties": {
          "itemId": {
            "type": "string",
            "format": "uuid"
          },
          "quantity": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "InvoiceInModel": {
        "type": "object",
        "properties": {
          "number": {
            "type": "string",
            "nullable": true
          },
          "dueDate": {
            "type": "string",
            "format": "date-time"
          },
          "companyId": {
            "type": "string",
            "format": "uuid"
          },
          "billToId": {
            "type": "string",
            "format": "uuid"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/InvoiceInItemsModel"
            },
            "nullable": true
          },
          "resumen": {
            "$ref": "#/components/schemas/InvoiceInResumenModel"
          }
        },
        "additionalProperties": false
      },
      "InvoiceInResumenModel": {
        "type": "object",
        "properties": {
          "subtotal": {
            "type": "number",
            "format": "double"
          },
          "taxes": {
            "type": "number",
            "format": "double"
          },
          "total": {
            "type": "number",
            "format": "double"
          }
        },
        "additionalProperties": false
      },
      "InvoiceOutCustomerModel": {
        "type": "object",
        "properties": {
          "document": {
            "type": "string",
            "nullable": true
          },
          "type": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "address": {
            "type": "string",
            "nullable": true
          },
          "city": {
            "type": "string",
            "nullable": true
          },
          "province": {
            "type": "string",
            "nullable": true
          },
          "firstName": {
            "type": "string",
            "nullable": true
          },
          "lastName": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "InvoiceOutItemModel": {
        "type": "object",
        "properties": {
          "quantity": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "price": {
            "type": "number",
            "format": "double"
          }
        },
        "additionalProperties": false
      },
      "InvoiceOutModel": {
        "type": "object",
        "properties": {
          "number": {
            "type": "string",
            "nullable": true
          },
          "dueDate": {
            "type": "string",
            "format": "date-time"
          },
          "company": {
            "$ref": "#/components/schemas/InvoiceOutSellerCompanyModel"
          },
          "customer": {
            "$ref": "#/components/schemas/InvoiceOutCustomerModel"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/InvoiceOutItemModel"
            },
            "nullable": true
          },
          "resumen": {
            "$ref": "#/components/schemas/InvoiceOutResumenModel"
          }
        },
        "additionalProperties": false
      },
      "InvoiceOutResumenModel": {
        "type": "object",
        "properties": {
          "subtotal": {
            "type": "number",
            "format": "double"
          },
          "taxes": {
            "type": "number",
            "format": "double"
          },
          "total": {
            "type": "number",
            "format": "double"
          }
        },
        "additionalProperties": false
      },
      "InvoiceOutSellerCompanyModel": {
        "type": "object",
        "properties": {
          "document": {
            "type": "string",
            "nullable": true
          },
          "type": {
            "type": "string",
            "nullable": true
          },
          "phone": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "address": {
            "type": "string",
            "nullable": true
          },
          "city": {
            "type": "string",
            "nullable": true
          },
          "province": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "InvoiceUpdateModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "billToId": {
            "type": "string",
            "format": "uuid"
          }
        },
        "additionalProperties": false
      },
      "ProductInModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "unitPrice": {
            "type": "number",
            "format": "double"
          },
          "unitAvailable": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "ProductOutModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "unitPrice": {
            "type": "number",
            "format": "double"
          },
          "unitAvailable": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      }
    }
  }
}`

**Comment by DQJ0521** [comment]
Version 9.4.1 the problem still exists
link：
https://tech-release.api.fuliaoyi.com/app-customer/v2/api-docs
Others can import success。like : https://tech-release.api.fuliaoyi.com/app-purchase/v2/api-docs

**Comment by Shivani2772** [comment]
#10706 
# Version 9.14.13

UI Version 9.14.13-ui-220310-0130

Desktop Platform Version 9.14.0

Architecture x64

OS Platform win32 10.0.19042
