### ISSUE TITLE
To validate the contents in the request body

### ISSUE THREAD

**Issue by sopaul** [a85/POSTMan-Chrome-Extension#8687]
Is there a way to validate the contents in the request body before we send the request.
for example 
1. To validate if a particular xml tag appears twice. 
2. To check if a particluar xml value is present in xml

Postman version : win64-7.25.0

**Comment by DannyDainton** [comment]
Hey @sopaul 👋🏻, 

This seems like a great question that could be opened as a thread, over on the community forum.

https://community.postman.com

Members of the wider Postman community will be able to help you with a  solution 🏆

**Comment by DannyDainton** [comment]
I can see that a new topic has been created over on the community so I'm going to close out this issue. 

https://community.postman.com/t/how-to-validate-the-contents-in-the-request-body/13566
