### ISSUE TITLE
Feature Request: Curl Import

### ISSUE THREAD

**Issue by anthonycmain** [a85/POSTMan-Chrome-Extension#869]
Im not sure how feasible it would be but it would be nice to be able to paste in curl examples from API documentation and create the equivalent Postman request

e.g. curl -u fred:fred -X GET -H "Content-Type: application/json" {context_path}/rest/tempo-rest/1.0/timesheet-approval?period=0813

**Comment by abhijitkane** [comment]
This is available in the packaged Postman app (https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en)

Click on import in the top-left, and paste the curl command. It should be converted to a request. All curl options aren't fully supported yet, though.

**Comment by anthonycmain** [comment]
Brilliant so it is, seems a slightly strange workflow though using the import collection button, but Im glad to see it

**Comment by abhijitkane** [comment]
We're working on a UI revamp, and hopefully features like this will be a lot more discoverable.

**Comment by dirosden** [comment]
The example given above works. But these didnt:
1) curl -X POST -H "Content-Type: application/json" -d "{ Name: 'Scott Guthrie', Age: 67}". 
2) curl -s https://www.box.com/accounts/login -d "username=xyz&password=abc"
Any changes to be made for the above one to work?

**Comment by abhijitkane** [comment]
@dirosden 
For the first one, you need to add a URL.
For the second one, there's an issue with the raw data format that we'll fix in a coming release.

We'll also add notifications for any issues faced while parsing the curl command.

**Comment by dirosden** [comment]
Thanks Abhijit for the reply. Will await the next release.

**Comment by eduardosponda** [comment]
When is the new version going to be released?
