### ISSUE TITLE
Error is not displaying when you check non existing field - to.be.not.null

### ISSUE THREAD

**Issue by deshmanedr** [a85/POSTMan-Chrome-Extension#8693]
**Describe the bug**
Error is not displaying when you check non-existing field - **to.be.not.null**

**To Reproduce**
1. Add the following API 
`https://postman-echo.com/get?foo=bar`
2. Add following **Test** to the API

```javascript
let resp = pm.response.json();    //store response in to resultJson 
// check required location data should not be null
pm.test("Verify that all required fields should not be null the response", function(){
    console.log(resp.url);
    **pm.expect(resp.testFieldError).to.be.not.null;**
})
```

Actual Result - 
1. Field - **testFieldError** is not present in the response but the **Test** is passing.

**Expected behaviour**
1. An error message must get shown when we compare a field which is not present in the response. 

**App information (please complete the following information):**
 - App Type - Native Application
 - Postman Version - v7.26.1
 - OS: Windows 10

**Comment by DannyDainton** [comment]
Hey @deshmanedr 

The `pm.expect(resp.testFieldError).to.be.not.null` statement is referencing a property that is `undefined` so it's not `null`. That would be, from what I can see, the reason why the test passes.

```javascript
pm.test("Verify that all required fields should not be null the response", function(){
    pm.expect(resp.testFieldError).to.be.not.undefined;
})
```
This test would fail with the error `AssertionError: expected undefined not to be undefined`

**Comment by SabriH10** [comment]
Hi @deshmanedr , Just wanted to follow up to let you know I'm going to close this out. Hopefully, the information provided in Danny's response helped here regarding the difference between `undefined` and `null`. Feel free to reach out if you have ant questions or concerns.
