### ISSUE TITLE
CollectionRunner - Progress Percentage NaN%

### ISSUE THREAD

**Issue by akashDash458** [a85/POSTMan-Chrome-Extension#8696]
**Describe the bug**
When the number of iterations that are set is not a number, the progress bar shows NaN%. 

**To Reproduce**
1. Go to 'Runner'
2. Select your tests and environments
3. Set number of iterations as a string, ex: '13b'
4. Click on Run
5. Progress bar shows NaN% and Progress shows 'Running 13b iterations'
6. Test run stops after 1 iteration.

**Expected behavior**
Progress should show a default number of iterations, and progress percentage should be a valid number. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46552682/85310484-abb2ae80-b4d1-11ea-8d5d-461428116fd4.png)

**App information (please complete the following information):**
 - App Type 
 - Postman Version 7.26.1 (7.26.1)
 - OS: [e.g. macOS Catalina 10.15.4]

**Comment by vvs11** [comment]
@akashDash458 Thanks for letting us know.

**Comment by timbochamp** [comment]
We've added in input validation that non-numeric values aren't able to be entered in the iteration field to address part of this issue. The work to implement Runner statistics will be addressed through #4324 where the run percentage was removed in our v8 release, so I'll mark this as closed. Feel free to reopen if you find related issues to this iteration input at the same time!
