### ISSUE TITLE
Trigger an update to the collection from Postman API

### ISSUE THREAD

**Issue by arlemi** [a85/POSTMan-Chrome-Extension#8697]
**Is your feature request related to a problem? Please describe.**
As of now, you have to use the Postman UI to update a collection generated from an API Schema. I'd like to be able to trigger a validation/update from the Postman API so I can integrate it in my CI/CD pipeline. 

**Describe the solution you'd like**
A new endpoint in [the Postman API](https://api.postman.com/) that allows to trigger a validation/update.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hilary** [comment]
That would be us. 😄 We'd like to be able to upload an updated version of an API via the Postman API and update an existing associated collection. 

Thanks so much for your work serving the design-first folks in your community.

**Comment by arlemi** [comment]
We've added a new endpoint to the Postman API that allows you to sync an API Element with an OpenAPI 3.0 spec:
`https://api.getpostman.com/apis/:apiId/versions/:apiVersionId/:entityType/:entityId/syncWithSchema`

You can see an example of it in the [Postman API documentation](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-17971d1e-8f4f-46cf-8f60-1868b85596f0), it requires an `apiId`, `apiVersionId`, `entityType`, and `entityId`.

Let us know if you're having any issues using it, and otherwise... enjoy!

**Comment by airoasis** [comment]
Is this endpoint updating the collection from schema immediately? Or is it the same as hitting the validation button?

**Comment by arlemi** [comment]
@airoasis It's updating the collection immediately, like if you were clicking validate, checking all changes, and pushing them.

**Comment by airoasis** [comment]
Awesome!

**Comment by bernardgut** [comment]
@arlemi I tried to use the endpoint with little success. I assume `entityType` is "schemas" and `entityId` is {{schema id}}.

The link to the documentation you provided doesn't work and [the official API docs ](https://documenter.getpostman.com/view/631643/JsLs/#intro) (first link on google so I assume it's the latest docs) doesn't reference anything like that.

can you advise?

**Comment by arlemi** [comment]
@bernardgut `entityType` is one of  documentation, contracttest, integrationtest, testsuite, mock, monitor. 

That API doc is indeed out of date! I'll see if we can get it replaced with the latest one that can be found here: api.postman.com

**Comment by bernardgut** [comment]
Thanks for the rapid answer. I don't understand then. How can I automatically trigger an update of my API schema. I thought this is what this endpoint was for ?

Basically I have an OpenAPI v3 definition that is auto-generated by spring boot available at some "/api-docs" URL and that gets updated at every deployment. Every time I deploy my service I need to update my postman schema so that it reflects the changes in the verbs. I thought this Postman API endpoint was it but apparently not. I cant seem to find any solution to this anywhere.

sorry if this is not the right place to ask.

**Comment by arlemi** [comment]
@bernardgut This endpoint is to update a collection that was generated from an API schema, whenever the schema is updated. If you're looking to update the schema you'll have to use this endpoint: 
https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a

If you still have questions I'd recommend asking on community.postman.com where more people will see it and be able to help!
