### ISSUE TITLE
Won't Verify Account

### ISSUE THREAD

**Issue by anaw4804** [a85/POSTMan-Chrome-Extension#8698]
-Pulling up postman and go to Dashboard
-Side bar Pops up with account completion status 
-Says I need to verify my email
-Click to resend email
-Open link and I Finishing verifying my account 
-When I return to my dashboard it still says I need to verify my account 
-Ive tried multiple times on different devices, still won't work

Summed up my verification is not being processed. I'm trying to create a new workspace so I can invite my team members, but each time I try it would not work and just would not load. Hoping through finishing setting up I can fix this.

**Comment by arlemi** [comment]
Could you send an email to our support team on help@postman.com indicating the email address used for the Postman account? They'll be able to help. 🙂

**Comment by DannyDainton** [comment]
Hey @anaw4804 

Are you still seeing this issue?
