### ISSUE TITLE
It is recommended that I be prompted to save automatically or copy and move

### ISSUE THREAD

**Issue by MinaAndLuoXia** [a85/POSTMan-Chrome-Extension#8699]
It is recommended to prompt me to save when automatically saving or copying and moving. I moved the item when I didn't save, but the data was lost, and now I am crashing

**Comment by vvs11** [comment]
@MinaAndLuoXia could you elaborate more on this? What data were you moving and from where to where?

**Comment by mccannt** [comment]
Closing this issue as there is no response from the user. Please feel free to reopen with additional information if this is still an issue.
