### ISSUE TITLE
filter in the left panel does not filter URLs in the collections

### ISSUE THREAD

**Issue by priyanshujain** [a85/POSTMan-Chrome-Extension#8702]
**Describe the bug**
After installing new updates filter in the left panel does not filter URLs in the collections. It used to filter URLs in the collection, now it only filters by name of the request.

**To Reproduce**
1. Go to any collection
2. click on top filter and search a request by URL
3. No result for URL search

**Expected behavior**
It will filter all requests in collections and give filtered requests in result

**Screenshots**
![image](https://user-images.githubusercontent.com/9302265/85388813-2f1ce000-b564-11ea-9bbe-82900cb7182b.png)

**App information (please complete the following information):**
 - App Type [Native App on MacOS]
 - Postman Version 7.25.3
 - OS: macOS Catalina 10.15.5

**Comment by vvs11** [comment]
@priyanshujain We currently filter only on collection name, request name and folder name. We don't search the URL in the request. I am marking this as a feature request and will plan it in our roadmap. Will keep you posted.

**Comment by priyanshujain** [comment]
@vvs11  Thanks for the response. I think I used to filter collection requests by URL in the earlier version.

**Comment by priyanshujain** [comment]
@vvs11  This is fixed now in version 7.26.1.
