### ISSUE TITLE
Collection disappears when uploaded using the "Run in Postman" feature.

### ISSUE THREAD

**Issue by Ashwin-Gangadharan** [a85/POSTMan-Chrome-Extension#8704]
**Describe the bug**
Collection disappears when uploaded using the "Run in Postman" feature.

**To Reproduce**
1. Go to the website from which the collection is to be imported
2. Click on "Run in Postman" CTA (It uploads Collection with Environment)
3. Open postman to see the desired collection to be uploaded
Observe that after 10-15 sec the collection uploaded disappears automatically but the environment remains as it is.

Have tried this with other websites also,
**Observation** - Collection uploaded with environment only causes this issue, else it works fine.

**Expected behavior**
The collection uploaded should be available in the left nav

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.27.0]
 - OS: [e.g. macOS Catalina 10.15.5] -  MacBook Pro

**Comment by cyrielle-hada** [comment]
@Ashwin-Gangadharan thanks for flagging this and sorry you’re seeing issues when importing collections. Engineering is currently investigating and working towards a solution and we hope to have a fix in place soon!

We'll update this issue as soon as updates materialize!

**Comment by cyrielle-hada** [comment]
@Ashwin-Gangadharan I wanted to check-in with you and see if you're still experiencing the behavior and if so, would you also be able to [raise a support ticket](https://go.pstmn.io/help-center-signin-newrequest) and send your logs as well as a screen record that shows how to replicate the behavior? To find the logs, please navigate to `View > Developer > View Logs in Finder/Explorer`.

<img width="1461" alt="Screenshot 2020-06-24 at 10 21 52" src="https://user-images.githubusercontent.com/47351631/85529025-8d999b00-b604-11ea-842b-0a34314c34c6.png">

**Comment by Ashwin-Gangadharan** [comment]
I have a raised a ticket - https://support.getpostman.com/hc/en-us/requests/53047

**Comment by ankit-m** [comment]
@Ashwin-Gangadharan we have pushed out a fix for the same. If the issue is still not fixed for you, please reopen this issue.
