### ISSUE TITLE
Unable to declare and use the field "data" in Pre-request Script

### ISSUE THREAD

**Issue by raghavendar-ts** [a85/POSTMan-Chrome-Extension#8705]
I am unable to declare and use the field "data" in Pre-request Script and I get the following error when I use it.

**Error:**
There was an error in evaluating the Pre-request Script:  SyntaxError: Identifier 'data' has already been declared

1. Create any new request
2. In Pre-request Script add the following code
let data = "";
3. Click Send to get the error

It looks like Postman is internally using the field data and my expectation is that the users should be able to use any field names.

![image](https://user-images.githubusercontent.com/5101635/85511091-dad23880-b615-11ea-82b0-6694b4961f1b.png)

**Comment by mccannt** [comment]
@raghavendar-ts This is correct. `data` is a reserved variable in Postman as it's used to access the data variables.
We are looking at ways to improve this going forward.
