### ISSUE TITLE
Postman window is flickering 💃🕺

### ISSUE THREAD

**Issue by vivekpatel111** [a85/POSTMan-Chrome-Extension#8706]
**Describe the bug**
When using postman and upon clicking on Send request button, then Postman window is flickering as shown in below screenshot. 

![postman_dancing_bug](https://user-images.githubusercontent.com/8190653/85510838-90e95280-b615-11ea-80a3-8e6df5b0a6b6.gif)
![postman_dancing_bug_2](https://user-images.githubusercontent.com/8190653/85511577-664bc980-b616-11ea-87db-bfdd26aea1dd.gif)

**To Reproduce**
- Don't know exact steps to reproduce this, but got this issue multiple times.

**Expected behavior**
- Window should not flicker.

**Screenshots**
Attached in bug description.

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 7.26.1 (linux 4.15.0-106-generic / x64)
 - OS: Ubuntu 18.04 LTS

**Additional context**
None

**Comment by DannyDainton** [comment]
Hey @vivekpatel111,

I'm finding it difficult to reproduce the issue you're currently seeing, are you able to update the version that you're running and see if the problem is still persisting?

**Comment by vivekpatel111** [comment]
@DannyDainton I'm already on the latest version I guess.

**Comment by DannyDainton** [comment]
There's a feature that's been added to the latest version around additional network information that I would expect to see in that view so you might not be 😉

Have you tried using our Canary build in parallel to see if the issue is seen in there?

It's difficult to advise either way if we are unable to produce the issue consistently. 😔

**Comment by vivekpatel111** [comment]
@DannyDainton I've updated version to Version 7.27.0

![image](https://user-images.githubusercontent.com/8190653/85946246-c1582600-b960-11ea-9078-97e5353957b9.png)

I've also seen the same issue on this version too, but I'm not able to regenerate the issue as it's not consistent.

I've not tried to replicate the same on Canary build.

Updated on 2020-06-29
![postman_dancing_bug_3](https://user-images.githubusercontent.com/8190653/85985166-f8cddd80-ba07-11ea-8312-e085492619f1.gif)

**Comment by aharbavets** [comment]
The easiest way to reproduce it is to send request to some endpoint which takes several seconds or tens of seconds to complete. Maybe it only happens when you send the request second/third/etc time

**Comment by DannyDainton** [comment]
Hey @vivekpatel111 

I'm unable to reproduce this in the latest version on the platform (9.16.1) - I'm going to close this now but if you are still experiencing the issue then we can look to reopen it again.
