### ISSUE TITLE
Postman collection Runner - getting error data unavailable in response body only for last iteration from csv , other rows from csv runs properly 

### ISSUE THREAD

**Issue by archana781** [a85/POSTMan-Chrome-Extension#8708]
**Describe the bug**
Getting error "data unavailable (only data about the top 10 historical runs is stored) in postman request body. 
This error I get only for last iteration

**To Reproduce**
1) Created Data Driven with Postman using CSV
2) Runner all request with multiple set of data
**Expected behavior**
It should not give error for last iteration.

Note : if I delete the last row from CSV( if last row is 9), now the last row will become row-8 ,this time the error occurs on row-8
**Screenshots**

![image](https://user-images.githubusercontent.com/67378304/85580807-ad0ee300-b659-11ea-9382-8c2a381d7706.png)

**Comment by DannyDainton** [comment]
Hey @archana781,

Would you be able to provide some additional environment and Postman version information, please?

That request looks like it's returning a 500 error, can you confirm that the individual request to that endpoint using the same data is working?

**Comment by archana781** [comment]
Yes  its working for individual request to the endpoint using the same data. 
Postman for Windows
Version 7.0.9
win32 6.1.7601 / x64

**Comment by DannyDainton** [comment]
Are you able to update to the latest Postman Version?

Could you provide more details about the data file used and how you're referencing this in the request?

The status code displayed points more towards an issue from the server rather than something within the Postman application.

**Comment by archana781** [comment]
No, I am not able to update it as I am working on Virtual Machine.
I am using CSV file & Setting global variable from Manage Environment.

**Comment by DannyDainton** [comment]
Unfortunately, without those specific details that would allow us to reproduce the issue on our side, it's going to be difficult to take this any further.

Once you're able to upgrade to the latest version and if you're still seeing the problem, we can look to open up this issue again but for now, I'm going to close it. 

We have an awesome community of users who might also be able to offer some guidance here if you need additional help - https://community.postman.com/
