### ISSUE TITLE
Postman 7.27.0 won't start on Mac OS X 10.15.5

### ISSUE THREAD

**Issue by emoseman** [a85/POSTMan-Chrome-Extension#8710]
**Describe the bug**
The application doesn't fully start, it hangs on the initial loading window indefinitely.

**To Reproduce**
1. Click on Postman.app

**Expected behavior**
The application to start.

**Screenshots**
<img width="402" alt="Screen Shot 2020-06-25 at 1 07 34 PM" src="https://user-images.githubusercontent.com/452524/85766278-e17bb100-b6e4-11ea-8a1e-9d2d2eca649c.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.27.0
 - OS: 10.15.5

**Additional context**
Log output from command-line execution:

```
 $ ./Postman
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Disabling GPU
ProtocolHandler~init - Success with status: true]
Main~createDefaultWorkingDir - Default working dir creation already attempted
1593104945868 main info "Booting Postman 7.27.0, darwin-19.5.0 on x64"
1593104945869 main info "EventBus~initialize - Success"
1593104945871 main warn "CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/Users/someuser/Library/Application Support/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/Users/someuser/Library/Application Support/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/Users/someuser/Library/Application Support/Postman/Postman_Config/proxy'"}
1593104945872 main info "CloudProxyManager~init - Success"
1593104945873 main info "UpdateHandler~init - Success"
1593104945874 main info "RuntimeExecutionService~initialized: Success"
1593104946426 main info "Bootstrap-models~bootstrap - Success"
1593104946581 main info "window-manager~newSharedWindow: Shell loaded"

```

**Comment by Raj-postman** [comment]
Hi @emoseman - Sorry to hear that. Would you please try renaming (or clearing) the local files for your Postman installation which generally resolves this issue.  You can find full instructions for doing so in the below article.

> https://support.getpostman.com/hc/en-us/articles/360025359014

If the issue persists, please write to us at help@postman.com by providing us the logs [as per this article.](https://support.getpostman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-)

**Comment by WurstCommander** [comment]
Same with Windows 64 bit, everytime the app upgrades this error appears, very annoying.

**Comment by emoseman** [comment]
Clearing the support files resolved the issue.
