### ISSUE TITLE
Certificate URL setting is incorrectly case sensitive

### ISSUE THREAD

**Issue by motor75** [a85/POSTMan-Chrome-Extension#8714]
**Describe the bug**
The URL value used when setting up certificates to be used seems to be case sensitive.

**To Reproduce**
1. Set up a certificate to be used for an API endpoint in all lower case `exampledev.company.com` to a URL that requires a certificate
2. Attempt to hit the API with the URL of `exampleDEV.company.com`
3. Error received:
Error: write EPROTO 1079526952:error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 42

**Expected behavior**
URLs are not case sensitive.  Therefore, the setting for the certificate path should not be case sensitive when PM determines what certificate is used.  Both `exampledev.company.com` and `exampleDEV.company.com` should work - both sending the desired certificate with the payload.

**App information (please complete the following information):**
 - Postman Version 7.27.0

**Comment by vvs11** [comment]
@motor75 can you please send us a screenshot of the error you're getting? We will have more information to help you. 
Also, you can reach out to our community https://community.getpostman.com/ for quicker support

**Comment by motor75** [comment]
@vvs11 Here are the screen shots you requested (the URL used is filtered due to privacy/security concerns):

1) Set up a URL that uses a global "environment" variable and use the "DEV" environment:
![Screenshot_7](https://user-images.githubusercontent.com/42443455/86827103-97d58380-c05f-11ea-83e4-836913f153ad.png)
![image](https://user-images.githubusercontent.com/42443455/86826563-eafb0680-c05e-11ea-85b3-ca18a7e9dc41.png)

2) Set up the global variable in all caps to be "DEV":
![Screenshot_4](https://user-images.githubusercontent.com/42443455/86826595-f8b08c00-c05e-11ea-9fb8-75dd8c14d27c.png)

3) Set up the cert to hit the URL in all lower case:
![Screenshot_3](https://user-images.githubusercontent.com/42443455/86826664-0c5bf280-c05f-11ea-9757-ed0e203676b9.png)

4)  Hit the URL and receive error (notice the console **_shows_** all lower case):
![Screenshot_5](https://user-images.githubusercontent.com/42443455/86826842-3f9e8180-c05f-11ea-83ce-48da8baba128.png)
![Screenshot_6](https://user-images.githubusercontent.com/42443455/86826852-43ca9f00-c05f-11ea-80e1-4fb593836ca8.png)

5)  Change the environment variable to be lower case "dev":
![Screenshot_8](https://user-images.githubusercontent.com/42443455/86827006-770d2e00-c05f-11ea-8339-cd4079183bbb.png)

6)  Hit the URL and receive success 200 (notice that the URL is still showing in all lower case):
![Screenshot_9](https://user-images.githubusercontent.com/42443455/86827059-868c7700-c05f-11ea-9f45-6f0581ac44e9.png)

**Comment by LeKaido** [comment]
The certificate URL also does not clean for whitespace. It's quite easy to accidentally copy-paste an URL with included whitespace into the cert config box and it will only be visible in the console that you do not have cert attached to the request sent.

**Comment by DannyDainton** [comment]
Closing due to age and inactivity. If this is still an issue you're facing in the latest version of the platform, we can look at reopening this again.
