### ISSUE TITLE
Collection Runner Doesn't Parse  Number and Bool Columns in CSV Data Files Correctly

### ISSUE THREAD

**Issue by RashmithaK** [a85/POSTMan-Chrome-Extension#8715]
**Describe the bug**
trying to provide the boolean value from csv file, when we preview the  data in the postman runner its taken as string

**To Reproduce**
click on runner
select csv file
click on preview

**Expected behavior**
the value should be boolean

**Screenshots**

**App information (please complete the following information):**
 - Postman Version: PostmanCanary-win64-7.28.0-canary01-Setup and Postman-win64-7.24.0-Setup
 - OS: windows

**Additional context**
Json:
{
      "id": "{{a}}",
      "name": "{{b}}",
      "bool": {{c}}
    }

csv file generation:
a         | b         | c
fname | lname | true

PREVIEW Data:
Iteration      a                    b           c
1                "fname"    "lname"    "true"

and also when we pass the number instead of taking as integer value is take as string
Json:
{
      "id": {{a}},
      "name": "{{b}}",
      "bool": {{c}}
    }

Iteration     a         b                  c
1                1         "lname"       "true"

**Comment by DannyDainton** [comment]
Hey @RashmithaK,

Given this request body:

```
{
"id": {{a}},
"name": "{{b}}",
"bool": {{c}}
}
```

Is the request being successfully made with a boolean? 

You're only showing the value that you're seeing in the file _Preview_ in your question and I was wondering about the actual request and the response you received.

**Comment by RashmithaK** [comment]
hey Sorry , got solution

when we are getting details from Excel  boolean value is capital, so wrote the pre script  to convert capital into small
