### ISSUE TITLE
"Authorize using browser" fails to complete authentication

### ISSUE THREAD

**Issue by willsthompson** [a85/POSTMan-Chrome-Extension#8717]
**Describe the bug**
I am able to get access tokens from my Auth0 service using the built-in Postman browser. However, using the "authorize using browser" option, authentication fails, despite apparently completing successfully in Auth0. I've added Postman's browser-specific callback URL to the Auth0 config.

**To Reproduce**
1. Go to 'Authorization'
1. Click on 'Get New Access Token'
1. Check 'Authorize using browser`
1. Click 'Request Token'
1. (Postman will redirect to Auth0 in new browser window) Enter credentials and submit.
1. Browser window displays 'Authentication complete. You can close the tab and go back to the Postman app.'
1. Postman still displays dialog titled 'Get New Access Token' with loading animation and text: `Sign in through the browser. This dialogue will automatically close once the auth callback is received.`
1. 'Get New Access Token' dialog changes to `Authentication failed. Couldn't complete authentication. Check the Postman Console for more details.`
1. Postman Console has a one-line error: `Error: OAuth 2.0 request timed out. Please try again.`
1. Close dialog, uncheck, 'Authorize using browser`, click 'Get New Access Token', and request succeeds.

**Expected behavior**
Postman is able to receive auth callback from browser.

**Screenshots**
<img width="646" alt="Screen Shot 2020-06-27 at 12 57 41 PM" src="https://user-images.githubusercontent.com/1315884/85929115-d6a55580-b877-11ea-9833-790ba6f83609.png">

<img width="391" alt="Screen Shot 2020-06-27 at 1 05 42 PM" src="https://user-images.githubusercontent.com/1315884/85929122-e02ebd80-b877-11ea-8d55-33916bf527b5.png">

<img width="622" alt="Screen Shot 2020-06-27 at 1 05 26 PM" src="https://user-images.githubusercontent.com/1315884/85929125-ecb31600-b877-11ea-9e6b-e00347ae6000.png">

<img width="623" alt="Screen Shot 2020-06-27 at 12 57 29 PM" src="https://user-images.githubusercontent.com/1315884/85929133-f472ba80-b877-11ea-8d1c-6a6efd83ab8f.png">

**App information (please complete the following information):**
 - App Type: Flask-based webservice/API
 - Postman Version: 7.27.1
 - OS: macOS Catalina 10.15.5

**Comment by mithucste30** [comment]
Yes, I am facing this issue from this morning too.

- Postman Version: 7.27.1
- Os Ubuntu Linux[Snap]

**Comment by vikiCoder** [comment]
Hi,

Are you getting a popup asking to open the Postman app after completing the authorization in browser (like shown in the below screenshot)?

![image](https://user-images.githubusercontent.com/16588032/86795657-6a9eca80-c08b-11ea-9145-8137656607ed.png)


If you are not seeing a popup like that, please make sure pop-ups are not blocked in your browser. If you are using Chrome, you can enable the pop-ups as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/16588032/86796578-5dcea680-c08c-11ea-9435-7ca7d7f9ba43.png)

**Comment by willsthompson** [comment]
@vikiCoder No, that was not happening. However, after allowing popups for `oauth.pstmn.io`, it did, and the Authentication succeeded. Thank you!

Considering that all major browsers have been blocking popups for years by default - and Safari does this with no visual indication that a popup has been blocked - I propose that Postman issue a warning (maybe as a tooltip?) along with the checkbox that popups must be enabled for this feature to work. Warning users about the requirement to disable popup blockers has been standard practice for some time now.

**Comment by vikiCoder** [comment]
Fair enough @willsthompson. We'll consider adding a warning. Thanks for the suggestion.

**Comment by willsthompson** [comment]
Thank you for your attention to this issue 🙂

**Comment by lfarci** [comment]
I just have encountered this issue. I have allowed popups on `oauth.pstmn.io` but the popup does not show up. I do no even get the dialog asking me to open it.

I ended up using the Postman embedded popup (unchecked "*Authorize using browser*" box).

My environment is the following:
- Postman Version 7.36.4
- OS: Ubuntu 20.04.1 LTS
- Browser: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by krishna2095** [comment]
same issue with me 
OS: Ubuntu 20.04.1 LTS
Browser: Google Chrome

**Comment by krishna2095** [comment]
> Yes, I am facing this issue from this morning too.
> 
> * Postman Version: 7.27.1
> * Os Ubuntu Linux[Snap]

how did you solve this

**Comment by krishna2095** [comment]
> I just have encountered this issue. I have allowed popups on `oauth.pstmn.io` but the popup does not show up. I do no even get the dialog asking me to open it.
> 
> I ended up using the Postman embedded popup (unchecked "_Authorize using browser_" box).
> 
> My environment is the following:
> 
> * Postman Version 7.36.4
> * OS: Ubuntu 20.04.1 LTS
> * Browser: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

what's remedy for this problem ?

**Comment by lfarci** [comment]
> > I just have encountered this issue. I have allowed popups on `oauth.pstmn.io` but the popup does not show up. I do no even get the dialog asking me to open it.
> > I ended up using the Postman embedded popup (unchecked "_Authorize using browser_" box).
> > My environment is the following:
> > 
> > * Postman Version 7.36.4
> > * OS: Ubuntu 20.04.1 LTS
> > * Browser: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
> 
> what's remedy for this problem ?

I did not solve the issue. I was able to make it work using the embedded Postman popup though. I have simply unchecked the box under the Callback URL field: _Authorize using browser_.

Redirecting from the browser to Postman still does not work for me.

**Comment by dominik-stypula-polcode** [comment]
same here on Ubuntu: still not working, pop-ups are allowed for `oauth.pstmn.io` but it still does not authorize me, and window just hangs with authorization

**Comment by mwaleed0517** [comment]
> > > I just have encountered this issue. I have allowed popups on `oauth.pstmn.io` but the popup does not show up. I do no even get the dialog asking me to open it.
> > > I ended up using the Postman embedded popup (unchecked "_Authorize using browser_" box).
> > > My environment is the following:
> > > 
> > > * Postman Version 7.36.4
> > > * OS: Ubuntu 20.04.1 LTS
> > > * Browser: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
> > 
> > 
> > what's remedy for this problem ?
> 
> I did not solve the issue. I was able to make it work using the embedded Postman popup though. I have simply unchecked the box under the Callback URL field: _Authorize using browser_.
> 
> Redirecting from the browser to Postman still does not work for me.

![image](https://user-images.githubusercontent.com/57632167/173007624-1c47f93d-e2d7-4570-8492-ee3986286a41.png)

**Comment by hassanshahzadaheer** [comment]
> Hi,
> 
> Are you getting a popup asking to open the Postman app after completing the authorization in browser (like shown in the below screenshot)?
> 
> ![image](https://user-images.githubusercontent.com/16588032/86795657-6a9eca80-c08b-11ea-9145-8137656607ed.png)
> 
> If you are not seeing a popup like that, please make sure pop-ups are not blocked in your browser. If you are using Chrome, you can enable the pop-ups as shown in the below screenshot.
> 
> ![image](https://user-images.githubusercontent.com/16588032/86796578-5dcea680-c08c-11ea-9435-7ca7d7f9ba43.png)

thank you so much, save a lot of effort and time.

**Comment by shabiulhassan** [comment]
In my case pop-up is also coming but still postman didn't give me token. Anyone know the reason?

**Comment by ashley-wardell-access** [comment]
Broken for me also. Tried all the browsers i have.
I've enabled popups and you can see the browsers stating they are opening the link with postman. But nothing happens in postman. It would be good if the token was shown in the browser as this would be a workaround in case the re-direct didn't happen.

**Comment by GoulartNogueira** [comment]
> I have simply unchecked the box under the Callback URL field: _Authorize using browser_.

It worked for me, thanks! It's not the most elegant solution, but it works!

**Callback URL:**
Keep the same url as when the box was checked:
- https://oauth.pstmn.io/v1/callback (Desktop-app)
- https://oauth.pstmn.io/v1/browser-callback (Web-app)
