### ISSUE TITLE
OpenAPI query parameter of type array leads to incorrect warning

### ISSUE THREAD

**Issue by weickmanna** [a85/POSTMan-Chrome-Extension#8719]
**Describe the bug**
OpenAPI query parameter of type array leads to incorrect warning.

**To Reproduce**
1. Specify Open API query parameter of type array
2. Generate Postman Collection from that API
3. Execute the request via Postman, sending the parameter multiple times as in: ?attributes=Name&attributes=Key
4. Schema Validation reports warning: "The query parameter attributes needs to be of type array"

**Expected behavior**
No warning, since the default Open API serialization for array query parameters is form - exploded (see https://swagger.io/docs/specification/serialization/#query)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.27.1
 - OS: Ubuntu 18.04

**Comment by VShingala** [comment]
@weickmanna We have added support for parameter serialization in conversion and validation flows. This should be fixed with latest Postman App v7.33. Closing this issue, for now. Feel free to reopen this issue if you face problems further.
