### ISSUE TITLE
Environment variables don't support callback to initial value

### ISSUE THREAD

**Issue by VipSaran** [a85/POSTMan-Chrome-Extension#8723]
**Describe the bug**
The `Current Value` tooltip (in Environment settings) says:
![image](https://user-images.githubusercontent.com/995948/86113350-7148a300-bac9-11ea-828d-42e2a2779d82.png)
but that does not work (anymore).

**To Reproduce**
Set up an environment with only `Initial value` fields filled in and use those variable(s) in request.

**Expected behavior**
The variable value from `Initial value` field is taken in request.

**Screenshots**
Env setup:
![image](https://user-images.githubusercontent.com/995948/86113819-08155f80-baca-11ea-84b6-11bc684a450a.png)

Request URI: 
![image](https://user-images.githubusercontent.com/995948/86114254-95f14a80-baca-11ea-99c2-7078910ef2fe.png)

Request result (variable value empty)t:
![image](https://user-images.githubusercontent.com/995948/86113852-11063100-baca-11ea-94f7-617a49034e61.png)

**App information (please complete the following information):**
 - Postman v7.27.1
 - OS: Win10 x64

**Additional context**
Was working before...

**Comment by giridharvc7** [comment]
@VipSaran , this is because `url-local` doesn't have an `initial value` Once you assign an initial value to it, it will work fine. 
Let me know if this works. Closing this ticket for now, feel free to reopen if you face any issues.
