### ISSUE TITLE
AWS signature not signing X-Amz-Date header

### ISSUE THREAD

**Issue by slang25** [a85/POSTMan-Chrome-Extension#8724]
When making a call to an API Gateway API with authtype `AWS_IAM`, calls to the API signed by Postman for with a `304` response code, and the following body:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>There were headers present in the request which were not signed</Message>
    <HeadersNotSigned>x-amz-date</HeadersNotSigned>
    <RequestId>...</RequestId>
    <HostId>...</HostId>
</Error>
```

It looks like the `X-Amz-Date` header is added, but not factored into the canonical representation of the request that is signed. Interestingly, when I look at the hidden headers in Postman I can see that `x-amz-date` is listed in the `SignedHeaders` part of the `Authorization` header, however when I look at the request in fiddler, it is then missing.

1. Create an API Gateway resource in AWS
2. Enable AWS_IAM as the authorization method
3. Export the API definition to Postman (that's so cool!)
4. In Postman, under any request go to the Authorization tab
5. Add accesskey & secretkey details & info (`execute-api` for the service name)
6. Hit send

**Expected behavior**
`200 Ok`

**App information (please complete the following information):**
 - Native App
 - v7.27.1
 - Windows 10 (build 2004)

**Comment by slang25** [comment]
The plot thickens, I've created a simple "Hello world" lambda with IAM auth, and it's working fine! I'll work on a minimal reproduction.

**Comment by vikiCoder** [comment]
I tried to reproduce the issue by calling an AWS S3 endpoint but it worked fine for me (`x-amz-date` header was included in the `SignedHeaders`). And I think it should be the case for API Gateway as well.

Can you check in the Postman console after sending the request, whether the `x-amz-date` is included in `SignedHeaders` or not? And please let us know if you succeed in minimal reproduction of the issue and can share the details/sample collection with us.

**Comment by slang25** [comment]
I ran into the same issue over a year later, googled it and found my own issue 😆 

I've discovered what I'm doing wrong, I've left the option `Add authorization data to` as `Request Headers`, but it should be `Request URL` for this service (API Gateway in my instance).

User error! Nothing to see here 😆  Hopefully this will be useful for anyone else running into the same problem.

**Comment by DannyDainton** [comment]
Seems like the issue has been resolved. Closing this one out. 🎉
