### ISSUE TITLE
How to dynamically pass request in Postman? Need a way where we can dynamically build the json body without hardcoding. Body contains json which is huge.

### ISSUE THREAD

**Issue by AmitKunjir222** [a85/POSTMan-Chrome-Extension#8727]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by DannyDainton** [comment]
Hey @AmitKunjir222,

This seems like a perfect question for our Postman Community forum.

Would you mind create a new topic on the forum and explain the problem you're facing in greater depth. 

I'm confident our community member was help with a solution.

https://community.postman.com
