### ISSUE TITLE
The post method can work with Postman, but cannot work with Curl

### ISSUE THREAD

**Issue by tomwuxj** [a85/POSTMan-Chrome-Extension#8729]
**Describe the bug**
I am not sure if this is a bug. I can make it work on Postman, but I have no idea why I can't make it work with Curl. I have been looking at it for a while and tried many times.

**To Reproduce**
1. build the local server. I use the TP-LINK Omada Controller. You can also download it from [here](https://www.dropbox.com/sh/yg9fvwz0s59ofhe/AABHMR1t31Pw6BdzmDUy-lIUa/v4.1.4%20Firmwares/windows%20software%20controller/Omada_Controller_4.1.4_%5B20200611172437%5D.zip?dl=0) and install it easily on-premises.

2. after the installation, you can log in to the server via https://127.0.0.1:8043. The API endpoint is also https://127.0.0.1:8043

3. on Postman, I build a POST method as the screenshot shows.
![image](https://user-images.githubusercontent.com/35658676/86285782-e6ad9400-bbed-11ea-9c29-b5d9a0683bdc.png)

4. it works as the picture shows
![image](https://user-images.githubusercontent.com/35658676/86285900-283e3f00-bbee-11ea-9b58-fcfc625c79df.png)

5. but when I use the following command on curl, I got "400 Bad Request" Error
curl -k -X POST "https://127.0.0.1:8043/api/v2/login" --header "Content-Type: application/json" -d "{"username":"admin","password":"admin123"}"
![image](https://user-images.githubusercontent.com/35658676/86286287-dc3fca00-bbee-11ea-91e2-f84cc0901b06.png)

I use the Window 10 OS and the curl version is 7.55.1
![image](https://user-images.githubusercontent.com/35658676/86286346-f5487b00-bbee-11ea-9e93-731d90b1b97c.png)

**Comment by DannyDainton** [comment]
Hey @tomwuxj

Is this using the Postman code generated Curl command or something you have crafted yourself?

Does the same thing happen without the `-k` flag?

**Comment by tomwuxj** [comment]
Hello @DannyDainton 

I did try the Curl code generated by Postman, it doesn't work either. Here is the Curl code generated by Postman:
`curl --location --request POST 'https://127.0.0.1:8043/api/v2/login' \
--header 'Content-Type: application/json' \
--header 'Cookie: TPEAP_SESSIONID=4c264caa-f91e-4bc8-acf9-e87379bd8f55' \
--data-raw '{
    "username": "admin",
    "password": "admin123"
}'`

if without -k, I will get the following error:
curl: (35) schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322)

I believe this -k flag is the same as I disable SSL certificate verification on the Postman.

**Comment by tomwuxj** [comment]
Anyone can help me? Highly appreciated!

**Comment by tomwuxj** [comment]
Today I tried with Linux OS, and I still use this command: `curl -k --request POST 'https://192.168.0.104:8043/api/v2/login' -H 'Content-Type: application/json' -d '{"username":"admin","password":"admin123"}'` It works fine.

My curl version is as below:
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3

I guess it's because Windows OS doesn't support some kind of character. But I haven't figured it out yet.

**Comment by aman-v-singh** [comment]
Hey @tomwuxj,
Is there any update on the issue? Did it get resolved?
Please let us know if you need any help.

**Comment by aman-v-singh** [comment]
Hey @tomwuxj,
We have already fixed Windows cURL code snippet bugs, and as this issue is no longer reproducible I will close this issue.
