### ISSUE TITLE
Making Pull Request with 22 new requests doesn't work

### ISSUE THREAD

**Issue by yhminbv** [a85/POSTMan-Chrome-Extension#8730]
**Describe the bug**

**To Reproduce**
1. fork collection from team space to myworksapce
2. add 22 requests to forked collection
3. click 'create pull request' in collection menu
4. new tab of browser opend, but inifinity loding in changes tab and no response to any event (clicking, trying to add text to title)

**Expected behavior**
I want to make pull request for new 22 requests.

**Screenshots**
![image](https://user-images.githubusercontent.com/49857553/86302081-9ca2cd80-bc42-11ea-8783-aa8e938638f3.png)

**App information (please complete the following information):**
 - Navtive App, Chrome (same behavior)
 - Postman Version 7.26.0
 - macOS High Catalina 10.15.2

**Additional context**

**Comment by SKrPl** [comment]
Hi @yhminbv 
Can you please write to us on [help@getpostman.com](mailto:help@getpostman.com) and provide the details of collections (destination and source) along with the link of this Github issue?

**Comment by DannyDainton** [comment]
Hey @yhminbv

I'm going to close this issue for now, we can look to open it again if this is still an issue for you.
