### ISSUE TITLE
oauth2 access_token request, client_id is sent even if basic authentication is added

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#8731]
**Describe the bug**
Postman oauth2 ```access_token``` request sends ```client_id``` in the body parameters event if ```basic``` authentication is applied.

**Expected behavior**
[The OAuth 2.0 Authorization Framework: section 4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3)

>  client_id
         REQUIRED, if the client is not authenticating with the
         authorization server as described in Section 3.2.1.

As the standard describes the ```client_id``` is required ONLY IF the client is NOT authenticated via ```basic``` auhentication

**App information:**
 - Native App
 - Postman Version:  v7.27.1
 - OS: Windows

**Comment by vikiCoder** [comment]
You are right @danieldonev. Thanks for pointing it out. We will be fixing it. Meanwhile, I think you still should be able to generate the token regardless of the extra `client_id` parameter in the token request body. Please let us know if that is not the case and the current behaviour is a blocker for you so we can prioritize it accordingly.

**Comment by eventgo-admin** [comment]
@vikiCoder thank you for your attention. By standards, the ```access_token``` uri params should be strict - no "unknown" query parameters. Since the ```oauth2 server```, which I am trying to use has this standards implemented - it fails since there is "unsupported" query parameter. So yes, it is a blocking issue

**Comment by ghost** [comment]
@vikiCoder thank you for your attention. By standards, the access_token uri params should be strict - no "unknown" query parameters. Since the oauth2 server, which I am trying to use has this standards implemented - it fails since there is "unsupported" query parameter. So yes, it is a blocking issue

**Comment by ghost** [comment]
@vikiCoder Do you have update on this issue. It seems that this problem is still in existence.

**Comment by martinskalicky** [comment]
@danieldonev I think I do have same #9771 issue and it is selected for development. All we need is wait. I hope it will be soon. This is really annoying in my workflow.

**Comment by martinskalicky** [comment]
Hello, any update on this?

**Comment by ghost** [comment]
Any update on this?

**Comment by coditva** [comment]
Hey, this issue has been fixed in version 10.6.x onwards. You should receive the update in the next couple of days, if not already. 🚀 
Let us know if you still face issues. Closing the issue for now. 🙂

**Comment by JohnOnSoftware** [comment]
Hi @coditva , I am using version 10.8.0, but I still got the error complaining "client_id" in the request body while using "send as Basic auth header", any ideas?

**Comment by coditva** [comment]
@JohnOnSoftware Hey, sorry about that. Can you share a screen recording of the issue? It would help us replicate this faster.

**Comment by dylantack** [comment]
I'm also seeing the issue persist on 10.8.0. Is this enough information to replicate? 

![Screenshot_1_18_23__1_38_PM](https://user-images.githubusercontent.com/106996/213302986-900a68fa-4707-4523-baf3-9a1f0bd68abd.png)

**Comment by coditva** [comment]
@dylantack Thanks for the screenshots; they helped. It seems that this is an issue in Scratch Pad mode. We'll fix this soon and update on this thread.

@JohnOnSoftware Can you also confirm that you're seeing this issue in Scratch Pad mode?

**Comment by coditva** [comment]
@dylantack @JohnOnSoftware This has been fixed in Postman v10.9.x. Let me know if you're still facing an issue.
