### ISSUE TITLE
Postman sends payload body on GET requests

### ISSUE THREAD

**Issue by fuweichin** [a85/POSTMan-Chrome-Extension#8732]
Postman sends payload body on GET requests

**Describe the bug**

while web browsers don't, they either ignore the body parameter (XHR API) or throw an error (fetch API), and [RFC7231](https://tools.ietf.org/html/rfc7231) says:  
> A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.

**To Reproduce**

1. Click 'Add Request', select method 'POST', select body 'raw' 'JSON', input '{"id:"1}' as request body
2. Change method to 'GET', and click 'Send'
3. Previously defined request-body was sent to server

**Expected behavior**

Request body should not be sent on GET requests, just ignore it, or if to send, a warning message/confirmation dialog should be given.

By the way, the code snippets generation algorithm may need to be modified considering GET/HEAD methods.

**Screenshots**

N/A

**App information (please complete the following information):**
 - Native App
 - Postman Version [e.g. 6.0.1]
 - OS: Windows 10 Version 2004 Build 19041

**Additional context**
I'm developing a servlet to dump http request/response and find such an issue.

Figure 1: Raw GET request sent by Postman:  the payload body is sent to server
```http
GET /api/echo HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.1
Accept: */*
Cache-Control: no-cache
Postman-Token: 6794638d-8655-48da-9ead-619c3e68a052
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 8

{"id":1}
```

Figure 2: For `fetch`, specifying body on a GET request will result in an error:  
> Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

```js
fetch("/api/echo",{
   method: 'GET',
  headers: {
    'Content-Type': 'application/json',
  },
  body: '{"id":1}'
}).then((res)=>{
  return res.text();
}).then((text)=>{
  console.log(text);
});
```

Figure 3:  For `XMLHttpRequest`, the 'body' parameter passed to `xhr.send()` will not be sent.
```js
request("/api/echo",{
  method: 'GET',
  headers: {
    'Content-Type': 'application/json',
  },
  body: '{"id":1}'
}).then((text)=>{
  console.log(text);
});

function request(url, options={}){
  return new Promise((resolve,reject)=>{
    let xhr=new XMLHttpRequest();
    let method=options.method||"GET";
    xhr.open(method, url);
    xhr.onload=()=>{
      resolve(xhr.response);
    };
    xhr.onerror=()=>{
      reject(new Error('Loading failed '+xhr.status+' '+xhr.statusText));
    };
    let {headers}=options;
    if(headers){
      Object.keys(headers).forEach((k)=>{
        xhr.setRequestHeader(k, headers[k]);
      });
    }
    xhr.responseType=options.responseType||'';
    xhr.send("body" in options?options.body:null);
  });
}
```

**Comment by harshit-j** [comment]
Things like Elastic Search do use body in GET requests. So it is useful for testing.
