### ISSUE TITLE
Cant install new version of postman

### ISSUE THREAD

**Issue by mostopalove** [a85/POSTMan-Chrome-Extension#8733]
**Describe the bug**
It is imposible to install application.

**To Reproduce**
1. Download App
2. Run App
3. See error

**Expected behavior**
Application is worked

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] Native App
 - Postman Version [e.g. 6.0.1] 7.27.1
 - OS: [e.g. macOS High Sierra 10.13.2] macOS Catalina 10.15.5

**Screenshot**
<img width="537" alt="Снимок экрана 2020-07-02 в 16 06 39" src="https://user-images.githubusercontent.com/49098339/86362587-2f149280-bc7e-11ea-89b2-682f961872b4.png">

**Comment by mostopalove** [comment]
<img width="539" alt="Снимок экрана 2020-08-26 в 12 18 11" src="https://user-images.githubusercontent.com/49098339/91285811-511a2500-e796-11ea-8bd7-e6be5cd49c27.png">

**Comment by SabriH10** [comment]
Hi @mostopalove ,

Could you try to clear the Postman folders first and then re-install postman as described here: support.getpostman.com/hc/en-us/articles/360025359014

If things still don't work, write to Postman support by submitting a ticket here: postman.com/support
Include Postman app logs and screenshots: support.getpostman.com/hc/en-us/articles/360047765713

**Comment by DannyDainton** [comment]
I'm going to close this issue due to inactivity - If you're still facing the issue on the latest version, we can look at reopening it again.
