### ISSUE TITLE
SSL CERTIFICATION OPTION IS NOT ENABLED IN 5.5.5 version

### ISSUE THREAD

**Issue by sriharshakatakam** [a85/POSTMan-Chrome-Extension#8734]
installed latest version of postman app from
Chrome extension and SSL Option is not available

![Uploading 86408194...]()

**Comment by DannyDainton** [comment]
Hey @sriharshakatakam 

The latest version of the native desktop app 7.27.1 can be downloaded here:

https://www.postman.com/downloads/

The support and feature development for the chrome extension were stopped at version 5.5.5.

**Comment by SabriH10** [comment]
Hi @sriharshakatakam ,

Considering the information provided by my colleague Danny and the Chrome extension is deprecated, I'll go ahead and close this for now. If you still have questions or concerns or need help with the Native App, don't hesitate to reach out to help@postman.com.

Have a great day!
