### ISSUE TITLE
New IDs are generated on Import or Export 

### ISSUE THREAD

**Issue by entimaniac** [a85/POSTMan-Chrome-Extension#8735]
**Describe the bug**
When importing and/or exporting a collection, a new ID is generated for collection elements such as requests even though there is already an ID present in the file.

**To Reproduce**
1. Create collection.
2. Create a request (doesn't need to 'work', can be empty pretty much)
3. add any basic test like; 
```
pm.test("test", function() {
    pm.response.to.not.be.error;
});
```
2. Export the collection to json (v2.1). 
3. Delete original collection from postman. 
4. Import collection JSON.
5. Export collection again, pick a different location or name, just don't overwrite the previous json file. 
6. compare IDs for the same request (script/test ID) and see they are different even though nothing changed. 

**Expected behavior**
A collection file that has an ID field already should reuse the ID field on import instead of generated a new one. Or if the issue is on export, then don't generate a new ID on export.

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] 
native? whatever the recommended download is for mac
 - Postman Version [e.g. 6.0.1]
Version 7.27.0 (7.27.0)
 - OS: [e.g. macOS High Sierra 10.13.2]
macOS Sierra 10.12.6 

**Additional context**
We use Git. Postman tests are how we run integration tests both locally and in our automated staging environment via Jenkins. with a collection of 1100+ tests, we have SOOO many IDs. And they all get regenerated each time. We do code reviews on Github and the browser breaks if you try to load the diff. My IDE breaks if I try to load the diff. Its unmanageable.

**Comment by fongie** [comment]
There are several other issues for this like #8440 #2906 

I really wish for this to be fixed too since it really messes up our git workflows.. either you have to go edit the json manually or the PRs are really annoying to try to review and find what actually changed.

**Comment by arlemi** [comment]
Let's keep the conversation going in #2906, @entimaniac I'll add your feedback there but please add more if needed!
