### ISSUE TITLE
Wrong cURL code generation when multipart

### ISSUE THREAD

**Issue by nelson-gonzalez** [a85/POSTMan-Chrome-Extension#8736]
**Describe the bug**
When you make a multipart request with a `file` and another field of JSON type, the generated code snippet to run this request with cURL is wrong. Omits the type for the field with JSON type.

**To Reproduce**
1. Create a request with body of type `form-data`
2. Add a field of type `file` with content type `multipart/form-data` and a field of type text with content type `application/json`.
3. Go to `Code` functionality and generate code for `cURL`.
4. See the error. The generated code does not work, but postman request do.

**Expected behavior**
The generated code sniped should be:
```
curl --location --request POST 'https://example.com/documents' \
--form 'file=@/Users/xxxx/Downloads/0ffaa789-b1a7-4ce3-a80b-4c7f3fcfd5d2.png' \
--form 'metadata={"group": "PROOF_RESIDENCE","type": "UNDEFINED","side": "FRONT"};type=application/json'
```

**Screenshots**
Image for step 2:
![image](https://user-images.githubusercontent.com/61240359/86418051-93dae780-bc94-11ea-8814-644e4636fb5e.png)

Image for step 3:
![image](https://user-images.githubusercontent.com/61240359/86418120-c1c02c00-bc94-11ea-9b13-c833b7192cf2.png)

**App information:**
 - App Type: Native App
 - Postman Version: 7.27.1
 - OS: macOS Catalina 10.15.5

**Additional context**
This problem exist in almost all libraries that generate content body for `multipart/form-data`.

**Comment by IlabSentuser** [comment]
Hello, unless I am confused about this changes I think the problem is not solved. cURL codegens keep ignoring content-type in order to generate the snippets. 

![Screenshot_20211215_164722](https://user-images.githubusercontent.com/71553739/146220657-0e47018c-95da-4fbb-8efc-5cc2d947eea9.png)
