### ISSUE TITLE
OAuth 1.0 signature keeps failing once I upgraded to v7.27.1

### ISSUE THREAD

**Issue by noizecamp** [a85/POSTMan-Chrome-Extension#8737]
**Describe the bug**
All OAuth1 requests in my collection start failing after upgraded to v7.27.1. The signature generated is different from what it used to be.
Could be related to https://github.com/postmanlabs/postman-app-support/issues/8402

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.27.1
 - OS: Windows

**Comment by vikiCoder** [comment]
Can you please provide the following information about your request so that we can identify the issue?

1. Which signature method are you using in OAuth1?
2. Is the signature method same before and after the Postman app update?
3. Are you using `callback` and `verifier` fields recently added in 7.27.0?
4. Is `include body hash` option enabled?
5. Is the authorization data added in request body/request URL or in request headers?

It would be great if you can provide a sample collection with the configuration you are using (minus the sensitive information).

**Comment by firstlight-comm** [comment]
I am seeing the same problem. I am using:

1.  HMAC- SHA1
2. same signature method as before
3. I am not using `callback` or `verifier`
4. I am not using `include body hash`
5. Add authorization data to = Request Headers

**Comment by noizecamp** [comment]
@vikiCoder My settings are exactly the same as above. I reverted to back to v6 and it started working again.

![image](https://user-images.githubusercontent.com/11703462/86869882-ec353d80-c109-11ea-8c20-c5117ca3decb.png)

**Comment by vikiCoder** [comment]
I think it could be because of the newly added fields(in the latest version) `Verifier` and `Callback` left empty. Can you please try disabling the `Add empty parameters to signature` option in the latest version (v7.27.1) and see if that works?

**Comment by firstlight-comm** [comment]
The endpoint I"m calling requires the `Add empty parameters to signature` option to be selected. A co-worker is using an older version of Postman and is succeeding with the same options that I'm using, including the `Add empty parameters to signature` option. Is there a way to install an older version of Postman while I wait for this to be resolved?

**Comment by noizecamp** [comment]
@Firstlist-comm I got v6 from the link below. You may want to save a dump before you install v6. Somehow the collections are not synced for me when I started using the old version.
https://learning.postman.com/docs/administration/migrating-to-v7/

**Comment by frahugo** [comment]
> I think it could be because of the newly added fields(in the latest version) `Verifier` and `Callback` left empty. Can you please try disabling the `Add empty parameters to signature` option in the latest version (v7.27.1) and see if that works?

I had the same problem since 2-3 days. Disabling that option fixed the issue on my side.

**Comment by mccannt** [comment]
This issue should be resolved now in v7.32 
Closing this issue. If you are still experiencing this issue on the latest version, let us know.
