### ISSUE TITLE
Improper scrolling in the Interceptor/proxy dropdown

### ISSUE THREAD

**Issue by adriancuadrado** [a85/POSTMan-Chrome-Extension#8738]
**Describe the bug**
Can't see some fields in a popup.

**To Reproduce**
1. Open Postman in a screen with low resolution. Mine is 1919x1079
2. Click on the button at the top bar to open the popup to 'Capture requests and cookies'
3. Scroll down as much as you can
4. You can't reach the 'Methods' field unless you focus another field and keep pressing TAB until 'Methods' get focus, or by zooming out.

**Expected behavior**
The popup should be more responsive and resize itself upon the available height size of the window. The popup won't show the contents properly because it is larger than the window itself in some cases.

**Screenshots**
![image](https://user-images.githubusercontent.com/29214635/86566345-c83af600-bf69-11ea-92d1-33f028347fa0.png)

**App information (please complete the following information):**
 - App Type :Native App
 - Postman Version 7.27.1
 - OS: Windows 10

**Comment by shashankawasthi88** [comment]
@adriancuadrado this should be solved with the latest version of the app. You should be able to scroll to any element within the proxy/ interceptor pannel.
