### ISSUE TITLE
Could not send request

### ISSUE THREAD

**Issue by Saurabh9455** [a85/POSTMan-Chrome-Extension#8741]
Not able to hit apis deployed on AWS through postman

**Comment by vvs11** [comment]
@Saurabh9455 could you provide us with more info on what you're trying to do? Preferably with a screenshot. 
Also, we have a very active community where you can reach out for quicker response http://community.getpostman.com/

**Comment by thesaurabhsrivastav** [comment]
*Hi,*

I have deployed my spring boot application on AWS Elastic Beanstalk and it
is working fine when I hit APIs on browser,
But not able to hit APIs from postman.
Please find below snapshot.

[image: image.png]

**Comment by arlemi** [comment]
@Saurabh9455 We're not able to see the file attached. You'll have to visit the thread on browser to attach it to a message I think.

**Comment by DannyDainton** [comment]
Hey @Saurabh9455 

Are you still seeing this issue?

**Comment by DannyDainton** [comment]
Hey @Saurabh9455  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
