### ISSUE TITLE
TLS 1.3 post-handshake authentication > Implement RFC 8740 "Using TLS 1.3 with HTTP/2"

### ISSUE THREAD

**Issue by schefbi** [a85/POSTMan-Chrome-Extension#8743]
There is a problem with TLS 1.3 post-handshake authentication in Chrome and Firefox. In Postman version v7.25.2 you have support for TLS v1.3, is it possible to add TLS v1.3 to protocols that are disabled during handshake or fixed that bug with TLS v1.3 post-handshake authentication?  

https://bugzilla.mozilla.org/show_bug.cgi?id=1637754

Thanks

**Comment by schefbi** [comment]
Please add  TLS v1.3 to "protocols that are disabled during handshake". This would help us a lot so that we can monitor our test and production environment again. 
![image](https://user-images.githubusercontent.com/41326409/108379858-9d569700-7206-11eb-9285-122061943d8c.png)

 Thanks a lot

**Comment by codenirvana** [comment]
@schefbi We've added support for disabling **TLS v1.3** last year, probably forgot to update this thread 🤦🏻‍♂️.

<img width="1002" alt="Screenshot 2022-01-04 at 4 28 08 PM" src="https://user-images.githubusercontent.com/4865836/148049148-9f680a66-48fc-427d-a7bf-a50b20dd6065.png">

Please feel free to reopen if the issue persists.
