### ISSUE TITLE
404 error status is not displaying in v7.27.1

### ISSUE THREAD

**Issue by Dipankar151** [a85/POSTMan-Chrome-Extension#8745]
Error status is not showing in postman v7.27.1. All the error status code should get displayed if the a user fires an incorrect request. Here in the img I fired a GET request instead of POST, hence it should show the 404 ERROR code, which is not being displayed. Please help in this
![image](https://user-images.githubusercontent.com/67973385/86823933-1b689200-c0ab-11ea-8488-9a47291ea3b2.png)

**Comment by arlemi** [comment]
@Dipankar151 You'll only get 404 for endpoints/subdomains of existing domains. In your case it looks like restapi.demoqa.com isn't a valid domain, hence why you're getting ENOTFOUND instead of a 404. Double-check the URL and it should work correctly.
