### ISSUE TITLE
Collection Runner not running all requested iterations

### ISSUE THREAD

**Issue by NelsonRebelo** [a85/POSTMan-Chrome-Extension#8746]
I've searched for a solution, and also for similar issues already open, and couldn't find anything that suited this problem, so I'm assuming it's a bug. I apologize if this issue is already reported.

**Describe the bug**
I've been facing a couple of issues with Postman's Collection Runner when there's a lot of requests involved. After asking collection runner to run **X** amount of iterations, it doesn't run all of them, but returns the information that it did.

**Context:**
- I'm using a CSV that contains all the data I want to send in the requests, provided the headers and proper variables -> https://prnt.sc/tdlupa
- The collection I'm running includes 4 different post requests. All requests contain tests to confirm if the response was positive or not ->
- I ran the whole CSV data, which means Collection Runner would run **1853 iterations** (a total of **7412 requests**) -> https://prnt.sc/tdl2p5

**Results:**
- Visually, it seems that all 1853 iterations were ran -> https://prnt.sc/tdljem
- It returns the information that only 6946 requests were sent, instead of 7412 -> https://prnt.sc/tdleeb
- Exporting the results, we can see it only ran 1735 tests for one of the requests involved, instead of the 1853 -> https://prnt.sc/tdld78
- I can only see the result of 1735 of the above example request in the endpoint DB, instead of 1853.

**To Reproduce:**

It's a very specific case to reproduce but:
1. Create a collection with multiple post requests, with variables within the payload.
2. Run Collection Runner and use the CSV feature to populate your variables
3. Check the amount of total iterations (for the purpose of this test, should be a reality of 1k+ iterations)
4. Run Collection Runner, and check in the exported results how many iterations actually ran

**Expected behavior**
Once X amount of iterations are set to run in Collection Runner, Postman should attempt to run all of them.

**App information:**
 - Native App
 - Postman Version 7.27.1
 - MacOS 10.14.6 (18G5033) Mojave

**Additional context**
Nothing for now.

**Comment by NelsonRebelo** [comment]
Update:

The Iteration didn't run due to a 500 Internal Server Error. Still investigating why is this is, but doesn't seem to be a Postman Bug.  https://prnt.sc/te1lsq

**Comment by arlemi** [comment]
@NelsonRebelo Thanks for letting us know! I'll close this for now, let us know if you're facing any other issue.
