### ISSUE TITLE
High CPU Usage on macOS when waiting for request

### ISSUE THREAD

**Issue by e-xing** [a85/POSTMan-Chrome-Extension#8749]
**Describe the bug**
While waiting for a request to return its response, postman will take more than half a core.
![image](https://user-images.githubusercontent.com/3982358/86839027-e50d2180-c06e-11ea-8045-d0ef83a58d7c.png)

**To Reproduce**
1. Call any endpoint that doesn't return immediately
2. Send the request
3. Check CPU usage while the request hasn't returned

**Expected behavior**
Pretty close to 0% cpu usage, like how browsers/curl behave

**App information (please complete the following information):**
Postman for Mac
Version 7.27.1
OS X 19.5.0 / x64 (Catalina, but also reproduced on Mojave)

**Comment by kamalaknn** [comment]
@LegitPanda Could you try out the latest version and let us know if you are still seeing this?
