### ISSUE TITLE
Publish templates button returning 404

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#8750]
**Describe the bug**
The publish template button on the top of the page (https://explore.postman.com/templates) returns a 404

**To Reproduce**
It currently redirects to a learning center page- https://learning.postman.com/docs/postman_for_publishers/postman_templates/add_templates

**Expected behavior**
If the intention is to point towadrs documentation- it should be redirected to this page I believe: https://learning.postman.com/docs/publishing-your-api/add-templates/

**Screenshots**
<img width="1385" alt="Screenshot 2020-07-08 at 9 47 07 AM" src="https://user-images.githubusercontent.com/12132423/86875447-24378300-c100-11ea-872c-fc8b7d00728f.png">

**Comment by gitThingsDone** [comment]
@harshachelle thanks for reporting this! It should be fixed now 👍

**Comment by harsh-reality** [comment]
@gitThingsDone thanks, it is now fixed.

Now, I notice a similar issue with the **Add to API Network** button here- https://explore.postman.com/. Throws a 404. Pease fix this as well?

**Comment by gitThingsDone** [comment]
The link on https://explore.postman.com/ is fixed now too 👍
