### ISSUE TITLE
Memory error once postman is loaded up

### ISSUE THREAD

**Issue by JamesElliott-Wren** [a85/POSTMan-Chrome-Extension#8751]
**Describe the bug**
Numerous memory relates issues when trying to use Postman

**To Reproduce**
1. Open Postman
2. Try to load up an API in the collection
3. The response time is sluggish and is prone to blacking out completely. 

**Expected behavior**
There should be no issues. 

**Screenshots**
<img width="1188" alt="Screenshot 2020-07-08 at 11 18 56" src="https://user-images.githubusercontent.com/68007981/86908828-10dfe400-c10f-11ea-9fa5-ce6f2a657a6d.png">
<img width="1267" alt="Screenshot 2020-07-08 at 11 32 49" src="https://user-images.githubusercontent.com/68007981/86908833-12a9a780-c10f-11ea-96ae-f25ea9b19093.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version : 7.27.1
 - OS:  macOS Catalina 10.15.5

**Comment by arlemi** [comment]
@JamesElliott-Wren We're tracking this in #7294, could you please get your logs and share them with our support team on help@postman.com? 

Please follow up in #7294, I'll close this one.
