### ISSUE TITLE
Unique icons for each workspace

### ISSUE THREAD

**Issue by dalthonmh** [a85/POSTMan-Chrome-Extension#8758]
**Is your feature request related to a problem?**
Once I send a request and don't receive anything because the environment variables, so I realized I'm in local workspace and not in team workspace where the environments be defined.

**Describe the solution you'd like**
It would be helpful to have an icon for each workspace like this:

![workspace icons](https://user-images.githubusercontent.com/35436405/87156077-b4510600-c281-11ea-9c2f-0815d9b8efb5.png)

**Comment by arlemi** [comment]
Thanks for the suggestion @D4ITON, we'll look into it and update here if we decide to implement it. In the meantime, anyone else agreeing that this is a good feature request can add a 👍 on the original post to show interest. 🙂

**Comment by sankalp0o** [comment]
Hey @D4ITON , we've added different icons for workspaces with different visibility, very similar to what you had suggested. Do give our recent versions (v8+) a try and tell us what you think. The same experience is also available on the web. In the meantime, I'll close this ticket, but do let us know how we can improve this experience.

**Comment by dalthonmh** [comment]
Hi, I'm grateful to have contributed, It seems useful, if someone else think there is a better option it could be welcome, so much thanks postman team!
