### ISSUE TITLE
Could not send request: Error: write EFAULT

### ISSUE THREAD

**Issue by azimkhank** [a85/POSTMan-Chrome-Extension#8759]
All my post requests get error:  Could not send request. Error: write EFAULT.

![error](https://user-images.githubusercontent.com/35109608/87163051-95398f00-c2e8-11ea-97ce-4200ebcbd9c4.png)

Postman for Windows
Version 7.27.1
win32 10.0.19041 / x64

**Comment by vvs11** [comment]
@azimkhank could you share the error you're seeing in the console?
Also, for quicker response, you can reach out to our community https://community.getpostman.com/

**Comment by azimkhank** [comment]
![error](https://user-images.githubusercontent.com/35109608/87220240-f95d6100-c383-11ea-8a32-18427b149d1a.png)

**Comment by DannyDainton** [comment]
Hey @azimkhank  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
