### ISSUE TITLE
Postman bootcamp issue with 'Open the collection browser'

### ISSUE THREAD

**Issue by julia-blake** [a85/POSTMan-Chrome-Extension#8760]
**Describe the bug**
I've started 'API Documentation' lesson via Postman Bootcamp. The collection was imported successfully. Then I added the description of a collection as pop-up asked.  After that the next pop-up told me to click the 'collection browser' button. I did it, but the next pop-up doesn't appear and blocks the further lesson passage.

**To Reproduce**
1. Go to 'API Documentation' lesson' via Bookcamp.
2. Click on 'Import' button in the pop-up window.
3. Click on 'Open the collection browser'.
4. Click on 'Add description' button and add some.
5. Click on 'Save' button.
6. Click on 'Continue learning' button.
7. Click on 'Open the collection browser'.
8. Pop-up window vanishes and there are no next steps that show up.

**Expected behavior**
The next pop-up appears to preceed the lesson.

**Screenshots**
[https://www.screencast.com/t/Ni4aWGiNX](url)

**App information:**

 -  App Type [Native App]
 - Postman for Windows [v.7.27.1]
 - OS: [Windows 10 18363.900 / x64]

**Comment by arlemi** [comment]
Hey there,

I'm closing this issue as the Bootcamp is not available in the app anymore from the March 2023 (v10.12) release.

If you're interested in Postman training courses here's a few resources to check out:
-  [Postman Quickstarts](https://quickstarts.postman.com/) 
-  [Postman Academy](https://academy.postman.com/)
- [Postman Intergalactic webinars](https://www.postman.com/events/intergalactic/)
