### ISSUE TITLE
Very slow & unresponsive. High CPU and memory usage

### ISSUE THREAD

**Issue by zubairk-net** [a85/POSTMan-Chrome-Extension#8761]
**Describe the bug**
It has become very slow lately(last few weeks). It consumes lot of RAM as soon as it is launched even before start using it. RAM usage goes up as I start using it. I have been using postman for years and this is the first time I m facing this unresponsiveness. I have about 8 collections and less than 60 requests total. Everything is slow including typing, sending request, clicking any icon or button. Even if I close all requests or switch collection it is still slow. At my previous job I had much bigger collection and apis which would return large data but I never ran into such issues. Sometimes even with high RAM usage it is still responsive but sometimes it just becomes very slow and its unmanageable to work with.

**To Reproduce**
1. Launch TaskManager to keep an eye on RAM and CPU usage.
2. Launch postman v7.27.1
3. Watch CPU and RAM going up in  TaskManager
4. Go to postman and open a request or type something.

**Expected behavior**
Being able to work normally.

**Screenshots**
Here is the screenshot of my TaskManager showing RAM and CPU usage for both postman and postman Canary. I am not sure why Canary's title says "Sign in to Postman" where as I am already signed in and it loaded my workspaces.
![image](https://user-images.githubusercontent.com/15318792/87180003-51716600-c2a5-11ea-9b5f-43728a48fc65.png)

**App information (please complete the following information):**
- App Type [Native App]
- Postman for Windows [v.7.27.1]
- OS: [Windows 10 18362.836 / x64]
- System:- Windows 10 Pro with 8th Gen i7, 16GB RAM with SSD

**Additional context**
I installed Canary yesterday and neither it consumes much RAM nor CPU. I can work normally using same collection.

**Comment by ejanla2** [comment]
Same on the Mac. Postman has been unusable for the past two weeks, and we've had to script up our tests in the meantime.
It persistently clogs the CPU (over 100% CPU utilization).
What's going on?
<img width="423" alt="Screen Shot 2020-07-11 at 8 41 07 PM" src="https://user-images.githubusercontent.com/2252128/87236389-f9c31f80-c3b6-11ea-96e6-b495e589df30.png">

**Comment by ejanla2** [comment]
Update: We found a way around this by using Postman Canary. Much more stable and usable at the moment.
Also, the issue with the Postman main app may be larger than we thought. Many of our tests started failing this week and we've been digging. Using Postman Canary, the same tests are now passing, which is what we expect.

**Comment by kamalaknn** [comment]
@ejan1a @zubairk-net Would it be possible to record and share a performance profile? It'll help us triage the issue and resolve as soon as possible.

Here's the how-to on recording a profile: https://www.loom.com/share/01e103f8511549ec93e22ff2afb2769e

**Comment by zubairk-net** [comment]
Here are the steps I followed to recored profile.
I launched postman.
I didnt touch a thing in postman like issues a request or any work
I launched Developer Tools and started recording
I let it run about 3 minutes and watched RAM usage increasing in TaskManager until it reached above 3000MB
Then I stopped recording and saved profile.

Please see Taskmanager picture "Postman-RAM-CPU-usage.png" attached

I recorded a 3 minutes profile but Json file was 180+MB so I have zipped it, it is still 14MB. Github is not accepting my email so I recorded a 15second profile adn sending that instead. If you want the long one then please tell me an email address which can accept upto 15MB attachments. Please find zipped profile attached.

Please let me know if these help.

Regards
Zubair

________________________________

**Comment by kamalaknn** [comment]
Hey @zubairk-net 

Could you share the profile recording to `help@postman.com`? You can record the profile for 10-15 seconds. The RAM usage spike might be because of the DevTools was trying to handle a very large profile.

**Comment by mariDubois** [comment]
Same for me. It takes ages to update a collection variable. It freezes and I'm not able to work.
How can I get an older version of Postman?

**Comment by numaanashraf** [comment]
@zubairk-net Could you send the profile to help@postman.com?

**Comment by numaanashraf** [comment]
@mariDubois Would it be possible to record and share a performance profile? It'll help us triage the issue and resolve as soon as possible.

Here's the how-to on recording a profile: https://www.loom.com/share/01e103f8511549ec93e22ff2afb2769e

**Comment by mariDubois** [comment]
@numaanashraf I'll try to do it when I have more time (urgency at work :/).
![image](https://user-images.githubusercontent.com/53441110/87795140-eb0dba00-c847-11ea-8b00-0fdc732385dc.png)

Is it possible to have an v7 version of postman for Windows 64 older than v26 please? (as issue seems to begin with v27(?))
I was using a v6 of postman. I updated to latest  I read that adding headers to request programmatically was solved in v7.

Thank you in advance.

**Comment by numaanashraf** [comment]
@mariDubois Sure! Could you write to us at help@postman.com? We can help you out with an earlier build.

**Comment by mariDubois** [comment]
@numaanashraf Thanks :) Mail sent!

**Comment by zubairk-net** [comment]
Numaan,

I sent my profile last week. My issue has been resolved. Please follow ticket #54127 and let me know if you still need profile recording.

Regards
Zubair

________________________________

**Comment by mariDubois** [comment]
@zubairk-net  Hello 

Is it possible please to put a link for ticket 54127? I didn't manage to find it and I'm curious to know if it can solve my issue :)

Thank you in advance.
Regards

**Comment by zubairk-net** [comment]
Hi,

My issue was resolved by turning off interceptor in chrome. Someone named "JP" was comminucating with me from postman team. Please see email msgs below:-
BEGIN================================================
Zubair Khan

Jul 18, 2020, 12:58 AM UTC

yep, it is back to normal since I turned interceptor off.

Thank you guys for the support.

JP (Postman)

Jul 17, 2020, 11:02 PM UTC

Hi Zubair,

Thanks for checking. Sounds like you're seeing an improvement with Interceptor turned off?
Cheers,
JP
Product Support, Postman

Check out our status page: https://status.postman.com/
Learning Center: https://learning.postman.com
File bugs or feature requests: https://github.com/postmanlabs
Ask "How do I?" questions in our community: https://community.postman.com

Zubair Khan

Jul 16, 2020, 7:01 PM UTC

I turned off interceptor, logout and login again. I guess I need to keep interceptor off until I really need it

Regards
Zubair

JP (Postman)

Jul 16, 2020, 6:42 PM UTC

Hi there,

Thanks for sharing.

From the profile we could see a lot of activity from Interceptor. Would you please try turning off Interceptor to see if it helps? Also, please try signing out and signing in + turning off Interceptor.
Cheers,
JP
Product Support, Postman

Check out our status page: https://status.postman.com/
Learning Center: https://learning.postman.com
File bugs or feature requests: https://github.com/postmanlabs
Ask "How do I?" questions in our community: https://community.postman.com


END================================================

I hope this help you.

Regards
Zubair
________________________________

**Comment by zubairk-net** [comment]
https://support.getpostman.com/requests/54127/satisfaction/new/g7cOuoIjg8kz6XPJ6lHW23rPh?locale=1&intention=16


________________________________

**Comment by mariDubois** [comment]
@zubairk-net Thank you :) For me I used an older version an my issue was solved. Will try some day update and see if it solves the problem :)

**Comment by qualitas-software** [comment]
I had high CPU from Postman whilst doing frankly nothing.  Installing the pending update has worked for me so far (now a couple of hours).

I am now on:
  Postman for Windows
  Version 8.3.0
  win32 10.0.18363 / x64

**Comment by jviotti** [comment]
Merging this issue with https://github.com/postmanlabs/postman-app-support/issues/7294
