### ISSUE TITLE
All of my requests have disappeared

### ISSUE THREAD

**Issue by randeepbydesign** [a85/POSTMan-Chrome-Extension#8762]
I opened up Postman and found it had been upgraded significanltly. Dark mode... yes!

However, I can't see any of my requests. If I go to Runner I can see the collections there but cannot access anything.

I am on a MacOs using Postman 7.27.1

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by mccannt** [comment]
@randeepbydesign Can you send an email to help@postman.com ? Someone from our side should be able to help you out.

**Comment by SabriH10** [comment]
Hi @randeepbydesign,

I am just following up here. Did you get a chance to write to help@postman.com so we can assist further? I'll wait for your response to confirm so we can close out the issue here and help troubleshoot when you've written in.

**Comment by randeepbydesign** [comment]
I did but, in the interim I logged out and logged back in and the cloud synch took over and fixed this. It's still a scary user experience but glad I still have all my work,
