### ISSUE TITLE
Post not always sending content-length 

### ISSUE THREAD

**Issue by DanFreed** [a85/POSTMan-Chrome-Extension#8763]
**Describe the bug**
When sending a request from PostMan to a HTTPS service, it reliably only sends the content-length of the package every other time I send the exact same package.  The only potentially unique scenario is that I'm using a client certificate as part of the request.

When it doesn't send the content-length it causes this error :

`
Error: write EPROTO 140217382453800:error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 80
`

The console log entries (keep in mind I simply clicked the send button 2x in a row for the exact same request):

`
POST https://kennel234.company.com:10443/service
200
452 ms
Warning: Self signed certificate
Client Certificate
Network
Request Headers
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/7.26.1
Accept: */*
Cache-Control: no-cache
Postman-Token: fb0d1e78-e830-4ee8-b594-fbc430c277b2
Host: kennel234.dhcp.epic.com:10443
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
**Content-Length: 609**
Request Body xml: _"<xml>omitted</xml>"
Response Headers
Date: Fri Jul 10 20:55:26 2020 GMT
Connection: close
Server: ESMPD/Epic522128-97323
Content-type: text/xml
Response Body

POST https://kennel234.company.com:10443/service
Error: write EPROTO 140217382453800:error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 80
Client Certificate
Request Headers
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/7.26.1
Accept: */*
Cache-Control: no-cache
Postman-Token: c500973f-f1ef-4d97-92b9-93cd17fa7d4c
Host: kennel234.dhcp.epic.com:10443
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Request Body xml: _"<xml>omitted</xml>"
`

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version Version 7.27.1 (7.27.1)
 - OS: macOS Catalina 10.15.5

**Comment by mohitranka** [comment]
@DanFreed Could you try executing this the equivalent `curl` command (found under the `code` ) in the terminal, and list the behaviour?

![image](https://user-images.githubusercontent.com/80672/87278199-80841380-c501-11ea-9138-43de11de4ea5.png)

**Comment by DanFreed** [comment]
That returns the expected XML package every time I call it. There isn't much to show that shouldn't be obfuscated.  

```
curl --insecure --location --request POST 'https://kennel234.dhcp.epic.com:10443/esmpcom' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'xml=._..omitted_.'
<?xml version="1.0" encoding="utf-8"?>
_...omitted..._

```

**Comment by DanFreed** [comment]
I was initially thinking this was related to using client certificates in PostMan, but I've removed the client certificate I was using (which is only optional in my application), and it is behaving the same way.  Every other execution it generates the error.

**Comment by mohitranka** [comment]
@DanFreed  I cannot reach this URL, can you confirm that the `Content-Length` is returned every time via the curl command? This is set by the Server, so we need to establish if the issue is with Postman or the Server's implementation.

**Comment by DannyDainton** [comment]
Hey @DanFreed  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
