### ISSUE TITLE
Black screen and then crash

### ISSUE THREAD

**Issue by MatteoInfi** [a85/POSTMan-Chrome-Extension#8765]
**Describe the bug**
Trying to start postman, but I get blank screen

**To Reproduce**
1. Open postman

**Expected behavior**
Should work normally

**App information (please complete the following information):**
 - App Type Desktop
 - Postman Version 7.27.1
 - OS: Ubuntu 18.04.4 LTS

**Comment by kamalaknn** [comment]
Hey @MatteoInfi 

Could you share your logs from `View -> Developer -> Show logs in Finder` with us at `help@postman.com` so we can take a closer look at the issue?

**Comment by havaball** [comment]
I am getting the same issue when I start up postman.  It starts with postman trying to load or acting like it is going to load, then it goes to a gray screen and nothing shows.

**Comment by MatteoInfi** [comment]
> Hey @MatteoInfi
> 
> Could you share your logs from `View -> Developer -> Show logs in Finder` with us at `help@postman.com` so we can take a closer look at the issue?

Unfortunately I cannot access that section, postman completely stop working

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5980
