### ISSUE TITLE
pre-requisite file is not executed in CLI mode

### ISSUE THREAD

**Issue by jtj999** [a85/POSTMan-Chrome-Extension#8766]
**Describe the bug**
I created a collection with a pre-requisite file to set a global or environment parameter but the pre-requisite file is not executed when I ran it from CLI mode.

**To Reproduce**
1. Go to window CMD and from Nodejs Dir , run newman run https://www.getpostman.com/collections/a734cb4eecdb723f788a
the pre-requisite file contain pm.globals.set("url","http://13.210.49.61");
2. See error
![image](https://user-images.githubusercontent.com/67640441/87297945-2f741f80-c501-11ea-8020-ba44421ede47.png)

**Expected behavior**

I expect the "url" variable to be set to "http://13.210.49.61"

**App information (please complete the following information):**
 - newman version14.5.0 (includes npm 6.14.5)
 - Postman Version v7.27.1 
 - OS: window 10

**Additional context**

**Comment by DannyDainton** [comment]
Hey @jtj999 

I was able to import the collection using the link provided - I don't see anything set in any of the pre-request scripts.

Have you made the change to the collection and not updated that link? Without updating the link, the changes won't take effect.

**Comment by jtj999** [comment]
HI, Thanks for helping out.

I have  created the link at all time, by select the share button and GEt publik Link.

is this the correct way to update the link ?

Thanks
________________________________

**Comment by DannyDainton** [comment]
The link is a snapshot of the collection at the time of creating it. 

Any changes made to the collection, even if they are saved, won't be included in the link until its updated.

You can do this by going to `Share` again and selecting 'Update Link', once that's done the changes will be run with Newman.

You would need to do this each time a change is made, alternatively, you could use the Postman API URL for the Collection to get the most up-to-date version without the need to update it each time.

**Comment by jtj999** [comment]
Thank you turned out I need to click the update button.
I thought select , share will create  a new link.

Thank you so much
________________________________

**Comment by DannyDainton** [comment]
Closing this as it seems you have solved the problem. 😁
