### ISSUE TITLE
Trying to publish API on Postman

### ISSUE THREAD

**Issue by Kineto** [a85/POSTMan-Chrome-Extension#8772]
**Describe the bug**
I am trying to publish the API from Postman, but I get a 404 error.

**To Reproduce**
1. Go to Postman
2. Click on Publish from the Collection
3. In the window that opens I select the domain I want to use bankapi-swagger.rtgnt.co
4. I click on Publish and get a success message
5. But when I open the url I get 404

**Expected behavior**
The api should be available the URL.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Chrome
 - Postman Version: 7.27.1
 - OS: macOS High Sierra 10.13.2

**Comment by Kineto** [comment]
![Screenshot 2020-07-14 at 09 37 58](https://user-images.githubusercontent.com/68270338/87398156-c9959f80-c5b5-11ea-88fb-6cb260542780.png)
![Screenshot 2020-07-14 at 09 37 03](https://user-images.githubusercontent.com/68270338/87398163-cbf7f980-c5b5-11ea-9748-f86b2796ef5f.png)

**Comment by Kineto** [comment]
![Screenshot 2020-07-14 at 09 37 03](https://user-images.githubusercontent.com/68270338/87398249-eaf68b80-c5b5-11ea-8ee9-f456af800cb6.png)

**Comment by Kineto** [comment]
![Screenshot 2020-07-14 at 09 39 17](https://user-images.githubusercontent.com/68270338/87398288-f8137a80-c5b5-11ea-8591-9022640f0332.png)

**Comment by godfrzero** [comment]
Hey @Kineto, I'm checking out the DNS entries for bankapi-swagger.rtgnt.co and rtgnt.co but I don't see the requisite CNAME & TXT records. I'm guessing these were removed, but please let me know if that's not the case.

Also, could you try publishing without the custom domain and post the link here? We're looking into this in parallel as well.

**Comment by godfrzero** [comment]
I just realized that bankapi-swagger.rtgint.co is the correct address, and bankapi-swagger.rtgnt.co is a typo. https://bankapi-swagger.rtgint.co seems to be working.

**Comment by Kineto** [comment]
Yes it is working now. Thanks. 

Kind regards
Kumarie

On 15 Jul 2020, at 08:22, Vivek Thuravupala <notifications@github.com> wrote:

﻿
I just realized that bankapi-swagger.rtgint.co is the correct address, and bankapi-swagger.rtgnt.co is a typo. https://bankapi-swagger.rtgint.co seems to be working.
