### ISSUE TITLE
Please, return previous design of a response panel

### ISSUE THREAD

**Issue by catherine-greene** [a85/POSTMan-Chrome-Extension#8773]
Please, return previous design of a response panel. The new one is very uncomfortable and annoying. 
![Screenshot](https://user-images.githubusercontent.com/36898627/87415287-94994500-c5d5-11ea-8f23-fa81f1f1eab2.png)
We need open a dropdown each time to see test results or body. That reduces productivity and is very user unfriendly!

**Comment by coditva** [comment]
Hey, @catherine-greene the dropdown appears when there isn't enough space in the response panel to show the tabs. You can change the dropdown to tabs by simply resizing the response pane to a bigger size.
![Screen Recording 2020-07-14 at 17 04 41](https://user-images.githubusercontent.com/8445768/87421332-637c3d00-c5f4-11ea-93c7-5930579f4aee.gif)


If you don't have enough space inside the Postman window, you can switch to a single-pane layout for wider space.
![image](https://user-images.githubusercontent.com/8445768/87421463-96263580-c5f4-11ea-80e6-c6bc8e4c883f.png)

**Comment by catherine-greene** [comment]
hm.. Yeah I see now . That is because this info 
![image](https://user-images.githubusercontent.com/36898627/87422787-ed6eda80-c5e1-11ea-839a-647701827809.png) now takes more space. 
Bad decision....but anyway. 
Thank you for the response

**Comment by shamasis** [comment]
@catherine-greene ... in next few rounds we will take care of the right side that takes up space. The conundrum is between presenting it consuming more vertical space versus more horizontal ones. 

Also researching to give more options in times to come as to what to keep visible and what to converge under dropdown based on your preferences.
