### ISSUE TITLE
Environment variables get ignored when creating mock server example

### ISSUE THREAD

**Issue by BennyAlex** [a85/POSTMan-Chrome-Extension#8774]
**Describe the bug**
When I try to create a example response for an mock server for GET: {{url}}/my-ressource it does not work **(where url is the URL of the mock server and an api prefix (eg.  https://123-456.mock.pstmn.io/api/v1.0)**

The api still throw {"error":{"name":"mockRequestNotFoundError","message":"Double check your method and the request path and try again.","header":"No matching requests"}}

The url variable is created and filled in my current environment and the example response have been modified and saved.

When using the complete mock url and api endpoint manually in the 'add-example-view' it works as expected.

This is really impractical considering having to write two requests for the same ressource to cover the mock and the real endpoints.

**Expected behavior**
The example response gets created for the complete mockup url which is stored in the variable. 
So I can use the same request in a different environment (the real one for example).

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/17402724/87429251-c6b1a380-c5e3-11ea-8f1a-a183dab4af01.png)

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [7.28]
 - OS: [windows 10]

**Comment by pranayat** [comment]
The `{{url}}{{api}}` portion of the example url is being considered as the host and the `filters/templates` portion is being considered as the path.

For now, can you update your example request to `{{url}}/{{api}}/filters/templates` and save your variables as `{{url}} = anybaseurl`, `{{api}} = api` (and not '/api').

'/' stored in the environment variable is getting ignored while trying to match your request path. So for now you can separate your variables by '/'.

This may not be ideal and we are working on the fix.

**Comment by BennyAlex** [comment]
it would be nice to have the complete URL variable (includes the api) and pass it

**Comment by pranayat** [comment]
@BennyAlex This has now been fixed.

**Comment by mccannt** [comment]
Resolved in Mock Service v1.17.1
Please feel free to reopen if this is still an issue.
