### ISSUE TITLE
not getting value of variables in test result

### ISSUE THREAD

**Issue by svarshney2311** [a85/POSTMan-Chrome-Extension#8776]
pm.test("Verify enabled field", function () {
    pm.response.to.have.status(200);
   pm.expect(jsonData.data[0].isEnabled, "isEnabled value is not correct for **{{$(jsonData.data[0].sku)}}"**).to.equal(pm.environment.get("isEnabled"));

            }); 

I am not getting value of  jsonData.data[0].sku in results if it fails. Could you please let me know what wrong am I doing?

**Comment by DannyDainton** [comment]
Hey @svarshney2311 

It looks like you have some syntax issues here:

```javascript
pm.test("Verify enabled field", function () {
	pm.response.to.have.status(200);
	pm.expect(jsonData.data[0].isEnabled, `isEnabled value is not correct for ${(jsonData.data[0].sku)}`).to.equal(pm.environment.get("isEnabled"));
});
```

These types of questions are perfect to raise as a new topic on Community forum.

https://community.postman.com/

**Comment by DannyDainton** [comment]
Closing this out as the question has been posted on the Community site.
