### ISSUE TITLE
Filter doesn't filter new requests

### ISSUE THREAD

**Issue by seromenho** [a85/POSTMan-Chrome-Extension#878]
Hi,
Toggle on Interceptor.
Go to history and filter for something.
The new intercepted requests are not being filtered.

**Comment by abhijitkane** [comment]
I'm not able to reproduce this. The requests that have been captured through the interceptor are filter-able like normal requests.
Can you follow the steps at http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/ and check if you see any errors in the console?

**Comment by seromenho** [comment]
Sorry, maybe i've not been clear on the first place. 
The requests that have been captured through the interceptor are filterable, but if after filter you kept intercepting other requests that ones simply show up and aren't being filtered.

**Comment by abhijitkane** [comment]
Got it. We'll fix this in a coming release.

Thanks for reporting this.
