### ISSUE TITLE
Top level scroll

### ISSUE THREAD

**Issue by siddy1705** [a85/POSTMan-Chrome-Extension#8780]
The top-level scroll was helpful as I like to view the response in a larger space. Now, every time I have to resize the request window for a larger space for the response window. Is there any way you can keep the top-level scroll. At least make it configurable from settings or something. Meanwhile, I would like to know how to downgrade the version where I will get the top-level scroll.

**Comment by coditva** [comment]
Hey, @siddy1705
If you would like a larger space for response section, you can switch to 2-pane layout where you can view the request and response panes side by side.

Tip: You can also, hide the sidebar for maximum screen space.

![Screen Recording 2020-07-15 at 12 59 48](https://user-images.githubusercontent.com/8445768/87516577-42225c00-c69b-11ea-8496-7ffdc7fe4899.gif)

Hope that helps. I'll close this issue for now. Do let me know if it still bothers you.

**Comment by sajadsholi** [comment]
@coditva 
what about the description of request ? when there is a lot of  descriptions , I should extend the description space to see all descriptions . why?

I prefer to downgrade the postman version to have not this ux
