### ISSUE TITLE
Disable Update Prompt

### ISSUE THREAD

**Issue by madhu-rapolu** [a85/POSTMan-Chrome-Extension#8785]
Even with "Automatically download major updates" Disabled in SETTINGS/Update, it still keeps prompting for update every now and then on MacOS. With no Admin rights, this is a real annoyance. Why cannot the choice of update to be left to the user completely? Looks like Postman is not mature enough to function without the continuous updates

**Comment by madhu-rapolu** [comment]
<img width="445" alt="Screen Shot 2020-07-15 at 8 53 57 AM" src="https://user-images.githubusercontent.com/56461259/87567246-eba42600-c678-11ea-8c00-e7fb8bee5bdc.png">

**Comment by madhu-rapolu** [comment]
Looks like Postman is not mature enough to function without the continuous updates

**Comment by arlemi** [comment]
Hi @madhu-rapolu, we consider major updates bumps from 6.x to 7.x for example. Anything within the same version (7 for example) will be considered a minor version.

We're already tracking this in #6999 so I'll close this one and you can follow updates there. 

Edit: We've just announced Postman for the Web in beta. This means no more updates on your side, using this would probably solve your problem, as it's still in beta please provide any feedback here: 
https://community.postman.com/t/announcing-postman-for-the-web-now-in-open-beta/14192
