### ISSUE TITLE
Export collections in predictable order (for source control diff)

### ISSUE THREAD

**Issue by matttrawicki** [a85/POSTMan-Chrome-Extension#879]
Portions of the collection export seem to have a non-deterministic order. This presents challenges for diff/merge with GitHub.

**Comment by abhijitkane** [comment]
The collections should always be exported in the order that is shown in the app. The folders in a collection are sorted in alphabetical order.
The requests within folders, and those directly in the collection are ordered as they appear in the UI.

Are you seeing a problem with the order of requests, or some other property?
Also, what version of the app are you using?

**Comment by matttrawicki** [comment]
I am unable to reproduce and apologize for the confusion. Version 1.0.6

**Comment by rohitjoshi** [comment]
@matttrawicki Problem  is when stored in the GitHub.  Given it reorders and generates uid based on the machines, git diff doesn't work.

**Comment by abhijitkane** [comment]
@rohitjoshi The latest version of the app strips out all IDs (except one) while exporting (you'll need to choose the v2 option). This should make using version control a lot easier.

**Comment by rohitjoshi** [comment]
@abhijitkane thanks.  We exported to V2 but our newman execution is failing. Is there a particular version or patch needed?

**Comment by matttrawicki** [comment]
Enjoying the v2 format! 🎆 Finally, some sanity when reviewing PRs. Thanks for finally servicing this request.

**Comment by vkaegis** [comment]
Hey guys! We've made an RFC to document our ideas on version control in Postman and it could be relevant to this discussion. Would love your thoughts and feedback on it:

https://community.getpostman.com/t/version-control/2715
