### ISSUE TITLE
The same request works in Postman as Google Chrome add-on but doesn't in desktop version

### ISSUE THREAD

**Issue by Genri1441** [a85/POSTMan-Chrome-Extension#8790]
**Describe the bug**
I have GET log request. This request returns me a file. I can download a file via Postman in Google Chrome, but can't in Postman for desktop for Windows. 

**To Reproduce**
1. Make the new request as here: https://natcheztrace.gitlab.io/pro-av-documentation/#mpa1000_logs_csv_get
2. Try to send

**Expected behavior**
The same behavior for both version

**Screenshots**
Desktop version 
![image](https://user-images.githubusercontent.com/45367554/87684555-0cf53700-c78b-11ea-8eb0-c7aa7c20d3e1.png)
Add-on
![image](https://user-images.githubusercontent.com/45367554/87684601-1aaabc80-c78b-11ea-848f-a7e8a89afd40.png)

**App information (please complete the following information):**
 - Google Chrome [83.0.4103.116]
 - Postman Version [PostmanRuntime/7.26.1]

**Comment by mohitranka** [comment]
@Genri1441 Can you try to make the request with the latest version of the application v7.28.0 ? 
If the issue persists, can you share 

* The expanded output in the Postman console?
* Output of `curl -sSL -D - <URL> -o /dev/null`

**Comment by Genri1441** [comment]
Hi @mohitranka .
1. I saw the same situation with 7.28.0
![image](https://user-images.githubusercontent.com/45367554/87781783-0671c880-c83a-11ea-9c43-8428c0ad3c20.png)
2. The console output is here
![image](https://user-images.githubusercontent.com/45367554/87781850-1ee1e300-c83a-11ea-8cf6-d0775a4138d3.png)
3. Curl output 
![image](https://user-images.githubusercontent.com/45367554/87781986-5b154380-c83a-11ea-9a35-1836a6fc0a5b.png)
Can you please review?

**Comment by Genri1441** [comment]
Hi @mohitranka . Any updates?

**Comment by Genri1441** [comment]
Hi @mohitranka , @xk0der @jeremys @abourget . Can you help me?

**Comment by Genri1441** [comment]
Hi @mohitranka . Any updates?

**Comment by Genri1441** [comment]
Hi @mohitranka . Any updates?

**Comment by Genri1441** [comment]
It fixed by our developers. Thank you for help. Please mark it as done

**Comment by DannyDainton** [comment]
Closing this issue as it looks like a resolution has been found. 🎉
