### ISSUE TITLE
Postman Team please put back the VERTICAL SCROLL!!!

### ISSUE THREAD

**Issue by sorin21** [a85/POSTMan-Chrome-Extension#8792]
First of all thank you very much that you put a lot of effort to develop this great app.

Bun now is very, very annoying to have 2 windows and to have a scroll in each one, to resize each one to see bettwer the content, to switch bettween panels view, to move one window in top of another window to see the content from this one, etc.

Please, please, please let the user to choose if he wants the vertical scroll area or if he wants to disable this. 

Believe me, with this new feature that you came: 2 windows side by syde or small windows on in top on each other, without verticall long scroll for whole area, I saw that the time to resolve tasks has increase with half. Now I have to toggle a lot bettwen those 2 views(because I don't like either one), or I have to resize windows to see better...

**PLEASE POSTMAN TEAM PUT BACK THE VERTICAL SCROLL ASAP**, even you put it like an option for who want it :).

**Comment by DannyDainton** [comment]
Hey @sorin21 

The scrolling has been improved in this version so that now you can control which pane you want to scroll at a time. You can also resize and collapse panes which you don't need for a decluttered UI.

You can also drop a mail at help@postman.com to get in a discussion around what is getting in the way. Since we understand that any change that we are accustomed to over the years may feel disruptive, our goal is to overall make the experience better in the new UI system. The more underlying feedback we get around the workflow, the better it will help us make the current system meet the remaining use cases.

Related: #5903

**Comment by sorin21** [comment]
Thank you for answer @DannyDainton , but why you didn't let the whole area vertical scroll?

I understand that now you can resize screens, but imagine now in almost every big company everyone works on laptops, and if you move a lot inside and outside company, the laptops are small, so you need for whole area a vertical scroll  to view better request and response areas. 

I work for a telecom international company and, please believe me, this new update, where you took the whole area vertical scroll, is a big issue for all of us, plus a lot of waste of time to toggle bettween views.

Is it not possible even like this to have the vertical whole area scroll?

**Comment by SeanAWilliams** [comment]
Same issue here. I cant make the postman screen any bigger, and the two panes are killing my productivity. I have to keep resizing each pane whenever I need to look at one or edit it. This sucks.

**Comment by DragonGirl09** [comment]
I was so surprised by your decision to not have the vertical scroll anymore. My PM asked me why I have a delay with the tasks and when I told him the problem, he said he didn't care. I'm in loved with postman, but I saw that someone recommended a different app. In this situation, I will try every app, that will do the job, because for any PM doesn't matter what tool we use, they care only about money.

**Comment by sorin21** [comment]
I found a solution, for who wants to still use postman: downgrade to a prev version.

[https://learning.postman.com/docs/administration/migrating-to-v7/#team-user-on-postman-v7](https://learning.postman.com/docs/administration/migrating-to-v7/#team-user-on-postman-v7)

and disable automatically download updates:
[https://community.postman.com/t/disable-postman-from-updating/4239/2](https://community.postman.com/t/disable-postman-from-updating/4239/2)

**Comment by shamasis** [comment]
Just a quick thought, have you tried the side-by-side two pane layout that gives extended vertical space to both request and response?

Let's work together to arrive at a pane based layout and still solve for the problems.

Would love to see some screenshots, gifs and screen resolution info along with rough idea of number of headers and request response lines to gauge the amount of screen real estate that's being consumed.

**Comment by sorin21** [comment]
Thank you shamasis for info, but I don't use postman from yesterday :). I tried everything. With what you r saying the top menu is hidden like will be on mobile. So to see better that menu, where you have header, body, etc, I have to switch a lot between one in top of each other, then side by side to see the response. The conclusion: waste of time. I will stay with the prev version.

**Comment by vkaegis** [comment]
Hey Sorin, thanks again for the feedback. Out of curiosity, what resolution do you use Postman at? Would you be able to tell us the size of the window?

**Comment by NoitaminAoki** [comment]
> I found a solution, for who wants to still use postman: downgrade to a prev version.
> 
> https://learning.postman.com/docs/administration/migrating-to-v7/#team-user-on-postman-v7
> 
> and disable automatically download updates:
> https://community.postman.com/t/disable-postman-from-updating/4239/2

Yeah, i follow your solution. But when i came back to version v7.27.0, the postman automatically download the latest minor updates, and Automatically install the updates when postman restarted. The disable button for automatically updates only for major not minor updates, there is issue but was closed. Therefore, when i open postman the next day, i must reinstall version 7.20.0. Please considere not all user like the same appearance. Thanks.

**Comment by DannyDainton** [comment]
Hey all, 

As there are many issues/threads talking about the same thing, in a bid to centralise the information and feedback, I'm going to close this issue out and ask everyone to follow the discussion here #8789.

We will be providing more updates on the scroll behaviour, on that GH thread.

Thanks.
