### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by Caaalabash** [a85/POSTMan-Chrome-Extension#8793]
**Describe the bug**

server got `unexpected end of JSON input` when process body.

BUT it works with `axios` and `curl`

**To Reproduce**

Golang Code

````golang
package main

import (
	"github.com/kataras/iris"
)

type Person struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

func MyHandler(ctx iris.Context) {
	var persons []Person
	err := ctx.ReadJSON(&persons)

	if err != nil {
		ctx.StatusCode(iris.StatusBadRequest)
		ctx.WriteString(err.Error())
		return
	}

	ctx.Writef("Received: %#+v\n", persons)
}

func main() {
	app := iris.New()
	app.Post("/", MyHandler)
	app.Run(iris.Addr(":8080"))
}
````

Use postman, copy from "code panel"

````
POST / HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/json

{"name":"1","age":1}------WebKitFormBoundary7MA4YWxkTrZu0gW--
````

Got error

````
unexpected end of JSON input
````

**App information (please complete the following information):**
 - Postman Version 7.28.0
 - OS: 10.15.6

**Comment by DannyDainton** [comment]
Hey @Caaalabash,

I'm not really sure what the issue is, in Postman, that you're facing here - Would be able to expand on your use case, please?

**Comment by Caaalabash** [comment]
please check this url:  http://111.229.115.45:6006/

NodeJS source code:

````javascript
require('http').createServer((req, res) => {
    let data = ''
    req.on('data', chunk => data += chunk)
    req.on('end', () => res.end(data))
}).listen(6006)
````

in postman, I got 400 error

![postman-test](https://static.calabash.top/blog-media/file/file-QQ20200718-150226@2x.png)

use axios

![axios-test](https://static.calabash.top/blog-media/file/file-QQ20200718-150500@2x.png)

use curl

![curl-test](https://static.calabash.top/blog-media/file/file-QQ20200718-150728@2x.png)

**Comment by Caaalabash** [comment]
> Hey @Caaalabash,
> 
> I'm not really sure what the issue is, in Postman, that you're facing here - Would be able to expand on your use case, please?

“unexpected end of JSON input” error in Golang case and "400 bad request"  error in Nodejs test case might be the same problem.

I have tried re-install the app, didn't work :(

**Comment by Caaalabash** [comment]
> > Hey @Caaalabash,
> > I'm not really sure what the issue is, in Postman, that you're facing here - Would be able to expand on your use case, please?
> 
> “unexpected end of JSON input” error in Golang case and "400 bad request" error in Nodejs test case might be the same problem.
> 
> I have tried re-install the app, didn't work :(

Sorry, this is my bad, I unchecked the 'Content-Length' attr in auto-generated headers

https://github.com/postmanlabs/postman-app-support/issues/8768#issuecomment-659128191

**Comment by autofi-bnapky** [comment]
@Caaalabash saved me some time today :)
