### ISSUE TITLE
Pipe ( | ) is not urlencoded with the next-generation URL processor

### ISSUE THREAD

**Issue by grunk** [a85/POSTMan-Chrome-Extension#8794]
**Describe the bug**
Sending a GET request with a parameter containing a pipe "|" lead to 400 Bad request because the pipe is not correctly url encoded

**To Reproduce**
1- Go to settings , enable next-generation URL processor
2- In request settings enable urlencoding
3- Send request like this : http://myapi/myendpoint?score=>|10
4- In console you'll see the following result : 

> GET http://myapi/myendpoint?score=%3E=|10

The ">" is correctly encoded but not the "|".

**Expected behavior**
The pipe should be urlencoded , the console should display : 

> GET http://myapi/myendpoint?score=%3E=%7C10

**App information (please complete the following information):**
 - App Type  : Native
 - Postman Version : 7.28.0
 - OS: Windows 10

**Additional context**
With the next-generation URL processor disabled the problem does not appears.
According to https://www.ietf.org/rfc/rfc3986.txt the pipe is not an allowed char , it should be encoded.

**Comment by codenirvana** [comment]
@grunk Thanks for reporting this.

As mentioned in https://github.com/postmanlabs/postman-app-support/issues/8775#issuecomment-659126717, the next-generation URL processor follows the [WHATWG (URL) standards](https://url.spec.whatwg.org/) which is widely adopted in the web browsers and modern programming languages. You can know more about this change [here](https://github.com/postmanlabs/postman-app-support/issues/8154).

So, `|` is no longer an unsafe character in the query. And if the requesting server requires `|` or other safe characters to be encoded, one has to encode it explicitly. Here's an example from the [Google Maps API](https://developers.google.com/maps/documentation/urls/url-encoding):
`"Spaces in a string are either encoded with %20 or replaced with the plus sign (+). If you use a pipe character (|) as a separator, be sure to encode the pipe as %7C. A comma in a string should be encoded as %2C."
`

**Example**: try sending this request `http://postman-echo.com/get?score=>|10 ` from a web browser, you will notice the `url` property in the response is `http://postman-echo.com/get?score=%3E|10"`.

Finally, I will not suggest you use Postman with the next-generation URL processor disabled as this setting is deprecated and will be removed in the future. This aligns with our vision of bringing the platform on the [web](https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta).
So, you can either manually encode the `|` to `%7C` or add the script mentioned in https://github.com/postmanlabs/postman-app-support/issues/8775#issuecomment-659126717 as a temporary workaround.
