### ISSUE TITLE
Saving Example - Response is not saving.

### ISSUE THREAD

**Issue by Gonzo102** [a85/POSTMan-Chrome-Extension#8797]
**Describe the bug**
After making a successful call, I click on Save Response/Save as Example.  The example comes up to be saved, but the response is blank.  I have been using this a lot and it just started happening after the last update.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the app to _two pane view_ and reduce the screen size to `1400px x 730px`
2. With a saved Request, Send the request and select `Save as Example` from the Response Body section of the builder.

**Expected behaviour**

Example response body to be shown for all screen resolutions  

**Screenshots**

![Issue](https://user-images.githubusercontent.com/11306038/87825279-d5e35c00-c844-11ea-9356-090b96e33272.png)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version: 7.28.0
 - OS: Win

**Additional context**

The problem occurs in multiple OS' but is only visible in the `examples` when using the `two-pane view`

**Comment by DannyDainton** [comment]
Hey @Gonzo102

Would you be able to also provide a screenshot or a recording of what you're seeing please.

Also, any context related information about what the response payload, JSON, XML, something else? An example of that would be great.

Finally, the specific version and what platform/OS you're using would be helpful to help debug this on our side.

**Comment by Gonzo102** [comment]
Windows 10 and Postman version 7.28.0

![image](https://user-images.githubusercontent.com/11306038/87825252-c82dd680-c844-11ea-880e-8af358270a49.png)

![image](https://user-images.githubusercontent.com/11306038/87825279-d5e35c00-c844-11ea-9356-090b96e33272.png)

**Comment by DannyDainton** [comment]
Thanks for getting those over to us, I'll take a look at this on my end.

Will update here if I require any additional information.

**Comment by DannyDainton** [comment]
I can see that some of the different options in the builder have gone in the collapsed state when the screen size is reduced or the different panes are given more space. 

Are you seeing the same when those panes are resized or the window is expanded?

Could you try the same scenario in the _single pane view_ and not in the _two pane view_?

**Comment by Gonzo102** [comment]
Do you mean like this?

![image](https://user-images.githubusercontent.com/11306038/87827819-a551f100-c849-11ea-92cd-c70d7171b9cf.png)

**Comment by Gonzo102** [comment]
So that is a work around.  if I toggle the 2 pane view so that the response is underneath, then it works correctly.  I don't work that way though, because I don't have enough screen real estate.  I work side by side.

**Comment by DannyDainton** [comment]
I think I just replicated the issue on my Mac, as well as the Win10 machine I have. I'm not sure of the screen size you're working in by I think this is showing the issue for you.

When I resize the window, the example response is shown and hide at different points - I will raise this further and ask the team to take a look at this.

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/17089546/87828736-79e4fb80-c875-11ea-8b74-ec9397bf7745.gif)


Thanks for raising this! 🏆

**Comment by Gonzo102** [comment]
Thanks.  Yes I am working on a laptop so I can't stretch my screen enough for it to show.  My window is maximized and it shows hidden.

**Comment by mccannt** [comment]
Resolved in v7.29.0
