### ISSUE TITLE
Postman for the web - Collection runner does not detect data file (csv/json)

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#8799]
**Describe the bug**
It seems that the collection runner has some issues importing an external JSON or CSV file.

To Reproduce

**Steps to reproduce the behavior:**

Open the collection runner and try importing an external file. 

![image](https://user-images.githubusercontent.com/1197635/87877672-e2e88280-c9df-11ea-9c1c-cabb9cd45c77.png)

The data preview won't work and the collection will only run once. 

**App information (please complete the following information):**

App Type: Postman for the web
OS: macOS

**Comment by DannyDainton** [comment]
Hey @vdespa

I believe that this has been fixed, would you be able to confirm on your end please?

**Comment by vdespa** [comment]
Looks good, Danny! Thanks.

**Comment by DannyDainton** [comment]
Awesome!! Going to close this one out now!! 

Thanks for reporting this! 🏆
