### ISSUE TITLE
oauth 2.0 on Google Drive and Instagram

### ISSUE THREAD

**Issue by mikerkeating** [a85/POSTMan-Chrome-Extension#880]
Hi @a85 

I'm trying to use OAuth 2.0 for requests on Instagram and Google Drive. I've not been able to do this.

- Questions
  - Is this possible right now?
  - Do you have an example setup for this on Google Drive and / or Instagram? 
  - Is any specific access or config needed to enable the redirect/ handover of the token?
  - I have read http://www.getpostman.com/docs/helpers and [enabling-chrome-developer-tools](http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/)
- Setup 
  - I'm using the Packaged App and Jetpacks
  * I've created apps on both Google API Console and Instagram - see below
  * I've setup OAuth 2.0 in Postman requests - see below; client id and secret match
  * Instagram docs are http://instagram.com/developer/authentication/
     * `auth`: `https://instagram.com/oauth/authorize`
     * `token`: `https://api.instagram.com/oauth/access_token`
- Steps
  * I'm able to start the flow by pressing `Get Access Token`
  * I login on Google/ Instagram, i.e. see their web page for login and this appears to succeed
  * but then see the message `Could not initiate OAuth 2 flow`
  * I've enabled developer tools but do not see any messages in the console

Screenshots

![postman-instagram](https://cloud.githubusercontent.com/assets/690583/5793182/54d50fb4-9f32-11e4-84f8-9ac9c7793584.png)

![postman-oauth2](https://cloud.githubusercontent.com/assets/690583/5793183/571545a0-9f32-11e4-96b7-c8e09812e28e.png)

Thanks, Mike

**Comment by abhijitkane** [comment]
The chrome API we're using doesn't give us any information about what went wrong. In the next release, we'll show the URL that's used to initiate the OAuth2.0 flow, so you can use your browser to mimic the flow and see what goes wrong.

As an example, I tried it with the Google API, and the page said "invalid scope". Such errors are impossible to debug from within the app.

**Comment by mikerkeating** [comment]
OK; thanks for quick reply.

**Comment by larismendi** [comment]
Thanks.
