### ISSUE TITLE
Auto Generated Headers

### ISSUE THREAD

**Issue by saradavani-koppisetty** [a85/POSTMan-Chrome-Extension#8800]
**Describe the bug**
Not able to remove the temporary headers, while importing curl 5 headers will get added automatically because these headers my request is getting failed

**Screenshots**
https://snipboard.io/MnvwfZ.jpg

**App information (please complete the following information):**
 - App Type: web application
 - Postman Version: Postman v7.28.0
 - OS: Ubuntu

**Comment by saswatds** [comment]
Hi @saradavani-koppisetty, The number shown alongside is not indicative of what headers are sent but how many headers are defined (enabled + disabled).
I can see you have disabled `Host` and `User-Agent` headers. I have checked and can confirm that they are not actually getting sent. You can uncheck all the checkboxes and no header will be sent with your request.

If your server is NodeJS based, then from previous experience I have seen the server throw a `400 Bad Request` if the `Host` header is not set. You can try enabling the `Host` header to debug.

We no longer have the temporary header logic and have modified the system to have configurable auto-generated headers and allow the user to disable every such header using the checkbox.

**Comment by saswatds** [comment]
Hi @saradavani-koppisetty, We haven't heard from you for a while, and we are not able to reproduce this issue.  Closing this issue for now. Feel free to reopen if the issue persists for you.

**Comment by thedude4ever** [comment]
hello, when I uncheck the "Host" auto-generated header, it keeps on being check again. This happens only when I use a variable for endpoint, could you please give me some help? thanks a lot

![image](https://user-images.githubusercontent.com/83371417/159493269-7bdf9ae6-19c4-4db5-a818-ebe98f91e664.png)
![image](https://user-images.githubusercontent.com/83371417/159493664-db638b03-998c-45ee-92f2-49a5a880942f.png)
![image](https://user-images.githubusercontent.com/83371417/159493871-4ef151fb-b468-4faa-9481-5cef5b710474.png)
