### ISSUE TITLE
Collection Pre-Script running prior to Each Request

### ISSUE THREAD

**Issue by Ben1nBlack** [a85/POSTMan-Chrome-Extension#8802]
**Describe the bug**
I created a code in the Collection Pre-Sctipt section, thinking that this would run once to init values, it is running after each request in the collection.

**To Reproduce**
1. create collection
2. add some request
3. edit the collection pre-script and add console.log("collection pre-script called")
4.run collection in collection runnner

**Expected behavior**
the console.log shows once at run of collection

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version_  7.28.0 (7.28.0)
 - OS: [e.g. macOS Mojave 10.14.6]

**Additional context**
is there any way to talk to someone in support over phone?

**Comment by DannyDainton** [comment]
Hey @Ben1nBlack 

This is the intended behaviour of the Pre-request Script, it would run before _each_ request in the Collection. 

![Screenshot 2020-07-20 at 15 05 22](https://user-images.githubusercontent.com/17089546/87946900-88602c80-ca9a-11ea-9a23-dfafa82e03ca.png)

More information about these can be found on our learning center:

https://learning.postman.com/docs/writing-scripts/pre-request-scripts/

**Comment by Ben1nBlack** [comment]
Then there is no way to init variable thru scripting, 

collection script should be run once, then all other tests.

**Comment by DannyDainton** [comment]
If you wanted to start a new thread on the [community forum](https://community.postman.com/) with an example of your use case, I'm sure we will be able to walk through what you're doing and a potential solution for to achieve this.
