### ISSUE TITLE
Add a Collection level Pre-Script that only runs once

### ISSUE THREAD

**Issue by Ben1nBlack** [a85/POSTMan-Chrome-Extension#8804]
[Test Runner.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/4948818/Test.Runner.postman_collection.json.zip)

**Describe the solution you'd like**

The flow should be

    Collection Pre-Script (for initialization of value prior to collection run)
    Request Pre-Script
    Request Test (post script)
    … Loops
    finally Collection Test (post script)

The current setup makes no sense, yeah ok you can have some of the script run for each request, BUT! this makes it impossible to Initalize a set a variablse.

My Case.

I place a JSON Array of object in the Collection Pre-Script that defines the variable (scope) in each Request Script I read the JSON and loop thru all the calls for this request defined in the Collection.

With the Collection Pre-Script running each time you have no way programmatically to assign varialbles as pre-sets. The calling of collection pre-scripts, destroys looping

**Describe alternatives you've considered**
The options, to Toggle if the Collection Script is run once or for all

**Additional context**

**Comment by PPatel0212** [comment]
Would be useful as IM facing a similar issue

**Comment by giridharvc7** [comment]
We have a collection level Pre-request script, please let us know if this works for you. 
Here is more documentation on this - https://learning.postman.com/docs/writing-scripts/intro-to-scripts/
![Screenshot 2021-04-14 at 12 16 42 PM](https://user-images.githubusercontent.com/1040583/114665958-4909f800-9d1b-11eb-9313-57a0663d648a.png)

**Comment by smkOld** [comment]
Is there any built-in way to set the script to only run once though?

**Comment by spatialy** [comment]
Hi, this will be util

any workaround for running only once and setting variables to run on each iteration with the same values?

**Comment by malvikach** [comment]
Hi @spatialy @sequoiaKozak thanks for writing to us.

Postman has the ability to run a logic exactly once for a collection run. To do this you can follow the steps below:

You can define a request inside the collection that runs first every time you run the collection. This request will be executed only once when you run the entire collection. You can add the logic that you would like to run exactly once and you can even set variables with values on the pre-request or test section on this request. See the example below:

![image](https://user-images.githubusercontent.com/89449769/141733757-0048f86d-e8a4-478d-949b-1d8a45107dd7.png)


Please let me know if this helps.

**Comment by sunilvp** [comment]
This is a good example thanks. 
But there is still one case which might not work, correct if i am wrong. But this might be different use case as well. 
If we are using collection with multiple iteration and the dummy request will get executed for every iteration. 
Is there a way to have pre script for every collection run even though multiple iterations are selected. 

Let me know if any other alternatives exists. 

Thank You
