### ISSUE TITLE
A cookie with the secure attribute as true being reported as false

### ISSUE THREAD

**Issue by JoeyEamigh** [a85/POSTMan-Chrome-Extension#8805]
**Describe the bug**
When I post or get to my server which is setting a secure cookie (as verified by FireFox, Edge, and my code), the secure flag will say false in Postman.

**To Reproduce**
1. Make a request to a server with a secure cookie
2. Tab over to the cookies page. It says false.

**Expected behavior**
Secure should be true

**Screenshots**
###### Postman:
![image](https://user-images.githubusercontent.com/55670930/87977212-5ea80500-ca9c-11ea-95f4-dc8cd86df540.png)
###### My code:
![image](https://user-images.githubusercontent.com/55670930/87977228-6798d680-ca9c-11ea-96bc-dad998a4d3ef.png)
###### Microsoft Edge Dev Tools:
![image](https://user-images.githubusercontent.com/55670930/87977299-872fff00-ca9c-11ea-8edf-0f1dbba80f57.png)

**App information (please complete the following information):**
 - App Type: Express App
 - Postman Version: 7.28.0
 - OS: Windows 10

**Comment by codenirvana** [comment]
@JoeyEamigh I am not able to reproduce this issue locally and haven't seen other users facing the same.
![Screenshot 2020-07-21 at 10 33 23 AM](https://user-images.githubusercontent.com/4865836/88014918-a894f780-cb3d-11ea-8a5c-fc49e4728155.png)

Can you share a scaled-down collection or an endpoint that we can use to reproduce this issue?
If it's an internal endpoint, can you just share the `Set-Cookie` response header?

**Comment by JoeyEamigh** [comment]
A reinstall and a reboot fixed it for me. This bug only happened when I placed a insecure cookie with the same name as the secure one then cleared the cookie jar and set the secure one. If no one else is reporting it then don't waste your time on it. Might have been a fluke.

**Comment by codenirvana** [comment]
@JoeyEamigh Thanks for the confirmation, glad it worked out for you.
