### ISSUE TITLE
When minimized, the application window changes its position when maximized

### ISSUE THREAD

**Issue by karolh95** [a85/POSTMan-Chrome-Extension#8809]
**Describe the bug**

When minimized, the application window changes its position after maximized

**To Reproduce**

1. Open Postman
2. Open some other window
3. Snap Postman window to the left edge of your screen
4. Minimize Postman's window
5. Maximize Postman's window
6. The Postman's window is slightly shifted to the right

**Expected behavior**

The postman window should appear exactly on the left edge of the screen

**Screenshots**

Windows before:

![https://ibb.co/QPjQBwR](https://i.ibb.co/n78m2Jv/ss1.png)

... and after reproduce the behavior:

![https://ibb.co/WfL9pS5](https://i.ibb.co/Zx0s1yX/ss2.jpg)

**App information (please complete the following information):**

- Postman for Windows
- Version 7.28.0
 - win32 10.0.18363 / x64
 - OS: [Windows 10 Pro, v1909]

**Additional context**

When snapped to the right edge of the screen, the Postman window is properly maximized.
The problem only occurs with the Postman window.

**Comment by jviotti** [comment]
Thanks a lot for reporting! I'll close this one so we can focus the discussion on https://github.com/postmanlabs/postman-app-support/issues/9598
