### ISSUE TITLE
Error parsing null response

### ISSUE THREAD

**Issue by bcroq** [a85/POSTMan-Chrome-Extension#881]
null does not seem to be a valid JSON value:

![image](https://cloud.githubusercontent.com/assets/130780/5800565/7501173e-9fe0-11e4-86d9-4c10c449cae4.png)

![image](https://cloud.githubusercontent.com/assets/130780/5800563/695dba0e-9fe0-11e4-9315-b1a43aa58c53.png)

**Comment by abhijitkane** [comment]
The JSON view will only show a valid JSON object. 
Strings that cannot be parsed as JSON will not be shown.

**Comment by bcroq** [comment]
null is a valid JSON value but it is considered invalid by POSTMan's parser.

This issue might come from https://github.com/zaach/jsonlint/issues/42
