### ISSUE TITLE
Select request in the Sidebar in the COLLAPSED tree from (by switching) a tab

### ISSUE THREAD

**Issue by aleqcz** [a85/POSTMan-Chrome-Extension#8810]
Hi,
would you please consider adding a function to locate/select the request (opened in a tab) in the collapsed Collection in the sidebar?  It works nicely if the tree is expanded, but not, if it is collapsed. Can I trigger some action and let it find it in the tree and expand the path to it, keep it expanded even after clearing the search? 
Just like in IntelliJ IDEA when you click the “target” icon for instance… I miss this very much.

Thanks a lot,
A.

**Comment by arlemi** [comment]
Duplicate of #8486, we'll give any update there. 🙂
