### ISSUE TITLE
Header prefix default placeholder is confusing

### ISSUE THREAD

**Issue by ajbrun** [a85/POSTMan-Chrome-Extension#8811]
We've just run into an issue where we found the default placeholder of "bearer" in the header prefix field to be a little confusing. Since it displays "bearer" rather than "Enter hearer prefix", it's assumed that this is the default value rather than just a placeholder.

This issue is that the screenshot below will not result in a header prefix being sent, but can be overlooked to assume it should:
![image](https://user-images.githubusercontent.com/16187357/88168425-4fe35e80-cc12-11ea-911d-86dbca918555.png)

Replication:
* Using OAuth2, get an access token
* Delete all contents from the header prefix box, it should show "Bearer" as a placeholder
* Send an authenticated request

Actual:
* There is no "bearer" as part of the authorization header
* 401 unauthorized
* Since the placeholder appears to be a default value, this is confusing

When it's found, the reason is clear, so I wouldn't necessarily say this is a bug...

Expected - one of:
* Change placeholder to "Enter header prefix"
* Have a warning appear if nothing is entered. It might also be worth having a similar warning if there's no space entered after the header prefix? "Bearer" will 401 but "Bearer " won't.
* Remove the placeholder totally
* Send a default value of "Bearer " if there's nothing entered. I'm aware there may be occassion to require that nothing is sent as a prefix, so this might not be a possibility.

**Comment by codenirvana** [comment]
@ajbrun Thanks for the feedback and this is something which we are already tracking internally and we'll try to improve this as soon as possible.

**Comment by mccannt** [comment]
This issue is now resolved in v7.32 of the application.
Closing this issue. If you are still experiencing this issue in the latest version, please let us know.
