### ISSUE TITLE
OpenAPI Responses with nested $ref properties are not interpreted correctly

### ISSUE THREAD

**Issue by Asafkbalink** [a85/POSTMan-Chrome-Extension#8812]
**Describe the bug**
When importing a valid OpenAPI specification file that has nested schema references, postman interprets the nested object as "<object>" instead of displaying the object itself.

**To Reproduce**
1. Take the following yaml:
```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: 'Sample API'
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    JSendSuccess:
      type: object
      properties:
        status:
          type: string
          readOnly: true
        data:
          type: object
          readOnly: true
      required:
        - status
        - data
    JSendError:
      type: object
      properties:
        status:
          type: string
          readOnly: true
        message:
          type: string
          readOnly: true
        code:
          type: number
          readOnly: true
        data:
          type: object
          readOnly: true
      required:
        - status
        - message
        - code
        - data
    IPluginResponse:
      type: object
      properties:
        source:
          type: string
          readOnly: true
        actionId:
          type: string
          readOnly: true
        result:
          type: object
          readOnly: true
      required:
        - source
        - actionId
        - result
    IPluginErrorResponse:
      type: object
      properties:
        err:
          type: string
          readOnly: true
        data:
          type: object
          readOnly: true
      required:
        - err
        - data
    IClientReduced:
      type: object
      properties:
        clientId:
          type: string
        clientName:
          type: string
      required:
        - clientId
        - clientName
    IClients:
      type: object
      properties:
        clients:
          type: array
          items:
            $ref: '#/components/schemas/IClientReduced'
      required:
        - clients
paths:
  /v1/clients:
    get:
      operationId: ClientsController_findAll
      summary: Get all clients.
      responses:
        '200':
          description: 2XX Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/JSendSuccess'
                  - properties:
                      data:
                        allOf:
                          - $ref: '#/components/schemas/IPluginResponse'
                          - properties:
                              result:
                                $ref: '#/components/schemas/IClients'
        '400':
          description: 4XX Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/JSendError'
                  - properties:
                      data:
                        allOf:
                          - $ref: '#/components/schemas/IPluginResponse'
                          - properties:
                              result:
                                $ref: '#/components/schemas/IPluginErrorResponse'
        '500':
          description: 5XX Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/JSendError'
      tags:
        - Clients
      security:
        - bearer: []
```
2. Paste it to Postman's API "define" section under a new API
3. Generate a collection by this specification
4. Go to the `GET /clients` request
5. Click on "Examples" and choose "2XX Response"
6. See the error:
```json
{
 "status": "<string>",
 "data": "<object>"
}
```

**Expected behavior**
I expect Postman to interpret the file correctly, as can be seen at: https://editor.swagger.io/
```json
{
  "status": "string",
  "data": {
    "source": "string",
    "actionId": "string",
    "result": {
      "clients": [
        {
          "clientId": "string",
          "clientName": "string"
        }
      ]
    }
  }
}
```

**Screenshots**
You can paste the given yaml to https://editor.swagger.io/ to see how all of the responses are interpreted.
 
**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.28.0
 - OS: Ubuntu 18.04

**Additional context**
Probably will have a question asking why am I creating a schema with 3 nested schemas inside of it, instead of creating one schema that populates all the fields. The answer is that I'm using a javascript library to create this swagger automatically with generic interfaces - JSend success for example is a format for all of my responses. Instead of having to create hundreds of interfaces, I'm able to pass a lower-level interface to a generic one that way.

**Comment by VShingala** [comment]
@Asafkbalink Thanks for reporting issue.

Currently we resolve all elements in `allOf` by their order of occurrence and each property is treated independently, this means for following schema:

```
schema:
  allOf:
    - $ref: '#/components/schemas/JSendSuccess'
    - properties:
      data:
        allOf:
          - $ref: '#/components/schemas/IPluginResponse'
          - properties:
              result:
                $ref: '#/components/schemas/IClients'
```

`data` property in `JSendSuccess` component is resolved first and as it doesn't contain any properties it's treated as empty object. Now when resolving further when `data` is found inside properties, as we already have `data` property we don't resolve this `data` property.

For now, You can change order of schema in `allOf` array. I was able to produce intended result mentioned by you using following schema (Note that only order is different)

```
schema:
  allOf:
    - properties:
        data:
          allOf:
            - properties:
                result:
                  $ref: '#/components/schemas/IClients'
            - $ref: '#/components/schemas/IPluginResponse'
    - $ref: '#/components/schemas/JSendSuccess'
```

We will look more into how we can correctly produce result irrespective of order in which they are mentioned in schema.

**Comment by Asafkbalink** [comment]
@VShingala thank you. This temporary solution works. Please just notice the key "result" and it's nested properties needs to be indented once more in your examples :)

EDIT:
example was fixed

**Comment by VShingala** [comment]
@Asafkbalink Thanks for pointing it out. Have updated it. 👍

**Comment by Asafkbalink** [comment]
@VShingala @DannyDainton 
Please notice that since `IPluginResponse` schema `result` property is defined to be an object, 
OpenAPI itself won't allow to switch the order of the keys.

This "properties first" approach won't be interpreted by OpenAPI -
```yaml
schema:
  allOf:
    - properties:
        data:
          allOf:
            - properties:
                result:
                  type: array
                  items:
                    $ref: '#/components/schemas/ICountries'
            - $ref: '#/components/schemas/IPluginResponse'
    - $ref: '#/components/schemas/JSendSuccess'
```
![image](https://user-images.githubusercontent.com/59600866/88263515-d2cbee00-ccd2-11ea-942d-c541c2fe9c30.png)


While "reference first" does get interpreted -
```yaml
schema:
  allOf:
    - properties:
        data:
          allOf:
            - $ref: '#/components/schemas/IPluginResponse'
            - properties:
                result:
                  type: array
                  items:
                    $ref: '#/components/schemas/ICountries'
    - $ref: '#/components/schemas/JSendSuccess'
```
![image](https://user-images.githubusercontent.com/59600866/88263797-4837be80-ccd3-11ea-8836-95b9ce9d922b.png)


That means this isn't the expected behavior and therefore should be treated as a bug, and not as a feature.

**Comment by VShingala** [comment]
@Asafkbalink Yes, the order shouldn't affect the converted value. Thus should be treated as bug.

**Comment by VShingala** [comment]
@Asafkbalink This issue should be resolved with the latest Postman App v7.35.

**Comment by arlemi** [comment]
We had to delay the release of the app, I'm reopening this issue for now and will close it again once 7.35 is widely available. 🙂

**Comment by kavish-chathuranga** [comment]
> @VShingala @DannyDainton Please notice that since `IPluginResponse` schema `result` property is defined to be an object, OpenAPI itself won't allow to switch the order of the keys.
> 
> This "properties first" approach won't be interpreted by OpenAPI -
> 
> ```yaml
> schema:
>   allOf:
>     - properties:
>         data:
>           allOf:
>             - properties:
>                 result:
>                   type: array
>                   items:
>                     $ref: '#/components/schemas/ICountries'
>             - $ref: '#/components/schemas/IPluginResponse'
>     - $ref: '#/components/schemas/JSendSuccess'
> ```
> 
> ![image](https://user-images.githubusercontent.com/59600866/88263515-d2cbee00-ccd2-11ea-942d-c541c2fe9c30.png)
> 
> While "reference first" does get interpreted -
> 
> ```yaml
> schema:
>   allOf:
>     - properties:
>         data:
>           allOf:
>             - $ref: '#/components/schemas/IPluginResponse'
>             - properties:
>                 result:
>                   type: array
>                   items:
>                     $ref: '#/components/schemas/ICountries'
>     - $ref: '#/components/schemas/JSendSuccess'
> ```
> 
> ![image](https://user-images.githubusercontent.com/59600866/88263797-4837be80-ccd3-11ea-8836-95b9ce9d922b.png)
> 
> That means this isn't the expected behavior and therefore should be treated as a bug, and not as a feature.

**Comment by kavish-chathuranga** [comment]
> @VShingala @DannyDainton Please notice that since `IPluginResponse` schema `result` property is defined to be an object, OpenAPI itself won't allow to switch the order of the keys.
> 
> This "properties first" approach won't be interpreted by OpenAPI -
> 
> ```yaml
> schema:
>   allOf:
>     - properties:
>         data:
>           allOf:
>             - properties:
>                 result:
>                   type: array
>                   items:
>                     $ref: '#/components/schemas/ICountries'
>             - $ref: '#/components/schemas/IPluginResponse'
>     - $ref: '#/components/schemas/JSendSuccess'
> ```
> 
> ![image](https://user-images.githubusercontent.com/59600866/88263515-d2cbee00-ccd2-11ea-942d-c541c2fe9c30.png)
> 
> While "reference first" does get interpreted -
> 
> ```yaml
> schema:
>   allOf:
>     - properties:
>         data:
>           allOf:
>             - $ref: '#/components/schemas/IPluginResponse'
>             - properties:
>                 result:
>                   type: array
>                   items:
>                     $ref: '#/components/schemas/ICountries'
>     - $ref: '#/components/schemas/JSendSuccess'
> ```
> 
> ![image](https://user-images.githubusercontent.com/59600866/88263797-4837be80-ccd3-11ea-8836-95b9ce9d922b.png)
> 
> That means this isn't the expected behavior and therefore should be treated as a bug, and not as a feature.

Were you able to sort this out? This isn't working for me
