### ISSUE TITLE
POST request with request param value as json string is not working from v7.28.0

### ISSUE THREAD

**Issue by av9saxena** [a85/POSTMan-Chrome-Extension#8813]
I had exposed a POST request which accepts HttpSerlvetRequest as request body. I used to hit it using following URL :

**{{url}}/api/ext/payment/stargate/notify/response?data={"sessionId":"3a16b901-01ac-4881-8d22-aafdsfldfdkjfldlf6e449c1bae","rrn":"PGSM2UF2sjfkjdshfkj4XB","amount":"100.00","ordernumber":"40fdljfd70sfddf7","transactionId":"0000","payResult":"Ofkdjlkfjl","responseCode":"100","avsRawResp":"fdjkfd","cvvRawData":"fdof","maskedCardNumber":"fdjhfldlk","token":"fdjhfkjdhk","expirydate":"fdhfk","zipcode":"fdjfhk","cardtype":"fdkljflkd","authorizationCode":"dfjdlk"}**

As visible from request I have one request param as "data" which is actually a JSON string. I was able to hit my api successfully till v7.27.1 but after recent upgrade to v7.28.0 I am getting 400 bad request every time.

If I am removing "data" part from URL then I am able to hit but I need to hit with the data.

**{{url}}/api/ext/payment/stargate/notify/response**

Also, removal of main scroll sidebar is causing many operational delays while testing as for viewing request and responses I need to resize sections every time. Please add the main scroll sidebar again.

**Comment by codenirvana** [comment]
@av9saxena You might be facing the encoding issue similar to https://github.com/postmanlabs/postman-app-support/issues/8808.
Please refer https://github.com/postmanlabs/postman-app-support/issues/8808#issuecomment-662212275 for more details.

Also, we are actively looking into the scroll UX improvements and you can follow https://github.com/postmanlabs/postman-app-support/issues/8792 for updates.
