### ISSUE TITLE
Create reusable testing scenarios from a collections. 

### ISSUE THREAD

**Issue by jwbanning** [a85/POSTMan-Chrome-Extension#8816]
**Is your feature request related to a problem? Please describe.**
Having an authoritative collection of requests limits my use case testing scenarios.  To accomplish all my testing I have to write complex scripts to check flags and change the .setNextRequest. This leads to a many messy scripts or many duplicate collections.

**Describe the solution you'd like**
The possibility to toggling on/off and reorder folders and requests in the collection runner and saving that as a "scenario". I would then like to select a scenario associated with a collection and just run that. This automation should also be available in Newman. 

**Describe alternatives you've considered**
Forking the authoritative collection and removing those folder and requests not needed. This leads to many collections. 

**Additional context**

**Comment by malvikach** [comment]
Tracking this on Duplicate ticket: [8433](https://github.com/postmanlabs/postman-app-support/issues/8433)

**Comment by malvikach** [comment]
@jwbanning I have shared some updates regarding this [here](https://github.com/postmanlabs/postman-app-support/issues/8433)
