### ISSUE TITLE
Variable pop up window is shown behind the Collection Edit modal

### ISSUE THREAD

**Issue by InnaMakhova** [a85/POSTMan-Chrome-Extension#8819]
||Project:|Postman for Windows|
||Build:|Version 7.29.0|
||Type:|win32 10.0.18362 / x64|

**Describe the bug**
Pop_up windows which should shown to a user information about his LogIn and Pass is overlaps by Collection Windows

**To Reproduce**
1. Open the Postman
2. Click on "Create Collection"
3. Create one
4. In the left panel (with tabs History/Collection/etc.) click on symbols "..." for opening drom down list
5. Click on "Edit" -> "Variables"
6. Add your "Variables" data
7. Click "Edit" -> "Authorization" -> And choose here "Basic Auth"
8. Try to enter your data via {{Variables data}} (For example {{TWILIO_ACCOUNT_SID}})
9. Pay attention on Pop_up windows

**Actual result:**
Pop_up windows is shows behind Collection Windows and in this way user can't choose his data

**Expected behavior**
Pop_up windows is shows before Collection Windows because user want to choose his data

**Screenshots**
![postman](https://user-images.githubusercontent.com/68690725/88285671-d0c45800-ccef-11ea-88ce-13c61bab8204.png)

**Comment by DannyDainton** [comment]
Hey @InnaMakhova 

Thank you for flagging this issue ❤️  - We're already tracking this internally and working towards a fix.

**Comment by timbochamp** [comment]
Hi @InnaMakhova, this should now be resolved with our latest Postman version 8 app release, as well as on Postman for Web! I'm going to close out this issue, but please feel free to reopen if you're still encountering this issue after updating.
