### ISSUE TITLE
postman launch problem 

### ISSUE THREAD

**Issue by jack-iml** [a85/POSTMan-Chrome-Extension#8823]
i have problem with launching postman when i open postman then display like that nothing to show any option

![image](https://user-images.githubusercontent.com/59472792/88369561-eac47000-cdad-11ea-930c-1749e1d3211f.png)

**Comment by gignonje** [comment]
Got same issue on Ubuntu (Snap install)

**Comment by twitharshil** [comment]
Hey, @jack-iml Thanks for reporting this issue. Please mention the Postman version and platform details on which your are seeing this issue. Also, can you send logs to us at **help@postman.com** so that we can take a deeper look into this?  
You can find logs for Windows at: `C:\Users\<username>\AppData\Roaming\Postman\logs`

**Comment by twitharshil** [comment]
Hey @gignonje can you write to us at **help@postman.com** with logs attached so that we can understand the issue much better? 
You can find logs for Postman app installed via Snap at : `/home/<username>/snap/postman/current/.config/Postman/logs`

**Comment by Raj-postman** [comment]
@jack-iml @gignonje - Just checking to see if the issue persists? If yes, could you please [submit a ticket to Support](http://support.postman.com/) and we will further take a look at it?

**Comment by NicolasDepoilly** [comment]
my postman is totally frozen and not working, which is a bit painful.

lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:    18.04
Codename:    bionic

Got as well a snap install

I have the same screen as above, and am not able to use postman anymore.
I sent a mail with my logs, hope this will help.
Thanks

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5980
