### ISSUE TITLE
Crash Error when Posting

### ISSUE THREAD

**Issue by Antheabenting** [a85/POSTMan-Chrome-Extension#8824]
Hi 
I am getting this error when doing a POST request.  Although the status is 200 OK.
{
    "result": "ERROR",
    "message": "There was an error, please contact support, please quote this crash ID: 5f1aaff09dea33d9f636fd61"
}

Please assist.

**Comment by mccannt** [comment]
@Antheabenting This looks like it is an issue with your API itself and not a Postman issue. 
Can you please confirm that this is the case and let us know?

**Comment by Antheabenting** [comment]
Hi, this was the case I have discovered.  Thanks for pointing it out though.
