### ISSUE TITLE
OAuth 2.0 certificate issue

### ISSUE THREAD

**Issue by davinderxav** [a85/POSTMan-Chrome-Extension#8825]
**Describe the bug**
While performing OAuth 2.0 postman is not using/attaching client certificates with the request. There all the attempts to perform OAuth 2.0 to the server which require client certificate and key are failing. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the setting >certificate> add host, certificate and key
2. Go to OAuth 2.0 request token
3. SignIn
4. The request fails as not client certificate provided by the postman

**Expected behaviour**
While making OAuth 2.o request postman should make the request with client certificates 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.29.0]
 - OS: [Ubuntu Bionic]

**Comment by dramkler** [comment]
> **Describe the bug**
> While performing OAuth 2.0 postman is not using/attaching client certificates with the request. There all the attempts to perform OAuth 2.0 to the server which require client certificate and key are failing.
> 
> **To Reproduce**
> Steps to reproduce the behaviour:
> 
> 1. Go to the setting >certificate> add host, certificate and key
> 2. Go to OAuth 2.0 request token
> 3. SignIn
> 4. The request fails as not client certificate provided by the postman
> 
> **Expected behaviour**
> While making OAuth 2.o request postman should make the request with client certificates
> 
> **App information (please complete the following information):**
> 
> * App Type [Native App]
> * Postman Version [7.29.0]
> * OS: [Ubuntu Bionic]

I confirm, same issue with Mac OS Mojave:
* App Type [Native App]
* Postman Version [7.29.0/1]
* OS: [macOs Mojave]

![Schermata 2020-07-25 alle 01 08 21](https://user-images.githubusercontent.com/9319944/88442054-5856b780-ce13-11ea-817a-06720893e97f.jpg)


Trick:
When I try to simulate the OAuth2 with a new Request for obtaining the bearer token, everything function ok.
 
Thank’s

**Comment by vikiCoder** [comment]
Hi, we were able to reproduce it and we are working on the fix. I'll update here once it is fixed.
