### ISSUE TITLE
Remove internet explorer (IE) as the user agent for calls from Postman

### ISSUE THREAD

**Issue by pipeaesac** [a85/POSTMan-Chrome-Extension#8826]
**Is your feature request related to a problem? Please describe.**
On the desktop version of Postman for Windows, calls to the Postman backend (e.g. the update site) uses internet explorer as user agent. In many organizations, internet explorer is blocked or will become blocked sooner or later by application firewalls, because it's no longer the Windows standard browser. Updating Postman and signing into Postman account is then no longer possible.

**Describe the solution you'd like**
Replace internet explorer as user agent and use Edge for example.

**Describe alternatives you've considered**
Unfortunately, I can't see alternatives for this.

**Additional context**
None.

**Comment by vmburdParl** [comment]
Have just encountered this issue as I have been using Postman for testing cPanel/WHM API calls. Unfortunately, as from release 88, cPanel has removed support for Internet Explorer 11.  This means I can't use Postman anymore for testing/development.

Following url refers  blog.cpanel.com/internet-explorer-11-end-of-support-in-cpanel-version-88/

**Comment by postman-kenji** [comment]
Closing due to age of request. Please reopen this if this continues to be an issues. Thanks!

**Comment by giwleb** [comment]
I know this is closed, but I'm curious what people's workarounds are for this are. Our systems/internet protection now block "older browsers" and Postman Desktop seems to be using older browsers, at least from a useragent standpoint.
