### ISSUE TITLE
Additional Dynamic Variables

### ISSUE THREAD

**Issue by chluther** [a85/POSTMan-Chrome-Extension#8828]
Love mock server and the way it allows us to decouple front-end and back-end development schedules.  The integrations I work with require data which meets specific formats.  Within Postman Mocks I would like more control of the format of dynamic variables, to allow me to mock up just about any specific data string.  The Dynamic Variables might look like:

$randomNumber-1 = string of 1 number
$randomNumber-2 = string of 2 numerics
$randomNumber-9 = string of 9 numerics
$randomChar-3 = string of 3 lowercase and uppercase ASCII characters
$randomCharUpper-4 = string of 3 uppercase ASCII characters
$randomCharLower-3 = string of 3 lowercase ASCII characters
$randomUTF8-2 =  string of 2 international characters

##Example Usage:
{{$randomCharUpper-3}}-{{$randomNumber-4}}-{{$randomNumber-2}} => ATF-1943-81

**Comment by sony-mathew** [comment]
Hey @chluther , thank you for the suggestion. Our team has been actively working on improving the feature over time, and we've added new capabilities to make it even more powerful and user-friendly. 


You can read more about creating dynamic responses with mock severs here: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/creating-dynamic-responses/

More specific details on how to use use dynamic variables to return randomly generated data is documented here: https://learning.postman.com/docs/tests-and-scripts/write-scripts/variables-list/


I believe that our documentation and the new capabilities should help address your concerns and provide a better experience for you. If there's anything else we can do to assist you, please let us know. If you have any further questions or concerns, please feel to reopen this ticket.
