### ISSUE TITLE
POST request-token

### ISSUE THREAD

**Issue by mar20** [a85/POSTMan-Chrome-Extension#883]
When oauth-token is empty Verification of signature is failed, but when option "Add empty params to signature" then request-token is response correctly.

With disabled option "Add empty params to signature" I must set oauth_token to null and then my response is correct.

**Comment by abhijitkane** [comment]
This is due to different implementations of OAuth by different providers. Some require empty parameters to be part of the signature (against the spec), and some don't. This is why the "Add empty params" option  exists.

**Comment by bertop89** [comment]
I came across this problem. While I appreciate the "Add empty params", the behavior of POST and GET requests seems to be different in my case. In GET requests, leaving the "Token" field blank, doesn't generate an empty "oauth_token" param. However, in POST requests, leaving this field blank generates an empty "oauth_token" param which might lead to confusion when computing the signature.
