### ISSUE TITLE
App crashes when choosing files for form-data - segment fault

### ISSUE THREAD

**Issue by mevinod** [a85/POSTMan-Chrome-Extension#8835]
**Describe the bug**
I have a PATCH API which is of formdata. When I choose file and on selecting the file, postman crashes with segment fault error. I am using debian and the latest postman client 7.29.1

**To Reproduce**
1. Open postman
2. New request
3. Select body and formdata
4. Choose File as key and click to choose file
5. On selecting the file, app crashes.

**Expected behavior**
I should able to select and upload the file

**Logs**
```
./Testing/Postman/Postman
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Not disabling GPU
Main~createDefaultWorkingDir - Default working dir creation already attempted
1595677273226 main info "Booting Postman 7.29.1, linux-4.19.0-9-amd64 on x64"
1595677273228 main info "EventBus~initialize - Success"
1595677273322 main warn "CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/user/.config/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/home/user/.config/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/home/user/.config/Postman/Postman_Config/proxy'"}
1595677273325 main info "CloudProxyManager~init - Success"
1595677273336 main info "UpdateHandler~init - Success"
1595677275664 main info "RuntimeIPCAgent~started: Success"
1595677275856 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1595677276661 main info "Bootstrap-models~bootstrap - Success"
1595677277085 main info "window-manager~newSharedWindow: Shell loaded"
1595677279888 main info "Main~AppEvents - Received booted event for process shared"
1595677282174 main info "UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
1595677282194 main info "Main~AppEvents - Received booted event for process requester"
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }
Segmentation fault
```

**Comment by DannyDainton** [comment]
Hey @mevinod

Thanks for writing in 🏆

Would it be possible to send us a screenshot or a short recording of the app crashing, please?

**Comment by mevinod** [comment]
See video here: https://a.uguu.se/vjbqad.mp4 the video will be removed in 24 hrs from now. @DannyDainton, in the video I'm trying to open the folder, but if I choose a file also it behaves same way.

**Comment by DannyDainton** [comment]
Are you able to upload the mp4 to github using the upload image option provided? 

I tried accessing the video and it wasn't showing anything but also, it's the weekend and I wouldn't want any link provided to expire before someone else has looked into the issue.

**Comment by mevinod** [comment]
Cant upload mp4 to github. Here is few screenshot from video.
![Screenshot_2020-07-27_11-43-27](https://user-images.githubusercontent.com/34798214/88509367-8a783d00-cffe-11ea-9e94-335e3aef9ebb.png)
![Screenshot_2020-07-27_11-43-01](https://user-images.githubusercontent.com/34798214/88509372-8ba96a00-cffe-11ea-8f07-a739f582b0fd.png)
![Screenshot_2020-07-27_11-42-25](https://user-images.githubusercontent.com/34798214/88509373-8c420080-cffe-11ea-832b-25e0c854634d.png)

**Comment by mevinod** [comment]
@DannyDainton do you have any update on this?

**Comment by mccannt** [comment]
@mevinod What flavour of Linux are you using? 
I just tried to replicate this on Ubuntu 18.04 and I am not seeing any unusual behaviour 🤔

**Comment by mevinod** [comment]
I'm using debian 10

**Comment by mevinod** [comment]
This is still an issue to me, I am closing this as I have discovered other tools to do this. Thanks for delaying it.

**Comment by ccarnus** [comment]
@mevinod what other tool do you use for that? I have the same issue
