### ISSUE TITLE
Postman.setNextRequest("Request Name") does not execute next request within a loop

### ISSUE THREAD

**Issue by EugeneKonneh** [a85/POSTMan-Chrome-Extension#8841]
**Describe the bug*

I have an api that returns a list of 90 vehicle manufacturers.
I want to loop though response of from calling this API and set a collection variable = manufacturerId for each manufacturer.
Within this looping, I want to call a second API to consume the manufacturerId variable display all the vehicle models for that manufacturer.

![image](https://user-images.githubusercontent.com/48555490/88567124-f4a8d600-d02e-11ea-8d33-ae6155337f06.png)

**Expected behaviour**
I expect the models of the each selected model to be displayed and the tests to be executed against the inner request

![image](https://user-images.githubusercontent.com/48555490/88568224-882ed680-d030-11ea-91f2-790ed49d9016.png)

**App information (please complete the following information):**
 - App Type [Website]
 - Postman Version [7.29.1]
 - OS: [Windows10 Enterprise build 17134.1610 ]

**Comment by xk0der** [comment]
Hey @EugeneKonneh , I think there is confusion on how `postman.setNextRequest()` works which is resulting in the behaviour you are noticing. What you should be using instead is `pm.sendRequest()` to invoke an API call from within the loop.

Do check out the following articles for more details:
* https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#pmsendrequest
* https://learning.postman.com/docs/running-collections/building-workflows/

In short, `postman.setNextRequest()` just set's the next request to be run. Once the current request has completed and it's "Test" script is finished, the request set via `postman.setNextRequest()` would be run.
In your case "`Get Vehicle Models ....`" request would be run once when the Test script finishes for the current request.

_Couple of ways to solve this:_
* Looking at your description, I believe you want to call the API endpoint from within the loop, in that case, you would need to invoke the API using `pm.sendRequest()` construct. You can then print the response via `console.log()` and check the Postman Console to view the response for both the APIs.

* Alternatively, you can store the result from the first request into an environment/collection variable and then create a loop using `pm.sendRequest()` to process the items one by one.

If you have any follow-up queries, I would highly encourage you to post it at Postman's community forum https://community.postman.com/ It's a vibrant and very active community, you should get good quality feedback there.

Hope this helps!

**Comment by EugeneKonneh** [comment]
Thank you very much @xk0der.
I will proceed per recommendations.
Much appreciated.
