### ISSUE TITLE
It should recognize non-apostrophed ('...') url with queries in order to import from cURLs

### ISSUE THREAD

**Issue by Dentrax** [a85/POSTMan-Chrome-Extension#8843]
**Describe the bug**
Postman does not recognize non-apostrophed URLs like: `https://test.com/test/foo?bar=1&baz=2`

**To Reproduce**
1. Go to _Import_
2. Click on _Raw Text_
3. Paste this _cURL_:
```sh
curl -X GET -H "User-Agent: Dalvik/2.1.0 (Linux; U; Android 10; SM-A705FN Build/QP1A.190711.020) Test/4.6.4.459" -H "Authorization: bearer XXX" -H "x-storefront-id: 1" -H "x-application-id: 5" -H "Build: 4.6.4.459" -H "Platform: Android" -H "Gender: M" -H "SearchSegment: 98" -H "OSVersion: 10" -H "DeviceId: b147ee89" -H "pid: bdb5748e" -H "sid: 5096fd6e" -H "x-features: FEATURE1_ENABLED" -H "Accept-Language: tr-TR" -H "Content-Type: application/json" https://test.com/test/foo?bar=1&baz=2
```
**P.S:** This _cURL_ was generated from [chuck](https://github.com/jgilfelt/chuck).
4. See error: `arg.startsWith is not a function`

**Expected behavior**
It should import that `cURL` without any error.

**Screenshots**
<img width="323" alt="Screen Shot 2020-07-28 at 11 22 01" src="https://user-images.githubusercontent.com/16493751/88638729-91698300-d0c4-11ea-8385-002b48bee9c3.png">

**App information:**
 - App Type: _Native App_
 - Postman Version: _7.29.0_
 - OS: _macOS High Sierra 10.15.3_

**Comment by Dentrax** [comment]
Hey @DannyDainton, sorry for pinging. It seems this bug still happens in the latest version of Postman. Any updates?

**Comment by DannyDainton** [comment]
Hey @Dentrax 

There haven't been any recent product updates that would have fixed this issue - I don't currently have any updates for this issue.

**Comment by SahilChoudhary22** [comment]
Hey @Dentrax
The bug has been resolved and you won't be encountering it from the next production release.
