### ISSUE TITLE
Sync API schema for GitLab

### ISSUE THREAD

**Issue by canisay** [a85/POSTMan-Chrome-Extension#8844]
The Sync API schema integration is not available for GitLab like it is for GitHub, would like to have that option if possible:
![sync](https://user-images.githubusercontent.com/775535/88641880-b0154d00-d0b7-11ea-9193-930c556fce32.PNG)

**Comment by zleroy** [comment]
Our organization would also benefit from a GitLab integration

**Comment by vinnytroia** [comment]
+10

**Comment by jotsarup** [comment]
We are working on it and will push it out as soon as possible.

**Comment by mhowes82** [comment]
Hi @jotsarup , is there an update on when the GitLab integration might be updated with this feature? We're planning to move our APIs to Postman using a GitLab repo and would love to be able to sync collections. Thanks!

**Comment by bagage** [comment]
Bumping this issue since a few months have passed since. @jotsarup is there any ETA for it? :heart:

**Comment by sweethuman** [comment]
I'm wondering why this doesn't have so more traction behind it. Is GitLab not used that much?

**Comment by shashankawasthi88** [comment]
Hey Everyone, while we are planning to add GitLab integration soon, we would want to gain some feedback on the recent release (API Platform with Integrations with repository Integrations). We would love to know how well the release caters to your use cases. For GitLab, the flows will remain exactly the same, hence you could try out the flows with existing providers. This will help us plan any changes if required for the GitLab Integration.
You can schedule a call with us using this link - https://calendly.com/shashank-awasthi/api-platform-feedback

**Comment by shashankawasthi88** [comment]
@sweethuman @bagage @mhowes82 @vinnytroia @canisay and others can you confirm which GitLab deployment do you folks use. GitLab Cloud Hosted or GitLab Self Hosted ?

**Comment by sweethuman** [comment]
> @sweethuman @bagage @mhowes82 @vinnytroia @canisay and others can you confirm which GitLab deployment do you folks use. GitLab Cloud Hosted or GitLab Self Hosted ?

Gitlab Hosted

**Comment by zleroy** [comment]
Gitlab self hosted is what we use.

**Comment by abhijitkane** [comment]
We've launched support for GitLab SaaS last week. This is part of our new Git integration released in September (https://blog.postman.com/the-reimagined-api-first-workflow-for-developers/). Support for self-hosted instances of GitLab will only be available on our Enterprise plan.

**Comment by sweethuman** [comment]
it seems though that i can't connect two api's to the same repo

**Comment by shashankawasthi88** [comment]
@sweethuman Two APIs can not be connected to the same repo+branch combination. If the APIs are hosted in the different branches of the same repo, you should be able to connect to them. We don't support the mono-repo pattern yet.
