### ISSUE TITLE
Need support for IPv6 Address in Request URI

### ISSUE THREAD

**Issue by chodges15** [a85/POSTMan-Chrome-Extension#8847]
**Describe the bug**
Cannot use raw IPV6 address in request.

**To Reproduce**
1. Create a request with a URL that includes a raw IPV6 address
2. Click on Send
3. See error: `Error: getaddrinfo ENOTFOUND [2607:f8b0:4002:813::200e]`

**Expected behavior**
Postman should allow both raw IPV4 and IPV6 addresses.

**Screenshots**
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/24880218/88708793-d1873080-d0d9-11ea-8976-80aae13e4cb6.png">

```
~ » curl http://\[2607:f8b0:4002:813::200e\]
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  ...
  ...
```

**App information (please complete the following information):**
 - App Type: Mac Native
 - Postman Version [e.g. 7.0.0]: 7.29.0
 - OS: [e.g. macOS High Sierra 10.13.2] macOS Catalina 10.15.5

**Additional context**
The example here does a request using the IPV6 address for google.com. Using a domain name solves this problem, but is not always available. My current workaround is documented in a [Postman community discussion](https://community.postman.com/t/ipv6-post-request-does-not-work/4400).

**Comment by codenirvana** [comment]
@chodges15 Thanks for reporting this issue, we've identified the issue and will be fixed as soon as possible.
