### ISSUE TITLE
Blue Screen of Death (Windows 10) 

### ISSUE THREAD

**Issue by ShamanFromSiberia** [a85/POSTMan-Chrome-Extension#8848]
**Describe the bug**
Running Postman on my Windows 10 laptop always leads to system crash with the blue screen of death. Also there're some annoying graphic artifacts between crashes.The artifacts and blue screens could be seen in the screenshots section below. There are three BSD error codes so far: MEMORY_MANAGEMENT, BAD_POOL_CALLER, KMODE_EXCEPTION_NOT_HANDLED

**To Reproduce**
It happens unexpectedly, with only one condition - Postman window is active. Graphioc artifacts are there constantly, just moving from one place to another. 
_Please don't blame my graphic adapter or drivers - all is checked and every other program works fine._

**Expected behavior**
There should be stable working process without artifacts and blue screens. Every other application on my laptop works smoothly.

**Screenshots**
Artifacts: ![{469A59A3-F706-4F08-8CFE-922C3B6E9D9F} png](https://user-images.githubusercontent.com/7860406/88713697-61ea6300-d124-11ea-9ab6-0fe09f193075.jpg)
BSD MEMORY_MANAGEMENT: ![photo_2020-07-28_21-11-39](https://user-images.githubusercontent.com/7860406/88713663-55660a80-d124-11ea-9c0d-3092ddd8abb9.jpg)
BSD BAD_POOL_CALLER: ![photo_2020-07-28_21-11-45](https://user-images.githubusercontent.com/7860406/88713668-56973780-d124-11ea-9421-10f6480b8bcb.jpg)
BSD KMODE_EXCEPTION_NOT_HANDLED: ![photo_2020-07-28_21-11-33](https://user-images.githubusercontent.com/7860406/88713669-56973780-d124-11ea-8c63-f70a76a59c3f.jpg)

**App information (please complete the following information):**
 - Native App
 - Postman v7.29.1
 - OS: Windows 10 1909

**Additional context**
Laptop ASUS N56DY

**Comment by kamalaknn** [comment]
Hey @ShamanFromSiberia 

1. Could you forward the logs from `View -> Developer -> View logs in Explorer` to `help@postman.com`, to help us debug the issue better?

2. Could you try launching Postman with GPU disabled? You can find the steps to disable GPU [here](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621)

**Comment by ShamanFromSiberia** [comment]
1. Is it possible to access the logs out of Postman?

2. I'll try it and will let you know of the results.

**Comment by kamalaknn** [comment]
@ShamanFromSiberia You can find the logs in `C:\Users\<user>\AppData\Roaming\Postman` directory.

**Comment by ShahinKohan** [comment]
For some reason the recent postman release actually tries to use the High Speed GPU (for example on surface book) instead of the default GPU. In Surface Book you have the option to right click on the icon and choose to run it with high speed graphics. But the recent version of Postman forces that by default. It should by default run on integrated graphics not high-speed GPU.

![image](https://user-images.githubusercontent.com/12249626/89912418-62b0d980-dba7-11ea-883c-f960bef730d2.png)

**Comment by numaanashraf** [comment]
@ShamanFromSiberia 

We haven't gotten a response to further triage and debug this issue. With the information that is currently in the issue, we don't have enough details to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by zhiyong-ft** [comment]
Please let me know what information you need. I think I am running into the same issue now, can help gather whatever information you guys need.

**Comment by jviotti** [comment]
Does the issue remain if you disable "Hardware Acceleration" from the "Help" menu? If you can't manage to access this setting before it crashes, can you run `setx POSTMAN_DISABLE_GPU 1` on a `cmd.exe` instance and then run the application?
