### ISSUE TITLE
Error message of "xmlhttprequest is undefined" was shown when execute http request via javaScript  in test/pre-script-test

### ISSUE THREAD

**Issue by lqinss** [a85/POSTMan-Chrome-Extension#885]
![test](https://cloud.githubusercontent.com/assets/10612485/5815656/670f522e-a0d2-11e4-9ddd-610deaa19a4c.png)

**Comment by abhijitkane** [comment]
Pre-request scripts and Test scripts are run synchronously. There's no way of making XHR requests from the test script right now.

You'll have to add another postman request before this, and use environment variables to persist data across requests.

**Comment by lqinss** [comment]
Thanks for your quick repose .
