### ISSUE TITLE
Is there any way to continue with tests in postman even if any one assert fails in it?

### ISSUE THREAD

**Issue by svarshney2311** [a85/POSTMan-Chrome-Extension#8850]
In a Postman GET request, I have used multiple assertions. However, if any assertion fails, Postman will stops its execution then and there and will throw an error.

Is there any way to prevent this and continue with other assertions even if any one among them fails?

pm.test("Verify the Usage amount for Text", function () {
 pm.response.to.have.status(200);
 var jsonData = pm.response.json() ;
 pm.expect(responseBody.length).to.eql(3);
 pm.expect(jsonData, "response is NOT empty").not.to.be.empty;
  });
like in above example, I wanted to test all 3 assertion and than fail the tests.
Currently if it fails on first assertion, it stops the test and showed the result only for first assertion without testing rest two assertions.

**Comment by DannyDainton** [comment]
Hey @svarshney2311

This seems like a great question for the community forum, rather than an issue for this repository.

Could you close this out and open a new thread here please?

https://community.postman.com

**Comment by DannyDainton** [comment]
Question raised in the community.

Closing this out now.
