### ISSUE TITLE
export test result needs add html format 

### ISSUE THREAD

**Issue by henry-ceo** [a85/POSTMan-Chrome-Extension#8853]
**Describe the bug**
after collection run，the test result export only has json format，but user cann't see json content，

 add html format  is very useful.

**Comment by DannyDainton** [comment]
Hey @henry-ceo

Not sure if this is a feature request or not - Would you be able to expand on the details of your use case please?

Alternatively, you could use our CLI Collection Runner, Newman. 

https://github.com/postmanlabs/newman

This will provide you with a way to run the Collection and output to results to a HTML report.

This one is quite good... 😁

https://github.com/DannyDainton/newman-reporter-htmlextra

**Comment by DannyDainton** [comment]
Hey @henry-ceo 

We haven't heard back from you, regarding the information we need to move this request further.

I'm going to close out the issue for now but we can look to open it again when we receive the clarifying details.
