### ISSUE TITLE
High CPU usage in Version 7.29.1 (for windows)

### ISSUE THREAD

**Issue by costa-levine** [a85/POSTMan-Chrome-Extension#8854]
**Describe the bug**
High CPU usage in Version 7.29.1

**To Reproduce**
Open Postman 
Go to windows task manager and find postman
The CPU LOAD is about 30% without running any requests

**Expected behavior**
Low CPU load

**Screenshots**
![image](https://user-images.githubusercontent.com/1649451/88799306-a570bb80-d17c-11ea-80c8-f73a67a64bc8.png)

**Comment by mccannt** [comment]
@costabi Do you happen to have many collections or requests in your workspace?

**Comment by costa-levine** [comment]
@mccannt , Yes, I do have about 100 requests in the collections and about 3-5 tabs opened at the time of the screenshot.

Checked the CPU again a moment ago and the CPU load had stabilized and went back to 0.1-2% range.

I'd guess it's not an issue anymore, tho it was very unusual CPU load for a long time.

**Comment by mccannt** [comment]
@costabi Thanks for the follow-up. We are constantly working to improve the performance of our application, so we appreciate your feedback on this.
