### ISSUE TITLE
extract variable in string

### ISSUE THREAD

**Issue by jiqimaogou** [a85/POSTMan-Chrome-Extension#8855]
I request a url like: `{{host}}/test`:

and in script I want to extract {{host}} to it's real value like `testHost/test`, How can I do, which Api should I use.

**Comment by DannyDainton** [comment]
Hey @jiqimaogou

This seems like a perfect question to raise as a new topic on our community site - https://community.postman.com

I'm going to close this issue for now and see you over there. 🚀
