### ISSUE TITLE
Saving responses with Interceptor

### ISSUE THREAD

**Issue by tiago-oliveira-trustly** [a85/POSTMan-Chrome-Extension#8856]
**Is your feature request related to a problem? Please describe.**
I use interceptor to test API implementations. I can intercept the requests but not the responses. If I want to save the responses I need to run all the requests again that Interceptor just saved.

**Describe the solution you'd like**
I would like to be able to save both requests and responses at the same time while intercepting.

**Comment by jzyrobert** [comment]
Hi, I am having this issue as well.
Was https://github.com/postmanlabs/postman-app-support/issues/622 not a solution for this, or was that only for manual requests sent within Postman?

**Comment by SpaceRoger777** [comment]
same issue here

**Comment by shashankawasthi88** [comment]
@tiago-oliveira-trustly @jzyrobert @RogerMichel - we have started exploring flows around response capturing via interceptors/ proxy. Would love to get onto a call to understand your exact use case so that we could tailor the experience accordingly. If you could schedule a call using this link - https://calendly.com/shashank-awasthi/postman-proxy according to your convenience, it would be great.

**Comment by shashankawasthi88** [comment]
@tiago-oliveira-trustly  @jzyrobert @RogerMichel  with the latest release (v 8.9.1) of the Postman App, you now have the ability to save the responses along with the corresponding request via **Postman Proxy**.  You should now see the requests and the corresponding responses for the traffic captured via Proxy in the History or Collection based on your selection.

Additionally, we have added the ability for you to organize the captured traffic based on 'Domain Name' and 'End Point' in the Collection. This shall help you organize the Collection better and can help in better collaboration and documentation using that collection. Look for more information [here](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/)

**Comment by jzyrobert** [comment]
Thank you!

**Comment by abhijitkane** [comment]
Closing this - Chrome doesn't have the required APIs to capture responses, and the updated proxy feature solves this use case.
