### ISSUE TITLE
Allow user to specify what header to use when sending OAuth 2.0 token

### ISSUE THREAD

**Issue by TJReinert** [a85/POSTMan-Chrome-Extension#8857]
**Situation**
I currently have a proxy that requires the 'Proxy-Authentication' header to be populated with an OAuth 2.0 token.  Right now the OAuth 2.0 screen forces the token into the 'Authorization' Header. 

**Current Workflow**
I use Postman to get a new token and have to manually copy the token to the Proxy-Authorization header.

**Solution**
Allow the user to specify a header where the OAuth token should be placed.

**Comment by giridharvc7** [comment]
You can set your own header prefix in v8 and the web, please let us know if this fixes your issue
![Screenshot 2021-04-14 at 12 21 10 PM](https://user-images.githubusercontent.com/1040583/114666571-07c61800-9d1c-11eb-90e4-48058001213f.png)

**Comment by mancave** [comment]
It's not the prefix of the value of the Autorization HTTP Header, it's the HTTP header name what's requested

**Comment by TJReinert** [comment]
I missed the first reply to this issue. @mancave is correct. I want the ability to specify what Header Name to put my authorization in. Example:

X-API-KEY: Bearer ...
