### ISSUE TITLE
addition of timeout in postman

### ISSUE THREAD

**Issue by shanmukha8290** [a85/POSTMan-Chrome-Extension#8859]
Hi All,

Can you please help me to write a test in postman such that whenever I fire an API and if it is not giving response within 30 minutes, I need to exit/skip the service.

Thanks in advance

Regards,
Shanmukha

**Comment by mccannt** [comment]
@shanmukha8290 You will likely be able to get better support on this from our community over at https://community.postman.com/ 

Everyone there is super helpful and I believe an answer to this may already be posted there.
