### ISSUE TITLE
Generated Docs Authorization key "Value" not resolving

### ISSUE THREAD

**Issue by rainabba** [a85/POSTMan-Chrome-Extension#8861]
**Describe the bug**
The Authorization sections on generated documentation appears off to me as it's not provided the information I'd expect.

**To Reproduce**
1. For a collection, set Authorization to "API Key" and Key field to "x-api-key" and Value to "the-key-resolving-in-context" and "Update".
2. Go to an API, then Documentation (reached from Collection running button then "View in Web").
3. Locate the generated "Authorization API key" area then see the table below to find **Key**/**\<key\>**, **Value**/**the-key-resolving-in-context**

**Expected behavior**
I would expect the header row to read **Key**/**Value** and the data row to display as **x-api-key**/**the-key-resolving-in-context** or the top row to read **Key**/**x-api-key** and the data row to read **Value**/**the-key-resolving-in-context**.

**Screenshots**
![image](https://user-images.githubusercontent.com/553630/88860433-9146b180-d1b0-11ea-84d3-f5c4675250b7.png)

**App information (please complete the following information):**
- Chrome Version 84.0.4147.89 (Official Build) (64-bit)
- Windows 10 2004/19041.388

**Comment by Raja-Simha** [comment]
@rainabba You can use environment variables to show desired auth values in the documentation. 

For example, you can set {{key}} as x-api-key and {{value}} as the-key-resolve-in-context to display variable initial values in documentation. For example,

![image](https://user-images.githubusercontent.com/45988836/89217381-b50f5a80-d5e9-11ea-8b7e-c6cd74bca7a5.png)

 would result in 

![image](https://user-images.githubusercontent.com/45988836/89217455-da03cd80-d5e9-11ea-97f6-9708f53519fe.png)



This is to avoid accidental leakage/sharing of auth credentials. For example,

![image](https://user-images.githubusercontent.com/45988836/89217793-62826e00-d5ea-11ea-8e56-3b7e26be5084.png)

The above will show up by default in the documentation as placeholders.

![image](https://user-images.githubusercontent.com/45988836/89217920-affedb00-d5ea-11ea-98bc-fe778041f3fa.png)

I hope this resolves your issue. Do let me know if you have any further concerns or feedback. I will keep this issue open for a couple of more days.

**Comment by rainabba** [comment]
Thank you. 

Now that I see that in this context, it looks like the take-away I needed was to "see" that <key> was a variable placeholder as would be {{key}}.

I'm new to this side of PostMan and that wasn't obvious to me so I didn't infer that "I need to provide a value for "key" in context.

Cheers!
