### ISSUE TITLE
Can't create collection from API graphql schema

### ISSUE THREAD

**Issue by AndresDV** [a85/POSTMan-Chrome-Extension#8863]
Hi, we have a couple of years now using postman for all our APIs but currently we are facing an issue when we try tro create a collection based in our graphql schema. The error messages don't give us any significant information to know what is wrong, can you please help us knowing why this is failing.

Attached our current schema so you can take a look.

Thanks for your time and any help you can provide.

[schema.zip](https://github.com/postmanlabs/postman-app-support/files/4999875/schema.zip)

**Comment by DannyDainton** [comment]
Hey @AndresDV

Could you also provide your OS and app version, please? 

Also, the error message you're seeing, a screenshot and steps to reproduce would help us understand your issue in more detail.

**Comment by AndresDV** [comment]
Sure: 

OS: Windows 10 

Postman Version: 7.29.1

Creating API
![image](https://user-images.githubusercontent.com/28811341/88901079-8ec67500-d20d-11ea-8942-5b5aefa129d8.png)

Definition seems to be fine
![image](https://user-images.githubusercontent.com/28811341/88901122-a271db80-d20d-11ea-82e6-0e85f95668c8.png)

Create Collection
![image](https://user-images.githubusercontent.com/28811341/88901178-b4ec1500-d20d-11ea-8f97-9faf9cfdb9dc.png)

Failed with the following error and nothing else is visible in console
![image](https://user-images.githubusercontent.com/28811341/88901227-c6352180-d20d-11ea-9722-7680d4638071.png)

**Comment by DannyDainton** [comment]
Hey @AndresDV 

Apologies, I've been away and I'm taking another look at this one now. If you use your schema file on the main `Import` flow, the API would be created and not the Collection, like you mentioned, this time you will see more context in the error message. 

> Error while importing GraphQL: Could not generate collection. Error Message:Cannot read property 'getFields' of undefined

![Screenshot 2020-08-03 at 13 42 39](https://user-images.githubusercontent.com/17089546/89183544-4bfaf900-d58f-11ea-84a2-add1b2fcb947.png)

I'm still looking into this but wanted to update here first.

**Comment by AndresDV** [comment]
Thanks for taking a look into this, yeah that was also another error message I saw but I couldn't see anything related to that 'getFields' in our schema.

Please let me know if you have any update :)

**Comment by DannyDainton** [comment]
Hey @AndresDV 

I've raised this internally and created a bug for it. Don't have an ETA for any sort of fix yet but the issue will be updated once there's more information.

**Comment by nickwinsor** [comment]
+1 we're seeing the same behaviour when trying to import our GraphQL schema as well.

We've tried exporting the schema in both SDL and JSON with the following tools, and all failed upon attempting to generate the collection with the same error mentioned above :
- [Apollo](https://github.com/apollographql/apollo-tooling)
- [GraphQL Export](https://github.com/oshosanya/graphql-export)
- [get-graphql-schema](https://github.com/prisma-labs/get-graphql-schema)

**Comment by umeshp7** [comment]
@nickwinsor 
Thanks for the update. We have taken this up and we will have an update on this super soon. :)

**Comment by bcorke** [comment]
+1 seeing the same behaviour 

Error message when importing GraphQL as collection:

`Error while importing GraphQL: Could not generate collection. Error Message:Cannot read property 'getFields' of undefined`

**Comment by cosmicbuffalo** [comment]
+1 getting the same `Could not convert the given schema` message. I'm not seeing a better error message on the main `Import` flow either

**Comment by umeshp7** [comment]
@AndresDV Sorry for the inconvenience! 
 
I see that you have this in your current schema:
```
schema {
  query: QueryRoot
  mutation: MutationRoot
}
```
If you change this to: 
```
schema {
  query: Query
  mutation: Mutation
}
```
and 
`type QueryRoot {` => `type Query {` and similarly for `MutationRoot`. The schema should be converted successfully. 

Of course this is not ideal and we have worked on a fix to support any name for your Root Query, Mutation and Subcription types and we will be releasing the fix soon. Meanwhile this workaround should help. 

@bencorke @nickwinsor @cosmicbuffalo Could you also try checking your root types and changing them to `Query`,  `Mutation`, and `Subscription` respectively? This might help unblock you.
