### ISSUE TITLE
Saving No Longer Defaults to Previous Location

### ISSUE THREAD

**Issue by evancjohnson** [a85/POSTMan-Chrome-Extension#8864]
**Describe the bug**
The safe file dialog no longer saves previous location.

In the latest version of postman, saving results to a file no longer start at the previous location of the last saved file. For example if I saved a response to my documents folder when the dialog opens again it should save to my documents folder. Instead it now defaults to quick access. This behavior was not present a few weeks ago.

**To Reproduce**
1. Send a request (GET/POST/ETC..)
2. Click on 'Save Response'
3. Click on 'Save to a file'
4. See open file dialog 

**Expected behavior**
Native save dialog to save previous save location instead of defaulting to Quick Access.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/17952965/88937234-7c6a2c80-d249-11ea-9e81-e102d831af98.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.29.1
 - OS: Windows 10 Enterprise 1809 (17763.1339)

**Additional context**
N/A

**Comment by mccannt** [comment]
@evancjohnson Please have a look at this documentation and let us know if it resolves your issue - https://learning.postman.com/docs/getting-started/settings/

**Comment by evancjohnson** [comment]
@mccannt That does not fix my issue. My issue occurs when saving a response. I changed the directory but Save File dialog still defaults to Quick Access on windows

**Comment by richardgroves** [comment]
Also seeing this problem on MacOS Catalina 10.15.6
Postman version Version 7.29.1 (7.29.1), was fine before the last update I did but unfortunately I don't know which version that was.

I worked out how to download an old version and 7.28.0 - from https://dl.pstmn.io/download/version/7.28.0/osx64 - doesn't have the problem.
