### ISSUE TITLE
Make comments accessible via Postman API

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8865]
**Is your feature request related to a problem? Please describe.**
There is no way to access comments via the Postman API.

**Describe the solution you'd like**
Make comments accessible via the Postman API.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/postmanlabs/postman-app-support/issues/7261

**Comment by TheAlakazam** [comment]
Hey, can I work on this if it's possible?

**Comment by arlemi** [comment]
@TheAlakazam This is not something you'd be able to work on from the outside unfortunately. If you're interested in helping us you can have a look at some of our open source repositories: 
- Documentation https://github.com/postmanlabs/postman-docs
- OpenAPI to Postman converter https://github.com/postmanlabs/openapi-to-postman
- Code generators https://github.com/postmanlabs/postman-code-generators

**Comment by meenakshi-dhanani** [comment]
I wanted to clean up a workspace before it goes public to remove all private comments. The API would be really useful in that case

**Comment by camellia** [comment]
Another use case for this: I'd like to be able to maintain a record of the commentary. For example, I could pull a summary of all comments on a collection rather than navigating through all requests to find comments for each.

**Comment by davidespihernandez** [comment]
Hi! The Postman API now allows you to manage comments programmatically.
- CRUD comments on [collections](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-9ff12786-452c-45e4-9dd1-6819a000434f)
- CRUD comments on [APIs](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-8b8ce8f4-58df-4a7a-975b-4fa9e3ff5164)
- CRUD comments on a [collection folder](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-c53b2943-0dcf-4f6b-baff-eec9e94297c4)
- CRUD comments on a [collection request](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-ee3f1a82-336b-4e32-901a-7af7b87c3d1e)
- CRUD comments on [request responses](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-491c5494-e6e4-477f-bdc4-4ef569a72ff3)
