### ISSUE TITLE
TCP Keep Alive packets are being sent in Chrome app but not in native app

### ISSUE THREAD

**Issue by Aileron79** [a85/POSTMan-Chrome-Extension#8868]
**Describe the bug**
The Postman standalone app does not send TCP Keep-Alive packages while the Postman Chrome app does.

**To Reproduce**
Do this for both, native and Chrome versions of Postman:
1.) Find some API which takes a long time (>6 minutes or even much more) to respond
2.) Create GET request in Postman native/Chrome
3.) Launch Wireshark and configure to monitor the connection
4.) Fire the GET request in Postman native/Chrome
5.) Compare the results in Wireshark. You will notice that after 45 seconds the Chrome app starts sending out TCP keep alive packets while the native app does not. Therefore, a request might time out/not return any data in the native app while it works fine in the Chrome app

**Expected behavior**
Send keep-alive pings in both versions of Postman. Or even better, enable/disable TCP Keep Alive packets in the settings.

**Screenshots**
not applicable. Assume you know how Wireshark works and how it looks like.

**App information (please complete the following information):**
Chrome app: Version 5.5.5
Native app: Version 7.29.1
OS: Windows 10.0.19041 / x64

**Additional context**

**Comment by mohitranka** [comment]
@Aileron79  The chrome app has been deprecated and is not supported anymore. Can you explain a bit about the problem you are facing ?

**Comment by Aileron79** [comment]
I am attempting to download data from a web service. The server needs several minutes of internal work before it would even return data. We are talking about 8 to 20 minutes. The server will return data when the client is sending TCP Keep-Alive packets but won't return anything if these packets are not being send by the client. Hence the request works in the deprecated Chrome extension while it does NOT work in the standalone version. Thus, I would expect that the latter has an option to enable these packets being sent. I have attached a screenshot from Wireshark where you can clearly see the Keep-Alive packets. These you won't see when using the standalone version.

I am not asking for support for the deprecated version, I am just confused why there is functionality in that rather old version which is not supported in the current version. I'd expect there to be a possibility to enable/disable this kind of packets.

![timeout](https://user-images.githubusercontent.com/16278437/89154505-4c7f9980-d567-11ea-899c-abc1e1b40a59.gif)

**Comment by codenirvana** [comment]
@Aileron79 Keep-Alive is supported in the native app as well.

Tried reproducing this issue locally:
![Screenshot 2021-04-12 at 9 49 48 PM](https://user-images.githubusercontent.com/4865836/114428261-954d1f00-9bd9-11eb-9bb4-48a827d85f19.png)

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.
