### ISSUE TITLE
How to minify formatted json

### ISSUE THREAD

**Issue by Numenorean** [a85/POSTMan-Chrome-Extension#8870]
I can beautify json text. but i can't minify it then. Is there any hotkey or button to do this?

**Comment by DannyDainton** [comment]
Hey @Numenorean

By minify, do you mean fold?

Is this what you're after - https://stackoverflow.com/a/30077543/6028443

**Comment by DannyDainton** [comment]
Hey @Numenorean

Not heard back from you for about 5 days. 

I'm going to close this issue for now but we can reopen once more information is supplied.

**Comment by nacengineer** [comment]
For the record pretty sure the OP was requesting white space minification, basically the opposite of Beautify, not folding. It would be a useful feature. Why? e.g. using to create one-liners in bash for a curl POST in a script

**Comment by colonelclick** [comment]
Yes, exactly that, uglify it to a one-line string with no whitespace around the JSON control characters such as `{}[]:,`

Some (misbehaving) apis require minification (uglify) and I am unable to smoothly use postman to develop against them. The workflow is that I need to beautify it to sanely make some changes, then uglify it to send my request, and iterate on this process.

**Comment by colonelclick** [comment]
@DannyDainton Should we make a new issue for this request? Thank you for your help.

**Comment by luke-belton** [comment]
This feature would also be handy for APIs that impose a payload size limit - for larger payloads all the extra whitespace can considerably increase the payload size (and postman doesn't automatically strip that when sending a request). The beautify feature is great for doing minor edits of the payload before making a request, but it would be good to then be able to reverse that!
