### ISSUE TITLE
Encoding `charset` from older response are getting persisted when new response have no `charset` defined in Content-Type

### ISSUE THREAD

**Issue by saswatds** [a85/POSTMan-Chrome-Extension#8876]
**Describe the bug**
In case of responses which use content-type encoding other than `utf-8`, 
* When the `charset` is missing in the Content-Type header is assumed to be `utf-8`. 
* If the `charset` is defined in the Content-Type header it takes precedence. 

This issue arises when a response containing an explicit charset defined is followed by a response containing no charset defined. The app uses the older charset and does not default to `utf-8` for the new response.

**To Reproduce**
Steps to reproduce the behaviour:
1. Restart or Open the postman app. (Quit and Restart is important)
2. Open a new tab
3. Make a request to `https://httpbin.org/get` (Do not use postman-echo)
4. Notice the response being rendered correctly
5. Now use this  [Snippet](https://gist.github.com/saswatds/78e4b2c6b010db9d3a31539a2a893c95) to start the server
6. Make a request to `http://localhost:8080/utf16`
7. Notice the response is rendered correctly as the encoding is being handled
8. Now make a request again to `https://httpbin.org/get`
9. Notice that the response is now garbled because the encoding did not default to `utf-8` but used the previous `utf-16` encoding

**Expected behaviour**
The new response without having an explicit charset should default to `utf-8` decoding for the content.

**App information (please complete the following information):**
 - App Type - Native App, Web
 - Postman Version - v7.29.1
 - OS: macOS

**Additional context**
This seems to be a problem with the `postman-collection` ~ `Response.contentInfo()` implementation

**Comment by codenirvana** [comment]
This issue is fixed in the latest version of the Postman app `v8.3.0`.
