### ISSUE TITLE
Add option for `Empty the Trash` and/or `Restore all` in the Trash section

### ISSUE THREAD

**Issue by 1bitphoenix** [a85/POSTMan-Chrome-Extension#8877]
**Is your feature request related to a problem? Please describe.**
I feel there should be option for `Empty the Trash` and/or `Restore all` in the Trash section in Postman. Recently, I wanted to empty my trash and I had to delete every item one by one. So I think it might be a good small feature to have.

**Describe the solution you'd like**
Two buttons at the top of the page: 
1. Empty the Trash/Delete All - To delete all the items at once.
2. Restore all - To restore all the items at once.

**Comment by DannyDainton** [comment]
Hey @1bitphoenix 

This has recently been added as a feature request - https://github.com/postmanlabs/postman-app-support/issues/8679

It might be worth adding a `thumbs up` on that one and also adding the additional requirement of a _Restore All_

I'm going to close this as a duplicate and track the progress over on that issue.
