### ISSUE TITLE
Working Directory change not reflected in Settings

### ISSUE THREAD

**Issue by Archimedyz** [a85/POSTMan-Chrome-Extension#8878]
**Describe the bug**
Unable to change the working directory for Postman. After selecting a directory, the display directory remains `~/Postman/files`.

**To Reproduce**
1. Open Postman
2. Open the Settings dialogue by clicking the wrench icon in the top right.
3. Under the "General" tab, scroll down to "Working Directory"
4. Take note of the working directory path, it should be `~/Postman/files`
5. Click the "Choose" button to open an explorer dialogue.
6. Navigate to any other directory, and select it.
7. Notice that the value for the Working Directory remains unchanged: `~/Postman/files`

**Expected behavior**
The Working Directory should have updated properly to the chosen path.

**Screenshots**
![image](https://user-images.githubusercontent.com/1493104/89182865-653a8000-d564-11ea-9b0b-bf81d26b686f.png) 

**App information (please complete the following information):**
 - App Type: Windows Desktop
 - Postman Version: 7.29.1 (win32 10.0.18363 / x64)
 - OS: Windows 10 Pro (Version: 10.0.18363 Build 18363)

**Additional context**
While reproducing the issue, I noticed that after selecting your working directory, subsequent clicks on "Choose" will actually open the working directory you had originally chosen (i.e. _not_ `~/Postman/files`).

**Comment by pss-miracle** [comment]
Hello, is there a workaround for this?

**Comment by Archimedyz** [comment]
There's no workaround that I am aware of. 

It seems like the setting is properly saved. It's just not properly reflected in the UI.

**Comment by Mechanicalkeyboard** [comment]
@Archimedyz  Thanks for the information. I was able to reproduce the behaviour using the request you provided. We will investigate it further.

**Comment by samiullah119** [comment]
but in my pc the choose button is not active how can  I change it to the active button

**Comment by arlemi** [comment]
@samiullah119 You can't change the directory when using Postman in the browser, only when using the native app.
