### ISSUE TITLE
select file in Client Certificates adding \ before cert address

### ISSUE THREAD

**Issue by uaksine** [a85/POSTMan-Chrome-Extension#8880]
**Describe the bug**
When trying to add a certificate in settings -> certificates, when I click on the select file, the path is shown with a forward slash instead or the directory back slash format and shows a slash before the root directory.

**To Reproduce**
1. Go to settings
2. Click on certificates
3. enter a valid URL
4. in the PFX  file, select a certificate from a C drive location
5. add appropriate Passphrase for certificate
6. See error /C:/Users/...

**Expected behavior**
I have two other certificates loaded for other environments with the appropriate formatting 

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**

 - Postman Version [7.29.1]
 - OS: [Chrome Version 84.0.4147.105]

**Comment by xk0der** [comment]
Hey @uaksine does the use of forward slashes cause any issues with the certificate's usage? Or it's just the use of forward slashes instead of back-slash on Windows platform that you want to report?

**Comment by saswatds** [comment]
Hi @uaksine, I have tried to explain the reason you see a differently formatted file path in this comment https://github.com/postmanlabs/postman-app-support/issues/8852#issuecomment-665603793

Would like to know if your requests are actually failing.

**Comment by RJFoster** [comment]
I noticed this issue today, it seems that the server is no longer receiving the client certificates I've configured. I tried with an existing certificate setup with a traditional Windows path and it worked fine. Then I removed the certs and re-added them such that I now have the new forward slash style path and my server no longer receives certs.

Postman for Windows
Version 7.29.0

**Comment by xk0der** [comment]
Hey @uaksine , @RJFoster is this issue still occurring for you with the [latest Postman app](https://postman.com/downloads)?

**Comment by DannyDainton** [comment]
Closing due to age and inactivity. If this is still an issue you're facing in the latest version of the platform, we can look at reopening this again.
