### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by kapil-kapri** [a85/POSTMan-Chrome-Extension#8882]
<img width="733" alt="Screenshot 2020-08-04 at 1 28 35 PM" src="https://user-images.githubusercontent.com/14553746/89268773-9bf0c300-d656-11ea-9c01-31545a0bde56.png">

<img width="1255" alt="Screenshot 2020-08-04 at 1 20 56 PM" src="https://user-images.githubusercontent.com/14553746/89268383-19680380-d656-11ea-8184-02f265ff163b.png">

**Comment by DannyDainton** [comment]
Hey @kapilkapri007 

Thanks for writing in, we're going to need some more context around the issue you're facing to be able to debug what's happening here.

A short summary of what you were doing/steps to reproduce the problem. Anything that helps us to understand what's going on there.

**Comment by DannyDainton** [comment]
Hey @kapilkapri007

It's been a couple of days now without a response for you. 

I'm going to close out this issue for now but we can revisit this once the additional information is supplied.
