### ISSUE TITLE
Add Pull Changes button in Postman

### ISSUE THREAD

**Issue by mjerem34** [a85/POSTMan-Chrome-Extension#8883]
**Is your feature request related to a problem? Please describe.**
Not easy to understand how to pull changes

**Describe the solution you'd like**
A button below "Create Pull Request" named : "Pull Changes"

**Comment by ankit-m** [comment]
Duplicates #8303

**Comment by ankit-m** [comment]
This feature is now available on our web ([go.postman.co](go.postman.co)) version. You can find it in the collection tab - Open go.postman.co > Switch to your workspace > Click on collection in sidebar > Open `...` menu > Pull changes.

It will soon be available on our native apps as well.

**Comment by berkedif** [comment]
@ankit-m is this soon going to be in the native-apps?
