### ISSUE TITLE
Right click variable assignment no longer working

### ISSUE THREAD

**Issue by mymuss** [a85/POSTMan-Chrome-Extension#889]
In the past I've been able to right click the selected text in the response area and assign it to a predefined variable. With the last update it's gone and now I am seeing the default popup with the following items: "Copy", "Lookup in dictionary" etc...

OS X 10.10.1
Chrome 40.0.2214.91 (64-bit)
Postman packaged v 1.0.6

**Comment by ammar** [comment]
Same here. Just noticed it today.

Setting global values manually in "Manage environments" does not seem to work either.

**Comment by abhijitkane** [comment]
Not sure what happened...the code hasn't changed, and a simple rebuild works fine. 
We'll push a fix of sorts in the next release.

@ammar What problem are you having setting global values? You need to press "Back" after making changes for the values to be saved.

**Comment by skuppa** [comment]
Yes, I am using the environment feature a lot.  I am expecting this will be fixed and released soon.

Thanks.

**Comment by ammar** [comment]
@abhijitkane Sorry, you are correct. I did not click the "Back" button.  So there's a workaround at least.

The only thing that changed, as far as I can tell, is the Chrome version. It is "40.0.2214.91 (64-bit)" now. Same OS and POSTMan versions.

Thanks!

**Comment by paulsperanza** [comment]
Same here. Just noticed it. Bummed!

**Comment by abhijitkane** [comment]
@paulsperanza Do the "Set global/Set environment" menu items not appear after a restart either?

**Comment by paulsperanza** [comment]
No

Paul Speranza

**Comment by abhijitkane** [comment]
On my machine, the menu items appear on restart, and disappear only after I send a request. @shamasis

**Comment by abhijitkane** [comment]
@paulsperanza @ammar @mymuss As a temporary solution, you can run this in your console to re-enable the menus:
`pm.envManager.get("globals").trigger("change");`
We don't know why this happening, though. Will keep this thread updated.

**Comment by ammar** [comment]
@abhijitkane, running that in the console works and it helps a lot.

Out of curiosity I downgraded Chrome, back to version "39.0.2171.95 (64-bit)", and the menus showed up and worked as expected. I hope that helps narrow things down a bit.

Thanks for a great tool!

**Comment by paulsperanza** [comment]
Yes same here. I get the env menu until I do a request.

Paul Speranza

**Comment by dn2k-dev** [comment]
Hi,
same here,
how to you get console for the postman window?

**Comment by abhijitkane** [comment]
Follow the steps at http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/

Right click > Inspect element

We've just pushed a fix. If you have version 1.0.7 (you can check by going to chrome://extensions/, you shouldn't be facing the issue)

**Comment by dn2k-dev** [comment]
Hi,

Working here, Thanks! :)

**Comment by paulsperanza** [comment]
That fixed it for me. Thanks!
 
 
Date: Sun, 25 Jan 2015 05:04:11 -0800
