### ISSUE TITLE
Add the ability to ignore/disable a block of tests at the collection level

### ISSUE THREAD

**Issue by BabaliKumari** [a85/POSTMan-Chrome-Extension#8896]
In my collection, for all the requests I have 3 scenarios:
1.  when the response code is 200 and the response body is not empty.
2.  when the response code is 200 and the response body is empty.
3. When response code is other than 200

For 2nd and 3rd, I have added functions at the collection level and that's working fine.

for the 1st, I want to add a function at the collection level, basically, the function should check if the response code is not  200 then don't executed the block of scripts written at the request level.
The purpose of adding this conditional check (responseCode.code === 200 && jsonData.data.length > 0) at the collection level because I have more than 500 requests in my collection and I don't want to go and add this piece of code in all 500 requests.
And this check is important in this case when the response body is empty and the response code is 200 then it's throwing "Cannot read property '0' of undefined" because the script is trying to validate some elements which are not present in the response body.

I tried so many things but it didn't work out.

Please suggest how we can add a function at the collection level to check if the response code !=200 then skip the whole block of tests written at the request level

**Comment by DannyDainton** [comment]
Hey @BabaliKumari

Thanks for writing in! 🏆

This feels like it's a javascript based question that can be asking in the Postman community rather than a specific issue with the functionality of the app.

Could you raise this as a new topic over on our Postman community fourm, please? 

https://community.postman.com

I'm going to close this issue out for now.

**Comment by mverma-va** [comment]
@BabaliKumari did you find any solution for this, if so, please share link for that.
