### ISSUE TITLE
Is there a way to convert "Timestamp" say "2020-08-06T08:18:12.500Z" to "UTCTimestamp": "1596701892" or Vice versa??

### ISSUE THREAD

**Issue by AvinashBalekundri** [a85/POSTMan-Chrome-Extension#8897]
My postman response body looks something like this:
{
    "GetServerTimeResponse": {
        "Timestamp": "2020-08-06T08:18:12.500Z",
        "UTCTimestamp": "1596701892",
}
}

How to make sure Timestamp and UTCTimestamp are equal? Either I can convert Timestamp to UTCTimestamp and say both strings match or convert UTCTimestamp to Timestamp and say both strings are matching?

In Java langauge, I know this is how we do. But would be interested to know how to do in postman scripts:
			//Verify time
				String timeStamp = new Long(responseType.getTimestamp().getTimeInMillis()/1000).toString();
				String UTCTimestamp = responseType.getUTCTimestamp();
				test.assertValue("TimeStamps are equal", timeStamp, UTCTimestamp);

**Comment by DannyDainton** [comment]
Hey @AvinashBalekundri

This is a great question to post on our community site.

https://community.postman.com 

Could you open up a new thread on there, please?

Going to close this issue as its not specifically a functional issue with the app.

**Comment by AvinashBalekundri** [comment]
Thanks for a quick reply: Created the same in postman community

https://community.postman.com/t/is-there-a-way-to-convert-timestamp-say-2020-08-06t0812-500z-to-utctimestamp-1596701892-or-vice-versa/14809
