### ISSUE TITLE
Authorization and Content-Type headers merged to one line for form-data

### ISSUE THREAD

**Issue by mkeller-ergon** [a85/POSTMan-Chrome-Extension#8899]
**Describe the bug**
I've got a request configured with authentication (Basic auth) and no explicit headers. Body is set to 'form-data'.
The generated request does not put the Content-Type header on its own line but appends it to the Authorize header, this it is useless.

**To Reproduce**
Steps to reproduce the behavior for my exact setup:
1. New POST request to any URL
2. Authorization: Basic Auth with any credentials
3. Headers: empty
4. Body: form-data with any parameter
5. Click on 'Code' to the right

My outcome is:
`POST /bla HTTP/1.1
Host: localhost:8443
Authorization: Basic aW50cm9zcGVjdG9yOmludHJvc3BlY3Rvcl9wYXNzd29yZA==Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x"

d
----WebKitFormBoundary7MA4YWxkTrZu0gW
`
Notice the Content-Type appended to the Authorization header.

**Expected behavior**
The Authorize and the Content-Type header should be on separate lines but they are not.

**App information (please complete the following information):**
 - App Type Postman for Windows
 - Postman Version 7.29.1  win32 10.0.18363 / x64
 - OS: Windows 10 1909

**Comment by shreys7** [comment]
hey @mkeller-ergon, thanks for reporting this issue. Will keep this thread updated with further information.

**Comment by webholik** [comment]
Hey @mkeller-ergon Could you retry this in version 7.36 of Postman App? It is the latest version as of now and I am not able to reproduce this issue there.
