### ISSUE TITLE
Does Interceptor support PUT requests?

### ISSUE THREAD

**Issue by chrismeyersfsu** [a85/POSTMan-Chrome-Extension#890]
Interceptor is not intercepting PUT requests for me. Is this supported?

**Comment by abhijitkane** [comment]
There was a bug in Interceptor which prevented put/patch requests from being intercepted. We'll push a fix soon.

**Comment by abhijitkane** [comment]
@chrismeyersfsu If you use the new versions of Interceptor (0.2.8) and Postman (1.0.7), PUT requests should work.

**Comment by abadyan** [comment]
@abhijitkane I'm using the versions you mentioned and still don't see PUT requests.

**Comment by abhijitkane** [comment]
@abadyan 
This is what I did:
1. Opened Postman, and toggled the interceptor (The traffic light icon should be green)
2. In the interceptor, turned "Request capture" to ON. Set "dump.getpostman.com" as the filter.
3. Navigated to "dump.getpostman.com". Opened the console, and entered the following:
var xhr = new XMLHttpRequest();xhr.open("put","http://dump.getpostman.com/put",true);xhr.send()

4. The PUT request showed up in Postman.

**Comment by abhijitkane** [comment]
Are you sending the request with raw data?

**Comment by abadyan** [comment]
Using your steps I am seeing the put request, but the request I was trying to make was indeed with raw data. Is that the problem?

**Comment by abhijitkane** [comment]
@abadyan There was an issue with raw data capture. This has been fixed in Postman v1.0.8. Can you confirm?

**Comment by abadyan** [comment]
works now, thanks :+1: 
I didn't understand how to update the app so I had to remove it and reinstall, but that's a different issue :)
