### ISSUE TITLE
SSL Certificate Problem: Unable to get Local Issuer Certificate

### ISSUE THREAD

**Issue by duddukurimd** [a85/POSTMan-Chrome-Extension#8900]
We have a shared resource collection that is being used by our team. Till now we are able to hit our applications from Postman, but suddenly one after one resource started getting the below error message while hitting our applications. 

**Error: Unable to get local issuer certificate.**

We need to activate SSL validation for hitting our applications.

**Image 1: even when we have added the valid certificate and correct configuration, getting the below error:** 

<img width="673" alt="postman2" src="https://user-images.githubusercontent.com/22025315/89652369-028a1100-d8e3-11ea-9d1c-e492d67fb668.PNG">

**Image 2: When we diable the SSL validation, getting the below error while hitting our application API's**

<img width="665" alt="postman1" src="https://user-images.githubusercontent.com/22025315/89652371-03bb3e00-d8e3-11ea-8ca7-d1c1cbb6552f.PNG">

Note:  we need a Certificate as part of our request, we have added the necessary certificate details in our local postman and it was working as expected till 2 days back. Suddenly around 4-5 resources started facing the above the mentioned error message while hitting our APIs. For remaining resource who has a similar setup is working as expected and we tried multiple options that we found around Postman forum and no luck in resolving the issue. Now we are worried if all the resources might get impacted due to the same issue. 

Looking for fix on the above request.

**Comment by duddukurimd** [comment]
@DannyDainton any update on the requested details?

**Comment by duddukurimd** [comment]
@codenirvana  Any help here? Now additional 2 resources are facing the same issue.  Now we are worried if it might impact the complete team, your inputs might help us.

**Comment by codenirvana** [comment]
@duddukurimd this error occurs if the issuer certificate is untrusted. Can you share the following details:
* What's the app's version where request fails
* What's the app's version where request pass
* What's the type of client certificate (CRT + KEY or PFX)
* Does it require a CA certificate

**Comment by duddukurimd** [comment]
@codenirvana  


What's the app's version where request fails  -- v7.29.0 and tried till the current latest version v7.30.1
What's the app's version where request pass  --  v7.29.0 and tried till the current latest version v7.30.1 
What's the type of client certificate (CRT + KEY or PFX)   -- Combination of CRT+KEY+PFX
Does it require a CA certificate  -- No

Just to confirm, It was happening for only few resources, and for few resources with the same version and new version all the cases it's working. For now, 7 resources are facing this problem and for remaining it is working properly only.

**Comment by codenirvana** [comment]
@duddukurimd This is weird that on the same version (say `v7.30.1`) a few of your resources are working fine and the rest are facing this issue. This seems like some kind of misconfiguration in either **certificate** or **proxy** configuration (does the request require a proxy setup?).

I recommend you compare the request sent (passed and failed) using the Postman Console to see what's the difference.
![Screenshot 2020-08-13 at 2 14 49 PM](https://user-images.githubusercontent.com/4865836/90113812-80c93600-dd6f-11ea-8c19-1e50a67fb733.png)

**Comment by duddukurimd** [comment]
@codenirvana , settings wise we think it was initialized correctly only. As mentioned earlier for the resources who are currently facing the issue have the postman working for them as expected and suddenly they started getting the issue. 

As suggested above options to check the request in Postman console, Tried validating the request and seems everything is matching and the only difference we see here is they are getting the error message as "Error: Unable to get local issuer certificate." as mentioned in actual description. 

Attaching a sample screenshot for reference. 

**1. The user who is facing the issue postman console.**
<redated>


**2. The user who is not facing the issue postman console:**
<redacted>




If we check both the images, request wise and certificate wise everything matching. Request you to just have a cross-check once from your end as well.

**Comment by DannyDainton** [comment]
The differences I can see are the file paths to the certificate locations - both in terms of names and `/` or `\` 🤔 

Would that cause an issue @codenirvana? Are these paths related to the directory set in the Working Directory?

**Comment by DannyDainton** [comment]
@duddukurimd I removed the images as the _masking_ you used, was not really masking any of those details like the client_id and client_secret. 😬

**Comment by duddukurimd** [comment]
@DannyDainton Sure. Thank you for deleting. 

we are selecting the same certificate, the path would be different but the certificate is the same. The path difference "/" & "\" is populating automatically, we are not selecting manually from the folder. By default when we select the file from the specific folder it was populating like that.

**Comment by Ramya-From-Postman** [comment]
@duddukurimd @DannyDainton 
The path file you see with "/" is a postman normalized file path that we store in order to maintain compatibility between different operating systems for collaboration and this shouldn't be a problem. Please refer to the following thread for more information: https://github.com/postmanlabs/postman-app-support/issues/8852#issuecomment-665603793

**Comment by DannyDainton** [comment]
Hey 👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
