### ISSUE TITLE
Generated cURL commands will produce the error "curl: (3) bad range in URL" if the request contains a bracketed query param key

### ISSUE THREAD

**Issue by mattalexander-pantheon** [a85/POSTMan-Chrome-Extension#8902]
**Describe the bug**

Generated cURL commands will produce the error "curl: (3) bad range in URL" if the request contains a bracketed query param key

**To Reproduce**
1. Go to Postman
2. Create a new Request
3. Set the URL to "http://example.com/endpoint"
4. Add a query param with the key `a[b]`, with no value.
5. Click the "Code" link.
6. Select "cURL" in the left sidebar of the dialog. 
7. Notice the command that's generated (`curl --location --request GET 'http://example.com/?a[b]'`).

**Expected behavior**
Either the command should escape the brackets, or the `--globoff` parameter should be set on the `curl` command.

**Screenshots**
Error that's created:
```
user@host ~ $ curl --location --request GET 'http://example.com/?a[b]'
curl: (3) bad range in URL position 23:
http://example.com/?a[b]
                      ^
```
No error with `--globoff`:
```
user@host ~ $ curl --location --request GET 'http://example.com/?a[b]' --globoff
<!doctype html>
<html>
<head>
    <title>Example Domain</title>
[...]
```

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.29.1
 - OS: macOS Catalina 10.15.6 (19G73)

**Comment by DannyDainton** [comment]
Hey @mattalexander-pantheon 

When using `Import` > `Raw Text`, this command will create the request `curl -X GET 'http://example.com/?a[b]'`. 

This is the Postman code snippet output created when I manually crafted the request in the UI.

Would you be able to provide a screenshot of the code snippet produced in the app and which settings for that language have been applied?

**Comment by mattalexander-pantheon** [comment]
Screen recording:

[Screen Recording 2020-08-09 at 8.27.27 PM.mov.zip](https://github.com/postmanlabs/postman-app-support/files/5048742/Screen.Recording.2020-08-09.at.8.27.27.PM.mov.zip)

Settings:

<img width="727" alt="Screen Shot 2020-08-09 at 8 31 06 PM" src="https://user-images.githubusercontent.com/52413912/89746477-719c6c80-da7f-11ea-8a6b-290fdbbead64.png">

**Comment by DannyDainton** [comment]
Hey @mattalexander-pantheon,

I'm still not sure that I understand _what_ the issue is that you're seeing. 

I'm using a different endpoint here but sill using the same `?a[b]=foo` query param that you used in the video. I've created the request in the app and use the code generator with the same setting. 

![Screenshot 2020-08-10 at 09 38 02](https://user-images.githubusercontent.com/17089546/89764971-56684600-daed-11ea-9817-b153db3b1eea.png)

When running this command from the terminal, it's not throwing the error and is creating that nested query param I specified:

![Screenshot 2020-08-10 at 09 36 10](https://user-images.githubusercontent.com/17089546/89765191-c080eb00-daed-11ea-8bfb-230bb3ff3db2.png)

Even if I use _example.com_ - It's returning a different error message:

![Screenshot 2020-08-10 at 09 54 20](https://user-images.githubusercontent.com/17089546/89766200-b52ebf00-daef-11ea-874e-743239be551d.png)

**Comment by mattalexander-pantheon** [comment]
@DannyDainton Not sure how else I can help, but let me know if you want me to take a look at anything for you.

**Comment by DannyDainton** [comment]
I followed your steps and I'm not seeing the same thing, are you seeing this error when creating a code snippet from `https://postman-echo.com/get?a[b]=foo`

The site you're using is to show the issue is an example domain. Are you also seeing the issue when using this against a public API or one there you're currently developing?

**Comment by mattalexander-pantheon** [comment]
Used your URL, same result:

[Screen Recording2 2020-08-10 at 1.28.56 PM.mov.zip](https://github.com/postmanlabs/postman-app-support/files/5052655/Screen.Recording2.2020-08-10.at.1.28.56.PM.mov.zip)

**Comment by DannyDainton** [comment]
Not really sure where to go from here, you can see in the command line image above, with the same request, that it's working. 🤔

The only other differences are between our two terminals or versions of OS. 

Is the same curl request failing when entered manually (not copy and pasted) straight into your terminal? 

Postman isn't doing any magic, it's just crafting the command. 😁

**Comment by mattalexander-pantheon** [comment]
I typed these commands in manually:
```bash
user@host ~ $ curl --location --request GET 'https://postman-echo.com/get?a[b]=foo'
curl: (3) bad range in URL position 32:
https://postman-echo.com/get?a[b]=foo
                               ^
user@host ~ $ echo $0
/bin/zsh
user@host ~ $ bash -c "curl --location --request GET 'https://postman-echo.com/get?a[b]=foo'"
curl: (3) bad range in URL position 32:
https://postman-echo.com/get?a[b]=foo
                               ^
user@host ~ $ bash -c "curl --location --request GET 'https://postman-echo.com/get?foo=bar'"
{"args":{"foo":"bar"},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-5f31aa46-ad9202f4f1f0de6a528d547c","user-agent":"curl/7.71.1","accept":"*/*"},"url":"https://postman-echo.com/get?foo=bar"}
```
Only the prompts have been altered in this output. I tested in iTerm2 and Terminal on macOS.

> Postman isn't doing any magic, it's just crafting the command.

Whoops, didn't need the second screencast since your command is the same.

**Comment by SabriH10** [comment]
Hi @mattalexander-pantheon, I too, was unable to reproduce this issue. Judging by https://stackoverflow.com/questions/8333920/passing-a-url-with-brackets-to-curl, this seems to be an issue with cURL and globbing but outside of Postman. Not quite sure what the exact root cause is here but could be the cURL version you are using? I also tested in iTerm2 and was unable to reproduce this on my end.

**Comment by SabriH10** [comment]
Hey @mattalexander-pantheon, following my previous comment, I'll go ahead and close out this issue. Feel free to reach out if you have any other questions or concerns.

**Comment by gimansour** [comment]
Hey @SabriH10 , @DannyDainton ,

I found something that might be relevant to this conversation. Not necessarily a bug in Postman, but curl is somehow misinterpreting the curl request when there is a [] with a - between them

here is my example: 
``` 
curl --location --request GET 'https://postman-echo.com/get?a[A-ID]=123'

curl: (3) bad range in URL position 32:
https://postman-echo.com/get?a[A-ID]=123 
```

while:

```
curl --location --request GET 'https://postman-echo.com/get?a[A-ID]=123' -g
{"args":{"a":{"A-ID":"123"}},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-5fad57d3-2acec88a495727cd1ad201ca","user-agent":"curl/7.64.1","accept":"*/*"},"url":"https://postman-echo.com/get?a[A-ID]=123"}
```

you can see the first one is failing because the -g flag is not set while the second one works because the -g flag is provided.

if a[A-B] is provided as the key you can see curl is interpreting this as 2 requests
```
curl --location --request GET 'https://postman-echo.com/get?a[A-B]=123'   

[1/2]: https://postman-echo.com/get?aA=123 --> <stdout>
--_curl_--https://postman-echo.com/get?aA=123
{"args":{"aA":"123"},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-5fad5959-2ebb7c3902d8fc93261f0097","user-agent":"curl/7.64.1","accept":"*/*"},"url":"https://postman-echo.com/get?aA=123"}
[2/2]: https://postman-echo.com/get?aB=123 --> <stdout>
--_curl_--https://postman-echo.com/get?aB=123
{"args":{"aB":"123"},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-5fad5959-7617a3e17c131a540d318d8a","user-agent":"curl/7.64.1","accept":"*/*"},"url":"https://postman-echo.com/get?aB=123"}
```

I'm using this version of curl :
```
curl -V
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

```

**Comment by mattalexander-pantheon** [comment]
Here's my macOS Catalina 10.15.6 (19G73) again:

```
user@host ~ $ curl --location --request GET 'https://postman-echo.com/get?a[A-ID]=123'
curl: (3) bad range in URL position 32:
https://postman-echo.com/get?a[A-ID]=123
                               ^
user@host ~ $ curl --version
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

**Comment by mattalexander-pantheon** [comment]
Here's a linux machine with curl 7.40.0 with a somewhat different error:

```
user@host ~ $ curl --location --request GET 'https://postman-echo.com/get?a[A-ID]=123'
curl: (3) [globbing] unmatched close brace/bracket in column 36
user@host ~ $ curl --version
curl 7.40.0 (x86_64-redhat-linux-gnu) libcurl/7.40.0 NSS/3.21 Basic ECC zlib/1.2.8 libidn/1.32 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets Metalink
user@host ~ $ cat /etc/redhat-release
Fedora release 22 (Twenty Two)
```

**Comment by mattalexander-pantheon** [comment]
Perhaps you could just add the `--globoff` parameter so that all curl versions are supported. Both my Mac and Fedora machines work when I add `--globoff`.

**Comment by nbeuchat** [comment]
The `--globoff` did the trick for me. I had the same problem when running:
```
curl -X DELETE 'https://graph.facebook.com/v10.0/me/custom_user_settings?psid=53xxxxxx&params=[%22persistent_menu%22]&access_token=EAAExxxxx'
```

OS: `Ubuntu 18.04.5 LTS`, 64-bit. 
```
nicolas@nicolas-neo-ubuntu:~$ curl --version
curl 7.65.2 (x86_64-conda_cos6-linux-gnu) libcurl/7.65.2 OpenSSL/1.1.1c zlib/1.2.11 libssh2/1.8.2
Release-Date: 2019-07-17
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by steve-todorov** [comment]
I had the same issue.

```
$ curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

$ curl -L -O "https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=681&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=5325072e9faa48b58faa41d0e6f5ea83"
curl: (3) bad range in URL position 144:
https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=681&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=5325072e9faa48b58faa41d0e6f5ea83

```

Adding `--globoff` does seem to work. Although I don't know why you'd need to add this flag for something that's standard.

```
$ curl -L --globoff -O "https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=681&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=5325072e9faa48b58faa41d0e6f5ea83"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1070M  100 1070M    0     0  22.6M      0  0:00:47  0:00:47 --:--:-- 23.5M
```
