### ISSUE TITLE
postman.getResponseCookie(“csrftoken”).value undefined

### ISSUE THREAD

**Issue by huan415201** [a85/POSTMan-Chrome-Extension#8903]
**Describe the bug**
postman.getResponseCookie(“csrftoken”).value returned "undefined"

**To Reproduce**
1. I was able to use it at first
2. Log out
3. Log in again
4. Bug happen

**Expected behavior**
postman.getResponseCookie(“csrftoken”).value return a new cookie as before

**Screenshots**
![image](https://user-images.githubusercontent.com/43948939/89724112-3ec78980-da29-11ea-82cc-6f04ed751dc2.png)

**App information (please complete the following information):**
 - App Type: python backend django
 - Postman Version: v7.29.1
 - OS: Windows 10 Pro

**Comment by codenirvana** [comment]
@huan415201 When you log out, all your locally stored cookies get cleared as well.

**Comment by huan415201** [comment]
> @huan415201 When you log out, all your locally stored cookies get cleared as well.

So how can I acquire a new one?  I thought that the script will auto generate a new cookie if the stored one get cleared

**Comment by DannyDainton** [comment]
Hey @huan415201 

As this has also been raised as a question over on our community site, I'm going to close this issue and a track the conversation there.
