### ISSUE TITLE
List of examples is not scrollable on Mac. (missing the scrollbar)

### ISSUE THREAD

**Issue by ddeleur** [a85/POSTMan-Chrome-Extension#8906]
**Description**
The user is blocked from accessing all examples when the example list for a request is pretty big. The scrollbar does not appear.

**To Reproduce**
1. Go to any request from the collection. The request should contain a bunch of examples (30+)
2. Click on Examples button
3. Scroll down to the last item in the examples list

**Expected behavior**
The examples list should be scrollable (scrollbar should appear). User should be able to access the last in a list example

App information:
 - Native App
 - Postman Version 7.29.1 
 - OS: macOS Catalina 10.15.6

**Comment by mohitranka** [comment]
Hey @ddeleur , Thanks for reporting - We’ll update the issue when we have more information
