### ISSUE TITLE
Keyboard shortcut broken v7.30.0

### ISSUE THREAD

**Issue by Satheskumar89** [a85/POSTMan-Chrome-Extension#8909]
Version - v7.30.0
OS - Windows 10

Issue - Shortcut to send request not working as expected in combination with Next item (down arrow) and Previous item (up arrow) shortcut.

Steps to recreate:
1. in an collection with multiple request press down arrow to navigate to next request
2. Press Ctrl+Enter to send request
3. Press down arrow
4. Press Ctrl+Enter (not working) or press down arrow again (not working)

**Comment by sujayvenaik** [comment]
@Satheskumar89 Hey, we can reproduce the issue at our end and seems like a regression that happened in v7.30.0 (stable build). We would be rolling out a fix soon.

I'll keep this thread updated once the fix is rolled out. Thanks for reporting.

**Comment by sujayvenaik** [comment]
@Satheskumar89 We pushed out a fix for this in v7.30.1. You could update your app and should work as expected.

Feel free to reply to this thread if you still face issues regarding this issue.

**Comment by Plinqy** [comment]
@Satheskumar89 Issue is occurring again.

On Mac Command-enter does NOT submit again. v8.0.5
OS Catalina 10.15.7

**Comment by Plinqy** [comment]
@sujayvenaik sujayvenaik @Satheskumar89 Command-Enter not working again.

Also, Command-W is not closing tabs.

**Comment by timbochamp** [comment]
Hi @Plinqy , this sounds similar to #9528 if you want to follow the resolution there? This should hopefully be addressed in our next update. For now, restarting the app or using Postman for Web are possible workarounds.
