### ISSUE TITLE
'Refused to set unsafe header' - interceptor installed

### ISSUE THREAD

**Issue by NielsRak** [a85/POSTMan-Chrome-Extension#891]
I need to send requests including restricted headers like Cookie, Host. I've seen http://www.getpostman.com/docs/requests on restricted headers. Interceptor is installed (but not on, as per doc?) 0.2.8 according to Chrome. Using Postman packaged app 1.0.7.

Chrome dev tools console explicitly complains about the headers:

![image](https://cloud.githubusercontent.com/assets/10673501/5898819/4ae5ea4a-a54b-11e4-84f2-35f2403363d3.png)

Not sure if relevant, but the only other error in console is:
![image](https://cloud.githubusercontent.com/assets/10673501/5898837/6eb53890-a54b-11e4-9e45-7a3ffb6cd02c.png)

For completeness, I also reported an issue with the Send button event handler - I'm using the fix mentioned in this thread, to re-attach the handler:

https://github.com/a85/POSTMan-Chrome-Extension/issues/712

**Comment by abhijitkane** [comment]
You need to click on the interceptor icon in Postman (traffic light icon in the top right) to route requests through the interceptor.

**Comment by NielsRak** [comment]
Oh, OK, misunderstood the doc - it says you should toggle 'again' but presumably that's if you've just installed it, to turn it on. Not to turn it back off again. Sorry.
