### ISSUE TITLE
while sending request through postman i am getting invalid request though my request is valid. Anyone faced this type of issue, please give your advice.

### ISSUE THREAD

**Issue by jassubhai** [a85/POSTMan-Chrome-Extension#8914]
<HTML><HEAD>
<TITLE>Invalid URL</TITLE>
</HEAD><BODY>
<H1>Invalid URL</H1>
The requested URL "&#91;no&#32;URL&#93;", is invalid.<p>
Reference&#32;&#35;9&#46;78762c31&#46;1597151599&#46;16e860e1
</BODY></HTML>

**Comment by DannyDainton** [comment]
Hey @jassubhai 

This seems like a question that is better placed on our community forum, could you please open up a new topic?

https://community.postman.com/

When raising the question, can you ensure that you're giving people the best opportunity to help by providing more context and detailed information about what you're facing?

Images and some environmental information will help too.

**Comment by orestborovets** [comment]
Make sure you turned on all hidden auto-generated headers at `Headers` tab
