### ISSUE TITLE
Can't change http method for requests

### ISSUE THREAD

**Issue by ckjet** [a85/POSTMan-Chrome-Extension#8915]
Version: 7.30.1

If I change http method to any another then get server show error 405: method not allowed, only post allowed. How can I change method to post?

**Comment by DannyDainton** [comment]
Hey @ckjet 

Would you be able to provide a recording or some screenshots of what you're seeing, please? 

Without more details about what's going on, it's going to be difficult to suggest a possible solution.

**Comment by ckjet** [comment]
https://ibb.co/J2dxTZM3

**Comment by ckjet** [comment]
Problem was detected in redirects. Request was redirected to https and in this process I think something lost (headers or data)

**Comment by DannyDainton** [comment]
It sounds like you've found the issue? Are we good to close this now?

**Comment by ckjet** [comment]
Yes, thank you.
