### ISSUE TITLE
Unable to resolve canned dynamic variables

### ISSUE THREAD

**Issue by marzolfb** [a85/POSTMan-Chrome-Extension#892]
I can't seem to resolve any of the canned dynamic variables ({{$guid}}, {{$timestamp}}, {{$randomInt}}) when plugging them into any of the dynamic variables in a JSON string using a raw form POST. For example:

{ "blah" : "{{$randomInt}}" } 

I can put my own variables in my own environment and they will get resolved but not the canned ones. 

I've tried different variations of the variable syntax with no luck. Looked at the PR where the functionality was introduced and that didn't help. I have not changed my delimiter from the default "{{..}}" in the settings.

Are there any troubleshooting steps that are helpful here?

This must be an environment thing for me because I don't see anything here on Github or elsewhere with anyone else having this issue.

**Comment by abhijitkane** [comment]
Can you import this collection and check if it works for you (there's a test included in the request):
https://www.getpostman.com/collections/f585c83e6d768f4bb612

If not, follow the steps at http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/, and check if there are any error messages in the console.

**Comment by marzolfb** [comment]
Imported the collection and the test didn't resolve the dynamic variables. Enabled developer tools and saw no errors in the console. Doing some debugging to see if I can figure out where I'm having issues...

**Comment by abhijitkane** [comment]
What version of Postman are you on?

**Comment by marzolfb** [comment]
Embarrassingly, I was using the old non-packaged version (0.8.4.12). When I switched to the latest packaged version (1.0.7), everything is being resolved as expected. I didn't realize the documentation was targeted to the newer packaged app but that makes sense now.

Thanks for your quick help on this!
