### ISSUE TITLE
Postman couldn't connect to the internet

### ISSUE THREAD

**Issue by erlendl** [a85/POSTMan-Chrome-Extension#8921]
**Describe the bug**
Postman desktop client (Mac) reports "Postman couldn't connect to the internet". 
![Screenshot 2020-08-12 at 11 23 06](https://user-images.githubusercontent.com/2368574/89998930-708d5a00-dc8e-11ea-8a1d-d3f1ea37e655.png)

I am successfylly authenticating with "Sign in with Google". All request succeeds. All other internet activity works as expected from the computer. Hence, the internet connection is up and running, but Postman is not able to connect to its cloud services and sync workspaces.

**To Reproduce**
1. Start Postman and sign in
2. Observe sync button in toolbar is red
3. Click browse in bottom toolbar
4. Postman states "Looks like you're offline"

**Expected behavior**
We expect Postman to be online with its cloud services and sync successfully.

**Screenshots**
The console viewed from menu item "Developer | Show Dev Tools (Shared)" shows an error "Failed to load resource: net: ERR_CER_COMMON_NAME_INVALID"
![Screenshot 2020-08-12 at 11 30 47](https://user-images.githubusercontent.com/2368574/89999771-936c3e00-dc8f-11ea-95cb-c749c912a0be.png)

![Screenshot 2020-08-12 at 11 43 07](https://user-images.githubusercontent.com/2368574/90000910-0d50f700-dc91-11ea-8210-47dee884939d.png)

**App information (please complete the following information):**
 - Desktop app for Mac
 - Postman Version 7.30.1 and PostmanCanary 7.30.0-canary02
 - OS: macOS Catalina 10.15.5

**Additional context**
From the developer console log it seems that the request to https://bifrost-v4.getpostman.com/ws/connect fails due to an invalid certificate. When the URL https://bifrost-v4.getpostman.com/ws/connect is put in Safari, Safari reponds with this message.
![Screenshot 2020-08-12 at 11 55 54](https://user-images.githubusercontent.com/2368574/90002319-cc59e200-dc92-11ea-96dd-68c4963f7c0f.png)

Chrome agrees with certificate problems:
![Screenshot 2020-08-12 at 11 56 34](https://user-images.githubusercontent.com/2368574/90002468-fa3f2680-dc92-11ea-87ea-8d7ab8cd547c.png)

Old Postman Chrome Extensions successfully connects with an enabled sync button, but workspaces are upgraded to newer versions and does not work with the extension.

**Comment by DannyDainton** [comment]
Hey @erlendl 

That's interesting? I'm not seeing this on my side for either the Production or Canary app. 🤔  

Hate to be that guy...have you tried quitting the app and restarting it again to try and establish the connection?

Are you currently on a VPN, behind a firewall or using some sort of proxy on your machine?

You could head over to web.postman.co and use Postman's web version to see if that's going to unblock you in the short term?

**Comment by erlendl** [comment]
> Hey @erlendl
> 
> That's interesting? I'm not seeing this on my side for either the Production or Canary app. 🤔
> 
> Hate to be that guy...have you tried quitting the app and restarting it again to try and establish the connection?
> 
> Are you currently on a VPN, behind a firewall or using some sort of proxy on your machine?
> 
> You could head over to web.postman.co and use Postman's web version to see if that's going to unblock you in the short term?

Hi @DannyDainton 

Thanks for your reply.

I have done the basics - and then some :-). Quitted app, updated to latest version, unistalled and installed multiple times, restarted pc and so on.
I am not on a VPN, do not use any sort of proxy but is behind a standard router firewall which is not configured besides ordinary configurations. 
I haven't noticed that there are any requirements to open any special ports in firewall for Postman (?).

I have already used web.postman.co as a workaround - thanks for the tip.

**Comment by erlendl** [comment]
I updated firmware on the router, and the certificate error accessing https://bifrost-v4.getpostman.com/ws/connect is no gone. This case may be closed.

**Comment by DannyDainton** [comment]
So you're all good and running on the native app now?

**Comment by DannyDainton** [comment]
I'm going to close this for now.

If you run into any other Network issues, you can open a support ticket and send logs/a network profile to help@postman.com, so we can look further into the issue. 😄

**Comment by mendozagit** [comment]
Same issue on windows staring from yesterday 20/10/2025 



<img width="1282" height="803" alt="Image" src="https://github.com/user-attachments/assets/23bb81c2-7c4b-4e86-a7b3-36d0dff489b9" />
