### ISSUE TITLE
RawRequestWithText is not supported properly

### ISSUE THREAD

**Issue by ritika50** [a85/POSTMan-Chrome-Extension#8923]
When you will import Collection file with Raw request(Text);data options are null.
When you select some other option(say JavaScript/HTML) and then reselect 'text' option at that time  data options have proper data.

**Comment by DannyDainton** [comment]
Hey @ritika50 

Thanks for writing in! 🏆 

In order for us to begin to debug any potential issues, we will need to be able to reproduce it locally. Could you provide us with the following information, please?

- Full steps to reproduce the issue
- Screenshots or a recording of the issue
- Environmental information:
  - Postman Version
  - OS
- Any additional context that might be important/relevant 

The more details that you can provide, the easy it will be for us to help with a solution.

**Comment by DannyDainton** [comment]
Hey @ritika50 

I'm going to close out this issue due to a lack of information, we can look to open it up again if we receive these details.

**Comment by ritika50** [comment]
Hi Danny ,

The Issue is  -

1.Go to Postman
2.Click on Body section>>raw -Text (See screenshot)
3.Provide Text as  'Hello  world'
4.Now go to Settings >>Data-Download only my data (This file will be saved
on your system as Json file)
5.Open this Json file (Check Req5-Data option is Null even when data is
entered) -See Screenshot

It means save is not working properly
--

**Comment by DannyDainton** [comment]
Could you confirm that you're saving the request after you have entered "Hello World"?

I followed your step, the first time I didn't save the changes and the text was not in the data download. I then followed the steps again but saved the changes before downloading the data, this time the "Hello World" text was in the downloaded file.

The screenshots are not coming through with your message so I'm unable to see those.

**Comment by ritika50** [comment]
Yes,I am saving that Text But still 'Data Option' is null.
Please see screenshot.

I am very much sure that this is defect.

**Comment by DannyDainton** [comment]
We cannot see any of the screenshots that you're sending.

If you're replying via an email client, that might be this issue. Could you go to Github from a Web browser and attach the files please.

**Comment by ritika50** [comment]
This Issue is resolved -When I am selecting some other option than
Text(say javascript)-Save it
and then again  Select Text  and save it-Then Import that file and
check data option -It is not null.

**Comment by ritika50** [comment]
![dataPotionNullJson](https://user-images.githubusercontent.com/69587412/90519863-39cfac00-e186-11ea-9bb9-3f40053d74fc.png)
![ReselectText](https://user-images.githubusercontent.com/69587412/90519887-418f5080-e186-11ea-8d63-6ec7b47da7b6.png)

**Comment by ritika50** [comment]
save button is not working properly in case of 'raw Request With text'

**Comment by ritika50** [comment]
![image](https://user-images.githubusercontent.com/69587412/90520403-ead64680-e186-11ea-918e-f7753bdba7ff.png)

**Comment by ritika50** [comment]
let me know If needs more Info

**Comment by DannyDainton** [comment]
Can you provide a scaled-down collection showing the issue, please?

It's becoming difficult to piece together what's going on with all the individual messages, could you collate them all together and provide a single description of the problem, please.
