### ISSUE TITLE
app freezing

### ISSUE THREAD

**Issue by NadaBahaa** [a85/POSTMan-Chrome-Extension#8926]
the app freezes after running any api

**Comment by DannyDainton** [comment]
Hey @NadaBahaa 

Could you provide us with the following information, please?

- Full steps to reproduce the issue
- Screenshots or a recording of the issue
- Environmental information:
  - Postman Version
  - OS
- Any additional context that might be important/relevant

The more details that you can provide, the easy it will be for us to help with a solution.

**Comment by DannyDainton** [comment]
Hey @NadaBahaa 

I'm going to close out this issue due to a lack of information, we can look to open it up again if we receive these details.
