### ISSUE TITLE
Snippets panel on "Pre-requsest Script" extends off screen

### ISSUE THREAD

**Issue by Zinnurka** [a85/POSTMan-Chrome-Extension#8927]
**To Reproduce**
1. Go to 'Pre-request Script'
2. Emphasize on Snippet

**Screenshots**
![bug](https://user-images.githubusercontent.com/21366/90092931-7498a500-dd7e-11ea-9351-a433ab61fc79.gif)

**App information (please complete the following information):**
 - App Type [Windows]
 - Postman Version [e.g. 7.30.1]
 - OS: [Windows 10]

**Comment by DannyDainton** [comment]
Hey @Zinnurka 

Thanks for writing in! 🏆 

I was able to recreate the issue with the following steps
- Open a new request
- Close the `pre-request` snippet and move to the `tests` tab
- Open the snippet on the `tests` tab and then switch to the `pre-request` tab

![snippet_issue](https://user-images.githubusercontent.com/17089546/90106090-d3d6c500-dd3e-11ea-8225-8c76a036a537.gif)

**Comment by xk0der** [comment]
@DannyDainton great find! :100:

I was able to apply your steps and reproduce the issue in reverse as well, reproducing the issue when switching to "`Test`" tab.

* Open a request (New or existing)
* Switch to "`Test`" tab close the snippet pane
* Switch to "`Pre-request Script`" tab and  open snippet pane
* Switch to "`Test`" tab, and see the snippets pane pushed out the right edge

![gh8927](https://user-images.githubusercontent.com/21366/90118394-47fb8200-ddac-11ea-989d-50b84d2bdd63.gif)

**Comment by timbochamp** [comment]
Hi @Zinnurka, this should now be resolved with our latest Postman version 8 app release, as well as on Postman for Web! I'm going to close out this issue, but please feel free to reopen if you're still encountering this issue after updating.
