### ISSUE TITLE
Ability to stop a request from executing using a command in the Pre-request script

### ISSUE THREAD

**Issue by nolimitdev** [a85/POSTMan-Chrome-Extension#8929]
In many other softwares pre-request script usually can stop continuing main operation. Such as in git pre-commit script we can stop commit operation if we want, what is expected. But in postman pre-request script we can not stop request which is illogical. So postman pre-request script does not use its potential. I have found several years old fallback by throwing error but it is not good solution because in collection runner there are many red lines.

I have data file with e.g. 30 iterations but I do now want to run each iteration for each request. Some request are simple so I can not write 30 alternatives of variable value. SO I would like to add conditions in some requests... e.g. pseudo code... 
`if (pm.info.iteration > 10)
  pm.request.stop() // or pm.request.skip()`

Is it hard to add this feature? Is it planned samewhen?

**Comment by jency26** [comment]
Is this in-progress of development?

**Comment by abeward** [comment]
Have you tried seeing if you can modify/use the test method that stops subsequent requests from running in runner? Example from a test I use to stop subsequent requests from being executed in a runner folder/collection if one of the dependency requests fail:

```
pm.test("Response is a 200 Success", function () {
    postman.setNextRequest(null);
    pm.response.to.have.status(200);
    //  alt: pm.expect(pm.response.code).to.equal(200); 
    postman.setNextRequest();
});
```

I'd think you could swap out pm.reseponse.to.have.status(200); to use a loop, no? I'm a beginner when it comes to programming, but something to chew on while you await a pm.response (pun intended).

**Comment by vali-craciun** [comment]
> Have you tried seeing if you can modify/use the test method that stops subsequent requests from running in runner? Example from a test I use to stop subsequent requests from being executed in a runner folder/collection if one of the dependency requests fail:
> 
> ```
> pm.test("Response is a 200 Success", function () {
>     postman.setNextRequest(null);
>     pm.response.to.have.status(200);
>     //  alt: pm.expect(pm.response.code).to.equal(200); 
>     postman.setNextRequest();
> });
> ```
> 
> I'd think you could swap out pm.reseponse.to.have.status(200); to use a loop, no? I'm a beginner when it comes to programming, but something to chew on while you await a pm.response (pun intended).

I think the feature refers to skip current request, not the subsequent ones

**Comment by Sophos06** [comment]
> Is it hard to add this feature? Is it planned samewhen?

I don't think so. At pre-request script stage, the body is not even sent.
Should be easy to jump straight to end of test script stage on a certain command.

**Comment by jeremymurray** [comment]
An example of where this would be super useful: we have tests in subfolders that require logins to have occurred.  If we could put a login request in each folder but use a pre-request script to check if the local token variable had already been set (from a previous login in a different folder when running the full collection), we could skip unnecessary logins.  Would give the flexibility of running any folder's tests ad-hoc while saving a bunch of time on the full collection run.

**Comment by chrisj-td** [comment]
I would definitely love to see this feature in Postman. Currently, I don't see a neat way to skip the first request in the runner. At least not with the `postman.setNextRequest()`. The only possible solution I could think of is either delete the first request (this I would want to avoid) or put it as a second request and jump to third from the first request. However, I feel this is more like a workaround.

**Comment by Conjuror** [comment]
+1, it would be lovely if we can make some check before executing. While we are iterating the tests, some combinations may not be applicable. In the case, it will be easier to simply drop than executing and mark them as accepted.

**Comment by saiudayakella** [comment]
+1, this is a good feature. Currently, we cannot stop sending the current request even if some criteria fails in preconditions

**Comment by Gaboxondo** [comment]
+1, this will be very usefull depending on the environment selected, for example to execute test in local maybe you dont need a token but you need it in develop environment

**Comment by wiczit** [comment]
+1

**Comment by iamsush** [comment]
+1, this request is very much in demand. @postman-support Please have a look.

**Comment by ShyanFung** [comment]
+1. I've tried throwing an Error in the pre-request script to get the iteration to skip and it works for a small set, but it eventually crashes postman after it runs about 100+ iterations.

**Comment by petelah** [comment]
+1 to this functionality please

**Comment by NRam0s** [comment]
+1

**Comment by gen1321** [comment]
+1

**Comment by maraby777** [comment]
+1

**Comment by pwhty** [comment]
+1

**Comment by leitste1** [comment]
+1

**Comment by stephengaudet-textiq** [comment]
+1

**Comment by johannsmit** [comment]
+1

**Comment by Hima2021-rajesh** [comment]
+1

**Comment by jjduarte** [comment]
+1

**Comment by Preethiy** [comment]
+1

**Comment by tammarut** [comment]
+1 🆙 
We want these features!

**Comment by rdelmont** [comment]
+1

**Comment by beckerp86** [comment]
+1

**Comment by lucaslov** [comment]
+1

**Comment by Shubham-Kumar-2000** [comment]
+1

**Comment by tinder-andresruizvelediaz** [comment]
+1

**Comment by OguzhanUlucay** [comment]
+1

**Comment by matrixzj** [comment]
+1, please

**Comment by andekis** [comment]
This is basic and essential, please add it.

**Comment by vonckm-kadaster** [comment]
+1 please :)

**Comment by DLTKLukaszKaldunski** [comment]
+1, please

**Comment by lovelycas** [comment]
+1 :)

**Comment by SusenaP** [comment]
Is it developed? When it will be available?

**Comment by malvikach** [comment]
We have taken note of this feature request. I agree this would be helpful. However, we do not have ETA on this to share yet. 

I can suggest the below-mentioned workaround for the time being: 

> I would definitely love to see this feature in Postman. Currently, I don't see a neat way to skip the first request in the runner. At least not with the `postman.setNextRequest()`. The only possible solution I could think of is either delete the first request (this I would want to avoid) or put it as a second request and jump to third from the first request. However, I feel this is more like a workaround.

**Comment by andekis** [comment]
@malvikach I don't see how this solution helps to skip the request being sent if some condition in pre-request script is not fulfilled.

For example, I have 30 requests in my collection.
In pre-request script of every request I want to check the value of a global variable, and do NOT send the request if that variable equals null (meaning that the request is fully skipped - not sent to the server, and post-request tests not run).

How can I do this using that workaround?

**Comment by malvikach** [comment]
@andekis Agreed! A scenario like the above might be difficult to fulfill using the workaround. It would work best for skipping one or two requests or similar limited scopes. 

For multiple requests, it has to be a simpler experience. I will get back with updates on this thread.

**Comment by atif-ali** [comment]
+1

**Comment by thanhnq-ja** [comment]
+1

**Comment by umesh-swamidas** [comment]
+1. This should be a basic feature to have in the first place.
Thanks to the whole postman team for supporting such a wonderful tool.

**Comment by tenglish61** [comment]
+1 please :)

**Comment by ThaGeege** [comment]
Its not just a great feature Im shocked its not available. So many basic things are complicated without it and we have to find workarounds. Most basic common example ever:

Loop through a CSV and perform some rest api call every iteration. 
- First script is a call to a /token endpoint to get an oauth token. 
- Second script calls some api method.

I dont want to generate a new token every time so need some basic simple way to skip it. I originally thought I would just check in the first script pre-request if a collection variable is set but its pointless since you cant skip the request.

- putting setNextRequest(null) makes the entire execution stop
- putting setNextRequest("script_2") still execute the token request in step 1

+1 million for a common sense basic feature that needs to be there

**Comment by blindstuff** [comment]
+1 with how complete Postman is I'm surprised this isn't an option

**Comment by TLYoz** [comment]
+1 The proposed work around is truly awful.

**Comment by BlackGad** [comment]
Any chance that this feature will become available?) Or it is just placeholder for random complains?

**Comment by xxldoctor** [comment]
> @malvikach I don't see how this solution helps to skip the request being sent if some condition in pre-request script is not fulfilled.
> 
> For example, I have 30 requests in my collection. In pre-request script of every request I want to check the value of a global variable, and do NOT send the request if that variable equals null (meaning that the request is fully skipped - not sent to the server, and post-request tests not run).
> 
> How can I do this using that workaround?

@andekis not sure if it work, but maybe you can put some condition at the end of "Tests" block of previous request and use postman.setNextRequest() there? In this case next request(s) could be fully skipped, I guess.

**Comment by hurrycaner** [comment]
This feature request made 2 years anniversary... looks like this thread is not being considered for any development roadmap... sad

**Comment by m-buecher** [comment]
+1

@xxldoctor This here is about a different functionality. .setNextRequest() is just an ugly workaround to get a .skipRequest().

I want to skip the current request and not define the next request. Whenever something changes the order of requests inside the collection (e.g. new requests, delete requests, re-ordering requests), then the workaround with .setNextRequest() may fail.
You always have to maintain the script of the "previous" request instead of the script of the actual request it is relevant for.
With .skipRequest() I maintain the pre-script in a request only once and no matter how the collection changes it will still be skipped.
It just like using "continue" in a loop.

Should be there from day 1, but still not in Postman after years (decades?)

**Comment by JSSAggie** [comment]
Just curious what the hold up on this is?  I feel like I search for a solution every month or so and reach a dead end on the GitHub issue.  I feel like this is a valuable feature request for when writing scripts in postman.

**Comment by sgperlman** [comment]
+1
It should not be difficult to add an event to the pm class that does the same thing as the user click on the "cancel" button to cancel the current request. Kind of disappointing that this is now over 2 years on the wish list!

**Comment by JavierPDev** [comment]
+1
Looking to use this proposed feature for a "speed test" collection where we don't actually want to keep downloading from the endpoint for more than a few seconds, but still want the request to pass.

**Comment by adammerk** [comment]
+1 Still so many people looking forward for this feature to come. Give it a go 👍

**Comment by maxlinux** [comment]
+1 Please, to be a professional test tool, listen to the professionals.

**Comment by thallbeck** [comment]
+1 it's been 5 years, can't be that hard. I charge $65/hr, I'll do it. 
Requirement: implement pm.skipRequest(), usable in the Prerequest or Test section, which immediately exits the current request and moves on to the next one. 
text only anytime: four oh eight  three four eight   four four two nine
Timmeh in Kentucky

**Comment by BrianWatson-PT** [comment]
Looks like I'm not alone in wanting a feature like this.  Maybe someday?!?!

**Comment by nekszt** [comment]
## Postman team is dead ?
> So many people need it but it's so overlooked

Is it useful to report things here @postman-support ?

Simple case:
I need to build the request in the pre-request script and in some case I want to skip the request because it's not fulfillable.

**It's a bug** not a feature request (https://learning.postman.com/docs/running-collections/building-workflows/#use-setnextrequest-in-pre-request-or-test-scripts)
Wake up @postman-support

@codenirvana 
@kunagpal 
@kamalaknn 
@shamasis 
@coditva 

Sorry, maybe you will change things

At least one answer

**Comment by giridharvc7** [comment]
@nekszt 
We understand the situation and we'll look into this, i will share updates in this thread. 

The solution will mostly be creating a new command to skip a request during a Run, something like `pm.skipRequest()`. 
The `setNextRequest` is for modifying the workflow set by runner. It is not expected to stop a current request at this point.

**Comment by BlackGad** [comment]
@giridharvc7 new method name is ok to not break compatibility. But it must be SkipCurrentAndSetNext. Also this method must be available only on pre script stage. Just skip request adorable but in a joint with existing set next request. Because at the end this is a flow control functions

**Comment by sgperlman** [comment]
I don’t care what it’s called so long as it supports the ability to cancel the current request and terminate the entire script.  Sometimes there is no next request to be set.


  *   Stu

**Comment by nekszt** [comment]
Thanks @giridharvc7 
That's what we need `pm.skipRequest()`

I think the documentation should be clearer about `setNextRequest`.

**Comment by ailakeji** [comment]
I hope this function can be realized soon.

**Comment by qq1176914912** [comment]
I hope this function can be realized soon.

**Comment by Tyson1986** [comment]
Almost 2.5 years, ~70 people asked for this basic (IMHO) functionality, but no reaction, sad

**Comment by matt-filion** [comment]
+1

**Comment by jscottrobb** [comment]
> @giridharvc7 new method name is ok to not break compatibility. But it must be SkipCurrentAndSetNext. Also this method must be available only on pre script stage. Just skip request adorable but in a joint with existing set next request. Because at the end this is a flow control functions

I think this breaks the SOLID single responsibility principle where the responsibility is to stop the request and optionally fail. Just because you stop the request from being issued it does not mean you do not want to do something right then, after that command in the context of the pre-request. You could then use the .setNextRequest() after that.

**Comment by ZeusMode** [comment]
+1

2023 and still waiting

**Comment by mvalter24** [comment]
@postman-support It's the best time to add `pm.skipRequest()` feature now, since you started to charge for the use of a Collection Runner (it's not free anymore).

**Comment by nickwinsor** [comment]
Big +1. We need this too please.

**Comment by linh4github** [comment]
+1 Need it too, LOL

**Comment by lalalawson** [comment]
+1. Please.

**Comment by DavidAccola** [comment]
+1

**Comment by ch806290** [comment]
+1, please ~

**Comment by esha052026** [comment]
+1

**Comment by clabonte** [comment]
+1, it would definitely be very useful!

**Comment by cretucosmin3** [comment]
+1

**Comment by ja185215** [comment]
+1

**Comment by tiagojsrios** [comment]
@giridharvc7 Can we have an update on this feature request? It has been almost 3 years since this post was made and the only update we got was 4 months ago.

**Comment by aprevost** [comment]
+1. Definitely needed.

**Comment by chill389cc** [comment]
I, too, would like this feature :)

**Comment by OmarSedano** [comment]
+1, I think this would be a very useful feature to develop :)

**Comment by pavelstoyanov-payarc** [comment]
+1

**Comment by rggentil** [comment]
+1
It's not the most complicated feature for this tool and many people would appreciate it

**Comment by blindstuff** [comment]
Does the product team read these anymore?

It's pretty clear that postman is following PLG, new revenue streams, entry to the product for free, etc etc. We get it, you have to drive revenue for your app now that postman is a maturing company, that however doesn't mean that you can ignore the features that make you relevant, you need to listen to your users.

I can tell you that we had a key migration process we run periodically that used to be on postman, but since it has moved away from postman. The issue in particular is that this process has many exit points depending on the conditions to the data sent and received, the amount of "fake requests" we had to add to evaluate things and provide exit points made the collection a nightmare to maintain.

**Comment by giridharvc7** [comment]
@blindstuff thank you for explaining why the workaround doesn't work for you. 

Please allow us some time to get back on this, i'll ensure to keep this thread updated as we progress.

**Comment by jpturski** [comment]
+1

**Comment by mgalm** [comment]
+1

**Comment by jaybhanushali3195** [comment]
+1

**Comment by dipanshuchaubey** [comment]
+1 much needed feature

**Comment by lucianamerege** [comment]
+1

**Comment by pmd30011991** [comment]
+1

**Comment by tmargheim** [comment]
+1

**Comment by david-malouf-vizio** [comment]
+1

**Comment by elimetzlerprieb** [comment]
+1

**Comment by WendallHershberger-Allscripts** [comment]
@DannyDainton  @loopDelicious Is there anyway this could happen? Has this been prioritized at all?

**Comment by giridharvc7** [comment]
Hey folks, 
We are working on this and what we've come up so far is `pm.execution.skipRequest()` . This function when used in Pre-request scripts will not execute the request. 

Thank you for your patience, let us know if this would work, and if you'd like to see any other improvements on this. I want to ensure we get community feedback before we ship this out later this month.

**Comment by mallechilie** [comment]
Yes that would be awesome! Any idea when we get to use it? (Yes I really need this functionality)

**Comment by ThaGeege** [comment]
It would be very useful and im super excited this is on the horizon! I have a few questions.   

Could we still control the next request to execute? For instance you have requests A, B, C, D which normally would execute sequentially. Request A prerequest script runs. Due to some condition we decide the http request should not execute and the next script should be D. Is it still possible after calling skiprequest?

Also it seems obvious but worth stating that the post test would not run sunce that usually verifies the http response in some way (and the http request would have been canceled). Is that correct? If the post request test is still going to run for some reason it would be good if there was a way to detect that skiprequest was called for the current request.

**Comment by ThaGeege** [comment]
My main use case is to keep auth tokens alive but there are tons of other applications. The token comes from a url and has some expiration. If the token is expired the http request should run and generate a new token. I run a large number of requests using csv runner and want to avoid having to call the token endpoint every time. I think your solution achieves what I want to do.

**Comment by thallbeck** [comment]
Awesome!TimmehOn Nov 2, 2023, at 2:12 AM, Giridhar ***@***.***> wrote:﻿
Hey folks,
We are working on this and what we've come up so far is pm.execution.skipRequest() . This function when used in Pre-request scripts will not execute the request.
Thank you for your patience, let us know if this would work, and if you'd like to see any other improvements on this. I want to ensure we get community feedback before we ship this out later this month.

**Comment by WendallHershberger-Allscripts** [comment]
That is amazing. Thank you for making this a priority!!

**Comment by blindstuff** [comment]
Thanks @giridharvc7, phenomenal news.

Seconding a question along the lines of @ThaGeege, as long as we're able to use `postman.setNextRequest()` right before `pm.execution.skipRequest()` we should be covered, is this possible in the proposed approach?

**Comment by vedkribhu** [comment]
@blindstuff @ThaGeege 

> Could we still control the next request to execute? For instance you have requests A, B, C, D which normally would execute sequentially. Request A prerequest script runs. Due to some condition we decide the http request should not execute and the next script should be D. Is it still possible after calling skiprequest? 

Yes, you will be able to do this by writing `postman.setNextRequest` before invoking `pm.execution.skipRequest`.


> Also it seems obvious but worth stating that the post test would not run since that usually verifies the http response in some way (and the http request would have been canceled). Is that correct?

Yes, tests scripts for that request won't be executed if skipRequest function is invoked in pre-request script.

Thanks for the feedback. Let me know if you have anymore questions.

**Comment by UnInfamous** [comment]
Wow, what timing that this was implemented right when I needed it! You all are great, keep up the good work!

Question, is there potential to add an optional argument to skipRequest() to still log pre-request script console commands?

**Comment by vedkribhu** [comment]
@UnInfamous Could you please elaborate on your specific use case, I am trying to understand why you are interested in logging console commands from the pre-request script, especially after the execution of `pm.execution.skipRequest()`.

**Comment by ThaGeege** [comment]
Right on. I think it covers any use case I can think of!

**Comment by giridharvc7** [comment]
Hey folks, this is now released in the latest version of Postman. You can read more about this [here](https://blog.postman.com/optimize-your-api-testing-workflow-with-postmans-skip-request-feature/). 

We'd love to know what you think about this and how you are using it.

**Comment by mallechilie** [comment]
This feature is amazing, and works perfectly. 
Two questions:

- Is there a way to hide skipped requests in the manual runner view?
- When will newman support this new function? Currently it returns a type-error when using this function.

**Comment by giridharvc7** [comment]
Glad you like it!

We don't want to completely skip the requests in Runner view as there are also `Skipped` tests. We will work on an experience that best reflects the skipped execution of the request in the upcoming releases. 

We are looking to release this in the Postman CLI first. You can learn more about it [here](https://learning.postman.com/docs/postman-cli/postman-cli-installation/)

**Comment by DavidAccola** [comment]
After you release it in the Postman CLI will you release it in newman?

**Comment by mallechilie** [comment]
> We don't want to completely skip the requests in Runner view as there are also `Skipped` tests

As far as I know, there are two ways to skip a request: with `setNextRequest()` and with `skipRequest()`. With `setNextRequest()`, the skipped requests aren't viewed in the manual run viewer at all. Would you mind explaining why the skipped tests are much more relevant with the `skipRequest` method? (In my personal application, it doesn't make sense to show them at all, but I may have an atypical workflow.)

**Comment by victorlsds** [comment]
I'm using pm.execution.skip Request() a lot in Postman, but when I run it in my project using Newman it doesn't work. Am I doing something wrong? Or should I do something different to make it work?

**Comment by DannyDainton** [comment]
Hey @victorlsds - I'm not sure what version of Newman that you're running that on but it will only work on the latest version. 

It was added in the [6.1.0 release](https://github.com/postmanlabs/newman/blob/develop/CHANGELOG.yaml).

**Comment by mallechilie** [comment]
Be aware 6.1.0 does seem to have a memory leak, keep that in mind when updating to 6.1.0

**Comment by victorlsds** [comment]
Thank you both very much, I checked here and I'm using version 6.1.0. Actually, doing a unit test, pm.execution.skipRequest() works, but I'm having a problem with my collection. As you can see, the function is called but the request is still made. I know this is a problem with my code so I'll ask on stackOverflow, thanks again!
![image](https://github.com/postmanlabs/postman-app-support/assets/97249392/dc218f16-1cac-409e-8042-b6531870838b)
![image](https://github.com/postmanlabs/postman-app-support/assets/97249392/9fc145f8-6cf4-49ca-81ae-df37d5935e3e)

**Comment by tiagojsrios** [comment]
@victorlsds Based in your screenshot, it seems like that `codCertColetivo` is not defined as the console.log is outputing null.

Are you sure that the variable is defined in the collection? Perhaps you defined it on the environment and therefore you should do `pm.environment.get(...)`.

**Comment by victorlsds** [comment]
@tiagojsrios In this logic, the intention is that if this variable is null, this request will be skipped. The funny thing is that in Postman it works perfectly, but when exported to Newman it doesn't. That's why I asked the question if 'skipRequest()' works in Newman.
![image](https://github.com/postmanlabs/postman-app-support/assets/97249392/e054cc2e-3e07-4dc7-8dce-a6614b4e26a6)

**Comment by nowickimt** [comment]
What about making this work in a Monitor?  When I attempt to use pm.execution.skipRequest() within a pre-request script, it works fine from within Postman but fails when run through a Monitor I get `TypeError: Cannot read properties of undefined (reading 'skipRequest')`.

You can easily reproduce by adding just that one line (pm.execution.skipRequest) to a pre-request script and run it through a Monitor.

**Comment by axelonaut** [comment]
Hey @nowickimt, we are working on adding support for skipping a request in monitors. 

We will update on this thread as soon as we roll out the feature for monitors.

**Comment by axelonaut** [comment]
We have added support for skipping a request in monitors and scheduled collections. 

Feel free to comment on this thread in-case you face any issues.

**Comment by nowickimt** [comment]
Fantastic!!  Thanks for turning that around so quickly!
