### ISSUE TITLE
Hawk Auth header doesn't include user field (7.30.1)

### ISSUE THREAD

**Issue by jeromeklam** [a85/POSTMan-Chrome-Extension#8930]
Hawk Header User no more send to server :

Code view :

```
curl --location --request GET 'http://localhost:8080/api/v1/prj_mgnt/project/132/lastversion' \
--header 'App-Id: <redacted> \
--header 'Sso-Id: <redacted>' \
--header 'Api-Id: <redacted>' \
--header 'Accept: application/vnd.api+json' \
--header 'Authorization: Hawk id="<redacted>", ts="<redacted>", nonce="<redacted>", mac="<redacted>"'
```

Authorization config in the attached file.

Or I'm doing something wrong

**Comment by mohitranka** [comment]
@vikiCoder Can you please validate this issue?

**Comment by vikiCoder** [comment]
@jeromeklam , can you please explain a bit more regarding what is your expected result v/s Postman generated result you are seeing while using Hawk authentication?

**Comment by DannyDainton** [comment]
Hey @jeromeklam  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
