### ISSUE TITLE
Postman 7.30.1 performance issues bringing my system to a halt and impossible to work with. 

### ISSUE THREAD

**Issue by lallenmaestro** [a85/POSTMan-Chrome-Extension#8934]
I have only a few collections 1 to be exact with 11 requests.  Version of postman I'm running is 7.30.1 
my OS is Windows 10 

Postman is consuing 15-20% CPU Membor is 1523 - 1700mb  GPU is 79-85%  
See attached video.   

[Postman.zip](https://github.com/postmanlabs/postman-app-support/files/5070139/Postman.zip)

I don't understand why you cannot fix this issue.  I see it's been reported many times for the last few years.   This is making it very difficult to get any work done.

**Comment by lallenmaestro** [comment]
Any updates?

**Comment by arlemi** [comment]
@lallenmaestro No updates on this specific issue but while we're looking into it I can recommend to try out the [web version of Postman](https://go.postman.co/build) and see if it helps.

**Comment by lallenmaestro** [comment]
I will try Web version.

**Comment by kublermdk** [comment]
I'm having pretty much the same issue.
I've been using the Web version of Postman, but just submitted a support request as the web version isn't currently saving my local environment variables into anything long term. A refresh of the page clears them, making dealing with APIs which have authentication a nightmare.

**Comment by mccannt** [comment]
Closing this out as we are tracking this issue on an existing thread -https://github.com/postmanlabs/postman-app-support/issues/4361
