### ISSUE TITLE
Postman takes focus twice during startup

### ISSUE THREAD

**Issue by bdharrington7** [a85/POSTMan-Chrome-Extension#8935]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the app starts up (either for the first time, but usually after an update) and the screen will grab focus *twice*, once for the loading / splash screen, and again when the app becomes visible. The startup time isn't slow, but it's not instant either, so I usually switch away to do something else while it's updating. When it starts to load, it grabs focus for the loading screen, which will be there for a few seconds (enough time for me to switch to something else), and then **again** when the app finally starts. 

**Describe the solution you'd like**
It would be wonderful if it would not grab focus for any reason.

**Describe alternatives you've considered**
Pushing off updating because it's so disruptive. Something other than Postman that doesn't do this.

**Comment by jviotti** [comment]
I'm guessing that the reasoning behind this is that if you *are indeed* focusing on the splash screen, then you want to ensure the app itself gets focused once the splash screen closes (and not something else, which is OS/WM dependent AFAIK).

Assuming that's correct, the BrowserView could only set the focus *if* the splash screen was focused by the time it opens.

**Comment by jviotti** [comment]
Hi @bdharrington7 , can you check if the issue still occurs in the latest version of the Postman desktop application? The application should not grab focus anymore on the splash screen

**Comment by bdharrington7** [comment]
It still does grab focus for both the splash screen and the main window on macOS BigSur 11.5 and Postman v8.10.0

**Comment by bdharrington7** [comment]
As this is still happening, re: your comment about a conditional focus, I don’t think it’s appropriate under any circumstance to grab focus. It doesn’t make sense to me: if I’m working on something else, by definition I am not paying attention to Postman loading. I don’t need nor want Postman to yank me away from whatever I’m doing when it’s done updating. I honestly can’t think of any scenario where it’s a good user experience for Postman (or any app for that matter) to grab focus on load.

**Comment by jviotti** [comment]
Hey @bdharrington7 , 

The latest version of the Postman app has removed the loading screen altogether, so we believe this should not be a problem anymore!
