### ISSUE TITLE
Not responding when open select file browser window

### ISSUE THREAD

**Issue by quyennt21** [a85/POSTMan-Chrome-Extension#8938]
**Describe the bug**
Not Responding when open file select file browser.

**To Reproduce**
1. Go to 'body - form-data - File param'
2. Click on 'Select files'

**App information (please complete the following information):**
 - Postman Version v7.30.1
 - OS: Window10 10.0.18363 N/A Build 18363

**Comment by DannyDainton** [comment]
Hey @quyennt21 

I've been unable to reproduce this error on Mac or Windows OS.

Your repo steps mention the `body` - Is this the `form-data > File` option?

Is the error something that's presented in the app? Could you post a screenshot of this, please?

**Comment by quyennt21** [comment]
> Hey @quyennt21
> 
> I've been unable to reproduce this error on Mac or Windows OS.
> 
> Your repo steps mention the `body` - Is this the `form-data > File` option?
> 
> Is the error something that's presented in the app? Could you post a screenshot of this, please?

yeah, in form-data.

![image](https://user-images.githubusercontent.com/46489447/90226188-d7507600-de3c-11ea-8726-5c36a1fb0a57.png)

**Comment by DannyDainton** [comment]
The 'error' being the the file explorer window is lot responding and is not showing you the files in the directories on your computer?

I'm still unable to reproduce the same issue on Win 10, are you able to quit and restart the app? Or sign out and sign back in?

Just trying to run through some lower level troubleshooting to try and get you unblocked.

Alternatively, you could try using our Canary build or accessing the build mode from Postman on the Web.

https://www.postman.com/downloads/canary/

https://go.postman.co

**Comment by quyennt21** [comment]
@DannyDainton  no, I try to restart pc, but it still error. :(

**Comment by DannyDainton** [comment]
Did you have any luck with signing out or the app and back in again?

Or the other 2 options (Canary / Postman on the web) ?

**Comment by quyennt21** [comment]
yeah, I'm using postman on the web. thanks for your help.

**Comment by DannyDainton** [comment]
Cool, I'd be interested to know if signing out of the native app worked if you have time to check. 🤔 

I'm going to close out this issue but we can open it up again if you/other users are facing the same issue.
