### ISSUE TITLE
postman doesn't sent POST form data for HTTPS target

### ISSUE THREAD

**Issue by johnathanz** [a85/POSTMan-Chrome-Extension#894]
we recently updated our endpoints with SSL.

Unfortunately, this change seem to have introduced an error in postman where POST form data is not sent through to the receiving PHP script.

We are hitting a HTTPS URL direct (i.e. no redirect). Because it's commercial in nature, I can't post any screenshots.

What does work:
* SSL connection is established, receiving PHP script runs
* POSTMAN Preview shows payload data correctly

What doesn't work:
* doing a var_dump from the receiving PHP script outputs NULL
* we've tried tried form-data, x-www-form-urlencoded, raw.  None of it works
* we've also tried both the standalone Chrome App, and the embedded Chrome Extension, enabling developer tools as instructed here (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/).  No errors shown by Developer Tools.

Any help appreciated!

**Comment by abhijitkane** [comment]
In the Network tab of the Developer tools window, you'll see a request being made after you press send. Is the request payload section showing the form data correctly?

**Comment by johnathanz** [comment]
We found an ASCII character error in our JSON payload that was causing the issue.  Fixing the payload error corrected this issue.  No bugs in POSTMAN relating to this.  Please close issue.  Thanks abhijit!
