### ISSUE TITLE
Show Newly added Add-Request after its addition

### ISSUE THREAD

**Issue by udsharma015** [a85/POSTMan-Chrome-Extension#8941]
**Is your feature request related to a problem? Please describe.**
When I add a new request, the new request gets added in the background, I am shown the old Request again instead of the newly added request. 

**Describe the solution you'd like**
I feel for User experience, whenever a User adds a New Request inside a collection, and click on SAVE, then User should be shown the newly added request, instead of showing the older request. The science is, User added New Request to work on that only, If you show the Older request then User needs to find that newly added request and open which is not so User friendly.

**Comment by james-postman** [comment]
Hi @udsharma015,

Thanks for writing in, that sounds like a great question for the Postman community!

https://community.postman.com

James

**Comment by timbochamp** [comment]
Comparing the behaviour from version 7, this looks to be addressed in our version 8 release. I can't reproducible this anymore in the current v8.2.3 build or on Postman for Web with the new request opening in the active tab on save. This is trying both creating a request from the sidebar, or from the New (+) button. Please feel free to reopen if there's still issues!
