### ISSUE TITLE
Graphql body changes are not viewable within Postman Pull requests 

### ISSUE THREAD

**Issue by Liz1979** [a85/POSTMan-Chrome-Extension#8944]
**Is your feature request related to a problem? Please describe.**
The issue I am having is when I create a pull request from a forked collection that uses the GraphQL body element, any changes made here do not show up, but if there is a request that uses the raw body request it shows these changes in the pull request. This is causing an issue as we can't review the actual request that has been added or changed.

**Describe the solution you'd like**
Is there any chance that some one could add this feature to the postman Pull requests please?.

**Screen Shots**
![Screenshot 2020-08-17 at 15 06 21](https://user-images.githubusercontent.com/32060388/90407099-f7cb3b00-e09d-11ea-8357-547b70550748.png)
![Screenshot 2020-08-17 at 15 05 47](https://user-images.githubusercontent.com/32060388/90407103-f994fe80-e09d-11ea-9c9e-7430b87fd982.png)

**Comment by kartikjain26** [comment]
@Liz1979 Are you able to reproduce this issue ? If yes, please can you elaborate the steps here.
We were unable to reproduce the issue on our end.
![image](https://user-images.githubusercontent.com/26088676/90428805-2834c880-e0e2-11ea-9679-dbc8e9e94d5d.png)

**Comment by joelbiffin** [comment]
@kartikjain26 I was able to reproduce this. 

1. Create new request in fork of main collection
![Screenshot 2020-08-18 at 08 36 59](https://user-images.githubusercontent.com/2061283/90484509-34467780-e12e-11ea-9f27-1f6beafb137f.png)

2. Create pull request

3. Inspect 'Changes' tab to see no 'GRAPHQL QUERY' section
![Screenshot 2020-08-18 at 08 37 41](https://user-images.githubusercontent.com/2061283/90484630-5a6c1780-e12e-11ea-9728-840308de69c7.png)

**Comment by kartikjain26** [comment]
@joelbiffin Does this happen for every collection ? Can you try this on a freshly created collection and let us know if similar behaviour exists ?

**Comment by Liz1979** [comment]
@kartikjain26 Hi yes this happens for every collection you are not able to see the queries people are creating in their Pull requests.

**Comment by kartikjain26** [comment]
@Liz1979 Can you also check the same as @joelbiffin .
1. Create a new collection with requests
2. Create a new fork and modify request
3. Check if the Graphql query/variables are present or not.

**Comment by Liz1979** [comment]
@kartikjain26 So I recreated the steps above:
created and forked a new collection
![Screenshot 2020-08-18 at 09 49 14](https://user-images.githubusercontent.com/32060388/90492090-b045bd00-e138-11ea-8142-43428aa730e0.png)

added two requests - a graphQL body request and a raw body request 
![Screenshot 2020-08-18 at 09 54 47](https://user-images.githubusercontent.com/32060388/90492275-ec791d80-e138-11ea-98a7-2c44645c9547.png)
![Screenshot 2020-08-18 at 09 49 23](https://user-images.githubusercontent.com/32060388/90492285-ef740e00-e138-11ea-8303-b5736f0d2bb1.png)

Created a pr for these collections and this is the code changes you can see on the pr
![Screenshot 2020-08-18 at 09 50 19](https://user-images.githubusercontent.com/32060388/90492402-103c6380-e139-11ea-884f-3daebe062aab.png)

**Comment by kartikjain26** [comment]
Thanks @joelbiffin  @Liz1979  This was reproducible on our end and we have filed this bug. We'll track it on our roadmap and provide constant updates on this.

**Comment by Liz1979** [comment]
@kartikjain26 Thank you

**Comment by kartikjain26** [comment]
@Liz1979  This issue is fixed.
