### ISSUE TITLE
The problem for interceptor about decoding and encoding?

### ISSUE THREAD

**Issue by tester-xm** [a85/POSTMan-Chrome-Extension#8945]
![image](https://user-images.githubusercontent.com/60353008/90412637-f02c8600-e0df-11ea-80c6-52d2fcf7c5f1.png)
I get the body from interceptor, and my request body has chinese.
So,I need help?
Thanks~

**Comment by DannyDainton** [comment]
Hey @tester-xm 

Could you also provide information about the App Version, Interceptor Extension Version and your OS, please? 

Any other information about how to replicate this issue would also be really useful. Is there a particular endpoint that you're hitting?

**Comment by tester-xm** [comment]
ok, my app version is  Postman v7.30.1,  the intercepter package is from https://community.postman.com/t/postman-interceptor-bridge-download-failing/11204/6, my os is win10 professional.

**Comment by postman-kenji** [comment]
Closing this issue for now given age and response time. @tester-xm please feel free to reopen this if you are still encountering this issue. Thanks!
