### ISSUE TITLE
collections do not build proper payload when using variable with multiline string

### ISSUE THREAD

**Issue by AyushG3112** [a85/POSTMan-Chrome-Extension#8946]
**Describe the bug**
GIven a collection with the pre-request script,

``` js
pm.collectionVariables.set("data", "\n\n## Changelog\n\nbe09cd4 fix travis.yml\naf55d75 goreleaser with travis\n0b3790a jobs travis ci\n86a89f9 move script to deploy .travis.yml\nff33766 travis yml changes\n\n\n")
```

A request using the following payload:

``` json
{
    "text": "{{data}}",
    "mode": "gfm",
    "context": "ayushg3112/schmp"
}
```

which finally translates to: 

``` json
{
    "text": "

## Changelog

be09cd4 fix travis.yml
af55d75 goreleaser with travis
0b3790a jobs travis ci
86a89f9 move script to deploy .travis.yml
ff33766 travis yml changes


",
    "mode": "gfm",
    "context": "ayushg3112/schmp"
}
```

Which is rejected by the API Server, because this is not valid JSON

**To Reproduce**
1. Import the collection provided in the link at the end
2. Run the collection

**Expected behavior**
Request Payload should be:

``` json
{
    "text": "\n\n## Changelog\n\nbe09cd4 fix travis.yml\naf55d75 goreleaser with travis\n0b3790a jobs travis ci\n86a89f9 move script to deploy .travis.yml\nff33766 travis yml changes\n\n\n",
    "mode": "gfm",
    "context": "ayushg3112/schmp"
}
```

**Screenshots**
<img width="1440" alt="Screenshot 2020-08-17 at 10 08 36 PM" src="https://user-images.githubusercontent.com/21307931/90421953-c8d1bb00-e0d7-11ea-997b-b60a13c256ec.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Version 7.30.1 (7.30.1)
 - OS: macOS 10.15.5

**Additional context**
Collection Link: https://www.getpostman.com/collections/3eab254edb41126b5d10

**Comment by DannyDainton** [comment]
Hey @AyushG3112 

If you change the `/n` to `</br>` it will work and display the markdown.

```
pm.collectionVariables.set("data", `</br></br>## Changelog</br></br>be09cd4 fix travis.yml</br>af55d75 goreleaser with travis</br>0b3790a jobs travis ci</br>86a89f9 move script to deploy .travis.yml</br>ff33766 travis yml changes</br></br></br>`)
```

<img width="1197" alt="Screenshot 2020-08-18 at 07 38 59" src="https://user-images.githubusercontent.com/17089546/90479101-0eb57000-e126-11ea-9856-233d18f78b85.png">

**Comment by AyushG3112** [comment]
@DannyDainton yes, but in the actual use case, `data` is received as a response from another API, which is set into collection variables, and read in the next request. I would rather not modify the response string I received before setting it in the collection variables.

**Comment by DannyDainton** [comment]
Those new lines in the variable are being handled in a different in the app. 

As a workaround, you could do this to replace the `\n` before setting the variable in the pre-request:

```javascript
let markdownData = `\n\n## Changelog\n\nbe09cd4 fix travis.yml\naf55d75 goreleaser with travis\n0b3790a jobs travis ci\n86a89f9 move script to deploy .travis.yml\nff33766 travis yml changes\n\n\n`,
    strippedData = markdownData.replace(/\r?\n|\r/g, "</br>");

pm.variables.set("strippedData", strippedData)
```

**Comment by AyushG3112** [comment]
@DannyDainton thanks, that worked. Also, can this be marked as a feature request, or can this behaviour be documented somewhere?

**Comment by DannyDainton** [comment]
So for some reason (maybe because it's early), I didn't see the obvious issue with setting that string into a JSON body.

You need to wrap the string with `JSON.stringify()` before setting the variable:

```javascript
pm.collectionVariables.set("data", JSON.stringify("\n\n## Changelog\n\nbe09cd4 fix travis.yml\naf55d75 goreleaser with travis\n0b3790a jobs travis ci\n86a89f9 move script to deploy .travis.yml\nff33766 travis yml changes\n\n\n"))
```

The body needs to be also changed to be this:

```
{
    "text": {{data}},
    "mode": "gfm",
    "context": "ayushg3112/schmp"
}
```
The `{{data}}` variable needs to be added _without_ the quotes.

<img width="1190" alt="Screenshot 2020-08-18 at 09 29 28" src="https://user-images.githubusercontent.com/17089546/90489588-5bed0e00-e135-11ea-834e-43335fbce41d.png">

**Comment by AyushG3112** [comment]
@DannyDainton thanks that worked!
