### ISSUE TITLE
Support mqtt npm package in sandbox

### ISSUE THREAD

**Issue by Ariemeth** [a85/POSTMan-Chrome-Extension#8947]
**Is your feature request related to a problem? Please describe.**
When testing our APIs many of them should generate an mqtt message to a client.  

**Describe the solution you'd like**
We would like to be able to establish a mqtt connection in a test script and then expect a specific message after making the API request.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered
Other or custom frameworks for testing

**Additional context**

**Comment by vvs11** [comment]
Hi @Ariemeth. This is something that is on our roadmap. No timelines yet. Will keep you posted. Thanks for the writing in

**Comment by philCryoport** [comment]
@Ariemeth please also vote for https://github.com/postmanlabs/postman-app-support/issues/9490 -- a separate request for MQTT?

**Comment by skatikia** [comment]
@Ariemeth Fresh off the protocol bakery; Postman now supports MQTT! You can test your MQTT APIs built on V5 and V3.1.1 and analyze the responses better with real-time response visualization. Learn about all the stuff we have done and how to get started: https://blog.postman.com/postman-supports-mqtt-apis/

![image](https://github.com/postmanlabs/postman-app-support/assets/67992216/3a52c4ce-8a51-47ab-914a-cb03e026475a)

Thank you for the feedback, and we look forward to hearing more from you once you get your hands on it! ❤️
