### ISSUE TITLE
Not able to open the postman

### ISSUE THREAD

**Issue by ravikumarkornu** [a85/POSTMan-Chrome-Extension#8949]
**Describe the bug**
Not able to open the lastest version postman application.
It's showing below error

Error: Migration: IndexedDB schema migration failed. IndexedDb was not upgraded successfully after `dexie.open`.

Please try restarting the app. If the issue persists, please refer to https://go.pstmn.io/troubleshoot-could-not-open

Logs:
vendor-shared.js:223852 Initializing the global config
vendor-shared.js:295815 Error in fetching user information Error: Could not get waterline model for user. ORM not initialized.
    at Object.getModel (vendor-shared.js:57758)
    at Object.findOne (vendor-shared.js:57820)
    at Object.get (vendor-shared.js:64157)
    at EventEmitter.<anonymous> (vendor-shared.js:954370)
    at EventEmitter.emit (vendor-shared.js:49202)
    at _dispatch (vendor-shared.js:210197)
    at EventEmitter.<anonymous> (vendor-shared.js:210207)
    at EventEmitter.emit (/Applications/Postman.app/Contents/Resources/app/html/events.js:203)
    at Object.onMessage (/Applications/Postman.app/Contents/Resources/app/html/electron/js2c/renderer_init.js:2469)

**To Reproduce**
I have installed the latest version and try open its giving below error
Logs:

**Expected behavior**
It should open

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Version 7.30.1
 - OS:  macOS High Sierra 10.13.2

**Additional context**

**Comment by Raj-postman** [comment]
Hi @ravikumarkornu

Clearing local files of your Postman installation generally resolves this issue. May I know if you have followed the steps mentioned in this article below?

- [Could not open Postman error](https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-)

**Comment by ravikumarkornu** [comment]
Thanks for your response. Its working after deleting the files .
macOS - Go to Finder (Cmd+Opt+Space) > Go to folder (Shift+Cmd+G) > Paste ~/Library/Application Support/Postman  > hit return > Delete the files.

**Comment by Raj-postman** [comment]
Awesome! In that case, will mark as Closed :)
