### ISSUE TITLE
Remember what token is selected for each collection

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#8951]
**Is your feature request related to a problem? Please describe.**
For OAuth 2, the token that is selected persists across collections and workspaces. This requires users to employ variables and environments to easily switch authorization details when switching collections and/or workspaces.

**Describe the solution you'd like**
Save context of what token is selected per collection, or at least per workspace.

**Describe alternatives you've considered**
None

**Additional context**
User requested

**Comment by giridharvc7** [comment]
Token context is saved per collection in OAuth2.0 with v9.x and above, feel free to open this ticket in case this issue is still persistent.
