### ISSUE TITLE
'Import' - 'Raw Text' import Unicode Error

### ISSUE THREAD

**Issue by microkof** [a85/POSTMan-Chrome-Extension#8953]
**Describe the bug**
When 'Import' - 'Raw Text' import Unicode, the char '\\' (a backslash) will be disappeared.

**To Reproduce**
1. 'Import' - 'Raw Text'
2. Paste curl code, the value contains Unicode.
3. Submit.
4. the code '\\' will be disappeared.

**Expected behavior**
the char '\' will not be disappeared.

**Screenshots**

**App information (please complete the following information):**
 - Postman Version [7.30.1]
 - OS: [Window 10]

**Additional context**

**Comment by DannyDainton** [comment]
Hey @microkof 

Would you be able to provide an example of the curl code you're posting, please?

Or a screenshot of before and after 😄

**Comment by microkof** [comment]
> Hey @microkof
> 
> Would you be able to provide an example of the curl code you're posting, please?
> 
> Or a screenshot of before and after

```
curl 'http://192.168.9.133/dev-api/baseinfo/supporting/elevatorinfo' -X PUT -H 'Cookie: Admin-Token=eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsImxvZ2luX3VzZXJfa2V5IjoiZWE5YzE1OWItZDcxOS00MmMxLTk0MDYtNzRkNmZmMzg5ZTYzIn0.RbpULGfTpBiIR9VnlOXiGrzy2civqfRUTu_Eod7jANC5IxGLnS8tYMhBRHL1cNDzCrgFquureM9rm5qUNQIbsA' -H 'Origin: http://192.168.9.133' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsImxvZ2luX3VzZXJfa2V5IjoiZWE5YzE1OWItZDcxOS00MmMxLTk0MDYtNzRkNmZmMzg5ZTYzIn0.RbpULGfTpBiIR9VnlOXiGrzy2civqfRUTu_Eod7jANC5IxGLnS8tYMhBRHL1cNDzCrgFquureM9rm5qUNQIbsA' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://192.168.9.133/baseinfo/supporting/elevatorinfo' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary $'{"searchValue":null,"createBy":null,"createTime":null,"updateBy":null,"updateTime":null,"remark":null,"dataScope":null,"params":{},"id":1,"elevatorId":"DT0021","proId":153,"proName":"\u540c\u7965\u57ce\u5c0f\u533a1\u671f","buildingNum":6,"unitNum":3,"type":"1","purpose":"1","brand":"\u4e09\u661f","variety":"\u5347\u964d\u5f0f","registrar":"\u8d28\u76d1\u5c40","checkOrg":"\u6cb3\u5317\u4e2d\u610f\u68c0\u6d4b\u673a\u6784","registerNum":"NO:4221213","careCompany":"\u7ef4\u4fdd\u6709\u9650\u516c\u53f8","careCycle":"\u534a\u5e74","proTreeSelectValue":[153]}' --compressed
```

**Comment by microkof** [comment]
> > Hey @microkof
> > Would you be able to provide an example of the curl code you're posting, please?
> > Or a screenshot of before and after
> 
> ```
> curl 'http://192.168.9.133/dev-api/baseinfo/supporting/elevatorinfo' -X PUT -H 'Cookie: Admin-Token=eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsImxvZ2luX3VzZXJfa2V5IjoiZWE5YzE1OWItZDcxOS00MmMxLTk0MDYtNzRkNmZmMzg5ZTYzIn0.RbpULGfTpBiIR9VnlOXiGrzy2civqfRUTu_Eod7jANC5IxGLnS8tYMhBRHL1cNDzCrgFquureM9rm5qUNQIbsA' -H 'Origin: http://192.168.9.133' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.9' -H 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VySWQiOjEsImxvZ2luX3VzZXJfa2V5IjoiZWE5YzE1OWItZDcxOS00MmMxLTk0MDYtNzRkNmZmMzg5ZTYzIn0.RbpULGfTpBiIR9VnlOXiGrzy2civqfRUTu_Eod7jANC5IxGLnS8tYMhBRHL1cNDzCrgFquureM9rm5qUNQIbsA' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://192.168.9.133/baseinfo/supporting/elevatorinfo' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary $'{"searchValue":null,"createBy":null,"createTime":null,"updateBy":null,"updateTime":null,"remark":null,"dataScope":null,"params":{},"id":1,"elevatorId":"DT0021","proId":153,"proName":"\u540c\u7965\u57ce\u5c0f\u533a1\u671f","buildingNum":6,"unitNum":3,"type":"1","purpose":"1","brand":"\u4e09\u661f","variety":"\u5347\u964d\u5f0f","registrar":"\u8d28\u76d1\u5c40","checkOrg":"\u6cb3\u5317\u4e2d\u610f\u68c0\u6d4b\u673a\u6784","registerNum":"NO:4221213","careCompany":"\u7ef4\u4fdd\u6709\u9650\u516c\u53f8","careCycle":"\u534a\u5e74","proTreeSelectValue":[153]}' --compressed
> ```

the char '\\' disappeared:

```
{
    "searchValue": null,
    "createBy": null,
    "createTime": null,
    "updateBy": null,
    "updateTime": null,
    "remark": null,
    "dataScope": null,
    "params": {},
    "id": 1,
    "elevatorId": "DT0021",
    "proId": 153,
    "proName": "u540cu7965u57ceu5c0fu533a1u671f",
    "buildingNum": 6,
    "unitNum": 3,
    "type": "1",
    "purpose": "1",
    "brand": "u4e09u661f",
    "variety": "u5347u964du5f0f",
    "registrar": "u8d28u76d1u5c40",
    "checkOrg": "u6cb3u5317u4e2du610fu68c0u6d4bu673au6784",
    "registerNum": "NO:4221213",
    "careCompany": "u7ef4u4fddu6709u9650u516cu53f8",
    "careCycle": "u534au5e74",
    "proTreeSelectValue": [
        153
    ]
}
```

**Comment by VShingala** [comment]
@microkof This issue has been fixed for some time now with [this fix](https://github.com/postmanlabs/postman-app-support/issues/8505#issuecomment-953108948).

Below is behavior now for the request you shared after import.
![image](https://user-images.githubusercontent.com/16756296/224234183-1b3d49df-01cb-4f3d-8d42-303f5a430793.png)
