### ISSUE TITLE
new-line character included when copying a single line and pasting into the Collection/Environment variables

### ISSUE THREAD

**Issue by wiltonlazary** [a85/POSTMan-Chrome-Extension#8955]
Issue Editing collection or environment variables.
When triple-click to select all it's seems to include the newline character where it should not.

*Platform/Version*
* Postman for Linux | Version 7.30.1
* linux 5.4.0-42-generic / x64

*Screenshots/Videos*
![postman-line-copy_paste](https://user-images.githubusercontent.com/21366/90845531-57855700-e3ba-11ea-840d-be71c723e795.gif)

**Comment by DannyDainton** [comment]
Hey @wiltonlazary

If this is an issue that you're reporting, could you also provide some environment (App version and OS) details please.

We will also require the steps to reproduce the issue and some screenshots of what you're seeing to help bring the information to life.

**Comment by wiltonlazary** [comment]
Linux Ubuntu 20.04,

When triple click to select all it's seems to include the newline character where it should not.

**Comment by DannyDainton** [comment]
Which app version are you seeing this issue on?

Can you share an image of what it looks like please?

**Comment by wiltonlazary** [comment]
https://www.dropbox.com/s/lfex8d9zqyha2z9/postman-line-copy_paste-2020-08-20_18.19.10.mp4?dl=0

**Comment by wiltonlazary** [comment]
> Which app version are you seeing this issue on?
> 
> Can you share an image of what it looks like please?

I put the references on the first comment.

Thanks.

**Comment by DannyDainton** [comment]
I see that you're copying and pasting the text from the `description` tab which includes a markdown editor. Highlighting when you have text over multiple lines is showing an extra space at the end of the line.

The behaviour you're seeing with the `variables` editor is expected and it's warning you that new characters are present.

Are you seeing this same behaviour when copying text from a non-markdown editor outside of the application?

**Comment by wiltonlazary** [comment]
> I see that you're copying and pasting the text from the `description` tab which includes a markdown editor. Highlighting when you have text over multiple lines is showing an extra space at the end of the line.
> 
> The behaviour you're seeing with the `variables` editor is expected and it's warning you that new characters are present.
> 
> Are you seeing this same behaviour when copying text from a non-markdown editor outside of the application?

I tested others editors and no one copy the new line character with the triple click.

**Comment by DannyDainton** [comment]
Just using vscode and a `.md` file, if I triple-click on a single line the text is highlighted and the cursor moves to the end of the line.

<img width="257" alt="Screenshot 2020-08-21 at 19 37 10" src="https://user-images.githubusercontent.com/17089546/90923623-e9ef2000-e3e5-11ea-8aca-668b2aff692c.png">

When there is a second line and you triple-click, the cursor moves to the start of the new line but also includes an additional space at the end of the first line.

<img width="358" alt="Screenshot 2020-08-21 at 19 36 46" src="https://user-images.githubusercontent.com/17089546/90923710-0c813900-e3e6-11ea-94e5-c189aa4c25f6.png">

**Comment by wiltonlazary** [comment]
You are right, i tested it and some others editors, some put the new line and some don't.

**Comment by wiltonlazary** [comment]
gedit, leafpad: don't.
kate, vscode, intelij, eclipse: yes 

For sure it was my bias on the linux editor.
I will close this, thanks for the attention.
