### ISSUE TITLE
Content-Type header automatically added to Response even if it's defined in the OpenAPI specification

### ISSUE THREAD

**Issue by DannyEnsink** [a85/POSTMan-Chrome-Extension#8956]
**Describe the bug**
When defining a content-type header in the OpenAPI specs, the API Docs generator still adds a "Content-Type" header even though one is manually defined. 

**To Reproduce**
1. Create a new OpenAPI spec with the following example included:
```
"responses": {
  "200": {
    "description": "Success Response.",
      "content": {
        "[TYPE ENTERED HERE IS ALWAYS ADDED AS A 'Content-Type' HEADER]": {
          "schema": { ... }
        }
      },
      "headers": {
        "content-type": {
        "description": "This entity header is used to indicate the media type of the resource.",
          "schema": {
            "type": "string",
            "example": "application/json; odata=fullmetadata; charset=utf-8"
          }
      }
  }
}
```
2. Generate an API Documentation based on the OpenAPI Specs
3. Open the generated documentation and Expand the Example Response headers
4. Notice that there are 2 Content-Type headers.

**Expected behavior**
1. When a manual content-type header is defined, don't automatically generate one based on the type mentioned in the "content" part.
2. Add an option to turn off ANY automatic generation of headers at all when working with a (OpenAPI) specification. The whole point of a specification is to specify, not to have a tool "think" for you and add things to your specification.

**Screenshots**
Content-Type header that gets automatically added, always:
![image](https://user-images.githubusercontent.com/8476848/90877609-a58f6000-e3a4-11ea-8a94-7da2ff889d11.png)

Manual definition of the content-type:
![image](https://user-images.githubusercontent.com/8476848/90877746-dec7d000-e3a4-11ea-8461-14772b366157.png)

Result after generating API Docs:
![image](https://user-images.githubusercontent.com/8476848/90877986-3b2aef80-e3a5-11ea-82cb-8d2b988052d0.png)

**App information**
 - App Type: Native App
 - Postman Version: Version 7.30.1
 - OS: Windows 10

**Comment by VShingala** [comment]
@DannyEnsink As mentioned in OpenAPI specification ([source](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-10)), `Content-Type` header definition is ignored. You can mention the exact media type (with parameters) as part of content object. In your case you should mention exact content type under content object instead header as below.

```
"responses": {
  "200": {
    "description": "Success Response.",
      "content": {
        "application/json; odata=fullmetadata; charset=utf-8": {
        "schema": { ... }
      }
    }
  }
}
``` 

As mentioned [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#media-types) media type parameters are allowed under media type.
