### ISSUE TITLE
Can't see the Send and Save button anymore

### ISSUE THREAD

**Issue by liukangwei1213** [a85/POSTMan-Chrome-Extension#8957]
postman The right no Send and save type，But there is one Comments，what's this case?
![88ca86d866e7ea024ae1e3410acfa78](https://user-images.githubusercontent.com/30920753/90894403-207f6780-e3f3-11ea-932c-40e638142dbf.png)

**Comment by DannyDainton** [comment]
Hey @liukangwei1213 

You currently have the app in `Comment` mode and this would allow you to add inline comments to certain request level elements. You would need to use the toggle to switch this to the `Build` mode to be able to send requests that you're currently building.

https://community.postman.com/t/what-s-new-in-postman-7-30/14864
