### ISSUE TITLE
why my doesn't +Add Cookie work?

### ISSUE THREAD

**Issue by liukangwei1213** [a85/POSTMan-Chrome-Extension#8958]
Unable to use after adding domain name,What's the problem?
![微信图片_20200821215317](https://user-images.githubusercontent.com/30920753/90898113-bf5a9280-e3f8-11ea-89c5-8350547f4dfe.png)

**Comment by DannyDainton** [comment]
Hey @liukangwei1213 

Could you please use the template provided to allow us to understand what's happening so that we can recreate the problem locally.

Without this basic information, we will be unable to help.

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
Add any other context about the problem here.
```

**Comment by codenirvana** [comment]
@liukangwei1213 The input expects a valid hostname, not the complete URL.
I hope adding just the domain name (without `http://` and path) will fix your issue.
