### ISSUE TITLE
load variables from CSV in raw JSON request with collection runner

### ISSUE THREAD

**Issue by thricex** [a85/POSTMan-Chrome-Extension#896]
Truly apologize if this has been raised before but I could not find the solution any where.

I would like to run a series of tests via the collection runner. I'm trying to keep it simple for now and my collection includes a POST request with a raw JSON request body. I would like to dynamically load certain variables from a CSV file with each iteration.

My CSV file looks something like this:
```
key_id,p_id
newtokenid01,9991
newtokenid02,9992
newtokenid03,9993
```
With each iteration, i'd like to replace a variable ("key_id" and "p_id") within the raw JSON request submitted:
```json
{
    "id": "{{key_id}}",
    "accessLevel": {
        "type": "P",
        "value": "{{p_id}}"
    }
}
```

Clearly I am doing something wrong (or perhaps I assumed this would work but this functionality doesn't exist) as what ends up being submitted according to the console is:
```
Object {key_id: "newtokenid01", p_id: "9991"}
```

Thanks for your help.

**Comment by abhijitkane** [comment]
I just tried this using your raw data and csv, and it works as expected (the request sent replaces key_id and p_id correctly).

What do you mean by "submitted to the console"? The data variables are printed to the console for logging purposes. What do you see when you check the network tab (Right click on the collection runner > Inspect element > Network)? Is something unexpected being sent?

**Comment by thricex** [comment]
I did not think to look at the network tab, thank you. I can clearly see the JSON request is submitted correctly. The error is due to something else entirely. Thanks for helping so quickly.
