### ISSUE TITLE
Error: Invalid character in header content ["Host"]

### ISSUE THREAD

**Issue by eemechs** [a85/POSTMan-Chrome-Extension#8960]
**Describe the bug**
Error to send GET on {{apiQueryUrl}} variable.

**To Reproduce**
1. Go to 'GET on {{apiQueryUrl}}/1/sales/paymentId'
2. Click on 'Send'
3. Scroll down to 'Body - Response'

**Expected behavior**
Error: Invalid character in header content ["Host"]

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/37016326/90904942-d328d900-e3a5-11ea-8ec8-ff20baab9a32.png)

**App information (please complete the following information):**
 - App Type [Postman for Windows]
 - Postman Version [Version 7.30.1]
 - OS: [win32 10.0.18363 / x64]

**Comment by DannyDainton** [comment]
Hey @elierton 

Would you be able to provide an image of the request headers, please? One that shows the ones that you have added (mask any sensitive information) and the auto-generated ones.

**Comment by emcostadev** [comment]
Hello @DannyDainton 

![image](https://user-images.githubusercontent.com/37016326/90906596-4af80300-e3a8-11ea-96a5-c12d6c3729a5.png)

**Comment by DannyDainton** [comment]
Looking at the console message and the way the URL it constructed I think there might be a new line character in your variable.

![Screenshot 2020-08-21 at 16 27 08](https://user-images.githubusercontent.com/17089546/90907691-35480500-e3cb-11ea-87f1-10d8a97a16e6.png)

The variable with the new line looks like this:

![Screenshot 2020-08-21 at 16 28 22](https://user-images.githubusercontent.com/17089546/90907832-6aecee00-e3cb-11ea-8293-660a33ce0dc0.png)

Could you open the `Manage Environments` and check that's the case in your file, please?

**Comment by emcostadev** [comment]
Exactly that, this enter symbol in clear mode, I hardly see it, thank you very much for your support !!!

**Comment by emcostadev** [comment]
@DannyDainton solve my problem!!!
