### ISSUE TITLE
Very High CPU/GPU usage while a request is pending

### ISSUE THREAD

**Issue by tangphillip** [a85/POSTMan-Chrome-Extension#8961]
**Describe the bug**
While a Postman request is waiting for a response, and while that request's tab is visible in the Postman window, Postman consistently uses 60-70% of CPU (according to Activity Monitor) on the `Postman Helper (GPU)` and `Postman Helper (Renderer)` threads. That amount of CPU is excessive—more than a Google Meet call!

I'm assuming that Postman is using the GPU and renderer threads to render the little "in-progress" animation:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/463460/90933888-5100da80-e3ce-11ea-80ae-9e7d792b9c5c.gif)

The animation is very pretty, but this amount of resource usage is too much. It means that when I'm debugging an endpoint, I need to remember to switch Postman tabs if I don't want Postman to run down my laptop battery!

**To Reproduce**
1. Create a server that supports breakpoints.
2. Make an endpoint and set a breakpoint in it so that the endpoint doesn't ever respond.
3. Ensure that Postman's `Request timeout in ms` setting is set to `0`.
4. Use Postman to make a request to your never-returning endpoint, and don't switch tabs.

**Expected behavior**
I expected Postman to not use a ton of system resources for an extended period of time. It's putting my new 2020 Macbook Pro's fans into jet engine mode!

**Screenshots**
<img width="1072" alt="Screen Shot 2020-08-21 at 4 38 33 PM" src="https://user-images.githubusercontent.com/463460/90934122-c2d92400-e3ce-11ea-9639-59e756a48236.png">

**App information (please complete the following information):**
 - App Type: Native Mac App
 - Postman Version: Version 7.30.1 (7.30.1)
 - OS: macOS Catalina 10.15.6 (19G73)

**Comment by rosdi** [comment]
I left my Postman open (idle) today...,, and the CPU fan kept spinning for no reason... Postman (that is being left idle) is using 20% of the CPU! .. this is not macOs specific (as tagged in this thread), I am on Windows 10.

I closed Postman and my CPU usage almost immediately dropped to 3-4%

**Comment by Mardenlr** [comment]
Use Thunder Client in VS Code and by happy! Postman is very very very heavy (CPU and GPU) usage and the creators not solve that problem

**Comment by ebebpl** [comment]
Similar high GPU 80-90% when Postman Desktop client was open throughout the day. This Windows10 laptop is high-end i7 8vcpu 32GB RAM but I could hardly move my mouse it was stuck when GPU reaches 90%. Once I closed Postman desktop GPU usage went below 10% and remained there and laptop was back to normal. The GPU 90% was seen for the process Desktop Window Manager. 

UPDATE: After turning off Postman desktop Help->Hardware Acceleration and restarting Postman, GPU usage is now below 5% and everything is back to normal. No high cpu/gpu usage anymore.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/8749
