### ISSUE TITLE
File is missing

### ISSUE THREAD

**Issue by pwyss0** [a85/POSTMan-Chrome-Extension#8964]
**Describe the bug**
With the Postman App it is no longer possible to import a file via POST request / form-data. With the Postman Chrome App it works perfectly fine.

**To Reproduce**
1. First a job with a POST request has to be created
Request: https://system.xy.net/bulk-configuration/v1/import-jobs/jobs  -> note down the id of that job e.g. 1001
Body (raw):

```json
{
    "name": "Bulk_import_No_Instance_Validation_Node",
    "validationPolicy": [
        "no-instance-validation"
    ],
    "executionPolicy": [
        "continue-on-error-operation"
    ]
}
```

2. With the ID given by the first job another POST request with Body / form-data and the two keys "file" and "filename" needs to be created. Select a file as a value of key "file". The value of key "filename" is the name of the selected file.

```
Request: https://system.xy.net/bulk-configuration/v1/import-jobs/jobs/1001/files
Body (form-data):
KEY file: select file
KEY filename: name of file
```

3. When executing the previous request the error message "file-is-missing" pops up.

```json
{
    "totalCount": 2,
    "errors": [
        {
            "type": "ERROR",
            "code": "file-format-error",
            "message": "Supported file extensions are xml, csv, txt, zip."
        },
        {
            "type": "ERROR",
            "code": "file-is-missing",
            "message": "The correct import file must be supplied."
        }
    ]
}
```

**Expected behaviour**
Import is created (Status 201). Below the output of Postman Chrome App

```json
{
    "id": 20003,
    "name": "wcdma_bulk_import_continue_on_error.xml",
    "format": "3GPP",
    "_links": {
        "job": {
            "rel": "job",
            "href": "https://system.xy.net/bulk-configuration/v1/import-jobs/jobs/20003"
        },
        "invocations": {
            "rel": "invocations",
            "href": "https://system.xy.net/bulk-configuration/v1/import-jobs/jobs/20003/invocations"
        }
    }
}
```
**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.30.1
 - OS: Windows 10 Enterprise

**Comment by DannyDainton** [comment]
Hey @pwyss0 

Could you confirm that files you're selecting are in the same directory as the path set for the working directory, in the app's settings

https://learning.postman.com/docs/getting-started/settings/#working-directory

**Comment by pwyss0** [comment]
Hi Danny

Yes, I can confirm that the link set in the working directory points to the folder were the import files are.

**Comment by DannyDainton** [comment]
Is there any documentation that you could provide for the endpoint? Do you have a CURL example that could help us see the structure of the request?

Does the `key` for the filename need to be a specific value/name?

Is the file that you're importing, one of the extensions mentioned?

Without more details about the implementation of the API or that endpoint, it's going to be difficult to point out what the solution may be.

**Comment by pwyss0** [comment]
I think I found the root cause. The request is not updated with the selected filename. E.g. The file I have selected is called "wcdma_bulk_import_continue_on_error.xml". However, if I check the curl code, the filename "OLMP10_A_UTF-8_new.xml" is populated, see below. Therefore the error message <file missing>. The file mentioned in the code is indeed not available and is also not selected.

curl --location --request POST 'https://henms-haproxy.sharedtcs.net/bulk-configuration/v1/import-jobs/jobs/null/files' \
--header 'Cookie: ssocookie=ssocookie-1; amlbcookie=01; iPlanetDirectoryPro=S1~AQIC5wM2LY4SfczsmylSf1hmU_r6wbVZH9dNSEicq146Ons.*AAJTSQACMDIAAlNLABM5MTU1MTc2Mjk3NzQwMTM5MDU1AAJTMQACMDE.*' \
--form 'file=@OLMP10_A_UTF-8_new.xml' \
--form 'filename=nr_bulk_import_contOnErrorOperation.xml'

**Comment by DannyDainton** [comment]
Are you able to send the request now or are you still seeing issues?

Is the filename not updating in the curl something that you can reproduce every time - Would you like adding the steps to reproduce it that's the case.

**Comment by pwyss0** [comment]
It never works. You always get the same error message "file-is-missing" and in the curl code, there is always the same filename populated (OLMP10_A_UTF-8_new.xml). My work colleagues have exactly the same problem.

**Comment by saswatds** [comment]
Hi @pwyss0 , Do you see any error in your `Postman Console` when you are trying to send the request?

**Comment by pwyss0** [comment]
Hi @saswatds, the only error message I see in the console is "{"totalCount":1,"errors":[{"type":"ERROR","code":"file-is-missing","message":"The correct import file must be supplied."}]}"  (Status: 422 Unprocessable Entity).

**Comment by pwyss0** [comment]
Hi @saswatds, any news on this issue? Unfortunately we are still forced to use the Postman Chrome App.

**Comment by DannyDainton** [comment]
Hey @pwyss0 

I'm going to close this issue due to inactivity. If you're still facing these issues in the latest version of the platform we can look at reopening the issue.
