### ISSUE TITLE
Collection Pre-requisite Scripts : Can not read the global variable set in request test

### ISSUE THREAD

**Issue by musanas** [a85/POSTMan-Chrome-Extension#8965]
Hi,

It is observed that if i **set a global variable in a request test**, (say step 1) the same global variable can't be read back by invoking a function which is at collection pre-requisite script, with in the same execution of the request (say step 2).

pm.globals.get("varibaleName") returns it as undefined, but at the same time i see the variable gets persisted in the postman ide global variable section.

To reproduce this issue, I have attached a small collection here which contains 1 requests of [https://petstore.swagger.io/](petstore)
[Bug Repo.zip](https://github.com/postmanlabs/postman-app-support/files/5117531/Bug.Repo.zip)

Postman Version : Postman v7.30.1 (on windows 10)

Thanks & Warm Regards
Musa

**Comment by DannyDainton** [comment]
Hey @musanas 

There seems to be an issue with your script, I would expect it to be something like this:

```
global_functions = {
  function1: () => {
   console.log("Here executing function1 to get petResponse global variable, which was set in request");
   var globVariable = pm.globals.get("petResponse");
   console.log(globVariable);
   }
}
```

Also, I would recommend that these types of questions are asked over on our Postman Community site, we have many folks over there willing to help. 

https://community.postman.com/

I'm going to close this issue out for now and see you over on the community forum.

**Comment by musanas** [comment]
Thanks @DannyDainton  for responding
Sure, I will get over to the community

The only difference i see in my script is how the property **function1** in the object **global_functions** is defined
I used a double quote for -  "function1" , not sure that matters or not

If i remove it and made as you pasted above, the result is same :( 
Not sure whether am missing anything here

Warm Regards
Musa

**Comment by musanas** [comment]
`global_functions = {

function1 : (pm)=>{
   console.log("Here executing function1 to get petResponse global variable, which was set in request");
   var globVariable = pm.globals.get("petResponse");
   console.log(globVariable);
},
}`

this would solve this problem
the scope of 'pm' variable inside the function1 was the prob
