### ISSUE TITLE
Empty Mock Server Call Log

### ISSUE THREAD

**Issue by GHAStVHenry** [a85/POSTMan-Chrome-Extension#8967]
**Describe the bug**
Mock Server Call Log: Not displaying history (been 1hr and counting and not showing any calls)

**To Reproduce**
1. create a mock server
2. send calls
3. go to the call log

**Expected behavior**
See a history of the calls to the mock server

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] Chrome
 - Postman Version [e.g. 6.0.1] v7.30.1
 - OS: [e.g. macOS High Sierra 10.13.2] Win10

**Additional context**

**Comment by DannyDainton** [comment]
Hey @GHAStVHenry 

We're currently investigating an issue with the call logs on Mock servers - You can track this here https://status.postman.com/incidents/b70rk6k2gvyp

We'll update this thread with more information soon.

**Comment by DannyDainton** [comment]
The incident has been resolved. However, we'll continue to monitor the issue for a few hours.

@GHAStVHenry Would you be able to confirm on your end if you're now able to see the Mock server logs?

**Comment by GHAStVHenry** [comment]
Confirmed, it is logging!

**Comment by DannyDainton** [comment]
Going to close this one out! Thanks for flagging this 🏆
