### ISSUE TITLE
History from a Team Workspace is showing "Something Went Wrong" or response data from another API

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#8968]
**Describe the bug**
I've been having to look through the History to find information on an issue we are having. In doing so, I started running into issues with the History showing the correct response data,

One of the following will happen:
- It will show the correct response data
- Will display the error "Something Went Wrong"
- Will show response data from a different API that has been ran
- Will show nothing at all <-- With these, based on the API that was called, I would expect something to show.

**To Reproduce**
1. Go to a Workspace that has a lot of History
2. Starting at the top, just start clicking on each item to see the response render something
3. If the response shown is correct, go to the next one
4. Once you encounter a problem., either the “Something Went Wrong” or response data from another API call, close the tab at the top
5. Click on the exact same item in History, and it will now show the correct response
6. Unless it's one of the APIs where it doesn't show anything

**Expected behavior**
For the correct response data to be shown for the selected item in History every time.

**App information (please complete the following information):**
 - App Type = Native App
 - Postman Version = 7.30.1
 - OS: Windows Server 2019

**Comment by DannyDainton** [comment]
Hey @thetreythomas 

Thanks for reporting this issue 🏆 - We're tracking this internally and will update this thread once we have more information.

**Comment by DannyDainton** [comment]
Hey @thetreythomas 

We've just released a new version (7.31.1) which includes a fix for this issue.

Would you be able to confirm that you can see your history after updating, please?

**Comment by thetreythomas** [comment]
@DannyDainton

I updated to 7.31.1, and I was not able to reproduce the bug. Looks fixed to me. 

One extra question though...

How far back is this supposed to go? In this particular team workspace, I can see history going all the way back to August 19th. For August 19th and 20th, I see the API calls made in the history list, but no response. I suspect the "Save Response" toggle was not set until August 21st.

I have another team workspace where the history goes back to August 7th.

So I'm just wondering how far back Postman is capable of going for saved History, in the Postman App. Viewing from the website may show more history, but it lacks the detail the Postman app shows.

**Comment by DannyDainton** [comment]
Awesome!! Glad it's solved the issue for you 🏆

I don't actually know the answer to that question so I may need to refer to either @ritwijsinha or @ankitjaggi who might be able to provide that information.

**Comment by DannyDainton** [comment]
@thetreythomas as this solved your original issue, I'm going to close this out for now but I'm hoping we'll get you an answer to that question soon though.
