### ISSUE TITLE
Interceptor does not capture POST requests

### ISSUE THREAD

**Issue by inash** [a85/POSTMan-Chrome-Extension#897]
Just noticed that interceptor (0.2.8) does not capture POST requests. The Content-Type is application/json. Below is the original request headers from Chrome dev tools and from there it actually shows the request.

---
POST /example HTTP/1.1
Host: example.com
Connection: keep-alive
Content-Length: 193
Origin: https://example.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36
Content-Type: application/json
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
X-FirePHP-Version: 0.0.6
Referer: https://example.com/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Cookie: JSESSIONID=xxx

```
{a: 'a', b: 'b'}
```
---

**Comment by abhijitkane** [comment]
What version of Postman are you using?

**Comment by inash** [comment]
That's right. I had to remove the extension and then install it back again for the new version. Cheers.
