### ISSUE TITLE
Allow custom roles and permission with fork and merge feature.

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#8970]
It would be great if we have the ability to do the followings 
1. Make the reviewer mandatory during the merge in the Team workspace branch / Fork. 
2. Create an approver group within postman, so that it can be assigned as a reviewer.

**Comment by ankit-m** [comment]
We've added options to add merge checks. This allows you to enforce mandatory approvals. We will soon add options to add custom mergers.

This feature is only available on our Business and Enterprise tiers.
