### ISSUE TITLE
Postman is synchronizing and I cannot share my collection

### ISSUE THREAD

**Issue by imenosd** [a85/POSTMan-Chrome-Extension#8973]
Since this morning (new version 7.31.0) when trying to share a collection (updating a public link as I used to to before), the sync icon  remains blue, and it is not possible to share it. 
![error_postman](https://user-images.githubusercontent.com/70215162/91189444-bddbe380-e6f2-11ea-8a5e-901a831238a7.png)

See file attached with the error displayed when clicking on "Share Collection" option.

**Comment by DannyDainton** [comment]
Hey @imenosd 

Are you also able to share the environment details of your machine?

Could you log in to your account on the web view and see if that's syncing the changes for you https://go.postman.co - If so, you can update and share the links from there.

Other options would be to quit and restart the app on your machine to establish the connection again.

**Comment by postman-kenji** [comment]
Closing due to age of issue and response time. Please feel free to reopen this if this is still an issue @imenosd. Thanks!
