### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by rcodd** [a85/POSTMan-Chrome-Extension#8975]
would be nice to enable a lock on certain values in the environment variables.
We add them to share across tests, but if new tests are made incorrectly these values are overridden, they cause failures.

**Comment by vvs11** [comment]
@rcodd We have RBAC enabled on environments. You can assign roles editor or viewer roles to the users in your workspace. More documentation here: https://learning.postman.com/docs/sending-requests/managing-environments/#managing-environment-roles

**Comment by vvs11** [comment]
@rcodd closing this issue for now. Feel free to reopen if you have questions/concerns
