### ISSUE TITLE
UI is not response 30 seconds after opening app since update to 7.30.0

### ISSUE THREAD

**Issue by dmarra** [a85/POSTMan-Chrome-Extension#8977]
Upon opening up the app, after about 30 seconds the UI starts to become almost totally unresponsive. The issue persists in 7.31.0. I have since had to switch to a different product in the meantime because of how severe the UI issue is. 

Unsure what else I can supply to help diagnose the issue. please advise.

**Comment by qamib** [comment]
Starting today (8/26/20) I am also experiencing a consistent Postman crash happening 5-to-30 seconds after launching.

**Comment by Raj-postman** [comment]
Hi @dmarra @qamib - may I know if you see the loading state of the app or are you able to send requests for the first 30 seconds?

Also, could you try installing Canary  [from here](https://www.postman.com/downloads/canary/) and let us know if that helps?

**Comment by dmarra** [comment]
I _can_ send requests and use the app; it's not a loading screen. I can use
it even with the unresponsive UI, its just _extremely_ jerky, like, 5
seconds go by and then I see it update jerky.

Installed Canary and it remains responsive.

**Comment by qamib** [comment]
I also can post requests, and utilize Postman normally within the first 10-30 seconds of launching. Then it crashes.

I installed Canary as suggested and it appears to be functioning normally Canary does not crash.

**Comment by Raj-postman** [comment]
@qamib Glad to know that helped! In that case could you please try to clear cache for the Postman app as per [this doc here ](https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-)and let us know if that helps?

**Comment by Raj-postman** [comment]
@dmarra Would it be possible for you to send a screen-record of this case to help@postman.com with the title `GH-8977`. I find (https://www.loom.com) to be helpful for the same.

Also, try tweaking the "Max response size" from settings to 100 MB and see if that helps.

**Comment by pompan129** [comment]
This was happening to me as well. Maybe 30 seconds and then slower than molasses. And often crashes.I noticed the spinner in the upper right corner continuously rotates even when not making a request. 
![Screen Shot 2020-08-30 at 8 09 12 AM](https://user-images.githubusercontent.com/10966169/91662582-44e4df00-ea98-11ea-8b7c-5edd2aaf0e86.png)

I cleared the cache as suggested above. It did not help.
I installed Canary and that seams to be working fine.

**Comment by DonBakke** [comment]
I came across this thread after preparing to post my own complaint with Postman. Everything written above describes my own problems. I uninstalled and reinstalled the stable release to no avail. Postman just updated to 7.33.1 and it still exhibits the same problems. I finally installed 7.32.0-canary04 and I'm finally able to use Postman normally again. I'm running on Windows 10.

**Comment by DonBakke** [comment]
Follow-up: I was able to clear out my cache as per the instructions posted above and this seems to have helped.

**Comment by cfortune1** [comment]
I am having a similar issue on app version 7.27.1 on a macbook pro. Everything was fine until the last update. When I attempt to open new item within a collection, application response time is very slow (15-20s). Then once it opens, the data elements associated with the item takes another 10s to populate. I have attempted to reinstall to no avail. The app is unusable at this point. 

-- update: discovered that the update process has failed several times. Even when selecting update manually, no joy. I had to download the latest release and reinstall. Working now on 7.34.0.

**Comment by kamalaknn** [comment]
We have made several improvements to how Postman loads the collections in your workspaces in the recent releases. This should fix issues that might have caused sluggishness during the app launch. Do try out the latest version of Postman and let us know if you are still seeing any issues.
