### ISSUE TITLE
Don't create startmenu shortcut on update

### ISSUE THREAD

**Issue by smares** [a85/POSTMan-Chrome-Extension#8980]
**Is your feature request related to a problem? Please describe.**
I am organizing program shortcuts in a custom way and like to have things grouped in folders by software category. It's always a PITA that Postman keeps creating the Postman\Postman.lnk on update.

**Describe the solution you'd like**
The program shortcut should be created once during the first installation. On update, don't create any shortcuts.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DannyDainton** [comment]
Hey @smares 

Could you also provide details about the app version and your OS, please?

**Comment by smares** [comment]
Sure, OS is **Windows 10 x64 Version 2004** and Postman is currently at **7.31.1**, but I am having the mentioned "issue" since I am using Postman, so for at least a year.

**Comment by jviotti** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6604
