### ISSUE TITLE
Postman 7.31.1 macOS Runner - Recent runs are out of order

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#8981]
**Describe the bug**
When accessing runner in Postman 7.31.0 or 7.31.1 on macOS, the recent runs are out of order.

**To Reproduce**
1. Go to Runner
2. Look at the Recent runs
3. See the results being out of order

**Expected behavior**
Recent runs should be in order of the runs being triggered.

**Screenshots**
![image](https://user-images.githubusercontent.com/43671684/91299455-8411e800-e799-11ea-9182-730093fb8c84.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.31.0 and 7.31.1 
 - OS: macOS Catalina 10.15.6

**Comment by coditva** [comment]
Hey, @VicKetchup Thanks for reporting. 🙌 
I could reproduce this issue. Will update this thread with more info soon.

**Comment by dmchodnicki** [comment]
Experiencing the same problem on v7.31.1 from a Windows 10 laptop.  Thanks.

**Comment by KroezeC** [comment]
I've got same problem with Windows Laptop and Postman  v7.32.0

**Comment by coditva** [comment]
Hey everyone,
Just wanted to let you know that we've been working on an improvement where you can have the Runner open as a tab in the main window itself as a tab. 🤯 

You can also find the recent runs in the sidebar in History tab in correct order as well:

![image](https://user-images.githubusercontent.com/8445768/92718628-ac940780-f37f-11ea-9ea5-d64b36339d60.png)

If you would like to try this out, it's already available in [Postman Canary](https://www.postman.com/downloads/canary/) 🚀 

Do let us know your views and suggestions regarding this change!

**Comment by babenkovitaliy** [comment]
This is an issue on the Windows build. Are there any updates on getting this issue resolved? I do a variety of different automations and sometimes I have to review past automations, and this bug makes it extremely painful to do so.

**Comment by coditva** [comment]
@babenkovitaliy Sorry to hear that. Can to try out the latest [Postman Canary](https://www.postman.com/downloads/canary/)?

**Comment by timbochamp** [comment]
From my testing on macOS and Windows (as well as Ubuntu), this should now be resolved in the recent [builds](https://www.postman.com/downloads/)! Please feel free to reopen if the issue is persisting.
