### ISSUE TITLE
Postman duplicates parameter for array type fields after Importing OpenAPI documentation

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [a85/POSTMan-Chrome-Extension#8982]
**Describe the bug**
Postman duplicates parameter for array type fields. 
If I specify in OpenAPI 'example' propertie two or more values, then all my values are displaing, and if I specify only one, then the postman duplicates value.

**Screenshot**
![Postman duduplicates parameter](https://user-images.githubusercontent.com/19765202/91320849-a706c100-e7c6-11ea-82e8-9d0f7ebd8727.png)

**Expected behavior**
Why Postman duplicates parameter for array type fields if I spesify only one value?

**App information (please complete the following information):**
 - Postman Version v7.31.1
 - OS:  Ubuntu

**Comment by DannyDainton** [comment]
Hey @Morgunov-Vitaly 

Could you supply an example of your OpenAPI spec file so that we can recreate this issue locally, please?

**Comment by Morgunov-Vitaly** [comment]
> Hey @Morgunov-Vitaly
> 
> Could you supply an example of your OpenAPI spec file so that we can recreate this issue locally, please?

Hi!
I can only share the file with path description: https://yadi.sk/d/lsbGrJmVwKS0IQ

**Comment by VShingala** [comment]
@Morgunov-Vitaly Thanks for raising the issue.

This is the intended behavior. According to the API definition provided, it has query parameters which are of type: `array` and according to [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#style-values) default behavior for this case is `style: form` and `explode: true`.

This means each element in the array will be mentioned separately. See the corresponding [example](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#style-examples) for exact case in the specification for more detail.

You can mention `explode: false` specifically for parameters with type: `array` if you want to avoid duplicate parameters.
