### ISSUE TITLE
For a collection I created in my Team Workspace, I suddenly no longer have access to Manage Roles/Merge/Pull/Fork

### ISSUE THREAD

**Issue by rboren** [a85/POSTMan-Chrome-Extension#8983]
I created all the collections for my team in a shared workspace. We had someone import an exported copy for several of those collections into the same team workspace as they mistakenly thought they were in their personal workspace. 

Those that had permission to merge/pull from those collections no longer are able to do so.

![image](https://user-images.githubusercontent.com/70290573/91350900-5dfa4100-e7b5-11ea-928f-9bbbc6eadbed.png)

I am an admin for the workspace and I am not longer able to use the "Manage Roles" feature. 

![image](https://user-images.githubusercontent.com/70290573/91349091-cdbafc80-e7b2-11ea-98fa-ba93e4948d48.png)

When I use the Postman UI in my browser, I can see and click on that collection, but then see an error (screenshot below) stating that I do not have access to the item and "This collection belongs to another team. To access it, switch accounts" 

![image](https://user-images.githubusercontent.com/70290573/91348796-4ec5c400-e7b2-11ea-9e54-9874b06bf8fc.png)

Need some kind of resolution other than export everything and import to another workspace as we have a number of folks on the team working on changes that need to be merged in.

**Comment by ankit-m** [comment]
@rboren Can you email us the collection ID and workspace ID so that we can take a closer look at the issue? Email: help@postman.com

**Comment by rboren** [comment]
Will do and will send it from my team email account. Thanks!

**Comment by ankit-m** [comment]
This has been fixed.
