### ISSUE TITLE
Open API Response in a separate section

### ISSUE THREAD

**Issue by dharoda** [a85/POSTMan-Chrome-Extension#8986]
Currently, API Response is displayed in a window merged to the bottom part of Postman screen. But, it would be better if the API Response could have its own, independent section besides "Body" section so that we do not have to adjust the window size every time.

**Comment by DannyDainton** [comment]
Hey @dharoda 

Could you expand on the details of this request please - Images showing what you're currently seeing versus what you would like to see. 

Also include the environment details (App version / OS) so with know which platform you're referring too.

**Comment by dharoda** [comment]
Hi @DannyDainton , I am using Postman version - "Postman v7.30.1", OS = Windows 10, 62 bit
Please refer the screenshot below. Here, the response section, marked in Red is overlayed with the request section above. So, could it be possible to have an option to see this response section besides request section and not have it overlay the request section ?
![image](https://user-images.githubusercontent.com/70201894/91444319-3331ea80-e892-11ea-83cd-4eb272606c54.png)

**Comment by DannyDainton** [comment]
In the bottom right of that image, there is an icon/option, to place the view in '2 pane mode' which will place those next to each other.

Is that what you're looking for?

**Comment by dharoda** [comment]
This (2 pane mode) does help in some cases. But, it would be also nice to have a Single Pane View with an individual Response section, such that we need not adjust the window size by dragging it up/down (for single page view) or left/right (for 2 pane mode).
Or what would also help is if we can expand/collapse this section like an accordion. Right now, the accordion concept works in a single page view when I want to expand the response section (by clicking on any of the tabs in it when fully collapsed), but to collapse it, I still have to drag it all the way to the bottom so that I can see the Request section in a full screen view.

**Comment by coditva** [comment]
Hey @dharoda, I see your problem with not being able to view Request or Response with full screen size unless you drag the pane up or down. For making this easier, we have added a shortcut to allow easier and faster resizing of panes (in version `7.30.0` and above).

You can now scroll over the Request and Response while pressing the `Alt` key to quickly resize the pane. You can use this interaction to quickly hide the Request and have Response take the full height.

![Screen Recording 2020-08-25 at 11 04 25](https://user-images.githubusercontent.com/8445768/91129043-f06fe700-e6c6-11ea-9a3d-b28c2b3b5170.gif)

I hope this will speed up your workflow.

**Comment by dharoda** [comment]
Thanks @coditva That helps !
