### ISSUE TITLE
'Could Not send request' Error!

### ISSUE THREAD

**Issue by damian-sketch** [a85/POSTMan-Chrome-Extension#8988]
I am trying to run a GET request on Postman to this URL , https://codeserver-framework-{16571}.devfactory.com/api/v2/repositories/summary/?groupBy=day but I keep getting faced by this error

![postman](https://user-images.githubusercontent.com/63429298/91485000-9d9a5900-e899-11ea-98d6-c584d6bc8515.PNG)

**Comment by DannyDainton** [comment]
Hey @damian-sketch

Could you also include your environment details please?

Is there any other information you can provide about the endpoint that you're hitting?

**Comment by damian-sketch** [comment]
This is the environment http://10.69.11.89:16571/. Consider using a VPN to access it.

**Comment by DannyDainton** [comment]
Could you also please share an image of the Postman console output when this error occurs. 

You should be able to navigate to it by pressing the 'View in Console' in the error message.

We still require some details about you OS and the app version that you're seeing this issue on. 

Any other context and the endpoint itself would also be helpful as we try to debug what's happening for you.

**Comment by mohitranka** [comment]
@damian-sketch It appears that the url is not being resolved from inside of your VPN appropriately, and I cannot access the URL from the public network. Can you share if you are facing the problem on a publicly accessible URL?

**Comment by damian-sketch** [comment]
hey @mohitranka @DannyDainton. I realized I have been using the wrong environment format the whole time.
![postman](https://user-images.githubusercontent.com/63429298/91977153-dd928d80-ed2a-11ea-9f54-8c186fe7e2d5.PNG)
This should work now.

**Comment by damian-sketch** [comment]
Hey @mohitranka @DannyDainton
![postedit](https://user-images.githubusercontent.com/63429298/91977469-64e00100-ed2b-11ea-9952-92683b96d812.PNG)
. The problem was actually caused by using the wrong environment name in the URL. 
 
Replacing the current URL with http://codeserver-framework-qa.devfactory.com/api/v2/repositories should work. 
Also, set these headers:
 Accept: application/json
Content-Type: application/json.

Cheers.

**Comment by DannyDainton** [comment]
Are we good to close this out now @damian-sketch ?

**Comment by damian-sketch** [comment]
Yeah sure

**Comment by pauloggdev** [comment]
This has already happened to me I had to run my server again
