### ISSUE TITLE
Account timed out and cannot get back in 

### ISSUE THREAD

**Issue by cassnapper** [a85/POSTMan-Chrome-Extension#8994]
![postman](https://user-images.githubusercontent.com/69794856/91553980-2e1e7b00-e926-11ea-83e5-2cc33fbb3236.png)

**Comment by DannyDainton** [comment]
Hey @cassnapper 

Unfortunately, on that information alone it's going to be super difficult to help you.

Could you drop us a message to help@postman.com from your registered account email and I'm sure that we can take a look at what's happening there and get you all sorted.

**Comment by SabriH10** [comment]
hey @cassnapper ,

Just wanted to follow up here. Were you able to reach out to help@postman.com for us to help investigate?

**Comment by ghost** [comment]
@cassnapper Could you tell what is happening when you are trying to log back in?

**Comment by cassnapper** [comment]
This is all good now Suraj thanks
