### ISSUE TITLE
postman freezes while sending  GET request

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#8995]
I have tried to make a get request to my backend but postman continuously shows **sending request** forever. I thought it will take time to load & i waited for more than 1 hour for few bytes of data but still it kept showing _sending request_ .

I have tried to make get request [www.google.com](url) just to check whether anything comes up in screen but still it showed sending request.

So i created, a link using **ngrok** & asked my friend to check. He actually got the output which means my backend is working properly. So, I request you all to please help me in this.

Also, I am attaching an image file in that you will find a link in url which is **valid for 6 hours** even you can check on your system.

<img width="1436" alt="Screenshot 2020-08-28 at 5 51 47 PM" src="https://user-images.githubusercontent.com/42679215/91560319-4bb80880-e957-11ea-9cfa-077dbdd75f8d.png">

**Comment by ahcode0919** [comment]
@borbhuiyagulsan this can happen if the Postman agent isn't connecting properly. Is the PostmanAgent updated to the current version and running?

If it is and you're still seeing the problem could you respond with your browser and its version so we can try to replicate the issue.

**Comment by borbhuiyagulsan** [comment]
<img width="113" alt="Screenshot 2020-08-29 at 8 17 12 AM" src="https://user-images.githubusercontent.com/42679215/91626840-1dc2da80-e9d0-11ea-9a76-ded9debb7c50.png">

@ahcode0919 are you speaking about above details ?
If no, then could you please say me how to check the version on mac?

**Comment by ghost** [comment]
> @borbhuiyagulsan this can happen if the Postman agent isn't connecting properly. Is the PostmanAgent updated to the current version and running?
> 
> If it is and you're still seeing the problem could you respond with your browser and its version so we can try to replicate the issue.

@ahcode0919 Are you speaking about below details ?
If no, then could you please say me how to check version in mac?
<img width="173" alt="Screenshot 2020-08-29 at 8 17 12 AM" src="https://user-images.githubusercontent.com/42679215/91626876-6f6b6500-e9d0-11ea-80e1-11da7007a6db.png">

**Comment by ghost** [comment]
@ahcode0919  It's been 4 days there is no update from your end ?

**Comment by xk0der** [comment]
> If it is and you're still seeing the problem could you respond with your browser and its version so we can try to replicate the issue.


@borbhuiyagulsan I think @ahcode0919 was asking for the Browser version, so if you are on Chrome, that would be `Chrome > About Google Chrome`

<img width="309" alt="Screen Shot 2020-09-01 at 4 44 02 PM" src="https://user-images.githubusercontent.com/21366/91795666-58e43880-ec72-11ea-99e6-d2cda4a5dc3e.png">

If you are using Safari by any chance, do try out other browsers to make sure it's not a browser-related issue.

Also, try sending the request using the Postman native app, it can be downloaded from here: https://postman.com/downloads
That should help us understand if the issue you are facing is network related.

**Comment by ghost** [comment]
@xk0der   @ahcode0919 

Still it doesn't work, I have tried all possible ways. 

<img width="448" alt="Screenshot 2020-09-02 at 12 49 56 PM" src="https://user-images.githubusercontent.com/42679215/91943876-e24f4580-ed1a-11ea-9623-1396c17fa653.png">
