### ISSUE TITLE
Improve UX interface

### ISSUE THREAD

**Issue by sberthu** [a85/POSTMan-Chrome-Extension#8997]
Please, avoid to replace/add/move buttons at the different states of treatments. 
Is is not better to simply disabled or enabled buttons dependening of the state of the app?
Now, when your test is over, the "STOP RUN" button is replaced by a "Retry" button and if you push button too late, you restart the test and lost your test data :(
Thank you for that and have a good day!

**Comment by DannyDainton** [comment]
Hey @sberthu

It's hard to tell from this if it's a feature request or you're raising an issue. 😁

Could you expand on the areas that you feel need attention and provide screenshots and an explanation for each one please.

Also, which version of app are you using? This would be really helpful as we are continously upgrading and improving the app for our users.

**Comment by sberthu** [comment]
Hello
thank you for your reply
I use the  v7.31.1 version, which is actually the last.
Here is a picture which can help you to better understand (see bottom).
When you start a job with the RUN button, you have the  red button under
your mouse cursor which is the "STOP RUN" button. perfect.
But if your script has a bug, you can stop the script pushing the "Stop
Run" button, that's ok.
But if you try to stop your script but it has just reached its end, the
"Stop Run" button has been replaced by the "Retry" button, and you are ok
for a second test (and lose your logs in the main window).
It is not a very serious bug, but it is very frustrating to have an UI
interface which changes in the time (you can compare this to these
websites which have a  big banner which replaces the link you'll want to
click, just at the bad moment... you know?)
Thank you for your interest and for your software which is very powerful.
Sylvain

[image: UX-issue.png]

Le sam. 29 août 2020 à 19:37, Danny Dainton <notifications@github.com> a
écrit :

**Comment by DannyDainton** [comment]
Hey @sberthu 

Not sure if it's because you replied via email but the image didn't get uploaded to Github, are you able to share that view a browser?

I'm not sure I follow you about losing the logs or the data from the previous collection runs as those are stored in the Run Results.

**Comment by DannyDainton** [comment]
Hey @sberthu  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
