### ISSUE TITLE
Cannot upload video with upload file

### ISSUE THREAD

**Issue by slomil** [a85/POSTMan-Chrome-Extension#8998]
I am not sure how to upload video, since don't know if video formats are supported by Postman, and can't find that information anywhere.
Thank you in each case:)

**Comment by DannyDainton** [comment]
Hey @slomil

It's difficult to get the full context of your question with that details that you have provided. 

If you're talking about uploading files for a specific POST request - That can done via the `form-data` option. This all depends on how the endpoint needs the data though.

https://learning.postman.com/docs/sending-requests/requests/#form-data

We have a Postman community fourm that seems like the perfect place for this question, you will be able to explain what you're trying to achieve in alot more detail.

https://community.postman.com

I'm going to close this question and hope to see you over there 🚀
