### ISSUE TITLE
Export/Import collection v2 and v2.1 seems broken

### ISSUE THREAD

**Issue by nandyc** [a85/POSTMan-Chrome-Extension#9001]
Hi Team,

I had to bulk update few URL's in my collection. I exported it first using the recommended Collection v2.1 method. Made changes and tried to import it again. Couple of URL's were updated but somehow most of the URL's still showed previous old parameters.
I repeated this process number of times. I even uninstalled the application, cleared Temp cache, cleared AppData/Roaming/Postman folder, reinstalled application and still the same result.
I tried to use the Collection v2 and performed all the above steps, still I faced the same issue. All old URL's were not going away.
Then finally Collection v1(deprecated) once worked for me.

Can you please see if this can be fixed.

**Comment by DannyDainton** [comment]
Hey @nandyc 

Could you provide details about the version of the app that you're using and your OS, please?

Do you have an example of a collection that you could share that shows the same behaviour or could you walk us through the steps with images to show us what you did when editing the collection file?

The more details that you can provide will help us to reliably recreate the issue locally, about figure what's happening.

**Comment by nandyc** [comment]
Hi Danny,

Thank you for your prompt response. I am using  v7.31.1 on a Windows 10 machine. 
I will not be able to share a collection due to legal issues as it's client proprietary. But I can walk you through the steps, and please refer to attached screenshot for few details.

**My use case** : 
I have a collection of API's that uses a {{base_url}}**/test/**"some_endpoint". And there were around 250+ calls that were using this URL. My task was to update all the urls to {{base_url}}**/**"some_endpoint". 

**What steps I performed:** 
Step 1 : I started by updating few of them manually, for which I quickly realized is not an optimal solution. Then I took an export of the collection using the recommended v2.1 
Step 2 : I opened the generated .JSON file with a text editor, replaced "/test/" with"/" saved the file. (_refer screenshot points 1 and 2_)
Step 3 : Opened Postman, clicked on Import and imported the collection as a new collection. And I ran a few get calls. I noticed that few of them were failing and when I debugged those, I found that "/test/" was still appearing in most of the URL's. (_refer point 3 in screenshot_)
_This was confusing for me as the .JSON file I just edited, did not contain any "/test/" string and still it was getting imported incorrectly in Postman_
Step 4 : I tried to clear out my previous collections, then uninstalled Postman, cleared out "%appdata%/Postman" folder, reinstalled application performed step number 3 again and still the same result.
Step 5 : I performed Step 1-3 again by exporting the collection using v2, and still got the same result.
Step 6 : Before losing hope, I tried exporting it with Collection v1 and this time it worked.

I hope these steps might help you with replicating or at least understanding the issue.
![postman-collection-issue](https://user-images.githubusercontent.com/8313016/91736573-832eeb00-ebcb-11ea-9fb8-730621b3b3a0.jpg)

**Comment by DannyDainton** [comment]
In the image with number 2 on it, I can see that the `path` array still has the value 'test' - does it remove that from the final URL, in the imported collection, if that's also removed?

**Comment by nandyc** [comment]
Hi Danny,

No, it remains intact as I was particularly replacing only `'forward-slash'test'forward-slash'` string.

**Comment by DannyDainton** [comment]
I understand that but where you have replaced that within the URL, there is a
`path` array below that, with that 'test' value still there. As it's still there, the
URL will remain the same after the import.

I checked the same locally and saw both what you were seeing when removing
just from the URL and the desired behaviour when removing both values.

**Comment by nandyc** [comment]
Ohh, now I got your point !!!
If I need to update URL I need to remove it from path array too. That's some extra work :(. Am I correct.
And this was missing in v1 schema.

![image](https://user-images.githubusercontent.com/8313016/91754188-a0bd7e00-ebe6-11ea-9c37-efdb5f618bc5.png)

**Comment by DannyDainton** [comment]
I'm not sure what your usecase is and the need to replace those values away from the app. There is a global find and replace option in the app.

I wouldn't recommend using v1 for any export and it's not supported.

Can you confirm that removong both values gives you the desired outcome?

**Comment by nandyc** [comment]
Hi Danny,

Thanks I just found the 'find and replace' option in the app itself, didn't know about this earlier. I might use this going forward !
And yes, I tried removing both the values, i.e. from URL and from PATH array and it is now importing correctly.

**Comment by DannyDainton** [comment]
It's a great feature!! 🚀

As you're all sorted, I'm going to close this issue. 🏆
