### ISSUE TITLE
Ability Share/embed a collection via postman api

### ISSUE THREAD

**Issue by ramith** [a85/POSTMan-Chrome-Extension#9007]
**Is your feature request related to a problem? Please describe.**
We are working on a product which want to allow users to host their applications/apis.
And then allow users to create postman collections/requests run them against the application/api.
However, to make surrounding user experience seemless I was looking at the possibility of invoke postman-api to embed/share a collection. apparently there is no endpoint to do this.

**Describe the solution you'd like**

To have a endpoint such as:
```
https://api.getpostman.com/collections/{collection_uid}/share
```

- with a `post` I could save current content of the collection in postman server to run and it will return a `collection-id` for the saved content ( same as in GUI) and optionally give me a link to invoke when I want to `run in postman` 
- with a `put` I could update the saved content.  

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by DannyDainton** [comment]
Hey @ramith

Would you be able to elaborate more on what the current functionality of the `Run In Postman` button, isn't doing right now. 

https://learning.postman.com/docs/publishing-your-api/run-in-postman/introduction-run-button/

Just trying to establish the full context of your feature request. 😁

**Comment by ramith** [comment]
Happy to explain!

Currently, if someone wants to make a collection available for `Run In Postman` she has to manually 'share/embed' from postman GUI and then embed the javascript (or markdown). This workflow is intended (and is fine) for an end-user of postman. 

On the other hand, our product will allow its users to host an API. At some point, the user may choose to create postman collection(s) for her application. It could be for her usage and/or for her application's users.  Now, we could generate a set of requests based on her application logic in her postman collection. 

Once requests are placed in a collection, we could show the `Run in Postman` button against it (in our GUI). The user clicks on the button and the browser navigates to postman GUI. From there onwards, the postman can do its magic by testing her API/application. This cycle can keep happening throughout the development cycle of her application and beyond.

The last part of this scenario to work requires the ability to share a collection (with its current content) via the postman-api.

**Comment by ramith** [comment]
@DannyDainton any updates on this?

**Comment by DannyDainton** [comment]
Hey @ramith

No current updates on this feature request at the moment.

**Comment by ramith** [comment]
@DannyDainton any updates?

**Comment by DannyDainton** [comment]
Hey @ramith,

No additional updates for this feature request - The thread will be updated once more information is available.

**Comment by ramith** [comment]
@DannyDainton its been a while and I wanted to check if you guys have decided anything on this?

**Comment by davidespihernandez** [comment]
Hi, @ramith!
In Postman v10 we released a new feature to share a collection via Postman API. Now, when you click on Share in the collection menú, you can see a new option in the modal window "Share via API":

<img width="624" alt="Screenshot 2023-01-18 at 12 03 51" src="https://user-images.githubusercontent.com/2665033/213155949-a3148799-a11b-4acb-9742-43bff6ea517e.png">

You have to generate an access key using the UI, and that access key can be used to retrieve the collection using the Postman API.

Hopefully, that's useful for you.

**Comment by davidespihernandez** [comment]
@ramith 
Sorry for the delay.
So, if I understand correctly, you want to generate a link that, given a collection UID, takes you to a Postman API collection (in the Postman website). Is that correct?

**Comment by cybertheory** [comment]
Yes! I am looking for this too and am surprised it's not more available. Its an awesome use case.
My users at www.jetski.ai create a rest API via a no code form. I want to generate a button for the user to open up an api endpoint and use Postman as an external playground. This would be an awesome addition and would allow users to immediately start interacting with the infrastructure they create. The idea is to allow us as devs to autofill fields in postman UI via a link. So the user clicks a button and it takes us to the app or web editor and autofills endpoint and body fields for example.

bump.

**Comment by DSchau** [comment]
Hey @cybertheory we'd love to meet up to learn more about what you're thinking.

Want to schedule some time with me so we can learn more? https://app.reclaim.ai/m/dschau/quick-meeting

**Comment by davidespihernandez** [comment]
Hi! You can build this URL to access a collection in the web UI, given the collection UID.

```
https://postman.co/collections/{uid}
```

The web will redirect, after authentication or team selection, to the collection in the Postman UI on the web.

**Comment by ramith** [comment]
Thank you.
