### ISSUE TITLE
Setting global variable value automatically from response

### ISSUE THREAD

**Issue by miklosgergely** [a85/POSTMan-Chrome-Extension#9008]
**Is your feature request related to a problem? Please describe.**
Currently I can't channel some data from the response automatically to a global variable.

**Describe the solution you'd like**
It would be great to have something like be able to declare that the response for this call would be a json, and the value of the field xxx should be the new value of the global variable yyy.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DannyDainton** [comment]
Hey @miklosgergely 

Are you able to expand on and explain your usecase in a bit more detail, please?

What's currently not working for you?

**Comment by miklosgergely** [comment]
Hi @DannyDainton 

A typical use case is this: I'm sending out a post request, and the response is a json, that looks like this:

`{
    "session_id": "9f5c3efcda26e54498ca38e7ea966e8d"
}`

Now I can select the session_id value, right click on it, and in the Set: Globals menu item I can assign this value to the global variable sessionId, which I'm referencing in other calls. It would be nice though to have a feature which would allow me to declare a mapping of session_id -> sessionId, i.e. from the field of the response json to the global variable automatically, thus I shouldn't have to make this click. It would be comfortable, and also prevent me from accidentally assigning the value to another global variable in the list, which causes quite a mess.

**Comment by DannyDainton** [comment]
From the `Tests` tab for that request - By adding this, it would automatically store that value as the variable:

```
pm.globals.set("session_id", pm.response.json().session_id)
```

More information about the `pm.*` API:

https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/

**Comment by miklosgergely** [comment]
Thank you @DannyDainton , it is working fine!

In my opinion you should consider renaming Tests, as it was not suggesting to me that I could place a command there to fill a global variable.

**Comment by DannyDainton** [comment]
The main purpose of that tab would be to add `Tests` to your request's response but it can also be used to do several other _post_ request sending actions like setting variables. 

I'm going to close this issue out as this seems to be doing what you're feature request is referring too.
