### ISSUE TITLE
Ability to filter the response of get all collections api endpoint.

### ISSUE THREAD

**Issue by ramith** [a85/POSTMan-Chrome-Extension#9013]
**Is your feature request related to a problem? Please describe.**
When I make a request to `https://api.getpostman.com/collections` it give me all the collection that user has access to.
However there seems noway I could filter the response by workspace. 
This seems an omission given that when I creating a collection I could pass a `workspace id` as a query parameter. 

**Describe the solution you'd like**

`https://api.getpostman.com/collections?workspace={{workspaceId}}` should return only collections attached to workspace specified.

**Describe alternatives you've considered**
To achieve the desired outcome we can do following:

1. invoke https://api.getpostman.com/workspaces/{workspace-id}
2. retrieve the content of extractable from json path ‘$.workspace.collections[*].uid’
3. invoke https://api.getpostman.com/collections/{collection-uid} for each UID I got from step (2).

Now thats a lot of network calls which I would like to avoid.

**Additional context**
N/A

**Comment by ramith** [comment]
@vvs11 any updates on this?

**Comment by ramith** [comment]
@vvs11 any updates?

**Comment by ramith** [comment]
Hi @giridharvc7 its been a while so I thought I might check on any updates? :)

**Comment by bpedro** [comment]
Hi @ramith,

Thank you so much for your patience. We are considering implementing the feature that you're requesting.

I will share any updates here.

**Comment by davidespihernandez** [comment]
Hi, @ramith!

There's a `workspace` querystring filter that can be applied to the `GET collections` endpoint. You can find the documentation here: https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-fa95fa93-5aa8-4146-94a6-bfebc1a578b4

Thanks for your patience.

**Comment by ramith** [comment]
Thanks @davidespihernandez ,much appreciated !
