### ISSUE TITLE
Text overflowing and circles becoming ellipses in collection runner run results window

### ISSUE THREAD

**Issue by FCulig** [a85/POSTMan-Chrome-Extension#9016]
**Describe the bug**
In the collection runner window under run results, response code text overflows to other tests, and circles become ellipses when the window is narrowed. (See attached images for better understanding)
![text overflow in run results in collection runner - smaller window](https://user-images.githubusercontent.com/36075622/91991571-5564b600-ed33-11ea-8129-2c6100485d64.png)
![text overflow in run results in collection runner - wider window](https://user-images.githubusercontent.com/36075622/91991575-5695e300-ed33-11ea-8e0b-411369b1d30e.png)

**To Reproduce**
Just run a collection with collection runner and narrow down the window

**Expected behavior**
The text should not overflow and circles should not deform.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.31.0
 - OS: Windows 10 Enterprise version 1909 build 18363.592

**Comment by coditva** [comment]
Hey @FCulig, thanks for writing in!
If you're bothered by this (I was too), then you may like the changes that we're doing to Runner. You can try these out in [Postman Canary](https://www.postman.com/downloads/canary/). We have integrated the whole Runner window inside a tab and made significant updates to the UI.

![image](https://user-images.githubusercontent.com/8445768/92001007-ccae4000-ed5b-11ea-9072-81065f23d83f.png)

Do write to us about what you think. It will help us make it even better! 🚀
