### ISSUE TITLE
Can shared public link be sceured

### ISSUE THREAD

**Issue by svarshney2311** [a85/POSTMan-Chrome-Extension#9018]
Hi,

I have shared my collection using 'GetPublicLink' like below. Can this be secured within our Teammates only? I dont want this link to be for public use as it has some sensitive data.

https://www.getpostman.com/collections/XXXXXXXXXXX.

Thanks,
Shailendra

**Comment by DannyDainton** [comment]
You can share collections with other team members and work collaboratively on them, right from the Team Workspace. 

https://learning.postman.com/docs/collaborating-in-postman/collaboration-intro/

If you did want to use a link, the best, easiest and most secure way to share your collections would be to use the Postman API with an API Key.

https://documenter.getpostman.com/view/631643/JsLs/

This gives you a number of benefits, it's secure and controlled by you being the main one but it's also the most update version of the collection. The public link is just a snapshot of the collection when the link was created.

**Comment by svarshney2311** [comment]
Hi,
 I have created a API-key and stored in collection without passing actual value, but still I am able to execute the API without 401 error.Please suggest me what I am missing here. I did not save API key in any environment varaiable or anywhere

![image](https://user-images.githubusercontent.com/66395814/92032956-e4c09800-ed38-11ea-844b-e9757a1f39da.png)

![image](https://user-images.githubusercontent.com/66395814/92032913-d7a3a900-ed38-11ea-9997-ec98b2805e61.png)

**Comment by DannyDainton** [comment]
I'm not really sure what you're trying to call with the URL you have in that image. 

If you got the Postman API Key from https://go.postman.co/settings/me/api-keys you would be able to use it with _https://api.getpostman.com/collections_ for example. 

As this is not a functional issue with the app, I'm going to close this out and suggest you raise this question over in the community fourm.

https://community.postman.com 

It will be a better place to discuss certain flows like this one.

**Comment by svarshney2311** [comment]
Hi,
I got the API key  and added to header with avariable, but still I am not getting unauthorized errror as I did not save api key anywhere in the environment. I was expecting 401 as I have API-key in the header but actual value is not availble

Url -  I passed url in prereq.so this is fine.
