### ISSUE TITLE
Sync History with Computers?

### ISSUE THREAD

**Issue by Dastano** [a85/POSTMan-Chrome-Extension#9022]
**Describe the bug**
Logged into Postman on fresh formated Computer, but sadly the History is only loaded partially, the main history, stays only available on the WEbsite Browse -> History

**To Reproduce**
Login to new Account and wait for History to be synced.

**Expected behavior**
Sync my whole history to the Desktop app or make it possible to export it.

**App information (please complete the following information):**

You are up to date! Postman v7.31.1 is the latest version.

**Comment by DannyDainton** [comment]
Hey @Dastano 

Would you be able to show us an example of this, please?

Are you seeing the same thing in the web version of the app -  https://go.postman.co/build ?

**Comment by Dastano** [comment]
On the Web Version, if I scroll down in my History, it loads the History fine. But on the Desktop App, there is like an Cap?
On WebApp I can go back over a few month, in the App, it is like 2 month at max.

https://imgur.com/a/yebi4Bp

**Comment by fermelone** [comment]
Same thing here, got a new computer from work, logged in with my account, I can't see the history from my previous postman desktop app. Doesn't seem to be syncing. 

Both macOS 10.15.7 (Catalina)
Both postman Version 7.34.0 (7.34.0)

**Comment by Dastano** [comment]
Yeah or just partially. Lets see.

**Comment by postman-kenji** [comment]
Closing this issue for now given age and response time. @Dastano @fermelone please feel free to reopen this if you are still encountering this issue in the latest version of Postman. Thanks!
