### ISSUE TITLE
Tests for empty response body

### ISSUE THREAD

**Issue by svarshney2311** [a85/POSTMan-Chrome-Extension#9023]
Hi ,
I have below test:

```javascript
pm.test("Verify the status and name"  , function () {
    var jsonData = pm.response.json();
     pm.expect(jsonData[0].name, "Name is not available").not.equal(null);
  });

``` 

for some situation we get valid response but in some situation, we get empty response . So I wanted to test "name" value should not be null in the response. When the response is Not null, in this case my tests Passed. But when get empty response, in this scenario, I am getting below error:

> Verify the status and name | TypeError: Cannot read property 'name' of undefined.

This is not a ideal test report. Instaed of this I wanted someting like that:(Valid assertion error)

Verify the status and name | AssertionError: Name is not available : expected undefined to not equal null.

How can I achieve this?

This is something handling type error and providing generic error.

**Comment by DannyDainton** [comment]
Hey @svarshney2311 

This seems like more of a question for the Postman community, could you raise this one on there, please?

https://community.postman.com

I'm going to close out this one and see you over there 😄
