### ISSUE TITLE
Formatting of XML in the text editor not respecting the indentation settings set 

### ISSUE THREAD

**Issue by pankajk07** [a85/POSTMan-Chrome-Extension#9024]
**Describe the bug**
The beautifying process for XML is not respecting the General indentation settings but instead adding 4 space every time.

**To Reproduce**
1. Go to General Settings
2. Set Indentation Count to 2
3. Switch to Raw Body Editor and change the type to XML
4. Add some XML content
5. Click on Beautify button 

**Expected behavior**
The XML should be formatted with 2 spaces as indentation.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/44100113/92124040-ee223100-ee1a-11ea-8595-7fbc2d51712b.png)
![image](https://user-images.githubusercontent.com/44100113/92124069-f37f7b80-ee1a-11ea-9764-04237b9e44f5.png)

**App information (please complete the following information):**
 - App Type Native and Web App
 - Postman Version 7.31
 - OS: macOS

**Additional context**

Originally reported in [here](https://github.com/postmanlabs/postman-app-support/issues/4117#issuecomment-686417818) by @andreypolyak

**Comment by pankajk07** [comment]
@andreypolyak We fixed this issue as part of `v7.33`. Please do try it out and let us know if you encounter any other issues.

**Comment by rudisills** [comment]
Please make 2 spaces the default instead of 4 spaces.

**Comment by arlemi** [comment]
@rudisills You can change that in your settings: 
![image](https://user-images.githubusercontent.com/5029719/116228118-c8042500-a74c-11eb-8072-7b0bf4b1a5e6.png)

**Comment by rudisills** [comment]
I appreciate your response to make sure I understand the feature.
The feature works as intended.

I'm suggesting that most customers would prefer the default indentation count to be 2 instead of 4. Four-line indentation wastes space visually -- especially in the Response panel which is only ~1/3 of the screen width and from my experience often wraps lines in output text (which are frequently long).

I'm suggesting changing the default from 4 to 2 for all new installs.

**Comment by arlemi** [comment]
@rudisills In that case I'd recommend creating a new feature request and see if other people feel the same, though to be completely transparent that feature has been out for 8 months and this is the first time we're hearing this. 😄

**Comment by pankajk07** [comment]
@rudisills To add to @arlemi's comment, before this setting was introduced the value of the indentation count was 4 and not configurable. Hence we kept the default value equal to 4 when we introduced this setting.
