### ISSUE TITLE
[CONFLICT] appears on original tab if a duplicated tab has changes

### ISSUE THREAD

**Issue by rohanahata** [a85/POSTMan-Chrome-Extension#9025]
**Describe the bug**
[CONFLICT] appears on original tab if a duplicated tab has changes

**To Reproduce**
1. Duplicate a tab
2. Try to change the name of the new tab
3. [CONFLICT] appears in the first tab. 

**Expected behavior**
Expect to be able to save duplicated tabs independently without links to the original. 

**App information (please complete the following information):**
 - Native App
 - Version 7.31.1 (7.31.1)
 - 10.15.6

**Additional context**

**Comment by DannyDainton** [comment]
Hey @rohanahata 

Just some context about how duplicating a tab works within the app. 

You might need to duplicate the request, from the Collection sidebar to achieve what you want. 

> Duplicating a tab does not mean creating a second request to the same endpoint—when you duplicate a tab any edits you make will affect the original request.

https://learning.postman.com/docs/getting-started/navigating-postman/#tabs
