### ISSUE TITLE
Postman Dashboard: 'Cancel' button is not functional under 'Create pull request' page

### ISSUE THREAD

**Issue by dish25** [a85/POSTMan-Chrome-Extension#9026]
**Describe the bug**
Postman Dashboard: 'Cancel' button is not functional under 'Create pull request' page

**To Reproduce**
Steps to reproduce the behavior under postman:
1. Create a collection(Example: "I am parent Collection") and add a request to it .
2. Create a fork(Click on kebab menu next to collection-->choose 'Create a fork' from the drop down menu) from the parent collection. Make some changes in fork collection's request(if required).
3. Now, click on Fork Collection's(Example: "I am Fork Collection") kebab menu(... three dots displayed next to the collection) and select "Create Pull Request" option.
4.  Notice that you would be navigated to 'Create pull request' page under postman web dashboard.
5. Click on 'Cancel' button and observe that 'Cancel' button is not functional.

Test Data:
Parent Collection Name: "I am parent Collection"
Fork Collection Name: "I am Fork Collection"

**Expected behavior**
'Cancel' button should be functional and on cancelling the pull request user should get navigated to the right page.

**Screenshots**
![Postman_CancelbuttonIssue](https://user-images.githubusercontent.com/69243634/92222819-31cd7700-eebd-11ea-945f-e8241d55aaeb.jpg)

**App information (please complete the following information):**
 - App Type: Desktop App
 - Postman Version : v7.31.1 
 - OS: Windows 7
- Chrome browser version: 85.0.4183.83

**Comment by ankit-m** [comment]
@dish25 thank you for pointing this out. Looks like the navigation fails in some scenarios. Will keep this ticket updated when we have fixed the issue.

**Comment by DannyDainton** [comment]
The PR workflows have now been brought into the app in V8. 

Closing this issue.
