### ISSUE TITLE
500Internal Server

### ISSUE THREAD

**Issue by ooohroel** [a85/POSTMan-Chrome-Extension#9029]
Hi,

trying to send data for our API but I got error 500Internal Server.

Can you help?

my version is : Postman v7.31.1

Thank you

**Comment by DannyDainton** [comment]
Hey @ooohroel

Not sure if there is much that we can do here as this feels more like an issue coming from the endpoint/API that's you're calling.

I'm going to close this issue out, it doesn't feel like a functional issue with Postman as that status code is being returned by the server.

Our awesome Postman community might be able to help you with this problem, if you wanted to raise a new thread on the forum.

https://community.postman.com
