### ISSUE TITLE
Imported runner results show incorrect stats

### ISSUE THREAD

**Issue by nils-work** [a85/POSTMan-Chrome-Extension#9030]
**Describe the bug**
Imported runner results show incorrect stats

**To Reproduce**
1. Run something in the Runner with some failed **and skipped** tests
2. Click on 'Export Results'
3. Go back to Collection Runner and click on 'Import Runs'
4. Runner report shows failed tests (**Update**: these are actually skipped tests) but the summary of tests at the top shows '0 FAILED'

**Expected behavior**
Summary should show correct number of **passed, skipped and failed tests**.

**Screenshots**
![image](https://user-images.githubusercontent.com/60594671/92361911-7f9ee500-f132-11ea-8c43-1ce4cdedc3c7.png)

**App information (please complete the following information):**
 - Native App - Collection Runner
 - Postman Version 7.31.1
 - OS: win32 10.0.1... / x64

**Additional context**
Report summary issue also related to [issue 8512](https://github.com/postmanlabs/postman-app-support/issues/8512)

**Comment by DannyDainton** [comment]
Hey @nils-work,

I've been trying to recreate the issue but I'm failing 😬 - Maybe it's the collections that I'm running.

Do you have any scaled down collections or run results exports that we could use to reliably reproduce this issue?

Any other contextual information would be awesome too. Are the skipped tests now showing up as fails in the main runner results window?

**Comment by nils-work** [comment]
Hi @DannyDainton 

Sample collection is below. 

This is the report when I first run the test (note that skipped tests are slightly misleading when [marked as 'Pass'](https://github.com/postmanlabs/postman-app-support/issues/8512))

![Runner report](https://user-images.githubusercontent.com/60594671/92546155-429f3380-f295-11ea-866d-05b78e409cdf.PNG)

This is after I export the results, then import them again. Skipped tests are shown as failed -
![Runner report - after export and import](https://user-images.githubusercontent.com/60594671/92546187-521e7c80-f295-11ea-903b-53377bd3fce7.PNG)

Collection -
`{"info":{"_postman_id":"1234","name":"Test collection","schema":"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},"item":[{"name":"Test A","event":[{"listen":"test","script":{"id":"fedb7032-a48a-4629-9ef8-2447a84d40ff","exec":["pm.test('PASS A1');\r","pm.test.skip('SKIP A2');\r","pm.test('FAIL A3', function(){\r","    pm.expect.fail('FAIL A3');\r","});"],"type":"text/javascript"}}],"request":{"method":"GET","header":[],"url":{"raw":"https://postman-echo.com/get","protocol":"https","host":["postman-echo","com"],"path":["get"]}},"response":[]},{"name":"Test B","event":[{"listen":"test","script":{"id":"49bf4cdb-05c1-4523-b414-95fb67d62431","exec":["pm.test('PASS B1');\r","pm.test.skip('SKIP B2');\r","pm.test('FAIL B3', function(){\r","    pm.expect.fail('FAIL B3');\r","});"],"type":"text/javascript"}}],"request":{"method":"GET","header":[],"url":{"raw":"https://postman-echo.com/get","protocol":"https","host":["postman-echo","com"],"path":["get"]}},"response":[]}],"protocolProfileBehavior":{}}`

Runner results -
`{"id":"5678","name":"Test collection","timestamp":"2020-09-09T01:29:41.896Z","collection_id":"077bc49b-db66-4bb9-b842-c42d8692c084","folder_id":0,"environment_id":"0","totalPass":4,"totalFail":2,"results":[{"id":"76ebd26c-1e09-4403-b47a-dad76ba43fbb","name":"Test A","url":"https://postman-echo.com/get","time":1213,"responseCode":{"code":200,"name":"OK"},"tests":{"PASS A1":true,"SKIP A2":false,"FAIL A3":false},"testPassFailCounts":{"PASS A1":{"pass":1,"fail":0},"SKIP A2":{"pass":0,"fail":0},"FAIL A3":{"pass":0,"fail":1}},"times":[1213],"allTests":[{"PASS A1":true,"SKIP A2":false,"FAIL A3":false}]},{"id":"ce2a2e8f-69d0-4c5f-80c2-787dfc0dddb5","name":"Test B","url":"https://postman-echo.com/get","time":1219,"responseCode":{"code":200,"name":"OK"},"tests":{"PASS B1":true,"SKIP B2":false,"FAIL B3":false},"testPassFailCounts":{"PASS B1":{"pass":1,"fail":0},"SKIP B2":{"pass":0,"fail":0},"FAIL B3":{"pass":0,"fail":1}},"times":[1219],"allTests":[{"PASS B1":true,"SKIP B2":false,"FAIL B3":false}]}],"count":1,"totalTime":2432,"collection":{"requests":[{"id":"76ebd26c-1e09-4403-b47a-dad76ba43fbb","method":"GET"},{"id":"ce2a2e8f-69d0-4c5f-80c2-787dfc0dddb5","method":"GET"}]}}`

**Comment by DannyDainton** [comment]
Thanks for that information @nils-work !! 🏆  It really helped to replicate the issue.

I've raised a bug for this so that our team can take a closer look at what's going on - We will update this thread once we have have more details to share.

**Comment by timbochamp** [comment]
Hi @nils-work , this should be resolved on the latest build with grey visuals for skipped tests as seen in the screenshot below:
![Screen Shot 2021-03-10 at 5 02 53 PM](https://user-images.githubusercontent.com/4521134/110698328-e37a9700-81c3-11eb-97d1-a7b7f11fb7fe.png)

Please feel free to reopen this issue if you're still seeing issues!

**Comment by nils-work** [comment]
Hi @timbochamp 

Thanks to the team for fixing that bug.

Would it be possible to also show the total number of tests and 'Skipped' counts in the top title bar as well? 

In a large collection run with some tests being skipped based on conditions, it would be helpful to filter to the specific skipped tests as well as seeing the count to see how many conditions have changed.

Something like this -
![image](https://user-images.githubusercontent.com/60594671/110705175-1d8e7c00-824a-11eb-8b88-48de7054a589.png)

Thank you

**Comment by timbochamp** [comment]
@nils-work I think I spoke a bit too soon in my initial comment where I am seeing the same behaviour as before when I import the collection run in terms of skipped tests being shown as failed:
![imported collection wrong colour for skip](https://user-images.githubusercontent.com/4521134/110823939-f1cebe80-8268-11eb-886e-8a4b99aa35ec.png)
I reopened this issue and we're chatting internally to have this addressed!

That's a good suggestion for sure to have the skipped requests filterable. I believe that's being tracked in #9590

**Comment by malvikach** [comment]
Hi All,

This bug is now resolved. Please update to Postman version 10.9 to see the fix.

<img width="1039" alt="Screenshot 2023-02-06 at 6 07 43 PM" src="https://user-images.githubusercontent.com/89449769/216973853-bdfdb2f6-fb47-43ba-9c44-02191a82429d.png">


As noted above, the skipped tests now appear correctly. Please do let us know if you see any other problems in the imported run results. We will be tracking this issue as closed. 

Cheers!
Malvika
