### ISSUE TITLE
team members don'ts see my  collections 

### ISSUE THREAD

**Issue by BartVanRaemdonck** [a85/POSTMan-Chrome-Extension#9032]
**Describe the bug**
I've created collections in the team workspace but my team members don't see those new collections.

**To Reproduce**
1. Make a new collection in the team workspace
2. Ask a team member if he sees that new collection

**Expected behavior**
The team member sees the new collection

**Screenshots**
![Picture 117](https://user-images.githubusercontent.com/11335721/92392827-32654800-f11f-11ea-930b-b96a2fabb141.jpg)
![Picture 118](https://user-images.githubusercontent.com/11335721/92392850-37c29280-f11f-11ea-918f-f3315d130e21.jpg)

**App information (please complete the following information):**
 - Chrome App, Native App
 - Postman Version [e.g. 7.31.1]
 - OS:macOS ]

**Comment by Raj-postman** [comment]
Hi @BartVanRaemdonck - one thing I would cross-check is to see if my application is synced. The sync icon should help you know this. Click on "Sync Icon" {Orange = Synced, Blue-Spinning = Syncing} 

![image](https://user-images.githubusercontent.com/47771757/92434917-af93ca00-f1be-11ea-93a6-fc711d8ae826.png)

Once done, navigate to [Web-dashboard](https://go.postman.co/me/collections) and see if the collection is present there and if team member is able to locate the same. Let us know how it goes and we will take it from there.

**Comment by BartVanRaemdonck** [comment]
Hi @Kurmavathar,

We already tried that but still my other team member doesn't see any new
collection I create in the team workspace.

KR,

Bart

Op di 8 sep. 2020 om 07:07 schreef Kurmavathar <notifications@github.com>:

**Comment by Raj-postman** [comment]
Thank you @BartVanRaemdonck. In that case, could you please [submit a ticket to Support](http://support.postman.com/) along with the screenshots of the complete app (Personal and Team Member view) and we will further take a look at it?

**Comment by BartVanRaemdonck** [comment]
Hi Kurmavathar,

I just signed in with the other team account and I found the problem.
My team members were just working in their workspace.
Sorry for the time and effort.

KR,

Bart

Op di 8 sep. 2020 om 10:22 schreef Kurmavathar <notifications@github.com>:

**Comment by Raj-postman** [comment]
@BartVanRaemdonck No problem. Glad to know you managed to resolve this issue :)
