### ISSUE TITLE
Feature request: Send Authorization header when fetching GraphQL schema

### ISSUE THREAD

**Issue by leehambley** [a85/POSTMan-Chrome-Extension#9033]
**Is your feature request related to a problem? Please describe.**

My GraphQL schema introspection relies on having a user's JWT present. The JWT contains a platform specific schema which describes which queries/mutations people can use. Part of that, is that describing the entire schema is a privilidge we don't expose to all clients. Additionally we use directives to hide and authenticate access to certain input types, args, queries, mutations, etc.

**Describe the solution you'd like**

I would love Postman to _at least_ show an error if the schema introspection fails (currently it shows a `(i) your schema has been refreshed`), preferably it would send the `Authorization` header related to the request page being viewed.

**Describe alternatives you've considered**

Currently we use GraphQLPlayground to render the documentation because Postman doesn't seem to send the authorization header.

**Comment by lxop** [comment]
Even without using the JWT to determine which bits of the schema to return, this would be very useful - in our case all calls need to be authenticated, so loading the schema just fails. This just looks like a bug at the moment, since all the other headers appear to be sent.

**Comment by frank-orellana** [comment]
I'm having this problem too, when I have the authorization defined in the collection, the Auto-fetch will fail to sync. If I define the authorization directly on the request, then it works, so I'm using that as a workaround for now but it would be really useful to have it working with the collection config. I think this is the same issue as #10773

**Comment by giridharvc7** [comment]
@lxop @frank-orellana @leehambley we've released a fix for this in 9.18.2. Feel free to open this if you still see this error.
