### ISSUE TITLE
Error Message: Could not open Postman

### ISSUE THREAD

**Issue by hcmehta** [a85/POSTMan-Chrome-Extension#9035]
I am unable to open Postman Tool.
It was working fine, but afterwards, i uninstalled it and installed it. Now it shows the error message as below:

AdapaterError:Malformed error from adapater:should always be an Error instance, but instead,got:
[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]

[Note: I am unable to upload the snapshot with the bug description]

**Comment by DannyDainton** [comment]
Hey @hcmehta 

What's the version that you're trying to install and on which Operating System?

**Comment by hcmehta** [comment]
Hi @DannyDainton 

Version : 7.31.1
Tool Setup Ref: Postman-win64-7.31.1-Setup
Operating System: Windows 10, 64 bits

**Comment by SabriH10** [comment]
Hi @hcmehta ,

Have you had an opportunity to try the following troubleshooting guidelines to see if it helps? Referenced here: https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-
Particularly regarding deleting local data and re-install the App. Please make sure to, before deleting anything, pay particular attention to the recommendations regarding steps to follow if you have a Postman account and are signed in as well as if you aren't signed in ( to help ensure you don't lose data of value ).

Let us know if this helps!

**Comment by postman-kenji** [comment]
Closing this issue for now given age and response time. @hcmehta please feel free to reopen this if you are still encountering this issue in the latest version. Thanks!
