### ISSUE TITLE
How to enable this textbox for JsonPath Expression input (in POSTMAN Tool) under "Visualize" tab?

### ISSUE THREAD

**Issue by hcmehta** [a85/POSTMan-Chrome-Extension#9036]
How to enable this textbox for JsonPath Expression input (in POSTMAN Tool) under "Visualize" tab?
I want to use JSONpath queries to filter data of Response Body in POSTMAN Tool.

![Query 1](https://user-images.githubusercontent.com/29515239/92486375-a419c080-f209-11ea-9f31-94e5ceb9f54f.jpg)

**Comment by DannyDainton** [comment]
Hey @hcmehta 

As that's a community created template, the best for this question would be over on our Community Forum. 

Would you be able to raise that in there, please?

https://community.postman.com/

**Comment by hcmehta** [comment]
I have posted into it
Ref: 
https://community.postman.com/t/how-to-enable-this-textbox-for-jsonpath-expression-input-in-postman-tool-under-visualize-tab/15689
