### ISSUE TITLE
Collection Runner inconsistently not recognizing "Find and Replace" variable changes

### ISSUE THREAD

**Issue by bbrashier** [a85/POSTMan-Chrome-Extension#9038]
**Describe the bug**
After using "Find and Replace" to update requests, some requests in Collection Runner do not recognize the change.

**To Reproduce**
1. Change a Collection variable name that is used as a parameter in a request or requests.
2. Use "Find and Replace" to update the requests in the collection that use the variable.
3. Run the collection or folder that contains the affected requests using Collection Runner.
4. A request or requests will fail.
5. Run the failing request individually (not in Collection Runner). Notice that it passes.
6. Run the request again in Collection Runner and it fails.
7. Look at the request in the console, and you can see that the old variable name was used in the parameters of the request.
8. Edit the request by adding a space in the variable name and save the change. Edit again and remove the space.
8. Run the collection or folder again that contains that request, and the test passes.

**Expected behavior**
After updating the requests with "Find and Replace", requests run in Collection Runner should recognize the variable change.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 7.31.1 
 - OS: macOS Catalina 10.15.6

**Additional context**
It seems to be inconsistent. Other requests recognized the change. This has occurred more than once, however.
This may be related to: https://github.com/postmanlabs/postman-app-support/issues/7307

**Comment by DannyDainton** [comment]
Hey @bbrashier

Just to clarify / confirm one thing - Are you saving the request each time you make a change to the collection?

Wanted to confirm that you have no unsaved changes in the collection before running the collection Runner, all _unsaved_ changes are not reflected in the Runner.

**Comment by bbrashier** [comment]
Hi Danny,

I don't think that request had any unsaved changes, but I can't guarantee
it - I've been updating the collection since last week and had moved on
from that particular request. The test was passing before I made the
variable change. I did try closing Postman and reopening it when I saw the
Collection Runner was using the old variable name - would that have
mattered (meaning would closing and reopening Postman have saved any
changes)?

Brenda Brashier
Quality Engineer II
Endurance International Group - Bluehost

**Comment by DannyDainton** [comment]
Would you be able to share some images of the full app window before and after the changes?

Make sure you mask any sensitive information before sending.

It will really help bringing the information to life. 😁

**Comment by bbrashier** [comment]
I'm sorry, I don't have those images. I moved on to other work, and I
didn't take screenshots of the full app either before or after. I can try
reproducing the issue and get those.

Brenda Brashier
Quality Engineer II
Endurance International Group - Bluehost

**Comment by DannyDainton** [comment]
Hey @bbrashier 

Following your steps, I changed a variable name in the Collection and then used `Find and Replace` to change the request.

![Screenshot 2020-09-09 at 09 29 02](https://user-images.githubusercontent.com/17089546/92574388-ecbf9100-f27e-11ea-9535-9a5bc8af02ae.png)

On changing the variable name in the request, the tab now has _unsaved_ changes, this can be seen by the orange dot on the tab. If the request has _unsaved_ changes, these wouldn't be known by the Collection Runner. If you were to run the Collection before saving the change, the old values would still be used.

Sending the request directly from the Builder, wouldn't show this behaviour so you don't see an error with sending the request.

**Comment by bbrashier** [comment]
Ok - is it possible to either: 1) When the variable is replaced using "Find
and Replace" to prompt the user to save the change or have it automatically
save, since the user has made the choice to change it or 2) have Postman
notify the user when running Collection Runner and Builder after making
changes with "Find and Replace" that there are now unsaved changes in the
updated requests? Option 1 would be similar to how Google Sheets works when
using "Find and Replace" there.

Thanks,

Brenda Brashier
Quality Engineer II
Endurance International Group - Bluehost

**Comment by DannyDainton** [comment]
Currently, the app doesn't 'autosave' changes. Editing the requests within a collection could be from a number of different actions, it's not specific to changing something with the `Find and Replace` feature.

As a long term user of the app, I have been caught out on far too many occasions with not saving my changes before running the collection so I feel your pain. We're moving the runner into a separate tab within the app, which will be beside the requests. This should make those save changes more visible.

As well as moving it into the tab, a number of the long-standing issues will be addressed and improvements made as we iterate on the feature and listen to users feedback.

You can to a look at this on our Canary app, you will be able to use this alongside the normal app that you're currently using - Any feedback would be really helpful.

https://www.postman.com/downloads/canary/

I'm going to close out this issue as it seems like the unsaved changes were the cause of the problem.

**Comment by bbrashier** [comment]
Great - thanks for the information. I will take a look at Canary.
Brenda Brashier
Quality Engineer II
Endurance International Group - Bluehost

**Comment by LaneShipleySportradar** [comment]
Hello - I found this thread and have been experiencing the same problem.  I use Find/Replace to make a variety of mass changes quickly and then export the collection after having made the changes. 

The problem: the export does not reflect the changes made by Find/Replace. 

The only way to ensure the changes are saved are to go request by request and hit "Crtl + S" to save, one by one.  Doing it this way eliminates the time saved by using Find/Replace since those changes
![Postman_exports not reflecting Find Replace changes_example NBA_G League](https://user-images.githubusercontent.com/85259472/120560535-b5b68000-c3b7-11eb-86f2-187d5926c85b.png)
 aren't being reflected in the export of the collection.

**Comment by davecader** [comment]
This is a hugely impactful defect, making Search and Replace not only useless but dangerous to use. I have wasted many hours trying to work around this bug and it's a showstopper IMHO. Needs to be resolved ASAP.

**Comment by fjodoin** [comment]
> This is a hugely impactful defect, making Search and Replace not only useless but dangerous to use. I have wasted many hours trying to work around this bug and it's a showstopper IMHO. Needs to be resolved ASAP.

I concur - this issue (Find & Replace not truly replacing variables for the Collection Runner) is still present in version v10.19.7 - critical show stopper for me tbqh :/

**Comment by aaronalvarezunosq** [comment]
This is still an issue present, i just stumbled upon this today, and "saving" is not a solution because the option to "save" the request is greyed out in my requests becuase "find and replace" supposedly already saved the changes, yet the collection runner STILL uses the old variable names, this is a very damaging bug which makes find and replace almost unusable as is.
