### ISSUE TITLE
Collection runner fails to expand variables on 2nd run

### ISSUE THREAD

**Issue by iseem** [a85/POSTMan-Chrome-Extension#904]
The first time I run a collection everything works. But if I try to run it again without closing the Collection runner window, the script crashes. The console error shows that my {{url}} variable in the url isn't getting replaced with the real value: 

test_runner.min.js:7 POST http://%7B%7Burl%7D%7D/page net::ERR_NAME_NOT_RESOLVED

**Comment by abhijitkane** [comment]
Is the url variable coming from an environment or a data file?

**Comment by iseem** [comment]
From an environment variable.

**Comment by abhijitkane** [comment]
I'm not able to replicate this. (After the first run, I can hit 'New Run' and run the collection with the environment again)
Are there any other error messages in the console?

**Comment by iseem** [comment]
Ah, I realized the environment drop down gets reset after each run so I have to manually reselect it *facepalm*
