### ISSUE TITLE
Cookie management does not work AT ALLL!!!! in postman.

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#9043]
The Manage Cookies section is COMPLETELY!!! broken in Ubuntu 20.04 LTS. After adding a cookie, it cannot be edited. "Save" closes the editing box but the cookie is not updated. After adding a bunch of cookies, and closing the manage cookies dialog, all cookies are lost.

The alternative, Interceptor, only supports google chrome. Seriously?

**Comment by DannyDainton** [comment]
Hey @davidmoseler 

Would you be able to clarify which parts are broken? Could you walk through how you're adding and editing the cookies, please?

This is a short clip of me creating and editing cookies - Is this close to what you're seeing?

![Cookies](https://user-images.githubusercontent.com/17089546/92918630-8164f300-f427-11ea-8fa9-7a7414ae961f.gif)


Also, which version of the app are you currently seeing these problems?

The Interceptor is currently only available in Chrome - Is there another browser that you use and want to see a version of it in there?

**Comment by ghost** [comment]
Hi @DannyDainton ! Thanks for the answer.

Yes, that's the workflow I was following. Weirdly, I didn't find the version number anywhere in the application. But it had been just downloaded from the website for Ubuntu 20.04 LTS, so I guess it was the last one.

I tried replicating the bug today, but things are working normally as far as I tried. I'm 100% sure the problem was happening that day, because I went through the procedure multiple times, and, every time, closing the cookie dialog box made all added cookies disappear, besides most of the times editing the cookies was also not saving anything. I had to switch to Insomnia. Anyway, today, after rebooting the system and so on, things are working well in Postman. So idk what happened.

**Comment by DannyDainton** [comment]
That's a strange one but looks like it's all good now. 🏆

I'll close this issue out for now but we can open it up again if you see the issue again.
