### ISSUE TITLE
Facing Tunneling Socket issue while sending request behind proxy

### ISSUE THREAD

**Issue by sarthak-satish-ps** [a85/POSTMan-Chrome-Extension#9045]

**Comment by DannyDainton** [comment]
Hey @sarthak-satish-ps 

Could you also fill in the details for the rest of the headings, please? The more detail that you can provide, the easier it will be for us to investigate the problem that you're seeing.

**Comment by sarthak-satish-ps** [comment]
Removing issue as this no longer persists
