### ISSUE TITLE
Environment Window as a Tab

### ISSUE THREAD

**Issue by michaelvannevel** [a85/POSTMan-Chrome-Extension#9047]
**Describe the solution you'd like**
I would like to see the Environment Window move to a Tab. Basically leave the environments dropdown at the top, but once it is clicked...open it in a tab.  The current environment window which pops up as a modal is too small in width in many scenarios.  When you put json, html, urls, long variable names, it becomes extremely difficult to see any of the information without scrolling, copying etc.

It would be awesome to have it as a tab similar to the Launch Pad.  If all the width of one of the tabs was available, it would be amazing.  You'd be able to see things without having to resize columns or click into them.  You could possibly have environments open as tabs, so when you need to add new variables you can just switch tabs to add the value to the next environment.  You'd be set to add other features to environment variable.  Maybe add the ability to see environment variable history etc.  It opens up a lot of options.

The environment tabs could have a different highlight color at the top to indicate they are environment tabs.  Requests are orange, and environments could be blue of some sort or whatever color.

**Describe alternatives you've considered**
I can shift the columns to resize, but there still isn't enough space.  I can click into the cells to view most of the data, but a lot of the time, that will have to be scrolled as well.

**Additional context**
On a daily basis, I am fairly confident thousands of users are resizing the headers in the grids just to view data.  Clicking into cells to view the full content etc.  I truly believe that users would be so grateful for this feature. 

![EnvironmentTab](https://user-images.githubusercontent.com/32906437/92950198-e74e7c00-f421-11ea-96c8-382e7f900a94.png)

Sorry for the bad image. I'm sure your team could make it looks much better.

**Comment by giridharvc7** [comment]
Environments open as a seperate window and a Tab in Postman v8 both on the app and web. Please let us know what you think!
