### ISSUE TITLE
Save button disappeared

### ISSUE THREAD

**Issue by eugene-sotirescu** [a85/POSTMan-Chrome-Extension#905]
Postman stopped showing the Save button:
![capture](https://cloud.githubusercontent.com/assets/5321786/6045121/ac6cb9b2-ac65-11e4-9958-c9f9f228bb9c.PNG)

Version 1.0.8 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
The save button is only shown for requests that are part of a collection. Did you click on a collection's request?

If not, you can add this request to a collection. Any subsequent changes can then be persisted by clicking Save.
