### ISSUE TITLE
Send Email

### ISSUE THREAD

**Issue by Farhahtahir** [a85/POSTMan-Chrome-Extension#9054]
Hi all, I hit the error below when i trying to send email using postman

{
    "Code": "00000"
}

Below is the request that I used:

http://10.180.1.26:94/Streamline_UtilityAPI/Email/SendMail
POST /Streamline_UtilityAPI/Email/SendMail HTTP/1.1
Host: 10.180.1.26:94
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: b94c7fbf-4f86-cfae-a632-563e2cafac7b
{
    "FromAddress": "",
    "ToAddress": "",
    "ReplayAddress":"",
    "Body":"",
    "Subject":""
}

The status is 200 (OK)
Is there anyone experience it?

**Comment by DannyDainton** [comment]
Hey @Farhahtahir

This seems like a perfect question for our community site - There are lots of awesome Postman users who would be able to offer a solution to your problem.

https://community.postman.com 

As this is not a functional issue with the app, I'm going to close this out.
