### ISSUE TITLE
Get the raw unmodified response body in test scripts

### ISSUE THREAD

**Issue by DamienGarrido** [a85/POSTMan-Chrome-Extension#9058]
**Describe the bug**
In test scripts, in some cases`pm.response.text()` returns the body modified.

**To Reproduce**
1. Write the following test script to display the body in hexadecimal form as well as its corresponding MD5:
```javascript
var rawBody = pm.response.text();
var hexBody = "";
for (i = 0; i < rawBody.length; i++) {
  hexBody += rawBody.charCodeAt(i).toString(16);
}
console.log("MD5: " + CryptoJS.enc.Hex.stringify(CryptoJS.MD5(pm.response.text())));
console.log("Hexa data: " + hexBody);
```
2. Send an HTTP request which returns a response with a body content of exactly one byte whose value is 0x97.
3. See the output of the test script in the console:
For a received body with one “0x97” byte, I get the following displayed in the console:
```
"MD5: 9b759040321a408a5c7768b4511287a6"
"Hexa data: fffd"
```

**Expected behavior**
For a received body with one “0x97” byte, I should get the following displayed in the console:
```
"MD5: c444b580079efb1fe408f17f029e5d35"
"Hexa data: 97"
```
Or I should have a method which returns the raw body content.

**App information (please complete the following information):**
 - Native App
 - Version v7.32.0
 - OS: Ubuntu 18.04

**Additional context**
We should be able to retrieve the response body raw content unmodified of an HTTP response.

**Comment by vikiCoder** [comment]
Hi @DamienGarrido 

The response you get using `pm.response.text()` is not the exact byte-to-byte data received in raw response. It processes the response using defined charset in the `Content-Type` response header and converts it into JavaScript `String` representation.

For your use case, check out `pm.response.stream` property. That will give you a JavaScript `Buffer` containing exact data received in the response.

I hope this will solve your problem. Feel free to reopen the issue if the problem still persists.
