### ISSUE TITLE
Search and sort environment variables

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#9062]
In bigger projects the number of our (environment) variables grows. This leads to management challenges in the interface.  A few 'minor' improvements would make life of environment management much easier:

**Sorting**
In short - be able to sort the environment variables by key. It will make searching and organising much easier.

**Filter**
Have a small search box which allows to filter the variables on key or value. In bigger lists of variables it makes lookup much easier.

**Screen resize** 
Be able to resize the variable screen (eg full). This makes management much easier.

**Comment by giridharvc7** [comment]
Environments is now available as a separate window and a tab. 
Tracking this as a duplicate to #5342.

**Comment by vedkribhu** [comment]
In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback.
![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219374983-1f66d6cb-4f5e-4c39-9fe5-7c5b2998c9b5.png)
We are also working on adding sort functionality available in the manage variables table which should be out next month.
