### ISSUE TITLE
Setting collection variables does not work after clearing cookies.

### ISSUE THREAD

**Issue by commakoerschgen** [a85/POSTMan-Chrome-Extension#9063]
**Describe the bug**
After clearing cookies in a pre-request script, setting collection variables in the same script does not work.

**To Reproduce**

*Update: Make sure that example.com is NOT on the cookie whitelist.*

1.  Setup a new GET request to `example.com`.
2.  Pre-request script:
```
let jar = pm.cookies.jar();
pm.collectionVariables.set('before','foobar');
jar.clear('https://example.com');
pm.collectionVariables.set('after','foobar');
```
3.  Tests
```
console.log(pm.collectionVariables.get('before'));
console.log(pm.collectionVariables.get('after'));
```
4.  Ensure that the collection does not have any collection variables.
5.  Run the request

**Expected behavior**
Collection variables are stored properly independent of cookie jar operations.

**Actual behavior**
Collection variables stored after the cookie clear call are not persisted. Console output is
```
before
undefined
```
so the variable stored before `jar.clear` was set properly while the one afterward was not set.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.32.0
 - OS: Windows 10

**Comment by DannyDainton** [comment]
Hey @commakoerschgen 

I've tried to reproduce this but I'm not seeing the same thing in the console output

![Screenshot 2020-09-16 at 12 01 20](https://user-images.githubusercontent.com/17089546/93328999-712c8980-f814-11ea-8c80-1df4036acae3.png)

Is there any other contextual information that you could give us that might be the cause of the issue?

Is the domain whitelisted? Only whitelisted domains work with `pm.cookies.jar()` 

Have you tried clearing out all the cookies and seeing if this give you a different outcome?

You can access these via the `Cookies` option in the request builder:

![Screenshot 2020-09-16 at 12 04 49](https://user-images.githubusercontent.com/17089546/93329312-eac47780-f814-11ea-91cc-3dc3dfd77cdc.png)

**Comment by commakoerschgen** [comment]
Thank you for the swift response, @DannyDainton 

It turns out that whitelisting the domain (`example.com` in my original example) prevents the issue.

---

However, this is still weird behavior: If the domain is not whitelisted, `jar.clear` fails, but the failure is managed through a callback (like `jar.clear('https://example.com',function(error){console.log(error)});`), and calling the clear method still succeeds from a script point of view. In particular, the following call  `pm.collectionVariables.set('after','foobar');` is executed.

But the latter call does not have its intended effect (setting a collection variable), although managing cookies and managing collection variables are independent in theory. So the jar.clear call seems to have an unexpected side effect on collection variables.

---

I have just reproduced the issue again in a fresh Postman environment (logged out of my account). Can you reproduce it with an empty cookie whitelist?

**Comment by DannyDainton** [comment]
I'm still seeing the same abut this time the error is in the console:

Is this what you're seeing? 

![Screenshot 2020-09-16 at 12 54 59](https://user-images.githubusercontent.com/17089546/93334023-2282ed80-f81c-11ea-8b45-20efb0660d1d.png)

> I have just reproduced the issue again in a fresh Postman environment (logged out of my account). 

As we are unable to see what's in front of you, you will need to provide a screenshot of what you're seeing, please.

**Comment by commakoerschgen** [comment]
Here is a screenshot:

![screenshot](https://user-images.githubusercontent.com/40790681/93338270-7694ce80-f82a-11ea-922a-d549be7e298f.png)

Have you cleared out the collection variables again? Apart from that, the only difference I can think of would be the platform since you appear to be using macOS. Could there be a Windows-specific glitch in the script runner?

**Comment by igorovic** [comment]
I faced the same Issue but only on **windows**.
On Mac OS my pre-request script is able to set the collectionVariables. 

order of operations.
1. clear cookieJar
2. set collectionVariables

If you clear your cookies at the end of the pre-request script then it works on both platforms. `Win` and `Mac`
1. set collectionVariables
2. clear cookieJar    <== this must be last operation in your script

**Comment by apoorvgupta03** [comment]
Hey @commakoerschgen , we are not able to reproduce this anymore in Windows or Mac, can you please confirm if this issue still persists on your end? You can also update the app for feature improvements and rich UI

**Comment by commakoerschgen** [comment]
Well, I have not tried in a while since I've been working on other topics lately. As it is not reproducible anymore on your end, I will just go ahead and close this issue.

**Comment by apoorvgupta03** [comment]
thanks for your time and input @commakoerschgen
