### ISSUE TITLE
Lossy parsing of large numbers from JSON responses using pm.response.json() 

### ISSUE THREAD

**Issue by filfreire** [a85/POSTMan-Chrome-Extension#9065]
**Describe the bug**
There's loss of data when trying to get "big integer" fields parsed with `pm.response.json()`. A number like `9223372036854775807` gets converted into `9223372036854776000`.

**To Reproduce**
1. `curl --location --request GET 'https://filfreire.com/test.json'` (or try and parse locally `{ "somebignumber" : 9223372036854775807 }`)
2. Observe the `pm.response.json()` resulting object

**Screenshots**
![example](https://user-images.githubusercontent.com/11976836/93376575-19187600-f85a-11ea-8993-c84c24160f84.jpg)

**App information (please complete the following information):**
 - App Type: Any app type
 - Postman Version: Any version
 - OS: Any OS

**Additional context**
 Possibly similar or linked to `JSON.parse` issue in [dealing with large numbers](https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigint) and slightly related to an open [ECMAScript proposal](https://github.com/tc39/proposal-json-parse-with-source). 

/cc @DannyDainton @loopDelicious  @shamasis

**Comment by kevinswiber** [comment]
Hi @filfreire,

The JSON specification allows implementations to set limits on numbers, and in fact, suggests constraints imposed by IEEE754-2008, which allows the range `[-(2**53)+1, (2**53)-1]`.

I would recommend placing a bigint in a string to help maintain interoperability with tooling.

Reference: https://tools.ietf.org/html/rfc7159#section-6

**Comment by DannyDainton** [comment]
Closing this as per the suggestion by @kevinswiber
