### ISSUE TITLE
i just duplicate a postman request, which is POST request. Internally  changed that request to GET. Not updating in the left side bar list.  

### ISSUE THREAD

**Issue by adharsh05** [a85/POSTMan-Chrome-Extension#9067]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by adharsh05** [comment]
<img width="361" alt="Screenshot 2020-09-17 at 1 46 10 PM" src="https://user-images.githubusercontent.com/26116417/93454500-27af6d80-f8ec-11ea-9d72-381a2bc6d270.png">
Leftside list not updating

**Comment by DannyDainton** [comment]
Hey @adharsh05 

Could you please fill in the details of the template to help us to replicate what you're seeing. 

The steps to reproduce and the environment details are the important things here to get clarity on.

**Comment by DannyDainton** [comment]
Hey @adharsh05 👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
