### ISSUE TITLE
Folder edit Authorization cannot take effect

### ISSUE THREAD

**Issue by hcpx** [a85/POSTMan-Chrome-Extension#9069]
Describe the bug
When I keep the authorization variables in the working range, I edit the folder authorization. Its sub files and sub requests can't add authorization synchronously, and they must be reset in each request

To Reproduce

Go to 'collections'
Right  Click on any yourself collection
choice edit->Authorization 
setting type BearerToken and token
click update
this any yourself collection sub files and sub requests have no authorization settings
Expected behavior
this any yourself collection sub files and sub requests have the same authorization settings

Screenshots
![93476500-74b33400-f92c-11ea-8a4c-0c4e45694b88](https://user-images.githubusercontent.com/18361107/93497689-4ab93c00-f943-11ea-83d8-f6acfe4a17b4.png)
![93476683-a6c49600-f92c-11ea-943f-1ba3972dde3b](https://user-images.githubusercontent.com/18361107/93497695-4bea6900-f943-11ea-988b-71def7ea4671.png)

App information (please complete the following information):

App Type [Native App]
Postman Version [v7.32.0]
OS: [win32 10.00.183562 / 64]

**Comment by DannyDainton** [comment]
Hey @hcpx 

Can you provide the additional template details, please? 

---

**Steps To Reproduce**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See an error

**App information:**
 - Postman Version:
 - OS: 

**Additional context**
Add any other context about the problem here.

**Comment by DannyDainton** [comment]
Hey @hcpx 

Is this still an issue that you're facing with the latest app version?

**Comment by DannyDainton** [comment]
Hey @hcpx  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
