### ISSUE TITLE
Bad request when using queryparameters 

### ISSUE THREAD

**Issue by aaroncornelissen** [a85/POSTMan-Chrome-Extension#9070]
With the postman 7.3 version I experience an error when using query parameters.
When I send a request like https://www.example.com/api?q={"id": "1234"} I get an 400 bad request error.

I downgraded my postman to 7.2 and it worked again. 

I am using windows 10, my collegue on a mac is experiencing the same problem.

**Comment by DannyDainton** [comment]
Hey @aaroncornelissen 

Can you confirm the version you're using, please? 

We will also need to know a little bit more context of what you're trying to do, can you provide some steps to reproduce to the problem?

Any screenshots (masking the sensitive data) of the real requests you're sending and the Postman Console output of the request.

A 400 request would suggest something wrong at the server-side with the data you're sending so can you check that you have no additional whitespace or line ending in the request. This might be more difficult to see if you're using variables.

**Comment by aaroncornelissen** [comment]
Hello @DannyDainton,

Thank you for your quick response. 
I am using now version v7.32.0, I tested the request also with version v7.2.0 and there it worked (I could not find an later version to download except the latest). 

I am sending my requests to a oracle API ([see docs](https://docs.oracle.com/cd/E56351_01/doc.30/e87809/developing-REST-applications.htm#AELIG90103)). I am using the query parameters to filter my results in de database before I recieve them. 

I think there is going something wrong with transforming the request (url). I think the application transforms the request differently then before and because of that the API recieves a bad request. 

The query parameters do work with the older postman version I used (7.2.0) and it also works with the js library axios from my react-native app.

**Request without query parameters**
![request1](https://user-images.githubusercontent.com/57479235/93565422-a27b9580-f98b-11ea-9f38-d016683d744e.png)

**Request with query parameters**
![request2](https://user-images.githubusercontent.com/57479235/93565424-a3142c00-f98b-11ea-8942-b8a7067b08fb.png)

**Comment by DannyDainton** [comment]
We have made changes between those 2 versions around the URL processing - You can read the full details on this here:

https://github.com/postmanlabs/postman-app-support/issues/8154

**Comment by aaroncornelissen** [comment]
> We have made changes between those 2 versions around the URL processing - You can read the full details on this here:
> 
> #8154

Thank you!,  disabling the "Use next-generation URL processing" settings solved my issue.

**Comment by kotpal** [comment]
Simple GET with a header fails in Postman with HTTP 400 - but the same request succeeds in Curl or PowerShell. I don't find any setting related to 'next gen url processing' and I get the same error whether I turned off 'encode url automatically' or not.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Hostname</h2>
<hr><p>HTTP Error 400. The request hostname is invalid.</p>
</BODY></HTML>

```
