### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by cobbi1309** [a85/POSTMan-Chrome-Extension#9072]
**Describe the bug**
The postman´s windows turned gray

**To Reproduce**
1. Open postman
2. Wait 5 minutes
3. The window turned gray.

**Expected behavior**
The window doesnt turn gray

**Screenshots**
![image](https://user-images.githubusercontent.com/71472271/93538808-aae4b980-f914-11ea-9113-1d1921c1bae9.png)

**App information (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by santoshmohan** [comment]
I have the same issue as well. 
![image](https://user-images.githubusercontent.com/6982545/93548253-378d8700-f9aa-11ea-895f-03e54d108df3.png)

Postman v7.32.0
Platform Windows 10  2004

**Comment by DannyDainton** [comment]
Hey @cobbi1309 / @santoshmohan 

Would you be able to switch over to the Canary build, to see if that loads up the app for you, please?

https://www.postman.com/downloads/canary/

This can be downloaded and run in parallel to your main Postman app.

**Comment by cobbi1309** [comment]
It works perfectly, thanks!!

**Comment by santoshmohan** [comment]
I am still facing the issue with Canary build.
I am using dark mode, is this something related with?
![image](https://user-images.githubusercontent.com/6982545/93965534-b5d09b80-fda5-11ea-8194-32729825632b.png)

**Comment by Raj-postman** [comment]
@santoshmohan Issues related to the black screen on Postman are usually resolved by disabling GPU. Can you follow [this article here](https://support.postman.com/hc/en-us/articles/360026088854-Postman-window-is-blank) and let us know if that helps?

**Comment by bitbound** [comment]
I have the same issue at start-up.  With GPU disabled, I get a flash of UI, then it goes back to gray.

**Comment by joseluisrios55** [comment]
same issue. Gray screen after 1-2 minutes. 
Disabled GPU = true.
Tested with windows 10 problems solved
Nothing works

**Comment by matthewboman** [comment]
I'm running into this on Ubuntu 18

**Comment by DannyDainton** [comment]
@crashspringfield 

Which version of app are you using? Is this the case on V8?

**Comment by jmammri** [comment]
@DannyDainton v8.0.7 for me. (I'm facing the same problem)

I updated a few weeks ago, but got this issue only today.

**Comment by ggfuzzy** [comment]
Experiencing this on Fedora 33. Comes and goes, but currently happening every time I start it up and try to make a change in the body of my request.

**Comment by m3dbedb** [comment]
The issue does not appear in 8.5.1 and other 8.x.x versions under windows 7-32

**Comment by m3dbedb** [comment]
the issue appeared in postman 8.5.1 64 under windows 10. Postman 7 have updated to 8.4.1 and every start it opens grey and window resize does not make it back to life like it was in postman 7. (the app requres app restart, in my case it run correctly after windows restart). The issue wasn't seen in Postman 8.6.0 (win 7 32)

**Comment by JetStarBlues** [comment]
I get this grey-out frequently enough that the Postman desktop client is unusable (Windows 10, Postman v8.10.0). After a couple of minutes, sometime even on first open, the entire UI disappears.

The workaround that seems to work is [using Postman in "offline mode"][0]. This is achieved by clicking the `Settings` gear icon and selecting `Scratch Pad` mode from the options on the menu that pops up.

While this works in preventing the grey-out, it is not really a great long-term solution as I do not have access to collections stored on the cloud and other Postman features that rely on being online...

\* The disable `Hardware Acceleration` trick mentioned in this issue thread had no effect

[0]: https://community.postman.com/t/working-in-offline-mode/20174/25

**Comment by edegaudenzi** [comment]
> The workaround that seems to work is [using Postman in "offline mode"](https://community.postman.com/t/working-in-offline-mode/20174/25). This is achieved by clicking the `Settings` gear icon and selecting `Scratch Pad` mode from the options on the menu that pops up.

Currently running Postman 9.1.3 on Windows10. It happened to me exactly the same, and actually, it comes grey after a few seconds. Your offline workaround still works but I also needed, in those few seconds that Postman allowed me to run before the grey screen, to 'Sign out' from my Postman account (orange astronaut icon -> Sign Out) 

So far, on Linux (Xubuntu 18.04) it does not give any problem. Exporting all of the saved API over there.

**Comment by m3dbedb** [comment]
The issue has uppeared in postman 9.1.5 for windows 10 64
![Снимокгит](https://user-images.githubusercontent.com/25632818/142876767-75838fc0-f858-49cd-ba5e-cea9b4517f89.JPG)

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5980

**Comment by ferrumie** [comment]
Currently facing this issue
