### ISSUE TITLE
The name of postman is not gender-neutral

### ISSUE THREAD

**Issue by hanayashiki** [a85/POSTMan-Chrome-Extension#9074]
**Describe the bug**
The name of postman is not gender-neutral. We should promote gender-neutrality in naming.

**To Reproduce**
-
**Expected behavior**
A gender-neutral name for this application.

**Screenshots**
![image](https://user-images.githubusercontent.com/26056783/93567114-029a1980-f943-11ea-8f67-11458ff0ab8d.png)

**App information (please complete the following information):**
 - App Type [All]
 - Postman Version [All]
 - OS: [Any]

**Additional context**
No

**Comment by sandy2008** [comment]
You can just not use it, you Libtard

**Comment by miki-nis** [comment]
No. Go create your own gender-neutral app.

**Comment by arlemi** [comment]
Hey @hanayashiki - thanks for reaching out. We're using this repository to track feature requests, integrations, and bug reports with the Postman app. For discussions about the Postman brand please use our contact email `info@postman.com`.
