### ISSUE TITLE
Variables not retained between sessions in web interface (web.postman.co) when over certain length

### ISSUE THREAD

**Issue by nickchampion** [a85/POSTMan-Chrome-Extension#9082]
**Describe the bug**
I have JWT tokens in my environment variables, every time I reboot my laptop or restart by browser these tokens no longer work as they seem to be truncated at 228 characters, they are approximately 400 characters in length.

This never used to happen with the downloadable client, its only not happening when I moved to the web interface

Is there a character limit of variables?

**To Reproduce**
1. Add an environment variable with ~400 characters
2. Sync to postman server
3. Close browser and reboot laptop
4. Re-open browser and check the variable it should have been truncated.

**Expected behavior**
Variables should be retained in their original length

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by DannyDainton** [comment]
Hey @nickchampion 

I'm unable to recreate this issue using the latest version of the platform. I'm going to close this out for now but we can look at reopening this issue if you're still seeing the same problem.
