### ISSUE TITLE
Interface is HUGE

### ISSUE THREAD

**Issue by Montago** [a85/POSTMan-Chrome-Extension#9085]
![image](https://user-images.githubusercontent.com/456040/94122898-6648a900-fe53-11ea-92c2-0935dc8c9fac.png)

There's a ton of FLUFF in regards to the interface. 

I'm here working on a 150DPI FullHD screen (working as secondary montitor) and 3/4 of the screen is just FLUFF 

Marked in red are interface that is not really essential: 
- Black bar in top is unnecessary huge, and could for the most part be packed away in the File-Edit-View menu.. 
- Name of Request is just double-fluff, it says the name just above in the tab AND in the sidemenu .. 

Marked in blue are elements that are just too big:
- Address bar is huge with tons of margin, the content could easily be part of the params-auth-body tabs and tucked away. 
- Pretty-Raw-Preview could be a dropdown property of BODY 

I know that configuring the request is just as important as the result - but leaving almost no room left for the response is not the way to go.

**Comment by tjmcdonough** [comment]
Completely disagree. These options are critical in creating documentation.

**Comment by DannyDainton** [comment]
There have been various changes made to the UI in the latest version of the platform. The original issue is showing a very outdated app.
