### ISSUE TITLE
Export request to curl

### ISSUE THREAD

**Issue by AdemHodzic** [a85/POSTMan-Chrome-Extension#9092]
I use Postman regularly but not all of my colleagues do. It would be awesome if someone implemented a way to export a request as a curl command.

**Describe the solution you'd like**
Add a button that says "Export to curl" that opens a modal with curl command in a span element and a button that coppies that command.

**Comment by DannyDainton** [comment]
Hey @AdemHodzic 

Is this what you're looking for 😄 

![code_gen](https://user-images.githubusercontent.com/17089546/94251340-4af4a100-ff1a-11ea-8e36-e96211cd213d.gif)

You will find curl and a number of other languages in this feature.

**Comment by AdemHodzic** [comment]
Ah awesome.

That's exactly what I'm looking for.
