### ISSUE TITLE
Add ability to "Send and Download/Save response" while using Postman Desktop Agnet.

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#9093]
**Is your feature request related to a problem? Please describe.**
Currently, the **_Send and Download_** button is not available while using the Postman desktop agent. 

**Describe the solution you'd like**
Enable the Send and download button to save responses for the desktop agent as well

Screenshot:
![image](https://user-images.githubusercontent.com/40994626/94254571-9459e600-ff44-11ea-97dc-e4f9e6025010.png)

**Comment by DannyDainton** [comment]
This feature is now part of the latest version. Closing this feature request.
