### ISSUE TITLE
UX issue | Tooltip in the test script section prompts immediately and not able to select/edit the text easily

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#9094]
**Is your feature request related to a problem? Please describe.**
When you hover on the line in the test script section, the tooltip message prompts immediately and blocks the line that needs editing which is causing inconvenience. 

**Describe the solution you'd like**
Adding the tooltip message above/below the pointed text would really help in terms of usability perspective.

Screenshot:
![image](https://user-images.githubusercontent.com/40994626/94258336-5495fd00-ff4a-11ea-829a-0e5bda552867.png)

**Comment by pankajk07** [comment]
@Ramya-From-Postman, we are already tracking this issue as part of https://github.com/postmanlabs/postman-app-support/issues/8829.

Marking it as duplicate and closing it out.
