### ISSUE TITLE
Cannot open Postman Agent - nothing happens

### ISSUE THREAD

**Issue by mshparber** [a85/POSTMan-Chrome-Extension#9097]
**Describe the bug**
Cannot open Postman Agent - nothing happens

**To Reproduce**
1. Donload Postman Agent-win64-0.2.1-Setup.exe
2. Click on it
3. "Installing Postman" appears then disappears 
4. Nothing Happens
5. Find postman Agent in Windows programs, click on it
6. Nothing happens

**Expected behavior**
Expected to open

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
- Postman Agent-win64-0.2.1

**Additional context**

**Comment by gabrielcamen** [comment]
Hello, I encountered the same issue and after trying the most common fixes nothing has worked (reinstalling app, opening installation with admin, looking at logs etc.) I am using Windows 10 with the same Postman Agent-win64-0.2.1 installer.

**Thanks in advance!**

**Comment by vvs11** [comment]
@mshparber @gabrielcamen  could you attach a video of this happening? Will help us understand the issue better

**Comment by eweintra** [comment]
same for me cant open postman agent

**Comment by undeadzant** [comment]
Hello,

I am having a similar issue on MacOS.

1. Click Postman - nothing happens 
<img width="278" alt="Screen Shot 2020-10-07 at 9 29 54 AM" src="https://user-images.githubusercontent.com/13440434/95345358-41efc200-0880-11eb-8498-f781713f0beb.png">
2. Check system tray - shows Postman is running even though icon near bottom of the screen is not
<img width="209" alt="Screen Shot 2020-10-07 at 9 30 26 AM" src="https://user-images.githubusercontent.com/13440434/95345354-4025fe80-0880-11eb-8c00-448a500977c8.png">
3. Even though it is "open" Chrome, Edge, Firefox, Safari, Brave, all show the same "Agent Unavailable" message
<img width="293" alt="Screen Shot 2020-10-07 at 9 31 14 AM" src="https://user-images.githubusercontent.com/13440434/95345350-3f8d6800-0880-11eb-8fa3-45cfe7370db2.png">

**Comment by MaxKrog** [comment]
Same problem as undeadzant
MacOS Catalina 10.15.6
Postman Agent v0.2.2

**Comment by obrun** [comment]
Same here. It is in the menu bar but does not function with Safari or Chrome.
MacOS 10.15.7
Postman v0.2.2

**Comment by johnelbasha** [comment]
I am on Mac OS Catalina.

All I have is this tiny icon in the tray:
![Screenshot 2020-11-18 at 21 51 11](https://user-images.githubusercontent.com/59657806/99592573-4b745a00-29e8-11eb-9a6d-8930f80a1cfb.png)
I can't actually "open" anything:


![Screenshot 2020-11-18 at 21 52 28](https://user-images.githubusercontent.com/59657806/99592621-5b8c3980-29e8-11eb-8fc0-56cac13fc4d1.png)

**Comment by jordydehaes** [comment]
Same issue on Windows 10, appears to be running but nothing opens up.

**Comment by kevinswiber** [comment]
Hmm.  This might be a shot in the dark, but it's possible some folks have cached HSTS rules associated with localhost, which would force redirects to HTTPS.

The Network log in DevTools would show failed requests to https://localhost:10533/knockknock.  In Chrome, at least, that can be checked here: chrome://net-internals/#hsts.  If you query localhost and find entries, I'd try deleting the localhost entry to see if that resolves the issue.

Explanation: The Desktop Agent starts a server on localhost.  The Web app communicates with the Agent, which is hosted over HTTP.  If something forces the request to be HTTPS, it will fail to communicate with the Agent.

**Comment by ShubhamShah** [comment]
The same happening with me, the postman chrome extension and app runs smoothly,
When downloaded the PostMan Agent, it gets installed, shows in the tray but does not open.
I've removed all the postman extensions and agents, reinstalled the postman agent file but not opening.

Configuration:
1)Windows 7 64 Bit
2)Postman Agent win64-0.2.4

**Comment by moomoolive** [comment]
Same issue as undeadzant.

I tried it with the Postman Agent-win64 0.2.4 setup wizard on Windows 10. It didn't respond after uninstalling and installing again.

**Comment by siralam** [comment]
Hey guys, I just realized Postman Agent and Postman app are different things. If you want to run Postman as a desktop app, do not download `Postman Agent` but the app here: 

https://www.postman.com/downloads/

**Comment by apoorvpandey02** [comment]
> Hey guys, I just realized Postman Agent and Postman app are different things. If you want to run Postman as a desktop app, do not download `Postman Agent` but the app here:
> 
> https://www.postman.com/downloads/

I was stuck with the same thing... thanks for pointing out!

**Comment by mohitranka** [comment]
We have improved the user experience a bit with the ability to open postman (web app) from the Postman Agent tray with the latest release (`v0.2.5`). More improvements to come! :)

**Comment by DrSensor** [comment]
Is there a setting to prevent web.postman.co polling http://localhost:10533/knockknock ?
I think this causes my browser to hang/laggy when opening multiple workspaces in multiple browser tabs.
(also bit afraid if there is a bad daemon listening to HTTP port 10533)

**Comment by Brent7788** [comment]
> Hey guys, I just realized Postman Agent and Postman app are different things. If you want to run Postman as a desktop app, do not download `Postman Agent` but the app here:
> 
> https://www.postman.com/downloads/

This was also my problem. Thy should be more clear about Postman desktop and the Agent one!

**Comment by badrik-github** [comment]
> Hello, I encountered the same issue and after trying the most common fixes nothing has worked (reinstalling app, opening installation with admin, looking at logs etc.) I am using Windows 10 with the same Postman Agent-win64-0.2.1 installer.
> 
> **Thanks in advance!**

**Comment by gebbber** [comment]
The problem is that the website tells you to download it, and implies that it's a standalone local app, but doesn't explain that the intent is still to work in the web app.

**Comment by TheBean** [comment]
Mac user here and I downloaded the Postman Agent using the browser based Postman suggested interstitial when I really wanted to download the client app from the Postman download site, and ran into same issue where it was running, couldn't kill it using "Force Quit" or remove the program. 

So I executed the following steps to kill and remove the file:
1. Open Terminal 
2. type 'ps -ax'
3. Find the postman agent process and PID
4. type 'kill [PID]'
5. Proceed to uninstall Postman Agent

Afterwards I did download the client version of Postman and able to open and use application without issue.

**Comment by suresh-gandhi** [comment]
https://support.postman.com/hc/en-us/articles/360039876493-How-to-Install-Postman-from-Terminal-
Using command line to install worked for me since postman/downloads was not working for me

**Comment by pinksynth** [comment]
From the perspective of a brand new user, when you initially sign up, it really feels like you're supposed to click the button here to download the Desktop App. I didn't even know that the "agent" was a separate thing, and assumed that this was just the name of the app.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/25071920/130120787-9ed642a8-c927-4b13-81c0-28f0a886d021.png">

Maybe it would be good to add some copy to this modal that clarifies the differences between the two options? For example:
> NOTE: This is for the Desktop Agent, not the Desktop App. For the Desktop App, click here.

Just a suggestion to remove confusion for future users. Thanks!

**Comment by AngelikaSk92** [comment]
> Hey guys, I just realized Postman Agent and Postman app are different things. If you want to run Postman as a desktop app, do not download `Postman Agent` but the app here:
> 
> https://www.postman.com/downloads/

Wow thank you very much ! I was troubling with the issue and can not find solution. :)

**Comment by mikiyasgirma** [comment]
The same thing happening here. looks running but nothing happens

**Comment by Sbadibanga** [comment]
> Hello,
> 
> I am having a similar issue on MacOS.
> 
> 1. Click Postman - nothing happens
> 
> <img alt="Screen Shot 2020-10-07 at 9 29 54 AM" width="278" src="https://user-images.githubusercontent.com/13440434/95345358-41efc200-0880-11eb-8498-f781713f0beb.png">
> 
> 2. Check system tray - shows Postman is running even though icon near bottom of the screen is not
> <img alt="Screen Shot 2020-10-07 at 9 30 26 AM" width="209" src="https://user-images.githubusercontent.com/13440434/95345354-4025fe80-0880-11eb-8c00-448a500977c8.png">
> 
> 3. Even though it is "open" Chrome, Edge, Firefox, Safari, Brave, all show the same "Agent Unavailable" message
> <img alt="Screen Shot 2020-10-07 at 9 31 14 AM" width="293" src="https://user-images.githubusercontent.com/13440434/95345350-3f8d6800-0880-11eb-8fa3-45cfe7370db2.png">

I was having this same issue, it turns out it was a storage problem as in I didn't have enough space on my mac to download and open it, after clearing up some space it now works!

**Comment by littleironical** [comment]
I was facing the exact same issue but when **I tried to run it in a different browser** as mentioned by @Sbadibanga **it worked** ✅

I was using Brave(didn't work) then switched to Chrome, and it worked!

**Comment by kiocjw** [comment]
I'm using a different device, and it works. It does work for my win 11 chrome only but works for firefox and other.

**Comment by clxrityy** [comment]
From my limited understanding, the [**Postman Agent**](https://learning.postman.com/docs/getting-started/basics/about-postman-agent/#:~:text=The%20Postman%20Desktop%20Agent%20is,your%20local%20machine%20and%20network.) app isn't meant to be run itself as a standalone application. It is a [*micro-application that runs locally on your desktop*](https://learning.postman.com/docs/getting-started/basics/about-postman-agent/#:~:text=The%20Postman%20Desktop%20Agent%20is,your%20local%20machine%20and%20network.). 

It is simply acts as your agent for making API calls from the [web app](https://web.postman.co/). 

## Install the actual Postman app:

- ### [MacOS](https://learning.postman.com/docs/getting-started/installation/installation-and-updates/#install-postman-on-mac)
```brew
brew install --cask postman
```
> the postman agent as well for API calls on the web app:
```brew
brew install --cask postman-agent
```

- ### [Windows](https://learning.postman.com/docs/getting-started/installation/installation-and-updates/#install-postman-on-windows)

- ### [Linux](https://learning.postman.com/docs/getting-started/installation/installation-and-updates/#install-postman-on-mac)

**Comment by Benrobo** [comment]
For anyone having faced this issue on `Brave Browser`, simply *Disable Shield* for `web.postman.co` and the desktop agent should be up and running.
