### ISSUE TITLE
Import not working and not backward compatable

### ISSUE THREAD

**Issue by sunshineo** [a85/POSTMan-Chrome-Extension#910]
I'm on version 0.8.4.12 . Chrome version Version 40.0.2214.93 (64-bit) . On a Mac
I have a lot of collections and a lot of things saved in them.
The exported collections json is valid. I used http://jsonlint.com/ to validate it.
But I cannot import it back onto another machine which also have 0.8.4.12
The error is:
Uncaught TypeError: Cannot read property 'length' of undefined

Do not tell me to update to the Packaged App. I cannot import it to the packaged app either. It says "Failed to import: Format not recognized."

So if 0.8.4.12 is not working not supported and no one plan to fix it, please delete it from chrome web store. And the new packaged app is not usable in my opinion because it cannot open multiple windows.

Here is the JSON it exports. I removed all my other collections and left only one. I also tried with just this one. It does not work.
{
  "version": 1,
  "collections": [
    {
      "id": "06600c17-f77e-bc1c-4f9d-e9f04a22c61c",
      "name": "Inbound API",
      "timestamp": 1421966730796,
      "requests": [
        {
          "collectionId": "06600c17-f77e-bc1c-4f9d-e9f04a22c61c",
          "id": "4e4cc881-d5b5-647c-b292-43568f600626",
          "name": "Get po by eventId & vendorId",
          "description": "",
          "url": "http://vxp-inboundapi.iad.prod.zulily.com:8083/inbound/po?vendorNumber=54&eventId=75792&count=1000",
          "method": "GET",
          "headers": "",
          "data": [],
          "dataMode": "params",
          "timestamp": 0,
          "responses": [],
          "version": 2
        }
      ]
    }
  ],
  "environments": [],
  "headerPresets": [],
  "globals": []
}

**Comment by abhijitkane** [comment]
How are you importing the collections? The file you've shared is a data dump (contains collections+environments+headerPresets+globals), not a single collection file.

In the packaged app, this dump file can be imported by going to the Settings Modal > Data > Import. I was successfully able to import it in the packaged app. The steps are described in the documentation here - https://www.getpostman.com/docs/migration

The main Import dialog is meant for importing individual collection files.

**Comment by sunshineo** [comment]
Thank you @abhijitkane . I imported them properly into the packaged app using the steps you pointed to.

Now is 0.8.4.12  ever going to be fixed? If not you can close this issue.

However the packaged app lacks the ability to open multiple window at the same time.

**Comment by abhijitkane** [comment]
What's the problem with 0.8.4.12? The collection import works for importing collections, not the entire dump file. The dump file is meant to help migrate all data to the packaged app.

In the packaged app, you can open a new window by clicking the icon to the left of the Import button in the top bar.

**Comment by sunshineo** [comment]
I GOT IT!!!!
THANK YOU VERY MUCH!
I need to export the collection one by one use the share button and then import the collection one by one.
