### ISSUE TITLE
Cookie is being stored automatically when we hit any request, this leads to failing of following requests

### ISSUE THREAD

**Issue by swasthik8** [a85/POSTMan-Chrome-Extension#9100]
**Describe the bug**

- Hit an API Request ( for eg: Login API
- Hit 2nd API ( Cookies is being stored in headers automatically) this leads to failing requests which do not expect cookies.
- Try writing script to clear cookie

Still the Cookie in being stored ( tried in newman as well)

**Expected behaviour**

Cookies should not get stored automatically, leads to failures of following requests

**Screenshots**

The screenshots attached have the script used to clear cookies,

![Screenshot 2020-09-28 at 12 48 50 PM](https://user-images.githubusercontent.com/51586332/94402011-12a6ca00-0189-11eb-8fb4-71a6f9f698e9.png)
![Screenshot 2020-09-28 at 12 48 42 PM](https://user-images.githubusercontent.com/51586332/94402014-14708d80-0189-11eb-9598-f606afe72e16.png)

**Comment by DannyDainton** [comment]
Hey @swasthik8 

Has the domain that you're trying to access been added to the Cookie whitelist?

https://learning.postman.com/docs/sending-requests/cookies/#whitelisting-domains-for-programmatic-access-of-cookies

There's an additional request level setting that can be applied to disable the cookie jar:

![image](https://user-images.githubusercontent.com/17089546/94562458-43583380-025d-11eb-8c82-2da1d5006000.png)


Can you also provide the version and platform information, please?

**Comment by swasthik8** [comment]
@DannyDainton Thanks, both ways working
