### ISSUE TITLE
Export ids change every export

### ISSUE THREAD

**Issue by TomONeill** [a85/POSTMan-Chrome-Extension#9101]
**Describe the bug**
Everytime I export a collection, the ids are being regenerated. I need them to stay the same every single export, what seem to have been the case in the past. Unfortunately I don't know a version number in which this behavior had changed.

**To Reproduce**
1. Export a collection (v2.1)
2. Export the same collection with the same version as 1

**App information**
Version 7.33.1
win32 10.0.19041 / x64

**Comment by vvs11** [comment]
@TomONeill We have a thread around this going on #2906. We are working on finalizing a fix for this. Will post the update on the issue itself.

**Comment by TomONeill** [comment]
@vvs11 I didn't see that one. Thanks for your quick response!
