### ISSUE TITLE
env vars are incorrectly marked as "unresolved variables"

### ISSUE THREAD

**Issue by nutmix** [a85/POSTMan-Chrome-Extension#9103]
I cant use postmans environment variables in some rest api collections, it always says "unresolved variable" for variables which are correctly defined in the current active env. I have to hard code everything, and either use duplicates of the apis for different envs, or hand edit each api depending on the env. Does anyone know of any work arounds to this issue?

Observations:

- some api collections work, some don't. There is no difference between them, except may be that some apis were created with the env var in the URL from scratch, some were modified form hard coded urls and had the var added later.
- When vars dont work, its always in the url, such as POST https://{{myhost}}/something. myhost in this case is "undefined", even though its defined in the currently selected env, AND OTHER VARS IN THE BODY are picked up correctly...

In console is this:
Error: getaddrinfo ENOTFOUND {{myhost}}

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version  7.33.1
 - OS: mac OS 10.14.4 (18E227)

![image](https://user-images.githubusercontent.com/5080942/94559361-6ab0ff80-0261-11eb-8bfb-3db7cb17cb02.png)

**Comment by cvanlabe** [comment]
Having the same issue. If it matters, I first created the collection with the variable defined there. Then later I created the environment with the variable defined there (and removed from the collection). It's saying the variable is not defined in the active collection, environment or globals. This is not correct, it is definitely defined in the environment.

**Comment by vvs11** [comment]
@nutmix I am not able to reproduce this. Could you attach a video highlighting the steps to reproduce it? 
You can upgrade to 7.36 and check if you're still facing this issue

**Comment by sunnyttravers** [comment]
This is still a bug and I'm frustrated that it isn't fixed yet. This has been happening for 6 months now. I can't remember which version caused this. I've been using Postman for years. This bug is definitely most frustrating. I've learned to ignore it. 
It's frustrating to see all these updates being pushed out with all these lovely new features. How about fix some existing bugs! This is a pretty standard feature and I'm surprised they haven't fixed it. 
End rant.

**Comment by OfirD1** [comment]
One has to make sure that its environment is actually active:
![image](https://user-images.githubusercontent.com/30159171/152679457-adedc8a8-8042-4875-adcf-d50ef0c12d8c.png)

**Comment by shubhbhargav** [comment]
@sunnyttravers @cvanlabe  Is the issue still there for you? If yes, can you please share a screenshot / recording of the same? We are not able to reproduce it on our latest app (9.12.2).

**Comment by sunnyttravers** [comment]
> @sunnyttravers @cvanlabe Is the issue still there for you? If yes, can you please share a screenshot / recording of the same? We are not able to reproduce it on our latest app (9.12.2).

This is no longer an issue. I just confirmed it. Thanks!
