### ISSUE TITLE
Collection monitor fails with request order and skips some requests.

### ISSUE THREAD

**Issue by Sayusuli** [a85/POSTMan-Chrome-Extension#9104]
**Describe the bug**
Collection monitor in one case does not run the requests in order they are organized into folders.
As I don't use setNextStep and only expect requests to run in order the tests keep failing on one collection.
having 7 total collections and only one of them fails.

Tests work fine in collection runner and in newman.
Scenario:
1. get all preferences
2. post add 4 new preferences
3. get to verify that post has created n new values.
4. Delete preference 1
5. Delete preference 2
6. get to verify deletion
7. delete the rest
8. verify they have been deleted.

In Posman monitor the order changes to:
1. 3. get to verify that post has created n new values. (it fails)
2. 6. get to verify deletion
3. 7. delete the rest
4. 8. verify they have been deleted.
5. 4. Delete preference 1
6. 5. Delete preference 2

seems like requests 1 and 2 are not even ran.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.33.1]
 - OS: [macOS 10.15.5]

**Comment by DannyDainton** [comment]
Hey @Sayusuli 

Are you able to share an image of the Monitor run and the one you see in the runner, please?

This will help visualize the issue rather than trying the list out the order and help with the comparison.

**Comment by Sayusuli** [comment]
![Screenshot 2020-09-30 at 13 54 44](https://user-images.githubusercontent.com/69350371/94678633-7b2bad80-0327-11eb-9a4a-d2df7e10b774.png)
![Screenshot 2020-09-30 at 13 53 01](https://user-images.githubusercontent.com/69350371/94678642-7e269e00-0327-11eb-8809-c0feae37b5a3.png)

collection runner and same part from the collection in monitor.

**Comment by ArjunSingh-PM** [comment]
@Sayusuli Are you still facing this issue? If yes, could you please check if you have different versions of this collection (test-p1-users) or have any other collection with the same name? Also, did you see any 'errors' for the monitor run?

**Comment by Sayusuli** [comment]
Hi,
I figured it out. it was due to some syncing issues in postman.
I locally had different set of requests in different order.
Why tha happened i have no idea, but that caused it.
