### ISSUE TITLE
Headers, AUTH, BODY don't change the position. Its required extra clicking

### ISSUE THREAD

**Issue by MahalakshmiMasilamani** [a85/POSTMan-Chrome-Extension#9107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by MahalakshmiMasilamani** [comment]
Previously version has all the headers, AUTH, body section in the right place

**Comment by DannyDainton** [comment]
Hey @MahalakshmiMasilamani 

Could you use the template provided and add the relevant details and version information? 

As you're referencing something in the UI, an image would also be awesome. 🏆

**Comment by MahalakshmiMasilamani** [comment]
![Screenshot 2020-10-02 at 19 10 51](https://user-images.githubusercontent.com/42213280/94950660-42d0ce80-04e3-11eb-87b7-3ae0aa5cb99a.png)

Hi @DannyDainton,

Attached the UI screenshot. Even the response section also same to click and check the test response and headers.
When we are performing testing, eg: new API, request payload changes... We need to verify the logs with the header response(TraceID). Each time it is very difficult to double click and copy the traceID.

In the request need to update the header (cookies) and few times modify the test(javascript).

It would be very helpful we limit our multiple clicking

**Comment by MahalakshmiMasilamani** [comment]
Is there any shortcut key to navigate those headers, body, auth field?

**Comment by DannyDainton** [comment]
Hey @MahalakshmiMasilamani  👋🏻

Are you still facing this issue in the latest version of the platform?

**Comment by MahalakshmiMasilamani** [comment]
Hi Danny,

The reported issue is no longer in the current version. We are good to
close the issue


Thanks,
Mahalakshmi Masilamani
