### ISSUE TITLE
Text for Code Snippets fail to render properly on macOS Big Sur Beta

### ISSUE THREAD

**Issue by skargbo** [a85/POSTMan-Chrome-Extension#9108]
**Describe the bug**
Text and column in the 'Generate Code Snippets' field do not render properly (if at all) on macOS Big Sur beta (20A5364e).

**To Reproduce**
1. Click on 'Code' on API request window
2. In 'Generate Code Snippet' window, note that text is not rendered or only briefly displays

**Expected behavior**
Text and information for Code snippets should render in field.

**Screenshots**
![2020-09-30 08 50 39](https://user-images.githubusercontent.com/8403266/94709319-73094900-02fa-11eb-9790-af51587a1c5c.gif)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version: 7.33.1
 - OS: macOS Big Sur beta (20A5364e)

**Comment by DannyDainton** [comment]
Hey @skargbo 

Are you also seeing this happening in the light theme?

**Comment by skargbo** [comment]
Hey @DannyDainton - Yes, seeing this also with the light theme.  I'll note that a similar issue appears to exist with the field tip text for 'Request description (Optional)' in the 'Save Request' window launched by '+New' > 'Request'.

**Comment by DannyDainton** [comment]
As that's a new OS and not fully released I would imagine that it would have a few UI issues in there. As it's in Beta, we can't guarantee when these would be fixed. 

Thank you for reporting them, we will be looking to address these issues and other found during testing before Big Sur is GA.

**Comment by skargbo** [comment]
Sounds good.  Thanks for taking the time to have a look.  Cheers!

**Comment by DannyDainton** [comment]
This feature has been updated since the original issue and the location for the code snippets have moved to the right context bar. I'm going to close this for now but if you're still facing any issues in the latest version we can look to reopen this again.
