### ISSUE TITLE
Sync is not working - Unable to sync data.

### ISSUE THREAD

**Issue by r3faat1** [a85/POSTMan-Chrome-Extension#9110]
I am using Postman Desktop app, version: 7.33.1. This is used on Windows 10, 1909. 

When I sign on to my account, it signs on successfully. However, my "Sync" function is not working. When I try to create a workspace, it says to "Enable Sync". When I click on "Enable Sync", it just takes me to a website.

![image](https://user-images.githubusercontent.com/33644294/94723997-70185380-030e-11eb-9af0-453fa5961586.png)

**Comment by preethammavin** [comment]
@r3faat1 hey can you write to us at help@postman.com to get this sorted out for you?

**Comment by r3faat1** [comment]
Sure.

**Comment by r3faat1** [comment]
Issue as been resolved. Support team re-enabled my sync settings.
