### ISSUE TITLE
Manage environment window display blank for false value

### ISSUE THREAD

**Issue by DamayantiVinayakam2010** [a85/POSTMan-Chrome-Extension#9111]
**Describe the bug**
Manage environment window display blank for false value

**To Reproduce**
1. Define a environment variable with value as false 
2. for eg : isTest = false
3. Now on click of the view environment variables , the value for isTest = false
4. but when u load the environment to edit values Manage environment window loads the values , in this the 
initial value and current value for the variable is blank 

**Expected behavior**
In the manage environment window the variable should be able to display  isTest = false

**Screenshots**
Attached screenshots on click of how view environment variables display and how manage environment variables window behaves 

**App information (please complete the following information):**
 - Postman for Windows
 - Postman Version [e.g. 7.33.1]/ win32 10.0.19041 / x64
 - OS: [e.g. Windows 10 Single  ]

**Additional context**
![Manage_environment](https://user-images.githubusercontent.com/59367394/94775604-c6a09300-03dd-11eb-9882-83f08cd79c12.PNG)
![eye_icon_view_2](https://user-images.githubusercontent.com/59367394/94775635-d7510900-03dd-11eb-9a43-fd418c883ef3.png)

**Comment by Dhembla** [comment]
Hey @DamayantiVinayakam2010 ,
Sorry for the trouble that you have to go through because of this issue. We have released a fix for this as part of our latest release V10.12. Please check it out and let us know if there is any feedback. Thanks for your patience!
