### ISSUE TITLE
Pre-request Script (and Tests) slow global variables update

### ISSUE THREAD

**Issue by freerider7777** [a85/POSTMan-Chrome-Extension#9112]
When clicking Send quickly (2x per second for example) the variable is not updated as needed. Looks like it's updated asynchronously...

Postman for Windows
Version 7.33.1
win32 10.0.19041 / x64

1. Pre-request Script (Tests the same):

let counter = parseInt(pm.globals.get("counter")) || 100;
pm.globals.set("counter", counter + 1);
console.log("counter: " + counter)

2. Click several times to send a request (executes quick ~20-30 ms)
3. Open Postman Console
4. See that "counter" values sometimes does not change (does not increase as expected - 231 value is repeated)
 
POST http://localhost:5050/backendApi/v1/messages/send
200
31 ms
counter: 230
 
POST http://localhost:5050/backendApi/v1/messages/send
200
17 ms
counter: 231
 
POST http://localhost:5050/backendApi/v1/messages/send
200
20 ms
counter: 231

**Comment by DannyDainton** [comment]
Hey @freerider7777 

Is this still an issue for you, I can manually recreate it by clicking the send button quickly but I'm not really sure of the use case here. Are you also seeing this during automation runs?

I'm going to close this issue for now as I don't think this is something that we're going to be 'fixing'. Of course, if this is impacting several users we can investigate further.

**Comment by freerider7777** [comment]
It was a long time ago :)) I just needed a simple way to send a number of requests one by one (quickly clicking send), which was not working...
