### ISSUE TITLE
UUID generator in headers editior

### ISSUE THREAD

**Issue by hahyes** [a85/POSTMan-Chrome-Extension#9113]
**Is your feature request related to a problem? Please describe.**
Hi there,

I'm using Postman on Windows 10 and I have little annoying problem. I'm testing requests to some REST API and I need to create UUID to Trace-Id header in order to get in response proper Trace-Id string. This string is used to report errors for devs of REST API. 

**Describe the solution you'd like**
There is possibility to add something like UUID generator to headers editor? Like Right Click on header value and Generate UUID option? That would be great help. I think other people working with UUID would be happy, if UUID generator would be on the box.

**Comment by DannyDainton** [comment]
Hey @hahyes 

You can use the dynamic variable `{{$guid}}` in the header value - Would that suit your needs?

**Comment by hahyes** [comment]
> Hey @hahyes
> 
> You can use the dynamic variable `{{$guid}}` in the header value - Would that suit your needs?

Oh, I didn't know about that. And yeah, it's enough for me. Thanks.
