### ISSUE TITLE
Bootcamp Walkthrough stops at 23% "Remember the path" on "Design an API"

### ISSUE THREAD

**Issue by k-byun** [a85/POSTMan-Chrome-Extension#9118]
**Describe the bug**
Under the Bootcamp in Postman, BootCamp stops prematurely at 23%.

**To Reproduce**
1. Start Postman
2. In Bootcamp window, click "Designing and mocking APIs"
3. Select first lesson - "Design an API"
4. Go through the steps as prompted, but the procedure stops at 23% "Remember the path"

**Expected behavior**
Next step after 23%

**Screenshots**
![image](https://user-images.githubusercontent.com/72177353/95007522-1a71ce80-05ce-11eb-99db-aab16eeae0ad.png)
![Untitled](https://user-images.githubusercontent.com/72177353/95007504-ff06c380-05cd-11eb-93cb-bc5959f2932e.gif)

**App information (please complete the following information):**
 - App Type [e.g. Native App]
 - Postman Version [e.g. 7.33.1]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by k-byun** [comment]
Similarly, I can't get past a step at 12% in the "Design an API in a minute" lesson module under the Bootcamp "Designing and mocking APIs" - see the attached animated gif file below:
![Untitled1](https://user-images.githubusercontent.com/72177353/95007700-e5ff1200-05cf-11eb-9872-af9dcfcc2771.gif)

**Comment by davewburns** [comment]
I also have the same issue with stopping at 12%, I had previously completed the first lesson "Design an API"

**Comment by imankurpatel000** [comment]
Here is the error in console when you click on "Next" after the "remember path".
![image](https://user-images.githubusercontent.com/37868387/95303506-e2ee7500-08a0-11eb-88f1-2906e2a213b3.png)

**Comment by imankurpatel000** [comment]
Here's the link to an old version of Postman https://dl.pstmn.io/download/version/7.2.0/win64
In this version, I was able to finish all the Bootcamps without any issues. I am posting this just so if anyone is coming to here to looking for a solution to the Bootcamp issue then they can at least go through the Bootcamp by using an old version of Postman.

**Comment by k-byun** [comment]
Thank you Ankur for sharing that valuable info with all of us.  I definitely will be going through it sometime this week (for sure).

Greatly appreciated!

**Comment by arpitbatra123** [comment]
Hey @k-byun, We've fixed the issues happening in the Bootcamp lessons. Please try out the lessons and let us know if you're still facing these issues.

**Comment by k-byun** [comment]
this task of checking totally slipped my mind.  let me set a time tmrw to go through this.

**Comment by k-byun** [comment]
I've finally gone thorough the Bootcamp and was able to successfully complete it to 100%.  There were a few bugs I noticed but I was able to complete the Bootcamp.  - thanks

**Comment by GianniQTXR** [comment]
> I've finally gone thorough the Bootcamp and was able to successfully complete it to 100%. There were a few bugs I noticed but I was able to complete the Bootcamp. - thanks

Hi there, we're you able to complete the Bootcamp for the new version, or are you referring to the old one sent by Ankur?
