### ISSUE TITLE
Can't access objects returned in JSON array in postman test

### ISSUE THREAD

**Issue by calebreid** [a85/POSTMan-Chrome-Extension#9121]
**Describe the bug**
I have a GET request which returns an array of objects, I want to validate that each object has both an id and a name

This is the response (I have abbreviated it to 3 items for clarity)
```json
[
    {
        "id": "60816713",
        "name": "First object"
    },
    {
        "id": "60863297",
        "name": "Second object"
    },
    {
        "id": "60864389",
        "name": "Third object"
    }
]
```

This is my test:
```javascript
var jsonData = pm.response.json();

pm.test("Validate JSON data of summary list", function () {
    for (var i = 0; i < jsonData.length; i++) {
        pm.expect(jsonData[i]).to.include("id");
        pm.expect(jsonData[i]).to.include("name");
    }
});
```

But I get this error against the two pm.expect statements `Validate JSON data of summary list | AssertionError: object tested must be an array, a map, an object, a set, a string, or a weakset, but object given`

The message suggests that it's allowed to be an object which is why I have raised this as a bug.

**To Reproduce**
1. Use an endpoint which returns an array of objects.
2. Try to access a specific array item and try to check the contents of the object 

**Expected behavior**
To be able to validate the keys in each object when the root JSON object is a list.

**App information (please complete the following information):**
 - App Type: Microservice
 - Postman Version: v7.33.1
 - OS: Windows 10

**Comment by DannyDainton** [comment]
Hey @calebreid 

This seems like a question that would be best asked over on our community forum - https://community.postman.com

You could probably achieve this check using something basic like this:

```javascript
const jsonData = pm.response.json();

pm.test("Validate JSON data of summary list", () => { 
    jsonData.forEach(obj => pm.expect(obj).to.have.keys("id", "name"))
});
```

That was just a quick answer but the folks over on the community would be able to give you a better solution.

**Comment by calebreid** [comment]
Hi @DannyDainton 

Your solution does not work either. Could you explain why this isn't a bug given the error message? That would help me understand why this is better asked in the community forum. 

Thanks

Caleb

**Comment by DannyDainton** [comment]
What is it that doesn't work? 

Can you expand of that please and maybe provide a screenshot or an error message?

The message is coming from the Chai assertion library so if this is an issue, it would be with that library rather than specifically something that Postman has created.

This is a link to the API method that you're currently using in the test. 

https://www.chaijs.com/api/bdd/#method_include

**Comment by calebreid** [comment]
Hi @DannyDainton. Thank you for the explanation, that makes sense. And thank you for the documentation, I realised I was using your solution wrong and I've got it working now.

To help me understand for next time, is there an easy way for me to determine whether a problem I'm having is a bug in postman vs one of the libraries it uses?

**Comment by DannyDainton** [comment]
Glad you have it working now. 

Feel free to raise it if you feel it's a bug in the platform - We can take a look at it on our side and let you know.

I would advise posting a question on the community forum and gauge the reaction there too - lots of awesome people on there can let you know if they also feel it's an issue too.
