### ISSUE TITLE
Postman doesn't react to keyboard

### ISSUE THREAD

**Issue by KatseNarniaan** [a85/POSTMan-Chrome-Extension#9124]
**Describe the bug**
I installed new Postman from snap and now I'm unable to use the keyboard at all in Postman. I click in a text field, try typing, but nothing happens. For example the login screen, can't type anything for the email/username or password fields and mouse rightclick doesn't offer the rightclick menu for copy/paste. When I skip login, or login via webpage, and then try to type something in the request body, nothing happens. The only way to edit the body or any other input field, like params, is to highlight with mouse and rightclick to cut/paste. It gets a bit tedious to work only with mouse copy/cut/paste, when postman doesn't react at all to any keyboard pushes.

**To Reproduce**
sudo snap install postman
postman

**Expected behavior**
When I push the key "a" on my keyboard, I expect the letter "a" to appear in an input field.

**App information (please complete the following information):**
Postman for Linux
Version 7.33.1
Ubuntu 20.04.1 LTS / linux 5.4.0-47-generic / x64

**Additional context**

**Comment by KatseNarniaan** [comment]
Now Postman is suddenly working fine again.

**Comment by cidit** [comment]
having this issue too, fingers crossed it magically fixes itself
