### ISSUE TITLE
why works in postman and dont work on the site

### ISSUE THREAD

**Issue by maryst1986** [a85/POSTMan-Chrome-Extension#9125]
why works in postman and dont work on the site
postman make this code . other curl works on the server,,,,but this doecnt work. why? 
<?php
error_reporting(E_ALL);

$curl = curl_init();

assert(curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.sbis.ru/retail/sale/create",
 CURLOPT_AUTOREFERER => true,
CURLOPT_BINARYTRANSFER => true,
CURLOPT_COOKIESESSION => true,
CURLOPT_FOLLOWLOCATION => true,
CURLOPT_FORBID_REUSE => false,
CURLOPT_RETURNTRANSFER => true,
CURLOPT_SSL_VERIFYPEER => false,
CURLOPT_CONNECTTIMEOUT => 10,
CURLOPT_TIMEOUT => 11,
CURLOPT_ENCODING=>"",
CURLOPT_USERAGENT=>	$_SERVER["HTTP_USER_AGENT"],
  CURLOPT_MAXREDIRS => 10,
CURLOPT_COOKIE => 'sid=005e3401-005e3402-eeba-3a18ab4a679d60ca',
  CURLOPT_POST=>true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
        
  CURLOPT_POSTFIELDS => array ("companyID" => "162", 
"cashierFIO"=> "Курбатова М.В.", "operationType"=> "1", "cashSum"=> "100", "bankSum"=> null, "internetSum"=> null, "accountSum"=> null, "postpaySum"=> null, "prepaySum"=> null, "vatNone"=> "100", "vatSum0"=> null, "vatSum10"=> null, "vatSum20"=> null, "vatSum110"=> null, "vatSum120"=> null, "allowRetailPayed"=> "1", "nomenclatures"=> array ( "nameNomenclature"=> "Товар для животных в ассортименте", "barcodeNomenclature"=> "95211", "priceNomenclature"=> "100", "quantityNomenclature"=> "1", "measureNomenclature"=> "ШТ", "kindNomenclature"=> "Т", "totalPriceNomenclature"=> "100", "taxRateNomenclature"=> "0", "totalVat"=> "100" ), "customerFIO"=> null, "customerEmail"=> null, "customerPhone"=> null, "customerINN"=> null, "customerExtId"=> null, "taxSystem"=> "8", "sendEmail"=> "test@test.ru", "sendPhone"=> null, "propName"=> null, "propVal"=> null, "comment"=> "тестовый чек", "payMethod"=> "4"),
  CURLOPT_HTTPHEADER => array("Content-Type: application/json; charset=utf-8",
    "X-SBISAccessToken: bHNzLC4sVVtuOn5MS25TVRMOEJwaSQkUl5MR1Q5aUdLYWFneDU4QG52dCpsJUNHfjksLSRpQ09BI2taKVExYzIwMjAtMTAtMDIgMjA6MTU6MTIuNzEwNTA3\r\n"."Content-Length: 67\r\n"."Content-Disposition: inline; filename*=UTF-8\r\n"
  ),
)));

$response = curl_exec($curl);
print_r(curl_getinfo($curl));
//echo $curl;
curl_close($curl);

**Comment by maryst1986** [comment]
`<?php
error_reporting(E_ALL);

$curl = curl_init();

assert(curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.sbis.ru/retail/sale/create",
 CURLOPT_AUTOREFERER => true,
CURLOPT_BINARYTRANSFER => true,
CURLOPT_COOKIESESSION => true,
CURLOPT_FOLLOWLOCATION => true,
CURLOPT_FORBID_REUSE => false,
CURLOPT_RETURNTRANSFER => true,
CURLOPT_SSL_VERIFYPEER => false,
CURLOPT_CONNECTTIMEOUT => 10,
CURLOPT_TIMEOUT => 11,
CURLOPT_ENCODING=>"",
CURLOPT_USERAGENT=>	$_SERVER["HTTP_USER_AGENT"],
  CURLOPT_MAXREDIRS => 10,
CURLOPT_COOKIE => 'sid=005e3401-005e3402-eeba-3a18ab4a679d60ca',
  CURLOPT_POST=>true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
        
  CURLOPT_POSTFIELDS => array ("companyID" => "162", 
"cashierFIO"=> "Курбатова М.В.", "operationType"=> "1", "cashSum"=> "100", "bankSum"=> null, "internetSum"=> null, "accountSum"=> null, "postpaySum"=> null, "prepaySum"=> null, "vatNone"=> "100", "vatSum0"=> null, "vatSum10"=> null, "vatSum20"=> null, "vatSum110"=> null, "vatSum120"=> null, "allowRetailPayed"=> "1", "nomenclatures"=> array ( "nameNomenclature"=> "Товар для животных в ассортименте", "barcodeNomenclature"=> "95211", "priceNomenclature"=> "100", "quantityNomenclature"=> "1", "measureNomenclature"=> "ШТ", "kindNomenclature"=> "Т", "totalPriceNomenclature"=> "100", "taxRateNomenclature"=> "0", "totalVat"=> "100" ), "customerFIO"=> null, "customerEmail"=> null, "customerPhone"=> null, "customerINN"=> null, "customerExtId"=> null, "taxSystem"=> "8", "sendEmail"=> "test@test.ru", "sendPhone"=> null, "propName"=> null, "propVal"=> null, "comment"=> "тестовый чек", "payMethod"=> "4"),
  CURLOPT_HTTPHEADER => array("Content-Type: application/json; charset=utf-8",
    "X-SBISAccessToken: bHNzLC4sVVtuOn5MS25TVRMOEJwaSQkUl5MR1Q5aUdLYWFneDU4QG52dCpsJUNHfjksLSRpQ09BI2taKVExYzIwMjAtMTAtMDIgMjA6MTU6MTIuNzEwNTA3\r\n"."Content-Length: 67\r\n"."Content-Disposition: inline; filename*=UTF-8\r\n"
  ),
)));

$response = curl_exec($curl);
print_r(curl_getinfo($curl));
//echo $curl;
curl_close($curl);
`

**Comment by DannyDainton** [comment]
Hey @maryst1986 

I'm not really sure what you mean from this information - Can you update the issue with the following details to help us to understand the problem.

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See an error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Web App, Native App]
 - Postman Version
 - OS

**Additional context**
Add any other context about the problem here.

**Comment by DannyDainton** [comment]
Hey @maryst1986  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
