### ISSUE TITLE
Integration with Azure DevOps

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#9131]
**Is your feature request related to a problem? Please describe.**
Currently custom scrips should run to take backups of collections. Disadvantage is the high number of API requests to be executed and the missing traceability about who did what change. Audit logs have some value, but are limited in that sense.

**Describe the solution you'd like**
An integration support for Azure DevOps like the one for GitHub.

**Comment by shashankawasthi88** [comment]
Hi @jgraham8524, we have launched a repository integration with Azure DevOps in App version 9.6.0. Please refer to the blog post (https://blog.postman.com/the-reimagined-api-first-workflow-for-developers/) for ideal flow and learning center docs (https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#connecting-a-repository) to know how to configure Azure integration.
The Azure DevOps Service (TFS/ on-prem) will follow soon.
