### ISSUE TITLE
Postman cannot execute on macOS Catalina

### ISSUE THREAD

**Issue by alexandru** [a85/POSTMan-Chrome-Extension#9133]
Running on macOS Catalina 10.15.6. Don't know Postman's version, because I can't run it:

<img width="532" alt="Screenshot 2020-10-06 at 11 30 44" src="https://user-images.githubusercontent.com/11753/95177905-6f2c6980-07c7-11eb-85d9-7d10d909ac9b.png">

The issue was reported before:

- #6029
- #8507

This is most likely a package signing issue. Since this problem only manifests with Postman, and haven't had it with any other app—except for this one open source app, whose developer couldn't afford to pay the $99 tax. So I hope that's not it, because Postman is a commercial service 🙂

**Comment by DannyDainton** [comment]
Hey @alexandru 

Where did you download the package from? 

Was it from our website? 

https://www.postman.com/downloads/

The text suggests that but I wanted to confirm :D

**Comment by alexandru** [comment]
From the website, yes.

I have downloaded the latest (7.34.0), and now it seems to work. Possibly a delay in Apple's malware scan results or something? This is odd 🤔

Will now close the issue.
