### ISSUE TITLE
Drag and drop import doesn't work

### ISSUE THREAD

**Issue by byrdman** [a85/POSTMan-Chrome-Extension#9135]
**Describe the bug**
Trying to utilize drag-and-drop import of a collection doesn't work.

**To Reproduce**
1. Click on Import button
2. When import screen pops up, drag a collection from Windows File Explorer over
3. Cursor changes to have "copy"
4. Drop
5. Screen flashes and stays on import screen, nothing happens though.

**Expected behavior**
Collection should be imported as if browsed to

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
- App type: Native App
- Postman Version 7.33.1
- OS: Windows 10

**Additional context**

**Comment by mccannt** [comment]
@byrdman Thanks for reporting this issue. I was able to replicate this myself as well.
We will work to get this resolved soon. For the time being, please use the method of manually selecting the file to upload it. 
Sorry for the inconvenience.
