### ISSUE TITLE
Deeplink URLs for individual Collection Items/Requests

### ISSUE THREAD

**Issue by inland-rob** [a85/POSTMan-Chrome-Extension#9136]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem. I is a new functionality request.
I would like secure deeplinks that point to individual Collection items so I can reference them in my specification documentation.

**Describe the solution you'd like**
Simple a deeplink URL string that works to point to a specific Collection request in the app or on the web. Must be secure

**Describe alternatives you've considered**
No using Postman for URL specifications

**Additional context**
Being able to do this would start the process of using Postman at the specification stage. Making everyone happier. 🥇

**Comment by DannyDainton** [comment]
Each of the entities in the latest version of the platform provides a URL link that can be referenced in external documentation.
