### ISSUE TITLE
Not able to Pull during merge

### ISSUE THREAD

**Issue by pss-miracle** [a85/POSTMan-Chrome-Extension#9140]
**Describe the bug**
The issue seems to be that diff reports active conflicts while every conflict is already resolved during Pull 

**To Reproduce**
Having a collection in one workspace and a fork in another.

1. Go to the fork (that has changes) 
2. Merge
3. Pull (because it seems something in the source has changed)
4. See a list of conflicts marked with "2" in the left pane, and also some 'deleted' rows that are marked with '1' below
5. Resolve conflicts one by one using "destination" (the fork) and observe that all rows in the left pane are now marked with '1' (assuming resolved). No "use this" buttons are present
6. Press orange "Pull changes" as this is the only option now (besides cancel) 

Error message appears in the upper right corner:
Something went wrong
Resolve the active conflicts in the diff.

**Expected behavior**
Expecting merge screen to appear as usual.

**Screenshots**

![image](https://user-images.githubusercontent.com/41998060/95370168-adfe1480-08d8-11eb-9efb-163fbc6a7d48.png)

**App information **
 - App Type [e.g. Native App]
 - Postman Version [e.g. 7.33.1]
 - OS: [e.g. Windows 10]

**Comment by DannyDainton** [comment]
Hey @pss-miracle 

I know it's been a while - Apologies for that. 😬  Are you still facing this issue in the latest version of the platform?

I'm going to close out this for now but if this is still a problem for you, we can look to reopening this again.
