### ISSUE TITLE
Bug : distorted text in postman generate code(left sidebar) both app and webiste.

### ISSUE THREAD

**Issue by aksharma53** [a85/POSTMan-Chrome-Extension#9147]
**Describe the bug**
Language is text is distorted as shown below:-
![Untitled Project](https://user-images.githubusercontent.com/50196057/95486845-2df7ad80-09b1-11eb-81bc-bbece8843c02.gif)

**To Reproduce**
1. Go to Code in generate code snippet both app as well as website and resize the window you will see 

**Expected behavior**
Avoid distortion in text it should be clear.

**App information (please complete the following information):**
 - App Type: both app 
 - Postman Version: v7.33.1
 - OS: Windows 10

**Comment by mccannt** [comment]
@Alphasaurs Thanks for reporting this. We are able to replicate this issue. 
It looks like an issue with the size of the screen and resolution. If you resize the window or zoom out you should be able to read everything fine (if you are able to do this).

We will work to get this resolved soon and let you know when it has been fixed.

**Comment by umeshp7** [comment]
Thanks for reporting this @Alphasaurs 

This view has been updated to a different view in the recent versions (8.x). 
Do try the latest version and let us know if still face any issues with the updated code generator UI.
