### ISSUE TITLE
Link replication, hosts management

### ISSUE THREAD

**Issue by xpwi** [a85/POSTMan-Chrome-Extension#9151]
1、Link replication
2、hosts management

**Comment by DannyDainton** [comment]
Hey @xpwi

Without the basic information and the context behind this issue, we're unlikely to be able to do anything about this.

Can you expand on this issue please?

**Comment by DannyDainton** [comment]
Closing this issue are it's lacking the contextual details for us to progress it further. If the details are provided, we will look to open it up again.

Please use the template as a guide to show what information we require.
