### ISSUE TITLE
Runner wit data files does not load iteration data from JSON

### ISSUE THREAD

**Issue by loretoparisi** [a85/POSTMan-Chrome-Extension#9152]
**Describe the bug**
I have a iteration data file as json:

```json
[
    {
        "value": 85365070
    },
    {
        "value": 114947355
    },
    {
        "value": 113838056
    }
]
```
When I do Runner, I can see the json correctly file loaded in the collection runner, but following the tutorial described in ["Running collections with data files"](https://learning.postman.com/docs/running-collections/working-with-data-files/) the runner will not use the `{{value}}` variable that I have defined in the URL, from the json data file iteratively, but it will use the first item only.

**To Reproduce**

**Expected behavior**
To load iteratively the values from the json file

**Screenshots**
<img width="736" alt="Schermata 2020-10-12 alle 09 41 05" src="https://user-images.githubusercontent.com/163333/95718683-12b9c600-0c6f-11eb-8624-71fb19920be2.png">

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
macOS Desktop App
 - Postman Version [e.g. 6.0.1]
` 7.34.0 (7.34.0)`
 - OS: [e.g. macOS High Sierra 10.13.2]
`macOS 10.14.5`

**Additional context**

**Comment by DannyDainton** [comment]
Hey @loretoparisi,

In the runner, can you ensure that the iteration count matches the number of items in the file.

Sometimes, what happens is that on the initial loading of the file the count is set correctly, which would be the number of objects in the array. If any edits are made to the file, the preview will show the correct amount but the iteration count wouldn't have changed.

I believe that there's a bug open for this already but it would be great if you can confirm that's what is happening.

**Comment by loretoparisi** [comment]
@DannyDainton so, I have found that it works if I put some code in the "Tests" section. I have put this metrics https://gist.github.com/romcaname/dfc98b4f5577fb0deb4fb2b5ea3c6017

**Comment by DannyDainton** [comment]
I took a look but as that code is from a few years ago and the syntax is slightly different, I'm not sure what you currently have in your tests. 

Could you paste the code here and maybe expand on the use case a little bit please?

Also, a point to note on the builder / runner - if you have unsaved changes in the request tab, the runner won't pick these up so ensure that things are all saved before running again.

**Comment by loretoparisi** [comment]
@DannyDainton the code is this

```javascript
function standardDeviation(values, avg) {
    var squareDiffs = values.map(value => Math.pow(value - avg, 2));
    return Math.sqrt(average(squareDiffs));
}

function average(data) {
    return data.reduce((sum, value)=>sum + value) / data.length;
}

if (responseCode.code === 200 || responseCode.code === 201) {
    response_array = globals['response_times'] ? JSON.parse(globals['response_times']) : []
    response_array.push(responseTime)
    postman.setGlobalVariable("response_times", JSON.stringify(response_array))

    response_average = average(response_array);
    postman.setGlobalVariable('response_average', response_average)

    response_std = standardDeviation(response_array, response_average)
    postman.setGlobalVariable('response_std', response_std)
}
```

**Comment by DannyDainton** [comment]
There's a bunch of context missing here and the actual request you're making is unknown.

That script relates to things that might not be specific to your request. It's also using some of the older syntax. 

I don't really see any place that you're using the data from the file you're running.

This seems more like a question that's better placed over on our Community forum - You'll be able to expand on the full details of your usecase and the problem you're trying to solve.

https://community.postman.com

**Comment by loretoparisi** [comment]
Thank you.
