### ISSUE TITLE
Could not open Postman

### ISSUE THREAD

**Issue by ChesterZheng** [a85/POSTMan-Chrome-Extension#9153]
![图片](https://user-images.githubusercontent.com/23701211/95718736-72c96000-0ca1-11eb-866d-851309115f52.png)

**Comment by ChesterZheng** [comment]
@DannyDainton Hi, when i upgraded postman from v7.10.0 to the newest & restarted it, the error window shows like the picture. I tried to uninstall and install the newest version, the same error appears.

**Comment by clementizard** [comment]
Same issue here, except i don't have any error showing up and postman icon stays in the bottom right. Any actions requiering the app to show up does nothing. Even if launched with administrator rights.

**Comment by Raj-postman** [comment]
Hi @ChesterZheng @clementizard,

Clearing local files of your Postman installation generally resolves this issue. May I know if you have followed the steps mentioned in this article below?

- [Could not open Postman error](https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-)

**Comment by ArnieGA** [comment]
Hi.
I encountered the very same problem, resulting in the very same error screen, while upgrading to Postman version 7.34.0 (64bit) on a Windows 10 Pro.

I'm happy to report that after following [these steps](https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-#h_47ace2f6-ecfa-4917-a72a-9312ef87ae8f) as suggested by @Raj-postman, using the latest version of CCleaner to clean the registry entries, restarting my PC and finally clean-installing Postman, my issue got resolved.

I'd like to point out that in my case, ensuring that **none of the local Postman directories (`\AppData\Local\Postman` and `\AppData\Roaming\Postman`) exist before running the installer was the issue fixer**. I was removing the one in Local but didn't know there was another one in Roaming.  Making sure both of them got removed fixed the issue.

**Comment by Raj-postman** [comment]
@ChesterZheng @clementizard did that help you?

**Comment by DannyDainton** [comment]
Hey @ChesterZheng / @clementizard 

Is this still an issue that you're facing or can we close this one out?

**Comment by DannyDainton** [comment]
Hey @ChesterZheng / @clementizard  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.

**Comment by ChesterZheng** [comment]
Hi Danny

  Acturally, I'm already upgraded the version. 

Thanks. 


***@***.***
 
From: Danny Dainton
Date: 2022-03-30 17:32
To: postmanlabs/postman-app-support
CC: Chester Zheng; Mention
Subject: Re: [postmanlabs/postman-app-support] Could not open Postman (#9153)
Hey @ChesterZheng / @clementizard ????????
I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
