### ISSUE TITLE
Shortcut for moving up and down the rows is not working in Params tab

### ISSUE THREAD

**Issue by lucifercr07** [a85/POSTMan-Chrome-Extension#9157]
**Describe the bug**
When a query param is selected and we try to use the shortcut for moving up and down the rows i.e CMD + SHIFT + Arrow UP (or Arrow Down). It displays "Something Went Wrong" and unable to return to the request, so the request itself is lost.

**To Reproduce**
1. Create a new request.
2. In the Params tab create at least 3 Key-Value combinations.
3. Select any element that is neither the top nor the bottom one.
4. Use the shortcut CMD + SHIFT + Arrow UP (or Arrow Down).

**Expected behavior**
The list of params should scroll up or down.

**App information (please complete the following information):**
 - Postman Version [e.g. 7.34.0]

**Comment by mohitranka** [comment]
Release with App version 8.0.3
