### ISSUE TITLE
Copied Environment has incorrect "role" assigned

### ISSUE THREAD

**Issue by rosibaj** [a85/POSTMan-Chrome-Extension#9159]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15824252/95872014-54fd0900-0d3c-11eb-9259-5cceb4f4ba30.png)

**To Reproduce**
1. Make an environment.  Click the Copy button
2. Edit some fields i the env. Click save
3. Leave and try to re-edit the environemt.  you can get these errors: 
![image](https://user-images.githubusercontent.com/15824252/95872155-7d850300-0d3c-11eb-9723-7d5f0758bf48.png)
![image](https://user-images.githubusercontent.com/15824252/95872206-88d82e80-0d3c-11eb-80c8-9beecd000125.png)

**Expected behavior**
When i copy an environement in my personal collection, it should give me complete access.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - Postman v7.33.0
 - OS: Windows

**Comment by mccannt** [comment]
@rosibaj Thanks for reporting this. I have tried to replicate this issue but I am not able to see the same outcome. 
Can you clarify the step of "Leave and try to re-edit the environment."? 
Thanks

**Comment by rosibaj** [comment]
@mccannt i meant "click the update button, which returns you the the list of all environemnts` for that step

**Comment by mccannt** [comment]
@rosibaj I am still not able to successfully replicate this issue. Can you possibly try this on the latest version of the app, v7.34.0?

Can I also assume you are doing all of this in a personal space?

**Comment by xk0der** [comment]
@rosibaj I'm closing this thread for now, but do let us know if you still face this issue on the latest versions: https://postman.com/download
