### ISSUE TITLE
Adds space into URL

### ISSUE THREAD

**Issue by eugene-rockspoon** [a85/POSTMan-Chrome-Extension#9160]
**Describe the bug**
Somehow Postman adds space into URL before `/`.
And most curious thing that if I copy code of the request to the any editor(`Sublime` or `Slack`) it doesn't have an extra `space`, but I can see it in the terminal

```
curl --location --request POST '{{base_url}}/thing/:id/item/:subID/mySubThing {here is an extra space}/:subSubID/action' \
```

**To Reproduce**
1. Create `Collection`
2. Create new `POST` or `DELETE` request with a few parameters(didn't test with other methods)
2. Click on `Send`

**Expected behavior**
 Instead of `404` error I want to see at least `500`

**App information (please complete the following information):**
 - Postman Version 7.29.1 (7.29.1)
 - OS: macOS Catalina 10.15.7

**Additional context**
Happens only with requests with 3 and more parameters and every time adds space before the `/` after last parameter

**Comment by vikiCoder** [comment]
Hi @eugene-rockspoon 

I was unable to reproduce it in the latest version of the Postman desktop app (v7.34.0). I created a new request and entered the URL you have mentioned (also added some dummy values for path variables). Then I checked the code and copy-pasted it in the editor. I didn't see any extra spaces in the pasted code. Here's a screen recording of what I tried.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/16588032/96377764-5055ac00-11a5-11eb-9dd1-3503ef99b1a8.gif)

Can you please update to the latest Postman app and see if it is still reproducible for you? If it is, please provide screenshots/recording for us to understand what you are exactly trying to do.

**Comment by vvs11** [comment]
@eugene-rockspoon Could you attach a video highlighting the steps when you see this issue? Will help us in finding the root cause more efficiently

**Comment by eugene-rockspoon** [comment]
Cannot reproduce it with `Version 7.36.5 (7.36.5)`
