### ISSUE TITLE
Team sync doesn't work

### ISSUE THREAD

**Issue by jkewley** [a85/POSTMan-Chrome-Extension#9172]
**Describe the bug**
I have two work computers. One is a corporate device behind a client proxy. Another is a company laptop with direct Internet connection. I have been trying to use Postman to collaborate with team members on the shape of a payload for a successful request in Postman desktop.

Edits on one machine sometimes show up on the other, but not typically. Rearranging requests in a collection appear to sync correctly. Team members have different versions of the same response payload, even though we are all restarting PM and licking the manual sync button.  **_No errors are being reported to end users._**

This has become harmful to our team, as we often find ourselves working against legacy sample payloads. As a result we've moved to the web interface for Postman because it apparently works directly off of the sync storage back end. This is not ideal for our team's productivity, but is better than wasting time with an old payload.

At the moment I have a request with a single response, That response is out dated in both of my personal clients as compared to what is visible in the web interface. I've tried closing and upgrading the Postman clients on both machines, but I cant get the clients to pick up the new payload edits which are available in the web interface. It's been about 4 hours since I last updated web.

**To Reproduce**
This is easy to reproduce if you are working in a team 

**Expected behavior**
Normal sync behavior that is present in most software 

>> If Postman knows that a sync is failing or that there is a condition which is preventing it from syncing (say it's been updated in multiple places and can't sync safely) ****It Should Notify The End User Without Requiring Them To Explore The Logs**** - especially if they are working in a team workspace

Without this you are putting end users at risk if part of their daily workflow involves Postman iteration.

**App information (please complete the following information):**
 - App Type : Windows and Web
 - Postman Version 7.34.0
 - OS: Windows 10 / x64

**Additional context**
Can provide collection-level detail if required for root cause analysis

**Comment by DannyDainton** [comment]
Hey @jkewley 

I've been unable to recreate this issue, are you still facing issues with the latest version of the platform?

**Comment by jkewley** [comment]
It's been two years and two companies. I abandoned the team subscription at that company and won't pay for it again or suggest that my current company invest in Postman
