### ISSUE TITLE
postman not giving proper response(All time giving 404 response for every api)

### ISSUE THREAD

**Issue by Steffi-cloud** [a85/POSTMan-Chrome-Extension#9173]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
http://localhost:8080/courses
![postman_error](https://user-images.githubusercontent.com/67022557/96368999-f5a45c00-1174-11eb-8f14-6f3a1ba3d896.jpg)

{
    "timestamp": "2020-10-18T13:25:10.917+00:00",
    "status": 404,
    "error": "Not Found",
    "message": "",
    "path": "/courses"
}

**Comment by DannyDainton** [comment]
Hey @Steffi-cloud

This is an issue with the route you're hitting rather that anything specifically wrong with Postman. The server is returning that response body. 

I would check the implementation of that API, it looks like you're running it locally so I'm guessing that you have the code. Check that you have a `/courses` route and it's not hot anything else in the path. 

I'm going to close this as it's not a functional issue with the app, if you needed more assistance from the Postman community - You can create a new thread in the forum and explain what's happening.

https://community.postman.com
