### ISSUE TITLE
Windows crashing

### ISSUE THREAD

**Issue by luis-ten** [a85/POSTMan-Chrome-Extension#9177]
When using Postman 7.34.0, Windows 10 is experiencing an error. The operating system is crashing. The computer is a Dell Vostro 5490 with the Nvidia MX230 video adapter, which is activated automatically when the Postman is started. The error happens after a few minutes using Postman. This error also occurs in previous versions of Postman.
![P_20201019_100226_vHDR_Auto](https://user-images.githubusercontent.com/31459540/96460865-0ea32080-11fa-11eb-999c-1d7ecf48ca1b.jpg)

**Comment by RaisinTen** [comment]
duplicate of https://github.com/postmanlabs/postman-app-support/issues/10066
