### ISSUE TITLE
Improvement - "You have an update" prompt 

### ISSUE THREAD

**Issue by asi-postman** [a85/POSTMan-Chrome-Extension#9179]
Submitting on the behalf of the community. 

>Could you make the "You have an update" prompt a little less annoying? I don't need a reminder hijacking the top part of my Postman window every time there's an update. A small red dot or something somewhere is enough.

**Comment by numaanashraf** [comment]
@asi-postman This banner is shown only after a week since an update is available. Up to a week we show a small indicator on the settings icon.

**Comment by DannyDainton** [comment]
Closing this out due to inactivity.
