### ISSUE TITLE
Publishing the generated collection

### ISSUE THREAD

**Issue by alexibz** [a85/POSTMan-Chrome-Extension#9181]
In the postman app there's an option to Share the collection and then "Update public link". With the collection being regenerated with the library each time, is there a way to have the same "public link" be updated? Or maybe completely forego the UI, and have a command line option that would update the collection at that link?

**Comment by DannyDainton** [comment]
Hey @alexibz 

Would you be able to expand on this use case please and walk through what's currently happening for you?

It's difficult to know what you would like to see happen from the information you have given. 😄

**Comment by alexibz** [comment]
Hi @DannyDainton, I should've been more thorough in my description 😅 

We use an openapi spec file to generate our documentation and now our postman collection using the very helpful [openapi-to-postman ](https://github.com/postmanlabs/openapi-to-postman) library in our CI. So our flow is:

1. Make a change to the openapi specification file.
2. Commit to github
2. This triggers the CI process to generate the documentation and the postman collection automatically.

The problem lies in the "shareable link" to the postman collection. Before, when we maintained the postman collection manually, we would have a Team account in Postman, into which we would login, make the required changes to requests, and then click the `Update Link` button, which would propagate our collection changes.
![image](https://user-images.githubusercontent.com/54906681/96898229-7e651580-145d-11eb-8780-10482a097110.png)

This was great since it would make the link static, and we wouldn't have to update the links in our documentation. Now though, with the automated process of generating the postman colleciton - even if I do the "share" step manually, I would have to import the newly generated collection into postman, click "Share Collection", and the link would be different. 

In an ideal world, there would be a way to have a static link and the generated collection would be published each time with that static link. Is that something possible?

**Comment by DannyDainton** [comment]
Have you explored using the Postman API to create the Collection in the account?

That way you have would have the most upto date Collection available from the same URL. There wouldn't be the need to use that public link and manually update it.

https://documenter.getpostman.com/view/631643/JsLs/?version=latest

**Comment by alexibz** [comment]
Thanks Danny - that's perfect for my use case. 

Just to confirm, if I update a collection that has a public link, using the `PUT Update Collection` endpoint, the public link will remain the same.

**Comment by DannyDainton** [comment]
Hey @alexibz

Sorry I totally missing this message 😢

Were you able to try this out to see if this was working, after you updated the Collection via the API?

**Comment by DannyDainton** [comment]
I've just tried this out on my side and the Public Link remains the same.

I'm going to close this for now but we can look to open it again if you're seeing something different happening.
