### ISSUE TITLE
Bad formatted json string on using randomLoremText in exampleResponse

### ISSUE THREAD

**Issue by maikusch** [a85/POSTMan-Chrome-Extension#9182]
Im working the first time with postman mocks. I generate a request for getting dummy data so i use the random variables.

my responst looks like this:
`
[
    {
        "id": "{{$randomUUID}}",
        "name": "{{$randomProductName}}",
        "description": "{{$randomLoremText}}",
        "points": 100,
        "level": "beginner"
    },
    {
        "id": "{{$randomUUID}}",
        "name": "{{$randomProductName}}",
        "description": "{{$randomLoremText}}",
        "points": 100,
        "level": "beginner"
    },...
`
If i debug the generated json string in my response i always get bad json because of line breaks i think.
Or maybe i have to do it otherwise?

**Comment by Cyperwu** [comment]
Hi @maikusch , how did you fixed this?
