### ISSUE TITLE
Pull Request created from Personal Workspace Collection to Team Workspace Collection gives permission denied

### ISSUE THREAD

**Issue by omkar-dsd** [a85/POSTMan-Chrome-Extension#9183]
**Description**
PR should be visible even if the reviewer does not have permission to the source collection

**To Reproduce**
1. Create a folder in ABC Collection in Team Workspace
2. Fork ABC-sample to Personal Workspace
3. Add new APIs to forked workspace
4. Create PR back to the parent collection
5. Ask some user of the parent collection to check the PR
6. It tells that reviewer should have access to both Source and Destination Collection 

**Expected behavior**
PR should be visible in the above stated scenario. We won't be giving permission to personal collection again and again for every forked collection.

**App information :**
 - Postman Version 7.34.0

**Comment by omkar-dsd** [comment]
This is urgent and blocking our current use-case flow.

**Comment by ankit-m** [comment]
Apologies for such a late response. We are looking to improve this workflow in our upcoming releases. Will keep this thread updated.

**Comment by ankit-m** [comment]
As a workaround, instead of forking the collection in a personal workspace, if you fork it into the same team workspace and then create a PR, all team members will have view access.

**Comment by omkar-dsd** [comment]
Yes, as a workaround we are following the same. But it's actually messing up the team workspace.

**Comment by ankit-m** [comment]
We have now added an explicit step to share the collection from personal > team workspace before creating a PR in a team workspace.

Elements in personal workspaces are only visible to the user, not the team. To view the diff between collections, team members need access to the forked collection. Hence the need for sharing. We do realize that this may end up in team workspaces having multiple collections. We are working on workflows to better manage forks and maintain a clean team workspace. It will be released soon. :)
