### ISSUE TITLE
Postman Mock Server matching algorithm logic for request body param form-data

### ISSUE THREAD

**Issue by abdullah4one** [a85/POSTMan-Chrome-Extension#9184]
I added this in header x-mock-match-request-body:true

Postman responding with this error message

```json
{
    "error": {
        "name": "mockRequestNotFoundError",
        "message": "Double check your method and the request path and try again.",
        "header": "No matching requests"
    }
}
```

<br>form-data<Br><br>https://stackoverflow.com/questions/64425539/postman-mock-server-matching-algorithm-logic-for-request-body-param-form-data

**Comment by Raj-postman** [comment]
Hi @abdullah4one 

Could you please check [this screen-record](https://www.youtube.com/watch?v=qgurMVJgPd4) for this case and let us know if that helps?

**Comment by Dhembla** [comment]
Hey @abdullah4one 👋 
We have added support for body matching on text fields for form/data content type. Please give it a try and let us know if that works for you. 🙇

**Comment by Dhembla** [comment]
Hey @abdullah4one, 
I am closing this issue. Please feel free to reopen it if the fix does not work for you.
