### ISSUE TITLE
Bootcamp Lesson options Resume & Learn no longer function

### ISSUE THREAD

**Issue by cikent** [a85/POSTMan-Chrome-Extension#9186]
_Originally posted by @cyrielle-hada in https://github.com/postmanlabs/postman-app-support/issues/8221_

As of Postman Release v7.34.0, this issue appears to have regressed and is actively reproducing again.

Anytime I attempt to **Resume** or start a new lesson with **Learn**, either option, results in absolutely nothing happening inside of Postman.

**Comment by cyrielle-hada** [comment]
@prashantagarwal I managed to reproduce the issue reported by @cikent here. 
Is it a known issue?

**Comment by arpitbatra123** [comment]
Hey, @cikent Can you please check whether this happens for all lessons or a specific set of lessons?

**Comment by cikent** [comment]
As of today (Postman v7.35.0), what I'm seeing in relation to this issue is:

Working: (i.e. These Lessons seem to accurately display the UI Tooltips and Untitled Request when Learn, Resume or Restart is selected)
- Designing and mocking API's
-- Design an API
-- Design an API in a minute
- Debugging and manual testing
-- Global variables
-- Environment variables
-- Collection variables
- Automated testing
-- Working on test scripts
-- Working on pre-request scripts
-- Building workflows
-- Carry data between requests
- API Documentation
-- Document an API
- Monitoring
-- Monitoring a collection
- Collaboration
-- Collaborate with your team
-- Forking and merging

Not working: (i.e. These Lessons do not accurately display the UI Tooltips when Learn, Resume or Restart is selected)
- Debugging and manual testing
-- Debugging and manual testing

The Lesson: *Debugging and manual testing* is populating the Untitled Request tab now, it wasn't doing that before, but other UI Tooltips associated with this lesson still fail to display.

Hope this helps. Thank you for the resolution on the other Lesson's.

**Comment by cikent** [comment]
> Hey, @cikent Can you please check whether this happens for all lessons or a specific set of lessons?

As of today (Postman v7.35.0), what I'm seeing in relation to this issue is:

Working: (i.e. These Lessons seem to accurately display the UI Tooltips and Untitled Request when Learn, Resume or Restart is selected)
- Designing and mocking API's
-- Design an API
-- Design an API in a minute
- Debugging and manual testing
-- Global variables
-- Environment variables
-- Collection variables
- Automated testing
-- Working on test scripts
-- Working on pre-request scripts
-- Building workflows
-- Carry data between requests
- API Documentation
-- Document an API
- Monitoring
-- Monitoring a collection
- Collaboration
-- Collaborate with your team
-- Forking and merging

Not working: (i.e. These Lessons do not accurately display the UI Tooltips when Learn, Resume or Restart is selected)
- Debugging and manual testing
-- Debugging and manual testing

The Lesson: *Debugging and manual testing* is populating the Untitled Request tab now, it wasn't doing that before, but other UI Tooltips associated with this lesson still fail to display.

Hope this helps. Thank you for the resolution on the other Lesson's.

**Comment by roseechoii** [comment]
Hello, I was wondering if there are any updates to this issue?

**Comment by arpitbatra123** [comment]
Hey, @roseechoii @cikent We've fixed the issues happening in the Bootcamp lessons. Please try out the lessons and let us know if you're still facing these issues.

**Comment by jansche** [comment]
Hey there,
This issue is still reproducing in the current version of Postman app (8.8.0) on MacOS Big Sur (11.4). 
Experienced it in Bootcamp, and brought to attention here on the forums:
https://community.postman.com/t/bootcamp-continue-learning-resume-does-nothing/11371/8?u=jansche
Thanks!

**Comment by AitorGuerrero** [comment]
Hi! Im experiencing it at Ubuntu 21.10

**Comment by Stacy-Sanders** [comment]
Hello! I am also experiencing issues with the Postman Bootcamp for Windows. I was able to proceed to 56% completion for creating a mock server and then it stops. No more popups guiding my choices.

**Comment by rkulagowski** [comment]
Postman v9.9.3

I'm getting failures when going through the bootcamp; on the Environments module, after setting the variable "environment_type" and clicking Next, nothing happens. I'm not guided to the next step.

**Comment by strangesongs** [comment]
Using Postman v9.9.3 on macOS Monterey 12.1

I've been receiving similar errors for some time now. If I click away from a dialogue box in Bootcamp, the box disappears and I cannot continue with the lesson. Sometimes it seems that the box will disappear entirely if I click outside of the box or do not click NEXT or the item referenced (i.e. MOCK SERVER, GLOBALS, etc) directly.

Hitting RESUME on the Bootcamp page always resets the lesson entirely.

If I go back to RESUME, the lesson restarts.

**Comment by kskilt** [comment]
Following up that this still exists. Selecting environment at 56% is the last directed task before the lesson stops leading

**Comment by ashn45** [comment]
I'm experiencing the same issues as strangesongs and kskilt. Using postman in Edge, working on the "Design an API in a minute" bootcamp, I'm able to complete 56% and get a prompt to "Switch the environment" 

![image](https://user-images.githubusercontent.com/105071309/167178871-20fc80e0-72f1-4d03-8d69-8392edd9f647.png)

However, after I change the environment, the bootcamp prompts disappear and I am unable to resume. My bootcamp button along the bottom toolbar gives me the option to "Continue learning," but choosing this option restarts the bootcamp. Attempting to resume not from the toolbar but from https://web.postman.co/bootcamp also only restarts the lesson. 

![image](https://user-images.githubusercontent.com/105071309/167179089-e60e3e3c-d3cb-410d-8839-a7a958ded6ea.png)

Unable to complete this bootcamp

**Comment by arlemi** [comment]
Hey there,

I'm closing this issue as the Bootcamp is not available in the app anymore from the March 2023 (v10.12) release.

If you're interested in Postman training courses here's a few resources to check out:
-  [Postman Quickstarts](https://quickstarts.postman.com/) 
-  [Postman Academy](https://academy.postman.com/)
- [Postman Intergalactic webinars](https://www.postman.com/events/intergalactic/)
