### ISSUE TITLE
Nova Integração - <postman-app-support>

### ISSUE THREAD

**Issue by rinaldiluciene** [a85/POSTMan-Chrome-Extension#9191]
Desenvolvimento de APIs

O Postman será utilizado para integrar produtos / ferramentas específicos e para simplificar testes.

Ainda não considerei nenhuma ferramenta alternativa. Esta é a minha primeira escolha para testes

**Comment by DannyDainton** [comment]
Hey @rinaldiluciene,

I'm not sure if this was created by mistake or it's just lacking the details needed for a new integration request. 

I'm going to close this issue for now but we can open it up again if you provide more details and context for the request.
