### ISSUE TITLE
Inconsistent Introduction link between web version and API docs

### ISSUE THREAD

**Issue by mindaugasw** [a85/POSTMan-Chrome-Extension#9192]
There is a small inconsistency between Postman web version (https://web.postman.co/collections/123456?version=latest&workspace=123456) and API docs (https://documenter.getpostman.com/view/1234567/abc123): Introduction section link on the former one is `#introduction`, but `#intro` on the latter. This makes it impossible to create a link in the documentation to the introduction, which would work both on web version and API docs.

Attaching screenshots:  
1. On Postman web version (https://web.postman.co/collections/123456?version=latest&workspace=123456)
![](https://i.imgur.com/klVDy5x.png)

1. On API docs online (https://documenter.getpostman.com/view/1234567/abc123)
![](https://i.imgur.com/qgGuObR.png)

**Desired behaviour**: that Introduction url in both versions would be the same, so that it would be possible to link to it. Right now link will not work in one place or the other.
![](https://i.imgur.com/CQlwZCb.png)

**Comment by Himanshu0781** [comment]
Closing the issue as we have moved to query params from hash fragments in postman-app. Please re-open if required.
