### ISSUE TITLE
Postman is giving blank grey  screen after few seconds,then need to restart it 

### ISSUE THREAD

**Issue by Namrata23github** [a85/POSTMan-Chrome-Extension#9193]
**Describe the bug**
Postman is giving blank grey  screen after few seconds,then need to restart it 

**To Reproduce**
1. Open postman
2. switch desktop on mac 
3. come back to the desktop where the postman was there
4. complete blank grey screen and hence not able to perform any action

**Expected behavior**
It should not show grey screen and allow to perform any action

**Screenshots**
![image](https://user-images.githubusercontent.com/34562445/96831023-f03b6000-1459-11eb-95ea-279e6f2b0fda.png)

**App information (please complete the following information):**
 - Postman Version 7.34.0 (7.34.0)
 - OS: macOS Catalina 10.15.5

**Comment by Raj-postman** [comment]
Hi @Namrata23github,

Looks like [this suggestion](https://github.com/postmanlabs/postman-app-support/issues/9072#issuecomment-694790050) worked for users facing similar issue: https://github.com/postmanlabs/postman-app-support/issues/9072#issuecomment-694790050

Could you follow the same and let us know if that helps?

**Comment by mtt88** [comment]
I faced an identical issue whilst using PostmanCanary. I was able to solve the issue by following the advice in [`this comment`](https://github.com/postmanlabs/postman-app-support/issues/4634#issuecomment-574073350).

**Comment by letowebdev** [comment]
I solved the issue by just going to the postman directory, than chose a previous version and it worked like a charm, so if that did it for you then you may want to add a shortcut to your desktop

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5980
