### ISSUE TITLE
Importing swagger.json only creates API documentation but no collection appears, although it says "1 API and 1 collection were imported."

### ISSUE THREAD

**Issue by kristjanparve** [a85/POSTMan-Chrome-Extension#9194]
I am trying to import a swagger.json from a link to create a collection from it but I can only see the API documentation it created.
for example: https://api.ionos.com/cloudapi/v5/swagger.json.
If I use the deprecated Chrome version it does work.

**To Reproduce**
1. Import - enter url https://api.ionos.com/cloudapi/v5/swagger.json
2. Click on "continue"
3. Click on "import"
4. See "1 API and 1 collection were imported."
5. Open Collections from left hand side - can't find the collection
6. Do the same flow in Chrome app - collection is created

**Expected behavior**
There should be a collection created.

App information
 - App Type : Native App
 - Postman Version:  v7.34.0
 - OS: Ubuntu 18.04.4 LTS

**Comment by abhinaba-ghosh** [comment]
Hi @kristjanparve , Thanks for connecting. I am not able to reproduce the issue in the target version of the app. Make sure you have checked the `Generate Collection` option while importing the API if you intend to create the `Collection` automatically. 

<img width="703" alt="Screenshot 2020-10-22 at 1 37 04 PM" src="https://user-images.githubusercontent.com/23141842/96843400-e4f13000-146b-11eb-900a-3367ac98e10d.png">

**Comment by kristjanparve** [comment]
I have it enabled.
But I found a workaround that works for me.
If I set myself offline and copy the contents of the json and use the "raw text" import then it does  create the collection.

**Comment by abhinaba-ghosh** [comment]
@kristjanparve  the `Collection` does appear after a few seconds. Check out the video below

![ezgif com-gif-maker](https://user-images.githubusercontent.com/23141842/96845912-dc4e2900-146e-11eb-8071-bb85d21cc213.gif)

**Comment by kristjanparve** [comment]
Thank you for looking into this. 
I did everything just like in your vid. But unfortunately collections do not appear for me after a few seconds. I've restarted Postman and even my computer to see if they were somehow hidden. 
I tried with swagger,  openapi links and no such luck.

**Comment by abhinaba-ghosh** [comment]
We will have a close inspection of this. If you have different schemas [files/inks] where you encounter similar behavior, keep sharing them. it will help us debug better. Thanks.
