### ISSUE TITLE
changes could not be saved  You don't seem to have the required permissions to perform these actions

### ISSUE THREAD

**Issue by paolobiavati** [a85/POSTMan-Chrome-Extension#9197]
every time I call a request in the bottom right corner appear a message that say:

_1 changes could not be saved 
You don't seem to have the required permissions to perform these actions_

to reproduce, just make a request... 

Versione 7.35.0-canary03 (7.35.0-canary03)
mac os High Sierra 10.13.6 
![Schermata 2020-10-22 alle 11 02 41](https://user-images.githubusercontent.com/2340162/96857162-95ecd000-1456-11eb-9b76-f17090a6bca4.png)

**Comment by coditva** [comment]
@paolobiavati Thanks for writing in. I could reproduce this.
We're working on a fix for this. In the meantime, as a workaround, can you enable the "Save responses" setting?

![image](https://user-images.githubusercontent.com/8445768/96859694-6dc59700-147f-11eb-88d7-6eebb2358abd.png)

**Comment by BrianMinJT** [comment]
@coditva I'm also experiencing the same issue and toggling on the Save Responses does stop the "You don't seem to have the required permissions to perform these actions" from showing up on the bottom right corner upon making a call request. 

However, I can't make call requests continuously as it returns the same result from the previous call made. So I have to call a new request on a new tab but the limitation is still the same each time.

**Comment by coditva** [comment]
@paolobiavati @BrianMinJT This has been fixed. Let me know if you still experience this issue 🎉
