### ISSUE TITLE
Edit Request Modal and Request Description Panel are not fully in sync

### ISSUE THREAD

**Issue by not-a-bobbit-fish** [a85/POSTMan-Chrome-Extension#9198]
**Describe the bug**
When changing a request's description through the Request Modal, the description change is not propagated to the Request Description panel. However, the reverse is not true; editing the description through the Request Description panel _does_ update the Request Modal.

**To Reproduce**
1. In Collections, inside a collection, click on a request to select it
2. Click the ">" caret next to the request's name (above the GET/POST selector bar) to expand it and reveal the Request Description panel
3. Set the description through this panel.
4. Right click on the request in the sidebar, and go to Edit to open the Request Modal
5. Note that the text is the same as it was in the Request Description panel
6. Change the text in the modal to something else
7. Click "Update" button to dismiss the modal
8. Note that the Request Description panel does not update.

**Expected behavior**
Changing the text within the Request Modal should propagate to the Request Description page.

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.30.1
 - OS: macOS Catalina

**Additional context**
N/A

**Comment by not-a-bobbit-fish** [comment]
This may be a duplicate of #8833

**Comment by DannyDainton** [comment]
Thanks @not-a-bobbit-fish, I was going to mention the same issue.

We have a bug raised internally for that other issue, can you confirm that's the same behavior?

If it is, we can close this as a duplicate and continue to teak this over on that other thread.
