### ISSUE TITLE
The API "Response Body" cannot present in pretty format.

### ISSUE THREAD

**Issue by ZiegerJheng** [a85/POSTMan-Chrome-Extension#9200]
**Describe the bug**
The API "Response Body" cannot present in pretty format. Every API every requests and every responses are all ran into this problem.

**To Reproduce**
1. Click "Send" button to request the API.
2. Switch to "Pretty" in bottom window in API response body.
2. The API response in the bottom window cannot present in pretty format even you select "Pretty".

**Expected behavior**
The response of the API is JSON format, it should be present in Pretty format, not in on e line.

**Screenshots**
![image](https://user-images.githubusercontent.com/693061/97251106-3ae61f00-1842-11eb-9d19-612dcdea1367.png)
![image](https://user-images.githubusercontent.com/693061/97251276-81d41480-1842-11eb-9e23-e6e469579964.png)

**App information (please complete the following information):**
 - Chrome App
 - Postman Agent v0.2.2
 - OS: macOS Catalina 10.15.6

**Comment by dogkeeper886** [comment]
I meet same problem.

**Comment by vvs11** [comment]
@ZiegerJheng @dogkeeper886 could you guys try this now? We have made some fixes to the web version, it should be working now.

**Comment by dogkeeper886** [comment]
Thank you sir, this problem does not happen now

**Comment by ZiegerJheng** [comment]
@vvs11 Yes, It fixed now. Thanks for your good jobs!

**Comment by vvs11** [comment]
Thanks a lot for your response. Closing this for now :)
