### ISSUE TITLE
Response body did not reload until user switch and switch back tab from pretty to others

### ISSUE THREAD

**Issue by dogkeeper886** [a85/POSTMan-Chrome-Extension#9201]
**Describe the bug**
The content view of response body does not reload after click send button. The content view keep previous data without reload

**To Reproduce**
1. Send API 1
2. Send API 2
3. Check content view
4. See API 1 response
5. Try to switch tab at to RAW
6. Display API 2 content

**Expected behavior**
Content view should display API 2 response

**Screenshots**

**App information (please complete the following information):**
Doesn't relate to browser

**Additional context**

**Comment by DannyDainton** [comment]
Hey @dogkeeper886

Can you also provide screenshots or a short recording of the behaviour to show us what you're currently seeing.

**Comment by dogkeeper886** [comment]
This problem does not happen now
