### ISSUE TITLE
[Darkmode] The text color is so dark

### ISSUE THREAD

**Issue by tonghoang196** [a85/POSTMan-Chrome-Extension#9202]
**Describe the bug**
I have trouble when using Visualize with darkmode. The text color is
so dark,  it's so hard to read.

**To Reproduce**
1. Turn on darkmode
2. Write some scripts to show data on visualize
3. See text color

**Expected behavior**
Highlight text on darkmode

**Screenshots**

![image](https://user-images.githubusercontent.com/51238177/97303975-b4efc580-188d-11eb-9fd6-f09c622fd8a4.png)

**App information (please complete the following information):**
 - Postman for Windows
 - Version 7.34.0
 - OS: Windows 10.

**Comment by DannyDainton** [comment]
Hey @tonghoang196 

Are you able to share the visualizer script that you're using, please? 

As a workaround, you could change the background or the text colour using CSS in the script.

**Comment by tonghoang196** [comment]
Hi @DannyDainton, this is my script

``` ruby
pm.test("test", function () {
    pm.response.to.have.status(200);
});

var beautiful = `
    <table>
        <tr>
            <th>name</th>
            <th>account</th>
            <th>balance</th>           
            <th>status</th>
        </tr>

        {{#each data.items}}
            <tr>
                <td>{{name}}</td>
                <td>{{mt4_account_id}}</td>
                <td>{{latest_analysis.balance}}</td>
                <td>{{status}}</td>                                
            </tr>
        {{/each}}
    </table>
`;
var res = pm.response.json();
pm.visualizer.set(beautiful, res);
```

![image](https://user-images.githubusercontent.com/51238177/97769643-55c8d400-1b5f-11eb-9390-2de0a801c19d.png)

**Comment by giridharvc7** [comment]
We've pushed an update that should fix this. 
Irrespective of the theme chosen, Visualizer will render the canvas in the default white background.
