### ISSUE TITLE
Github API schema sync broken 

### ISSUE THREAD

**Issue by marcusmathioudakismoo** [a85/POSTMan-Chrome-Extension#9204]
**Describe the bug**
Changes to my schema in Github are not synced to my postman API, despite having set up the Github integration correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Github Repo containing an api schema (e.g. a GraphQL schema in a file `schema.gql`). In this repo create a branch called `schema-changes`.
2. Follow the steps [here](https://learning.postman.com/docs/integrations/available-integrations/github/#syncing-your-api-schemas-on-github) to setup a new API in postman and configure it to synchronise its schema with the api schema stored in the GitHub repository you just created. As part of this, make sure you configure postman to use your `schema-changes` branch to sync changes between the two schemas.
3. Now go to the Github repository you created, make some changes to `schema.gql`, and push them to the `schema-changes` branch. If you now go back to your postman api, you should see your changes appear in the schema there. The integration is working as expected so far.
4. Now make some changes to `schema.gql`, but this time push them to the `master` branch in your Github repo. As these changes are now missing from your `schema-changes` branch, add them there by resetting that branch to point to the head of `master`:
   * `git fetch origin`
   * `git checkout schema-changes`
   * `git reset --hard master`
   * `git push -f`
5. If you now check your schema file in postman, the changes you just pushed aren't synced.
6. *More generally: Given a `schema-changes`  branch for which the Postman integration is configured, if you reset the  `schema-changes` branch to any other commit and force-push `schema-changes`  to the remote repository, the synced `schema.gql`  file version is not reflected in Postman, and the schema changelog in the Postman UI is not showing the correct history  of  `schema.gql`*

**Expected behaviour**
I expect to see the schema changes I made in my repo appear in my synced schema in postman

App information:
 - App Type: Native App (but the issue is present in the web app too)
 - Postman Version: Version 7.34.0
 - OS: macOS Sierra 10.12.6

**Comment by arlemi** [comment]
Hey! We've updated the Git integration and now have native Git support (Bitbucket and GitHub for now, more to come) in Postman v9. Please[ check this blog post](https://blog.postman.com/announcing-new-postman-api-platform/) for more info, and update your app to try it out! 

Let us know if this fixes your issue. 🙏
