### ISSUE TITLE
CHROME_NOT_INSTALLED error when trying to install Interceptor Bridge on Postman native app

### ISSUE THREAD

**Issue by kplatis** [a85/POSTMan-Chrome-Extension#9205]
**Describe the bug**
When I try to install `Interceptor Bridge` capturing in Postman native app, I am getting the following error:

```
COULDN'T INSTALL
Postman doesn't have the required permissions to install Node.js and other dependencies. Read our troubleshooting doc for more information.
ERROR CODE: CHROME_NOT_INSTALLED
```

even though Chrome is installed and open in my machine

**To Reproduce**
1. Open Postman App
2. Click on `capture requests and cookies with Postman` button (satellite icon on top right corner of app)
3. Click on `Cookies` tab
4. Click on `Install Interceptor Bridge`

**Expected behavior**
Install Interceptor Bridge and be able to use cookies

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.34.0
 - OS: macOS Catalina 10.15.7

**Comment by ibakshay** [comment]
I am also facing the same issue on my macOS `Big Sur 11.0.1`

**Comment by shashankawasthi88** [comment]
@kplatis @ibakshay can you confirm that `NativeMessagingHosts` directory exists at the right location corresponding to your OS (this exact location can be found in https://learning.postman.com/docs/sending-requests/capturing-request-data/interceptor/#troubleshooting-tips - trouble shooting steps).

**Comment by kplatis** [comment]
@shashankawasthi88 Thank you for your answer. You are right, the `NativeMessagingHosts` directory did not exist in the location you mention. The issue was fixed when I created the `NativeMessagingHosts` directory.

**Comment by shashankawasthi88** [comment]
@kplatis thanks for confirming. I am closing the ticket as the installation can be done with the fox provided.

**Comment by shaileshgade** [comment]
Couldn't install Node.js and other dependencies

Postman doesn't have the required permission to install Node.js and other dependencies. Read our troubleshooting doc for more information.

Error code: REGISTRY_ACCESS_NEEDED

**Comment by shaileshgade** [comment]
Facing this error any one know solution

**Comment by agrwl-harsh** [comment]
@shaileshgade Can you also confirm if you have the `NativeMessagingHosts` directory at the right location corresponding to your OS (this exact location can be found in https://learning.postman.com/docs/sending-requests/capturing-request-data/interceptor/#troubleshooting-tips - trouble shooting steps)
