### ISSUE TITLE
Unable to use more than 1 graphQL variable

### ISSUE THREAD

**Issue by MegaCoderX** [a85/POSTMan-Chrome-Extension#9207]
**Describe the bug**
I am trying to call a mutation for GraphQL that has 2 variables. The issue is whenever I use more than 1 variable I receive a 400 response with the message below:
"SyntaxError: Unexpected token X in JSON at position 294<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/var/app/current/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /var/app/current/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/var/app/current/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/var/app/current/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/var/app/current/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:194:15)<br> &nbsp; &nbsp;at IncomingMessage.EventEmitter.emit (domain.js:441:20)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1125:12)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)"

**To Reproduce**
1. Try to make a call to GraphQl using more than 1 variable. Here is the format of my mutation and GRAPHQL VARIABLES window in Postman.

```
mutation ($patronId: ID! $randomPassword: String!) {
  patron(criteria: { 
    id: $patronId
    libraryCard: $randomPassword 
  }) {
    id
    hooplaUserId
    email
    libraryCard
  }
}
```

```
{
    "patronId": {{registeredPatronId}},
    "randomPassword": {{$randomPassword}}
}
```

**Expected behavior**
I expected a 200 response with returned data, but received a 400

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type Native App on Windows running version 7.35.0
![Capture](https://user-images.githubusercontent.com/73600652/97454894-a0531200-190d-11eb-813a-6db3cb6abdf8.PNG)

 - Postman Version 7.35.0
 - OS: Windows 10

**Comment by codenirvana** [comment]
@MegaCoderX As you can see from your server's error log, it's failing because of `JSON.parse` which means an invalid JSON body is sent.

And that's because `{{$randomPassword}}` variable (string) is not quoted properly. Currently, variables are sent as:
```json
{
    "patronId": 123,
    "randomPassword": password
}
```

I hope this will fix your issue,
```
{
    "patronId": {{registeredPatronId}},
    "randomPassword": "{{$randomPassword}}"
}
```

**Comment by MegaCoderX** [comment]
Thanks for the clarification and timely response! I didn't realize that the dynamic variables needed quoted, but not the environment variables, I think that is what caused me the confusion.
