### ISSUE TITLE
Indentation count setting change not honored until Postman is restarted

### ISSUE THREAD

**Issue by AustonZ** [a85/POSTMan-Chrome-Extension#9209]
**Describe the bug**
If a response body has already been received **prior** to changing the "Indentation count" setting for pretty JSON, then the old setting will continue to be used until Postman is restarted. The actual indentation indicator line updates immediately, however.

**To Reproduce**
1. Start Postman
2. Go to Preferences and set Indentation Count to 4, Indentation Type to Space (I believe this is default, so this step can be skipped)
3. Send a request that results in a JSON body
2. View the response body as Pretty (if not already selected)
3. Open Preferences and change Indentation Count to 2
4. Observe response is still displayed with 4 spaces, but the indentation indicator lines have updated to 2 spaces
5. Try running the request again and observe the result is the same
6. Restart Postman
7. Send the request again and observe that indentation is now correct

**Expected behavior**
When indentation count is changed, the indentation should actually update immediately. Or at least upon the next update of the Pretty view (e.g. sending a new request, or toggling out and back into Pretty view). The indentation line indicators should not be out of sync with the number of spaces used.

**Screenshots**
![postman_indentation_bug](https://user-images.githubusercontent.com/13610250/97488717-d0a1ad00-191b-11eb-99a4-71291d6faa7b.gif)

**App information**
 - App Type: Native App
 - Postman Version: 7.34.0
 - OS: macOS Catalina 10.15.7

**Comment by pankajk07** [comment]
@AustonZ Thanks for reporting this issue. We were able to reproduce this and are looking into it.
