### ISSUE TITLE
Wrong cURL code generation for empty string value in header

### ISSUE THREAD

**Issue by edonmustafa** [a85/POSTMan-Chrome-Extension#9212]
**Describe the bug**

When a request is made with empty string value in header wrong curl code is generated. It doesn't add ; at the end.

**To Reproduce**
1. Set request url to localhost/users
2. Set header field name to tenant and leave it empty
3. Click code
4. you will get:  curl --location --request GET 'localhost/users' --header 'tenant: '
5. which should be: curl --location --request GET 'localhost/users' --header 'tenant;'

**Expected behavior**

curl --location --request GET 'localhost/users' --header 'tenant;'

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.34.0]
 - OS: [macOS Catalina 10.15.5]

**Additional context**

**Comment by DannyDainton** [comment]
Hey @edonmustafa 

Could you expand more on the use case here? 

Is this causing you an issue when using that code snippet outside of Postman?

**Comment by edonmustafa** [comment]
Hi @DannyDainton 

I wanted to show the behaviour of API with empty string in the field "tenant" in header of the request.
We usually share the curl code with the team, so they could replicate the issue.
But got different results, the generated curl code is not what Postman is doing actually.

The generated curl code generates request with field as missing (not included in request).
The Postman app generates a request that includes the field and sets empty value.

So finally you can't use generated code as it is different what Postman is doing actually.

**Comment by DannyDainton** [comment]
Hey @edonmustafa  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
