### ISSUE TITLE
Not able to launch postman - returns version mismatch

### ISSUE THREAD

**Issue by mamataT** [a85/POSTMan-Chrome-Extension#9213]
I was running Postman app version: 7.34.. Accidently, got upgraded to 7.35 - I was having issues with that version and was not happy. So decided to install back 7.34. But when I tried to install using changelog, I get the erro "Version mismatch". But now I can't even open existing 7.35 postman version. And I cannot find postman app for 7.35 version. So I am blocked and stuck. For my API testing, I use postman more than 8 hours a day. Please help either provide me 7.35 version back or how can I get rid of this error and still install 7.34 version back

![image](https://user-images.githubusercontent.com/46796344/97641784-b1854700-1a11-11eb-9b5d-df59c574875b.png)

**Comment by MDzyga** [comment]
the same situation

**Comment by z25clave** [comment]
I had the same problem.
to fix i put in trash all postman files (finder > search postman and delete all postman files linked to the application) and reinstalled the version 7.34 then I blocked automatic upgrade.

**Comment by vvs11** [comment]
You can follow the steps mentioned here: https://support.postman.com/hc/en-us/articles/360025359014

**Comment by DannyDainton** [comment]
A new version of the app was recently released that should solve this error for you. I'm going to close this out for now but we can look to open it again if folks are still facing this problem.
