### ISSUE TITLE
Allow to set custom response_type and nonce when acquiring OAuth 2.0 implicit access token

### ISSUE THREAD

**Issue by ambachtelijk** [a85/POSTMan-Chrome-Extension#9214]
**Is your feature request related to a problem? Please describe.**
When I try to use the built in feature to get an implicit OAuth access token, the `response_type` request param is set automatically to `token`. It is not possible to include additional parameters, such as `nonce`. This prevents me from acquiring an Azure AD access token, because AAD requires `response_type` to be set to `id_token` (see: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-the-sign-in-request). If the response type is set to `token` instead of `id_token`, Azure will return a token with the audience set to Microsoft Graph, instead of the Azure AD application.

Additionally, for using the OpenID Connect flow, a `nonce` parameter must be included in the request.  Setting the `response_type` parameter in the Auth URL results in a duplication of this parameter, and as such in an invalid request.

**Describe the solution you'd like**
* Allow the `response_type` parameter to be set manually in the 'Get new access token' dialog of the OAuth 2.0 Implicit Grant authorization type.
* Allow additional parameters, including `nonce` to be set in the 'Get new access token' dialog of the OAuth 2.0 Implicit Grant authorization type.

**Describe alternatives you've considered**
Manually creating the auth URL as a request in Postman, which looks like `https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/authorize?client_id={{client_id}}&response_type=id_token&redirect_url=https://localhost&scope=openid profile email&nonce=nonce&response_mode=fragment`. Then I intercept the generated URL in the Postman console, and run the request in the browser.

**Additional context**
![image](https://user-images.githubusercontent.com/3234834/97666976-15922480-1a7f-11eb-98d1-a40f51908061.png)

This request from the screenshot will resolve to `https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/authorize?response_type=token&state=&client_id={{client_id}}d&scope=openid%20profile&redirect_uri=https%3A%2F%2Flocalhost`, while the actual request should become `https://login.microsoftonline.com/{{tenant_id}}/oauth2/v2.0/authorize?client_id={{client_id}}&response_type=id_token&redirect_url=https://localhost&scope=openid profile email&nonce=nonce&response_mode=fragment`

The `token` request returns a JWT with `aud` set to `00000003-0000-0000-c000-000000000000`, while the `aud` parameter should be set to `{{client_id}}`. This will be the case if the `response_type` is `id_token`. Also note how the response bodies of the token are completely different between `token` and `id_token`.

`response_type=token` (incorrect):
![image](https://user-images.githubusercontent.com/3234834/97667422-1e372a80-1a80-11eb-9ded-56653ccfe84b.png)

`response_type=id_token` (correct):
![image](https://user-images.githubusercontent.com/3234834/97667709-c77e2080-1a80-11eb-995e-640dfd23c25f.png)

**Comment by smythemm** [comment]
Facing a similar issue here, where our Azure AD is not set up to generate access tokens, so I can't use the response_type = token and have to use id_token.

I'm managing to get further using ReadyAPI from Smartbear, but ideally would prefer postman.

**Comment by abhijeetborole** [comment]
Hey everyone! Thank you for the patience! We’ve added the ability to customise your OAuth2,0 requests with Postman v10.13.
This is available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests. You can also add query params to the auth request.

You can attach the `response_type` and `nonce` parameters here.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)

If you have any Audience and Resource parameters, you can move them to the new editors with the Move Audience and Resource button.

![MoveAudAndResFlow](https://user-images.githubusercontent.com/9638586/232850201-59d30590-d7c7-41c1-94c7-9a1c77f1757b.gif)


Do let us know if you have any issues.

P.S. - For refresh parameters, these will be stored with the token and any changes will only be considered when you generate a new token

Postman app v10.13 is being rolled out will be available for everyone in couple of days

**Comment by gunsto** [comment]
Hi @abhijeetborole , I dont see these advanced settings in Postman v. 10.14.2 (Mac). How can I enable this?
