### ISSUE TITLE
Getting CORS preflight origin header error during "Authorize using browser" (pstmn.io)

### ISSUE THREAD

**Issue by josephtannenbaum** [a85/POSTMan-Chrome-Extension#9217]
**Describe the bug**

We are implementing our own OAuth 2.0 server (using node-oauth2-server) and trying to use Postman for internal testing, including generating access tokens. I'm not sure if this is our misconfiguration because pstmn.io seemed to work normally yesterday. My bad if this is some foolishness on my part!

**To Reproduce**
1. Go to _Get New Access Token_ screen
2. Enter info in first screenshot

**Expected behavior**
Browser window redirects back to Postman window

**Screenshots**

<img width="664" alt="Screen Shot 2020-10-30 at 12 25 54 PM" src="https://user-images.githubusercontent.com/28641/97731165-31132480-1aab-11eb-8261-8925cb6d4a8a.png">

<img width="1417" alt="Screen Shot 2020-10-30 at 12 18 34 PM" src="https://user-images.githubusercontent.com/28641/97730513-55223600-1aaa-11eb-8e53-7babf2e3bf46.png">

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.34.0
 - OS: macOS Catalina 10.15.6

**Additional context**

Thank you!!

**Comment by oivindth** [comment]
I'm having the same issue athenticating to Azure AD. In parent authorization settings it doesen't work because of CORS error. But it works doing a post call with http interceptor and origin in header.

**Comment by augustocb23** [comment]
Same here. Trying to configure login using Azure AD

**Comment by giridharvc7** [comment]
@augustocb23 @oivindth @josephtannenbaum can you confirm if you are still facing this issue with Postman v10+ versions?
