### ISSUE TITLE
OAuth not using the right token in 7.35

### ISSUE THREAD

**Issue by Thomas-Ritsert** [a85/POSTMan-Chrome-Extension#9218]
**Describe the bug**
Postman updated to 7.35 today.  Wiped out my OAuth settings which I assume is the new UI being non-modal.  Annoying but manageable..  I can get a new token however subsequent requests will not use the bearer token.  Even if I manually enter the bearer token into the current token interface it will not be used.

**To Reproduce**
1. Go to Request > Authorization > Configure New Token
2. Fill out form (I used password credantials)
3. Click Get New Access Tokenbutton
4. View Authentication complete dialog
5. View Manage Access Tokens dialog
6. See new access token displayed and click Use Token button (Note **new token** value)
7. Observe Access Token in the Current Token value has not changed
8. Execute request and observe failure
9. Manually Update Current Token value with **new token** value
10. Execute request and observe failure
11. Observe the bearer token used in the last request in the console
12. Note that this bearer token is not **new token** value

**Expected behavior**
OAuth bearer token should update appropriately and/or work when manually updated

**Screenshots**
I think repro steps should be enough

**App information (please complete the following information):**
 - App Type: Windows Native App
 - Postman Version: 7.35
 - OS: Windows 10 Pro Version 10.0.19041 Build 19041

**Additional context**

**Comment by xngage-insite** [comment]
And now this appears to be working...  Computer was restarted over the weekend.  Odd.  Blame the user!

**Comment by Thomas-Ritsert** [comment]
And now this appears to be working.  Computer was restarted over the weekend.  Blame the user!  False report!  Be well humans

**Comment by joris-van-oers** [comment]
I have (almost) the same issue, so probably some edge case... 

- Wiped out my OAuth settings
- "Get New Acces Token" does store the token (it is listed, can be displayed using "Manage Tokens"), but not updating the access token
  - Same result when manually selecting from the "Available Tokens" dropdown

Type: OAuth 2.0 
Client credentials without a scope
Postman version: v7.35.0

**Comment by vvs11** [comment]
@joris-van-oers We are fixing this issue. Please go through #9056 for more details. We will post the updates there
