### ISSUE TITLE
Suggested change in official Postman Echo test collection

### ISSUE THREAD

**Issue by cyberjetx** [a85/POSTMan-Chrome-Extension#9219]
Sorry I didn’t find the _postman echo_ git repo to do a proper pull request. I did search for it in your repos. 

### The response from Hawk authentication has changed since the last test update.

In the  GET https://postman-echo.com/auth/hawk

Need to change this test: 
```
pm.test("response body has json saying passed 'status'", function () {
    pm.response.to.have.jsonBody('status', 'pass');
});
```

To the following: 
```
pm.test("response body has json saying passed 'status'", function () {
    pm.response.to.have.jsonBody('message', 'Hawk Authentication Successful');
});
```

![image](https://user-images.githubusercontent.com/11842304/97781689-801c9080-1b63-11eb-90bc-a229cdafc0e2.png)

![image](https://user-images.githubusercontent.com/11842304/97781702-96c2e780-1b63-11eb-9dc7-2fa8bc63efce.png)

Again, I apologize that if there is a postman echo repo that I could not find it.

**Comment by DannyDainton** [comment]
The request in the collection has been updated.

https://www.postman.com/postman/workspace/f21c2968-b83d-485e-9360-21fc4de72be3/request/631643-843acf02-a33c-c4bb-d742-c07b9212e4b0
