### ISSUE TITLE
Changelog not updating.

### ISSUE THREAD

**Issue by ClementRoyer** [a85/POSTMan-Chrome-Extension#9220]
**Describe the bug**
When updating/creating/deleting anything in the collection it don't update the changelog.

**To Reproduce**
1. Create Collection
2. Add a request
3. Check the changelog.
4. See if it's accurate.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.34.0
 - OS: Windows

**Additional context**
This problem is quite important cause since there is no changelog update I can't bind the new update to a API version and update the documentation.

**Comment by DannyDainton** [comment]
Hey @ClementRoyer

Thanks for reporting this issue 🏆

I've passed it on to the relevant team and we will update this thread with more information once we have more details to share.

**Comment by gauravsoni1** [comment]
@ClementRoyer Same issue on MacOS. For me, this happens when using the API builder.

**Comment by tylermilner** [comment]
I'm also seeing this as well. Last week, the app wasn't working (or was at least updating very slowly), but I was still able to use the web interface to tag my changes. Now the web interface doesn't seem to be showing my changes either. This is really throwing a wrench into my API development process so if it doesn't get fixed soon, I will have no choice but to look at other platforms for API development.

**Comment by DannyDainton** [comment]
This has been raised and the team are aware of it - We will update the thread with more information, 
once we have it.

**Comment by DLTKMonBlaza** [comment]
I also encountered this same issue right about the same time that the issue was raised by @ClementRoyer. 
I second the additional context that was provided above.
I hope this issue will be resolved soon.
Thank you.

**Comment by DLTKMonBlaza** [comment]
As of this writing, I'm seeing that the changelog issue has been fixed. I hope that it isn't temporary and that it really is fixed for good. I can now proceed with my needed doc updates.

@ClementRoyer and @tylermilner, you may want to verify if the same is true from your end. Hope that it is so you can also proceed with what you need.

Thank you all.

**Comment by jcgarciaram** [comment]
I can also confirm **Changelog** is now updating. Will wait on Postman to officially close this issue before returning to version tags for published docs.

**Comment by ClementRoyer** [comment]
It's working again for me too, should I close the issue ?

**Comment by tylermilner** [comment]
The changelog started working for me yesterday as well. I'm hoping it's fixed for good! 🤞

**Comment by DannyDainton** [comment]
Hey folks,

Thanks for confirming the fix and your issues being resolved, apologies for not updating the thread before this went out. Busy times at the moment :D 

Closing this out now but drop a message with the details if you see the issue recurring.
