### ISSUE TITLE
Postman is not showing the response in a JSON Pretty format. 

### ISSUE THREAD

**Issue by feluis67** [a85/POSTMan-Chrome-Extension#9223]
**Describe the bug**
Postman is not showing the response in a JSON Pretty format. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34856162/97904124-fa057300-1d37-11eb-98cf-2cab5716efd1.png)

**App information (please complete the following information):**
 - Postman Version v7.35.0
 - OS: Windows 10

**Additional context**

**Comment by DannyDainton** [comment]
Hey @feluis67

That image shows a HTML response, I wouldn't expect it to be a pretty print JSON one.

You my need to expend on the details of this issue to help us to understand what you feel is happening here.

**Comment by feluis67** [comment]
Hi,

Thanks for the quick response.

Look at the picture below. it's not a Pretty JASON response.
I


[image: image.png]

That's my problem.
I do not know why .

Regards,
Fernando

**Comment by DannyDainton** [comment]
We're unable to see that image you've posted.

Was it the one from the original issue? 

![image](https://user-images.githubusercontent.com/34856162/97904124-fa057300-1d37-11eb-98cf-2cab5716efd1.png)

That endpoint is returning a HTML response so it's not JSON. 

Do you have an example of what the response should look like?

**Comment by feluis67** [comment]
I am expecting a JSON response in order to understand.
That is why the option JSON is selected.

Regards,
Fernando

**Comment by feluis67** [comment]
Hi ,

I am attaching more details in the annex file,
Also an example I made in Python with a JSON response.

That's what I am expecting to read when the option JSON is selected.

Regards,
fernando

**Comment by DannyDainton** [comment]
Still not able to see the images you have attached, if you're replying by email to can cause problems uploading these to the issue.

The server is responding with an HTML response, changing the setting on the Postman UI isn't going to change this to show a JSON response. 

This doesn't feel like a functional issue with Postman as the request looks like it returning without any errors. I'm going to close this and ask that you raise this as a new question over on our community forum, please.

https://community.postman.com/
