### ISSUE TITLE
I have the data read from the .csv file even though the expected and actual results displays as same but still the Assert is failing. Please advice For Eg. Actual "3-ABC Test" Expected: "3-ABC Test". Still the Assert fails.

### ISSUE THREAD

**Issue by rahulprinjay** [a85/POSTMan-Chrome-Extension#9224]
**Describe the bug**
I have the data read from the .csv file even though the expected and actual results displays as same but still the Assert is failing. Please advice
For Eg. Actual "3-ABC Test" Expected: "3-ABC Test". Still the Assert fails.
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by DannyDainton** [comment]
Hey @rahulprinjay

This feels more like a question for out Postman community.

https://community.postman.com 

I'm going to close this issue as it doesn't sound like a functional issue with the app itself and more like a understanding of how the app works.

Could you create a new thread in the community and include more context and some images to show what's happening for you.
