### ISSUE TITLE
cannot copy the console of the previous and next page

### ISSUE THREAD

**Issue by Melcome7** [a85/POSTMan-Chrome-Extension#9225]
for details, I made an attachment of the bug, that I can only copy the console content of the current view, cannot copy the content of previous and next page, fix the bug?
![image](https://user-images.githubusercontent.com/11468955/97936935-1fd25c80-1db8-11eb-9d35-9ddcb6bc5a7b.png)

**Comment by DannyDainton** [comment]
Closing as this is a duplicate of #8785

**Comment by DannyDainton** [comment]
Closing as this is a duplicate of #8757
