### ISSUE TITLE
Copying a request and moving it to another folder, it will keep the "old" folders inherited headers.

### ISSUE THREAD

**Issue by andybutlermf** [a85/POSTMan-Chrome-Extension#9227]
**Describe the bug**
A copied request will not inherit a parents folders "headers etc" when moved. 

**To Reproduce**
1. Create two folders and add different Auth via "Api keys" to them. 
2. Create a request in "1" and copy it and move it to "2". 
3. Look at request "2"'s auto generated headers. They will not match the parent folder. 
4. Create a request in folder "2" and it will have the correct auto headers.

**Expected behavior**
The copied request that has been moved should pull the headers from the new parent folder.

**Screenshots**
![bug_1](https://user-images.githubusercontent.com/37069449/97971311-bdc72680-1dba-11eb-88a1-0f6f6d99f10f.PNG)
![bug_when_req_created_in_parent_folder](https://user-images.githubusercontent.com/37069449/97971313-be5fbd00-1dba-11eb-860a-a4dc0aa9eaaf.PNG)

**App information (please complete the following information):**
Postman for Windows
Version 7.34.0
win32 10.0.18363 / x64

**Comment by giridharvc7** [comment]
This is fixed now, please let us know if you still find this issue.
