### ISSUE TITLE
Variables not being recognized in request body

### ISSUE THREAD

**Issue by tylerw909** [a85/POSTMan-Chrome-Extension#9231]
**To Reproduce**
1. Go to set a collection variable in the tests tab of one call
2. Call that variable in the next call's request body
3. The first call shall successfully set the variable as expected, but then you get the error when running the second call 

**Expected behavior**
I should be able to run the first call and set the TicketTotalId collection variable and pass it to the second call and run it with no issue. I am trying to eliminate the need for transferring changing data between calls.

**App information (please complete the following information):**
 - Postman Version v7.35.0

**Screenshots**
![Screenshot 2020-11-03 121826](https://user-images.githubusercontent.com/31831841/98018605-be69b800-1dce-11eb-901a-20ea05c0c1b3.jpg)
![Screenshot 2020-11-03 121738](https://user-images.githubusercontent.com/31831841/98018608-bf024e80-1dce-11eb-872a-7101d2d507cd.jpg)
 
I have the collection variable TicketTotalId (I have also tried storing it as an environment variable) begin saved properly as expected in my first call (GetCartTotalPrices under the _tests_ tab).  I set the key-value pair in the JSON request body in the next call (ConfirmOrder which works if I manually type the value), when the option comes to set that to the collection variable TicketTotalId, it doesn't show the value.  I then get the error in the image above: 

There was an error in evaluating the Pre-request Script:  
JSONError: Unexpected token 'T' at 43:22 "TicketTotalId": {{TicketTotalId}}, ^

I have tried deleting the variable and call separately and recreating them to see if it was because the variable was outdated. That was suggested in another thread but did not help me.

**Comment by DannyDainton** [comment]
Hey @tylerw909 

What do you have in the `Pre-Request Script`? 

That's where the error is coming from but I can't see what you have in there to know why it's causing an issue. :D 

It looks like you have duplicated the tab and have 2 `ConfirmOrder` requests on display - Can you close one and save so you only have 1 view of that request. 

> Duplicating a tab does not mean creating a second request to the same endpoint—when you duplicate a tab any edits you make will affect the original request.

Just want to rule out the possibility that you have added something in there by mistake and this is impacting your requests.

**Comment by tylerw909** [comment]
Hey @DannyDainton thank you for the quick reply!

I am creating an automatic testing suite to run in a separate collection. That duplicate request tab was from a separate collection so I don't think it affected anything, but I closed it regardless just to completely rule it out.

Here is the pre-request script:
![Screenshot 2020-11-03 124008](https://user-images.githubusercontent.com/31831841/98021023-c70fbd80-1dd1-11eb-803c-321ed3fc160c.jpg)

**Comment by DannyDainton** [comment]
Could you post the raw code here, please? 

It's a little tricky writing that all out from an image :D 

What is `request.data` in this context? Is that the request body you have in the other image?

As I can see that the Postman environment syntax is slightly old, did you copy this code from somewhere else?

**Comment by tylerw909** [comment]
Yes, I believe this is slightly older syntax from calls that are likely 2 years old at my company. They haven't been an issue ever for me. Here it is in text (sorry about the image):

```javascript
function guid() {
    function _p8( s ) {
        var p = (Math.random().toString( 16 ) + "000000000").substr( 2,8 );
        return s ? "-" + p.substr( 0,4 ) + "-" + p.substr( 4,4 ) : p;
    }
    return _p8() + _p8( true ) + _p8( true ) + _p8();
}
var nonce = guid();
postman.setEnvironmentVariable( "nonce", nonce );
var message = "nonce=" + nonce + "|" + JSON.stringify( JSON.parse( request.data ) );
postman.setEnvironmentVariable( "verify", CryptoJS.HmacSHA1( message, "encryption blah blah" ) );
```

**Comment by DannyDainton** [comment]
Could you try with this replacement line, please?

```
var message = "nonce=" + nonce + "|" + JSON.stringify( request.data  );
```

**Comment by tylerw909** [comment]
I get a 403 Forbidden response and the error `"Invalid Verification Value"`

**Comment by DannyDainton** [comment]
Ok but no script error so that's a bonus :D 

Can you clear out all the variable and start fresh again?

Also might be worth using `console.log()` to see that the right values are being used in the request.

**Comment by tylerw909** [comment]
Yessir! I reset the collection variable and ran the first call. It stored it correctly (70805).  I put 

```javascript
console.log(pm.collectionVariables.get("TicketTotalId"));
```

into the confirmOrder call pre-request script but it didn't print it anywhere. I ended it up with the same initial error:

`There was an error in evaluating the Pre-request Script:  JSONError: Unexpected token 'T' at 43:22 "TicketTotalId": {{TicketTotalId}}, ^`

Again that line with the issue is just the request body where I reference the collection variable (which I auto-populated with postman's suggestion):

`  "TicketTotalId": {{TicketTotalId}},`

**Comment by DannyDainton** [comment]
Hey @tylerw909

Did you manage to get it working in the end?

**Comment by tylerw909** [comment]
Yes. I had to add this code snippet to the pre-request script:

```javascript
for (var key in environment) {
    data = data.split('{{' + key + '}}').join(environment[key]);
}
for (var key in globals) {
    data = data.split('{{' + key + '}}').join(globals[key]);
}
```

That ended up working only for environment variables, not collection variables.
