### ISSUE TITLE
Requests in collections getting reordered 7.35.0

### ISSUE THREAD

**Issue by Seregy** [a85/POSTMan-Chrome-Extension#9232]
**Describe the bug**
Desktop application reorders requests in the collection view and for collection runner seemingly at random.

**To Reproduce**
1. Ensure that more than one workspace exists, create one if necessary 
2. Import a collection
3. Execute synchronization via in-app button
4. Switch to another workspace and back
5. Execute synchronization via in-app button
6. Try to run collection via collection runner, at this point runner should already display requests in wrong run order
7. Relaunch the application, requests in collection should be displayed in wrong order, just as in collection runner 

**Expected behavior**
Requests in collection should not change their order without user interaction

**Screenshots**
Newly imported collection:
![Postman-reorder-1](https://user-images.githubusercontent.com/9089329/98023080-158f7d00-1e0f-11eb-8f59-0d26c6306d4b.png)

Collection runner with reordered requests:
![Postman-reorder-2](https://user-images.githubusercontent.com/9089329/98023077-145e5000-1e0f-11eb-8994-c39cd8b91718.png)

Collection after restarting application:
![Postman-reorder-3](https://user-images.githubusercontent.com/9089329/98023071-132d2300-1e0f-11eb-8016-b91493921f25.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.35.0
 - OS: macOS Catalina 10.15.3

**Additional context**
The order of requests is correct when viewing collection via browser, so it seems that only desktop application is affected. 
I was able to consistently reproduce the issue by switching between two workspaces and manually triggering synchronization process.

**Comment by JP-from-Postman** [comment]
Another user report of this:

> When I duplicate or rename a call within the Collection, the order of all the calls sometimes changes within the Collection"

**Comment by hkarjala** [comment]
Any updates regarding this one? I'm running into this issue (requests order changing when adding/removing requests to/from folder) constantly and it becoming a major headache for the day-to-day.
Since first noticing this issue, I've uninstalled Postman desktop app (v7.35.0) and it's local files and am running the 7.34.0 version now - which unfortunately did nothing to improve the situation.

**Comment by AndyScott1** [comment]
Morning, I have stumbled on this issue this morning as we are also seeing this problem and it is causing mass amounts of rework as we reorder collection that have been broken, can this be escalated asap please

**Comment by vvs11** [comment]
Thanks for reporting. We are looking into this issue. Will get back with an update soon

**Comment by ivnakov** [comment]
I encountered this issue multiple times last week and it's overly annoying. However it appeared in the past as well - https://github.com/postmanlabs/postman-app-support/issues/3231

Until there is a fix for it, you can simply log out -> log in again and the requests will be ordered correctly. I know this doesn't fix the problem (as it would appear once again you add/move folders) but it's a better workaround than re-ordering the requests manually every time it appears.

**Comment by eraymond-bt** [comment]
Two of my teammates are seeing this issue, as well

**Comment by jgalvacky-bt** [comment]
Can confirm that this has happened to me as well recently. I resolved (temporarily) by deleting the collection from Postman and re-importing it.

**Comment by aerazo-bt** [comment]
As @jgalvacky-bt & @eraymond-bt have mentioned, almost all my collections had to be removed then reimported back into Postman.  Was very surprised to see how things were so out of order.

Can't tell if it is a synchronization issue or not.  It appears it is not limited to just version 7.35.0 as other users in the company are on version 7.11 and also experiencing the same issue.

**Update:** Based on other users feedback, logging out of Postman then logging back in fixes the order.

**Comment by kosmonaffft** [comment]
I'm seeing this when i add new request to folder, or copy-paste requests from one folder to another.

**Comment by GimmeDaKitty** [comment]
Having this same issue when I close the application, then reopen it. If I delete the collection and re-import it it shows in the right order. 
Halp.
Postman version: v7.34.0 on Windows 10

**Comment by mohitranka** [comment]
We have released a [new version](https://www.postman.com/downloads/) of the app - while we don't anticipate any impact, please let us know if you continue to observe the requests getting reordered.

**Comment by DannyDainton** [comment]
@Seregy / @bdelsaz / @ivnakov / Anyone else

Could you please let us know if this is still an issue and in the latest version?

**Comment by GimmeDaKitty** [comment]
@DannyDainton I did a quick test and it seems like the issue is fixed now. 
Thanks so much for the quick update! :)

**Comment by Seregy** [comment]
@DannyDainton I'm no longer experiencing this issue as well

**Comment by DannyDainton** [comment]
Closing this issue now but we can reopen/raised a new issue if we see any additional reports of the problem.
