### ISSUE TITLE
Postman change requests order from folder inside collections to alphabetic.

### ISSUE THREAD

**Issue by KyryloKuchuk** [a85/POSTMan-Chrome-Extension#9234]
**Describe the bug**
Unfortunately I can't localize the steps to reproduce.
Sometimes when I copy folder with requests inside collection and rename it, after next run up postman , I face changed requests order in alphabetic order.

**App information (please complete the following information):**
Postman for Windows
Version 7.35.0
win32 10.0.19042 / x64

**Comment by DannyDainton** [comment]
Hey @KyryloKuchuk,

Is this the behaviour that you're seeing #9232 or something else?

**Comment by KyryloKuchuk** [comment]
Hi,it's look like the same issue, but in my case the order change to
alphabetic and I don't change workspace.
Thanks! Sorry for dublicate issue.

чт, 5 нояб. 2020 г., 8:30 Danny Dainton <notifications@github.com>:

**Comment by DannyDainton** [comment]
Thanks for taking a look - If you haven't done so already, could you add what you're seeing to the thread, please.

I'm going to close this one out and track the conversation over on #9232
