### ISSUE TITLE
Access token textbox is empty after getting new access token

### ISSUE THREAD

**Issue by AndersMalmgren** [a85/POSTMan-Chrome-Extension#9236]
Postman 7.35

After getting a new valid token the Acces token textbox is empty. And the Token header in request just Says

"Bearer" and no token after prefix. 

Sync token button is disabled

**Comment by AndersMalmgren** [comment]
I downgraded to 7.23 (a version  I happened to have in download folder)

**Comment by janjan19** [comment]
I have same issue . Postman this is a blocker !

**Comment by auraxangelic** [comment]
I have the same issue. I downgraded to 7.34.0, and plan to run the installation before every Postman launch since we can't even prevent upgrades. Very annoying.

Tested with OAuth2.0 on Windows:

- Access token doesn't get set.
- Can't resync when I unsync.

**Comment by vvs11** [comment]
We are working on fixing this. Will share an update soon. You can check out #9056 for updates

**Comment by AndersMalmgren** [comment]
Bug is back. This is a huge showstopper guys

**Comment by AndersMalmgren** [comment]
btw we dont use sync feature.

**Comment by jftai1** [comment]
+1 this is a blocker for us as well. Please fix asap.

**Comment by enricoferrari** [comment]
+1 Suddenly restarting and getting this new version is a huge blocker.  I can manually cut and paste tokens into my Headers, but our tokens are way to short lived for that to be usable.

**Comment by vvs11** [comment]
We are working on fixing this issue. Please check out #9056 for updates

**Comment by bmclaughlin-soteria** [comment]
If anyone runs into this problem where this works in web browser but not in desktop app. Try running desktop app in Administrator mode.
