### ISSUE TITLE
 '25 request sharing limit' header shows with no shared content

### ISSUE THREAD

**Issue by dzmitry-kakaruk-webjet** [a85/POSTMan-Chrome-Extension#9239]
I have '25 request sharing limit' header constantly showing even though I have only one personal workspace and not sharing it with anyone. 

![image](https://user-images.githubusercontent.com/51070391/98186216-606dd980-1f62-11eb-8980-9141b93d5f76.png)

Only one personal workspace 
![image](https://user-images.githubusercontent.com/51070391/98186236-6e235f00-1f62-11eb-8c17-516ca8974223.png)
![image](https://user-images.githubusercontent.com/51070391/98186248-74b1d680-1f62-11eb-9dc7-a1bf8513ed86.png)

And stats show no shared content. 

![image](https://user-images.githubusercontent.com/51070391/98186286-86937980-1f62-11eb-8d08-5ac465a7d65a.png)

It seems like a bug.

**Comment by prashantagarwal** [comment]
@dzmitry-kakaruk-webjet Thanks for reporting this. It would really help us in triaging this issue faster if you could drop an email at help@postman.com. 

Also, since when or after what action did you started seeing this banner? Were you part of a team before?

**Comment by dzmitry-kakaruk-webjet** [comment]
Do you want me to send a request to email or continue conversation here? 
Yes, it seems the banner started to appear after I was removed from a team.

**Comment by DannyDainton** [comment]
Hey @dzmitry-kakaruk-webjet,

Is this still causing you an issue?

**Comment by dzmitry-kakaruk-webjet** [comment]
> Hey @dzmitry-kakaruk-webjet,
> 
> Is this still causing you an issue?

I'm afraid yes :(

**Comment by sujayvenaik** [comment]
@dzmitry-kakaruk-webjet We had a potential bug at our end which we patched up. Can you try once if you still face this?

If yes, can you provide with the app version as well as the screenshot of the app screen. That would be helpful.

**Comment by dzmitry-kakaruk-webjet** [comment]
> @dzmitry-kakaruk-webjet We had a potential bug at our end which we patched up. Can you try once if you still face this?
> 
> If yes, can you provide with the app version as well as the screenshot of the app screen. That would be helpful.
Looks good now. Thanks heaps :)

**Comment by dzmitry-kakaruk-webjet** [comment]
Great work :)
