### ISSUE TITLE
OpenAPI importer to not select every query parameter by default

### ISSUE THREAD

**Issue by n2ygk** [a85/POSTMan-Chrome-Extension#9241]
**Is your feature request related to a problem? Please describe.**
When I import an openapi schema that has optional query parameters, they are all checked (selected) by default.

**Describe the solution you'd like**
I'd like them to be not selected by default.

**Describe alternatives you've considered**
 Alternatively add a global check box to uncheck/check all of them.

**Additional context**
See attached schema doc and screenshot.

<img width="1221" alt="Screen Shot 2020-11-05 at 8 58 44 AM" src="https://user-images.githubusercontent.com/4356471/98250259-378b1b80-1f45-11eb-9bd3-43c51d2c9b5d.png">

[openapi.yaml.txt](https://github.com/postmanlabs/postman-app-support/files/5494832/openapi.yaml.txt)

**Comment by miguelblcfigueira** [comment]
I support the considered alternative: "Add a global check box to uncheck/check all of them."

**Comment by n2ygk** [comment]
It looks like Query Params now has a selectable Key that checks/unchecks all of the params.
![image](https://github.com/user-attachments/assets/45ff485e-b584-4680-acf8-c1e7fcd2bf28)
