### ISSUE TITLE
Yesterday's Oath2 Bearer token sent, even though no token is available

### ISSUE THREAD

**Issue by WarrenDavidson** [a85/POSTMan-Chrome-Extension#9244]
**Describe the bug**
I have created a request with Oath 2.0 Authorization that worked as expected yesterday. Today, only tokens from yesterday are being sent, even after all tokens have been deleted, a new token has been received from the browser, and the new token has been verified to be current. 

**To Reproduce**
1. Create a new Collection 
2. Create a new request
3. Configure Oauth 2.0 and Authorize using browser
4. Click `Get New Access Token`
5. `Use Token`
6. Click `code` (Under the Save button), and verify the curl call contains the Bearer token you just received. 
7. Wait 1 day
8. Go to `manage tokens` and delete all tokens
9. Repeat step 6
10. Observe that, even though all tokens are gone, the curl call has yesterday's token.

**Expected behavior**
When tokens are deleted, and a new token is created and used, the new token should be the one sent with requests.

**App information (please complete the following information):**
 - App Type: Firefox Developer 83.0b8 (64-bit)
 - Postman Version: v.7.35.0
 - OS: Windows 10 Enterprise 1903

**Comment by Raj-postman** [comment]
Hi @WarrenDavidson 

We are aware of this issue and our team is currently working towards fixing the same. You can also check https://github.com/postmanlabs/postman-app-support/issues/9056 for updates.

To mitigate any impact for now, please use [Postman v7.34.0.](https://dl.pstmn.io/download/latest/windows). Thanks!

**Comment by WarrenDavidson** [comment]
Hi @Raj-postman ,

Thank you for this information. I uninstalled v.7.35.0 and tried to install the v7.34.0 but was blocked by

![image](https://user-images.githubusercontent.com/74026134/98389992-acc02480-2009-11eb-86a2-40b6834e556c.png)

Is there a Registry entry I could delete?

Thank you,
Warren

**Comment by WarrenDavidson** [comment]
I followed the steps in this article to cleanup Postman files, and now I'm running v7.34.0. Thank you for your help!

https://support.postman.com/hc/en-us/articles/360025359014

**Comment by vvs11** [comment]
Tracked on #9056
