### ISSUE TITLE
Postman app v7.35.0 on windows 10 is not sending OAuth 2.0 access token Request Headers.

### ISSUE THREAD

**Issue by dworthen** [a85/POSTMan-Chrome-Extension#9246]
**Describe the bug**
Postman app v7.35.0 on windows 10 is not sending OAuth 2.0 access token Request Headers. 

**To Reproduce**
1. Select OAuth 2.0 and add the authorization data to Request Headers.
2. Get New Access Token
3. Use Token
3. Send Request
4. Observe in the Postman Console that Authorization header is not set.

Here is my setup
![image](https://user-images.githubusercontent.com/624870/98386682-58b34100-2005-11eb-937b-e6bc8f4e25cc.png)

I am able to retrieve valid access tokens using the Get Access Token button. Selecting Use Token also indicates success:
![image](https://user-images.githubusercontent.com/624870/98387009-c0698c00-2005-11eb-82a0-56724baa3861.png)

but the Access Token field never gets set:
![image](https://user-images.githubusercontent.com/624870/98387257-09214500-2006-11eb-90b1-577a1d56f2ea.png)

When I send the request, Postman Console shows that the Authorization header is not set:
![image](https://user-images.githubusercontent.com/624870/98387412-340b9900-2006-11eb-9fdf-29c79616c942.png)

I tried reselecting the token using the Available Tokens dropdown. I tried manually pasting the token into the Access Token field and I tried using the sync token button. No matter what I do, the authorization header is never set. I noticed that the Headers area lists a calculated token field but again this just never gets sent.
![image](https://user-images.githubusercontent.com/624870/98387879-d9bf0800-2006-11eb-8524-3facd22a624d.png)

I tested using Authorization Code flow and Client Credential flow. I am able to get tokens but Postman is not setting the Authorization header.

I updated to v7.35.0 this morning. This was working before updating to v7.35.0.

My current workaround is to change the Authorization from OAuth 2.0 to Bearer Token and manually paste in the access token after retrieving a token using the OAuth 2.0 Get Token capabilities.

**Expected behavior**
OAuth 2.0 Authorization configured to add authorization data to Request Headers should send retrieved access tokens as Bearer tokens in an Authorization header. 

**App information (please complete the following information):**
 - App Type windows desktop app.
 - Postman Version 7.35.0
 - OS: Windows 10 Build 19042.572

**Comment by vvs11** [comment]
We are working on fixing this issue. Please check out #9056 for more details. You'll have to downgrade to v7.34

**Comment by SavvySkylark** [comment]
@vvs11 how do you downgrade? I'm not finding anything useful in my search engine results.

**Comment by skylar-smith** [comment]
For anyone else looking at how to downgrade the instructions are in the thread on #9056
