### ISSUE TITLE
ReferenceError: Intl is not defined

### ISSUE THREAD

**Issue by yusuf-tayman** [a85/POSTMan-Chrome-Extension#9247]
**Describe the bug**
We are currently unable to use the Intl library, which we used to use previously. We're getting a reference error.

**To Reproduce**
1. Go to 'Pre-request Script' or 'Tests'
2. Make a definition as follows 
```
const today = new Intl.DateTimeFormat('en-US', { dateStyle: 'short'}).format(new Date());
console.log(today);
```
4. See error "There was an error in evaluating the Pre-request Script:  ReferenceError: Intl is not defined"

**Expected behavior**
The DateTime operations should be done properly by using Intl.

**Screenshots**
![image](https://user-images.githubusercontent.com/70777390/98400662-7b7d3e00-2075-11eb-8f72-c9896525ba75.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.35.0]
 - OS: [macOS Catalina 10.15.7]

**Additional context**
You can find those who have the same problem below.
https://community.postman.com/t/has-intl-been-taken-off-the-latest-version-of-postman/17332

**Comment by DannyDainton** [comment]
I also left a response on the community thread but leaving this here too for extra visibility.

> The JS Intl API was never intended to be exposed in the sandbox and wasn’t even included in the official Postman documentation, as something to use within Postman. This has been removed in the latest version of the app.

> You can achieve the same output from either using vanilla JS or using the moment module, that is included and documented, to create the date object that you can use with your requests.

https://momentjs.com/docs/

```
const moment = require('moment');
pm.globals.set("today", moment().format("MM/DD/YYYY"));
```

**Comment by yusuf-tayman** [comment]
Thank you very much 🙏 @DannyDainton
