### ISSUE TITLE
Flickering and jumping cursor in the Headers tab

### ISSUE THREAD

**Issue by levani** [a85/POSTMan-Chrome-Extension#9251]
**Describe the bug**
In Headers tab if I try to make the VALUE column wider and drag the DESCRIPTION column to the right and then click inside any input in DESCRIPTION tab this happens:

https://imgur.com/a/RBIJYcU

**To Reproduce**
1. Go to Headers tab
2. Drag DESCRIPTION column to the right
3. Click inside input below DESCRIPTION column
4. Inputs will start blinking

**Expected behavior**
Inputs should not blink

**Screenshots**

https://imgur.com/a/RBIJYcU

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.35.0
 - OS: macOS Catalina 10.15.7

**Additional context**

**Comment by DannyDainton** [comment]
Hey @levani 

I was able to reproduce this issue locally - Thank you for raising this 🏆

**Comment by Pricilla09** [comment]
I too faced this issue today. And found that @levani have already logged. I was trying to edit the header and it started flickering. Please find the video.

[Postman_Header_Flickering.zip](https://github.com/postmanlabs/postman-app-support/files/5511227/Postman_Header_Flickering.zip)

Using Postman for Windows - Version 7.35.0

**Comment by simax** [comment]
Yep, same here

**Comment by DannyDainton** [comment]
Hey @Pricilla09 / @simax,

It's going to be happening for everyone - There's no real value in reconfirming the same thing. 😄

**Comment by vvs11** [comment]
This is fixed in v7.36. 
Closing this for now. Please feel free to reopen if you're still seeing this issue
