### ISSUE TITLE
Postman Version: 7.35.0 : Oauth2 jwt expiry timestamp exp: is set to past

### ISSUE THREAD

**Issue by MrMedTech** [a85/POSTMan-Chrome-Extension#9254]
Since the last update I have the following problem:

I can get an accesstoken ( jwt ). When I inspect is, the expires timestamp is set a few days in the past.
Before the update, everything worked fine but now I always get unauthorized.

**Comment by DannyDainton** [comment]
Hey @MrMedTech 

We're currently tracking an issue with OAuth in the latest release here: https://github.com/postmanlabs/postman-app-support/issues/9056

Closing this as it feels like it relates to that - If this is not the case, can you open a new issue and follow the template to provide the details to reproduce this issue, please.
