### ISSUE TITLE
Collection and Environment Variables Are Not Recognized in Body

### ISSUE THREAD

**Issue by tylerw909** [a85/POSTMan-Chrome-Extension#9257]
**Describe the bug**
I set variables to be environment or collections variables in the request body through the UI pop up that says "Set as Variable". After running the call I always get the error:

There was an error in evaluating the Pre-request Script:  JSONError: Unexpected token 'e' at 3:24 "EmailAddress" : {{email}}, ^

**To Reproduce**
1. Create a call and set something in the body to a collection/environment variable
2. Give that variable a value in the environment
3. Execute the call

**Expected behavior**
I expect the call to work with no issues and populate and recognize the environment variables that exist.

**Screenshots**
![Screenshot 2020-11-10 114420](https://user-images.githubusercontent.com/31831841/98704013-262d7f00-234a-11eb-9946-3006fea92e4d.jpg)
![Screenshot 2020-11-10 114318](https://user-images.githubusercontent.com/31831841/98704020-26c61580-234a-11eb-8feb-89f83574c8b2.jpg)
![Screenshot 2020-11-10 114840](https://user-images.githubusercontent.com/31831841/98704482-b53a9700-234a-11eb-97c3-61c9751c25fc.jpg)

I included my pre-request script because that is where it says the issue is. I have the issue wether or not I include the first loop in the pre-request. That did solve an issue to define the environment variables for another call since they don't seem to get set before the call and it always throws an error.  But it is not working for this call. It does population the variable to be "email@gmail.com" in the body which is what I expect, but the error persists.

**App information (please complete the following information):**
 - App Type Windows 64 bit Native App
 - Postman Version v7.34.0 (Persists on 7.35.0 as well)
 - OS: Windows 10

**Additional context**

**Comment by DannyDainton** [comment]
Hey @tylerw909 

Does the same thing happen if you wrap that variable in quotes? For example `"{{email}}"`

**Comment by tylerw909** [comment]
I got another error that I believe stems from my pre-request script. Although the script runs fine if I just hard code the request body. There are no syntactical errors with it.

**Comment by DannyDainton** [comment]
What was the additional error - can you provide examples please.

**Comment by tylerw909** [comment]
It is just `"Invalid Verification Value"` which is one of our responses. I figured it out I believe. I had to set the `request.data` to the `var data` after setting the environment variable. But, this is a workaround. It isn't how Postman is intended to work, correct? Why would Postman not be able to simply recognize the interpolation and plug in the environment variable? That has consistently been an issue for me trying to automate data between calls through environment variables. 

Also, as a side note, using the environment variables wouldn't be limited because I am on the free version, correct?

**Comment by DannyDainton** [comment]
That's not limited in any pricing tier.

The script you're using looks dated and is using the older syntax and it's doing things in a way that you could probably make more streamlined with more modern JS and some of the built-in module. 

I don't believe this is a functional issue with Postman, as you have something that that works, might not been the best solution though. 

I'm going to close this issue and ask that you open up a thread over on our Community site and walk through different possible solutions with our community members. 

https://community.postman.com 

This isn't the best medium for doing that. Feel free to ping me on the thread.
