### ISSUE TITLE
Cutting multiple rows: "Something Went Wrong"

### ISSUE THREAD

**Issue by char-s** [a85/POSTMan-Chrome-Extension#9259]
**Describe the bug**
Cutting(Ctrl-X) in the Query Params table causes a "Something Went Wrong" error if you move cells while holding the CTRL. Appears to happen every time when there are multiple rows and this is the first time noticing it.

**To Reproduce**
1. Create a Request
2. Add 3 rows of Query Params
3. Select a cell in the bottom row and hold CTRL
4. While still holding CTRL, select a cell in the top row and press X

**Expected behavior**
In the Headers section it normally just removes the row

**Screenshots**
![postman_cut_crash](https://user-images.githubusercontent.com/68617838/98756824-4fc1c700-2399-11eb-9bc6-3a7d4a52b42c.gif)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.34.0
 - OS: win32 10.0.19041 / x64

And

 - App Type: Native App
 - Postman Version 7.35.0
 - OS: OS X 19.6.0 / x64

**Additional context**
From Developer DevTools Shared Shell
_Error: [mobx] An invariant failed, however the error is obfuscated because this is an production build._

**Comment by DannyDainton** [comment]
Hey @char-s

Thank you for reporting this 🏆 - we will take a look and update thread ones we have more details to share.

**Comment by timbochamp** [comment]
Hi @char-s , this should be resolved now on our latest builds and on Postman for Web! Please feel free to reopen this issue if the problem is persisting for you
