### ISSUE TITLE
Cannot select token in OAuth 2.0 dropdown

### ISSUE THREAD

**Issue by eking-isp** [a85/POSTMan-Chrome-Extension#9262]
**Describe the bug**
You cannot select a token you have created in Postman for the OAuth 2.0 flow. This means you can't provide the token with your requests.

**To Reproduce**
1. Go to any request
2. Go to authentication
3. Select OAuth 2.0, and fill in your typical values
4. Issue a new token
5. Click on the token in the dropdown

**Expected behavior**
The token would be selected and its value filled. Instead, nothing happens.
**Screenshots**
Clicking the button under my cursor does nothing.
![image](https://user-images.githubusercontent.com/54548183/98870032-7fb7ab80-2427-11eb-9e45-d1b8ea4d26c6.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version 7.35.0
 - OS: Win 10

**Additional context**
Had a coworker reproduce this on their machine.

**Comment by DannyDainton** [comment]
Hey @eking-isp

Thanks for reporting this issue. 

We're currently tracking an issue with OAuth in the latest release here: #9056

Closing this issue out and centralising all the information in one place. All updates will be added to the linked issue.
