### ISSUE TITLE
Importing Multi-File Swagger OAS 2.0

### ISSUE THREAD

**Issue by stfgl** [a85/POSTMan-Chrome-Extension#9265]
Hello,
[Purchase.zip](https://github.com/postmanlabs/postman-app-support/files/5529853/Purchase.zip)

I have an api specification (attached zip) which importation isn’t working as expected. It was generated, and works properly with the OpenAPI VSCode plugin. The swagger is splitted in three files: purchase.fishmarket-purchases.swagger.v1.1.0.json, purchase.v1.1.0.json and structural.v.1.0.0.json.

purchase.fishmarket-purchases.swagger.v1.1.0.json contains the paths and some specific definitions of the specification.

purchase.v1.1.0.json and structural.v.1.0.0.json contains definitions that are shared with other specifications.

Each of these .json files is located in different folders.

The references in purchase.fishmarket-purchases.swagger.v1.1.0.json to the defenitions in purchase.v1.1.0.json and structural.v.1.0.0.json are made via “$ref” property in this way: " “$ref”: “…/…/…/goldenRecords/purchase.v1.1.0.json#/definitions/FishMarketPurchaseType” ".

When I preview the specification with some tool like the OpenAPI VSCode plugin, it shows no problem. But when I import the folder to Postman to create a collection using the Import Folder feature it is not able to resolve the references and it shows a “reference …/…/…/goldenRecords/purchase.v1.1.0.json#/definitions/FishMarketPurchaseType not found in the OpenAPI spec” message.

I’ve been navigating the forums, stackoverflow and the github postman-app-support repositroy and I’ve seen some issues talking about this problem, but these issues are old and I’ve understood that in newer versions of Postman this reference solving should work fine when using the Import Folder feature.

Thank you for your help.

**Comment by jotsarup** [comment]
@stfgl Multi file schema file imports are still not supported in Postman but we are planning on supporting them. 

Meanwhile what you can do. 

`npm install swagger2openapi -g`, they’ll get access to the `boast` CLI that will flatten the schema for you including all the refs from files in different directories.

`boast purchase.fishmarket-purchases.swagger.v1.1.0.json -o purchase.fishmarket-purchases.swagger.v1.1.0_flattened.json`

Upload this flattened file in Postman API Builder and you should be good to go from there.

**Comment by shashankawasthi88** [comment]
@stfgl Multifile schemas are now supported with Postman V10. Additionally we have launched a new API builder experience to work cohesively with your repository. We can walk you through the end to end workflow over a short call. Feel free to schedule a call with us using [this](https://calendly.com/shashank-awasthi/v10-feedback?month=2022-09) link.
