### ISSUE TITLE
postman reshuffles requests from time to time

### ISSUE THREAD

**Issue by bjornzki** [a85/POSTMan-Chrome-Extension#9269]
I see that Postman shuffles the request from time to time.
This bug has been filed a number of times but it's a reintroduced problem.

Reproduction:
Can't reproduce it. It just happens every few days. Once a week.

Expected behavior:
Requests should stay in the order they are in.

App information:
Version 7.35.0
win32 10.0.17134 / x64
Chrome 86.0.4240.198 (Official Build) (64-bit)

**Comment by DannyDainton** [comment]
Hey @bjornzki 

I see that you have already commented on the main issue tracking this - https://github.com/postmanlabs/postman-app-support/issues/9232

All update will be placed against that issues thread, Closing this issue to help centralise the information.
