### ISSUE TITLE
API definitions were duplicated within each collection in new PostMan Sync

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#927]
Somehow, all my API definitions were duplicated using the new PostMan Sync.  Not every API was duplicated but now I have many duplicates within each collection.  Collections themselves were not duplicated.

For example, in one collection:
![duped_apis](https://cloud.githubusercontent.com/assets/2750330/6269354/7fa31752-b807-11e4-80b9-b0b8f4d8e6fe.png)

There are about 10 more APIs in this collection.  Every API is duplicated.  I think when it occurs, every API in the collection is duplicated.  These collections are not shared.

But there are some collections where no items were duplicated.

**Comment by abhijitkane** [comment]
Did you notice this problem today? Both the "Delete Share" requests seem were created on Feb 2, about 2 seconds apart. 

Also, if you imported the collection from a file, can you mail it to help@getpostman.com?

**Comment by stevemcmillen** [comment]
I don't know when it appeared,  I just noticed about 5 days ago.  Around Feb 2 that time I was dumping and imported all settings.  So likely this occurred then.  I think we should close this and I will keep and eye out to see if it recurs.
