### ISSUE TITLE
Cookie Keys Missing

### ISSUE THREAD

**Issue by HthSolid** [a85/POSTMan-Chrome-Extension#9270]
I didn't find a bug similar.

**Describe the bug**
When receiving a Cookie it has keys (Expiry, Secure, HttpOnly, etc...) when making the request Postman only sends name&value, all other keys of the Cookie are not sent.
For extending expiry dates on server side, this behaviour creates issues.

**To Reproduce**
1. Get Cookies from API
2. Create another call to any API
3. See what is being sent on Server and Postman side, both dont have the keys that are mentioned inside Cookie Manager

**Expected behavior**
All keys from the Cookie should be transferred to the Server or API

**App information:**
 - Server: Python
 - Postman Version 7.35.0
 - OS: Windows 10 64bit

![image](https://user-images.githubusercontent.com/4158547/99079981-f20fc380-25c0-11eb-8c8a-1d0e0cc9865a.png)
![image](https://user-images.githubusercontent.com/4158547/99080126-21becb80-25c1-11eb-9635-bc6591101e6a.png)
![image](https://user-images.githubusercontent.com/4158547/99080191-3d29d680-25c1-11eb-83a6-cfe48697ec4f.png)
![image](https://user-images.githubusercontent.com/4158547/99080213-4450e480-25c1-11eb-8e5d-df67a52b9be0.png)

**Comment by codenirvana** [comment]
@HthSolid That's how cookies work 😅 

In the response, you can set multiple `Set-Cookie` headers with all the details like Expiry, Secure, etc. to instruct the client how to store those cookies.
But while making a request, the client can only set a single `Cookie` header with all the cookies (`key=value`) separated with `;`.

Refer https://en.wikipedia.org/wiki/HTTP_cookie#Setting_a_cookie for more details.

**Comment by HthSolid** [comment]
I have this problem only with Postman. 
In all browsers like Chrome, Firefox, Opera, I can access these values from server-side (using Django), only in Postman I cannot access the values at server side. So this is still an issue and I had to go further with real browsers in order to be able to develop.

**Comment by codenirvana** [comment]
Can you share a scaled-down collection that we can use to reproduce this issue?
