### ISSUE TITLE
Try to open Release Notes: Something Went Wrong tab opens

### ISSUE THREAD

**Issue by aureole82** [a85/POSTMan-Chrome-Extension#9272]
![Postman has a really bad UI](https://user-images.githubusercontent.com/4819891/99081285-ddccc600-25c2-11eb-8892-75ce20321755.gif)
Occured in Postman v7.35.0

**Comment by mccannt** [comment]
@aureole82 Thanks for reporting this. 
We have actually rolled back on this release of the application due to other issues you may have encountered. 
You can try downgrading to v7.34 and everything should work as you would expect.
