### ISSUE TITLE
浏览器使用拦截器抓取入参是中文的接口，postman中录制到的接口入参显示乱码

### ISSUE THREAD

**Issue by jinghe0929** [a85/POSTMan-Chrome-Extension#9274]
环境：
chrome上的拦截器版本：v1.1.1
windows的postman版本：v7.35.0 
步骤：
1.浏览器发出请求，请求接口的入参包含有中文
2.查看postman中抓取的接口入参

实际：显示乱码

![image](https://user-images.githubusercontent.com/30433641/99143777-235cc200-269b-11eb-8b46-237167f3d9b0.png)

**Comment by DannyDainton** [comment]
Hey @jinghe0929 

Would you be able to confirm that is is an issue that you're seeing what using the Interceptor and it's returning Chinese characters?

**Comment by jinghe0929** [comment]
![image](https://user-images.githubusercontent.com/30433641/99359916-bf303d00-28ea-11eb-94df-fb63023f5a60.png)

**Comment by hui-huo** [comment]
遇到一样的问题，请问如何解决的

**Comment by yuzd** [comment]
+1

**Comment by jinghe0929** [comment]
> 遇到一样的问题，请问如何解决的

没有解决 可能他们没有看懂我写的问题

**Comment by QingMings** [comment]
@jinghe0929   重新打开吧

**Comment by QingMings** [comment]
> Hey @jinghe0929
> 
> Would you be able to confirm that is is an issue that you're seeing what using the Interceptor and it's returning Chinese characters?

using interceptor capture requests,  the request body contain Chinese characters, display incorrectly

**Comment by jinghe0929** [comment]
> 环境：
> chrome上的拦截器版本：v1.1.1
> windows的postman版本：v7.35.0
> 步骤：
> 1.浏览器发出请求，请求接口的入参包含有中文
> 2.查看postman中抓取的接口入参
> 
> 实际：显示乱码
> 
> ![image](https://user-images.githubusercontent.com/30433641/99143777-235cc200-269b-11eb-8b46-237167f3d9b0.png)

**Comment by PeachesIsland** [comment]
遇到同样的问题，楼主解决了吗

**Comment by jinghe0929** [comment]
> 环境：
> chrome上的拦截器版本：v1.1.1
> windows的postman版本：v7.35.0
> 步骤：
> 1.浏览器发出请求，请求接口的入参包含有中文
> 2.查看postman中抓取的接口入参
> 
> 实际：显示乱码
> 
> ![image](https://user-images.githubusercontent.com/30433641/99143777-235cc200-269b-11eb-8b46-237167f3d9b0.png)

@

**Comment by jinghe0929** [comment]
> 环境：
> chrome上的拦截器版本：v1.1.1
> windows的postman版本：v7.35.0
> 步骤：
> 1.浏览器发出请求，请求接口的入参包含有中文
> 2.查看postman中抓取的接口入参
> 
> 实际：显示乱码
> 
> ![image](https://user-images.githubusercontent.com/30433641/99143777-235cc200-269b-11eb-8b46-237167f3d9b0.png)

@DannyDainton

**Comment by jinghe0929** [comment]
> 遇到同样的问题，楼主解决了吗

没有解决,一不小心点错了

**Comment by nicky-chen** [comment]
一样，解决不了

**Comment by Polunpin** [comment]
我遇到了同样的问题，使用`Postman Interceptor` 谷歌浏览器插件，捕获浏览器post请求，涉及到中文传参(body中)，在postman中会显示乱码。麻烦指导处理下

**Comment by dogeow** [comment]
我也是

**Comment by shblhy** [comment]
+1 同样的问题

**Comment by vamosdalian** [comment]
urlencoded?

**Comment by shblhy** [comment]
不是，参数在post请求的body当中，并不在url上。post请求内的参数，如果有中文，postman录制请求，参数那位置会显示为乱码。完全是不可读的乱码，和urlencode好无关系。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月12日(星期二) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [postmanlabs/postman-app-support] 浏览器使用拦截器抓取入参是中文的接口，postman中录制到的接口入参显示乱码 (#9274)





 
urlencoded?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by agrwl-harsh** [comment]
Hey All, the issue has been fixed. Please try it on the latest postman app. Let us know if you find any issues.

**Comment by VShingala** [comment]
Hey All, This issue has been fixed for some time now. I'll be closing it for now, but please feel free to open this issue in case you have any further problems with it.
