### ISSUE TITLE
Postman Bootcamp - Forking and Merging: Collection Does Not Import and Step Box Pop Up Disappears After Clicking Import Collection

### ISSUE THREAD

**Issue by wildintu** [a85/POSTMan-Chrome-Extension#9280]
**Describe the bug**
Postman Bootcamp - Forking and Merging: Collection Does Not Import and Step Box Pop Up Disappears After Clicking Import Collection

**To Reproduce**
1. Go to 'Forking and Merging' on Postman Bootcamp
2. Click on 'Import Collection' on the pop up step and observe that the next pop up step does not pop up and no collection is imported

**Expected behavior**
Upon clicking 'Import Collection' on the pop up step, it should show a new pop up step with the next instructions for 'Forking and Merging' on Postman Bootcamp

**Screenshots**
https://cargo.teamairship.com/79dASU

**App information (please complete the following information):**
 - Macbook Pro 13 inch 2017 
 - Postman Version 7.35.0 (7.35.0)
 - OS: macOS Big Sur 11.0.1 (20B29)

**Additional context**
This seemed to happen with some of the other lessons but I was able to get it to start working upon restarting the lesson. This did not seem to help with Forking and Merging lesson though.

**Comment by james-postman** [comment]
Hi @wildintu

Sorry for the inconvenience this has caused you. Just to let you know I'm looking into this and will give you an update soon.

James

**Comment by Aronpd1** [comment]
Exact error is happening to me in the following device:
- Lenovo Legion Y740
- Windows 10 v2004 BUILD19041.630
- Postman v7.34.0

**Comment by james-postman** [comment]
Hi @wildintu and @Aronpd1 

I've investigated the issue and it is now with the team to fix the bug. I'll update you as soon as I have an update on its progress.

Thanks for your patience!

James

**Comment by Raj-postman** [comment]
Hi @wildintu and @Aronpd1 - The issue should now be resolved.
Can you please try this flow in the latest version of the application (v.7.36.1) and let us know if that helps?

**Comment by anthonyChaussin-d4e** [comment]
Hi @Raj-postman , I'm in  Postman v7.36.3 and I experiencing the same issue.
Is it a probleme with the account type ?

**Comment by james-postman** [comment]
Hi @wildintu and @anthonyChaussin-d4e,

This appears to be working in the latest version (v8.2.1). Could you update and test it again please?

Thanks!
James

**Comment by anthonyChaussin-d4e** [comment]
Hi @james-postman, it's works perfectly, thanks for the fix !

**Comment by james-postman** [comment]
No problem @anthonyChaussin-d4e 😄
