### ISSUE TITLE
Missing buttons while creating mock server

### ISSUE THREAD

**Issue by haarts** [a85/POSTMan-Chrome-Extension#9282]
**Describe the bug**
When designing an API and subsequently generating a collection based on the definition, when selecting 'API Mocking' the Next and Back buttons are missing.

**To Reproduce**
1. Go to APIs tab
2. Click on New API
3. Fill out the form
4. Go to Overview tab if not already there
5. Click Generate Collection
6. Name the collection and select API Mocking
7. Click Generate collection
8. On the Configure mock server modal the buttons in the bottom are missing, you are now stuck

**Expected behavior**
The buttons should show.

**Screenshots**
![missing-next](https://user-images.githubusercontent.com/10660/99383155-c563f080-28cd-11eb-9d07-4b17f29dc52a.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.34.0
 - OS: Linux Ubuntu 20.10

**Comment by vvs11** [comment]
@haarts We are not able to reproduce it. Could you attach a video with the steps you performed that got you here?

**Comment by haarts** [comment]
How odd. I'll see what I can do tomorrow.

**Comment by vvs11** [comment]
Also, can you see if you're able to add mock server from here: 
![image](https://user-images.githubusercontent.com/4140290/99696152-62807e00-2ab4-11eb-9b5b-e463ae0f4c7d.png)

**Comment by DannyDainton** [comment]
Closing the issue due to inactivity. If you're still facing any issues in the latest version we can look at reopening this again.
