### ISSUE TITLE
Right Click on Response Body Not Working in Macbook Screen (1440x900)

### ISSUE THREAD

**Issue by mssio** [a85/POSTMan-Chrome-Extension#9287]
**Describe the bug**
When I have long response body and I want to right click it to set it to my env variables, it wont work on my mac screen (1440x900). But when I used my external monitor screen (1920x1080), it will work.

**To Reproduce**
Here is the screenshot when I try to right click on small screen resolution (1440x900) -- **it does not work**:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/1535102/99513161-e9eac600-29bc-11eb-8f96-c71de747e407.png">

Here is the screenshot when I try to right click on bigger screen resolution (1920x1080) -- **it works**:
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/1535102/99513274-04bd3a80-29bd-11eb-9839-baf8c6b567ca.png">

**Expected behavior**
I should be able to right click on small screen resolution (1440x900).

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.34.0]
 - OS: [macOS Big Sur 11.0.1]

**Additional context**
This problem also occurred in previous macOS Catalina version, so I don't think this bug is introduced by Big Sur update.

**Comment by DannyDainton** [comment]
Hey @mssio 

I've been unable to replicate this issue on my Mac with that resolution - Would you be able to do a quick recording so we can see what's happening for you.

As a workaround and prevent the need to manually copy and paste that value from the response each time, you could add this to the `Tests` tab to automatically set that value as a variable.

```javascript
pm.environment.set("access_token", pm.response.json().body[0].access_token)
```

**Comment by mssio** [comment]
Hi @DannyDainton ,

Thanks for the reply, okat I will send screen recording later tomorrow. About why it happens is maybe the popup menu that appear when I press right click is wider than 1440px (including child menu) when there is really long text selected.

**Comment by mssio** [comment]
Here is the video capture

Smaller Screen:
https://youtu.be/7lHTxZBSU18

Bigger Screen
https://youtu.be/hvciqc8C9Do

Maybe it will need sometime for Youtube to finish the rendering.

**Comment by DannyDainton** [comment]
I will take a look at those - in the meantime, did the script help to automatically capture the token?

**Comment by mssio** [comment]
Yes it works, thank you very much for the tips! 😀

**Comment by giridharvc7** [comment]
@mssio Can you confirm if you still have this issue with the latest versions of Postman (v10+)? I'm not able to replicate the issue myself. 
i'm closing this issue for now, feel free to reopen if you find this happening again.
