### ISSUE TITLE
Upgrade to 7.34.0 (currently the latest) causes a version mismatch error upon startup

### ISSUE THREAD

**Issue by maulemon** [a85/POSTMan-Chrome-Extension#9288]
**Describe the bug**
I've upgraded to 7.34.0 using Chocolatey I get a version mismatch error :(

This looks very similar to #7553 
Apparently that's the latest available version as of now.
 
**To Reproduce**
 Upgrade to 7.34.0 using Chocolatey

**Expected behavior**
Postman starts up as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/8656471/99527043-13dbc280-2994-11eb-9c48-0da9b4f28b06.png)

**App information (please complete the following information):**
 - App Type Windows Native App
 - Postman Version 7.34.0
 - OS: Windows Version 10.0.19041 Build 19041

**Comment by DannyDainton** [comment]
Hey @maulemon 

Have you tried going through the steps listed here:

https://github.com/postmanlabs/postman-app-support/issues/7553#issuecomment-724333761

Also, unsure of the installation location and directory that Chocolatey places application it to - Are you able to share that information please?

**Comment by maulemon** [comment]
Hi @DannyDainton , the instructions under the comment are for MacOS. 

I'm on Windows:
Following the shortcut from Start Menu pointed me to:
![image](https://user-images.githubusercontent.com/8656471/99529759-412a6f80-2998-11eb-9bb0-a75be1aeb449.png)

**Comment by maulemon** [comment]
I also have a folder under **Roaming**:
![image](https://user-images.githubusercontent.com/8656471/99530796-b2b6ed80-2999-11eb-9794-58797660fd90.png)

**Comment by DannyDainton** [comment]
I see that you have navigated within the Postman folder. To resolve this issue, please follow the steps below:

1) Uninstall the Postman application from Control Panel
2) Navigate to the below two locations:
   - C:\Users\<user>\AppData\Local
   - C:\Users\<user>\AppData\Roaming
3) Rename the Postman folder to "Postman.old"
   - This is just to avoid any loss of local data if it wasn't synced.
4) Once done, navigate to below link and install version v.7.34.0 based on the windows bit version:
   - https://dl.pstmn.io/download/latest/win32
   - https://dl.pstmn.io/download/latest/win64

**Comment by maulemon** [comment]
Hi @DannyDainton ,

I have

1. Uninstalled postman using (Chocolatey)[https://chocolatey.org/]
2. Renamed folders under \local and \Roaming
3. Installed postman using Chcolatey

That has resolved the issue - I believe that I've lost some of the pre-populated values for parameters but I should be able to recreate them.

**Comment by DannyDainton** [comment]
That's great - I'm going to close this issue out as you have a resolution for your issue.
