### ISSUE TITLE
Postman request crashes on charset ibm850 in Content-Type header

### ISSUE THREAD

**Issue by rbi** [a85/POSTMan-Chrome-Extension#9292]
**Describe the bug**
When the server returns "Content-Type: text/plain; charset=ibm850" the request tab just crashes. This seams to happen for any charset unknown to Postman e.g. "Content-Type: text/plain; charset=mycustomcharset" 

**To Reproduce**
1. Send a HTTP GET Request with Postman to https://public.voidnode.de/ibm850test/ibm850test.txt 

**Expected behavior**
Postman shouldn't crash regardless of the what the Server sends in the Content-Type header.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/483599/99639364-cb7ddc80-2a47-11eb-9355-a06e22cb8e2d.png)

**App information (please complete the following information):**
 - Linux App
 - Postman v7.31.0
 - OS: Kubuntu 20.04, also happened on Windows

**Comment by dev-sharma-08** [comment]
Hi @rbi,
Can you update your app to the latest version, and check if this is still an issue for you ?

**Comment by rbi** [comment]
I tested the URL https://public.voidnode.de/ibm850test/ibm850test.txt with Postman v10.14. It doesn't crash anymore.
