### ISSUE TITLE
Disalignment between local Postman collection and online documentation ()

### ISSUE THREAD

**Issue by gauthierpetetin** [a85/POSTMan-Chrome-Extension#9294]
**Describe the bug**
See screenshot.

**To Reproduce**
I created a folder in local Postman collection, then deleted it. But it's still there in online documentation, even after a week.
Other changes performed in local Postman collection reflect successfully on the UI, but this oen doesn't.

**Expected behavior**
Changes performed in local Postman collection shall always reflect successfully on the UI.

**Screenshots**
![Screenshot 2020-11-19 at 15 11 23](https://user-images.githubusercontent.com/7071180/99677157-b15cf200-2a79-11eb-9aa5-b87176aaebf2.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by DannyDainton** [comment]
Hey @gauthierpetetin,

Could you confirm the version of the app and the OS you're using, please?

Was the Documentation published or just local in the Team Workspace? Are the changes only being made in the forked Collection or also pushed to the main collection?

**Comment by gauthierpetetin** [comment]
Hello @DannyDainton ,
I use the following version of Postman: 7.35.0
I'm on Mac OS: 10.14.6
The documentation was published.
Actually it was even published multiple times since I update it almost every day. Always on the main collection (not on a fork).
All other changes I make are properly published on the online documentation, except this one: I'm not able to delete the folder called "7.Multiple networks Copy", c.f. screenshot above.

**Comment by DannyDainton** [comment]
Hey @gauthierpetetin 

Is this still continuing to be an issue on the latest version of the platform? I'm unable to recreate this on my side.

**Comment by gauthierpetetin** [comment]
Hi @DannyDainton , thanks for reaching out, it doesn't seem to be an issue anymore.
