### ISSUE TITLE
Updating email in account setting on Mozilla Firefox doesn't redirect to Identity page

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#9295]
**Describe the bug**
When trying to change your email address in https://go.postman.co/settings/me/account in Mozilla Firefox the account verification doesn't happen. User gets stuck on the this below screen.

![Pasted-image-Thu_Nov_19_2020_103611_GMT-0500__Eastern_Standard_Time_](https://user-images.githubusercontent.com/47351631/99695147-23870400-2a85-11eb-946a-b3a55a1e35c1.png)

**To Reproduce**

1. Head to https://go.postman.co/settings/me/account
2. Modify your email address.
3. Click Save Changes. You should now be brought to the identity page, that opens in a new tab that asks you to confirm your account but on Mozilla Firefox, this doesn't happen. 

While, on Chrome, a new tab oppens so the user can enter the password associated with the account and hit sign in do the new email can be updated.

**Expected behavior**
1. Head to https://go.postman.co/settings/me/account 
2. Modify your email address.
3. Click Save Changes. 
4. An identity page opens in a new tab and prompts the user to confirm the account.

![Screenshot_2020-11-19_at_15_51_28](https://user-images.githubusercontent.com/47351631/99695266-4a453a80-2a85-11eb-8be9-43d2961559e4.png)

5. Enter the password associated with the email and hit sign in.
6. The email is now updated.

**App information (please complete the following information):**
- Windows 10, Firefox 82.0.4

**Additional context**
Workaround for now is to go through Chrome.

**Comment by ArjunSingh-PM** [comment]
@cyrielle-hada Could you please confirm if pop-ups were blocked on the browser?

**Comment by cyrielle-hada** [comment]
@ArjunSingh-PM This issue was reported via a support ticket and I am unable to confirm with the user as the ticket is now closed. However, I was actually able to reproduce when blocking the pop-ups. So perhaps this was the reason here for it to happen!

**Comment by ArjunSingh-PM** [comment]
This issue is not reproducible when pop-ups are not blocked.
