### ISSUE TITLE
Validation against incorrect path

### ISSUE THREAD

**Issue by fernion** [a85/POSTMan-Chrome-Extension#9296]
**Describe the bug**
The validation of an get request is validating against incorrect path

**To Reproduce**
1. Create an openAPI with two endpoints:
 /something
 /anotherthing/{id}/something
2. When the first endpoint is called, and the validation runs we can see it validating against the wrong path

Removing the {id} from the second endpoint fixes the issue.
An example spec is the following: [bugResportSpec.zip](https://github.com/postmanlabs/postman-app-support/files/5568482/bugResportSpec.zip)

**Expected behavior**
The correct path should be picked for validation

**Screenshots**
![BugReport](https://user-images.githubusercontent.com/21362419/99698333-8f1ea080-2a88-11eb-97b5-49fb05574d81.png)

**App information (please complete the following information):**
 - Postman 7.35.0
 - OS: Windows 10 version 1909

**Comment by VShingala** [comment]
@fernion This should be fixed now and I wasn't able to reproduce the issue anymore. Could you confirm if it's fixed for you?

**Comment by fernion** [comment]
Was not able to reproduce it either!

Seems to be solved.
