### ISSUE TITLE
Microsoft Azure - <Azure API>

### ISSUE THREAD

**Issue by KingCuster** [a85/POSTMan-Chrome-Extension#9299]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by DannyDainton** [comment]
Hey @KingCuster,

Thanks for writing in, could you complete the rest of the template, please?

**Comment by DannyDainton** [comment]
Closing this for now, can be reopened once the individual heading details have added.
