### ISSUE TITLE
Comments to Activity Feed (so they post to Slack integration)

### ISSUE THREAD

**Issue by camellia** [a85/POSTMan-Chrome-Extension#9300]
**Describe the solution you'd like**
I'd like to (optionally) include comments in the Activity Feed so that these will post to our Slack integration.

**Comment by shashankawasthi88** [comment]
@camellia thanks for raising this request. We are actively working on a new Integration that shall allow you to get notified on various scenarios such as being tagged in a comment, PR created, etc. We will update on the thread itself as and when we have an update on this.

**Comment by shashankawasthi88** [comment]
@camellia we have launched a new integration with Slack that will enable you to receive notifications on Slack when someone tags you in the comment. Please follow the [blogpost](https://blog.postman.com/postman-notifications-slack/) for more details.
