### ISSUE TITLE
Postman web version - Variables

### ISSUE THREAD

**Issue by meghamahant** [a85/POSTMan-Chrome-Extension#9304]
**Describe the bug**
The variables that are saved during work session on web postman go away as soon as browser tab is closed (or browser is closed)

**To Reproduce**
1. Open the web postman
2. Save one or more variables (key and value)
3. Close the browser tab where you are running postman
4. Open the postman again - go.postman.co
5. Open the Variables section and observe that values are no longer there

**Expected behavior**
Variables should be saved permanently unless deleted by user explicitly.

**App information (please complete the following information):**
Postman Web version - go.postman.co

**Comment by DannyDainton** [comment]
Hey @meghamahant

Thanks for creating this - would you be able to attach a few images or a quick recording of the issue, please?

Just to clarify, we're the the variables added and _saved_ (there's a save button on the environment tab) or just added - Before closing the browser tab?

**Comment by meghamahant** [comment]
Hi @DannyDainton,

I have created a recording but this comment area does not support video files (I have .mp4).

I share it here - https://www.dropbox.com/s/c5ffh5a9fl80o2c/bandicam%202020-11-21%2020-34-38-949.mp4?dl=0

**Comment by giridharvc7** [comment]
@meghamahant This is fixed with the latest version of the web app. Closing this issue for now.  Feel free to open this if you still face this issue
