### ISSUE TITLE
Does not show hints by code in edit collection

### ISSUE THREAD

**Issue by sergeevichvn** [a85/POSTMan-Chrome-Extension#9305]
**Describe the bug**
Hi, when I write script in request tab I have hints
![image](https://user-images.githubusercontent.com/10349805/99881762-b8783180-2c2c-11eb-9577-1fd07e5d0470.png)
but when I write script in edit collection hints on the background, not active + i cant change position window
![image](https://user-images.githubusercontent.com/10349805/99881825-09882580-2c2d-11eb-9b92-b9e1dd7722bc.png)

**To Reproduce**
1. Choose collection
2. Click on Edit
3. Choose Pre-request Scripts tab
4. Write code

**Expected behavior**
While I edit code in tab "Pre-request Scripts", I see hints by code

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information:**
 - App Type Native App
 - Postman Version 7.36.0 
 - OS: Windows 10 19041.630

**Comment by DannyDainton** [comment]
Hey @sergeevichvn 

Thanks for reporting this inconsistency - We'll take a look at this. 

In the meantime, you could jump over to our web version https://go.postman.co/build where you'll be able to use the auto-complete feature at the Collection, Folder and Request level. 🏆

**Comment by mccannt** [comment]
@sergeevichvn This should now be resolved. 

Can you please try the latest version of the application and let us know?

**Comment by sergeevichvn** [comment]
@mccannt  works, thx
without pop-up, good solution )
