### ISSUE TITLE
Post method not working in latest version 7.36.0

### ISSUE THREAD

**Issue by hamzamtn** [a85/POSTMan-Chrome-Extension#9312]
Only GET method is working in the latest version of postman v7.36.0 except other methods, but works in the previous version.

Kindly fix this bug. Thanks in advance

**Comment by preethammavin** [comment]
@hamzamtn can you try sending different request methods in the collection on your app and check if the methods are working as expected? 
https://docs.postman-echo.com/#9a4c3bce-30f7-a496-c9ec-78afecbf1545

You should be able to import the collection by clicking on the Run in Postman at the top right.

**Comment by DannyDainton** [comment]
Hey @hamzamtn 👋🏻 

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
