### ISSUE TITLE
Postman Web - Settings

### ISSUE THREAD

**Issue by meghamahant** [a85/POSTMan-Chrome-Extension#9314]
**Describe the bug**
My settings are lost in web version that I saved initially when I started using Postman Web.

**To Reproduce**
1. I logged in to Postman Web two days ago.
2. I changed the theme to dark one and enabled "Always open requests in new tab"
3. Now when I logged in today - Theme was default again and  "Always open requests in new tab" was OFF

**Expected behavior**
I expect my settings to be same until I change them. But as per current behaviour I have to make the settings again and again.
Since settings are to save the user's preference, s(he) should not have to do that again and again.

**Screenshots**

**App information (please complete the following information):**
 - App Type : Postman Web
 - Postman Version - Postman Web
 - OS: Windows

**Additional context**
I am mostly using desktop version as it will take some time to get habitual to web version but yes when I am going to Web , the things that I saved when I last worked on Web are gone. I see this as a pain point.

**Comment by DannyDainton** [comment]
I'm unable to recreate this issue in the latest version of the platform. I'm going to close this for now but if you're still facing a problem we can look to reopen this again.
