### ISSUE TITLE
No feedback provided when attempting to import malformed swagger.json

### ISSUE THREAD

**Issue by jdmallen** [a85/POSTMan-Chrome-Extension#9315]
**Describe the bug**
When importing the contents of a swagger.json file as raw text, if the `version` field is missing from the `info` object, the Continue button does not function at all. There's no feedback provided at all that the json is malformed-- it simply does nothing.

**To Reproduce**
1. Click Import.
2. Click raw text tab.
3. Paste [this sample swagger file](https://petstore.swagger.io/v2/swagger.json) into the raw text area.
4. Delete `"version":"1.0.5",` from the pasted text, near the top.
4. Click Continue and observe that nothing happens.

**Expected behavior**
It presents an error to the user when validation fails instead of providing no feedback. Since Postman is clearly validating the imported JSON against the OpenAPI spec, it would great to get feedback from the app as to what part of the pasted JSON failed validation. At the very least it should say it failed validation in general.

**Screenshots**
![image](https://user-images.githubusercontent.com/5761601/100142441-e1353c80-2e61-11eb-83b9-c50ded270bcf.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version v7.36.0
 - OS: Windows 10 Pro 1909

**Additional context**
Great app!

**Comment by arlemi** [comment]
This has been fixed in Postman 7.36.1, please update your app or download the latest version from postman.com/downloads 🙂

**Comment by jdmallen** [comment]
Cornfirmed. Thanks.
