### ISSUE TITLE
Version management of collections

### ISSUE THREAD

**Issue by Julien-Marpault** [a85/POSTMan-Chrome-Extension#9317]
I Have an API with versions 1.0 and 2.0.

In web view, no worry
![image](https://user-images.githubusercontent.com/23618436/100220824-287e0480-2f18-11eb-9dbe-25d16db50c10.png)
<hr/>

![image](https://user-images.githubusercontent.com/23618436/100220978-57947600-2f18-11eb-8e09-f07f8dd1327d.png)

But in Postman App, thre's no way to see the correct version, I only see the last one

![image](https://user-images.githubusercontent.com/23618436/100221174-9a564e00-2f18-11eb-8666-cc927e51f0bf.png)
<hr/>

![image](https://user-images.githubusercontent.com/23618436/100221264-b954e000-2f18-11eb-971b-76f710af7b34.png)

Thanks

**Comment by sankalp0o** [comment]
@JulienM28 with the release of V8 of Postman, it becomes possible to switch between collection versions in the app as well - 
<img width="484" alt="Screenshot 2021-02-01 at 8 04 24 PM" src="https://user-images.githubusercontent.com/7601762/106472454-b0f4c480-64c8-11eb-9477-1b9ce14cdf2c.png">

We understand that version management is not an easy process and we're introducing some new ways for you to do this. If you can spare some time, I'd love to have your inputs about how you'd like to do version management in Postman.

**Comment by Julien-Marpault** [comment]
Thank you for your message.
If I can help, it's ok for me.

**Comment by DannyDainton** [comment]
Hey @Julien-Marpault 

With the latest changes to the platform, is this still an issue for you? If not, can we close this out, please?
