### ISSUE TITLE
Ability to link to request in collection

### ISSUE THREAD

**Issue by inland-rob** [a85/POSTMan-Chrome-Extension#9323]
**Is your feature request related to a problem? Please describe.**
I want to be able to deep link to an API a collection so I can include the link in specification documents. The link should open the Postman client and display the API documentation in question. Getting the href should be as easy as selecting "Link to this API" with option-click on mouse.

**Describe the solution you'd like**
The link should open the Postman client and display the API documentation in question. Getting the href should be as easy as selecting "Link to this API" with option-click on mouse.

**Describe alternatives you've considered**
wasting time describing where to find the API specification in Postman.
![Screen Shot 2020-11-25 at 1 00 51 PM](https://user-images.githubusercontent.com/68445105/100281242-654cfa00-2f1e-11eb-994b-5d8bfcebc479.png)

**Additional context**
![image](https://user-images.githubusercontent.com/68445105/100281045-08e9da80-2f1e-11eb-8402-0add56f85505.png)

**Comment by sankalp0o** [comment]
@inland-rob if you use Postman on the web, you should just be able to copy the URL to the API request that you see in the address bar. Can you try it out and let us know if this solves what you are looking for? We will improve the experience of the desktop app to include this as well.

**Comment by inland-rob** [comment]
Thank you. Looking forward to using deep links in Postman.
While I'm at it I'll (hopefully) look forward to adding JS style comments to JSON in Postman. Super helpful during development phase. Can be stripped out for production. I realize JSON does not have comments, but who cares when it's inside Postman. Delight your users!!

**Comment by sankalp0o** [comment]
@inland-rob have you tried using the comment feature inside Postman? It lets you annotate different parts of the request, including json bodies, headers, etc. They are not JS style, but built in the interface, so that you can tag other team members, reply to comments, resolve them when they aren't needed.

**Comment by inland-rob** [comment]
Yes...but that is not my point. Inline comments have the benefit of being
both proximally contextual and informative. They are on the same line as
the key:value pair. No need to 'point over there' to a comment AND when you
publish APIs for customer/partner consumption you can provide meaning in a
very simple way. Of course we make mention to partners that the comments
are stripped out at runtime.
Think of how useful that would be to Postman users and how they would brag
about it to others. Might just be a growth tool for your company.
Perhaps survey your customer base in a neutral way to gauge interest.

**Comment by sankalp0o** [comment]
Inline comments this way can be contextual (up to the exact letter, not just the line), and informative (affording use of markdown, discussion threads, and more). For example,
<img width="622" alt="Screenshot 2021-01-26 at 1 06 55 PM" src="https://user-images.githubusercontent.com/7601762/105814402-601c3200-5fd7-11eb-93ef-77fe0f0d2b18.png">

We'd think more about how json comments help solve use cases not covered by the current feature and also reach out to the community for their opinions. Thanks for sharing!

**Comment by inland-rob** [comment]
Ok. 
But you still have to click to see the comment. That is more work tha the comment being right there ‘on the page’ as it were.

**Comment by sankalp0o** [comment]
I'm closing this issue since the original request is solved. If you have more inputs on how request links can be improved, please let us know!
I understand that interface-based commenting features require additional interaction as compared to code comments. However, this direction lets us build a consistent commenting experience across everything in Postman. I'd, however, keep this feedback in mind and we will research into json comments and how they can be leveraged for collaborating on the request body.

**Comment by inland-rob** [comment]
ok
for now we are adding comments in the value example of the key:value pair.
Sucks, but works for today.
Maybe survey your user base to see what they want and how important this is.
