### ISSUE TITLE
 Invalid file save format

### ISSUE THREAD

**Issue by Zinnurka** [a85/POSTMan-Chrome-Extension#9324]
1) Execute a request
2) Click "Save to file"

Expected Result: The file is saved in * .p10 format. (example of saving from the browser)
![image](https://user-images.githubusercontent.com/32505382/100309470-c92dfc00-2fcc-11eb-92a0-698f71523aae.png)

Actual result: the file is saved in * .bin format
![image](https://user-images.githubusercontent.com/32505382/100309342-79e7cb80-2fcc-11eb-82d4-ed53c854a617.png)

**Comment by DannyDainton** [comment]
Hey @Zinnurka 

Can you fill out the issue template and provide more context, please.

---



**Describe the Issue**

> A high-level summary or description of the problem that you're facing.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.


**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 


**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version:
 - Operating System:

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by DannyDainton** [comment]
Hey @Zinnurka  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
