### ISSUE TITLE
New Integration Request - uipath

### ISSUE THREAD

**Issue by Nosipho93** [a85/POSTMan-Chrome-Extension#9327]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
@Nosipho93 Can you please elaborate on the other parts of the Integration Request Template as well. It will help us design/ plan the Integration accordingly.

**Comment by shashankawasthi88** [comment]
Closing this for the lack of details. @Nosipho93 please feel free to reopen with more details on the Integration required.
