### ISSUE TITLE
Environment variables are not syncing in the current version Postman v7.36.0

### ISSUE THREAD

**Issue by lineshr** [a85/POSTMan-Chrome-Extension#9330]
Environment variables are not syncing in the current version.
more specifically I can say that it will not sync INITIAL VALUE and  CURRENT VALUE in cloud.

variables name is updating but not values.

**Comment by DannyDainton** [comment]
Hey @lineshr 

Can you please fully complete the issue template and provide more context, please.

---



**Describe the Issue**

> A high-level summary or description of the problem that you're facing.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.


**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 


**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version:
 - Operating System:

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by DannyDainton** [comment]
Hey @lineshr 👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
