### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by thinkersOne** [a85/POSTMan-Chrome-Extension#9334]
登录客户端报了这样一个错

Something went wrong!
We're having some difficulties connecting to our authentication service. Try again after some time.

**Comment by DannyDainton** [comment]
Hey @thinkersOne 

Please could you complete the full issue template and provide more context about the issue you're facing.

---



**Describe the Issue**

> A high-level summary or description of the problem that you're facing.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.


**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 


**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version:
 - Operating System:

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by thinkersOne** [comment]
<img width="797" alt="1" src="https://user-images.githubusercontent.com/19427384/100859137-d9ad0d80-34c9-11eb-85d5-b1904efedd5c.png">
<img width="471" alt="2" src="https://user-images.githubusercontent.com/19427384/100859150-ddd92b00-34c9-11eb-85e5-a90123e03fb6.png">

**Comment by thinkersOne** [comment]
1，Sign in
2,  error：
Something went wrong!
We're having some difficulties connecting to our authentication service. Try again after some time.

postman version 7.3.5
postman client login

**Comment by thinkersOne** [comment]
i use windows system，mac ios system is ok

**Comment by DannyDainton** [comment]
Hey @thinkersOne 

Is this still an issue for you? If not, we can close this one out.
