### ISSUE TITLE
Backup on GitLab custom domain only shows last 100 projects

### ISSUE THREAD

**Issue by arlemi** [a85/POSTMan-Chrome-Extension#9335]
Reported by a user on Twitter: https://twitter.com/alex_makdessi/status/1334076901346959365

**Describe the Issue**

I'm trying to backup my collections into a gitlab custom domain.
I can't select my project because the dropdown is actually showing only the last 100 projects

**Steps to Reproduce**

1. Create GitLab integration
2. Try to back-up collection
3. Can't access more than the last 100 projects

**Screenshots or Videos**

NA

**Environment Information**

 - Platform Type: All platforms
 - Postman Version: 7.36
 - Operating System: Windows

**Additional Context**

**Comment by Veridis** [comment]
If this can help, postman is calling gitlab's API on this endpoint:

```
/api/v4/projects?private_token=<token>&membership=true&per_page=100&page=1
```

I'm not sure increasing the `per_page` parameter is a good solution, but we could have the possibility to at least use the `project id` if the project is not in the list ?

**Comment by shashankawasthi88** [comment]
@Veridis - we have addressed this issue now. You should be able to fetch more than 100 projects now. We have increased the limit significantly and users should not face this issue anymore.
