### ISSUE TITLE
Cannot open Postman

### ISSUE THREAD

**Issue by nikhjoy** [a85/POSTMan-Chrome-Extension#9338]
![error postman](https://user-images.githubusercontent.com/38971649/100934715-98881e00-3508-11eb-8c00-032e209108e5.JPG)

I cannot open Postman in my system. Above attached is the screenshot when I try to  open Postman App in the system. Cleared files in local and roaming, installed a new version and still no change. For the past 2 days I am having this issue. Its still not getting opened.

Kindly do the needful.

**Comment by nerdfiles** [comment]
same, i run the desktop app on macOS big sur and it simply does not open. i've added it for full disk access, etc.

**Comment by Raj-postman** [comment]
Hi @nikhjoy @nerdfiles - Sorry to hear that. Would you please try renaming (or clearing) the local files for your Postman installation and see if that helps? You can find full instructions for doing so in the below article.

> https://support.getpostman.com/hc/en-us/articles/360025359014

**Comment by introkun** [comment]
Cannot open at all.
`[11456][1607778020940][main][info]["Booting PostmanAgent 0.2.4, darwin-20.1.0 on x64"]
[11456][1607778021038][main][warn]["Postman Agent~Main~populateInstallationId: Failed to get installationId from agentSettings but with no error"]
[11456][1607778021054][main][info]["UpdateHandler~init - Success"]
[11456][1607778021760][main][info]["WebsocketAgent~start - Listening on port",10533]
[11456][1607778021841][main][info]["AutoLaunch: Enabled"]
[11456][1607778021851][main][info]["AutoLaunch: Enabled as the default behaviour."]
[11456][1607778021921][main][info]["AutoLaunch: isAutoLaunchDefaultBehaviourSet is set and persisted."]
[11540][1607778145343][main][info]["Booting PostmanAgent 0.2.4, darwin-20.1.0 on x64"]
[11540][1607778145356][main][info]["InitHelpers~createDefaultWorkingDir - Default working dir creation already attempted"]
[11540][1607778145357][main][info]["UpdateHandler~init - Success"]
[11540][1607778146228][main][info]["WebsocketAgent~start - Listening on port",10533]
[11540][1607778268377][main][info]["AutoLaunch: Disabled"]
[11540][1607778270513][main][info]["Quitting app"]
`

**Comment by askilondz** [comment]
Same issue here. Got a new mac...upgraded to Big Sur...download postman...app simply doesn't open.

**Comment by nikhjoy** [comment]
Disappointed that it is not yet fixed. app simply doesn't open. I switched to online version :(

**Comment by Raj-postman** [comment]
@nikhjoy Sorry to hear that, could you [submit a ticket from here](https://www.postman.com/support) and share logs with us to check on this further?
[This article here](https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-) should help you with the same.

**Comment by xk0der** [comment]
For folks on MacOS - Check out this thread and see if the solution mentioned there helps: https://community.postman.com/t/postman-native-app-doesnt-work-on-apple-macbook-m1-chip/18990

> I came across something similar to this and found that file permissions may at times cause this. One of our users had fixed this by enabling the root user on their machine.
> 
> Essentially when listing the following folders, you should not get permission denied error.
> 
>     ls ~/Applications/`
>     ls ~/Library/`
> To enable root account run the following command:
> 
>     sudo -i
> Enter your password when asked for and then you may exit out by typing exit
> 
> Then try installing the Postman app again from here: https://www.postman.com/downloads/ 
> 
> You can also try to see if an `Administrator` account works (assuming your current account is standard account).
> 
> If nothing works feel free to reach out to Postman support here: https://www.postman.com/support

For Windows 10 - check to see if Postman Canary works: https://www.postman.com/downloads/canary else reach out at Support so that we can help figure out what's going on!
----
I'm closing this - as we have a solution for MacOS and Windows 10 might be a very specific issue as we haven't had any more reports.

**Comment by xk0der** [comment]
We are investigating the MacOS BigSur issue here: #9429
