### ISSUE TITLE
Send array as part of x-www-form-urlencoded

### ISSUE THREAD

**Issue by toriacht** [a85/POSTMan-Chrome-Extension#934]
I am posting a form, one of the fields requires an array. I have tried numerous ways around this with brackets, commas etc but to no avail. How can I force/tell my form to send the value of a certain key as an array

```
{
"id": "unprocessable_entity",
"message": "The provided ssh_keys value must be an array."
}
```

**Comment by abhijitkane** [comment]
If you use "form-data", and include multiple fields with the same key, it'll be interpreted as an array on the server:
```
------WebKitFormBoundaryAw8flIkTiBYSCWBy
Content-Disposition: form-data; name="key1"

value1
------WebKitFormBoundaryAw8flIkTiBYSCWBy
Content-Disposition: form-data; name="key1"

value2
------WebKitFormBoundaryAw8flIkTiBYSCWBy
Content-Disposition: form-data; name="key1"

value3
------WebKitFormBoundaryAw8flIkTiBYSCWBy--
```
For a single entity, I'm not sure how you can HTTP to send data as an array. Can you give a curl command that works for you?

**Comment by toriacht** [comment]
Thanks for the reply,

This doesn't work I'm afraid, commands below converted to CURL

Good command:

```
curl -X POST -H "Authorization: Bearer vvvvvvvvvvvvvvvv" -H "Cache-Control: no-cache" -H "Postman-Token: xxxx-f239-c871-4931-xxxxx" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -F "name=test" -F "region=lon1" -F "size=2GB" -F "image=333333" -F "backups=false" -F "user_data=null" -F "private_networking=null" -F "ipv6=false" https://api.digitalocean.com/v2/droplets
```
Bad command:

```
curl -X POST -H "Authorization: Bearer vvvvvvvvvvv" -H "Cache-Control: no-cache" -H "Postman-Token: xxx-xxx-5709-xxx-0f312f76ace2" -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -F "name=test" -F "region=lon1" -F "size=2GB" -F "image=44444" -F "ssh_keys=444" -F "ssh_keys=555" -F "backups=false" -F "user_data=null" -F "private_networking=null" -F "ipv6=false" https://api.digitalocean.com/v2/droplets
```

**Comment by toriacht** [comment]
Hi again...

a successful raw CURL command looks like this


curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer YOUR_TOKEN_HERE' -d '{"name":"example.com","region":"nyc3","size":"512mb","image":"ubuntu-14-04-x64","ssh_keys":[KEYID1,KEYID2],"backups":false,"ipv6":true,"user_data":null,"private_networking":null}' "https://api.digitalocean.com/v2/droplets

**Comment by abhijitkane** [comment]
If you're sending JSON, you can just use the same JSON that you're passing in the "-d" flag in the "raw" body mode. You can check the console to ensure the correct data is being sent.

Check this collection - https://www.getpostman.com/collections/d16c51a2e26ee8aaffdb

**Comment by toriacht** [comment]
many thanks...
