### ISSUE TITLE
Postman Interceptor can't capture *.js and etc.

### ISSUE THREAD

**Issue by NewUserHa** [a85/POSTMan-Chrome-Extension#9340]
**Describe the Issue**

Postman Interceptor can capture things in chrome `doc` and `xhr` tab. And can't capture things in `pic` and `js` tab.
the proxy has no issue. but the interceptor can work well with https than proxy.

**Steps to Reproduce**

1. make postman native and interceptor connected
2. access http://httbin.org
3. can see only the `get http://httpbin.org/` is captured. 

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/32261870/101203751-23524f80-36a6-11eb-8818-f0ae4e7bc288.png)
![image](https://user-images.githubusercontent.com/32261870/101203790-3107d500-36a6-11eb-8a2b-dc92ec45bb2e.png)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 7.36.0
 - Operating System: win32 10.0.17134 / x64

**Additional Context**

both filters in the `interceptor` and the `postman nativa app` are empty!

**Comment by shashankawasthi88** [comment]
@NewUserHa while we are looking into this, we now support capturing HTTPS traffic via Postman Proxy that should help you with the current use case that you have. Following the steps [here](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#capture-https-traffic-with-postmans-built-in-proxy) to enable capturing of HTTPS traffic via Postman Proxy.

**Comment by agrwl-harsh** [comment]
Hey @NewUserHa , we have fixed the issue. Please try in the latest postman app.

**Comment by VShingala** [comment]
@NewUserHa This issue has been fixed for some time now. I'll be closing this for now but feel free to open this issue in case you face any further problems with it.
