### ISSUE TITLE
Adding dimensions for header images in profile pages

### ISSUE THREAD

**Issue by carrrson** [a85/POSTMan-Chrome-Extension#9341]
**Is your feature request related to a problem? Please describe.**
Not so much a problem, but it would be super helpful to have the dimensions/aspect ratio available on the team and personal settings page in the web interface.

![header](https://user-images.githubusercontent.com/20145532/101210876-3af8ec00-3644-11eb-9c96-073c97ad075f.png)

**Describe the solution you'd like**
The picture upload popup gives a max size and formats, but no dimensions. It's not a super common ratio, so would be easier to hand off to design teams if there was an aspect ratio available.

<img width="354" alt="upload popup" src="https://user-images.githubusercontent.com/20145532/101211067-90cd9400-3644-11eb-8451-9d9e40e0b1c2.png">

**Comment by abhijitkane** [comment]
Also, the aspect ratio shown while cropping (333x166) isn't the same as in the final render (810x80).

**Comment by ArjunSingh-PM** [comment]
We have added dimension details to the picture upload pop-up for the header image
![image](https://user-images.githubusercontent.com/53265429/195326788-d08b59ee-7945-4709-ac10-ac62604c20df.png)
