### ISSUE TITLE
Constant Blank Screen Issue

### ISSUE THREAD

**Issue by Diboiza** [a85/POSTMan-Chrome-Extension#9345]
Keep getting the below blank screen everytime when you the App:
Version: v7.36.0
![image](https://user-images.githubusercontent.com/28605220/101316035-64905e00-3864-11eb-81f6-26acefb3cda7.png)

**Comment by Raj-postman** [comment]
Hi @Diboiza 

Looks like [this suggestion](https://github.com/postmanlabs/postman-app-support/issues/9072#issuecomment-694790050) worked for users facing similar issue: #9072 (comment)

Could you follow the same and let us know if that helps?

**Comment by m3dbedb** [comment]
I have the same issue with postman 9.2.0 (win 64) under windows 10, with 1.2 gb free ram (i5 laptop)

Disabling hardware acceleration does not fix the issue. Postman getting white after several minutes of work with regular requests.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5980
