### ISSUE TITLE
Apple Silicon build of Postman for macOS

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#9346]
Add support for `darwin-arm64` architecture that support Apple Silicon and M1 powered Macs.

**Comment by numaanashraf** [comment]
Postman for macOS (v7.36.0, as of this post) supports M1 powered Macs via Rosetta2 translation. True Apple Silicon build of Postman for macOS is expected in early 2021.

**Comment by soilSpoon** [comment]
> Postman for macOS (v7.36.0, as of this post) supports M1 powered Macs via Rosetta2 translation. True Apple Silicon build of Postman for macOS is expected in early 2021.

It doesn't seem to work on the mac mini DTK.

**Comment by numaanashraf** [comment]
@soilSpoon There are no plans to bring support for pre-release DTK hardware at this point.

**Comment by barefeettom** [comment]
Please support the Apple DTK. Your core customers are developers who, like me, are likely to have an Apple DTK running the latest macOS.

**Comment by notsle** [comment]
Any update on a native or universal build for apple silicon?

**Comment by vicampuzano** [comment]
I can't get postman working on my new Macbook Pro 13 16Gb Ram with Apple Silicon. Lucky to have Postman web but it's not a long-term solution.

Any updates about native support?

Thanks!

**Comment by ManojSatishkumar** [comment]
I'm looking for Apple silicon build for postman app.
Please built It fast and change our experience.

**Comment by numaanashraf** [comment]
@vicampuzano Could you share your logs with help@postman.com? Both Postman v7 and Postman v8 is tested and certified to work with Apple Silicon (M1) hardware. We'd love to understand any issues you are facing at your end and help you troubleshoot.

<img width="1390" alt="Screenshot 2021-02-13 at 10 58 33 AM" src="https://user-images.githubusercontent.com/3295568/107842645-e499ed80-6dea-11eb-8139-86dc158dad93.png">

**Comment by vicampuzano** [comment]
You're right @numaanashraf . I don't know what happens but it's working fine now. 

Congratulations from my side. Postman v8 looks pretty nice and works fine! ;) 🙌🙌🙌

I can't wait to see the new apple silicon native version!

**Comment by cessenagano** [comment]
Hi, is your client certificate working on mac m1 while you are connected to vpn?

**Comment by kasharaylo** [comment]
Can't wait for native m1 support for Postman.

**Comment by ghost** [comment]
Just got a MacBook Air m1 and waiting for Postman native support

**Comment by 4thousand** [comment]
> @vicampuzano Could you share your logs with [help@postman.com](mailto:help@postman.com)? Both Postman v7 and Postman v8 is tested and certified to work with Apple Silicon (M1) hardware. We'd love to understand any issues you are facing at your end and help you troubleshoot.
> 
> <img alt="Screenshot 2021-02-13 at 10 58 33 AM" width="1390" src="https://user-images.githubusercontent.com/3295568/107842645-e499ed80-6dea-11eb-8139-86dc158dad93.png">

can run  but not native

**Comment by 4thousand** [comment]
good bye postman i go use thunder clinet i cant wait postman support m1

**Comment by thedocbwarren** [comment]
> good bye postman i go use thunder clinet i cant wait postman support m1

What is thunder?

**Comment by notsle** [comment]
> > good bye postman i go use thunder clinet i cant wait postman support m1
> 
> What is thunder?

VS Code extension.  Since VS Code is M1 native and fast, this could be a decent alternative.  I've never used it. so not sure if it can handle pre-request scripts, tests, variables, like postman does. 
https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

**Comment by thedocbwarren** [comment]
> > > good bye postman i go use thunder clinet i cant wait postman support m1
> > 
> > 
> > What is thunder?
> 
> https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

Cool thanks!

I'll check it out.  I don't use 99% if postman's features as I normally write mocha tests.  That said, sometimes it's nice to quickly work with something in a client.  Who knows if postman is working on Apple Silicon native version.  Even though I think the tool-chain is native now.  But I don't work there.

**Comment by AminulBD** [comment]
Maybe the @postmanlabs don't care about users. I'm moved to https://paw.app/ which is excellent so far I'm using.

**Comment by camerons2001** [comment]
Use Insomnia for m1, postman is disgusting!

**Comment by ksharpe5** [comment]
> Postman for macOS (v7.36.0, as of this post) supports M1 powered Macs via Rosetta2 translation. True Apple Silicon build of Postman for macOS is expected in early 2021.

Is there any update on this? We're getting well beyond early 2021 as mentioned above.

**Comment by LilaQ** [comment]
Any updates would be really appreciated. The M1 community is growing and still using essential software like Postman with Rosetta is hurting my soul.

**Comment by ishouvik** [comment]
Eagerly waiting for Postman on native Apple Silicon

**Comment by elahmo** [comment]
Any updates about this? It works well in the browser, so it would be neat to have a native version as well.

**Comment by avxkim** [comment]
Any news?

**Comment by nickshatilo** [comment]
Any updates on this one?

**Comment by numaanashraf** [comment]
Hey everyone! We are still working on ironing out some of the issues in the M1 build and we hope to get an exploratory version available on our Canary channel in the next 2 weeks. Thanks for your patience!

**Comment by avxkim** [comment]
@numaanashraf are you upgrading electron version to the latest, ie 12?

**Comment by louis-hoang21** [comment]
> Hey everyone! We are still working on ironing out some of the issues in the M1 build and we hope to get an exploratory version available on our Canary channel in the next 2 weeks. Thanks for your patience!

**I waited almost 1 year. So I hope to release a version that supports m1 soon, not run through the via Rosetta2 translation plz.**

**Comment by dromeroDev** [comment]
Eagerly waiting for Postman on native Apple Silicon

**Comment by LilaQ** [comment]
@numaanashraf  Yea any update on this? The 2 weeks ETA are almost over.

**Comment by csulit** [comment]
Any update?

**Comment by PikaFederation** [comment]
Up, any update?

**Comment by humbertowoody** [comment]
Any updates?

**Comment by numaanashraf** [comment]
Hey everyone! We are ironing out few occasional crashes we observed in our internal testing. We will share an update as soon as we have a stable build. Thanks again for your patience.

**Comment by encryptedtouhid** [comment]
looking forward to it 😁

**Comment by merrcury** [comment]
Having Performance Issues on Apple M1 with intel build. Looking forward to the M1 build.

**Comment by PikaFederation** [comment]
I can't wait to get it.

**Comment by theshakilahmed** [comment]
Waiting for the m1 version :)

**Comment by rawrstack** [comment]
> Waiting for the m1 version :)

I dont know why people downvote this. Current Postman having performance issues on Apple M1 with intel build

**Comment by DavidGarciaCat** [comment]
> > Waiting for the m1 version :)
> 
> I dont know why people downvote this. Current Postman having performance issues on Apple M1 with intel build

Simple: spamming all people following this case with unnecessary messages.

The Postman team already knows people want this update, so there's no need to keep posting the "I am eager to get it too".

Can you guys please stop making unnecessary noise? I also want it, and I understand it's "frustrating" but everyone already knows about your case too. Just give the :+1: as part of the first message of this issue.

**Comment by hnher** [comment]
Waiting for the m1 version :)

**Comment by twitharshil** [comment]
Hey Everyone, 
We're happy to share the first preview of arm64 arch-based canary application, that natively supports the Apple silicon platform (m1 machines). It took us a while to make it stable, but you can now download it from [here](https://dl.pstmn.io/arm64/PostmanCanary-osx-8.6.0-canary210608-1405.zip) & run it on mac platform with M1 chips to experience better performance. 

**Note:** These app builds are an early preview of the canary application with auto-updates disabled. We'll be evaluating the stability of these application builds for a while before rolling them out in production, along with making adjustments to our distribution servers. Expect few more iterations of these application builds if any issues are discovered. 

Do try it out and report issues if you find any on this thread !!

**Comment by yy523697597** [comment]
dude, the canary version is much faster than rosetta version! Love it.

**Comment by LilaQ** [comment]
Oh god, it's so much faster as native version! ❤️

**Comment by stephan-swiftcom** [comment]
Will there be a popup of some sort with a seamless upgrade method for users using the Rosetta version?

**Comment by SubtleCo** [comment]
Wow what luck, I literally randomly googled Postman ARM M1 and found this thread 7 hours after the first public build was released? OH OK FATE

Edit: Holy speed, batman

**Comment by Ritish-Madan** [comment]
> Will there be a popup of some sort with a seamless upgrade method for users using the Rosetta version?

Maybe no, as @twitharshil said that it is a canary version and has not been rolled out in production yet. So maybe, you need to download and install it manually. But that's much faster and smoother than Intel Version.

**Comment by Yachint** [comment]
Thanks for the update, I was just on the brink of finding an alternative but then I saw this thread 👍

**Comment by focher** [comment]
Is it preferred that issues are reported separately on their own? I have experienced timeouts on some calls that work fine from 8.x running under Rosetta 2 but other calls work fine. Just want to report the problem properly.

**Comment by jviotti** [comment]
@focher Let's keep the discussion in this issue, so its easier for us to manage how the M1 build is doing until we do a stable release!

>  I have experienced timeouts on some calls that work fine from 8.x running under Rosetta 2 but other calls work fine

Any details would be appreciated! Mainly if its something we can reproduce from our side too (I have an M1 too).

**Comment by nilicule** [comment]
> These app builds are an early preview of the canary application with auto-updates disabled

How do we get updates for this? The download from the [canary page](https://www.postman.com/downloads/canary/) seems to result in non-arm64 versions.

**Comment by Xor-el** [comment]
@nilicule , you need to use the [direct link](https://dl.pstmn.io/arm64/PostmanCanary-osx-8.6.0-canary210608-1405.zip) posted by @twitharshil some comments above.

**Comment by nilicule** [comment]
> @nilicule , you need to use the direct link posted by @twitharshil some comments above.
> [Postman M1 Canary](https://dl.pstmn.io/arm64/PostmanCanary-osx-8.6.0-canary210608-1405.zip)

I'm aware, but that's a much older version than the latest canary, hence the question where we can find future updates

**Comment by twitharshil** [comment]
@nilicule Until we have a stable release for arm64 based application, you can find the updated builds from this thread itself. We will continue to post updated builds if any issues are reported which are specific to arm64 based application

**Comment by twitharshil** [comment]
@focher Can you share some more details around the issue that you are facing? Also, since we are tracking this thread for issues that are particular to arm64 based application, would you mind giving a try to our x64 arch-based canary application [link](https://dl.pstmn.io/download/channel/canary/osx_64) & see if the issue still reproducible for you?

**Comment by craigz** [comment]
> @focher Can you share some more details around the issue that you are facing? Also, since we are tracking this thread for issues that are particular to arm64 based application, would you mind giving a try to our x64 arch-based canary application [link](https://dl.pstmn.io/download/channel/canary/osx_64) & see if the issue still reproducible for you?

I just downloaded this 'update' as it appears to be newer than the 8.6.0 canary build I have been running. Get Info suggest this is not in fact an Apple Silicon build, has the download been replaced since the link was posted? 
<img width="264" alt="postmanInfo" src="https://user-images.githubusercontent.com/1929275/124169595-688c0380-da74-11eb-8d07-c651bd88ed38.png">

**Comment by simoncpu** [comment]
I thought there was something wrong with my setup. The "Import" feature doesn't work on my Macbook Air M1.

Version 8.7.0 (8.7.0)

Edit: Downloading the Canary version now...

**Comment by jnovak-SM2Dev** [comment]
@twitharshil Can you update this channel when the main build is updated to work with the M1, so we can know when to switch off the canary build?

**Comment by blueberry6401** [comment]
Hi, the last M1 version is quite long time ago. Is there any updates?

**Comment by samparmenter** [comment]
Using the above canary version it still comes up as intel based in Activity Monitor. Whats the deal?

**Comment by bugflux** [comment]
Comes up as Apple on my machine 
![image](https://user-images.githubusercontent.com/583643/129347052-c6eeaca7-e817-4f1b-b759-509cb4988ea4.png)

**Comment by rawrstack** [comment]
> Comes up as Apple on my machine

Which version is this? mine use 8.10 canary version and its show as intel. And yes it load quite slow.

**Comment by bugflux** [comment]
I don't think all Canary versions have M1 support, only the one that was linked in a [previous comment](https://github.com/postmanlabs/postman-app-support/issues/9346#issuecomment-858367418):

![image](https://user-images.githubusercontent.com/583643/129446175-9f08c343-6c22-4e24-a1ea-bda7819e3c66.png)

**Comment by samparmenter** [comment]
@bugflux You are correct, I just "downgraded" to the above version and its back on apple silicon instead of intel via rosetta2. Thanks!

**Comment by orendi84** [comment]
Any roadmap for the non-canary apple silicon version? 
The performance and the experience is day and night compared to the rosetta one. 
Thanks!

**Comment by anapeksha** [comment]
Any idea when we will have a stable Postman build for M1?

**Comment by louis-hoang21** [comment]
How long will we have to use this Postman beta build for M1? You guys are too late to release the official version

**Comment by vkoivula** [comment]
This is as agile as "Spotify agile" which everybody should be doing. Meaning it takes over one year since dev kits were available to realease a working software :)

**Comment by EggsBlue** [comment]
We urgently need to use the m1 chip native version, and you should do it as soon as possible

**Comment by ngohungphuc** [comment]
@EggsBlue you are not their boss.

**Comment by EggsBlue** [comment]
> @EggsBlue you are not their boss.

Yeah, Sorry...

**Comment by vkoivula** [comment]
> @EggsBlue you are not their boss.

You ever heard of TextMate? What happened when there started to be alternatives and it didn't get updated regularly?

**Comment by thedocbwarren** [comment]
Web version works in any M1 native browser.  So does electron.  Sorry to say it screams of, "Meh.  Will get to it someday if I feel like it."

**Comment by DavidGarciaCat** [comment]
Hey @thedocbwarren 

Please allow me to intervene here: the problem with the "web version" is precisely that it is a "web version", which means it's hosted online. It means it is impossible to target local network nodes for development and testing or even some hosts that run behind a VPN.

**I don't remember having any problem** with the M1 Canary version of Postman; I must also say **I don't use it daily**. But, as s Software Engineer, I recall both the necessity of using the best tools I can use while at the same time my constraints might not be pleasing everyone using the software I develop. In the end, everyone wants everything for yesterday.

Still, if anyone feels _"this bad"_ because the M1 version of Postman doesn't work as they want, remember there are alternatives over there. You can look for other HTTP Clients or even consider browser extensions (Google Chrome Store has some of them). I will stick with the current M1 version and wait until it's fully ready and M1 native.

**Comment by agnoster** [comment]
> remember there are alternatives over there

Unfortunately if your team/company has standardized on Postman, the switching costs are high. I'm in the camp of "still using the old M1 Canary version", myself, and I do hope eventually the Postman team builds universal binaries as part of their standard pipeline. I understand these things take time sometimes, but to the degree user feedback matters I guess I'd like to give this a +1 as a "paying" customer.

**Comment by thedocbwarren** [comment]
> Hey @thedocbwarren
> 
> Please allow me to intervene here: the problem with the "web version" is precisely that it is a "web version", which means it's hosted online. It means it is impossible to target local network nodes for development and testing or even some hosts that run behind a VPN.
> 
> **I don't remember having any problem** with the M1 Canary version of Postman; I must also say **I don't use it daily**. But, as s Software Engineer, I recall both the necessity of using the best tools I can use while at the same time my constraints might not be pleasing everyone using the software I develop. In the end, everyone wants everything for yesterday.
> 
> Still, if anyone feels _"this bad"_ because the M1 version of Postman doesn't work as they want, remember there are alternatives over there. You can look for other HTTP Clients or even consider browser extensions (Google Chrome Store has some of them). I will stick with the current M1 version and wait until it's fully ready and M1 native.

You are absolutely correct you can not use the web version for local apis.  My point that the web version works (also as a software dev) tells me there is some other reason for massive delay.

Where I think the issue is not wanting to invest on it for the AS crowd yet as it's working in Rosetta.  That could be the long term approach till forced as well. 

That makes no sense since the Canary build shows it's possible.  I mean, anything is possible given time and money.

For me I can use alternatives and do so.

**Comment by 2stash** [comment]
Hi, just downloaded for macpro 13in M1, postman will not open. Shows up in the activity monitor, but no windows open up and I don't get an error of any kind.

**Comment by AbdullahDiaa** [comment]
Canary version is M1 ready and works perfectly with M1 Macs:
https://isapplesiliconready.com/app/Postman

**Comment by anapeksha** [comment]
@AbdullahDiaa We know about that already! But, we are waiting for the stable Apple Silicon build of Postman!

**Comment by agnoster** [comment]
@AbdullahDiaa Actually the live canary build available at https://www.postman.com/downloads/canary/ is _not_ universal/native - you have to download the one specific M1 canary build linked in this thread, and it's very old at this point. I'd actually be pretty happy if there was an option to download an ARM build, similar to how the Windows canary build has 32-bit and 64-bit builds - and I assume this would be a prerequisite for eventually offering an M1 build of the non-canary version, which would _also_ be nice, but I can live with being on canary for native performance. I just wish it were the _live_ canary build, and not a "dead" one 😆

**Comment by 2stash** [comment]
@postman and friends.
I just wanted to give feedback on what I saw with the M1. I am a new user to mac, and got the M1 because I needed a laptop, and wanted to work more in react-native, and the m1 was the cheapest.  Coming from windows I think setting a mac is really hard, but I love using postman. However I don't want to try and mess around with installing something else as a workaround, so until the M1 stops sucking (no dual monitor support!!) I am using a vscode extension "Thunder Client" that mimics postman.

**Comment by jdgarcia1381** [comment]
> @postman and friends.
> I just wanted to give feedback on what I saw with the M1. I am a new user to mac, and got the M1 because I needed a laptop, and wanted to work more in react-native, and the m1 was the cheapest. Coming from windows I think setting a mac is really hard, but I love using postman. However I don't want to try and mess around with installing something else as a workaround, so until the M1 stops sucking (no dual monitor support!!) I am using a vscode extension "Thunder Client" that mimics postman.

Right now you can install most dependencies/software using Homebrew, it will automatically install ARM version for you. For Postman, you can use the installer posted on [this comment](https://github.com/postmanlabs/postman-app-support/issues/9346#issuecomment-858367418). For dual (or more) monitors, you can use DisplayLink. I was also new to Mac with my M1 and I'm loving it 🙂

**Comment by thinh090** [comment]
Postman was slow for native support on m1 mac

**Comment by jovenntann** [comment]
> Postman was slow for native support on m1 mac

this is true hopefully they can fix it on the next update

**Comment by pravinkanna** [comment]
It's been more than one year since apple released the apple silicon. Still no native support for m1 macs

**Comment by vkoivula** [comment]
@numaanashraf when is Postman releasing Apple Silicon version? Is it impossible to communicate schedules for us or have you set a goal of being the last Intel-only application?

**Comment by numaanashraf** [comment]
We are adding the finishing touches to it now and Apple Silicon support for Postman will be available by end of next week.

<img width="1259" alt="Screenshot 2021-10-14 at 12 16 14 AM" src="https://user-images.githubusercontent.com/3295568/137194562-402aa097-c199-47ab-b1a3-a956c490da0d.png">

**Comment by ngohungphuc** [comment]
Super thank you for your team hard work 💯

**Comment by vkoivula** [comment]
> We are adding the finishing touches to it now and Apple Silicon support for Postman will be available by end of next week.

Thanks for your prompt answer! I am looking forward to it and getting subscription back for our team.

**Comment by twitharshil** [comment]
Hey everyone !!

We have our first public build of Postman for Desktop that runs natively on Apple Silicon. You can download it via [this link](https://dl.pstmn.io/download/version/9.0.7/osx_arm64). This build has auto-updates enabled and new versions of Postman will be pushed via auto-updates.

Do let us know what you think and report any issues on this thread.

**Comment by sparty02** [comment]
Does this team maintain the cask in homebrew?  If so, can you update it with support to download the arm version when appropriate?

**Comment by jviotti** [comment]
@sparty02 I believe the Cask is maintained by contributors. Anyone can send a PR to the Cask Formulas though

**Comment by ngohungphuc** [comment]
When do you guys intend to update this on [web](https://www.postman.com/downloads/) ?

**Comment by numaanashraf** [comment]
> When do you guys intend to update this on web ?

@ngohungphuc We are working on that and it should be up on our downloads page when Postman v9 hits general availability (tentatively by the end of this month)

**Comment by craigz** [comment]
first of all, cheers on the release, i'm stoked to have a native version to run, although i have to say the canary app has been very stable in my case, but it's nice to be on v9 and for the moment feel slightly ahead of the curve ;)

an issue i've just run into is that when running the new application none of my saved `current values` are available.
it's as if i am working with a shared collection; i have the placeholder values, rather than the saved values.

i've just confirmed the postman canary app i've been running on the M1 for some time now continues to have it's saved values, um, saved.

i've reviewed this document: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/ 

the best i can figure is that collections can be imported, but i see no way to export/import a workspace. 

meanwhile, i tested a single collection and after bringing it in as a copy, my variables are in the same state, as in the `current values` are all placeholders.  in the canary app those are actual data points (api keys, etc).

is there a way to bring the workspaces over to the new application without manually re-entering all `current values`?

**Comment by dalisoft** [comment]
@twitharshil I trying add Apple Silicon version to Homebrew ([PR](https://github.com/Homebrew/homebrew-cask/pull/113012)), but seems versions are different. Please can you're update release for Apple Silicon too?

Thank you

**Comment by fishcharlie** [comment]
Is https://dl.pstmn.io/download/version/9.0.7/osx_arm64 that @twitharshil linked a stable version? When going to https://www.postman.com/downloads/?utm_source=postman-home it downloads a 8.12.5 version that isn't Apple Silicon native.

**Comment by thedocbwarren** [comment]
It can be updated as well to latest.  Brew needs an update but this is the latest.

**Comment by Olegt0rr** [comment]
https://www.postman.com/downloads/ - still no M1 version available to download :(

**Comment by anangkur** [comment]
try to download from this link, it works fine in my Mac Mini M1
https://dl.pstmn.io/download/version/9.1.4/osx_arm64

edit: change the version with the latest version available

**Comment by DavidGarciaCat** [comment]
I think what Olegt0rr tried to say is the website is not up to date.
Anyone following this thread already got the link to download the M1 version.

**Comment by kpuscas** [comment]
So just downloaded the osx_arm64 (v 9.1.4) on a new MBPro 14 and it won't open any of my requests.  The web version isn't an ideal option so any idea what could be going on?

**Comment by samparmenter** [comment]
@kpuscas I've got the same version installed on a 14" MBP and have no issues. What do you mean it won't open any of your requests? Is in they can't be sent or they won't even open in the UI.

**Comment by kpuscas** [comment]
@samparmenter It's the UI pane that shows the requests. I try to open an existing request from a collection and nothing happens. If I click the plus to create a new request nothing happens. In the pane itself is just the logo with a link that says Open Overview however clicking that does nothing as well. 

![image](https://user-images.githubusercontent.com/10567035/142273223-b5da69ed-bf33-49f4-84fd-4f07827d3d2d.png)

**Comment by idevchandra** [comment]
> It's the UI pane that shows the requests. I try to open an existing request from a collection and nothing happens. If I click the plus to create a new request nothing happens. In the pane itself is just the logo with a link that says Open Overview however clicking that does nothing as well.

I have the same issue.

**Comment by idevchandra** [comment]
> I've got the same version installed on a 14" MBP and have no issues. What do you mean it won't open any of your requests? Is in they can't be sent or they won't even open in the UI.

I have the same issue. On the left bar, when I click on any POST, GET or any request, it has to appear on the right side. But it does not.

Screenshot with explanation is here -> https://imgur.com/a/qODn4Gn

**Comment by twitharshil** [comment]
@idevchandra Could you file it as a separate issue that you are facing?

**Comment by twitharshil** [comment]
Hey Everyone, 

M1 builds for the postman application are now available for direct downloads via postman website download [page](https://www.postman.com/downloads/).

**Comment by kpuscas** [comment]
Hi Harshil,

Just downloaded the new build and still seeing the same issue.

**Comment by Olegt0rr** [comment]
@kpuscas, 
<img width="557" alt="Screenshot 2021-11-23 at 19 10 49" src="https://user-images.githubusercontent.com/25399456/143061237-525d0f3b-f12e-4f13-a0aa-2eaaf8465231.png">

<img width="412" alt="Screenshot 2021-11-23 at 19 11 29" src="https://user-images.githubusercontent.com/25399456/143061252-0feaf7f2-fe46-4328-a296-26a49f463ad9.png">

**Comment by kpuscas** [comment]
It's the M1 version.
[image: image.png]

Running on Montery
[image: image.png]


Now one of my developers is running it just fine on a M1 MBP 13in under Big
Sur if that helps.

**Comment by fishcharlie** [comment]
> Hey Everyone, 
> 
> 
> 
> M1 builds for the postman application are now available for direct downloads via postman website download [page](https://www.postman.com/downloads/). 

@twitharshil Getting an error when trying to open that page.

![image](https://user-images.githubusercontent.com/860375/143067814-9c124df8-fb9f-4b79-9e35-82fd88097ca2.jpeg)

**Comment by tkuenster** [comment]
I upgraded my laptop to a new mb pro arm with 64gb mem - I'm seeing a strange issue - no resources will open. I can see requests, etc in the left panel, but "new" anything or trying to open an existing resource doesn't do anything. Nothing in the logs either. Just curious if anyone has any suggestions to mitigate.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/19959144/143665714-5681f5d8-fdcb-42ca-a649-03abc2685cdf.png">

**Comment by twitharshil** [comment]
We have received a few reports for apple silicon builds not being actionable on M1 pro & M1 max hardware, we are looking into the issue. To help us out triaging the issue faster and to share additional information, pls use this [thread](https://github.com/postmanlabs/postman-app-support/issues/10460)
