### ISSUE TITLE
Global Variable 'Current Value' should be using the 'Initial Value' when it's 'Current Value' is empty

### ISSUE THREAD

**Issue by PureKrome** [a85/POSTMan-Chrome-Extension#9348]
### Issue

When creating a new global variable:
- `Initial Value` is set
- `Current Value` is left empty/not set

then when I try and use this variable, the *empty* value of `Current Value` is used, instead of the `Initial Value` (which I assume would be copied to the `Current Value` as described in the tooltip/docs.

![image](https://user-images.githubusercontent.com/899878/101467109-0499d480-3996-11eb-9acd-1b857c8adff3.png)

![image](https://user-images.githubusercontent.com/899878/101467206-21cea300-3996-11eb-8367-539e74bafe2c.png)

![image](https://user-images.githubusercontent.com/899878/101467437-6ce8b600-3996-11eb-8cc0-4f5e22e5e791.png)

### Expectation

When creating a Global Variable:
- Set `Initial Value` to something
- Leave `Current Value` empty / not set

and then the value of this Global Variable (when used) should be the `Initial Value`.

### Steps to Reproduce

- Click `Environment Quick Look`
- Click `Globals` -> Edit
- Add a new (global) variable
- Create a new Request
- Use that variable name in the request 

### Environment Information

 - Platform Type: Native Desktop App
 - Postman Version: Postman v7.36.0
 - Operating System: Windows 10

Cheers!

**Comment by DannyDainton** [comment]
I'm unable to recreate this issue in the latest version of the platform.

If you're still facing this issue, could you add a short recording of the problem you see? 

Closing this one out for now.
