### ISSUE TITLE
Data import fails on Packaged App 1.0.9

### ISSUE THREAD

**Issue by jotb** [a85/POSTMan-Chrome-Extension#935]
While trying to import a previously exported data dump I get the following error in the console:

Uncaught TypeError: Cannot read property 'replace' of undefinedrequester.min.js:2 Backbone.Collection.extend.escapeScriptrequester.min.js:2 (anonymous function)requester.min.js:9 h.onsuccess

The data is imported partially and I can even browse the collection but I cannot display the requests.

**Comment by abhijitkane** [comment]
We'll be pushing a fix in 1.0.10.

**Comment by jcachat** [comment]
I had this same issue and 1.0.10 has resolved it for me.  Thank you for the quick response!
