### ISSUE TITLE
Ability to disable cookies in requests by default

### ISSUE THREAD

**Issue by SabriH10** [a85/POSTMan-Chrome-Extension#9354]
At the moment, we enable [programmatic access to cookies](https://learning.postman.com/docs/sending-requests/cookies/#delete-all-the-cookies). We can also [disable runs with stored cookies in the collection runner](https://learning.postman.com/docs/running-collections/intro-to-collection-runs/#starting-a-collection-run). However, it would be nice if we could choose to disable the use of cookies in general as default.

-- Logged on behalf of a user --

**Comment by codenirvana** [comment]
There's a request level setting for that.
<img width="935" alt="Screenshot 2020-12-09 at 8 50 51 AM" src="https://user-images.githubusercontent.com/4865836/101570081-aef81300-39fb-11eb-88eb-dac986e5d59b.png">

**Comment by SabriH10** [comment]
@codenirvana Yup! The user was already aware of that, but they want to be able to disable it by default as opposed to the request level setting.

**Comment by ocroz** [comment]
Thanks for sharing the request setting.
However I still don't see where to disable cookies globally in [Postman desktop app](https://learning.postman.com/docs/getting-started/installation-and-updates/#installing-postman-on-windows).
Why is this issue closed when [it was requested](#issuecomment-741769181) to disable cookies by default as opposed to the request level setting ?
Also, if closed, where is this documented? The [doc](https://learning.postman.com/docs/sending-requests/cookies/) refers to the request setting only, not to the global settings.
