### ISSUE TITLE
Possible race? condition when setting global variables in pre-request script

### ISSUE THREAD

**Issue by cen1** [a85/POSTMan-Chrome-Extension#9355]
**Describe the Issue**

When setting globals in pre-request script, when executing requests **fast** one after another, globals are not updated.

**Steps to Reproduce**

Pre-request script example:
```
let j=postman.getGlobalVariable("xyz");
console.log(j);
if (j==null || j==NaN || j===undefined) {
    j=20000;
}
j++;
postman.setGlobalVariable("xyz", j);
```

Case 1 - execute request repeatedly, slowly (like at least a second between requests). Result: console prints counter increasing by 1. e.g. undefined, 20001, 20002...

Case 2: execute request rapidly and repeatedly (On Mac I do it cmd+enter). Result: every second or third request has the same counter value.

**Screenshots or Videos**

I can provide them if steps are not reproducible.

**Environment Information**

 - Platform Type: Postman App for Mac
 - Postman Version: 7.36.0
 - Operating System: Mac Os Mojave, 10.14.6

**Additional Context**

I am using a pre-request script to generate unique values for each request and since I am checking for duplicated on the backend I get a random 409 (conflict) error when testing "too fast". After doing some tests it appears that globals are not updated for whatever reason. If I execute requests slowly the problem disappears.

**Comment by falk0069** [comment]
I had the exact same problem but with the collectionVariables in the pre-request script.  After upgrading to v8.0.3, the problem went away.

**Comment by cen1** [comment]
> I had the exact same problem but with the collectionVariables in the pre-request script. After upgrading to v8.0.3, the problem went away.

I will give it a try. Fingers crossed.

**Comment by cen1** [comment]
Looks like something was indeed fixed in v8. No conflict errors today. Closing.
