### ISSUE TITLE
Disable cookies set by default

### ISSUE THREAD

**Issue by iamkarlson** [a85/POSTMan-Chrome-Extension#9357]
I don't know who was that genius who made this annoying function available to all users at once but it terribly bad. I mean that and only thing was giving me so many hard times. It would be super nice if you can make a feature toggle "add cookie jar" in the options which will set or remove this setting for ALL the requests at once. I'm using Postman for 5  years in a row and that particular thing only made me thinking to find alternatives. Some peer's opinions:

![image](https://user-images.githubusercontent.com/4534374/101629837-3c4e5e00-3a22-11eb-89b9-0c9cbb7a5438.png)
![image](https://user-images.githubusercontent.com/4534374/101630214-db735580-3a22-11eb-8b14-2aeeed41f599.png)

**Comment by iamkarlson** [comment]
Okay, I shared my pain to a few friends and they recommended me to use Insomnia. So probably it's a way to go. especially when Postman doesn't have unique features.

**Comment by mccannt** [comment]
@iamkarlson While we understand your frustration with this current implemented functionality, please be respectful to our teams and users. 

This is currently a Feature Request https://github.com/postmanlabs/postman-app-support/issues/9354 
Please go add a like or supportive comment to that as it will help us gauge the impact on our overall userbase and set priority appropriately.
