### ISSUE TITLE
Beautify in XML add blank line at start

### ISSUE THREAD

**Issue by kolonuk** [a85/POSTMan-Chrome-Extension#9358]
**Describe the Issue**

When using the "Beautify" option for an XML body where line 1 is blank creates an additional blank line.

Rinse and repeat to have more blank lines.

**Steps to Reproduce**

New request, enter sample XML, click "Beautify".

```
1.
2.<somexml>
3.    <element>test</element>
4.</somexml>
```

**Screenshots or Videos**

n/a

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: v7.36.0
 - Operating System: Windows 10 (latest)

**Additional Context**

n/a

**Comment by kolonuk** [comment]
I'd see this as a very low priority issue - XML interpreters should not care about white space outside of elements.

**Comment by DannyDainton** [comment]
I'm unable to recreate this issue in the latest version of the platform. Closing this out for now.
