### ISSUE TITLE
Couldn't upload file in Postman Web

### ISSUE THREAD

**Issue by TheBoneJarmer** [a85/POSTMan-Chrome-Extension#9361]
**Describe the Issue**

When I try to select a file for a POST multipart/form-data request I get an error notification in the bottom-right corner of my screen: _Couldn't upload file. Make sure that Postman can read files inside the working directory._ I run the postman agent on my Linux Mint 20.04 using the terminal. I extracted the tar somewhere on my filesystem and soft-linked the binary _Postman Agent_ to /usr/bin/postman-agent. Odd thing is, this **used** to work in a previous web version.

**Steps to Reproduce**

Kinda said it already, just make a blank POST multipart/form-data request and try to select a file using the button _select files_. No need to fill in an url for this to happen, or special headers or what not. But make sure you install the agent like I did, just extracting the tar somewhere and run it from the terminal.

**Environment Information**

 - Platform Type: web.postman.co/workspace/***
 - Postman Version: Idunno, the one currently active at that url?
 - Postman **Agent** Version: v0.2.4
 - Operating System: Linux Mint 20.04

**Terminal output**
```
1607552011494 main info "Booting PostmanAgent 0.2.4, linux-5.4.0-26-generic on x64"
1607552011503 main warn "Postman Agent~Main~populateInstallationId: Failed to get installationId from agentSettings but with no error"
1607552011510 main info "UpdateHandler~init - Success"
1607552011754 main info "WebsocketAgent~start - Listening on port",10533
LinuxAutoUpdater~Cleanup - Initial cleanup successful
```
**Additional info**
* I located a folder _~/Postman Agent/files_, could this be that working folder?
* I did not upload log files since there was just 1 file called _main.log_ which had exactly the same text as the terminal output above
* Tried running the agent binary using sudo, no difference

**Comment by praveendvd** [comment]
could you goto settings>General scroll down and  enable : allow reading file outside working directoy

**Comment by TheBoneJarmer** [comment]
Hi @praveendvd 

Thanks for the suggestion. Sadly I already tried that with no success. Figured it'd probably be something as small like that but alas..

**Comment by BrianLDev** [comment]
I'm running into the same issue.  Can't upload any files even though I checked the "allow reading files outside working directory" option.

**Comment by chenfeiyu132** [comment]
I ran into the issue as well and I fixed it by changing the name of the directory "Postman Agent" to "Postman" so the path satisfies the one that the working directory setting defaults to. But you still have to copy the files into the specified folder for the web upload to accept it.

**Comment by sanjay-murmu-au9** [comment]
HI I just sort out these problem...Make sure that you have downloaded the Postman. Than it will work....In my case this worked
"Couldn't upload file. Make sure that Postman can read files inside the working directory. "

**Comment by DannyDainton** [comment]
Hey @TheBoneJarmer 

I know it's been a while but is this still something that you're having issues with on the latest version of the platform and Postman Agent?

**Comment by TheBoneJarmer** [comment]
Hey @DannyDainton 

Honestly completely forgot all about this. Indeed, has been a while and I vaguely remember it again. Thanks for checking it out though. I appreciate it. :)

Anyhows, I have not used Postman for a while and I have no use case for it either so I cannot quickly test it I'm afraid. But please, do leave my issue open for the time being if possible. If it helps your organization, assign it to me. That way it wont be lost on my list either.

**Comment by DannyDainton** [comment]
Thanks for the response. 

As we don't have any current steps to recreate the problem, I'm going to close this out for now but we can reopen it if more information is posted by yourself or other users.

**Comment by Leuow95** [comment]
> I ran into the issue as well and I fixed it by changing the name of the directory "Postman Agent" to "Postman" so the path satisfies the one that the working directory setting defaults to. But you still have to copy the files into the specified folder for the web upload to accept it.

It worked to me. Thank you.

**Comment by NordSpirit4567** [comment]
Issue still presented

**Comment by JosePaniagua7** [comment]
I was encountering this issue using postman web client. The only thing I needed to do to solve it was changing my postman agent from "Desktop Agent" to "Cloud Agent". 

This configuration is close to the right-bottom corner. 

Hope someone finds this useful.

**Comment by thortiede** [comment]
I just ran into this issue with Desktop Agent version v0.4.16 on MacOS 14.0 with Apple Chip.
The Agent creates a folder named `Postman Agent` in the home directory.
The Web version of Postman is hardwired to using the folder `Postman`, though.

I created the folder ~/Postman and a subfolder named `files`.
Any file inside this folder can be used in requests on the web version.

I know this solution has been shared before, but the problem still persists. Maybe it helps to know that I replaced my older version of Postman (I don't recall the version unfortunately) with a newly downloaded one, instead of updating the existing one (as I didn't remember having the Desktop Agent already installed).

**Comment by rubybui** [comment]
I just ran to this issue today, cannot used with newest postman agent : allow reading file outside working directoy did not work, create a working directory did not work.

**Comment by sayedulkrm** [comment]
On my `ubuntu` got the same problem. Later  on `console(browser)`, i get that error

```
... others
{"errno":-2,"code":"ENOENT","syscall":"access","path":"/home/sayedul-karim/Postman/files"}

```

> The error message ENOENT (Error NO ENTry) indicates that the specified file or directory does not exist. In this case, the Postman Agent is looking for a file in /home/sayedul-karim/Postman/files, which it cannot find.

**And here is the solution**


**1) Ensure that the file you're trying to upload exists at the specified path `/home/your-name/Postman/files`.**

**If you didn't find the path then create. After `/home/put-your-user-name`. In my case `(Linux)`**

```
mkdir -p /home/sayedul-karim/Postman/files
```
Then restart the `Agent`

And it did work.

**Comment by leniel** [comment]
If you're on Windows, rename the folder  **Postman Agent**  located on Users\YourUserName  to just **Postman** like in the following screenshot. After doing this the file selection is finally enabled.

<img width="589" alt="image" src="https://github.com/user-attachments/assets/a41b72f4-4980-4335-a5bb-60d64b8a5b17">
<br><br>
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/d0b109f4-4a20-4a0a-94b9-73738f703df1">
