### ISSUE TITLE
Software installation error

### ISSUE THREAD

**Issue by chenxu2011** [a85/POSTMan-Chrome-Extension#9366]
![image](https://user-images.githubusercontent.com/23093140/101871012-bc5cfb00-3bbd-11eb-9210-6cffd5f649ae.png)

2020-12-11 14:32:26> Unhandled exception: System.IO.FileNotFoundException: 未能加载文件或程序集“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”或它的某一个依赖项。系统找不到指定的文件。
文件名:“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”
   在 Squirrel.Update.Program.executeCommandLine(String[] args)
   在 Squirrel.Update.Program.main(String[] args)

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by Raj-postman** [comment]
Hi @chenxu2011 - Could you check [this comment here](https://github.com/postmanlabs/postman-app-support/issues/5681#issuecomment-601673575) and see if the steps help you get around this issue?

**Comment by chenxu2011** [comment]
@Raj-postman 
I can't solve my problem here

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/7842
