### ISSUE TITLE
Collection ReadMe - to help team know how to implement complex Collections

### ISSUE THREAD

**Issue by inland-rob** [a85/POSTMan-Chrome-Extension#9368]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my team keeps asking me to provide support on how to run a collection (when we're in dev mode, before publishing)

**Describe the solution you'd like**
I want to be able to publish a readme plain text file in a collection where I can describe how to run the collection when there are multiple, non-obvious steps. For example, step 1 may be to clean the database of old records. That is not a Postman capability, so the readme would contain those details.

**Describe alternatives you've considered**
Separate readme that is not with the Collection in Postman.

**Additional context**
None, you get the idea...

**Comment by sony-mathew** [comment]
Hey @inland-rob , We support overview for collections now. So when someone lands on a collection, they get the overview page where you can describe all sorts of information for the particular collection, like what is this collection for, how do you run this collection, how does error handling work, what are the authorisation methods this collection supports or how to get auth token, what are the certain steps that you need to do before running this collection etc.

I'm taking an example from a public collection [here](https://www.postman.com/TwitterAdsAPI/workspace/twitter-ads-api-s-public-workspace/collection/7379786-16f91dc4-d94d-439c-9687-6cd4a7ad1788):

<img width="1508" alt="Screenshot 2024-05-13 at 7 07 51 PM" src="https://github.com/postmanlabs/postman-app-support/assets/2040199/31a300f5-13b4-47b0-99ae-b850a28389ce">

Closing this issue as this address the problem you described. Feel free to reopen if you have any concerns.
