### ISSUE TITLE
Postman Mock Server configure response delay time per request

### ISSUE THREAD

**Issue by mrsGehred** [a85/POSTMan-Chrome-Extension#9369]
When I attempt to test error handling in my application, I would like a way to easily setup a request that takes a set amount of time to return. That way I can validate my retry logic in my application.

I would like to have an option in the example to take a query parameter from the request and use that variable to be the number of seconds before the postman mock server waits to respond. Example {{postmanmockserverurl}}/my/route?delayseconds=60, the "60" would populate a variable that could be used to set the delay for the particular response.

**Comment by vvs11** [comment]
@mrsGehred We support a delay in mock servers but it is at the mock level. You can edit the mock server and set a delay that you want and it will be applied to all the requests in the mock server. 
Please try that out and let us know your feedback. We will keep this feature request open to track this request

**Comment by mrsGehred** [comment]
I see that you support it at the mock level, however that is not sufficient
for our needs, you see for example using Auth0, we want to get the auth
token "quickly" and delay the next request to our server. Or vice versa to
insure we are handling client side time outs in an appropriate manner.

So in my opinion, and for our use case it would be excellent if we could
get a request, run some sort of "code" i.e. JavaScript set some variable
that would control the amount of time that "response" would wait for.

Thank you for listening,

Bob

**Comment by akshaydeo** [comment]
👋 @mrsGehred We are currently working on a revamped version of mocks, which is releasing in Q2 2022 would address this feature request 🙇 cc @Dhembla

**Comment by PratikThorve** [comment]
@akshaydeo is this feature of adding delay to individual request rather than at mock server level available now ?

**Comment by Dhembla** [comment]
@PratikThorve Adding delay on a request has been removed from the scope of Q2 2022. I am sorry for the inconvenience caused to you. We will update the ticket as soon as we start working/enabling this feature for our users.

**Comment by PratikThorve** [comment]
@Dhembla Thank you :)

**Comment by Dhembla** [comment]
Hey @mrsGehred @PratikThorve,
Thanks for your patience. We have added support for a custom header `x-mock-response-delay`, which you can use to delay your responses from the mock server. This header can take a value between `0 to 180000ms`. Auto-complete is also enabled on this header in the Postman requestor window.

<img width="1440" alt="Screenshot 2022-11-07 at 10 55 47 AM" src="https://user-images.githubusercontent.com/75123575/200232862-bddbe416-b0ca-4849-b956-40171ba64dc2.png">

> If you use both mock level delay which can be configured via UI, and request level delay using header, the header level delay will take precedence, and you will get your response accordingly. 🙇
