### ISSUE TITLE
Unable to export a collection [header.key undefined]

### ISSUE THREAD

**Issue by amlwwalker** [a85/POSTMan-Chrome-Extension#9372]
**Describe the Issue**

When exporting a collection instead of it being exported I receive an error toast:
![image](https://user-images.githubusercontent.com/2920180/102333980-0f4ffd00-3f86-11eb-95d6-e4846b73116f.png)
![image](https://user-images.githubusercontent.com/2920180/102334628-cf3d4a00-3f86-11eb-8ef8-b660af03f062.png)

When I check the console I can see

```
postman-converters.js:524 Error while exporting an entity {id: "1b5599ff-7869-4526-bf76-4acc1a6440f2"} {type: "collection", inputVersion: "1.0.0", outputVersion: "2.1.0"} TypeError: Cannot read property 'replace' of undefined at vendor-shared.js:401825
```

When I check lin 401825 of vender-shared.js I can see 

```
        _.forEach(headerData, function (header) {
            if (_.startsWith(header.key, headersCommentPrefix) || (header.enabled === false)) {
                header.disabled = true;
                header.key = header.key.replace(headersCommentPrefix, '').trim();  // <--- this line
            }
```

My guess is that some header is not set or something, I can see all my environment variables are set however

> A high-level summary or description of the problem that you're facing.

It seems that when exporting a collection if a header is not correct it cannot export the collection. However there is little to know exactly what is causing the problem

**Steps to Reproduce**

To recreate it would either require understanding what causes a header to be underfined and then why this is occuring, and confirm it, or to have access to my specific collection as I am not sure what exactly causes that undefined

> A list of steps that can be followed to recreate the issue.

See above

**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 

See above

**Environment Information**

 - Platform Type: Native applications
 - Postman Version: 7.36.0
 - Operating System: Linux & OSX tested

**Comment by DannyDainton** [comment]
I'm unable to recreate this issue in the latest version of the platform. Closing out for now.
