### ISSUE TITLE
Student Programm Link 

### ISSUE THREAD

**Issue by joanashehaj01** [a85/POSTMan-Chrome-Extension#9373]
Hello, 

Hope everything is ok.

I saw that in the footer menu  on Student Programm, the protocol is not in the right way. 
The url is (hhttps://www.postman.com/company/student-program/).
Attached are some illustration photo. 

Thank you,
Joana

![Student Menu](https://user-images.githubusercontent.com/61551357/102483294-cd49b880-4064-11eb-9c2c-a35f964519c2.png)
![Student Program Url Bug](https://user-images.githubusercontent.com/61551357/102483296-cde24f00-4064-11eb-9e52-3ae8cae490fc.png)

**Comment by DannyDainton** [comment]
Hey @joanashehaj01 

You have an extra `h` at the start of the URL. I've checked the link on the site and it looks fine from here.

![image](https://user-images.githubusercontent.com/17089546/102484634-750fb800-405e-11eb-8845-d559cc7d3e78.png)

Could check this again or make a quick recording of what you're seeing so we can check where that's going, please?

**Comment by ch264** [comment]
@DannyDainton I found the link on learning.postman.com. Will move this ticket to the correct Github

**Comment by ch264** [comment]
https://github.com/postmanlabs/postman-docs/issues/2756

**Comment by DannyDainton** [comment]
@ch264 

Ah I see it now...I was thrown by the URL not having learning.postman.com in it 😬

**Comment by joanashehaj01** [comment]
> 
> 
> Hey @joanashehaj01
> 
> You have an extra `h` at the start of the URL. I've checked the link on the site and it looks fine from here.
> 
> ![image](https://user-images.githubusercontent.com/17089546/102484634-750fb800-405e-11eb-8845-d559cc7d3e78.png)
> 
> Could check this again or make a quick recording of what you're seeing so we can check where that's going, please?


@DannyDainton This url is on the postman site, I know that the problem is the 'h' but this is a mistake from the postman not from my side.

**Comment by DannyDainton** [comment]
As you didn't mention the actual page that you were on, I was looking at the footer on `https://www.postman.com/` and not `https://learning.postman.com/` these are 2 different sites. :D 

The Issue https://github.com/postmanlabs/postman-docs/issues/2756 has now been fixed.

**Comment by joanashehaj01** [comment]
> 
> 
> As you didn't mention the actual page that you were on, I was looking at the footer on `https://www.postman.com/` and not `https://learning.postman.com/` these are 2 different sites. :D
> 
> The Issue [postmanlabs/postman-docs#2756](https://github.com/postmanlabs/postman-docs/issues/2756) has now been fixed.

@DannyDainton  yes I saw, thank you by the way. :)
