### ISSUE TITLE
Remove IDs from the GET collection endpoint

### ISSUE THREAD

**Issue by arlemi** [a85/POSTMan-Chrome-Extension#9375]
Reporting on behalf of @lbenedetto, following #2906.

**Is your feature request related to a problem? Please describe.**

Workflow:
A bunch of tests are stored in Postman. When adding a test, create a fork, and export the fork to the json in your Git branch. Push the changes for review (along side your actual code changes). When accepted, merge the postman fork, and then merge your git branch. During our jenkins builds, we run the json file with newman.

Is how we would like it to go. But to avoid polluting our git history, we have to do a second fetch from the main collection after we merge our postman fork to get a version of the json where the IDs are the same, and then squash and force push that to our git branch before merging.

Export to json is done with
curl -s -H "X-Api-Key: ${POSTMAN_API_KEY}" https://api.getpostman.com/collections/${COLLECTION_ID} | docker-compose run --rm jq . -M > $COLLECTION_FILE

**Describe the solution you'd like**
While exporting from the menu now strips the IDs, using the API to get a collection still has the IDs. Ideally there would be an option to get an export without IDs through another API endpoint, or the GET collection endpoint should not show the IDs by default.

**Describe alternatives you've considered**
Some parsing on the exported json file.

**Additional context**
More context in #2906

**Comment by mojo2012** [comment]
The ids are not exported anymore (except for the top level postman id field. But unfortunately the `status` and `code` fields are still there. This seems to me like internal postman "runtime data" and should not be included in the export (as it adds no value and makes it harder to diff the file).

**Comment by davidespihernandez** [comment]
Closing this, as it seems nothing else needs to be done. @arlemi feel free to reopen with more context if you need something else.
