### ISSUE TITLE
Hello,how to send the pm.info.requestId by pm.sendRequest?

### ISSUE THREAD

**Issue by tester-xm** [a85/POSTMan-Chrome-Extension#9383]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
@tester-xm we use GitHub to track user issues and new requests. The "How to" questions are more suited for Postman Community - https://community.postman.com/.Feel free to start a discussion over there for the same. 

Closing this for now, feel free reopen it if you have more details on the bug or new request
