### ISSUE TITLE
Airtable Integration

### ISSUE THREAD

**Issue by s3audi** [a85/POSTMan-Chrome-Extension#9384]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?
Connect STATIC HTML Pages with Airtable data!
And also you can use static html pages like dynamic pages. Also speed is advantage!

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by jotsarup** [comment]
@s3audi Can you please elaborate on the integration you are looking for?

**Comment by shashankawasthi88** [comment]
@s3audi gentle reminder. Can you fill out the other parts of the request template as well ? It helps us define the Integration better for the users.

**Comment by s3audi** [comment]
Thank you for your reply.
I want to use Airtable as database for static websites
There is an option named Airpress that works on wordpress but it is more complicate
Think about an HTML website, maybe hosted on Github.com, but all the contents can be edited by Airtable
It will be so good to have an option :)

**Comment by abhijitkane** [comment]
@s3audi This isn't something that fits in with our roadmap. Something like Airpress would be your best bet.
