### ISSUE TITLE
Badge for Body tab

### ISSUE THREAD

**Issue by MaRmARk0** [a85/POSTMan-Chrome-Extension#9386]
**Is your feature request related to a problem? Please describe.**
Yes. During development of my own API service on localhost I use Postman to test every endpoint. Sometimes I need to switch between GET/POST/DELETE/PUT rapidly and I always forget to unselect `x-www-form-urlencoded` within **Body** tab and select `none`.

If I write my own Headers, theres is also a green number informing me about the count of headers. It's neat because I known that _there are some headers present_.
![headers-image](https://imgur.com/UXm5mRi.png)

**Describe the solution you'd like**
If only there could be some small label/badge that informs the user that _there is something selected within Body tab_.
![](https://imgur.com/7KJuCQz.png)

Tab title suggestions based od what's selected inside it:
- **Body**
- **Body** (fd)
- **Body** (xw) 
- **Body** (r)
- **Body** (b)
- **Body** (gql)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by giridharvc7** [comment]
This is now available in app v8 and web version of Postman
![Screenshot 2021-04-14 at 12 53 50 PM](https://user-images.githubusercontent.com/1040583/114670307-7b6a2400-9d20-11eb-99d0-f8968c813df6.png)
