### ISSUE TITLE
Request that before worked now stuck on sending request

### ISSUE THREAD

**Issue by kuriel-trivu** [a85/POSTMan-Chrome-Extension#9388]
this error occurs on a fresh install with Mac 11 and Postman, both are fresh, Postman throws this errors:

![image](https://user-images.githubusercontent.com/46456105/103236962-e4fa2a00-490b-11eb-8146-dae10af2f6ee.png)

Postman V7.36.1

**Comment by kuriel-trivu** [comment]
This error is thrown with Postman Web:

![image](https://user-images.githubusercontent.com/46456105/103242472-e59abc80-491b-11eb-8f26-03f310ff261d.png)

**Comment by jviotti** [comment]
Based on the logs, the error seems to be throws when connecting to a server running on localhost. That local service was then killed and therefore was refusing further requests. 

I'll close this as it doesn't seem to be a problem with Postman, but rather with the localhost HTTP server you are sending the requests to. Please re-open if not!
