### ISSUE TITLE
cURL import: '\n' not behaving as intended

### ISSUE THREAD

**Issue by a2br** [a85/POSTMan-Chrome-Extension#9391]
## **Describe the Issue**

When importing a request as cURL, if the body is `x-www-formencoded` and contains one or more `\n`, it will be transformed into `n`, making the data invalid. In `\n`, only `\` is deleted, but `n` stays.

## **Steps to Reproduce**

- Copy a request with a form-encoded body as cURL (bash)
- Import it in Postman (Import -> Raw text -> Paste)
- Read the imported body
- Some `n`s, remaining from `\n`, are in the body

### **More precisely:**

- Import the following  as raw text:
```curl
curl 'https://api.secretdomain.com/v3/login.awp' \
  -H 'authority: api.secretdomain.com' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'origin: https://www.secretdomain.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.secretdomain.com/' \
  -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-raw $'data={\n    "username": "someValue",\n    "password": "somethingSecret",\n    "token": "secret-token"\n}' \
  --compressed
```
- Open the body tab.
- In front of the `data` key, the value contains parasite `n`s. The data, that should be parsed into JSON, is now invalid.

## **Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Postman for Windows / Version 7.36.1 / win32 10.0.18363 / x64
 - Operating System: Windows 10 Pro

**Comment by raghumurthy-jayandran** [comment]
@a2br We have fixed this issue in the latest version of the postman app. Please try this out and share your feedback.
