### ISSUE TITLE
digital ocean api

### ISSUE THREAD

**Issue by dmbe11** [a85/POSTMan-Chrome-Extension#9392]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
@dmbe11 can you please add more details to the request? Filling out the template would give us an understanding of your workflows and what you are trying to achieve with this Integration.

**Comment by shashankawasthi88** [comment]
Closing this for the lack of details. @dmbe11 please feel free to reopen with additional details on the Integration
