### ISSUE TITLE
New Integration Request - <Rest Client>

### ISSUE THREAD

**Issue by sreelekha3399** [a85/POSTMan-Chrome-Extension#9394]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
@sreelekha3399 can you please add more details to this request. FIlling out each component of the template will help us understand your request better.

**Comment by shashankawasthi88** [comment]
Closing this for lack of details.
