### ISSUE TITLE
Feature Request - to import Newman results into Postman Runner

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#9401]
**Is your feature request related to a problem? Please describe.**
Unable to import Run results from Newman into Postman.

**Describe the solution you'd like**
Be able to import the exported json summary results from Newman into Postman Runner using the "Import Runs" feature.

**Describe alternatives you've considered**
At the moment we use reporters to view and send run results to other users.

**Additional context**
_Filed by Product Support_

**Comment by jotsarup** [comment]
@Raj-postman This is great. Do you happen to have more details around this. What is the use case users want to solve?

**Comment by Raj-postman** [comment]
Hi @jotsarup User wanted to perform this action as mentioned on our Docs and I have now raised for a correction [here](https://github.com/postmanlabs/postman-docs/issues/2778)  :)

**Comment by malvikach** [comment]
You can use Postman CLI, that we recently launched as part of Postman v10 release, and directly get your results into Postman. You can check out this blog to know [how](https://blog.postman.com/introducing-the-postman-cli-to-automate-your-api-testing/).
