### ISSUE TITLE
How to disable shared history?

### ISSUE THREAD

**Issue by Aditya94A** [a85/POSTMan-Chrome-Extension#9402]
The constant pop-ups about shared history limits are a bit annoying considering I don't really care about sharing history in the first place.

Any way to disable this?

**Comment by DannyDainton** [comment]
Hey @AdityaAnand1

Could you provide some more context, please?

- Are you using the Web or Desktop App? 
- Are you using Team Workspaces?
- Are you the only member of the Team? 
- Have you been making requests in those Workspaces to activate the history limits? 
- If you clear the History from the Team Workspaces, does that remove the banner?

**Comment by Aditya94A** [comment]
* Behavior on web/desktop both is the same
* Yes, team workspace (free right now)
* Two members in the team
* Yes, making the requests in the workspace
* Yes, clearing the history removes the banner (but doing that every few seconds is annoying and feels like a dark pattern nudge to pay up)

![image](https://user-images.githubusercontent.com/13274079/103750957-8cbed880-502d-11eb-9dd3-5b4a4bc805d6.png)

**Comment by DannyDainton** [comment]
Hey @AdityaAnand1 

Thanks for the additional information.

A dark pattern would suggest that we're trying to "trick" users into something, which is not the case here, our usage levels for items shared in **Team** Workspaces are displayed in a number of different areas for users to know exactly what the current state is in their accounts. The image you post gives you the opportunity to see this by selecting the `Check usage` option.

You can also see your current usage stats but using the dropdown in the top right of the app.

![Screenshot 2021-01-06 at 10 20 48](https://user-images.githubusercontent.com/17089546/103758727-81a68100-500a-11eb-8ac8-c4d785565cb6.png)

More information about the Usage Limits can be found here:

https://learning.postman.com/docs/collaborating-in-postman/collaboration-intro/#usage-limit

**Comment by Aditya94A** [comment]
Is there any way to disable sharing history?

**Comment by DannyDainton** [comment]
If you are using Team Workspaces and are sharing items and making requests within them, the limits will apply and you will see the notifications if you've created a Free Team. Upgrading to the Team licence would remove the limits but you wouldn't be able to 'disable' anything and make everything unlimited as a Free Team user.

You can work within Personal Workspaces, make requests and share items between those and not impact the usage limits. 

Creating a Public Workspace that others can join would also remove those limits but of course, that would be public and anyone could see your items shared in there.

**Comment by DannyDainton** [comment]
@AdityaAnand1 I'm going to close this issue out for now - Feel free to open up a thread in our Community Forum for any more questions that you may have regarding the sharing limits.

https://community.postman.com/
