### ISSUE TITLE
Generating test suites from OpenAPI 3.0 schema results in schema validation errors due to random numbers

### ISSUE THREAD

**Issue by taehoshino** [a85/POSTMan-Chrome-Extension#9404]
**Describe the Issue**

Generating test suites from OpenAPI 3.0 schema results in schema validation errors due to random numbers being appended to path variables. 

**Steps to Reproduce**
- Import OpenAPI 3.0 schema (JSON format) to create a new API
- Create test suites - In advanced settings, select `Example` for both `Request parameter generation` and `Response parameter generation`. 
- Test fails due to some random values are appended to path variables.

**Screenshots or Videos**
![test_results](https://user-images.githubusercontent.com/55820883/103827971-3a81c400-50ce-11eb-91ad-212779c6b716.png)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 7.36.1
 - Operating System: OS X 20.2.0 / x64

**Additional notes**
* Logging at GitHub public tracker on behalf of a user after an internal escalation discovered this issue

**Comment by mccannt** [comment]
This should now be resolved.
