### ISSUE TITLE
Postman web app: duplicating a request creates invisible request

### ISSUE THREAD

**Issue by jim-obrien-orig** [a85/POSTMan-Chrome-Extension#9405]
**Describe the Issue**

Duplicating a request by clicking "..." and "Duplicate", creates a duplicate request that instantly becomes invisible. However, if you export the collection, the request will be in the json at the bottom.

**Steps to Reproduce**

Click on "..." next to a request, and choose "Duplicate"

**Screenshots or Videos**

**Environment Information**

 - Platform Type: Postman on the Web
 - Postman Version: not sure how to find version on the web
 - Operating System: Mac 11.0.1
 - Browser: Brave Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) (x86_64) - brave shields disabled

**Additional Context**

**Comment by giridharvc7** [comment]
We've made some improvements to this flow. Please let us know if you still face this issue. 
Closing this ticket for now
