### ISSUE TITLE
postman crashes when sending a file which doesn't have access to

### ISSUE THREAD

**Issue by sinamna** [a85/POSTMan-Chrome-Extension#9407]
**Describe the Issue**
postman crashes when i try to send a sudo-created file (for example text) in multipart/form-data post request

**Steps to Reproduce**
create a text file with `sudo touch test.txt`
send created file in form-data body with post request 

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Postman v7.36.1
 - Operating System: Ubuntu 20.04.1 LTS

**Comment by rafiahmad16** [comment]
Same issue with me. I used snap to install postman:7.36.5 it hangs a lot in ubuntu20.04

**Comment by dev-sharma-08** [comment]
Hi @sinamna 
I know that it's been a while but is this still an issue for you? If not, can we close this issue out?

**Comment by apoorvgupta03** [comment]
Hey all, since its working fine currently, we are closing this issue for now, please feel free to reopen this and provide more details. You can also update the app for our latest improvements.
