### ISSUE TITLE
OAuth 2.0 with PKCE still requires client secret

### ISSUE THREAD

**Issue by damithsj** [a85/POSTMan-Chrome-Extension#9409]
I'm trying to get an access token with PKCE flow and it still requires client secret.
According to PKCE protocol flow, client should use the code_verifier instead of client secret.

[https://tools.ietf.org/html/rfc7636](https://tools.ietf.org/html/rfc7636)

How to recreate:
In the Auth tab, select OAuth 2.0 from dropdown.
In the Configure token section, select Authorization Code (with PKCE) 
Notice you'd still need to provide the client secret

![2021-01-08 08_55_17-Postman](https://user-images.githubusercontent.com/8566532/103989588-36b67600-5190-11eb-9ada-d7542a3dba4e.png)
**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version:  Postman v7.36.1
 - Operating System: Windows 10 Enterprise

**Comment by MariaCobretti** [comment]
I have been wondering for an hour if I was understanding something wrong with the Authorization Code PKCE flow before I found this post.. So it is not supposed to need a client secret

**Comment by jngibert** [comment]
Agreed. Use of the Authorization Code with PKCE Flow should never requiring use of the client secret.
But if the client secret is left blank in the Postman UI, then Postman is sending client_secret = "" (an empty string) which causes the last step of the flow (exchanging the code for a token) to fail.
It's been over a month since this was reported as a bug; any ETA for resolution?

**Comment by jmereaux** [comment]
Same issue here. Any news on the subject please ? Is this bug going to be fixed soon ?
Thanks.

**Comment by jeanrp** [comment]
Any update?

**Comment by giridharvc7** [comment]
> But if the client secret is left blank in the Postman UI, then Postman is sending client_secret = "" (an empty string) which causes the last step of the flow (exchanging the code for a token) to fail.
It's been over a month since this was reported as a bug; any ETA for resolution?

With that, PKCE flows should work as expected with empty client-secret. This is fixed in Postman v8.9 on the app. You can also check out the web app.

Keeping this issue open so that we can remove the `client secret` field from the OAuth2 for PKCE flows.

**Comment by rusticdeity** [comment]
@giridharvc7 I am using postman desktop app version v8.11.0 but I still face the same issue. Would you please confirm if this issue is resolved in v8.11.0

**Comment by zinsserzh** [comment]
I suggest adding a new option `None (e.g. for PKCE)` under the `Client Authentication` dropdown. When PKCE flow is selected, this option will be used by default, and the `Client Secret` field is hidden.

**Comment by giridharvc7** [comment]
> @giridharvc7 I am using postman desktop app version v8.11.0 but I still face the same issue. Would you please confirm if this issue is resolved in v8.11.0

@rusticdeity 
Can you confirm if Postman sends `client_secret = ""` ?

**Comment by zinsserzh** [comment]
I am using v8.12.0 and I see postman sending `client_secret = ""`
<details>
  <summary>Screen Shots</summary>

![image](https://user-images.githubusercontent.com/6081431/131883415-f1782bf1-9f4c-493e-8f19-e40c638468e3.png)
![image](https://user-images.githubusercontent.com/6081431/131883610-81321b22-2175-4edb-8d80-77314af8ca30.png)
</details>

**Comment by rusticdeity** [comment]
> > @giridharvc7 I am using postman desktop app version v8.11.0 but I still face the same issue. Would you please confirm if this issue is resolved in v8.11.0
> 
> @rusticdeity
> Can you confirm if Postman sends `client_secret = ""` ?

@giridharvc7 there is no client_secret being sent in the request. I can only see `grant_type`,`code`, `redirect_uri`,`code_verifier`, ,`client_id `in the console for both successful and failed requests.

**Comment by giridharvc7** [comment]
@zinsserzh Can you try this in the Web app? It should work fine there. We will see why this happens on the Desktop app and fix it.

**Comment by brockwmills** [comment]
Can removing the client secret be made optional? There are use cases where PKCE can be used by private clients. I think the easiest fix here when PKCE is selected, there's a check box for including the client secret in the call for the token

**Comment by giridharvc7** [comment]
@stringy05 you can leave `client_secret` blank and we wont add this as a key to the OAuth request

**Comment by cgontario** [comment]
This isn't fixed for me on the desktop client as of v9.3.1. Leaving the Client Secret field blank when using Authorization Code (With PKCE) results in the following error in the console:

Error: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

Edit: For anyone else that made the same mistake I did in their Azure AD App Registration: you need to place the Postman Reply URIs under the Desktop/Mobile platform, not the Web platform. Web clients are assumed to be private. We want to treat Postman as a public client, so it's Redirect URIs need to appear under Desktop/Mobile.

**Comment by Grant-Lay** [comment]
Is this going to get fixed on the desktop client?  Or if I want to use the web app, how do I set the callback URL to localhost (it's not giving me the option to change the value from https://oauth.pstmn.io/v1/browser-callback)?

**Comment by abhijeetborole** [comment]
Hey! We updated the OAuth2.0 PKCE flow to no longer send a `client_secret` when it is left empty. @stringy05 @cgontario Could you verify if this fixes the issue for you on `v9.8`? Do let us know if you face any other issues.

**Comment by cgontario** [comment]
Thanks for updating us, @abhijeetborole :) I just tested this with v9.8.2 and confirmed that client_secret isn't be included in the request body when POSTing to https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/token endpoint. I was able to authenticate using Authentication Code with PKCE by leaving the Client Secret field blank.

**Comment by folbo** [comment]
Just noticed this bug returned in v9.14.0. Can anyone reopen this?
![image](https://user-images.githubusercontent.com/7533717/157697042-906da64d-c226-4725-89a2-1a55cce77d84.png)

**Comment by abhijeetborole** [comment]
@folbo Thanks for reporting the issue. Could you please share the steps you're taking/a dummy configuration which would help us reproduce the issue on our end? Could you also share the console logs as it would help us identify the issue.

**Comment by moschenkovpropellerads** [comment]
@abhijeetborole confirm the issue
Even if "Client Verifier" is blank
<img width="595" alt="Screenshot 2022-03-24 at 18 31 39" src="https://user-images.githubusercontent.com/89989197/159953139-c5aedd96-e6bf-4723-be2c-bd2c57e517df.png">
<img width="359" alt="Screenshot 2022-03-24 at 18 28 57" src="https://user-images.githubusercontent.com/89989197/159953182-fec2a9fe-3f84-40fd-9bb6-aa5c9d83555d.png">

**Comment by giridharvc7** [comment]
@moschenkovpropellerads we will track this as a feature request on top of Oauth2.0 

We are rethinking ho we are approaching OAuth into a fully customizable one so that these edges that might not be covered in the original OAuth RFC will be covered.

**Comment by cgontario** [comment]
Any updates on fixing this regression? It's preventing us from using Postman with all of our Azure AD-protected APIs and, more critically with Microsoft Graph API. We've settled on Auth Code with PKCE and Delegated permissions (so no Client Secrets) and I don't see that changing, so we're in a bit of a bind; may need to look for alternatives to Postman and that's not ideal given how prolific it is. Much easier if we can keep everyone using the tool they know and love.

**Comment by williamdphillips** [comment]
@cgontario I'm with you - this issue makes using Postman with Azure AD APIs utilizing Auth Code with PKCE a non-plausible solution. 

@giridharvc7 Would a temporary small fix be probable in the meantime? I'm all for an overhaul on the current approach, but it seems some of Postman's users are being left out with no solution at the moment.

**Comment by mholttech** [comment]
I'm also running into this same issue. Would love to be able to specify client_assertion

**Comment by cgontario** [comment]
@williamdphillips, I got the Postman desktop client (v9.24.2) working using Auth Code with PKCE and wanted to see if this works for you too:

1. Make sure that you have the desktop client's Redirect URI under "Mobile and desktop applications" in the App Registration's Authentication blade: https://oauth.pstmn.io/v1/callback:
![image](https://user-images.githubusercontent.com/72411622/179231898-defb1c30-a166-4453-9700-11a3fd1f6e5b.png)
3. Leave Client Secret empty in Postman. Just to be sure, here's what my Authorization settings look like:
![image](https://user-images.githubusercontent.com/72411622/179231402-51b5a8f2-822d-446a-b224-f4f07403d93c.png)

At some point I had moved the desktop client's Redirect URI to "Web" and this may have been my issue.

Hope you can get it working too :)

**Comment by giridharvc7** [comment]
@Grant-Lay This was fixed in an earlier version on the desktop app, please update to the latest version just in case. 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/1040583/201589472-64631a37-ad97-43d5-b813-a1f79fbc1266.png">

**Comment by giridharvc7** [comment]
@cgontario I'm assuming that you don't face this issue anymore. Was the fix just mentioning Postman's callback URL with the Auth provider?

**Comment by giridharvc7** [comment]
@mholttech can you expand your use case, Do you want to pass `client_assertion` with the token url?

**Comment by cgontario** [comment]
> @cgontario I'm assuming that you don't face this issue anymore. Was the fix just mentioning Postman's callback URL with the Auth provider?

I don't think that the Redirect URI is even required in my case now as I ended up switching the App Registration in question to a Public Client. But I haven't had any issues authenticating to Azure AD using a few different App Registrations, some configured as Public Clients and some as Confidential Clients (secret and Redirect URI required).

**Comment by giridharvc7** [comment]
@cgontario thank you for confirming. I will close this ticket in a few days as we don't send `client_secret` when set empty.

**Comment by giridharvc7** [comment]
Closing this issue. 
We will continue to show `client_secret` for `Authorization Code with PKCE`. 
When the `client_secret` is left blank, Postman will not be sending this key with the OAuth request. 

But there might be cases where the Auth server expects the `client_secret` or you simply want to test out your own servers with `client_secret`, can still pass values to `client_secret` to test these flows. For this reason, we are keeping the `client_secret`. 

Let us know if you face any concerns with this setup.

**Comment by DavithkbY** [comment]
Hi, in the latest desktop version it's still sending an empty client_secret="", in the browser version it is not.

**Comment by JaekwanLee** [comment]
Version 10.12.10

I am trying with PKCE flow for Docusign application. Everything is PKCE configuration and it sends code challenge correctly with right code_challenge method. However, it fails unless I feed a client_secret. So I looked at postman console to see if it sends client secret but it does not send it in any case. But the PKCE fails as soon as I remove client_secret from the configuration. so it is something do to with hidden stuff.

I am quite puzzled.

**Comment by DavithkbY** [comment]
Try with postman client. I had the same with AWS. The postman desktop app would always send a client secret in the header. This bug is fixed in de browser version. Maybe you have the same bug :)

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Jaekwan Lee ***@***.***>
Verzonden: Thursday, April 6, 2023 12:50:32 AM
Aan: postmanlabs/postman-app-support ***@***.***>
CC: Davit Hakobyan ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [postmanlabs/postman-app-support] OAuth 2.0 with PKCE still requires client secret (#9409)


Version 10.12.10

I am trying with PKCE flow for Docusign application. Everything is PKCE configuration and it sends code challenge correctly with right code_challenge method. However, it fails unless I feed a client_secret. So I looked at postman console to see if it sends client secret but it does not send it in any case. But the PKCE fails as soon as I remove client_secret from the configuration. so it is something do to with hidden stuff.

I am quite puzzled.

**Comment by juanheyns** [comment]
Changing the "Client Authentication" to "Send client credentials in body" worked for me on desktop v11.15.0.

![CleanShot 2024-10-07 at 17 27 01@2x](https://github.com/user-attachments/assets/ed2d202c-aa6b-40c2-9910-9d4a8f437499)

**Comment by Nonobeam** [comment]
> Changing the "Client Authentication" to "Send client credentials in body" worked for me on desktop v11.15.0.
> 
> ![CleanShot 2024-10-07 at 17 27 01@2x](https://github.com/user-attachments/assets/ed2d202c-aa6b-40c2-9910-9d4a8f437499)

This is the right approach from now. First, with PKCE is will work fine without client_secret, but still need a client_id in request body when POST /oauth2/token. So turn on this will handle putting the client_id for us. Now simply remoe client_scret and wait for the magic
