### ISSUE TITLE
Can't get OAuth2 token with PKCE on MacOS (Okta)

### ISSUE THREAD

**Issue by jpriebe** [a85/POSTMan-Chrome-Extension#9411]
**Describe the Issue**

When attempting to get an access token (grant type "Authorization Code (with PKCE)"), I am prompted for my username, then I see a flash of the Okta logo, and then the login window goes white and just hangs indefinitely.

**Steps to Reproduce**

We use Okta an an identity provider.  Not sure if that's relevant

- set up the authorization form as shown in screenshot
- click "Get New Access Token"
- a window pops up, and I am prompted for my username (my corporate email address)
- I don't get prompted for password (presumably because of our company's SSO mechanisms); I do see a brief flash of the Okta "spinner" before the login window goes white
- the login window never closes, and I never get a token

**Screenshots or Videos**

<img width="1088" alt="postman" src="https://user-images.githubusercontent.com/2745032/104029967-a7619080-5198-11eb-9df3-cc8b2f37aabc.png">

**Environment Information**

 - Platform Type: native desktop app 
 - Postman Version: 7.36.1
 - Operating System: MacOS 10.15.7

**Additional Context**

I suspect this is a MacOS-specific issue; I have had three other users test this:

- MacOS user: fail
- Windows user: success
- Linux user: success

**Comment by giridharvc7** [comment]
@jpriebe can you confirm if you still face this issue on v10+ version of the app? 
We've made a bunch of changes, including the callback URL - which I'm assuming the reason for the issue

I'm closing this ticket for now, feel free to open it in case the issue still persists
