### ISSUE TITLE
Environment variables are not set from script  ( Postman Canary 8.0.0)

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9412]
**Describe the Issue**

pm.environment.set("key","value") , is not setting value to environment variable

**Steps to Reproduce**

- Add the line to test or pre-requisite session : pm.environment.set("hi",22) 
- Check the environment and see if variable "hi" was created or updated
- Observes that environment varaible was not updated or created

**Environment Information**

 - Platform Type: [e.g. Native Desktop App]
 - Postman Version: Version 8.0.0-canary01
win32 10.0.19041 / x64

**Comment by savalik** [comment]
pm.globals.set not working too.

**Comment by DannyDainton** [comment]
Thank you for reporting this issue @praveendvd :D - We have identified the problem and are working on a fix. 

We will be updating this thread when we have more information.

**Comment by asmusz-adobe** [comment]
Having same issue here.  Thanks guys for all the hard work!

**Comment by DannyDainton** [comment]
Hey folks,

A new version of the Canary app has been released, which includes a fix for this issue. 🏆 

Would you be able to update your app and confirm that it has resolved the problem from your side, please? 😄

**Comment by yogesh1140** [comment]
worked for me

> Hey folks,
> 
> A new version of the Canary app has been released, which includes a fix for this issue. 🏆
> 
> Would you be able to update your app and confirm that it has resolved the problem from your side, please? 😄

**Comment by praveendvd** [comment]
> **Describe the Issue**
> 
> pm.environment.set("key","value") , is not setting value to environment variable
> 
> **Steps to Reproduce**
> 
> * Add the line to test or pre-requisite session : pm.environment.set("hi",22)
> * Check the environment and see if variable "hi" was created or updated
> * Observes that environment varaible was not updated or created
> 
> **Environment Information**
> 
> * Platform Type: [e.g. Native Desktop App]
> * Postman Version: Version 8.0.0-canary01
>   win32 10.0.19041 / x64

Its working , checked collection , global ,environment and local variable set and unset
