### ISSUE TITLE
Importing raml 1.0 spec with resourceTypes does not generate requests in collection

### ISSUE THREAD

**Issue by niecore** [a85/POSTMan-Chrome-Extension#9415]
**Describe the Issue**

When creating a collection from a raml 1.0 spec which includes `resourceTypes` like this example ([https://github.com/raml-org/raml-examples/blob/master/resourcetypes/simple-resourcetype.raml](link)) no requests in the collection are generated.

I expect that `postman` would create 2 requests in the collection for the linked example but none is created.

**Steps to Reproduce**

1. Import the example api description
2. Generate a collection
3. See that no requests are in the collection

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: v7.36.1
 - Operating System: Linux

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by VShingala** [comment]
@niecore This issue has been now fixed with latest Postman App v10.13.
