### ISSUE TITLE
Unable to publish to API network or as an API template via publish docs options for collections in Postman 

### ISSUE THREAD

**Issue by raghav19** [a85/POSTMan-Chrome-Extension#9417]
**Describe the Issue**

> Currently unable to publish any collection to the API network freshly. The collection discovery option is not populating any options 

**Steps to Reproduce**

* Create a fresh dummy collection
* Click Publish docs option
* In the web link, check "Collection Discovery" option after "Styling"
* Actual: The Collection discovery option does not show any options to publish the collection for a user

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/21075059/104278200-35f24c80-54ce-11eb-86ed-33064c34a877.png)

**Environment Information**
Postman for Windows
Version 7.36.1
win32 10.0.18363 / x64

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by gitThingsDone** [comment]
We no longer support templates, you can instead [create a public workspace](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/public-workspaces/), and move collections there to share them on the Public API network
