### ISSUE TITLE
Lost All Collections in Teams Workspace and My Workspace on Logout of POSTMAN

### ISSUE THREAD

**Issue by dmoryani** [a85/POSTMan-Chrome-Extension#9418]
I had signed out of Postman as my forked collection was not displayed in My Workspace. After which I lost all the Collections in my workspace, Environments , as Well as Teams Workspace. 

> I thought Sync is in process but its been an hour now. I had the json files for most of my collections which i imported into My workspace, when i try to share it to Teams it gives me an error saying I cannot share as Sync is in Progress. This is very frustrating and faced this for the first time. Will be very helpful if you could guide on the same. 

**Steps to Reproduce**

1. Sign-out and try to login back with the credentails used to create all collections. 
2. Its blank - No environments, No collections and No Collections in Teams Workspace. 

Adding screenshots - the few collections are cuz i managed to share it after importing from local to My workspace
**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 
![image](https://user-images.githubusercontent.com/31031890/104283102-0271eb00-54eb-11eb-94ec-0784bb75421a.png)

When i try to share I get : 
![image](https://user-images.githubusercontent.com/31031890/104283328-57156600-54eb-11eb-9fdc-ddb7bc7d8014.png)

**Environment Information**

 
![image](https://user-images.githubusercontent.com/31031890/104283367-64caeb80-54eb-11eb-812b-077705a16840.png)

**Additional Context**

Please consider this as a Blocker and help fix the issue

**Comment by dmoryani** [comment]
![Uploading image.png…]()

**Comment by dmoryani** [comment]
![image](https://user-images.githubusercontent.com/31031890/104284023-59c48b00-54ec-11eb-8e50-4fb7577cd332.png)

**Comment by dmoryani** [comment]
The sync icon is red. Clearly the sync not happening. Attached is the log for reference
[logs.zip](https://github.com/postmanlabs/postman-app-support/files/5801979/logs.zip)

**Comment by postman-staff** [comment]
@dmoryani while we check the logs, do checkout here to see if your collection/environments etc show up (You will have to sign in): https://go.postman.co
If you are able to confirm that your data is available and synced online - you may follow the steps here https://support.getpostman.com/hc/en-us/articles/360025359014 to rename the local Postman folder and then re-install Postman and see if that helps.

via @xk0der | Postman Support

**Comment by dmoryani** [comment]
Hi Team,

Thank you for getting back to me. I had tried reinstallation before I had
raised this concern. Also i see the sync is working as below :
Just curious to know if the* non payment would have caused this sync to
stop *in my Teams Workspace in Postman application?

Please confirm.

[image: image.png]

**Comment by postman-staff** [comment]
@dmoryani Thank you for your message.

Looks like the attached image did not come through.

Non-payment would lock the team till payment is made.
Since this looks to be an account related issues, do reach out to us at our support portal: https://www.postman.com/support and we can check your account status to make sure everything is in order, plus help you with the next steps.

Do mention this GitHub ticket id #9418 when reaching out via our support portal.

via @xk0der | Postman Support

**Comment by postman-staff** [comment]
@dmoryani I was able to locate the internal ticket and found that the issue has been resolved and you are now unblocked :)

I will be closing this ticket next, feel free to reach out directly over at our support channel for account related issues.

via @xk0der | Postman Support
