### ISSUE TITLE
After starting Postman, the pre-selected environment is not fully selected (Postman v8.0.0-canary03)

### ISSUE THREAD

**Issue by Tithugues** [a85/POSTMan-Chrome-Extension#9423]
When an environment is selected, close and reopen Postman. The environment is still selected (in the list), but:
* clicking on the eye beside the environments list shows "No Environment variables" message
* opened requests show variables as "red" (as unknown)

Still, running the requests "works".

**Reproduce**

* select an environment
* open a request with environment variables
* see that environment variables are dispalyed in orange (as known) and that clicking on the eye beside the environments list shows the environment variables
* close Postman
* reopen Postman

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Postman v8.0.0-canary03
 - Operating System: Ubuntu 20.04

**Comment by DannyDainton** [comment]
Thank you for reporting this issue @Tithugues 🏆  - The team is going to take a look at this and see what might be causing this issue.

We will be updating this thread when we have more information.

**Comment by mohitranka** [comment]
@Tithugues This issue has been fixed in the latest canary version - `8.0.0-canary09` . Please do upgrade and let us know if you face any issues.

**Comment by Tithugues** [comment]
It works now! Thank you!

**Comment by kenirwin** [comment]
I'm having basically this same issue. 

I'm on:
Mac OS 11.6 (M1 chip)
Postman 9.6.0

* created an environment
* created a "URL" variable in the environment
* created a new request and selected the environment
* tried using {{URL}} in the request, it shows up in red and gets the response `getaddrinfo ENOTFOUND {{url}}`
* when I click the eyeball icon next to the environment setting it says "no environment variables"; in that same pane I click the "edit" button to add variables and it shows me the URL variable I have set. 

I've tried updating and restarting Postman and the behavior persists.

**Comment by shubhbhargav** [comment]
@kenirwin Can you please confirm that the changes were saved to the environment before clicking on the `Send` button? I was able to replicate the issue with the steps mentioned above. In order to fix the issue, I saved the environment and it worked.

**Comment by kenirwin** [comment]
@shubhbhargav - that solved it. It took me a while to find the save button!
