### ISSUE TITLE
Link in the console doesn't seem to look clickable

### ISSUE THREAD

**Issue by iamkarlson** [a85/POSTMan-Chrome-Extension#9424]
**Describe the Issue**

When outputing some url in the console it would be superuseful to them clickable

**Steps to Reproduce**
1. 
```
console.log("http://localhost")
```
2. open the console
3. look the link is not clickable

there's also a question on stackoverflow https://stackoverflow.com/questions/51176245/postman-console-output-clickable-url

**Comment by coditva** [comment]
@iamkarlson Thanks for writing in. This is the expected behaviour since Postman Console acts as a tool for debugging and all messages that are logged as treated as strings.
But I see where you're coming from so I'll track this as a feature request. Will post any updates on this thread.

**Comment by KevinVanthuyne** [comment]
This would be very useful if you want to construct a clickable link for the developer from response data

**Comment by iamkarlson** [comment]
@coditva if you can provide any other way to have a link constructed with a response data - it would be more than enough. maybe let postman use some system hooks, idk

**Comment by coditva** [comment]
@iamkarlson I think this might be possible using the [Visualizer](https://learning.postman.com/docs/sending-requests/visualizer) in Postman. The constructed link can be opened in a new tab using "Open link in new tab" option on right click.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/8445768/170984902-26cf90c1-9257-44c7-bbfb-5013996eb2ac.png">

Here's the script that you can use in the tests section of the request.
```javascript
const template = `
    <html>
        <body>
            link: <a href="{{link}}">{{text}}</a>
        </body>
    </html>`;

pm.visualizer.set(template, {
    link: pm.response.json().data.link, // Get the URL using response
    text: 'Postman'
});
```

Let me know if this works out. 🙂

**Comment by iamkarlson** [comment]
Definitely! seems like exactly what I was looking for!
