### ISSUE TITLE
$isoTimestamp doesn't work in Monitoring

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#9426]
**Is your feature request related to a problem? Please describe.**
Users looking to bring {{$isoTimestamp}} to the Monitor environment. At the moment it's not supported. Could be considered as a Feature Request. 

**Describe the solution you'd like**
Monitors don't seem to support the same feature set as whatever platform is running "normal" requests.

**Describe alternatives you've considered**
For now, it might be possible to store get as a temporary variable by script, the user can do the same to get unblocked. 

![image](https://user-images.githubusercontent.com/41741228/104553330-7c77b080-5660-11eb-8908-e8430887bb02.png)

**Addtional Context**
Filed by Product Support

This feature work is already being tracked by the team internally, this issue is to let users who are facing similar issue be notified upon this release.

**Comment by godfrzero** [comment]
$isoTimestamp should be working correctly within monitor now.
