### ISSUE TITLE
Exporting collection with unsaved requests. 

### ISSUE THREAD

**Issue by pawel1981** [a85/POSTMan-Chrome-Extension#9427]
**You can export collection with unsaved requests**
I had collection of 15 requests, they were opened, and not saved. I exported them to json, then removed collection from workspace.
Then, I have imported collection from json on the same machine but different workspace. All my work has gone since I forget to save things before export. 
 

**User should be informed that he has unsaved requests**
There should be a clear message when user try to export collection that the stuff he is going to export is unsaved. 

Thanks

**Comment by coditva** [comment]
@pawel1981 Sorry that this happened to you, but this is the expected behaviour. Postman cannot export the data until it is saved. I'm closing it out but please feel free to reopen if you feel otherwise.
