### ISSUE TITLE
Postman desktop app doesn't launch on fresh install of macOS BigSur

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#9429]
_This is being logged by Postman, based on a couple of reports we have had of the following issue as we investigate further_

## Describe the Issue

Postman app fails to launch, on a fresh install of macOS BigSur.
After unzipping the downloaded archive from here: https://www.postman.com/downloads/ and then clicking on the `Postman.app` file nothing happens.

You may see the Postman icon bobbing in the dock but no window would open.

No traces of the app inside `~/Applications` folder or any logs inside `~/Library/Application Support/` folder.

:star: If you are running into this issue, there is a workaround that should help, but we would appreciate if you are able to provide us with the log collected as follows:

### Log Collection 

_Run the freshly downloaded and unzipped `Postman.app` from the command line while collecting stream logs_

**Open a Terminal window and start logging as follows**
```
log stream > postman.log
```
Let the command run and launch Postman normally.

Next, quit the app, and launch it as follows from a new Terminal window or tab.

For example, if you have unzipped the app inside your `~/Downloads` folder, run it as follows
```
open  ~/Downloads/Postman.app
```
Once done, go to the Terminal window running the log stream command and press Control + C to stop logging.

Collect the `postman.log` file and open a new ticket here: https://www.postman.com/support and provide the log file. We thank you in advance in helping us investigate this issue. 🤝 

## Steps to Reproduce

* Have a fresh macOS BigSur install (Example: a fresh re-install, a brand new laptop)
* Download and install the Postman Native app
* The app fails to launch when clicking on the `Postman.app` file

## Workaround
Enabling the root account fixes the issue.

To enable root account run the following command in the Terminal app

```sudo -i```
Enter your password when asked for and then you may exit out by typing exit

Installing the app next should work as expected.

## Environment Information

 - Platform Type: Native Desktop App
 - Postman Version: 7.36.0
 - Operating System: MacOS BigSur

**Additional Context**
Only applicable to macOS BigSur.

**Comment by tshubham7** [comment]
Hi, I have a macbook pro(big sur)
postman app is not working properly: when i click on requests it does not open, it does after doing open in new tab
also i am not able to open the saved response examples

**Comment by michael120288** [comment]
> Hi, I have a macbook pro(big sur) postman app is not working properly: when i click on requests it does not open, it does after doing open in new tab also i am not able to open the saved response examples

I have the same issue!!!

**Comment by twitharshil** [comment]
Hey @tshubham7 @michael120288 
We are tracking the issue where the application seems to be unclickable here https://github.com/postmanlabs/postman-app-support/issues/10460

@[xk0der](https://github.com/xk0der) I believe the issue reported above was faced during the earlier versions of macOS big Sur OS and should be fixed now. Closing the ticket now, feel free to re-open if this issue is still reproducible or community is still reporting the same issue with the latest version of the Postman application

**Comment by owldrak** [comment]
same issue, fresh mac with latest os - its not opening

**Comment by MatanKoby** [comment]
Still happening on mac, on macos Monterey 12.1

**Comment by jviotti** [comment]
@MatanKoby @oliverwh What do you get if you open Postman through the `Postman` executable directly rather than through the `*.app`? i.e. on a Terminal do:

```sh
/Applications/Postman.app/Contents/MacOS/Postman
```

**Comment by ak4sh18** [comment]
works fine if you install from Homebrew :

brew install --cask postman

**Comment by aashuagg** [comment]
After running command /Applications/Postman.app/Contents/MacOS/Postman I am getting below message:
**Could not get the lock, quitting**

**Comment by hnaht310** [comment]
> works fine if you install from Homebrew :
> 
> brew install --cask postman

Thank you. It works for me

**Comment by 1solation** [comment]
> works fine if you install from Homebrew :
> 
> brew install --cask postman

Second this, also works for me!

**Comment by jpmartins** [comment]
Homebrew "saved the day" to me too, just a minor improve, use reinstall since almost certainly you have the version installed from the web already installed.

brew **re**install --cask postman
