### ISSUE TITLE
Unable to access collections in scratch

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#9432]
Might be me (probable), but i upgraded Canary to 

Version 8.0.0-canary07
linux 5.8.0-38-generic / x64

But I am unable to see any of my collections in scratch - i can see the environments ok and the history but its says i have 14 collections but when i select doesn't do anything. It does say I can perhaps see them in Workspaces and gives me dialogue box to sign in - go to sign in lets me see in on the web browser but doesnt refresh the local application version and just resends the sign in dialogue.

**Comment by DannyDainton** [comment]
Closing this out due to inactivity - given the version and information provided, it would be difficult to recreate the issue and investigate further.
