### ISSUE TITLE
Sorting of examples

### ISSUE THREAD

**Issue by mbraidy** [a85/POSTMan-Chrome-Extension#9433]
The examples in the documentation are sorted differently than the sorting in the collection.
 Moreover, I can't sort the examples in the collection with drag & drop.

Any help?

**Comment by ro-rah** [comment]
Hi @mbraidy ,

Would you give a link to the documentation referenced in your issue (also here in the [forum](https://community.postman.com/t/sorting-examples-in-the-published-documentation/19328/2)) please?  I was looking to make documentation fixes.

**Comment by DannyDainton** [comment]
Hey @mbraidy 

![image](https://user-images.githubusercontent.com/17089546/196402461-a33ffea1-a7f8-45e6-a284-425dab11066b.png)

The examples can be reordered in the Collection and these changes are reflected in the documentation.

**Comment by mbraidy** [comment]
Apparently it works now.
Thank you
