### ISSUE TITLE
Postman web: losing work when editing the documentation 

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#9434]
**Describe the Issue**

It is too easy to lose a lot of work while editing the markdown in the request documentation. 

**Steps to Reproduce**

- open the documentation and click the pencil to edit
- make a small change
- navigate to a different tab
- when you come back, the editor is closed and your changes have to been saved. 
- no warning has been issued about the possible changes that will get lost

**Environment Information**

 - Platform Type: Postman On The Web

**Comment by Raja-Simha** [comment]
@vdespa thanks for reporting. We will try to get this fixed soon. Meanwhile, you could use the complete documentation view to edit documentation. Unsaved changes are preserved in the complete collection documentation tab.

**Comment by Raja-Simha** [comment]
@vdespa We have fixed the issue. If switch tabs while editing, your unsaved changes are preserved in the context bar.
