### ISSUE TITLE
When syncing, the app is so stuck.

### ISSUE THREAD

**Issue by yangxikun** [a85/POSTMan-Chrome-Extension#9435]
**Describe the Issue**

![image](https://user-images.githubusercontent.com/3364160/105016822-12a34080-5a7e-11eb-843a-669f1b306e1a.png)

When syncing, the app is so stuck.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.

**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 

**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version: 7.36.1 (7.36.1)
 - Operating System: macOS Catalina

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by giridharvc7** [comment]
We've solved a bunch of sync issues with v10+, please update the app and let us know if you still face this.
