### ISSUE TITLE
Collection changing url

### ISSUE THREAD

**Issue by sciutand** [a85/POSTMan-Chrome-Extension#944]
Running Version 2.0.0 (packaged) on Mac Osx.
Recently I've been having issue with collections randomly changing the url. Because now importing a collection also creates a new url for it it means that the previous collection url is now locked and stale.
This is an issues when jobs (such as jenkins build using newman) are created based on a collection url that is now stale with no way of ever being able to edit it again.

**Comment by abhijitkane** [comment]
When did you first notice the issue?
What do you mean by randomly changing the URL? Does it pick another URL from the same collection?

**Comment by sciutand** [comment]
When I press share collection the url that is shown is no longer what it used to be assigned to that collection. So now I have the original (now no longer accessible) collection and a new one. 
First noticed it yesterday.

**Comment by abhijitkane** [comment]
Are you signed in to the app? If you are signed in, the collection URL should not change when you hit 'update' in the 'share collection' dialog.

**Comment by sciutand** [comment]
Yes signed in and unfortunately it does change. Had it change four times in
a hour yesterday. The problem manifests itself with updating not working,
ie. pressing update doesn't propagate to the url. I then close and reopen
the app, most of the time the url is the same and update works again. Other
times the url has changed. Is there a way to access or overwrite what
postman thinks is the url as a temporary fix?

**Comment by abhijitkane** [comment]
We've pushed a related fix in v2.0.2 of the app, which should take care of the URL changing. It should be available in a few hours.  (You can check the currently available version here - https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en)

If you don't see the new version, you can go to `chrome://extensions/`, enable 'Developer Mode', and force the update.

**Comment by sciutand** [comment]
Ok thanks I'll try it out.

**Comment by sciutand** [comment]
Hi,

I currently can only see v 2.0.1 published on the 3rd of march. Not sure if
you mentioning 2.0.2 is a typo or it's still on its way.
Any way I can replicate the issue and it looks like it's even worse now.

1 create a new collection.
2 add a request (with or without test doesn't seem to make any different)
3 share the collection (pressing update multiple times does not change the
url)
4 open collection runner and run the newly created collection
5 close collection runner
6 open share collection and press update. Now each time upload is pressed
the url will change.
7 close postman
8 reopen and share collection. Url does not change.
9 go to step 4 to reproduce again.

**Comment by sciutand** [comment]
This is a sample of the data stored for a collection that is being
duplicated:
{id: "2dc2f1b4-1fee-0ec3-b293-f1396d9e9041", name: "Ruffl Tests",
description: "", order: [],…}

   1. description: ""
   2. folders: [{id: "fa392b30-f377-3303-0045-09af03454850", name:
   "create-ruffl", description: "", write: true,…},…]
   3. id: "2dc2f1b4-1fee-0ec3-b293-f1396d9e9041"
   4. name: "Ruffl Tests"
   5. order: []
   6. owner: "16066"
   7. public: false
   8. remoteLink: "
   https://www.getpostman.com/collections/f93388e9074aa0a93f25"
   9. remote_id: 291209
   10. sharedWithTeam: false
   11. subscribed: false
   12. synced: false
   13. timestamp: 1423423933889
   14. write: true



Each time I press upload and the url changes the remote link and remote_id
are changing.

**Comment by abhijitkane** [comment]
@sciutand -  v2.0.2 is out now. Can you check if you're still facing the problem?

**Comment by sciutand** [comment]
Just updated and issue is still present.

I can easily replicate using the steps described above. Tried log out and
log in but made no difference. I tested some of the api's the app uses and
it appears to me that the issue could be with your back end where it return
differents remote_id and url for the same collection id.

**Comment by sciutand** [comment]
This is a sample of the Post request postman makes when it's in a 'broken'
state and each uploads request generates a new remote url:

{
"id": "3e5ec4cb-2262-c840-94f5-365df2f15882",
"name": "test",
"description": "",
"order": [
"f17769c5-9314-c7b1-5c84-0fa8c3a4ecc6"
],
"folders": [],
"timestamp": 1425384144146,
"synced": false,
"owner": "16066",
"sharedWithTeam": false,
"subscribed": false,
"remoteLink": "https://www.getpostman.com/collections/43d1cc8f4e9d53cab52a",
"public": false,
"write": true,
"requests": [
{
"id": "f17769c5-9314-c7b1-5c84-0fa8c3a4ecc6",
"headers": "",
"url": "{{api-url}}login/username",
"preRequestScript": "",
"pathVariables": {},
"method": "POST",
"data": [],
"dataMode": "raw",
"version": 2,
"tests": "var data :
JSON.parse(responseBody);\n\npostman.setEnvironmentVariable(\"rufflr-access-token\",
data.access_token);\n\n\n",
"currentHelper": "normal",
"helperAttributes": {},
"time": 1425375157560,
"name": "Login copy",
"description": "just login",
"collectionId": "3e5ec4cb-2262-c840-94f5-365df2f15882",
"responses": [],
"synced": false,
"rawModeData": "{\n    \"username\":\"{{test-email}}\",\n
 \"password\":\"{{test-password}}\"\n}",
"owner": "16066",
"write": true,
"isFromCollection": true,
"collectionRequestId": "c4481143-f2ca-938b-aa85-cbbd681f6f5f"
}
]
}

**Comment by sciutand** [comment]
Forgot to mention this is the url:
https://www.getpostman.com/collections?is_public=false&user_id=16066&access_token=XYZ.
..

**Comment by abhijitkane** [comment]
Can you try now?

**Comment by sciutand** [comment]
Executing Collection Runner no longer causes the url to change as per
details above. Well done. I shall let you know If I experience the issue
again.
As for those stale collection shall I delete them from my account and
import and upload again to have them show up? Currently they were not
duplicating in my account view every time I uploaded but they still point
to the old remote_id.

**Comment by abhijitkane** [comment]
You can delete the old ones from your account. Now they won't be duplicated each time you update.
