### ISSUE TITLE
How to download postman collection and env from workspace via rest api?

### ISSUE THREAD

**Issue by ruowan** [a85/POSTMan-Chrome-Extension#9441]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I want to download postman collection from workspace via rest api? 

**Describe alternatives you've considered**

**Additional context**

**Comment by DannyDainton** [comment]
Hey @ruowan 

This seems like the perfect question to as over on the Postman Community Forum, They are folks on there who can walk you through the process. 🏆 

https://community.postman.com/

Additionally, The Postman API Collection can also be found in our Public Workspace which will give you the details to download the different entities that are part of your user account.

https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a

I'm going to close this issue as this doesn't relate to a new feature for the product.

**Comment by ruowan** [comment]
Great! The public workspace api is what I am found.
