### ISSUE TITLE
newman 5.2.1 is running 0/0 iterations for any export from postman 7.36.1

### ISSUE THREAD

**Issue by ashishvd1** [a85/POSTMan-Chrome-Extension#9442]
**Describe the Issue**

newman does not recognize any request in the postman export. 
newman always runs 0/0 iterations.
This started once I upgraded to latest postman. There is some issue in postman export. Quick comparison, I see the ID attribute is missing in export.

**Steps to Reproduce**

Create postman collection in 7.36.1
Export collection in the collection 2.1 format
Run collection using newman
The collection runs with 0/0 iterations

**Environment Information**

 - Platform Type: Native desktop app
 - Postman Version: 7.36.1
 - Operating System: Windows10 and Ubuntu

**Comment by DannyDainton** [comment]
Hey @ashishvd1 

Could you please create this issue on the Newman repo - https://github.com/postmanlabs/newman

Going to close this one out from here.
