### ISSUE TITLE
Prompt the user to fill in missing variables

### ISSUE THREAD

**Issue by MkFoster** [a85/POSTMan-Chrome-Extension#9445]
Public workspaces may contain collections/requests that require a variable to be filled in such as an API key.  If the user doesn't do this we are dependent on the API to tell them they are missing something.  New Postman users might not realize where they need to go to fill in the variable value even if they know it is required.

It would be cool if you could mark a variable as required.  If the user has not provided a value but attempts to execute the request, prompt them for it explicitly.  I.e. a dialog might come up that says you are missing a required parameter with the API author's description of the parameter needed and a field to enter.  You could also do a similar alert message but navigate to, and highlight where in the Postman interface they can enter the needed value.

Current alternatives: If I have control over the API, I can make sure to provide a good error message regarding missing required parameters or authorization keys.   Unfortunately, we may not control the APIs we are using in many cases.  I can make sure to note any required parameters or authentication variable values in the collection or request documentation.  This is not a great solution either because when you click a collection in a workspace, Postman doesn't really call out that there is documentation available.  The user would need to know that collections can have documentation and that they need to click on the little document icon in the upper right corner of the interface to see it.

Thanks! -Mark

**Comment by skatikia** [comment]
@MkFoster I'm too late to be posting an update on this, but I bring good news!

With Postman V11.14, we have rolled out a bunch of updates to our variables interface, **including a new appearance for empty variables**. Empty variables are now marked with a popping red background and red dotted borders to remind you to fill them in before you hit Send.

![empty-variable](https://github.com/user-attachments/assets/4d43c0fb-a8c5-4c67-8ffb-d7f22835d888)

Additionally, **we're introducing a variables pane that lets you view all the variables in a request in a single place** and nudges you when there are empty variables.

Click on the button next to the environment selector to bring up the variables pane and control all the moving parts of a request, a.k.a. variables, without hopping around.

![variables-pane](https://github.com/user-attachments/assets/055e939d-64e6-4b34-a37c-2465065a1c42)

I hope you like these changes as much as we do! Update your app to start working with those changes and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)

**Comment by MkFoster** [comment]
This is excellent!  Thank you! 🙏

**Comment by DSchau** [comment]
Let us know if you have other suggestions about how we can improve Postman @MkFoster (new issues, please!). We'll aim to be quicker than multi-year reply, but we're still glad to have this good suggestion implemented. Thank you!
