### ISSUE TITLE
Cannot close window that appears everytime on launching postman

### ISSUE THREAD

**Issue by santoshkar** [a85/POSTMan-Chrome-Extension#9447]
I am using Windows 10. When I open Postman, it opens a window after launching postman with 3 tabs - Create New, Templates, API Network. 
The problem is, I cannot close that window. None of my mouse click responds there. And I am not able to use the postman. 
![postman_error](https://user-images.githubusercontent.com/1926004/105451868-410c6000-5cb8-11eb-86a1-6d1f47fa1b2d.jpg)

**Comment by DannyDainton** [comment]
Hey @santoshkar 

That looks like a very old version of the app - When did you download this one?

**Comment by santoshkar** [comment]
@DannyDainton Thanks for responding. Actually I’m working for a bank and they have software center from where we can only download authorised softwares. But I think yes, it could be an old version. Any workaround available for it? I think the lagging issue is because of it’s searching for updates and it’s not responding till it get a response.

**Comment by DannyDainton** [comment]
I'm not sure about what your current restrictions are in terms of downloads but you can access the latest version using a web browser.

https://go.postman.co

**Comment by DannyDainton** [comment]
Closing due to inactivty.
