### ISSUE TITLE
Collection variable propagation. Confusing script execution,

### ISSUE THREAD

**Issue by githugt** [a85/POSTMan-Chrome-Extension#9450]
**Describe the Issue**

> If there is a failure to clear cookies (example: the cookie domain is not correctly whitelisted), the rest of the script in pre-request/ test seems to execute, but the collection variables that were set does not carry forward to the next request.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.

**Screenshots or Videos**

Here's a collection that can explain the problem.
[Postman variable propagation error.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/5856015/Postman.variable.propagation.error.postman_collection.json.zip)

![error screenshot](https://user-images.githubusercontent.com/8955849/105494845-65306700-5ce1-11eb-9568-96b971ea5444.png)

As can be seen from the above picture.
The first variable executes just fine.
Then the cookie deletion part fails because it does not have access due to improper whitelisting.
Then the other bit executes as per the test and the console logs at least, but in reality, it actually does not (as can be seen from the test in the next request).

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: v.7.36,1
 - Operating System: Windows 10 Home, Pro

**Additional Context**

I think the problem might also be applicable to a few other problems that were listed such as 
https://github.com/postmanlabs/postman-app-support/issues/5039 and
https://github.com/postmanlabs/postman-app-support/issues/6001

**Comment by giridharvc7** [comment]
@githugt Do you still see this happening in v10+? 
I imported your collection, and it ran fine. 
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/1040583/213446590-2c456c06-01ce-4168-b974-58d9c135cef6.png">

Will close the ticket for now, feel free to open it if you still face the issue.
