### ISSUE TITLE
Could not send request Error: ENOTFOUND

### ISSUE THREAD

**Issue by abhisek3122** [a85/POSTMan-Chrome-Extension#9451]
**Describe the Issue**
> I was using postman for testing my backend api, It was working fine till yesterday. Suddenly its not working and I'm getting an error " Could not send request Error: ENOTFOUND "
The connection in perfect and hosted on localhost, The request is working with curl and check, Why is postman failing to send request?

**Environment Information**
 - Platform Type: Postman Web

**Comment by DannyDainton** [comment]
Hey @abhisek3122

Can you check the type of Postman Agent that you're using, please?

![f99ba0bc56595eaded9adf7374385329fd762aac.png](https://user-images.githubusercontent.com/17089546/105576325-dfa4c980-5d69-11eb-9d4c-b8e24fbddfe5.png)

If you're making requests to a local server, you would need to use the `Desktop Agent` - I suspect that it's currently on `Auto-Select` and it's currently using the `Cloud Agent`.

**Comment by abhisek3122** [comment]
Okay I will ping, Once I change and test it

**Comment by abhisek3122** [comment]
Could you tell me, steps to change to desktop agent?

**Comment by mohitranka** [comment]
@abhisek3122 

* Turn off `Auto-Select`
* Select `Desktop Agent`

If you have Desktop Agent installed and running, it will automatically connect to it - otherwise download it by clicking the button. Following the instructions there should set you up.

**Comment by DannyDainton** [comment]
What @mohitranka said 😁 - I included an image of where that's located in the Web view. 😁

**Comment by abhisek3122** [comment]
I changed to browser agent, and its working now!
Thank you

**Comment by abhisek3122** [comment]
Thanks for awesome fast support, This issue can be closed
