### ISSUE TITLE
Postman interceptor / Proxy save to collection doesn't show all the requests in native app

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9452]
**Describe the Issue**

Captured request count is different in postman web and postman native app

**Steps to Reproduce**

1. in native app set postman capture as proxy and set save requests to collection 
2. Set firefox proxy as localhost and port we set in postman capture proxy
3. navigate to http://www.kociesprawy.pl/magazyn/czytelnia_artykuly_w_kocich_sprawach/koty_i_ludzie/kocie_blogi_-_w_krainie_pieciu_kotow/).
4. Check the collection in native app and postman web dashbpard

**Observation** 

Postman web app works correctly and has all the requests , but in native app only few are there eg :

search for /upload/obrazki/Reklamy/nowe/2_0.jpg request

it shows the collection but no request inside it (Native app)

![image](https://user-images.githubusercontent.com/45095911/105606222-feb65200-5d8f-11eb-89da-bc0aa536e225.png)

in postman web it shows the request correctly:

![image](https://user-images.githubusercontent.com/45095911/105606259-345b3b00-5d90-11eb-9669-6f4a23abe2a0.png)

**Environment Information**

Version 7.36.1
win32 10.0.19041 / x64

**Comment by gpa** [comment]
We're affected by this as well. Unfortunately some requests are missing in the web app too. Requests are also missing when saving to history.

**Comment by shashankawasthi88** [comment]
@praveendvd @gpa can you give a few more details: -
1- What version of the app are you on
2 - Can you point out which requests are not being captured. This will help us identify some pattern if any
3 - Can you try the same flow with proxy and see if these requests are still missing.

You can also raise a request on help@getpostman.com and give a reference to this ticket to share more details.

**Comment by agrwl-harsh** [comment]
@praveendvd @gpa 
The issue has been fixed. Please try in the latest postman app version and let us know in case you find some other issues.
