### ISSUE TITLE
Unable to view public workspace in Desktop application

### ISSUE THREAD

**Issue by ipranjal** [a85/POSTMan-Chrome-Extension#9455]
**Describe the Issue**

I am unable to create or view public workspace from my Postman Desktop application . I can create a team workspace and when I convert it to public workspace I can no more open that workspace on my desktop application. 

**Steps to Reproduce**

1) Open postman application 
2) Goto create new workspace 

Boom, there is no option to create public workspace !

1) Create a team workspace
2) Goto web application and change visibility from team to public

Boom, there is no way to access the workspace in desktop application now !

**Screenshots or Videos**

<img width="727" alt="Screenshot 2021-01-25 at 2 44 05 AM" src="https://user-images.githubusercontent.com/7591484/105643729-982c5380-5eb7-11eb-8b36-3519fab9efc2.png">
Screenshot showing absence of public workspace

<img width="1278" alt="Screenshot 2021-01-25 at 2 45 54 AM" src="https://user-images.githubusercontent.com/7591484/105643739-a9756000-5eb7-11eb-86e9-b44e8fa54cf3.png">
changing the workspace from team to public using the web panel causes workspace to disappear from desktop app

**Environment Information**

 - Platform Type: Mac OS Native Desktop App
 - Postman Version: 7.36.1
 - Operating System: Mac OS

**Additional Context**

- Region: India 
- Public workspace is working perfectly fine if I log in into web version

**Comment by mohitranka** [comment]
@physcocode Public workspaces should be accessible with the latest 8.x version, which you can download from https://www.postman.com/downloads/ 

Please give that a try, it has tons of new features, and let us know if you face any issues.

**Comment by ipranjal** [comment]
Weird, postman showed no updates available :(
@mohitranka thanks for the help, it works on 8.x version :)
