### ISSUE TITLE
Export option on web platform is not obvious

### ISSUE THREAD

**Issue by taehoshino** [a85/POSTMan-Chrome-Extension#9457]
**Is your feature request related to a problem? Please describe.**
_Feature request filed by Product Support._ 

On web platform, "Export" option is moved from the context menu (on left pane) to the menu on the central window (as below):
![web-menu](https://user-images.githubusercontent.com/55820883/105664569-1d9c1c00-5f29-11eb-8863-78b52e23448e.png)
![web_export](https://user-images.githubusercontent.com/55820883/105664592-27258400-5f29-11eb-9c2c-144edcd8bab4.png)

On the native app, "Export" option is still available in the context menu (on left pane):
![native-app-menu](https://user-images.githubusercontent.com/55820883/105664614-373d6380-5f29-11eb-8f8a-082efda7b5b3.png)

This inconsistency may be confusing to users, and we have received user reports on this. 

**Describe the solution you'd like**
Restore "Export" option in the context menu on web platform.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mohitranka** [comment]
@taehoshino Users will get the same web ui experience with the upcoming major version of the app - Check it out at https://www.postman.com/downloads/ and we look forward to your feedback! :)

**Comment by kolya182** [comment]
> @taehoshino Users will get the same web ui experience with the upcoming major version of the app - Check it out at https://www.postman.com/downloads/ and we look forward to your feedback! :)

@mohitranka This docs outdated, no way i can locate `Code` button here https://learning.postman.com/docs/sending-requests/generate-code-snippets/. As https://github.com/taehoshino mentioned i can't export individual query from:
<img width="1014" alt="Screen Shot 2021-01-25 at 2 15 48 AM" src="https://user-images.githubusercontent.com/3277207/105692392-379b1780-5eb3-11eb-8145-93dd12efd384.png">

**Comment by DannyDainton** [comment]
Hey @kolya182 

The code snippet generator is now located in the right side context bar, along with various other options. The docs with been getting updated to reflect all the changes very soon.

![image](https://user-images.githubusercontent.com/17089546/105693455-a8642300-5ef7-11eb-83af-aa7e3a112186.png)

More of the new changes can be found here - https://blog.postman.com/introducing-postman-desktop-app/

**Comment by DannyDainton** [comment]
The `export` is part of the Collection context menu in the latest version. Closing this issue.
