### ISSUE TITLE
Postman Issue connecting when signing in to Authentication Services

### ISSUE THREAD

**Issue by ninoDagdag** [a85/POSTMan-Chrome-Extension#9458]
**Describe the Issue**
Unable to Sign with below messages:

_Something went wrong!_
_We're having some difficulties connecting to our authentication service. Try again after some time._

**Steps to Reproduce**
1. Install Postman v.8.0.1 in 64-bit Windows
2. Open Postman
3. Click Sign In
4. Postman is loading
5. Message shown:

_Something went wrong!_
_We're having some difficulties connecting to our authentication service. Try again after some time._

**Screenshots or Videos**

![postman](https://user-images.githubusercontent.com/58241777/105698059-572c5180-5f40-11eb-89e4-2105fb0c0f80.png)

**Environment Information**

 - OS Name: Microsoft Windows 10 Home Single Language 64-bit
 - Version: 10.0.19041 Build 19041
 - Postman Version: Postman v8.0.1 

**Additional Context**

> Problem happens even to other Postman version 7
> It happens just now. Yesterday Postman is ok.

**Comment by ArjunSingh-PM** [comment]
@ninoDagdag Do you still face this issue while signing in to Postman?

**Comment by ArjunSingh-PM** [comment]
This issue may occur due to a firewall or proxy that causes issues in connecting to the authentication service. Closing this issue as of now due to the lack of information to proceed further.
