### ISSUE TITLE
I  have Error: connect ECONNREFUSED  by http2

### ISSUE THREAD

**Issue by Barolina** [a85/POSTMan-Chrome-Extension#9462]
**Describe the Issue**

> I send  request  a  and get  response  _ECONNREFUSED,  but  i use on backend  http2

**Steps to Reproduce**

> 

**Screenshots or Videos**

> ![изображение](https://user-images.githubusercontent.com/5443003/105819546-5ee40880-5fc9-11eb-94bb-8726d62b6b20.png)

**Environment Information**

 - Platform Type: [ Native Desktop App]
 - Postman Version:v7.36.1
 - Operating System: Windows10

**Additional Context**

> On  Backand use  to   nginx/1.18.0 (Ubuntu)

**Comment by ryanhugh** [comment]
#2701
