### ISSUE TITLE
Importing a valid OpenAPI 3 document fails

### ISSUE THREAD

**Issue by denisvmedia** [a85/POSTMan-Chrome-Extension#9463]
**Describe the Issue**

When I try to import an OpenAPI 3 document generated by [API Platform](https://api-platform.com), 

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.

When I try to upload [this document](https://pastebin.com/raw/xZGV10mJ), I get "There was an unexpected error. Please try again later".

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/5462781/105829087-33125400-5fc4-11eb-85cd-2c63966f055e.png)

**Environment Information**

 - Platform Type: Native Desktop
 - Postman Version: v7.36.1 (the latest so far)
 - Operating System: Windows 10

**Additional Context**

I tried uploading a file, providing a link, pasting as text. The problem persists.

**Comment by DannyDainton** [comment]
Hey @denisvmedia 

It looks like you need to have a name in the "title" rather than an empty string - If you use the `Raw text` option and paste the Schema, add a name and hit Continue.

![image](https://user-images.githubusercontent.com/17089546/105830614-9d73c600-5fbd-11eb-8d6f-a66881b5d56c.png)

You will see that value in the `Name` section:

![image](https://user-images.githubusercontent.com/17089546/105830677-b5e3e080-5fbd-11eb-95a4-f78bb4624ef8.png)

**Comment by denisvmedia** [comment]
It worked. Thank you!

**Comment by denisvmedia** [comment]
@mccannt @DannyDainton I'm just wondering, if we can't have a better error reporting for this issue.

**Comment by DannyDainton** [comment]
👍  I agree the message doesn't really tell you _why_ it failed or how you _could_ recover from this scenario.

I'm going to raise an internal issue to track this. Any updates will be added here.

**Comment by mccannt** [comment]
@denisvmedia There have been some recent improvements in this area. 

Can you have a look and let us know if it is working better for you?

**Comment by denisvmedia** [comment]
If I have a title that is an empty string, it now says "Error while importing: format is not recognized". Which is way better, however I'm still not sure if it can help the person to understand the real problem.

Also, as a side note: if I set the title to a single space, it starts working. So, I'm not sure what's the difference, and why a space can be accepted as a name, while an empty string can't. Anyway, those seem to be edge cases, and I'm not sure how it should be handled, as it's maybe not a technical question, but rather a product-level one. And as such, I'll maybe close this. Thank you for your efforts!
