### ISSUE TITLE
Tests don't have directory path information in the runner

### ISSUE THREAD

**Issue by KyryloKuchuk** [a85/POSTMan-Chrome-Extension#9464]
Environments:
Postman for Windows
Version 8.0.2

Preconditions:
- Create a collection with three directories inside
Steps to reproduce:
- Run collection in the runner
- Move focus to any test to display a tooltip with the full request's directory path.

Expected result:
Tooltip displayed as in previous 7.x.x version

Actual result:
Tooltip doesn't display.
![image](https://user-images.githubusercontent.com/45817511/105835128-b4211980-5fcb-11eb-97fc-352aa5feca04.png)

**Comment by mccannt** [comment]
Thanks for the report @KyryloKuchuk we are looking into the cause of this.

**Comment by ManiacDC** [comment]
Thanks @mccannt . Noticed this as well and this functionality is pretty important for us.

**Comment by vdcardenas** [comment]
Yeah, I came to report this too. In collections with thousands of requests, this functionality is essential to identify the failed test.
Getting back to functionality would be great news.

**Comment by mccannt** [comment]
This should now be fixed in recent versions of the application. 
Closing out this issue, if you are still experiencing issues please reach out.
