### ISSUE TITLE
Postman mock server unable to handle request with payload bigger than ~ 1134046 bytes

### ISSUE THREAD

**Issue by haoj-loy** [a85/POSTMan-Chrome-Extension#9467]
Postman for Mac
Version 7.36.1
OS X 20.1.0 / x64

Postman mock server is returning 400 Bad Request for the request with payload content-length: "1134046" but it is working fine when the request payload is smaller (e.g: content-length: "998144")
![Screen Shot 2021-01-27 at 1 32 50 pm](https://user-images.githubusercontent.com/73458540/105939888-36820a00-60ae-11eb-8d90-1a22ac036c57.png)

**Comment by vvs11** [comment]
@haoj-loy The maximum size of request body that you can send is 1 MB on mock servers

**Comment by akshaydeo** [comment]
👋 @haoj-loy I am closing this issue for now as we have a hard limit on the max size of the payload 🙇 . Feel free to re-open if you have any questions/concerns 🙂 .
