### ISSUE TITLE
Feature Request : Copy - DragDrop a request

### ISSUE THREAD

**Issue by Brilbroeder** [a85/POSTMan-Chrome-Extension#9468]
I have multiple collections, each collection has multiple folders, each folder has multiple requests.
In my case a folder groups all requests related to one entity f.e. book, author, ....
In each folder I have a create, read, read/id, update/id, delete/id request

Given the request for a given entity all look the same, if would be easy if I could just drag/drop copy a request from one folder to another. How do that ?

hold control, drag/drop the request on the desired destination.
It would be nice to have the pointer change to a plus.

Hence kind-of the same behavior as in windows explorer.

**Comment by DannyDainton** [comment]
This behaviour has now been included in the latest version of the platform.
