### ISSUE TITLE
Postman 8.0 lacks collection export option

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#9471]
Option to export collection missing

**Steps to Reproduce**

> Open collection options and see no export option any more

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 8.0
 - Operating System: windows 7 64 bits

**Comment by m3dbedb** [comment]
I've found the option but now it is hidden: click on the collection, press ... on the top on uppeared on the right collection info window,
I propose to change the issue into feature request to add export option to be able to fast export collections.

**Comment by mccannt** [comment]
@m3dbedb Thanks for reaching out. 
We are looking into this currently as we have received feedback from others as well. We will keep you updated on this.

**Comment by mohitranka** [comment]
@m3dbedb Export option would be available in the upcoming Postman 8.0.3 with collection action menu dropdown, and right-click as well, same as v7 :)

**Comment by DannyDainton** [comment]
Version 8.0.3 is now available for folks to update. 

![image](https://user-images.githubusercontent.com/17089546/106125425-1147d700-6154-11eb-8a20-1dae5e5b2812.png)

**Comment by Muhammet15** [comment]
![Image](https://github.com/user-attachments/assets/e5e79cd7-5299-4fb0-9e27-f6c2e8dcbf18)
This is an abnormal situation. When I click on the 3 dots on the Collection and export, the export window does not work at all. (I also tried with the web.)

Postman v11.44.0 , win 11 x64
