### ISSUE TITLE
Postman 8.0 Vertical Space Usage

### ISSUE THREAD

**Issue by ManiacDC** [a85/POSTMan-Chrome-Extension#9472]
**Describe the Issue**

Postman 8.0 uses too much vertical space, especially when NOT signed into a workspace.

**Steps to Reproduce**

Launch Postman. To see the exacerbated issue, ensure you are NOT signed into Postman.

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/1823305/106006324-1b4dd500-6083-11eb-94e1-e8724172dde4.png)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 8.0.2
 - Operating System: Windows 10

**Additional Context**

I don't sign into Postman, and realized with Postman 8.0 that there's a ton of wasted vertical space. Some of this is due to the annoying yellow bar that seemingly can't be turned off, but even if I were signed into postman, there's still a lot of wasted space.

***Edit 1/29***
8.0.3 appears to have added an "x" button to close the yellow bar, though the bar comes back after restarting postman.

**Comment by reseto** [comment]
For me there is a small X button to close that yellow bar which solved this issue.

**Comment by ManiacDC** [comment]
That is new with 8.0.3. That definitely solves most of the issue. I think the space could still be optimized by combining the traditional menu with the home/workspaces/reports/explore/search bar, so I'll leave this open for now.

**Comment by ManiacDC** [comment]
Also, the yellow bar comes back with each restart... I would think it should retain the state of the bar.

**Comment by timbochamp** [comment]
Closing this where the option to close the Scratch Pad banner is available as of v8.0.3. Tracking the issue to disable the banner from reappearing in #9488
