### ISSUE TITLE
Where is the code generation button?

### ISSUE THREAD

**Issue by bknowles** [a85/POSTMan-Chrome-Extension#9475]
**Describe the Issue**

I'm trying to take my existing collection and get code generated for me based on the steps in the collection

**Steps to Reproduce**

1. Open collection
2. Go to first step in the collection
3. Try to find the button that says "Code" so that I can use the generator
4. Fail

**Screenshots or Videos**

Every screenshot or piece of documentation I've found says that there should be a "Code" button right next to the "Cookies" button, underneath the "Save" button.  But this screenshot shows no such thing in that location: https://i.ibb.co/Y2DQ8Wf/Screen-Shot-2021-01-27-at-12-34-57-PM.png

Other documentation points to a setting that can be changed to enable the code generation, in a value right underneath "Trim keys and values in request body".  But this screenshot shows no such thing: https://i.ibb.co/2s2qPwM/Screen-Shot-2021-01-27-at-12-34-26-PM.png

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 8.0.2
 - Operating System: macOS 10.14.6 "Mojave"

**Additional Context**

I've tried the web page version, too.  Again, no code generation button.  I would love to see a button that would allow me to generate code for the entire collection, but for now I would settle for generating code for each step one at a time in the collection.

**Comment by DannyDainton** [comment]
Hey @bknowles

The code snippet generator can be found in the right side context bar. If you open a request, you should see this option along with several other items, depending on the saved state of the request. 

Could you post a picture of your app's interface so we can see what you can see please?

**Comment by bknowles** [comment]
The two links above are screenshots from the app on my machine.  But I can directly post them here, too.

Here's the one showing that the button does not exist on my machine in the location where it is shown on all the other screenshots I've seen:

<img width="510" alt="Screen Shot 2021-01-27 at 12 34 57 PM" src="https://user-images.githubusercontent.com/1151895/106052137-ddff3c80-60ae-11eb-9c29-4097e12c2f02.png">

And here's the screenshot of the settings page, showing that the option to enable code generation also does not exist:

<img width="732" alt="Screen Shot 2021-01-27 at 12 34 26 PM" src="https://user-images.githubusercontent.com/1151895/106052217-f2dbd000-60ae-11eb-8e77-4f6a3b889f8b.png">

**Comment by DannyDainton** [comment]
In the image where you have circled the cookies, you will see the `code` icon in the right side context menu next to it with the documentation, comments and info options.

![app image](https://i.ibb.co/Y2DQ8Wf/Screen-Shot-2021-01-27-at-12-34-57-PM.png)

**Comment by bknowles** [comment]
Ahh, so this is a documentation bug?  There is no longer a red button that says "Code" that sits right next to the red button labeled "Cookies"?

Edit:

For example, on the page at https://learning.postman.com/docs/writing-scripts/script-references/test-examples/#parsing-response-body-data we see the following graphic:

![example-test-assertion-result](https://user-images.githubusercontent.com/1151895/106056445-47ce1500-60b4-11eb-8da2-3e90b9e5da9e.jpg)

And this graphic clearly has a "Code" button in red, sitting right next to the "Cookies" button.  This type of screenshot is found throughout the documentation that I've looked at regarding the code generator.

**Comment by bknowles** [comment]
And does that icon only work if you're logged into a Workspace on the web site?  Because I tried using all those icons on the right hand side of the screen for the Documentation mode, the Comments mode, and the Information mode, and none of them worked so long as I was in a private Scratchpad.

**Comment by DannyDainton** [comment]
The whole documentation is in the process of getting updated to match the new V8 layout.

The right context menu will show in the Web view and in the app - I'm not sure what you were seeing, when you couldn't access these items. 

Could you provide an example of this, please? 

As it's a context menu, the entity that you're currently viewing in the tab will have different options to suit the context.

**Comment by bknowles** [comment]
Taking the Workspace version of the work I've done and re-importing it back to the Scratch Pad, I find that "Comments" and "Info" can only be used while in Workspace mode.

Screenshots:
<img width="444" alt="Screen Shot 2021-01-27 at 4 10 38 PM" src="https://user-images.githubusercontent.com/1151895/106060881-41db3280-60ba-11eb-83f3-421f9c05a330.png">
<img width="443" alt="Screen Shot 2021-01-27 at 4 10 51 PM" src="https://user-images.githubusercontent.com/1151895/106060910-47387d00-60ba-11eb-91fb-ec7870302422.png">

The "Documentation" menu does seem to work in the Scratch Pad.  I won't provide a screenshot, since this does work and a screenshot would show sensitive information unless I blacked out most of the screenshot.

And trying the menu labeled as "</>", it appears that this also works in the Scratch Pad.  Again, I won't provide a screenshot for the same reasons.

Now, the code that's being generated doesn't fully implement the entire step.  It doesn't implement the pre-request script, nor does it implement any of the code in the Tests.  But maybe that should be addressed in a different Github Issue?

**Comment by DannyDainton** [comment]
None of the code snippets would show the pre-request or tests code, as those are very contextual to Postman itself.

I'm going to close this issue out as it was to do will being able to locate the code snippet itself and it seems like you have not found that in the app. 😁

**Comment by bknowles** [comment]
Thanks for helping me locate the "</>" menu!  That at least gets me part of the way to where I need to be.
