### ISSUE TITLE
Documentation is hanging if content is huge

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9480]
**Describe the Issue**

https://www.postman.com/crimson-sunset-709132/workspace/public/documentation/8296678-8b22cd36-d1de-4299-8381-f6a438151663

This is my submission for hackathon , but as the examples are huge the documentation is hanging . 

Is there a limit for documentation size 

postman v8 , issue is there both in app and web

**Steps to Reproduce**

> Open https://www.postman.com/crimson-sunset-709132/workspace/public/documentation/8296678-8b22cd36-d1de-4299-8381-f6a438151663 in web or native app.

**Environment Information**

 - Platform Type: Native Desktop App, Postman On The Web, Web Dashboard
 - Postman Version: 8.0.2
 - Operating System:  Windows 10

**Comment by godfrzero** [comment]
Closing as this has been fixed now. Let me know if you're still seeing this problem and we can reopen it.

**Comment by praveendvd** [comment]
> Closing as this has been fixed now. Let me know if you're still seeing this problem and we can reopen it.

The documentation section is not scrollable using keyboard should i raise a separate bug or re open this ?
