### ISSUE TITLE
[Feature Request] Use Windows certificate store as a source for client certificate

### ISSUE THREAD

**Issue by einhorneyal** [a85/POSTMan-Chrome-Extension#9483]
**Is your feature request related to a problem? Please describe.**

Our problem is how to use client certificate that contain private key in a secure way (such as imported certificate in the windows certificate store) instead of file that located in the filesystem.

**A clear and concise description of what you want to happen.**

Unfortunately the only way to use a client certificate is with file that located in the filesystem(CRT&KEY files/PFX file) - which is not secure while the private key is kept on the filesystem instead of the certificate store.

We would greatly appreciate if it would be possible to use an imported certificate from the windows certificate store as a source by thumbprint/subject.

**Comment by giwleb** [comment]
We use Windows IIS, and our enterprise has a certificate server that "manufactures" signed internal certificates, signed by our enterprise root CA. In order for us to test these web APIs using postman, we have to import the enterprise intermediate PFX file in the settings for Postman on Windows. Being able to tell postman to use the Windows certificate store (like its "Trusted Root Certification Authorities" )would be very helpful.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5930
