### ISSUE TITLE
[Postman v8.0] Sync connection error

### ISSUE THREAD

**Issue by DinoSourcesRex** [a85/POSTMan-Chrome-Extension#9484]
**Describe the Issue**

Sorry for the poor form bug report but my colleague showed me this when he experienced it but he was too lazy to log it (his words not mine :D)

He upgraded to the latest postman version today (v8.0.3 I believe).

When he did this his cloud sync was disconnected. He clicked it and tried to reconnect however nothing happened.

When looking in dev tools (View -> Developer -> Devtools) no network request was made when clicking the button however there was a console log that showed that a method with the signature `pm.something.forceConnect` did not exist.

**Steps to Reproduce**

1) Open postman v 8.0.3
2) Be unable to sync your files
3) Open dev tools
4) Click the reconnect button on the sync

**Screenshots or Videos**

None, sorry

**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]: Desktop app, on web he has a connection when he loads the page
 - Postman Version: 8.0.3
 - Operating System: Windows 10, not sure on the version number

**Comment by DannyDainton** [comment]
Hey @DinoSourcesRex,

Would it be possible to send over the logs to help@postman.com so we can take a look at what's going on, please?

You can find the logs at `View -> Developer -> View logs in Finder/Explorer.`

Feel free to reference the GH Issue number in the subject line of the email.

**Comment by DinoSourcesRex** [comment]
@DannyDainton I've asked my colleague to do so. 

---

Logs are on the way

**Comment by DannyDainton** [comment]
Similar issues have been raised on the repository and to try and keep the flow of information in a central place, I'm going to close this issue and kindly ask that you follow the thread, on the issue below, for more information. 

https://github.com/postmanlabs/postman-app-support/issues/9481
