### ISSUE TITLE
Why does postman not support concurrent testing

### ISSUE THREAD

**Issue by xflihaibo** [a85/POSTMan-Chrome-Extension#9485]
Why does postman not support concurrent testing

**Comment by DannyDainton** [comment]
Hey @xflihaibo 

This feels like a great question to post over on our Postman Community forum - The question is a little light on details so be sure to expand on the context and provide some examples of your use case. 🏆 

You can find the Community forum here - https://community.postman.com/

I'm going to close this issue for now.
