### ISSUE TITLE
New Integration Request - OpsGenie

### ISSUE THREAD

**Issue by ShahAnuj2610** [a85/POSTMan-Chrome-Extension#9486]
**Describe your current workflow**
We monitor our APIs through Postman for our site onequince.com

**Describe your ideal workflow**
I want to integrate with OpsGenie to receive calls whenever API is down

**Describe alternatives you've considered**
Not any as of now

**Additional context**
https://docs.opsgenie.com/docs/bitbucket-connection

**Comment by jotsarup** [comment]
@ShahAnuj2610 We are currently building OpsGenie integration and you should see in the next week. Will keep you posted.

**Comment by jotsarup** [comment]
@ShahAnuj2610 

We have added Opsgenie integration. Please check it out here https://go.postman.co/integrations/browse?category=all
Users should now be able to send monitor run failures as alerts to Opsgenie.
The Opsgenie API key to be used can be created here https://docs.opsgenie.com/docs/api-integration

Do let us know about any feedback or improvements
