### ISSUE TITLE
Add support for publishing and subscribing to MQTT brokers to Postman

### ISSUE THREAD

**Issue by bryanbarnard** [a85/POSTMan-Chrome-Extension#9490]
**Describe the solution you'd like**
I'd like to use Postman, which I've used for developing and tesing HTTP APIs to also be able to test my interactions with Pub/Sub systems specifically using MQTT. The transport protocol is different but Pub/Sub to MQTT presents many of the same challenges as HTTP APIs. Authentication, Payload Format, Response Validation, ETC. With more integrations and systems starting to support eventing and pub/sub scenarios I would like to see Postman add support.

**Describe alternatives you've considered**
- MQTT Explorer
- Command line tools
- VS Code with plugins

**Comment by philCryoport** [comment]
We are paid subscribers.  We would love to use Postman's team-collaboration features with a MQTT API collection. Please add soon!

Please include things like:
* selection of which MQTT standard (3.1.1 or 5)
* selection of MQTT QOS level
* X.509 certificates for authentication
* TLS for encryption 
  * ...with the ability to force a specific TLS level
  * ...with the ability to force a minimum TLS level (there's a difference)

Thank you!

**Comment by codenirvana** [comment]
@philCryoport 💯

As you may have already noticed, Postman now supports testing [WebSocket](https://blog.postman.com/postman-supports-websocket-apis/), [Socket.IO](https://blog.postman.com/postman-now-supports-socket-io/) and [gRPC](https://blog.postman.com/postman-now-supports-grpc/) APIs!

We are currently working on enabling collaboration features for these new protocols along with connecting them with the rest of the ecosystem to complete their API development lifecycle.

There's no ETA just yet, but MQTT is definitely at the top of our to-do list.
Thanks for the detailed feature list and stay tuned for more updates!

**Comment by philCryoport** [comment]
Hi @codenirvana and @saeedgatson -- checking in...any luck getting MQTT integrated into Postman?

**Comment by jonathanhaviv** [comment]
@philCryoport Hey we're working on this and wanted to know if you'd have 15 minutes to chat through your team needs and any feedback you might have!

**Comment by philCryoport** [comment]
> @philCryoport Hey we're working on this and wanted to know if you'd have 15 minutes to chat through your team needs and any feedback you might have!

Absolutely @jonathanhaviv !  I just messaged my email address and the email address of one of my fellow engineers to Ian Douglas, whom is one of your Senior Developer Advocates -- and a really smart engineer (I learned a lot from him)

**Comment by laboratoryyingong** [comment]
> Hi @codenirvana and @saeedgatson -- checking in...any luck getting MQTT integrated into Postman?

You are correct; we all expect that Postman could support testing the MQTT broker.

**Comment by skatikia** [comment]
Hey All! Fresh off the protocol bakery- Postman now supports MQTT! You can test your MQTT APIs built on V5 and V3.1.1 and analyze the responses better with real-time response visualization. Learn about all the stuff we have done and how to get started: https://blog.postman.com/postman-supports-mqtt-apis/

![image](https://github.com/postmanlabs/postman-app-support/assets/67992216/3a52c4ce-8a51-47ab-914a-cb03e026475a)

Thank you all for the feedback, and we look forward to hearing more from you once you get your hands on it! ❤️
