### ISSUE TITLE
Feature-Request: Ability to update/edit Fork Labels

### ISSUE THREAD

**Issue by SabriH10** [a85/POSTMan-Chrome-Extension#9491]
**Opened on behalf of a user** 

**Is your feature request related to a problem? Please describe.**

At the moment, Fork labels cannot be updated or changed once a collection is forked. 

**Describe the solution you'd like**
It would be nice to be able to edit/update a Fork label without resorting to deleting a fork ( for example if there's a typo )

**Additional context**
**Opened on behalf of a User** who may follow up with specific use case.

**Comment by stcalica** [comment]
multiple users report fork labels cover collection names

**Comment by sehuff** [comment]
Would be nice to remove the fork label all together too.

**Comment by kartikjain26** [comment]
@SabriH10 You can update fork labels now in Postman app ( > v10.21) and Postman web 🎉 

All you need to do is click over the fork label.
![image](https://github.com/postmanlabs/postman-app-support/assets/26088676/f7065560-2d88-44ad-9056-d55f28430479)

Do try it out and let us know your feedback.
