### ISSUE TITLE
Postman 8.0.3 crashes after moving requests between folders and collections

### ISSUE THREAD

**Issue by daokrajaih** [a85/POSTMan-Chrome-Extension#9492]
**Describe the Issue**

> Postman 8.0.3 crashes after moving requests between folders and collections

**Steps to Reproduce**

1) Open app 
2) Update several requests inside collection
3) Duplicate request 
4) move requests to different folder within and between collections 
5) App show a pulsing line instead of the name of request - even after more than 5 mins, it does not get resolved

![request being moved does not get moved properly](https://user-images.githubusercontent.com/48604538/106191739-431f6480-6179-11eb-85a6-28649dbf7ed7.jpg)

6) Also when navigating between folders by expanding on folders arrows, App crashes (just closes itself) sometimes.

**Environment Information**

 - Platform Type:  Postman app on window 
 - Postman Version:  v8.0.3
 - Operating System:  Window 10 Pro

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by ManiacDC** [comment]
I had this happen when trying to move a request into an empty folder. To workaround it, I first created a request in the folder, then moved the request in, and deleted the original request.

**Comment by daokrajaih** [comment]
I've updated to v8.0.5 and I'm still experiencing the app crashing at least 5 times a day.  Since I move requests and use duplicate to create more requests throughout the day (and other activities), I have to review all previous changes after reopening the app.  Is there a crash log that I should attach to this ticket to help investigate the issue?

**Comment by m3dbedb** [comment]
I confirm the issue on postman Postman v8.0.1 - v8.0.5 under windows 7 64. Request, moved to the end of collection's root blinking forever (as daokrajaih stated). It's a good luck the app did not crush.

**Comment by m3dbedb** [comment]
Also I have noticed weird behaviour of tabs. Yesterday I closed Postman. Today I have opened postman and became closing tabs. After selecting some tab it opened empty and blinking.
![blinking_tab](https://user-images.githubusercontent.com/25632818/109473766-cdaef880-7a84-11eb-9260-7dd11eef0a3d.JPG)

**Comment by timbochamp** [comment]
The persisting loading issue on moving requests and potentially crashing should now be addressed on the latest app version and on Postman for Web! Please feel free to open new issues if these additional issues are still happening on the latest version, or reopen this issue should you still encounter the persisting loading initial issue.
