### ISSUE TITLE
Postman 8.0.3 for mac can not duplicate current tab

### ISSUE THREAD

**Issue by KylinChan** [a85/POSTMan-Chrome-Extension#9493]
### Describe the Issue
> Postman 8.0.3 can not duplicate current tab

###
Environment Information
* Platform Type: Postman app fot mac
* Postman Version: v8.0.3
* Operating System: MacOs 10.15.7

### Steps to Reproduce
1. Open app
2. Create a new POST request tab.
3. Attempt to copy current POST tab.
4. Postman created a new GET tab with no content, But I want to create a tab that is exactly the same as the current tab, just like the previous Postman.
![image](https://user-images.githubusercontent.com/22339099/106223410-4d466f00-621c-11eb-8aa6-fae663fc72ec.png)
![image](https://user-images.githubusercontent.com/22339099/106223438-60593f00-621c-11eb-9b36-6bf98d1073a1.png)

**Comment by DannyDainton** [comment]
Hey @KylinChan 

The original looks like it's in an unsaved state and has never been saved to a Collection - Duplicating the tab in that scenario would be copying an empty tab.

This does look like something that has changed from V7 > V8 so we'll take a look at what's going on here.

Thanks for flagging that issue 🏆

**Comment by KylinChan** [comment]
@DannyDainton 
Thank you for your reply. There are many similar questions. I want to copy or open a new tab from a saved collection , but no matter how I operate, I can't achieve the expected effect.

As shown in the figure below, 
I want to open a new tab again, but there is no change after right clicking and clicking. Or I create a new tab and click the post request that I need to open, but the original get request becomes a post request，I'm not sure if 8.0.3 was designed in this way or there was a bug, but it really affected me. I'm thinking about whether to go back to the original version.
![image](https://user-images.githubusercontent.com/22339099/106364484-4c235800-636a-11eb-9609-247c088429b9.png)

**Comment by mohitranka** [comment]
@KylinChan Thanks for the report. This is a known issue, which is being fixed, and will be out with the next release of Postman app.

**Comment by ivanbarayev** [comment]
its not only in MAC, in windows OS is same issue on same version...

**Comment by DannyDainton** [comment]
It will be the same issue across all the available platforms.

As @mohitranka mentioned, this is being fixed and will be released soon.

**Comment by DannyDainton** [comment]
Quick update - The new version of the `Canary` build contains fixes for the _duplicate tab_ and _open in a new tab_ issue.

You can grab the version here:

https://www.postman.com/downloads/canary/

**Comment by DannyDainton** [comment]
It's now been released on the main app build 🎉 

Update your app to grab the latest! 🏆

**Comment by timbochamp** [comment]
Where the duplicate tab and open in new tab issues are resolved here, I'm going to close the ticket. Please feel free to reopen if you encounter issues on v8.0.6!
