### ISSUE TITLE
Documentation not accessible in browser

### ISSUE THREAD

**Issue by debjeetsarkar** [a85/POSTMan-Chrome-Extension#9496]
**Describe the Issue**

> Trying to view the documentation by clicking **view in web** option from app, it opens up a browser tab with a postman tab saying **Something went wrong** 

**Steps to Reproduce**

- Open postman app.
- Select View in Web.
- Browser tab opens up and shows error.

**Screenshot**
<img width="1680" alt="Screenshot 2021-01-29 at 2 24 35 PM" src="https://user-images.githubusercontent.com/6427574/106253656-c609f300-623d-11eb-8eca-4fdfedac7437.png">

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Version 7.36.1 (7.36.1)
 - Operating System: Mac OS 10.15.7

**Comment by lbs-rodrigo** [comment]
I have the same problem

**Comment by debjeetsarkar** [comment]
This seems to have resolved now. Closing this :)
