### ISSUE TITLE
Response is not formatted correctly in postman 8

### ISSUE THREAD

**Issue by RezaRahmati** [a85/POSTMan-Chrome-Extension#9497]
**Describe the Issue**

Json responses are not formatted correctly in version 8

**Steps to Reproduce**

Send any request that response is json

**Screenshots or Videos**
**v8**

![image](https://user-images.githubusercontent.com/10086092/106289324-26d20500-6217-11eb-941e-07d8b9374fc1.png)

**v7.28**

![image](https://user-images.githubusercontent.com/10086092/106289978-e9ba4280-6217-11eb-9dbc-e1fcb083d67e.png)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 8
 - Operating System: Macos

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by DannyDainton** [comment]
Hey @RezaRahmati 

I'm not seeing this on my side for requests made to https://postman-echo.com/bytes/500/kb?type=json 

![Screenshot 2021-01-29 at 14 58 57](https://user-images.githubusercontent.com/17089546/106290738-b0e39300-6242-11eb-8dc6-ef2d4d6fbb01.png)

Are you seeing the same on your side for this URL? If not, is there anything specific about the request you're making that could just us some issue about what's happening here?

If you could provide a Public URL showing the issue that we can use, that would be awesome 🙏

**Comment by RezaRahmati** [comment]
@DannyDainton I don't know what had happened, seems now working correctly

![image](https://user-images.githubusercontent.com/10086092/106296372-95b35c00-621f-11eb-9790-c9975c5befae.png)

**Comment by DannyDainton** [comment]
Ah cool! That's good news! 🏆 

I'm going to close this issue but if you see this issue again we can reopen it! :D

**Comment by MatthiasPdx** [comment]
I have the same problem right now and it's not showing formatted for me. Should this be reopened? 

I'm on Version 8.0.7 (8.0.7)

![image](https://user-images.githubusercontent.com/56409651/115250370-5853c180-a0de-11eb-86c6-fe7b0a493ee7.png)
