### ISSUE TITLE
Generate collection from schema options via api

### ISSUE THREAD

**Issue by alanwales** [a85/POSTMan-Chrome-Extension#9508]
We are facing a similar issue from other people that whenever we update our api specs and create a new collection via api that we cannot set any of the advanced options e.g.

* Request / Response parameter generation (schema vs example -> seems schema is the default when we want example)
* Folder organization (paths vs tags -> seems also via api that path is default but we want tags)

If there was a way to even set these as "workspace defaults" we would be happy with that, but we cannot control this behaviour via the postman open apis.

Similarly we would want to control these generated collections more and be able to upload pre-request scripts for each operation, ability to publish documentation with automation etc. Right now it's not really usable when you have apis which are changing often and then the linked collection is 'frozen in time' with the old schema

**Comment by lobbin** [comment]
I'm having a similar issue with the documentation/syncWithSchema. The original collection is generated with "Folder organization" = tags and "Disable optional parameters" = true, however, when syncing new changes, these settings are lost for new changes.

**Comment by airoasis** [comment]
I'm having the same issue with the `syncWithSchema` API...

**Comment by stonskt** [comment]
@arlemi I think the API `syncWithSchema` has some bugs like @lobbin stated. Is there a workaround for this issue?

**Comment by clintberry** [comment]
We are trying to generate new collections based on OpenAPI schema and want to be able to control these settings as well. I tried to see if maybe they just weren't documented and copied the properties that are sent via the postman websocket connection. 

```
"collapseFolders": true,
"disableOptionalParameters": true,
"exampleParametersResolution": "Example",
"folderStrategy": "Tags",
"includeAuthInfoInExample": true,
"indentCharacter": "Space",
"keepImplicitHeaders": false,
"optimizeConversion": true,
"requestNameSource": "Fallback",
"requestParametersResolution": "Example"
```


No luck :-) I would love it if you exposed these options to the API and not just the private websocket endpoint. If not, I will have to figure out how postman connects and authenticates to the websocket and send the commands that way... but ugh...

**Comment by chepa92** [comment]
any update on this?

**Comment by shruti-paranjape** [comment]
Thank you for reporting the issue. This feature is now available via the API. You can find all details in this [documentation](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-aab6039a-c565-4c18-b94c-b80381e303ca?ctx=documentation).
