### ISSUE TITLE
error in response section

### ISSUE THREAD

**Issue by Pushpalathahareesh** [a85/POSTMan-Chrome-Extension#9509]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try
	again.</p>

how to resolve above error.

request format
method: used POST
url:http://localhost:5000/init 
body-raw-JSON
{
"id": "dm:342341231233",
"paragraph": "There are rats in the room."
}

regards,
pushpalatha M

**Comment by DannyDainton** [comment]
Hey @Pushpalathahareesh 

This is a response that's coming from your server and it's not an issue with Postman.

I would check the route you've given against the implementation to see if they match, a 404 response code suggests that there isn't a resource at the URL you entered.

I'm going to close this issue as there isn't anything that we can really do to help here.
