### ISSUE TITLE
Enhance Move Request Functionality

### ISSUE THREAD

**Issue by silverbullettruck2001** [a85/POSTMan-Chrome-Extension#9517]
I am using the new version 8, and I have instances where I want to move a request from one collection to another.  

Since we have a lot of collections it's a pain to drag and drop because you have to find the right place on the screen to have the right-hand navigation window to make it scroll down to find the destination collection.  

It would be nice if you could right-click on a request and have a new option for 'Move' and a context window would come up listing the collections in your workspace, and any folders/subfolders, to select the location for where you want to move the request.

Also, it would be nice to be able to move multiple requests using this functionality

**Comment by daokrajaih** [comment]
I would like this improvement as well.

**Comment by silverbullettruck2001** [comment]
I just realized this is duplicate of request [https://github.com/postmanlabs/postman-app-support/issues/6040](6040)
