### ISSUE TITLE
Mouseover on variables not displaying values

### ISSUE THREAD

**Issue by silverbullettruck2001** [a85/POSTMan-Chrome-Extension#9518]
When I put a collection variable into a request body and I mouseover the variable, the variable is displaying in orange, so it is recognized as a valid variable, but it does not provide a popup to display the current value/initial value/scope as it does for other areas.  

I have tried the following to get this to display as it worked in previous versions:
1. double click the variable name to select the variable name text
2. put my mouse cursor in the variable name
3. put my mouse cursor in the curly braces for the variable name
4. highlight the variable name and include the curly braces

No matter what I try or how long I leave my mouse over the variable it does not show the value of the variable.

I am doing this in version 8.0.3

**Comment by vvs11** [comment]
<img width="624" alt="Screenshot 2021-02-15 at 6 59 08 PM" src="https://user-images.githubusercontent.com/4140290/107952530-e4068000-6fbf-11eb-825d-8b3bab75c274.png">
@silverbullettruck2001 I am able to see this. Could you try relaunching the app?

**Comment by silverbullettruck2001** [comment]
I agree that it works correctly in the "URL builder" part of the app, but
the issue that I posted states this is with the 'request body'.

If you change your request to 'Post' instead of 'Get', then go to the
'Body' of the request, change it to 'raw' and build a request body in JSON
format and put a variable in the request it could look something like this:

[image: image.png]

You will see that it senses that it is a variable by the color and styling,
however, no matter how long you put your mouse over, around, or in the
variable on the screen it will not show the value of the variable.

Let me know if there is something I am doing wrong that would correct this
for me.  Thanks!

**Comment by coreyog** [comment]
A year on and this is still happening.

**Comment by malvikach** [comment]
@coreyog @silverbullettruck2001 We have taken note of this behavior need. I do not have an ETA to share as yet to build this. I agree this would be a really helpful feature to quickly understand what value resides in a variable. 

For the time being, I would request you to watch the attached video and use it as a workaround until this behavior is supported.

https://user-images.githubusercontent.com/89449769/151295050-e36ada18-ab76-4c82-8ba1-01bc862875a9.mov


We appreciate you writing to us about it.

**Comment by timabell-newday** [comment]
Another workaround is to temporarily copy the variable into the url and then hover over it 👍 

+1 for this feature request

**Comment by omarboulbaze** [comment]
Thanks @silverbullettruck2001 for the feature request, it would definitely improve the Postman's user experience

**Comment by swildy** [comment]
This is quite problematic for api's that require the posting of json bodies. Yes, while editing the variable name in the body then triggers the display of the value on completion of the variable name, this is pretty inconvenient and does not show the source of the value. Showing the source is very helpful when you have environment variables, collection variables and request variables and are having trouble identifying where the value is coming from.

This thread goes back 18 months. How about addressing this one please.

**Comment by TNGD-YQ** [comment]
I'm quite surprise this post doesn't get much attention. @malvikach Any chance we can have votes ranking like this?
https://feedback.gitkraken.com/
So the community can easily track the feature requests?

**Comment by giridharvc7** [comment]
This can be a bit frustrating, we are looking into how to support this!

Meanwhile you can use Github's sort feature fort the most requested feature asks 
https://github.com/postmanlabs/postman-app-support/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by CodeMonkey80s** [comment]
It works when hovering over the variable in `Authorization` tab:
![Zrzut ekranu 2023-11-23 140512](https://github.com/postmanlabs/postman-app-support/assets/1492142/9aa900ea-34cc-43d9-9ff9-5e8e3807c1a9)


but it does not work in `Body` tab:
![Zrzut ekranu 2023-11-23 140441](https://github.com/postmanlabs/postman-app-support/assets/1492142/32696100-c17a-47cf-b99b-df44db91ebaf)

PostMan Information:
````
Postman for Windows
Version
10.20.0
UI version
10.20.0-ui-231018-1251

Desktop platform version
10.20.0

Architecture
x64

OS platform
win32 10.0.19045
````

**Comment by saket-ranjan-010** [comment]
Hi folks! Happy to announce you can now hover over a variable in your JSON request body to see the variable information like initial and current values and the scope of the variable. Do let me know if this experience helped with your use case or if you have any feedback to make this interaction even better. Thanks!
<img width="1063" alt="Screenshot 2024-02-20 at 8 44 51 PM" src="https://github.com/postmanlabs/postman-app-support/assets/116867391/96c15714-9881-4f94-a8d3-df847b985b50">

**Comment by swildy** [comment]
This is very good news!

I've been looking for this functionality for some time now, and it is very
helpful to see what values are being provided. In the past, when
troubleshooting api's not working I've had to manually overwrite
environment variables in the request body to be sure the expected values
were being sent.

One comment though, I still think there's room for improvement with this
feature as it is not consistent with the way the popups appear for other
variables and appears to be inaccurate. For example, here is a variable I
use for an api URL, whereby the popup clearly shows the value and source
for the variable:

[image: image.png]

Now, here's the same variable used in the request body. The popup actually
provides the wrong value and source, and then provides a comment that the
environment "overwrites" the collection. I think it meant to say
"overrides", but more importantly it is showing the collection value which
is plainly incorrect:

[image: image.png]

Pls let me know when this feature is fully baked.

Thx. Scott.

**Comment by swildy** [comment]
Attachments for comment above - same variable shown in URL vs body...
URL popup: 
![postman_url_variable_popup](https://github.com/postmanlabs/postman-app-support/assets/15275458/80878600-cba5-4637-891c-6926c44427b2)

Body popup:
![postman_body_variable_popup](https://github.com/postmanlabs/postman-app-support/assets/15275458/a4dd6d7e-496f-475c-99f1-af4bc9ab3281)
