### ISSUE TITLE
[8.03] [Mac] There was an error importing this collection. Please try again.

### ISSUE THREAD

**Issue by eyalgrossdev** [a85/POSTMan-Chrome-Extension#9519]
**Describe the Issue**

Getting _There was an error importing this collection. Please try again._ using version 8.0.3 on Mac. Same collection on an older version of postman works.

**Steps to Reproduce**

Click _Run in Postman_ here - https://apidocs.awardforce.com/

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/41741388/106488799-5d787b80-64b4-11eb-90a8-1650a340a2c6.png)

**Environment Information**

 - Platform Type: Desktop
 - Postman Version: 8.0.3
 - Operating System: Mac (Big Sur and Catalina)

**Comment by DannyDainton** [comment]
Hey @eyalgrossdev 

Thanks for raising this against the app - We'll take a look and update the thread once we have more information for you. 🏆 

As a workaround, you can import this Collection with Postman on the Web, you should see that as an option in the `Run In Postman` import flow.

**Comment by mccannt** [comment]
@eyalgrossdev Can you try this again in the most recent version of the app? 
I was able to do this successfully.

**Comment by eyalgrossdev** [comment]
Works! Thanks @mccannt
