### ISSUE TITLE
[8.03] [Mac] Import popup works only once after launching Postman.

### ISSUE THREAD

**Issue by GalaxyZpj** [a85/POSTMan-Chrome-Extension#9520]
**Describe the Issue**

After a fresh launch of Postman, the Import pop (Cmd + O on Mac) works fine for the first time. On opening it the second time, nothing happens, no error, it just won't show up.

**Steps to Reproduce**

- Launch Postman
- Open import popup from File -> Import (or Cmd + O for Mac).
- It should show up as usual. Close it.
- Now try opening it again, nothing happens.

**Screenshots or Videos**

https://user-images.githubusercontent.com/42998576/106501378-148eea00-64e9-11eb-801a-60ac20ea9c81.mov

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: 8.0.3
 - Operating System: macOS Big Sur <Version 11.1>

**Comment by DannyDainton** [comment]
Hey @GalaxyZpj 

I've been able to replicate this issue on my side and I've raised an internal issue with the team - Thank you for flagging this problem. 🏆 

We will update the thread when we have more information.

**Comment by umeshp7** [comment]
Hey @GalaxyZpj! Thanks for reporting this. 

We have fixed this in the latest version of the app v8.0.6. Now you'll be able to use the shortcut and the option from the File menu more than once. 

cc @shashankawasthi88 @DannyDainton

**Comment by umeshp7** [comment]
Similar to #9528

**Comment by lewiscowleschipuk** [comment]
Not sure what I've done wrong to anger the software gods but I am getting this 2021-05-04 on latest, completely vanilla install on OSx Big Sur .3

**Comment by 09samit** [comment]
Import popup not coming.
Postman version 10.0.8
Environment - MacOS 12.2.1 Apple M1 Pro.
