### ISSUE TITLE
Unable to Sign In from Linux Desktop App

### ISSUE THREAD

**Issue by fcosanabria** [a85/POSTMan-Chrome-Extension#9522]
Hello team, 

Basically I'm just trying to sign up un my linux desktop app, but it does not open any tab in order to validate session. 
Here the steps:

- Clicking on the Sign In or Create Account.
![image](https://user-images.githubusercontent.com/37163970/106536430-0b3c5800-64be-11eb-8271-ae338934c752.png)

- After few minutes of the following screen, it just go into a time out screen.
![image](https://user-images.githubusercontent.com/37163970/106536349-e0ea9a80-64bd-11eb-813b-5b775c63a3b6.png)

![image](https://user-images.githubusercontent.com/37163970/106536300-cdd7ca80-64bd-11eb-9937-a1169e5595ea.png)

**Environment Information**

 - Platform Type: Linux Desktop app, Flatplak.
 - Postman Version: 8.0.3
 - Operating System: Red Hat Enterprise Linux 8.3, Gnome version 3.32.2

**Comment by mariooooo** [comment]
The same problem on Windows10

**Environment Information**

- Platform Type: Windows Desktop app
- Postman Version: v8.0.4
- Operating System: Windows 10 Pro, version 20H2, build 19042.685

**Comment by mariooooo** [comment]
@piktonus97m 
this is help me try
https://github.com/postmanlabs/postman-app-support/issues/8717#issuecomment-654905138

**Comment by DannyDainton** [comment]
I'm unable to recreate this in the latest version of the platform, closing this out for not but we can look to reopen if this is still causing you a problem.
