### ISSUE TITLE
Content in "Example Request" is incomplete for request with large payload 

### ISSUE THREAD

**Issue by taehoshino** [a85/POSTMan-Chrome-Extension#9524]
**Describe the Issue**
On documentar page, the content of "Example Request" is incomplete for requests with large payload, e.g. 
https://documenter.getpostman.com/view/13023420/TVYCBLki#bdf9424d-f556-489f-880a-69be1e3934b7

There is no issue when copying the content from the icon below - the whole content can be copied. 
![Screen Shot 2021-02-02 at 12 25 49 pm](https://user-images.githubusercontent.com/55820883/106539286-ccf07880-6551-11eb-871d-7e52bc916360.png)

**Steps to Reproduce**
1. Create an empty collection
2. Import the above request
3. Publish the collection

**Environment Information**

 - Platform Type: Documentar

**Additional Context**
This issue is filed by Product Support according to user report. 

I am not completely sure if this design is intentional or bug. However it would be useful for users to be able to view the complete request, for example by having the "View more" option as for "Example Response".
![Screen Shot 2021-02-02 at 12 29 12 pm](https://user-images.githubusercontent.com/55820883/106539525-47b99380-6552-11eb-8869-346343cac5be.png)

**Comment by Raja-Simha** [comment]
@taehoshino you can scroll horizontally to view the content. Do you think that is not obvious?

We could provide an option to wrap and improve the experience around it.

**Comment by taehoshino** [comment]
@Raja-Simha 
Even scrolling horizontally, in this case the content is getting cut off. Please see the demo link here:
https://www.loom.com/share/cf94a0a27a6342e38d3c175d75fede22

**Comment by Raja-Simha** [comment]
@taehoshino we are working on a fix for this issue

**Comment by taehoshino** [comment]
@Raja-Simha Great! Thanks for the update!

**Comment by mccannt** [comment]
This should now be resolved.
