### ISSUE TITLE
Ability to resolve comments on requests

### ISSUE THREAD

**Issue by meenakshi-dhanani** [a85/POSTMan-Chrome-Extension#9526]
**Is your feature request related to a problem? Please describe.**
I was working in a workspace that I recently moved to public. It had a few comments that were private so I wanted to be able to resolve them like I would resolve inline comments, but there isn't an option to resolve comments on the request. Now that the workspace is public I expect more comments, and I'd like to be able to resolve something to get a sense of all issues/comments I've addressed.

**Describe the solution you'd like**
Need an ability to resolve comments, the way we can for inline comments 
https://learning.postman.com/docs/collaborating-in-postman/commenting-on-collections/#resolving-comments

**Describe alternatives you've considered**
I am manually deleting the comments, the problem is that I won't be able to find them later on.

**Additional context**
![image (5)](https://user-images.githubusercontent.com/14279061/106568303-227c5380-6559-11eb-8626-7254b1218b57.png)

**Comment by akshay-kulkarni-03** [comment]
Hey @meenakshi-dhanani , we are glad to tell you that you can now resolve top request level comments. Ensure you download the latest version of Postman-app to start leveraging this capability :)
