### ISSUE TITLE
Runner collection is missing folder contains

### ISSUE THREAD

**Issue by TienTran1112** [a85/POSTMan-Chrome-Extension#9527]
Hello, I use new postman UI and runner collection. But after run, I cannot find the folder contains my POST request (when hovering mouse in old UI). I try to change many thing in setting. It waste my time during regression test today. Could you please help me?

**Comment by DannyDainton** [comment]
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9464
