### ISSUE TITLE
v8.0.3 after importing collection, shortcuts don't work

### ISSUE THREAD

**Issue by KristofNalesnyik** [a85/POSTMan-Chrome-Extension#9528]
**Describe the Issue**
After importing a collection, shortcuts, like ctrl+W, ctrl+Enter do not work. (alt + scroll works)
I have not tried every shortcut. I only imported collection.

**Steps to Reproduce**
Import a collection.
Open a request. Press ctrl + W to close it.

**Environment Information**
 - Platform Type: Native Desktop App
 - Postman Version: 8.0.3
 - Operating System: win32 10.0.18363 / x64

**Comment by pankajk07** [comment]
@nalesnyik We were able to reproduce this issue and are looking into it.

**Comment by pankajk07** [comment]
@nalesnyik  We have pushed a fix recently that addresses issues with shortcuts and is available in the latest version `8.0.6` . Could you update and confirm if you are still seeing this issue?

**Comment by KristofNalesnyik** [comment]
@pankajk07 Thanks for the fix, it works properly.
