### ISSUE TITLE
Text has too low contrast, to the point of being fuzzy

### ISSUE THREAD

**Issue by NiklasBr** [a85/POSTMan-Chrome-Extension#9529]
**Describe the Issue**

It is hard to read the contents of the user interface. Please allow me to use sharp text with high contrast so that it is readable.

**Steps to Reproduce**

1. Open the app.
2. Use a 1:1 pixel monitor (i.e. no "retina" screens)
2. Be >30 years old ;) 

**Screenshots or Videos**

Example location, and with Windows settings to compare:

![image](https://user-images.githubusercontent.com/279826/106614720-f4543f00-656b-11eb-8fca-c38ea7bdf32a.png)
![image](https://user-images.githubusercontent.com/279826/106615129-69c00f80-656c-11eb-86ab-1e87f3ece9b9.png)

**Environment Information**

 - Platform Type: Desktop App
 - Postman Version: 8.0.3
 - Operating System: Windows 10 Pro

**Additional Context**

Application does not support the Windows accessibility settings for "High contrast" either.

**Comment by Dean-NC** [comment]
This is the main reason I try to avoid using it. I do use it sometimes.

**Comment by chris-torruella** [comment]
Hey everyone, we heard you and I'm excited to share that Postman v11 introduces a whole set of application themes accessible via Settings/Themes. Now you can also sync these with your System preferences. But very importantly, we've also included High Contrast themes for enhanced contrast as needed. We hope these will help to elevate your experience, and we're eager to hear your feedback. Cheers!
