### ISSUE TITLE
eTag for examples/samples for mock server not changing even when the payload of the example is updated

### ISSUE THREAD

**Issue by ArunRajMony** [a85/POSTMan-Chrome-Extension#9534]
**Describe the Issue**

> eTag for an example/sample of a request/response for mock server is not changing even when the payload of the example is updated

**Steps to Reproduce**

1. Create a mock server collection.
2. Create a GET request and save as an example (with payload as JSON). 
3. Postman generates a eTag for the payload in the example and it also sends back the etag when this GET call is made. 
4. now update the saved example's payload. 
5. call the GET request, postman still serves the old etag, the etag has not been updated even though the payload has changed/updated considerably. 

**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 

**Environment Information**

 - Platform Type:  Native Desktop App (used to create and update example for mock request)
 - Postman Version: 7.36.1 (7.36.1)
 - Operating System: MacOs Catalina

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by Dhembla** [comment]
@ArunRajMony, I followed the steps mentioned by you, and I would like to tell you that the mock server returns whatever is stored as part of collection examples. Changing the value of the response body does not update the eTag value in example headers.
You can check the screen record for the same [here]. (https://drive.google.com/file/d/1QSMlYhiSdEiGi9SoL8ga84aJ_cqViICI/view?usp=sharing).

**Comment by Dhembla** [comment]
@ArunRajMony, I am closing the issue as the product is working as expected. Please feel free to reopen it if you think your use case is not satisfied. Thanks!
