### ISSUE TITLE
Can not use placeholder in header name

### ISSUE THREAD

**Issue by bonaluo** [a85/POSTMan-Chrome-Extension#9535]
can not use placeholder in header name

version 8.0.3

**Describe the Issue**

> A high-level summary or description of the problem that you're facing.

**Steps to Reproduce**

> A list of steps that can be followed to recreate the issue.

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/27731323/106709713-e2d46b00-662f-11eb-983e-732cc9fa2f82.png)

**Environment Information**

 - Platform Type: [e.g. Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version:
 - Operating System:

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by DannyDainton** [comment]
Hey @bonaluo 

Could you elaborate more on the issue please and provide some steps to recreate what you're seeing?

![image](https://user-images.githubusercontent.com/17089546/106739858-9417d880-6611-11eb-8b66-6606ad1ec5eb.png)

If you are talking about adding Descriptions to the `auto-generated headers`, this is not something that can be done and the description of the header can be found when the hover over the `i` icon.

![image](https://user-images.githubusercontent.com/17089546/106739896-a3972180-6611-11eb-869d-637272fb1345.png)

**Comment by bonaluo** [comment]
First create two global environment variables.
![image](https://user-images.githubusercontent.com/27731323/106855173-7ae95780-66f7-11eb-86da-ef6536d4595b.png)
Second use them as header name and header value in the placeholder way.
![image](https://user-images.githubusercontent.com/27731323/106855293-a79d6f00-66f7-11eb-96b1-7d1b470f82f6.png)
Third execute request and failed.

**Comment by bonaluo** [comment]
But it dose work in a new workplace.

**Comment by bonaluo** [comment]
I test for several times, the placeholder in header name must be non-global variable

**Comment by bonaluo** [comment]
![image](https://user-images.githubusercontent.com/27731323/108347677-c170a300-721b-11eb-8aaf-e0169e86a7a4.png)

**Comment by DannyDainton** [comment]
Hey @bonaluo 

I'm using v8.0.6 of the app and can resolve a Global variable in the header when using the placeholder

![image](https://user-images.githubusercontent.com/17089546/108354122-f14e8500-71e0-11eb-818d-fea4fd877f91.png)

**Comment by DannyDainton** [comment]
Closing this out due to inactivity - If this is still causing you problems in the latest version of the platform, we can look at reopening it.
