### ISSUE TITLE
Save request hotkey doesn't raise an event.

### ISSUE THREAD

**Issue by Aemilivs** [a85/POSTMan-Chrome-Extension#9543]
**Describe the Issue**

Given a postman request with recent changes to it
When I hold ctrl+s combination
Then nothing happens
And request remains unsaved

**Steps to Reproduce**

1. Create request
2. Introduce any changes
3. Hold ctrl+s

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: v8.0.4
 - Operating System: Windows 10 x64 (10.0.19042, Build 19042)

**Comment by DannyDainton** [comment]
Hey @Aemilivs 

Could you please provide a short recording of this behaviour, please?

Is the request already saved to the Collection or a new unsaved request?

**Comment by Aemilivs** [comment]
Hi @DannyDainton 👋

Seems like the reboot of the PC helped and issue is gone now 🤷‍♂️
The request was already saved to the Collection
