### ISSUE TITLE
Request tab no longer visible after updating to 8.0.4 win32 10.0.18363 / x64

### ISSUE THREAD

**Issue by jstallm** [a85/POSTMan-Chrome-Extension#9547]
**Describe the Issue**

After auto updating today to 
Postman for Windows
**Version 8.0.4
win32 10.0.18363 / x64**

Clicking on an existing collections request no longer opens up request details. Instead, black screen persists

**Steps to Reproduce**

Update to 
Postman for Windows
**Version 8.0.4
win32 10.0.18363 / x64**

Click request

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/6054668/106927031-95efa380-66c6-11eb-9591-21972a040f51.png)

![image](https://user-images.githubusercontent.com/6054668/106941502-ca1f9000-66d7-11eb-96d0-2b30481a388b.jpeg)

**Environment Information**

 - Platform Type: [Native Desktop App]
 - Postman Version: Postman for Windows
**Version 8.0.4
win32 10.0.18363 / x64**
 - Operating System: Windows

**Comment by DannyDainton** [comment]
Hey @jstallm 

Is this still happening if you quit the app and then restart it?

It's hard to get a feel for what's happening with a static image, are you able to provide a quick recording?

**Comment by jstallm** [comment]
@DannyDainton , have you tried to reproduce using the steps to reproduce provided? The issue is still present. Try using the same version I am, click on a collection request, and see if the details of the request show for you. You can even post a screenshot of what you see. Stopping and restarting postman did not resolve. If you are unable to reproduce, please let me know and I'll literally reinstall postman itself. Thank you!

**Comment by jstallm** [comment]
You can see it more clearly here. ![image](https://user-images.githubusercontent.com/6054668/106941402-a0666900-66d7-11eb-8e05-2455aa760ecc.jpeg)

Upon clicking the sidebar, no screen shows( it persists the jetman image)

**Comment by DannyDainton** [comment]
Yep, everything is opening as I expected it too. 😁

The Overview page that's in your screenshot, shows the correct information. Closing that tab, shows the button to open the Overview.

Selecting a request from the collection opens this up in a tab.

The other thing to try is logging out and logging back into the app again?

**Comment by jstallm** [comment]
There is just something strange going on with the tabs and clicking on existing postman collection requests. 

The tab is not showing after I click for existing requests, Which is very unfortunate because I am completely unable to use those requests. 

I noticed that I can create a brand new request and there's no issues if I create a brand new request, but existing requests and existing old collections have problems￼. 

My best guess is the collection schema, either whatever is reading the schema or the schema itself. 

Is there a postman schema validator anywhere? 

Maybe I need to look at request item schema. I can't share collections

**Comment by DannyDainton** [comment]
Are you able to use those requests in the Web view?

https://go.postman.co

If those can be viewed and run from there, it might not suggest any kind of schema validation issue.

**Comment by jstallm** [comment]
Sign off sign on resolved! Thank you.

**Comment by DannyDainton** [comment]
Awesome. That was a weird one - glad it's all done. 

I'm going to close this one out. 🏆
