### ISSUE TITLE
8.0.4 Bootcamp "Environment variables" lesson breaks when opening new request tab

### ISSUE THREAD

**Issue by micka190** [a85/POSTMan-Chrome-Extension#9550]
**Describe the Issue**

When going through the "Environment variables" lesson, once I reach the "Open new request tab" step (47% completion), no popups appear once I open a new request tab, and the lesson hangs there indefinitely.

The "Continue learning" button on the bottom also does nothing once this happens, and manually selecting the "Resume" option from the bootcamp overview simply takes me to a new request tab without any popups.

**Steps to Reproduce**

Simply follow along the "Environment variable" lesson's steps.
Once you open the new request tab, there won't be any other popups telling you how to progress.

**Environment Information**

 - Platform Type: Desktop App
 - Postman Version: 8.0.4
 - Operating System: Windows 10

**Comment by arpitbatra123** [comment]
Hey @micka190 , We've pushed out a fix for this issue. Can you please try going through the lesson again and verify if it works for you?

**Comment by micka190** [comment]
@arpitbatra123 I can confirm that this is working on the 8.0.6 version. Thanks!
