### ISSUE TITLE
[FR] Add flexibility to the aspect ratio on logo in published doc 

### ISSUE THREAD

**Issue by taehoshino** [a85/POSTMan-Chrome-Extension#9552]
**Is your feature request related to a problem? Please describe.**
A recent change to team logo imposes aspect ratio of 1:1 when uploading image to https://go.postman.co/settings/team/general
This also limits the image being used in published doc and needs to comply with 1:1 aspect ratio.

**Describe the solution you'd like**
Add flexibility to aspect ratio, or to allow user to upload/select a different image to use in publishing doc flow. 

**Additional context**
This issue is filed by Product support.

**Comment by taehoshino** [comment]
@godfrzero

**Comment by Ephesoft-Stitus** [comment]
This is a recent issue that was introduced when the ability to select part of an image to use was introduced.  

This feature would be very helpful for our team because it would allow our public facing documentation to look more professional.

**Comment by Raja-Simha** [comment]
@taehoshino and @Ephesoft-Stitus we are looking into this issue. I will get back to you with more updates.

**Comment by graham-saunders** [comment]
@Raja-Simha any updates on this? My company's logo isn't 1:1 so it looks extremely odd in Postman. Thanks!

**Comment by graham-saunders** [comment]
@Raja-Simha per our company branding guidelines, we need to use a full-size logo. 

Here are our postman API docs: https://docs.virtuoussoftware.com

Here is our company website: https://www.virtuous.org

Any chance we can get some movement on this?

**Comment by VladislavLazarov** [comment]
@akshaydeo Hi There! I need assistance in uploading full size logo to a API document page: https://documenter.getpostman.com/view/19439650/2s93JqSQc3

The current one is resized to square. Any chance you can help me on that? Thank you

**Comment by sony-mathew** [comment]
Hi @VladislavLazarov @taehoshino @Ephesoft-Stitus @graham-saunders 

We understand your concerns and challenges with your use case. We've been working on improving this over the course of time. We have removed the restriction of 1:1 aspect ratio. You can upload the images of custom aspect ratios at the moment.

Here is a screenshot of of uploading a logo which is NOT 1:1 aspect ratio:
![Screenshot 2024-09-03 at 12 05 35 AM](https://github.com/user-attachments/assets/57fbcc29-eec5-4dfa-b219-d58a903107d0)

![Screenshot 2024-09-03 at 12 09 32 AM](https://github.com/user-attachments/assets/9065a607-947b-41e5-9a6b-8c20bb53c864)


And here is the how it is displayed in the published documentation page:
![Screenshot 2024-09-03 at 12 06 08 AM](https://github.com/user-attachments/assets/245c580f-ee6b-4048-8ccc-3472ce550b1d)


We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
