### ISSUE TITLE
Double click = open permanently

### ISSUE THREAD

**Issue by DianaLaa** [a85/POSTMan-Chrome-Extension#9555]
**Is your feature request related to a problem? Please describe.**
All tabs in PostMan are opened in some sort of temporary mode, where the title bar is italic. If you click something new in the pane on the left, your italic tab is replaced. This is really frustrating, especially if you just started running a request. I clicked that thing, just stay open! I often want to run multiple requests at the same time. Now I have to keep double clicking that titlebar to force things to stay opened.

**Describe the solution you'd like**
If I choose open a tab, never ever replace it by something else. (I didn't tell you to close. I want it opened, keep it opened. I know what I'm doing, I open these things because I want to run them, I'm not browsing through my collection just to see that I have them...)

**Describe alternatives you've considered**
Acceptable alternative is to Ctrl+Click to explicitly open something in a new tab that should NOT EVER autoclose. Note that I will then be using Ctrl+Click all the time.

**Comment by DannyDainton** [comment]
Hey @DianaKoenraadt 

Do you have the "Always open requests in new tab" enabled?

![image](https://user-images.githubusercontent.com/17089546/107021007-83936980-679b-11eb-812d-62b4c91ba019.png)

**Comment by DianaLaa** [comment]
Huh, I never associated that "opening in new tabs" with "tabs won't close on you". Does the trick though, thanks!

**Comment by DannyDainton** [comment]
Nice to see that it's what you need. 🏆

I'm going to close out this issue.
