### ISSUE TITLE
Automated schema validation for API-linked test collections

### ISSUE THREAD

**Issue by Samgrocock** [a85/POSTMan-Chrome-Extension#9559]
**Is your feature request related to a problem? Please describe.**
We're looking to automate the validation of responses against the defined API schema for individual requests in an API-linked test collection. Currently one can manually validate the requests but somehow there is no way of automating this feature which seems odd. The only alternative I can see is manually inserting each endpoint's schema into each test environment (and maintaining changes over time across both sources - API schema + tests) which would be far from ideal.

**Describe the solution you'd like**
A way of running validation for the individual requests at the same time as running the collection, and being able to export the result along with the collection result.

**Describe alternatives you've considered**
Another possibility would be the ability to import items from the API schema into the test environment to test against.

**Additional context**
-

**Comment by Samgrocock** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9556 but I've added more info here.

**Comment by DannyDainton** [comment]
@Samgrocock

Could you please add your use case to the other open ticket, so the feature request is not across 2 separate issues?  That would really help keep the information centralised.

I'm going to close this one out as you have already mentioned that it's a duplicate issue.

**Comment by Samgrocock** [comment]
This is a shame as Raj’s submission doesn’t really reflect my original request. I’ve added my closed ticket as a comment.

Sam Grocock
Software Developer, Earthsense
+44 (0) 7795 298307 or +44 (0) 116 296 7460
