### ISSUE TITLE
Mac Os 11 (Big Sur) icon style

### ISSUE THREAD

**Issue by niccolomineo** [a85/POSTMan-Chrome-Extension#9560]
Hi, it would be nice if you added the support for the Mac Os 11 (Big Sur) icon style, as per the new Apple's guidelines and resources: https://developer.apple.com/design/resources/

**Comment by niccolomineo** [comment]
Hi, any developments on this?

**Comment by numaanashraf** [comment]
@niccolomineo This will be available in our immediate next release. We are expecting it to start rolling out by end of this week.

Here's a sneak peek and thanks for your patience!

<img width="344" alt="Screenshot 2021-05-13 at 11 03 16 AM" src="https://user-images.githubusercontent.com/3295568/118082563-064f4480-b3db-11eb-9c78-d625709c1d4e.png">

**Comment by numaanashraf** [comment]
We have started rollout of Postman v8.4.0 which includes the updated icon.
