### ISSUE TITLE
Postman lets you import the same environment twice

### ISSUE THREAD

**Issue by romanleshko** [a85/POSTMan-Chrome-Extension#9561]
**Describe the Issue**

When you import an environment that you already imported, Postman doesn't detect that it's a duplicate so you end up with two identical environments.

**Steps to Reproduce**

1. Import an environment .json file
2. Import it again

**Screenshots or Videos**

![Screenshot 2021-02-05 at 18 19 58](https://user-images.githubusercontent.com/14238237/107073051-c460a200-67de-11eb-8abb-652638755f2c.png)

**Environment Information**

 - Platform Type: Desktop App
 - Postman Version: 8.0.4
 - Operating System: macOS Catalina 10.15.7 (19H114)

**Additional Context**

When you try to do the same with a collection you get a popup instead, asking if you want to either replace or import as copy. This would be the expected behaviour for environments as well.

**Comment by TipsyJay** [comment]
Any update on this issue?

**Comment by akshaydeo** [comment]
@TipsyJay we are looking into this issue. I will keep this thread updated as we ship the fix 🙇‍♂️

**Comment by dhwaneetbhatt** [comment]
This is fixed in the latest version. Closing this issue, feel free to reopen it if the issue persists.

**Comment by TGutowski** [comment]
This is still not working in Postman 10.17 on Windows.

**Comment by agrwl-harsh** [comment]
@TGutowski Tried reproducing the error, it seems to be working fine on 10.17 on a windows machine. PFA: screen recording for the same. 

When we try to import a duplicate environment, a few things to note are, 
1. Selecting "Replace" will overwrite the existing environment 
2. Selecting 'Import as Copy' will import it as '<environment_name> copy'

https://github.com/postmanlabs/postman-app-support/assets/99398960/e34abdb7-0f37-44fe-8eb6-c32ea93f0f28

If the problem still persists, can you please share a sample environment JSON which is not working.

**Comment by TGutowski** [comment]
Thank you, @agrwl-harsh , I see my mistake. I was still using the Scratchpad, where this change proably wasn't implemented.
