### ISSUE TITLE
Allow user to select banner or logo for published documentation 

### ISSUE THREAD

**Issue by Ephesoft-Stitus** [a85/POSTMan-Chrome-Extension#9562]
Currently, only the logo is used for public documentation.  However, it would be very helpful if the team could use a banner for published documentation.  Providing the banner helps the page be more on-brand for our organization.

This could look like an option on the publish documentation page to select either the logo or banner as the image shown at the top-left of the documentation page.

**Comment by arlemi** [comment]
We've added the ability to add a custom logo for published documentation in the latest version of Postman (v10.13), try it out! 

More info here: https://learning.postman.com/docs/publishing-your-api/publishing-your-docs/#making-your-documentation-public
