### ISSUE TITLE
PR Submitter Not Getting Emailed On PR Comments

### ISSUE THREAD

**Issue by Ephesoft-Stitus** [a85/POSTMan-Chrome-Extension#9563]
**Describe the Issue**

According to ankit-m on [feature request issue 8021](https://github.com/postmanlabs/postman-app-support/issues/8021), a pull request submitter should receive an email notification for each comment left on their pull request.

However, we are finding that the submitter is only getting emails if @mentioned in the comments.  This is not expected so our team is missing vital communications.

**Steps to Reproduce**
Create a pull request and have a reviewer comment but not @mention you.

**Environment Information**

Postman for Web
Version 8.0.4-210205-0530
Chrome 88 / Windows 10

**Additional Context**
I'm an email admin so I can see every email coming into our platform.   I can confirm that emails ARE being sent to reviewers on pull requests and that when a user @mentions another user an email is sent.  However, the PR submitter is NOT getting emails when a reviewer leaves a comment and does not @mention them.

**Comment by ankit-m** [comment]
@Ephesoft-Stitus currently, we only send notifications when someone is tagged in comments. However, we do recognize the need for sending notifications to reviewers without explicitly tagging them. This is being actively worked upon and you can expect an update soon. I will comment on this thread once the feature has been deployed.

**Comment by Ephesoft-Stitus** [comment]
@ankit-m  - That is great news, thanks for the update!

**Comment by ankit-m** [comment]
We have launched the ability to watch a PR. The PR author will now be notified about any comments left on the PR. Do let us know if this resolves your issue :)

**Comment by Ephesoft-Stitus** [comment]
@ankit-m - Thank you for the update.  I see that feature and will update our team on this, and it should resolve the issue.   FYI: I think the update broke in-line comments on PR's.  Existing comments disappeared after the Watch feature showed up...  I'll submit a separate issue for that.
