### ISSUE TITLE
"code" button no longer there

### ISSUE THREAD

**Issue by thetimetraveler** [a85/POSTMan-Chrome-Extension#9565]
The [documentation describes ](https://learning.postman.com/docs/sending-requests/generate-code-snippets/#generating-code-snippets-in-postman) how Postman can be used to generate code snippets (e.g. curl command) by clicking a "code" button right next to the cookies button. However with the latest update, this button is no longer there. I also can not find it anywhere else.

**Comment by DannyDainton** [comment]
Hey @thetimetraveler 

The code option has been moved into the right side context menu, the comment and thread below will show you what this can be located. 

https://github.com/postmanlabs/postman-app-support/issues/9475#issuecomment-768580478

All the documentation is in the process of getting updated, as you can appreciate, with the amount of changes to the UI in V8 this can take a little bit longer. 😁

**Comment by thetimetraveler** [comment]
oh wonderful. thank you so much for the fast response. 

I got a little nervous as that's my most used feature

**Comment by DannyDainton** [comment]
It's still very much there, we love it too 😍
