### ISSUE TITLE
Postman App Address Bar Issue : Editing issues in long url

### ISSUE THREAD

**Issue by arneesh** [a85/POSTMan-Chrome-Extension#9570]
**Describe the Issue**

When a long URL with a couple of variables like {{host}}, {{user_id}} and a query parameter like api_key is used, it gets really annoying to edit it, 2-3 words can't be selected together using shift and erased at once, often I have to delete 1 character at a time. 

Also, when the URL is long and contains a few query parameters like filters then even copying stuff has issues and I can't remove the query param filter object in one selection, have to backspace characters one by one from the end. Kindly resolve this issue as soon as possible as it is really irritating to work with long URLs.

**Steps to Reproduce**

Just Post a long address inside the address bar of the postman with variables and few query params.

**Comment by DannyDainton** [comment]
Hey @arneesh 

All the query params you are editing in the URL, are also in the `Params` tab of the request, which _should_ make it easier for you to change:

Key-Value Edit

![image](https://user-images.githubusercontent.com/17089546/107346010-1abe3100-6abc-11eb-942a-109691a15e46.png)

Bulk Edit

![image](https://user-images.githubusercontent.com/17089546/107346087-36293c00-6abc-11eb-8bf9-4a2f34ac35da.png)

With the Key-Value Edit, you can pick individual params that could be anywhere in the URL and erase them and wiith the Bulk Edit option, you can select all and delete all the params from the URL.

**Comment by arneesh** [comment]
Hey @DannyDainton 
Ya of course that how I manage my static query params. I am talking about dynamic query params here. Those query params can be anything from a huge range of combinations - I will provide a bit more context.

I have an analytics platform with complex filters. There are around 30 filters and each filter has at least 4 operators -> such as "is, is not, between, equals, not equals, in(substring) " etc and these operators vary as per data type, text has different operators, numbers have different, date have different and trees have different. Each lower-level filter has { key: '', operator: '', value ''}, structure but these can be grouped any way my clients want to filter products using AND - OR combination on each filter level and can also make these combinations between filter groups. As the clients can make any complex combination, I can't add this manually to params tab as combinations can be literally anything. They work well in URL params are then they have used as different places, inside my platform, inside our client's platform, in emails and also in my widgets that my clients install.
In order to test stuff if a client faces some issue with some products, I need to query this using my postman, but editing this is a complete nightmare as these are large filter objects and editing in postman doesn't work properly, and then I have to backspace these URL's from the end. Sometimes I just use curl from my terminal, but as I am paying for postman so of course, I should be able to use the tool, instead of having to run these commands in curl as if I have to use curl for my most important use case then what is the point of me paying for Postman?

**Comment by DannyDainton** [comment]
Can you also provide some images of the things you're explaining, as those are UI based elements, it would clear up any misunderstanding by seeing them 😄

**Comment by vvs11** [comment]
@arneesh Could you share some screenshots of your use-case? It'll help us understand the issue better

**Comment by DannyDainton** [comment]
Hey @arneesh  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
