### ISSUE TITLE
Release New Postman v8 to the Ubuntu snap tool

### ISSUE THREAD

**Issue by lflucasferreira** [a85/POSTMan-Chrome-Extension#9573]
I would like to see the new Postman v8 version available in the snap command 

```bash
$ snap info postman

name:      postman
summary:   API Development Environment
publisher: Postman, Inc. (postman-inc✓)
store-url: https://snapcraft.io/postman
contact:   https://github.com/postmanlabs/postman-app-support/issues
license:   unset
description: |
  Postman is the collaboration platform for API development, used by 8
  million developers and 400,000 companies worldwide. Postman is an elegant,
  flexible tool for building connected software via APIs quickly, easily, and
  accurately. Postman is a global company with headquarters in San Francisco,
  a large office in Bangalore (where the company was founded), and
  distributed team members on four continents. Postman is privately held,
  with funding from Nexus Venture Partners and CRV.
commands:
  - postman
snap-id:      fFcOtEEF4EdyYb95IUE5Isy28tICYMLf
tracking:     latest/stable
refresh-date: today at 09:42 -03
channels:
  latest/stable:    7.36.4 2021-02-08 (132) 183MB -
  latest/candidate: 7.36.4 2021-02-08 (132) 183MB -
  latest/beta:      7.36.4 2021-02-08 (132) 183MB -
  latest/edge:      7.36.4 2021-02-08 (132) 183MB -
  v7/stable:        7.36.1 2021-01-27 (130) 183MB -
  v7/candidate:     ↑                             
  v7/beta:          ↑                             
  v7/edge:          ↑                             
  v6/stable:        6.7.6  2019-10-23  (95) 138MB -
  v6/candidate:     ↑                             
  v6/beta:          ↑                             
  v6/edge:          ↑                             
installed:          7.36.4            (132) 183MB -
```

**Comment by elahens88** [comment]
waiting

**Comment by eroaespinosa** [comment]
snap info postman 
name:      postman
summary:   API Development Environment
publisher: Postman, Inc. (postman-inc✓)
store-url: https://snapcraft.io/postman
contact:   https://github.com/postmanlabs/postman-app-support/issues
license:   unset
description: |
  Postman is the collaboration platform for API development, used by 8 million developers and
  400,000 companies worldwide. Postman is an elegant, flexible tool for building connected software
  via APIs quickly, easily, and accurately. Postman is a global company with headquarters in San
  Francisco, a large office in Bangalore (where the company was founded), and distributed team
  members on four continents. Postman is privately held, with funding from Nexus Venture Partners
  and CRV.
commands:
  - postman
snap-id:      fFcOtEEF4EdyYb95IUE5Isy28tICYMLf
tracking:     latest/stable
refresh-date: 11 days ago, at 08:58 -04
channels:
  latest/stable:    7.36.4 2021-02-08 (132) 183MB -
  latest/candidate: 7.36.4 2021-02-08 (132) 183MB -
  latest/beta:      7.36.4 2021-02-08 (132) 183MB -
  latest/edge:      7.36.4 2021-02-08 (132) 183MB -
  v7/stable:        7.36.1 2021-01-27 (130) 183MB -
  v7/candidate:     ↑                             
  v7/beta:          ↑                             
  v7/edge:          ↑                             
  v6/stable:        6.7.6  2019-10-23  (95) 138MB -
  v6/candidate:     ↑                             
  v6/beta:          ↑                             
  v6/edge:          ↑                             
installed:          7.36.4            (132) 183MB -

**Comment by bean5** [comment]
I'm seeing similar results. Latest version is 7.35.5 and not even edge provides option to use the latest. :(

For now I'm forced to download and install another way so I can have v8 functionalities that coworkers are now using.

```
# snap info postman
name:      postman
summary:   API Development Environment
publisher: Postman, Inc. (postman-inc✓)
store-url: https://snapcraft.io/postman
contact:   https://github.com/postmanlabs/postman-app-support/issues
license:   unset
description: |
  Postman is the collaboration platform for API development, used by 8 million developers and
  400,000 companies worldwide. Postman is an elegant, flexible tool for building connected software
  via APIs quickly, easily, and accurately. Postman is a global company with headquarters in San
  Francisco, a large office in Bangalore (where the company was founded), and distributed team
  members on four continents. Postman is privately held, with funding from Nexus Venture Partners
  and CRV.
commands:
  - postman
snap-id:      fFcOtEEF4EdyYb95IUE5Isy28tICYMLf
tracking:     latest/stable
refresh-date: today at 09:33 MST
channels:
  latest/stable:    7.36.5 2021-02-22 (133) 183MB -
  latest/candidate: 7.36.5 2021-02-22 (133) 183MB -
  latest/beta:      7.36.5 2021-02-22 (133) 183MB -
  latest/edge:      7.36.5 2021-02-22 (133) 183MB -
  v7/stable:        7.36.5 2021-02-22 (133) 183MB -
  v7/candidate:     ↑                             
  v7/beta:          ↑                             
  v7/edge:          ↑                             
  v6/stable:        6.7.6  2019-10-23  (95) 138MB -
  v6/candidate:     ↑                             
  v6/beta:          ↑                             
  v6/edge:          ↑                             
installed:          7.36.5            (133) 183MB -
```

**Comment by bean5** [comment]
So the patch version has been ticking up, but not minor or major versions.

**Comment by bean5** [comment]
See also #6888. Is there an automatic process to update snaps or do we need to get a particular team member's attention?

@numaanashraf ?

**Comment by DannyDainton** [comment]
Hey folks 👋 ,

We are currently in the process of rolling out V8 to all users and all distributions channels. 

Snap is currently being worked on and should be available in the next few weeks.

**Comment by i5o** [comment]
Also looking forward to this one.
Just came accross this issue by googling about postman latest release.

I personally have problems with current 7.36.5 - it freezes sometimes, and the icon won't even show in the launcher until I close another window in Ubuntu 20.10.

So I just wanted to update but no snap release yet.

**Comment by bean5** [comment]
We're excited! Is there a timeline on it?

**Comment by lflucasferreira** [comment]
I just gave up.

I installed it manually, follow this instruction if you are anxious like me:
[https://gist.github.com/lflucasferreira/62f54cd41aa5608431c704e1ff7e4b81](https://gist.github.com/lflucasferreira/62f54cd41aa5608431c704e1ff7e4b81)

**Comment by numaanashraf** [comment]
Postman v8.0 is on a dedicated release channel on snap now. 

Existing users on stable track can switch to this channel using
`snap refresh postman --channel=v8`

New users can install this channel using:
`snap install postman --channel=v8`

**Comment by bean5** [comment]
@numaanashraf any reason why version 7 is still the default on snap? I don't think it is the default if I download manually.

**Comment by falnyr** [comment]
bump @numaanashraf

**Comment by arxeiss** [comment]
Any updates? Thank you

**Comment by tengl** [comment]
It feels like Linux isn't really a prioritized platform. Latest Postman version is v9.1.3. The snap is still on 8.12.5 (which isn't listed in the [release notes](https://www.postman.com/downloads/release-notes/)) and the download version for Linux is 8.12.4.

**Comment by mebteaching** [comment]
Hi, just found they updated the channel to v9 which brings the latest version, so the following command worked for me !

`snap refresh postman --channel=v9`

and probably for a fresh install, the following will work (I didn't test it)
`snap install postman --channel=v9`

**Comment by dregad** [comment]
That's great, thanks @mebteaching for the heads up !

Still it would be nice if @postman-support could update the _latest_ channel to actually point to the latest version instead of 7.3.5 as it currently does (which is even behind the v7 channel).

Extract from `snap info postman` as of today
```
channels:
  v8/stable:        8.12.5 2021-10-28 (149) 176MB -
  v8/candidate:     ↑                             
  v8/beta:          ↑                             
  v8/edge:          8.12.5 2021-10-28 (149) 176MB -
  latest/stable:    7.36.5 2021-02-22 (133) 183MB -
  latest/candidate: 7.36.5 2021-02-22 (133) 183MB -
  latest/beta:      7.36.5 2021-02-22 (133) 183MB -
  latest/edge:      8.5.0  2021-05-21 (139) 198MB -
  v9/stable:        9.4.1  2021-12-10 (155) 191MB -
  v9/candidate:     ↑                             
  v9/beta:          ↑                             
  v9/edge:          9.4.1  2021-12-10 (155) 191MB -
  v7/stable:        7.36.7 2021-11-25 (152) 183MB -
  v7/candidate:     ↑                             
  v7/beta:          ↑                             
  v7/edge:          7.36.7 2021-11-25 (152) 183MB -
  v6/stable:        6.7.6  2019-10-23  (95) 138MB -
  v6/candidate:     ↑                             
  v6/beta:          ↑                             
  v6/edge:          ↑                             
```

**Comment by numaanashraf** [comment]
Closing this as v8 and v9 is available on snap. v9 is the default track and will be used for all new installs.

**Comment by andrew-demb** [comment]
@numaanashraf as of https://github.com/postmanlabs/postman-app-support/issues/9573#issuecomment-991947827 and current fetching information from snap - `latest` channel pinned to v7 version of postman.

Is it planned to change `latest` channel to v9?

**Comment by NicoHaase** [comment]
> Closing this as v8 and v9 is available on snap. v9 is the default track and will be used for all new installs.

According to https://snapcraft.io/postman, v7.36.5 is the default version to be installed. Is there any chance to change this? Also, users who installed v7 don't receive any updates. They have to change the track manually to receive a new version - is there any good reason for this?
