### ISSUE TITLE
Open API example is not set correctly for parameters

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9574]
**Describe the Issue**

A valid Open API v3 definition is not setting example correctly in Postman

**Steps to Reproduce**

**valid definition:**

```
openapi: 3.0.0
info:
  version: '1'
  title: sd
servers:
  - url: 'http://localhost:3000'
paths:
  /{processDefinitionKey}/user:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: string
            format: int32
          example: somestring
        - name: processDefinitionKey
          in: path
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
          example: 45
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

**Validate it at :**

https://editor.swagger.io/

**Screenshots or Videos**

**Output in swagger editor:**
![image](https://user-images.githubusercontent.com/45095911/107275503-c24e4b80-6a49-11eb-848d-cfa0a9d50ffa.png)

**Output in Postman**
![image](https://user-images.githubusercontent.com/45095911/107275577-dbef9300-6a49-11eb-91e5-077cf2c21686.png)

**Environment Information**

 - Platform Type: [ Native Desktop App , Postman On The Web, Web Dashboard]
 - Postman Version: 8.0.4
 - Operating System: windows 10

**Additional Context**

Should work as per swagger editor

**Comment by VShingala** [comment]
@praveendvd Thanks for reporting this issue. We are already working on this issue as part of this [discussion](https://github.com/postmanlabs/postman-app-support/issues/9080#issuecomment-712899314). The fix is done on our open-source module and will be available on App around next week.

**Comment by VShingala** [comment]
@praveendvd Closing this as fix was available long time ago. i.e. below is the imported collection's request showed in the issue after fix.

![image](https://user-images.githubusercontent.com/16756296/155379504-6fa8735a-943a-45ff-80e4-19870b9927c6.png)
