### ISSUE TITLE
Sending bulk invitations to users needs Improvement

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#9577]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to invite bulk users is through uploading a csv from a workspace in Postman. This requires an admin to navigate to a workspace just for bringing in users onto Postman (which is not discoverable or mentioned in manage team page where the invitation option exists)

**Describe the solution you'd like**
- Have this feature discoverable in the manage team page maybe?
- Have options to import contacts from Google/ Slack/ etc and send invitations- which is an easier option to send out invitations

**Comment by ArjunSingh-PM** [comment]
We have added the option to bulk invite users by uploading a csv file at the manage team page as well. 
![image](https://user-images.githubusercontent.com/53265429/195309824-40b05fcf-228e-4214-a846-5911878c7bd5.png)

**Comment by emiliomartin84-uc3m** [comment]
What about accept all pending invitations?

**Comment by ArjunSingh-PM** [comment]
@emiliomartin84-uc3m Currently, we do not have the option to bulk accept pending invites. However, we will be adding this option in the near-term. Thanks!
