### ISSUE TITLE
Keyboard shortcuts are not working

### ISSUE THREAD

**Issue by gvsandeep2647** [a85/POSTMan-Chrome-Extension#9578]
**Describe the Issue**

> Some keyboard shortcuts like `Cmd + W` and `Cmd + S` are not working in the Mac App

**Steps to Reproduce**

> Install the latest version and trying doing the above actions

**Environment Information**

 - Platform Type: Mac Desktop App
 - Postman Version: Version 8.0.4 (8.0.4)
 - Operating System:  macOS Big Sur v11.2

**Comment by kamalaknn** [comment]
Hey @gvsandeep2647 

Would you mind restarting your app and sending a screen recording of the issue you are seeing? Could you also share your logs from `View -> Developer -> View logs in Finder` to `help@postman.com`?

This would help us identify the issue and resolve it faster.

**Comment by gvsandeep2647** [comment]
Sent. Restart has solved the problem though

**Comment by pankajk07** [comment]
@gvsandeep2647 Good to know that restarting the app solved the problem. Would like to know the detailed steps to reproduce the issue and fix the issue at its core. Please share the detailed steps to reproduce the issue.

**Comment by gvsandeep2647** [comment]
I didn't do anything particular to generate the issue. It happened somehow. Restarting worked. I have sent the logs via mail on the e-mail id and have tagged this issue in that.

**Comment by davidtimmsinshur** [comment]
I have also experienced this, and restarting the app fixed the issue. This was a clean install (not an upgrade) and I am on Catalina 10.15.7/ Postman 8.0.3
I am also unaware of at what point the shortcuts stopped. I am new to mac after using Windows and so I am still learning the new shortcuts.

**Comment by gvsandeep2647** [comment]
Although restarting the app helps, but this happens very frequently. Please try to fix this.

**Comment by kamalaknn** [comment]
@gvsandeep2647 @davidtimmsinshur We have pushed a fix recently that addresses issues with shortcuts after going through import flows. Could you update to the latest version 8.0.6 and confirm if you are still seeing this issue?

**Comment by gvsandeep2647** [comment]
Occurring frequently in this version as well: **Version 8.0.5 (8.0.5)**

**Comment by pankajk07** [comment]
@gvsandeep2647 We have pushed a fix recently that addresses issues with shortcuts and is available in the latest version `8.0.6`. Could you update and confirm if you are still seeing this issue?

**Comment by itutil** [comment]
Team, the bug returned in the latest release: can't perform intelligent selection and copy of multiple values, vertically stacked, every one between brackets.

**Comment by taylor-lindores-reeves** [comment]
Can confirm I am unable to select the next occurrence selected by the cursor with SHIFT + ꜜ
