### ISSUE TITLE
Open in new tab doesn't work

### ISSUE THREAD

**Issue by Soldier2003** [a85/POSTMan-Chrome-Extension#9580]
**Describe the Issue**

> Nothing happens when I click on Open in new tab

**Steps to Reproduce**

> 1. Open your collection; 2. Click the right button a mouse on request; 3. Select option Open in new tab

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/78794669/107352240-a942aa80-6adc-11eb-8233-0420f2794723.png)

**Environment Information**

 - Platform Type: Desktop App
 - Postman Version: 8.0.4
 - Operating System: Windows 10

**Comment by DannyDainton** [comment]
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9493
