### ISSUE TITLE
When a variable is empty it is automatically removed after sending request.

### ISSUE THREAD

**Issue by Hrafnkellos** [a85/POSTMan-Chrome-Extension#9581]
**Describe the Issue**

When i'm using an empty environmental variable.
In my case **port** is empty in all scenarios except when working on localhost.
The variable disappears from my environment when left empty.

**Steps to Reproduce**

Create a variable with and empty value.
Try sending one request, then the variables should be removed from your environment.

![image](https://user-images.githubusercontent.com/2863090/107354423-0aab4f00-6ac6-11eb-9e11-97bdd21bce2d.png)

**Comment by DannyDainton** [comment]
Hey @Hrafnkellos 

Which version of the app are you seeing this issue happening?

I just tried this on the latest version of the app and couldn't recreate the issue. Do you have the `port` variable referenced somewhere in the collection or have any scripts that might be doing something like `pm.environment.unset('port')` etc.

It would be great if you could provide a short recording of the problem so we can see what's going on from your side 😄

**Comment by Hrafnkellos** [comment]
hi you are correct there is a port unset 😅sorry this is a non issue then.

**Comment by DannyDainton** [comment]
That's all good - It seemed strange to have it completely cleared like that from sending a request 😄 

Glad to see you're all sorted 🏆
