### ISSUE TITLE
Documentation is not scrollable using keyboard in postman app and web

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9591]
**Describe the Issue**

> User cannot scroll through the documentation section using keyboard

**Steps to Reproduce**

> https://github.com/postmanlabs/postman-app-support/issues/9480

use this documentation: https://www.postman.com/crimson-sunset-709132/workspace/public/documentation/8296678-8b22cd36-d1de-4299-8381-f6a438151663

**Environment Information**

 - Platform Type: [e.g Native Desktop App, Postman On The Web, Web Dashboard]
 - Postman Version: v8.0.5
 - Operating System: wind 10

**Additional Context**

User should be able to scroll down using key board and mouse

**Comment by ankitjaggi** [comment]
Closing this since this has been fixed in the latest version.
