### ISSUE TITLE
Resize the request tab to see the description above, after reaching the bottom, unable to adjust the request window.

### ISSUE THREAD

**Issue by Pricilla09** [a85/POSTMan-Chrome-Extension#9593]
**Describe the Issue**

> When trying to resize the request tab for viewing description, I dragged to the bottom, After that I am unable to adjust the size, I have to close and reopen the request.

**Steps to Reproduce**

> Open any request.
> Drag the request window to type/view the description of the request.
> Drag completely to the bottom of the window.

**Screenshots or Videos**

https://user-images.githubusercontent.com/71498483/107612591-87365d00-6c81-11eb-9d4c-bf1241ca2eae.mp4

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: v7.36.4
 - Operating System: Windows

**Comment by coditva** [comment]
@Pricilla09 Thanks for writing in! We've fixed this bug in the latest Postman app version 8. You can get it from the [download page](https://www.postman.com/downloads/). You can also try it in your web browser: https://go.postman.co/build

**Comment by DannyDainton** [comment]
Closing this as the issue has been fixed in later versions of the platform.
