### ISSUE TITLE
Confirmation tab before deleting the Workspace by typing the "Workspace Name" itself.

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#9595]
**Is your feature request related to a problem? Please describe.**
Sometimes accidentally the workspace gets deleted with just 2 clicks.

**Describe the solution you'd like**
It would be a good feature to type the "workspace name" before deleting it. Same as GitHub & AWS does while deleting the repo & S3 bucket respectively.
<img width="823" alt="delete_bucket" src="https://user-images.githubusercontent.com/52168965/107628983-74bf2200-6c87-11eb-9aae-c9bd80cc6f17.png">

**Comment by akshay-kulkarni-03** [comment]
Hi @Swapnil-getpostman , thanks for feedback. This feedback was also reported by other postman users and we updated the `Delete Workspace` modal which now asks the user to type in the `workspace name` before deleting it. Please ensure you have the latest version of postman app to have this experience.

Feel free to open this issue again if you face any issue.
