### ISSUE TITLE
Response Body display is truncated for one entity but shown for another entity of the same OData service

### ISSUE THREAD

**Issue by SagarInvenio** [a85/POSTMan-Chrome-Extension#9597]
**Describe the Issue**
I am testing an Odata service which I need to expose to an external system. In the Odata service, I have 2 Entities. Postman is clearly "Get" ing the content of the first Entity in the Response body, but is not "Get" ing the content in the Response body of the second service. 

**Steps to Reproduce**
1. Open POSTMAN, enter the URL for the Service - http://******:****/sap/opu/odata/******/MM_MASTER_CDS/xIBSCMSxLANG
2. Enter the basic authentication details
3. Hit the "Send" button
4. Entire Response Body is shown
5. Open POSTMAN for the Service - http://******:****/sap/opu/odata/******/MM_MASTER_CDS/xIBSCMSxMM_MASTER
6. Enter the basic authentication details
7. Hit the "Send" button
8. Response body is truncated.
9. Open the same URL above in Chrome / Firefox. 
10. Hit the "Enter" or "Go" button
> A list of steps that can be followed to recreate the issue.

**Screenshots or Videos**
1. Entire response for the correct call
![image](https://user-images.githubusercontent.com/76476652/107647980-caa0c380-6ca1-11eb-9860-a994c54621fc.png)

2. Truncated response for the other Entity
![image](https://user-images.githubusercontent.com/76476652/107647864-9f1dd900-6ca1-11eb-8cdc-4a1065aaa9d8.png)

3. Call in Chrome / Firefox which gives the total response. 
![image](https://user-images.githubusercontent.com/76476652/107649514-8a424500-6ca3-11eb-8e33-481996e77531.png)

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: v8.0.5
 - Operating System: Windows 10

**Additional Context**

> Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.

**Comment by mohitranka** [comment]
@SagarInvenio Can you 

1.) Confirm that the data is also truncated in the 'raw' tab?
2.) share scenario where it can be reproduced without sensitive/private data?

**Comment by SagarInvenio** [comment]
Hi Mohit, 

1. Yes I can confirm that the data is truncated in the 'raw' tab as well. 
2. Although the data itself is not sensitive, the server details and the login details required to access the service are proprietary. Is there a way to share the authentication information privately. Do not want to share the information here since this is a public forum...? 

Thanks and Best Regards,
Sagar Ogale

**Comment by mohitranka** [comment]
@SagarInvenio You can reach out to postman.com/support and create a ticket.

**Comment by SagarInvenio** [comment]
Thank you Mohit. I have raised a ticket for the same.
