### ISSUE TITLE
Restore of Postman window does not restore to original position

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#9598]
Filling out for user

**Describe the Issue**

> When I launch Postman and tile it to the left half of my screen, then minimize and restore the window, it does not place the postman window back to the right spot. The title bar hides behind my taskbar (located at top of screen). Please note my taskbar is at the top of my screen. Postman is the only application which does this. I've tested with all my other apps.

**Steps to Reproduce**

1. Launch Postman native app in Windows
2. Tile it to the left half of my screen
3. Then minimize and restore the window, it does not place the postman window back to the right spot

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/5624835/107688932-10876880-6c5d-11eb-9fcf-aea121d3a5c6.png)

**Environment Information**

 - Platform Type: Native App
 - Postman Version: '8.0.5-win32-x64'

**Additional Context**

**Comment by t7yang** [comment]
Yes, This is terrible. Why assume user always place taskbar on bottom.
I don't think they going to fix this, because you can not move taskbar on Windows 11 anymore 😑

**Comment by OtherLeadingBrand** [comment]
In the latest version of the Windows Desktop application there are no windows controls. The screen cannot be minimized and one must resort to Windows-D to hide the application.

**Comment by Beckfield** [comment]
A seriously annoying bug.  The same is true when starting the app, not just minimize/restore.

**Comment by Beckfield** [comment]
> In the latest version of the Windows Desktop application there are no windows controls. The screen cannot be minimized and one must resort to Windows-D to hide the application.

This is not true in my case.  I have version 9.12.2, which I believe is the latest (so it tells me).  Window controls are still there.

**Comment by swantzter** [comment]
Well I guess windows 11 "solves" this by plain out not allowing you to have the taskbar at the top -_-

**Comment by sandmanx24** [comment]
Screenshot to illustrate issue of Postman opening behind the Task Bar at the top of the screen. In Windows 11, the Task Bar is not easily moveable, so this is now more of an issue.
![Windows11_Postman_Start_2022-02-28_07-08-49](https://user-images.githubusercontent.com/7471107/155981689-f0aed288-b999-47ea-b369-4f445bf97a55.jpg)

**Comment by dsanders11** [comment]
This should be fixed in Postman version v9.16.0 and newer, so I'm going to close this issue. If you're still seeing the problem on the latest versions of Postman, please comment and feel free to ping me and we'll take a look. Thanks!

**Comment by Beckfield** [comment]
Currently on 9.17.2, and it does indeed appear to be fixed.  Thanks!
