### ISSUE TITLE
Tab is not shown/displayed properly when selected. Old bug #5840

### ISSUE THREAD

**Issue by Petruciu** [a85/POSTMan-Chrome-Extension#9599]
**Describe the bug**
When I click on a request in the collection, the request details are not displayed on the right-hand side.

**Steps To Reproduce**

1. Go to any request in the collection
2. Click on any request
3. Nothing is shown on the right-hand side
4. Expected behavior
5. Show request details

Right click on request > Open in tab don't work (

Also Environment tabs cannot be opened

**Screenshot:**
![image](https://user-images.githubusercontent.com/61961473/107734362-dfaf3e00-6d05-11eb-80d8-1bfe3ac6d55f.png)

**Environment Information**

![image](https://user-images.githubusercontent.com/61961473/107734609-7b40ae80-6d06-11eb-955f-964b05bc851f.png)

**Additional Context**

[[Postman logs] Tab is not shown-displayed properly when selected.txt](https://github.com/postmanlabs/postman-app-support/files/5969873/Postman.logs.Tab.is.not.shown-displayed.properly.when.selected.txt)

**Comment by DannyDainton** [comment]
Hey @Petruciu

Sounds a bit too basic but could you sign out and sign back in again - sometimes it's the simple things that do the trick. 😅

There was an issue with the `Open in tab` option but this was fixed in 8.0.5, which it looks like you're using. 🤔

**Comment by Petruciu** [comment]
i deleted folder "Postman" from Roaming
%appdata%/postman.
and reinstalled the Postman.
and all is Ok
