### ISSUE TITLE
[Bug] Curl import with --data-urlencode adds single quotes

### ISSUE THREAD

**Issue by pboos** [a85/POSTMan-Chrome-Extension#960]
Importing the following curl creates wrong parameters.

```
curl http://someserver.com -X POST --data-urlencode 'action=test' --data-urlencode 'type=another'
```

Problem:
- First paramater has a value ending with a single quote
- Last parameter has a key starting with a single quote

I tested with multiple parameters and moving them around. it is always the first and the last one as described in the problem.

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll push a fix in the next release.

**Comment by abhijitkane** [comment]
This has been fixed in the latest version.  @pboos  Can you confirm?

**Comment by pboos** [comment]
@abhijitkane Great! I can confirm that it is now working as expected. Thank you for the quick fix!
