### ISSUE TITLE
Slow to start

### ISSUE THREAD

**Issue by hfsrazzimonti** [a85/POSTMan-Chrome-Extension#9602]
**Describe the Issue**

> When starting Postman, it takes a long time to load and show IDE

**Steps to Reproduce**

> Start Postman 8.0.5 in Windows 10. Actually Postman has always been slow to start but this last version even slower.

**Screenshots or Videos**

> Please add screenshots or a short video to help visually explain the problem. 
> Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 

**Environment Information**

 - Platform Type: Windows 10 laptop
 - Postman Version:8.0.5
 - Operating System: Windows 10

**Additional Context**

> We would like a setting to disable all extra features that may slow Postman to start. We just need a simple IDE to send requests and see responses, that's all.

**Comment by royparsaoran** [comment]
My Postman Version 8.0.5 issue:

1. Slow when opening
2. Sometimes error not loading any env 
3. Sometime error cannot use shortcut

**Comment by Loongle** [comment]
Postman Version 7.36.5.
 The startup time is no problem. I guess the new version is slow to load collection content online, but the old version does not have this problem

**Comment by DannyDainton** [comment]
There have many performance-based improvements since this was reported. Check out the latest version of the platform. 

Closing this issue out for now, due to this being related to older versions.
