### ISSUE TITLE
Not all environment variables get synced or exported

### ISSUE THREAD

**Issue by landonvg** [a85/POSTMan-Chrome-Extension#9603]
**Describe the Issue**
Not all environment variables get synced or exported.

**Steps to Reproduce**
With one or more environments with several values, try syncing to a different machine or exporting the environment(s).  Check the values on the synced machine or exported file(s).

**Screenshots or Videos**
Source data:
![image](https://user-images.githubusercontent.com/3535272/107809496-6e34b700-6d28-11eb-89af-732a36356b36.png)
Exported file (note that fields after "sessionid" are empty):
![image](https://user-images.githubusercontent.com/3535272/107809542-83114a80-6d28-11eb-9ab4-a0175e79c0f8.png)

**Environment Information**
Postman for Windows
Version 8.0.5
win32 10.0.18363 / x64
Windows 10

**Comment by DannyDainton** [comment]
Hey @landonvg

Are the same values in the `Initial Value` too, can only see the `Current Value` in the image.

Any value _only_ in the `Current` field wouldn't be part of the export file or syncd anywhere outside of that machine.

**Comment by landonvg** [comment]
Ah, that's it--only the fields with an initial value are exported.  Why is that?  Now I have to go populate all those missing initial values.

**Comment by DannyDainton** [comment]
Those are session variables that only you see and are not seen by team members etc.

https://learning.postman.com/docs/sending-requests/variables/#sharing-and-persisting-data

There should be an option in the environment section to move those to both using a button click. 😁

**Comment by DannyDainton** [comment]
I believe that this solves the problem that you're facing so I'm going to close out this issue. 🏆

**Comment by landonvg** [comment]
@DannyDainton Using "Persist" solved part of the problem.  The initial values are now synced up, but they are not getting used.  When I mouse over the placeholder, it shows the initial value, but when I submit the request, it isn't getting used.
![image](https://user-images.githubusercontent.com/3535272/107818097-ed77ba00-6d2b-11eb-9c07-b93f2375bfe6.png)

**Comment by DannyDainton** [comment]
The `prod` environment still has unsaved changes - is it still not working after saving?

**Comment by landonvg** [comment]
Right--still not working.  How can you tell there were unsaved changes?

**Comment by DannyDainton** [comment]
There's an orange dot on the tab - that would signify that changes have been made but haven't been saved yet.

**Comment by landonvg** [comment]
Here it is with the saved environment; still same behavior:
![image](https://user-images.githubusercontent.com/3535272/107819040-5e6ba180-6d2d-11eb-8c35-7b79a64b2aec.png)

**Comment by landonvg** [comment]
You can reproduce this by deleting the current value of a variable and sending a request that uses that variable.

**Comment by DannyDainton** [comment]
I believe that it needs to either be in both fields or just the `Current Value` field for it to resolve in the request.

I'm away from my machine so I'm currently going off the top of my head 😂

**Comment by landonvg** [comment]
If that's the case, then the behavior of syncing and exporting just the initial values is not much help, as I still have to go copy and paste every single initial value to the current value.  The behavior should be to use the initial value if the current value is empty.  This feels like a bug.

**Comment by DannyDainton** [comment]
Did you try either of the `Persit All` or `Reset All` to do that? Those are options in the environment section. 

You can also use the option in the general settings to Persit all variables.

**Comment by landonvg** [comment]
Yes, I persisted all of the variables on the source computer, then synced to the target computer, which pulled in the initial values only, leaving the current values blank, hence the problem with those variables.

**Comment by landonvg** [comment]
Oh, I see that I needed to use Reset All on the target environment--that did the trick.  I assumed Reset All would clear everything.  Thanks for your help and explanations.

**Comment by DannyDainton** [comment]
You're very welcome 🏆
