### ISSUE TITLE
No offline view

### ISSUE THREAD

**Issue by yusufdonmez** [a85/POSTMan-Chrome-Extension#9607]
**Is your feature request related to a problem? Please describe.**
Please provide offline mode, When I have no interne I cant see my collection, and examples.
And Postman after 8.0 very very slow.
I have to downgrade to 7.35 again if I can.

It seem 8.0 as Web site loading for a couple of seconds up to 10sec sometimes.
8GB ram win 10 PC running. with 8th gen intel i5 

**Describe the solution you'd like**
provide offline mode.
make it faster open and page,tab,worksapce passes.

**Describe alternatives you've considered**
postman 7.35 or older versions

**Comment by xenophero** [comment]
This has made postman unusable for me, I have to do work in a production environment with no outside internet access against internal servers and this new version is impossible to use without offline view.

**Comment by postman-staff** [comment]
Hey @yusufdonmez,

Thank you for reaching out and happy to help. V8 has a scratchpad feature that allows you to work offline. You can find it by going to the settings:
 ![](https://postman.zendesk.com/attachments/token/lISzYdX9Dy08GuKBkR2SbXGx4/?name=inline-1382685818.png)

 ![](https://postman.zendesk.com/attachments/token/4WMitsM3OV1qNplDbHeUMewSB/?name=inline-1383850183.png)​

You will, however, have to explicitly export your data periodically to backup your work and/or in the event you want to import your collections outside of scratchpad and for them to sync to the cloud.
More information data exports,here: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#exporting-postman-data

Hopefully, this helps.

via @SabriH10 | Postman Support

**Comment by postman-staff** [comment]
Hey @yusufdonmez,

Just following up here. Let me know if you have any questions or concerns following my last response.

via @SabriH10 | Postman Support

**Comment by postman-staff** [comment]
Hey @yusufdonmez,

I'm going to close this ticket as we haven't heard back, and given the information provided. Feel free to reach out if you ever have any questions or concerns. We'll be happy to help.

Have a great day!
via @SabriH10 | Postman Support

**Comment by DannyDainton** [comment]
Closing this as there has been no response regarding the issue.
