### ISSUE TITLE
Postman will replace the last couple of chars with "0" when running Runner with CSV file containing long String

### ISSUE THREAD

**Issue by j-c17** [a85/POSTMan-Chrome-Extension#9610]
**Describe the Issue**

Data driven testing by feeding a CSV file containing long String using Runner - Postman will replace the last couple of chars to "0"

**Steps to Reproduce**

- Prepare a CSV file with these values  

CustomerNumbers,Codes,CustomerId
1230007656662,7531901110010000431,12345

- Open Runner 
- Select the requests that need to be fed by the data from the CSV
- Iterations -- Change iterations value to 50 
- Data -- Select the prepared csv file 
- Hit Start Run
- Open Console 
- The column "Codes" in the CSV will be changed from "7531901110010000431" to "7531901110010000000"  (The last 3 digits are changed from 431 to 000)

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/28582666/107908119-262cc300-6fba-11eb-8f11-3cd583196695.png)

![image](https://user-images.githubusercontent.com/28582666/107907877-a999e480-6fb9-11eb-8e49-6ba25c31a40e.png)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Postman v8.0.5 
 - Operating System: Windows 10 newest update

**Additional Context**

When I copy paste the long string manually to the request body, then all good.  This issue only happens when run the test using Runner and CSV file.

**Comment by postman-staff** [comment]
Hi @j-c17!

Thanks for getting in touch and for the detailed information!

I could reproduce the behaviour and it looks like this is due to how JavaScript handles large integers.

As a workaround, you can use double-quotes "" in your csv file:

    "CustomerNumbers","Codes","CustomerId",,,,
    "1230007656662","7531901110010000431","12345",,,,

Then in the pre-request script, you can convert to BigInt type as:

    const Codes = BigInt(pm.iterationData.get('Codes'))

I hope this helps.
Please let me know if you have further questions :)

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hi @j-c17!

I hope the above workaround was useful.

We also have an open feature request for this issue - 6746
Please feel free to contribute to the thread.
via @labifrancis | Postman Support

**Comment by DannyDainton** [comment]
Close this as there has been no response about the initial issue.

**Comment by yassirkarkri** [comment]
> Hi @j-c17!
> 
> Thanks for getting in touch and for the detailed information!
> 
> I could reproduce the behaviour and it looks like this is due to how JavaScript handles large integers.
> 
> As a workaround, you can use double-quotes "" in your csv file:
> 
> ```
> "CustomerNumbers","Codes","CustomerId",,,,
> "1230007656662","7531901110010000431","12345",,,,
> ```
> 
> Then in the pre-request script, you can convert to BigInt type as:
> 
> ```
> const Codes = BigInt(pm.iterationData.get('Codes'))
> ```
> 
> I hope this helps. Please let me know if you have further questions :)
> 
> via @taehoshino | Postman Support

Thank you
