### ISSUE TITLE
Monitors are lost upon upgrade

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#9611]
**Describe the Issue**

Unable to view monitors on the Web nor against each collection. For the only monitor that can be viewed, it appears to be currently locked in spite of having Editor access over the collection as it's in the Personal workspace.

When switched to Browse from application (v.7.x), can see the below details:

![image](https://user-images.githubusercontent.com/47771757/107940186-d8aa5900-6fad-11eb-8021-2660523021da.png)

But when navigated from the collection, none can be seen.

<p align="center">
<img src="https://user-images.githubusercontent.com/47771757/107940004-96811780-6fad-11eb-8ec1-98aabb50e711.png" width="300" height="200">
</p>

**Environment Information**

 - Platform Type: Native Desktop App, Postman On The Web
 - Postman Version: v.7.x
 - Operating System: Windows

**Additional Context**

_Filed by Product Support_

This is already being tracked by the team internally, this request is to let users who are facing similar issues be notified upon the fix.

**Comment by DannyDainton** [comment]
@Raj-postman Is this something that can be closed out now or can this be reproduced on the latest version?

**Comment by Raj-postman** [comment]
@DannyDainton Haven't received any reports on this and it looks like this edge case has been addressed in the latest versions.
