### ISSUE TITLE
New Integration Request - <Test>

### ISSUE THREAD

**Issue by izza-rashid** [a85/POSTMan-Chrome-Extension#9613]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
Hi @izza-rashid can you add more details to the new Integration request.

**Comment by xk0der** [comment]
Hey @izza-rashid I'm closing this since we did not hear back from you, feel free to log a new integration request once you have more details 👍
