### ISSUE TITLE
Hide Example Responses From Sidebar

### ISSUE THREAD

**Issue by kDurg** [a85/POSTMan-Chrome-Extension#9614]
**Is your feature request related to a problem? Please describe.**
No, it is new functionality added to the most recent release that is crowding the sidebar. Previously for example responses, I could access them with a small button next to the send request button, but now that all the examples are in the sidebar, I find myself getting lost more often when trying to make calls. 

**Describe the solution you'd like**
Please allow a way to hide these example responses from the sidebar.

**Describe alternatives you've considered**
Can also allow to revert to the previous 'example' button location.

**Additional context**
With many collections, folders and calls in the sidebar, I do not need another item to crowd it even more. These are not items that I feel most people will be referencing when they make many calls for testing, therefore I doubt we need to trade quick access for organization.

**Comment by ShadowfootNZ** [comment]
Yes, please allow us to have these hidden unless we specifically ask to see them. Do not have them automatically open when I click on a request that I want to run. They making navigating a large collection unwieldy, with the need to close them every time.

**Comment by edouardGT** [comment]
I agree, very annoyed by this feature.

**Comment by chrisj-ifs** [comment]
Agreed!  My entire development team contacted me about this feature...too much clutter... give us a way to toggle it off if we want to!!

**Comment by rtudtu** [comment]
Agreed as well! Please have the option to hide it 😃

**Comment by AwaitAsync** [comment]
Agreed. This is super frustrating... I don't want to go DELETE 500 example responses...I just want the ability in my preferences or view options to turn this off.

**Comment by HenrikHolmIT** [comment]
I dont like this either. I just updated to 8.0.7 and it has this feature.

But I do propose an easy fix so the whole feature does not need to be rewritten. I believe Postman team had a reason to move these items some place else.

I think this could easily be managed/changed by not expanding the request node when clicking the name of the request. Just select it and show its properties on the righthand side. Only when you click the > icon should the UI expand the node and show child nodes. That way we can have both the old style and the new style featured at the same time. We can then decide to expand the request when we need to handle the subitems.

**Comment by dliwustl** [comment]
+1 to changing this behavior. Just make the caret expand the tree. While we're at it, let's also stop copying over the examples when we duplicate a request in a collection. The request is almost certainly going to be different, so why would we expect the old example to be relevant?

**Comment by divitngoc** [comment]
Agreed, this feature added quite a lot of clutter =/

**Comment by PZ01** [comment]
In my opinion a good idea would be to have the arrow '>' be the button that acts as a toggle to display or hide the examples under a given request. In which case clicking on a request would simply select it and not automatically expand the examples tab. This could also become an option if some people are keen on keeping the current behavior. Which I suspect is OK for small collections or with collections that don't hold examples in them.

Our team has about 20 collections for different micro-services with 5-15 endpoints each, which in turn have examples. It becomes really messy to scroll up and down whenever I click on a request. Especially for QA who aren't necessarily using Postman Runner or setting variables to show off their user-acceptance tests to other departments.

**Comment by vieiraes** [comment]
worst bug/feature of ever!

**Comment by WatanabeThiago** [comment]
up

**Comment by HenrikHolmIT** [comment]
How is this not a minor fix that has already been released?

Remove the expand code on click event on Request Title but leave it on the click event for the anchor icon...

**Comment by Kulu-M** [comment]
Very annoying. I came here to open a feature request. Apparently many people think the same. 

Please make a toggle or fix this.

**Comment by haiduc32** [comment]
Same here.

**Comment by CIDROY-Tek** [comment]
> In my opinion a good idea would be to have the arrow '>' be the button that acts as a toggle to display or hide the examples under a given request. In which case clicking on a request would simply select it and not automatically expand the examples tab. This could also become an option if some people are keen on keeping the current behavior. Which I suspect is OK for small collections or with collections that don't hold examples in them.
> 
> Our team has about 20 collections for different micro-services with 5-15 endpoints each, which in turn have examples. It becomes really messy to scroll up and down whenever I click on a request. Especially for QA who aren't necessarily using Postman Runner or setting variables to show off their user-acceptance tests to other departments.

+1  
Would be great if we could get this thing fixed soon!

**Comment by MarkusSeb** [comment]
our whole company is using version 7.36.5 until this bug/feature/issue is fixed.
its very annoying

**Comment by smwilli1** [comment]
Was this ever solved?  I am still having the issue of not being able to hide the examples in the sidebar, running on 8.11, however I have a friend running 8.10 but the sidebar isnt showing them for him.  I feel like ive gone through all possible configuration settings and cant figure out if im missing something. (About ready to throw my laptop out the window)

Thanks!

**Comment by Rakadetyo** [comment]
+1
this feature makes it looks way too cluttered. examples are not necessary to be showed like that in my opinion. I was hoping it would be fixed in recent 8.11.1 but I guess not

**Comment by HenrikHolmIT** [comment]
We're at a point where this is becoming very ridicules. Seems like most users that use examples hates this feature. And it seems like such an easy fix to not expand the request node when you click on the name but only on the > symbol but nothing is happening.

Easy 2 minutes fix but still nothing (I'm a developer so YES this would take 2 minutes to fix). Im still on v7 and having to dismiss the v8 Update dialog at every startup. Nope. No thanks. Still dont want v8. Im of the honest opinion that v7 is far more user friendly than v8 will ever be.

**Comment by SammyWhamy** [comment]
This is still not implemented? Very annoying to constantly have 3 to 5 examples clutter your sidebar for each request you click, and indeed, should be a very easy fix to implement!

**Comment by ftuyama** [comment]
It would be nice to have a settings option to toggle this feature... I wish I could hide the examples 😞

**Comment by at-besa** [comment]
I would also love to have this, since the responses are automatically generated and have to be deleted manually. just down show em would be an amazing option.

**Comment by d-mitrofanov** [comment]
it's fixed in 9.15.6 🎉

**Comment by giridharvc7** [comment]
This is now fixed with update 9.15.6
While your examples are still part of the sidebar, we don't expand your request when you select it. I hope this solves your problem. 
You can use the `>` symbol to expand the requests to see your examples

**Comment by WatanabeThiago** [comment]
ITS WORKINGGGGG!!!

THANK YOU
![image](https://user-images.githubusercontent.com/50850299/160949947-145593ec-217d-48a8-a746-52edefaa0b80.png)

**Comment by WatanabeThiago** [comment]
I LOVE IT

**Comment by montoner0** [comment]
> This is now fixed with update 9.15.6 While your examples are still part of the sidebar, we don't expand your request when you select it. I hope this solves your problem. You can use the `>` symbol to expand the requests to see your examples

@giridharvc7 
Do I need to enable this feature somehow? I use 9.31.0 and requests are still expanding upon click.
![postman](https://user-images.githubusercontent.com/13542804/193817405-70333135-db19-4482-8140-04cf666d0512.gif)

**Comment by shubhbhargav** [comment]
@montoner0 This should work for you if you are on 9.31.0. May I know which OS are you on?

**Comment by montoner0** [comment]
@shubhbhargav it's Windows 10

**Comment by shubhbhargav** [comment]
@montoner0 Can you confirm if you are able to reproduce the same behaviour on Postman Web? Also if possible if you can send a screen recording of issue happening on your machine, it would be super helpful. (maybe we are missing some explicit steps to reproduce this issue at our end)

**Comment by montoner0** [comment]
@shubhbhargav Postman Web doesn't have the issue, only desktop version. Please try the attached test collection, I can reproduce the issue with it on a fresh installation of Postman.
[Test.postman_collection.zip](https://github.com/postmanlabs/postman-app-support/files/9790464/Test.postman_collection.zip)

**Comment by parthverma1** [comment]
https://user-images.githubusercontent.com/75295512/198348737-bedca80d-417a-48b9-8abe-815c049287a7.mov

@montoner0 I tried replicating the issue using the collection you shared but was unable to do so. 

I tested this on version v10.0.39. Can you try updating to the latest version and see if that helps.

**Comment by montoner0** [comment]
> I tested this on version v10.0.39

The latest version I see is 9.31.0.
![image](https://user-images.githubusercontent.com/13542804/198354794-cc22e995-f157-422b-8e02-5ec80b8e1e23.png)

**Comment by shubhbhargav** [comment]
@montoner0 You should be able to upgrade to v10 now. Can you check once? Also can you confirm that you are signed-in in the app?

**Comment by montoner0** [comment]
@shubhbhargav I tried v10 and it works for me exactly the same way as v9.31. No, I don't have an account so I'm not signed in.

**Comment by shubhbhargav** [comment]
I see. Can you please sign-in? Currently it's only supported for signed-in users.

**Comment by montoner0** [comment]
I think this is the most ridiculous requirement for such feature... Sorry, but I'm not going to make an account for this.
