### ISSUE TITLE
OpenAPI 3.0 Keywords not recognized/used properly ( oneOf, anyOf, ... )

### ISSUE THREAD

**Issue by timothyk0908** [a85/POSTMan-Chrome-Extension#9616]
**Describe the Issue**
I'm using POSTMAN as a tool to monitor, test and define our APIs, my issue is that using oneOf, anyOf, and other keywords that meet OpenAPI 3.0 standards, throw issues.

If for example, I have a property that is either
oneOf:
- type: number
- type: string

If the first condition that Postman finds isn't true ( in this case, if the property isn't a number but a string ), it's not gonna check on the second condition of the oneOf, but instead it will give the issue. "data.property should be a number"

**Steps to Reproduce**

For example: use oneOf keyword to describe multiple possibilities of validation for one of your fields, then meet the second condition but not the first one, you'll still get an issue from POSTMAN, when triggering your endpoint, that one of the returned properties does not meet the schema.

**Screenshots or Videos**
<img width="285" alt="Capture d’écran 2021-02-16 à 12 32 27" src="https://user-images.githubusercontent.com/10809590/108057690-3e045580-7053-11eb-808f-1058fc01c3aa.png">
<img width="308" alt="Capture d’écran 2021-02-16 à 12 34 24" src="https://user-images.githubusercontent.com/10809590/108057806-68eea980-7053-11eb-98c1-349005fbed08.png">

![image](https://user-images.githubusercontent.com/10809590/108057388-dbab5500-7052-11eb-9fcc-4155ee65e2b3.png)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Version 8.0.5
 - Operating System: Mac OS Catalina 10.15.7 (19H114)

**Comment by VShingala** [comment]
@timothyk0908 Thanks for reporting the issue. We were able to reproduce this issue and are looking into it.

**Comment by timothyk0908** [comment]
Awesome, waiting for your feedback ! Thank you

**Comment by damiendiels** [comment]
@VShingala any update for this ?

**Comment by timothyk0908** [comment]
Hello @VShingala, any updates on this issue ? hanks

**Comment by VShingala** [comment]
Hi @timothyk0908, we are working on the fix for this issue and it will be available with the release v9.2.0. It might take a couple of weeks.

**Comment by VShingala** [comment]
@timothyk0908 This should be fixed now.

**Comment by timothyk0908** [comment]
Awesome, Ill check that :) thanks a lot
