### ISSUE TITLE
Send Request shortcut is ignored

### ISSUE THREAD

**Issue by megadix** [a85/POSTMan-Chrome-Extension#9617]
**Describe the Issue**

The shortcut for "Send Request" is ignored.

**Steps to Reproduce**

- Open or create a request
- edit headers, parameters, body, etc.
- hit "Send Request" shortcut (CTRL ENTER under Windows)
- **Error**: request is not sent

**Screenshots or Videos**

Not applicable

**Environment Information**

 - Platform Type: Native Windows App
 - Postman Version: 8.0.5
 - Operating System: Windows 10

**Additional Context**

Up until now I was used to edit requests, especially body and/or parameters, then hit CTRL ENTER to send the request. Very quick! This issue instead obliges me to use the mouse, which is making testing complex use cases inefficient and uncomfortable.

**Comment by pankajk07** [comment]
@megadix We have pushed a fix recently that addresses issues with shortcuts and is available in the latest version `8.0.6` . Could you update and confirm if you are still seeing this issue?

**Comment by megadix** [comment]
Updated to version `8.0.6`, shortcuts now work as expected. Good job!

I'm closing the issue
