### ISSUE TITLE
UI text size is very small in Postman 8.0.5 for Ubuntu 18.04

### ISSUE THREAD

**Issue by commadelimited** [a85/POSTMan-Chrome-Extension#9618]
**Describe the Issue**

I'm using Postman 8.0.5 on Ubuntu 18.04 and I wanted to report a significant UI issue. The application itself works flawlessly. However the UI is quite small and extremely hard to read as you can see in the attached screenshot. Here are some additional pieces of information that might help.

Resolution: 1920 x 1080
Chrome version: Google Chrome 87.0.4280.88 (Official Build) (64-bit)

Editing the "Font size" under Settings only increases the size of the response in the output tab, but does not affect the UI. FWIW this also happened in a previous major version of Postman, 7.x.x on the same machine.

**Steps to Reproduce**

View Postman on Ubuntu 18.04.

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/563460/108086333-dc84bc80-703b-11eb-8868-aa3f5e1ce82f.png)

**Environment Information**

 - Platform Type: Installed desktop application
 - Postman Version: 8.0.5 (and 7.x.x)
 - Operating System: Ubuntu 18.04

**Comment by arlemi** [comment]
Hey @commadelimited - what happens if you use the "zoom in" option in the Edit menu?

**Comment by DannyDainton** [comment]
Hey @commadelimited 👋  

The `Editor Settings` only relate to the `Pre-request Scripts` and `Tests` sandbox and not the main apps font-family / font-size.

![image](https://user-images.githubusercontent.com/17089546/108089917-01942200-7072-11eb-91e6-6fad7e990f57.png)

**Comment by commadelimited** [comment]
@arlemi View > Zoom In addresses this issue. This is the same interface zoomed three levels.

![image](https://user-images.githubusercontent.com/563460/108278812-315e2b00-7141-11eb-9ab4-22333f78b8a0.png)

1) This definitely addresses the issue and makes Postman FAR more usable for me.
2) This introduces a few UI issues when zooming in too far, but that's the same as a standard browser app.
3) It would be nice if the default were a bit larger to begin with, but this definitely takes care of my issue.

@DannyDainton I figured that part out. It might be nice to be explicit about exactly what the font size affects. It might also be nice to have a font size edit which affects UI labels, instead of having to zoom in. That way you can maintain your layout but update the text size.

Regardless, the zoom does what I need, you two were really helpful, thanks.

**Comment by DannyDainton** [comment]
Glad to see that working for you! 🏆

We do have open FRs regarding a more wider set of font sizes for the whole app as well as many other accessibility improvements. ❤️

Closing this issue out for now.
