### ISSUE TITLE
Pre-request script inheritance

### ISSUE THREAD

**Issue by lfox91** [a85/POSTMan-Chrome-Extension#9619]
**Is your feature request related to a problem? Please describe.**
I recently ran into an issue with nested folders (collection).

When I created a pre-request script, I expected the script to be run on the nested requests. This was not the case. I didn't label this as a bug because this may be the expected behavior to avoid potential conflicts with scripts. If not then this should possibly be a bug.

**Describe the solution you'd like**
If it is intentional I'd like to request the ability for a higher lever pre-request script to affect all of its children. I think this could be implemented with a toggle, maybe `inherits`.  This could then cause the child to collection to automatically receive its parent's script.

**Describe alternatives you've considered**
It is possible to just copy and paste the script in the nested children but I don't think this is the best alternative.

**Additional context**
Postman for Mac
Version 8.0.5
OS X 19.6.0 / x64

A little description of the script. It makes a request to get an xsrf token. It then saves this token to a variable. I mention this because the problem may not be with the script at all but possibly with scoping. I'm not sure.

**Comment by DannyDainton** [comment]
Hey @lfox91 

Would you be able to provide some visual examples of where this is currently failing for you? 

A basic example of scripts added to the Collection Pre-request Script and running against a request within a folder:

![image](https://user-images.githubusercontent.com/17089546/108358878-278f0300-71e7-11eb-8709-a46a13d04755.png)

Just trying to get a better understanding of what's happening for you so I'm not assuming that you mean doing something like this 😄

**Comment by lfox91** [comment]
It ended up being an asynchronicity issue upon closer inspection of the script in question. Thank you for the quick response. I'm not sure why the bug only became visible when nesting collections but that is something I can debug on my own time.

Figured I'd post a screenshot all the same.
![Screen Shot 2021-02-18 at 12 55 27 PM](https://user-images.githubusercontent.com/12665157/108421178-a4bb7780-71e9-11eb-90ca-e6cd26ab534a.png)
