### ISSUE TITLE
Give default editor access to users in a workspace

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#9620]
**Is your feature request related to a problem? Please describe.**

- In my current workflow, I'd like to have all the users in a workspace to have editor access to the collections. Not having this is a pain point.
- There's no easy way to assign permissions at for a group as well (either in product or through the API)

**Describe the solution you'd like**
- Everyone in a workspace should be able to edit collections
- Maybe have a default setting at a team level/ workspace level for assigning permissions for collections
- Maybe also have API capability to change permissions programatically at all levels and roles in the team (related to this- https://github.com/postmanlabs/postman-app-support/issues/6591)

**Comment by RaffaelaHiess** [comment]
We are also interessted in this feature. It should be possible, that all members of a workspace have editor access for all collections by default.

**Comment by sujayvenaik** [comment]
@RaffaelaHiess @harsh-reality With the release of the latest improvement in workspaces this is possible.

if the team is assigned the editor role on the workspace, then all elements inside the workspace all team members by inheritance will have editor access. More details here: https://blog.postman.com/collaborating-postman-workspace-roles/

You can get the latest version of the postman-app from: https://www.postman.com/downloads/ or user the web version by signing in directly on https://www.postman.com

Closing this feature request, but feel free to drop if any additional feedback on this issue or create a new one.

Thanks.
