### ISSUE TITLE
Remove Check Usage notification bar

### ISSUE THREAD

**Issue by lflucasferreira** [a85/POSTMan-Chrome-Extension#9624]
Hi guys,

Could you remove this unnecessary notification from the top bar? It just takes space and is still showing up even after removing the person I added accidentally to the team.

This is really annoying. Thanks (not in advance), but after removing this thing.

![2021-02-17_172939](https://user-images.githubusercontent.com/5920654/108264013-bd725180-7145-11eb-833c-eff4aa2fc9ed.png)

**Comment by postman-staff** [comment]
Hi @lflucasferreira,

So sorry for the hassle here. Would you please submit a request via the link below and we'll be happy to assist further:


- https://support.postman.com/hc/en-us/requests/new/

via @labifrancis | Postman Support

**Comment by lflucasferreira** [comment]
I fixed this by leaving the team I was in, and only me. But I still believe this top bar should not be present when reaching the limit. It will not force me to pay for something that bothers me. I will simply stop using it if this kind of approach is recurrent.
