### ISSUE TITLE
"Environment Quick Look" not working.

### ISSUE THREAD

**Issue by Pricilla09** [a85/POSTMan-Chrome-Extension#9626]
**Describe the Issue**

When trying to have a quick look of environmental variables, nothing changed. The "Eye" icon just displays the tooltip and no response.

**Steps to Reproduce**

> Select any collection, try  to select the existing environment and click the eye icon in the left next to the environment name.

**Screenshots or Videos**

![2021-02-18_15-01-04](https://user-images.githubusercontent.com/71498483/108318121-3f23b700-71fa-11eb-9d08-9046ba55a831.gif)

**Environment Information**

 - Platform Type: Native Desktop App
 - Postman Version: Version 8.0.6
 - Operating System: Win 10

**Comment by DannyDainton** [comment]
Hey @Pricilla09

Is this also happening after you quit the app and restart it?

**Comment by Pricilla09** [comment]
Hi @DannyDainton I tried to close and restart the app, still facing the same issue. I suspect this should be after the restart of my system.

**Comment by Pricilla09** [comment]
Its working now, maybe some glitch :-) Shall I close this? or some investigation in-progress? 

Will post the further comments if I face any issue again with this quick look!!

![image](https://user-images.githubusercontent.com/71498483/108461148-20362b00-72b5-11eb-8322-bd377348bf05.png)

**Comment by DannyDainton** [comment]
Ah that's great. 🏆

A few of us on different machines were trying to reproduce the problem but couldn't see the same behavior.

I'm going to close this now but we can reopen if it happens again.

**Comment by Pricilla09** [comment]
@DannyDainton Sure!!! Probable I did nothing, its working after some rest :-)

**Comment by Pricilla09** [comment]
I faced this issue again today. Restarting the app didn't help!!


https://user-images.githubusercontent.com/71498483/109093066-ae496000-7752-11eb-8a85-ca36dd881502.mp4

**Comment by bkonetzny** [comment]
Same here with Postman v8.0.6 (native desktop app) on Windows 10 (Version 10.0.19042.844), clicking the Eye (Quick Look) button for the environments does nothing. Restart of Postman didn't help. Nothing to see in the DevTools or Postman Console.

**Comment by Pricilla09** [comment]
@bkonetzny finally its not only for me :-) I was so confused with this behavior.

**Comment by bkonetzny** [comment]
Just wanted to give an update: This issue still exists in the just released v8.0.7

**Comment by DannyDainton** [comment]
Hey @bkonetzny / @Pricilla09 

Are you seeing any Dev console errors happening when hitting the button?

You can open up the console going to `View > Developer > Show Dev Tools (Current View)`

Are there any more contextual details that you can share, as this is not happening to all users, narrowing down the issue will require more granular details. 

Is this only happening in specific Workspaces? Personal Workspaces? Team Workspaces? Is it only for a specific environment? Does it open for others? Does the same environment open fro the left side menu option?

Do you have a large number of environment or global variables?

**Comment by bkonetzny** [comment]
Hi @DannyDainton 

The following message is showing up in the Dev Tools when clicking the Icon:
```
Could not find on CollectionStore. Missing or invalid parameter. (vendor-shared.js:952453)
```

I was able to narrow down the problem. I'm working in a shared Workspace with 8 environments, each of them with around 20 variables. None of these works in Quick Look, but all of them show up in the sidebar and are editable there.
However, when I switch to a different shared Workspace, the Quick Look there works for the enviroments in that workspace, so I think it must be Workspace related.

Funny thing is: I'm the only developer having this problem in our shared workspace, it's working for all other devs on windows, mac and linux with identical versions.

Any hint for me how I can narrow this down and debug?

**Comment by mohitranka** [comment]
Hey @bkonetzny @Pricilla09 ,

I am the Engineering Manager in the team, that works on this feature. Can you please open a support ticket with postman.com/support ? If it works with you, I'd like to get on a video call to debug the issue.

**Comment by DannyDainton** [comment]
Opening this again after seeing another user raise the same question on our community site.

https://community.postman.com/t/clicking-on-postman-environment-quick-look-does-nothing/21278

**Comment by Pricilla09** [comment]
@mohitranka Thanks a lot for your reply. I have logged #70137 ticket. Please let me know if I need to provide any other details :-)

**Comment by jweller24** [comment]
I am experiencing this issue as well in Postman Version 8.0.7. I only have 1 environment with ~50 variables. I noticed that if I switch the environment next to the Quick Look button to "No Environment", I can click the eye and view the Global Variables.

Let me know if there is anything I can provide for further troubleshooting.

**Comment by Pricilla09** [comment]
@bkonetzny @jweller24 I had a call with @mohitranka. He is now looking into the issue. Watch this space he will keep us updated on the fix :-) Until then please use the workaround by navigating to the "Environments" tab to see the variables.

**Comment by DannyDainton** [comment]
@Pricilla09 Were there any specific details about your set up which helped to recreate the issue?

**Comment by F-shaikh** [comment]
The edit button in the quick look also does nothing and simply closes the modal..

**Comment by DannyDainton** [comment]
Hey @F-shaikh

Can you provide a short recording of that behaviour please?

Are you sure that the environment is not already open in a tab, so it just appears that it does nothing.

**Comment by F-shaikh** [comment]
@DannyDainton Yes i'll have that recording for you tomorrow. 

Im positive its not already open in a new tab. 

Additionally, I cannot even open requests without forcefully clicking "open in new tab"..

**Comment by DannyDainton** [comment]
It seems like you have a few different things happening here for you, I don't want to try and squeeze it all into this issue.

Can you open up a new issue with all the details so we can take a look at what's going on.

The best thing to do, if it's a UI based problem, is to visually show that happening with a screenshot or a video.

**Comment by Pricilla09** [comment]
@DannyDainton No Danny, no specific detail he mentioned over the call. May be @mohitranka can provide more details :-)

**Comment by bkonetzny** [comment]
To give an update to this: The v8.0.9 fixed the issue for me.

**Comment by mccannt** [comment]
@Pricilla09 Can you update to the most recent version and try it again? Looks like others are having luck doing that.

**Comment by Pricilla09** [comment]
Hi @mccannt, It's working now.. I didn't face this issue for few days :-) Hope I am lucky too. You can close it. Thank you.

**Comment by mccannt** [comment]
@Pricilla09 This is great news! Thanks for letting us know. 

I will close this issue out for now but if you do experience it again, please reopen it.

**Comment by brchimp** [comment]
Having same issue with 8.2.2 running on macOS 11.2.3 M1 chip

**Comment by calkawahara** [comment]
Seems like only the web version is working not the non-web. very disappointing.

**Comment by Pricilla09** [comment]
@brchimp and @calkawahara , this issue was fixed for few of us here and I am not seeing that again. So far, the "eye" icon is doing the job perfectly. Please feel free to add your details in here. So that it will be helpful for the developers to debug :-)

**Comment by calkawahara** [comment]
As I mentioned in the ticket. The eye works fine for web version. But I
can't get the eye to open up in the non-web view. This seemed to happen
with the past release or so. It was initially very sporadic and It was so
frustrating I finally gave up and now using the web version. Unable to do a
screen shot as there are no errors as far as I can tell it just doesn't
open so I can't edit any environment..... with the exception of the NO
Environment and that's not usable.

**Comment by raghwendra-sonu** [comment]
Even i am facing this issue with desktop version 8.4.0. Environment variables list does not oon on clicking "Environment Quick Look" button.

**Comment by Ginaaates** [comment]
I am having this issue as well. Worked great last week, and when I started Postman today, couldn't get the list to pop up when selecting the quick look button. I have rebooted and restarted. I am on version 8.5.1.

**Comment by LPovv** [comment]
For me (MacOS-v13.12.1, Postman-v10.11.1) I'm having the same issue.
I would love to assign a value to {{baseUrl}} being part of all API-calls.
Even trying to add a (Global-environment) variable baseUrl with the proper value, and restarting Postman (and even my Mac) does not work for me.

Although the popup shows me:
C baseUrl
INITIAL /
CURRENT baseUrl
SCOPE Collection
I can not edit the 'CURRENT'-value
Why does adding through Environment>Global>Variable not work instead of the 'C baseUrl'-popup?

![Screenshot 2023-03-02 at 12 27 27](https://user-images.githubusercontent.com/122448268/222416713-1c40f028-a2e7-45c3-9599-b66988f13c27.png)
![Screenshot 2023-03-02 at 12 32 27](https://user-images.githubusercontent.com/122448268/222417447-aa2d82c2-d119-4f00-b862-15db0ef7723a.png)

**Comment by giridharvc7** [comment]
@LPovv 
You can edit this like so 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/1040583/222424836-1a1dc3ea-a833-46f6-9ee5-ac812436fee1.png">

**Comment by LPovv** [comment]
How do I add then this new environment variables to my APIs?

**Comment by LPovv** [comment]
Loading a previous environment in which I added the baseUrl did not work.
However creating a new environment and copy/pasting the baseUrl into that did however work!?

So probably, first selecting the API-query and then switching from 'No environment' to 'PreviousEnvironment' does not always seem to work! Creating a new-environment seems to do some magic, and then works as expected!
