### ISSUE TITLE
The export of the globals and environment, the value is empty.

### ISSUE THREAD

**Issue by tester-xm** [a85/POSTMan-Chrome-Extension#9627]
**Is your feature request related to a problem? Please describe.**
When I use the globals file, I need to rewirte json file.

**Describe the solution you'd like**
I want the value of the export is equal to postman.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/60353008/108325255-dd684a80-7203-11eb-8455-7662577401b7.png)

**Comment by DannyDainton** [comment]
Hey @tester-xm

Are all the Global variables placed in the `Current Value` and not in the `Initial Values`?

Variable values will only be exported if they are in the `Initial Value` field.

**Comment by tester-xm** [comment]
Ok, thanks. You're right~
