### ISSUE TITLE
"Set as variable" Popup

### ISSUE THREAD

**Issue by andrejmarinic** [a85/POSTMan-Chrome-Extension#9630]
When selecting any text in the Body editor a popup appears saying "Set as variable". 

Can this be disabled? I am not using it and it is obstructing the values above which is quite annoying. Have to click somewhere each time I want to remove the popup.

**Comment by malvikach** [comment]
@andrejmarinic Let us know if you are still facing this problem in the latest [postman](https://www.postman.com/downloads/) version 9.14.

I am unable to replicate this issue anymore. If you still see this, please do attach more information about your os environment and a screen recording of your experience.

**Comment by malvikach** [comment]
Closing this issue, please feel free to re-open and let us know if this is still a problem with the above-mentioned details.

**Comment by Kirill-N-dev** [comment]
It is actually excessing popup. Popups are evil.
