### ISSUE TITLE
Cannot remove Environment from Workspace were it got shared

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#9631]
**Describe the Issue**
I cannot remove the environment being the only member in the team workspace. 

**Steps to Reproduce**

1. I created an environment in my personal workspace say "abc" and share it over my team workspace with me only the member in the team workspace. 

2. I tried to remove the environment "abc" from my team workspace and I couldn't remove it and gets an error message as below, though the environment "abc" is already present in my personal workspace:

<img width="491" alt="Screenshot 2021-02-18 at 6 19 30 PM" src="https://user-images.githubusercontent.com/52168965/108359304-d9ddbf00-7215-11eb-8cf2-94a45bd63749.png">

3. I can delete the environment "abc" from both the workspaces (personal & team) but can ONLY remove the environment from the workspace where it was actually created.

4. Finally deleting the environment "abc" from the team workspace (where I have shared) deletes the environment from my personal (source) workspace too.

**Environment Information**

 - Platform Type: desktop app
 - Postman Version: Version 8.0.6
 - Operating System: macOS (big sur)

**Additional Context**
1. Need a better message window/pop-up so that it will not confuse the users.
2. The environment should be removable from the workspace where it is shared by the owner
3. Deleting the Environment from where it got shared should not delete the Environment source workspace.

**Comment by akshay-kulkarni-03** [comment]
@Swapnil-getpostman before v9.1 app version, we used to allow sharing of environments/collections across workspaces. However, with v9.1 & later version we moved towards a container model where-in this capability is no longer supported and you can only have environment/collection belonging to only one workspace. Closing this issue, since this is no longer applicable.
