### ISSUE TITLE
Cannot Manage Roles for Environment after update to v8.0.6 

### ISSUE THREAD

**Issue by RichFlickstein** [a85/POSTMan-Chrome-Extension#9634]
1. Log into Postman as a member of a Team
2. Create an environment
3. Select the environment
4. Click the Eyeball
5. Click Edit
6. Click Share and select the workspace to share the environment 
6. Click the three dots
Observe the Manage Roles option is grayed out
If you hover over it, you see “You need to be signed-in to a team to perform this action”
![image](https://user-images.githubusercontent.com/12286512/108413214-936d6d80-71df-11eb-8e4c-7f1276e62bf9.png)

I have tried logging out and logging back in
Other users of my team have also replicated the issue

**Comment by postman-staff** [comment]
Hi @RichFlickstein

Thank you for submitting this issue and providing screenshots, it certainly made it easier to reproduce and escalate internally. We have enough information to move forward internally and will update this ticket as we make progress.

via @asi-postman | Postman Support

**Comment by postman-support** [comment]
Hi Support​,

Thanks for reaching out! I am more than happy to assist you with your inquiry.

From what I can gather, you may leverage our built-in oAuth (1.0 & 2.0) for this. If you happen to have any questions on how to implement I suggest posting on our community forum.
https://learning.postman.com/docs/sending-requests/authorization/#oauth-20

We want to reserve this Support Channel for break-fix issues only, so as to provide good quality support when things are broken and not working as expected.

For How-To questions, our community is the best place: Postman Community - I encourage you to post your query at our forum, It is a vibrant community frequented by industry experts and our engineers alike. You should get good quality feedback soon.

Best,
Anthony​ | Product Support Engineer


Status Page | Learning Center | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by postman-staff** [comment]
### Hi @RichFlickstein,

Our team is in the process of rolling out a fix to the native app v8.0.7.

In the meantime, can you try managing the roles from the web dashboard?

go.postman.co/me/environments

With Kind Regards,

Anthony S.


Status Page | Learning Center | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by RichFlickstein** [comment]
I did not have a chance to test from web with the existing version, but I updated to Postman v8.0.7 and confirm that the issue has indeed been fixed. (I also it as a fixed issue in the release notes.)

**Comment by xk0der** [comment]
Closing as the issue is resolved in 8.0.7
