### ISSUE TITLE
Environments do not load when publishing docs (Native App)

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#9635]
**Describe the Issue**
When trying to publish documentation from the Postman desktop client, the environments do not load up.

**Steps to Reproduce**

 - Open Postman desktop application
-  Select any Workspace with available environments
-  Try to publish documentation for any collection
-  You will be redirected to the web app, but environments will not load.

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/47771757/108458829-6ed6cb80-729b-11eb-9df9-bd2263f8411f.png)

**Environment Information**

 - Platform Type: Native app
 - Postman Version: v.8.0.6

**Additional Context**
This works fine with Postman's web application.

_Filed by Product Support_

This is already being tracked by the team internally, this request is to let users who are facing similar issues be notified upon the fix.

**Comment by Raja-Simha** [comment]
Issue fixed in 8.0.7

**Comment by dawood76** [comment]
@Raja-Simha , getting the same issue , and i am unable to update postman to 8.0.7 on ubuntu. My version is 7.36.5 , and it is marked as the latest version.  I also tried using ,sudo snap refresh postman, command , but got the same message that postman is up to date
![image](https://user-images.githubusercontent.com/73113095/118682553-fdff6b00-b819-11eb-9868-b4513995c65b.png)

**Comment by Kostanos** [comment]
This issue happens to me even in WEB, when I publish the documentation, I can't chose the environment.
The environment added to the API among with the collection.

**Comment by Kostanos** [comment]
![image](https://user-images.githubusercontent.com/1136702/144907312-98f29466-2f53-47ad-b39a-f190f93e3c71.png)
