### ISSUE TITLE
Environment color

### ISSUE THREAD

**Issue by ms666** [a85/POSTMan-Chrome-Extension#9638]
Hello
A little suggestion for you to consider:
adding the possibility of specifying a color for the environment, and marking the currently selected color with this color - combobox in the upper right corner.
I think a few basic colors are enough, for me three are enough: red, green and none :)
I thought of it yesterday when I accidentally ran a method on a production environment :(

Greetings
Paweł

**Comment by DannyDainton** [comment]
Closing as it's a duplicate of https://github.com/postmanlabs/postman-app-support/issues/8260
