### ISSUE TITLE
Publish Fails To .Net Core Web API After Postman Call

### ISSUE THREAD

**Issue by chopswil15** [a85/POSTMan-Chrome-Extension#9643]
I've got a Postman (8.0.6) call to my .Net Core 3.1 Web API on my local IIS
I run the Postman call successfully.
I then make a change to my service and try redeploy the service to my local IIS.
The publish fails with lots of this "The file is locked by: "w3wp.exe (24116)".
I shut down Postman.
I redeploy the service again and it succeeds.
I realize w3wp.exe is IIS .

Why is Postman blocking deployment to IIS?
Is Postman somehow keeping a connection open to the service?
Am I doing something wrong?

From Visual Studio Output
lots of these failure messages
C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.FileSystem.targets(42,5): Error MSB3027: Could not copy "C:\Users\Owner\Documents\GitHub\PathfinderControlLibrariesCore\PathfinderServiceCore\PathfinderServiceCore\obj\Release\netcoreapp3.1\PubTmp\Out\DatabaseInterfaces.dll" to "C:\Users\Owner\Documents\Services\PathfinderServiceCore\DatabaseInterfaces.dll". Exceeded retry count of 10. Failed. The file is locked by: "w3wp.exe (24116)"

**Comment by DannyDainton** [comment]
Hey @chopswil15

Can you provide some screenshots or a recording of where you are seeing this error with Postman blocking what you're doing.

Does this same action work correctly if you perform it with a Curl request from the CLI - You can use the code section in the right side context menu to generate the code snippet for the request.

**Comment by chopswil15** [comment]
I don't have anything that shows Postman  blocking
all I'm seeing is this
1) run Post man call to my service on IIS - This succeeds and data is returned in Postman
2) try to publish to that IIS service - Fail
3) shutdown Postman
4) Publish to that IIS service -Success

everytime.

Do you want a recording of all these steps occurring?

**Comment by DannyDainton** [comment]
Does it work if you send the first request with the `Connection: close` header? 

There is an auto generated `Connection: keep alive` that is sent with the request, adding a new one will overwrite this header.

If you could send a recording, that would be great. The more information the better. 😄

**Comment by chopswil15** [comment]
Changing the header Connection did the trick.


It's there a way to universally turn this off?

**Comment by DannyDainton** [comment]
You could add something like this to the Collection `Pre-request Script` to ensure that header is used:

```javascript
pm.request.headers.add({key: 'Connection', value: 'close'})
```

**Comment by chopswil15** [comment]
I didn't realize keep-alive was a default.
Issue resolved for me.

Thank you for your help.
