### ISSUE TITLE
When disconnect internet, can't use `Collections` any more.

### ISSUE THREAD

**Issue by cs12110** [a85/POSTMan-Chrome-Extension#9648]
**Describe the Issue**

When I upgrade the postman version7 to version8, I got problem with the internet was broken, postman doesn't show `Collections` any more. But version7.0 is work fine on disconnect with internet(only local env). It was really annoying. Can you guys fix this, plz?

**Steps to Reproduce**

First: disconnect the internet

Second: open postman(v1.8.0) 

**Screenshots or Videos**

For example:

<img width="1386" alt="WX20210223-091922@2x" src="https://user-images.githubusercontent.com/12764287/108790711-5b3ba580-75b8-11eb-9d3c-d0443d159bca.png">

**Environment Information**

 - Platform Type: osx
 - Postman Version: Version 8.0.6
 - Operating System: macos catalina 10.15.7

**Additional Context**

**Comment by DannyDainton** [comment]
Closing as a duplicate of many other tickets raised with regard to Offline mode.
