### ISSUE TITLE
"File" in menu bar not displaying correctly when window is snapped to top left corner of second monitor on Windows

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#9649]
**Describe the Issue**
The "File" menu does not display properly when window is snapped to top left corner of second monitor on Windows

**Steps to Reproduce**
- Plug second monitor and arrange it to be at the right of main monitor (no bug when second monitor is on the left)
- Place Postman window on second monitor and snap to top left corner (full-screen or small window)
- Click on menu bar > File and see bugged context menu window

**Screenshots or Videos**
Postman window snapped to *top-left* corner of second monitor (virtually placed to the *right* of main monitor)
![Postman_file_menu_bug](https://user-images.githubusercontent.com/9873597/108822295-2bdc6700-75bf-11eb-80e3-6ef0a0670b14.gif)
Postman window snapped to *top-right* corner of second monitor (also virtually placed to the *right* of main monitor)
![Postman_file_menu_ok](https://user-images.githubusercontent.com/9873597/108822301-2da62a80-75bf-11eb-83a1-bf571f916969.gif)
Postman window snapped to *any* corner of second monitor (virtually placed to the *left* of main monitor)
_No gif but works properly_

**Environment Information**

 - Platform Type: Windows
 - Postman Version: 8.0.6
 - Operating System: Windows 10 Enterprise

**Additional Context**
Computer is a HP Elitebook laptop. Secondary monitor is a Samsung 24" CF39 Curved, FHD, 60Hz Monitor. Connection through HDMI cable.

**Comment by mccannt** [comment]
@jooleeanh Are you still experiencing this issue o the most recent version of the application? 
I am not able to replicate it but it may be a very specific scenario.

**Comment by mccannt** [comment]
Closing issue. It is not reproducible and there has not been any further input from the user.
