### ISSUE TITLE
Request throws ECONNRESET with SSL Certificate

### ISSUE THREAD

**Issue by stereoheart** [a85/POSTMan-Chrome-Extension#9652]
Hi,

I am using an ASP.NET WEB API.
Hosted on Windows 2019 IIS 10 server.
I am able to call the web API successfully using Postman 8.0.6.
But after adding the SSL certificate I am getting the below error.
![image](https://user-images.githubusercontent.com/19296270/108896772-efb6ff80-75da-11eb-88b8-6bee56799233.png)

I tried disabling the SSL certificate verification but I am receiving the same error:
![image](https://user-images.githubusercontent.com/19296270/108896886-137a4580-75db-11eb-9b2e-774555be8d61.png)

Please suggest.

**Comment by eya62** [comment]
Hello,

Are you running this with CI newman? if yes you can add --secure like this
newman run collection.json -e environment.json -g globals.json  --insecure

**Comment by ritwijsinha** [comment]
@stereoheart is the endpoint publicly accessible? It would be great if you could help us reproduce this issue.

**Comment by DannyDainton** [comment]
Hey @stereoheart 👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
