### ISSUE TITLE
Postman slows down my pc

### ISSUE THREAD

**Issue by jacox02** [a85/POSTMan-Chrome-Extension#9657]
**Describe the bug**
When I open Postman app, my pc slows down to a crawl

**To Reproduce**

- Open Postman app

- Expected behavior

- I expect postman to not slow down my PC

App information (please complete the following information):

App Type Windows EXE
Postman Version: v8.0.6
OS: Windows 10 20H2
RAM: 8GB

**Comment by DannyDainton** [comment]
Hey @jacox02 

Could you provide some images from the resource monitor or the Activity Manager, please? Also, any information about your Postman usage (rough number of Workspaces, Collections, Environments, etc.)?

As you can appreciate, it's very difficult to reproduce what's happens on your machine given all the other variables that could also cause it to be less performant - The more specific details that you can provide, the better we can investigate what might be happening.

**Comment by kool79** [comment]
It happens also for me also about 7 days ago. Unfortunately I did not collect any data and I have only one screenshot from task manager (see below) Postman occupied about 25..30% of CPU resource ( Intel Core i7-8565U with 4cores/8logical processors)
I found high CPU usage when I leave my working place and then back in ~5hours. It was _permanent_ load with 100% usage of one of the logical processors. Actually during this perion of time i **was able** to use postman: i.e. no significant freezes in UI - just high cpu usage and loud cooller on my note. After ~20 minutes CPU load was not decreased and I just restarted postman. After restart I did not see any issues with cpu load
  I hope it was one-time issue and (maybe) related to windows updates. NExt time it this happend I'll try to imvestigate more deeply with processExplorer from SysInternals

BTW the new 8.x version is much better than old one. With old (pre-8) version I should wait up to 10 minutes after each restart until UI became responsive. I have 1 large shared workpase (~30 teammembers)  with more than 2000 requests.
   So thanks for versio 8.x and thanks for 'comments' support

![Screenshot - 17 02 2021 , 21_58_55](https://user-images.githubusercontent.com/4625317/109041782-127b0e00-76d8-11eb-8c8c-196b89a7bc2a.png)

**Comment by jacox02** [comment]
Hello guys, I hope you are all well, well, in my case I have a gaming laptop and it has an ultra energy saving mode that, as its name says, saves energy at all costs, and as it happened it got slow when I opened postman, but **this is not a postman issue**, sorry for the inconvenience.

**Comment by DannyDainton** [comment]
Thanks for getting back to us @jacox02


@kool79 I'm going to close this one for now but we can always reopen it again if you notice any more issues with V8.
