### ISSUE TITLE
Postman appears to hang after updating on Linux

### ISSUE THREAD

**Issue by davmillar** [a85/POSTMan-Chrome-Extension#9665]
**Describe the Issue**
Postman appears to hang after updating on Linux. After clicking the prompt to restart, the app will update in the background, relaunch, and get stuck on the screen with the orbiting graphic and never transition into the main app. After using the terminal to pkill postman and relaunch it, it behaves normally.

**Steps to Reproduce**
Wait for an update prompt, follow it. 

**Screenshots or Videos**
Here is terminal output at the time it hangs and when I pkill it if I use the terminal to launch Postman instead of letting it relaunch on its own:

```
1614026104376 main info "Bootstrap-models~bootstrap - Success"
Terminated
1614026432936 main info "Quitting app"
```

**Environment Information**

 - Platform Type:  Linux
 - Postman Version: Multiple
 - Operating System: Fedora 33

**Additional Context**
I've provided logs to your support agent Anthony under Zendesk ticket number 67367.

**Comment by jviotti** [comment]
Merging this ticket with https://github.com/postmanlabs/postman-app-support/issues/8205.
