### ISSUE TITLE
Error while importing WADL: TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#9669]
I receive this error when trying to import a WADL file, or import via the raw text. 

This is on the latest version, v8.0.6

**Comment by DannyDainton** [comment]
Hey @maximm98

To be able to replicate this behaviour on our side and see the same error, we would need to use the same file.

Could you attach a copy of this to the issue please.

**Comment by companje** [comment]
I get the same error with the following WADL file: https://transkribus.eu/TrpServer/rest/application.wadl

**Comment by sansfromage46** [comment]
Same problem with https://mwa-formation.kipaware.fr/api/documentation/wadl

**Comment by sansfromage46** [comment]
Always same problem in Postman v8.2.3

**Comment by VShingala** [comment]
@sansfromage46 @companje @maximm98 We have identified the issue and are working on it. Fix for it will soon be available.

**Comment by VShingala** [comment]
@sansfromage46 @companje @maximm98 This issue should be fixed in the latest postman App and web (>= v8.4).
