### ISSUE TITLE
endless verification of syncing work when update to postman v8.0, not able to update to v8.0

### ISSUE THREAD

**Issue by rubydr** [a85/POSTMan-Chrome-Extension#9670]
**Describe the Issue**
endless verification of syncing work when update to postman v8.0. 
Not able to upgrade to v8.0. My current version is **Version 7.36.5 (7.36.5)**

btw, **I tried this scenario with our corp VPN and without corp VPN (internet at home), both didn't work**

**Steps to Reproduce**
1. Click "setting" icon on right top menu in Postman application on Mac OS.
![image](https://user-images.githubusercontent.com/79767843/109399561-9409b080-7911-11eb-8bc0-33e2bed4293a.png)

2. Click "Update available, view changes" 
![image](https://user-images.githubusercontent.com/79767843/109399593-ca473000-7911-11eb-905a-6a03ee425930.png)

3. Click "update"
![image](https://user-images.githubusercontent.com/79767843/109399614-ea76ef00-7911-11eb-815e-3e51e7b2b92f.png)

4. Click "Verify" on "SETTING UP YOUR WORKSPACE FOR POSTMAN V8.0"
![image](https://user-images.githubusercontent.com/79767843/109399639-0c707180-7912-11eb-8bef-f617e523249b.png)

6. Then the verification is endless, the progress bar is always there for more than 10 hours. Not able to upgrade to v8.0
![image](https://user-images.githubusercontent.com/79767843/109400042-5f4b2880-7914-11eb-8a81-7a2d91e472a8.png)

**Screenshots or Videos**
Screen Recording 2021-02-27 at 3.42.35 PM
https://user-images.githubusercontent.com/79767843/109399746-aa643c00-7912-11eb-9925-926dce6bea31.mov

**Environment Information**
Apple Mac OS on MacBook Pro
 - Platform Type: Mac OS
 - Postman Version: Version 7.36.5 (7.36.5)
 - Operating System:
![image](https://user-images.githubusercontent.com/79767843/109399784-d41d6300-7912-11eb-8346-73dff2b4d394.png)

**Additional Context**
Here are all related logs:
[renderer-shared2.log](https://github.com/postmanlabs/postman-app-support/files/6055356/renderer-shared2.log)
[renderer-shared3.log](https://github.com/postmanlabs/postman-app-support/files/6055357/renderer-shared3.log)
[renderer-shared4.log](https://github.com/postmanlabs/postman-app-support/files/6055358/renderer-shared4.log)
[renderer-shared5.log](https://github.com/postmanlabs/postman-app-support/files/6055359/renderer-shared5.log)
[renderer-shared6.log](https://github.com/postmanlabs/postman-app-support/files/6055360/renderer-shared6.log)
[renderer-shared13.log](https://github.com/postmanlabs/postman-app-support/files/6055361/renderer-shared13.log)
[renderer-shared14.log](https://github.com/postmanlabs/postman-app-support/files/6055362/renderer-shared14.log)
[renderer-shared15.log](https://github.com/postmanlabs/postman-app-support/files/6055363/renderer-shared15.log)
[renderer-shared16.log](https://github.com/postmanlabs/postman-app-support/files/6055364/renderer-shared16.log)
[renderer-shared17.log](https://github.com/postmanlabs/postman-app-support/files/6055365/renderer-shared17.log)
[renderer-shared20.log](https://github.com/postmanlabs/postman-app-support/files/6055366/renderer-shared20.log)
[renderer-shared21.log](https://github.com/postmanlabs/postman-app-support/files/6055367/renderer-shared21.log)
[renderer-shared22.log](https://github.com/postmanlabs/postman-app-support/files/6055368/renderer-shared22.log)
[renderer-shared23.log](https://github.com/postmanlabs/postman-app-support/files/6055369/renderer-shared23.log)
[renderer-shared24.log](https://github.com/postmanlabs/postman-app-support/files/6055370/renderer-shared24.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/6055371/renderer-shell.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/6055354/renderer-shared.log)
[renderer-shared1.log](https://github.com/postmanlabs/postman-app-support/files/6055355/renderer-shared1.log)
[main.log](https://github.com/postmanla
[renderer-auth.log](https://github.com/postmanlabs/postman-app-support/files/6055350/renderer-auth.log)
[renderer-console.log](https://github.com/postmanlabs/postman-app-support/files/6055351/renderer-console.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/6055352/renderer-requester.log)
[renderer-runner.log](https://github.com/postmanlabs/postman-app-support/files/6055353/renderer-runner.log)
bs/postman-app-support/files/6055348/main.log)
[pluginHost.log](https://github.com/postmanlabs/postman-app-support/files/6055349/pluginHost.log)

**Comment by postman-staff** [comment]
Hi @rubydr,

Thank you for reaching out! I am more than happy to help!

Looking at your screenshot as well as by analysing the log files, it looks like there is some problem with web socket connection.

You mentioned that the issue persists even without VPN. Do you use proxy, firewall or antivirus applications on your device, or would there be any corporate device management software being installed?
If you are using any of those, it is possible that the web-socket connection is being interrupted. In that case, please ensure to whitelist the following Postman domains to allow the connection to be established between the app and our server:

    *.getpostman.com
    *.postman.co
    *.pstmn.io
    *.postman.com


Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @taehoshino | Postman Support

**Comment by rubydr** [comment]
> corporate device management software being installed

Yes, we do have corporate device management software installed. Let me contact our IT/Security depart, and see whether the issue can be solved.

**Comment by postman-staff** [comment]
Hi @rubydr,

Thanks for getting back and confirming that you have a device management software installed.

Please let us know if the issue is persisting even after checking with your IT department.
We will then consult with our internal team to investigate further.

via @taehoshino | Postman Support

**Comment by rubydr** [comment]
> Hi @rubydr,
> 
> Thanks for getting back and confirming that you have a device management software installed.
> 
> Please let us know if the issue is persisting even after checking with your IT department.
> We will then consult with our internal team to investigate further.
> 
> via @taehoshino | Postman Support

I checked with IT department. Nothing is blocked from our side. 
**BTW, postman upgrade worked before (within or outside our Corp VPN), I have used postman on my laptop for more than a year.** 
**And some of my colleagues have upgraded the postman to V8.0 successfully.**
Can you help look into this issue?

**Comment by postman-staff** [comment]
Hi @rubydr,

Thanks for getting back!

To troubleshoot further, can you log out from the Postman app and then log back in?

Also, can you tell me if you can access the Postman web (go.postman.co) without any issue?

via @taehoshino | Postman Support

**Comment by rubydr** [comment]
> Hi @rubydr,
> 
> Thanks for getting back!
> 
> To troubleshoot further, can you log out from the Postman app and then log back in?
> 
> Also, can you tell me if you can access the Postman web (go.postman.co) without any issue?
> 
> via @taehoshino | Postman Support

I have no problem to access go.postman.co, and login. 
I am not even able to signout without saving my changes. It is just hanging there. 
![image](https://user-images.githubusercontent.com/79767843/109577005-d9b9ab00-7ac2-11eb-81c7-06c340223ae0.png)

I backup my data from setting, and will try to uninstall the postman, then directly install the latest version.

**Comment by rubydr** [comment]
The issue is resolved.
I uploaded the backup file to my cloud workspace via go.postman.co
Forced to quit Postman app
Restart Postman app, then see the empty local workspace, and syncing from cloud workspace to my local is executed successfully.
After those, finally the download and installation of new version is done successfully.

Thanks you very much.

**Comment by postman-staff** [comment]
Hi @rubydr,

That's awesome! I am so glad to hear that the issue is now resolved 🎉​

Thanks so much for sharing those steps to troubleshoot this issue - this information will be very helpful to other users who experience the same issue too!

Thanks again for reaching out. Please feel free to reach out to us if you have any other questions 🚀​

via @taehoshino | Postman Support

**Comment by DannyDainton** [comment]
Closing this as it seems like the issue is now resolved. 🎉
