### ISSUE TITLE
Problem with "Alt+Shift" key combination in electron apps

### ISSUE THREAD

**Issue by CTACyok** [a85/POSTMan-Chrome-Extension#9674]
On many Linux platforms "Alt+Shift" key combination is used to switch between multiple input languages, but in electron "Alt" key always forces focus from input field to app menu strip, stopping text input until focus is shifted back manually.
It does not break any functionality, but it's really annoying

It's a known electron issue, it has been already discussed here https://github.com/electron/electron/issues/17418

**Environment Information**

 - Postman Version: 8.0.6
 - Operating System: Ubuntu 18.04

Thank you!

**Comment by jviotti** [comment]
Merging with https://github.com/postmanlabs/postman-app-support/issues/7349
