### ISSUE TITLE
Missing Arrow Beside Title

### ISSUE THREAD

**Issue by cybercrypt13** [a85/POSTMan-Chrome-Extension#9677]
**Describe the Issue**

**Steps to Reproduce**

**Screenshots or Videos**

**Environment Information**
All versions of OS and latest versions of the client software modules.  The website seems to have also lost access to this description field but I never used to have to use the website for anything so not sure if it was there before or not.

**Comment by DannyDainton** [comment]
Hey @cybercrypt13

Without more information and an image of the app UI, it's going to be difficult to help here.

Could you update the details, please?

**Comment by Raja-Simha** [comment]
@cybercrypt13 The collection browser is not available in the new UI ( App version >8.0 and web)
You can now edit descriptions for collections, folders, and requests from their respective tabs.

![image](https://user-images.githubusercontent.com/45988836/109772108-9f1b5400-7c23-11eb-916c-03b6f2c79f6a.png)

Please reopen if this does not answer your question.
