### ISSUE TITLE
Missing the Publish menu when right clicking a Collection event or clicking 3 dots

### ISSUE THREAD

**Issue by cybercrypt13** [a85/POSTMan-Chrome-Extension#9678]
**Describe the Issue**

**Steps to Reproduce**

**Screenshots or Videos**

**Environment Information**
All OS's and applications

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @cybercrypt13

Without more information and an image of the app UI, it's going to be difficult to help here.

Could you update the details, please?

**Comment by Raja-Simha** [comment]
@cybercrypt13 publish option is not available in the collection menu anymore (App version > 8.0 and the web)
- You could share your collection in a public workspace OR
- Create a public doc ( collection menu -> view documentation -> publish)
