### ISSUE TITLE
Add an "Export" button for the environment

### ISSUE THREAD

**Issue by Zinnurka** [a85/POSTMan-Chrome-Extension#9680]
Please add an "Export" button for the environment  (Postman Windows v8.0.6)

![image](https://user-images.githubusercontent.com/32505382/109758014-c4509800-7c0c-11eb-9f86-234c21790d15.png)

**Comment by DannyDainton** [comment]
Closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/9608
