### ISSUE TITLE
Trimmed underscore character in comments 

### ISSUE THREAD

**Issue by goose12** [a85/POSTMan-Chrome-Extension#969]
If I create a collection and in the box "Request description" I add a text like "hello_great_world", after save this description, the underscore is not shown in the main panel and the text hellogreatworld (without underscores) is shown.
![01](https://cloud.githubusercontent.com/assets/11527130/6696131/291c2f2a-cca4-11e4-9a21-0453f307fc35.png)
![02](https://cloud.githubusercontent.com/assets/11527130/6696133/2fef4594-cca4-11e4-9b01-e1affbd13a1f.png)

**Comment by shamasis** [comment]
This is happening for you due to the *markdown* support built into the description field. Try escaping the underscore characters using `\`. As such your text would show underscore if you write it as `gus\_ta\_go.com`.

> More about markdown - http://en.wikipedia.org/wiki/Markdown
