### ISSUE TITLE
Improve UX of comment/build mode

### ISSUE THREAD

**Issue by askherconsulting** [a85/POSTMan-Chrome-Extension#9693]
**Is your feature request related to a problem? Please describe.**
I raised what I thought was a bug because I couldn't edit a request after adding and closing the comments panel. (see attached video)

**Describe the solution you'd like**
I think at the least closing the comments panel should revert the user into build mode, so they can continue to edit their request. At the most, getting rid of build/comments modes altogether would be perfect (although maybe there's a use case justification that I'm not aware of).

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/29501750/110243984-9644be00-7f54-11eb-8ca7-99bdd04af86b.mp4

**Comment by akshay-kulkarni-03** [comment]
We have removed the build/comment modes all together from Postman v11 version. You can now work on your collections/requests easily and collaborate with your team mates seamlessly.
