### ISSUE TITLE
Request for Ability to own or control forks of a collection

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#9694]
## **Is your feature request related to a problem? Please describe.**

- Currently when a Collection is forked in a workspace, the user who forks it gets the "`Editor`" role, while others get the "`Viewer`" role.
- This hinders the workflow where the original Collection owner wants to merge and delete the "`source`".
- The main collection owner has to explicitly reach out to the users owning the fork and ask them to grant the "`Editor`" role on forked collections.

## **What are the proposed solutions?**

- **Preferably, Allow a collection owner to own any forked collections as well**
  - Thus granting them editor role over forked collection in the same workspace
  - This would allow a collection owner to control forks and permissions on forks
  - This can be a **setting** or an **additional role** - per collection
  - This would be the most preferred solution as this allows the ability to have the control per collection.
- OR, **allow a Workspace admin to have "`editor`" role on all collections within a workspace**
  - This is an alternative proposal, where the main collection owner can be made a Workspace admin granting them access to all collections and forks within a Workspace
  - This helps but would require elevating a user to Workspace admin role
  - Maybe an additional "**Collection Owner**" role can be added at the Workspace level? - that grants "**Editor**" role for all collections in a workspace?
  - Not the best solution, as it either access to all collections or none.

## **Describe alternatives you've considered**
- No feasible workaround other than to manually reach out to the user "owning" the fork, every time a Pull-Request is to be merged and source to be deleted.

### **Additional context**
Logged by **Postman Support**  for internal feature-request which was filed based on use-case analysis for a customer's report.

**Comment by kartikjain26** [comment]
@preethammavin  @xk0der  can we close this ?
Workspace admins now can merge and delete the forks in that workspace.
