### ISSUE TITLE
Add Markdown strikethrough support

### ISSUE THREAD

**Issue by jolsen71** [a85/POSTMan-Chrome-Extension#9699]
Postman supports a pretty good chunk of the common Markdown markup, but it seems that it lacks strikethrough support. 

According to GitHub Markdown specifications, text that is intended to be struckthrough should be wrapped in two tildes. 

For example, documentation that is entered in markdown that looks like this:
&nbsp;&nbsp;&nbsp;&nbsp;Hello, \~\~Bob\~\~James
When rendered with a system that supports strikethrough, will appear as:
&nbsp;&nbsp;&nbsp;&nbsp;Hello, ~~Bob~~James.

Interestingly, Postman strips the double-tildes out of the rendered documentation, but it doesn't show the text as struckthrough. So the above example comes out looking like:
&nbsp;&nbsp;&nbsp;&nbsp;Hello, BobJames.

https://guides.github.com/features/mastering-markdown/
https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax
https://en.wikipedia.org/wiki/Markdown#Example

**Comment by rishipurwar1** [comment]
@DannyDainton Can I work on this issue?

**Comment by kamaraj-p** [comment]
This issue has been resolved
