### ISSUE TITLE
I don't want to use cloud space

### ISSUE THREAD

**Issue by AndrewTseZhou** [a85/POSTMan-Chrome-Extension#9701]
I don't want to use cloud space. Start up very slowly.

**Comment by DannyDainton** [comment]
Hey @AndrewTseZhou

Could you fill the full details of the issue template form and explain what's happening for you, please? 

Any usage information, details about the version you're using, videos showing the performance, screenshots of activity logs would also help here.

Without any information and context, it's going to be very difficult to do anything about this.

**Comment by Chaakar** [comment]
Same issue. After this major update with the very inconvenient redesign, in case if you work with the local collection, start up very slowly, history is cleared, so the tabs which are using requests from history fails with errors. Navigation between requests in history is also very slow. Before the update, it was almost instant, now it can load the whole minute
Postman version: 8.0.6

**Comment by DannyDainton** [comment]
Hey @Chaakar,

This initial report doesn't contain any details about what is happening for that user.

As you are describing certain UI areas and perceived performance, can you expand on the details and provide images or a screen recording so that it's clear what is currently happening for you.

**Comment by DannyDainton** [comment]
Closing this issue for now - Can be opened once more information is provided.

**Comment by iMro0t** [comment]
@Chaakar exactly. This version broke so many things in my current setup and most important history is cleared. I was having so many useful links before but now all are gone without any warning or notice. I couldn't find any alternative and this electron-based thing will never gonna beat the performance of the native app.
