### ISSUE TITLE
Do not expand requests when clicking on their names

### ISSUE THREAD

**Issue by HenrikHolmIT** [a85/POSTMan-Chrome-Extension#9703]
Please do not expand requests when clicking on their names. Only when clicking the > icon should you expand them.

Im on the latest version and I find it really annoying that requests expand when clicking on them and without being able to collapse them again by clicking name. It fills up my explorer view pretty quick and ruins my overview. I rarely need to view what is under a request.

**Describe the solution you'd like**
I want for requests to only expand and collapse when clicking the > icon, not when clicking the name itself. I dont mind if this is handled by an option as there are probably users who would like them to expand. I do not. 

Please dont just solve this by making clicking on name also collapse. I dont what it to ever expand in the first place. Never. Only when I need it to expand will I click the > icon.

Im on version 8.0.7

**Comment by DannyDainton** [comment]
Hey @HenrikHolmIT 

This feels similar to this open issue:

https://github.com/postmanlabs/postman-app-support/issues/9614

If so, I would like to close this and direct all feedback over to that one, to keep all the information together.

Also, you should be able to use the _left arrow_ key to collapse any open Collections, Folders or Requests in the sidebar.

**Comment by HenrikHolmIT** [comment]
Hey @DannyDainton 

Yes they do indeed describe the same problem. Clutter in the Request Sidebar.

Only my solution would be very quick to do and would not have to rewrite the entire feature. Just remove the Expand on Request Name Clicked event and only have it expand when clicking the > icon. Then it will not clutter and will still be a possibility if you need to handle the subitems.

Does that make sense? I'd want to add the above text to the other case so it can be taken into consideration if you decide to update the feature.

**Comment by DannyDainton** [comment]
We're still taking feedback on all the new changes made for V8, from a number of different places - No final decisions have been made about the potential improvements just yet. 

I'm going to close this issue - could you add any new comments to the #9614 thread, please.
