### ISSUE TITLE
Include the 'Edit' option in the 'View more actions' of the request.

### ISSUE THREAD

**Issue by JuniorMonzani** [a85/POSTMan-Chrome-Extension#9704]
**Description:**
Improvement in the process of adding or changing the description of the request.

**Steps:**
1 - In the request, click on 'View more actions' and select 'View documentation'.
2 - Search for the request you want to include or change a description.

**Result obtained:**
The process of adding or changing a description to the request has become more time-consuming and laborious.
First we have to click to view the documentation, then look in a large list for the requisition that I want to include or change the description of.

**Expected outcome:**
![Sem título](https://user-images.githubusercontent.com/36019213/110506664-0fbbe800-80de-11eb-9d41-b58f6372dbf3.png)

Ideally, the option 'Edit' should be included in 'View more actions' as in previous versions. So we will have much more agility to include or change the documentation for each request. More agile, easier, better navigability.

**Comment by DannyDainton** [comment]
Hey @JuniorMonzani 

It looks like you're using an old version of the app as we have recently moved to V8, which comes with more changes to the UI.

If you didn't want to upgrade straight away, you could check out the new changes using the Canary build.

https://www.postman.com/downloads/canary/

**Comment by JuniorMonzani** [comment]
I'm on version 8.0.7

But this print that I put was from an old version just to illustrate where this 'Edit' option could continue.
In version 8.0.7 I have to go a long way to add or change a description, with this option under 'View more actions' it would be easier and faster.

I'm sending a print of how it is and how it would look with the option, if they think it is necessary.

![Sem título](https://user-images.githubusercontent.com/36019213/110522105-4fd79680-80ef-11eb-9766-80e74f125f04.png)

Thanks!

**Comment by DannyDainton** [comment]
When you have a saved request open in the main window, the context bar on the right side of the app, always has the documentation icon (just below the eye icon) available.

Hitting a single icon button that's in view, would open it for you to edit, rather than hitting the ellipsis and then an edit button.

**Comment by JuniorMonzani** [comment]
Perfect Danny!

Indeed, this functionality remains simple to access.

I did not pay attention to the sidebar with the information from the open request.

And it actually got a lot more interesting.

Thanks!
