### ISSUE TITLE
Collapse / Expand folders by clicking on it

### ISSUE THREAD

**Issue by ajilk** [a85/POSTMan-Chrome-Extension#9705]
Clicking on the folder within a collection expands the folder but doesn't collapse/close it.

**Comment by timbochamp** [comment]
Hi @ajilk , thanks for bringing this up! This behaviour used to exist in older versions of the app. I'll raise it as a bug to be addressed.

**Comment by HenrikHolmIT** [comment]
Please add an option to not have it expanded when clicking the name. That is a really annoying behavior and will clutter the Requests list pretty quick. If this option exists and is checked then clicking the > icon should still expand. Only when clicking the name to bring up the properties of the request should it not expand.

**Comment by timbochamp** [comment]
@HenrikHolmIT , that's a fair suggestion! I've relayed that along to our user experience team as a feature request.

**Comment by mattantonelli** [comment]
This bug is my biggest issue with Postman 8, and I'd love to hear if there's any update from the UX team.

The new Collections view is half the size it used to be, and you have to carefully mouse over the new tiny arrow to close your collection. An option to switch back to the old non-compact view would be wonderful.

**Comment by HenrikHolmIT** [comment]
This issue should be merged with this issue: https://github.com/postmanlabs/postman-app-support/issues/9614

**Comment by krishnanandps1** [comment]
^ Why? It's a completely different issue altogether.

Also, it's July and this hasn't been fixed yet; please increase the priority for (what, for me personally, is certainly an...) issue!!!

**Comment by giridharvc7** [comment]
This is fixed with v9.15.8 
Please update the app and let us know what you think

**Comment by HenrikHolmIT** [comment]
Updated. Looks like you nailed it. Thanks.
