### ISSUE TITLE
Can't remove the collection from team workspace (unshare the collection)

### ISSUE THREAD

**Issue by feelipegr** [a85/POSTMan-Chrome-Extension#9706]
**Describe the Issue**
I created a collection at my personal "My Workspace" and shared it with the team, but now i want to unshare it. So, i try to remove the collection from "Team Workspace", but i receive this message: "This collection is only present in this workspace and can't be removed.". I created another collection to do a test and if i use "delete" option the collection is removed from everywhere.

I just want that the collection returns to be only at my personal workspace as when i created that.

**Steps to Reproduce**
1) Create a collection in your personal (private) workspace "My Worskpace";
2) Share this collection with your team (Team Workspace);
3) Try to remove the collection from the Team Workspace;

**Environment Information**

Platform Type: Web/Desktop
Postman Version: v8.0.7
Operating System: Windows 10

**Additional Context**
I need to "unshare" this collection because i have the free plan and i have a public documentation associate to this collection and the shared requests is going to hit the limit and i don't want that to be archived.

I created a third workspace and shared the collection with it, but it stills blocking me to delete from the team workspace, but i can remove from the others workspaces. It works like the owner of the collection were the team, but it's not.

Edit: I was searching at the community and found this information in a topic "Note that any collection you created and then shared in a team workspace becomes a team owned collection.". I shared with the team just to do a test and see how it works, and it was not clear that the collection would be owned by the team. I think that it would have an option to revert this since that it was me the owner of the collection and admin of the team (that has only me now, but it counts for the shared requests).

Edit²: I "solved" the problem by duplicating the collection and then deleting the original. So it was necessary to publish a new documentation and unpublish the original before deleting the collection. And after publish the new one i have to update the anchors tag becase the ids were different.

**Comment by DannyDainton** [comment]
Hey @feelipegr - I've created a bug from this issue. The behaviour and workflow are known but it's something that we might need to take another look to see if some improvements can be made here.

I will update this thread once we have more information.

**Comment by feelipegr** [comment]
Ok @DannyDainton, thanks, i'll follow this

**Comment by joeyeng** [comment]
This is much needed. Thanks

**Comment by kevinswiber** [comment]
@feelipegr @joeyeng 

As a workaround for the time being, you can:

1. In your personal workspace, expand the menu on the collection and select "Remove from Workspace."
2. Back in your team workspace, expand the menu on the collection and select "Share collection".
3. In the Share modal, choose your personal workspace and select the option "Share and remove from current workspace".

This will allow you to keep the collection metadata intact while successfully removing it from the team workspace.

Hope that helps.

**Comment by khandelwalneeraj** [comment]
Hi folks, the hack does work but would really appreciate if the fix could be released asap.

**Comment by akshay-kulkarni-03** [comment]
@khandelwalneeraj / @feelipegr we have re-vamped our sharing experience, where you can how provide explicit roles to team members/user groups while sharing an element. In your case, if you just provide a view role to the other team members your request limit should not get breached in that case. I will discuss this internally with our team and will see if we can have `unshare` kind of a feature in the future.

**Comment by iquabius** [comment]
I can't find the option "Remove from Workspace".

![image](https://user-images.githubusercontent.com/3139777/152660380-8a5ddf84-c7b2-4bdf-bf6a-12bb208eba8b.png)

Is it somewhere else?

Was it removed?

**Comment by akshay-kulkarni-03** [comment]
@iquabius as of today we don't have explicit un-sharing functionality. You try out the below options to restrict the collection which is already shared.

1. You can click on Manage roles -> explicitly remove members with whom you no longer want the collection to be shared. (You need to be an admin of the collection to do this)
2. You can delete the collection from this workspace.
3. You can move the collection to a different workspace. You need to be an admin to perform this operation.
