### ISSUE TITLE
[Feature request] Let me auto select "Body" section on new tab

### ISSUE THREAD

**Issue by RaptorCZ** [a85/POSTMan-Chrome-Extension#9710]
When a new tab is opened, it always starts in "Params" section. I would like to be able set in configuration default section. 

In 99% of actions I need to open saved request, change data and Send. I understand that it is primary for POST and not for GET verbs, but if can user set this behavior in configurations, it will be win-win.

**Comment by arlemi** [comment]
Thanks for the feature request @RaptorCZ , we're already tracking this in #2086 and are hoping to push something out over the coming weeks. 🙂 Keep an eye on the other issue if you want to stay updated.
