### ISSUE TITLE
Additional `await` invocations fail to execute after first `await` completes.

### ISSUE THREAD

**Issue by ode2code95** [a85/POSTMan-Chrome-Extension#9715]
The JS test script runner is unable to process multiple `await` calls within a single `async` function.
Given these functions:
```javascript
let testFunc = async (taskId) => {
    console.log(`Launching ${taskId} . . .`);
    for (i = 0; i < 10; i++) {
        await waitFunc(taskId, i + 1);
    }
};

async function waitFunc(taskId, count) {
    return new Promise(resolve => setTimeout(() => {
        console.log(`(${sw.elapsed()}) ${taskId}: Completing ${count} - Done!`);
        resolve();
    }, 1000));
}

// Implementation of simple JS stopwatch omitted for brevity;
// basically it clarifies the execution order of the Case #3 below.
let sw = new StopWatch();
sw.start();
```

These snippets produce the following results:
```javascript
// Async execution within testFunc stops after the first iteration.
(async () => {
   await testFunc("A");
})().catch(e => console.log(e));
```
![image](https://user-images.githubusercontent.com/23080282/110726475-70831780-81e7-11eb-9485-69429a8a9c57.png)

```javascript
// Same thing happens here.
testFunc("B");
```
![image](https://user-images.githubusercontent.com/23080282/110726810-1171d280-81e8-11eb-9c53-fbe376486479.png)

This 3rd case is very interesting.
```javascript
// But when we trigger two parallel runs,
// they take turns firing until the loop is done.
testFunc("A");
testFunc("B");
```
![image](https://user-images.githubusercontent.com/23080282/110726894-3c5c2680-81e8-11eb-9608-c1cc04e7af6f.png)

**Comment by xk0der** [comment]
Hey @Stanley-G 👋 
Have a look at [this thread](https://community.postman.com/t/executing-sync-requests-programmatically-from-a-pre-request-or-test-scripts/14678/2?u=amit) at Postman's community forum

**Quoting the relevant sections:**
> The Postman Sandbox detects open timeouts and intervals and awaits execution until they’re all cleared/resolved. If we use a dummy Interval object, we can use async/await to have a cleaner method of chaining asynchronous calls.
> _Example_:
>  ```
>  const _dummy = setInterval(() => {}, 300000);
>  . . .
>  . . .
> (async function main() {
>     . . . 
>     . . .
>     clearInterval(_dummy);
> })();
> ```

See if declaring a dummy Interval object at the start fixes the issue for you.

**Comment by ode2code95** [comment]
> See if declaring a dummy Interval object at the start fixes the issue for you.

That absolutely did the trick! Thanks a lot, @XkOder!
But I am curious if there is a reason why the Postman sandbox cannot handle this situation automatically?

**Comment by postman-staff** [comment]
Hey @Stanley-G

Glad that helped!

And that's an excellent question! Postman's community forum would be a great place to ask that: https://community.postman.com/
Our engineers frequent the community forum regularly and I'm sure they would love to provide more insight into the inner workings.

As for this GitHub issue, given we have a solution, I will close this out next.

via @xk0der | Postman Support

**Comment by postman-support** [comment]
Hey @Stanley-G

Glad that helped!

And that's an excellent question! Postman's community forum would be a great place to ask that: https://community.postman.com/
Our engineers frequent the community forum regularly and I'm sure they would love to provide more insight into the inner workings.

As for this GitHub issue, given we have a solution, I will close this out next.

via @xk0der | Postman Support

**Comment by steven94kr** [comment]
Hello! I am steven.
This issue has already been closed, but I'm curious.

Why the postman-sandbox library quit when it meets the first await?
Is there such code?
Is it intended?
