### ISSUE TITLE
Adding links to Pull Requests in Desktop Application

### ISSUE THREAD

**Issue by nrmartell** [a85/POSTMan-Chrome-Extension#9720]
**Is your feature request related to a problem? Please describe.**
User pointed out the frustration of not being able to grab a link for a PR in the native application, this is possible in the Web app, but is still not super intuitive

**Describe the solution you'd like**
Add a button to grab the link of a PR to share with teammates/collaborators

**Comment by ankit-m** [comment]
@nrmartell Thank you for filing this issue on user's behalf. I understand the concern and we are looking to introduce better ways to share PR links from the native app. I will keep this thread updated.

**Comment by Sushi21** [comment]
+1
We are looking exactly for the same feature.

I sent a request to Postman team and they mentioned someone already opened a Ticket for it.

As I was mentioning to them. Right now we are requiring our devs to put the link of their Postman PR within their Code change PR.

We are 99% using the desktop application and it would be nice if somewhere we can easily grab the URL of the PR created in Postman app to share it within other PRs or member of the team.

**Comment by ankitjaggi** [comment]
This is now available on the desktop app. You can view the copy link option by hovering over the Pull Request name.

![Screenshot 2022-05-27 at 12 27 22 PM](https://user-images.githubusercontent.com/6972850/170647734-549039f2-a90a-4f70-a8f4-c5b038ae2517.png)
