### ISSUE TITLE
Using global variables URI in run

### ISSUE THREAD

**Issue by kilimandzsaro** [a85/POSTMan-Chrome-Extension#9722]
Hi,

**Problem**

My team is using postman collections in CI with environments. We are using the url of the environment to run our collection (with newman) (`-e https://api.getpostman.com/environments/<UUID>`)

Also we have some global variables which works as quazy constants.

Recently I tried to use newman's "-g" switch to setup the tests with not only the environment variables, but with global variables.

I tried to use the URL of the global variables, and while I found the UUID of it I noticed that there is no endpoint in the API which gives me back the globals (not like there's an endpoint for environment variables). I tried to use the https://api.getpostman.com/environments/<UUID of the global variables> endpoint, but obviously there is no such thing.

**Current workaround**

1. As a workaround I added the used global variables to the environment we use for CI, but it is not a good solution for us.

2. Downloading the globals as json and pass the json file to newman's `-g` switch also feels like the same workaround, since if I modify something in the globals I don't want to do it in multiple places (like downloading the globals again and storing somewhere where the CI can use it). 

**Suggestion**

It would be a useful feature to add an endpoint to get (later add/modify/delete) global variables.
1. Can be added as an environment (which can be confusing, since it is not an environment): `https://api.getpostman.com/environments/<UUID of the global variables>`
2. Or can have a separate endpoint for globals: `https://api.getpostman.com/globals/<UUID of the global variables>`

**Comment by ravigajul** [comment]
Do we know if globals API is gonna be available soon?

**Comment by georgina-molo** [comment]
I have a similar request to this. I am using Postman CLI, running the tests in the CI/CD pipeline. I would like a way to pass in the UUID of the global environment into the command(the same way as you can with environment variables). Right now this is not a possibility. You have to get the file while inst really feasible.

**Comment by davidespihernandez** [comment]
Hi! We made some additions to the Postman API in the last months:

* The new [Workspace Global Variables API](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-a75846bd-c1c7-43e3-88f6-a0c752db83c5) allows to CRUD the workspace global variables (similar to the environments API).
* In addition, you should be able to modify collection variables using the [PATCH collections endpoint](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-24607f03-453e-4936-b544-78d99e05cd19).

Hopefully, you will find these APIs helpful.
In addition, you can use global variables in Postman CLI via command line options. More information can be found [here](https://learning.postman.com/docs/postman-cli/postman-cli-options/#:~:text=Multiple%20CLI%20global%20variables%20can,var%20%22alpha%3Dbeta%22.&text=Specifies%20the%20file%20path%20for%20global%20variables.).
