### ISSUE TITLE
Permanently Moved response (301) is redirected via GET method

### ISSUE THREAD

**Issue by hejplis12** [a85/POSTMan-Chrome-Extension#9723]
If POST request with POST params was executed and server returns 301, POSTMAN executed second request (with redirect URL) with GET method.

The second request needs the same method as first one.

**Comment by DannyDainton** [comment]
Hey @hejplis12 

Is the same thing happening with the `Automatically follow redirects` disabled?

![image](https://user-images.githubusercontent.com/17089546/110939035-aed61f00-832c-11eb-9b12-c9538d325e04.png)

Similar issues with redirects can also be found on this thread https://github.com/postmanlabs/postman-app-support/issues/8689#issuecomment-647586364

Would you be able to expand on the issue you're describing, please? Attaching recording and screenshots will help too. 

Also, you haven't mentioned any environmental details about the platform or version that you are seeing this problem.

**Comment by hejplis12** [comment]
Ah, sorry for that.
I'm working on Windows with Postman v8.0.7

 When the `Automatically follow redirects` is disabled it will return 301 correctly.

I call request via POST with xml post body. Server response with 301 and new URL and when Postman try to execute the new URL it will fall with 405 error because new URL needs POST request (same as first one) but Postman send GET.

![2021-03-12_13h34_40](https://user-images.githubusercontent.com/35332123/110941084-0f1e8e00-8338-11eb-9c33-5eb18bd6cb3a.png)

![2021-03-12_13h35_51](https://user-images.githubusercontent.com/35332123/110941087-0fb72480-8338-11eb-9ef6-a369d24ccc7e.png)

**Comment by DannyDainton** [comment]
There is also another setting below the one you have on the second image:

![image](https://user-images.githubusercontent.com/17089546/110941419-42f5b580-8330-11eb-924d-6063fae1b32c.png)

> Redirect with the original HTTP method instead of the default behavior of redirecting with GET.

**Comment by hejplis12** [comment]
Ok, thats it. Thanks for help and your time. You can Close this issue.
