### ISSUE TITLE
Link to read documentation after completing a tutorial is messed up

### ISSUE THREAD

**Issue by sanghvian** [a85/POSTMan-Chrome-Extension#9725]
**Describe the Issue**

Every time a tutorial finishes, link to additional documentation shows up. However, it appears in **pure URL form alongside non-converted markdown** instead of a clickable link

**Steps to Reproduce**
Change code in files handing the bootcamp

**Screenshots or Videos**
![Screenshot from 2021-03-14 10-47-37](https://user-images.githubusercontent.com/69717009/111062585-c994c900-84cf-11eb-9f87-4ed47c8b20e3.png)

**Environment Information**

 - Platform Type: Linux
 - Postman Version: 8.0.7
 - Operating System: Ubuntu 20.0.4 

**Additional Context**
Issue is only that I have to manually copy paste the URL to read  further documentation from postman into the browser instead of having easy click access 

Also, I am a relatively new contributer to open source so can you **please assign this issue for me to work on.**.
It seems fairly straightforward so I can solve it

**Comment by DannyDainton** [comment]
Hey @crew-guy

Thanks for reporting this issue with the markdown parser on that notification, can you confirm the version please as that looks like the  v7 app but you have V8 listed.

This part of the product isn't open source so it will be handled by the team. 

We appreciate the offer though ❤️

**Comment by sanghvian** [comment]
Hey @DannyDainton 

I just checked the version. You were right ! It is **version 7.36.5** 😅 
Thanks a lot for addressing this issue !!

**Comment by mccannt** [comment]
This is a breaking change introduced in v8 that impacts the v7 version of the application. 
Please update to the latest release to resolve this issue.
