### ISSUE TITLE
Allow editing request documentation in a separate tab

### ISSUE THREAD

**Issue by lex57ukr** [a85/POSTMan-Chrome-Extension#9727]
**Is your feature request related to a problem? Please describe.**
It's inconvenient to edit or create new documentation in the far right panel (especially on wide monitors). The far right panel is ideal for viewing but is inadequate for writing comprehensive documentation.

**Describe the solution you'd like**
Support transitioning the Documentation editing pane to its own tab.

**Describe alternatives you've considered**

**Additional context**
In-place editing still has its place and works nice to fix a typo or for a brief update. Viewing existing docs is great in the far right pane just the same. Documenting _many_ endpoints in this manner just doesn't cut it (for ergonomic considerations among other things).

**Comment by DannyDainton** [comment]
Hey @lex57ukr 

In the request context menu, at the bottom of the Documentation section, you will see this option:

![image](https://user-images.githubusercontent.com/17089546/111290013-9ff9b000-863d-11eb-8b39-ea5ba0e16c81.png)

This would open the full documentation in a new tab where you would be able to edit each part of it:

![Screenshot 2021-03-16 at 09 55 30](https://user-images.githubusercontent.com/17089546/111290173-c9b2d700-863d-11eb-9b8f-102919d9b06a.png)

Is this the behaviour you are describing in your feature request?

**Comment by lex57ukr** [comment]
@DannyDainton -- this is close enough. It's not obvious though. It doesn't imply the editing capability and one should navigate to the appropriate section to edit.

It would have been better if there was a second link, e.g. "Open this documentation" or "Focus on this documentation", which would either navigate to the current request's docs OR load up only that particular request's docs in a tab. I guess this is relevant for rich API collections. It's less important for small docs.

**Comment by DannyDainton** [comment]
Each Collection, Folder and Request also has this option to view the documentation without the need to go to the context menu option:
![image](https://user-images.githubusercontent.com/17089546/111338386-cf74e080-866e-11eb-99aa-5dbf4175d0f4.png)

**Comment by lex57ukr** [comment]
That "View documentation" option opens the same view for me without navigating to the actual section of the doc, i.e. it is equivalent to the "View complete collection documentation" in its function.
