### ISSUE TITLE
Mac 8.0.7 client: environment variable exists, but is not replaced by its value when making call

### ISSUE THREAD

**Issue by maccer83** [a85/POSTMan-Chrome-Extension#9729]
**Describe the Issue**
Some environment variables suddenly stop being used when making calls.
The variables exist when looking at the variables list for the environment or when hovering over the variable name in the URL field.

**Steps to Reproduce**
1. Insert a variable to the url.
2. Hover with the mouse over it, and see that it does exist in the chosen enviroment
3. Make a call.
The variable is not replaced. In my case it is a URL, so when making the call, I get back a error about address not found.

This is difficult to reproduce, but it could have something to do with syncing from a Windows Postman client to a Mac Postman client. I had a tab using the variable open and was told that there was a conflict, and I chose to discard my local changes. However, I have multiple tabs that use the same variable, and I was not asked about those tabs. The replacement fails in all tabs that uses the variable. It does not help to restart the Postman client or change to another environment or workspace and then back.

**Screenshots or Videos**
![Postman_-_enviroment_variable_not_recognized](https://user-images.githubusercontent.com/12064302/111202869-ac8df200-85c4-11eb-8ebf-03fcbf7633dc.png)

**Environment Information**

 - Postman Version: 8.0.7
 - Operating System: MacOS Catalina 10.15.7

**Additional Context**
The issue has happened two times during a span of perhaps 1-2 weeks.
The issue is not present when using the web client or the Windows client.

To fix the issue:
- First time this happened, I deleted the local Postman data folder according to [these instructions](https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-) and let the app re-create it when starting up next time.
- The second time I renamed the variable using the Edit page by removing one character from its name, saved it, added back the character, saved again. After that it started working.

**Comment by appurva21** [comment]
Hey @maccer83! 

We have released a fix for this in our latest app release ([v8.7.0](https://www.postman.com/downloads/)). Please feel free to reopen in case you are still encountering this issue on the latest version of the app or web client.

**Comment by Donato10** [comment]
This is happening to me again on  `Version 10.0.21` I am able to save a variable from a response but when I try using it in a subsequent request it is not populated. 
In my case, I am setting the environment variable {{token}} and then I use it on the authorization config (Bearer token {{token}}) for a subsequent request. I see the value is being populated but the request does not pick it up apparently. 

The workaround that works for me is changing the Authorization method configured to "No Auth" and back to "Bearer token" set {{token}} as the value to be used and try again

**Comment by shubhbhargav** [comment]
@Donato10 In order to debug this further, can you share a screen recording? Or in-case it is consistently reproducible, you can let us know the steps for the same.

**Comment by Donato10** [comment]
Steps:

1. Create a collection and set the Authorization method to "Bearer token" with the value being `{{token}} `(Notice this token environment variable does not exist yet)
<img width="937" alt="imagen" src="https://user-images.githubusercontent.com/5905031/194941973-29f49cd0-6040-460b-9f4c-a663b93284b8.png">


2. Create two environments to hold values for your collection. I named them "QA-1" and "QA-2" but that's not important.
3. Add a request pointing to your API auth endpoint as the first request in your collection and add a test to it that will verify you got a successful authentication, extract the JWT returned, and set it as an environment variable via 
`pm.environment.set("token", pm.response.json().token);` notice the name of the field to be consumed when setting the variable entirely depends on the API being hit.
<img width="649" alt="imagen" src="https://user-images.githubusercontent.com/5905031/194942095-67a9ff0e-277e-4a15-83aa-efbb018ede42.png">

5. Add another request to a protected endpoint in your API and verify the authorization tab of your request to make sure the method selected is "Inherit auth from parent". To verify it works add a simple test to check the response is 200 (or any other 2XX depending on what you expect).
<img width="551" alt="imagen" src="https://user-images.githubusercontent.com/5905031/194942240-ffed605d-3cc4-41a2-99db-d7cfe7aaa371.png">

6. Run the collection making sure you got both requests selected and in the correct order. This time expect it to work fine. The variable token is populated after running the collection.
<img width="1130" alt="imagen" src="https://user-images.githubusercontent.com/5905031/194942290-d30c2565-2026-4b0a-bd71-627af28f088e.png">

7. Switch to your second environment (I do it using the dropdown on the right upper side of the client UI) and run the collection again. In this case the error `TypeError: Cannot read properties of undefined (reading '0')` happens on the second request and the Authorization header is not sent. However, the token variable is successfully populated with the right value if you check the environment variables.
<img width="308" alt="imagen" src="https://user-images.githubusercontent.com/5905031/194942380-b5e2981b-7d4f-432b-9cd3-eb17b3869991.png">

8. If you switch back to the previous environment it does not work anymore and shows the same error.

**Comment by Donato10** [comment]
Another workaround that worked for me, this time fixing the problem is exporting the collection and environments and re-importing them, potentially something was wrong with the specific collection I had before, I could not reproduce anymore after re-importing @shubhbhargav

**Comment by Donato10** [comment]
Replicated once again, after restarting the computer start failing again

**Comment by shubhbhargav** [comment]
@Donato10 Looks like there was a bug in the 10.x version at the time. We have raised a fix for that. More details on this ticket: https://github.com/postmanlabs/postman-app-support/issues/11348

Do restart the app once just to be sure to get the fix working. Let us know in-case you still end up facing the issue.
