### ISSUE TITLE
Create a request through code snippet

### ISSUE THREAD

**Issue by Holinc19** [a85/POSTMan-Chrome-Extension#9732]
I can copy code snippet if I have created the request, but it is unable to create a request with code snippet.

**Comment by DannyDainton** [comment]
Hey @Holinc19

Can you expand on the usecase here please, not really sure I understand what you're trying to do.

The curl snippet created is probably the only one that could be turned into a request in the app, via the import feature.

**Comment by Holinc19** [comment]
> Hey @Holinc19
> 
> Can you expand on the usecase here please, not really sure I understand what you're trying to do.
> 
> The curl snippet created is probably the only one that could be turned into a request in the app, via the import feature.

nice, that's what I need.
