### ISSUE TITLE
Disable the "Run in Postman" button on published document

### ISSUE THREAD

**Issue by dineshvarmabudagam** [a85/POSTMan-Chrome-Extension#9734]
we want to publish the api documents and we want to share this documents with clients so it’s unprofessional and bad if my company’s official API documentation shows another company’s logo/information(Run in Postman) at the top of it.
I can understand this sort of thing for the Free service, but not the paid Postman Pro service. we dont want this Run in Postman Butoon on my published document. Please guide me how we can disable it.

**Comment by DannyDainton** [comment]
This request has previously been raised and closed.

https://github.com/postmanlabs/postman-app-support/issues/5465

The text of your request also looks like it's been taken from this comment - https://github.com/postmanlabs/postman-app-support/issues/5465#issuecomment-538803080

**Comment by dineshvarmabudagam** [comment]
May I know the resolution for above query???

**Comment by DannyDainton** [comment]
The originally posted issue (linked in my comment) from which your comment was taken, was closed. 

I don't believe there is going to be an option to disable the `Run in Postman` from the Postman created documentation.

**Comment by DannyDainton** [comment]
Closing this issue for now.

**Comment by vipin-chandran-compatio** [comment]
This would have been a useful feature for us too.
