### ISSUE TITLE
Overview Tab count mismatch

### ISSUE THREAD

**Issue by rajat12a** [a85/POSTMan-Chrome-Extension#9738]
**Describe the Issue**
Seeing the count mismatch in overview tab for mock server for a certain workspace
It shows 1 mock server but under mock server tab it says no mock server present

**Screenshots or Videos**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17059581/111367615-eb05d880-86ba-11eb-8c9b-f617cc8bd53f.png">

**Environment Information**
 - Platform Type: Postman for Mac
 - Postman Version: Version 8.0.7
 - Operating System: OS X 20.3.0 / x64

**Comment by akshay-kulkarni-03** [comment]
Hi @rajat12a , our workspace overview section was revamped and the inconsistencies reported in the above screenshot were also fixed as part of that. 
Feel free to re-open this issue in case you face the issue again.
