### ISSUE TITLE
Initial value column takes values from current value 

### ISSUE THREAD

**Issue by GAnatoliy** [a85/POSTMan-Chrome-Extension#9740]
Hello,

There is incorrect behaviour with initial values (environments) after update to  v8.0.7
I write PASSWORD_STUB text to the initial value and actual password to the current value.
But after some time if I open environments tab (after some request, etc) I see that current value copied to the initial value, 
so I assume that my password will be shared with team, that isn't desirable behaviour. 

Postman Version v8.0.7
Operating System Windows 10

Thank you

**Comment by GAnatoliy** [comment]
I have noticed information that it is new feature (Automatically persist variable values) and it is behaviour by default for old users.
I assume that bug can be closed.
I just don't think that it is good idea to make this behaviour on by default, as far as I undestand my passwords were shared with team.

**Comment by DannyDainton** [comment]
Hey @GAnatoliy

Are able to provide some reliable step to reproduce this issue?

If you need to use an endpoint to recreate the scenario, you can use https://postman-echo.com/get

Without those reproducible steps, it's difficult to tell what is happening as you mentioned things like 'after some time', 'after some requests' as those are quite vague and alot of things could have happen to your whole environment in that time.

**Comment by postman-staff** [comment]
Hi @GAnatoliy,
Thanks for reaching out.

If I understand correctly the initial value of the variable gets overwritten by the current value of the variable right?
Can you please check if you have the option **Automatically persist variable values** turned on - if yes, can you make sure to disable it.

If the option '**Automatically persist variable values' **is enabled then the initial value of your variables will be overwritten by their current value after each request.

You can find that option in **Settings** -> **General**
 ![](https://postman.zendesk.com/attachments/token/A9wze6uUgDdNqH75oMwSr5kdT/?name=inline524058457.png)

Please let me know how it goes.
Looking forward to your response​

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @GAnatoliy,

I hope my previous comment provided more context as to why you were experiencing this behavior.
I also noticed that you managed to find the solution on your end as well.

If any further questions/concerns arise please do not hesitate to reach us back.
via @nasco-a | Postman Support
