### ISSUE TITLE
Authorization inheritance seems broken in newest version for OAuth 

### ISSUE THREAD

**Issue by mtaylorfsmb** [a85/POSTMan-Chrome-Extension#9744]
We have a collection that uses OAuth2 bearer tokens. In the collection root we have configured OAuth to authenticate against our endpoint. Requests inherit the authorization from the collection. 

In previous versions to send a request we would go to the collection's authorization UI and request a new token and use it. Then switch to the request tab and send a request and it worked. With the current version (have no idea what the version is because it isn't shown anywhere in the UI but it is the version available as of 17 Mar 2021), it doesn't seem to work anymore. It continues to use an old token.

**Steps to Reproduce**
1. Create a collection that is configured to use OAuth2 bearer tokens to authenticate.
2. Create a request that inherits the parent authentication.
3. Send a test request to verify it fails authentication.
4. Go to the collection's authentication UI and request a new token and use it.
5. Go back to the request and send the request again.
6. Look at the request headers and confirm the Authorization header is correct.
7. Restart Postman (not sure it matters)
8. Repeat steps 4-6

The old token continues to be used. The UI says it may not update but the actual sent request is using the wrong token as well so it isn't a UI issue. The token being used doesn't exist anywhere (all tokens were deleted before running the test). It seems the request just remembers the inherited value and won't replace it anymore.

**Screenshots or Videos**

**Environment Information**

 - Platform Type: Windows
 - Postman Version: 17 Mar 2021 version (doesn't show version # anywhere in UI that I can find)
 - Operating System: Windows 10

**Additional Context**
This used to work correctly so not sure why it isn't now.

**Comment by timbochamp** [comment]
Hi @mtaylorfsmb , thanks for reaching out. Just to be sure, are you saving the collection-level authorization settings?
![Screen Shot 2021-03-18 at 6 04 12 PM](https://user-images.githubusercontent.com/4521134/111697467-5e6f2d80-8814-11eb-9eac-5e1e11915cd3.png)

**Comment by mtaylorfsmb** [comment]
No I didn't even see that collections had a save button.

Why do I need to save the collection when getting a new access token is a temporary thing? Every time you load the collection you would get a new access token as the old token has likely expired. Furthermore you would never actually store the token as it is a transient value. So why does this require that I save the collection? It would be equivalent to having to save the collection every time I logged into something using a username/password.

**Comment by timbochamp** [comment]
It's definitely a pain point that we're looking into addressing in the future with a solution to prevent having to save after each token generation. There's no timelines around this yet, but I'll tag this accordingly.

**Comment by timbochamp** [comment]
This was resolved as part of #9763 . Please feel free to reopen if the issue is persisting at the same time!
