### ISSUE TITLE
Ability to Set Permissions for Private Workspaces at the Workspace Level

### ISSUE THREAD

**Issue by nrmartell** [a85/POSTMan-Chrome-Extension#9749]
**Is your feature request related to a problem? Please describe.**
Right now you have to manage permissions for a Private Workspace at a user level since private workplaces default to viewer level access. 
![Screen Shot 2021-03-18 at 1 36 40 PM](https://user-images.githubusercontent.com/13713173/111686856-315c5400-87ef-11eb-969b-04fda78aae4f.png)

It would be great to have the ability to set permissions at the workspace level for new workspace members.

**Describe the solution you'd like**
Ability to manage permissions at the workspace level for Private Workspace

**Comment by akshay-kulkarni-03** [comment]
@nrmartell can you check out this learning center [documentation](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#managing-workspace-roles)? You should be able to give permissions to users at a workspace level and it will automatically trickle down to the respective elements/models inside it (E.g. collections, APIs etc).

Feel free to re-open this issue, if the above documentation doesn't work!
