### ISSUE TITLE
Cannot Edit Envrionment (Tab will not open) 

### ISSUE THREAD

**Issue by F-shaikh** [a85/POSTMan-Chrome-Extension#9750]
**Describe the Issue**
When clicking "Quick Look" for a given environment, then clicking the "edit" button, nothing opens up in a tab for me to edit the given environment. This happens regardless of me using the environments tab, or the quick look "edit" button.

**Steps to Reproduce**
1. Go to Postman and open any environment.
2. Click on the quick look button 
3. Click on "Edit".

**Screenshots or Videos**

https://user-images.githubusercontent.com/38937921/111699873-e85bce00-87f5-11eb-81ed-958bd833a987.mp4

-For the sake of the video I whited out environment variables-

**Environment Information**

 - Platform Type: Postman Desktop for Mac
 - Postman Version: v8.0.7
 - Operating System: MacOS Catalina 10.15.7

**Additional Context**
This also happens for anything that requires a "tab" to open. See below a video of me trying to open a request, but it will not open because I dont click on "open in tab" thus, any other option in postman that requires a "tab" to open simply will not open because they do not have an explicit "open in tab" option for me to click on..

https://user-images.githubusercontent.com/38937921/111700254-5e603500-87f6-11eb-91a4-0b55fee280b0.mp4

**Comment by F-shaikh** [comment]
@DannyDainton , as requested here is a new bug opened showcasing all of my issues with the latest version of postman. Please let me know next steps, or if there is anything that is not clear.

**Comment by timbochamp** [comment]
Hi @F-shaikh , this sounds somewhat similar to #9599 , though they were on Windows in that case. Are you able to see any errors in the console (View > Developer > Show DevTools (Shared)) when this happens to paste here?

**Comment by F-shaikh** [comment]
@timbochamp nothing useful in console unfortunately: 
![image](https://user-images.githubusercontent.com/38937921/111850875-b23e4d00-88ce-11eb-8dca-c00b90fffcbf.png)

**Comment by timbochamp** [comment]
@F-shaikh thanks for the screenshot. I'm having a hard time trying to reproduce this 😞  . Is there any other contextual information you could give here like an upgrade path of what version you were on before upgrading to v8.0.7 (or if this was a fresh install)?

**Comment by Wotuu** [comment]
I'm having the exact same issue in one of my workspaces. It's unusable - I can click requests/collections on the left, but nothing ever opens in a new tab. Other workspaces are unaffected. It started after ran a Collection that generated over 5k tests, while having the response body saved. Postman memory usage was high and it was consuming a bunch of memory. I restarted Postman to get rid of the giant memory leak and ever since I cannot access the environment.

My issue looks 100% the same as the video above.

**Comment by timbochamp** [comment]
Thanks for reporting, @Wotuu . I tried running a 5k request collection with save responses selected on the app v8.0.9, but I'm still able to open an environment through the quick look eye icon then clicking edit from the modal. 

1. What was your memory usage hovering around if you remember? Mine was only at 900mb or so, so the requests I'm using might have been too bare-boned with simple GET requests.

2. what version are you using? Can you try upgrading to v8.0.9 if you're not on it already?

I'll log a bug for the team to start investigating this

**Comment by F-shaikh** [comment]
I resolved this by completely uninstalling postman and removing all local files. Then re-downloaded the application.

**Comment by Wotuu** [comment]
@timbochamp
1. I recall it being around 3-4GB memory used. It _may_ have also happened because a script I created was spamming some console.logs() which made the console unusable, it put the CPU usage to 50% for a few hours (I left it running in the hope it'd clear itself).
2. I was running Postman 8.0.6. I upgraded this morning to v8.0.10 and still have the issue.

I will reinstall Postman as suggested above, I tried to avoid that since it will clear my settings as well etc and cause other issues. But at least it will be workable.

**Comment by timbochamp** [comment]
Hi @F-shaikh and @Wotuu , is this issue still persisting for you on the latest 8.2.1 version out of curiosity? 

I can somewhat reproduce this when trying a lot of intensive operations like copying large 5k collections, but I'm able to open the environment edit page once those operations finish.

**Comment by Wotuu** [comment]
Hi @timbochamp , I just updated to 8.1 and I still had the issue. Wanted to post here to say it wasn't fixed yet - then saw your message. Upgraded to 8.2.1 and it seems to be working again. Maybe it had something to do with the setting `Always open requests in new tab` which I had enabled before, but I just had to re-enable. I don't know when it got turned off, but either way re-enabling it may have contributed.

Opening an environment and collection summaries now seem to work as well. Thanks for the help!

**Comment by timbochamp** [comment]
Great, I'll close this out but please feel free to reopen if the issue is persisting in the future!

**Comment by Wotuu** [comment]
Hi, I'm running the latest v8.3.0 and the issue just came back. There's nothing in particular that I did, it's exactly like was described above. Only my own workspace is affected and not any other workspace.

**Comment by timbochamp** [comment]
Thanks for flagging this, @Wotuu . I've reopened the bug for the team to continue investigating.

**Comment by Wotuu** [comment]
Thank you. If there's anything I can do please let me know and Ill be happy to help.

**Comment by Wotuu** [comment]
I just updated to v8.3.1 and that didn't resolve the issue, fyi.

**Comment by timbochamp** [comment]
Sorry to hear, @Wotuu . It might help us out if you could please send along your logs using these steps?
https://support.postman.com/hc/en-us/articles/360025298633-How-to-share-logs-with-Postman-for-debugging-issue

I hope you're not completely blocked, and I'm wondering if using Postman for Web is an option as a workaround? You could also try the route of clearing your local data; I realize that's a bit of a pain to clear settings and other data at the same time. Think you're familiar with that process from earlier, but posting the instructions should anyone else encounter this and are looking for ways to try to unblock themselves in the removing local data section:
https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error

**Comment by renjithrnair** [comment]
I'm also facing one issue related to environment details : https://github.com/postmanlabs/postman-app-support/issues/9960
Wonder if anyone else is facing a similar issue!!

**Comment by timbochamp** [comment]
We did encounter a scenario where the environment quick look won't open due to the window size in both the app and on Postman for Web:
https://www.loom.com/share/dcf77e8ff2fe402baedf7a6a7930b61b

I'm not sure if this resizing issue applies to everyone here at the same time where the initial comments seem to be due to performance problems. @renjithrnair , is your issue related to the resizing one shown in the above Loom recording?

**Comment by renjithrnair** [comment]
@timbochamp , Checked the loom recording you have provided. My issue is occurring irrespective of the screen size.

**Comment by Wotuu** [comment]
@timbochamp Where do you want me to send the logs to? Since they contain private information (such as the full environment) I don't want to post them here.

Meanwhile I'm going to clear my local data. It's been getting quite annoying since the workspace is completely unusable :). Click on requests doesn't open them as they should, keybinds don't seem to work (such as ctrl + s), the Tests tab has all kinds of strange issues where I can't remove lines or use backspace/del keys etc.

**Comment by timbochamp** [comment]
@Wotuu , please send them to help@postman.com as per https://support.postman.com/hc/en-us/articles/360025298633-How-to-share-logs-with-Postman-for-debugging-issue

Feel free to strip out any sensitive information as you see fit. Apologies again for the continued hassle here

**Comment by renjithrnair** [comment]
> @timbochamp , Checked the loom recording you have provided. My issue is occurring irrespective of the screen size.

https://github.com/postmanlabs/postman-app-support/issues/9960 This issue got fixed in v.8.6.0 update .

**Comment by dsims-Incomm** [comment]
This issue is happening to me on version 8.8.0

**Comment by ghost** [comment]
I have the same issue on version 8.10.0.
requests not opening unless I "Open in tab" and no way to edit my environment variable.

In the console trying to open/edit the requests/an environment variable gives me this warning: "Could not find on editorStore. Missing or invalid parameter."

**Comment by ndelrueFFT** [comment]
I have the same issue with 8.11.1

here is a capture
![image](https://user-images.githubusercontent.com/53269322/131013196-0a27f6c3-3020-469e-8e06-eb009df78d69.png)


Solved by desinstalling and delete files in AppData\Roaming

**Comment by ignasi1993** [comment]
> Hi @timbochamp , I just updated to 8.1 and I still had the issue. Wanted to post here to say it wasn't fixed yet - then saw your message. Upgraded to 8.2.1 and it seems to be working again. Maybe it had something to do with the setting `Always open requests in new tab` which I had enabled before, but I just had to re-enable. I don't know when it got turned off, but either way re-enabling it may have contributed.
> 
> Opening an environment and collection summaries now seem to work as well. Thanks for the help!

Hi! I had same issue, and this solved it, thanks!

**Comment by shawner18** [comment]
I also had the same issue after an upgrade. Enabling the "Always open in new tab" and then  off, solved my issue too

**Comment by timbochamp** [comment]
Talking with our Product team, with some performance initiatives that were included in versions 9.19.x, we shouldn’t be seeing these classes of issues. Please feel free to reopen this ticket should you encounter problems with opening tabs after updating to the latest version at the same time!
