### ISSUE TITLE
Postman Interceptor fails to capture request body for PATCH requests

### ISSUE THREAD

**Issue by mattneub** [a85/POSTMan-Chrome-Extension#9752]
**Describe the Issue**

Postman Interceptor captures JSON request body for some types of request, but not for all. In particular it does not capture the JSON request body for a PATCH request. This makes Postman Interceptor essentially useless for me (I am currently working around the problem by using Proxyman instead).

**Steps to Reproduce**

Configure a web page that makes a PATCH request with a JSON request body. In Google Chrome with Interceptor turned on and Postman connected to it, trigger the request.

The PATCH request is captured in Postman's history (or wherever you routed it to), but the request body is completely missing.

**Screenshots or Videos**

The intercepted PATCH request is shown with an empty body. Trust me, the actual request did have a body!

<img width="806" alt="Screen Shot 2021-03-19 at 1 48 41 PM" src="https://user-images.githubusercontent.com/838939/111716009-ff63f400-88b9-11eb-8e79-43517a557039.png">

**Environment Information**

 - Platform Type: Mac OS
 - Postman Version: 8.0.7
 - Operating System: Mac OS 11.2.3

**Additional Context**

Google Chrome 89.0.4389.90

Interceptor 1.1.2

**Comment by shashankawasthi88** [comment]
Hi, @mattneub thanks for pointing this out. We are able to reproduce the issue at our end. We will investigate this further and keep you in the loop of any updates.

**Comment by Raj-postman** [comment]
@mattneub Looks like we do not have this supported as of now. Our team is actively working on getting this feature onto Interceptor - would request you to _Subscribe_ to this thread in order to receive notification once it's released.

**Comment by antoniovivalda** [comment]
Ok thanks, look forward to have news about it

**Comment by akshaydeo** [comment]
It's available in v3.0.2

**Comment by deezeddd** [comment]
I can see this issue resurfacing. Can you kindly check this again? I've downloaded the Chrome extension, but it doesn't handle the PATCH body
