### ISSUE TITLE
 YAML file (CTRL+SPACE) not working as expected

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#9753]
On behalf of the user:

**Describe the Issue**
Syntax auto-complete functionality while defining a YAML file (CTRL+SPACE) is not working correctly.Instead of returning only the list of properties that apply under the current node, it returns a list of all strings included in the document which is unnecessary.

**Steps to Reproduce**
 (CTRL+SPACE)  should list only the properties within that schema. Example below:
![image](https://user-images.githubusercontent.com/41741228/111762139-a9497d80-88c6-11eb-8253-b1858062f018.png)

**Comment by DannyDainton** [comment]
Closing this as I'm unable to recreate this in the latest version of the platform. If this is not the case and you're still facing this issue we can look at reopening this again.
