### ISSUE TITLE
Text Data File Values Corrupted if Numeric longer than 16

### ISSUE THREAD

**Issue by davidMavs** [a85/POSTMan-Chrome-Extension#9755]
When using a text/csv data file for Runner.  If the field is numeric and the field is longer than 16 characters the field gets corrupted.  This can be seen in the Preview window for the data file, or when the test is run.

Sample file:
lengthsPast_16_valuesModified
12345678901
123456789012
1234567890123
12345678901234
123456789012345
1234567890123456
12345678901234567
123456789012345678
1234567890123456789
12345678901234567890

What is shown in the Preview window:
Iteration
lengthsPast_16_valuesModified
1
12345678901
2
123456789012
3
1234567890123
4
12345678901234
5
123456789012345
6
1234567890123456
7
12345678901234568
8
123456789012345680
9
1234567890123456800
10
12345678901234567000

**Comment by postman-staff** [comment]
Hi @davidMars,

Thanks for reaching out.

We've had a similar issue reported here ->https://github.com/postmanlabs/postman-app-support/issues/6798#issuecomment-506642247
This behavior can usually be overcome this by wrapping the number in quotes to be parsed as a String.

Please let us know if you have any other questions.

via @nrmartell | Postman Support

**Comment by chrisdeso** [comment]
@davidMavs Closing this thread out for now. If you're still facing issues, let us know by reopening the thread or by filing a [support ticket](support.postman.com).

Thanks!
