### ISSUE TITLE
Follow updates when running tests

### ISSUE THREAD

**Issue by HenrikHolmIT** [a85/POSTMan-Chrome-Extension#9758]
When running a test it would be awesome if the view would either pop the latest request that has run at the top of the list or have the scroll follow when the next request is run.

Right now it just shows a static list and I have to scroll down to follow the requests as they run. There are over 100 requests in our collections.

**Comment by malvikach** [comment]
@HenrikHolmIT The vertical scroll currently moves automatically to show the run execution progress as shown below. Please let me know if this helps. Please feel free to reopen the ticket if you would like to suggest any other improvements on this. 


https://user-images.githubusercontent.com/89449769/168083551-5b6822c2-9528-401d-a6a8-1a1e0c5db8d9.mov

**Comment by HenrikHolmIT** [comment]
The first PostMan 8 did not 'follow' when it first came out. There were other new 'features' that I didn't like on 8 that have also been fixed in the meantime. So on version 9.18.2 now. All good. It is alright to close this.

**Comment by malvikach** [comment]
@HenrikHolmIT thanks for your response. Glad that you checked this out on the new version. 

Appreciate your feedback. Feel free to let us know if you have any other suggestions or if you face some other problems while running tests.
