### ISSUE TITLE
Mock Server Call Log Request Body Problem with Twilio Webhook

### ISSUE THREAD

**Issue by DanDepot** [a85/POSTMan-Chrome-Extension#9762]
**Describe the Issue**

The mock server log request body does not show data when the request content-type header is application/x-www-form-urlencoded; charset=utf-8. The problem appears to be charset=utf-8 being included in the content-type. When removed the request body appears.  This presents a problem seeing postman mock server log request body data for incoming Twilio Webhook requests.

**Steps to Reproduce**

Using the Twilio API I sent an SMS message with a statusCallback url to my mock server endpoint.  The Twilio request content-type header is application/x-www-form-urlencoded; charset=utf-8.  When I view the mock server log for this request from Twilio the Request Body section says "This request does not have a body." .  I then simulated this webhook request in Postman on my own and removed the charset=utf-8.  The mock log Request Body section for this request shows the body data.  This demonstrated how the mock server log request body appears differently when charset=utf8 is included or excluded with application/x-www-form-urlencoded in the content-type request header.  I have made certain my mock server example POST request content-type header is set to application/x-www-form-urlencoded; charset=utf-8.  Other mock servers I tested like requestbin and hookbin show the request body coming from Twilio webhooks, so I verified that Twilio is sending it.

**Screenshots or Videos**

**Environment Information**

 - Platform Type: x64-based PC
 - Postman Version: 8.09
 - Operating System: Windows 10 Pro - Version 10.0.19041 Build 19041

**Additional Context**

Since the Twilio API Webhooks always send a content-type of "application/x-www-form-urlencoded; charset=utf-8", I have no control over changing it.  I need to be able to see the request body coming from my Twilio webhooks in the Postman mock server log, but because of this bug I am unable to see it.  Reference - https://www.twilio.com/docs/usage/webhooks/sms-webhooks#type-2-status-callbacks

**Comment by DanDepot** [comment]
To test this simply send a POST to your mock server with a content-type header value = application/x-www-form-urlencoded; charset=utf-8.  Include a request body with form delimited data(value1=123&value2=abc) and send it.  The mock server log will not show the request body, it shows instead "This request does not have a body.".

**Comment by vvs11** [comment]
@DanDepot We are working on this issue. will give you an update soon on the release once we test it internally

**Comment by akshaydeo** [comment]
@DanDepot I know it's almost a year since you raised this issue 🙁 . 
We have fixed this issue from our end; could you test and confirm 🙇. 

Closing this issue for now, but feel free to re-open if things are still not working for you 🙂
