### ISSUE TITLE
Inherit from parent auth not working after 8.x upgrade. 

### ISSUE THREAD

**Issue by Sadagopan88** [a85/POSTMan-Chrome-Extension#9763]
**Describe the Issue**
After upgrading to Postman 8.x when using inherit from a parent is not getting the latest token from the parent. there is a sync issue

**Steps to Reproduce**
Create a collection with OAuth 2.0 authorization. Get the new token by passing the client id /secret at the parent level. Check the collection header the new oauth 2.0 token is not synced 

**Screenshots or Videos**

Got new token 
![image](https://user-images.githubusercontent.com/3282404/112548871-87e30880-8d82-11eb-8b28-06b3770a4c60.png)
Header is still reflecting old tokem
![image](https://user-images.githubusercontent.com/3282404/112548916-992c1500-8d82-11eb-99de-4481680501c2.png)
Using inherit from parent
![image](https://user-images.githubusercontent.com/3282404/112548932-9d583280-8d82-11eb-99a1-f04ad727345a.png)

**Comment by hpinsley** [comment]
I just upgraded to v8.0.9 and am having the exact same problem.  At first I thought maybe I was missing some nuance of the changed interface.  I'm glad someone reported this.

**Comment by vvs11** [comment]
@hpinsley @Sadagopan88 Could you please share the video of this not working? 
I am assuming you are defining collection level auth and using it in the requests. Could you check if the Save button is active in the collection tab? If it is, could you try saving and then checking if it works?

**Comment by hpinsley** [comment]
@vvs11 I think that was the issue.  If you change the token for the collection -- either by choosing an existing token and clicking "Use Token" or by getting a new one, I think you have to click the Save button before it will be used.  I wasn't doing that (and don't recall having to do so in previous versions)?

**Comment by jthake** [comment]
Here is what I discovered same as @hpinsley . You have to click *Save* after click *Get New Token* and *Use Token*. You did not need to do this before the latest update.

Can we please revert back. Our user based of our collection is flooding my inbox with this frustration. We tried to simplify our auth process by using inheritance and this UX is still very clunky.

I would love to see prompts that if there is no token when you hit the *request* button. that it prompts you to *Get New Token* and does it all in the background, without having to navigate to the Authorization tab to do it for instance.

**Comment by giridharvc7** [comment]
Thanks for reporting this. We are taking this up and we'll be fixing it soon.
Till then, please save the collection after generating a new token.

**Comment by dan-lind** [comment]
I believe this issue is closely related to https://github.com/postmanlabs/postman-app-support/issues/9470

**Comment by giridharvc7** [comment]
This is now fixed in app version 8.3.0 and on the web. Please give it a try and let us know! @Sadagopan88 @jthake-msft @hpinsley

**Comment by jthake** [comment]
Its odd.  If I fork the Microsoft Graph collection. then If i go to my collection with no tabs open in Postman. And click on the "Delegated" folder which is where the authorization is setup and when its open a colored dot shows up next to it which would typically indicate something has changed. If i close that tab, it doesn't prompt me to save.

![image](https://user-images.githubusercontent.com/6786616/116282267-67222000-a73f-11eb-8f6b-885e6a8e5b4c.png)

But if i click on the Get New Access Token and click on Use token.

If i click on Users | Get My Profile it actually closes that open tab for "Delegated" which I don't think it did before and shows just the "Get My profile" tab. The good news is that it does just work now.  I no longer have to click save after clicking Use Token.

![image](https://user-images.githubusercontent.com/6786616/116282547-c2eca900-a73f-11eb-8350-3680772fbc6a.png)

**Comment by timbochamp** [comment]
@jthake-msft for your point about the coloured dot, the Green dot next to Authorization indicates you have authorization set to something other than No Auth. I can definitely relate to the usual UX of the dot next to a tab or field would indicate a change where we denote that with an orange dot in our tabs. In this case to show changes in authorization settings, the Save icon in the upper right would be enabled instead of being greyed out. I can relay along to our UX team if this is something we'll address - thanks for pointing this out!

The second point with the folder tab being replaced by the request tab, I want to say relates to the setting Always Open Requests in New Tab being off if I were to guess!
