### ISSUE TITLE
Pasting a cURL command in URL bar should create an appropriate request 

### ISSUE THREAD

**Issue by giridharvc7** [a85/POSTMan-Chrome-Extension#9768]
**Problem and possible solution**
I often have to deal with cURL commands, it'll be great if i can paste the cURL commands on the URL tab and postman would automatically parse it to create an appropriate postman request. It'd save me so much time. 

**Describe alternatives you've considered**
Right now, i'm doing this using the import flow in postman. This adds 3 clicks to my flow, would be great if it was simpler.

**Comment by Abhijeet104** [comment]
yes, I really need this.
Earlier I was using Insomnia rest client it has that.

**Comment by dhwaneetbhatt** [comment]
We released this feature in v10.12 of Postman in March. Please try it out and feel free to provide feedback.
