### ISSUE TITLE
Export on Mac does not work

### ISSUE THREAD

**Issue by MuffinSpawn** [a85/POSTMan-Chrome-Extension#9769]
The copy of Postman I have on my MacBook does not work. The export button on EXPORT COLLECTION pop-up used to do absolutely nothing. Now, after the latest update, it at least closes the pop-up window; but it still does not generate an export file. No file selection dialog appears. The copy on my Windows machine works fine.

**Comment by numaanashraf** [comment]
@MuffinSpawn Could you verify whether the file selection dialog is opening in the background? This issue sounds similar to https://github.com/postmanlabs/postman-app-support/issues/8726#issuecomment-651872174

**Comment by pm-komal-jain** [comment]
Is there any progress on this issue ?  Recently I have updated my postman app to Version 8.1.0. And my mac OS version is 10.15.7 . On exporting collections (tried both v2.1 and v2 collection version)  absolutely nothing happens. There no collection json file generated. This is a major blocker for us as we cant run newman now.

**Comment by numaanashraf** [comment]
@pm-komal-jain Could you verify whether the file selection dialog is opening in the background? This issue sounds similar to https://github.com/postmanlabs/postman-app-support/issues/8726#issuecomment-651872174

**Comment by seancarroll** [comment]
I hit this issue today on 8.2.2. I tried verifying file selection was in the background but no other windows/dialogs appear.

**Comment by DannyDainton** [comment]
Hey Folks,

Are you still seeing this issue in the latest version of the app? If not, we can look to close this one out.

**Comment by pm-komal-jain** [comment]
@DannyDainton  -  its working for me now. Thanks.

**Comment by bmckinle** [comment]
Export collection appears broken in 9.1.3.  This is not fixed, apparently.  Collection ... -> Export gives choice of export v2 or v2.1 (recommended).  Selecting 2.1, as I've always done for over a year now, no longer results in a pop-up to select an output file name.  Nothing happens, which means I cannot update my newman json test scripts.  Is this fixed yet or how can I work around it?

**Comment by DannyDainton** [comment]
Hey @bmckinle

Does this still happen after closing and reopening the app?

On occasions the file explorer has opened behind the app, could you do a quick check to see if that's happening.

As for Newman, using the Postman API to get the most up to date Collection is a more efficient way of doing this, than exporting each time. 

The Postman API URL to the collection can be used in the Newman command.

**Comment by bmckinle** [comment]
Checked for hidden windows but found none.  After reboot, the problem
resolved.
