### ISSUE TITLE
Remove leading and trailing spaces in URLs

### ISSUE THREAD

**Issue by Ghenty** [a85/POSTMan-Chrome-Extension#9772]
Hi support,
 
I just had a very long support session with a customer of us regarding the authorization problem.
Root cause was a trailing space in the “OAuth2.0 Authorization Code” Auth Url.
 
I think it would be extremely helpful feature to remove automatically all leading and trailing spaces (“ “) in all URLs or at least in the Autorization Urls.
 
Best regards,
Ghenty

**Comment by DannyDainton** [comment]
This is a similar request to one that was recently answered by @vvs11 

https://github.com/postmanlabs/postman-app-support/issues/9707
