### ISSUE TITLE
could not login

### ISSUE THREAD

**Issue by luwol03** [a85/POSTMan-Chrome-Extension#9773]
**Describe the Issue**

Today I created an account on the postman website. Then I tried to login to the postman cannary app.  First it worked pretty well. Then I decided to relogin for a quick test. But now the window is loading but if the first screen is loaded, it get white and reloaded in a loop. Then I opend the development tools for the main process and see some issues with sentry.
![image](https://user-images.githubusercontent.com/60048565/112801456-35029d00-9071-11eb-88d0-548be1aa9f2a.png)

**Steps to Reproduce**

dont know if you can reproduce it.

- create a account
- login to postman canary
- logout
- relogin
- and then the window keeps loading in a loop
- after a few minutes, the window loades with errors in the console
![image](https://user-images.githubusercontent.com/60048565/112802015-e99cbe80-9071-11eb-97d8-381604d1c073.png)
![image](https://user-images.githubusercontent.com/60048565/112802043-f28d9000-9071-11eb-9f73-875f0cbe3648.png)
![image](https://user-images.githubusercontent.com/60048565/112802053-f8837100-9071-11eb-97d3-dd901b74dcf9.png)
and a `Couldn't load this page Refresh the page or check back later` error. Then I click reload, but same error appears. And if I try to relogin or restart my system same thing.
![image](https://user-images.githubusercontent.com/60048565/112802360-6039bc00-9072-11eb-93bd-21279f638cb6.png)

**Screenshots or Videos**

**Environment Information**

 - Platform Type: Canary
 - Postman Version: Version 8.0.8-canary01
 - Operating System: Windows

**Additional Context**

**Comment by postman-staff** [comment]
Hello @luwol03,
Thank you for all the provided details.

We have received similar reports from other users as well, and our engineers are actively looking into the the issue.

Meanwhile as a workaround could you please try using Postman's v8.07 ( https://www.postman.com/downloads/ )
Alternatively you can also try using our Web Application - http://go.postman.co/

If the issue persists even using Postman v.8.0.7 please provide us with the logs for your application on our email help@postman.com
We'll keep you posted on any updates - sorry for the inconvenience.

via @nasco-a | Postman Support

**Comment by luwol03** [comment]
Thanks for the great qick support. With the normal postman version all works fine except the 429 sentry error in the console. But postman is working fine. 
![image](https://user-images.githubusercontent.com/60048565/112808282-1d2f1700-9079-11eb-8ebc-1a3078fd0ecd.png)

**Comment by postman-staff** [comment]
Hello @luwol03
Many thanks for letting me know that you were able to resume your work in Postman.

On a side note - our engineers were able to identify the issue and have released a fix for it in the latest version of Postman Canary(**v8.0.10**)

It is already available for download on our website https://www.postman.com/downloads/canary/

Thanks!
via @nasco-a | Postman Support

**Comment by luwol03** [comment]
I updated with the auto updater from the electron app. Now I can login and relogin without errors. But the could not load error is still there. And also the sentry errors.
![image](https://user-images.githubusercontent.com/60048565/112813722-d3492f80-907e-11eb-9ac4-026dbc205b9e.png)

EDIT:
I reloaded and now all works fine. So I close this issue for now. Thanks for the great support.
