### ISSUE TITLE
Send button is out of the edge of the screen

### ISSUE THREAD

**Issue by chernyy-svyat** [a85/POSTMan-Chrome-Extension#9774]
Hello!
I'm facing a bug when the **Send** button moves out of the edge of the screen if I use long length parameter value in query string in GET request

<img width="1156" alt="Снимок экрана 2021-03-29 в 18 46 51" src="https://user-images.githubusercontent.com/46106197/112865255-44113b80-90c1-11eb-8f61-8920f3a45e18.png">

<img width="1157" alt="Снимок экрана 2021-03-29 в 18 47 14" src="https://user-images.githubusercontent.com/46106197/112865385-64d99100-90c1-11eb-9c58-3a3df4bba235.png">

Postman for Web
Version 8.0.9-210325-1217
Safari 13 / Mac OS 10.15.5

**Comment by numaanashraf** [comment]
This issue has been addressed! Thanks for reporting @chernyy-svyat!
