### ISSUE TITLE
Mark URLs in emails as intentionally obstrucated and link to a "why" page 

### ISSUE THREAD

**Issue by bean5** [a85/POSTMan-Chrome-Extension#9778]
When I first noticed that URLs were obstrucated, I copy + pasted it into my omnibar. But then it did a google search. Google turns it back into a URL which I then click.

To users who do not understand that you are protecting them, you are just confusing them and making them expose a portion of their URI to google search.

To users who would understand but think their email app failed to convert to clickable, they copy + paste.

To users who would understand and already know you do this, they are fine.

As a power user of postman, I'm okay. But I forward these emails and have some monitors sending to non-engineers in my organization. They are confused by the non-link URLs.

In my opinion:
* obstrucated URLs in emails should be marked as such with a link to a "why" page
* I should be able to set whether URLs are even visible in URLs. For non-engineers, they are more interested in the impacted user story than the how. Test case titles display stories. So to these users, the URL is just bulking up the email.

**Comment by DannyDainton** [comment]
Hey @bean5 

Would you be able to provide some visual examples of where you're seeing this, please?

Just want to get a better understanding of the problem.

**Comment by mccannt** [comment]
@bean5 Any updates here as per @DannyDainton's ask?

**Comment by DannyDainton** [comment]
Hey @bean5  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
