### ISSUE TITLE
it broken

### ISSUE THREAD

**Issue by tomkluas** [a85/POSTMan-Chrome-Extension#978]
when i visit www.taobao.com, it just broken, and remind me to restart,has the same question

**Comment by abhijitkane** [comment]
@tomkluas Is this related to Postman?

**Comment by cameron-fgx** [comment]
I stumbled across this issue, the good news is that I just visited www.taobao.com in my browser, and seems like the website is working fine to me.
@abhijitkane good job on fixing that problem.
