### ISSUE TITLE
New Integration Request - Postman integration with Bitbucket private server

### ISSUE THREAD

**Issue by LeonWenbu** [a85/POSTMan-Chrome-Extension#9784]
**Describe your current workflow**
I'm a FTE of SS&C Advent. Looking for a method to integrate postman with bitbucket private server.

**Describe your ideal workflow**
Should be same as the integration with bitbucket public server.

**Comment by shashankawasthi88** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/8769
