### ISSUE TITLE
New Integration Request - <Postman API>

### ISSUE THREAD

**Issue by Mohammad-islam** [a85/POSTMan-Chrome-Extension#9789]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
@Mohammad-islam can you please elaborate on the different sections of the Integration request template. This would help us plan the Integration better.

**Comment by shashankawasthi88** [comment]
Closing this for now. Feel free to reopen by adding more details to the ticket.
