### ISSUE TITLE
Allow for 'dot masking' of sensitive data stored in variables, adding to protections provided by Sessions/Private Workspaces

### ISSUE THREAD

**Issue by COB-SM** [a85/POSTMan-Chrome-Extension#9792]
This shares some scope with closed request #7108 but introduces additional use cases.

An added layer of security could be provided by allowing for 'dot masking' of variable fields in web/local clients. This would protect against 'screen scraping' of credentials in a limited local compromise scenario (e.g. an attacker can view a user's screen via a compromised remote viewing session or simple 'shoulder surfing' in a co-working or café context). Dot masking could also guard against inadvertent exposure of sensitive variable data when collaborating in real-time with others (e.g. local or remote pair programming or technical support contexts).

**Comment by giridharvc7** [comment]
Closing this to track in #8388
