### ISSUE TITLE
New Integration Request - jenkins

### ISSUE THREAD

**Issue by srishtiagg** [a85/POSTMan-Chrome-Extension#9795]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijitkane** [comment]
@srishtiagg Thanks - can you elaborate on the use-cases you'd like the proposed Jenkins integration to solve?
