### ISSUE TITLE
[mac] Flickering and jumping in the table of Params and Headers when hovering with cursor

### ISSUE THREAD

**Issue by gianpaj** [a85/POSTMan-Chrome-Extension#9801]
**Describe the Issue**
Various tables flicker when the text goes over multiple lines.

It might be related to the scroll bars. This happens with any "Show scroll bars" setting:

<img width="640" src="https://user-images.githubusercontent.com/899175/113694251-6ad60000-96c7-11eb-9d33-e5860cd3ffb0.png" />

**Steps to Reproduce**
1. Go to Params tab
2. Enter a param VALUE so it's larger than the length of the screen and goes over at least 2 lines
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur cursus risus eu odio suscipit, condimentum ullamcorper urna eleifend. Maecenas volutpat mauris ac sapien malesuada fringilla. 
```
3. Make the KEY column shorter so the scroll bars appear
4. Move the cursor to the row that has the long header

<img width="640" src="https://media.giphy.com/media/bcABHTkbfWSoim05M8/giphy.gif" />

Full video: https://imgur.com/a/AMUBC0e

**Environment Information**

 - Platform Type: Native App
 - Postman Version: 8.1.0
 - Operating System: macOS Catalina 10.15.7

**Comment by vvs11** [comment]
@gianpaj Thanks for reporting this. I am able to reproduce this. Will get it fixed soon

**Comment by timbochamp** [comment]
Our Product team tested this, and it should now be resolved in the latest app. Please feel free to reach out if it's still an issue!
