### ISSUE TITLE
Not able to open single request in test window by clicking on it

### ISSUE THREAD

**Issue by sumit1720** [a85/POSTMan-Chrome-Extension#9804]
**Describe the Issue**

Basically just not able to open & run single requests, always need to right click on required request & select 'Open in New tab'.
It was able to before but from last couple of days facing this issue.
**Steps to Reproduce**

Open collection 
Click on any single request to run
Will get issue 
**Screenshots or Videos**

**Environment Information**

 - Platform Type: 
 - Postman Version: 8.1.0
 - Operating System: Windows 10

**Additional Context**

**Comment by postman-staff** [comment]
Hi @sumit1720 👋​

Could you try enabling the option "_Always open requests in new tab_" from the **Settings > General** and see if that helps? This helps to open multiple requests in different tabs.

 ![](https://postman.zendesk.com/attachments/token/Oiq4NhVsySl7Li1vdQpYcbtXw/?name=inline-623835874.png)

via @Raj-postman | Postman Support

**Comment by sumit1720** [comment]
Yes, Perfect !! thank you so much for quick help

**Comment by postman-staff** [comment]
Thank you! :)

Have a nice day.

via @Raj-postman | Postman Support
