### ISSUE TITLE
Downgrade from team to personal workspace

### ISSUE THREAD

**Issue by kedigby** [a85/POSTMan-Chrome-Extension#9806]
**Incorrectly upgraded to team workspace.**
I upgraded to a team workspace to share some requests with a work colleague, however when i noticed the request limits on the "free" team I new it wasn't for me. I removed my colleage from the team and assumed that the team would revert to a personal one.

**Archived Collections**
After ignoring warning about request limits for a while postman archived all of my collections, this was extremely frustrating as I was on a video conference at the time debugging an issue.

**Can't downgrade from a Team to a Personal workspace**
Once i realised I couldn't downgrade, I exported the collections via the postman web portal and deleted the team workspace. I then created a new personal workspace and imported the collections. I have unfortunately lost all of my environment settings for the workspace.

**New Feature**
Please make it possible to revert a single member team to a personal workspace.

**Comment by jasonycw** [comment]
Same thing happening, cannot revert the default "My Workspace" back to personal one
![image](https://user-images.githubusercontent.com/4518597/139372115-897e6da9-f2ce-463e-bd90-0a189dc8467e.png)

I am the only one in the team and only member in that workspace, why can't it convert back to `Personal`

**Comment by akshay-kulkarni-03** [comment]
@kedigby the request limits as a feature is removed now. On a side note, we will think about this feature request and see if we can have the downgrade functionality in the future.

**Comment by lordrhodos** [comment]
I accidentally turned a personal workspace into a team workspace and can not undo the action. Very disappointing to see that Postman does not support converting the workspace or even moving a collection from e team workspace to a personal workspace.

Ist this feature request is > 2 years old. Any updates if this will be implemented? Otherwise maybe be better to close the issue if this is tracked anymore.

**Comment by analytiks-team-squlpt** [comment]
This feature is needed! I can't downgrade to a personal workspace... and since there's a price increase coming in August seems to be on purpose. Great job, Postman!

@lordrhodos is correct...this request is over 2 years old. Please close it if it's not being tracked.

**Comment by akshay-kulkarni-03** [comment]
Hi All, we now allow converting team workspace to personal workspace as well. Ensure you're on the latest version of Postman app. Let us know if you face any issue.

**Comment by PostmanJallad** [comment]
Postman

**Comment by TheArKaID** [comment]
> Hi All, we now allow converting team workspace to personal workspace as well. Ensure you're on the latest version of Postman app. Let us know if you face any issue.

Where's actually this feature implemented? I cannot find it
