### ISSUE TITLE
Is it possible to know the IP address of monitors in Postman?

### ISSUE THREAD

**Issue by ShahAnuj2610** [a85/POSTMan-Chrome-Extension#9807]

**Comment by postman-staff** [comment]
Hi @ShahAnuj2610,

Static IP address monitoring is available on Postman Business and Enterprise plans for the moment.

You may refer to this resource document to learn more about the same. Hope that helps!

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
Sorry looks like the link didn't come through, reattaching this here: https://learning.postman.com/docs/designing-and-developing-your-api/monitoring-your-api/using-static-IPs-to-monitor/#whitelisting-static-ip-addresses

via @Raj-postman | Postman Support

**Comment by ShahAnuj2610** [comment]
That is fine. I want to know the IP address of monitors which does not have static IP.

**Comment by postman-staff** [comment]
Unfortunately, we don't yet have IP addresses for you to whitelist. Postman Monitors currently runs on Amazon's AWS infrastructure. Therefore the monitoring regions use the same regions as AWS.

A potential solution would be to whitelist the IP ranges provided by AWS here: https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html. However, the IP ranges may change without notice so you will have to factor that into your solution.

Best,
Cyrielle

Postman | Product Support | Europe

Status Page | Learning Center | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by postman-staff** [comment]
Hi @ShahAnuj2610,

I'll be closing this on our end as we haven't heard back. Hopefully, the information shared was helpful. If you still require assistance, please reach out to us by submitting a ticket here: https://www.postman.com/support

Have a great day!

via @Raj-postman | Postman Support
