### ISSUE TITLE
Path Variables are not rendered in Documentation

### ISSUE THREAD

**Issue by ckang777** [a85/POSTMan-Chrome-Extension#9808]
**Describe the Issue**
After saving a request with a path variable, documentation section does not render the path variables

**Steps to Reproduce**
1. Create a request
2. Add a path variable
3. Save request
4. Notice that in the documentation section does not have Path Variable listed.

**Screenshots or Videos**
![Screen Shot 2021-04-07 at 8 18 11 AM](https://user-images.githubusercontent.com/7827831/113892209-a54ca500-977a-11eb-8cf7-bf9d6a53f355.png)

**Environment Information**

 - Platform Type: Postman App
 - Postman Version: 8.1.0
 - Operating System: macOS 11.2.3

**Additional Context**
Path variables, however, do appear in the published document at documenter.getpostman.com.

**Comment by Raja-Simha** [comment]
@ckang777 This issue has been fixed in the latest version of the App and on the web.

**Comment by ckang777** [comment]
@Raja-Simha It's working now. Thank you!
