### ISSUE TITLE
Request example not displayed in Documentation

### ISSUE THREAD

**Issue by ckang777** [a85/POSTMan-Chrome-Extension#9809]
**Describe the Issue**
Request example is not displayed in Documentation in the Postman for Web.

**Steps to Reproduce**
1. Add an example to a request.
2. Add response body.
3. Save the example.
4. View complete collection documentation.
5. Notice the empty body in example section of the document.

**Screenshots or Videos**
![Screen Shot 2021-04-07 at 9 28 42 AM](https://user-images.githubusercontent.com/7827831/113901749-03ca5100-9784-11eb-9d0a-827f98271748.png)
![Screen Shot 2021-04-07 at 9 28 21 AM](https://user-images.githubusercontent.com/7827831/113901755-05941480-9784-11eb-858d-0c34c1665717.png)

**Environment Information**

 - Platform Type: Postman for Web
 - Postman Version: 8.1.0-210401-0400
 - Browser Version: Chrome 89.0.4389.114
 - Operating System: macOS 11.2.3

**Additional Context**
It works fine in the standalone app.

**Comment by DannyDainton** [comment]
Hey @ckang777 

A fix for this issue was pushed to the latest version - Are you able to check this has fixed the problem for you?

**Comment by ckang777** [comment]
@DannyDainton Yes, it is fixed now. Thank you!

**Comment by DannyDainton** [comment]
Awesome, great to hear!

Going to close this issue out now. 🏆
