### ISSUE TITLE
Merge greyed out for forked collection - "Share the source collection to merge changes"

### ISSUE THREAD

**Issue by chrisdbutler** [a85/POSTMan-Chrome-Extension#9810]
As of Version 8.1.0 the merge button is now greyed out for forked collections with the error "Share the source collection to merge changes".
I had a colleague who was still on 8.0.9 try and they were able to merge in, and I was able to then pull these changes.
The "parent" collection is on a team workspace and is forked into local workspaces.

We've checked out the "Using source control" documentation and as far as we can tell, this is the process we have been (and are trying to) follow.

![image](https://user-images.githubusercontent.com/20384965/113907069-da81e300-97cc-11eb-9935-8ea6db7235cd.png)

**Comment by chrisdbutler** [comment]
Ok, I'm not sure if I got my version numbers mixed up or what, but having found an installer for 8.0.7 and reverting to that yesterday, 8.2.1 has installed overnight and the issue does not exist there, so closing this.

**Comment by Surt** [comment]
Version 8.2.2 paid suscription for 4 users.

We can't merge forked collections on the source collection. We did on previous versions but now nobody can merge or pull request.  We already check all permissions etc.
