### ISSUE TITLE
Auto sort environment variables

### ISSUE THREAD

**Issue by neowulf** [a85/POSTMan-Chrome-Extension#982]
It'd be nice to allow for auto sorting the list of environment variables when the plugin restarts.

**Comment by a85** [comment]
@neowulf33 What do you exactly mean by auto sorting?

**Comment by neowulf** [comment]
It'd be nice if the variables are auto sorted.

Usually, the variable is appended to the bottom of the list. But, when scanning to update the variable, it's easier to scan an alphabetically sorted list.

**Comment by raksahb** [comment]
As a postman user I would like the ability to filter and sort environment variables - both key and value, so I can easily find a key or value to edit or view its value
 
![postman](https://user-images.githubusercontent.com/2277664/43601706-b5df5c78-9642-11e8-80da-584e68f37c41.png)

**Comment by mennopot** [comment]
I really would like this feature as well.
I have a lot of variables already, and it's always a search for the correct one.
Could you please implement this?

**Comment by TMUNYU** [comment]
This would be an awesome feature. 
A quick search feature would be awesome as well.

**Comment by jessica-streem** [comment]
This would be extremely helpful for my company and I as well.

**Comment by andrewzuk** [comment]
Any updates on this?  I'm honestly shocked this wasn't a feature from the beginning.

**Comment by vvs11** [comment]
This is in our roadmap and we'll be working on it soon

**Comment by carboncope** [comment]
I also needed the ability to sort my environment variables. I ended up writing a Pre-request script that sorts the environment I have selected and uses the postman API to update the environment variables. Maybe it will help someone.

**Requirements:**

1. Set a environment variable e_pm_env_uid to the UID of your environment that you can get from your postman dashboard.
2. Set a global variable g_POSTMAN_APIKEY to your postman API key.

```// We need the json contents of the environment from the postman API
var pmRequest1 = {
    "url": `https://api.getpostman.com/environments/${pm.environment.get("e_pm_env_uid")}?apikey=${pm.globals.get("g_POSTMAN_APIKEY")}`,
    "method": "GET",
    "header": {
        "content-type": "text/plain",
        "accept": "text/plain"
    }
};

pm.sendRequest(pmRequest1, (error, response) => {
    if (error) throw new Error(error);
    var envJson = response.json();
    var sortedValues = envJson.environment.values;
    sortedValues.sort((a, b) => (a.key > b.key) - (a.key < b.key));
    envJson.environment.values = sortedValues;
    console.log(`Sending envJson ${pm.environment.get("e_pm_env_uid")}`, envJson);
    
    var pmRequest = {
        url: `https://api.getpostman.com/environments/${pm.environment.get("e_pm_env_uid")}?apikey=${pm.globals.get("g_POSTMAN_APIKEY")}`,
        method: 'PUT',
        header: {
            'Content-Type': 'application/json'
        },
        body: {
            mode: 'raw',
            raw: envJson
        }
    };

    pm.sendRequest(pmRequest, (error, response) => {
        if (error) throw new Error(error);
        const jsonResponse = response.json();
        console.log('Update response', jsonResponse);
        pm.expect([200]).to.include(response.code);
    });
});

**Comment by tmoney100** [comment]
Any progress on this? This would be super helpful for all my team!

**Comment by reishou** [comment]
Make 2 requests to re-order enviroment variable with simple url from postman

CLEAR_ENVIROMENT_VARIABLE

![image](https://user-images.githubusercontent.com/4869137/99562584-dfe7b800-29fa-11eb-9fdf-63565a8c7f9d.png)
Pre-request Script: 
```
var keys = []
var values = {}

for (const [key, obj] of Object.entries(pm.environment.values.members)) {
    keys.push(obj.key)
    values[obj.key] = obj.value
}

pm.environment.clear()

set_var("KEYS", JSON.stringify(keys.sort()))
set_var("VALUES", JSON.stringify(values))

function set_var(name, value) {
    pm.environment.set(name, value);
}
```


RE_ORDER_ENVIROMENT_VARIABLE

![image](https://user-images.githubusercontent.com/4869137/99562810-23422680-29fb-11eb-8f34-839a501fcb17.png)
Pre-request Script: 

```
var keys = JSON.parse(pm.environment.get("KEYS"))
var values = JSON.parse(pm.environment.get("VALUES"))

keys.forEach(function(key) {
    set_var(key, values[key])
})

pm.environment.unset("KEYS");
pm.environment.unset("VALUES")

function set_var(name, value) {
    pm.environment.set(name, value);
}
```

**Comment by cateyes99** [comment]
Keen to see this to be implemented.

**Comment by dmrickey** [comment]
> This is in our roadmap and we'll be working on it soon

Has soon happened yet?

**Comment by NikitaKharkov** [comment]
Guys, I understand that you are working on the big important features, which do something very important (no sarcasm). But it's the very simplest one. Moreover: it's a key feature, because, e.g., I about 60 variables, I need from time to time to have quick access to it. So need either sorting or filtering (better both). It's very useful, really.
It was open in 2015, guys. 2015!.. :(
We are waiting for this so much.

**Comment by andrewzuk** [comment]
> Guys, I understand that you are working on the big important features, which do something very important (no sarcasm). But it's the very simplest one. Moreover: it's a key feature, because, e.g., I about 60 variables, I need from time to time to have quick access to it. So need either sorting or filtering (better both). It's very useful, really.
> It was open in 2015, guys. 2015!.. :(
> We are waiting for this so much.

Or better, open-source your project and let one of us implement it for you.  Lol

**Comment by fingentzenvrm** [comment]
What's the deal with this? This is open since 2015 - seriously this is a major issue with anyone who has dozens of env variables - how is this still not solved?

**Comment by minionOfZuul** [comment]
It's a gigantic pain to still not have this feature. Give it to one of your junior devs. It has been years.

**Comment by giridharvc7** [comment]
Hello folks, we have released sorting & filtering on variables in our latest update to Postman (10.12) - the update is being rolled out, you will get it in the next couple of days if you haven't already.

You can read about the latest updates we have on variables and its management [here](https://blog.postman.com/faster-and-easier-variable-management-in-postman/). We hope you like these updates. Thank you for your patience and your feedback, we really appreciate it. 

![Sort](https://user-images.githubusercontent.com/1040583/225613544-6b3754c2-7550-41f5-b00e-57c287ded079.gif)
