### ISSUE TITLE
can not open postman

### ISSUE THREAD

**Issue by BalanceHan** [a85/POSTMan-Chrome-Extension#9825]
**Describe the Issue**

**Steps to Reproduce**

**Screenshots or Videos**

**Environment Information**

 - Platform Type: Window
 - Postman Version:8.2.1
 - Operating System:19042.867

**Additional Context**

![image](https://user-images.githubusercontent.com/20102785/114362440-e9d8a600-9ba9-11eb-9d42-8564ec5ac194.png)

**Comment by BalanceHan** [comment]
#9690

**Comment by postman-staff** [comment]
Hi Support,

Thanks for writing in. Sorry to hear you’re seeing issues with your Postman install - happy to help!

If possible, would you please share your app's logs to help us debug the issue? They can be found at this location on Windows - `%appdata%\Postman\logs`



_If you need additional help finding Postman's logs, please see this article._

**Then, renaming (or** _clearing_**) the local files for your Postman installation generally resolves this issue.** You can find full instructions for doing so in the below article.


- https://support.getpostman.com/hc/en-us/articles/360025359014

Hope this helps! Thanks for letting us know how this goes.


via @stcalica | Postman Support

**Comment by postman-staff** [comment]
Hi Support,

I hope all is well! I just wanted to follow up on my previous message - is there anything else I can do to help you?

I am closing this ticket now, simply reply to this thread to reopen the ticket.
Please let me know if you have any further questions - I'd be happy to address them!

via @stcalica | Postman Support

**Comment by BalanceHan** [comment]
[main.log](https://github.com/postmanlabs/postman-app-support/files/6362070/main.log)
this is my log,the error is recorded at the end

**Comment by BalanceHan** [comment]
delete AppData\Roaming\Postman,can solved this problem
