### ISSUE TITLE
Option to stop runner when an error appears

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#9826]
Sometimes it is comfortable to make exucution continue when error happens, but for some reason it would be useful to be able to stop runer just in time of error.

**Describe the solution you'd like**
An option in runner dialog to stop if error happens.

**Comment by JWATSU** [comment]
Is this being worked on? @giridharvc7

**Comment by malvikach** [comment]
Hi @m3dbedb , @JWATSU 

Glad to inform that this improvement has been released in the latest Postman release (version 10.13). You can now customize the Collection Runner to continue to run if an error occurs.
![ezgif com-video-to-gif (2) (1)](https://user-images.githubusercontent.com/89449769/232978898-56a2b198-59b8-4d77-9243-623d0dc69011.gif)

The setting will be checked by default i.e. by default Runner will stop the execution in case of an error. If you wish to continue runner to execute, you can uncheck this setting and Postman will remember it throughout your session for all subsequent runs unless you change it.

Hope this helps your workflows. Once again, thanks a lot for sharing your feedback on this.

Please note: The Postman version update is being rolled out, you will get it in the next 1-2 days if you haven't already.

Cheers,
Malvika
