### ISSUE TITLE
Error "Something Went Wrong" - When trying to switch to Scratch Pad

### ISSUE THREAD

**Issue by mantey-github** [a85/POSTMan-Chrome-Extension#9828]
**Describe the Issue**
While using postman and trying to switch to Scratch Pad, it seems that the error Something Went Wrong prevents me from using the **Scratch Pad** feature

**Steps to Reproduce**
1. Open postman desktop application (Version 8.2.1 (8.2.1))
2. Try switching to **Scratch Pad**
3. Notice the error **Something Went Wrong**

**Screenshots or Videos**

- Video
https://www.loom.com/share/4f34714365c7422993d748707980fa19

- Screenshot
<img width="899" alt="Screen Shot 2021-04-12 at 8 57 57 PM" src="https://user-images.githubusercontent.com/39991756/114462703-f02f4800-9bd2-11eb-96e5-86ab5cef6ed9.png">

**Environment Information**

 - Platform Type: Desktop
 - Postman Version: Version 8.2.1 (8.2.1)
 - Operating System: macOS Catalina Version 10.15.5

**Additional Context**

**Comment by Atr07** [comment]
Im also facing the same issue in windows version. 

Screenshot:

![postman_crash_something_wrong](https://user-images.githubusercontent.com/48724706/114529876-0affcc00-9c68-11eb-9d00-3bdb37f3877e.jpg)

**Comment by Raj-postman** [comment]
Hi @mantey-github @Atr07

Our team has just released a fix for this issue, could you please update the application to v.8.2.2 and let us know if that helps?

![image](https://user-images.githubusercontent.com/47771757/114538931-8e71eb00-9c71-11eb-938a-3329f9102685.png)

**Comment by Atr07** [comment]
@Raj-postman 

Installed new version but still the same.

**Comment by Raj-postman** [comment]
@Atr07 Sorry to hear that, could you please share the app logs by submitting a ticket here: https://www.postman.com/support   with the title as "GH #9828"

The following help guide provides information on retrieving app logs based on your OS:

https://support.postman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-

**Comment by mantey-github** [comment]
@Raj-postman it works on my macOS Catalina

**Comment by Raj-postman** [comment]
@Atr07 Just checking back to see if you are still seeing issues?

Also to let you know, our team has just released a new fix for this in the latest version v.8.2.3. Do update and let us know if that helps.

**Comment by Atr07** [comment]
@Raj-postman  installed v8.2.3 and it's working now. Thanks.

**Comment by Raj-postman** [comment]
Thank you for the update :)
