### ISSUE TITLE
Postman unexpectedly un-maximizes when getting a new Auth token.

### ISSUE THREAD

**Issue by nbon12** [a85/POSTMan-Chrome-Extension#9832]
**Describe the Issue**

The postman screen goes from Maximized to not-maximized after getting a new access token.

**Steps to Reproduce**

Maximize the screen for Postman
![image](https://user-images.githubusercontent.com/17408265/114559696-002e4280-9c3a-11eb-9428-978feb2d11df.png)

Click "Edit" on a collection:
![edit collection](https://user-images.githubusercontent.com/17408265/114559841-2358f200-9c3a-11eb-9656-e1282dea8777.png)
Get a new Auth Token:
![image](https://user-images.githubusercontent.com/17408265/114559576-e0971a00-9c39-11eb-82d4-e081ca75a1d0.png)
Observe that the screen went from Maximized to a non-maximized window.
![image](https://user-images.githubusercontent.com/17408265/114560095-5b603500-9c3a-11eb-862f-5ac50a62404c.png)

**Environment Information**

 - Platform Type: Windows
 - Postman Version: 8.1.0
 - Operating System: Win32 10.0.19042 / x64

**Comment by postman-staff** [comment]
Hello 👋​  @nbon12,

Thank you for flagging this and providing all the details.

Our engineers are actively looking into the issue.

We'll keep you posted on any updates - sorry for the inconvenience.

via @VaishnaviChallaPostman | Postman Support

**Comment by RaisinTen** [comment]
Hey @nbon12, could you please test out the latest Postman version (v9.16.x) and let us know if this is still an outstanding issue?

**Comment by dsanders11** [comment]
This should be fixed in Postman version v9.16.0 and newer, so I'm closing this issue. If you still see this problem, please leave a comment and feel free to ping me. Thanks!
