### ISSUE TITLE
Unable to Import Swagger API Documentation in version 8.2.2

### ISSUE THREAD

**Issue by StaciMize** [a85/POSTMan-Chrome-Extension#9834]
**Describe the Issue**

**Steps to Reproduce**

**Screenshots or Videos**

https://vimeo.com/536382224/79f74674d4

**Environment Information**

 - Platform Type: win32 10.0.17763 / x64
 - Postman Version: Version 8.2.2
 - Operating System: Windows 10

**Comment by postman-staff** [comment]
Currently working on your ticket and escalating to engineering.
Will merge the ticket into the current ticket you have.
via @stcalica | Postman Support

**Comment by xk0der** [comment]
@StaciMize I see you had logged a [support ticket](https://postman.com/support) with us too and that was addressed.
I'm closing this GitHub issue.

If there are any further issues/queries, feel free to create a new GitHub issue or log a new ticket.
