### ISSUE TITLE
Global Variables Stopped Working within Bearer Token

### ISSUE THREAD

**Issue by brotsky** [a85/POSTMan-Chrome-Extension#9836]
**Describe the Issue**
Globals vars stopped working in the Bearer Token input. This works in the Newman CLI and it worked until I updated Postman today. 

**Steps to Reproduce**
Set a global variable
Use the Variable in the token input

**Screenshots or Videos**

This is where I set the variable:
![Screen Shot 2021-04-13 at 3 27 05 PM](https://user-images.githubusercontent.com/2758150/114629022-b579ee00-9c6c-11eb-8188-4fa26f56db8c.png)

This is how I know the variable isn't working:
![Screen Shot 2021-04-13 at 3 27 50 PM](https://user-images.githubusercontent.com/2758150/114629084-d04c6280-9c6c-11eb-9f52-0359eb9db79e.png)

I know the global variable is set because when I hover over it it shows up:
![Screen Shot 2021-04-13 at 3 31 42 PM](https://user-images.githubusercontent.com/2758150/114629398-5a94c680-9c6d-11eb-86e4-929b609c1324.png)

**Environment Information**

 - Postman Version: 8.1.0
 - Operating System: OSX

**Comment by DannyDainton** [comment]
Hey @brotsky

Out of interest, when you hit `Reset all` in the global variable management section, does it work?

**Comment by brotsky** [comment]
> Hey @brotsky
> 
> Out of interest, when you hit `Reset all` in the global variable management section, does it work?

That worked! Thanks @DannyDainton
