### ISSUE TITLE
Bug: I just updated to latest v8.2.2 version and all my examples from all the collections disappeared

### ISSUE THREAD

**Issue by harshvchawla** [a85/POSTMan-Chrome-Extension#9837]
**Describe the Issue**
I just updated to latest v8.2.2 version and all my examples from all the collections disappeared

**Steps to Reproduce**
1. Save some examples in different collections
2. upgrade postman to v8.2.2

**Screenshots or Videos**
NA

**Environment Information**
 - Platform Type: Windows app
 - Postman Version: new version v8.2.2
 - Operating System: Windows

**Additional Context**
Not part of any workspace (unsigned account of postman app) so there was no sync/backup even

**Comment by harshvchawla** [comment]
Exporting and re-importing the collection restores the examples
but restarting postman do not fix the issue

**Comment by postman-staff** [comment]
Hey @harshvchawla,

Thanks for reaching out and we are really sorry for the troubles.

As I understand it, you have lost all the examples **in Scratch Pad** after updating to v8.2.2, however, you could restore them by exporting and importing the collections, is that correct?

This is definitely an unexpected behaviour, but I am glad to hear that you could at least restore your data.
I am going to report this to our engineering team. In the meantime, please do let me know if you have any other questions that I can help.

via @taehoshino | Postman Support

**Comment by AndrewTseZhou** [comment]
> **Describe the Issue**
> I just updated to latest v8.2.2 version and all my examples from all the collections disappeared
> 
> **Steps to Reproduce**
> 
> 1. Save some examples in different collections
> 2. upgrade postman to v8.2.2
> 
> **Screenshots or Videos**
> NA
> 
> **Environment Information**
> 
> * Platform Type: Windows app
> * Postman Version: new version v8.2.2
> * Operating System: Windows
> 
> **Additional Context**
> Not part of any workspace (unsigned account of postman app) so there was no sync/backup even
I also have same problem. Because, postman replaced local data with workspace since 8.x. I think the function of workspace is very poor! I uninstall postman, it's really a bad software now!

**Comment by postman-staff** [comment]
Hey @AndrewTseZhou,

Thanks for reaching out and really sorry for the troubles.

Our engineering team is currently working on this issue. As soon as I receive any updates, I will be in touch with you.

Thanks again for your patience.

via @taehoshino | Postman Support

**Comment by badmansan** [comment]
Confirm that, I have the same bug. 
It looks like this:
![screnshot](https://user-images.githubusercontent.com/13345595/114847421-5e982400-9de6-11eb-8329-044946d786d8.png)

All workspaces are present, but they are empty

**Comment by gerektoolhy** [comment]
Not sure if that is the same issue, but i see this.  

P.s. my colleague is seeing the same.  version 8.2.2

![image](https://user-images.githubusercontent.com/131102/114850958-fd724f80-9de9-11eb-8303-66d2803f8582.png)

**Comment by AndrewTseZhou** [comment]
> Not sure if that is the same issue, but i see this.
> 
> P.s. my colleague is seeing the same. version 8.2.2
> 
> ![image](https://user-images.githubusercontent.com/131102/114850958-fd724f80-9de9-11eb-8303-66d2803f8582.png)

I have same problem. https://github.com/postmanlabs/postman-app-support/issues/9818

**Comment by arlemi** [comment]
We're aware of the issue and investigating it. Please check https://status.postman.com/ and #9840 for updates as this issue is for a different problem.

**Comment by postman-staff** [comment]
Thanks for reporting this and we are really sorry for the troubles.

Regarding to the **"Unable to load data"** error, we had some downtime on our service, but the issue is now resolved.

via @taehoshino | Postman Support

**Comment by harshvchawla** [comment]
i just updated to v8.3.3 and now the already opened requests wont load :(
got scary for a bit but then i closed all open tabs and now it works (these glitches can be annoying in production when i did not sign up for beta/canary releases)
phiew, i wont be updating postman for another century now lol, confidence shaken

**Comment by postman-staff** [comment]
Hey @harshvchawla,

Thanks for confirming the fix! I am glad to hear that it is working fine.

But again, sorry for the troubles, and thanks so much for your cooperation on this.

With regard to this original issue with missing examples in Scratch Pad, our team has released the fix on v.8.2.3, could you update the application and let us know if that helps?

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @harshvchawla,

I hope all is well! I just wanted to follow up on my previous message.
If there's anything we can help, please do feel free to reach out!

Have a great day and thanks for using Postman 🚀​

via @taehoshino | Postman Support

**Comment by harshvchawla** [comment]
Hi @taehoshino 

> With regard to this original issue with missing examples in Scratch Pad, our team has released the fix on v.8.2.3, could you update the application and let us know if that helps?
> via @taehoshino | Postman Support

On updating to v8.2.3, my examples did not disappear so this issue seems to have fixed. Thanks for the follow-up

> Thanks for confirming the fix! I am glad to hear that it is working fine.
> via @taehoshino | Postman Support

I was not confirming any fix but was raising a different issue actually where I had to close all opened tabs as they had stopped working
Though this is a different bug than the one raised here I understand so hopefully you create a ticket for your development team separately
