### ISSUE TITLE
Unable to validate Mock Server after changing the spec

### ISSUE THREAD

**Issue by pranav-davar** [a85/POSTMan-Chrome-Extension#9838]
After adding one schema element to the spec definition, I am unable to validate Mock Server. PFB.

![postman](https://user-images.githubusercontent.com/30888879/114657371-8e272d80-9d0d-11eb-9cdd-e74c0dddf496.gif)

After I click on Click to validate it changes to → validating → Issues found → Click to validate

Due to this, I am unable to update the Mock server with new API spec changes.

Postman Version: 8.2.2

**Comment by DannyDainton** [comment]
Hey @cipherwizard9 

I'm unable to recreate this issue with the provided information. If you are still having issues and can reproduce this in the latest version of the platform we can look at reopening this but I'm closing for now.
