### ISSUE TITLE
Feature request: Quick access to current environment variables editing dialogue

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#984]
Every time I'd like to add a new environment variable I find myself repeating the same steps over and over again:
1. Click on environment name
2. Click on Manage Environments
3. Click on desired environment name again (I have quite some environments so this takes time to discern the environment I'm interested in)

This can be quite tedious and is also an error prone approach.

So here is my feature proposition:
Postman has this awesome 'peek functionality' when hovering over the eye symbol that shows the current environments variables as well as the globals. Why not add a click handler to the eye, that would directly lead into the current environment editing mode? This would be quite handy and I guess also easily implemented.

Cheers,
Ben

**Comment by a85** [comment]
@jotb The click handler is there now in the latest versions of Postman. More improvements for variable editing are coming soon!
