### ISSUE TITLE
Postman says I'm offline though my Internet connection is working. 

### ISSUE THREAD

**Issue by KelvinGits** [a85/POSTMan-Chrome-Extension#9840]
I can't access my workspaces because Postman thinks I'm offline though I'm clearly online. This is quite frustrating. I have tried restarting postman but to no avail. 

![image](https://user-images.githubusercontent.com/42736291/114825223-9bf0b780-9dce-11eb-9a5f-2020eb8b66d9.png)

**Comment by DudeGrim** [comment]
I think theres a problem with the Postman API Network (API Explore). I'm having similar problems. 
https://status.postman.com/


![image](https://user-images.githubusercontent.com/9623863/114825896-5c8b9080-9df9-11eb-9ddc-41e1c86061f9.png)

**Comment by DannyDainton** [comment]
We were observing elevated error rates on Postman across both the desktop and the browser. The systems are back on track now and we are actively monitoring it.

Are you still experiencing issues connecting @KelvinGits / @DudeGrim

**Comment by DudeGrim** [comment]
> 
> 
> We were observing elevated error rates on Postman across both the desktop and the browser. The systems are back on track now and we are actively monitoring it.
> 
> Are you still experiencing issues connecting @KelvinGits / @DudeGrim

Things on my end is working now. Thanks for the speedy fixes! ☜(ﾟヮﾟ☜)

**Comment by DannyDainton** [comment]
That's great to hear! 

@KelvinGits are things also looking better for you now, if so, can we close this issue out? 🙏🏻

**Comment by DannyDainton** [comment]
All the services are currently operational, if you're still experiencing issues we can open this issue again. Closing it for now.

**Comment by tscheckenbach** [comment]
Please reopen, I still have the mentioned problem.

**Comment by n-verbitsky** [comment]
Me and my team are having the same issue across multiple devices.

@DannyDainton, could you please take a look?

**Comment by arlemi** [comment]
We're aware of the issue and investigating it. Please check https://status.postman.com/ for updates.

**Comment by arlemi** [comment]
The issue has been mitigated and we are actively monitoring it. Thank you for your patience!

**Comment by rajvis** [comment]
Hi @arlemi - I am still facing this issue. Please advise.

**Comment by arlemi** [comment]
@rajvis Are you seeing it on the web or the app? Have you tried closing/re-opening, or refreshing the page?

**Comment by rajvis** [comment]
@arlemi - I've had the problem in both the Web and the App at the time, but looks like it is working for me now. Thanks for checking in

**Comment by thobson** [comment]
Now seems to be working for me 👍

**Comment by saarthakbhagra** [comment]
Experiencing the same problem right now - Is there an issue going on?

@postman-support

**Comment by ghost** [comment]
getting the same issue
@postman-support

**Comment by GiJ03** [comment]
Getting the same issue now:
![image](https://user-images.githubusercontent.com/57536491/115160364-6ccf9400-a0b5-11eb-8a14-3ac721298e41.png)

However, "https://status.postman.com/" says everything is up.
![image](https://user-images.githubusercontent.com/57536491/115160388-81ac2780-a0b5-11eb-8420-8e02cdd1bd7b.png)

@postman-support : Please suggest. Is something wrong with the latest version of Postman?
![image](https://user-images.githubusercontent.com/57536491/115160405-9d173280-a0b5-11eb-9984-ce8a77feebdb.png)

**Comment by konstantin-tcherkashin** [comment]
same issue @postman-support

**Comment by awaken180-dev** [comment]
This is happening to me today following upgrade.

**Comment by hiyers** [comment]
This issue still exists.

**Comment by xpcyl8** [comment]
Same...

**Comment by vikash-pro** [comment]
I have a proper internet connection but in my postman it appears that I am offline and get message "Please connect to internet to use this feature". @postman-support

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9b833f14-f40b-4e88-ba61-476fb2af5554" />
