### ISSUE TITLE
Merge greyed out for forked collection - "Share the source collection to merge changes"

### ISSUE THREAD

**Issue by Surt** [a85/POSTMan-Chrome-Extension#9842]
**Describe the Issue**

As of Version 8.2.2 the merge button is now greyed out for forked collections with the error "Share the source collection to merge changes".
On previous attempts with older versions we were using it with no problems. (can't say in which versions it broke)

We've checked out the "Using source control" documentation and as far as we can tell, this is the process we have been (and are trying to) follow.

This a copy of related to closed: https://github.com/postmanlabs/postman-app-support/issues/9810

**Steps to Reproduce**

From a SHARED collection with permissions setted we fork it to "My Workspace" then, we make changes on the "local"-"My Workspace" fork and when triying to Merge or Pull changes the button is greyed out.

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/48085/114843417-170b9b00-9dda-11eb-98e0-bef322a28c62.png)

**Environment Information**

 - Postman Version: 8.2.2
 - Operating System: Windows 10 PRO (latest update)

**Comment by DannyDainton** [comment]
Hey @Surt 

Could you complete the rest of the issue template and provide more information, please?

```
<!--
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.
Provide as much information as you can as this will give us the best possible chance to quickly get to the root of the problem.
-->

**Describe the Issue**
<!--
A high-level summary or description of the problem that you're facing.
-->

**Steps to Reproduce**
<!--
A list of steps that can be followed to recreate the issue.
-->

**Screenshots or Videos**
<!--
Please add screenshots or a short video to help visually explain the problem. 
Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 
-->

**Environment Information**

 - Platform Type: 
 - Postman Version:
 - Operating System:

**Additional Context**
<!--
Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
-->

```

**Comment by Surt** [comment]
> Hey @Surt
> 
> Could you complete the rest of the issue template and provide more information, please?
 
It is done

**Comment by ankit-m** [comment]
Hey @Surt,

Thank you for reporting this issue. I was able to reproduce it as well. I have also filed a bug on our internal tracker. Will keep this thread updated.

**Comment by ankit-m** [comment]
We have released a fix for this on our web version. Check it out on https://go.postman.co. It will soon be released on the native apps.
