### ISSUE TITLE
Slow loading of workspaces in v8

### ISSUE THREAD

**Issue by nasco-a** [a85/POSTMan-Chrome-Extension#9845]
**Describe the Issue**

When working with large collections loading workspaces seems to be taking quite a lot of time, making the initial loading of the workspace and the switch between workspaces time consuming(a couple of minutes to an hour)

**Steps to Reproduce**
1. Create a very large collection (50MB+)
2.Make sure the collection gets synced to the server
3. Try restarting Postman/switching workspace, and see the time it takes for the collection to fully load and to be able to make changes to it

![image](https://user-images.githubusercontent.com/77739708/114983576-767cb000-9e99-11eb-8d98-37b0c3e32efc.png)

**Environment Information**

 - Platform Type: v8

**Additional Context**
This issue is already being tracked internally.

**Comment by victordias2000** [comment]
I'm experiencing this issue with Postman app (v8.4) on macOS (11.3.1). Before v8, loading large collections were fine.

**Comment by romit7** [comment]
Same issue here..before v8 on windows10 large collections loading and syncing was fine. Now I have to wait for more than 30mins to go to my workspace

**Comment by Meowzz95** [comment]
Same issue here, large collection takes forever to load in both Mac App and web version.

**Comment by odonnell-anthony** [comment]
Same issue for me, please fix this makes use of the desktop application quite painful sometimes

**Comment by shipleyr** [comment]
Yes same with me - more specifically it's around loading the environments. As soon as I change tabs to the environment select the app locks for about 20 seconds. Same on every switch of a workspace.

**Comment by deresh** [comment]
Same here, sync button says it's in sync. but collection list view is loading for minutes, and i can see that Postman isn't loading anything from network.

**Comment by DannyDainton** [comment]
Hey folks,

There have been lots of performance improvements since this was reported. If this is still happening in the latest version of the platform we can look deep at the issues being faced but for now, I'm going to close this out.
