### ISSUE TITLE
Scratch Pad failed to show the request tab page

### ISSUE THREAD

**Issue by hlmd** [a85/POSTMan-Chrome-Extension#9846]
**Describe the Issue**

This is a **Scratch Pad**'s request tab error.
I opened a request saved in the collection in the Scratch Pad, and then I opened the following (Body, Pre-request Script or Test) tab and switched to the workspace. When I switched to the Scratch Pad again, the request tab appeared "Something Went Wrong"

**Steps to Reproduce**

![a](https://user-images.githubusercontent.com/45023268/114998088-2d495200-9ed3-11eb-8ef0-c4dd46a5dd7e.gif)

**Screenshots or Videos**

![QQ图片20210416165217](https://user-images.githubusercontent.com/45023268/114999187-325ad100-9ed4-11eb-94c2-8073e09fcfd3.png)

**Environment Information**

 - Platform Type: Desktop Agent
 - Postman Version: 8.2.3
 - Operating System: Windows [win32 10.0.19042 / x64]

**Additional Context**

The error can be reproduced every time.
This error was discovered recently, but I think it has always existed.

**Comment by pankajk07** [comment]
@hlmd Sorry to hear that, could you please share the app logs by submitting a ticket here: [https://www.postman.com/support](https://www.postman.com/support)

The following help guide provides information on retrieving app logs based on your OS:

https://support.postman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-

**Comment by hlmd** [comment]
@pankajk07 
Is it this one.
![image](https://user-images.githubusercontent.com/45023268/115003865-caf35000-9ed8-11eb-9061-ea238df440a5.png)

**Comment by pankajk07** [comment]
@hlmd I would suggest you zip the complete folder and send it to us.

**Comment by hlmd** [comment]
@pankajk07 
I have sent logs.zip to help@getpostman.com. please check.

**Comment by pankajk07** [comment]
@hlmd We haven't received the logs yet. Can you please raise a ticket here [https://postman.com/support](https://postman.com/support)?

**Comment by hlmd** [comment]
@pankajk07 I have submitted a request for 73214.

**Comment by pankajk07** [comment]
@hlmd Thanks for raising the support ticket. We have received the logs and are looking into the issue. In the meantime, closing the crashed tab and reopening it should work fine.

**Comment by hlmd** [comment]
@pankajk07 Yes, it can run and save normally

**Comment by hlmd** [comment]
I updated Postman to v8.4.0, this issue has been resolved, Thanks！！！
👍👍👍
