### ISSUE TITLE
Persist variable value option no more available in settings page

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9847]
**Describe the Issue**

**Steps to Reproduce**

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/45095911/115150723-8ba43b00-a061-11eb-8f1b-01594982c6a4.png)

**Environment Information**

 - Platform Type:  web and destop
 - Postman Version: Version 8.2.3
 - Operating System: Win32

**Comment by DannyDainton** [comment]
This option was removed as part of the V8.0.8 release:

> For enhanced privacy of your environment variable data, current values of variables no longer automatically persist to initial values when modified. You can still persist these values via the Persist All button in the variable edit screens

**Comment by praveendvd** [comment]
> This option was removed as part of the V8.0.8 release:
> 
> > For enhanced privacy of your environment variable data, current values of variables no longer automatically persist to initial values when modified. You can still persist these values via the Persist All button in the variable edit screens

is there a way to dynamically change the variable value for mock server other than this option ?

**Comment by praveendvd** [comment]
https://community.postman.com/t/passing-request-parameters-as-variables-to-use-in-response-body/22787/10?u=praveendvd

There was one work around mentioned in the community forum thanks Danny , it's about modifying the example using postman api . Just commenting if someone is looking for a workaround

**Comment by sony-mathew** [comment]
Hey @praveendvd , we have enhanced our dynamic mocking experience over the course of time. Please find the learning documentation link for the same here: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/creating-dynamic-responses/

This document talks about various ways you can make a mock server response more dynamic and suited for your use-case.
I'm closing this ticket with this. Feel free to reopen if you feel that this does not solve your use-cases.
