### ISSUE TITLE
Looping over request doesn't accumulate test results

### ISSUE THREAD

**Issue by der-kommissar** [a85/POSTMan-Chrome-Extension#9848]
**Describe the Issue**

When looping over a request (using the collection runner) the test results include only those from the last iteration.
![image](https://user-images.githubusercontent.com/74671809/115152925-f2612e80-a038-11eb-9970-1332874fe59c.png)
Notice that there are 6 passing tests but only 2 are shown.

**Steps to Reproduce**

Create a collection that sets up an array of `args` that we can loop over:
![image](https://user-images.githubusercontent.com/74671809/115153023-64d20e80-a039-11eb-9828-394e33f643d5.png)

Create a request in that collection with the following pre-request script:
```JavaScript
const args = JSON.parse(pm.collectionVariables.get("args"));
const arg = args.pop(); //grab an arg from the array
if (args.length > 0) {     //run this request again if there are still args in the array
    postman.setNextRequest("Postman echo");
}
pm.variables.set("arg", arg);
pm.collectionVariables.set("args", JSON.stringify(args));
```

And add the following test script:
```JavaScript
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});

pm.test("arg1 is set", function () {
    const responseBody = pm.response.json();
    console.log(responseBody);
    pm.expect(responseBody).to.exist;
    pm.expect(responseBody.args.arg1).to.eq(pm.variables.get("arg"));
});
```
Then run the collection in the collection runner.

**Environment Information**

 - Platform Type: Postman for Windows
 - Postman Version: 8.2.2
 - Operating System: win32 10.0.18363 / x64

**Additional Context**

The above is a simplified example of my problem. Ultimately I want to loop over an array of IDs and send the same request with a tokenized ID in the URL. With each iteration I want the tests to run and to be able to see the results for each iteration.

**Comment by praveendvd** [comment]
https://www.getpostman.com/collections/9390904e1312cbebe30f

it works fine , your setnext request name would be wrong . Try : 

postman.setNextRequest(pm.info.requestName);

**Comment by DannyDainton** [comment]
Closing this based on @praveendvd's comment - If this is still an issue for you, we can look to reopen this again.
