### ISSUE TITLE
Feature Request: Display Scaling

### ISSUE THREAD

**Issue by hitsuji** [a85/POSTMan-Chrome-Extension#985]
It's quite difficult to read the text on a 3K or 4K display in the packaged app. If it could scale up to 2X+ for such displays that would be awesome. The old chrome extension does this fine as it scales with the browser settings, however, the newer packaged app does not scale with the browsers settings.

**Comment by abhijitkane** [comment]
@hitsuji This is a limitation of the Chrome packaged app platform. v3.0.4 of the app has a 'UI Scale' setting in the Settings modal. Does that help?

**Comment by kemallette** [comment]
+1

On `v3.0.9` of the Chrome packaged app. At 4k, UI text is almost unreadable. `UI Size` setting set to `bigger` does not help. In fact, it actually makes the UI text appear a bit smaller compared to `default`. The response text setting works great, however. I've got mine set to 16px.  Much to my dismay, this is enough of an issue for me that I can't really use the packaged app until this is addressed. :( 

I'm happy to provide any extra details that may help.

**Comment by a85** [comment]
Display scaling is available in the Postman apps now. Check out the shortcuts screen!
