### ISSUE TITLE
[FR] Documentation on how API validation works

### ISSUE THREAD

**Issue by taehoshino** [a85/POSTMan-Chrome-Extension#9850]
**Is your feature request related to a problem? Please describe.**
Currently, the only public facing information on API validation is the following LC article:
https://learning.postman.com/docs/designing-and-developing-your-api/validating-elements-against-schema/#validating-elements

However, it is not very clear/obvious to users what properties are validated and what is not, so it would be helpful to users if this information is publicly available. 

**Describe the solution you'd like**
Include what properties are being validated in Learning Center article

**Additional context**
Filed by Product Support. 
This has already been internally filed. Filing here for public tracking purpose.

**Comment by DannyDainton** [comment]
Hey @taehoshino

This might be better over on the Documentation repo:

https://github.com/postmanlabs/postman-docs

**Comment by taehoshino** [comment]
Thanks for your comments @DannyDainton!

I have moved it over to `postman-docs` https://github.com/postmanlabs/postman-docs/issues/3010 👍
