### ISSUE TITLE
Calls to postman-echo.com that worked for over a year started failing with 403s

### ISSUE THREAD

**Issue by jimshowalter** [a85/POSTMan-Chrome-Extension#9855]
We use curl https://postman-echo.com/get?key=val to unit test our HTTP client.

We chose that URL because it is fast, lightweight, returns a simple response that's easy to parse (to validate that it worked), doesn't require complicated auth configuration, and seems to always be up.

To avoid bugging the site owner, we insert a delay before each call, and our total traffic per day is probably no more than 100 calls.

Recently we started getting 403s back from the server.

Have we been blocked?

**Comment by postman-staff** [comment]
Can you paste the cURL request you use to make the call?

via @stcalica | Postman Support

**Comment by jimshowalter** [comment]
It's above:

`curl https://postman-echo.com/get?key=val`

It returns:

`{"args":{"key":"val"},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-607df4de-4f9ee28947b84db975e33c9f","user-agent":"curl/7.64.1","accept":"*/*"},"url":"https://postman-echo.com/get?key=val"}`

**Comment by postman-staff** [comment]
Importing into Postman it returns a 200 and this is the proper response.
Here are our limits on the Postman API, however, we would return a response detailing you have reached the limits.
https://support.postman.com/hc/en-us/articles/360026236734-Postman-API-Usage-and-Rate-Limit#:~:text=Rate%20Limits,key%20basis%20in%20unit%20time.

Do you have an example response from when you get a 403?

​ ![](https://postman.zendesk.com/attachments/token/RqxAnqYCwYLSFhycBdJs2qS69/?name=Screen+Shot+2021-04-19+at+2.42.49+PM.png)​

via @stcalica | Postman Support

**Comment by jimshowalter** [comment]
This is all we get back:

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

**Comment by postman-staff** [comment]
Can you log a support ticket at https://www.postman.com/support, please?
I can look up your account details from there and see if you have reached any limits.

via @stcalica | Postman Support

**Comment by jimshowalter** [comment]
We don't have an account.

**Comment by postman-staff** [comment]
For a free team max # of calls to Postman API (monthly) can be made is 1000 calls.
But we cannot verify if you have hit this limit without an account.
If you had an account we could check:
https://go.postman.co/billing/add-ons/overview

A screen recording might be helpful to see if there's any other issues you are facing when making this call.

via @stcalica | Postman Support

**Comment by jimshowalter** [comment]
I'm going to try to find a different URL first. Thanks for your help!

**Comment by postman-staff** [comment]
Alright, if you need any more help please reach out again.

via @stcalica| Postman Support
