### ISSUE TITLE
Not found postman-proxy certification

### ISSUE THREAD

**Issue by gatrongnuoiheo** [a85/POSTMan-Chrome-Extension#9857]
Hi team,
According to https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#capture-https-traffic-with-postmans-built-in-proxy

I could not find proxy folder in C:\Users<user>\AppData\Roaming\Postman\proxy

So could not Capture HTTPS traffic with Postman's built-in proxy

**Environment Information**
 - Platform Type: 
 - Postman Version: 8.2.3
 - Operating System: Windows 10

Pls help me.
Many thanks,
Cap Tan

![Capture](https://user-images.githubusercontent.com/82895251/115426930-2c922200-a22b-11eb-8a23-817b67e8fe3d.PNG)

**Comment by postman-staff** [comment]
Hey @gatrongnuoiheo,

Thanks for reaching out and reporting this.

I am currently checking with our internal team on this - as soon as I receive any updates, I will be in touch with you!

Let me know if you have any other questions in the meantime.

via @taehoshino | Postman Support

**Comment by AMBULATUR** [comment]
Same trouble.

- Postman for Windows
- Version 8.2.3
- win32 10.0.19041 / x64

**Comment by postman-staff** [comment]
@gatrongnuoiheo and @AMBULATUR,

Our engineering team has confirmed that the https proxy feature will be included in the version 8.3.0 release.

We do not have an exact ETA yet but I will update here if we hear back any further information!

Thanks for your patience and also thanks for your interests in our new feature!

via @taehoshino | Postman Support

**Comment by abhijitkane** [comment]
@gatrongnuoiheo @AMBULATUR Support for HSTS in Postman's proxy has been released with version 8.3.0. This is only available on Postman's native app, and not the version on the web.

Once you upgrade your app, check https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#capture-https-traffic-with-postmans-built-in-proxy for installing the certificate Postman needs to read HTTPS requests.

**Comment by avchernys** [comment]
I have updated my postman. I'm on Windows and the folder C:\Users<user>\AppData\Roaming\Postman\proxy exists however no certificate inside. What should I do?

**Comment by abhishekc23** [comment]
@avchernys Please ensure openssl is installed on the windows machine. The steps can be found here
https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#requirements-to-use-the-openssl-module

After installing openssl, please restart the app.

**Comment by avchernys** [comment]
> After installing openssl, please restart the app.
Works now, thanks!

**Comment by gatrongnuoiheo** [comment]
> > After installing openssl, please restart the app.
> > Works now, thanks!

perfect

**Comment by gatrongnuoiheo** [comment]
> @avchernys Please ensure openssl is installed on the windows machine. The steps can be found here
> https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#requirements-to-use-the-openssl-module
> 
> After installing openssl, please restart the app.

many thanks

**Comment by saucedbeacon** [comment]
I've installed openSSL and the certificate isnt showing after restart.
Postman v8.7.0, Win86

**Comment by taehoshino** [comment]
Hey @saucedbeacon,
Thanks for getting in touch! 
So that we can assist you further, would you please submit a support request from the following link?
https://support.postman.com/hc/en-us/requests/new

**Comment by jehanjazz** [comment]
@taehoshino this is still not working it seems.

Made a new request here : https://support.postman.com/hc/en-us/requests/84715

**Comment by jehanjazz** [comment]
Update : https://github.com/postmanlabs/postman-app-support/issues/10299

Seems like this is already open. My above comment can be ignored.

**Comment by lianguooo** [comment]
> @taehoshino this is still not working it seems.
> 
> Made a new request here : https://support.postman.com/hc/en-us/requests/84715


restart window solve my issue
