### ISSUE TITLE
Not able to send images as part of form-data

### ISSUE THREAD

**Issue by saiudayakella** [a85/POSTMan-Chrome-Extension#9859]
**Description**
Not able to send images as part of form-data

**Scenario**
Send images as part of the API request

**Steps to Reproduce**
Send a request with following attributes:
- HTTP method: `POST`
- Enter the request URL
- Body: Select  form-data option
- Specify key name and select `File` option from the drop-down
- Browse a image

![image](https://user-images.githubusercontent.com/19469293/115482306-b83e9980-a291-11eb-8c11-be3c3541e3de.png)

**Observation:** Browsed image is not picked while sending the request. I could see the value as `undefined` while sending the request. Refer the screenshot for reference.

I tried the same scenario in swagger and it all worked fine. 

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/19469293/115479390-aa861580-a28b-11eb-95ad-b6b55d090e01.png)

**Environment Information**

 - Platform Type: win32 10.0.19041 / x64
 - Postman Version: Version 8.2.3
 - Operating System: Windows

**Comment by mccannt** [comment]
Hi @saiudayakella 

Thanks for pointing this out, I do see the `undefined` in the console. However, it is still working for me when I send an image.

Could you maybe try the postman-echo.com service to verify?
![image](https://user-images.githubusercontent.com/14275144/115556606-3c3f5400-a287-11eb-9992-bce8a662d1bd.png)

I have gone ahead and logged the defect for `undefined` in the console logs.

**Comment by saiudayakella** [comment]
Thanks @mccannt for logging a bug related to the console log. 

I could send form-data. Earlier I was missing a character in the request URL on my side :)

You can close this issue if you have already logged a new bug.

**Comment by mccannt** [comment]
@saiudayakella Thanks for following up on this. 
I will close this issue out for now but please let us know if you run into any further issues like this. 

I had kept the defect open for `undefined` in the console on our end to address shortly :)
