### ISSUE TITLE
Feature Request: Add headers to multipart form builder for each form part

### ISSUE THREAD

**Issue by PaigingAlyssa** [a85/POSTMan-Chrome-Extension#986]
# Feature

I would like to be able to set the Content-Type header for each of my form parts. Currently the only way to set a Content-Type header for a form part is to use the file option. The Content-Type is chosen by the extension of the selected file. In cURL I can add the ;type=application/json (etc) on my form part to set the Content-Type;
## Use Case

I want to send JSON data as part of my form, where the key is the name of the form part and the value is the JSON data. I need to be able to set the Content-Type header to application/json for this part of the from.
### Adding a file to get the application/json header

![screen shot 2015-04-02 at 10 50 36 am](https://cloud.githubusercontent.com/assets/6575650/6967628/248cf028-d926-11e4-9c4f-b99e9c39e5f7.png)
### Has the header I want, but is for a file upload

![screen shot 2015-04-02 at 10 50 43 am](https://cloud.githubusercontent.com/assets/6575650/6967629/24908c92-d926-11e4-871d-11cec099c604.png)
### I want to do add my JSON like so, but cant set it as JSON

![screen shot 2015-04-02 at 10 50 12 am](https://cloud.githubusercontent.com/assets/6575650/6967626/2480328e-d926-11e4-8e9a-681376c2f816.png)
### Content-Type not set

![screen shot 2015-04-02 at 10 50 22 am](https://cloud.githubusercontent.com/assets/6575650/6967627/24816014-d926-11e4-82c4-37343480a342.png)
### Example curl command to set the content type

```
curl -i -v -F "form_part_json={"json_key":"json_value"};type=application/json" \
-F "file=@./test.pdf" \
http://localhost:3000/upload
```

**Comment by a85** [comment]
Not sure how I missed this. This has been requested by others too. We'll have support for this soon.

**Comment by a85** [comment]
Tracking here: https://github.com/postmanlabs/postman-app-support/issues/1104. Closing this issue as a duplicate.
