### ISSUE TITLE
Test Appearing as if it runs twice

### ISSUE THREAD

**Issue by andersonjackc** [a85/POSTMan-Chrome-Extension#9862]
**Issue**

When working in a Collection Suite of tests, and running them, the number of tests run varies in number.  That is, the passed + failed value goes up and down, without tests being added.  It is not a variable amount, it increases/decreases by 1 more than the actual amount of tests.  This can be seen in the screenshots, as it appears as if the first test is running multiple times.  I say appears, since, I added a print statement to see the number of times the test actually runs, and this occurs only the expected amount of times.  For example, the "GET Homepage" Test appears to have run 6 times in the screenshot, but there are only 5 "I ran" statements in the Log.  This leads me to believe that this is just a UI issue, especially since the exported results say that the expected number of tests ran, rather than the expected number of tests + 1.

**Steps to Reproduce**

Unfortunately, this is variable in nature.  I have come across it multiple times when running the collection of tests in the screenshots.  I just run the tests, or several iterations of the tests, and it is always the first test that appears to run 1 extra time, but this does not always occur.

**Environment Information**

 - Platform Type: Postman Desktop
 - Postman Version: 8.2.3
 - Operating System: Windows 10

**Additional Context**

My teammate and I originally were concerned that it was actually duplicating the test, which could lead to an issue if this were duplicating, say, an insert into a database, but not duplicating the removal from said database.  As I mentioned, it does appear to just be a UI problem.  It is similar to the closed issue #1983

This screenshot shows that the test appears to pass 6 times, with it running 2 times in the first iteration, but the console log demonstrates that it only executed the test 5 times.
![image](https://user-images.githubusercontent.com/60368246/115604057-eaaabf80-a2ae-11eb-876e-899bf3109567.png)

This screenshot shows that when reordering the tests, it is in fact the first test that feigns duplication, instead of the specific "GET Homepage" test.
![image](https://user-images.githubusercontent.com/60368246/115604227-204fa880-a2af-11eb-892c-84ddab19f633.png)

**Comment by codenirvana** [comment]
@andersonjackc Can you share a scaled-down collection that we can use to reproduce this issue?

**Comment by andersonjackc** [comment]
@codenirvana Here is a link to the collection we have right now.  Let me know if there is anything else I can provide you with.

https://www.getpostman.com/collections/3fa4816eda28b0abb628

**Comment by der-kommissar** [comment]
I ran into this same issue.
_Postman for Windows
Version 8.11.1
win32 10.0.19042 / x64_

**Comment by malvikach** [comment]
Hi @andersonjackc @der-kommissar sorry about the experience. This can certainly be confusing and we would love to fix this issue. 

I tried running the collection you shared a few times and I am unable to reproduce the issue. 
Would you try this once on the latest app version 9.15 and let us know if you are still seeing this.

**Comment by iambearman** [comment]
I ran into this issue with v9.20.0. However, when I "Export Results" and check the output JSON file, it appears that the test only ran once. I believe it is a postman app bug rather then postman-runtime bug.

**Comment by iambearman** [comment]
I used the following collection to reproduce the problem:

https://www.getpostman.com/collections/fea8ef0d771d1f4f871d

**Comment by malvikach** [comment]
@bearmc27 thanks for sharing the collection.

Unfortunately, I am not seeing the issue at my end. Maybe you can share some screenshots and [logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs-in-the-Postman-Desktop-app
) from your end. 

This is what I see - as expected (tried both on web and desktop app) 
<img width="1430" alt="Screenshot 2022-06-07 at 5 08 15 PM" src="https://user-images.githubusercontent.com/89449769/172372371-77a7481c-fde3-4a6c-b874-be71c93f7526.png">

On a sidenote- did you mean to use a 'post' request here since the assertion says so.

**Comment by malvikach** [comment]
Update- I was able to reproduce the issue after changing the requests to `POST`. I observe that it happens intermittently and also seems like the request is being executed once but the runner UI shows that it is executed twice. Our team will be looking into this. Thanks again for helping us reproduce the problem. 

See below:


![Screenshot 2022-06-07 at 5 30 14 PM](https://user-images.githubusercontent.com/89449769/172374073-a643e16e-5ea9-4a48-af2e-046c3fcb740b.png)

**Comment by iambearman** [comment]
HTTP method shouldn't matter as I reproduced issue with 10 `GET`s, it just appears randomly. Anyways, thank you for the follow-up!

**Comment by malvikach** [comment]
You are right, after a few attempts I can see the issue with `GET` requests too.

**Comment by malvikach** [comment]
Hello @bearmc27 👋 

Glad to inform you that this bug has been fixed in Postman version 10. 

Please give it a try and let us know your feedback. 

Cheers!
Malvika

**Comment by iambearman** [comment]
I am not in Postman v10 early access group, and sorry, not intended to do so for now.

Interestingly, I fail to reproduce this problem with v9.31.0. Bug gone, everyone happy! 🎉
