### ISSUE TITLE
2 feature requests : Support of load-testing + Code editors/IDEs integration via plugins/extensions

### ISSUE THREAD

**Issue by jdecode** [a85/POSTMan-Chrome-Extension#9868]
**About me:**
I am a web developer with over 20 years of experience in making web-apps (since 2000).
And I love Postman.

I am using Postman (of/for/with/options) :
 - API testing locally (while development)
 - In my company's almost all projects
 - Non-free version
 - Integrated in our CI pipeline (via newman, dockerised, on CircleCi, GitHub and GCP)
 - With monitoring, and notifications are sent to Slack
 - Synced with GitHub repo (for auto-saving)
 - Feature-testing using Postman tests and pre-request-script (obviously)

Now that *that* part is out of the picture, let me jump on the feature requests.

**Feature request 1:** (Problem or rather "need" definition)
Add support of load testing (very similar to what/how k6.io is offering)

To run load testing in k6, there is a similar setup/structure as of Postman that requires API endpoint, parameters, test cases (javascript/web based) etc - which, since I am already using Postman, I don't want to repeat for k6.

We might move to k6 (from Postman) because it provides options to run test-cases on the API as well, but Postman does not provide the option to load-test the APIs.

**Solution that I would like :**
Running "runner" in a "load-testing" mode, so when I select "Runner" and select collection and environment, I would want to see an option (like a toggle button perhaps) that says "Run x number of times" (this feature is what is already there) and next to that should be an option to "Run each request separately" (not existing feature, will be activated via the toggle) and on toggling the option to this, the "number of executions", an input field, is shown next to each API in the collection with a number in it (the environment-controlled default value, perhaps), which would not only run the collection as a whole (while keeping, say, the first iteration of a specific API's response as the variable that could be stored as env. var for following requests), but also will run each single API the number of times it is set to run for each request in the input field defined against it.

E.g. If there are 5 APIs with different parameters running in a collection (or a folder inside a collection) called "User login and logout flow testing", then while running runner, and selecting "Run each request separately", and adding a value of, say, 100 to the "login" API, the runner will run this "login" API 100 times - not sequentially, but in parallel - projecting like a "load-test" for the server.

**Additional context :**
I did not like when I was asked to use "k6.io" for load testing (which says on its website "best developer experience for load testing") and I was able to see clearly that it was not the best experience. Not really good if I compare that to Postman.

I "had" to use k6 because of the load-testing options that it provides - looped/repeated/multi-threaded requests (I don't know how they are doing that), from different geographical locations, amount of time for which tests need to run, or number of times (parallel, not sequential), notifications (Slack or Pub/Sub) and CI pipeline integration (with options, obviously, to have a better DX).

**Feature request 2:**
Enable IDE/Editor support to run (at least *some*) test cases (or just API requests) as extension/plugin of (say) VS Code, PhpStorm, Xcode, Android Studio etc

**Solution that I would like :**
The core idea is that I want to be able to run just (and quickly) a "single" API (GET/POST/PUT) - the one that I am working on right now, from within the IDE/Editor to avoid switching different windows and to have a seamless DX.

**Additional context :**
Recently launched VS Code extension "Thunder Client" (https://www.thunderclient.io) does a great job at mimicking the Postman UI inside VS Code, while adding support of Collections, Environments, and it has gone one step further and have created a UI to allow creating common test-cases (that would be a separate feature-request from this post's POV).
It would be a great improvement in DX if some popular IDEs/Editors get the power of Postman while they are in the code.
Some good/great extension/plugin developer would be a better candidate to share insights on "simplest way Postman's API testing feature can be integrated with an IDE for a better DX".

Feature requests stop.............................
While I see a lot of new things being added to Postman, I don't see any "groundbreaking" or "creative/exciting" stuff happening in the Trello roadmap - at least from a developer POV.
Please see to the above feature requests.
I know that a lot of developers would be more than excited to have these features.
And someone in a unique situation (like mine) should not have to leave Postman.

Thanks

**Comment by vvs11** [comment]
@jdecode Thanks for writing in! Your feedback is really helpful for us. We are aware of the issues that you mentioned and are working towards figuring out a solution that fits all use cases. We will keep you posted on the developments on this thread.

**Comment by jdecode** [comment]
https://github.com/postmanlabs/postman-app-support/issues/9890

Tagging related issue.

Also, guys, let me know if I can be of any help (I know you guys can take care of the development, but I am more than happy to offer any assistance)

**Comment by shashankawasthi88** [comment]
Hey, @jdecode thanks for a detailed explanation of the use cases. We are starting to explore the ideas around the "Feature request 2" i.e. an IDE plugin. Will it be possible to get onto a short call to understand the rationale behind the requirements in depth? If yes, can you please pick a time for discussion using this link -  https://calendly.com/shashank-awasthi/ide-plugin-explorations

**Comment by jdecode** [comment]
Thanks for the follow-up @shashankawasthi88.
I have picked a time from the Calendly link above - let's catch up at the proposed time.

**Comment by Cereal916** [comment]
Another idea for implementation:
When running on multiple threads, run the collection sequentially, but on multiple instances each on their own thread, where each thread gets its own isolated environment to share variables. This way you can use collections that were designed to run sequentially in a load test.

**Comment by malvikach** [comment]
@Cereal916 👋 

Thanks for the feedback. We are looking at building this capability in Postman. Therefore, I want to understand your suggestion better.

You are looking to run parallel threads each of which runs the collection sequentially, thereby allowing you to load test your entire workflows in one go. Can you elaborate more on what kind of load you want to simulate (a couple of hundred of parallel threads vs thousands?). What kind of output metrics are you interested to look at (Response times/ error rates, anything else etc.)

I would love to discuss your use case in more detail.

If you are interested, I would request you to block some time with me to talk about this. You can use [this calendly link](https://calendly.com/malvika-chaudhary/v10-feedback?month=2023-03) to send me an invite.

Regards,
Malvika

**Comment by Cereal916** [comment]
Wish list:
The ability to load test with the desktop app.
The ability to load test with Newman.
At least a hundred concurrent threads, the more the merrier.
The ability to kill all threads/cancel while running.

Options for run include:
- number of threads
- collection runs per thread or continenuos testing for x minutes

Results include:
- avg/min/max response time per request
- total time to complete.
- http response code count per request
- test results count per request
- if test failed, log request/response

Would be nice:
- The ability to increase/decrease threads while it's running

**Comment by malvikach** [comment]
@Cereal916 Thanks for the detailed response! 👍 

I am keen to know the utility of 'test results count per request'. Do you expect that some tests might fail for some virtual users and if yes -why? _(I can imagine some of that tests might fail if there was a non-200 response)_ 

Asking the above question to understand how you want to use the load tests to do functional tests. 

I also have some early prototypes that I would love to show you. Would you be interested in this? Please drop me a yes here ([malvika.chaudhary@postman.com](mailto:malvika.chaudhary@postman.com)) if you like to. 😄

**Comment by malvikach** [comment]
Hi @jdecode 👋 

Glad to update that in the latest Postman release (version 10.15.1), we have released API Performance Testing feature. You can now use Postman to simulate real world traffic and observe your API Performance Metrics.

Read more about this on our blog [here](https://blog.postman.com/postman-api-performance-testing/).

We also released Postman's VS Code Extension. You can read about it on our blog [here](https://blog.postman.com/introducing-the-postman-vs-code-extension/). 

Appreciate your feedback. Looking forward to your feedback on the released features!

(I am closing this issue)

Cheers!
Malvika

**Comment by jdecode** [comment]
@malvikach  - Thanks for the update and much thanks to the team for bringing this concept to reality.
:pray:  :+1:  :rocket:
