### ISSUE TITLE
OpenAPI Response headers are not shown in generated documentation if body is empty

### ISSUE THREAD

**Issue by jyeros** [a85/POSTMan-Chrome-Extension#9869]
**Describe the Issue**

When a header is included as part of the response in OpenAPI 2.0 it is correctly added to a collection generated from that schema. However, documentation generated from that collection does not include the header in code examples as it should if response doesn't contain body

**Steps to Reproduce**

1. Go to "Browse"
1. Click on "Create new API" with "Open API 2.0"
1. Enter test names and open "Define"
1. A sample schema should be present. Replace the schema with one that include a path with response header and without response body. Like `HEAD /users` in the following example

```yaml
swagger: '2.0'
info:
  title: test-example-response-header
  version: 1.0.0
schemes:
  - https
host: localhost:3000
definitions:
  User:
    type: object
    required:
      - date
    properties:
      Id:
        type: string
        description: Id
      name:
        type: string
        description: Name
  UserList:
    type: array
    items:
      $ref: '#/definitions/User'
paths:
  /users:
    head:
      operationId: head-users
      responses:
        '200':
          description: OK
          headers:
            X-Query-Count:
              type: integer
              description: The count of resources.
    get:
      operationId: get-users
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserList'
          headers:
            Link:
              type: string
              description: >-
                Indicates a typed relationship with another resource, where the relation type is defined by RFC 5988.
```
5. Save
1. Click on "Develop"
1. Create Documentation
1. Open documentation

**Screenshots or Videos**

Published documentation:
![image](https://user-images.githubusercontent.com/43852295/116037135-abc19480-a635-11eb-9a99-5cad0fd08f4f.png)

Complete collection documentation view:
![image](https://user-images.githubusercontent.com/43852295/116038255-33f46980-a637-11eb-8618-0ecd32057201.png)

**Environment Information**

 - Platform Type: Web/Desktop
 - Postman Version: v8.0.7
 - Operating System: Windows 10

**Additional Context**

Expected behavior:

Response headers should be shown at generated documentation if the response body is empty, like it happens in the complete collection documentation view.

**Comment by ishan-ks** [comment]
@jyeros The documentation generated is correct and contains the headers in the `headers` tab even if `body` is empty. Please see the attached screenshot. Let us know if you are still having difficulty seeing the headers.
<img width="758" alt="image" src="https://user-images.githubusercontent.com/98811858/199664796-9d77294e-72ab-4da1-892d-ffe3c441bb17.png">

**Comment by jyeros** [comment]
It is working now, thanks

> @jyeros The documentation generated is correct and contains the headers in the `headers` tab even if `body` is empty. Please see the attached screenshot. Let us know if you are still having difficulty seeing the headers. <img alt="image" width="758" src="https://user-images.githubusercontent.com/98811858/199664796-9d77294e-72ab-4da1-892d-ffe3c441bb17.png">
