### ISSUE TITLE
Share Collection: Download as a file fails

### ISSUE THREAD

**Issue by mpiasta-ca** [a85/POSTMan-Chrome-Extension#987]
In some cases, the "Share Collection > Download as a file" does work. Redirects me to a page with json blob I can copy.

In other cases, when I click "Download as a file", nothing happens. Screens stay exactly where it is (showing the Share pop-up). But the console reports "Error: Unknown Error requester.js:1607". No other errors or debug information visible.

**Comment by abhijitkane** [comment]
As a quick fix, you can try duplicating the collection and downloading it. 
What version of Postman are you using?

**Comment by mpiasta-ca** [comment]
Version 0.8.4.14.

I don't see an option to duplicate a collection. But when I created a new collection folder, and dragged in the requests from the broken collection, it WORKED for "Download as a file". However I renamed the new collection to the old one, and refresh the page, again it wouldn't work.

**Comment by abhijitkane** [comment]
This looks like an unknown filesystem error - unrelated to disk space exceeded / permissions etc. Not sure what the exact problem is.

I suggest you look at the packaged app - https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en. It has a lot more features, and migrating data from the old app is easy - http://getpostman.com/docs/migration_new
