### ISSUE TITLE
Added request description | AssertionError: expected [] to have a length above 0 but got 0?

### ISSUE THREAD

**Issue by aditya305** [a85/POSTMan-Chrome-Extension#9871]
How can I solve this in postman??
Tried finding documentation but can't find anything?? 
![image](https://user-images.githubusercontent.com/41361167/116066569-d2b7af00-a6a5-11eb-93ad-cbea5666f050.png)

**Environment Information**

 - Platform Type:  Windows 
 - Postman Version: v8.2.3 
 - Operating System: Windows 10

**Comment by DannyDainton** [comment]
Hey @aditya305 

This assertion error looks like it's very specific to the Postman Student Expert Course - Can you open up a new thread on the Postman Community forum, please. They're a great group of folks on there who have already taken that course and will advise you on how to resolve this scenario.

https://community.postman.com/

Closing this issue and it's not a functional problem with the Postman platform.
