### ISSUE TITLE
New Integration Request - <product name>QuickBooks

### ISSUE THREAD

**Issue by mmci2468** [a85/POSTMan-Chrome-Extension#9872]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?
Get payment

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?
Cash flow
**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
@mmci2468 can you please elaborate upon what use case are you trying to achieve and how the Integration might be helpful in the same

**Comment by shashankawasthi88** [comment]
Closing this for now. Feel free to reopen while adding more details.
