### ISSUE TITLE
Collection created from API definition has different structure than in swagger

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9873]
**Describe the Issue**

1. Generate collection from open api schema doesn't show folder structure as in swagger. 
2. If only one request under a section then no folder is created in for that section in the generated collection

**Steps to Reproduce**

use the twitter api definition: 

[Twitter API definition](https://api.twitter.com/labs/2/openapi.json)

The swagger structure is as follows: 

![image](https://user-images.githubusercontent.com/45095911/116147481-b0d72000-a6d7-11eb-9739-d6e4a532e565.png)

**so the expected structure should be**

Collection name :  Tweets and Users
folder structure :  
   -       General
   -        Tweets
   -        Users
  
Request names could be PATH as it is or description instead of PATH

**Screenshots or Videos**

Actual structure of generated collection:

![image](https://user-images.githubusercontent.com/45095911/116148229-8a65b480-a6d8-11eb-9238-bddda8a56fe7.png)

**Environment Information**

 - Platform Type:      Web and Desktop
 - Postman Version:   8.3.0
 - Operating System: Win10

** Expected structure**

![image](https://user-images.githubusercontent.com/45095911/116148811-49ba6b00-a6d9-11eb-9302-981df6990fee.png)

**Comment by VShingala** [comment]
@praveendvd While importing or generating collection from API, you can select options under `Show advanced settings` dropdown menu. Make sure you have selected `Tags` for option `Folder organization`, this results in the use of specification-defined tags for generating folders.

![image](https://user-images.githubusercontent.com/16756296/116185840-0c3cf880-a740-11eb-97c4-e4a6be570c36.png)
