### ISSUE TITLE
Failed to enable HTTPs capture after upgrading Postman v8.3.0

### ISSUE THREAD

**Issue by passcodex** [a85/POSTMan-Chrome-Extension#9875]
**Describe the Issue**

Failed to enable HTTPs capture after upgrading Postman v8.3.0

**Steps to Reproduce**

https://user-images.githubusercontent.com/11014056/116264671-121cf300-a7ad-11eb-8622-7ee4bbbac219.mp4

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/11014056/116264777-2b25a400-a7ad-11eb-9c89-c577d5990ec0.png)

**Environment Information**

 - Platform Type: Postman for Windows (Desktop Agent)
 - Postman Version: 8.3.0
 - Operating System: win32 10.0.17134 / x64

**Additional Context**
There is no postman-proxy-ca.crt file in directory C:\Users<user>\AppData\Roaming\Postman\proxy

**Comment by shashankawasthi88** [comment]
@passcodex can you ensure that OpenSSL is installed on your windows machine. https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#requirements-to-use-the-openssl-module
Please restart the Postman App after the installation of OpenSSL and check if the proxy directory is created or not.

**Comment by passcodex** [comment]
@shashankawasthi88  Thank you for your guidance.

**Comment by shashankawasthi88** [comment]
I am assuming the solution has worked for you @passcodex, if not feel free to reopen the ticket.
