### ISSUE TITLE
Support OpenAPI 3.1

### ISSUE THREAD

**Issue by gwerbin** [a85/POSTMan-Chrome-Extension#9877]
**Is your feature request related to a problem? Please describe.**

[OpenAPI 3.1](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md) was released in February and has was previously in draft phase since mid 2020.

It offers several improvements over 3.0 and there are good reasons to adopt 3.1 in new projects, especially its new unification with JSONSchema.

OAS 3.1 is not currently supported by Postman.

**Describe the solution you'd like**

It would be very nice if Postman added support for OpenAPI 3.1.

**Describe alternatives you've considered**

I am not aware of any alternative.

**Additional context**

None at this time.

**Comment by samirageb** [comment]
This is a big deal for us and I can't locate it on any of the roadmaps; it's effectively a blocker to some of docs initiatives. It's kind of amazing that it's not supported given how PostmanLabs was touting their [joining the OAS initiative](https://blog.postman.com/postman-joins-openapi-initiative/) to migrate people to OAS yet they don't even support the spec themselves.

If someone can point me to where this sits on the roadmap (in case I missed it) I'd greatly appreciate it.

**Comment by dan-j** [comment]
@DannyDainton has there been any update on this issue?

**Comment by bazmandude** [comment]
Lack of OpenAPI 3.1 support is a blocker for us using Postman. We are especially keen on 3.1 as it has support for defining webhooks. An update on when/if Postman will support OAS 3.1 would be much appreciated.

**Comment by jony1993** [comment]
Lack of OpenAPI 3.1 support is a blocker for our company moving to Postman. Are there any plans when it will be integrated?

**Comment by jonasgroendahl** [comment]
also looking for this

**Comment by apkrieg** [comment]
Any update on this? It's been over seven months now.

**Comment by b166er** [comment]
> Any update on this? It's been over seven months now.

i use now Stoplight Studio for API-Definition with OpenAPI 3.1

**Comment by samirageb** [comment]
> > Any update on this? It's been over seven months now.
> 
> i use now Stoplight Studio for API-Definition with OpenAPI 3.1

I also use Stoplight, but you can't reliably import and use 3.1 definitions in Postman to take advantage of its testing capabilities.

**Comment by akshaydeo** [comment]
👋 everyone. This feature is already in development, and we will ship it in the first week of March 2022 🎉 . 
Thank you so much for your patience. 

I will keep this issue updated 🙂

**Comment by akshaydeo** [comment]
It's out now https://blog.postman.com/postman-now-supports-openapi-3-1/. 
Let us know your feedback 🙇

> For desktop, Open API 3.1 is available from version 9.14 🙇    
> We are still rolling out 9.14 to all users. You will get an in-app notification as soon as its available for download.
> Till then you can use web version of Postman to try this feature :)

**Comment by dvbsknd** [comment]
Is this available in the Desktop release yet? I'm on `Version 9.13.2` and it's not an option for me.

**Comment by akshaydeo** [comment]
For desktop, Open API 3.1 is available from version 9.14 🙇

**Comment by r2DoesInc** [comment]
The issue is that the app is not displaying an update and the web page doesnt show one available yet either.

You can use the following to download 9.14.1 directly for your os versions

https://dl.pstmn.io/download/version/9.14.1/win64
https://dl.pstmn.io/download/version/9.14.1/linux64
https://dl.pstmn.io/download/version/9.14.1/osx_64
https://dl.pstmn.io/download/version/9.14.1/osx_arm64

If thats not exactly it for your distro or you need another one you can fiddle with the urls,

**Comment by akshaydeo** [comment]
We are still rolling out 9.14 to all users. You will get an in-app notification as soon as its available for download.

Till then you can use web version of Postman to try this feature :).

**Comment by christianseel** [comment]
The "generation of documentation" is still only supporting OpenAPI 3.0, not 3.1. Is that correct? https://learning.postman.com/docs/publishing-your-api/documenting-your-api/#generating-api-documentation

We tested it and the UI is showing a warning "Documentation for the current API specification format is not supported.".

**Comment by ifbarrera** [comment]
Any update on when generated API documentation will support OpenAPI 3.1? Is there a new issue for that or should we continue to follow this issue?

**Comment by lougeo** [comment]
Any update on this? We require the ability to define webhooks which is part of the OAP 3.1 spec.

**Comment by nissen-chris** [comment]
@akshaydeo Would it be possible to reopen this issue or should rather a new Issue be created? 
When having a OAS 3.1 file the definition does not load for the boilerplate code. Should be easy to reproduce.

**Comment by shashankawasthi88** [comment]
@nissen-chris can you raise a different issue for the errors/ issues that you might be facing.
