### ISSUE TITLE
Updated to latest v8.3.0 but now reopening postman results in error screen when in scratchpad

### ISSUE THREAD

**Issue by harshvchawla** [a85/POSTMan-Chrome-Extension#9878]
**Describe the Issue**
When I reopen postman desktop app, I get this error if there were any opened (unsaved and saved - errors out for either/both) tabs while closing

**Steps to Reproduce**
1) Open any tab in scratchpad (not logged in) in postman desktop app
2) Close postman
3) Open postman
4) Error screen as shown in screenshot

**Screenshots or Videos**
![postman error - v8 3 0](https://user-images.githubusercontent.com/6857593/116357048-e4d24400-a7b0-11eb-8f6a-77cbf18fa5d7.png)

**Environment Information**
 - Platform Type: Desktop app
 - Postman Version: v8.3.0
 - Operating System: Windows 10

**Comment by spacecowgoesmoo** [comment]
Having the same problem here. Postman v8.3.0 desktop app, Mac OS 11.3. I've got two scratchpad tabs open all the time and whenever I launch Postman one of them displays the 'something went wrong' notice. The tab works fine after I close and reopen it.

**Comment by galmok** [comment]
I have the same problem. Is there any way to recover these tabs? They are crucial to my work!

**Comment by spacecowgoesmoo** [comment]
The recent update has fixed this for me. Thank you!
