### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by sawantamitb** [a85/POSTMan-Chrome-Extension#988]
The error is getting while executting collection and data passing by json format.
Range error, regular expression error message has displayed.

**Comment by abhijitkane** [comment]
Can you explain your problem better? A screenshot of the error would help.

Also, you can enable the console - http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/
Right click > Inspect element > Console
Do you see any error messages there?
