### ISSUE TITLE
Interceptor for Requests and Cookies is always disabled everytime Postman starts

### ISSUE THREAD

**Issue by OculiViridi** [a85/POSTMan-Chrome-Extension#9881]
### Description

First of all, I'm not sure this is an issue, because maybe it's a deliberate behaviour for reasons I don't know.

The problem is really simple to describe: **everytime I open Postman after a reboot of the PC**, a popup message appears on the bottom right corner of the app, saying:

![image](https://user-images.githubusercontent.com/42179710/116366158-496bbe00-a806-11eb-8062-42d3194ea122.png)

And so, I need to click on the Interceptor icon and set the `Capture Cookies` option to `ON`. Otherwise I can also open Chrome and enable it from the Extension panel, like this:

![image](https://user-images.githubusercontent.com/42179710/116366597-c1d27f00-a806-11eb-9b75-7044faa39b16.png)

I always close Postman with the option set to `ON`.
I've looked into Interceptor settings for any option but I didn't find anything. I've also read the online documentation but there's no mention about this.

I don't know what exactly means

> Looks like you switched workspaces...

### Steps to reproduce

1. Install Interceptor.
2. Enable Capture Cookies option.
3. Use Postman.
4. Close Postman.
5. Reboot the system.
6. Open again Postman.
7. See the popup message.

### Environment Information

 - Postman Version: 8.3.0
 - Operating System: Windows 10 20H2 build 19042.067

**Comment by geekerzhou** [comment]
+1

**Comment by elwaxoro** [comment]
+1
its a minor annoyance, but would be really nice as an option in preferences maybe? or go back to keeping previous state?

**Comment by OculiViridi** [comment]
The problem still persists on Postman v8.7.0.

**Comment by shashankawasthi88** [comment]
@OculiViridi @elwaxoro @geekerzhou is intended to safeguard users from accidentally capturing the traffic while restarting the app or switching the workspace. But as suggested we can look into adding preferences to allow this.

On this note though, we would like to understand what are the use case that you need to have 'capture the traffic' always?  If you could walk through why and how do you use the interceptor, it would help us design a better experience for you.

**Comment by OculiViridi** [comment]
> @OculiViridi @elwaxoro @geekerzhou is intended to safeguard users from accidentally capturing the traffic while restarting the app or switching the workspace. But as suggested we can look into adding preferences to allow this.
> 
> On this note though, we would like to understand what are the use case that you need to have 'capture the traffic' always? If you could walk through why and how do you use the interceptor, it would help us design a better experience for you.

@shashankawasthi88 I was using Interceptor to get auth cookies, necessary to be able to call the APIs I was implementing and testing. I'm on development of such APIs for several weeks per year, so it is a bit annoying to always have to open the panel and set the Cookies Interceptor to ON each time I need to use Postman. Of course, in my case, everything is done in a testing environment, so even if Interceptor is accidentaly left ON, then it wouldn't be a problem.

**Comment by akshaydeo** [comment]
@OculiViridi thanks for reporting this issue with us. One safer implementation we see here is - 

1. By default we keep cookie sync disabled.
2. But once changed, we will remember this decision across the reboots. 

I will update this ticket once we ship this feature.

**Comment by akshaydeo** [comment]
This is shipped with extension version 3.0.2.
