### ISSUE TITLE
Postman fails to generate Postman Collection for GraphQL

### ISSUE THREAD

**Issue by neglectedvalue** [a85/POSTMan-Chrome-Extension#9884]
Postman fails to generate collection for Postman Collection (from GraphQL) API.

**Steps to Reproduce**
1) Open Postman, go to your Workspace
2) Press import button
3) Select graphql schema file (see it in attachment)
[GraphQLSchema.schema.zip](https://github.com/postmanlabs/postman-app-support/files/6393321/GraphQLSchema.schema.zip)

4) Make sure 'Generate collection from imported APIs' checkbox is selected
5) Press import

Expected result: 
Importing finished without errors.

Actual result:
Import partially complete
Unable to generate collection for Postman Collection (from GraphQL) API.
1 API was imported.

**Screenshots or Videos**

https://s3.eu-central-1.amazonaws.com/texhnolyze/ShareX/2021/04/2021-04-28%2019-08-42.mkv

**Environment Information**

Postman for Windows
Version 8.3.0
win32 10.0.19042 / x64

**Additional Context**

Seems like problem is in graphql union (union FieldsUnion in my case) with large number of members, If I'm cutting union to 4 members - all works as expected.

**Comment by neglectedvalue** [comment]
Addition to the bug:
If you change subFields type from FieldsUnion to CompoundFieldInfoBase - all works fine.
FiledInfoGroup is a recursive structure and all other tools are fine with it (we are using apollo on a front-end side and Banana Cake Pop \ GraphQL Playground for testing). May be it will help in issue solving.
![изображение](https://user-images.githubusercontent.com/69389840/118873613-9e28c300-b8f2-11eb-80f7-406aa63bf557.png)

**Comment by umeshp7** [comment]
@neglectedvalue Thank you for reporting this. We have recently fixed this issue and you should now be able to generate collection from that GraphQL specification.

**Comment by DannyDainton** [comment]
Closing this issue as a fix was released in a previous version. If this is still an issue we can look at reopening the issue again.
