### ISSUE TITLE
I can not see 'Automatically persist variable values'

### ISSUE THREAD

**Issue by aakashsingh90** [a85/POSTMan-Chrome-Extension#9887]
**Describe the Issue**
I can not see 'Automatically persist variable values'

**Steps to Reproduce**
I can not see 'Automatically persist variable values'
I have Postman version Version 8.3.0 using it on mac

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/51633863/116457305-dd7a6b80-a880-11eb-82d7-d1d5590a2dd6.png)

**Environment Information**

 - Platform Type: Mac os
 - Postman Version: 8.3.0
 - Operating System: Mac OS Catalina

**Comment by DannyDainton** [comment]
This option was removed in version v8.0.8

> For enhanced privacy of your environment variable data, current values of variables no longer automatically persist to initial values when modified. You can still persist these values via the Persist All button in the variable edit screens

https://www.postman.com/downloads/release-notes/

**Comment by postman-staff** [comment]
### @aakashsingh90
Our team has filed another GitHub Issue ([3029](https://github.com/postmanlabs/postman-docs/issues/3029)) with our documentation repo to fix the discrepancy. This should align with what Danny has mentioned and what is currently posted on our docs.

via @asi-postman | Postman Support
