### ISSUE TITLE
Postman 8.3.0 can't use "Edit"

### ISSUE THREAD

**Issue by VincentChen1212** [a85/POSTMan-Chrome-Extension#9889]
Postman 8.3.0 can't use "Edit" Button to edit variable etc..
Click  collection is not work too.

**Comment by DannyDainton** [comment]
Hey @VincentChen1212 

Without more contextual information and a visual example of what you mean, it's going to be tough for us to take this any further.

**Comment by DannyDainton** [comment]
Hey @VincentChen1212 - As we haven't received more details for the issue, I'm going to close this one out.

We can look to open it again if more context and examples are provided.
