### ISSUE TITLE
Unable to set environment variable dynamically

### ISSUE THREAD

**Issue by NileshHindoliya** [a85/POSTMan-Chrome-Extension#9891]
Unable to  set/add environment variable from `Tests` after getting the API response.
That's what I'm doing:

```javascript
if (jsonData.accessToken != null) {
  pm.environment.set("accessToken", jsonData.accessToken);
  pm.environment.set("refreshToken", jsonData.refreshToken);
}
pm.test("hasTokenSet", function () {
  console.log(pm.environment.get("accessToken")); // undefined
  pm.expect(jsonData.accessToken).to.eql(pm.environment.get("accessToken"));
  pm.expect(jsonData.refreshToken).to.eql(pm.environment.get("refreshToken"));
});
```

Postman Version: `8.3.0`
Operating system: `macOS Big Sur`

**Comment by postman-staff** [comment]
Hey @NileshHindoliya

Thanks for reaching out. Happy to help.

I have tested your code assuming the jsonData is valid. It is working completely fine for me. Screenshots below :
 ![](https://postman.zendesk.com/attachments/token/IdrCJdKofL0J7SJHGL21fk0uN/?name=inline-850576479.png)​​
 ![](https://postman.zendesk.com/attachments/token/qn8iNxWtX4nh55xrdq9Whw3xj/?name=inline1090556988.png)​ Could you please confirm if the jsonData is fine here, using console.log(jsonData) once?

Will wait to hear back from you :)

via @VaishnaviChallaPostman | Postman Support

**Comment by NileshHindoliya** [comment]
When I was trying to add new variable (not from the json), in `hasTokenSet()`, it wasn't added either so I thought there maybe a problem in the latest release but apparently the problem was with json, after correcting it everything working fine. 

Thanks for pointing out

**Comment by postman-staff** [comment]
Awesome 😍​ Glad that it is working fine now! Thanks for letting me know.

I am closing this thread here, just for the time being. Please do feel free to reach out if there is anything else we can help!

Have a great day and thanks for using Postman! 👋​

via @VaishnaviChallaPostman | Postman Support
