### ISSUE TITLE
Workspaces are not being displayed after I restart postman 8.3.0

### ISSUE THREAD

**Issue by sandrapavankumar** [a85/POSTMan-Chrome-Extension#9893]
**Describe the Issue**

**Steps to Reproduce**

**Screenshots or Videos**

**Environment Information**

 - Platform Type: 
 - Postman Version:
 - Operating System:

**Additional Context**

**Comment by cdixon4** [comment]
I think I'm experiencing the same but all the ticket content is hidden due to the markup... if its filled out. 
https://github.com/postmanlabs/postman-app-support/issues/9914 @sandrapavankumar  does mine look the same?

**Comment by DannyDainton** [comment]
Hey @sandrapavankumar / @cdixon4  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
