### ISSUE TITLE
JSON response no longer beautify in new update

### ISSUE THREAD

**Issue by VictorAlagwu** [a85/POSTMan-Chrome-Extension#9894]
**Describe the Issue**
The JSON response is no longer beautify

**Steps to Reproduce**
Make a request using any API, that is expected to return a JSON formatted response, The pretty tab no longer displays beautify JSON formatted data 

**Screenshots or Videos**

Before Update:-
<img width="782" alt="Before Update" src="https://user-images.githubusercontent.com/15857679/116587636-8e7d1680-a912-11eb-9656-a5a734f0c1ea.png">

After Update:-
<img width="807" alt="After Update" src="https://user-images.githubusercontent.com/15857679/116587722-a2287d00-a912-11eb-80db-80c28b84acb8.png">

**Environment Information**

 - Platform Type: Mac
 - Postman Version: 8.2.3 (8.2.3)
 - Operating System: Mojave 10.14.6

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @VictorAlagwu 

That looks like you're using a mock server, the example request would need the `Content-Type: application/json` header too.

**Comment by VictorAlagwu** [comment]
Actually @DannyDainton it's not a mock server (The first screenshot is an example of a request made in the previous version)

I did as you said, but same issue 
<img width="685" alt="Screenshot 2021-04-29 at 5 55 54 PM" src="https://user-images.githubusercontent.com/15857679/116589372-7a3a1900-a914-11eb-8db1-52982ec140f3.png">

**Comment by DannyDainton** [comment]
The `before Update` Image, is from an _example request_ and not an actual main request. You can see that by how the _Status Code_ is displayed in the image.

Can you check the **response** headers to see if the correct header is coming through for the request, that will determine how the data is displayed.

Do you have an example request that we can run locally? It's difficult to see exactly what is happening with a cropped down image of the whole app window.

**Comment by VictorAlagwu** [comment]
Thanks @DannyDainton 
It's resolved, I just restarted my laptop..and everything is back to normal
<img width="501" alt="Screenshot 2021-04-29 at 6 12 37 PM" src="https://user-images.githubusercontent.com/15857679/116591346-9ccd3180-a916-11eb-8206-b366af830f98.png">
