### ISSUE TITLE
New Integration Request - Mercado Libre

### ISSUE THREAD

**Issue by fernadodemitropulos** [a85/POSTMan-Chrome-Extension#9895]
It would be great to have a complete integration with MercadoLibre

**Comment by shashankawasthi88** [comment]
@fernadodemitropulos Can you please add more details about your exact use case and how you believe the Integration would help you achieve it?

**Comment by shashankawasthi88** [comment]
Closing this for now. @fernadodemitropulos feel free to re-open by adding more details.
