### ISSUE TITLE
Name is not valid error on trying to make a workspace public

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9896]
**Describe the Issue**

Public workspace converts special and space character to - in the constructed public url , this causes test-test and test@test to be resolved to the same url . So if a public workspace with name test-test exists then user cannot create workspace with name test@test.

The error message just says workspace name is not valid, no other helpful message

**Steps to Reproduce**

1.  Create a workspace test test and make it public
2.  Create a new workspace test#test make it public ; Invalid workspace name error is thrown

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/45095911/116631671-64951580-a94d-11eb-94f3-c377cb468bbc.png)

**Environment Information**

 - Platform Type:   web and desktop
 - Postman Version:    8.3.0
 - Operating System: win32 10.0.19042 / x64

**Comment by akshay-kulkarni-03** [comment]
@praveendvd thanks for reporting this we are actively working on fixing this issue and provide an update in next couple of weeks once we have identified the RCA and fix for the same.

**Comment by akshay-kulkarni-03** [comment]
@praveendvd we have fixed this issue! Would request you to use the latest version of the app if you're using standalone app!
