### ISSUE TITLE
Warn when trying to use `Referer` header

### ISSUE THREAD

**Issue by jwarkentin** [a85/POSTMan-Chrome-Extension#990]
I just wasted a bunch of time trying to figure out why the `Referer` I set with Postman wasn't showing up. Finally I Googled and found #384 which indicates that Chrome simply doesn't allow it. It would save others the wasted time to simply display a warning when someone tries to use the `Referer` header indicating that it will not work.

**Comment by a85** [comment]
Sorry about this. Postman can send restricted headers using the Postman Interceptor extension: https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo/related. You will need the packaged app for this. You can get it from www.getpostman.com

**Comment by jwarkentin** [comment]
Ah, that's very good to know. Thanks! It is probably still a good idea to add a notice of some sort to tell users that they need the interceptor extension to use the header.

**Comment by a85** [comment]
Yep. It comes in the packaged app: https://www.dropbox.com/s/q9qlynhj2pm7ddm/Postman_interceptor_header.png?dl=0 

We are working on a new UI for this and the experience will be much better.

**Comment by heylucky** [comment]
oh, no! I just spent 2 days to find out this problem. Referer won't be sent which contained in headers,it was no allowed by Chrome, no wonder i can't get my correct  responses. sad....... and forgive my poor English

**Comment by sdnts** [comment]
@heylucky You should be able to use the native apps to send a Referrer header. Native apps can be downloaded [here](https://getpostman.com/apps)

**Comment by paulisfluent** [comment]
Is this still an issue?  I have similarly been baffled why setting `Referer` hasn't made it through to my app.

I am using Postman for Windows 7.36.0 -- I think this is the "native app" @madebysid ?  I can see no warning (which would have been enough to highlight the issue):
![image](https://user-images.githubusercontent.com/18393158/100843993-1d285d00-3473-11eb-9b46-2cc8066b0edb.png)
