### ISSUE TITLE
Code snippet does not resolve collection variable for examples

### ISSUE THREAD

**Issue by odonnell-anthony** [a85/POSTMan-Chrome-Extension#9900]
**Describe the Issue**

Generated code snippets do not resolve variables from Collection for examples

**Steps to Reproduce**

1. Set request base URL in collection variables
2. Use variable in request URL
3. Send request and save example
4. Click on example saved
5. Click on </> button to open Code Snippet
6. Base URL variable is not resolved

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/42035917/116793666-f58bfe00-aabf-11eb-8105-258f8c2f93e9.png)

![image](https://user-images.githubusercontent.com/42035917/116793648-e016d400-aabf-11eb-8a80-9381787a7b27.png)

![image](https://user-images.githubusercontent.com/42035917/116793691-1ce2cb00-aac0-11eb-9035-430af700459b.png)

![image](https://user-images.githubusercontent.com/42035917/116793495-f8d2ba00-aabe-11eb-85d7-d2a70322be4c.png)

**Environment Information**

 - Platform Type:  Desktop Application
 - Postman Version: 8.3.0
 - Operating System: Windows 10

**Comment by DannyDainton** [comment]
This issue has been fixed in the latest version of the platform.
