### ISSUE TITLE
OAuth2 customize http headers for access token request

### ISSUE THREAD

**Issue by keenser** [a85/POSTMan-Chrome-Extension#9902]
**Is your feature request related to a problem? Please describe.**
OAuth2 authorization token request uses _Accept: \*/\*_ http header. In my case IDP uses xml as default response format. As result OAuth2 authorization does not work for me as expected.

**Describe the solution you'd like**
Add option to modify http headers for access token request

**Describe alternatives you've considered**
Currently I use pre-request script as workaround:
```javascript
var token_time = pm.environment.get("token_time");
console.log('token expires in:', (token_time) ? new Date(token_time) : 'now');
if(!token_time || token_time <= Date.now()) {
    if (pm.environment.has("idp_username")) {
        var body = 'grant_type=password'
            + '&username=' + pm.environment.get("idp_username")
            + '&password=' + pm.environment.get("idp_password");
    } else {
        var body = 'grant_type=client_credentials';
    }
    pm.sendRequest({
        url: 'https://' + pm.environment.get("ip") + ':' + pm.environment.get("port") + '/token',
        method: 'POST',
        header: {
            'Content-Type': 'application/x-www-form-urlencoded',
            'Accept': 'application/json'
        },
        auth: {
            type: 'basic',
            basic: {
                username: pm.environment.get("idp_client_id"),
                password: pm.environment.get("idp_client_secret")
            }
        },
        body: {
            mode: 'raw',
            raw: body
        }
    }, function (err, res) {
        pm.environment.set("access_token", res.json().access_token);
        pm.environment.set("token_time", Date.now() + res.json().expires_in*1000);
    });
}
```

**Comment by mancave** [comment]
Looks like the same feature #10008

**Comment by abhijeetborole** [comment]
Hey @keenser! Thank you for the patience! We’ve added the ability to customise your OAuth2,0 requests with Postman v10.13.
This is available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests. You can also add query params to the auth request.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)

If you have any Audience and Resource parameters, you can move them to the new editors with the Move Audience and Resource button.

![MoveAudAndResFlow](https://user-images.githubusercontent.com/9638586/232850201-59d30590-d7c7-41c1-94c7-9a1c77f1757b.gif)


Do let us know if you have any issues.

P.S. - For refresh parameters, these will be stored with the token and any changes will only be considered when you generate a new token

Postman app v10.13 is being rolled out will be available for everyone in couple of days
