### ISSUE TITLE
I lost all of my postman collections today

### ISSUE THREAD

**Issue by snehi23** [a85/POSTMan-Chrome-Extension#9903]
I opened the request with support which has most of the details.

https://support.postman.com/hc/en-us/requests/74421

But in summary, I could not able to find my collections after the new postman upgrade (Version 8.3.0 (8.3.0)).
I keep on getting Connection Error if I want to sync with the cloud server. Please help.
<img width="1428" alt="Screen Shot 2021-05-03 at 9 23 25 AM" src="https://user-images.githubusercontent.com/5720497/116904472-9549a900-abf2-11eb-8f87-6ebe18cf5f9e.png">

OS: Mac

**Comment by jcolemn3** [comment]
I had the same issue. I went back version 8.2.2 only to be upgraded to the new 8.3 version on restart. I then have to go back and reinstall the older version to get my workspace.

**Comment by postman-staff** [comment]
Hi @jcolemn3

Sorry to see you are not able to view your collections after update.

If you are still facing the same issue then we would like to investigate further. Could you open a new ticket on our support channel using this link - https://www.postman.com/support/ please? Also, do add this GitHub issue number and your GitHub username in the request description to make it easy for us to track.

We will wait to hear back from you on our support channel.

via @Swapnil-getpostman | Postman Support

**Comment by vanqard** [comment]
I too had this issue. I lost all of my previous work when switching to offline mode, which I did because the connection error icon kept bugging me.

Should I open a (duplicate) support ticket too? Or will this ticket get updated with the outcome? 

App: Version 8.3 
OS: macOS Big Sur 11.3

**Comment by postman-staff** [comment]
@vanqard  It would be really helpful if could file a new request from our support portal using this link -https://www.postman.com/support/, as it will be secure communication between you and our support engineers in case we require any log files, other details for further troubleshooting.

via @Swapnil-getpostman | Postman Support

**Comment by postman-staff** [comment]
Hi there,

I hope all is well! Just wanted to follow up on my previous message - is there anything else I can do to help you?

I am closing this ticket now, simply reply to this thread to reopen the ticket and let me know if you have any further questions - I'd be happy to address them!

via @Swapnil-getpostman | Postman Support
