### ISSUE TITLE
frequent logout from postman app

### ISSUE THREAD

**Issue by ahsas5** [a85/POSTMan-Chrome-Extension#9905]
**Describe the Issue**
 Everytime I try to use postman or in few mins after login, I automatically get logout & need to login again.

**Steps to Reproduce**
 login
after login. keep idle
again logout automatically 

**Screenshots or Videos**

**Environment Information**

 - Platform Type: MAC native app
 - Postman Version:
 - Operating System:MAC OSX

**Additional Context**

**Comment by postman-staff** [comment]
Hey hi,

Thanks for reaching out to Postman Support. Sorry that you are facing issues while using Postman --- Happy to help.

Could you please check our web version if you are seeing the same behaviour - go.postman.co ?
If the Web Version works, I'd first recommend to check if your work is synced, please check the below links


- All Collections: https://go.postman.co/me/collections
- All Environments: https://go.postman.co/me/environments

Please find the below guide to do a complete clean re-installation
-> https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

This issue should generally resolved by renaming the Postman installation folder.
Please give it a try and let us know it goes.

If that doesn't work, do give our Canary build a try and let us know if that helped: https://postman.com/downloads/canary

Looking forward to your response!

via @Lincimary | Postman Support

**Comment by ghost** [comment]
@ahsas5 Sorry for the inconvenience that you faced. I need few details from you before I can help you with the issue.

Could you tell me:
1. What version of Postman are you on?
2. How have you performed login? Google, Password etc
3. Do you sign in to postman app using web browser?
3. Do you uncheck `Keep me signed in`?

**Comment by postman-staff** [comment]
Hi @ahsas5,

Could you please let us know if you were able to re-install the desktop app successfully after renaming the postman folders?

Let me know if you still need any assistance from us.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @ahsas5,
Hope you are doing fine!

Just letting you know I’m still here so feel free to give me a shout if you’re still running into any issues.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @ahsas5,

Just letting you know that I'm going ahead and closing this conversation. If you still need help, just respond to this ticket to re-open it. Otherwise, please feel free to reach out again later!

Have a great day:)

via @Lincimary | Postman Support
