### ISSUE TITLE
Postman hangs when editing  environment variable in the (in the environment tab ) that  contains long content like json schema

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#9906]
**Describe the Issue**

When trying to edit the content of environment variable  (**in the environment tab** )the UI hangs 

**Steps to Reproduce**

Create an environment variable with large content, like json schema

Try editing it the content

**Screenshots or Videos**

NA : 

**Environment Information**

 - Platform Type:   Both web and Desktop
 - Postman Version:  v8.3.1 
 - Operating System: Win 10

**Additional Context**

It would be great to have a  separate window to edit environment variables with large content

**Comment by kamalaknn** [comment]
Duplicate of #9014
