### ISSUE TITLE
Default User-Agent header is outdated

### ISSUE THREAD

**Issue by kazbeel** [a85/POSTMan-Chrome-Extension#9907]
**Describe the Issue**

Every request attach the header User-Agent with "PostmanRuntime/7.28.0" regardless Postman's version.

**Steps to Reproduce**

- Open up Postman 8.x
- Create a new GET request where URL is "https://httpbin.org/headers".
- Check the response: headers -> User-Agent.
- You will see "PostmanRuntime/7.28.0"

**Screenshots or Videos**

N/D

**Environment Information**

 - Platform Type: MacMini
 - Postman Version: 8.3.0
 - Operating System: macOs Catalina

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @kazbeel

That is the current version of the Postman runtime:

https://github.com/postmanlabs/postman-runtime

This does not follow the same versioning as the main app build.
