### ISSUE TITLE
In collection runner after the tests is finished the load circle still load

### ISSUE THREAD

**Issue by hanyghazal** [a85/POSTMan-Chrome-Extension#991]
In collection runner after the tests is finished the load circle still load, and I opened the chrome inspector to see what happened and I see

1- in the console after run the requests in the collection, I got error in console "Uncaught TypeError: undefined is not a function"

2- after the request, I got request "app_error" with url : https://www.getpostman.com/app_error with response 200 and the response of this request is 

{"error":true,"result":"Invalid access token","code":"INVALID_TOKEN"}

**Comment by a85** [comment]
Are you still seeing this issue?
