### ISSUE TITLE
Collection pre-request script not run

### ISSUE THREAD

**Issue by galmok** [a85/POSTMan-Chrome-Extension#9912]
Using version 8.3.1

Pre-request script from the collection is not run.

1. Create collection. 
2. Add pre-request script to collection, e.g.:
  var apikey = pm.environment.get('apikey');
  pm.request.headers.add({key: 'X-Api-Key', value: apikey })
3. Add request.
4. Add necessary environment variable, apikey and assign a value.
5. Run request.
6. Watch as request has no X-Api-Key header attached, not even without value.

 - Platform Type: windows 10
 - Postman Version: 8.3.1
 - Operating System: windows 10

**Comment by DannyDainton** [comment]
Hey @galmok 

Would you be able to provide a visual example or a short recording of what you're seeing, please?

I've not been able to recreate the issues with those steps.

**Comment by galmok** [comment]
I just tried but now it worked. But honestly, I tried many times prior to writing this ticked and it just didn't work, but now it does. I guess we can close this ticket.
