### ISSUE TITLE
After upgrade to 8.3.1 can't view requests

### ISSUE THREAD

**Issue by zburk** [a85/POSTMan-Chrome-Extension#9913]
**Describe the Issue**

After upgrading to 8.3.1 (not sure what the prior version was), when I click a request to view its details, it stays blank and nothing loads. If I can an example, nothing happens. If I click the 3 dots and add an example, then the panel updates and I can add a new example.

**Steps to Reproduce**

Open Postman and try to access any request

**Screenshots or Videos**

![Screen Shot 2021-05-06 at 3 35 27 PM](https://user-images.githubusercontent.com/5782327/117355525-b1627a00-ae80-11eb-8be6-649ee51d7d83.png)

**Environment Information**

 - Platform Type: macOS 11.4 beta
 - Postman Version: 8.3.1
 - Operating System: Mac

**Additional Context**

**Comment by postman-staff** [comment]
Hey @zburk,

Thanks for reaching out. Sorry that you are facing issues while using Postman --- Happy to help.

I have tried replicating this issue, but works fine for me.

Could you please check our web version if you are seeing the same behaviour - go.postman.co ?

If the Web Version works, I'd first recommend ensuring your work is synced: https://go.postman.co/me/collections before trying the following:
-> https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-
You'll want to try the steps to remove local data. As mentioned previously, please make surer to pay attention to the **Requirements** section before deleting anything just to make sure your work is synced.

Once that's done, I'd recommend re-installing the Postman App.

Hope this helps. Please let me know if you have any further queries or this is not what you are looking for. Will be more than happy to help!

Looking forward to your response :)
via @VaishnaviChallaPostman | Postman Support

**Comment by zburk** [comment]
Cleared the local data and re-installed and it works now. Thanks!

**Comment by postman-staff** [comment]
Awesome!

Thanks for letting us know :)

Please feel free to reach out again later if you have any queries. Will be more than happy to help!

Have a great day!


via @VaishnaviChallaPostman | Postman Support
