### ISSUE TITLE
"Something went wrong error" on 8.3.0 Postman launch- workspaces can't be selected- Windows 10

### ISSUE THREAD

**Issue by cdixon4** [a85/POSTMan-Chrome-Extension#9914]
**Describe the Issue**
On Postman desktop app 8.3.0 using Windows 10 app launch displays a something went wrong error. 
![image](https://user-images.githubusercontent.com/83786087/117356891-e4553f80-ae79-11eb-91a1-5e13d0ec07bb.png)

Then when clicking view all workspaces and trying to select a workspace the app doesn't respond- it doesn't recognize the click event. I also tried using the workspaces dropdown to select the workspace but still no luck. 
![image](https://user-images.githubusercontent.com/83786087/117357007-077fef00-ae7a-11eb-954d-6aee09746367.png)

**Steps to Reproduce**
1. On Windows 10 PC login to Postman. 
2. Update App version. 
3. Launch app- workspaces do not show. 

**Screenshots or Videos**
Screenshots above

**Environment Information**
 - Platform Type: Postman for Windows - desktop application
 - Postman Version: 8.36.0 win 32 10.0.19042/ x64
 - Operating System: Windows 10

**Additional Context**
Postman details 
![image](https://user-images.githubusercontent.com/83786087/117357035-11a1ed80-ae7a-11eb-95c2-94c8a746cea5.png)
From teammate Matteo, this same version of Postman is also nonfunctional from his Windows 10 but **works** on his mac.

**Comment by postman-staff** [comment]
Hi @cdixon4

Sorry to see you are experiencing issues accessing your workspaces.

It would be really helpful if could file a new request from our support portal using this link -https://www.postman.com/support/, as it will be secure communication between you and our support engineers in case we require any log files, other details for further troubleshooting.

Meanwhile, to get you unblocked could try accessing "Postman on Web" using any of the below links and see if that helps? It has the same UI & features as that of the desktop app and I know you will like it.

- http://go.postman.co/
- http://web.postman.co/

We will wait to hear back from you on our support channel.

via @Swapnil-getpostman | Postman Support

**Comment by postman-staff** [comment]
Hi All,

I hope all is well! I just wanted to follow up on my previous message - is there anything else I can do to help you?

I am closing this ticket now. Simply reply to this thread to reopen the ticket and let me know if you have any further questions - I'd be happy to address them!

via @Swapnil-getpostman | Postman Support
