### ISSUE TITLE
Postman v8.x - Cannot run collection offline

### ISSUE THREAD

**Issue by chatelao** [a85/POSTMan-Chrome-Extension#9915]
Situation
- Due to security restrictions we are not allow to connect Postman to the Internet.
- Up to Version 7 it was no problem at all to run collections from ".csv" files.

Problem
- Since Version 8, the very same option is not available anymore.

![image](https://user-images.githubusercontent.com/2461532/117402131-1dd38c80-af06-11eb-8969-84f2970213fa.png)

**Comment by DannyDainton** [comment]
Hey @chatelao

Is the `Run` option in the Collection tab or the `Runner` option on the menu at the bottom right of the app window also not active?

The `Run Collection` option was never part of V7 so this could be a different issue.

**Comment by chatelao** [comment]
Perfect, thank you!
