### ISSUE TITLE
Feature Request: expose request name variable

### ISSUE THREAD

**Issue by darrylkuhn** [a85/POSTMan-Chrome-Extension#992]
Is there a way to pass the request name (i.e. the name I've given the request in a collection) up via a header request parameter? I'm using postman for test automation and collecting code coverage. Having the request name would allow me to tie coverage details to specific requests (right now the best I can do is Method and URI)

**Comment by abhijitkane** [comment]
No, short of hard-coding it, there's no way you can pass the request name in the header. We're looking at ways to expose the request metadata (request/folder/collection name) in the pre-request script and test script environments.

**Comment by darrylkuhn** [comment]
Understood - if you need a tester for the feature or I can provide assistance let me know.
