### ISSUE TITLE
Download environment should be easily accessible

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#9920]
**Is your feature request related to a problem? Please describe.**
It is very hard and not intuitive how to download an environment.

**Describe the solution you'd like**
The download environment should be part of the menu (see below).

![image](https://user-images.githubusercontent.com/1197635/117690992-b47ca380-b1bb-11eb-81d6-7a6fb34077ef.png)

Currently, users have to go completely somewhere else to download the environment.

**Comment by DannyDainton** [comment]
Hey @vdespa 

This looks like a similar feature request 

https://github.com/postmanlabs/postman-app-support/issues/9608

**Comment by vdespa** [comment]
Agreed, thanks for linking that.
