### ISSUE TITLE
Postman 8.3.0 - tab names unreadable

### ISSUE THREAD

**Issue by wabiloo** [a85/POSTMan-Chrome-Extension#9921]
**Describe the Issue**
With the new design (in 8.3 I believe), the tab names almost completely disappear if a few tabs are open. Hovering over them does not reveal the name. There is no menu / button to show the list of tabs open either

**Steps to Reproduce**
Open multiple tabs (eg. multiple requests)

**Screenshots or Videos**
![Screenshot 2021-05-10 at 19 26 05](https://user-images.githubusercontent.com/4056263/117706819-ac296600-b1c5-11eb-9866-f6d9d2911ab7.png)

**Environment Information**
 - Platform Type: Mac
 - Postman Version: 8.3.1
 - Operating System: Mac

**Comment by chris-torruella** [comment]
Hey @wabiloo, exciting news! ⭐
We've just introduced Tab Search, a new step in our journey to improve tabs UX and management at Postman. Now, you can easily read the entire name of all your opened tabs, regardless of their number.

**What's New:**
1. Dropdown display with all of your tabs.
2. Recently closed section for easy recovery.
3. Search bar for quick tab access.
4. Moved "Close all tabs" options to right-click tab menu to gain more tab bar space.

![demo](https://github.com/postmanlabs/postman-app-support/assets/120389184/ca1ed227-5cc2-45bd-9577-28197bed31f5)

Give it a try and let us know what you think. Your feedback is key to help us taking Postman to the next level! 🚀
