### ISSUE TITLE
PR merge loses query param descriptions and inactive query params

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#9922]
**Describe the Issue**

When a pull request is merged from a fork back into the source, requests are missing query param descriptions and inactive query params after the merge.

**Steps to Reproduce**

1. Collection with requests with query params with descriptions and inactive query params exists.
2. Fork collection.
3. Make change to request path, e.g., add or remove "/version" from the path.
3. Create pull request, approve, and merge from fork back to source.
4. Inspect requests in merged destination for missing query param descriptions and missing inactive query params.

**Screenshots or Videos**

Source collection example request:
![source](https://user-images.githubusercontent.com/7584863/117728337-2e059900-b19e-11eb-8c64-c09cb7b269ff.png)
Forked, same request:
![fork](https://user-images.githubusercontent.com/7584863/117728350-31992000-b19e-11eb-9c88-0299ab49f08a.png)
Merged, same request:
![merged](https://user-images.githubusercontent.com/7584863/117728362-352ca700-b19e-11eb-8d11-e08de77f1423.png)

**Environment Information**

 - Platform Type: Mac desktop
 - Postman Version: Version 8.3.1 (8.3.1)
 - Operating System: macOS 11.3

**Additional Context**

This did not happen with all of the requests in the collection. Requests that were created by duplicating an existing request and then modifying to meet my needs were not affected. The original request was affected, but the duplicate was not.

**Comment by ankit-m** [comment]
Hi @watchwithjames,

Thank you for the detailed description about the issue. I was able to reproduce this behaviour. I'ved filed it on our internal tracker. I will update this thread when the fix is released.

**Comment by ankit-m** [comment]
Hi @watchwithjames,

The fix for this bug is deployed. Please reopen this ticket if you are still facing the issue.
