### ISSUE TITLE
Import OAS3: Referenced response descriptions are missing

### ISSUE THREAD

**Issue by savage-alex** [a85/POSTMan-Chrome-Extension#9923]
Given the following openAPI definition that is imported to postman, the descriptions of the responses is missing:
https://app.swaggerhub.com/apis/AdvancedComputerSoft/example-pet-inventory/1.0.5
![image](https://user-images.githubusercontent.com/25430683/117776185-2d6b1200-b233-11eb-8d86-635ab4692a3c.png)
This API definition uses referenced responses for error conditions so I assume its to do with how Postman importer is resolving these. 
Reason why I believe this is when importing the "full resolved" version of the API (available via export/download api/ json or yaml fully resolved is that then the descriptions show successfully 
![image](https://user-images.githubusercontent.com/25430683/117776537-9a7ea780-b233-11eb-8130-108f7aa9cc10.png)

Thanks

**Comment by VShingala** [comment]
@savage-alex Currently we are not supporting remote references inside the definition. All local references should work fine. We already have a similar issue here - https://github.com/postmanlabs/postman-app-support/issues/8827. We will post any future updates there meanwhile I will be closing this issue as a duplicate.
