### ISSUE TITLE
"Create New" option in the Home page is not routed to the correct screen, instead it is routed the current open window/workspace.

### ISSUE THREAD

**Issue by Pricilla09** [a85/POSTMan-Chrome-Extension#9928]
**Describe the Issue**
In the "Home" page the "Create New" link is not routed as expected. It is supposed to land on the "New" options page, but this is landing in the previously working workspace/request tab.

**Steps to Reproduce**
1. Login to Postman
2. Navigate to the "Home" page.
3. Under "Start with something new" tab, click "Create New" option.
4. 

**Screenshots or Videos**
https://user-images.githubusercontent.com/71498483/117987226-dbc6a280-b36c-11eb-96b2-33e19a4bee22.MP4

**Environment Information**

 - Platform Type: Desktop application
 - Postman Version: Version 8.3.1
 - Operating System: Win 10

**Additional Context**
When clicking the "Import file" option in Home page is routed correctly to the import options under the workspace. This "Create New" link is also expected to work like the same.
-->

**Comment by mccannt** [comment]
This should now be resolved.

**Comment by Pricilla09** [comment]
Yes, this is working fine now :-)
