### ISSUE TITLE
UI - Make Postman Packaged App supports Full screen mode option (F11)

### ISSUE THREAD

**Issue by rajatharya** [a85/POSTMan-Chrome-Extension#993]
I am using Chrome version 41.0.2272.118 m and Windows 7. 
Postman Packaged App is not respecting full screen mode option (F11)

**Comment by emigre** [comment]
I use OSX and Postman doesn't seem to have a "full screen" keyboard shorcut here. If you press in its top-left  green zoom button it does enter full screen normally, though. But a keyboard shortcut would be a nice thing to have, I usually prefer to enter full screen that way.

**Comment by a85** [comment]
Mac app available at www.getpostman.com/apps. Should fix all chrome platform related issues.
