### ISSUE TITLE
Change environment variable live while hovering variable in request

### ISSUE THREAD

**Issue by ColdCerealAtWork** [a85/POSTMan-Chrome-Extension#9931]
![2021-05-12 15_09_46-Postman](https://user-images.githubusercontent.com/45828766/118050905-fd0b9c80-b334-11eb-859d-b10af74b5f39.png)
**Is your feature request related to a problem? Please describe.**
As a user who has to use environment variables extensively for security reasons, it is a pain to have to hunt down variables in the environment view to change them. It slows my work down tremendously.

**Describe the solution you'd like**
When I hover a variable with my cursor in the url a window opens that shows me the value. I'd like to ability to change the value live in that window. That feature being added to the body of the request would be even better.

**Describe alternatives you've considered**
- Sorting/searching in the environment view.
- a new environment search window somewhere that can be accessed quickly

**Comment by skatikia** [comment]
@ColdCerealAtWork Sorry to be so late in posting an update, but I bring good news!

With Postman V11.14, we have rolled out several updates to our variable interface, including the ability to update variable values on the fly. Just hover on a variable to view its value, edit it and hit Send.

![edit-value](https://github.com/user-attachments/assets/7c5387d3-3987-4108-a9e8-9f64d81c078f)

Additionally, **we're introducing a variables pane that lets you view all the variables in a request in a single place** and nudges you when there are empty variables.

Click on the button next to the environment selector to bring up the variables pane and control all the moving parts of a request, a.k.a. variables, without hopping around.

![variables-pane](https://github.com/user-attachments/assets/055e939d-64e6-4b34-a37c-2465065a1c42)

I hope you like these changes as much as we do! Update your app to start working with those changes and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
