### ISSUE TITLE
No encoding is specified after content type, and it is not UTF-8

### ISSUE THREAD

**Issue by Corey956** [a85/POSTMan-Chrome-Extension#9932]
I try to use raw in body to specify JSON

this is json

``` json
{
    "comment": "test",
    "triggerCommand": "",
    "tslVersion": "{\"condition\":{\"powerSwitch\":\"1.0.0\",\"volume\":\"1.0.0\"},\"action\":{\"guardSensitivity\":\"1.0.0\"}}",
    "itemAction": "{\"guardSensitivity\":\"0\"}",
    "itemCondition": "{\"and\":[{\"==\":[{\"var\":\"powerSwitch\"},\"1\"]},{\">\":[{\"var\":\"volume\"},50]}]}"
}
```

![image](https://user-images.githubusercontent.com/52793589/118075308-57166b80-b3e2-11eb-9026-ea46ca3704a3.png)
But it can't be requested

|  JSON parse error: Unexpected character ('\' (code 92)): expected a valid value (number, String, array, object, 'true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('>' (code 92)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')| at [Source: (PushbackInputStream); line: 1, column: 2] 

I determined by positioning that it is > cannot be escaped

But when I change the content type to application / JSON; Charset = UTF-8, can be requested. Isn't UTF-8 the default in content type?

Because I see that you have modified this problem in version 8.3.0. In the past, you used to specify UTF-8 directly

**Comment by postman-staff** [comment]
Hi there,

Thank you for writing in. It would be great if you can send the screenshot that covers both the error and the payload of the request.

via @ | Postman Support

**Comment by postman-staff** [comment]
Hi,

We haven’t heard back from you on the requested information, if this is still an issue then kindly provide us more information.

Thanks!

Regards,
Asha Singh

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by Corey956** [comment]
This is the request body
``` json
{
    "Liu": "{\"guardSensitivity\":\"0\"}",
    "testTwo": "{\"and\":[{\"==\":[{\"var\":\"powerSwitch\"},\"1\"]},{\">=\":[{\"var\":\"volume\"},50]}]}"
}
```
and this is headers
![image](https://user-images.githubusercontent.com/52793589/120772899-5e4d1700-c553-11eb-81ca-658b05722156.png)

Return value

``` json
{
	"code": "200",
	"message": "success",
	"data": null
}
```

But now in the picture Content-Type amend to read this
![image](https://user-images.githubusercontent.com/52793589/120773339-d7e50500-c553-11eb-8ea1-3d7f57707ff6.png)

is return value 500 and this 
![image](https://user-images.githubusercontent.com/52793589/120773624-167abf80-c554-11eb-8c0b-70124c8d092a.png)

**Comment by postman-staff** [comment]
Hi,

Apologies for the delayed response and thanks for providing the requested information. We have tried the flow from our end and it seems to be working fine. If I have understood the question right then you are asking if Postman is supposed to automatically set the charset to UTF-8 and the answer is No for this.

Let me know if this clarifies, happy to assist you further with any follow-up questions.

via @ash007-postman | Postman Support

**Comment by Corey956** [comment]
If the default is not UTF-8, what is the default encoding format of postman's raw request JSON format？

**Comment by postman-staff** [comment]
Sorry for the delayed response. We have raised this internally to the respective team. I Will update you as soon as I have more information on the reported query.

Thank you!

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi,

We have tried sending a request to postman echo (https://learning.postman.com/docs/developer/echo-api/ ) with your body data and there is no issue parsing the JSON body provided. Can you please check if you can reproduce this for Postman Echo API?

It would be great if you can share your endpoint so that we can test the same from our end. You can provide these details via https://postman.com/support

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi,

We haven’t heard back from you. As requested before can you try sending a request to postman echo and let us know if you are able to reproduce the issue.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi,

Just letting you know that I'm going ahead and closing this conversation. If you still need help, just respond to this ticket to re-open it. Otherwise, please feel free to reach out again later!

Have a great day!

via @ash007-postman | Postman Support
