### ISSUE TITLE
Postman v8.3.1 JSON is not beautified anymore ¿?

### ISSUE THREAD

**Issue by thmasker** [a85/POSTMan-Chrome-Extension#9933]
**Describe the Issue**
I just updated to v8.3.1, and JSONs are not formatted anymore. Even trying to write one does not launch autocomplete functions or anything like that. Colours have also been lost.

**Screenshots or Videos**
![Screenshot 2021-05-13 at 12 57 40](https://user-images.githubusercontent.com/43535391/118116751-f4759d80-b3ea-11eb-955d-355a4364813b.png)

**Environment Information**
 - Postman Version: 8.3.1
 - Operating System: macOs Catalina 10.15.7

**Comment by DannyDainton** [comment]
Hey @thmasker 

It's a little difficult to know which part of the app that you're showing that JSON in - Could you update the image showing the full app window, please?

I'm currently seeing this:

![image](https://user-images.githubusercontent.com/17089546/118118019-3d762380-b3e4-11eb-96b4-26cb843ef008.png)

**Comment by thmasker** [comment]
Apparently, it is solved now. I guess it got stuck or something like this. Thanks!
