### ISSUE TITLE
Error when generating collection from OpenAPI Specification

### ISSUE THREAD

**Issue by amatmv** [a85/POSTMan-Chrome-Extension#9936]
**Describe the Issue**
I'm getting an error when generating a collection from an API I imported from a OpenAPI 2.0 schema.

**Steps to Reproduce**
- Import the swagger schema from https://api-docs.connectif.cloud/swagger.json
- Try to generate a Collection from this API

**Screenshots or Videos**
----------------------

![image](https://user-images.githubusercontent.com/11032995/118258494-34eb1f00-b4b0-11eb-91db-ca82d2353b3b.png)
----------------------------
</br>

![image](https://user-images.githubusercontent.com/11032995/118258633-6b289e80-b4b0-11eb-8d09-80cb70fd9431.png)

**Environment Information**

 - Platform Type: Postman Web
 - Postman Version: v8.4.0
 - Operating System: Ubuntu 20.04

**Additional Context**

**Comment by VShingala** [comment]
@amatmv Thanks for reporting the issue. We are working on a fix and will update the thread once it's fixed.

**Comment by VShingala** [comment]
@amatmv This issue is now fixed with the latest postman app v9.1.2.
