### ISSUE TITLE
Variable values being silently shortened with 3 dots in final collection json

### ISSUE THREAD

**Issue by ysee-mma** [a85/POSTMan-Chrome-Extension#9937]
I have a dozen collection variables with a long multiline json in them. Sometimes they got silently cutted without any explanation.

Steps to reproduce:
1. Save long variable value
2. Go to any request tab
3. Enter some characters in the url field
4. select this characters and save it as a collection variable

Actual result: new variable added, All long variables cutted and all it saved.

![image](https://user-images.githubusercontent.com/8360097/118389460-4bca7680-b654-11eb-9499-28d8007dc4d9.png)

 - Postman Version: Postman for Windows Version 8.4.0 win32 10.0.19042 / x64
 - Operating System: Win10, Ubuntu

**Comment by postman-staff** [comment]
Hello @ysee-mma
Thank you for flagging the behaviour you observe on your end

I tried replicating the same behaviour on my end, however, it seems that I was able to send a rather long variable.

May I ask if you face the same behaviour when using environmental variables?

Can you also make sure that you are setting the **Current Value** of the variable before sending the request - as this is the value that will get picked if you are manually sending the request?

Looking forward to your response

via @nasco-a | Postman Support

**Comment by ysee-mma** [comment]
The problem is not with sending variable. Here is the gif.

![postman bug long variables](https://user-images.githubusercontent.com/8360097/118491725-79451c00-b749-11eb-8ada-eda64013dc9d.gif)

So after that I exporting collection and all long variables are shortened and so it broken. Currents values are fine , but they are not exporting.

PS. The bug is not reproducible if you setting Global variable. It is a Collection variable that is caused a problem

**Comment by postman-staff** [comment]
Hello @ysee-mma,
Thank you for the update

Thanks a lot for providing a gif I was able to replicate the same behavior.
I will check the issue internally with our team and provide you with an update

Once again many thanks for all the details shared by you, apologies for any inconvenience caused

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @ysee-mma,
I hope that you are doing great.

I'm just letting you know that since the issue was actively reproducible I have raised it to our engineering team and they already started their investigation.

Many thanks for flagging this to our attention - apologies for the inconvenience caused

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @ysee-mma,
I hope that you are doing great.

Many thanks for your patience, and all the provided details regarding the issue you are facing.

Our engineering team has released a fix to the reported issue in the latest version of Postman (8.6.0)

Can you try updating Postman and then attempt to reproduce the same behavior?

- **Postman** -> **Settings** -> **Update** -> **Check ****for ****updates**

I already tested it on my end, and it seems like the issue has been fixed and the variables are not getting trimmed, but I just wanted to check with you as well.

via @nasco-a | Postman Support

**Comment by ysee-mma** [comment]
Thank you for the fix, it is working perfect with the new version!

**Comment by postman-staff** [comment]
@Hello ysee-mma,
I hope that you are doing great.

Since we haven't heard from you in a while, and I have tested the behaviour and the issue it seems to be fixed,I will go ahead and mark this ticket as **Closed**

If any further questions or issues arise, please do not hesitate to reach us back at any given time.

via @nasco-a | Postman Support
