### ISSUE TITLE
Auto-closed meta elements are not rendered correctly

### ISSUE THREAD

**Issue by rspilker** [a85/POSTMan-Chrome-Extension#994]
In the pretty view of the result the meta elements that are not explicitly close either by /> or by &lt;/meta> still increase the indentation level. But meta elements are specified to not need explicit closing.

**Comment by abhijitkane** [comment]
@rspilker Are you still seeing this in v3.0.4?

**Comment by rspilker** [comment]
I don't know how to see the version number. I am using a v3. Just tested it. My reproduction recipe:
- "Send" a GET without any headers etc. to `https://github.com/postmanlabs/postman-app-support/issues/994#issuecomment-121942004`
- Look at the resulting Body in Pretty view.

Most of the `<meta>` tags on that page are not closed, resulting in increased indentation levels. Actually, the same goes for all the `<link>` tags, that also don't need closing.

![meta-tags-and-link-tags-indent](https://cloud.githubusercontent.com/assets/93318/8729708/f5753948-2bec-11e5-92cc-4f24ad1ca2bc.png)

**Comment by a85** [comment]
The bug still exists. Probably due to an issue with the pretty printer.

**Comment by abhijitkane** [comment]
Have fixed in the vkbeautify library and will push in 3.2.9.
