### ISSUE TITLE
Import feature for graphql broken

### ISSUE THREAD

**Issue by arghyaiitb** [a85/POSTMan-Chrome-Extension#9941]
**Describe the Issue**
Import feature from cURL is not working when we try to import any graphql request. It is imported as a regular request with the graphql

**Steps to Reproduce**
- Create a simple graphql query request
- Get the curl request
`curl --location --request POST 'localhost:8080/abc' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n    }\n}","variables":{}}'`
- Now import the graphql request from `Raw text` tab, putting the content generated above.
- You would see the request getting imported as normal post request with the content being added as a text body

Following are the issues
- The import request is not getting added into the proper graphql tab
- The request imported as request body is also not working properly. For example `\n` is converted to `n` which ultimately gives syntax error

**Screenshots or Videos**
![Untitled](https://user-images.githubusercontent.com/12271033/118462531-636d3200-b71c-11eb-8810-e26f810c63a2.gif)

**Environment Information**

 - Platform Type: Web/Desktop
 - Postman Version: All
 - Operating System: Any OS

**Comment by umeshp7** [comment]
@arghyaiitb Thanks for reporting this. 

We have noted this internally and will be tracking this. There is no way to clearly identify that its a GraphQL request just using the cURL command unless we look into the content. We can try to _guess_ that its a graphql request by parsing the content of the `data-raw`. Currently the data-raw of curl command is mapped to a Raw body in Postman.

Having said that, its definitely a feature worth having and we will track this internally as a feature request. :)

**Comment by aman-v-singh** [comment]
Hey @arghyaiitb,
This feature will be available in the Postman App July 2023 Release.
