### ISSUE TITLE
OPENSSL path issue in POSTMAN 

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#9942]
While enabling post man proxy **capture request** it show's an error **"Could not find openssl on your system on this path : openssl"** 
i install openssl in my C drive and also added environment varibale and run command of openssl it;s work but postman capture request still getting this errors.
![postman iisue](https://user-images.githubusercontent.com/61722997/118485192-bd2e2600-b735-11eb-8ced-83f2b8fa017a.png)

**Comment by shashankawasthi88** [comment]
Hi, @mrjijo did you restart the Postman app post the OpenSSL installation? Also, can you confirm if you can see the following directory in your system - %APPDATA%\Postman\proxy (It usually points to C:\Users<user>\AppData\Roaming\Postman\proxy)

**Comment by ghost** [comment]
i resolved this issue by 
installing openSSL for 32 and 64 both , my system is 64 but after install 32 and set environment varible , and restart my PC it works .
![Screenshot 2021-05-23 000540](https://user-images.githubusercontent.com/61722997/119237493-bef35180-bb5a-11eb-9549-33c7ab782bc5.png)

**Comment by ghost** [comment]
> Hi, @mrjijo did you restart the Postman app post the OpenSSL installation? Also, can you confirm if you can see the following directory in your system - %APPDATA%\Postman\proxy (It usually points to C:\Users\AppData\Roaming\Postman\proxy)

Thanks for reply .
