### ISSUE TITLE
@ encoding to %40

### ISSUE THREAD

**Issue by ricardomcifba** [a85/POSTMan-Chrome-Extension#9945]
Hi everyone.
I am using Postman to test my program, bum, when i sending my email to login, Postman encoding my email. Resulting in thsi error
error_description": "[401] during [GET] to [http://hr-user/users/search?email=rickmc123%40gmail.com]

**Comment by DannyDainton** [comment]
Hey @ricardomcifba 

In order for us to know what's happening here, we would need you to expand on the information provided.

Please complete the issue template and include all the relevant details:

```
**Describe the Issue**
<!--
A high-level summary or description of the problem that you're facing.
-->

**Steps to Reproduce**
<!--
A list of steps that can be followed to recreate the issue.
-->

**Screenshots or Videos**
<!--
Please add screenshots or a short video to help visually explain the problem. 
Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 
-->

**Environment Information**

 - Platform Type: 
 - Postman Version:
 - Operating System:

**Additional Context**
<!--
Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
-->

```

**Comment by DannyDainton** [comment]
Hey @ricardomcifba  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
