### ISSUE TITLE
Feature Request: Provide an option to adjust app font size

### ISSUE THREAD

**Issue by kpowick** [a85/POSTMan-Chrome-Extension#995]
It would be nice if there was a _zoom_ option for the application font size.  Personally, I find the font size a bit too small for comfortable reading.  Yes, I am old(er).

**Comment by kpowick** [comment]
Closed as duplicated by #979

**Comment by michaeltarleton** [comment]
I'm using the Mac Packaged App and I've found the UI/Response font size settings but is there a way to adjust the font size of the left bar or the request body?

I changed the UI to bigger and response font size to 16 which helps but I need to also change the font size of the request body.
