### ISSUE TITLE
The "Save request" popin should show more collections at a time

### ISSUE THREAD

**Issue by BlueInt32** [a85/POSTMan-Chrome-Extension#9952]
**Is your feature request related to a problem? Please describe.**
I have several collections (about 15), and when I want to save a new request into one of the existing collections, the size of the select window shows only 3 collections at a time, while there is plenty of space available to show at least 6 at a time. I am forced to chose one of them to save the request, so I am forced to scroll in a tiny select window. This is quite frustrating.

**Describe the solution you'd like**
It would be way less frustrating to have at least 6 to 10 collections visible in that select component. For example, the description textarea is very big but I never use it (moreover it's optional), it could be smaller. There is also a lot of whitespace and "help" text that eat up a lot of vertical space.

**Describe alternatives you've considered**
Searching across the collections is a bit irrelevant because there are not that many, and suggests I know their name. I would start using search text field in a list of more than 20 probably.

**Additional context**
![image](https://user-images.githubusercontent.com/2920038/118977903-f903fe00-b976-11eb-9988-58a6df31e86e.png)

Sorry I can't find the About menu to know which version of postman I am using. All I know is that it's the free desktop app on Windows 10.

**Comment by DannyDainton** [comment]
Hey @BlueInt32 

We have just released version 8.5.0 which has various improvements for the `Save Request` feature. Would you be able to update the app version and see if that addresses your feature request, please?

**Comment by BlueInt32** [comment]
Indeed, the new version is way better, thanks !
