### ISSUE TITLE
Support for -X GET -d (for Elasticsearch, etc.)

### ISSUE THREAD

**Issue by naterkane** [a85/POSTMan-Chrome-Extension#996]
Elasticsearch requires data to be sent along with GET requests for many operations.

```
$ curl -XGET /cars/transactions/_search?search_type=count -d '
{
    "aggs" : { 
        "colors" : { 
            "terms" : {
              "field" : "color" 
            }
        }
    }
}'
```

**Comment by abhijitkane** [comment]
This is a Chrome limitation - you can't add a body to GET requests. We're looking at ways to work around this though.

**Comment by fjcero** [comment]
@naterkane From the Elasticseach documentation

> Both HTTP GET and HTTP POST can be used to execute search with body. Since not all clients support GET with body, POST is allowed as well.

http://www.elastic.co/guide/en/elasticsearch/reference/1.x/search-request-body.html

I've been using sense a while and this seems to be a recommendation when trying to hit Elasticsearch with chrome: https://github.com/bleskes/sense. The official support for this extension was moved to Marvel, but you could use the extension loading it with Developer Mode.

**Comment by abhijitkane** [comment]
Chrome app platform restriction - cannot include a body with GET requests

**Comment by naterkane** [comment]
Maybe this shouldn't have been built within the Chrome sandbox so it could have utilized curl or something similar _shrugs_
