### ISSUE TITLE
UrlEncoding of char %

### ISSUE THREAD

**Issue by spudcz** [a85/POSTMan-Chrome-Extension#9961]
I have to communicate with API that has feature to filter data by dynamic query sent in querystring parameter where. One of the posibility to filter is using LIKE

GET <API_URL>?where={"name":{"$like":"%search%"}}
![image](https://user-images.githubusercontent.com/15734023/119118639-b7348f80-ba2a-11eb-891f-3f3cdad349b0.png)

This query above is encoded by Postman however only double quotes are encoded (%22) but the percentage characters are not.

GET https://api.someurl.com/?where={%22name%22:{%22$like%22:%22%search%%22}}

Expected behavior is that encoded url should contain %25 instead of percentage chars like this:

GET https://api.someurl.com/?where={%22name%22:{%22$like%22:%22%25search%25%22}}

To achieve the expected behavior I have to write manually %25 in Postman GUI to queryparam value
![image](https://user-images.githubusercontent.com/15734023/119119397-7426ec00-ba2b-11eb-8e7e-00f33daf7968.png)

**Environment Information**

 - Platform Type: x64
 - Postman Version: v8.5.0
 - Operating System: Windows 10

**Comment by shamasis** [comment]
We've spent a while deciding the appropriate approach for this considering all use cases and this is the best-fit compromise that was something that works for most cases. I will let @codenirvana expand more on this.
