### ISSUE TITLE
0New Integration Request - <product name>

### ISSUE THREAD

**Issue by JudaristFullstackProCoder** [a85/POSTMan-Chrome-Extension#9963]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
Please reopen by adding more details to the ticket!
