### ISSUE TITLE
Follow link only works 1 time in a tab

### ISSUE THREAD

**Issue by rdorris** [a85/POSTMan-Chrome-Extension#9965]
Running a post which returns some json that includes a link. Clicking the link the first time opens a new tab as it should. Rerunning the post in the first tab creates new json with a new link, but clicking on that link no longer opens a new tab.

**Steps to Reproduce**
Perform a post in tab, results show a link.
Click on link to open 2nd tab. Close 2nd tab.
Perform post in 1st tab to get new json data/link
Click on link - does not open another tab.

**Environment Information**

 - Platform Type: Windows
 - Postman Version: 8.5.1
 - Operating System: Windows 10, 21H1

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @rdorris 

I've not been able to replicate this issue with the step that you have provided, are you able to share a short recording of this happening in the app, please?

**Comment by NickBarrett** [comment]
I believe this is what @rdorris is experiencing. It is certainly the problem we have.

https://user-images.githubusercontent.com/2435714/119407537-78f3e480-bd38-11eb-860f-ed9002e1f93d.mp4

Hope that helps =)

**Comment by rdorris** [comment]
This is the exact issue. Thanks for posting the recording.

**Comment by NickBarrett** [comment]
This seems to be fixed in 8.7.0

**Comment by shubhbhargav** [comment]
Closing this off as the fix has been verified in the above comment.
