### ISSUE TITLE
Certificate generation doesn't work on Windows properly

### ISSUE THREAD

**Issue by QuAzI** [a85/POSTMan-Chrome-Extension#9966]
Looks like value for -subj should be double quoted because of spaces. Even manually I can't run it.

```
C:\Users\rusla\AppData\Roaming\Postman\proxy\certificates>"c:\Program Files\OpenSSL-Win64\bin\openssl.exe" req -new -sha256 -subj /C=US/ST=CA/L=San Francisco/O=Postman Inc./OU=Postman/CN=Postman Proxy CA/emailAddress=info@getpostman.com -key C:\\Users\\rusla\\AppData\\Local\\Temp\\3f35b1296f3b2da15c233c36c0f5b01c8b8e9a75
req: Use -help for summary.
```

as a result no certificates present
![image](https://user-images.githubusercontent.com/1897605/119258086-e127b680-bbd0-11eb-9c19-0c9cddc1d2e3.png)

**Comment by shashankawasthi88** [comment]
@QuAzI I am assuming that you are trying to generate the certificate to use the Proxy functionality of Postman. You don't really need to generate the certificate as such. Can you follow the steps [here](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/#windows) to install the certificate?

**Comment by QuAzI** [comment]
I solved it for me but in general will be fine to fix it.
Also installed perl can invoke troubles with his broken version of openssl. So right version of OpenSSL in `%path%` should be before perl. 
Now I am stuck on [IIS interaction](https://community.postman.com/t/use-postman-as-proxy-from-iis-app-timeouts/24012)

**Comment by DannyDainton** [comment]
Hey @QuAzI 

It looks like you have solved this issue 🎉  - I'm going to close this one out for now.
