### ISSUE TITLE
Packaged app without additional Chrome window

### ISSUE THREAD

**Issue by espen** [a85/POSTMan-Chrome-Extension#997]
I normally don't use Chrome but since Postman is so awesome I launch Chrome just to use it. I use the packaged app and it is great to be able to launch just the app, however when I open Postman Packaged App there is also another Chrome window "open". Well there is not really any window but it is visible in the dock and when tabbing. Is there a setting to disable this or is it a Chrome Package App "feature"?

**Comment by abhijitkane** [comment]
No, this can't be disabled. The Chrome process has to be open for any of its apps to load. We're looking at ways to get around this, but till we're restricted by the Chrome platform. Will keep this thread updated.

**Comment by a85** [comment]
There does not seem to be any change in sight. We'll be releasing a native Mac app soon. Email us at help@getpostman.com to get the beta link if you are on OS X.
