### ISSUE TITLE
Reset All button in the scope of Variables Concept isn't functioning

### ISSUE THREAD

**Issue by shoglu** [a85/POSTMan-Chrome-Extension#9971]
**Describe the Issue**

**Steps to Reproduce**

**Screenshots or Videos**

**Environment Information**

 - Platform Type: 
 - Postman Version:
 - Operating System:

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @shoglu - Not sure what happened here but could you update your issue with the relevant details, please?

**Comment by shoglu** [comment]
@DannyDainton Hey Danny, I am closing this, since the issue is no longer exists.
