### ISSUE TITLE
New Integration Request - <Dear Inventory>

### ISSUE THREAD

**Issue by jimmyvadera** [a85/POSTMan-Chrome-Extension#9975]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by jotsarup** [comment]
@jimmyvadera thanks for reaching out. Can you please provide more details
