### ISSUE TITLE
Search does not show all matching collections

### ISSUE THREAD

**Issue by smaeder** [a85/POSTMan-Chrome-Extension#9977]
This is a very late bug report - several versions back, the UI of the Postman app on Mac OS was updated, and the search began not showing all matching collections, and instead only a few.

I save lots of templated requests in Postman with auth headers for various customers, and there are too many to scroll through to find what I am looking for quickly, so I relied upon search to see a list of requests available by customer name. Now that only up to 2 results show when searching, I frequently am not able to get what I was looking for.

Is this known and being worked on?

**Comment by DannyDainton** [comment]
Hey @smaeder 

Just so we're talking about the same thing, do you mean the Filter on the Collections sidebar or the Universal Search feature at the top of the app?

Would you be able to provide an example of what you're seeing and the version/platform you're using, please?

**Comment by smaeder** [comment]
Hi Danny,

Thanks so much for your reply and trying to clarify my request.

I did not even know about the filter on the collections sidebar. That is exactly what I was needing, and it works as I was expecting the "Universal Search" to work. Several versions back, the "universal search" box worked as this collections sidebar filter works now, so that was the way I had always used it, and when it changed, it was a "who moved my cheese?" moment.

So the collections sidebar filter 100% meets my need - thank you - you may close the issue or replace with my UI suggestion below.

Perhaps the UI could be made more clear? Here's my suggestion:
[Graphical user interface  Description automatically generated]

Stephen Maeder
Senior Product Manager
Commerce & Fulfillment
www.ingrammicrocommerce.com<https://www.ingrammicrocommerce.com/>

From: Danny Dainton ***@***.***>
Date: Wednesday, May 26, 2021 at 11:11 AM
To: postmanlabs/postman-app-support ***@***.***>
Cc: Maeder, Stephen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [postmanlabs/postman-app-support] Search does not show all matching collections (#9977)

Hey @smaeder<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smaeder&d=DwMCaQ&c=--1RjWWBW4Kf6aBAaj53vPItwfT0BR1YjSDV46P5EvE&r=tFNq3qjBxI-P6mSRZ1LS1D3Wmxqc0KgT4iXkcxDH2mA&m=JgPnBa_5DDlwiKlanB-EC29MvW_ozP8Us9tRZef84jY&s=besxCIo3TTqTumrXXGHFML9y7GW_o3wQkkznl1LQ048&e=>

Just so we're talking about the same thing, do you mean the Filter on the Collections sidebar or the Universal Search feature at the top of the app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_postmanlabs_postman-2Dapp-2Dsupport_issues_9977-23issuecomment-2D848905729&d=DwMCaQ&c=--1RjWWBW4Kf6aBAaj53vPItwfT0BR1YjSDV46P5EvE&r=tFNq3qjBxI-P6mSRZ1LS1D3Wmxqc0KgT4iXkcxDH2mA&m=JgPnBa_5DDlwiKlanB-EC29MvW_ozP8Us9tRZef84jY&s=jrOXGv3K0yW3uLXq1r4kJ67TG7CTzBNMPxvSvpD6IQU&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AELMVJ6VJTBJ2LJQQUDLD63TPUMTRANCNFSM45SLYN2Q&d=DwMCaQ&c=--1RjWWBW4Kf6aBAaj53vPItwfT0BR1YjSDV46P5EvE&r=tFNq3qjBxI-P6mSRZ1LS1D3Wmxqc0KgT4iXkcxDH2mA&m=JgPnBa_5DDlwiKlanB-EC29MvW_ozP8Us9tRZef84jY&s=_eTVKz3JSg3RJqtTWhhX0YCQj1l24sJiWVGK8-TlnOQ&e=>.

If you do not wish to receive promotional materials from Ingram Micro via e-mail, please go to Our unsubscribe link<https://pc2.mypreferences.com/IngramMicro/?PGID=IM_EMEU_OPTDOWN&LocaleID=en_US> and select your Country and Language Preference to unsubscribe.

Ingram Micro Inc.
Corporate Headquarters, 3351 Michelson Drive, Suite 100, Irvine, CA 92612

This email may contain material that is confidential, and proprietary to Ingram Micro, for the sole use of the intended recipient. Any review, reliance or distribution by others or forwarding without express permission is strictly prohibited. If you are not the intended recipient, please contact the sender and delete all copies.
[Ingram_2818e5de]

**Comment by DannyDainton** [comment]
Thanks for confirming and telling us that the Collection filter fulfils your usecase.

I'll close this one out 🎉
