### ISSUE TITLE
Cookies are not being set on request return

### ISSUE THREAD

**Issue by minamassoud** [a85/POSTMan-Chrome-Extension#9979]
**Describe the Issue**
after sending an authentication request, localhost/sanctum/csrf-cookie, we expect some cookies to be set but non is set and the request returns correctly with headers set-cookie: {cookie} 

**Steps to Reproduce**
have a vanila laravel with sanctum library
send the request /sanctum/csrf-cookie
request returns with 204 no content and headers set-cookie: #####
the cookies on posman are empty 

**Screenshots or Videos**
<img width="1434" alt="Screen Shot 2021-05-27 at 2 18 24 PM" src="https://user-images.githubusercontent.com/26849271/119825379-2b71a600-bef7-11eb-8446-19cfd3808585.png">
<img width="1440" alt="Screen Shot 2021-05-27 at 2 20 44 PM" src="https://user-images.githubusercontent.com/26849271/119825386-2e6c9680-bef7-11eb-8110-b23d8e427a89.png">

**Environment Information**

 - Platform Type: postman for macos
 - Postman Version: 8.5.1
 - Operating System: macos - Big Sur 11.3.1 (20E241)

**Comment by codenirvana** [comment]
@Mina-R-Meshriky can you share the complete `Set-Cookie` string (response header)?

**Comment by minamassoud** [comment]
@codenirvana, you mean that:

`XSRF-TOKEN=eyJpdiI6IndiYmpCdTJ6Q1QyR09YWnhybGNXc3c9PSIsInZhbHVlIjoiV3NsaWY3SEtvTWtFNE1mNVIyYVFNQjJsc0ltWFgxVjZVbGQ2dnlIQ1grK1FKWlE1UXlzdkowSTdzSXAzbEZuSkZtTDJxY2xsN3R4NVhFd0ZtNkNGN2tFT0p2eGgyUnpoWFZGb1dBSll2QUhXYjF4RGljZjBZQy9iSWNkdEl5Zy8iLCJtYWMiOiJmNzU2MTQ0YjZhZGU2MDU4MTBkMWY1MWM5NDM0N2Y3MjYzMzhjMmUxMzc4NTU0MGU5YmZmN2VjZTg0ZmI4YjZjIn0%3D; expires=Mon, 31-May-2021 10:39:45 GMT; Max-Age=7200; path=/; domain=.http://127.0.0.1:8000; samesite=lax`

**Comment by codenirvana** [comment]
This issue is with the `domain` attribute, it must not include the `http://` protocol and should match the request hostname.

**Comment by minamassoud** [comment]
yup the problem was in the domain indeed.

the request: was `curl --location --request GET 'http://127.0.0.1:8000/sanctum/csrf-cookie' \` 

However, I removed the `http://` and there was also an extra `.`, I also removed that and the cookies were not set as well
but when I removed the `domain=` completely it worked

`XSRF-TOKEN=eyJpdiI6InlMN3hRdlBCbUhMUGgxekVicXNScVE9PSIsInZhbHVlIjoicHpjanRHcm5MTU5Tc1ZnM0lUaGtqNkkwaG5UQS9kNlNjT0I5QjJxa0J5NkNieUFwWVhJVDI4NytnVjNCMjV0dWhOL1J5TXEwYWlIQTdNYUc4bk5SK2dmdUVLNzg3WFdQbzhzem04TUZ5cHRsWWwxRFdFTTNwYkFwM2VWVTI1NTUiLCJtYWMiOiJlNDViYTI3OGFkZTc1ZWY5MGMxYjZhYjA3YTU3ODY1MTU1MTNjM2FjMDllODljMzkwMGE4NzIyMzQ5ZGFmNGFlIn0%3D; expires=Mon, 31-May-2021 11:27:48 GMT; Max-Age=7200; path=/; samesite=lax`
