### ISSUE TITLE
inSync doesn't retrieve Globals and 

### ISSUE THREAD

**Issue by am-bloombees** [a85/POSTMan-Chrome-Extension#998]
Thank you for this great func.. but I am experiencing several probelms since I started its use.
1. When I logout and I log-in inSync retrieves all folders and requests but some time the requests appear out of its folders (spending time to reorganize them)
2. Globals always appears empty and I have to fill again each time.

**Comment by abhijitkane** [comment]
@am-bloombees - Can you share your username/email ID?

**Comment by a85** [comment]
We are handling Sync issues through our support helpdesk at help@getpostman.com. Closing this for now.
