### ISSUE TITLE
Add direct support for Faker.js module in Postman

### ISSUE THREAD

**Issue by mikayelgr** [a85/POSTMan-Chrome-Extension#9980]
**Is your feature request related to a problem? Please describe.**
When the developers are creating a authentication back-end, it's not always easy to create fake users to interact with. They have to do it manually and waste their time on doing meaningless things instead of focusing on the main problem.

**Describe the solution you'd like**
I would like to see the integration of a popular JavaScript module: [Faker.js](https://github.com/marak/Faker.js/), in Postman as a built-in module that we could use in our test scripts/pre-request scripts like this

```js
const faker = require("faker");
// ...
```

**Describe alternatives you've considered**
The only alternative solution that I considered is to do everything manually which is not really effective and it's really time-consuming

**Additional context**
None

**Comment by DannyDainton** [comment]
Hey @MichaelGrigoryan25

There is a subset of that module built-in to the app. You should be able to use `{{$randomEmail}}`, for example, in your requests.

The full list of what is currently available can be found here:

https://learning.postman.com/docs/writing-scripts/script-references/variables-list/

**Comment by mikayelgr** [comment]
Hi @DannyDainton

Yeah, I understand that there are parts of Faker.js built-into Postman, but I don't really find it effective to use it with the current way

```javascript
pm.variables.replaceIn('{{$randomFirstName}}')
```

When instead I can do

```javascript
faker.name.findName();
```

In my opinion this is a much cleaner way of doing it. 

What do you think?

**Comment by DannyDainton** [comment]
I don't believe, in the short term at least, that it's going to be changing from the way you would access those values now but I'm also not the person who would make that call either. 😁

Are you only using it that way in a pre-request script? 

The values can also be directly used in the URL, Params, Headers and Request Bodies.

**Comment by mikayelgr** [comment]
Okay! I'm closing this issue then, have a good day 🙂
