### ISSUE TITLE
Postman crashes on entering Non Iso character in sockets request header.

### ISSUE THREAD

**Issue by HamzaAnis** [a85/POSTMan-Chrome-Extension#9983]
**Postman crashes on entering Non Iso character in sockets request header.**

**Steps to Reproduce**

1. Create a new `WebSocket Request".
2. Enter the socket link to connect
3. Select the headers tab
4. Enter the non-ISO-8859-1 character in either the key and value. (  …  <= example input, it is )

**Screenshots or Videos**

https://user-images.githubusercontent.com/18266623/119973739-49a9d580-bfcd-11eb-9a44-dad477cd27ac.mov

**Environment Information**

 - Platform Type: OSX
 - Postman Version: Version 8.5.1 (8.5.1)
 - Operating System: OSX

**Additional Context**

**Comment by appurva21** [comment]
@HamzaAnis Thanks for reporting this! 

I am able to reproduce the issue at my end. We'll take a look at this and soon rollout a fix for the same.

**Comment by timbochamp** [comment]
This should now be addressed on Postman for Web, and has been added to our next app release! Please feel free to reopen if you're still encountering the issue on the web client or next v8.7.0 app version once released
