### ISSUE TITLE
Low contrast on error counter label

### ISSUE THREAD

**Issue by josebsanchez** [a85/POSTMan-Chrome-Extension#9984]
**Describe the Issue**
Black text with a dark background is very difficult to read.

**Steps to Reproduce**
1. Open console tab.
2. Make a request that results in an error. i.e: Error: read EADDRNOTAVAIL
3. Observe the text between the error icon and the logs dropdown filter is very difficult to read due to its low contrast. ❌ 

**Screenshots or Videos**
<img width="1789" alt="Screen Shot 2021-05-28 at 10 32 37 AM" src="https://user-images.githubusercontent.com/22062869/120001101-73e59e00-bfa1-11eb-854e-41e7e1b9d95a.png">

**Environment Information**

 - Platform Type: Mac
 - Postman Version: Version 8.5.1 (8.5.1)
 - Operating System: macOS Big Sur v11.3.1

**Additional Context**

**Comment by timbochamp** [comment]
Thanks for the report! We have a fix in progress for this and will report back when it's addressed

**Comment by parthverma1** [comment]
Hi @josebsanchez. 
The issue is fixed and not reproducible as of version: 9.31.18

Please let us know if you still think this is a bug.
