### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by JohnGilmore100** [a85/POSTMan-Chrome-Extension#9985]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by jotsarup** [comment]
@JohnGilmore100 thanks for reaching out. Can you please provide more details
