### ISSUE TITLE
Could not send request Parse Error: Expected dot

### ISSUE THREAD

**Issue by neeraj-nss** [a85/POSTMan-Chrome-Extension#9988]
I am able to access the API without burp suite and successfully getting the response as well. When I use the burp proxy and send the request to the server the server responds to the burp i can see the output in the burp proxy tool the response not showing in the postman tool. Always saying the "Could not send request Parse Error: Expected dot view in console" when i see the console i do not get any error message except "Error: Parse Error: Expected dot".

![image](https://user-images.githubusercontent.com/78147163/120108234-e57c4280-c181-11eb-83d8-6b023e26575d.png)

![image](https://user-images.githubusercontent.com/78147163/120108184-b239b380-c181-11eb-90d0-bdccf9d0a1bc.png)

Can you please check and help me to resolve the issue. I checked this on the v8.3.0 and v8.5.1.

**Comment by codenirvana** [comment]
@neeraj-nss it looks like the proxy is responding with an invalid HTTP response.

`Expected dot` happens if the response starts with an invalid HTTP major/minor version like `HTTP/11.1 200 OK` instead of `HTTP/1.1 200 OK`.

**Comment by neetech18** [comment]
Thank you for response.

Any working solutions for this issue. Do i need to make changes in Burp proxy tool or in postman.

Thanks.

**Comment by neeraj-nss** [comment]
Thank you for response.

Any working solutions for this issue. Do i need to make changes in Burp proxy tool or in postman.

Thanks.

**Comment by codenirvana** [comment]
@neeraj-nss Since you mentioned that API is accessible without the proxy so I feel there's some misconfiguration on the Burp proxy side (or response is altered incorrectly).

**Comment by neetech18** [comment]
Yes. you are right, The issue was with server response it was giving me "HTTP/2 200 OK" and postman was expecting "HTTP/1.1 200 OK". I just change the value in the proxy response from 2 to 1.1 and postman was showing the output. 

Just wanted to know if we can change this value in Postman Desktop application. We can resolve this issue permanently.

I suppose as of postman supports HTTP/1.1. (v8.5.1)

**Comment by neetech18** [comment]
After disabling the below HTTP/2 option from burp, now working fine.

![image](https://user-images.githubusercontent.com/12570891/120463189-4772bd00-c3b9-11eb-937a-9fdc49349da0.png)
