### ISSUE TITLE
Html Report: Test results should be grouped by iteration

### ISSUE THREAD

**Issue by youranwj** [a85/POSTMan-Chrome-Extension#999]
I have a collection which should be executed with a data file. In the Newman command output, there are 5 iterations in one run, but in the Html report (which was generated by "-H"), it shows only 1 iteration, and all test results are shown in one list.

Notes: there are several tests in Test Script part, and the key of some tests contains dynamic info which means the key may be same or different in each iteration.

![image](https://cloud.githubusercontent.com/assets/10199565/7077017/5c66da26-dec2-11e4-81a8-d6b60a02c59c.png)

**Comment by DannyDainton** [comment]
Hey @saswatds 

Should we transfer this issue over to the HTML reporter or Newman repo?

Or maybe look to close it as there are alternative reporters out there which can handle this request. 😄

**Comment by DannyDainton** [comment]
Closing this issue. The reporter has its own repository.

https://github.com/postmanlabs/newman-reporter-html
