### ISSUE TITLE
WebSocket subprotocol supporting error in response

### ISSUE THREAD

**Issue by SerzhSergeev** [a85/POSTMan-Chrome-Extension#9997]
**Describe the Issue**

WebSockets are supporting subprotocol functionality, and for now it looks like there is no supporting of that with request that sending by clicking on `Connect` button in Postman.

For sure we can add subprotocols in Headers, and Postman will successfully send it to your server. Server will response with supporting list of subprotocols (or will choose one of them) and if both sides supporting same protocols (or one of them) you still will get error: ```Error: Server sent a subprotocol but none was requested```

**Steps to Reproduce**

1. Create a server with few of supported subprotocols
2. Add WebSocket request that content  subprotocols or one of them in Header
3. Add Basic Authorization (not sure, in this bullet but this exist in my case)
4. Connect to Server

After authorization will be successful, you will get ```Error: Server sent a subprotocol but none was requested``` on step ```Status Code: 101 Switching Protocols``` with interesting fact - response header from Server will have `Sec-WebSocket-Protocol`, and `Sec-WebSocket-Accept` with `Connection:upgrade`.

**Environment Information**

 - Postman Version: Version 8.5.1 (8.5.1)
 - Operating System: MacOSX

**Comment by codenirvana** [comment]
Subprotocols are not supported yet, we are currently working on it and will update here once we make any progress.

@SerzhSergeev can you share the subprotocol you are trying to connect with?

**Comment by prabhakarj13** [comment]
@codenirvana  a please add a support for subprotocols: `graphql-ws` websocket in postman

**Comment by SerzhSergeev** [comment]
@codenirvana thanks for feedback!
Sure, from my side here they are:
- ocpp1.6
- ocpp2.0
- ocpp2.0.1
- graphql-ws

**Comment by immohellwig** [comment]
Same with v12.stomp

**Comment by mtaylorSF** [comment]
require support for `graphql-ws` as well.  thank you in advance.

**Comment by appurva21** [comment]
Hey folks! 

We have enabled support for subprotocols in the latest release. With this, you should now be able to use the `Sec-WebSocket-Protocol` header to negotiate the subprotocol with the server.

![image](https://user-images.githubusercontent.com/24985700/123251329-b484f880-d508-11eb-98cc-927ddd1bfb40.png)

We are also actively working on adding dedicated support for few of the common subprotocols and will provide the updates here once we have something.

**Comment by osharaki** [comment]
Awesome! I can now connect with `v12.stomp` as the desired subprotocol. The only thing I'm missing right now is the how to add the [null octet](https://stomp.github.io/stomp-specification-1.2.html#STOMP_Frames) after the message body in the STOMP frame.

**Comment by mtaylorSF** [comment]
Thank youu, `graphql-ws` is working in 8.7.0

**Comment by aang13** [comment]
Hi @osharaki, did you able to make it work?

> Awesome! I can now connect with `v12.stomp` as the desired subprotocol. The only thing I'm missing right now is the how to add the [null octet](https://stomp.github.io/stomp-specification-1.2.html#STOMP_Frames) after the message body in the STOMP frame.

**Comment by vinothkrstatiq** [comment]
hey everyone ,
<img width="1045" alt="ocpp" src="https://user-images.githubusercontent.com/96102600/169040166-16060271-6768-4a3e-84c1-ba9d29d45d62.png">

I am using one of the ocpp  sub protocols it not connecting can anyone help me with this 
ocpp1.6
ocpp2.0
ocpp2.0.1

**Comment by vinothkrstatiq** [comment]
hi people it is working now 
u can also refer my screenshot
<img width="1056" alt="ocpp working" src="https://user-images.githubusercontent.com/96102600/169040936-ae088e9f-3223-4902-b9b9-5b46d907e5d5.png">

**Comment by Bowske** [comment]
getting 
`
Error: Invalid WebSocket frame: RSV1 must be clear
`
after setting  graphql-transport-ws value of Sec-WebSocket-Protocol. Is there any way to bypass it?

**Comment by Zgore14** [comment]
I'm actually facing the issue but on GraphQL query with Subcription. When I modify the header nothing is modified in the request : 
![image](https://user-images.githubusercontent.com/21169263/228913054-07155622-91ab-416c-8873-21b8b457277b.png)

I'm on Postman v10.12.9 Desktop for Windows (on Windows 11)
