### ISSUE TITLE
OAuth2 / PKCE / Azure AD failure - Azure expects Origin header for Single Page App registration

### ISSUE THREAD

**Issue by josh-k-cb** [a85/POSTMan-Chrome-Extension#9998]
Azure AD has the concept of a [SPA (Single Page App) registration](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration). This is the registration type which supports PKCE on the AAD 2.0 endpoint.

As a security measure, [AAD expects the `Origin` header to be present when asking for a token](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2482). 
```
Error: AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin
```

Postman doesn't include this header, so the authorize step works but the token step fails. 

I tried adding the header programmatically using a Pre-Request script, but these scripts are not executed during the Access Token retrieval step.

I grabbed the token request from the console and manually constructed a new request in Postman with the same values. It failed as before and succeeded when adding an `Origin` header to the request.

Fix here is either
- Support pre-request scripts for built-in authorization flows
- Add `Origin` header to the OAuth2/PKCE behind-the-scenes token request
- Add headers collection to Advanced Options area of PKCE auth setup

**Environment Information**

 - Platform Type: Windows
 - Postman Version: 8.5.0
 - Operating System: Windows

**Comment by mancave** [comment]
Looks like the same feature request #10008

**Comment by jkewley** [comment]
As Microsoft pushes developers toward the use of PKCE, this fix is a blocker for those of us who want to test secured APIs. Please prioritize this fix. 

Better yet, since the automated token auth flows seem to be consistently problematic, come up with a way for us to manipulate the token request before sending so we can fix it on our own as we wait for these ignored issues to be resolved.

**Comment by IlliaMamonov** [comment]
+1

**Comment by super-ppx** [comment]
+1

**Comment by abhijeetborole** [comment]
Hey everyone! Thank you for the patience! We’ve added the ability to customise your OAuth2,0 requests with Postman v10.13.
This is available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests. You can also add query params to the auth request.

You can add the `Origin` header here in the `Advanced` section to the Token Request.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)

If you have any Audience and Resource parameters, you can move them to the new editors with the Move Audience and Resource button.

![MoveAudAndResFlow](https://user-images.githubusercontent.com/9638586/232850201-59d30590-d7c7-41c1-94c7-9a1c77f1757b.gif)


Do let us know if you have any issues.

P.S. - For refresh parameters, these will be stored with the token and any changes will only be considered when you generate a new token

Postman app v10.13 is being rolled out will be available for everyone in couple of days
